### ISSUE TITLE
[videoroomtest.cfg] codec isn't change

### ISSUE THREAD

**Issue by 4i-helpynet** [meetecho/janus-gateway#1000]
I cannot change the codec in videoroom.

My videoroomtest.cfg is:

[1234]
description = Demo Room
secret = adminpwd
publishers = 6
bitrate = 128000
fir_freq = 1
;audiocodec = opus
videocodec = vp9
record = false
;rec_dir = /path/to/recordings-folder

And I receive:
{janus: "event", session_id: 67248937191837, sender: 8004835962635332, transaction: "ZmFwSH5LUfST",…}
janus:"event"
jsep:{type: "answer",…}
plugindata:{plugin: "janus.plugin.videoroom",…}
data:{videoroom: "event", room: 1234, configured: "ok", audio_codec: "opus", video_codec: "vp8"}
audio_codec:"opus"
configured:"ok"
room:1234
video_codec:"vp8"
videoroom:"event"
plugin:"janus.plugin.videoroom"
sender:8004835962635332
session_id:67248937191837
transaction:"ZmFwSH5LUfST"

**Comment by lminiero** [comment]
As explained in the guidelines, please DO NOT paste stuff inline. Use pastebin/gist/whatever instead.

Make sure you're restarting Janus after a codec change in the configuration file, as the config is only read at startup.

**Comment by lminiero** [comment]
Ok, I think I found out the cause of the issue. If I set the room to VP9, the codec is set correctly (I see it in the SDP) but the info we're sending in the event is wrong (the "vp8" you see). From a media perspective, VP9 is used correctly, though, so no issue there. I'll work on a fix shortly.

**Comment by lminiero** [comment]
Solved, it was a stupid typo... it should work now. Thanks for bringing this to my attention!

**Comment by 4i-helpynet** [comment]
I thank you for your patient help!

**Comment by 4i-helpynet** [comment]
@saroar write down your problem to tifgit@4i.hu
