### ISSUE TITLE
how to use rtpforwarder to redirect rtp to ffmpeg/gstreamer pipeline and send it back.

### ISSUE THREAD

**Issue by mars00772** [meetecho/janus-gateway#1003]
hi,I am trying to implement a mcu plugin to mix rtp stream, after reading audiobridge.c, by using RTP forwarder instance,  redirect the plain RTP feeds that get to the plugin to a ffmpeg/gstreamer pipeline, getting the mix back and send this to the participants, job is done.  I still got some questions here, some tips were appreciated.
1. forward to ffmpeg server to mix the steam, but how to send it back, and send to every participants?
2. need to remove his own stream, both video and audio, then things become complicated, what should be done there? sum all the steam ,and remove the specific one for each participants?

**Comment by lminiero** [comment]
Closing as not a code issue.

As explained in the guidelines, please post on our [Google group](https://groups.google.com/forum/#!forum/meetecho-janus) for questions like this instead.
