### ISSUE TITLE
Join muted

### ISSUE THREAD

**Issue by arcifius** [meetecho/janus-gateway#1008]
Sending:
message: { request: `join`, room: 1234, display: `Augusto`, muted: true }

Don't join in muted state... When participant list arrives it comes with <muted: false>. Did I missed something or this is a bug?

**Comment by arcifius** [comment]
After some tests I saw that muted actually is true but nothing happens

**Comment by arcifius** [comment]
Solved by adding:
mixer.send({ message: { request: `configure`, muted: true } });

on _createOffer_ success callback that is inside joined event, still wondering why just joining with <muted: true> didn't work...

**Comment by lminiero** [comment]
Currently abroad so can't check if there's a bug. Please remind me on Monday, when I'll be back.

**Comment by lminiero** [comment]
Just checked in our AudioBridge demo by:

1. setting `muted: true` when doing `request: "register"` [here](https://github.com/meetecho/janus-gateway/blob/master/html/audiobridgetest.js#L344)
2. removing the `muted: false` in the `request: "configure"` [here](https://github.com/meetecho/janus-gateway/blob/master/html/audiobridgetest.js#L146)

and it works as expected: users join muted, and notification tell the right thing too. My guess is that there's something broken in your application.

Closing as not an issue. If you can replicate the issue somehow, let us know and we'll reopen.

**Comment by arcifius** [comment]
Just to clarify, then i cant make a ``request: "join"`` with ``"muted: true/false"`` ?
Something like I posted:
```javascript
{ request: join, room: 1234, display: Augusto, muted: true }
```

**Comment by lminiero** [comment]
You can: it's what I did, and it worked. You probably were sending another configure somewhere that was replacing the muted you sent in the join.
