### ISSUE TITLE
Safari 11 - Not display video (H.264 Baseline)

### ISSUE THREAD

**Issue by uasan** [meetecho/janus-gateway#1013]
Hello.

Janus send video stream (plugin.streaming), Safari receiving this stream, but not display in video player.

But if proxy without converting in `ffmpeg`, then in Safari the video display perfectly:
`ffmpeg -i rtsp://ip-camera/h264 -codec copy rtp://127.0.0.1:5050`

What is the problem, why doesn't it work without `ffmpeg`?

Thanks.

**Comment by lminiero** [comment]
Closing as not a code issue. Please post questions like this on our Google group instead.
