### ISSUE TITLE
janus crash

### ISSUE THREAD

**Issue by liulongqiang1984** [meetecho/janus-gateway#1014]
when i used more than 40 sip client call sip phone at same time, total call count  more than 2000+ janus will crash;
because gdb file is too big more than 2G, if need it i will upload a website can download,
[gdb.txt](https://github.com/meetecho/janus-gateway/files/1341628/gdb.txt)

**Comment by lminiero** [comment]
As explained in the guidelines, please DON'T paste logs inline: use gist/pastebin/whatever instead.

**Comment by liulongqiang1984** [comment]
sorry i have changed problem description,if you need crash core file, please tell me, i will give you download address, thanks

**Comment by lminiero** [comment]
This is not a complete trace, there's no line on what's crashing or where.

**Comment by liulongqiang1984** [comment]
what more detail information you need, please tell me, i will provide it? because core file is too big

**Comment by liulongqiang1984** [comment]
i add bt full information
[core.txt](https://github.com/meetecho/janus-gateway/files/1366371/core.txt)

**Comment by lminiero** [comment]
This still isn't a full backtrace... Please try using AddressSanitizer instead: https://janus.conf.meetecho.com/docs/debug

**Comment by atoppi** [comment]
@liulongqiang1984 can you run a test with [iceloop-sessions-mgmt](https://github.com/meetecho/janus-gateway/tree/iceloop-sessions-mgmt) branch?

**Comment by liulongqiang1984** [comment]
i upload crash core file path http://www.51feiyun.com/libs/core/core.7844, you can download it, because i can not analysis gbd so need you analysis it , thanks!

**Comment by atoppi** [comment]
@liulongqiang1984 we can not analyze a core dump without the involved binaries.

**Comment by liulongqiang1984** [comment]
but  my janus app is exited very frequently, if no crash why janus process exit self

**Comment by liulongqiang1984** [comment]
@atoppi  i have used iceloop-sessions-mgmt branch app still will crash,

**Comment by atoppi** [comment]
Ok, thank you for testing.
Have you tried with AddressSanitizer, like @lminiero suggested?

**Comment by liulongqiang1984** [comment]
https://share.weiyun.com/62c7cf133d9e8e8ad6acc691d7099eef
i test new version still crash, i have upload core and log file, please download it , thankyou

**Comment by lminiero** [comment]
@liulongqiang1984 posting cores and logs over and over will not help. As @atoppi and I said, please check with libasan instead: https://janus.conf.meetecho.com/docs/debug

**Comment by liulongqiang1984** [comment]
i need test detail so i closed it for the moment
