### ISSUE TITLE
TextRoom Safari 11 datachannel randomly not opened

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#1015]
Hi!

I testing textroom plugin on macbook and safari 11. (janus v0.2.5)
Janus randomly not open the data channel, and onDataChannelStateChange don't called.
I use HTTPS for janus rest. Chrome, Firefox still work fine.

I don't find any relevant info in debug log or console. I use level7.
How can i find what is wrong?

Edit: Same error in offical demo page!

Thanks

Found log when using safari:
`[Wed Oct  4 19:34:09 2017] [WARN] [6069961294805855] Still waiting for the DTLS stack for component 1 in stream 1...
[Wed Oct  4 19:34:10 2017] [WARN] [6069961294805855] Still waiting for the DTLS stack for component 1 in stream 1...
[Wed Oct  4 19:34:11 2017] [WARN] [6069961294805855] Still waiting for the DTLS stack for component 1 in stream 1...
[Wed Oct  4 19:34:13 2017] [WARN] [6069961294805855] Still waiting for the DTLS stack for component 1 in stream 1...`

**Comment by izemize** [comment]
https://gist.github.com/izemize/cb671f1954d4cd8f7d7d58b86f0a581c

**Comment by izemize** [comment]
fixed:

https://groups.google.com/d/topic/meetecho-janus/drunykSJEPU/discussion

**Comment by lminiero** [comment]
:+1:
