### ISSUE TITLE
Remote picture coming from mobile is rotated 90 degrees in Firefox

### ISSUE THREAD

**Issue by artmatsak** [meetecho/janus-gateway#1021]
Tested with Firefox 56.0 and the M59 branch of WebRTC built into our native iOS app. In a peer-to-peer call, the image from the iOS app is shown with a proper orientation in Firefox. However, if the same call is terminated via Janus, the image from the app is shown with a 90-degree rotation. Same problem with M59 in our Android app.

The problem is not reproducible with Chrome, or with the M54 branch of WebRTC on iOS or Android (which is what we've been using earlier).

Also found a mention of the same issue here:

https://groups.google.com/d/msg/meetecho-janus/Jx0CHJyWcvU/A6Elga-6AgAJ

**Comment by lminiero** [comment]
We don't touch the media, so I don't think this is not a fault in Janus. In most plugins we already forward extensions like the video orientation one, that should address that on the client side. What plugin are you talking about here?

**Comment by artmatsak** [comment]
That's strange. We're using the VideoRoom plugin.

**Comment by lminiero** [comment]
Try setting `videoorient_ext=no` in your room's configuration, either statically in the config file or programmatically if you're creating via API. This will prevent the publisher from sending orientation info in RTP extensions.

**Comment by artmatsak** [comment]
Setting `videoorient_ext=no` worked, thank you!
