### ISSUE TITLE
netowrk disconnection

### ISSUE THREAD

**Issue by tanton81** [meetecho/janus-gateway#1023]
Hello, 

I face the following problem:
I have 2 clients connected to Janus video room over my local network. I am able to disconnect just the media stream of one of my clients in a such a way, to simulate a network lost, the signaling remains active - session and handles are still available on Janus.
When I do the network drop for the media stream, Janus sends this message:

 {
     "janus": "media",
     "session_id": 8877740218715531,
     "sender": 6353931387940296,
     "type": "audio",
     "receiving": false
 }

and just after that (1 sec may be later) I get this event:

 {
     "janus": "media",
     "session_id": 8877740218715531,
     "sender": 6353931387940296,
     "type": "audio",
     "receiving": true
 }

but my client is still disconnected... The session and the handles present in these messages belongs to the disconnected client.

I think this is a bug because once the media stream is disconnected and it is not normal to have a 'receiving':'true'.

Best regards, 
Anton

**Comment by lminiero** [comment]
Are you sure the user is disconnected from a media perspective as well (browser closed the PeerConnection) and not just from a signalling perspective? The only place where we send a `receiving: true` is in the code that handles incoming RTP packets.

**Comment by tanton81** [comment]
Hi, 
yes, in my case I have a separate program that controls the signaling and and helps the end client program to establish the media stream. The end client program and the helping program are running on separate machines. So to simulate the network lost, I just turnoff the network adapter on the machine where the end client program is running.
I will try to make a log file of Janus and a pcap.

**Comment by tanton81** [comment]
Hello again, 

it seems that I was not in the best conditions for testing. I had 2 clients on same PC... One of the clients was running on my Windows but the other one was running in a linux vurtial machine. And at the same time I had the Janus running on the same VM. So probably event disconnecting the network of my second client, as it was next to the Janus, it was capable of finding the route to the server.
Now a made my tests with separate PCs  and Janus detects that it does not receive anymore an audio.

Anton

**Comment by lminiero** [comment]
Does this mean we can close the issue?

**Comment by tanton81** [comment]
yes :)
