### ISSUE TITLE
Videoroom does not notify "joining" to participants

### ISSUE THREAD

**Issue by tugtugtug** [meetecho/janus-gateway#1030]
When a participant joins the room, no event is sent to the other participants, i.e. someone can join the room without others knowing and start listening to the conference, this is inconsistent with the other room plugins, and is also inconsistent with the leaving event.

1. publisher joins the room, no notification to participants
2. publisher leaves the room, "leaving" sent to participants

Much like the other plugins, the videoroom plugin should also offer a "joining" event to match the "leaving" event.

**Comment by lminiero** [comment]
Not a bug. The plugin only advertizes active feeds (publishers sending media), not participants in general. Closing.

**Comment by tugtugtug** [comment]
but the leaving event is published anyway even if the publisher doesn't publish
