### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by uasan** [meetecho/janus-gateway#1034]
Starting proccess janus- Segmentation fault.

ASAN:DEADLYSIGNAL
https://gist.github.com/uasan/20675c193fa3bfefd69f7ecb78bd4959

**Comment by lminiero** [comment]
You'll need to be much more detailed than that... as info on your distro, libraries version, OpenSSL version you're using, Janus commit, etc.etc.etc.

**Comment by uasan** [comment]
OS - ClearLinux (very fast :)
OpenSSL 1.0.2 and 1.1 (this problem)

The problem in different versions of the OpenSSL.
In `/usp` set OpenSSL **1.0.2** in `/opt` OpenSSL **1.1**
When compiling Janus, it is not possible to specify where to look for the OpenSSL.

I think need to add a configuration option for the Janus compilation
`./configure --with-openssl-dir=/opt`

**Comment by lminiero** [comment]
Is this still an issue or did you find a way around it?

**Comment by uasan** [comment]
Yes, this is problem if you need to specify OpenSSL dir to compile Janus.

**Comment by lminiero** [comment]
Have you tried simply setting `CFLAGS` and `LDFLAGS` the way [configure.ac already does](https://github.com/meetecho/janus-gateway/blob/master/configure.ac#L20) on Mac OS?

**Comment by uasan** [comment]
Ok, I'll try, but I already have one version of OpenSSL, the segmentation error may already not be reproduced.

**Comment by uasan** [comment]
Yes, like error solved, if specify CFLAGS and LDFLAGS, I close, if this error appears i reopen.

Thanks.
