### ISSUE TITLE
only securred connections allowed

### ISSUE THREAD

**Issue by ShettyRakshith** [meetecho/janus-gateway#1038]
Hey,

when i tried with port(8088) to host janus on chrome it's throwing 
> _"only secure origins are allowed"_
and port 8089 throwing " _Page not found_" 
i found that chrome is  allows only https connection. 
i tried to change configuration in janus.transport.http.cfg file but it did't work . then i tried with python script to bind https it's throwing "_
> "the requested address is not valid in this context"
any solution to come out from this?
Thanks in advance

**Comment by lminiero** [comment]
Closing as not a code issue. As explained on the guidelines, please post questions like these on our Google group.
