### ISSUE TITLE
Janus gateway state always disconnected on iOS

### ISSUE THREAD

**Issue by najielchemaly** [meetecho/janus-gateway#1039]
Dear Support,

I am using janus-gateway-ios project and trying to connect to our test server.
From Android side it is connecting and the video is published to the room, but from iOS side I can only see the sessionId, handleId and the streams from the Admin but the components looks as the following:
"components": [
                {
                    "id": 1,
                    "state": "disconnected",
                    "local-candidates": [
                        "1 1 udp 2013266431 188.166.38.50 53354 typ host",
                        "2 1 udp 2013266431 10.18.0.5 37893 typ host"
                    ],
                    "dtls": {},
                    "in_stats": {},
                    "out_stats": {}
                }
            ]

Could you please advise.

Thank you in advance.

**Comment by lminiero** [comment]
Closing as not a code issue. As explained on the guidelines, please post questions like these on our Google group.
