### ISSUE TITLE
Safari11 Still waiting for the DTLS stack for component 1 in stream 1

### ISSUE THREAD

**Issue by yarekc** [meetecho/janus-gateway#1041]
Version 0.2.6, plugin videoroom.cf with codec H264

Works fine on firefox and chrome.

On safari11, when requesting remote stream, Janus outputs infinite: (and does not open the stream)
`Still waiting for the DTLS stack for component 1 in stream 1`

Safari11 NEEDS the webcam access: if access is granted, everything works fine.
(Works normally on chrome and firefox without webcam access)

**Comment by lminiero** [comment]
Please don't post the same question over and over in different places. You already wrote on the group, where the question belongs as it's not a code issue. Closing as per the guidelines.
