### ISSUE TITLE
Error with latest master 6d98a5e029ddc394eb0edf8b1a396718e2d1b88c

### ISSUE THREAD

**Issue by anildigital** [meetecho/janus-gateway#1042]
I had just reproduced following error with Janus version with the commit. It doesn't happen with the earlier build (a few months back one) I have.

https://github.com/meetecho/janus-gateway/commit/6d98a5e029ddc394eb0edf8b1a396718e2d1b88c

```
[2508130578606045] Creating ICE agent (ICE Full mode, controlled)
[WARN] [2508130578606045] ICE failed for component 1 in stream 1, but let's give it some time... (trickle received, answer received, alert not set)
[ERR] [ice.c:janus_ice_check_failed:1554] [2508130578606045] ICE failed for component 1 in stream 1...
No WebRTC media anymore
```

**Comment by lminiero** [comment]
Sorry but this doesn't help. You'll need to be much more detailed than that if you think this is a bug, as "ICE failed" is too generic. At the very least, please provide Admin API dumps for the affected handle(s). Besides, if you can 100% confirm it works on an earlier build but not on master, then you should use `git bisect` to find the exact commit that first causes the problem.

**Comment by anildigital** [comment]
@lminiero sorry my fault, I had recompiled Janus with the latest source. I forgot to set nat stun server settings
```
[nat]
stun_server = stun.l.google.com
stun_port = 19302
```
I think most of the users would deploy Janus in backend servers, so this thing should go in README.

**Comment by indatawetrust** [comment]
@anildigital thanks this worked for me
