### ISSUE TITLE
Demo: Video Call not work when calling from Chrome to Firefox

### ISSUE THREAD

**Issue by ealebed** [meetecho/janus-gateway#1043]
I try demo here - https://janus.conf.meetecho.com/videocalltest.html

OS: Ubuntu 16.04.3 LTS
Google Chrome Version 62.0.3202.62 (Official Build) (64-bit)
Firefox 56.0 (64-bit)
Opera 48.0.2685.52

I'm trying test call from Chrome or from Opera to Firefox I get this error (in Firefox):
`WebRTC error... {"name":"InternalError","message":"Starting video failed"}`

When I try to call from Firefox or from Opera to Chrome I get (in Chrome):
`WebRTC error... {"name":"NotReadableError","message":""}`

When I try to call from Firefox or from Chrome to Opera I get (in Opera):
`WebRTC error... {"name":"NotReadableError","message":""}`

When I try to call from Firefox to Firefox I get (I think it's normal):
`WebRTC error... {"name":"NotReadableError","message":"Concurrent mic process limit."}`

When I try test call Chrome -> Chrome or Opera -> Opera all works fine...

What I am doing wrong?

**Comment by lminiero** [comment]
As explained in the guidelines, this is a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), not github. Closing.
