### ISSUE TITLE
Janus not receiving clients video

### ISSUE THREAD

**Issue by giordanocardillo** [meetecho/janus-gateway#1051]
I have a Janus instance running in a Docker container (docker-compose file [here](https://pastebin.com/mQ4TF1KN)) since June without any issue. 

I use Janus for videoconferences purpose, and suddently it stops receiving client video, causing the conference members to not see each others.

I've seen that the recordings I'm getting are all files from 0 byte to 8 byte. It's like that Janus drops incoming video/audio streams.

I've deleted and then put up another docker container but the results are still the same. 

Deploying the same container with the same config on another server solved he problem.

This issue happened once in September and I had to change server. But In October I changed the client links to use the old server (just to try it) and It was working fine. Now this issue appeared again on the same server, reverting to the new server solved again.

Someone got any idea about what is happening? 

Log file [here](https://pastebin.com/w2df1EQY)

**Comment by lminiero** [comment]
You should check with Wireshark or tcpdump to make sure media is indeed getting to Janus. My feeling is it's more likely a networking issue, where firewalls of some sorts are preventing media going through. Checking other demos will probably also help.

**Comment by giordanocardillo** [comment]
I'll make a try. The strange thing is that while one day it is working perfectly, the day after is not working, without modifying the network.

**Comment by lminiero** [comment]
Just checked the log, and it's quite clearly a connectivity issue: there's no log line that suggests WebRTC ever completed, so ICE and/or DTLS failures somewhere. As such, a matter for the group and not a code issue, and something you might want to investigate with the usual Admin API. Closing.

**Comment by giordanocardillo** [comment]
Thanks
