### ISSUE TITLE
Building Janus on Amazon Linux 

### ISSUE THREAD

**Issue by atyachin** [meetecho/janus-gateway#1052]
Hi,

I'm having hard time solving dependencies on Amazon Linux AMI.
First finding is you need to add:
`yum install glib2-devel gnutls-devel`

Second, there's no libnice and libnice-devel packages in the Amazon repo. Trying to download CentOS RPMs and install locally opens a dependency hell...
Also, trying to build nice locally from sources doesn't help since the Janus install script is looking for a package ("nice").

Any suggestions here?

**Comment by lminiero** [comment]
Closing as not a code issue. Please post questions like this on our [community group](https://groups.google.com/forum/#!forum/meetecho-janus).
