### ISSUE TITLE
Janus crashes when starts at centos7.3

### ISSUE THREAD

**Issue by richard1219** [meetecho/janus-gateway#1058]
I get the follow log and stack on both v0.25 and 0.26, the follow ones is v0.25:
log:
[Fri Nov 10 12:04:35 2017] VideoRoom watchdog started
[Fri Nov 10 12:04:35 2017] JANUS VideoRoom plugin initialized!
[Fri Nov 10 12:04:35 2017] Loading plugin 'libjanus_voicemail.so'...
[Fri Nov 10 12:04:35 2017] JANUS VoiceMail plugin initialized!
[Fri Nov 10 12:04:35 2017] Transport plugins folder: /usr/local/lib/janus/transports
[Fri Nov 10 12:04:35 2017] VoiceMail watchdog started
[Fri Nov 10 12:04:35 2017] Loading transport plugin 'libjanus_http.so'...
Segmentation fault (core dumped)

stack:

[https://gist.github.com/richard1219/be0bd4b48013e48037f61550839665a5](https://gist.github.com/richard1219/be0bd4b48013e48037f61550839665a5)

**Comment by lminiero** [comment]
As clearly explained in the guidelines, please do NOT paste huge logs inline. Use pastebin, gist or whatever instead.

**Comment by lminiero** [comment]
Looks like it's dying deep within dlopen when loading the HTTP transport. Have you tried removing that shared object and see if it works with the other transports instead? A clean install may also help understand if it was a one-time compile issue.

**Comment by richard1219** [comment]
Thank you for you replay @lminiero ! 
Finally, I found that the "libjanus_http" moduel conflicts with the "libjanus_sipre" module, when I disabled the libjanus_http in transports section OR disable libjanus_sipre in plgins section, janus started up smoothly, but when I enable both of them, I got a libjanus_http dlopen crash.

**Comment by lminiero** [comment]
Weird, did you find out where the conflict was?

**Comment by richard1219** [comment]
Not yet, but I think it's somthing like 'open twice' issue likes [https://github.com/dlfcn-win32/dlfcn-win32/issues/32](https://github.com/dlfcn-win32/dlfcn-win32/issues/32), but I haven't looked into about this.

**Comment by lminiero** [comment]
Ack. Closing then as this looks very specific to your setup, feel free to reopen should you find more info that indicate a fix we should apply.
