### ISSUE TITLE
sdp error content on chrome android 62

### ISSUE THREAD

**Issue by frankville** [meetecho/janus-gateway#1059]
Hi, I've been using janus for a couple of weeks and it's been working fine until today that I tested on a couple of android devices with chrome 62 and got an ERROR_CONTENT when parsing the remote offer sdp (chrome desktop works fine). I've tested my app on browserstack with older chrome versions and firefox and it works. Also it works on firefox on my android phone.

pastebin with remote offer sdp and chrome console error message: https://pastebin.com/VBUEd6pK
pastebin with my current config in the streaming.cfg file: https://pastebin.com/w7Uhwc0V
thanks

**Comment by lminiero** [comment]
Looks good to me... may be an issue with those devices and H.264. You way want to ask on [https://groups.google.com/forum/#!forum/discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) instead. Closing as not a code issue, please post questions like this on our [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
