### ISSUE TITLE
Documentation error: Admin interface over MQTT

### ISSUE THREAD

**Issue by oej** [meetecho/janus-gateway#1069]
The documentation for the admin API is focused on HTTP and for the handle_info the session ID is in the HTTP URL. 

For MQTT there's no URL and we subscribe to a single topic, not a wildcard (so I can't push the session ID in the topic). I have tried several names for the session ID in the JSON structure, but can't find anything that works. The source seems to hint at "id" but I can't seem to get it to work. This is the json I'm trying with:

`{"janus":"handle_info","admin_secret":"janusoverlord","id":3299787687795846,"transaction":"laksdfj1::handle_info"}
`

**Comment by oej** [comment]
Disclaimer: I can be stupid, but I have tried really hard to read docs and code :-)

**Comment by oej** [comment]
It was "session_id"

**Comment by lminiero** [comment]
You're absolutely right, the Admin API documentation is still pretty much
the one we started with at the time (http only) and while we updated the
docs on the Janus API to reflect other transports, we failed to do the same
there, sorry about that... Adding to the to-do list for when I get back.

Il 13 nov 2017 9:56 PM, "Olle E. Johansson" <notifications@github.com> ha
scritto:
