### ISSUE TITLE
When I configure and start janus, it appears bash: installdir: no such a file or directory.

### ISSUE THREAD

**Issue by pyy1994** [meetecho/janus-gateway#1070]
Hello, I am fresh studying for this. Maybe, my question is a little childish, but I really want to know how to solve it. Thank you for give your precious opinions.

**Comment by pyy1994** [comment]
root@debian:/home/pyy/janus-gateway# <installdir>/bin/janus --help
bash: installdir: 没有那个文件或目录`

**Comment by lminiero** [comment]
Github is for code issues only. Please post questions like this on our [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
