### ISSUE TITLE
Simulcast breaks on FF if the ordering of the media attributes change

### ISSUE THREAD

**Issue by tugtugtug** [meetecho/janus-gateway#1072]
The sdp parsing to enabling FF simulcast relies on the ordering of the rid being before the ssrcs. This is not always true, especially if one uses a parser (such as sdp-transform) to pre-process the sdp before sending to the gateway.

e.g.
working case:

a=rid:high send
a=rid:medium send
a=rid:low send
a=simulcast: send rid=high;medium;low
a=ssrc:886186561 cname:{082564b1-a28e-4eeb-ad17-a6c8182c4733}
a=ssrc:1461403014 cname:{082564b1-a28e-4eeb-ad17-a6c8182c4733}
a=ssrc:2198807420 cname:{082564b1-a28e-4eeb-ad17-a6c8182c4733}

failing case:
a=ssrc:886186561 cname:{082564b1-a28e-4eeb-ad17-a6c8182c4733}
a=ssrc:1461403014 cname:{082564b1-a28e-4eeb-ad17-a6c8182c4733}
a=ssrc:2198807420 cname:{082564b1-a28e-4eeb-ad17-a6c8182c4733}
a=rid:high send
a=rid:medium send
a=rid:low send
a=simulcast: send rid=high;medium;low

**Comment by lminiero** [comment]
Good catch... I'm abroad for at least one more week, so I won't be able to look into this until I get back. Please ping me after the 26th in case I forget.

**Comment by tugtugtug** [comment]
@lminiero will do.

**Comment by lminiero** [comment]
This patch should fix that broken behaviour, please let me know if that's not the case.

**Comment by tugtugtug** [comment]
@lminiero looks promising, thx!
