### ISSUE TITLE
Problems of running samples 

### ISSUE THREAD

**Issue by sriyanfernando** [meetecho/janus-gateway#1076]
I installed  janus on a virtual pc(Ubuntu 16.04). 
i tried using separate web server , but when i try to run echotest.html..then it will see some error like that.

Error : "Probably a network error,Is the gateway down"  then i identified  echotest.js file has  variable called server should change.. But what ip address should include in to server variable?

**Comment by lminiero** [comment]
Closing as this looks like a configuration issue, and we only use github for code problems and bugs. Please use our [group](https://groups.google.com/forum/#!forum/meetecho-janus) for questions like these.
