### ISSUE TITLE
Minimum version for jansson should be specified

### ISSUE THREAD

**Issue by cescp** [meetecho/janus-gateway#1077]
I'm trying to compile Janus in a computer with Linux Mageia 5 (not the latest one), where the most recent official package of jansson is version 2.4.
In Janus >=v0.2.5 you introduced the forward declaration of janus_t in plugin.h:
[User forward declaration of json_t in plugin.h](https://github.com/meetecho/janus-gateway/commit/131a872a00facd639805c973943ad9762c4819d8)
but in order to make it work, the jansson version must be >=2.5:
[Make it possible to forward declare struct json_t](https://github.com/akheron/jansson/commit/02beb90db3734263c424fe208cdfae0a8405d640)

Therefore, in configure.ac for Janus >=v0.2.5, a minimal requirement for jansson library should be introduced:
```
jansson_version=2.5
[...]
PKG_CHECK_MODULES([JANUS],
                  [
                    glib-2.0 >= $glib_version
                    nice
                    jansson >= $jansson_version
                    libssl >= $ssl_version
                    libcrypto
                  ])
```
For my particular case, the solution is upgrading to Mageia 6 or compiling a recent version of jansson.

**Comment by ivanovaleksey** [comment]
By the way, our forward declaration is just
```
typedef struct json_t json_t;
```
Shouldn't it be 
```
struct json_t;
typedef struct json_t json_t;
```
like in the [commit example](https://github.com/akheron/jansson/commit/02beb90db3734263c424fe208cdfae0a8405d640)?

**Comment by lminiero** [comment]
Apologies for the very delayed feedback, I was abroad for a while and couldn't always work. Good catch on the version check for Jansson, I'll update the configure.ac script to take that into account.
