### ISSUE TITLE
Segmentation fault in icesend thread

### ISSUE THREAD

**Issue by eihalseth** [meetecho/janus-gateway#1080]
I'm using Janus with the SIP plugin, and this crash initially happened in a production environment. I'm now able to recreate this pretty consistently within 10-15 minutes of running a test setup tailored to cause this crash.

This is running Janus master (commit 96b866904d76d4331cdc87befd909bc6410c09cd), with libsrtp 2.0.0.

I can force the crash by placing an outbound call, answering and then immediately hanging up, over and over on multiple clients until the segfault occurs.

Logs leading up to the crash and gdb backtrace:
https://pastebin.com/a8y2LS0K

Tell me if you need any additional information.

**Comment by eihalseth** [comment]
I've been doing some testing on my own, trying to uncover how this segfault occurs. This is in no way my area of experties, but I want to help as much as possible to solve this issue.

According to the gdb backtrace the segfault occurs on this line:
res = srtp_protect_rtcp(component->dtls->srtp_out, sbuf, &protected);

I tried adding a NULL check on "component", "component->dtls" and "component->dtls->srtp_out", printing to the log if this happens, and this actually happens while running my test setup (seems like "component->dtls" is NULL). The segfault still occurs, but now it is always deeper within srtp_protect_rtcp.

My theory is that "component->dtls" is modified by some other thread concurrently, which causes the crash.

**Comment by atoppi** [comment]
Thanks for reporting @eihalseth.
Given the scenario you are discussing, most likely the hangup is triggering a race condition where a call to `janus_ice_webrtc_free` destroys a DTLS context, while the `janus_ice_send_thread` is still using it.

**Comment by lminiero** [comment]
Is this one of the things #1035 fixes?

**Comment by atoppi** [comment]
Yes, #1035 should at least mitigate the issue.

**Comment by eihalseth** [comment]
I've now tested this in Janus master (commit 66af3d85de5d9b2218c9999e244a529833a278d4), and I'm happy to report that I can no longer reproduce this crash.

Thank you!
