### ISSUE TITLE
Is there a guide to install Janus on macOS?

### ISSUE THREAD

**Issue by rabashani** [meetecho/janus-gateway#1081]
is there a guide to install on MacOS? Or even better a Docker ready to use?

**Comment by ivanovaleksey** [comment]
Hello @rabashani,
you can try [this](https://github.com/ivanovaleksey/janus-docker) docker image.

**Comment by rabashani** [comment]
what is the different between this and the other version  - https://github.com/efacilitation/docker-janus-webrtc-gateway

**Comment by lminiero** [comment]
Closing as not a code issue. Please post questions like this on our [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
