### ISSUE TITLE
Ops! got an error encoding the Opus frame: -1 (invalid argument)

### ISSUE THREAD

**Issue by konstantin-mohin** [meetecho/janus-gateway#1086]
`[plugins/janus_audiobridge.c:janus_audiobridge_participant_thread:3842] [Opus] Ops! got an error encoding the Opus frame: -1 (invalid argument)

==30577== ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x07c492ba28ee
    #0 0x7f8663426009 (/usr/lib64/libasan.so.0.0.0+0x16009)
    #1 0x7f8658869611 (/opt/janus/lib/janus/plugins/libjanus_audiobridge.so.0.0.0+0x14611)
Thread T28 (iceloop 7600224) created by T13 (pool) here:
    #0 0x7f866341ac3a (/usr/lib64/libasan.so.0.0.0+0xac3a)
    #1 0x7f86627645c1 (/usr/lib64/libglib-2.0.so.0.4600.2+0x8c5c1)
Thread T13 (pool) created by T12 here:
No WebRTC media anymore
    #0 0x7f866341ac3a (/usr/lib64/libasan.so.0.0.0+0xac3a)
    #1 0x7f86627645c1 (/usr/lib64/libglib-2.0.so.0.4600.2+0x8c5c1)
Thread T12 created by T10 here:
    #0 0x7f866341ac3a (/usr/lib64/libasan.so.0.0.0+0xac3a)
    #1 0x7f86548be13f (/usr/lib64/libmicrohttpd.so.10.22.0+0x813f)
Thread T10 created by T0 here:
    #0 0x7f866341ac3a (/usr/lib64/libasan.so.0.0.0+0xac3a)
    #1 0x7f86548be13f (/usr/lib64/libmicrohttpd.so.10.22.0+0x813f)
==30577== ABORTING`

**Comment by lminiero** [comment]
As clearly explained in the guidelines, please DON'T paste logs inline here: gdb traces like yours create fake links to unrelated issues, and mess everything up.
