### ISSUE TITLE
Videroom plugin incorrect behaviour for pause/resume of the video stream

### ISSUE THREAD

**Issue by danpascu** [meetecho/janus-gateway#1087]
If I stop the video stream on a listener session using a configure request with video=false and then later I resume it with another configure request with video=true, it takes up to 30 seconds for the video to resume (it the meanwhile it just shows a black screen).

This happens because janus doesn't send FIR/PLI when the configure request with video=true restores video and it takes that much until the browser sends a key frame to reset the video stream.

When using the pause request, it works as expected, because in that case FIR/PLI is sent, but in my case I need to keep receiving audio and only pause the video stream, while the pause request pauses both.

**Comment by lminiero** [comment]
Thanks for spotting this, fixed!

**Comment by danpascu** [comment]
On 27 Nov 2017, at 13:57, Lorenzo Miniero wrote:

> Thanks for spotting this, fixed!

Great. Thank you.
