### ISSUE TITLE
Build error with  ./configure --enable-post-processing 

### ISSUE THREAD

**Issue by atyenoria** [meetecho/janus-gateway#1094]
I encountered the build error with --enable-post-processing 
The log is like this.
https://gist.github.com/atyenoria/0f1e9a7de7b1e8fb99a0370e06ed4efe

Janus version is the latest master today (cdd9e535072f510906805b8287929b669e02565f). 

This is related to my docker repo https://github.com/atyenoria/janus-webrtc-gateway-docker/issues/8

As @danotrilogic says, the modification works. I tried the clone repo 
https://github.com/danotrilogic/janus-gateway

**Comment by lminiero** [comment]
The modification he suggests is not a valid fix as it is, as while it would work for you, it would break the tool for users with a different version of FFmpeg. What we need are conditional usages of the defines you found, like all the `LIBAVCODEC_VER_AT_LEAST` we already have in place. If you can find out which versions changed the defines for which it fails for you, we can add them to the code.

**Comment by alexamirante** [comment]
https://github.com/FFmpeg/FFmpeg/blob/master/doc/APIchanges#L573

I'll push a commit shortly.

**Comment by atyenoria** [comment]
Thank you very much!

**Comment by atyenoria** [comment]
it works perfectly!
