### ISSUE TITLE
missing rtsp_user and rtsp_pwd when creating permanent mountpoint via API

### ISSUE THREAD

**Issue by frankville** [meetecho/janus-gateway#1096]
Hi, I've just started using the API on nodejs with minijanus.js and I noticed that when I wanted to create a new permanent streaming mountpoint sending (among other fields) rtsp_user and rtsp_pwd these fields didn't appear in the streaming.cfg file. So I looked into the source code and found this section:

`} else if(!strcasecmp(type_text, "rtsp")) {
				janus_config_add_item(config, mp->name, "url", json_string_value(json_object_get(root, "url")));
				janus_config_add_item(config, mp->name, "audio", mp->codecs.audio_pt ? "yes" : "no");
				janus_config_add_item(config, mp->name, "video", mp->codecs.video_pt ? "yes" : "no");
			}`
 (lines 1973-1977 from the plugin/janus_streaming.c)

I'm not a C developer but I modified that section to look like this:

`} else if(!strcasecmp(type_text, "rtsp")) {
                                janus_config_add_item(config, mp->name, "url", json_string_value(json_object_get(root, "url")));
                                janus_config_add_item(config, mp->name, "audio", mp->codecs.audio_pt ? "yes" : "no");
                                janus_config_add_item(config, mp->name, "video", mp->codecs.video_pt ? "yes" : "no");
                                janus_config_add_item(config, mp->name, "rtsp_user", json_string_value(json_object_get(root, "rtsp_user")));
                                janus_config_add_item(config, mp->name, "rtsp_pwd", json_string_value(json_object_get(root, "rtsp_pwd")));
                        }
`

then I re-compiled the project and the problem was solved. 
I don't know if this issue was addressed by someone else but the first code snippet was extracted from the master branch and I didn't find anything on pull requests. If it's necessary I can make a PR (would be my very first :smile: )  

By the way this project is awesome. Congratulations!

**Comment by lminiero** [comment]
Good catch, thanks, we solved something similar in a couple of other plugins just a few days ago. Anyway, your patch is not enough as RTSP may not be available: it needs to check for `HAVE_LIBCURL` before accessing properties that may not exist in the struct. I'll fix this later on.

**Comment by lminiero** [comment]
This commit should fix it.

**Comment by frankville** [comment]
Great, that was fast! I downloaded and recompiled everything from the current master branch and now if I create an rtsp streaming mountpoint with audio:true it is saved with audio:no and these other fields that I didn't specified: 
audiortpmap =
audiofmtp =
video = yes
videortpmap = H264/90000
videofmtp = packetization-mode=1\;profile-level-id=42001E\;sprop-parameter-sets=Z0IAHukBQHtcSAA27oAM3+YA2IEJQA==,aM4xUg==

those empty fields are causing this error message:
[ERR] [config.c:janus_config_parse:160] Error parsing item at line 16: no value (janus.plugin.streaming.cfg)

I believe this is not intended. Those parameters in videofmtp I think are a good addition though we'll have to change the profile-level-id before parsing the sdp on the browser.
