### ISSUE TITLE
SIP Plugin: Inform about held/retrieve operation (from SIP)

### ISSUE THREAD

**Issue by mtbramo** [meetecho/janus-gateway#1098]
It should be interesting to inform webRTC user of remote held/retrieve operation by sending an event associate to SDP direction state.
In janus_sip_sdp_process(...), on RE-INVITE SDP analysis; JANUS_SDP_SENDONLY or INACTIVE --> <media>_held
SENDRECV -> <media>_active

Regards.

**Comment by lminiero** [comment]
Questions like this belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), not here: we only use Github for cose issues. Anyway, I'm working on a branch that will attempt to provide renegotiation support, so you'll find it there I suppose.
