### ISSUE TITLE
IPv6 Waiting for candidates-done callback

### ISSUE THREAD

**Issue by royreuversgit** [meetecho/janus-gateway#1100]
Yesterday me and my collegue's app got rejected by Apple because it dit not function with a IPv6 network. Because of that we enabled IPv6 support on the Janus mediaserver. When we tested this a couple of times it always resulted in the below standing errors. It seems to be a mediaserver issue because if we delete the client side `IPv6: true` code the error still occurs. However if we do not enable the IPv6 option in the mediaserver everything (without IPv6 support) functions correctly. One of the 5 tests resulted in a working connection/conference but it took around 5 minutes to setup this meeting. 

`[Thu Dec  7 10:58:27 2017] [591864623857163] Waiting for candidates-done callback...`
`[Thu Dec  7 10:58:27 2017] [591864623857163] Waiting for candidates-done callback... `
`[Thu Dec  7 10:58:27 2017] [591864623857163] Waiting for candidates-done callback...`

We checked for relating articles and found 2 from 2014. This two issues seem to occur because of an endless loop that occurs because of ice negotiation not finishing.  Maybe it's the same case here.

We hope anybody know's how to fix this error.

**Comment by lminiero** [comment]
IPv6 definitely works, we use it all the time. Try disabling the interfaces you won't need in `janus.cfg`, and check if you're using STUN or nat-1-1 too.

**Comment by royreuversgit** [comment]
Thanks for the quick response. We checked the janus.cfg and we are not using stun and nat-1-1. All the interface lines where disabled which means janus determines which one to use if I am correct. We tried to check this in the documentation but could not find anything. That's why we tried to enable and test one interface at a time. Unfortunately the same errors/warnings kept occuring. Should we try to change a different setting?

**Comment by lminiero** [comment]
Is the server IPv6 compliant? If Janus can't get any IPv6 address, it will indeed loop forever, I guess.

**Comment by lminiero** [comment]
Any update?

**Comment by royreuversgit** [comment]
We changed the DNS records so it should be able to support IPv6. The test however did not go so well today. It showed the same response and we were unable to get a conversation going. We will try again in a couple of weeks and let you know if/when we made any progress.

**Comment by lminiero** [comment]
Any update?

**Comment by lminiero** [comment]
Closing as we didn't get any update. Please let us know if it's still an issue.
