### ISSUE TITLE
100% cpu usage after leaving VideoRoom

### ISSUE THREAD

**Issue by BHamrick1** [meetecho/janus-gateway#1105]
I am using a dynamically made room and then removing a all the participants that are publishing without actually sending a remove. I am letting them timeout and then eventually JANUS will stop sending any messages back and in the console it logs:

 [WSS-0x7fb4bc002200] 50 ((null))

over and over again. Like that is all it logs. The JANUS process just takes up 100%. I have to restart it to solve this issue.

**Comment by BHamrick1** [comment]
I had to bump up the logs to be at 7 to see this message.

**Comment by BHamrick1** [comment]
Maybe this is related:

[8756508719138451] Notifying that we are NOT receiving video
[Fri Dec  8 10:50:55 2017] [8756508719138451] Sending event to transport...
[Fri Dec  8 10:51:15 2017] [WSS-0x7f1b80000a20] WS connection down, closing
[Fri Dec  8 10:51:15 2017] A janus.transport.websockets transport instance has gone away (0x7f1b80000c60)
[Fri Dec  8 10:51:15 2017] [WSS-0x7f1b80000a20] Destroying WebSocket client
[Fri Dec  8 10:51:15 2017] [WSS-0x7f1b80000a20]   -- closed

**Comment by BHamrick1** [comment]
Another thing that I am doing that might be problematic is that I am opening multiple web socket connections from the same program to show up as different clients.

**Comment by BHamrick1** [comment]
So I figured out the problem. It seems to be an issue with the websocket library I was using. I was using master from https://github.com/warmcat/libwebsockets.git. I switch to v2.4-stable and it now works.

**Comment by BHamrick1** [comment]
This seems to still be an issue. We require the master version of libwebsockets because we are trying to run janus on a mac. This might be the issue we are seeing https://github.com/warmcat/libwebsockets/issues/1124 but I am not 100% certain. So this might be an issue with libwebsockets or an issue with the new libwebsocket not being compatible with janus.

**Comment by lminiero** [comment]
Ack, please keep us updated in case it was an issue with the library, so that we can change the recommended version if needed.

**Comment by lminiero** [comment]
Any update?

**Comment by lminiero** [comment]
Assuming the issue was indeed with the library, then: closing.
