### ISSUE TITLE
rtp_forward question

### ISSUE THREAD

**Issue by GNUConsultores** [meetecho/janus-gateway#1107]
Hi all,

i'm newbie in this awesome Janus, and have one question that i hope someone can answer.

If i use the rtp_forward call, in videoroom plugin, all the stream is forwarded to the new IP or there is a "fork" and then two stream exist?, one in videoroom and another in the new IP?

That's what i'm looking for, one publisher emit stream in the videoroom plugin, and the same stream forwarded to another IP at same time. Is that possible? ... or the publisher have to make two connection, one at each plugin?

Thank you all.

**Comment by ivanovaleksey** [comment]
Hi, I am a beginner too but I guess I could help.
[Here](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2217) is where the `rtp_forward` event handled. In the gist it [creates a new socket](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2298) for further forwarding.

The actual forwarding is made when you have a data to forward, e.g. in `incoming_rtp` callback.
You can see it [here](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2959-L2988). Note `sendto` calls that do the job.

Meanwhile existing listeners [receive that data too](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L3029).

**Comment by lminiero** [comment]
As clearly explained in the guidelines, we only use Github for issues, not questions. That's what the [group](https://groups.google.com/forum/#!forum/meetecho-janus) is for. Closing.

**Comment by GNUConsultores** [comment]
Hi,

thank you very much @ivanovaleksey for your detail explication. And sorry @lminiero for ask my dude in the wrong place. Thank you all.
