### ISSUE TITLE
videoroom api documentation

### ISSUE THREAD

**Issue by raju2592** [meetecho/janus-gateway#1108]
I am new to Janus. I am trying to use the videoroom plugin. Currently I am reading videroom demo and screensharing demo codes to have an idea of how to use it, but where can I find the exact formats of the messages and meaning of the fields etc.?

**Comment by ivanovaleksey** [comment]
I am not sure about existing documentation (it might be somewhere).
If you are able to read C code you can take a look at the plugin itself.

**Comment by lminiero** [comment]
As clearly explained in the guidelines, we only use Github for issues, not questions. That's what the [group](https://groups.google.com/forum/#!forum/meetecho-janus) is for. Closing.
