### ISSUE TITLE
H264 IDR-frame in streaming pluggin

### ISSUE THREAD

**Issue by asmyasnikov** [meetecho/janus-gateway#1112]
Hi all!
I need your help, seniors!
I have problem with streaming h264 video to clients - IDR frame of h264 stream only one (!!!) restreamed to attached clients from external source (like ffmpeg or gstreamer). I am use hardware encoder (openmax library layer on raspberryPi3 Broadcom chip), which publish IDR first time at started and nothing send during at work. It doing for economy traffic, but every new client of Janus not understand what resolution of video stream and other SDP-options. Currently I restarting ffmpeg graber for resending IDR-frame to Janus-clients, but this not correctly.
For example, rtcp-server written on perl (https://github.com/revmischa/rtsp-server) saving IDR-frame parameters and send to new clients correct SDP-options.
Please, fix it, seniors!

**Comment by lminiero** [comment]
If this is something you usually set in `fmtp` SDP attributes, then do it there when creating the mountpoint: the streaming plugin allows you to overwrite whatever the source sends via configuration.

**Comment by asmyasnikov** [comment]
Ok, I will trying it and report about them in this issue

**Comment by asmyasnikov** [comment]
It worked! =)
Tnx!
