### ISSUE TITLE
[ERR] [ice.c:janus_ice_cb_component_state_changed:643:] ICE failed for handle 1716821054...

### ISSUE THREAD

**Issue by dmerlitti** [meetecho/janus-gateway#112]
I have installed Janus (configured without websockets, data-channel and rabbitmq, ) on a Ubuntu x64 14.04 LTS VM running on Azure (http://iudev.cloudapp.net/janus/).
I have created only a new endpoint for the 8088 TCP port.
The following is the Janus output from the startup time till the moment I got the error in the echo test demo app (http://iudev.cloudapp.net/janus/echotest.html):

<pre>
---------------------------------------------------
Starting Meetecho Janus (WebRTC Gateway) v0.0.6
---------------------------------------------------

Reading configuration from /opt/janus/etc/janus/janus.cfg
Checking command line arguments...
Debug/log level is 4
Adding 'vmnet' to the ICE ignore list...
Using 10.0.0.4 as local IP...
Initializing ICE stuff (IPv6 candidates disabled)
Fingerprint of our certificate: C5:5F:DA:7D:84:47:B1:BF:6B:55:16:62:48:31:3E:D3:F1:7B:25:89:92:4A:4B:4D:4D:D9:D5:AF:EA:D8:15:44
Plugins folder: /opt/janus/lib/janus/plugins
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
[ERR] [config.c:janus_config_parse:72:]   -- Error reading configuration file... error 2 (No such file or directory)
JANUS VideoRoom plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
[ERR] [config.c:janus_config_parse:72:]   -- Error reading configuration file... error 2 (No such file or directory)
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_recordplay.so'...
JANUS Record&Play plugin initialized!
Loading plugin 'libjanus_sip.so'...
[ERR] [config.c:janus_config_parse:72:]   -- Error reading configuration file... error 2 (No such file or directory)
JANUS SIP plugin initialized!
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin initialized!
Loading plugin 'libjanus_audiobridge.so'...
[ERR] [config.c:janus_config_parse:72:]   -- Error reading configuration file... error 2 (No such file or directory)
JANUS AudioBridge plugin initialized!
Loading plugin 'libjanus_streaming.so'...
Echotest watchdog started
Record&Play watchdog started
VideoRoom watchdog started
SIP watchdog started
VideoCall watchdog started
VoiceMail watchdog started
JANUS Streaming plugin initialized!
HTTP webserver started (port 8088, /janus path listener)...
[WARN] HTTPS webserver disabled
[WARN] WebSockets support not compiled
[WARN] RabbitMQ support not compiled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
AudioBridge watchdog started
Streaming watchdog started
Sessions watchdog started
Creating new session: 1666044823
Creating new handle in session 1666044823: 2820090189
[2820090189] There's a message for JANUS EchoTest plugin
[2820090189] There's a message for JANUS EchoTest plugin
[2820090189] Creating ICE agent (controlled mode)
[2820090189] ICE send thread started...
[2820090189] Done! Ready to setup remote candidates and send connectivity checks...
ICE started and trickling, sending connectivity checks for candidates retrieved so far...
No more remote candidates for handle 2820090189!
Creating new session: 1942371579
Creating new handle in session 1942371579: 954972076
[954972076] There's a message for JANUS EchoTest plugin
[954972076] There's a message for JANUS EchoTest plugin
[954972076] Creating ICE agent (controlled mode)
[954972076] ICE send thread started...
[954972076] Done! Ready to setup remote candidates and send connectivity checks...
ICE started and trickling, sending connectivity checks for candidates retrieved so far...
[WARN] [954972076]    Unsupported transport tcp!
[WARN] [954972076]    Unsupported transport tcp!
No more remote candidates for handle 954972076!
Detaching handle from JANUS EchoTest plugin
Handle detached (0), scheduling destruction
[2820090189] ICE send thread leaving...
Destroying session 1666044823
[2820090189] WebRTC resources freed
[2820090189] Handle and related resources freed
Detaching handle from JANUS EchoTest plugin
Handle detached (0), scheduling destruction
[954972076] ICE send thread leaving...
Destroying session 1942371579
[954972076] WebRTC resources freed
[954972076] Handle and related resources freed
Creating new session: 1239651098
Creating new handle in session 1239651098: 1716821054
[1716821054] There's a message for JANUS EchoTest plugin
[1716821054] There's a message for JANUS EchoTest plugin
[1716821054] Creating ICE agent (controlled mode)
[1716821054] ICE send thread started...
[1716821054] Done! Ready to setup remote candidates and send connectivity checks...
ICE started and trickling, sending connectivity checks for candidates retrieved so far...
[WARN] [1716821054]    Unsupported transport tcp!
[WARN] [1716821054]    Unsupported transport tcp!
No more remote candidates for handle 1716821054!
[ERR] [ice.c:janus_ice_cb_component_state_changed:643:] ICE failed for handle 1716821054...
No WebRTC media anymore
[1716821054] ICE send thread leaving...
</pre>

**Comment by ldenoue** [comment]
I also get *sometimes* some server errors when using the janus_recordplay.c plugin.
On the client side, I get a "oncleanup" message and the recordings are empty on disk.

[ERR] [ice.c:janus_ice_cb_component_state_changed:1018:] [2199408902] ICE failed for component 1 in stream 1...

Any idea if enabling TURN in Janus (you've added this recently I think) could help?

Laurent

**Comment by lminiero** [comment]
An ICE failed error means no connectivity ould be established for media between Janus and the client, so TURN can indeed help increasing the chances of getting a working connection, yes.

**Comment by ldenoue** [comment]
any idea why it would work one minute and not the next?
It seems strange that all of a sudden TURN would be required.

**Comment by lminiero** [comment]
There are several different reasons why ICE may fail. You should check what's happening with Wireshark, with the aid from the info provided by the admin API.

**Comment by ldenoue** [comment]
looks fine today. I've updated to the latest Janus, enabled TURN and added my TURN server information in janus.cfg file.
Thanks for your help.
