### ISSUE TITLE
Streaming demo works on Firefox and Edge but fails on Chrome

### ISSUE THREAD

**Issue by haueck** [meetecho/janus-gateway#1123]
Hi,

I use Firefox 57.0.3 (64-bit), Edge 41.16299.15.0 and Chrome 63.0.3239.108 (Official Build) (64-bit).

Firefox and Edge play the video stream without any problems. Chrome, on the other hand, shows only the spinner and the current bitrate. Bitrate is changing, so the stream is reaching the browser, but it is not displayed. It looks like 'playing' event is never triggered after `Janus.attachMediaStream($('#remotevideo').get(0), stream);`.

Screenshot: [https://imagebin.ca/v/3mwAf0I7p08K](https://imagebin.ca/v/3mwAf0I7p08K)

Janus log:

``Creating new session: 6436023162179935
Creating new handle in session 6436023162179935: 6396742899427177
[6396742899427177] Creating ICE agent (ICE Full mode, controlling)
[WARN] [6396742899427177] Still waiting for the DTLS stack for component 1 in stream 1...
[WARN] [6396742899427177] ICE failed for component 1 in stream 1, but let's give it some time... (trickle pending, answer received, alert not set)
[6396742899427177] The DTLS handshake has been completed
WebRTC media is now available``

This `ICE failed for component 1 in stream 1...` warning I also get for other browsers.

Best regards,
Rafał

**Comment by lminiero** [comment]
Which codec? Please provide the local and remote SDPs (as gist/pastebin, not inline).

**Comment by haueck** [comment]
H.264. I use test-launch tool from gst-rtsp-server to generate the stream: `./test-launch -p 8500 "videotestsrc ! x264enc  ! rtph264pay name=pay0 pt=96"` (I am writing this from memory). I will provide SDPs tomorrow. 

Janus runs on Ubuntu 16.04 and browsers on Windows 10.

**Comment by chadfurman** [comment]
@haueck I've recently had trouble with a separate feature in Janus due to my browser.  Restarting my browser (exit, re-launch) usually helps; however, this might not be the same problem you're experiencing.  

Also, I've found some extensions can interfere.  For example, the "Privacy Badger" chrome extension breaks things for me (there might be other extensions that break things also, so might be worth checking there)

In rare occasions, I have to restart my network connection and/or my computer for things to behave correctly.  Always a good thing to try if on the off-chance you haven't already.  

I'm not as helpful as Lorenzo, certainly, but maybe I'm helpful at least a little bit :)

**Comment by KensakuKOMATSU** [comment]
With using Chrome, I think more attributes will be needed for ``x264enc``.

Could you try with below?

```
gst-launch-1.0 videotestsrc ! \
  video/x-raw,width=640,height=480,framerate=30/1 ! \
  x264enc aud=false key-int-max=1 tune=zerolatency intra-refresh=true ! \
  "video/x-h264,profile=constrained-baseline,level=(string)3.1" ! \
  rtph264pay pt=96 ! \
  capssetter caps='application/x-rtp,profile-level-id=(string)42e01f' ! \
  udpsink host=127.0.0.1 port=5004
```

**Comment by arjenveenhuizen** [comment]
Note that the above GStreamer command line creates an intra-only stream which is not ideal. Forcing `profile=constrained-baseline` and `aud=false`, however, is good practice. Also, for completeness sake, I always suggest to set `is-live=true` on videotestsrc:

> gst-launch-1.0 videotestsrc is-live=true ! \
>   video/x-raw,width=640,height=480,framerate=30/1 ! \
>   x264enc aud=false option-string="keyint=30:min-keyint=30:bframes=0:no-scenecut" key-int-max=30 tune=zerolatency intra-refresh=true byte-stream=true speed-preset=2 bitrate=400 ! \
>   "video/x-h264,profile=constrained-baseline,level=(string)3.1" ! \
>   rtph264pay pt=96 ! \
>   capssetter caps='application/x-rtp,profile-level-id=(string)42c01f' ! \
>   udpsink host=127.0.0.1 port=5004

Furthermore, `profile-level-id` for constrained-baseline is `42c01f` and not `42e01f` as can also be seen when running the command above with `gst-launch -v`:

> /GstPipeline:pipeline0/GstRtpH264Pay:rtph264pay0.GstPad:src: caps = application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, packetization-mode=(string)1, profile-level-id=(string)**42c01f**, sprop-parameter-sets=(string)"Z0LAH6aAoD2wFqDAILSgAAADACAAAAeR4wZU\,aM48gA\=\=", payload=(int)96, ssrc=(uint)4131033584, timestamp-offset=(uint)1624487046, seqnum-offset=(uint)28091, a-framerate=(string)30

**Comment by haueck** [comment]
It works! Option `aud=false` is required for Chrome. So this is a minimal command to generate a H.264 RTSP test stream using gst-rtsp-server: `./test-launch -p 8512 "videotestsrc ! x264enc aud=false ! rtph264pay name=pay0"`

And corresponding Janus configuration:

```
[rtsp-test]
type = rtsp
id = 99
description = RTSP Test
audio = no
video = yes
url=rtsp://localhost:8512/test
```

Thank you for your help!
Rafał
