### ISSUE TITLE
Might have a problem with WS api

### ISSUE THREAD

**Issue by idi-ot** [meetecho/janus-gateway#1124]
After sending `{\"janus\":\"create\",\"transaction\":\"qw5DX/TImxNaWBe02xpZ\"}` to janus it logs the following
```
...
[Wed Jan  3 20:49:46 2018] [WSS-0x7fdf9d812c00] Got 55 bytes:
[Wed Jan  3 20:49:46 2018] [WSS-0x7fdf9d812c00] First fragment: 55 bytes, 0 remaining
[Wed Jan  3 20:49:46 2018] {"janus":"create","transaction":"qw5DX/TImxNaWBe02xpZ"}
[Wed Jan  3 20:49:46 2018] [WSS-0x7fdf9d812c00] Done, parsing message: 55 bytes
[Wed Jan  3 20:49:46 2018] Got a Janus API request from janus.transport.websockets (0x7fdf9d50fef0)
[Wed Jan  3 20:49:46 2018] Transport task pool, serving request
[Wed Jan  3 20:49:46 2018] Creating new session: 4485517464138841
[Wed Jan  3 20:49:46 2018] Sending Janus API response to janus.transport.websockets (0x7fdf9d50fef0)
...
```
but never sends the created session id back.

However, if I send several similar requests (about 100), it does. And logs the following lines in addition for each of them
```
...
[Wed Jan  3 20:53:11 2018] [WSS-0x7fdf9d812c00] Sending WebSocket message (115 bytes)...
[Wed Jan  3 20:53:11 2018] [WSS-0x7fdf9d812c00]   -- Sent 115/115 bytes
...
```

 I'm on mac and installed `libwebsockets` from `brew`.
```sh
> brew info libwebsockets
libwebsockets: stable 2.4.1 (bottled), HEAD
C websockets server library
https://libwebsockets.org
/usr/local/Cellar/libwebsockets/2.4.1_1 (21 files, 751.2KB) *
  Poured from bottle on 2018-01-02 at 13:51:18
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libwebsockets.rb
==> Dependencies
Build: cmake ✔
Required: libev ✔, libuv ✔, libevent ✔, openssl ✔
```

Janus commit: 345641443fa073b4274cf6eabe5b190077629cce

**Comment by idi-ot** [comment]
I think I should try running janus in a docker container to make sure it's not just a mac issue.

**Comment by lminiero** [comment]
Well known issue with libwebsockets on mac, you need master of that library as they only fixed it recently there. Closing.

**Comment by MinorUncle** [comment]
This problem is solved? Why do I have the same problem with all three Macos,
Is it wrong with me?

My libwebsocket version is v2.4.1_1,
srtp version is v2.1.0,
Libnice is v0.1.14,
Openssl is v1.0.2o,

**Comment by idi-ot** [comment]
@MinorUncle 

> libwebsocket version is v2.4.1_1

I think this version is still affected.

**Comment by MinorUncle** [comment]
Hi @idi-ot 
I switched to v2.4.2,
`libwebsockets: stable 2.4.2 (bottled), HEAD`
But the result was the same error, I'm debugging it with Xcode, so I still can't put it in docker.

**Comment by idi-ot** [comment]
> I'm debugging it with Xcode, so I still can't put it in docker.

Are you running janus as part of your XCode project?

**Comment by MinorUncle** [comment]
Yes, but there's a error with this WS

**Comment by idi-ot** [comment]
Yes to which question?

**Comment by MinorUncle** [comment]
Sorry, English is not my native language, so I answer slowly and even make some mistakes.

**Comment by MinorUncle** [comment]
But when I ran it through Xcode, it appeared the same error as you.

**Comment by MinorUncle** [comment]
NO,only janus-gateway server

**Comment by idi-ot** [comment]
Then the easiest way would be to compile the dependencies from source, I think.

**Comment by MinorUncle** [comment]
I tried building the libwebsockets v2.4.2 from source with XCode,and  the result was the same problem.

**Comment by MinorUncle** [comment]
I try to compile Janus on Xcode, just for debugging easily.

**Comment by MinorUncle** [comment]
I just debugged and found that janus_websockets_common_callback was not invoked, resulting in lws_write not being invoked. I will continue tracing the source code tomorrow.

**Comment by xcolwell** [comment]
I'm seeing this same behavior with the latest master of libwebsockets and janus. Did you find a resolution?

**Comment by xinxi053** [comment]
libwebsockets: stable 3.1.0 (bottled)  still no websocket response.

**Comment by xinxi053** [comment]
Finally, when i downgrade to 3.0.0 stable, and compile manually,  it works! https://github.com/warmcat/libwebsockets/blob/v3.0-stable/READMEs/README.build.md
