### ISSUE TITLE
Crash in janus_websockets_callback_http - Segmentation fault

### ISSUE THREAD

**Issue by nir100** [meetecho/janus-gateway#1127]
Hi,

We encountered with 2 crashes that came from janus_websockets_callback_http.

gdb trace here: https://pastebin.com/eUTLP4RM

Janus commit: 7fef0fba7e155a38fdd318ba16f402c180977695

Thanks for the hard work.

**Comment by lminiero** [comment]
The gdb trace doesn't tell anything useful unfortunately. You may want to try with libasan instead: https://janus.conf.meetecho.com/docs/debug

**Comment by nir100** [comment]
OK 
Is it safe to add it on production servers? Does it slow the Janus abnormally?

**Comment by lminiero** [comment]
It should be ok, it does slow Janus down a bit I guess (it's still tracking memory) but definitely not in a noticeable way like valgrind for instance.

**Comment by lminiero** [comment]
Closing as we didn't get any update. Please let us know if it's still an issue.
