### ISSUE TITLE
unnecessary [FATAL] Couldn't access event handler plugins folder...

### ISSUE THREAD

**Issue by fbertone** [meetecho/janus-gateway#1128]
Hi,

I have configured Janus with the flag --disable-all-handlers.
As consequence, the events_folder (/opt/janus/lib/janus/events) was not created during make install.

When I start Janus, I get this error: [FATAL] [janus.c:main:3678]     Couldn't access event handler plugins folder...

The problem is that in [janus.c](https://github.com/meetecho/janus-gateway/blob/master/janus.c#L3669), the events folder is accessed BEFORE checking if events are disabled [L3686](https://github.com/meetecho/janus-gateway/blob/master/janus.c#L3686).

I think that a cleaner flow would be to check the folder AFTER checking if the events are enabled, so that we don't get a FATAL log if it's not needed.

**Comment by lminiero** [comment]
Sorry, missed this... ack, will fix this when I have some time.

**Comment by lminiero** [comment]
Should be fixed now.

**Comment by kylebakerio** [comment]
just finished a fresh install of janus on debian 10, attempt to start by running ./janus in the folder itself, got this error. Not sure what to do, this is the most recent google hit.
