### ISSUE TITLE
 Multiple streams not supported from janus side

### ISSUE THREAD

**Issue by sriyanfernando** [meetecho/janus-gateway#1129]
> If you want to open an issue, please make sure that:
> 
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available[here](http://janus.conf.meetecho.com/docs/debug.html)).
> 
> If so, just remove this text and share your findings!

  When  I try to connect single peer connection to multiple streams it does not working for me.

**Comment by lminiero** [comment]
Not supported yet, as explained in the documentation.
