### ISSUE TITLE
onbeforeunload handler causes a reload of the current page when clicking on href link

### ISSUE THREAD

**Issue by ashimokawa** [meetecho/janus-gateway#1132]
I encountered this with my own test project but it is easily reproducible with the demos

Steps to reproduce:

1) go here: https://janus.conf.meetecho.com/echotest.html
2) press start, accept camera access, wait until you see the remote stream
3) press the blue "meetecho" link on the bottom

You will see the page reload instead of navigating to the meetecho homepage. Clicking again works since janus has already stopped and is not initialized.

**Comment by lminiero** [comment]
I did notice this behaviour, but didn't associate it to `onbeforeunload`. We don't have any piece of code that should prevent a change in page, what makes you think that's the cause?

**Comment by ashimokawa** [comment]
@lminiero 
Two reasons:

1) this happens in ALL browsers, so it is not a browser bug
2) it does not happen if I patch janus.js and do not assign the onbeforeunload handler

**Comment by ashimokawa** [comment]
@lminiero 
I took a look at the problem again and it seems that the onunload handler destroys the janus session which causes the detroyed handler to be called, and these handlers do window.location.reload() in the demos

https://github.com/meetecho/janus-gateway/blob/1e06290078268279ca69d5aaf0a76831973b3457/html/echotest.js#L384

**Comment by lminiero** [comment]
Good catch, that's probably it. I'll remove those next week, to just show a toastr notification or something.

**Comment by lminiero** [comment]
Fixed it in a different way: `destroy()` in `janus.js` now has a new property called `notifyDestroyed` (that detaults to `true`) that decides whether we should invoke the `destroyed` callback. In the `onunload` handler we set it to `false` instead, as we don't really need it to be invoked.
