### ISSUE TITLE
Plugin WebSockets.so missing

### ISSUE THREAD

**Issue by sraupach** [meetecho/janus-gateway#1135]
Hi,

i am running in the following issue when starting Janus with WebSockets enabled.

`Loading transport plugin 'libjanus_websockets.so'...
[ERR] [janus.c:main:4012] 	Couldn't load transport plugin 'libjanus_websockets.so': libwebsockets.so.12: cannot open shared object file: No such file or directory`

Also the Plugins directory of the pre-compiled janus-gateway does not have a websocket plugin included. 

Does someone got an idea, how i can achieve the wss-janus feature for a Mattermost WebRTC?

Thanks in advance

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), we only use Github for code issues. Closing.
