### ISSUE TITLE
Time delay after receiving destroy mountpoint response and actually freeing the port.

### ISSUE THREAD

**Issue by code-player** [meetecho/janus-gateway#1139]
When I make a POST request to Janus endpoint for deleting an existing mountpoint , even after I get the response for the request, there is a time-delay before janus actually free that port the mountpoint was aasociated with, and prevents me from create any new mountpoint on the same port unless the port is actually freed by Janus.

P.S. I'm dynamically creating ports and destroying them as needed, starting from a given offset. And whenever a port is freed, it is appended to the sorted list of available ports and new mountpoint is always tried to be created on one of the available ports. 

Is there a way I can remove or reduce this overhead?

**Comment by lminiero** [comment]
Not an issue, but simply the way we free resources right now (lazy frees). If you want faster frees, check the refcount branch: #403. Closing.
