### ISSUE TITLE
WebRTC stream not appearing in Firefox

### ISSUE THREAD

**Issue by code-player** [meetecho/janus-gateway#1140]
I have setup janus locally, and used the demo tests for viewing a gstreamer stream of my webcam into browser. It works well in Chrome but throws an error in Firefox `ICE failed, add a TURN server and see about:webrtc for more details`.
Following contains my `about:webrtc` logs from firefox
https://stackoverflow.com/questions/48165631/webrtc-error-in-firefox-ice-failed-add-a-turn-server-and-see-aboutwebrtc-for

I am using is `Mozilla firefox-57.0.4`

P.S.: Even after adding the turn server, the same error keeps occuring. So, I guess it's not associated with TURN/STUN servers.

Please suggest a solution.

**Comment by lminiero** [comment]
We only use github for code issues, and this seems related to connectivity or usage problems instead, which is what we use the [community group](https://groups.google.com/forum/#!forum/meetecho-janus) for. Please post your question there. Closing.

**Comment by code-player** [comment]
Please add me to the group. I have requested.
