### ISSUE TITLE
it seems that recording is not working in echotest plugin 

### ISSUE THREAD

**Issue by tgabi333** [meetecho/janus-gateway#1145]

**Comment by lminiero** [comment]
I often use the EchoTest with recording, in my own tests, and it always works fine. What doesn't in your case? What's the request you use to try recording?

**Comment by tgabi333** [comment]
It says that acodec and vcodec is null here: https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_echotest.c#L1090

**Comment by lminiero** [comment]
You can only start recording *after* the call started, or when you pass the JSEP to send your offer, as otherwise the plugin doesn't know which codecs you'll use:
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_echotest.c#L1249

Closing as not an issue.

**Comment by tgabi333** [comment]
thanks Lorenzo.
