### ISSUE TITLE
Changes and Roadmap

### ISSUE THREAD

**Issue by dwoz** [meetecho/janus-gateway#1147]
Great work on Janus WebRTC Gateway!  Providing a change log would helpful to developers and packagers. In addition, a roadmap would be super cool. I've looked around for these things but can't find them, if they exist please point me in the right direction. Otherwise, are either possible?

**Comment by lminiero** [comment]
Please discuss questions like these on our [group](https://groups.google.com/forum/#!forum/meetecho-janus), we only use Github for code issue. Closing.
