### ISSUE TITLE
Video Room Record Folder Creation

### ISSUE THREAD

**Issue by dimidiam** [meetecho/janus-gateway#1150]
In record.c file, is there a reason you guys using 
`if(janus_mkdir(rec_dir, 0755) < 0) {` 
and not 
`if(janus_mkdir(rec_dir, 0775) < 0) {`.

I am facing some issues having two users with the need to read/write the same file.

Thx on advance

**Comment by lminiero** [comment]
Simple permission configuration, where only the user can write to the file and not the group. I don't think it's related to your issue. Closing as we only discuss Janus issues here.
