### ISSUE TITLE
WebRTC error in subscriber after renegotiation

### ISSUE THREAD

**Issue by marcino1** [meetecho/janus-gateway#1151]
I'm testing renegotiations with public videoroom demo, and after calling from console on publisher (as described in #1099): 
```
sfutest.createOffer(
{
	media: { removeVideo: true },
	success: function(jsep) {
		Janus.debug(jsep);
		sfutest.send({message: {request: "configure"}, "jsep": jsep});
	},
	error: function(error) {
		bootbox.alert("WebRTC error... " + JSON.stringify(error));
	}
});
```
  
I get following WebRTC error on subscriber: 
> Failed to set remote offer sdp: The order of m-lines in subsequent offer doesn't match order from previous offer/answer.

**Comment by lminiero** [comment]
Mh, I may not have tested the `remove` stuff much. I guess that, when you do a `remoteVideo`, this turns the m-line to inactive for the publisher (as the browser won't just remove the m-line, it's against the standard). As such, when we try and forward that new SDP to the subscriber, we might still be using the code that removes inactive m-lines for new offers, and as such you end up with an SDP update that contains one less m-line than the original did.

If so, what we should do is keeping the m-line there when it's a renegotiation, and only remove it when it's the first offer instead. I guess there may be issues when an audio-only subscription becomes an audio + video-inactive offer, which might happen if a subscriber was subscribing to a publisher with an unsupported codec (think Safari trying to subscribe to a Opus+VP8 publisher), and then the publisher disables video. In that case, we would add the inactive video line there, and not sure what happens in the client side in that case.

**Comment by lminiero** [comment]
Yeah, as I suspected that's what's happening. As a side note, I guess you're not on master, as the renegotiation crashed for me due to a recent change: I just pushed a commit that fixes that specific problem. I'll look into the WebRTC error.

**Comment by lminiero** [comment]
This last commit fixes that renegotiation scenario for me. That said, apparently re-adding video again causes SRTCP decryption errors for subscribers:

```
[ERR] [ice.c:janus_ice_cb_nice_recv:2227] [3179317747046424]     SRTCP unprotect error: srtp_err_status_replay_fail (len=46-->46)
[ERR] [ice.c:janus_ice_cb_nice_recv:2227] [3179317747046424]     SRTCP unprotect error: srtp_err_status_replay_fail (len=46-->46)
[ERR] [ice.c:janus_ice_cb_nice_recv:2227] [3179317747046424]     SRTCP unprotect error: srtp_err_status_replay_fail (len=46-->46)
```

which may be related to the video SSRC change but I'm not sure, as I haven't investigated in depth yet. The same doesn't happen when you start from an audio only PeerConnection and only add video later, for instance; besides, doing an ICE restart on the viewer fixes it. I'll have a look later to see if I can sort that out.

In the meanwhile, could you confirm the latest master fixes it for you?

**Comment by marcino1** [comment]
Yes, the latest master fixes error with removing video. But as you written, there is a problem with adding video again.

**Comment by lminiero** [comment]
This commit fixes that problem for me. The issue was that we were re-using the same SSRC as before when re-adding the media stream, which resulted in the browser sending RTCP packets with the same indexes as the previous ones, and thus an SRTP decrypt error. It wasn't happening when going from audio only to audio-video the first time, as in that case the video SSRC was 0 to begin with. Now we reset SSRCs when a media stream is removed: https://github.com/meetecho/janus-gateway/commit/1b05b626b7a0ccf23df1de6e230c8bb1a9c06aa5

You can still see a couple immediately after the renegotiation succeeds, but it recovers right away. Closing as this fixes it for me, feel free to let us know if that's not the case.
