### ISSUE TITLE
Crash in lws_protocol_init

### ISSUE THREAD

**Issue by arturlangner** [meetecho/janus-gateway#1156]
I have just build latest janus. I have installed the default configs and tried running.
It crashes in `lws_protocol_init`. My libwebsockets is sane because other applications use it just fine.

Logs and traces: https://gist.github.com/arturlangner/b5f3a592fd7ba9dc03c8245071f5e811

**Comment by lminiero** [comment]
The trace doesn't contain any useful info, unfortunately.
