### ISSUE TITLE
H264 does not play in Safari

### ISSUE THREAD

**Issue by kamaliev** [meetecho/janus-gateway#1157]
Hello!

My janus.plugin.streamer.cfg

`[gstreamer-sample]
type = rtp
id = 1
description = Opus/VP8 live stream coming from gstreamer
audio = no
video = yes
videoport = 5004
videopt = 100
videortpmap = VP9/90000
collision = 3000
;secret = adminpwd`

my ffmepg command

ffmpeg -i rtsp://admin:pass@90.92.19.15:554/Streaming/Channels/101 \
-codec:v libx264 -profile:v baseline -preset ultrafast -tune zerolatency \
-s hd480 -pix_fmt yuv420p \
-b:v 0.2M -qmin 10 -qmax 50 -maxrate 0.3M -bufsize 1M \
-f rtp udp://127.0.0.1:8004

I tested with https://janus.conf.meetecho.com/streamingtest.html
example code.

Every browsers shows fine, but Safari browser in mac not showed and in Janus debug look like

`Transport task pool, serving request
No more remote candidates for handle 5113282193399523!
Sending Janus API response to janus.transport.websockets (0x7f357c001750)
[WSS-0x7f3585bc17c0] 71 ((null))
[WSS-0x7f357c0008c0] Sending WebSocket message (90 bytes)...
[WSS-0x7f357c0008c0]   -- Sent 90/90 bytes
[5113282193399523] Looks like DTLS!
[5113282193399523] Looks like DTLS!
[5113282193399523] Looks like DTLS!
[5113282193399523] Looks like DTLS!
[5113282193399523] Looks like DTLS!
[WARN] [h264-sample] RTP collision on video mountpoint, dropping packet (ssrc=3727784745)
[5113282193399523] Looks like DTLS!
[5113282193399523] Looks like DTLS!`

How to fix it?

Thank you

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), closing.
