### ISSUE TITLE
Screenshare freezing after PR 1118

### ISSUE THREAD

**Issue by agclark81** [meetecho/janus-gateway#1162]
We've been observing a new behavior since PR 1118 was merged into the refcount branch on 2018-01-10. A screenshare, with no bandwidth limit set, will freeze minutes after being initiated, and the remote end gets a frozen screen for a couple of minutes, after which it might briefly unfreeze and then re-freeze again. Chrome will report out via the WebRTC stats a linear increase of packetsLost that will track with an increasing googNacksReceived. This behavior occurs when using both the vp8 and h264 codecs, and it appears to only affect screenshares. This behavior is reproducible on the screenshare demo page online by initiating a screenshare, connecting to it via another tab (can be on the same computer), and leaving it open for a few minutes.

**Comment by lminiero** [comment]
Did you enable transport-wide cc for those rooms?

**Comment by agclark81** [comment]
No, not explicitly, and the default appears to be disabled.

**Comment by lminiero** [comment]
Then I don't see how that PR can change anything: it can only have an impact if the feature is enabled, otherwise everything stays the same. It doesn't seem to be happening for us, although we haven't tested extensively. If you know a version that is not affected, have you tried doing a `git bisect` to isolate the commit that breaks it for you?

**Comment by lminiero** [comment]
Any update?

**Comment by lminiero** [comment]
Closing for lack of feedback. Feel free to reopen if still an issue.

**Comment by lminiero** [comment]
@agclark81 you may want to look at the discussion in #1182, as it's probaby related to what you were experiencing.
