### ISSUE TITLE
sofia-sip : no.......can any one help me?

### ISSUE THREAD

**Issue by afshinsharafi** [meetecho/janus-gateway#1170]
hi
i wana compile janus gateway and
i download and install every dependency such as sofia-sip
i see in the result of ./configure 
sofia-sip : no
i am sure that i installed sofia-sip currectly.
can any one help me that why janus instalation process cant Detect sodia-sip
????

**Comment by lminiero** [comment]
Not a code issue, question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus).

**Comment by afshinsharafi** [comment]
can you help me ?...please...
i spend 2 days and i cant compile janus gate way because of sofia-sip

**Comment by lminiero** [comment]
G
R
O
U
P

**Comment by afshinsharafi** [comment]
i am locking in the group but i cant find my issue in there..

**Comment by afshinsharafi** [comment]
can you give me :  sofia-sip-ua dev lib Source address?

**Comment by bizzr3** [comment]
Sorry dude, but you can't open an issue, if you have server side issues
( Just ask in the group )

**Comment by bizzr3** [comment]
Afshin Jan, try a fresh installation, and let me know if you still have
that issue,but please make sure you are following the installation guide.

**Comment by afshinsharafi** [comment]
thank you mojtaba 
i will do that

**Comment by afshinsharafi** [comment]
Plugins:
    Echo Test:             yes
    Streaming:             yes
    Video Call:            yes
    SIP Gateway (Sofia):   no
    SIP Gateway (libre):   no
    NoSIP (RTP Bridge):    yes
    Audio Bridge:          yes
    Video Room:            yes
    Voice Mail:            yes
    Record&Play:           yes
    Text Room:             yes
Event handlers:
    Sample event handler:  yes
    RabbitMQ event handler:no
JavaScript modules:        no

**Comment by afshinsharafi** [comment]
i have the same error mojtaba
SIP Gateway (Sofia): no

**Comment by lminiero** [comment]
Do I have to ban you? I already told you *twice* to please use the group for questions like these.

**Comment by afshinsharafi** [comment]
when i run /.configure in the janus gateway folder i get this message

**Comment by bizzr3** [comment]
Alright, so FYI, here is not the correct place to ask this sort of
questions, please leave me a message at my mailbox, and I will try to help
you,and don't forget to attach the build log.
Thanks
