### ISSUE TITLE
janus-pp-rec.c how much CPU intensive it is

### ISSUE THREAD

**Issue by anildigital** [meetecho/janus-gateway#1171]
Hi,

This is not an issue per say, but could not find any docs about it so asking here in GH, but how much time `janus-pp-rec.c` takes to convert 10mins of worth recording to WebM/mp4 video and Opus audio files?

Does time of processing of `janus-pp-rec.c` increase with the size of recording?

**Comment by lminiero** [comment]
Not a code issue. Closing.
