### ISSUE TITLE
"_janus_log_level"  Undefined 

### ISSUE THREAD

**Issue by MinorUncle** [meetecho/janus-gateway#1174]
Hello, I have a problem, but this is not a bug. I tried to compile these plug-ins in Xcode,but show the error like "_janus_log_level Undefined symbols"  ， I know it's defined in janus.c ，How should I solve it？

**Comment by Globik** [comment]
@MinorUncle  try to compile plugins with -rdynamic flag. This flag resolves the symvols from the janus executable.

**Comment by lminiero** [comment]
Closing as not a code issue.

**Comment by MinorUncle** [comment]
@GaijinKa Thank you for your solution，But I have added "-rdynamic" to "Other Linker Flags". (in Xcode,the value of “Other Linker Flags” will be added to LDFLAGS), but it is still the same error. Is it the wrong place I wrote?

**Comment by Globik** [comment]
@MinorUncle  what kind of operation system do you have? Are you trying to compile the plugins by Lorenso's instructions or on your own?
Make shure You have Linux on board or what? Not windows.
If you are on your own you may want to make shure that xcode building exactly a dynamic lib, not static. There ara some trickyness to compile on your own. You should be familiare with the base knowlage, from command line, also from the code.

**Comment by Globik** [comment]
http://meandmark.com/blog/2011/03/xcode-4-accessing-build-settings/
@MinorUncle  Try to write and compile your own small programm executable with a dynamic plugin , a little mimic of Lorenzo's code in order to figured out HOW TO.

**Comment by Globik** [comment]
@MinorUncle  there are some tasks for you to figured out how to
Try to compile this programm. Shurely you must on your own write directories and pathes.
http://meandmark.com/blog/2011/03/xcode-4-accessing-build-settings/
Then complexer, with dlsym functionality:
https://github.com/Globik/webrtc/tree/master/thread1
Without it you can't to figure out how to hack Lorenzo's code.

**Comment by Globik** [comment]
Make note @MinorUncle  janus.exe should be compiled with -rdynamic. Or do you have clang compiler?

down vote
accepted
At least clang 3.3 seems to support -rdynamic though neither clang --help nor the manpage documents it. (If you are on OSX, -rdynamic isn't needed)

gcc -rdynamic says "-rdynamic Pass the flag --export-dynamic to the ELF linker, on targets that support it."

So clang should also be able to do the same with -Wl,--export-dynamic

**Comment by MinorUncle** [comment]
@Globik I use in the OSX operating system and work on Xcode. I have compiled the entire project on the command line. However,like  the above "Undefined symbols" error occurs when I compile it on Xcode.All the libraries I use are dynamic libraries.

**Comment by MinorUncle** [comment]
@Globik The task you gave me, I can do it correctly at the command line,
In xcode, the task at "https://github.com/Globik/webrtc/tree/master/thread" was also completed correctly.
 But the task in "https://github.com/Globik/webrtc/tree/master/thread1",
In order to complete the target of "p" in the makefile, I go to compile "plugin.c”,but there are also many undefined symbols,These symbols are in "glib-2.0"

**Comment by MinorUncle** [comment]
I have a question. in the "./thread1/makefile"
`p: p
    Gcc $(INCLS) $(CFLAGS) -c -fpic ./plugin/plugin.c`
 
did not link "glib-2.0", why it can link correctly？

**Comment by MinorUncle** [comment]
@Globik I found that I was wrong. This is just a compilation, not yet linked. I continue to accomplish these tasks, thanks

**Comment by MinorUncle** [comment]
@Globik I just tried on the command line. In the "./thread1/plugin" directory, I first use the "make j" command, then use the "make v" command, and there will be "j_plugin_res_new Undefined" error.

**Comment by Globik** [comment]
@MinorUncle I have forgotten to place the plugin.c file to j target and plugin.o to v target : ), I'm so sorry.

**Comment by MinorUncle** [comment]
@Globik Yes, I have configured the path and parameters correctly,If I add "plugin.c" to the target of "J" and "plugin.o" to the target of "V", I can compile "libecho.so" correctly. But this is different from the question I asked ("janus_log_level Undefined" error). In plug-ins, it doesn't contain "janus.c", so "janus_log_level" is not really linked to plug-ins. but in libecho.so, all symbols are linked.

**Comment by MinorUncle** [comment]
@Globik 
Do you know where the compilation flags and link flags are configured in the "janus-gateway" project? I was a little blunt and couldn't find it

**Comment by Globik** [comment]
Hi @MinorUncle  I'll reinvestigate my code and I'll try to provide a dummy_janus_log_level variable in executable file.
Ldflags are everywhere. Personally I'm using definitions JANUS_CFLAGS , JANUS_LIBS for custom compiling of janus. There a reson for me cause my new openssl installed in non standard directory.

**Comment by Globik** [comment]
I remember this case on windows. Also tried to compile the plugins. But always janus_log_level and his family was undefined for me. So I changed the source code a lot, specific for windows os. Two steps to compile. One for janus.exe itself, and step two for a plugin with a magic of dllexport. Just defined myself a definition in the source for two variants: with export stuff and non export stuff.
Sorry, english is not my native language.

**Comment by Globik** [comment]
Ldflags is also here
https://github.com/meetecho/janus-gateway/blob/master/configure.ac#L26

**Comment by Globik** [comment]
@MinorUncle  and a important question to you, are you trying to write a new plugin for janus on your own?
Or just there are the linkage errors?
Out from the box Janus supports macOS as I understand. Many using it on macOS.
Just do like in a readme.
sh autoge.sh
./configure
make
Etc...

**Comment by Globik** [comment]
Perhaps your compiler does not support -rdynamic flag?

**Comment by Globik** [comment]
Exactly _janus_log_level? May be janus_log_level? 
Make sure you using compiler for C code, not for C++.

**Comment by Globik** [comment]
@MinorUncle  you know the ide you a using may mess up all things. Let'say static compilation for dynamic purpose and back dynamic compilation for a static.
It's better to compile all stuff from a command line in the console then using any IDE.

**Comment by Globik** [comment]
And what gives configure output to you?

**Comment by Globik** [comment]
Janus_log_level undefined by what step? By linkage? Or at run time of janus command?

**Comment by MinorUncle** [comment]
Thank you for your patient answer. Yes, Just do like in a readme, I have completed the compilation in the command line, but now I want to compile it in Xcode, so it will be easier to debug.

**Comment by Globik** [comment]
Janus_echotest.dlyb to compile must in xcode to have different flags.
Janus.exe to compile must in xcode to have also different flags and pathes and includes.
It means you have to have two diffrent projects if you trying usin the xcode.

**Comment by MinorUncle** [comment]
@Globik After compiling, the corresponding symbol generated by "janus_log_level" is "_janus_log_level", so here they are the same thing. I'm sure I'm using the C compiler

**Comment by MinorUncle** [comment]
I finally solved the problem and changed some of the code. I put "janus_log_level" in log.c, and log.c has compiled into a separate dynamic library.

**Comment by MinorUncle** [comment]
Janus_log_level undefined by linkage

**Comment by Globik** [comment]
It's great))) i also did so when i was on f***g windows)

**Comment by MinorUncle** [comment]
Thank you very much

**Comment by MinorUncle** [comment]
Aha, english is not my native language as well, Are you Russian, you are very enthusiastic, thank you again
