### ISSUE TITLE
Handshake failure in echotest

### ISSUE THREAD

**Issue by Globik** [meetecho/janus-gateway#1175]
Echo test:
DTLS1_READ_BYTES: sslv3 alert handshake failure.
Chromium version 62 ubuntu 14.04 32-bit
In firefox OK.

**Comment by Globik** [comment]
OK, is there in configure --openssldir? Updated openssl from source and installed in non standard directory.

**Comment by lminiero** [comment]
Can you confirm that #1148 is the issue, and not something else, like #1166 for instance? If it's #1148, which of the two lines causes it for you?

**Comment by lminiero** [comment]
> OK, is there in configure --openssldir? Updated openssl from source and installed in non standard directory.

No, you have to mess with CGLAGS and LDFLAGS when configuring I think.

**Comment by lminiero** [comment]
Ping...

**Comment by Globik** [comment]
Pong..
It's my fault I thing. Struggling over openssl and family in non standart directory after compiling from source. One can close this issue. So sorry, waiting for other developer what they are saying about it.

**Comment by lminiero** [comment]
Ack, closing then.

**Comment by Globik** [comment]
All right now. With JANUS_CFLAGS and JANUS_LIBS definitions I solved the issue with openssl in non standard directory. Now echotest works like a charm in chromium.
