### ISSUE TITLE
turn uris in dynamic TURN credentials aren't name-resolved

### ISSUE THREAD

**Issue by mzanetti** [meetecho/janus-gateway#1176]
We're about to switch from hardcoded TURN credentials to dynamically provided ones by a REST server. It seems to work with one exception: Our server gives those turn uris as urls, not as IPs.

Looking at the janus code it seems it indeed just omits the lookup for names. This quick'n dirty patch makes it work for us. A real solution should probably check whether a resolution is required or not and deal better with the IPv6 part of it.

http://paste.ubuntu.com/p/8zsmyh4fkf/

**Comment by lminiero** [comment]
Thanks for the heads up. A pull request would be welcome, as tomorrow I'll fly to London for the IETF and will likely have few to no time to code anything myself until I come back.

**Comment by lminiero** [comment]
This commit should fix it: it's different from your patch, as I just incorporated what we already do for static TURN servers at startup (which we resolve as well). Verified it resolves to IPv6 if the TURN server has an IPv6 resolve too, and that if you pass a numeric IP it's resolved to itself.
