### ISSUE TITLE
900 Internal error at nua_client.c:711

### ISSUE THREAD

**Issue by speedo-spin** [meetecho/janus-gateway#1177]
Hi
I'm trying to make janus work localy (siptest demo), but get 
```
nta outgoing create: invalid URI
[user_1000][nua_r_invite]: 900 Internal error at nua_client.c:711
```

https://pastebin.com/SvFUdGVa

can anybody tell me what is wrong?

seems like smt similar to https://groups.google.com/forum/#!searchin/meetecho-janus/900%7Csort:date/meetecho-janus/0JBbMeepz04/g4gf4jAcAgAJ but solution is not provided (also I was unable to reply in google group, so created new issue here)

**Comment by speedo-spin** [comment]
seems like problem was because of sofia-sip library
Installing sofia-sip from this source solve issue for me 
https://github.com/BelledonneCommunications/sofia-sip

**Comment by prcvoldermort** [comment]
Wow~You saved my life!!!

**Comment by prcvoldermort** [comment]
Just git clone the whole project, use and compile the master branch, then ./configure with  --libdir=/usr/lib64. Finally do the janus compile things.
