### ISSUE TITLE
Janus Crash :- SDP Merge

### ISSUE THREAD

**Issue by garg-geek** [meetecho/janus-gateway#1181]
From few days i am having frequent janus crash. I generated coredump and tried to print stack trace. [https://pastebin.com/wXECn15P] here is the stack trace.

**Comment by atoppi** [comment]
Can you give a bit more context to the issue?
- Involved plugins 
- Usage scenario
- Browsers

**Comment by garg-geek** [comment]
- Janus commit:- I installed janus from master branch. Last commit id was 
   af87b812b4dfc3fb31ce3f161f6832c5bfe80c75.
- Involved plugins:- I am using video room plugin only.
- Browser:- FireFox v45
- Usage scenario:- One to One video call.

**Comment by atoppi** [comment]
Your Firefox version is quite old (March 2016), try first with a recent version.

The issue arises on the first access to `stream` in `sdp.c`, when dealing with a SDP answer coming from a listener Peer Connection.
Please post the Janus logs (not here, use a service like pastebin) and try to reproduce the issue with libasan enabled. If the `stream` has been somehow freed, libasan should catch the event of reusing after free.

**Comment by garg-geek** [comment]
Had janus crash again. This time stack trace was different. [https://pastebin.com/Jt2eqZ4K](url)

**Comment by atoppi** [comment]
This one is totally different from the original issue.
Are you dynamically creating and/or destroying the videorooms you are connecting to? Or you're just trying the default demo room? 
If you are not handling with the rooms, chances are Janus is freeing a participant while it is trying to relay the media to him. Issues like this are managed in the `refcount` branch (a run with it might worth a try).

All said, the guidelines I gave you are still valid:
- we need the Janus logs
- we need details on your usage scenario (what are you doing with the video rooms and the peers involved)
- in many cases (like this) we need a `libasan` output to help identify heap memory errors

**Comment by garg-geek** [comment]
This time issue occured and it was sdp merge. [https://pastebin.com/QEUXDYmj](url) This is stack trace.
I have uploaded janus logs on drive. here is the link [https://drive.google.com/file/d/1NvuxHQvLgfTyfCUjWvh2M3q1BE0wX_g8/view?usp=sharing](url).

Session id was :- 6151095408564181
handle id was :- 6151095408564181
room id was:- 16739727746150

About usecase:- When a publisher produces media , each time  new session and plugin handle is created then new video room is created. Then it joins the room as publisher. Then room is configured with configurations like file name,audio or video false and sdp offer.

When listener comes we create session then handle , then join room with feed id , in response sdp offer comes then we send sdp answer. 

So yes we are dynamically creating and destroying video rooms.

Also are you suggesting that we should switch to refcount branch as it is more stable?

**Comment by lminiero** [comment]
Make sure you're using master, I made a couple of changes recently.

**Comment by atoppi** [comment]
Noticed in your janus logs
`[Fri Mar 23 13:53:51 2018] Attempt to destroy an existing videoroom room`
in the middle of a negotiation. Is that a intended behavior or not?
This might be the root of the crashes.

**Comment by garg-geek** [comment]
I cross examined logs of my application and janus and i realised that negotiation was going on and before janus merged sdp, application sent event to delete video room. That might be the case. If that is the case then should not it be handled at janus side?
                               Yes this is intended behaviour.
@lminiero i will try with the latest code and see if it helps.

**Comment by lminiero** [comment]
> Yes this is intended behaviour

You mean you WANTED to destroy a room WHILE you were negotiating? This was intentional? Not sure what the purpose is, but it looks like a recipe for disaster. We can try and have a look in the next few weeks t see why it crashes in that specific circumstance, but I highly encourage you to destroy rooms following a more reasonable pattern, as otherwise you'll most likely encounter undefined behaviour like this.

**Comment by garg-geek** [comment]
@lminiero In my usecase(Application that i have built)  from browser events  are sent to my application server to start and stop streaming and application server send create room etc events to janus over web socket. When crash happened stop event came while negotiating.  So blindly i destroyed room and removed session and plugin handle.
Is there any event sent by janus to check that negotiation has been done or failed?

**Comment by atoppi** [comment]
> When crash happened stop event came while negotiating. So blindly i destroyed room 

Do you mean that your application server is reacting to a browser failure with a room destroy?

> Is there any event sent by janus to check that negotiation has been done or failed?

Easy task on browser side with ice state callbacks.
Janus will notify a success with `webrtcup` and might possibly notify a failure with `hangup` and a reason.

**Comment by garg-geek** [comment]
Not necessarily browser failure. To simplify let's say I have two button on
browser page. One for start and one for stop. So I clicked on start and
just after that when negotiation was going on, I clicked on stop.

**Comment by atoppi** [comment]
@garg-geek Understood.
Can you test your scenario against the `refcount` branch? It is intended to solve race conditions like the ones you are experiencing.

**Comment by lminiero** [comment]
Closing as we haven't heard from you for more than a month, so I'll just assume it's fixed. Feel free to reopen if still an issue.
