### ISSUE TITLE
Missing clean-up of janus.plugin.voicemail.cfg.sample

### ISSUE THREAD

**Issue by CyrilBrulebois** [meetecho/janus-gateway#1184]
Hi,

While looking into updating the Debian packaging to 0.3.0, I noticed that there's a generated file left behind after a build: `janus.plugin.voicemail.cfg.sample`

I'm attaching a patch which fixes this.
[0001-Clean-generated-janus.plugin.voicemail.cfg.sample.patch.txt](https://github.com/meetecho/janus-gateway/files/1836663/0001-Clean-generated-janus.plugin.voicemail.cfg.sample.patch.txt)

**Comment by lminiero** [comment]
Are you sure it's only a problem for the Voicemail cfg file? I see the CLEANFILES part missing for a lot of plugins.

**Comment by CyrilBrulebois** [comment]
I'm rather confident: the problem affects components which have their configuration generated from a `.in` file while not being removed through `CLEANFILES`. It looks to me only the Voicemail plugin matches both criteria.

Slightly more verbosely:

- Components with a static configuration don't have anything to clean-up.

- Other components with a dynamic configuration declare an addition to `CLEANFILES`: `conf/janus.cfg.sample`, `conf/janus.transport.http.cfg.sample`, and `conf/janus.transport.websockets.cfg.sample`.

**Comment by lminiero** [comment]
Got it, thanks for the heads up and the proposed fix!
