### ISSUE TITLE
Getting rid of RTSP stream if cannot connect.

### ISSUE THREAD

**Issue by Triuman** [meetecho/janus-gateway#1186]
https://github.com/meetecho/janus-gateway/blob/27708e3026659c782e0960a7b73fef33983eb0f0/plugins/janus_streaming.c#L4104

Instead of removing the mountpoint, we could just keep it and try to connect once in a while as the camera might be close when Janus starts.

Thank you.

**Comment by lminiero** [comment]
Good point, even though it's not as easy it looks. I'll add to the TODO list but no idea on when I'll be able to tackle this.

**Comment by Triuman** [comment]
I found a very easy way. Just delete the lines below. It will try to connect in the relay thread and if it cannot it will retry.

`if(janus_streaming_rtsp_connect_to_server(live_rtsp) < 0) {
		/* Error connecting, get rid of the mountpoint */
		janus_streaming_mountpoint_free(live_rtsp);
		janus_mutex_unlock(&mountpoints_mutex);
		return NULL;
	}
	/* Send an RTSP PLAY, now */
	if(janus_streaming_rtsp_play(live_rtsp_source) < 0) {
		/* Error trying to play, get rid of the mountpoint */
		janus_streaming_mountpoint_free(live_rtsp);
		janus_mutex_unlock(&mountpoints_mutex);
		return NULL;
	}`

**Comment by Triuman** [comment]
I found a very easy way. Just delete the lines below. It will try to connect in the relay thread and if it cannot it will retry. I tried it and it worked well.
```

      if(janus_streaming_rtsp_connect_to_server(live_rtsp) < 0) {
		/* Error connecting, get rid of the mountpoint */
		janus_streaming_mountpoint_free(live_rtsp);
		janus_mutex_unlock(&mountpoints_mutex);
		return NULL;
	}
	/* Send an RTSP PLAY, now */
	if(janus_streaming_rtsp_play(live_rtsp_source) < 0) {
		/* Error trying to play, get rid of the mountpoint */
		janus_streaming_mountpoint_free(live_rtsp);
		janus_mutex_unlock(&mountpoints_mutex);
		return NULL;
	}
```

**Comment by lminiero** [comment]
Mh, not sure I'd like to just remove this entirely. Better to add an option to decide whether to return an error if the first connect fails (what we do now) or go ahead and leave the reconnect in place (what you changed). I'll add it to the TODO list.

**Comment by lminiero** [comment]
Commit https://github.com/meetecho/janus-gateway/commit/98d80bb34f66c53be7c12c7920c12a57de56aa93 should implement what I said. It adds a new property called `rtsp_failcheck` when configuring RTSP mountpoints: if `TRUE` (the default) it fails if connecting to the server fails; if `FALSE`, it goes straight to the thread and leaves it up to the autoreconnection mechanism.

**Comment by Triuman** [comment]
Good job! Thank you.
