### ISSUE TITLE
Volume of Audio is very low

### ISSUE THREAD

**Issue by krishnaclouds** [meetecho/janus-gateway#1187]
I am trying to use streaming plugin:

type = rtsp
id = 420
description = RTSP Test
audio = yes
video = no
url=rtsp://192.168.1.30:554/videoMain
videortpmap = H264/90000
videofmtp = profile-level-id=42e01f;packetization-mode=1
rtsp_user=username
rtsp_pwd=password

The Video and Audio are being transmitted successfully, but the volume of Audio being received is very very low.  I am unable to find a relevant reason for this. 

SDP Offer: https://pastebin.com/embed_iframe/aSr6xpFi

SDP Answer: https://pastebin.com/embed_js/uikTjiV1

**Comment by lminiero** [comment]
It's definitely not Janus, as it only relays media. Closing.

**Comment by krishnaclouds** [comment]
Can it be Chromium issue?
