### ISSUE TITLE
chrome only gathers host candidates for answer

### ISSUE THREAD

**Issue by xenyou** [meetecho/janus-gateway#1188]
steps to reproduce.

1. for debug, insert this line in onicecandidate within janus.js
```
console.log(event.candidate);
```
2. access videoroom demo with chrome (user1)
3.  join the videoroom demo in another tab. (user2)
4. Check the user1's console. There is no stun candidates.

![screen shot 2018-03-25 at 16 57 17](https://user-images.githubusercontent.com/832358/37873017-900bb2a8-304e-11e8-9d49-0e49d1c5e745.png)

**Comment by lminiero** [comment]
Not sure why you opened an issue here for a behaviour in the browser. Anyway, it's very likely that the browser didn't gather all candidates because connectivity succeeded sooner than expected and so they were not needed. Closing.

**Comment by xenyou** [comment]
I opened this here because it works when I  copy the SDP from janus and paset it directly to the js code (in my application, not demo).
So I thought SDP from janus might be something wrong.
But not sure indeed.

**Comment by xenyou** [comment]
And this is problemtic when I use iOS safari (safari has the same behaviour).
Because they hides host private candidates.
Then iOS gathered no candidastes.

Anyway I'll try investigate it again later. Sorry for bothering you.

**Comment by lminiero** [comment]
Safari won't gather host candidates if you don't do a getUserMedia first.

**Comment by xenyou** [comment]
> Safari won't gather host candidates if you don't do a getUserMedia first.

Thank you for infromation. 

By the way, it seems that removing a=candidate from janus SDP forces the browsers use STUN.
So, I'll use this hack. Thanks.

**Comment by lminiero** [comment]
> By the way, it seems that removing a=candidate from janus SDP forces the browsers use STUN.

Mh, but removing a=candidate means preventing Janus to send you its candidates. If you don't want candidates in the SDP, you can use full-trickle, which is now available as an option in Janus. I think the only reason why you didn't get all candidates in the browser, is that Janus was sending you ALL the candidates in the SDP when half-trickling (see a=end-of-candidates), and Chrome would find a working match much sooner, thus stopping the gathering.

**Comment by xenyou** [comment]
Thanks for information. I'll try it later.
