### ISSUE TITLE
[Question] Thread safety

### ISSUE THREAD

**Issue by RSATom** [meetecho/janus-gateway#1192]
Hi, I want write some new plugin for Janus Gateway and have some question about it:
1. Could you please clarify if plugin API (set of functions assigned to janus_plugin structure) implementation should be thread safe or not?
2. Is Janus callbacks are thread safe?
3. Is there any guide about writing new Janus plugin from scratch?

Thanks in advance!

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), we only handle code issues here. Closing.
