### ISSUE TITLE
[Question] Is there a dead log in the log?

### ISSUE THREAD

**Issue by dinfer** [meetecho/janus-gateway#1193]
When `janus_log_init` starts `janus_log_thread`, the "log" thread will lock the `lock` variable as soon as possible. And once it acquires the lock, it will wait for the `cond`. At this time. the `lock` is locked by the "log" thread. [code](https://github.com/meetecho/janus-gateway/blob/master/log.c#L98-L104)

Then, when calling `janus_vprintf`, which will use `janus_log_getbuf` to get a buffer, will locks the `lock` before finding a usable buffer. The main thread will be blocked. The `janus_vprintf` only signals the `cond` AFTER got a buffer.

Is it a dead lock? or am I wrong?

**Comment by lminiero** [comment]
I have never seen the code deadlock there. I guess you mean this can happen if the thread gets there before `janus_vprintf` is called?

**Comment by dinfer** [comment]
yes

**Comment by lminiero** [comment]
Sorry, forgot about this... just checked the docs and this is the [correct behaviour](https://developer.gnome.org/glib/stable/glib-Threads.html#g-cond-wait) when using `g_cond_wait`:

    Atomically releases mutex and waits until cond is signalled.
    When this function returns, mutex is locked again and owned by the calling thread.

This is why we lock before calling `g_cond_wait`, and release when it returns. Closing.
