### ISSUE TITLE
Better if LOG_DBG rather than LOG_HUGE

### ISSUE THREAD

**Issue by Triuman** [meetecho/janus-gateway#1196]
https://github.com/meetecho/janus-gateway/blob/2639e2979eeca6b3c65cafdb80f8621c16d832fa/utils.c#L650

This is an excessive log. I believe this should be LOG_DBG.

**Comment by lminiero** [comment]
As if `LOG_HUGE` isn't excessive on its own :smile: 
Fair point, though, I'll change it.

**Comment by lminiero** [comment]
I ended up removing it entirely, as we don't really care which fragments we receive. Closing.
