### ISSUE TITLE
when we push disable video, the two camera windows should disappear

### ISSUE THREAD

**Issue by jidanni** [meetecho/janus-gateway#1201]
On https://janus.conf.meetecho.com/echotest.html
when we push disable video, the two camera windows should disappear.

**Comment by lminiero** [comment]
"Disable video" doesn't mean what you think it does. It simply instructs the plugin to drop the video packets, and not send them back: you're still capturing and sending them, though. Closing.

**Comment by jidanni** [comment]
I would have a mouseover to say that, as most users wouldn't expect that meaning.
