### ISSUE TITLE
Janus hang after upgrading 0.4.0 and joining a room which does not exist

### ISSUE THREAD

**Issue by trankkilou** [meetecho/janus-gateway#1204]
To reproduce the issue

start janus
start a session
join video room plugin + text room plugin (with a non existing text room)

janus log: https://pastebin.com/NzMZidHz

**Comment by lminiero** [comment]
Solved. The issue is that you were setting `notify_joining=yes`: since it's NOT the default, we couldn't replicate it. Enabling that had a double lock in place, which we removed.
