### ISSUE TITLE
Videoroomtest on Chrome: `Cannot assign to read only property 'iceServers' of object '#'"`

### ISSUE THREAD

**Issue by karth295** [meetecho/janus-gateway#1210]
I just started seeing this on my site (https://tawk.space) and confirmed it's an issue on the [videoroomtest](https://janus.conf.meetecho.com/videoroomtest.html).

Repro (on Chrome 65.0.3325.181 on Windows 10):

  - Open videoroomtest, create a username, see your video published. This should work.
  - Soft refresh (Ctrl-R for me). Again, create a username, but this time you'll see an error like this:

```
WebRTC error... {"name":"TypeError","message":"Cannot assign to read only property 'iceServers' of object '#'"}
```

  - This seems to happen consistently on soft refreshes, including after turning off adblockers, trying incognito, etc
  - Hard refresh (Ctrl-Shift-R for me) consistently is fine -- you can publish video.

However, I could not repro this issue on Firefox on Windows 10. Hopefully this is not just a weird issue with my Chrome environment.

Again, I just started seeing this today. I was on a version of Janus from a couple months ago, and I did try updating to the latest with no luck.

**Comment by lminiero** [comment]
Works fine here, can't replicate it.

**Comment by karth295** [comment]
Weird, I can't reproduce it on Chrome beta on windows 10 or Chrome beta on android. Alright, I'll close this as not reproducible outside my environment.

**Comment by arpu** [comment]
have the same problem with 
Version 65.0.3325.181 (Offizieller Build) (64-Bit)
( fedora 27)

**Comment by karth295** [comment]
@arpu what Chrome extensions do you have?

I noticed it was fine when I freshly installed Chrome Beta with no extensions, but then when I added a few extensions, I saw this bug again. I specifically installed Adblock, Adblock Plus, Ghostery, and Ublock Origin. The issue persisted even after I turned the extensions off. So maybe there's a weird caching issue?

**Comment by bigbangvn** [comment]
I also got this issue a few days ago (can't reproduce now).
On Chrome: Version 65.0.3325.181 (Official Build) (64-bit), with some extension: Ads blocker, adb..
I tried Firefox and it's ok. I guess it's problem of new Chrome version

**Comment by arpu** [comment]
@karth295  yeahh you are right the problem was/is Adblock Plus  3.0.3 
if i complete disable adblok h plus all works fine

**Comment by arpu** [comment]
only disable adblock plus on the website does not help, need to disable the extentation

**Comment by agclark81** [comment]
We're seeing the same issues as others have described, also with Adblock on Chrome 65. I recognize that this isn't a Janus issue since Adblock is tampering with RTCPeerConnection, but not sure if we have any options for circumventing these blocks outside of advising folks to disable Adblock in the meantime. It appears to occur when we create the room for the first time and not if we're joining an existing room, so potentially the extension is picking up something inside the create command.

**Comment by lminiero** [comment]
Or maybe you should all drop Adblock and pass to uBlock as I did :grin:
