### ISSUE TITLE
srtpsuite and srtpcrypto not permanently saved on created streaming mountpoint

### ISSUE THREAD

**Issue by ikoes** [meetecho/janus-gateway#1217]
Hello,
I'm using janus branch http-single-thread. I've noticed that when a new streaming RTP mountpoint is created via HTTP-REST API, srtpsuite and srtpcrypto values are not permanently stored on the provided janus.plugin.streaming.cfg file even if the "permament" option is selected.

Thanks
F.

**Comment by lminiero** [comment]
The `http-single-thread` branch is not aligned with master. Please try master instead and let us know if it's still an issue there, since we may have fixed it in the meanwhile.

**Comment by lminiero** [comment]
Thanks for the heads up :+1: 

Looks like we're not saving it as we're actually not storing the original values after we create the SRTP session. We'll have to first save those, and then save them to config after `create` and `edit`. My guess is that the same issue also occurs for new AudioBridge rooms with static SRTP forwarders, I'll have to check.

**Comment by lminiero** [comment]
Pleas let me knos if this commit fixes it: unfortunately I don't have to time to test it.
