### ISSUE TITLE
Extend dependencies in Janus.init

### ISSUE THREAD

**Issue by phsultan** [meetecho/janus-gateway#1229]
Hi !

I'm initializing Janus with a specific version of `adapter.js` the following way:
```
Janus.init({
    dependencies: {
      webRTCAdapter: MyWebRTCAdaper
    },
    debug: "all",
    callback: function() {console.log('ok');}
})
```

Doing so will not create the following objects in Janus:
```
    Janus.isArray = usedDependencies.isArray;
    Janus.httpAPICall = usedDependencies.httpAPICall;
    Janus.checkJanusExtension = usedDependencies.checkJanusExtension;
    Janus.newWebSocket = usedDependencies.newWebSocket;
```

And leads to an error when creating a new Janus instance. To reproduce the error, the code below can be used:
```
Janus.init({
	debug: "all",
	dependencies: {
		webRTCAdapter: {} // Empty object used for testing, the same error is thrown with a valid adapter.js instance
	},
	callback: function() {
		console.log('Janus init ok');
		var serverWsURL = 'wss://a-valid-secured-websocket-server-name:8989';
		var janusInstance = new Janus({
			server: serverWsURL,
			success: function() {
				console.log('Instance created');
			},
			error: function(error) {
				Janus.error(error);
			},
			destroyed: function() {
				console.log('Instance destroyed');
			}
		});
	}
});
```

Error thrown: `TypeError: Janus.isArray is not a function`.

As a workaround, I can build the `dependencies` object with all the necessary objects, but instead I modified `Janus.js` in order to accept to extend the dependencies using the `deps` argument in `useDefaultDependencies()`. The diff is simple, although I can make a PR if needed:
```
diff --git a/src/Janus.js b/src/Janus.js
index ccf4635..4c33ccc 100644
--- a/src/Janus.js
+++ b/src/Janus.js
@@ -33,7 +33,7 @@ Janus.useDefaultDependencies = function (deps) {
                newWebSocket: function(server, proto) { return new socketCls(server, proto); },
                isArray: function(arr) { return Array.isArray(arr); },
                checkJanusExtension: function() { return document.querySelector('#janus-extension-installed') !== null; },
-               webRTCAdapter: (deps && deps.adapter) || adapter,
+               webRTCAdapter: (deps && deps.webRTCAdapter) || adapter,
                httpAPICall: function(url, options) {
                        var fetchOptions = {
                                method: options.verb,
@@ -102,7 +102,7 @@ Janus.useOldDependencies = function (deps) {
                newWebSocket: function(server, proto) { return new socketCls(server, proto); },
                isArray: function(arr) { return jq.isArray(arr); },
                checkJanusExtension: function() { return jq('#janus-extension-installed').length > 0; },
-               webRTCAdapter: (deps && deps.adapter) || adapter,
+               webRTCAdapter: (deps && deps.webRTCAdapter) || adapter,
                httpAPICall: function(url, options) {
                        var payload = options.body !== undefined ? {
                                contentType: 'application/json',
@@ -189,7 +189,8 @@ Janus.init = function(options) {
                }
                Janus.log("Initializing library");
 
-               var usedDependencies = options.dependencies || Janus.useDefaultDependencies();
+               var usedDependencies = Janus.useDefaultDependencies(options.dependencies);
+
                Janus.isArray = usedDependencies.isArray;
                Janus.webRTCAdapter = usedDependencies.webRTCAdapter;
                Janus.httpAPICall = usedDependencies.httpAPICall;
```

I'm not sure why the `deps` argument is not used in `useDefaultDependencies`,  and maybe that function should be renamed if this change is accepted.

Thanks for the work that's being done on Janus !

**Comment by lminiero** [comment]
Hey Philippe, nice to hear from you again!

I'm not sure we should mess with the existing dependency objects, that is `useDefaultDependencies` and `useOldDependencies`: we might want to add a new stub object (e.g., `useCustomDependencies`?) instead, something that maybe inherits from `useDefaultDependencies` the properties that you didn't specify. Not sure if this makes sense, or if your suggestion indeed fixes an issue in the original submission: pinging @cmacq2 to correct me in case!

**Comment by phsultan** [comment]
Thanks Lorenzo, I'm happily back to using Janus ;-)

Yep, using the `deps` argument in `useDefaultDependencies()` rather than passing a fully instanciated `dependencies` object in `options` is the purpose of the change, but you're right, I'm not sure of the implications.

Looking at the code, `useOldDependencies()` seems to be here from the time `Janus.js` was relying on `jQuery`, and is no longer used in the code. It remains available to developers who were relying on it though.

**Comment by lminiero** [comment]
Sorry for the late feedback, I've been away for a few days and forgot about this... now that I look at your patch better, the concept is clearer, thanks!

I have a few doubts about the code, though. First of all, doesn't `deps && deps.adapter` (or `deps && deps.webRTCAdapter` as you fixed) translate to `true` in that check? Shouldn't it be something like `(deps && deps.webRTCAdapter) ? deps.webRTCAdapter : adapter`? Maybe it's the C guy in me who's talking, and the way it is might be a legitimate syntax in JS instead...

Even with this approach, it looks like not all of the properties can be overriddden, though: actually, webrtcAdapter is the only one that can, so in your specific case that works fine as the code takes `deps` into account there (although there was a typo your patch fixes); if you just want to replace `isArray`, though, you can't, as `deps` is ignored there. I guess it will be a matter of doing the same for all of them, e.g.:

```
httpAPICall: (deps && deps.httpAPICall) || function(url, options)
```

**Comment by lminiero** [comment]
Note: httpAPICall is a wrong example here, as `deps.fetch` is already used... maybe `isArray` is a better example.

**Comment by phsultan** [comment]
Hi Lorenzo,

> Sorry for the late feedback, I've been away for a few days and forgot about this... now that I look at your patch better, the concept is clearer, thanks!

No worries, I know you were in Berlin chasing down Pizza + Pineapples lovers :-)

`deps && deps.webRTCApdater` returns `deps.webRTCApdater` in JS if `deps` cannot be converted to `false` (i.e. if it does not return any of the followig: `null, NaN, 0, empty string ("" or ''),  undefined`). This is quoted from [this JavaScript reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Description), that indeed differs from C :-)

You have the same construction in the current `useDefaultDependencies` function at its beginning:
```
Janus.useDefaultDependencies = function (deps) {
	var f = (deps && deps.fetch) || fetch;
	var p = (deps && deps.Promise) || Promise;
	var socketCls = (deps && deps.WebSocket) || WebSocket;
...
```

You're right that it won't allow to change `isArray`, but the purpose was to change what can be changed as of now with `useDefaultDependencies`, which limits us to `fetch, Promise, WebSocket, webRTCAdapter`. 

In my opinion, `isArray` should not be subject to change and we should stick with `isArray = Array.isArray` like it is now in `useDefaultDependencies`, and allow users that still want to use `jQuery` get the alternate `jQuery.isArray` version in `useOldDependencies`.

In the context of this patch, we should probably rename `useDefaultDependencies` (suggestion : `buildDependencies`) as the function is called differently:

```
-            var usedDependencies = options.dependencies || Janus.useDefaultDependencies();
+            var usedDependencies = Janus.useDefaultDependencies(options.dependencies);
```

Calling `options.dependencies || Janus.useDefaultDependencies();` was the reason I originally proposed the patch, as it would force to define `isArray` in `options.dependencies` to work around the `TypeError: Janus.isArray is not a function.` error.

Sorry if I'm not clear enough here though, let me know if you have any question.

Cheers !

**Comment by lminiero** [comment]
Makes a lot of sense, thanks for the clarification and sorry for my abysmal JavaScript ignorance :smile: 
I'll integrate your patch in the code later today :+1:

**Comment by lminiero** [comment]
Obviously my patch was breaking the default scenarios instead, so just fixed that...

**Comment by cmacq2** [comment]
Sorry to resurrect this but do note: if you wanted to override `isArray()`, what you could do instead is the following:

```
var deps = Janus.useDefaultDependencies();
deps.isArray = function(testMe) {
   return true; // todo, replace with real implementation.
};
```

That approach for *any* dependency, has always done and is kind of typical for JavaScript code.

The case of the OP, again is different. OP simply should have done:

```
Janus.init({
  dependencies: Janus.useDefaultDependencies({adapter: MyWebRTCAdapter}),
  debug: "all",
  callback: function() { console.log("ok"); }
});
```

That is even *explicitly documented*. Note the example about modern ES modules. ;)

**Comment by cmacq2** [comment]
I would suggest to revert the single commit. Possibly add the two examples I gave to the docs as well?

**Comment by lminiero** [comment]
@cmacq2 sorry about that, I hadn't realized I was breaking stuff... I add a look at the docs but it wasn't clear to me what could it could not be done, as I personally never used the feature and am far from a JavaScript expert (and if you read the exchange Philippe and I had you'll find more work comments from me in that regard :smile: ). If you let me know what to revert specifically, I'll do that on Monday.

**Comment by phsultan** [comment]
Guys, I indeed had not read this [JavaScript documentation](https://janus.conf.meetecho.com/docs/js-dependencies.html), sorry about that.

However, I must say that object initialization like this example:
```
import * as WebRTCAdapter from "webrtc-adapter";

Janus.init({
    dependencies: {
      webRTCAdapter: WebRTCAdapter
    },
    debug: "all",
    callback: function() {console.log('ok');}
})
```

Is more like what I've seen working with JavaScript libraries, where default options are extended by passing JavaScript objects, rather than using functions from the library itself before initializing it, which seemed a bit convoluted to me.

@cmacq2, again, my apologies for having broken your code. Might be a good time for a few simplications though, what do you think ? `Object.assign` or simple object extensions look like valid options IMHO.

Cheers!

**Comment by cmacq2** [comment]
@phsultan 

While you do raise valid points w.r.t. API, we should also consider the question: what about `Janus.useOldDependencies()`, i.e. the JQuery fallback option.

Basically the current API is the result of trying very hard to stay as backwards compatible as possible whilst decoupling `janus.js` from its dependencies somewhat.

**Comment by cmacq2** [comment]
Also, technically you *could* monkey-patch the `Janus` object itself after `Janus.init()` has been called. It is JavaScript and these are simple properties on the `Janus` function so you can reassign them. 

But I don't think that would result in altogether cleaner code.

**Comment by phsultan** [comment]
`Object.assign` ([ES6, or ECMAScript 2015](https://www.ecma-international.org/ecma-262/6.0/index.html#sec-object.assign)) is now [widely supported](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Browser_compatibility) and it is used as well in `adapter.js`, but any other object extension method would be fine to apply default options while allowing the developer to merge its own opts.

Guys, the changes I made are simple enough to revert them from the current `Janus.js`. I guess we have time to think about this kind of changes in future releases.

I can provide a patch by the beginning of next week if that helps, after all, I was the one who came up with code that did not match with what's documented :-D. Just ping me if needed.

**Comment by phsultan** [comment]
Here is a diff that reverts the code I proposed and matches with what's documented:

```
diff --git a/html/janus.js b/html/janus.js
index 9b36dc0..428f657 100644
--- a/html/janus.js
+++ b/html/janus.js
@@ -91,7 +91,7 @@ Janus.useDefaultDependencies = function (deps) {
                newWebSocket: function(server, proto) { return new socketCls(server, proto); },
                extension: (deps && deps.extension) || defaultExtension,
                isArray: function(arr) { return Array.isArray(arr); },
-               webRTCAdapter: (deps && deps.webRTCAdapter) || adapter,
+               webRTCAdapter: (deps && deps.adapter) || adapter,
                httpAPICall: function(url, options) {
                        var fetchOptions = {
                                method: options.verb,
@@ -160,7 +160,7 @@ Janus.useOldDependencies = function (deps) {
                newWebSocket: function(server, proto) { return new socketCls(server, proto); },
                isArray: function(arr) { return jq.isArray(arr); },
                extension: (deps && deps.extension) || defaultExtension,
-               webRTCAdapter: (deps && deps.webRTCAdapter) || adapter,
+               webRTCAdapter: (deps && deps.adapter) || adapter,
                httpAPICall: function(url, options) {
                        var payload = options.body !== undefined ? {
                                contentType: 'application/json',
@@ -247,16 +247,7 @@ Janus.init = function(options) {
                }
                Janus.log("Initializing library");
 
-               var usedDependencies = null;
-               if(!options.dependencies || !options.dependencies.isArray ||
-                               !options.dependencies.webRTCAdapter || !options.dependencies.httpAPICall ||
-                               !options.dependencies.extension || !options.dependencies.newWebSocket) {
-                       // Not all dependencies have been overridden: use the default ones as a basis
-                       usedDependencies = Janus.useDefaultDependencies(options.dependencies);
-               } else {
-                       // This is a complete replacement of the dependencies
-                       usedDependencies = options.dependencies;
-               }
+               var usedDependencies = options.dependencies || Janus.useDefaultDependencies();
                Janus.isArray = usedDependencies.isArray;
                Janus.webRTCAdapter = usedDependencies.webRTCAdapter;
                Janus.httpAPICall = usedDependencies.httpAPICall;
```

I tested it, and made sure the `extension` property introduced in https://github.com/meetecho/janus-gateway/pull/1236 was populated, as this PR had been merged afterwards. Might be good if @s-ol could confirm that this new patch does not break his code though.

Let me know if I can help any further!

**Comment by lminiero** [comment]
@phsultan can you submit that as a PR?

**Comment by phsultan** [comment]
Sure, will do.
