### ISSUE TITLE
segfault in Text Room in Chromium

### ISSUE THREAD

**Issue by maltfield** [meetecho/janus-gateway#1233]
Hello,

Janus crashes with a segmentation fault when I attempt to connect to the Text Room demo on my server from Chromium.

Janus is v0.4.0 running on centos7 in aws ec2 on a t2.micro. Chromium is v57.0.2987.98 running on debian 9.

```
[root@ip-172-31-28-115 janus-gateway]# date
Mon May 14 16:47:12 UTC 2018
[root@ip-172-31-28-115 janus-gateway]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.5 (Maipo)
[root@ip-172-31-28-115 janus-gateway]# uname -a
Linux ip-172-31-28-115.us-west-2.compute.internal 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@ip-172-31-28-115 janus-gateway]# /opt/janus/bin/janus --version
Janus commit: d8da250294cbdc193252ce059ef281ba0e2ff5bd
Compiled on:  Mon May 14 16:09:15 UTC 2018

janus 0.4.0
[root@ip-172-31-28-115 janus-gateway]# 
```
Here are the steps I used to compile Janus:

```
# install epel
yum -y install epel-release

# install other depends, per the documentation
yum -y install libmicrohttpd-devel jansson-devel libnice-devel openssl-devel libsrtp-devel sofia-sip-devel glib-devel opus-devel libogg-devel libcurl-devel lua-devel pkgconfig gengetopt libtool autoconf automake

# install other depends, per my discovery of their necessity
yum -y install glibc2-devel
yum --enablerepo=* -y install libnice-devel jansson-devel lua-devel

# install usrsctp for Data Channels support (ie: text chat)
pushd /root/sandbox
git clone https://github.com/sctplab/usrsctp
pushd usrsctp
./bootstrap
./configure
make
make install
popd
popd

# add lib dir
cat << EOF > /etc/ld.so.conf.d/janus.conf
/usr/lib
/usr/local/lib
/opt/janus/lib/janus/plugins
EOF
ldconfig

# get & compile janus gateway
mkdir -p $HOME/sandbox
pushd $HOME/sandbox
git clone https://github.com/meetecho/janus-gateway.git
cd janus-gateway
sh autogen.sh

./configure --prefix=/opt/janus
make
make install
make configs
```

Here's the output from the janus server at highest verbosity (7) from start to segfault:

 * https://gist.github.com/maltfield/7446642ff77e3bef8fbf2c24c4f60ef7

The core dump is 245M. I can provide it if needed, just let me know where/how to upload it..

**Comment by lminiero** [comment]
Logs won't help, and your core dump won't either, as those are specific to the setup that created them (your installation). Please collect a gdb stacktrace instead, or use libasan to see if you can get more info: https://janus.conf.meetecho.com/docs/debug
Of course, don't post the results inline, but in a gist/pastebin/whatever.

**Comment by maltfield** [comment]
Alrighty, here's the backtrace from gdb:

 * https://pastebin.com/twubmaeT

**Comment by lminiero** [comment]
It doesn't look like you're using master, line numbers don't patch. Apparently it's the same issue as #1223, which we already patched.

**Comment by maltfield** [comment]
hmm, ok, I'll try a git pull & compile again.

fwiw, here's the output when I compiled-in the Address Sanitizer

 * https://pastebin.com/aMSSpEcp

**Comment by maltfield** [comment]
ok, I confirmed that janus no longer segfaults, but the text room is not working in chromium. It connects to the gateway & prompts me for my username. But after I type the username & click "Join the room", it hangs. The developer console shows this:

```
Sending string on data channel: {"textroom":"join","transaction":"lExD06IWN0On","room":1234,"username":"vJQZF6EL1Lln","display":"foo"}

janus.js:1275 Uncaught TypeError: Cannot read property 'send' of null
    at sendData (janus.js:1275)
    at Object.data (janus.js:1076)
    at HTMLButtonElement.registerUsername (textroomtest.js:316)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.i (jquery.min.js:3)
sendData	@	janus.js:1275
data	@	janus.js:1076
registerUsername	@	textroomtest.js:316
dispatch	@	jquery.min.js:3
i	@	jquery.min.js:3
```

This is isolated to Chromium; it works fine in Firefox.

I tried to connect to Meetecho's demo to see if it was just my server, but I was getting gateway connection issues there = "Lost connection to the gateway (is it down?)"

 * https://janus.conf.meetecho.com/textroomtest.html

**Comment by lminiero** [comment]
Our online demos server was probably outdated too, I just updated it.

My guess is that for datachannel-only PeerConnections Chromium is not passing an SRTP profile in the DTLS handshake, which other browsers (Chrome included) do: with master you should see a failure where before you had the crash. In that case, you're getting the exception because the connection was torn down as a result of a failed setup (before that you should see info on the PeerConnection being removed).

**Comment by lminiero** [comment]
To check if datachannels are working in general, you can try the EchoTest demo.

**Comment by lminiero** [comment]
Just installed Chromium in my Fedora and can't replicate the issue there either.

**Comment by maltfield** [comment]
Hey Lorenzo,

Thanks for updating your site. I confirmed that my Chromium browser also has this issue on your site:

 * https://janus.conf.meetecho.com/textroomtest.html

I'm using Chromium "Version 57.0.2987.98 Built on 8.7, running on Debian 9.4 (64-bit)" on debian 9:

```
user@conferences:~$ uname -a
Linux conferences 4.9.56-21.pvops.qubes.x86_64 #1 SMP Tue Oct 17 23:58:50 UTC 2017 x86_64 GNU/Linux
user@conferences:~$ dpkg -l | grep -i chromium
ii  chromium                                                    57.0.2987.98-1~deb8u1                       amd64        web browser
user@conferences:~$ 
```

The page loads fine. I click "Start", and them I'm presented with an input to "Choose a display name". I type it and click "Join the room". Immediately after, 2 things happen: (1) the "Join the room" button goes grey and (2) this message pop-sup into the developer console:

```
janus.js:1275 Uncaught TypeError: Cannot read property 'send' of null
    at sendData (janus.js:1275)
    at Object.data (janus.js:1076)
    at HTMLButtonElement.registerUsername (textroomtest.js:322)
    at HTMLButtonElement.dispatch (jquery.min.js:3)
    at HTMLButtonElement.i (jquery.min.js:3)
```

There is no further action. The greyed-out prompt remains on the screen for my nickname. The room never loads. I do, however, see keepalives pop-up into the dev console..

**Comment by lminiero** [comment]
I don't use Debian, and the Chromium that ships with Fedora is 63.x, so can't test this myself sorry.

**Comment by lminiero** [comment]
Pinging @atoppi who I think uses Ubuntu, so the Chromium version there may be closer to yours.

**Comment by maltfield** [comment]
I tried the Echo Test demo in the same browser using your server:

 * https://janus.conf.meetecho.com/echotest.html

And I confirmed that data channels *is* working.

**Comment by maltfield** [comment]
ok, so long as the segfault is fixed I'm pretty happy. Unfortunately, I think debian 9 chromium users are going to be around for a while. But at least firefox works.

Thanks for your prompt responses! Feel free to close this issue.

**Comment by lminiero** [comment]
Ack, closing then!
