### ISSUE TITLE
lock-order-inversion (potential deadlock) in videoroom plugin

### ISSUE THREAD

**Issue by fancycode** [meetecho/janus-gateway#1239]
There is a lock-order inversion in the code paths for joining a room and deleting it with the locks `rooms_mutex` and `videoroom->mutex`. If you are unlucky, this could result in a deadlock between the videoroom handler thread and the pool thread.

First codepath (`rooms_mutex` before `videoroom->mutex` in videoroom handler thread):
https://github.com/meetecho/janus-gateway/blob/3cab7362d54d20c952a7b50d2c77e707d35c3f41/plugins/janus_videoroom.c#L2937
https://github.com/meetecho/janus-gateway/blob/3cab7362d54d20c952a7b50d2c77e707d35c3f41/plugins/janus_videoroom.c#L2954

Second codepath (`videoroom->mutex` before `rooms_mutex` in pool thread):
https://github.com/meetecho/janus-gateway/blob/3cab7362d54d20c952a7b50d2c77e707d35c3f41/plugins/janus_videoroom.c#L4416
https://github.com/meetecho/janus-gateway/blob/3cab7362d54d20c952a7b50d2c77e707d35c3f41/plugins/janus_videoroom.c#L4569
https://github.com/meetecho/janus-gateway/blob/3cab7362d54d20c952a7b50d2c77e707d35c3f41/plugins/janus_videoroom.c#L2113

**Comment by lminiero** [comment]
Thanks for the heads up, we'll have a look at that as soon as we have some time! :+1:

**Comment by lminiero** [comment]
Apparently, as you pointed out, the main problem is that `janus_videoroom_participant_joining` locks the global `rooms_mutex`, causing the inversion: this was introduced a couple of months ago in https://github.com/meetecho/janus-gateway/commit/f788ecc321040b4a6c86e33998f99df35c11e4f0, I believe to address some issues where participants might be joining a room while it was being destroyed.

I agree that this is an issue, and I don't think `janus_videoroom_participant_joining` should do any such check: we already verified if the room existed at that point (we do that when first processing the request), which means we should ensure the room is still valid some other way (e.g., using the room mutex, or whatever protects the room when destroying it as well). I'll see how easy that is.

**Comment by lminiero** [comment]
I ended up removing the check, and anticipated the use of the room mutex. In fact, the room mutex is used to protect the moment when the `room` property for each participant is set to NULL when destroying a room, and since the same room mutex wraps, among other methods, `janus_videoroom_participant_joining` as well, there's no need to check if the room is valid or not.
