### ISSUE TITLE
Data channel not named "JanusDataChannel" or length 16 bytes will fail 

### ISSUE THREAD

**Issue by yultide** [meetecho/janus-gateway#124]
The culprit is here.
sctp.c:911
			switch (msg->msg_type) {
				case DATA_CHANNEL_OPEN_REQUEST:
					if(length < sizeof(janus_datachannel_open_request)) {
						// XXX: error handling?
						return;
					}

To reproduce, try changing "JanusDataChannel" in janus.js to something smaller like "janus"

**Comment by lminiero** [comment]
Let me know if that fixes it for you.

**Comment by lminiero** [comment]
Assuming it was fixed for lack of feedback (works for me).

**Comment by kirillt** [comment]
Is it fixed? DataChannels named differently don't work for me.
Only this works:
```
this.peerConnection.createDataChannel("JanusDataChannel", ...);
```
