### ISSUE TITLE
Segfault when queueing outgoing SCTP messages

### ISSUE THREAD

**Issue by mquander** [meetecho/janus-gateway#1247]
Ubuntu 17.10, Janus commit 4053b20baba6ec1b912e6d9e3889f931995cb214 (recent master).

Janus crashed with the following stack. I think this is what you would expect if it tried to push to the outgoing SCTP message queue after the queue's mutex was freed.

I can see a way that this could have happened if there were a race between [`janus_sctp_association_free`](https://github.com/meetecho/janus-gateway/blob/4053b20baba6ec1b912e6d9e3889f931995cb214/sctp.c#L124) and [`janus_sctp_data_to_dtls`](https://github.com/meetecho/janus-gateway/blob/4053b20baba6ec1b912e6d9e3889f931995cb214/sctp.c#L330). However, there shouldn't be a very big time window for that to happen, so it seems unlikely -- maybe there is a different problem?

I may try to reproduce this race with some strategic sleeping.

GDB backtrace:
```
#0  0x00007f282eedd11c in g_mutex_lock () from /hab/pkgs/core/glib/2.50.3/20180416191835/lib/libglib-2.0.so.0
#1  0x00007f282ee52e40 in g_async_queue_push () from /hab/pkgs/core/glib/2.50.3/20180416191835/lib/libglib-2.0.so.0
#2  0x0000000000472ded in janus_sctp_data_to_dtls (instance=0x7f2744d04800, buffer=0x7f27e4003460, length=56, tos=0 '\000', set_df=1 '\001')
    at sctp.c:331
#3  0x00007f282d4471e0 in ?? () from /hab/pkgs/mozillareality/usrsctp/0.9.4.0/20170923224507/lib/libusrsctp.so.1
#4  0x00007f282d452c1b in ?? () from /hab/pkgs/mozillareality/usrsctp/0.9.4.0/20170923224507/lib/libusrsctp.so.1
#5  0x00007f282d4564c0 in sctp_chunk_output () from /hab/pkgs/mozillareality/usrsctp/0.9.4.0/20170923224507/lib/libusrsctp.so.1
#6  0x00007f282d494dae in sctp_timeout_handler () from /hab/pkgs/mozillareality/usrsctp/0.9.4.0/20170923224507/lib/libusrsctp.so.1
#7  0x00007f282d41bd24 in ?? () from /hab/pkgs/mozillareality/usrsctp/0.9.4.0/20170923224507/lib/libusrsctp.so.1
#8  0x00007f282d41be27 in user_sctp_timer_iterate () from /hab/pkgs/mozillareality/usrsctp/0.9.4.0/20170923224507/lib/libusrsctp.so.1
#9  0x00007f282e6ac434 in ?? () from /hab/pkgs/core/glibc/2.22/20170513201042/lib/libpthread.so.0
#10 0x00007f282d13bdfd in clone () from /hab/pkgs/core/glibc/2.22/20170513201042/lib/libc.so.6
```

**Comment by lminiero** [comment]
I'm pretty sure that this is one of the things #1243 solves. In that PR, @fancycode made sure that when we're destroying the SCTP stack, we also join the SCTP thread until it leaves: this way, it can never generate packets after the queue is gone.

**Comment by lminiero** [comment]
PS: you may be interested in testing #1250 too, especially if you care about datachannels.

**Comment by lminiero** [comment]
@mquander can you let me know if this still happens on master as well, now that we merged the PR I referenced?

**Comment by mquander** [comment]
Yes, I'll upgrade our installation soon and then let you know if this recurs.

**Comment by lminiero** [comment]
Any news on this?

**Comment by mquander** [comment]
No sign of any problem in the past week, although this only happened the once to me so the fact that it hasn't happened again isn't that much evidence. But you should close it if you want and I'll reopen if it ever recurs.

**Comment by lminiero** [comment]
Closing for the time being then. Feel free to reopen if it turns out to still be an issue.
