### ISSUE TITLE
Echo test without IP leak?

### ISSUE THREAD

**Issue by mckea** [meetecho/janus-gateway#1253]
I'm using Firefox 60 with media.peerconnection.ice.proxy_only set to true to prevent IP leak (I'm using a socks5 proxy).

The echo test (https://janus.conf.meetecho.com/echotest.html) does not work under these conditions.  If I change the above setting to false, it works - but my IP leaks.

Is the echo test expected to work without IP leak?

**Comment by lminiero** [comment]
The online demo doesn't configure TURN servers on the browser side, so it's likely that it's not working for that reason. Anyway, this is a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), we only use github for code issues. Closing.
