### ISSUE TITLE
SIP Call fails after previous one is rejected

### ISSUE THREAD

**Issue by andresico** [meetecho/janus-gateway#1259]
Debian GNU/Linux 8.6 (jessie)
Google Chrome Versión 66.0.3359.181 (Build oficial) (64 bits)
Janus 0.4.1

Using Janus SIP plugin, I'm placing a call like that:

{
	"message":{
		"request":"call",
		"uri":**<intentionally removed>**
	},
	"jsep":{
		"type":"offer",
		"sdp": **<intentionally removed>**
	}
}

From Janus I receive these messages:
{"sip":"event","result":{"event":"ringing"}}
{"sip":"event","result":{"event":"proceeding","code":180}}
{"sip":"event","result":{"event":"ringing"}}
{"sip":"event","result":{"event":"proceeding","code":180}}
{"sip":"event","result":{"event":"hangup","code":486,"reason":"Busy Here"}}

Everything is ok since remote peer intentionally rejects the call. After that, everytime I try to place another call I receive this response:

Ooops: 471 Still cleaning a previous session

This also happens with incoming calls after one call is rejected. There is no problem if the call is accepted.

**Comment by andresico** [comment]
I have waited more than a minute to avoid calling while Janus is cleaning the previous connection.

This is what Janus shows in its logs:
[Wed May 30 11:11:15 2018] Got a Janus API request from janus.transport.http (0x7fa658001e80)
[Wed May 30 11:11:15 2018] [ERR] [janus.c:janus_process_incoming_request:1384] [2053225646888126] Received a trickle, but still cleaning a previous session
[Wed May 30 11:11:15 2018] [fAPuJbOBNZ9U] Returning Janus API error 471 (Still cleaning a previous session)

**Comment by lminiero** [comment]
Can you share (in a pastebin/gist, not inline) the content of the Admin API info for that handle after the call is refused and before you try again? http://www.meetecho.com/blog/understanding-the-janus-admin-api/
Besides, what's the CPU usage of Janus at that stage? (trying to understand if the ICE loop is stuck in you case, and thus not freeing resources as it should).

**Comment by lminiero** [comment]
Nevermind that, I managed to reproduce your issue locally, and I think I found out the problem: we were never quitting the ICE loop if ICE never succeeded (the "quit loop" directive was in the "get rid of the outgoing traffic source" code, but in your case that source had not been created due to the failure). Closing, please let me know if it's still an issue.

**Comment by andresico** [comment]
Everything is working fine with that fix. Thank you very much!
