### ISSUE TITLE
Din't get mediaState/webrtcState off events on listeners in videoRoom.

### ISSUE THREAD

**Issue by vahidov** [meetecho/janus-gateway#1268]
Version 0.4.1.

In videoroom we have only one publisher and many listeners. If publisher has problem with internet or call hangup/detach to SFU - listeners must get event in mediaState and webrtcState callbacks about stop receiving media. It's work on 0.3.1 version, but not working on 0.4.1/today master(0.4.2). Tested on websockets and http.

Start publisher in videoRoom. Connect another as subscriber. 
```
//Publisher starts 
[Tue Jun  5 13:44:18 2018] Creating new session: 113776618417766; 0x7f2f60031120
[Tue Jun  5 13:44:19 2018] Creating new handle in session 113776618417766: 8411871925030316; 0x7f2f60031120 0x7f2f60068c00
[Tue Jun  5 13:44:19 2018] [8411871925030316] Creating ICE agent (ICE Full mode, controlled)
[Tue Jun  5 13:44:20 2018] [WARN] [8411871925030316]     Missing valid SRTP session (packet arrived too early?), skipping...
[Tue Jun  5 13:44:20 2018] [8411871925030316] The DTLS handshake has been completed
[Tue Jun  5 13:44:20 2018] [janus.plugin.videoroom-0x7f2f6001ef20] WebRTC media is now available

//Listener start
[Tue Jun  5 13:44:39 2018] Creating new session: 4452501067203586; 0x7f2f6002fb40
[Tue Jun  5 13:44:39 2018] Creating new handle in session 4452501067203586: 679878884249087; 0x7f2f6002fb40 0x7f2f6000a600
[Tue Jun  5 13:44:39 2018] [679878884249087] Creating ICE agent (ICE Full mode, controlling)
[Tue Jun  5 13:44:40 2018] [WARN] [679878884249087]     Missing valid SRTP session (packet arrived too early?), skipping...
[Tue Jun  5 13:44:40 2018] [679878884249087] The DTLS handshake has been completed
[Tue Jun  5 13:44:40 2018] [janus.plugin.videoroom-0x7f2f60044cb0] WebRTC media is now available

//make hangup/destroy on publisher
[Tue Jun  5 13:45:08 2018] [janus.plugin.videoroom-0x7f2f6001ef20] No WebRTC media anymore; 0x7f2f60068c00 0x7f2f60030680
[Tue Jun  5 13:45:08 2018] Detaching handle from JANUS VideoRoom plugin; 0x7f2f60068c00 0x7f2f6001ef20 0x7f2f60068c00 0x7f2f60030680
[Tue Jun  5 13:45:08 2018] [8411871925030316] WebRTC resources freed; 0x7f2f60068c00 0x7f2f60031120
[Tue Jun  5 13:45:08 2018] [8411871925030316] WebRTC resources freed; 0x7f2f60068c00 0x7f2f60031120
[Tue Jun  5 13:45:08 2018] [8411871925030316] Handle and related resources freed; 0x7f2f60068c00 0x7f2f60031120
```

And listener is still on janus connection, video is freezing, but connect still work. Handle not freeing and listener handle info (after publisher hangup/destroy) get this data - https://pastebin.com/hgkJjBLy

Videoroom params:
```
{  
   "room":111,
   "secret":"secret",
   "is_private":false,
   "pin":"masterPin",
   "publishers":1,
   "bitrate":128000,
   "fir_freq":1,
   "audiocodec":"opus",
   "videocodec":"h264",
   "audiolevel_ext":false,
   "audiolevel_event":false,
   "permanent":false,
   "notify_joining":false
}
```

**Comment by vahidov** [comment]
log after hangup with additional data
```
[Tue Jun  5 14:15:29 2018] Got a Janus API request from janus.transport.websockets (0x7fa638002ff0)
[Tue Jun  5 14:15:29 2018] [4927948798184483] Telling the plugin about the hangup because of a Detach (JANUS VideoRoom plugin)
[Tue Jun  5 14:15:29 2018] [janus.plugin.videoroom-0x7fa63c059060] No WebRTC media anymore; 0x7fa63c0046b0 0x7fa63c002600
[Tue Jun  5 14:15:29 2018] Detaching handle from JANUS VideoRoom plugin; 0x7fa63c0046b0 0x7fa63c059060 0x7fa63c0046b0 0x7fa63c002600
[Tue Jun  5 14:15:29 2018] [4927948798184483] Sending event to transport...; 0x7fa63c0046b0
[Tue Jun  5 14:15:29 2018] [4927948798184483] Handle detached (error=0), scheduling destruction
[Tue Jun  5 14:15:29 2018] [4927948798184483] DTLS alert triggered on stream 1 (component 1), closing...
[Tue Jun  5 14:15:29 2018] [4927948798184483] ICE thread quit ICE loop 0x7fa63c0046b0
[Tue Jun  5 14:15:29 2018] [4927948798184483] WebRTC resources freed; 0x7fa63c0046b0 0x7fa63c001ed0
[Tue Jun  5 14:15:29 2018] [4927948798184483] ICE thread ended! 0x7fa63c0046b0
[Tue Jun  5 14:15:29 2018] [4927948798184483] WebRTC resources freed; 0x7fa63c0046b0 0x7fa63c001ed0
[Tue Jun  5 14:15:29 2018] [4927948798184483] Handle and related resources freed; 0x7fa63c0046b0 0x7fa63c001ed0
```

**Comment by lminiero** [comment]
I think you misunderstand what `mediaState` and `webrtcState` are about.

The `mediaState` callback is notified when you get a `"media"` event from Janus, which as explained in the documentation is sent when Janus receives (or stops receiving) media frorm a specific user: since listeners never send anything, it's clear they never get a `mediaState` event (publishers do, instead).

The `webrtcState` callback, instead, is fired when a PeerConnection goes up or down. In your case, this refers to a specific listener's PeerConnection, which has nothing to do with what happens on the publisher's side: while they're logically related by the VideoRoom plugin, they're different PeerConnections, and have different lifes. You can configure the plugin to tear down a listener PeerConnection when a publisher goes away, while others may prefer to keep it alive (e.g., to allow for switching). As such, you most definitely can't wait for a `webrtcState` change there, which is only needed to track the lifecycle of that individual PeerConnection.

For what you want, you need to track the VideoRoom plugin signalling instead. If a publisher goes away (no matter how), the plugin will tell your viewers, so that's what you should intercept.

Closing as not an issue.

**Comment by vahidov** [comment]
@lminiero 
I'm told that Janus not signalling to listener about cancelling publisher connection. You say, that videoroom plugin tell something about this situation to client. How to get this signal? 

And what about destroying listener handle? If client is connected to videoroom and publisher stop publishing I see active listener handle, connected to Janus and listener didn't get any information about this situation. There are no messages in onmessage, for example, etc.

The listener's behavior is "that the connection is active, everything is ok". But in fact the handle should already be broken, isn't it?

Thanks.

**Comment by lminiero** [comment]
These questions are for the group, so please post it there. We only use GitHub for code issue, and this is not an issue.
