### ISSUE TITLE
Proposal for using strings for identifyers

### ISSUE THREAD

**Issue by peffis** [meetecho/janus-gateway#1269]
Room IDs and user IDs in Janus plugins videoroom and audiobridge (and possibly other plugins, but these are the ones I have been using) typically have an integer type. When integrating Janus with other systems I usually end up having to map some external room ID and user ID, which comes in the form of a string, to the Janus integer identifiers before communicating with Janus. This is inconvenient as it adds an unneeded mapping table to the system but it also makes traceability more difficult when you compare activities in janus log files with activities in the external system's log files because users and rooms will end up having two representations - one in the external system and one inside janus. 

My question is: Would there be any interest in accepting a series of pull requests that change the type of all integer identifiers in applicable janus plugins to string identifiers? It would have implications on the API:s and therefore will break things for people, so I would understand if this change is not wanted, but in my opinion, having identifiers as strings rather than integers would make life easier for people to integrate janus into other services where often strings (such as UUID's or other forms) are used for identifiers.

**Comment by lminiero** [comment]
This has been discussed in the past and I've always refused them, because they would break compatibility with all apps in the wild out there. That said, please open this kind of discussions on the group, as we only use Github for code issues.
