### ISSUE TITLE
videoroom plugin: failure to unpause a video subscription after a long pause period

### ISSUE THREAD

**Issue by flaviogrossi** [meetecho/janus-gateway#1273]
If a videoroom subscriber pauses the media delivery from some publisher (using the `pause` and `start` requests) and then resumes it after a long period (more than an hour to give an idea), the following errors are printed

```
[ERR] [ice.c:janus_ice_send_thread:3820] [4826320804355368] ... SRTP protect error... err_status_replay_old (len=107-->107, ts=315603840, seq=1075)
```

and the received video stream is not restored.

I think this is related to #620, and resetting sequence numbers after the start method like this:

```c
subscriber->context.v_seq_reset = TRUE;
```

seems to fix it.

**Comment by lminiero** [comment]
Good catch! I think your suggestion doesn't apply to `pause` and `start` alone, but also to the subscriber `configure` requests, where you can temporarily disable/enable audio/video/data separately, and so act as more fine grained pause/start requests (which act on all the media instead). I'll take note of this for an upcoming fix.

**Comment by lminiero** [comment]
@flaviogrossi can you let me know if the above commit fixes it for you?

**Comment by flaviogrossi** [comment]
it works fine, thanks.
