### ISSUE TITLE
Locked websocket - transport mutex is being held

### ISSUE THREAD

**Issue by peffis** [meetecho/janus-gateway#1274]
I'm on latest janus master with libwebsockets  v2.4-stable built with LWS_MAX_SMP=1. After some usage time the websocket interface is locked and all request attempts will timeout. After enabling the lock_logging I see that there is one lock still taken and it's the one on transports/janus_websockets.c:janus_websockets_send_message:804:lock ( https://github.com/meetecho/janus-gateway/blob/02a105a60cda41c1feea6ed1517f22778cb4cc51/transports/janus_websockets.c#L804)

I do not understand what could make it keep holding on to that mutex in the coming lines as I am not familiar with how for instance lws_callback_on_writable works, but my use case is a use case when users come and go and might not close or leave the rooms in a clean way, so one of the reasons might be that there could still be references to participants where the websocket connection might not still have a remote side which would make the attempt to send an event fail (or bllock?). But I don't know. Still early in the analysis of this one. I did not see this when running on older Janus commits though (such as from march this year).

**Comment by lminiero** [comment]
Just answered you on the other thread: https://github.com/meetecho/janus-gateway/issues/1263#issuecomment-396939105

**Comment by peffis** [comment]
I have some update for this, but first some background on how I run this as it might not be the usual setup: The browser clients does not connect to Janus directly, but they connect to a signalling server that in turn connect to Janus over websocket. There is one websocket connection per room between the signalling server and Janus so all the clients that connect to a room will be multiplexed over the websocket connection to Janus - a websocket connection therefore carries several janus sessions. 

What I saw happening now when I tested things further was that, when clients disconnected abruptly without destroying their session (nor the plugin handles it had created) the janus session would eventually time out in Janus. When the timeout would happen Janus would, for some reason, also close the websocket connection even-though there were other sessions still alive over this websocket connection. On the signal server side I saw a close coming in from Janus. This in turn would lead to a complete lock of the websocket interface when some of the still existing Janus sessions would then need to send out an event over the already closed websocket connection. After this send attempt happened, no new connections will be accepted on the websocket. I think libwebsocket gets stuck if you sit and wait for the socket to be ready for writing if the socket has already been closed or something.  

I don't know yet why this happens - why janus closes the websocket connection despite there being other existing live sessions that uses it - but what I could do to avoid the locking situation was to avoid the session timeout completely by detecting the abrupt disconnect by the client and then do a session destroy on the now invalid janus sessions before it times out. Even if this solves things for me at the moment I think there is still something wrong here in Janus. Since the websocket connection is shared among sessions there should be some reference counter to determine if the websocket connection should be destroyed at a session timeout or not. Perhaps there is already and that it is just counting wrongly (such as decrementing twice sometimes?). I don't know. Since my problems are solved with the work around to always avoid the session timeout it will take time before I analyze this further I think. 

Worth noting is also that this type of websocket lock did not happen for me in the same situation for an earlier commit (from march this year). I'm not sure exactly when the reference counting was merged into master but perhaps it could be so that the reference counting merge somehow changed the logic when the websocket is closed and this is the reason why I did not see this in the earlier commit

**Comment by lminiero** [comment]
> When the timeout would happen Janus would, for some reason, also close the websocket connection even-though there were other sessions still alive over this websocket connection

That's how Janus is conceived to work right now. When a session timeout detection is detected, the core clears the session notifies the related transport plugin; as such, the timeout mechanism is a way to ensure we don't have leaks. Some plugins have a persistent connection and won't care (MQTT and RabbitMQ for instance), while those that can handle multiple clients treat this info as fatal. This includes the WebSocket transport plugin, which doesn't have a built-in timeout "monitor", and so trusts the core on that.

You make a good point saying that if other sessions are going fine, it's overkill to kill the connection for that single session that timed out. This means that we should build some smarter logic in transport plugins as well, so that they can make more informed decisions on how to treat a "timeout" notification from the core (e.g., got a timeout, but also got incoming data 5 seconds ago, ignore). This also means that these transports will have to have their own timeout monitor, though, which is going to be annoying to work on (I don't like the idea of yet another thread). Adding to the TODO list but honestly not sure when that will happen: in the meanwhile, your hack is a good patch; as an alternative, injecting keepalive messages for sessions you're handling through your proxy may help.

**Comment by peffis** [comment]
I am keeping session alive through the proxy, but when the clients disconnect from the proxy I stop keeping those "dead" sessions alive which caused this problem. I guess my assumption was that, since you are allowed to create several sessions on one connection the lifetime of the connection itself would not be affected by the lifetime of the sessions, and definitely not affected by the shortest life-time of any of the sessions which is true here. I guess I assumed that, if Janus is going to close the connection, it's gonna be when all the sessions are over and not when one session times out.  

I guess I would've preferred a solution here that completely disconnects the websocket connection from the lifetime of the sessions so that the websocket is kept alive as long as there is no ping-ponging timeout, but I guess other transports might have harder to clean things up and might require this dependency to session lifetime as a way to shut things down, so I understand if this is not a general solution. 

Anyway, I'm closing this issue with the note to others that, if you share a websocket connection among sessions you currently risk locking the entire websocket interface if one session times out while others are kept alive. A workaround is either to keep all sessions that share the websocket connection alive (with a keep_alive message) at all times or to explicitly destroy sessions that you no longer need before they time out.

**Comment by lminiero** [comment]
I've taken note of this as a TODO, in order to handle this more properly in the future. There are several things to be wary of if we switch approach, so we'll have to be careful.

**Comment by peffis** [comment]
(not to mention that it is a risk that, if Janus has its websocket port open on the Internet, which some people have, that ill-mannered people can connect, create two sessions on one connection, have one of them timeout...and leave you with a useless Janus instance - a very simple DoS attack :))

**Comment by lminiero** [comment]
Wait, we're talking of different issues, here. One is the fact that we close the connection if a session times out, even though others are just fine: this is annoying, but not a DoS attack (unless you proxy connections using a single WebSocket channel as you do).

If a timeout causes a deadlock in the WebSocket transport (or in how the core handles those), instead, it's a completely different problem, and one that we should indeed fix soon. Is this what's happening to you? Did you collect some info using that lock "crawler" we mentioned in previous exchanges? If so, we should keep this issue open, as this would need to be fixed no matter what.

**Comment by lminiero** [comment]
I just tested multiple session timeouts with WebSockets and I didn't get any lock, though.

**Comment by peffis** [comment]
Yes, perhaps I am not clear enough. The fact that one session timeout closes the connection will make the entire websocket transport lock-up if one of the remaining sessions that share that connection will do something that will generate a message over the closed transport (such as a webrtcup, or other error). When this happens it seems that libwebsocket will lockup waiting for the socket to be ready for write and it won't accept new incoming connections. So the fact that one timeout can close a connection that other sessions later might try to use is a serious problem which can probably, but I admit that I speculate here, probably be done just with one websocket connection from a browser if you just create two sessions in the same websocket connection. 

I don't know if this is easy to reproduce though. There could be some timing issue involved as well...and perhaps libwebsocket version aspects (I'm on 2.4-stable). But in order to lock it there has to be some session that tries to use the closed connection.

**Comment by peffis** [comment]
But I also recall places in that code that checks to see if the websocket connection is closed, so perhaps it's a race condition needed as well - that the timeout, and close, coincides with the other session attempting to use the websocket connection.

**Comment by peffis** [comment]
The output of the log crawler showed me the that the lock acquired in the line shown in the first message in this thread, was still held. Which makes me think that https://github.com/meetecho/janus-gateway/blob/02a105a60cda41c1feea6ed1517f22778cb4cc51/transports/janus_websockets.c#L814 might be where it gets a problem if the websocket connection was closed at the same time.

**Comment by lminiero** [comment]
`lws_callback_on_writable` is not blocking IIRC, though: at least, I remember discussing this method some time ago with one of the libwebsockets developers, but I don't remember what it led to. Anyway, let's reopen this issue to track the deadlock problem.

**Comment by lminiero** [comment]
That said, have you checked if your libwebsockets instance is compiled with `LWS_MAX_SMP=1` as suggested in #732? At the time we investigated a similar issue, and that's exactly where `lws_callback_on_writable` went under scrutiny as a possible cause of issues.

**Comment by lminiero** [comment]
Nevermind that... it's the first thing you wrote in the issue :slightly_smiling_face:

**Comment by peffis** [comment]
Ah, nice! That sounds like a nice commit. I'll check it out (I will have to change back my proxy code though so it leaves these sessions in there to timeout, but I'll do it later today or tomorrow)

**Comment by peffis** [comment]
I tried it now, with changed-back code (on my side - that let unused sessions time out), with some medium load where clients come and go. Before I used to be able to provoke this lock almost instantly. It has not yet (after 30 minutes) locked on me with the new commit...which I guess is expected since the commit removes the problematic operation. So all is fine as I can tell. Thanks!

**Comment by lminiero** [comment]
Closing then, feel free to reopen if it reappears.

**Comment by lcnssantos** [comment]
I'm facing a situation that I think it's related to this issue.
Basically, I've an application that uses WebSocket to control Janus. Aparently when the application creates a certain number of connections with Janus, the server stops to accept new connections. The connections already established are not affected, aparently.
We're using NodeJS v10.17.0 with ws library (https://www.npmjs.com/package/ws) and when Janus stops to answer, we've a lot of errors with WebSocket connection (1006 - connection closed abnormally).
Currently, we're using one WebSocket connection for each room we created at Janus. I would like to know if it's the best practice or if the use of a message queue with a limited number of connections is a better practice.
We've an installation of Janus at an Ubutu 18.04 Machine hosted by Digital Ocean.
The installation uses the version v3.1 of libwebsockets.

**Comment by chengmo03013106** [comment]
> I'm facing a situation that I think it's related to this issue.
> Basically, I've an application that uses WebSocket to control Janus. Aparently when the application creates a certain number of connections with Janus, the server stops to accept new connections. The connections already established are not affected, aparently.

Excuse me:
May I have the number of "certain" of connections with Janus ? 
I have used LWS 3.1 as well.
