### ISSUE TITLE
Bandwidth limit not working on firefox

### ISSUE THREAD

**Issue by groupboard** [meetecho/janus-gateway#1277]
The bitrate limit seems to be having no effect on firefox, either in the echotest or videoroom pages, both on the meetecho demo server and our server. It works fine in this page, so I think there is an error in the janus implementation:

https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/

It looks like the REMB bitrate is having no effect for some reason, even though firefox does support REMB.

I managed to get it to limit the bitrate to the value specified in the room config by fixing a few bugs in plugins/janus_videoroom.c. This is good enough for us, although it still doesn't let the user change the bandwidth in the middle of the session:

In janus_videoroom.c, change:

`if(strstr(msg_sdp, "Mozilla")) {
`
to:

`if(strstr(msg_sdp, "mozilla")) {
`
(should be lower case M).

And replace:

```
m->b_name = g_strdup("AS");
m->b_value = (int)(videoroom->bitrate/1000);
```

with:

```
m->b_name = g_strdup("TIAS");
m->b_value = (int)(videoroom->bitrate);
```

(Firefox uses b=TIAS rather than b=AS, and the bitrate for TIAS is in bps rather than kbps).

**Comment by lminiero** [comment]
Just tried the EchoTest with an updated version of both Firefox 60 (stable) and 62 (nightly), and the bandwidth controls seem to be working just fine here.

**Comment by lminiero** [comment]
Notice that adapting to the bitrate might be slow, but it's definitely happening in my case.

**Comment by groupboard** [comment]
I'm using firefox 60 on a macbook pro. Resolution is at 1280x720. If I go to https://janus.conf.meetecho.com/echotest.html and change to 128kbps, even after a minute it's still at about 600kbps.

**Comment by groupboard** [comment]
Just tried Nightly (62) with the same result (capping to 128kbps had no effect...remote stream stayed at 600kbps).

**Comment by groupboard** [comment]
I tested on Windows 10 and it works fine, so it looks like it's an issue specific to either macOS, or the camera on the macbook pro.

**Comment by lminiero** [comment]
Closing as not a Janus issue, then.

**Comment by groupboard** [comment]
The issue is that Firefox doesn't always adjust bandwidth dynamically when receiving REMB packets:

https://bugzilla.mozilla.org/show_bug.cgi?id=1362456

I suspect it is because the Macbook pro camera only has one hardware resolution, and perhaps Firefox doesn't adjust the bandwidth in the case.

However, there are still some bugs in Janus (see my original comment) with the bandwidth negotiation in the SDP, and if those are fixed then the bitrate can be successfully set at the beginning of the session to the default bitrate of the room.

**Comment by lminiero** [comment]
> However, there are still some bugs in Janus (see my original comment) with the bandwidth negotiation in the SDP

Good point, thanks for reminding me: I'll make the changes you suggested and check if they don't break REMB (I want to make sure that a `b=` attribute doesn't act as an immutable cap that you can't change dynamically later on).

**Comment by lminiero** [comment]
Unfortunately, as I feared, when you set the `TIAS` stuff, Firefox ignores REMB for higher targets (going down is fine), which means the bitrate cap stays like that forever. As such, I can't just change it as it is. I'll have to add a new property to either the room creation or the publishers "publish" request to specify the bitrate is meant to be more static. First I'll have to check if Chrome honors `AS` the same way as Firefox dies with `TIAS` though.

**Comment by groupboard** [comment]
Good to know. From what I understand, chrome uses both TIAS and AS, and firefox only uses TIAS.

**Comment by lminiero** [comment]
AS seemed to work on Chrome so I sticked to that. The above commit adds a new boolean property you can set when creating a room, `bitrate_cap`: if set to `true`, then the `b=` attribute is set in response to publisher offers, and the bitrate limit acts as a strict upper bound; if set to `false` or missing (default), the bitrate limit is loose. Hope this helps with your specific use case.

**Comment by groupboard** [comment]
Thanks, the changes look good. I'll do some testing and report back.

**Comment by groupboard** [comment]
Change seems to be working well, thanks.
