### ISSUE TITLE
Got "Uncaught TypeError: Cannot read property 'readyState' of null" when hangup video call

### ISSUE THREAD

**Issue by fitraditya** [meetecho/janus-gateway#128]
Hi,

I always got an error "Uncaught TypeError: Cannot read property 'readyState' of null" (janus.js:935) when end / hangup video call. Is it a bug or did i something wrong?

Thank you.

**Comment by lminiero** [comment]
This line has nothing:

https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L935

Are you using an up-to-date version of the gateway and JavaScript stuff?

L.

**Comment by fitraditya** [comment]
Oh, I mean in line 958 (https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L958).
I remove addJs function in line 48, so i have different line number.

**Comment by lminiero** [comment]
Well nothing to worry about then. Closing the demo closes the data channel, and the datachannel property of config is likely null at that point. Adding a check before the console.log will fix it.
