### ISSUE TITLE
Pfunix connection client is broken when the session is over.

### ISSUE THREAD

**Issue by Globik** [meetecho/janus-gateway#1282]
I'm using pfunix transport plugin, sock_seqpacket type. Also I'm using sock_seqpacket client in node.js app. When session is over the connection pipe to janus pfunix transport is broken.
In the source code janus_pfunix.c you write:
FIXME Should we really close the connection in case of a timeout?
Yes, it should be fixed. I want to be online  with janus pfunix transport as long as my app is running. The Janus webrtc gateway's part should to clear a session, but not to close the current connection to the nodejs client. Some overhead is with a keepalive approach just because I've created a session, ok I created a session and  then after some time it is over, but what the mother is that the connection to my client socket should be closed? It breaks all functionality on my node.js side  with its sock_seqpacket client addon module.
I can't create a new session couz the janus pfunix transport closed the connection.
I can't on the fly reconnect to pfunix transport plugin couz it closed the connection. And couz my module bound to websocket with bunch of event listeners that can't be removed on the fly if client browser sockets are active.
Yes, I can use the keep alive requests to janus, but what the point of it if there are no user for the time being? OK, there is one user with created session, then comes another one to the website and creates his own session, but what if one of him not active and his session is over, janus gateway in this case clears not only his timeout session but closes also the main connection to the sock_seqpacket client(but there is another man exists successfully active) - what point of it?

Let's say on the website 100 users being active and no timeout sessions. If one of them is not active, janus clears those session and closes connection to nodejs seqpacket client socket, as such all 99 happy active users become unhappy becouse one user has broken all functionality on the site?
I don't want for each user open a new connect to pfunix transport, cause it's enough one connection from nodejs part to janus as a bridge.

**Comment by Globik** [comment]
Excuse me, unique id for current session? Hm... Not for user is this session? I see, I see. So I should  I think at nodejs run time - at start time -  I should very quickly after actual connection to pfunix transport  to create an unique session, then very quickly attach one plugin and be happy with it and be keep alive as long as my app is running. Aha, I see this point.
Should also to save this session unique id in a global variable on server side and be happy. OK, I'll try it. But what about each user unique id? Where is it?

**Comment by Globik** [comment]
I think as an answer for "keepalive", from the janus part there are must be to add an additional key: "keepalive: true". It is very complicated to know if janus "ack" value is actually answer for keepalive or it is an aswer for trickle success or what there else is there. Don't mix up the logic of "ack".

**Comment by lminiero** [comment]
Can you please try not to say the same thing over and over on different
channels? You just ranted on the group: we got it.

Il sab 16 giu 2018, 19:33 Globik <notifications@github.com> ha scritto:

**Comment by Globik** [comment]
Yes, I can. This is not an issue. Closing here, open there.
