### ISSUE TITLE
 Encoder not available ,Error creating .webm file...

### ISSUE THREAD

**Issue by Ceydigitaluditha** [meetecho/janus-gateway#1284]
When i run  following code , it will return "WARN] No key frame?? assuming 640x480...
[ERR] [postprocessing/pp-webm.c:janus_pp_webm_create:104] Encoder not available
[ERR] [postprocessing/janus-pp-rec.c:main:674] Error creating .webm file..."

please help me to solve this issue

my code:
`
DEBUG=no
if [ "X$1" == "X-x" ]
then
	set -x
	DEBUG=yes
	shift
fi

if [ $# -lt 1 -o ! -d "$1" ]
then
	echo "USAGE: [-x] $0 dir [output]" >&1
	exit 1
fi

DIR="$1"
cd $DIR

/bin/rm -f *.webm *.opus

FILES=`/bin/ls -1 *video.mjr | sort -t- -k5 | sed 's/-video.mjr//g'`
CNT=`echo $FILES | wc -w`

i=0
BASEts=0
ENDts=0
dt="unknown"
DIFF=0
TMPFILE=`mktemp`

for FILE in $FILES
do
    /usr/local/janus/bin/janus-pp-rec $FILE-video.mjr $FILE-video.webm   
    i=$(($i+1))
done

**Comment by lminiero** [comment]
Not a code issue. Questions like these belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Besides, it's written pretty much everywhere that we don't like a bunch of inline text... please use pastebin or similar services instead. Closing.
