### ISSUE TITLE
Safari: enable/disable track

### ISSUE THREAD

**Issue by neilkinnish** [meetecho/janus-gateway#1285]
I've raised an issue with the webkit team regarding this...

https://bugs.webkit.org/show_bug.cgi?id=186889

When video/audio are sent enabling and disabling a stream causes the video to lag, much like a previous bug raised on here for chrome.

**However**, I'm raising here to sense check an additional side affect... if you only have audio and you set enable to false on the track, janus fires "didn't receive audio for more than 1 seconds..." event, I'm sure this is an issue on the webkit end, but flagging here just in case it helps resolve.

**Comment by neilkinnish** [comment]
It's intermittent, not every time - but easy enough to replicate with a few audio mutes.

**Comment by uxmaster** [comment]
I think Safari sends about a packet per second if a track is disabled, thus once in a while it triggers Janus' "media" events with "receiving" toggling `true`/`false`. Try with `no_media_timer = 2` in the `[media]` section of `janus.conf` - https://github.com/meetecho/janus-gateway/blob/master/conf/janus.cfg.sample.in#L98

**Comment by neilkinnish** [comment]
Thanks @uxmaster, been playing with this... had a device fault causing some issues and sending me down a rabbit hole. Have found one issue though which I've raised with the webkit team.

**Comment by lminiero** [comment]
Does this mean we can close this?

**Comment by lminiero** [comment]
I'll take that as a yes :wink:
