### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by LetsVape** [meetecho/janus-gateway#129]
Hello,

Thanks a lot for the great work on this, the gateway is performing way better than traditional peer 2 peer WebRTC.

We've been running a gateway to use for a videochat and we've been handling 5-30 cams at a time, with about 5-15 additional viewers
It keeps crashing after longer periods of time (2-20 hours) with a segmentation fault.

I've saved the last lines of the gdb output here; http://pastebin.com/RJeKsVig, but wasn't sure how to properly debug with the symbols and line numbers so I've compressed 2 core dump files which you can download here;
https://www.wetransfer.com/downloads/9c00b729a6ad273910b15b0ba0720dc820150112093821/58b312ac4d87f1bf33e99434cda80cbc20150112093821/f60b61

and

https://www.wetransfer.com/downloads/7e70b22bf721e1a097b67eb6687d8b8620150111211429/95af7067395acfecf33117ac1b34115920150111211429/3390d1

If there is anything else I can provide to make this easier to find the issue please let me know.

Thanks in advance

**Comment by lminiero** [comment]
I don't think core dumps are usable outside of your development environment. You should provide a backtrace (available with the ```bt``` command in gdb) to display what lead to the issue.

**Comment by LetsVape** [comment]
Thanks for your reply, I'll read into that command and try to get a proper backtrace with gdb soon, I wasn't sure how to properly debug and was under the impression a core dump would contain everything.

**Comment by lminiero** [comment]
It mostly does, but refers to your versions of the executable, libraries, etc. Opening your core dump on my machine I'd most likely just get garbage, as the reference code points wouldn't match.

**Comment by LetsVape** [comment]
I just got the backtrace from the segmentation fault core dump I linked in my first post, you can find it here;

https://www.wetransfer.com/downloads/f3da74d9a61a940f6a00634d6290ecda20150112160423/c26ab4336af9e6f35b518b776a9f703820150112160423/6566aa

I hope this contains what you need to see what causes the issue.
I saw glib and libc were missing the debug symbols so I installed the dbg packages for those, are there any other debug packages I should install to make this more useful for you?

Thanks

**Comment by LetsVape** [comment]
Hi again,

I recompiled the gateway from commit 5865a93 and got another segfault after some usage.
I hope this makes it easier to find the issue;
```
[New LWP 9554]
[New LWP 13283]

warning: Can't read pathname for load map: Input/output error.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/janus/bin/janus'.
Program terminated with signal 11, Segmentation fault.
#0  janus_videoroom_handler (data=<optimized out>)
    at plugins/janus_videoroom.c:1446
1446                    if(session->destroyed) {
```

You can download the full backtrace here;
[www.wetransfer.com/downloads/57d77.....](https://www.wetransfer.com/downloads/57d77b808938af067105323c09f18dfe20150115093300/8513a43a09da6558e4c7a0150396916020150115093300/a543d6)

**Comment by LetsVape** [comment]
Closing this as the code has changed so much recently
The memory fixes have had quite noticeable impact on the server stability the last 2 days, I will get new logs for the remaining crashes

Thanks for all the work!

**Comment by LetsVape** [comment]
Ah no close button for me I see, go ahead and close it if you want, the WeTransfer links have expired and I don't have all those logs saved anymore

**Comment by lminiero** [comment]
Good to know! So it may have been some lurking leak that caused this. Let us know if this still happens anyway.
