### ISSUE TITLE
RTP and RTCP timestamp synchronization problem for single stream

### ISSUE THREAD

**Issue by chadisid** [meetecho/janus-gateway#1300]
I am extracting rtp and rtcp packets of both audio and video stream from videoroom plugin. For example, When I extract rtp and rtcp packets  of same audio stream. The timestamp of rtp packet start with 0 always and RTP timestamp inside the RTCP packet is random value. Both are not synchronized. When I was using older janus 0.2.6 it was synchronized.  This enabled me to find  NTP time of each RTP packet. Now its not the case with 0.4.2. This issue started from following update. 
https://github.com/meetecho/janus-gateway/commit/77bcaa7f0de6cf681ea6fbdb4e55e4b02dfddd0b#diff-724b612068e82ba0ad6ed24da3a22e47R2117

In that janus_rtp_header_update where the timestamp is updated from original random timestamp to 0 in case of audio and video for RTP packet. But the RTP timestamp in the RTCP packet of the stream is not updated before sending to the plugin. So when I try to relay the RTP and RTCP packet of same stream one start with 0 at RTP packet and other start based on the random number in RTCP. Will RTCP update in ice.c will work or will it break any other things?. 
```
if(video) {
       	rtcp_header *r = (rtcp_header *)buf;
       	if (r->type == RTCP_SR) {
     		rtcp_sr *sr = (rtcp_sr*)r;
       		uint64_t rtp_ts = (unsigned long)ntohl(sr->si.rtp_ts);
       		uint32_t ntp_frac = (unsigned long)ntohl(sr->si.ntp_ts_lsw);
       		uint32_t ntp_sec =  (unsigned long)ntohl(sr->si.ntp_ts_msw);
                unsigned long long time_secs, time_usecs,time_secs_1, time_usecs_1;
                const unsigned long long OFFSET = 2208988800ULL;
                const unsigned long long NTP_SCALE = 4294967295ULL;
                time_secs =  ntp_sec - OFFSET;
                time_usecs = (ntp_frac + 1) * 1000000UL / NTP_SCALE;
                time_secs_1 =  ntp_sec - OFFSET;
                time_usecs_1 = (ntp_frac + 1) * 1000000UL / NTP_SCALE;
                struct timeval t;
                t.tv_sec = (time_t) time_secs;
                t.tv_usec = (suseconds_t) time_usecs;
                time_t nowtime;
                struct tm *nowtm;
                nowtime = t.tv_sec;
                nowtm = localtime((const time_t *)&nowtime);
                gchar *timerep = (gchar *) g_malloc0(sizeof(gchar*) * 100);
	        strftime((char *)timerep, 100,"%X",nowtm);
	        uint64_t ToMs = (time_secs_1 * (uint64_t)1000) + (time_usecs_1 / 1000);
        	uint64_t ntp_ms =  ToMs -((rtp_ts-stream->rtp_ctx->v_base_ts)/90);   //for audio replace  by a_base_ts and 90 to sampling freq 
		// NOW CALCULATE THE RTP_TS
		uint32_t rtp_ts_change = (ToMs - ntp_ms)*90;  //for audio replace  90 to sampling freq 
		sr->si.rtp_ts = htonl(rtp_ts_change);
         }
}
```
(I have now changed the RTCP timestamp based on 0 in ice.c ). 
But this solution doesn't work if the RTCP is first packet received and it happens. At the moment I am ignoring first RTCP sender report if its first received before an RTP packet. How can I make it work without ignoring it. Please help.

Another issue I face with this commit of changing SSRC of the rtp packet to original or the first one. If I change the video source. There is no way in the plugin, during relay of packet I can differentiate there is  source change. This RTP belong to this source. My scenario is based on source I treat video differently. Please help me

**Comment by lminiero** [comment]
The commit you refer to is probably the one when we introduced renegotiation support. We overwrite the RTP headers before passing packets to plugins to avoid them being confused when there are device changes (e.g., a camera switch) which would result in a different SSRC replacing the original one, and in a completely different seq/ts space. The `janus_rtp_header_update` ensures that everything looks the same to the plugin, as if nothing ever changed (we keep the seqnumber/ts changes consistent with what was happening before). It's true that this messes up the RTP/RTCP relationship in plugins, though, as RTCP is not overwritten accordingly.

You can try commenting out the two `janus_rtp_header_update` calls appearing [here](https://github.com/meetecho/janus-gateway/blob/master/ice.c#L2158) to see if that fixes it for you. Anyway, this will probably cause issues when those changes I mentioned appear, especially when simulcasting is involved: in fact, the VideoRoom plugin detects a simulcast substream from the SSRC, and it takes note of them when they're first negotiates, which means that if they change later on it won't work anymore. In case removing the `janus_rtp_header_update` fixes the main issue you're experiencing, we'll think about how to address the other problems: anyway, I'm abroad for a conference for another week, so it wouldn't happen before that anyway.

**Comment by lminiero** [comment]
Any feedback on commenting out the `janus_rtp_header_update` calls as suggested?

**Comment by chadisid** [comment]
Yes it worked by commenting the line.

**Comment by chadisid** [comment]
I have scenario where a client changing from  normal camera to screen sharing and vice versa.  The resolution size is different. So I treat these source differently. Now I am doing is stop_rtp_forward and start_rtp_forward again after the configure message in renegotiation (actually some other msgs I added in plugin but its like this anyway). This scenario I am missing sometimes stream. Is it possible to add timestamp change in plugin instead of ice.c?

**Comment by lminiero** [comment]
Looks like RTP forwarding was indeed one of the use cases we needed that RTP adaptation for. Sure, this can be done in plugins, but will need some refactoring, as it means RTP forwarders will need their own RTP context. I'm still abroad, and we're busy on other activities, so not sure when I'll be able to work on that.

**Comment by chadisid** [comment]
OK. I am trying to change timestamp of RTP and RTCP and keep the SSRC same as of original from browser in plugin. By this I can differentiate in external server the source change.

**Comment by atoppi** [comment]
Hey @chadisid take a look to #1428 to see if it accomplishes your needings.

**Comment by lminiero** [comment]
@chadisid any feedback? Do you still care about the issue? That PR only exists because you had this problem, so we'd like to know if it's still needed or not, as I won't hold it forever.

**Comment by chadisid** [comment]
@lminiero  I think it will sort my issue. I only care about SR packets so it is ok with me in this case.

**Comment by lminiero** [comment]
Closing then :+1:
