### ISSUE TITLE
How to join in videoroom using command line (curl)

### ISSUE THREAD

**Issue by titusece** [meetecho/janus-gateway#1301]
Hi,
I would like to join in videoroom using command line in Linux.
So far I can run the janus-gateway in my Linux PC and able to join using web page. It works well, and now I would like to join using command line.
Its because I would like to join in the same video room using my raspberry pi board too which is running on non-X server based image, so I need to join using commandline.
Any help greatly appreciated.
Thanks for the help.

**Comment by lminiero** [comment]
Question for the group, we only use Github for issues. Closing.
