### ISSUE TITLE
MintOS build with websockets

### ISSUE THREAD

**Issue by Kalumburu** [meetecho/janus-gateway#1303]
In MintOS we had a problem enabling libwebsockets.

We found that we are using MintOS's libwebsockets 1.7.1 so we removed it with Synaptic Package Manger, built as the instruction of Janus and it worked !

**Comment by lminiero** [comment]
Closing as not an issue. Feel free to share this info on our [group](https://groups.google.com/forum/#!forum/meetecho-janus) though.
