### ISSUE TITLE
[ERR] [janus.c:main:4074]       Couldn't load plugin 'libjanus_duktape.so': /usr/local/janus/lib/janus/plugins/libjanus_

### ISSUE THREAD

**Issue by vinson-zhang** [meetecho/janus-gateway#1306]
[ERR] [janus.c:main:4074]       Couldn't load plugin 'libjanus_duktape.so': /usr/local/janus/lib/janus/plugins/libjanus_

**Comment by lminiero** [comment]
You didn't provide enough information.

**Comment by lminiero** [comment]
Closing.
