### ISSUE TITLE
chotest.lua:6: module 'json' not found

### ISSUE THREAD

**Issue by jevian-ma** [meetecho/janus-gateway#1308]
Loading plugin 'libjanus_lua.so'...
[ERR] [plugins/janus_lua.c:janus_lua_init:1155] Error loading Lua script /opt/janus/share/janus/lua/echotest.lua: /opt/janus/share/janus/lua/e                                               chotest.lua:6: module 'json' not found:
        no field package.preload['json']
        no file '/usr/local/share/lua/5.3/json.lua'
        no file '/usr/local/share/lua/5.3/json/init.lua'
        no file '/usr/local/lib/lua/5.3/json.lua'
        no file '/usr/local/lib/lua/5.3/json/init.lua'
        no file '/usr/share/lua/5.3/json.lua'
        no file '/usr/share/lua/5.3/json/init.lua'
        no file './json.lua'
        no file './json/init.lua'
        no file '/opt/janus/share/janus/lua/json.lua'
        no file '/usr/local/lib/lua/5.3/json.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.3/json.so'
        no file '/usr/lib/lua/5.3/json.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './json.so'

Can you tell me how to fix this issue.

**Comment by jevian-ma** [comment]
I had fixed this bug use this patch.
[janus.zip](https://github.com/meetecho/janus-gateway/files/2216890/janus.zip)

**Comment by lminiero** [comment]
There's nothing to patch, because there's no issue. You're missing the Lua json parser library the demo uses: https://github.com/meetecho/janus-gateway/blob/master/plugins/lua/echotest.lua#L4

I'll have to change the configure to disable Lua and Duktape by default.

**Comment by jevian-ma** [comment]
"I'll have to change the configure to disable Lua", But I sync your source at 4 hours age, bug lua still work.
this is my patch http://download-1251316712.coscd.myqcloud.com/janus.patch.

**Comment by lminiero** [comment]
Are you even reading what I'm writing..?
I said that your patch is not a fix, because there is no issue. The `echotest.lua` clearly says that it depends on a JSON library that you need to install MANUALLY, using luarocks. Your patch simply puts that dependency in the folder with the other lua scripts, which may fix your problem, but is not the right solution. The right solution is installing all external dependencies using `luarocks`.

**Comment by jevian-ma** [comment]
You are right, thank you help me, but My system version is a clear linux debian system, fail to install luajson.
