### ISSUE TITLE
how to change the resolution ratio?

### ISSUE THREAD

**Issue by jevian-ma** [meetecho/janus-gateway#1314]
I use janus, Input stream from a ip camera, resolution ratio 1920*1080, so I use streaming plugin,
but Playing the stream just a phone app, I want change the resolution ratio to 240*320 at the broadcast this stream time.
If resolution ratio low, playing is more fluency.

**Comment by lminiero** [comment]
No idea what you're asking, but Github is for code issues, not questions. Closing.
