### ISSUE TITLE
I couldn't set profile-level-id=42e01f

### ISSUE THREAD

**Issue by jevian-ma** [meetecho/janus-gateway#1315]
I use streaming plugin to read rtsp stream and set janus.plugin.streaming.cfg profile-level-id=42e01f
but sdp still is:
`"v=0
o=- 1532611353170479 1 IN IP4 172.17.0.2
s=Mountpoint 10
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS janus
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 172.17.0.2
a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:I7xU
a=ice-pwd:NggTwidK4qqHhlLeXB0RKB
a=ice-options:trickle
a=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38
a=setup:actpass
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;profile-level-id=640028;sprop-parameter-sets=J2QAKKwa0A8ARLyoAA==,KO4EYsAA
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=ssrc:2699349578 cname:janusvideo
a=ssrc:2699349578 msid:janus janusv0
a=ssrc:2699349578 mslabel:janus
a=ssrc:2699349578 label:janusv0
a=candidate:1 1 udp 2013266431 172.17.0.2 47174 typ host
a=end-of-candidates
"`
### **some brower setRemoteDescription error.**

**Comment by lminiero** [comment]
Again: Github is for *code issues*, not questions. Please use the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for that, as clearly explained in the guidelines (the text you removed to write your issue).

**Comment by jevian-ma** [comment]
I think this is a issue.
when I want get rtsp stream by janus.plugin.streaming,
I couldn't set profile-level-id by janus.plugin.streaming.cfg file.
But your guidelines tell me that I can set it by configuration file in janus.plugin.streaming.cfg at 132 line.
some browse incompatible this flag, when I use win7 + chrome, profile-level-id=640028 is bad, setRemoteDescription error.

**Comment by lminiero** [comment]
setRemoteDescription is a browser error. If you tell Janus to put that profile, and the browser doesn't like it, is it Janus fault, or yours?

**Comment by lminiero** [comment]
And you can definitely override the profile using `videofmtp`. You're probably just doing it wrong, which again means it is a question for the group, and not here.

**Comment by jevian-ma** [comment]
I just tell you my issue, janus.plugin.streaming.cfg is not use about profile-level-id. maybe this error just for me, but you can check it.
I believe that set profile-level-id by configuration file is very important for improve compatibility.

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.streaming.cfg.sample.in#L132

**Comment by jevian-ma** [comment]
yes, I change here but no use, so I submit a issue for you. I don't know why no use. maybe this is my fault or this is a real issue.

**Comment by lminiero** [comment]
Works for me, so not a code issue. Locking the conversation.
