### ISSUE TITLE
Error while playing the recorded playout

### ISSUE THREAD

**Issue by arjun-spark** [meetecho/janus-gateway#1318]
Hi,
While trying to play the recorded video in recorder/playout functionality, it shows error.
The error it shows is " Error opening recording files".  Please a provide a solution.

**Comment by lminiero** [comment]
Question for the group. This section is only for code issues. Closing.

**Comment by arjun-spark** [comment]
Is this due to any plugin issue?? can you explain much more briefly

**Comment by lminiero** [comment]
Please post on the group.
