### ISSUE TITLE
ICE failed for component

### ISSUE THREAD

**Issue by arjun-spark** [meetecho/janus-gateway#1319]
Hi,
While playing the Recorder/playout functionalities the following error occurs.
[ERR] [ice.c:janus_ice_check_failed:1498] [3465971475934257] ICE failed for component 1 in stream 1...
[3465971475934257] Telling the plugin about the hangup because of a ICE failed (JANUS Record&Play plugin)

**Comment by lminiero** [comment]
Again, not a code issue, but a runtime one. Our [group](https://groups.google.com/forum/#!forum/meetecho-janus) explains in detail how to address these frequently asked questions in its description. Closing.
