### ISSUE TITLE
SUGGESTION: add Id on janus leave videoroom event

### ISSUE THREAD

**Issue by fega** [meetecho/janus-gateway#1320]
Hello, in the videoroom docs states that when a user leaves the room the following event is sent.

```
{
        "videoroom" : "event",
        "leaving" : "ok"
}
```
Is obvious that the users leaving should not receive their Id again, but this is not convenient when janus [event handlers](http://www.meetecho.com/blog/event-handlers-a-practical-example/) are being used.

Is better to know the user id or event better get the room id also.

Thanks

**Comment by lminiero** [comment]
Actually, event handlers can typically figure that out from the `handle` the event refers to. This wouldn't be the only event that has less context, which can in turn be evinced from related identifiers. Anyway, I'm not sure we have an event handler notification for "leaving".

**Comment by lminiero** [comment]
This patch makes sure event handlers get all the info they need. The VideoRoom API "leaving" event instead remains the same, as there's no need for the ID in that context (it's sent on the handle of the publisher themselves).
