### ISSUE TITLE
Can't execute janus from <installDirectory>/bin/janus

### ISSUE THREAD

**Issue by satish4linux** [meetecho/janus-gateway#1326]
Hii All,
I have installed Janus-Gateway on Ubuntu 16.04 distribution. I followed the whole installation procedure as mentioned in [READme file on github repo](https://github.com/meetecho/janus-gateway/). Installation was all good. After installation, these problems I am facing : 
Note : my installation Directory = /opt/janus

1.  Can't execute `janus --help `
![screenshot from 2018-07-31 08-20-23](https://user-images.githubusercontent.com/13817966/43434784-b3786a38-946c-11e8-8edd-bb14db303d5a.png)

2.  Can't execute `janus`
![screenshot from 2018-07-31 08-22-53](https://user-images.githubusercontent.com/13817966/43434854-fdd03ebc-946c-11e8-8df2-378d7f3644d0.png)

Seeking for some help. Thanks is Advance.

Satish

**Comment by lminiero** [comment]
Please use the group for questions.

**Comment by satish4linux** [comment]
Can I get a link for the Google Group for the same?

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
