### ISSUE TITLE
Libwebsock 3.0.0 ping pong support

### ISSUE THREAD

**Issue by denisicun** [meetecho/janus-gateway#1327]
Hi,

We recently tried to upgrade our version of Janus to latest and as part of that upgrade we also updated the version of libwebsocket to version 3.0.0.

We found that Janus is not supporting ping-pong with this version of libwebsocket.
We found in your code [this check](https://github.com/meetecho/janus-gateway/blob/77521cab15b88a8507fa740eca04a175e73c8bae/transports/janus_websockets.c#L492) which is probably causing  this bug. libwebsocket major version is 3 but the minor version is 0, so the condition is false even though this is a new version.

Our solution for this was to down-grade the libwebsocket version to 2.4.2.

Thanks!

**Comment by lminiero** [comment]
Thanks for pointing that out, I guess we'll have to tweak that check :+1: 
I'll try to do that later. Not sure if LWS 3 will be compatible with our usage of it though: have you checked if there are breaking API changes?

**Comment by lminiero** [comment]
Looks like a similar broken check is in some other parts of the code as well, specifically those related to the definition of `LLL_USER`. I'll have to fix those too.

**Comment by lminiero** [comment]
This should fix it, feel free to reopen if that's not the case. As a side note, @atoppi confirmed that he's been using libwebsockets 3.0 for a while already and it works fine for him, so no API change to worry about apparently.

**Comment by denisicun** [comment]
Thanks for your quick response :)
