### ISSUE TITLE
HMAC auth

### ISSUE THREAD

**Issue by Lestrangge** [meetecho/janus-gateway#1328]
The HMAC-SHA1 auth is enabled on a local virtual machine. 
`token_auth = yes
       
token_auth_secret = janus `

Then, the demo page for videocalls is used (which means no token is provided). And Janus does not send 403 or other errors to the client, just grants access. The [logs](https://pastebin.com/s6PrF9w7) contain some info about the token being invalid fro attaching the plugin and 403 being ready to be sent, but that does not happen. 

After restart of janus it drops some requests exactly with 403. But only does it ~10 times. Then grants access

**Comment by lminiero** [comment]
Are you computing the tokens as explained here? https://janus.conf.meetecho.com/docs/auth#signed
Signed tokens don't work as stored tokens, and are not preloaded via Admin API.

**Comment by Lestrangge** [comment]
Yeah, I get it. When I append token to a request, everything works perfectly. But when the token is either invalid or not sent, the plugin and janus are not dropping sush a request with an error

**Comment by lminiero** [comment]
Ack, I'll check later.

**Comment by lminiero** [comment]
Are you using master or an older/tagged version of Janus? We fixed something related to authorizations just a couple of months ago: https://github.com/meetecho/janus-gateway/commit/bf75111c1d7b5f22b3d0019927a8dd2e843d17af#diff-e26c229e0800bdaf6e4e995fba5d3c4d

Just tested with master and it works as expected here.

**Comment by Lestrangge** [comment]
Yeah, the update has solved the problem, thanks for help)
