### ISSUE TITLE
Videocall plugin

### ISSUE THREAD

**Issue by Lestrangge** [meetecho/janus-gateway#1329]
The plugin does not correctly handle incoming call hangup.
The sessions and handles get destroyed, the hangup message cannot access neither the caller nor to the callee as the connection to the janus unfortunately gets lost((
That also appears to happen in the [demo](https://janus.conf.meetecho.com/videocalltest.html)

And another problem. Not accepting the call for a long time leads to another bug: remote stream can not be accesed. If the call is accepted, both users get stuck within local stream, not recieveing remote data, whiel the janus logs state, that it recieves files

**Comment by lminiero** [comment]
I assume you're not on master for this either. We recently did many fixes on the VideoCall as well. Closing, feel free to reopen if you can confirm it's still an issue on master.
