### ISSUE TITLE
glibc double free or corruption (libwebsock)

### ISSUE THREAD

**Issue by LetsVape** [meetecho/janus-gateway#133]
Hey,

I've been trying out websockets instead of REST, performance definitely seemed better and less resources are being used.
I didn't expect it to work flawlessly as it hadn't been tested as much but it was surprisingly stable for 8 hours or so with 5-20 cams at a time

It eventually crashed with the following:
"*** glibc detected *** /opt/janus/bin/janus: double free or corruption (!prev): 0x00000000014725f0 ***"
Here is the full console log;
http://pastebin.com/CkykNA3S

and here is a backtrace of the core dump;
https://www.wetransfer.com/downloads/ee2cb2e67a17d57ae200cd75406ef3a620150113194213/d3f5cbf04760b347470c5283abd4637020150113194213/d63e58

Hope this helps to improve websockets at some point

Thanks in advance!

**Comment by lminiero** [comment]
From a quick glance, it looks like a problem within the library itself. Unfortunately, there's no way to check and wait for a fix as it came to my knowledge that the developer of the libwebsock library passed away. I'm currently abroad so I'll only be able to better look into this when I get back to work next week.

**Comment by LetsVape** [comment]
Thanks for having a look.
That's some sad news, let's hope it's not too much of an issue so a hotifx for janus can be released so you don't have to change libraries

Enjoy your time abroad!

**Comment by lminiero** [comment]
libwebsock has been replaced by libwebsockets, so I'm closing this issue. Please try the new version of Janus instead.

**Comment by LetsVape** [comment]
Thanks a lot for all the hard work as usual Lorenzo! 
Very nice to see a new websockets client, this seemed a bit smoother than REST
Will check out the latest version after i've got some logs for the handshake error.
