### ISSUE TITLE
Janus needs to be restarted after several transports/janus_http.c errors

### ISSUE THREAD

**Issue by blksh** [meetecho/janus-gateway#1334]
Hello guys, we having some troubles with the following scenario:

LAN application  WebClient  <--webrtc-> Janus-gateway (NAT 1:1) <- pjsip -> asterisk

Janus and asterisk are on the same server 10.10.10.10/24  The webclients run on Win10 PCs on 10.10.0.0/24 the two lan are just routed and there isn't any firewall in the middle.  

Sometime happens that all pjsip Endpoints became unreachable. When you run a restart of the janus process all the pjsip endpoints come back reachable again.  

As you can see from janus logfile ( see https://pastebin.com/22PphaWv) the janus process stop to log until the restart request.  

At the same time asterisk logs the block of unreachable Endpoints, janus starts to log a block of 4 "[ERR] [transports/janus_http.c:janus_http_handler:1367] Couldn't find any session ... " for several session id, except for the last one wrote just one time. The next logs after this row are:

Stopping gateway, please wait...
[Sun Aug 12 22:06:10 2018] Ending sessions timeout watchdog... 

If you follow the session id across janus logfile you can figure out that the session was created about two hours earlier, few seconds before the issue a timeout expires and the process try to destroy the session.   The error is wrote by the following statement if the session variable is 0 or the session has been already destroyed (I guess):

**************** in the janus_http.c (v0.4.3) :1367
 
if(!session || g_atomic_int_get(&session->destroyed)) {
            JANUS_LOG(LOG_ERR, "Couldn't find any session %"SCNu64"...\n", session_id);
            response = MHD_create_response_from_buffer(0, NULL, MHD_RESPMEM_PERSISTENT);
            janus_http_add_cors_headers(msg, response);
            ret = MHD_queue_response(connection, MHD_HTTP_NOT_FOUND, response);
            MHD_destroy_response(response);
            goto done;
}

Unfortunately the server is in production and we are unable to produce a coredump at the moment.

Thank you for your support.

**Comment by atoppi** [comment]
@AndreaGvA as for the #1330, it applies to WebSocket transport only.

**Comment by blksh** [comment]
Hi @atoppi thank you for your reply. The issue affects all the clients at the same time. Each client can't neither make neither receive calls. At the same time asterisk logs that all the endpoints are unreachable, janus stops to log. 
The network topology is very simple and clients communicate directly with janus. It is also very unlikely that all clients will stop sending keepalives at the same time. I think it is more probable that janus is no longer able to process them.

**Comment by atoppi** [comment]
Hi @blksh,
in this case, any chance you can switch to WebSocket transport?

**Comment by blksh** [comment]
Hi @atoppi, janus is configured to work as component of an appliance. We don't know how much it is a workable solution right now change the transport method.

**Comment by lminiero** [comment]
@blksh the reason why @atoppi suggested tryng with WebSockets is to check whether this is a transport or core issue. We suspect it's really a core thing (possibly a deadlock somewhere when sessions are used). One way to double check is to try and invoke the Admin API after you notice the unresponsiveness: Janus and Admin API use different web servers, and so a problem in one shouldn't affect the other; if that doesn't work either, it might be a confirmation that the issue is somewhere in the core. Enabling the locking debug might help in that sense.

That said, please make sure you're using master, as by policy I won't debug anything that we might have fixed already.

**Comment by lminiero** [comment]
PS: you should also let us know if yu changed anything in the default configuration of the HTTP transport (e.g., the threading model).

**Comment by blksh** [comment]
@lminiero as I told @atoppi in this case janus is a component of a nethcti installation. We didn't change anything. We have run several check on the transport level without  finding any issue.

**Comment by lminiero** [comment]
Closing for lack of feedback and because a lot changed in the Janus core since. Feel free to reopen if still an issue.
