### ISSUE TITLE
Videocall plugin

### ISSUE THREAD

**Issue by Lestrangge** [meetecho/janus-gateway#1335]
Here is a problem with videocall plugin: assuming papa calls user. User waits at about 1 minute and accepts the call. As a result, remote stream is empty, 'end of candidates' is logged before 'accepted' event. If the call is accepted instantly, remote stream isn't empty. Logs: https://pastebin.com/G2thAYcz

**Comment by Lestrangge** [comment]
The second problem only appears when trickle is set to true in offer

**Comment by Lestrangge** [comment]
Second problem only appears to happen when trickle is set to on

**Comment by lminiero** [comment]
I'm not sure I understand your problem. Please elaborate.

**Comment by Lestrangge** [comment]
Well
We take videocall plugin
Register two users: Alice, Bob
Alice calls Bob
Bob does not accept a call for 45 seconds or longer
After that he accepts it
And no remote media can ba accessed neither by Alice nor by Bob

Eventually, as far as i understand, this happens beacuse of these lines (janus.c:724:janus_request_ice_handle_answer)
`if((janus_get_monotonic_time() - trickle->received) > 45*G_USEC_PER_SEC) {
				/* FIXME Candidate is too old, discard it */
				janus_ice_trickle_destroy(trickle);
				/* FIXME We should report that */
				continue;
			}`

Here is that 45 seconds timeout. If I rise it to, let's say, 120 seconds, the call accepted within this time gets hangup here (dtls.c:1071:janus_dtls_retry)
`if(janus_get_monotonic_time() - dtls->dtls_started >= 20*G_USEC_PER_SEC) {
		/* FIXME Should we really give up after 20 seconds waiting for DTLS? */
		JANUS_LOG(LOG_ERR, "[%"SCNu64"] DTLS taking too much time for component %d in stream %d...\n",
			handle->handle_id, component->component_id, stream->stream_id);
		janus_ice_webrtc_hangup(handle, "DTLS timeout");
		goto stoptimer;
	}`

Rising this 20 sec timeout to 95 sec helps to solve the problem, call can now be answered within 95 sec. But im definitely not sure wheter this behaviour is alright or could this problem be solved in any other way
And, anyway, the call can still be only answered within specific timeouts, which doesn't seem pretty good(

**Comment by lminiero** [comment]
I understand the first timeout, which we can maybe make configurable in `janus.cfg`. Anyway, the second timeout I won't touch: 20 seconds waiting for DTLS to succeed after ICE went through is A LOT. If it's taking so long to complete, you have another problem, as this means there's a lot of retransmissions affecting the DTLS handshake.

**Comment by Lestrangge** [comment]
The issue is probably not at this place at all
I'm now using LTE (no VPN or additional NAT or anything) and trying to use videocalls
So, we have two users: Alice, Bob
Alice calls Bob
Bob waits for a minute and accepts the call
No remote media is recieved neither by Bob nor by Alice
Try it urself, maybe u can figure out the problem

**Comment by lminiero** [comment]
Sorry, I don't have an LTE enronment to do testing, and I'm busy on other stuff. Besides, this is a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus): let's not confuse this issue with unrelated stuff.

**Comment by Lestrangge** [comment]
This not only happens with lte but with any kind of network
Lte was used as a proof that im not behind loads of stuff like nat and so

**Comment by lminiero** [comment]
As to the trickle timeout discussed above, you can now override it in `janus.cfg`:
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.cfg.sample.in#L64

Closing as this fixes the original issue.
