### ISSUE TITLE
RTSP to WebRTC streaming in local network without internet

### ISSUE THREAD

**Issue by asmyasnikov** [meetecho/janus-gateway#1338]
Hi!
I need re-pack RTSP-streams from IP-cams in my local (offline) network to WebRTC-protocol streams with P2P connections for UDP-data channels. Because browsers cannot play RTSP-video instead WebRTC-video. For example, Janus getting RTSP signal data (which contains UDP-ports for video-streams) from IP-cam, Janus notify web-clients about UDP-ports for video-streams, and browser getting video-data from IP-cam directly without re-streaming video on Janus server-side. My local network basicly not connected to internet (and not connected to known STUN-servers).
How do I make this system? What the params of Janus config may realized this model.
Tnx!

**Comment by lminiero** [comment]
Closing as not a code issue, which is the only thing we use Github for. Please post questions like this on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.

**Comment by JackZhai2018** [comment]
> ections for UDP-data channels. Because browsers cannot play RTSP-video instead WebRTC-video. For example, Janus getting RTSP signal data (which contains UDP-ports for video-streams) from IP-cam, Janus notify web-clients about UDP-ports for video-streams, and browser getting video-data from IP-cam directly without re-streaming video on Janus server-side. My local network basicly not connected to internet (and not connected to known STUN-servers).
> How do I make this system? What the params of Janus config may realized this model.

Had you resolved that ploblem, can you share your experience？ @asmyasnikov

**Comment by asmyasnikov** [comment]
No solve. I use rtsp type of stream in plugin.streaming config.
