### ISSUE TITLE
Record & Play plugin Empty file - Unsupported transport tcp 

### ISSUE THREAD

**Issue by chest3x** [meetecho/janus-gateway#134]
Hello,
I'm trying out your Record & Play plugin and I am having certain issues. 
It is hosted on AWS EC2, ports are opened, Public IP in the config is also set, but as you can see in the log below, it practically creates empty file, what probably means that there are no frames from camera coming to the janus server. 

Can you tell what might be the possible reason for this?
Thank you very much.

Creating new session: 1677021463
Creating new handle in session 1677021463: 4228028012
[4228028012] There's a message for JANUS Record&Play plugin
[4228028012] There's a message for JANUS Record&Play plugin
[4228028012] Creating ICE agent (controlled mode)
[4228028012] ICE send thread started...
[4228028012] Done! Ready to setup remote candidates and send connectivity checks...
[WARN] [4228028012]    Unsupported transport tcp!
[WARN] [4228028012]    Unsupported transport tcp!
No more remote candidates for handle 4228028012!
[4228028012] There's a message for JANUS Record&Play plugin
File is 15 bytes: rec-3396960577-audio.mjr
Closed audio recording rec-3396960577-audio.mjr
File is 15 bytes: rec-3396960577-video.mjr
Closed video recording rec-3396960577-video.mjr
[4228028012] There's a message for JANUS Record&Play plugin
[4228028012] There's a message for JANUS Record&Play plugin
[4228028012] There's a message for JANUS Record&Play plugin

**Comment by lminiero** [comment]
I don't see any message on a successful completion of ICE and DTLS, which means connectivity may not be as open as you think, either on the server's or client's. Does the echo test work as expected?

**Comment by chest3x** [comment]
Thank you for a fast reply.
Well, server ports are fully opened, the other issue might be client network, I was trying to disable firewall and nothing happened. I'll try to connect from different network when I'm home.

EchoTest is not working either, this is the output:

Creating new session: 31660186
Creating new handle in session 31660186: 1028267817
[1028267817] There's a message for JANUS EchoTest plugin
[1028267817] No stream, wait a bit in case this trickle got here before the SDP...
[1028267817] There's a message for JANUS EchoTest plugin
[1028267817] Creating ICE agent (controlled mode)
[WARN] [1028267817] Skipping unsupported media line...
[1028267817] ICE send thread started...
[1028267817] Waiting for candidates-done callback...
[WARN] [1028267817] Queueing trickle candidate, status is not START yet
[WARN] [1028267817] Skipping unsupported media line...
[1028267817] Done! Ready to setup remote candidates and send connectivity checks...
[WARN] [1028267817]    Unsupported transport tcp!
[WARN] [1028267817]    Unsupported transport tcp!
[WARN] [1028267817]    Unsupported transport tcp!
No more remote candidates for handle 1028267817!
[WARN] [1028267817]     Missing valid SRTP session (packet arrived too early?), skipping...
Detaching handle from JANUS EchoTest plugin
Handle detached (0), scheduling destruction
[1028267817] ICE send thread leaving...
Destroying session 31660186
[1028267817] WebRTC resources freed
[1028267817] Handle and related resources freed

**Comment by chest3x** [comment]
I tried to run admin mode on both Virtual Box machine Ubuntu 14.04 and AMAZON machine Ubuntu 14.04. 
Situation is the same. I installed completely following your README and Deployment documentation and I don't know what to do next.

State value is "connected" right after Start, second later it is just "ready" and stays that way 'til turned off. What I find suspicious is also a DTLS log below.

Here is the log from Admin mode which is pretty much similar for both AWS and VirtualBox:
http://pastebin.com/UaXsLDQR

**Comment by lminiero** [comment]
Have you tried checking with Wireshark to see if DTLS messages are being exchanged after ICE completes? Also check issue #132 to see if you may be encountering the same problem, as the user reporting it said that he had different behaviours with different openssl versions.

**Comment by chest3x** [comment]
My WireShark output from client is similar to: https://groups.google.com/d/msg/meetecho-janus/-2TNqQ38IHI/tY_dRpHQAcYJ

**Comment by chest3x** [comment]
Issue is solved in https://github.com/meetecho/janus-gateway/issues/132 and has a similar core.

**Comment by lminiero** [comment]
Let me know if that indeed fixed the issue for you and I'll close it.

**Comment by chest3x** [comment]
It fixed the issue, Janus is working now. Thanks.
