### ISSUE TITLE
Segfault videoroom

### ISSUE THREAD

**Issue by vahidov** [meetecho/janus-gateway#1344]
commit - ef8477e
core dump - https://gist.github.com/vahidov/2e6c4814521974f61dc16836a4f7374e

**Comment by lminiero** [comment]
1. in the guidelines we explicitly ask NOT to put logs/dumps inline: you have to use services like gist/pastebin
2. you could at the very least describe the scenario and what led to the crash: I won't address an issue that just lists a core dump and nothing else.

Thanks

**Comment by vahidov** [comment]
We have schema 
1 room = 1 publisher > many viewers.
Rooms are never removed. Room id = user id.
Room config
```
publishersCount: 1
bitrate: 128000
firFrequency: 1
audioCodec: opus
videoCodec: h264
audiolevel_ext: false
audiolevel_event: false
permanent: false
notify_joining: true
```
Its worked without crashes about 2 weeks.
In time of crash - there are total 90-100 publishers and about 1000 total viewers on server.
I didn't know, what exactly led to the crash. It was in normal running, but in one time -  crashed

What kind of information you need yet?

**Comment by atoppi** [comment]
Try to understand which pointer is invalid.
Considering that line at `janus_videoroom.c:5573`
```
if(participant->room->acodec[i] == JANUS_AUDIOCODEC_NONE)
```
I'll try inspecting `participant`, `room` and `acodec[i]`, using gdb print functionality.

**Comment by vahidov** [comment]
(gdb) display participant
1: participant = (janus_videoroom_publisher *) 0x6b6837742450
(gdb) display participant->room
2: participant->room = (janus_videoroom *) 0x0

**Comment by atoppi** [comment]
what about `videoroom` ? Not the pointer value, but the pointed memory area with address `0x6b67b0039cc0`

**Comment by vahidov** [comment]
@atoppi - is this command?
```
(gdb) x/gx 0x6b67b0039cc0
0x6b67b0039cc0:	0x00000000001a10c2
```

**Comment by atoppi** [comment]
@vahidov IIRC it should be
```
p *videoroom
```

**Comment by vahidov** [comment]
```
(gdb) p *videoroom
$4 = {room_id = 1708226, room_name = 0x6b67b0244930 "Room 1708226", room_secret = 0x6b67b02e83e0 "hAwezxf", room_pin = 0x6b67b0048600 "hY8asd", is_private = 0, require_pvtid = 0, max_publishers = 1, bitrate = 128000, bitrate_cap = 0, fir_freq = 1, acodec = {
    JANUS_AUDIOCODEC_OPUS, JANUS_AUDIOCODEC_NONE, JANUS_AUDIOCODEC_NONE}, vcodec = {JANUS_VIDEOCODEC_H264, JANUS_VIDEOCODEC_NONE, JANUS_VIDEOCODEC_NONE}, do_svc = 0, audiolevel_ext = 0, audiolevel_event = 0, audio_active_packets = 0, audio_level_average = 0,
  videoorient_ext = 1, playoutdelay_ext = 1, transport_wide_cc_ext = 0, record = 0, rec_dir = 0x0, participants = 0x6b67e4316e40, private_ids = 0x6b67e4316f60, destroyed = 0, check_allowed = 0, allowed = 0x6b67e4316de0, notify_joining = 1, mutex = {__data = {
      __lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0, __spins = 0, __elision = 0, __list = {__prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>, __align = 0}, ref = {count = 1, free = 0x6b6860f107ea <janus_videoroom_room_free>}}
```

**Comment by vahidov** [comment]
@atoppi 
not in friday evening  - this is production :-). I'm try in monday.

**Comment by vahidov** [comment]
@atoppi  @lminiero 
6 days till now - commit bab65e3 without crashes.
I think, ticket may be closed. If any new info - i will reopen it.

**Comment by lminiero** [comment]
Excellent, thanks for the update! Closing then.
