### ISSUE TITLE
SegFault When Making SIP Call to an Unregistered Address

### ISSUE THREAD

**Issue by MichaelB76** [meetecho/janus-gateway#135]
A problem I've noticed when using the SIP plugin is that Janus crashes with a segmentation fault when calling an unregistered address. I can reproduce this every time. Catching the crash in NetBeans I can see it is in ice.c janus_ice_thread(). Here's the relevant code:

GMainLoop *loop = handle->iceloop;
if(loop == NULL) {
	JANUS_LOG(LOG_ERR, "[%"SCNu64"] Invalid loop...\n", handle->handle_id);
	g_thread_unref(g_thread_self());
	return NULL;
}
g_usleep (100000);
g_main_loop_run (loop); <-- crashes here

The problem occurs because the SIP plugin has already called janus_ice_webrtc_free() which cleans up the handle before g_main_loop_run is called. The check on (loop == NULL) doesn't work correctly because it occurs before the g_usleep() call and doesn't make use of the mutex which protects the handle.

I'm getting this with the SIP plugin but others could also have the same problem if they try to end a call before the ice thread is started.

Hope that's clear and helpful, please let me know if you'd like any more information.

**Comment by lminiero** [comment]
I've noticed this issue too a few days ago, but have had no time so far to look into it. From the quick glance I gave initially, this is a race condition as you found out, caused by the fact that the SIP plugin asks the core to tear down any PeerConnection that may be in place because something went wrong when handling the INVITE:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1654

This probably results in the double free for some reason, even though I've had no time to see what other request/event leads to this.

**Comment by MichaelB76** [comment]
Thanks, I was wondering if it might be related to issue #117 but missed your code link in that thread.

**Comment by lminiero** [comment]
No I don't think it is, it's probably exactly what you identified there and, possibly, a generic issue with the ```close_pc``` plugin request in some specific scenarios. I'll have a look at that ASAP.

**Comment by lminiero** [comment]
Sorry if this took so long, but we've been very busy improving things in Janus and fixing other stuff as well. I finally found some more time to look into this, and I think I found a more or less clean way to handle the ```close_pc``` related race conditions that lead to the crash. I basically let the ICE thread clean stuff as it should do, which means a call to ```close_pc``` will pretty much just change some values and defer it there.

This seems to be working for me for the specific case of the SIP 404 case. Let me know if it does fix it on your setup as well and I'll close the issue (although I'll probably do some more tests on other plugins as well).

**Comment by MichaelB76** [comment]
That's great thanks, I'll get the latest code and test this next week.

**Comment by MichaelB76** [comment]
Sorry for the delay looking at this, I've been working on a couple other things. Hope to test this in the next day or two.

**Comment by MichaelB76** [comment]
Retested this with the latest code and it seems to be fine thanks.
