### ISSUE TITLE
Videoroom crashes when a publisher leaves and require_pvtid is set to true

### ISSUE THREAD

**Issue by tugtugtug** [meetecho/janus-gateway#1362]
The video room has the owner subscription list when require_pvtid is set to true. There are a couple of bugs in the current implementation.
1. the owner subscription list isn't refcounted (i.e. can be accessed unsafely).
2. the owner subscription list isn't cleaned up when the publisher leaves and the publisher removes the last reference of the subscribers. i.e. the owner subscription list could be accessed after the subscribers are freed.

I think to properly fix this, we should use refcounted subscription list for the owner (as commented in code). However, it seems to have less value maintaining a subscriber instance if the publisher has already left.

Along with this major issue, I found a few synchronisation issues.
1. private_ids are accessed without protection in a couple of places (should be protected by room mutex). As a side note, I found the mutexes are getting unmanageable in this module and is asking for some review and proper documentation.
2. videoroom_mutex is unlocked twice in the "kick" handler.
3. owner could be accessed without the room lock or holding a reference when a new subscriber is added.
4. owner subscription list is accessed without the subscribers_mutex in janus_videoroom_hangup_media_internal.
5. Possible double free of the subscriber and publisher if the publisher frees the subscriber list first in janus_videoroom_hangup_media_internal, and subscriber races to be freed (subscriber->feed check to have publisher without any synchronisation, and then publisher removes the subscriber).  

I have a patch for addressing the issues above against master/0a5f379a (without doing refcounting for owner subscription).

https://pastebin.com/1F0jD6CS

**Comment by lminiero** [comment]
Thanks for your detailed analysis! The double unlocks are probably some leftovers from changes to the code that we missed, so good catch. I'll have to look at the patch and the possible implications: I'll probably only be able to do that early next week, as tomorrow I'll be out of the office. Can you share your fix as a pull request so that it's easier to review and discuss changes, if needed?

**Comment by tugtugtug** [comment]
No hurry, next week is fine.
One thing I'm still puzzled is how does it make sure the access to subscriber->feed is safe. e.g. if the publisher leaves, and calls janus_videoroom_hangup_media_internal to clean up the subscribers. What makes the g_pointer_clear of the feed synchronise properly with the other subscriber message handlers.

**Comment by lminiero** [comment]
Closing as we merged your PR.

**Comment by tugtugtug** [comment]
Thank you @lminiero !
