### ISSUE TITLE
MCU: Firefox "audio output" doesn't work

### ISSUE THREAD

**Issue by leonuh** [meetecho/janus-gateway#137]
Reproduce: Try to connect with 2 Firefox clients without video.
Other test: Try to connect with 1 Chrome and 1 Firefox client without video. You will notice that the microphone is working, but you will not hear anything from Firefox.

**Comment by lminiero** [comment]
Sorry for this late reply. What demo does this refer to?

**Comment by leonuh** [comment]
Video MCU

**Comment by lminiero** [comment]
Just tested this with both Firefox 35 and 38, and it worked as expected for me. What are you passing to createOffer when publishing? Closing for now, feel free to reopen if it's still an issue with the latest Janus and browsers.
