### ISSUE TITLE
Makefile – html/janus.js build issue in recent updates

### ISSUE THREAD

**Issue by neilkinnish** [meetecho/janus-gateway#1378]
Is this correct? It's causing a build issue for me...

https://github.com/meetecho/janus-gateway/blob/c8975d1331bbeafb11e33fc15ad1dbe0e0438109/Makefile.am#L77

**Comment by lminiero** [comment]
Mh, this is from #1364 and now that you point it out I noticed issues too, so I think you're right: `jsmodules_DATA` is added to `CLEANFILES` as well, which means that any time you do a `make clean` the `janus.js` file will be removed. I'll fix this.

**Comment by lminiero** [comment]
The above commit should fix it.
