### ISSUE TITLE
memory leak in videoroom plugin/recorder

### ISSUE THREAD

**Issue by Will-I4M** [meetecho/janus-gateway#138]
I added in videoroom plugin (after L.1519) :

```
 
if(participant->arc) 
		{
			janus_recorder_close(participant->arc);
			JANUS_LOG(LOG_INFO, "[Unpublish] Closed audio recording %s\n", participant->arc->filename ? participant->arc->filename : "??");
		}
		participant->arc = NULL;
		if(participant->vrc) 
		{
			janus_recorder_close(participant->vrc);
			JANUS_LOG(LOG_INFO, "[Unpublish] Closed video recording %s\n", participant->vrc->filename ? participant->vrc->filename : "??");
		}

```

Not sure for now but it seems the recorder is not properly closed/freed when user "unpublish".

WM

**Comment by Computician** [comment]
Isn't it cleaned up when the session is closed?

**Comment by Will-I4M** [comment]
AFAIK, not the "first" file. If the user unpublish, only the last file is showed up in log. the "janus_recorder_close" seems to be called just one time for the last file.

**Comment by lminiero** [comment]
Yes, they are, but I guess William refers to unpublishing and publishing again within the same handle context. Looking at the code this may indeed result in leaked recorders, so it may make sense to move the ```janus_recorder_close``` stuff from ```janus_videoroom_destroy_session``` to ```janus_videoroom_hangup_media```, as the latter is related to a PeerConnection closing which should also result in any related recorder to be closed as well.

**Comment by lminiero** [comment]
By the way, L1519 doesn't seem at all related to unpublishing though? https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L1519

**Comment by Will-I4M** [comment]
Yes, they are, but I guess William refers to unpublishing and publishing again within the same handle context. -> Yes i do.

/* This publisher just 'unpublished' */ -> I'm sorry for the line, I add this quickly just after the : 
	while(participant->listeners)  
{ [....] } in janus_videoroom_hangup_media, 
The recoder_close fct is called, and I added a dbquery  too for my tests. (tests about the files generated by the recorder).

**Comment by lminiero** [comment]
Sorry for this late reply. So your initial suggestion was indeed to add the recorder close stuff to hangup_media as I said in an earlier post, right?

**Comment by Will-I4M** [comment]
Yes, sorry for the delay, i suggested to add the recorder_close into
hangup_media.

**Comment by lminiero** [comment]
This patch should address what you talked about and add a couple of frees as well. Closing the issue, let me know if this doesn't work as expected or breaks anything.
