### ISSUE TITLE
Feature request: audiobridge mute another user

### ISSUE THREAD

**Issue by dmakeev** [meetecho/janus-gateway#1387]
Hello!

Is it possible to add ability for user to mute another user for himself only?

For example, we have 4 users in group call: John, Tom, Kate and Mary. John can mute Mary for himself and listen only Tom and Kate, while other will listen all users. No volume adjustment needed, just mute certain user for selected user only. 

As I see in https://github.com/meetecho/janus-gateway/issues/668, it's not easy to adjust volumes of sertain users (and it's not needed), but removing separate audiostream is possible (as it's done for user own audio).

Thank you!]

**Comment by lminiero** [comment]
This was discussed already some time ago, so we have no immediate plan to work on that. We can add it to the TODO list, but I have to say it would be quite low on our priority list. Of course, as usual we're open to review pull requests.

**Comment by lminiero** [comment]
Closing as we don't plan to do that.
