### ISSUE TITLE
Unable to send properly formatted SIP "MESSAGE" message using the SIP plugin

### ISSUE THREAD

**Issue by dbrichards** [meetecho/janus-gateway#1388]
Hi.

I was playing with the sip (Sofia) plugin and discovered that I could not send a SIP "MESSAGE" message successfully to another SIP application (that happens to be based on PJSIP) .  Further investigation reveled that PJSIP was not happy with the message because it was expecting the Content-Type field, which is indeed required by the SIP RFC.

I was able to add the Content-Type tag by adding  **SIPTAG_CONTENT_TYPE_STR("text/plain")** to the nua_message() call in janus_sip.c:

 nua_message( session->stack->s_nh_i, NUTAG_URL(session->callee),  **SIPTAG_CONTENT_TYPE_STR("text/plain"),** SIPTAG_PAYLOAD_STR(msg_content), TAG_END() );

The same change should probably be made to janus_sipre.c for consistency, however, libre doesn't seem to support the SIP "MESSAGE" at all, even though it claims to.

**Comment by lminiero** [comment]
Thanks for the heads up! Makes sense, so I'll make the change right away. As to SIPre, you're right, we only have a [placeholder](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sipre.c#L4389) as we're not aware it supports SIP message either.
