### ISSUE TITLE
It would be great if the demos automatically created the 1234 room

### ISSUE THREAD

**Issue by awsmsrc** [meetecho/janus-gateway#140]

**Comment by LetsVape** [comment]
If you set the room in the janus.plugin.videoroom.cfg file it automatically creates this room, there is no need for me to send a request to create it.

**Comment by awsmsrc** [comment]
Ok I see that now,

**Comment by gatecrasher777** [comment]
Just a small problem in the room configuration documentation:  is_private needs a boolean value, not a "yes"/"no".  Using a "yes"/"no" causes room creation to fail.

**Comment by lminiero** [comment]
I recenty added a method called ```json_is_true``` which evaluates both true and yes from configuration values. Not sure whether we're using it everywhere as it sohuld, though. Unless you mean in the API? In that case, yes, we expect a boolean.

**Comment by gatecrasher777** [comment]
Ah, ok. The behaviour I was seeing was in the API room creation call.
