### ISSUE TITLE
Creating a RTSP Stream with or without an ID works randomly

### ISSUE THREAD

**Issue by Rakiah** [meetecho/janus-gateway#1401]
Hello,

I've been tweaking with Janus Gateway for RTSP Streaming,
i'm trying to change the demo version to make it work by passing in RTSP links directly in the query params of a webpage, this is working flawlessly for a single one but i'm having a lot of troubles making it work for passing multiple query params at the same time,

What i am doing basically is I am creating a new Janus for each rtsp link ->
```
			rtspLinks.forEach((i, j) =>
			{
				//let i = rtspLinks[0];
				//let j = 0;
				// Create session
				let janus = new Janus(
				{
server: server,
					success: function() {
						janus.attach(
						{
							plugin: "janus.plugin.streaming",
							opaqueId: "streamingtest-"+Janus.randomString(12),
							success: function(pluginHandle) {
								janus.streaming = pluginHandle;
								Janus.log("plugin init");
								Janus.log("Plugin attached! (" + janus.streaming.getPlugin() + ", id=" + janus.streaming.getId() + ")");
								startStream(i, janus.streaming, j);
							},
```
then, using the startStream function, i actually create a new RTSP endpoint using this code, and here starts the problem
```
function startStream(rtsp, streaming, j) {
	let streamId = Math.floor(Math.random() * (1000000 - 10 + 1)) + 0;
	Janus.log(streamId);
	Janus.log("---- Starting RTSP Stream: " + rtsp + " with ID: " + streamId);
        streaming.send(
	{
	  "message": { 
		  "request": "create",
		  "type": "rtsp",
		  "id": streamId,
		  "description" : "RTSP Test",
		  "video": true,
		  "url": rtsp,
		  "permanent": false,
	   },
	   success: function(response) {
		Janus.log("Selected video id #" + streamId);
		var body = { "request": "watch", id: parseInt(response.created) };
		streaming.send({"message": body});
		// No remote video yet
		$('#stream-' + j).append('<video class="rounded centered" id="waitingvideo-' + j + '" width=50% height=50% />');
		if(spinner == null) {
			var target = document.getElementById('stream-' + j);
			spinner = new Spinner({ top:100 }).spin(target);
		} else {
			spinner.spin();
		}
	   }
	 });
}
```
(My function to generate an ID will always generate a positive integer from 10 to 100000)
The above function works half of the time, sometimes i get the following error in the SUCCESS callback (this is already strange to have the error in the success callback right ?):
```
error: "Error creating 'RTSP' stream"
error_code: 456
streaming: "event"
__proto__: Object
```
I then looked through the janus codebase and saw this at `janus_streaming.cs:1503`
```
if(id == NULL || id->value == NULL) {
					JANUS_LOG(LOG_VERB, "Missing id for stream '%s', will generate a random one...\n", cat->name);
				} else {
```
So i supposed that I could let empty the ID, but then it get even worse, I still get the same error above but now even when i receive real success callback with a Janus generated ID, at some point it doesn't work because it put a asynchronous event saying that there was a missing param ID on a request

Do you guys have any idea about that ?

**Comment by lminiero** [comment]
It probably means your request is malformed in those cases when it doesn't work, and you should check what you're sending when it fails: maybe setting the message in a variable that you can print before sending it, or looking at the debugging on the JavaScript console. Anyway, closing as we only use Github to track bugs, and this looks more like a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.

**Comment by Rakiah** [comment]
It was actually linked to the fact that my RTSP link was not working, the error is, however, pretty unclear, but thanks
