### ISSUE TITLE
A few minor issues with the SIP plugin

### ISSUE THREAD

**Issue by dbrichards** [meetecho/janus-gateway#1404]
Greetings.

I've been playing around a bit more with the Sofia SIP plugin, and I am very pleased with what I've seen and been able to do so far with the Janus Gateway!  Thanks!  However, in my exploration, I have found a few things you might be interested in:

1) In the "missed_call" event, the SIP URI of the caller is contained in the "caller" field, not the "username" field as indicated in the SIP plugin API (https://janus.conf.meetecho.com/docs/sipsofia.html).

2) The "decline" request (that's used in siptest.js to decline an SIP incoming call) is not documented in the SIP plugin API. The documentation implies that the "hangup" request should be used.

3) On the support page (https://janus.conf.meetecho.com/support.html), the "GitHub repo" link seems to be broken.

Finally, I wasn't quite clear on how the SIP plugin works for incoming calls. It's quite possible I missed something in the documentation. If so, I apologize! Nevertheless, since the documentation seems sketchy in this area, I assumed that the SIP plugin, like many SIP gateway implementations, uses only one SIP stack, bound to one port well known (usually 5060) for incoming calls. With this arrangement, you can forgo registration with applications like mine where all SIP calls originate from one system and terminate on the WebRTC gateway.  I assumed that using guest registration would established a local mapping in Janus between the username and the user's WebRTC browser session.

However, if I understand the SIP plugin correctly, each user registered with the plugin is assigned a unique (randomly picked) port for incoming calls, and provided a private SIP stack instantiation with a one-to-one mapping to the user's Janus plugin session.  All incoming SIP calls to a particular user must be sent to that user's port. If guest registration is used, meaning no external registrar is utilized, no incoming calls can be sent to a user because the calling party doesn't know what port to send the call to.

I have no problems with this design and, my case, I've added a registrar and things work great! If the documentation had been a bit more detailed, I wouldn't have spend so much time chasing my tail!

**Comment by lminiero** [comment]
Thanks for the heads up: I'll fix the inconsistencies you found between the code and the docs by updating the docs (code is what really matters, of course).

As to your other point, yes, each SIP stack we instantiate uses a different port, and that's because the Janus SIP plugin is not a SIP server, it's a collection of independent SIP clients. I assume you thought it would do some trunking of sorts: while we've considered that in the past, we've never worked on that part, and to be honest it's quite low in our priority list.

> If the documentation had been a bit more detailed, I wouldn't have spend so much time chasing my tail!

Apologies, we were too busy writing the code :smile:
