### ISSUE TITLE
Probably a network error, is the server down?: [object Object]

### ISSUE THREAD

**Issue by yunhai2009** [meetecho/janus-gateway#1405]
1、sudo cp janus.transport.websockets.cfg.sample janus.transport.websockets.cfg
2、/opt/janus/bin/janus --debug-level=7 --log-file=$HOME/janus-log
3、进入到 janus 目录下的 html 目录，启动 http-server
环境是搭在VMware中的，操作系统是Ubuntu 16.04 ，访问web时测试Echo Test，结果提示Probably a network error, is the server down?: [object Object]。

**Comment by lminiero** [comment]
Not an issue, question for the group.

**Comment by yunhai2009** [comment]
@lminiero what do you mean?
