### ISSUE TITLE
Regression with audiobridge in commit ad94a0905acdb58caa9b8fcd185bea0fd6504873 ?

### ISSUE THREAD

**Issue by peffis** [meetecho/janus-gateway#1406]
Somehow the commit ad94a0905acdb58caa9b8fcd185bea0fd6504873 breaks audiobridge for me. Did someone else test it with this commit with audiobridge and managed to get audio through it? 

The audioroom service I am running works fine with commit 18c6891a395d44cccc440b777f10c003377f7811 but with this commit (ad94a0905acdb58caa9b8fcd185bea0fd6504873) there is never any answer returned from the plugin to the client (and for each candidate the plugins says that it is "Still waiting for answer").

**Comment by lminiero** [comment]
It was my fault, there was a neverending while... Should be fixed now.

**Comment by peffis** [comment]
Yes, works again now :)
