### ISSUE TITLE
GWakeup: too many open files

### ISSUE THREAD

**Issue by Rakiah** [meetecho/janus-gateway#1412]
Hello, after opening more than 64 RTSP stream to a single Janus instance,
I get at some point an error that crashes Janus:

![image](https://user-images.githubusercontent.com/16012885/47000490-aad84f80-d128-11e8-91fa-82f7265aca51.png)

![image](https://user-images.githubusercontent.com/16012885/47000502-b6c41180-d128-11e8-99df-5b41499cbd02.png)

**Comment by Rakiah** [comment]
Following this:
https://www.ibm.com/support/knowledgecenter/kk/SSRMWJ_6.0.0.2/com.ibm.isim.doc_6.0.0.2/trouble/cpt/cpt_ic_trouble_many_filesopen.htm

seems to have it fixed

**Comment by lminiero** [comment]
It's clearly addressed in the FAQ as well: https://janus.conf.meetecho.com/docs/FAQ#ulimit
Please read that and the documentation before opening issues.

**Comment by Rakiah** [comment]
@lminiero my apologies

**Comment by lminiero** [comment]
No worries, I was just pointing to some points where you might find more info in case you get issues again.
