### ISSUE TITLE
Janus try unlocking not locked mutex

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#1421]
Hi. I'm looking solution why crasing janus gw, when i send http transport request.
I think, janus trying unlock not locked mutex, and going to loop.

[link](https://gist.github.com/izemize/fad6295cb0a147f4fd6f39ba7a8e8998)

**Comment by izemize** [comment]
#1415

**Comment by samuelfr** [comment]
Hello,

Same bug for me

I tried to remove this line : https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_textroom.c#L1101
and it works without it

Here an other debug : https://justpaste.it/1ypic

**Comment by lminiero** [comment]
Good catch, probably a leftover from a previous fix/refactoring of that plugin, I'll fix it.
