### ISSUE TITLE
chrome plugin for desktop capture either froze crhome or broadcasted blank video.

### ISSUE THREAD

**Issue by riatzukiza** [meetecho/janus-gateway#1423]
Until after I removed the plugin, then installed it again. Now its working. I don't know if its a coincidence, or I actually solved the problem. 

I currently do not have issues, I am working on getting to the bottom of why it happened at all.

**Comment by lminiero** [comment]
The plugin is not part of the repo. Closing.

**Comment by lminiero** [comment]
Please refer to the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for questions like this.
