### ISSUE TITLE
some error during successful deployment/ execution of Janus gateway!

### ISSUE THREAD

**Issue by hsbrg** [meetecho/janus-gateway#1424]
Let me give you a little insight about my janus gateway implementation, The Janus is deployed on a GCP instance and I'm sending the stream through GStreamer via
raspberry pi.
[ERR] [plugins/janus_voicemail.c:janus_voicemail_init:345] Permission denied
[WARN] The 'janus.plugin.voicemail' plugin could not be initialized

so these are the error which displayed just after starting the server, by this command ./janus -F /opt/janus/etc/janus/

and there is this error message which keeps popping up: 
[ERR] [transports/janus_http.c:janus_http_handler:1215] Invalid url /ws/v1/cluster/apps/new-application

and it keeps coming after a minute or so, regardless the server is running fine and showing the stream over website without any issue!

**Comment by lminiero** [comment]
Closing as not an issue

**Comment by hsbrg** [comment]
@lminiero with all due respect can you share any thoughts regarding this, why I'm facing this?

**Comment by alexamirante** [comment]
This is food for the [group](http://groups.google.com/d/forum/meetecho-janus), as it's not a code issue.

That said:

> [ERR] [plugins/janus_voicemail.c:janus_voicemail_init:345] Permission denied
[WARN] The 'janus.plugin.voicemail' plugin could not be initialized

This is a permission error while initializing the recordings folder of the voicemail plugin (which you're probably not using and you better disable)

> [ERR] [transports/janus_http.c:janus_http_handler:1215] Invalid url /ws/v1/cluster/apps/new-application

This is some http BOT or crawler that is hitting the janus http server with random queries.

**Comment by michgboxy2** [comment]
it isn't some random bot, cos i'm having the same issue with my janus gateway implementation.

**Comment by johnmelodyme** [comment]
> Closing as not an issue

why janus community is so rude ?

**Comment by lminiero** [comment]
Why u no read guidelines?

**Comment by lminiero** [comment]
> **IMPORTANT! READ OR WE WILL JUST CLOSE YOUR ISSUE!**
>
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.
> 2. If you think you really found a bug, make sure nobody reported it already (do a search first, and check open issues);
> 3. Make sure the issue wasn't already solved in master: we will ignore the issue otherwise.
> 4. Do **NOT** paste large amounts of text inline in the issue or comments: it makes the exchanges much harder to follow. If you need to provide logs or code snippets, either use a service like [pastebin](http://pastebin.com/) and [gist](https://gist.github.com/), or use the `details` and code block Markdown features to collapse them.
> 5. If you're encountering crashes, make sure you provide a useful trace of what happened: depending on the issue, we may need output from AddressSanitizer or GDB stacktraces (more details available [here](http://janus.conf.meetecho.com/docs/debug)).
>
> If you understood the guidelines, please do remove this text and share your findings. Notice that if you remove this text without reading the guidelines, or you just ignore them, we'll close the issue without further explanation.
