### ISSUE TITLE
Feature request: audio sampling rate in videoroom plugin

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#1430]
Hi!

I would like stream high quality audio from external audio source (dj turntable) to videoroom subscribers.
Now audio quality is poor, and currently not configurable sample rate size.  I think this feature implemented to audiobridge, but videoroom no. Sorry for my english.

**Comment by lminiero** [comment]
The AudioBridge plugin decodes, mixes and re-encodes, so that's why it has a bitrate property. The VideoRoom doesn't touch the media at all, it just relays it around. As such, there's nothing it has to do to improve quality, that's up to browsers, who should already send media at 48khz if there's enough bandwidth. Closing.

**Comment by izemize** [comment]
Sorry, but no. I have 70Mbit/s upload speed, and audio quality is poor. I search with google and some users suggest add maxaveragebitrate to SDP. How to furce use highest bw in client?

**Comment by izemize** [comment]
I added required extra lines to SDP via javascript, but janus cut out from local SDP

b=AS:128000 a=rtcp:9 IN IP4 0.0.0.0
a=fmtp:111 minptime=10;useinbandfec=1; stereo=1; maxaveragebitrate=262144

How can i add this lines in janus backend?

**Comment by atyachin** [comment]
izemize - I'm trying to solve similar issue, did you find anything that could increase the audio bitrate in the video room?

**Comment by izemize** [comment]
> izemize - I'm trying to solve similar issue, did you find anything that could increase the audio bitrate in the video room?

Hi. As i say before, you need modify janus.js answer sdp and offer sdp with this lines: stereo=1; sprop-stereo=1; maxaveragebitrate=' + (256 * 1024) + '; x-google-min-bitrate=256; x-google-max-bitrate=256; cbr=1; It works for me.

**Comment by atyachin** [comment]
Hi izemize, 
my scenario is that I have a single participant in the room, so only createOffer is called (createAnswer is never called in my case).
I managed to insert those parameters in the offer sdp, however, is still doesn't work. 

In chrome://webrtc-internals/ I see the required parameters in setLocalDescription, however they don't appear in setRemoteDescription.

Any ideas where can I change the SDP before it's being passed to setRemoteDescription() ?
Or, is there something else I do wrong?

Thanks much.

**Comment by izemize** [comment]
If in the chrome webrtc-internals you see >40K output speed, you are done. Some other config needed, ex: set the room bandwidth, and the codec type before create it, and you need set optimal bitrate, and codec type in publish command. ( high quality audio works only for me with vp8 codec ) I attached my janus.js file, you need addStereo function if sendVideo is true.

[janus.zip](https://github.com/meetecho/janus-gateway/files/2738348/janus.zip)

**Comment by atyachin** [comment]
Nevermind, I found it!
For anyone interested, in Janus.js, you need to manipulate the SDP in 2 places:

1. just before config.pc.setRemoteDescription(jsep) in prepareWebrtcPeer(handleId, callbacks)
2. just after config.pc.createOffer(mediaConstraints) in createOffer(handleId, media, callbacks)
