### ISSUE TITLE
Crash on mobile (iOS Safari) connection

### ISSUE THREAD

**Issue by streamer45** [meetecho/janus-gateway#1434]
Hey there,

I just upgraded from 1.4.3 to 1.4.5 and encountered this issue. It seems to be triggered by my iphone connecting to janus. It doesn't happen when using a desktop browser. Everything worked smoothly on previous version (1.4.3). I've also tried on master (c31b3dced5370cc27bbba060a8eb13835afa8143) and I run into the same issue.

Here's the full log:

https://gist.github.com/streamer45/2d6d06cac9947dea89259fb1ac4d69e0

At other times I get a SEGV:

https://gist.github.com/streamer45/55d1a6c070bded6c58197367c7f6bf5a

Not sure if they are two separate bugs but they seem to happen at the same time, on connection.

**Comment by lminiero** [comment]
Please try master, as I won't debug revisions we may have already fixed. If still an issue, you can try using `git bisect` to isolate the commit that originally caused it.

**Comment by lminiero** [comment]
The log ends with a:

```
libnice:ERROR:agent.c:2391:agent_signal_component_state_change: assertion failed: (TRANSITION (DISCONNECTED, FAILED) || TRANSITION (GATHERING, FAILED) || TRANSITION (CONNECTING, FAILED) || TRANSITION (CONNECTED, FAILED) || TRANSITION (READY, FAILED) || TRANSITION (DISCONNECTED, GATHERING) || TRANSITION (GATHERING, CONNECTING) || TRANSITION (CONNECTING, CONNECTED) || TRANSITION (CONNECTED, READY) || TRANSITION (READY, CONNECTED) || TRANSITION (FAILED, CONNECTING) || TRANSITION (FAILED, GATHERING) || TRANSITION (DISCONNECTED, CONNECTING))
```
You're on an old version of libnice, they fixed it a long time ago. You should get libnice master from their gitlab repo, which also solves some performance issue.

**Comment by streamer45** [comment]
Alright, I guess I trusted a bit too much my distro to have a reasonably updated package.
I will try to compile libnice from master source and check if the problem disappears.
Thanks for the support.

**Comment by lminiero** [comment]
Notice that the repo to refer to is this: https://gitlab.freedesktop.org/libnice/libnice
The github mirror is out of sync and outdated.

**Comment by streamer45** [comment]
Yeah, I have noticed. I am using the gitlab master repo (commit 5496500b1535d9343fdac2a3408864643fe65d7e). I will report back shortly. Thanks again.

**Comment by streamer45** [comment]
Okay so on janus master compiled with libnice master I still get the segfault on connection.
This is the full backtrace:

https://gist.github.com/streamer45/7574e71a769b317daada203ae1a5cb98

I guess I could now try the `git bisect` option as you suggested and see if I can find a point where bug firstly appeared.

**Comment by streamer45** [comment]
Okay scratch what I just said. It appears to be working without issues now. I think it was still loading an old lib version somehow. I'll test some more but I think it might be all solved. Sorry about this :P

**Comment by lminiero** [comment]
Good to know updating libnice fixed it! It was still something everyone should do considering [this](https://groups.google.com/forum/#!topic/meetecho-janus/7vvkNxtyXX4).
