### ISSUE TITLE
SIP Plugin (Sofia) Chrome to Chrome call problem when using PCMU

### ISSUE THREAD

**Issue by balazsradak** [meetecho/janus-gateway#1435]
I started to test janus-gateway SIP plugin with Kamailio (Sipwise CE) and it works great, until I instruct Kamailio to use only PCMU enconding, so the SDP offer contains only this codec.

The problem only occurs when making calls from  Chrome to Chrome client, the call cannot be established when trying to accept the call, and the following error is shown on the called side:

> WebRTC error... {"stack":"Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. Failed to parse audio codecs correctly at RTCPeerConnection.e.RTCPeerConnection.(anonymous function) [as setRemoteDescription] (https://cdnjs.cloudflare.com/ajax/libs/webrtc-adapter/6.0.3/adapter.min.js:1:46586) at streamsDone (https://xxxxxx.xxx/janus.js:1694:14)\n at https://xxxxxx.xxx/janus.js:2215:8"}

I saw that there were same kind of issues, but I couldn't figure out what and where should I modify the configuration. Can someone be so kind to help me solve this issue?

With Opus codec it works jusk great, but thee application I use with Kamailio / RTPEngine needs to feed with PCMU codec.

Thanks!

**Comment by lminiero** [comment]
Can you share the SDP that causes the failure?

**Comment by balazsradak** [comment]
Here you can find from the janus.log : https://pastebin.com/aXABxLdR

**Comment by lminiero** [comment]
Apologies, I've been abroad for a couple of weeks and have just come back to the office. I'll try to replicate later and get back to you.

**Comment by lminiero** [comment]
I tried forcing ulaw only for a SIP user in Asterisk and generating a call to a Janus user, and it worked fine. My guess, looking at your SDP, is that Chrome doesn't like the rtcp-fb attribute, which points to a payload type that doesn't exist anymore:

    a=rtcp-fb:111 transport-cc

Have you checked if it's Kamailio that doesn't remove that attribute when pruning the unneeded payload types?

**Comment by lminiero** [comment]
@balazsradak any update on my question above?

**Comment by lminiero** [comment]
@balazsradak did you have some time to check my comment on the original issue?

**Comment by balazsradak** [comment]
> @balazsradak did you have some time to check my comment on the original issue?

Hi! I just checked the SIP INVITE and yes, I still have the **a=rtcp-fb:111 transport-cc** attribute in it.

**Comment by lminiero** [comment]
I mean, is the application you were using the one that didn't remove it? Or one of the modules in Kamailio?

**Comment by balazsradak** [comment]
It is the Kamailio which doesn't remove it:

v=0
o=- 1901025048 32729 IN IP4 104.248.52.83
s=-
t=0 0
m=audio 30972 RTP/AVP 0
c=IN IP4 xxx.xxx.xxx.xxx
a=rtpmap:0 PCMU/8000
a=sendrecv
a=rtcp-fb:111 transport-cc
a=rtcp:30973
a=direction:both

Actually I'm using Sipwise CE and configuring it via browser, but  I'll test it with the latest Kamailio, hopefully  next week will have time for it.

**Comment by lminiero** [comment]
Thanks! In case, let us know which application and/or module is doing that, so that we can notify the developers about the potential bug.

**Comment by lminiero** [comment]
Closing.
