### ISSUE TITLE
Crash on latest master 0.5.0 libnice-0.1.13

### ISSUE THREAD

**Issue by BellesoftConsulting** [meetecho/janus-gateway#1437]
I am reporting a crash on latest master (commit 6b916658a88e29a0991007f6f79b6961ee02c784)

BT here: https://pastebin.com/B6XSu5BY
Relevant Janus log around the crash here: https://pastebin.com/1xBqp2rf

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe68b642764 in janus_videoroom_hangup_media (handle=0x0) at plugins/janus_videoroom.c:4428

This machine is running with libnice-0.1.13 (As it is a Debian Jessie, can't put libnice master on it easily.)  v0.4.5 seems stable there tho...

**Comment by atoppi** [comment]
It seems that Janus is closing all the ongoing sessions because of expiring timeouts. I can spot at least one `timeout expired` message, and that means that a client stopped sending keepalives.
Was this intentional?
What the scenario was here?
Was the server under heavy load?

**Comment by BellesoftConsulting** [comment]
Not intentional afaik... 

Yes it s a busy server, but normal load about 400 connections. (it has been running Janus v0.4.2 , v0.4.4 and v0.4.5 without issues for many many months under the same load, without crashes.  We have a video room that a presenter shares to, and then we rtp forward the stream to a streaming plugin endpoint.  I see timeout expired quite often, currently watching the logs on the same server on v.0.4.5, no crashes...

**Comment by atoppi** [comment]
@BellesoftConsulting  Can you try with `master` again? We've pushed a specific fix for this issue.

**Comment by lminiero** [comment]
@BellesoftConsulting any update on this?

**Comment by BellesoftConsulting** [comment]
will install this in production tomorrow , sorry for the delay

**Comment by lminiero** [comment]
Closing as I assume it's fixed now. Please let us know if it's still an issue.
