### ISSUE TITLE
Simulcast SDP munging bugs

### ISSUE THREAD

**Issue by danbriggs5** [meetecho/janus-gateway#1439]
Just playing around with simulcast at the moment. Noticed a few small issues in the [simulcast sdp munging function](https://github.com/meetecho/janus-gateway/blob/65c36f5cf6143d30f6b04e9b03c9381ae0fc5d04/html/janus.js#L2920) inside janus.js. 

If no `a=ssrc-group:FID` line is found in the sdp, then this [block](https://github.com/meetecho/janus-gateway/blob/65c36f5cf6143d30f6b04e9b03c9381ae0fc5d04/html/janus.js#L2991-L3058) will run and `ssrc_fid[0]` will remain as -1. That causes the attributes in the first RTX SSRC substream to look something like this: `a=ssrc:-1 mslabel:jYnEMKLYYUXnl0qOr9D00m4oLubmMNVzgldT
`. Chrome will throw an error when calling `pc.setLocalDescription()` since -1 is an invalid SSRC. 

Can simulcast still be enabled when no `a=ssrc-group:FID` line is found? Or should we just return the original sdp instead? Also, just out of curiosity, how common is it for this line to be left out? Will this ever happen?

Perhaps we could create a random SSRC for the RTX of the first substream similar to [what is done for the 2nd and 3rd](https://github.com/meetecho/janus-gateway/blob/65c36f5cf6143d30f6b04e9b03c9381ae0fc5d04/html/janus.js#L3070-L3073) substreams? I tried this and it didn't work, but that may be because I'm manually removing the `a=ssrc-group:FID` line before munging to test it. Perhaps a browser that doesn't have it by default would work with a random RTX SSRC on the first stream.

Happy to make a PR if changes are needed. Just let me know!

One other little thing. [This line](https://github.com/meetecho/janus-gateway/blob/65c36f5cf6143d30f6b04e9b03c9381ae0fc5d04/html/janus.js#L2973) and [this line](https://github.com/meetecho/janus-gateway/blob/65c36f5cf6143d30f6b04e9b03c9381ae0fc5d04/html/janus.js#L2977 ) should probably be `ssrc[0]` and `ssrc_fid[0]` respectively. Its not really a bug since js will automatically grab the first element, but definitely cleaner 👍

**Comment by lminiero** [comment]
The FID group is the one Chrome uses to advertise rtx, so the proper way of doing retransmissions (separate SSRC space for retransmitted packets). I'm not sure why in your case Chrome is not using them, since AFAIK they're always enabled. Anyway, yes, at the moment I think the simulcast code relies on that attribute to be present, as otherwise it's harder to figure out if an SSRC we see is the "main" one or not.

**Comment by ibc** [comment]
> Anyway, yes, at the moment I think the simulcast code relies on that attribute to be present, as otherwise it's harder to figure out if an SSRC we see is the "main" one or not.

If there is no `a=ssrc-group` line then you safely assume that any existing `a=ssrc` lines means a common stream SSRC.

**Comment by lminiero** [comment]
Good point :+1: 
Anyway, not sure why that FID group doesn't appear at times: I don't think I ever saw that happening (unless it's one of those "let's enable unified plan randomly" bugs?)

**Comment by ibc** [comment]
I've always seen the FID group. I cannot figure out how to make Chrome to not generate it (may be just in SDP answers when the offer does not support RTX).

**Comment by lminiero** [comment]
Yeah but enabling simulcast in answers never worked anyway, I think (and it's disabled in our JavaScript code).

**Comment by danbriggs5** [comment]
I should note, the FID group is always generated for me as well. I just noticed that the custom code to handle that case won't work as expected. I should have been clearer about that in the question.

If the FID group will always be generated, I think we can safely remove this [block](https://github.com/meetecho/janus-gateway/blob/65c36f5cf6143d30f6b04e9b03c9381ae0fc5d04/html/janus.js#L2991-L3058). But if you guys think it's possible that an FID group won't be generated for some users then we should probably update the code to make sure it handles that case.

**Comment by fippo** [comment]
> Yeah but enabling simulcast in answers never worked anyway

Works fine here.

Alas, it would have been great of there was at non-standard chrome constraint instead of keeping multiple projects busy writing their own munging :-)

**Comment by lminiero** [comment]
> Works fine here.

Ah, that's weird: looking at the old PR, I wrote

    I tried enabling simulcasting in a createAnswer and, while it didn't fail,
    it resulted in no video being sent by the browser, so I can only assume
    it's not supported.

I guess it might have been a bug they since fixed?

> Alas, it would have been great of there was at non-standard chrome constraint instead of keeping multiple projects busy writing their own munging :-)

At least Firefox does it properly!

**Comment by lminiero** [comment]
> If the FID group will always be generated, I think we can safely remove this [block](https://github.com/meetecho/janus-gateway/blob/65c36f5cf6143d30f6b04e9b03c9381ae0fc5d04/html/janus.js#L2991-L3058).

Yeah, I checked the code and that block does indeed get the video SSRC to use that as a basis for simulcasting, which means it works anyway even if FID isn't there. I'd rather keep the block in, just as a backup: it does no harm.

**Comment by lminiero** [comment]
I fixed the lines @danbriggs5 pointed at towards the end of his first post: I'm not going to change the way we handle FID, though, as in Chrome it will always be there. Closing, please let me know if I missed something.
