### ISSUE TITLE
Possible Memory leak in janus_videoroom_init(plugins/janus_videoroom.c)

### ISSUE THREAD

**Issue by lqp276** [meetecho/janus-gateway#1445]
in **plugins/janus_videoroom.c**, function **janus_videoroom_init**

```C
/* Launch the thread that will handle incoming messages */
	error = NULL;
	handler_thread = g_thread_try_new("videoroom handler", janus_videoroom_handler, NULL, &error);
	if(error != NULL) {
		g_atomic_int_set(&initialized, 0);
		JANUS_LOG(LOG_ERR, "Got error %d (%s) trying to launch the VideoRoom handler thread...\n",
			error->code, error->message ? error->message : "??");
		janus_config_destroy(config);
		return -1;
	}
	JANUS_LOG(LOG_INFO, "%s initialized!\n", JANUS_VIDEOROOM_NAME);
	return 0;
```

The **error** pointer is initialize to NULL, and populated by **g_thread_try_new**, which means this object is allocated by glib, but there is no matching **free**,I looked up the code of glib2.48.2, this error object could be freed by **g_error_free**. 
Hope this helps.

**Comment by lminiero** [comment]
Looking at the [GError documentation](https://developer.gnome.org/glib/stable/glib-Error-Reporting.html) it looks like you're right. I'll take note of this. Thanks!

**Comment by lminiero** [comment]
I added the fix to a larger branch I'm working on, which includes many fixes and a considerable refactoring.
