### ISSUE TITLE
Possible typo in if check condition in function janus_rtcp_link_quality_filter

### ISSUE THREAD

**Issue by lqp276** [meetecho/janus-gateway#1448]
in file **rtcp.c** line: **139**

```C
static double janus_rtcp_link_quality_filter(double last, double in) {
	if (last == 0 || last != last) {
		return in;
	} else {
		return (1.0 - 1.0/LINK_QUALITY_FILTER_K) * last + (1.0/LINK_QUALITY_FILTER_K) * in;
	}
}
```

In the **if (last == 0 || last != last)** check, **last != last** will always be false. 
In my understanding of these code, may be it's checking **last == in** and thus skip the adjust between last and current value?
Hope this helps!

**Comment by lminiero** [comment]
Mh, looks like the typo has been there since the beginning, when @pitkonst submitted #1168. I don't see any other value you can compare to, so I think that additional check can safely be removed: @pitkonst can you confirm?

**Comment by lminiero** [comment]
I'll make the change you suggested, as @atoppi also agrees it would fix it. Thanks for spotting this!

**Comment by pitkonst** [comment]
Check last != last is a check for a NaN. It is true when last is NaN. Sorry, I should added comment for this one.

**Comment by lminiero** [comment]
Looking around, it looks like the check you do is the one most people do:

    According to the IEEE standard, NaN values have the odd property that comparisons involving
    them are always false. That is, for a float f, f != f will be true only if f is NaN.
    
    Note that, as some comments below have pointed out, not all compilers respect this when
    optimizing code.

Apparently in math.h there is an [isnan()](https://en.cppreference.com/w/c/numeric/math/isnan) function, but considering I have no idea how widespread it is, we can just leave it as it is.
