### ISSUE TITLE
janus_streaming.c error in Rtsp PLAY command?

### ISSUE THREAD

**Issue by Phil1972** [meetecho/janus-gateway#1460]
Hi,

I just want to report an issue with the janus streaming plugin regarding an Rtsp source.

The proper format for the "Range:" for the Rtsp PLAY is not properly formatted and causes parsing error on some Rtsp servers.  Maybe I am wrong, but I went through the spec and cannot find a case for just putting a number.

Instead of the current "Range: 0.000-" it should be "Range: npt=0.000-" or any of the 3 possible options: clock, npt, smpte

	curl_easy_setopt(source->curl, CURLOPT_RANGE, "0.000-");

should be changed to:

	curl_easy_setopt(source->curl, CURLOPT_RANGE, "npt=0.000-");

thanks,

**Comment by lminiero** [comment]
Thanks for the heads up, I was unaware of this problem. Looking at the spec, though, I see you can also use `utc` or `smtpe` in the `Range:` property: wondering if `ntp` will indeed be fine for all RTSP servers?

**Comment by Phil1972** [comment]
Yes, true, I read the RFC: https://tools.ietf.org/html/rfc7826#page-162
maybe I forgot some details but it should all be in there.
Is it possible to fix this?

thanks for your quick reply.

**Comment by lminiero** [comment]
> Is it possible to fix this?

I can add the change, but as I said, I need to be sure we wouldn't break other servers. If you have many to test against, can you check if setting `ntp=` in the `curl_easy_setopt` call works with all of them, or if other options are better? If it does, I'll commit the fix you suggested.

**Comment by Phil1972** [comment]
I just went ahead and tested with as many Rtsp servers that I have here (mainly Rtsp streams from IP cameras), vlc and our in-house rtsp server and it seems to work fine.

**Comment by lminiero** [comment]
Ack, thanks for testing! I used the `npt=` syntax (which I thought was `ntp` but is actually `ntp`, as in Normal Play Time... you always learn something new!)

**Comment by Phil1972** [comment]
Thanks!
