### ISSUE TITLE
Update README.md. 

### ISSUE THREAD

**Issue by kuzm1ch** [meetecho/janus-gateway#1461]
Could you check issue which was closed.  I've expend it in more detail.
https://github.com/meetecho/janus-gateway/issues/1449
Thanks.

**Comment by lminiero** [comment]
Please update your issue with the details here.

**Comment by kuzm1ch** [comment]
**1. release candidate OpenSSL conflict with to libcurl2.0** 
```
openssl:
  Installed: 1.1.0g-2ubuntu4.1
  Candidate: 1.1.0g-2ubuntu4.1
  Version table:
 *** 1.1.0g-2ubuntu4.1 500
        500 http://ua.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0g-2ubuntu4 500
        500 http://ua.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```
 With openssl 1.1.0 version we have a problem during building libsrtp 2.0.0(the same for 1.5.x).
cisco/libsrtp#394 . 
Libsrtp should be changed to 2.2.0.

**2.  delete  note** 
`Note: when installing libsrtp, no matter which version, you may need to pass --libdir=/usr/lib64 to the configure script if you're installing on a x86_64 distribution.` 
There is no configure option for libsrtp 2.2. like --prefix and --libdir and it should be deleted 
 https://github.com/cisco/libsrtp 

```
wget https://github.com/cisco/libsrtp/archive/v2.2.0.tar.gz
tar xfv v2.2.0.tar.gz
cd libsrtp-2.2.0
./configure  --enable-openssl
make shared_library && sudo make install
```
**3. need to add some dependency to installation command( i have check this on Fedora 28)** 

a) libnice-devel 
need to have develop version of libnice package 

b) glib2 

take  this from code
```
 if test -n "$PKG_CONFIG" && \
    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"
                    glib-2.0 >= \$glib_version
                    jansson >= \$jansson_version
                  \""; } >&5
```

```
yum install libmicrohttpd-devel jansson-devel \
   openssl-devel libsrtp-devel sofia-sip-devel glib-devel glib2 \
   libnice-deve opus-devel libogg-devel libcurl-devel pkgconfig gengetopt \
   libconfig-devel  libtool autoconf automake 
```

**Comment by lminiero** [comment]
libnice is not listed in the yum/apt-get shortcut because we explicitly recomment manually installing from their gitlab master.

**Comment by lminiero** [comment]
> Libsrtp should be changed to 2.2.0.

Have you verified it works as expected with 2.2.0? I can't remember which version we're shipping in production, and I don't want to suggest something if I'm not sure it's ok.

> There is no configure option for libsrtp 2.2. like --prefix and --libdir and it should be deleted

I think you're wrong. They might not be listed in the libsrtp README documentation, but those are standard properties in autoconf, and I see them mentioned in the Makefile.in.

> a) libnice-devel

As I said in my previous comment, it's not there because it's suggested to install it manually.

> b) glib2

Isn't this installed automatically when you install glib-devel? I'm on Fedora 28 myself, but I use XFCE, which means glib comes already installed in my setup.

**Comment by alexamirante** [comment]
>>  Libsrtp should be changed to 2.2.0.

> Have you verified it works as expected with 2.2.0? I can't remember which version we're shipping in production, and I don't want to suggest something if I'm not sure it's ok.

We use libsrtp 2.2.0 in production.

>> b) glib2

> Isn't this installed automatically when you install glib-devel?

Yes, it is.

**Comment by lminiero** [comment]
Ok, made the changes. For glib, I changed `glib-devel` to `glib2-devel` that should fix it.
