### ISSUE TITLE
Include Janus version in the reply of a successfully created transport session

### ISSUE THREAD

**Issue by tgabi333** [meetecho/janus-gateway#1462]
In this case APIs could handle the changed and deprecated communication eg: https://github.com/meetecho/janus-gateway/blob/c8ee38780a6cdb75e3c459238c65b078273d60bd/plugins/janus_videoroom.c#L4973

**Comment by tgabi333** [comment]
Thank Lorenzo, we will use it. Do you think it would be a communication shortcut if it would be included in the successfully connected message?

**Comment by lminiero** [comment]
I don't think adding it there by default is a good idea, it's incredibly verbose. Besides, it depends on what you mean by successfully connected: if you use HTTP there's no connection at all.

**Comment by tgabi333** [comment]
thanks
