### ISSUE TITLE
Add event type JANUS_EVENT_TYPE_TRANSPORT_MESSAGE

### ISSUE THREAD

**Issue by redexp** [meetecho/janus-gateway#1467]
Hello, what do you think about adding new event type for each transport message. Something like rewrite function in `janus.c`
```c
void janus_session_notify_event(janus_session *session, json_t *event) {
	if(session != NULL && ...) {
		session->source->transport->send_message(session->source->instance, NULL, FALSE, event);
		janus_events_notify_handlers(JANUS_EVENT_TYPE_TRANSPORT_MESSAGE, session->session_id, handle->handle_id, event);
	} else {
		...
	}
}
```
I have two reasons for that. First - I don't want to convert internal events to events that get in browser (transport messages). Second - I want to make my own transport, but I don't want to write C code, so what I do is using http transport (just for posting actions) and listen for events through `eventhandler.sampleevh` and deliver them in my own way.

**Comment by lminiero** [comment]
I'm sorry, but I didn't understand what you want changed or how. You'll have to be clearer than that.

**Comment by redexp** [comment]
@lminiero I have mobile app and when it goes sleep I need to disconnect janus client but session and handle on server should be alive (for 20 min) and once per 15 min my app woke up, sends ping to server and goes sleep again. Right now I can't do this with websockets transport because when connection closed it destroy session. That's why I'm using http transport (because it not destroys session if client is not connected) + eventhandler.sampleevh (to store events, send push notifications on incomingcall) + sockets on my own server (to send events to client in realtime when mobile app is woke up).

My first problem was issue with sdp #1466 because without it I can't send to client correct jsep, but if you will add this new event type than I no need to fix sdp because all events already will be in correct condition to send them to client.

**Comment by lminiero** [comment]
These are all things you can do simply with an API wrapper: you have a server side application connect to Janus (e.g. using WebSockets) and that exposes your own API to end users. This way, you're free to allow user disconnections (using your API) and yet still keep the Janus sessions alive. As such, I don't think we need to change anything.

**Comment by redexp** [comment]
But it not solves problem with incorrect sdp in jsep

**Comment by lminiero** [comment]
I don't understand what's incorrect in the SDP we send, since it works in all browsers.

**Comment by redexp** [comment]
@lminiero janus send to browser "sdp_merged" (made with janus_plugin_handle_sdp) and in internal event janus send pure "sdp"

**Comment by lminiero** [comment]
Oh, you're right, we're sending the SDP from the plugin before it's been enriched by the core, I've fixed that.
