### ISSUE TITLE
events: Missed loop optimization

### ISSUE THREAD

**Issue by tmatth** [meetecho/janus-gateway#1472]
I'm seeing the following warning when building the latest master (commit 43fcfbe309b9153ec6901c1c8dbedc7dfc406aac):
```
events.c: In function ‘janus_events_edit_events_mask’:
events.c:349:12: warning: missed loop optimization, the loop counter may overflow [-Wunsafe-loop-optimizations]
       while(ev) {
            ^
events.c: In function ‘janus_events_type_to_label’:
events.c:371:7: warning: missed loop optimization, the loop counter may overflow [-Wunsafe-loop-optimizations]
  while(ev) {
       ^
events.c: In function ‘janus_events_type_to_name’:
events.c:381:7: warning: missed loop optimization, the loop counter may overflow [-Wunsafe-loop-optimizations]
  while(ev) {
       ^
```

To reproduce, build with e.g., gcc 7.3.0 and -O1.

Not super high priority as I don't think `ev` can actually overrun here, but maybe a different loop invariant should be used.

**Comment by lminiero** [comment]
Not sure what can be done to fix this or even what exactly the issue is, as I've never encountered that warning. If you can think of a fix to submit, I'll gladly review it, otherwise it's definitely low priority in light of the unified plan stuff for me now.

**Comment by lminiero** [comment]
Maybe the issue is that `event_types_string` doesn't have a NULL as the last element?

**Comment by lminiero** [comment]
And you thought of that already :smile: 
Thanks for the quick fix!

**Comment by tmatth** [comment]
@lminiero exactly, `ev` would never be NULL.
