### ISSUE TITLE
Janus gateway To Asterisk for PSTN calling

### ISSUE THREAD

**Issue by sandeep2244** [meetecho/janus-gateway#1479]
Hello,

When i try this [https://janus.conf.meetecho.com/siptest.html]() demo .... I registered my asterisk server details in JANUS gateway .... with plain secret registration method .... It registered 
but i cant call PSTN mobile number, it only ask to SIP URI for calling

How can i call to PSTN number with (ASTerisk SIP server details)  in janus gateway 

Thank you

**Comment by lminiero** [comment]
Closing as not a code issue, question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
