### ISSUE TITLE
Janus not including track SSRC in answer SDP

### ISSUE THREAD

**Issue by tobiasfriden** [meetecho/janus-gateway#1483]
Im am trying to connect with Janus using the python library `aiortc`.
However, it requires that the track SSRC is included in the answer sdp, which seems to not be the case with janus.

Outgoing SDP: https://pastebin.com/3m885fVg
Received SDP from Janus: https://pastebin.com/079markx

More discussion here: https://github.com/jlaine/aiortc/issues/114

**Comment by lminiero** [comment]
If we're not going to send anything (I see recvonly in the Janus SDP) we don't advertise any SSRC. Not a bug, closing.
