### ISSUE TITLE
macOS Install Instructions Broken (libdl)

### ISSUE THREAD

**Issue by euskadi31** [meetecho/janus-gateway#1486]
Hello,

I followed the installation instructions for macOS and I had a problem with the`./configure`

My Env:

```
uname -a
Darwin MacBook.local 18.2.0 Darwin Kernel Version 18.2.0: Fri Oct  5 19:41:49 PDT 2018; root:xnu-4903.221.2~2/RELEASE_X86_64 x86_64
```

Configure log
```
./configure --prefix=/usr/local/janus PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
...
checking for library containing tls_config_set_ca_mem... no
checking for nice_agent_set_port_range in -lnice... no
configure: libnice version does not have nice_agent_set_port_range
checking for nice_address_equal_no_port in -lnice... no
configure: libnice version does not support TCP candidates
checking for dlopen in -ldl... no
configure: error: libdl not found.
```

Thank you

**Comment by atacand1920** [comment]
same

**Comment by lminiero** [comment]
I don't own a Mac, and those instructions never changed, so no idea why they're not working for you (they seem to do for others). You may want to ask on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for help.

**Comment by atacand1920** [comment]
because of macOS 10.14 and no , it's not working with that instructions for me and for him.

**Comment by lminiero** [comment]
Yeah, as I said, I don't own a Mac so I can't help. Use the forum as I suggested, as most of the Janus users don't follow the github issues.

**Comment by vsimon** [comment]
Contrary case, I'm running macOS 10.14 and the build seems to work, ./configure works, `make` works with master.

```
uname -a
Darwin MacBook.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
```

Configure log

```
./configure --prefix=/usr/local/janus PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
...
checking for
                    glib-2.0 >= 2.34
                    nice
                    jansson >= 2.5
                    libssl >= 1.0.1
                    libcrypto
                  ... yes
checking for library containing tls_config_set_ca_mem... no
checking for nice_agent_set_port_range in -lnice... yes
checking for nice_address_equal_no_port in -lnice... yes
checking for dlopen in -ldl... yes
...
```

My brew list
```
brew list
bdw-gc          gettext         gmp             gstreamer       icu4c           libevent        libtasn1        libusrsctp      openssl         pcre2           srtp
autoconf        automake        git             gnutls          guile           jansson         libffi          libtool         nettle          p11-kit         pkg-config
autogen         bash-completion gengetopt       glib            libnice         libunistring    node@10         pcre            readline
```

Do you have /usr/lib/libdl.dylib? Are you trying to build master?

```
file /usr/lib/libdl.dylib
/usr/lib/libdl.dylib: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit dynamically linked shared library x86_64] [i386:Mach-O dynamically linked shared library i386]
/usr/lib/libdl.dylib (for architecture x86_64): Mach-O 64-bit dynamically linked shared library x86_64
/usr/lib/libdl.dylib (for architecture i386):   Mach-O dynamically linked shared library i386
```

**Comment by xntop** [comment]
Darwin xxx.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for
                    glib-2.0 >= 2.34
					libconfig
                    nice
                    jansson >= 2.5
                    libssl >= 1.0.1
                    libcrypto
                  ... yes
checking for library containing tls_config_set_ca_mem... no
checking for nice_agent_set_port_range in -lnice... no
configure: libnice version does not have nice_agent_set_port_range
checking for nice_address_equal_no_port in -lnice... no
configure: libnice version does not support TCP candidates
checking for dlopen in -ldl... no
configure: error: libdl not found.

**Comment by atacand1920** [comment]
@vsimon  i followed your step and your homebrew list and always the same configure:error: libdl not found, can you send me the full steps for macOS mojave 10.14.2 ?

**Comment by vsimon** [comment]
Not good news. Today I just tried to retrace the same commands (autogen.sh, configure) again on the same 10.14.2 machine after a git clean, and I'm hitting the same error again. I don't have an explanation as to why I wasn't running into 'libdl not found' and what could have changed from yesterday to today. So I'm currently seeing what you're seeing.

**Comment by atoppi** [comment]
The culprit might be [this line](https://github.com/meetecho/janus-gateway/blob/master/configure.ac#L74) from `configure.ac`.
That ld option name for MacOS should be `-Wl,-export_dynamic`.
@vsimon @atacand1920 can you try replacing that lines in `configure.ac` with the right MacOS value, in this way
```
# add rdynamic to LDFLAGS
LDFLAGS="$LDFLAGS \
	-Wl,-export_dynamic"

```
recompile from scratch, and see if that helps?

**Comment by vsimon** [comment]
Thanks, @atoppi, that's it! configure gets past the dlopen check successfully.

```
diff --git a/configure.ac b/configure.ac
index 59c42bce..f454c742 100644
--- a/configure.ac
+++ b/configure.ac
@@ -71,7 +71,7 @@ AM_COND_IF([USE_CLANG],

 # add rdynamic to LDFLAGS
 LDFLAGS="$LDFLAGS \
-       -Wl,--export-dynamic"
+       -Wl,-export_dynamic"

 JANUS_VERSION=60
 AC_SUBST(JANUS_VERSION)
```

**Comment by vsimon** [comment]
Pulled and everything works as expected. thanks @atoppi
