### ISSUE TITLE
SDP parsing issue "Missing mandatory lines (o=, s= or m=)"

### ISSUE THREAD

**Issue by petergerten** [meetecho/janus-gateway#1496]
I am using the gstreamer webrtc implementation to talk to janus. For video that works. Now I am trying to add a datachannel and send the following SDP answer to janus: https://pastebin.com/K2C8WmEK

Janus gives me the following error:
```
[ERR] [sdp-utils.c:janus_sdp_parse:542] Missing mandatory lines (o=, s= or m=)
[ERR] [sdp.c:janus_sdp_preparse:36]   Error parsing SDP? Missing mandatory lines (o=, s= or m=)
```

There is probably something wrong with the SDP provided - I just could not figure out what.
In any case the error message is a bit ambiguous as all of the lines mentioned are present in the SDP.

**Comment by lminiero** [comment]
Are you sure Gstreamer supports datachannels in the first place?

**Comment by petergerten** [comment]
@lminiero yes, gstreamer supports datachannels in master - will be available in the upcoming 1.16 release

```
-   GStreamer WebRTC stack gained support for data channels for
    peer-to-peer communication based on SCTP, BUNDLE support, as well as
    support for multiple TURN servers.
```

src: https://gitlab.freedesktop.org/gstreamer/gst-plugins-good/blob/master/NEWS

**Comment by petergerten** [comment]
Ok, I will check why datachannels got rejected.

Regarding the parsing issue - do you have a suggestion on how I can debug that?

**Comment by lminiero** [comment]
> Regarding the parsing issue - do you have a suggestion on how I can debug that?

I tried giving the string you provided to `janus_parse_sdp` and it worked fine, so it may be something that happens after we "anonymize" the SDP to pass it to the plugin. I'll have a look when I have some time.

I assume you're using master, right? I won't do anything if you didn't test the latest code.

**Comment by petergerten** [comment]
@lminiero I use a bit customized code - let me reproduce this with a clean master version and I will come back to you.

**Comment by lminiero** [comment]
Closing as I assume this has been fixed. Feel free to reopen if that's not the case.
