### ISSUE TITLE
if i add streaming plugin permanent info, then janus segment fault 

### ISSUE THREAD

**Issue by kimilpyoung** [meetecho/janus-gateway#1497]
i used api and send 
{ request: 'create',
  type: 'rtp',
  id: 33,
  description: 'domain',
  audio: true,
  video: true,
  audioport: 9000,
  audiopt: 111,
  audiortpmap: 'opus',
  videoport: 5800,
  videopt: 96,
  videortpmap: 'VP8',
  permanent: true }
 to my janus server 

but janus is down with "Saving mountpoint 33 permanently in config file
Starting streaming relay thread
segmentation fault  (core dumped)"

permenent : false is not error, but only true occured error

Did I put anything wrong?

**Comment by kimilpyoung** [comment]
i used websocket, and  disappears text in streaming.jcfg file  when an error occurs

**Comment by lminiero** [comment]
Please provide a gdb stacktrace or a libasan dump.

**Comment by kimilpyoung** [comment]
**this is core file gdb stack text**

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `bin/janus'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fd939d98dbc in config_setting_set_string ()
   from /lib64/libconfig.so.9

chat where

(gdb) where
#0  0x00007fd939d98dbc in config_setting_set_string () at /lib64/libconfig.so.9
#1  0x000000000041a5fb in janus_config_save_list (config=config@entry=0x1480140, file=file@entry=0x7fd8ec0030c0, level=level@entry=1, list=<optimized out>, lcfg=lcfg@entry=0x0, array=0) at config.c:572
#2  0x000000000041a676 in janus_config_save_list (config=config@entry=0x1480140, file=file@entry=0x7fd8ec0030c0, level=level@entry=0, list=<optimized out>, lcfg=0x7fd8ec003070, array=0) at config.c:604
#3  0x000000000041c149 in janus_config_save (config=0x1480140, folder=<optimized out>, filename=filename@entry=0x7fd9225f4e2d "janus.plugin.streaming")
    at config.c:667
#4  0x00007fd9225ede51 in janus_streaming_handle_message (handle=<optimized out>, transaction=0x7fd8ec0010c0 "VlMWxGv1jHlp", message=0x7fd8fc000de0, jsep=0x0)
    at plugins/janus_streaming.c:2820
#5  0x00000000004465b3 in janus_process_incoming_request (request=0x7fd8fc003c80) at janus.c:1328
#6  0x000000000044aabd in janus_transport_task (data=0x7fd8fc003c80, user_data=<optimized out>) at janus.c:2611
#7  0x00007fd9392b9e8c in g_thread_pool_thread_proxy ()
    at /lib64/libglib-2.0.so.0
#8  0x00007fd9392b94f0 in g_thread_proxy () at /lib64/libglib-2.0.so.0
#9  0x00007fd937dcddd5 in start_thread () at /lib64/libpthread.so.0
#10 0x00007fd937af6ead in clone () at /lib64/libc.so.6

i show this message debugging core file

**Comment by lminiero** [comment]
As it's written pretty much everywhere, PLEASE DO NOT write dumps inline! They mess up references to old issues, and make issues unreadable. I've edited the formattation for you, I'll simply close the issue next time.

**Comment by kimilpyoung** [comment]
sorry for my mistake.. I'll be careful next time.

So.. you know anything about the cause?

Is it just a bug? Or is it my server problem?

**Comment by perlethandersen** [comment]
I have the same issue. Whenever I try to create a mountpoint permanently to the configuration, I get segmentation fault. Happens locally as well as on my server.

[Backtrace](https://gist.github.com/perlethandersen/1d6e6b0e0ecdbbf927bec35e2f3943e7)
[address sanitizer](https://gist.github.com/perlethandersen/6b96c088880bdbfe8feb5c0112bb5963)

**Comment by lminiero** [comment]
Make sure you try with master, as I recently fixed an issue in the configuration management code in the core.

**Comment by perlethandersen** [comment]
It works now.

My mistake was that I hadn't pulled from master the last few weeks.

**Comment by lminiero** [comment]
Good to know that's fixed! I'll probably have to tag a new version soon, if 0.6.0 has this issue. Closing then.
