### ISSUE TITLE
Problem recoding SIP calls with recordings_tmp_ext

### ISSUE THREAD

**Issue by oscarvadillog** [meetecho/janus-gateway#1500]
I am using SIP plugin (v0.6.0) and I was testing the recording request.

The record files are correct, however, if you enable the recordings_tmp_ext and the SIP call is hung for any reason, the file is not being renamed by removing the temporary extension .tmp. I tried hanging up the SIP call from an Asterisk. It also happens if the browser of the SIP client is closed.

It seems to be a plugin issue.

**Comment by lminiero** [comment]
It may be an issue with the recording code in the core, actually. I'm abroad for a few days, I'll have a look when I have some time.

**Comment by lminiero** [comment]
This commit should fix it, please let me know if that's not the case.
