### ISSUE TITLE
Janus sends internal address in SDP when behind NAT

### ISSUE THREAD

**Issue by shrdlu68** [meetecho/janus-gateway#1509]
Similar to #6:
Behind NAT, Janus registers with the internal IP address rather than the external one.
This happens despite using a stun server `-S` or specifying the external address `-1`.

**Comment by lminiero** [comment]
You're not giving enough information. There's no registration in Janus.

Unless you're talking about the SIP plugin, and the related REGISTER requests sent on behalf of WebRTC users? If so, the settings you mentioned only refer to core stuff. Plugins are configured somewhere else, and the SIP plugin specifically in `janus.plugin.sip.jcfg`, which contains a NAT-related property.

Closing as not an issue: please post questions like these on our [community group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
