### ISSUE TITLE
Crash after connection on VideoCall

### ISSUE THREAD

**Issue by pbilinski** [meetecho/janus-gateway#151]
Hi,

We're experiencing too many crashes in our day-by-day tests. We're using latest (from GIT / 10.02) sources -- compiled like that:

./configure --prefix=/opt/janus --disable-data-channels --disable-rabbitmq

Scenario:

1. Connection from Web 2 users via Videocall
2. When connection after X times (2 or 10) process with janus disappears
3. Last 100 lines from logs just after crash:

Handling message: {
   "request": "register",
   "username": "e6d782fe108e457391aaf2da0c20a3c5"
}
Pushing event: {
   "videocall": "event",
   "result": {
      "event": "registered",
      "username": "e6d782fe108e457391aaf2da0c20a3c5"
   }
}
[2061587764] Adding event to queue of messages...
  >> 0 (Success)
We have a message to serve...
        {
   "janus": "event",
   "session_id": 3750320678,
   "sender": 2061587764,
   "transaction": "JnxfCXlrsboN",
   "plugindata": {
      "plugin": "janus.plugin.videocall",
      "data": {
         "videocall": "event",
         "result": {
            "event": "registered",
            "username": "e6d782fe108e457391aaf2da0c20a3c5"
         }
      }
   }
}
Request completed, freeing data
Got a HTTP OPTIONS request on /janus/3750320678/2061587764...
 ... Just parsing headers for now...
Request completed, freeing data
Got a HTTP POST request on /janus/3750320678/2061587764...
 ... Just parsing headers for now...
Got a HTTP POST request on /janus/3750320678/2061587764...
 ... parsing request...
Session: 3750320678
Handle: 2061587764
Processing POST data (application/json; charset=UTF-8)...
  -- Uploaded data (74 bytes)
  -- Data we have now (74 bytes)
Got a HTTP POST request on /janus/3750320678/2061587764...
 ... parsing request...
Session: 3750320678
Handle: 2061587764
Processing POST data (application/json; charset=UTF-8)...
Done getting payload, we can answer
{"janus":"message","body":{"request":"list"},"transaction":"CU1sySZ5Ai19"}
[2061587764] There's a message for JANUS VideoCall plugin
{
   "request": "list"
}
Request completed, freeing data
Handling message: {
   "request": "list"
}
Request for the list of peers
Pushing event: {
   "videocall": "event",
   "result": {
      "list": [
         "e6d782fe108e457391aaf2da0c20a3c5",
         "092684ec81554621a488af2bbc35fb83_agent"
      ]
   }
}
[2061587764] Adding event to queue of messages...
  >> 0 (Success)
Got a HTTP GET request on /janus/3750320678...
 ... Just parsing headers for now...
Got a HTTP GET request on /janus/3750320678...
 ... parsing request...
Session: 3750320678
Session 3750320678 found... returning up to 1 messages
Request completed, freeing data
Got a HTTP GET request on /janus/3750320678...
 ... Just parsing headers for now...
Got a HTTP GET request on /janus/3750320678...
 ... parsing request...
Session: 3750320678
Session 3750320678 found... returning up to 1 messages
... handling long poll...
Timeout expired for session 2614391159...
Cleaning up session 2614391159...
Destroying session 2614391159
Detaching handle from JANUS VideoCall plugin
Removing user 092684ec81554621a488af2bbc35fb83_agent session...
No WebRTC media anymore
Pushing event to peer: {
   "videocall": "event",
   "result": {
      "event": "hangup",
      "username": "092684ec81554621a488af2bbc35fb83_agent",
      "reason": "Remote hangup"
   }
}
[8830215] ICE thread ended!

It's important that last lines are always the same.

Do you need more feedback to debug it?

**Comment by lminiero** [comment]
Ops sorry for this awfully late reply, looks like I missed this notification.
For all crashes we need a gdb backtrace, logs are not enough. Please don't past logs and backtraces plain in issues and comments, but use a service like pastebin or others.

**Comment by lminiero** [comment]
Any update?

**Comment by lminiero** [comment]
Closing as too many things have changed in the meantime in the code. Feel free to reopen if you can provide details about it still happening.
