### ISSUE TITLE
Merged SDP not sent to event handlers

### ISSUE THREAD

**Issue by mtbramo** [meetecho/janus-gateway#1510]
Problem link to fix "Make sure the merged SDP is sent to event handlers".

It seems that it miss a call to method json_incref(merged_jsep) before sending the event to transport.

And the test line 2772 on jsep and not merged_jsep seems also not correct.

Regards,

 Eric.

**Comment by lminiero** [comment]
Mh, no need for a `json_incref`, we probably just have to use `json_object_set` instead of `json_object_set_new` at ~L2793:

	if(merged_jsep != NULL)
		json_object_set(event, "jsep", merged_jsep);

since AFAIK `json_object_set` adds a reference automatically. Can you check if it fixes it for you?

**Comment by lminiero** [comment]
Nevermind that, I see now that this isn't enough, as we still need to take a leak into account in case. I'll think of a fix and let you know.

**Comment by mtbramo** [comment]
Thanks lorenzo, I just forget to say that we get crashes on this event treatment.

**Comment by lminiero** [comment]
It seems to be working fine for me, though... anyway, it looks like a fix is needed anyway.

**Comment by lminiero** [comment]
I've moved the event handler message before the API event itself: this ensures that the merged SDP is still valid at that point. Please let me know if it solves the issue for you.

**Comment by mtbramo** [comment]
Seems OK for me too. Thanks
