### ISSUE TITLE
HTML video play function not working with Chrome 72

### ISSUE THREAD

**Issue by marcelgoya** [meetecho/janus-gateway#1512]
Hi, I'm using the code from the streaming example, except that I'm triggering the start button and video selection programmatically. The problem is that the video stream does not start in Chrome 72 but does in Firefox. When executing the video.play() function I'm getting the following error:
```
<div id="stream">
<video id="myVideo" class="rounded centered" width="320" height="240" controls="" playsinline=""></video>
</div>
```

```
janus-stream.js:108 Uncaught (in promise) DOMException
setTimeout @ janus-stream.js:108
setTimeout (async)
onremotestream @ janus-stream.js:104
config.pc.ontrack @ janus.js:1670
```

I'm using the latest janus version (0.61).

Cheers,
Marcel

**Comment by lminiero** [comment]
As explained in the guidelines, please don't paste hige chunks of code inline here. Use a pastebin or gist link for the purpose.

**Comment by uxmaster** [comment]
@lminiero I think the guidelines should state "don't paste **any** chunks of code inline" because apparently, "hudge" is considered as something different for most of the contributors to Janus. It'll save your time for explanations.

**Comment by marcelgoya** [comment]
@lminiero @uxmaster Regardless, I remove the JS bit because the code was identical to the one from the streaming example anyway

**Comment by lminiero** [comment]
@uxmaster I was referring to a previous version of the edit; I don't think your suggestion would work, because in my experience who opens issues rarely reads guidelines at all, which is why I have to appear as the Github jerk and say the same thing all over again.

Marcel has edited the content to meet my requirements, so thanks @marcelgoya.

**Comment by marcelgoya** [comment]
@lminiero Ur welcome :)

**Comment by lminiero** [comment]
You should check what causes the exception in your case, as your snippet doesn't say. Try wrapping the whole `onremotestream` code (I assume it's happening there?) in a try/catch to see if the exception manifests with more detail. If you're using an older janus.js, you may want to use a more recent one, as I remember adding those try/catches myself.

**Comment by marcelgoya** [comment]
Great idea, sorry I haven't thought about that. I'll get back to you once I got a more detailed error message.

**Comment by lminiero** [comment]
Any update?

**Comment by marcelgoya** [comment]
@lminiero Not yet but I will have on tomorrow

**Comment by marcelgoya** [comment]
@lminiero Hi, I've finally managed to find the problem. It was basically Google Chrome not allowing the HTML video.play() function because I didn't add the muted tag. It is quite ridiculous because it referenced the MediaStream object as error source but didn't output anything when I used a try/catch clause inside the janus.js file (which was correct).

**Comment by lminiero** [comment]
@marcelgoya thanks for the feedback!

**Comment by marcelgoya** [comment]
@lminiero Ur welcome, and thanks for trying to help me!
