### ISSUE TITLE
Janus not working with Digital Camera on Firefox

### ISSUE THREAD

**Issue by AKMishra22** [meetecho/janus-gateway#1514]
**Steps to reproduce:**
1. Connect 'Sony hdr-cx405' camera to computer using video card
2. Open Firefox browser
3. Open below URL
    https://janus.conf.meetecho.com/videoroomtest.html

**Actual results:**
Janus Video room not working and throwing below ‘WebRTC error’
WebRTC error.. ("name":"NotReadableError","message":"Failed to allocate videosource"}

**Expected results:**

User should join to Video room and display the user video on the screen captured by the camera.
The Video room working on Chrome browser with same setup.

**Comment by lminiero** [comment]
Looks like an incompatibility between Firefox and the camera+card you're using: nothing we can do on that.
