### ISSUE TITLE
data streaming issue ( Can't add 'rtp' stream 'data-example': no datachannels support......)

### ISSUE THREAD

**Issue by saravana87** [meetecho/janus-gateway#1516]
I tried to broadcast text using RTP using the following example

https://www.meetecho.com/blog/data-channels-broadcasting-with-janus/

but I got the following. could somebody help

[ERR] [plugins/janus_streaming.c:janus_streaming_init:1473] Can't add 'rtp' stream 'data-example': no datachannels support......

**Comment by lminiero** [comment]
You didn't install usrsctp or the configure couldn't find it. Closing.
