### ISSUE TITLE
Failure to load event handler plugin

### ISSUE THREAD

**Issue by Aidenhjj** [meetecho/janus-gateway#1517]
I've compiled Janus for Tx2 (aarch64), with [this](https://pastebin.com/QMFmGXSq) configuration.

When set:

`events: {
    broadcast = true
}`

In janus.jcfg, and:

`general: {
    enabled: true
}`

In janus.eventhandler.sampleevh.jcfg, I get:

```
[ERR] [janus.c:main:4038]   Couldn't load event handler plugin  \
    'libjanus_sampleevh.so': /opt/janus/lib/janus/events/libjanus_sampleevh.so: \
     undefined symbol: pow
```

**Comment by lminiero** [comment]
Looks like a missing `-lm`. Try adding it [here](https://github.com/meetecho/janus-gateway/blob/master/Makefile.am#L307) and recompiling.

**Comment by Aidenhjj** [comment]
Thanks. Great project by the way. Have added https://github.com/meetecho/janus-gateway/pull/1519 to resolve. If the pull request is badly formatted, please tell me, as I have 0 experience with github.

**Comment by lminiero** [comment]
Thanks, I've added the fix myself then.
