### ISSUE TITLE
Janus sending bad IP in Contact Header

### ISSUE THREAD

**Issue by StephaneG31** [meetecho/janus-gateway#1526]
With https://github.com/meetecho/janus-gateway/issues/1504, there's a new `sdp_ip` property you can set in the SIP configuration file (Sip plugin)
But in our case, the Contact header is not set to a good value (local IP and not floatting IP provided by cloud provider) and we don't use any STUN server and our network so `behind_nat = true` is not useful.

Is it possible to have a `contact_ip` in sip config file to force an specific IP for Contact header  ?

**Comment by lminiero** [comment]
I don't think there's a way to force what IP to show in the Contact header using Sofia SIP. Have you tried setting an `outbound_proxy` instead?

**Comment by lminiero** [comment]
@StephaneG31 any update on the suggestion above?

**Comment by StephaneG31** [comment]
We try with outbound_proxy and we got 503 error
We try with a STUN in config, but the private address 192.168... is still used in the contact header.

**Comment by lminiero** [comment]
Then I'm afraid you'll have to setup a STUN server to get the `natify` stuff to work, and enable `behind_nat`. Closing.

**Comment by lminiero** [comment]
> We try with a STUN in config, but the private address 192.168... is still used in the contact header.

The STUN server you configure in `janus.jcfg` is only for the Janus core, not the SIP plugin.

**Comment by lminiero** [comment]
PS: the Sofia SIP documentation says that «[..] If there is no public address, it will try to generate a Contact URI from the "received" and "rport" parameters found in the Via header of the response message.», so you may want to make sure you're putting those values in the response.

**Comment by pimenas** [comment]
Hi, I'm trying to setup a STUN server to work with the sip plugin, but so far I have failed miserably. By digging sofia-sip library I discovered that one way to configure it is to provide the stun address in an environment variable "STUN_SERVER". Has anyone accomplished this, and how?

**Comment by StephaneG31** [comment]
> > We try with a STUN in config, but the private address 192.168... is still used in the contact header.
> 
> The STUN server you configure in `janus.jcfg` is only for the Janus core, not the SIP plugin.

well, in the sip configuration file in behind_nat it says that stun_server will be used to detect public IP. But Janus doesn't add any STUNTAG to sofia sip stack so I think the sip stack cannot do a STUN request.
Cf. http://sofia-sip.sourceforge.net/refdocs/stun/stun__tag_8h.html#a854bb3b0743f40ed33a5c33a053c6dfc
Maybe it miss a stun config in sip plugin and so LOC to pass the stun server to the sip stack.
@lminiero what do you think about that?
