### ISSUE TITLE
Janus.isWebrtcSupported checks only navigator.getUserMedia

### ISSUE THREAD

**Issue by patrick-werner** [meetecho/janus-gateway#1527]
Currently Janus.isWebrtcSupported checks only the deprectad navigator.getUserMedia, but WebRtc can also be supported through: navigator.mediaDevices.getUserMedia

https://github.com/meetecho/janus-gateway/blob/e027f0a03804d55e2865fd56aa1f4a408906e14b/html/janus.js#L384

**Comment by lminiero** [comment]
We actually only use `navigator.mediaDevices.getUserMedia` in `janus.js`, so that check is indeed broken. Thanks for the heads up, I'll fix it shortly.
