### ISSUE TITLE
Stop's events for streaming not working

### ISSUE THREAD

**Issue by SArtemJ** [meetecho/janus-gateway#1529]
Hi!
I have some problems with getting janus events (plugin streaming), for example:
- create new stream (rtsp source)
- start stream from janus/demos/streaming web-page
- stop stream

From time to time i cant' get stream stop event  - not stable for both type (in my case) - mqtt/http
Here logs of events and janus actions [https://pastebin.com/DnVTCnfd](url)
gdb - no craches in this case
Why events - stop -  for stream not active? 
What does it mean?

Event settings - janus.eventhandler.sampleevh.jcfg
``` 
general: {
	enabled = true
	events = "plugins"
	grouping = false
	json = "indented"
	backend = "http://my_api_for_events"
	#backend_user = "myuser"
	#backend_pwd = "mypwd"
	#max_retransmissions = 5
	#retransmissions_backoff = 100
}
```
Thanks!

**Comment by lminiero** [comment]
Closing as there's a post here already: https://groups.google.com/forum/#!topic/meetecho-janus/UFixKP_l_80
