### ISSUE TITLE
Spawn script for rtp type in streaming plugin

### ISSUE THREAD

**Issue by towolf** [meetecho/janus-gateway#153]
Currently I’m feeding RTP video from Raspberry Pi to Janus. This works fine thank you. Now I’m only waiting for Google to see the light and allow H.264 on Chrome for Android.

The thing is, if I want to turn on the camera on demand when someone connects I have to use tricks.

Could the streaming plugin be extended to allow starting a shell script? 

The software which I evaluated before was https://github.com/arut/nginx-rtmp-module. This worked fine also, but RTMP was bad for Android and HLS had too much latency. But this software had some directives for executing external code to start ffmpeg et al.

What I’m asking is similar to exec_pull here: https://github.com/arut/nginx-rtmp-module/wiki/Directives#exec_pull

**Comment by lminiero** [comment]
While this is an interesting concept, I don't think we'll go that road on the short term. For now we assume Janus is just the arm controlled by a "brain" somewhere else, which means the actual delivery of streams (whose source may even not be colocated at all) must be originated somewhere else.

**Comment by lminiero** [comment]
That said, if you feel like trying to implement such a behaviour in the plugin yourself and then want to contribute it back to us, we would hardly say no! :-)

**Comment by towolf** [comment]
I was not planning to make an elaborate setup or dive very deep. I merely needed some way to stream  close to real-time video from Raspberry Pi to browsers, preferably Android browser. And as quite a few questions on Groups and here show there are more folks who need a solution for this.

Now, maybe only once a week someone wants to view video from the stream. It would make sense to start stream only when someone connects and stop when they disconnect. And Janus is the thing that knows exactly when that happens. I’m not sure where better to implement this. Janus is already the daemon with system access. I would have to add some kind of CGI for this only to handle process launching.

I would do it myself, but I’m not confident I can decently do clean process handling that would be good enough to merge.

**Comment by lminiero** [comment]
We'll think about it, thanks for the suggestion. Not sure when this would land, though.

**Comment by mspanc** [comment]
I don't think it's a right idea to embed such functionality in core janus. There are many better solutions for controlling spawning/respawning processes and it breaks KISS principle.

**Comment by lminiero** [comment]
I personally agree, as it's in line with my first comment at the time.

**Comment by marchaase** [comment]
Although this issue is really old, I'd still like to add a comment about how this could be accomplished fairly easily with a daemon and the admin API.

You could probably even accomplish this with a bash script.

Some psuedo code:

while True:
  sessions = admin API query sessions
    if sessions:
      if not streamEnabled:
        pid = startStreamBackground
    else:
      if streamEnabled:
        kill pid
  sleep 1

**Comment by lminiero** [comment]
Closing as this can indeed be done using helper tools. Now that the Event Handler mechanism has been merged, it would be even easier to be notified asynchronously (unlike the Admin API) as soon as somebody starts watching a mountpoint.
