### ISSUE TITLE
Can janus supports MCU so that we can record multiple streams?

### ISSUE THREAD

**Issue by SanskarSans** [meetecho/janus-gateway#1533]

**Comment by SanskarSans** [comment]
why is this closed without any comments? I am totally unsure if it support multiple stream recording or not so i can choose technology based on it for my product.

**Comment by lminiero** [comment]
1. we don't answer questions with no description;
2. we only use Github for code issues, not suggestions/questions; use the [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.

**Comment by SanskarSans** [comment]
Thank you. The description of my question is

There will be three streams which need to be recorded to the server separately. After that the recorded stream should be sent to somewhere like OBS studio for compositing. For this i wanted to ask if we can record 3 raw streams using MCU approach or not when using janus. Because in an example there is only stream shown for record so i wanted to ensure.  

Thanks again

**Comment by madhurgoel** [comment]
@SanskarSans  Did you find any solution for the use case.
