### ISSUE TITLE
Many feeds make cuted SDP

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#1534]
I did test with many feeds.
And in room with 16 participants I got:
"WebRTC error: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. c=IN IP4 51. Invalid SDP line.\n"

jsep that come in "onmessage" callback was cuted
Actually I found that more than 8 feeds already do problem

https://pastebin.com/QRVwmYVr

In Janus log sup looks the same way

**Comment by lminiero** [comment]
Looks like the SDP is cut:

```
c=IN IP4 IP_ADRESS
a=sendonly
a=mi
```

Probably the buffer we're using for the SDP is too small. I'll have a look.

**Comment by lminiero** [comment]
@amnonbb can you try changing the `char buffer[2048]` in `sdp.c` to `char buffer[4096]` or  `char buffer[8192]` and recompile to see if it fixes it?

**Comment by tmatth** [comment]
@lminiero also `g_strlcat` is being invoked with `JANUS_BUFSIZE` (i.e. 8192) as the `dest_size` argument, but it should really be sizeof(buffer), or buffer size should be increased to JANUS_BUFSIZE as you suggest:
https://github.com/meetecho/janus-gateway/blob/bb6e97adab70aec7c289c55f950d852b7514b28d/sdp.c#L1125

**Comment by lminiero** [comment]
@tmatth yeah, the 2048 there should just become `JANUS_BUFSIZE` as well, since it's what we use in the SDP utils too :+1:

**Comment by lminiero** [comment]
Should be fixed in that commit, so I'll close: @amnonbb please let me know if that's not the case.

**Comment by amnonbb** [comment]
It's did not help :(
I tried to put 16384 as well, and it's cuted in same place.

**Comment by lminiero** [comment]
Then you can try redefining JANUS_BUFSIZE itself to a larger value: I don't remember where it is (travelling right now) but it should be in one of the header files.

**Comment by lminiero** [comment]
Sorry, it's in sdp-utils.c and not one of the headers as I thought. If you change the define there it should be used wherever it counts.

**Comment by amnonbb** [comment]
Raised it to 16384 help. Now I can't test 16 feeds for now. Tomorrow I'll do that test

**Comment by amnonbb** [comment]
It's work. Thanks.

**Comment by lminiero** [comment]
Well, before closing I should apply the fix on the repo myself :smile: 

I'm a bit hesitant to enforce such a big value for all SDP usages. I'm wondering if this might be done in a way that is aware of the number of m-lines: e.g., if we assume ~1000 bytes per m-line (just speculating, since you said 16k worked for your 16 participants), then we might just use buffers that are num*1000 large. I'll think about it and fix it accordingly.

**Comment by lminiero** [comment]
For now I've simply used a larger buffer as you did in your tests. We can revisit this later on, if need be.
