### ISSUE TITLE
recordplay files sporadically 8 bytes

### ISSUE THREAD

**Issue by evictor** [meetecho/janus-gateway#1537]
Same server, about half the time it is recording/saving videos just fine and reporting "File is x bytes" with the correct size, but the other half of the time I get logs similar to the following in which files end up as only 8 bytes and are clearly truncated (and the frontend thinks it is still recording). I believe the only different logs are the [ERR] ICE failure that you see for these error cases.

```
Creating new session: 6539247599964297; 0x7f17d4001a90
Creating new handle in session 6539247599964297: 308809187039077; 0x7f17d4001a90 0x7f17d40023f0
[308809187039077] Creating ICE agent (ICE Full mode, controlled)
[WARN] [308809187039077] ICE failed for component 1 in stream 1, but let's give it some time... (trickle received, answer received, alert not set)
[ERR] [ice.c:janus_ice_check_failed:1650] [308809187039077] ICE failed for component 1 in stream 1...
[janus.plugin.recordplay-0x7f17d40021b0] No WebRTC media anymore
File is 8 bytes: rec-1772386877274684-audio.mjr
Closed audio recording rec-1772386877274684-audio.mjr
File is 8 bytes: rec-1772386877274684-video.mjr
Closed video recording rec-1772386877274684-video.mjr
[308809187039077] WebRTC resources freed; 0x7f17d40023f0 0x7f17d4001a90
```

Janus version is 0.6.2.

**Comment by lminiero** [comment]
This is not an issue: files will be 8 bytes if they're empty, and they're empty because setting up connectivity failed due to ICE. As such, I'm closing the issue: feel free to discuss the reasons of why you're getting the ICE failures on our Google group instead (you may want to investigate with the Admin API first though).

**Comment by evictor** [comment]
OK, thanks. I should have mentioned also that it is exact same client/network also. In other words in a vacuum sometimes ICE works, sometimes not. I assumed this would point to a Janus bug since there are no apparent external differences.

I will begin a discussion on the group.
