### ISSUE TITLE
SIP Plugin: sdp_ip property not working

### ISSUE THREAD

**Issue by shrdlu68** [meetecho/janus-gateway#1539]
The `sdp_ip` property, which fixes #1504, does not work for us - Janus still sends the private IP (we have 1-1 NAT), which happens to be the value of the `local_ip` property.

We're still seeing `c=IN IP4 192.168.1.25` in SDP, where we expect the public IP we've set as the value of the `sdp_ip` property.

**Comment by lminiero** [comment]
I assume by SDP, you mean on the SIP side, right? On the WebRTC side that value has no effect at all, it will be overridden by the core.

Try launching Janus with log level 5, and check if you see the log line we print [here](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1300) when we detect the `sdp_ip` setting. You should see something like this:

    IP to advertise in SDP: <your IP>

If you don't want the logs to be too verbose, change the `LOG_VERB` to `LOG_WARN` to make it visible. If you don't see that line, the plugin didn't find your configuration, which would explain why the IP is not put in the SDP.

**Comment by shrdlu68** [comment]
I am building in a container, turns out the layer was cached a while back.
Works now, thanks!
