### ISSUE TITLE
Janus was died unexpectedly.

### ISSUE THREAD

**Issue by kuzm1ch** [meetecho/janus-gateway#1544]
I've noticed a problem similar to this issue:  
https://github.com/cargomedia/janus-gateway-audioroom/issues/38 

FYI: In videoroom some users was in audio only mode.

 "commit-hash": "0f1dcfd7a18c5dc13e91ee7e5ec92270560f91d7",

Main log message from Janus: 
```
[ERR] [ice.c:janus_ice_setup_local:3154] [2843602597985776] Error getting list of interfaces...Creating new handle in session 3858213444827961: 2876604454104094; 0x7f114c1a8c00 0x7f115050b440
 
```
And main log message from journactl:  
```
systemd[1]: janus.service: Main process exited, code=killed, status=5/TRAP
```
More useful logs about the crash  from journalctl:  https://pastebin.com/rtLDwD0c 

Also, CPU metric ( iowait ) jumped extremely high before this crash and  I think that this jump was related to janus process, because only janus runs on this machine. FYI: As you can from screenshoot,  Janus was restarted imediatly because it is managed by systemd. 
Thanks.
![Screenshot from 2019-03-07 15-21-35](https://user-images.githubusercontent.com/32264674/54218812-ea983d00-44f6-11e9-970e-6219909e03f6.png)

**Comment by lminiero** [comment]
Please try master, that commit is from 3 months ago.

**Comment by lminiero** [comment]
Make also sure you're using the master version of libnice and not a repo one.

**Comment by kuzm1ch** [comment]
@lminiero  There aren't not  many changes since commit 0f1dcfd7a18c5dc13e91ee7e5ec92270560f91d7 . 
Also, seems like this issue is  related to glib (https://pastebin.com/rtLDwD0c ): 
```
Mar 07 12:55:37 janus-prod env[19735]: (process:19744): GLib-ERROR **: 12:55:37.408: Creating pipes for GWakeup: Too many open files
Mar 07 12:55:37 janus-prod env[19735]: (process:19744): GLib-ERROR **: 12:55:37.408: Creating pipes for GWakeup: Too many open files
Mar 07 12:55:37 janus-prod kernel: do_trap: 46 callbacks suppressed
Mar 07 12:55:37 janus-prod kernel: traps: janus[19753] trap int3 ip:7f116dc80855 sp:7f1147ffd180 error:0
Mar 07 12:55:37 janus-prod kernel: traps: janus[19747] trap int3 ip:7f116dc80855 sp:7f115f7fd190 error:0
```
From my side I've rebuild janus according to your advise and ping if it will reproduce, but seems that this issue is  not occur frequenly ( cargomedia/janus-gateway-audioroom#38 ).

**Comment by lminiero** [comment]
Addressed in the FAQ, closing.
https://janus.conf.meetecho.com/docs/FAQ#ulimit
