### ISSUE TITLE
Android native(not browser) I met an error when I received offer

### ISSUE THREAD

**Issue by kkbpower** [meetecho/janus-gateway#1546]
I trying to implement Janus WebRTC in Android native.
I found odd problem.
I have Samsung Galaxy S9(v9.0), HUAWEI WAS-LX2J(v7.0) and Samsung Galaxy Note 4 (v6.0).
My code is fine on S9 and Note4. But Only occurred in HUAWEI.

I create PeerConnection with setRemoteDescription() when I received offer from another peer.
HUAWEI device always occurred onSetFailure() of SdpObserver when I call the setRemoteDescription() with "Failed to set remote offer sdp: Failed to set remote video description send parameters." message.

janus: v0.6.1
video codec: H.264
audio codec: opus

Help me!

**Comment by lminiero** [comment]
Sounds like that mobile device doesn't support H.264 in WebRTC. Not a code issue, so closing. You may want to ask on [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) instead.
