### ISSUE TITLE
mvideoroomtest.js missing mandatory element (feed)

### ISSUE THREAD

**Issue by qmohammed93** [meetecho/janus-gateway#1553]
This issue is for PR #1459 (Unified Plan branch), on the latest commit as of now (4c9bbdd164b28277cd17a4bffcdd5729f1d5bf53). It occurs on the mvideoroomtest demo.

When I enter a display name and click "Join the room", I get a bootbox pop-up "Missing mandatory element (feed)" at the same time as the prompt for allowing camera/microphone.

In the Janus.log, I see the following error:
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:4928] Missing mandatory element (feed)
It's important to note this bootbox alert appears at the exact same time as the cam/mic prompt. 

Then once I accept the cam/mic prompt, the UI does not update to display the local and remote videos.

**Comment by lminiero** [comment]
Tried earlier today and it works as expected for me. Are you sure the demo is talking to the unified-plan Janus, and not a "regular" one? The error makes me think it's a matter version of Janus that is receiving the request.

If you have steps to consistently replicate the issue, please let us know.

**Comment by qmohammed93** [comment]
Thanks for your response. You are correct the mvideoroomtest.js was running on a master Janus backend. No problem like this using Unified Plan branch Janus backend.
