### ISSUE TITLE
Stream doesn't work in Chrome Canary version 75

### ISSUE THREAD

**Issue by alienpavlov** [meetecho/janus-gateway#1555]
I'm using Canary version of Google Chrome (_Version 75.0.3739.0 (Official Build) canary (64-bit)_) and after some update Janus stopped to establish peer connection anymore.
I'm not sure if this issue related to https://github.com/meetecho/janus-gateway/issues/1552

But I've tested it on https://janus.conf.meetecho.com/echotest.html page and what I found:
<img width="971" alt="Screenshot at Mar 21 19-07-57" src="https://user-images.githubusercontent.com/2844990/54766628-aa2e7280-4c0c-11e9-8e82-242f2c81679f.png">

`Cannot read property 'readyState' of undefined` is not the exact problem. It occurs because "done" message was received and Janus **oncleanup()** was called which empties **config.dataChannel** object (marked up with yellow arrows on the screenshot)

Do you have any clue how to fix that?

**Comment by vivaldi-va** [comment]
i've experienced this myself with the videoroom plugin. From what I can tell, it is due to the fact that chrome 75+ will drop support for TLS versions < 1.2, and as as result there are DTLS failures. Janus log output suggests that it expects or is receiving TLS 1.0.

**Comment by lminiero** [comment]
The hangup event says "dtls alert". You should check what the Janus logs have to say about that. No connectivity for me today (typing on my phone) so nothing I can do until tomorrow I'm afraid.

**Comment by lminiero** [comment]
Yeah that may be one of the causes. We use the generic DTLS stack in openssl which should offer both 1.0 and 1.2, not sure if the new Chrome will reject it.

**Comment by bwerther** [comment]
I just ran into this, and fixed it by upgrading OpenSSL to 1.1 on the
server. Now works fine.

**Comment by lminiero** [comment]
Which means that for pre-1.1 we need to use DTLSv1_2_method() instead of DTLSv1_method(). I'll take note of that to fix it when my ISP decides I can join the first world again.

**Comment by lminiero** [comment]
Fixed here: https://github.com/meetecho/janus-gateway/commit/435a1e91f1661e99d7a78c7953adfeedd95b66e3

**Comment by alienpavlov** [comment]
Thanks everyone. Just tested in `Version 75.0.3739.0 (Official Build) canary (64-bit)` and it works as expected!

**Comment by lminiero** [comment]
Mh, looks like the fix in https://github.com/meetecho/janus-gateway/commit/435a1e91f1661e99d7a78c7953adfeedd95b66e3 may not be working as I thought on older OpenSSL versions... despite the fact I'm explicitly using `DTLSv1_2_method()` there, if I have a look at the traffic with Wireshark DTLS 1.0 is still being used, causing failures. This means that at the moment the only way to get this working with Chrome 75 is using OpenSSL >= 1.1. Looking into this.

**Comment by lminiero** [comment]
@alienpavlov did you get it fixed upgrading OpenSSL to 1.1, or with my fix? Just asking in case it's specific to the OpenSSL version on the instance I'm using to reproduce the issue.

**Comment by lminiero** [comment]
Scratch that, looks like it's working now... probably a compilation issue!

**Comment by alienpavlov** [comment]
> @alienpavlov did you get it fixed upgrading OpenSSL to 1.1, or with my fix? Just asking in case it's specific to the OpenSSL version on the instance I'm using to reproduce the issue.

just with your fix and it seems to be working, but I'm going to update to OpenSSL 1.1 anyway (current version is 1.0.2)

**Comment by groupboard** [comment]
Just note that DTLSv1_2_method is only available from openssl version 1.0.2, so the minimum version of openssl should now be listed as 1.0.2. (Discovered this as we have 1.0.1 and was wondering why it was complaining about DTLSv1_2_method being undefined).

**Comment by lminiero** [comment]
Thanks for the clarification, I'll take note of that.

**Comment by WJdenghuo** [comment]
ubuntu 18.4 64 
openssl 1.1.1
this bug  in  70.0.1 64（FIrefox）

Object { janus: "hangup", session_id: 6969094214175435, sender: 1822829727662720, reason: "DTLS alert" }

![janus_DTLS alert](https://user-images.githubusercontent.com/25807145/70118834-f5f25080-16a3-11ea-816d-bf98c255d432.png)
