### ISSUE TITLE
janus error:1410242E:SSL routines:dtls1_read_bytes:tlsv1 alert protocol version

### ISSUE THREAD

**Issue by cosysun** [meetecho/janus-gateway#1560]
hi, my webrtc server is base on janus, but recently i find webrtc dtls handshake always failed in chrome canary(chome 75), the reason is chrome 75 already remove support tls1.0 and 1.1 support, but my janus server dtls is support tls1.0. my openssl version is 1.0.2g. now how can i fix it. upgrade openssl version? thanks you.

**Comment by lminiero** [comment]
Either update to master (we have a fix for that) or upgrade OpenSSL to 1.1. Closing.

**Comment by cosysun** [comment]
thanks. upgrade openssl version is ok.  and can you tell me what branch fix the problem.
