### ISSUE TITLE
How to track status of simulcast substreams?

### ISSUE THREAD

**Issue by bwerther** [meetecho/janus-gateway#1561]
Two scenarios I'm trying to figure out:

1) When chrome starts broadcasting with spec-compliant simulcast, I'm seeing that it doesn't start to stream the highest quality stream for a few seconds. I'm assuming that under the covers the browser hasn't yet enabled that MediaStreamTrack, but how can we know that it has become active so we can automatically switch up to it? (Right now it requires an explicit action to switch to substream 2, but we seem to miss the SPS and hang out on substream 1 for quite a while). You can see the effect of this in the web app -- just start 2 sessions connected to video room with chrome, and you'll see both on substream 1. When you click for substream 2 it requires a few clicks and waiting 10+ seconds after you've started clicking.

2) Likewise, where would the enable/disable of substreams (via setParameters()) surface in the videoroom or API? i.e. if a client wants to turn off all but the low-quality substream when the user is not speaking, how would that surface so the videoroom and other clients could cleanly know about this change? Would it need to be managed out-of-band, or does the enable parameter on the underlying track surface in Janus somewhere?

    Thanks,
     Ben

**Comment by lminiero** [comment]
Please post on the group, we only use github for issues. Closing.
