### ISSUE TITLE
[Android native] onDataChannel() never called.

### ISSUE THREAD

**Issue by kkbpower** [meetecho/janus-gateway#1562]
this is my code.

peerConnection = factory.createPeerConnection(iceServers, new PeerConnection.Observer(){
    @Override
    public void onDataChannel(DataChannel dataChannel) {
        Log.e("DataC", "DataChannel onDataChannel");

        this.dataChannel.registerObserver(new DataChannel.Observer() {
          @Override
            public void onBufferedAmountChange(long l) {
                Log.e("DataC", "DataChannel onBufferedAmountChange : " + l);
            }

            @Override
            public void onStateChange() {
                Log.e("DataC", "DataChannel onStateChange : " + dataChannel.state());
            }

            @Override
            public void onMessage(DataChannel.Buffer buffer) {
                Log.e("DataC", "DataChannel onMessage : " + command);
            }
        });
    }

    ...

});

DataChannel.Init init = new DataChannel.Init();
init.ordered = false;
this.dataChannel = peerConnection.createDataChannel("data channel", init);

But onDataChannel() never called. What happen?

**Comment by lminiero** [comment]
Did you enable datachannels when compiling Janus? Anyway, not sure it can be considered an issue in Janus, especially if it works as expected with "regular" browsers.

**Comment by kkbpower** [comment]
@lminiero 
Actually, I did not compiling. So I don't know.
If Janus was complied with disable datachannels, What can I do?

**Comment by lminiero** [comment]
Please check the README for instructions on how to build Janus with datachannels support. Closing.

**Comment by kkbpower** [comment]
@lminiero 
If Janus was complied with disable, I have to re-compile?

**Comment by lminiero** [comment]
To check if Janus has datachannels support, you can send an "info" request to Janus, or contact the `/janus/info` endpoint. For instance, this is the configuration of our online demos:

https://janus.conf.meetecho.com/janus/info

where you can see we have a `"data_channels": true` property.

**Comment by lminiero** [comment]
> If Janus was complied with disable, I have to re-compile?

Yes.

**Comment by ss99x2002** [comment]
> > If Janus was complied with disable, I have to re-compile?
> 
> Yes, you need to do a new configure and a new `make install`.

Hello, I set datachannel enable. I'm leaving a question because the same issue as this issue occurred on Android. Is there a solution?
