### ISSUE TITLE
sctp not found issue when I compile janus.

### ISSUE THREAD

**Issue by kkbpower** [meetecho/janus-gateway#1563]
janus-janus.o: In function `main':
/home/ubuntu/janus-gateway/janus.c:3924: undefined reference to `janus_sctp_init'
/home/ubuntu/janus-gateway/janus.c:4424: undefined reference to `janus_sctp_deinit'
janus-dtls.o: In function `janus_dtls_srtp_create_sctp':
/home/ubuntu/janus-gateway/dtls.c:594: undefined reference to `janus_sctp_association_create'
janus-dtls.o: In function `janus_dtls_srtp_incoming_msg':
/home/ubuntu/janus-gateway/dtls.c:675: undefined reference to `janus_sctp_data_from_dtls'
janus-dtls.o: In function `janus_dtls_srtp_destroy':
/home/ubuntu/janus-gateway/dtls.c:914: undefined reference to `janus_sctp_association_destroy'
janus-dtls.o: In function `janus_dtls_wrap_sctp_data':
/home/ubuntu/janus-gateway/dtls.c:961: undefined reference to `janus_sctp_send_data'
collect2: error: ld returned 1 exit status
Makefile:1624: recipe for target 'janus' failed
make[2]: *** [janus] Error 1

I found sctp lib issue. How can i compile correctly?

**Comment by lminiero** [comment]
Is this from a clean install? Did you install usrsctp?

**Comment by lminiero** [comment]
Any update?

**Comment by lminiero** [comment]
I assume it's not an issue anymore. Closing.

**Comment by SmithAdoph** [comment]
echo "not-a-git-repo" | awk 'BEGIN {print "#include \"version.h\""} {print "const char *janus_build_git_sha = \"" $0"\";"} END {}' > version.c
echo "2020年 03月 22日 星期日 15:04:02 CST" | awk 'BEGIN {} {print "const char *janus_build_git_time = \""$0"\";"} END {} ' >> version.c
echo "91" | awk 'BEGIN {} {print "int janus_version = "$0";"} END {} ' >> version.c
echo "0.9.1" | awk 'BEGIN {} {print "const char *janus_version_string = \""$0"\";"} END {} ' >> version.c
pkg-config --modversion nice | awk 'BEGIN {} {print "const char *libnice_version_string = \""$0"\";"} END {} ' >> version.c
  CC       janus-version.o
  CCLD     janus
janus-janus.o: In function `janus_info':
/usr/local/adoph/janus-gateway-0.9.1/janus.c:326: undefined reference to `srtp_get_version_string'
collect2: error: ld returned 1 exit status

**Comment by groupboard** [comment]
Try adding -lsrtp to JANUS_MANUAL_LIBS in Makefile
