### ISSUE TITLE
Configure script fails on OSX Mojave (Package 'libffi', required by 'gobject-2.0', not found)

### ISSUE THREAD

**Issue by mykola-mokhnach** [meetecho/janus-gateway#1565]
Just following the README:

`$ ./configure --prefix=/usr/local/janus PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig `

```
...
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for
                    glib-2.0 >= 2.34
					libconfig
                    nice
                    jansson >= 2.5
                    libssl >= 1.0.1
                    libcrypto
                  ... no
configure: error: Package requirements (
                    glib-2.0 >= 2.34
					libconfig
                    nice
                    jansson >= 2.5
                    libssl >= 1.0.1
                    libcrypto
                  ) were not met:

Package 'libffi', required by 'gobject-2.0', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JANUS_CFLAGS
and JANUS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
FAIL: 1
```

```
$ brew install libffi

Warning: libffi 3.2.1 is already installed and up-to-date
To reinstall 3.2.1, run `brew reinstall libffi`
```

**Comment by lminiero** [comment]
Unfortunately I'm not familiar at all with Mac OS, so no idea what the steps to fix that would be. You may have better chances of solving this by asking on our meetecho-janus group too: I think more people will read it there than here.

**Comment by mykola-mokhnach** [comment]
Thanks @lminiero. I'll try to ask there.

**Comment by kiq7** [comment]
Same problem here :(

**Comment by mykola-mokhnach** [comment]
Figured this out. Needed to alter PKG_CONFIG_PATH and now it looks like that (considering libffi has been already installed with brew): `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig`

**Comment by mykola-mokhnach** [comment]
@lminiero I assume it makes sense to update the README

**Comment by ehbb** [comment]
Setting PKG_CONFIG_PATH and LDFLAGS didn't work for me.

I have to `brew reinstall libffi` and then set `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig` and `export LDFLAGS="-L/usr/local/Cellar/libffi/3.2.1/lib/"` paths

**Comment by zigen** [comment]
@ehbb 
I got same problem 
but in my case, I forget to remove `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` from `$ ./configure --prefix=/usr/local/janus PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig`
this overrides `PKG_CONFIG_PATH` you set.

**Comment by geanfelipe** [comment]
> @ehbb
> I got same problem
> but in my case, I forget to remove `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` from `$ ./configure --prefix=/usr/local/janus PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig`
> this overrides `PKG_CONFIG_PATH` you set.



> Setting PKG_CONFIG_PATH and LDFLAGS didn't work for me.
> 
> I have to `brew reinstall libffi` and then set `export PKG_CONFIG_PATH=/usr/local/Cellar/libffi/3.2.1/lib/pkgconfig` and `export LDFLAGS="-L/usr/local/Cellar/libffi/3.2.1/lib/"` paths

It worked for me, thank you!
