### ISSUE TITLE
Send audio stream via janus

### ISSUE THREAD

**Issue by ahmadazarnia** [meetecho/janus-gateway#1566]
Hi, I developed my app without any problem. Now, i have connected a device that sends audio stream to mobile via Bluetooth, How to send this stream(byte[]) into VideoRoom as a AudioTrack?

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), as explained in the guidelines we only use github for issues. Closing.
