### ISSUE TITLE
Porting Janus webrtc to windows

### ISSUE THREAD

**Issue by asadkhan77** [meetecho/janus-gateway#1568]
I was successful in porting latest code to windows but at run time, I am getting "create" error. I am not sure what went wrong. Any help in this regard will be very helpful. Here is my output:
"janus
Janus commit: bf28e2121026b3f77658e8c5816b93f32587a96d
Compiled on:  Mon, Apr  1, 2019  1:33:52 PM

---------------------------------------------------
  Starting Meetecho Janus (WebRTC Server) v0.7.0
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Using 192.168.91.62 as local IP...
[33m[WARN][0m Token based authentication disabled
Initializing recorder code
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
TURN REST API backend: (disabled)
[33m[WARN][0m Janus is deployed on a private address (192.168.91.62) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
Crypto: OpenSSL >= 1.1.0
[33m[WARN][0m No cert/key specified, autogenerating some...
Fingerprint of our certificate: E0:2A:10:42:F0:5D:59:9C:5B:AC:57:1F:18:A8:5D:07:01:1E:A3:B4:BA:06:66:AD:53:31:C3:66:CB:60:0D:22
[33m[WARN][0m Data Channels support not compiled
[33m[WARN][0m Event handlers support disabled
Plugins folder: ../../mingw64/lib/janus/plugins
Sessions watchdog started
Joining Janus requests handler thread
Loading plugin 'libjanus_streaming-0.dll'...
[31m[ERR][0m [janus.c:janus_main:4328]        Couldn't load symbol 'create': "create": The specified procedure could not be found.
Transport plugins folder: ../../mingw64/lib/janus/transports
Loading transport plugin 'libjanus_http-0.dll'...
[31m[ERR][0m [janus.c:janus_main:4447]        Couldn't load symbol 'create': "create": The specified procedure could not be found.
[35m[FATAL][0m [janus.c:janus_main:4504] No Janus API transport is available... enable at least one and restart Janus".

Thank you very much in advance.
Khan.

**Comment by lminiero** [comment]
Sorry, we can't help on issues for code that is not in the repo. I see you've posted on the group too, so the discussion can happen there.
