### ISSUE TITLE
Stream not coming When publisher on chrome

### ISSUE THREAD

**Issue by garg-geek** [meetecho/janus-gateway#1570]
I had installed janus using master on ubuntu 18.04 . I am using video room plugin.  When publisher is on chrome, subscriber is not able to view feed but if publisher is on firefox it is working fine. In Logs, for publisher DTLS handshake completed log was not printed.  I checked the [Admin Api Response](https://pastebin.com/hCTAPkDr) and here also ready is false of dtls. I am using OpenSSL 1.1.0g. Can you help me what is wrong with DTLS or there is some other problem.

**Comment by atoppi** [comment]
Hi,
with the same setup
```
Ubuntu 18.04
Janus master
openssl 1.1.0g
```
videoroom (pub and sub) is working fine with both Chrome stable 73 and Chrome dev 75.

**Comment by lminiero** [comment]
As explained in the guidelines, questions like this belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), we only use github to track issues. Closing.
