### ISSUE TITLE
Configure request not renegotiating after first publish (Unified Plan)

### ISSUE THREAD

**Issue by qmohammed93** [meetecho/janus-gateway#1571]
This issue was observed on videoroomtest in PR #1459 (Unified Plan branch), using Firefox browser.

When sending a configure request in an attempt to make changes to the published streams, the following errors pops up:
> WebRTC error... {"name":"TypeError","message":"audio and/or video is required"}
and renegotiation on the peer side does not occur.

We observed this error to be only on the Unified Plan branch, however it works correctly on master.

To recreate the issue follow these steps:

1. Open the videoroomtest demo
2. Connect two or more users
3. Open the JS console and run the command: publishOwnFeed(false)

This should attempt to reconfigure the streams and remove the audio stream. It works correctly in master but fails with the above error on the unified plan branch.

Note: the above is the simplest way to duplicate. I have tried reconfiguring on my own code base, and it reconfigures the specific user who sends the request, but there is no notice or renegotiation on the peers.

**Comment by lminiero** [comment]
No, `publishOwnFeed` won't update streams. It can only be used to publish the first time. The demo doesn't include any hook to the updated API to change what you publish: it's up to you to do for the time being. Closing as not an issue.
