### ISSUE TITLE
Merge each recording file(combined to mp4) into a file.

### ISSUE THREAD

**Issue by kkbpower** [meetecho/janus-gateway#1572]
Hey, long time no see.

I have a interesting question.
I already combine audio and video files into mp4.

If multiple peers are in a room, how to combine multiple mp4 into a file?

Like this:
merged_recording_file.mp4 
included peer1.mp4 & peer2.mp4. 
Not continue stream.

**Comment by lminiero** [comment]
As clearly explained in the guidelines, we only use github for issues, not questions or debugging. Please refer to the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for that. Closing.
