### ISSUE TITLE
Segfault in lws_callback_on_writable when closing PC

### ISSUE THREAD

**Issue by vahidov** [meetecho/janus-gateway#1573]
Not usually. I have two crashes during 10 days on highly loaded production

Janus commit: d76a2516e4dc91a16fd8a1e907288d317fb2d957
libwebsocket ver: v3.0.0-53

gdb - https://gist.github.com/vahidov/6bfa1ee8581c6a69f2f077b2be74902a

P.S. I'l try update libwebsocket to last version, will see, whats will happend.

P.P.S. Don't know - is this real issue or not. May be helps you. You may close ticket.

**Comment by tmatth** [comment]
@vahidov you'll want to compile libwebsocket with `-DLWS_MAX_SMP=1`

**Comment by vahidov** [comment]
@tmatth 
this segfaults was with this libwebsockets build config

`cmake -DLWS_MAX_SMP=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" .. && make && make install`

**Comment by atoppi** [comment]
Next steps:
- enable AddressSanitizer
- enable debugging symbols (`-O1 -ggdb`) also in lws

**Comment by atoppi** [comment]
@vahidov Can you test with a lws `stable` branch ? Like for example `v3.1-stable`.

**Comment by atoppi** [comment]
Hi @vahidov,
I have edited the issue title and attempted a fix in #1585.
Can you give it a try?

**Comment by vahidov** [comment]
@atoppi
FYI: Till now (5 days) without crashes.
On monday I'll try build janus with yours fixes and stable libwebsocket. After - write you, if something happened.

Thanks.

**Comment by vahidov** [comment]
@atoppi during weekend was another same crash.
I'm started production on #1585. Lets see.
