### ISSUE TITLE
[ERROR] Failed to set remote audio description send parameters

### ISSUE THREAD

**Issue by DaGLiMiOuX** [meetecho/janus-gateway#1576]
Hi there.

Referring to https://groups.google.com/forum/#!topic/meetecho-janus/zi1ECKDDALY where I posted that I have a problem with audio description parameters in videoroom plugin using Chrome 73.0.3683.90 for Android, I tried to test janus in your demo page https://janus.conf.meetecho.com/videoroomtest.html and the same error is thrown with your demo server.

```
janus.js:2987 WebRTC error: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to set remote audio description send parameters.
```

I already updated gateway and libs in server, but it keeps throwing the error, like in your demo.

The (summarized) trace:

1 - [videoroomtest.js#257](https://github.com/meetecho/janus-gateway/blob/master/html/videoroomtest.js#L257)
2 - [janus.js#1111](https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L1111)
3 - [janus.js#2322](https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L2322)
4 - [janus.js#2341](https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L2341) <- Promise callback error is called
5 - [janus.js#2987](https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L2987) <- Error handled

Versions used:

Google Nexus 6P
Android 8.1.0
Chrome 73.0.3683.90
Janus v0.6.3
Libsrtp 2.2.0
Libnice 0.1.15

I hope this helps to find the problem.

Br,
D.

**EDIT:** Here is the SDP -> [https://pastebin.com/jnyEn9xx](https://pastebin.com/jnyEn9xx)

**Comment by lminiero** [comment]
From the SDP you shared on the group, the one with extmap:0, it might be related to #1575. Do you have the encrypted RTP extension flag enabled? If so, we don't support them yet.

**Comment by DaGLiMiOuX** [comment]
It worked disabling "Negotiation with encrypted header extensions for SRTP in WebRTC" in `chrome://flags`. Thank you.

Also, I saw that you have a pull request to ignore SRTP when modifying SDP. I will update when it is merged to master :)

Br,
D.

**Comment by lminiero** [comment]
Ack, closing then :+1:
