### ISSUE TITLE
H264-encoded stream does not get properly shown in the client if received from a RTSP source

### ISSUE THREAD

**Issue by mykola-mokhnach** [meetecho/janus-gateway#1578]
Everything is done on the same machine (Ubuntu 18). Janus is built from source (master branch)

1. Start RTSP server on the main interface (we are using https://github.com/chriswiggins/rtsp-streaming-server, but any other would also be ok)
2. Start FFMpeg stream to this RTSP server 

```
$ffmpeg -i <anything> -c:v libx264 -maxrate 2M -bufsize 640k -x264opts keyint=30 -pix_fmt yuv420p -g 30 -f rtsp rtsp://192.168.1.100:5554/live
```

3. Configure streaming plugin, so it should autotetect stream type:

```
[rtsp]
type = rtsp
id = 6554
description = RTSP Stream
audio = no
video = yes
url = rtsp://192.168.1.100:6554/live
```

4. Start janus and open the streaming demo page in browser
5. Start [rtsp] streaming in browser

Actual result:
No video is shown. I suppose this happens, because browser SDP expects VP8 instead of H264 (see the attached file [no_params.log](https://github.com/meetecho/janus-gateway/files/3064700/no_params.log) )

6. Stop janus and alter the streaming plugin config, so it contains stream attributes:

```
[rtsp]
type = rtsp
id = 6554
description = RTSP Stream
audio = no
video = yes
url = rtsp://192.168.1.100:6554/live
videopt = 126
videortpmap = H264/90000
videofmtp = profile-level-id=42e01f\;packetization-mode=1
```

7. Repeat steps 4-5

Actual result:
Janus shows that the connection has been established and bytes are being streamed, however the browser only shows the BPS counter, but the actual video is never loaded:

<img width="602" alt="no_video" src="https://user-images.githubusercontent.com/7767781/55894412-5b944880-5bba-11e9-8636-79d31f64657a.png">

See the attached file [with_params.log](https://github.com/meetecho/janus-gateway/files/3064701/with_params.log) for more details.

Although, everything is fine and the video can properly be seen on the demo page if I change the streaming format to VP8:

```
$ffmpeg -i <anything> -c:v libvpx -deadline realtime -crf 10 -pix_fmt yuv420p -b:v 800k -f rtsp rtsp://192.168.1.100:5554/live
```

We've also tried to stream the above x264 video using the `rtp` channel type and this worked (e.g. the video has been properly shown in the browser on the demo page)

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus): as explained in the guidelines, we only use github for code issues. Closing.
