### ISSUE TITLE
Segfault in janus_ice_setup_local

### ISSUE THREAD

**Issue by vahidov** [meetecho/janus-gateway#1588]
Janus commit: ce8255e56b4a1cecc992cd55633bcdb1ef88cfe7
gdb - https://gist.github.com/vahidov/fc80b43ac9a51a8585ba5dcb132941f0

**Comment by atoppi** [comment]
Hi @vahidov,
unfortunately the trace is not very useful because the crash is deep in libnice and the symbols are not available.
Which version of libnice are you using? Try first with a recent version (`0.1.14` or greatest).

If you are compiling the library from the sources, please enable the symbols and report the same backtrace.

**Comment by vahidov** [comment]
I'm using libnice-dev in debian:stretch (ver 0.1.13-2)

Will try compile from sources with recent version.

**Comment by lminiero** [comment]
@vahidov any feedback?

**Comment by lminiero** [comment]
We'll wait until you test with a recent version of libnice.

**Comment by vahidov** [comment]
@lminiero 
From friday production worked on 0b65fca and libnice master. 
Feels like - works better, more stable in connection establishing, especially safari.

Till now - one crash on websockets - https://gist.github.com/vahidov/455b779dcb56d2243fc9522019f5023d. 
And another time transports looks like "frozen". I mean - janus workes, in log no errors or another data. But when attempt to connect over websockets or api - timeouts, janus not answers. After restarting janus-docker - fully normal work.

**Comment by vahidov** [comment]
Another crash, today in "janus_ice_outgoing_traffic_handle"  - https://gist.github.com/vahidov/1edea841fe7a91606b89ecec79b788eb

**Comment by vahidov** [comment]
Next crash https://gist.github.com/vahidov/a00175614ba0d62e0ec00a4fb29bc8f2

**Comment by lminiero** [comment]
Please provide a libasan trace as well.

**Comment by vahidov** [comment]
@lminiero 
Can't do this. When I try build with libasan on production server - i'v got a lot overhead (4-5 times bigger load then without libasan). In this reason - can't enable it on production.

**Comment by vahidov** [comment]
@lminiero @atoppi - any information? We have same of this crashes almost everyday.

**Comment by lminiero** [comment]
Nothing we can do without a libasan trace.

**Comment by atoppi** [comment]
IIUC the [starting issue](https://gist.github.com/vahidov/fc80b43ac9a51a8585ba5dcb132941f0) has been solved with a recent libnice. For sake of clarity and simplicity, I think we should close this issue as solved and track the other crashes in different issues.
