### ISSUE TITLE
Videoroom plugin in ios12.2 safari can not use the back camera

### ISSUE THREAD

**Issue by jryiz** [meetecho/janus-gateway#1593]
Janus.listDevices
navigator.mediaDevices.enumerateDevices can get 3 devices with face camera's deviceid and audio's deviceid ,but back camera is empty string.

in the videoroom demo(https://janus.conf.meetecho.com/videoroomtest.html) got an webrtc error..."enumerateDevices error" in ios12.2's safari

**Comment by lminiero** [comment]
Not a Janus problem, since enumerateDevices is a browser thing. Closing.
