### ISSUE TITLE
Crash in janus_ice_outgoing_traffic_handle

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#1600]
#1459 
For me it's happened something like three times in last month ( libnice 0.1.14.1 )
https://pastebin.com/2xxAApCU

With last master it's occur more often.

**Comment by lminiero** [comment]
Please provide a libasan dump.

**Comment by lminiero** [comment]
Just noticed you mentioned libnice 0.1.14, have you tried master instead? Pretty sure libnice 0.1.14 precedes many fixes they made after that.

**Comment by lminiero** [comment]
Closing as we merged #1601. Feel free to reopen if still an issue with that patch and libnice master.
