### ISSUE TITLE
can not receive sessionId and handle in event handler

### ISSUE THREAD

**Issue by SlZeroth** [meetecho/janus-gateway#1603]
I use event handler but i can't get sessionId and handle. when emit leave, unpublished event 

![image](https://user-images.githubusercontent.com/8098724/56890541-b1228d80-6ab4-11e9-884f-c6c717fe84ba.png)

why leave, unpublished event not include sessionId , handle

**Comment by lminiero** [comment]
Not all events originated from a plugin include those details. For the unpublished event, you can use the participant ID as that's the only really need information. Closing as not an issue.
