### ISSUE TITLE
Videoroom rtp_forward does not forward Sender Reports

### ISSUE THREAD

**Issue by bennyveo** [meetecho/janus-gateway#1606]
It seems as though rtp_forward in the videoroom plugin does not forward sender reports (tested in master, ubuntu 18.04).

video/audio_rtcp_port was specified in the rtp_forward API call and the RTP forward is working correctly (ie, there is media flow) however no sender reports are received.

TCP dump and gst-launch pipeline:

```
tcpdump -i lo -w /tmp/srcandsink.pcap udp port 64002 or port 64872 or port 37792 or port 50870 or port 57995 or port 53994

gst-launch-1.0 --gst-debug 2 rtpbin name=rtpbin latency=2000 rtp-profile=avpf udpsrc name=artp-udpsrc address=127.0.0.1 port=64002 caps="application/x-rtp,media=audio,payload=111,clock-rate=48000,encoding-name=OPUS,sprop-stereo=(string)1" ! rtpbin.recv_rtp_sink_0 udpsrc name=artcp-udpsrc address=127.0.0.1 port=64872 caps="application/x-rtcp" ! rtpbin.recv_rtcp_sink_0 udpsrc name=vrtp-udpsrc address=127.0.0.1 port=50870 caps="application/x-rtp,media=video,payload=96,clock-rate=90000,encoding-name=VP8" ! rtpbin.recv_rtp_sink_1 udpsrc name=vrtcp-udpsrc address=127.0.0.1 port=57995 caps="application/x-rtcp" ! rtpbin.recv_rtcp_sink_1 rtpbin.send_rtcp_src_0 ! udpsink host=127.0.0.1 port=37792 sync=false async=false rtpbin.send_rtcp_src_1 ! udpsink host=127.0.0.1 port=53994 sync=false async=false rtpbin. ! rtpopusdepay ! rtspclientsink. rtpbin. ! rtpvp8depay ! rtspclientsink. rtspclientsink name=rtspclientsink location=rtspt://remoteaddr:80/ingest/a3e59617c6be2179/stage0d929752791
```

Pcap: [http://cc-sec-drop.s3.amazonaws.com/srcandsink.pcap.zip](url)

**Comment by lminiero** [comment]
That's on purpose. The RTCP support at the moment is only meant for PLI and REMB. Closing as not an issue.

**Comment by bennyveo** [comment]
Ok... so this is a design decision, or would we need to implement it?

> "video_rtcp_port" : <port to contact to receive video RTCP feedback from the recipient; optional>

Certainly implies that feedback will be send to specified ports.

**Comment by lminiero** [comment]
The description says "from the recipient", and indeed the RTCP channel is never used to send RTCP from the sender to the recipient (as SR in your casE), but only the other way around. Specifically, the main purpose was ensuring that, for instance, a recipient could send a PLI back to the publisher, so that a keyframe could be requested even by a RTP forwarder recipient, instead of just VideoRoom subscribers. REMB is something else that can be used, e.g., to use the REMB from multiple recipients somehow and possibly adapt.

**Comment by bennyveo** [comment]
I see, so video_rtcp_port is a "receiver" port in any case?

**Comment by lminiero** [comment]
Yes, as it is now it's never used to send anything, only receiving. This is confirmed by the fact that the `incoming_rtcp` callback in the VideoRoom plugin completely ignores feedback from publishers. That's where you should add your "relay RTCP too" logic if you need that.

**Comment by bennyveo** [comment]
yep, got it. ok thanks.
