### ISSUE TITLE
Segfault when destroying sessions

### ISSUE THREAD

**Issue by 0xFelix** [meetecho/janus-gateway#1610]
Today I updated my janus installation to d0fecb0b4a4c4dc23b3e0a7038970ba382e66620
Since then I had several crashes when janus tried to destroy a session.

Previously d76a2516e4dc91a16fd8a1e907288d317fb2d957 was installed, which worked fine with the same and unchanged config.
Did I miss something?

Only log output I can provide now:

`
May 09 15:38:23 srv-01 janus[29235]: Destroying session 8263199646806549; 0x7f381000b4d0
May 09 15:38:23 srv-01 systemd[1]: janus.service: Main process exited, code=killed, status=11/SEGV
`

I will try to collect a coredump tomorrow.

**Comment by lminiero** [comment]
Please provide a libasan dump too.

**Comment by lminiero** [comment]
Any update?

**Comment by 0xFelix** [comment]
I'm currently not able to reproduce the bug anymore. :( New builds are working again. I'm going to close this for now.
