### ISSUE TITLE
Camera freezes when there's no movement

### ISSUE THREAD

**Issue by antonioTechbase** [meetecho/janus-gateway#1612]
First of all, let me thank you for creating such an amazing product. Everything besides my problem works like a charm.

I'm currently experimenting with your Sip Gateway (Sofia), and I stumble upon this:

When there's no movement at the beginning of the call, the camera starts to freeze/lag. This happens when I move/don't cover the camera when the call start. If I move, the video call works very well.

Is this something related to Janus? (I'm a beginner in this kind of development)

**Comment by lminiero** [comment]
This feels more like a client side issue, as the SIP plugin only relays media around. You may want to check the [Admin API](https://www.meetecho.com/blog/understanding-the-janus-admin-api/) to see if anything's wrong there. Closing.
