### ISSUE TITLE
Request Port different from Contact header field

### ISSUE THREAD

**Issue by cilmeron** [meetecho/janus-gateway#1617]
When Janus sends Requests to the SIP Server it will basically randomly choose a port and not actually use the same port that it sends in its Contact header field. Example:

13:15:19:982 UA:192.168.1.23:60087 SIP Rx REGISTER sip:192.168.1.15 SIP/2.0
13:15:19:982 UA:192.168.1.23:60087 Via: SIP/2.0/UDP 192.168.1.23:47720;rport;branch=z9hG4bK480BttjB469Xj
13:15:19:982 UA:192.168.1.23:60087 Max-Forwards: 70
13:15:19:982 UA:192.168.1.23:60087 From: <sip:48@192.168.1.15>;tag=1KBDve6XD33QN
13:15:19:982 UA:192.168.1.23:60087 To: <sip:48@192.168.1.15>
13:15:19:982 UA:192.168.1.23:60087 Call-ID: 8369da81-edb2-1237-39ba-00155dfc9815
13:15:19:982 UA:192.168.1.23:60087 CSeq: 941618370 REGISTER
13:15:19:982 UA:192.168.1.23:60087 Contact: <sip:48@192.168.1.23:47720>
13:15:19:982 UA:192.168.1.23:60087 Expires: 3600
13:15:19:982 UA:192.168.1.23:60087 User-Agent: WebRTC Gateway
13:15:19:982 UA:192.168.1.23:60087 Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, UPDATE, MESSAGE, INFO
13:15:19:982 UA:192.168.1.23:60087 Supported: path
13:15:19:982 UA:192.168.1.23:60087 Content-Length: 0

Is that intended behaviour and if yes why? Doesn't make sense to me.

**Comment by lminiero** [comment]
Everything SIP related is done automatically by the Sofia SIP stack, so nothing we can do there I'm afraid.

**Comment by lminiero** [comment]
Closing as not a Janus issue.
