### ISSUE TITLE
Consume a long time for sending RTP packet by nice_agent_send.

### ISSUE THREAD

**Issue by vicentWei** [meetecho/janus-gateway#1625]
Hi, in gereral, the execution time of nice_agent_send is about 100us. But when the peerConnections is becoming large (about 300 rooms & 2 publishers per room), the execution time of nice_agent_send is increasing, can be reach 100ms! This result that the age is large than 1s, and discarding too old outgoing packet!
How to sovle the problems? Thanks very much!

**Comment by lminiero** [comment]
Pretty sure you're not using libnice master, as suggested in the README. Older version had a well known bottleneck that is documented on the group. Closing as not a Janus issue.
