### ISSUE TITLE
configure SIP Gateway (libre) plugin

### ISSUE THREAD

**Issue by llongoria** [meetecho/janus-gateway#1628]
Hi, how can i configure SIP Gateway (libre) plugin on new  installation?
<img width="191" alt="Captura de Pantalla 2019-05-16 a la(s) 23 59 11" src="https://user-images.githubusercontent.com/1166207/57904014-a008a900-7836-11e9-87ca-47fd61924cdb.png">

**Comment by lminiero** [comment]
That means the configure script didn't find the required libraries, so you very likely didn't install the development version and their headers. Closing as not an issue.
