### ISSUE TITLE
problems creating rtsp mountpoints through api

### ISSUE THREAD

**Issue by frankville** [meetecho/janus-gateway#1630]
Hi, I'm experiencing some bugs when trying to create rtsp mountpoints through API calls. I'm using minijanus (v0.6.2) library on nodejs to make the calls. 

The first one appears when I'm creating the mountpoint with audio enabled. If audio is configured with PCMA then it all works just fine. The problem appears with pcmu. When I send the creation request and the audio type is pcmu {audio:true, audiortpmap: "PCMU/8000/1", audiopt:0}, despite janus sending the audio stream correctly (I can hear the audio on the app) it seems to fail to write audio = "yes" on the streaming.jcfg file.  That creates a problem when janus restarts, causing janus not to send audio anymore because of the audio being disabled on the config file

The second issue is with the name of the mountpoint. If I send the request with something like {name: "5c50a4540c9274decc9fbe92",...,permanent:true} janus starts the stream with no problem but fails to write the mountpoint to the jcfg file and throws this error 

	[ERR] [config.c:janus_config_save_list:601] Error saving group '5c50a4540c9274decc9fbe92' to the config file...

in which case it also fails to start the stream again if janus is restarted. The strange thing is that if I create the mountpoint like this {name: "a-5c50a4540c9274decc9fbe92"} then janus has no problem writing the config file and does not throw any errors.

Those were the issues I've found so far. For now I'm doing some workarounds to prevent those errors like manually updating the config file after mountpoint creation so when janus restarts it can load the configuration correctly. I hope it helps. Janus is the best WebRTC tool out there. Keep up the good work!

**Comment by lminiero** [comment]
Mountpoint names can't start with a number. It's a limitation in libconfig apparently. I'll check the other issue when I'm back at the office on Monday.

**Comment by frankville** [comment]
I can confirm that if I add a letter at the beginning of the name then janus doesn't throw any errors and the mountpoint is persisted in the config file.

**Comment by lminiero** [comment]
The above mountpoint should solve both issues. For mountpoint names starting with a number, we simply prefix them with `mp-` as we already do when a name is not provided and so we craft one from the ID. Closing, please let me know if it's still an issue.
