### ISSUE TITLE
pb with compilation utils.h

### ISSUE THREAD

**Issue by trankkilou** [meetecho/janus-gateway#1632]
Hi,

I have issue compiling janus last available master version
All deps are presents (it is not the first time I compile janus)

janus claims not finding utils.h

events/eventhandler.h:233:2: error: unknown type name 'janus_flags'
  janus_flags events_mask;

I check where typedef or #define which define type 'janus_flags'.... but it is missing !!!

root@inwebrtc1n:/opt/janus-gateway# grep -RIw janus_flags .
./events.c:void janus_events_edit_events_mask(const char *list, janus_flags *target) {
./events.c:     janus_flags mask;
./events.c:             memcpy(target, &mask, sizeof(janus_flags));
./events.h:void janus_events_edit_events_mask(const char *list, janus_flags *target);
./ice.h:        janus_flags webrtc_flags;
./events/eventhandler.h:        /*! \brief Mask of events this handler is interested in, as a janus_flags object */
./events/eventhandler.h:        janus_flags events_mask;

**Comment by trankkilou** [comment]
i remove the plugin which needs it and I have the same issue with another file
make[2]: Entering directory `/opt/janus-gateway'
  CC       plugins/plugins_libjanus_echotest_la-janus_echotest.lo
In file included from plugins/janus_echotest.c:107:0:
plugins/plugin.h:160:22: fatal error: refcount.h: No such file or directory
 #include "refcount.h"

**Comment by lminiero** [comment]
No idea what you're doing wrong, sorry... definitely works fine here. Have you tried with a clean setup?

**Comment by trankkilou** [comment]
It is a clean setup. Fresh install, can’t be more « fresh"

**Comment by trankkilou** [comment]
I have delete the folder and did a git clone again -> issue solved. Dunno what happen first time

**Comment by lminiero** [comment]
Good to know it's solved :+1:
