### ISSUE TITLE
Cannot push event (handle not available anymore or negotiation stopped)

### ISSUE THREAD

**Issue by lcarneirofreitas** [meetecho/janus-gateway#1633]
Hi,

We have updated our janus-gateway version from the commit d0fecb0 to the 47b3ce319.

With the version 47b3ce319, the Janus keeps crashing.

We, fortunately, have the stack trace of the error below:

https://pastebin.com/wgTRVEUU

Thanks

**Comment by lminiero** [comment]
You may want to try master, as we made other fixes to the SIP plugin recently.

**Comment by tmatth** [comment]
I've opened a PR #1634 as I believe this bug is still possible with the latest master.
