### ISSUE TITLE
config.dataChannel is undefined if Janus is compiled with --disable-data-channels argument

### ISSUE THREAD

**Issue by mykola-mokhnach** [meetecho/janus-gateway#1637]
1. Compile janus server with `--disable-data-channels` argument and streaming plugin enabled
2. Start the server
3. Add any "fake" entry into streaming config, so ICE fails 
4. Try to connect to the added entry from demo ui and wait until the connection fails

Actual result:
![data_ch](https://user-images.githubusercontent.com/7767781/58326062-fde75300-7e2b-11e9-89c1-a706bb9543b4.png)

message in the Console

Expected result:
The demo javascript should properly handle the unavailability of data channels

**Comment by lminiero** [comment]
Pretty sure we fixed this already. Please try master (including janus.js from master).

**Comment by mykola-mokhnach** [comment]
Yes, master seems to be fine. Thanks
