### ISSUE TITLE
No media path established when SIP call traversed Janus 

### ISSUE THREAD

**Issue by oofp** [meetecho/janus-gateway#1641]
Hello, I have developed Haskell client library for Janus and successfully use for more then a year. Now I wanted to create demo for simple back to back SIP call trough Janus. I have attached the client twice to SIP plugin and then receive "incomingcall" on one plugin and created outbound call on another plugin with SDP of incoming call. Similarly I forwarded  SDP answer of accepted call from outbound leg to inbound. On signalling level everything worked fine,  but media path was not established. I am attaching log for the issue. Not sure, if it is expected to work, so please reject this ticket, if it does not work by design.
[janus.log](https://github.com/meetecho/janus-gateway/files/3219970/janus.log)

Thanks a lot.

**Comment by lminiero** [comment]
This isn't the type of issue you'll solve by looking at logs. You'll have to capture traffic somehow (especially SIP signalling) to see why media streams can't be established. Pretty sure it's a setup issue and not a Janus one (which means this question probably belongs to the [group](https://groups.google.com/forum/#!forum/meetecho-janus) and not here) but I'll keep the issue open until you can confirm that's the case.

**Comment by oofp** [comment]
Thanks Lorenzo. I captured tcpdump (attached along with new janus logs). SIP signalling shows successful setup of two SIP dialogs and SDP are properly exchanges. I also see two RTP stream incoming sent by SIP provider to Janus, but there is no RTP traffic from Janus to SIP provider. 


[janus2.zip](https://github.com/meetecho/janus-gateway/files/3223674/janus2.zip)
![RtpStreams](https://user-images.githubusercontent.com/25211514/58419356-61ee5f00-8058-11e9-9a16-cb9c303910d8.PNG)


Please let me know if I can provide any further information.
Thanks

**Comment by oofp** [comment]
Just wanted to add that log shows that both relay threads started in incoming RTP streams were detected by SIP plugin instances

[Mon May 27 11:55:18 2019] Starting relay thread (112229_11 <--> sip:19058833463@toronto2.voip.ms)
[Mon May 27 11:55:18 2019] Got SIP peer audio SSRC: 82182365

[Mon May 27 11:55:18 2019] Starting relay thread (112229_10 <--> sip:112229_5@158.85.70.149)
[Mon May 27 11:55:29 2019] Got SIP peer audio SSRC: 1401247833

**Comment by lminiero** [comment]
No idea on why you think fixing the WebRTC side fixes SIP for you. The SIP plugin has nothing to do with the WebRTC side of things.

**Comment by lminiero** [comment]
Pretty sure your issue had nothing to do with the SIP plugin. You had issue establishing the WebRTC connectivity on one of the two legs instead. If that's the reason, you should inspect the Admin API on the reason for that. I don't think trickling or not trickling has any effect on that.

**Comment by oofp** [comment]
Indeed issue is not with SIP plugin. The reason i that media path path is not established is not completion of ICE check. ICE check is not completed because despite  a=end-of-candidates appears at SDP, ICE check expects more trickled candidates.

**Comment by lminiero** [comment]
> ICE check is not completed because despite a=end-of-candidates appears at SDP, ICE check expects more trickled candidates.

But that's where I'm not convinced. This is how Janus has worked for years: we advertise both, and it still works. Saying we'll trickle and putting an end-of-candidates as well simply means we'll wait a bit longer before considering ICE failed. Unless you're trying to have Janus talk to itself on the WebRTC side?

**Comment by oofp** [comment]
Right, in my case webrtc side on both WebRTC parties are represented by Janus. I proposed another Pull request which starts ICE checks once trickle with 'completed:true' is received. Right after sending SDP with end-of-candidates I also sent trickle with "completed:true" to confirm that no more candidates are expected. It solved the media path problem after applying change at pull request. Thanks.

**Comment by oofp** [comment]
Yes, in my case both WebRTC side are represented by Janus. I am proposing another change when we just ensure that ICE check is in progress when all trickled candidates are received. It solved the problem.

**Comment by lminiero** [comment]
Have you checked if just #1635 (that we now merged, so you can try the new master) fixes it for you?

**Comment by oofp** [comment]
Thanks Lorenzo. I tried new master and had the same problem. Then I re-added the https://github.com/meetecho/janus-gateway/pull/1644 and it worked again, I am attaching log for both cases.
[1641_log.zip](https://github.com/meetecho/janus-gateway/files/3230207/1641_log.zip)

Thanks

**Comment by atoppi** [comment]
Hi @oofp,
I have prepared a PR to address your issue and other similar scenarios. Can you give https://github.com/meetecho/janus-gateway/pull/1652 a try?

Instead of acting on the JANUS_ICE_HANDLE_WEBRTC_ALL_TRICKLES flag and messing with `completed: true` or `end-of-candidates`, we try to start the ICE handshake upon the arrival of a SDP answer, assuming that Janus knows at least one candidate (that might come from a trickle or the SDP itself).

**Comment by oofp** [comment]
Thanks a lot for such quick turnaround. I will try it later on today

**Comment by oofp** [comment]
@atoppi , @lminiero Thanks a lot, I applied the fix and verified my test cases. All worked: media path has been successfully established. I am closing my PR.
