### ISSUE TITLE
relay pkg to other participant problem

### ISSUE THREAD

**Issue by tesion99** [meetecho/janus-gateway#1645]
I want to relay the incoming rtp pkg to other participants in the function janus_audiobridge_incoming_rtp. When the package is comming, I insert it to participant->outbuf for all the participants, but it does't work. How can I send the pkgs directly without insert them into participant->inbuf ???
Ps: at the same time, only one user can talk, so I don't need the mixer thread.

**Comment by lminiero** [comment]
Not a code issue, so closing. Please use the Group for questions like this.
