### ISSUE TITLE
Recording an individual publisher stream stuck for few seconds (no frame) in simulcast when playback

### ISSUE THREAD

**Issue by ramprakash110109** [meetecho/janus-gateway#1648]
Hello, I was testing video room recording  with simulcast enabled, and when playing the converted webm file, the first ~10 seconds of the video had no frame but the video was normal after ~10 seconds, and there was no issue with the opus file i was able to hear voice from the first second itself.

This issue happens when I was recording an individual publisher's stream and works fine when recording a whole room. In short,  I tested four scenarios  and one didn't work and had this issue

1. Without Simulcast and whole room recording - Works Well, no stuck
2.Without Simulcast and individual publisher recording - Works Well, no stuck
3.With simulcast and whole room recording - Works Well, no stuck
4.With simulcast and individual publisher recording - No frame for first 10 seconds, after that no issue

I printed some value to check whether writing packet to recording context was delayed but the function was called immediately as soon as i starts recording. Can anyone help me with this issue ?

Thanks

**Comment by lminiero** [comment]
The "no frame first 10s" means there was no keyframe in those first 10s, and this was only fixed after one arrived 10s later (assuming you're using the default 10s regular keyframe requests here).

**Comment by lminiero** [comment]
By individual publisher recording, do you mean with a `configure` *after* the publish, or when specifying the recording info in the `joinandconfigure`/`publish` itself?

**Comment by ramprakash110109** [comment]
Yes, For a publisher’s stream, i first publish it and then send a configure request to record after some mins. I also thought of key frame issue first, but it was working fine in non-simulcast mode (individual stream recording).  May be there was no Keyframe in the sub stream layer for 10 seconds before it got downgraded or eventually get’s one in the same layer.

**Comment by lminiero** [comment]
You may want to check if configuring the recording in the original publish request solves it, as it will enable recording before the PeerConnection is even set up, and so you won't lose any frame for sure.

**Comment by lminiero** [comment]
Closing as I don't believe this is an issue in Janus.

**Comment by ramprakash110109** [comment]
As you said, it’s the keyframe issue and when i also set keyframe to true in the configure request along with the record true property, it works as expected. Now, thinking of calling fir req in the janus plugin itself after janus recorder create. But still can’t figure out how it works without triggering any keyframe in non-simulcast mode. Anyway, thanks for the tip.
