### ISSUE TITLE
Data messages seems to always fallback on the default "JanusDataChannel".

### ISSUE THREAD

**Issue by ru-imajion** [meetecho/janus-gateway#1649]
There seems to be an issue with the recently added multi-data channel support.  It seems to always be falling back on the default label.

Looks like there is a good label at 
`janus_videoroom.c(4373): janus_videoroom_incoming_data()`
but nothing is done to get that through to 
`janus_videoroom.c(6420): janus_videoroom_relay_data_packe() `
so that it can be fowarded on.

**Comment by lminiero** [comment]
We only added multidata support for the Unified Plan branch. The VideoRoom plugin in master still only uses the default one, as there's no way to serve data from multiple sources on the same PeerConnection there. Closing.

**Comment by ru-imajion** [comment]
Ok, I'll just mention that I noticed it because it changed from previous behavior.  It seems that it is now necessary to use the label 'JanusDataChannel' when creating the data channel.

And thanks for all your efforts on this great project.

**Comment by lminiero** [comment]
Fair point, as before it was indeed the only label we supported! :+1:
