### ISSUE TITLE
[ERR] [ice.c:janus_ice_outgoing_traffic_handle:4124]

### ISSUE THREAD

**Issue by mmar2228** [meetecho/janus-gateway#1658]
Dear all,

I have using streaming plugin's Janus Gateway. I use the following  configuration in janus.plugin.streaming.jcfg file:

sample: {
type = "rtp"                                                                                                            
description = "camera_1"                                                                                                
videobufferkf = false                                                                                                   
audio = false                                                                                                           
video = true                                                                                                            
videoport = 5004                                                                                                        
videopt = 96                                                                                                            
videortpmap = "H264/90000"                                                                                              
videomcast = "239.192.140.12"                                                                                           videofmtp="packetization-mode=1;profile-level-id=42e016"                                                        
}     

Once janus is started, sometimes after several seconds, I get the following error and streaming stops:

[ERR] [ice.c:janus_ice_outgoing_traffic_handle:4025] [3147766270662971] ... only sent -1 bytes? (was 1482)
[ERR] [ice.c:janus_ice_outgoing_traffic_handle:4025] [3147766270662971] ... only sent -1 bytes? (was 1482)              
[ERR] [ice.c:janus_ice_outgoing_traffic_handle:4124] [798453743073346] ... only sent -1 bytes? (was 1482)               
[ERR] [ice.c:janus_ice_outgoing_traffic_handle:4124] [798453743073346] ... only sent -1 bytes? (was 1482)

Error message is repeated many times, but here I just show a sample.

Any idea about the reason? 

Thanks in advance

**Comment by lminiero** [comment]
Not a code issue, please use the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for problems like this.
