### ISSUE TITLE
listeners can't join another room after leaving a room (video room plugin)

### ISSUE THREAD

**Issue by xenyou** [meetecho/janus-gateway#166]
Listeners can't join another room after leaving a room with video room plugin.
I got this error.

```
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:2258:] Already in as a listener on this handle
```

Is this a spec or bug?
Do I have to get a new handle after leave to join another room?

**Comment by lminiero** [comment]
Yes, right now you cannot re-use a handle to join a different room, you'll have to close that and use a different handle.

**Comment by xenyou** [comment]
Okay, thanks for replying.
