### ISSUE TITLE
SIP plugin issue - SDP parsing fails with multiple b-lines

### ISSUE THREAD

**Issue by zayim** [meetecho/janus-gateway#1662]
SDP parsing fails for valid SDP with error:

`[Mon Jun 10 14:43:24 2019] [31m[ERR][0m [sdp-utils.c:janus_sdp_parse:583] Multiple m-line b= lines: b=RS:1000`

`[Mon Jun 10 14:43:24 2019] [31m[ERR][0m [plugins/janus_sip.c:janus_sip_sofia_callback:3813]     Error parsing SDP! Multiple m-line b= lines: b=RS:1000`

SDP content:

```
v=0
o=- 3790417309 42960157160000 IN IP4 X.Y.Z.W
s=-
c=IN IP4 X.Y.Z.W
t=0 0
m=audio 28594 RTP/AVP 8 126
b=RR:3000
b=RS:1000
a=rtpmap:8 PCMA/8000
a=rtpmap:126 telephone-event/8000
a=fmtp:126 0-15
a=maxptime:40
```

This is most probably introduced with this piece of code merged on April 19th, 2019:

```
if(mline->b_name) {
	if(error)
		g_snprintf(error, errlen, "Multiple m-line b= lines: %s", line);
	success = FALSE;
	break;
}
```

which does not allow SDP to have multiple b-lines, which is perfectly valid according to RFC https://tools.ietf.org/html/rfc4566 which says:

`b=* (zero or more bandwidth information lines)`

**Comment by lminiero** [comment]
We can limit that check to AS, but those RS/RR values the SIP client is setting won't get to the browser, as we don't parse them and so don't regenerate them either. Pretty sure they're not supported by browsers anyway.

**Comment by lminiero** [comment]
Fixed in the above commit.
