### ISSUE TITLE
janus unable to register display

### ISSUE THREAD

**Issue by Core-hx** [meetecho/janus-gateway#1667]
sres: /etc/resolv.conf: unknown option                      
[4001549124150996] Creating ICE agent (ICE Full mode, controlled)
[4001549124150996] Creating ICE agent (ICE Full mode, controlled)
[ERR] [plugins/janus_sip.c:janus_sip_handler:2363] Wrong state (not registered)
[ERR] [plugins/janus_sip.c:janus_sip_handler:2363] Wrong state (not registered)

How to resolve the log error!!!!!!!

**Comment by lminiero** [comment]
Sorry, but I have no idea what you're talking about. You'll have to be much more detailed than that if you want to open issues and have us look at them. Pretty sure it's not a code issue so I'll close. If you can come up with more information on your problem, feel free to refer to our [community group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
