### ISSUE TITLE
UDP port range for media

### ISSUE THREAD

**Issue by trankkilou** [meetecho/janus-gateway#1668]
Hi Lorenzo,

I notice the parameter to limit the use of UDP port range in the janus config file is not working as expected. At least you must be aware of what follows :

It does NOT overwrite the parameter port range in /proc/net
for instance in debian, default UDP range port is set to 40000-65535.

when I set this parameter it work like expected, I didn't test enough to tell if your parameter is used or not because of lack of time.

**Comment by lminiero** [comment]
Why should it override the `/proc/net` settings? That's a system property. Our setting works at an application level and _only_ for WebRTC ports (a system level property would limit all random ports to stay within that range, no matter the purpose), and is something we pass to libnice for them to use, so not something we do ourselves (although some plugins have a similar feature).

Closing as not a code issue.

**Comment by trankkilou** [comment]
As you like. Just be aware the parameter in janus cfg file is just useless. 
I just inform people like me who would like to tune it one day and avoid them to search like me many hours why their webrtc media port are not what they set in janus config

I add my colleague in the loop whenever he wants to add something (if a heart attack didnt kill him while reading your answer 😅)

Julien

**Comment by lminiero** [comment]
Still not sure what the problem you think is. The port range is a frontend to this method here: https://nice.freedesktop.org/libnice/NiceAgent.html#nice-agent-set-port-range

This is, again, an _application-level_ setting. It tells libnice to try and pick ports in that range. Whatever you configure at the system-level is your own responsibility, and nothing we can influence.

**Comment by lminiero** [comment]
Besides, the setting works. We use it all the time, and so do others. If it doesn't work for you, then you're doing something wrong.

**Comment by lminiero** [comment]
If by port range you mean the `ephemeral` port range, then our setting has nothing to do with that either.

The ephemeral port range impacts `bind` requests where you pass `0` as a port, and so want a random port from the system: a system-wide port range would limit that random port to the range specified there. Our range is completely different: when libnice has a port range configured, it will try to do different `bind` requests using ports within that range, until it succeeds. Notice that a port _is_ specified: it is _never_ `0`, and so the ephemeral port range is never involved either.
