### ISSUE TITLE
Js simulates a click event, unable to get the Shared screen

### ISSUE THREAD

**Issue by BadmasterY** [meetecho/janus-gateway#1669]
In the process of using screen sharing, I used JavaScript to simulate user click events to reduce user operands and then failed, as described in the title.

**I want to know if the server detects js mock clicks**, because I have no problem manually triggering the click event.

Among them, there is no problem in communication with the server, and it works well. But the video tag contains no pictures and no sound.

**Comment by lminiero** [comment]
Closing as not a code issue. As clearly explained in the guidelines, questions like this belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
