### ISSUE TITLE
SIGABRT, Aborted

### ISSUE THREAD

**Issue by gatecrasher777** [meetecho/janus-gateway#167]
Janus terminated for reasons unknown.  Hope this helps to detect the issue:

http://pastebin.com/p7pEnFsU

Ubuntu 14.04. Only videoroom plugin was loaded.  Compiled with  --disable-websockets --disable-data-channels --disable-rabbitmq --enable-post-processing --disable-docs

**Comment by lminiero** [comment]
Unfortunately that's not enough. A SIGABRT on a malloc seems to indicate a heap corruption, but the trace has no info on what was corrupted or when. Was this consequence of a lot of participants, or heavy usage for prolonged time? I guess you'll have to check with valgrind, which should give you info on invalid access to memory that may lead to the corruption above: unfortunately it will also really slow down Janus.

**Comment by gatecrasher777** [comment]
Not very heavy usage. However Janus had been running for 3 days without a restart.

**Comment by gatecrasher777** [comment]
I don't know if its related at all, but there does seem to be a certain amount of "creepage" in respect of base CPU and Memory usage as time progresses. So for example, after a restart Janus is close to 0% CPU, but after sessions come and go, the base CPU usage climbs, so that it is using 3% with no user activity on the server, and as more time passes, this will climb to 6%, and so on, never reducing back to 0%. Memory is a similar story. The longer it runs, the higher it climbs.

**Comment by Computician** [comment]
that creepage + the over use of magic numbers(static timeouts to remove things, etc.) could definitely cause something like this after extended usage.

**Comment by lminiero** [comment]
The several memory leaks that have been fixed may have improved this, have you already tried again to see if you're still experiencing this with the latest revision?

**Comment by lminiero** [comment]
Any update on this?

**Comment by lminiero** [comment]
Closing for lack of feedback and because a lot has changed since. Feel free to reopen if it's still an issue.
