### ISSUE TITLE
Send rtp_forward events to eventhandler

### ISSUE THREAD

**Issue by euskadi31** [meetecho/janus-gateway#1671]
Hi,

I would like to use `sampleevh` to receive the creation and stop events of the `rtp_forward` and `stop_rtp_forward` command.

 It possible to add that?

Thx

**Comment by lminiero** [comment]
Sure, it can be added. I'll see if I have time for that next week. Pull requests welcome as well, of course!

**Comment by euskadi31** [comment]
Thx :)

**Comment by lminiero** [comment]
Done: rather than send a single event, we generate a separate event for each stream in an RTP forwarder, both when creating new forwarders and stopping them. This will make it easy to port to the unified-plan branch.

**Comment by euskadi31** [comment]
Wow, Awesome !

Thank You @lminiero
