### ISSUE TITLE
Receive media events after configure request

### ISSUE THREAD

**Issue by VictorQueiroz** [meetecho/janus-gateway#1672]
I read in documentation about media events, but I'm not quite sure what trigger them. I'd like to understand what is the state of video in which of the publishers I'm connected to, is it possible? 

I tried sending "configure" request with different states of "audio" and "video" property but I just receive "slowlink" message on subscribers, no "media" event.

Thank you in advance.

**Comment by lminiero** [comment]
If you mean the Janus API `media` events, they're sent when Janus first receives an audio or video packet from the peer, or when it starts receiving again after no media arrived for `no_media_timer` seconds. Subscribers never send media themselves (they only receive), so obviously Janus will never send them `media` events. Closing as not an issue, please refer to the group for questions like this.
