### ISSUE TITLE
"janus: undefined symbol: srtp_crypto_policy_set_aes_gcm_256_16_auth"， when I run janus

### ISSUE THREAD

**Issue by zengpeace** [meetecho/janus-gateway#1674]
when I start janus，it throw undeifned symbol error:
"janus: undefined symbol: srtp_crypto_policy_set_aes_gcm_256_16_auth"

I deploy janus on ubuntu18.04，libsrtp2.2.0，no boringssl，make configures

**Comment by zengpeace** [comment]
I fix it by adding LD_LIBRARY_PATH

**Comment by 751503375** [comment]
when I start janus，it throw undeifned symbol error:
"janus: undefined symbol: srtp_crypto_policy_set_aes_gcm_256_16_auth"

I deploy janus on ubuntu18.04，libsrtp2.2.0，no boringssl，make configures

 @zengpeace
Author
zengpeace commented on 25 Jun
I fix it by adding LD_LIBRARY_PATH
您好，请问一下如何增加  LD_LIBRARY_PATH，操作步骤是？

**Comment by dsinni** [comment]
@zengpeace Could you possibly provide some more information on how you resolved this issue? Would greatly appreciate it. Thanks.

**Comment by mmgoodnow** [comment]
@dsinni Have you figured it out?

**Comment by BrodieBirko** [comment]
You need to add the path for the libraries Janus uses/created-on-install to the `LD_LIBRARY_PATH `environment variable. Library is usually `/usr/lib` or `/usr/lib64` for me. 

Append it to the environment variable using `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib` before running Janus. 

You will have to do this for every new terminal, or add that line to `.bashrc` and it will automatically.

**Comment by Matthewow** [comment]
Though this question is opened one year ago...  
My personal experience is re-installing the libsrtp2 from the source code, 'https://github.com/cisco/libsrtp', and configure it with all the needed options like --enable-openssl.

It works well for me
