### ISSUE TITLE
Video Game Voice Chat

### ISSUE THREAD

**Issue by nsmith1024** [meetecho/janus-gateway#1675]
Hello, I wrote a WebGL/HTML5 video game that runs in browser (JavaScript), and i want my players to have voice chat so they can talk to each other while playing.

Could i use the Janus Audio Bridge on my server to allow players to create voice rooms and to voice chat?

Thanks!

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), closing as not a code issue.
