### ISSUE TITLE
Audiobridge Sampling Rate issue

### ISSUE THREAD

**Issue by ramprakash110109** [meetecho/janus-gateway#1676]
In audiobridge.c,

1. While creating default room, the sampling rate is set by

janus_config_item *sampling = janus_config_get(config, cat, janus_config_type_item, "**sampling_rate**");

2. While creating dynamic room, the sampling rate is set by

json_t *sampling = json_object_get(root, "**sampling"**);   

There is a mismatch in setting the audiobridge sampling rate. According to jcfg file,   "sampling_rate" is the keyword to be used. But when I used the same key word, Dynamic room don't set the user defined sampling rate because of mismatch in key word. Please, kindly look into this issue.

**Comment by lminiero** [comment]
Yeah, I guess there's some mismatch there. I won't get rid of the existing syntax as that would be a breaking change, but what I can do is support both on the API in order to be consistent and backwards compatible at the same time. I'll take note that this needs fixing.

**Comment by lminiero** [comment]
Notice that the documentation explicitly mentions `sampling` for the API, though.
https://janus.conf.meetecho.com/docs/audiobridge
