### ISSUE TITLE
service start error

### ISSUE THREAD

**Issue by WJdenghuo** [meetecho/janus-gateway#1681]
ubuntu 16.4 64

in end
 /opt/janus/bin/janus --debug-level=7 --nat-1-1=ip --stun-server=*:3478 --cert-pem=*_bundle.crt --cert-key=*.key

[FATAL] [transports/janus_http.c:janus_http_init:784] Couldn't start webserver on port 8088...
[WARN] HTTPS webserver disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
[WARN] No HTTP/HTTPS server started, giving up...
[WARN] The 'janus.transport.http' plugin could not be initialized
Loading transport plugin 'libjanus_pfunix.so'...
JANUS Unix Sockets transport plugin created!
Configuration file: /opt/janus/etc/janus/janus.transport.pfunix.jcfg
[janus.transport.pfunix.jcfg]
    general: {
        enabled: false
        json: indented
    }
    admin: {
        admin_enabled: false
    }
[WARN] Unix Sockets server disabled (Janus API)
[WARN] Unix Sockets server disabled (Admin API)
[WARN] No Unix Sockets server started, giving up...
[WARN] The 'janus.transport.pfunix' plugin could not be initialized
[FATAL] [janus.c:main:4760] No Janus API transport is available... enable at least one and restart Janus

http 8088 work 
 https 8089 no work (use nginx)
rest api https error

**Comment by lminiero** [comment]
Please refer to the group for questions like this.
