### ISSUE TITLE
Error reading --cert parameters from command line

### ISSUE THREAD

**Issue by cyuste** [meetecho/janus-gateway#1683]
Hi there!
I'm having some issues using `--cert-key` and `--cert-pem` options, it looks like it checks if the files exist but then attempts to read the files defined in the .jcfg files

FIrst of all, I am trying to run janus from a container. In the janus.transport.websockets.jcfg file I have set the following:

```
# Certificate and key to use for any secure WebSocket server, if enabled (and passphrase if needed).
certificates: {
	cert_pem = "/etc/ssl/xxx.pem"
	cert_key = "/etc/ssl/xxx.key"
	#cert_pwd = "secretpassphrase"
}
```
**These files do not exist in the container**

To run the container I do:
`docker container run -it  --name janus  --env CERT=domain.crt --env KEY=domain.key  -v /etc/ssl/certs:/etc/ssl/certs -p 7088:7088 -p 8989:8989 -p 5000-5100:5000-5100/udp --entrypoint /bin/bash  cyuste/janus`

What internally calls a bash file that calls janus with this command:

```
./janus --rtp-port-range=5000-5100 --cert-pem=/etc/ssl/certs/${CERT} --cert-key=/etc/ssl/certs/${KEY} --nat-1-1=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
```

The nat part is because we are running it in AWS and we do not need stun and everything, anyway

If I run the container pointing to files that do not exist janus fails (as expected)

If I run the container pointing to the actual certificate/key files I get the following error:
```
[WARN] WebSockets server disabled
[FATAL] [transports/janus_websockets.c:janus_websockets_init:651] Error creating vhost for Secure WebSockets server...
[WARN] Admin WebSockets server disabled
[WARN] Secure Admin WebSockets server disabled
[WARN] No WebSockets server started, giving up...
[WARN] The 'janus.transport.websockets' plugin could not be initialized
[FATAL] [janus.c:main:4760] No Janus API transport is available... enable at least one and restart Janus
```

If I modify the entrypoint so I get a bash console instead of starting janus, modify the  janus.transport.websockets.jcfg to point to the actual files and then start janus it works

If any information is missing please let me know and thank you very much for your help and for developing janus!

**Comment by lminiero** [comment]
The command line flags you mentioned are only for DTLS, not the transports. Those (including for websockets) need to be configured in the jcfg file. Closing as not an issue.

**Comment by mingzhanghui** [comment]
Generate self-signed DTLS cert (if you don’t already have one)
If you're just testing locally or don’t care about being "trusted," you can generate a self-signed DTLS cert like this:

bash
Copiar
Editar
mkdir -p /opt/janus/certs
cd /opt/janus/certs
openssl req -x509 -newkey rsa:2048 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=janus"
Then in janus.jcfg, set:

ini
Copiar
Editar
cert_pem = "/opt/janus/certs/cert.pem"
cert_key = "/opt/janus/certs/key.pem"
