### ISSUE TITLE
mvideoroomtest.js leave room will occur an error in another client

### ISSUE THREAD

**Issue by jfdream** [meetecho/janus-gateway#1684]
Hello,I use unified-plan branch, I try the demo mvideoroomtest.js and find a problem, when someone leave this room, I receive on error from safari browser.

WebRTC error... {"stack":"Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote audio description streams."}

**Comment by lminiero** [comment]
Can you provide the remote SDP that causes the issue in a pastebin/gist link?

**Comment by jfdream** [comment]
Thank you for your reply, this is my sdp

https://gist.github.com/jfdream/1ca897b9e7332edeeff3b89aab58d312

**Comment by lminiero** [comment]
It may have something to do with the fact that both SSRCs are 0, because apart from that everything looks fine. I'll try and replicate in the next few days.

**Comment by lminiero** [comment]
Solved in https://github.com/meetecho/janus-gateway/pull/1459/commits/a0300e499b04e0ced81e164069eadb4ec4fbd7d2
