### ISSUE TITLE
I met a problem that is when i run echo test demo, it throw an error which is ICE failed for component 1 in stream 1...

### ISSUE THREAD

**Issue by Wdiviner** [meetecho/janus-gateway#1690]
>Hello , I met a problem when i run echo test, it throw a problem which is ICE failed for component 1 in stream 1...  
>And i don't konw why this happen, so i hope someone could help me solve this problem, i'll appreciate it!

**Comment by lminiero** [comment]
As explained in the guidelines, question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Closing.
