### ISSUE TITLE
Windows service does not start

### ISSUE THREAD

**Issue by AleCaste** [meetecho/janus-gateway#1697]
Hello, I did a fresh installation of this windows release:
[https://github.com/janus-gateway/janus-gateway/releases/download/v0.2.0.W/janus_setup_v0.2.0_x64.exe](url)
... to the folder:  `C:\Programs\Janus WebRTC Gateway`
My windows version is `Windows 10 Pro Version 1809 (build 17763.615)`
The problem is that the `Janus WebRTC Gateway` service cannot start.
Whenever I try to start it, I get the error `The system cannot find the file specified.`

Any ideas?

**Comment by lminiero** [comment]
Not sure where you took that file, but we certainly didn't prepare it. Besides, 0.2.0 is super-old and Windows is not officially supported: you have to run Janus in WSL if you want Windows. Closing.

**Comment by alexamirante** [comment]
The file has been taken from [this repository](https://github.com/janus-gateway/janus-gateway), which **IS NOT** the official Janus repo and **IS NOT** maintained by Meetecho. I don't know why [this account](https://github.com/janus-gateway) has the Meetecho logo, it definitely shouldn't and it is misleading.

@marcin-sielski as you seem to be involved in that GitHub organization (I see commits from you), can you have the Meetecho logo removed?

**Comment by lminiero** [comment]
Not only the logo: the account name is severely misleading, and must be changed as well. We can't tolerate this abuse.
