### ISSUE TITLE
[FATAL] [transports/janus_http.c:janus_http_init:784] Couldn't start webserver on port 8088

### ISSUE THREAD

**Issue by e1th0r** [meetecho/janus-gateway#1699]
Disabling ipv6 from grub (GRUB_CMDLINE_LINUX="XXXX ipv6.disable=1") avoid to start janus webserver service.

`[WARN] libwebsockets has been built without IPv6 support, will bind to IPv4 only
WebSockets thread started
[FATAL] [transports/janus_http.c:janus_http_init:784] Couldn't start webserver on port 8088...`

Enabling ipv6 allow start the service

`[WARN] libwebsockets has been built without IPv6 support, will bind to IPv4 only
libwebsockets logging: 0`
`WebSockets server started (port 8188)...`
`[WARN] Secure WebSockets server disabled`
`[WARN] Admin WebSockets server disabled`
`[WARN] Secure Admin WebSockets server disabled`
`JANUS WebSockets transport plugin initialized!`
`Loading transport plugin 'libjanus_http.so'...`
`HTTP webserver started (port 8088, /janus path listener)...`

 but port 8088 is using ipv6 protocol:

`tcp6       0      0 :::8088                 :::*                    LISTEN      0          20312      1077/janus `

ipv6 is disable on janus.jcfg configuration file.

Using ipv6 we get next issue on sip gateway:
 
`WebRTC error... "getUserMedia not available" `

So, does we have and configuration issue or it is a bug?

Thank you.

**Comment by lminiero** [comment]
Answered on the group. Closing.
