### ISSUE TITLE
[Unified Plan] SDP parsing segfault on build without usrsctp

### ISSUE THREAD

**Issue by Bug-Fairy** [meetecho/janus-gateway#1700]
Janus crash on Debian 10 when running echotest on Firefox.

Caused by building without usrsctp and offering data channel.
`janus_handle_webrtc_medium_create(handle, JANUS_MEDIA_UNKNOWN)` returns NULL when further logic expects medium to never be NULL.
https://github.com/meetecho/janus-gateway/blob/unified-plan/sdp.c#L195

Edit:
Exact crash line:
https://github.com/meetecho/janus-gateway/blob/unified-plan/sdp.c#L205

**Comment by lminiero** [comment]
Thanks for spotting this, I'll have a look :+1:

**Comment by lminiero** [comment]
Fixed in this commit https://github.com/meetecho/janus-gateway/pull/1459/commits/66bff683b5f1c83ddca520e634a9010058c20942
