### ISSUE TITLE
API To start and stop streaming

### ISSUE THREAD

**Issue by zetrixweb** [meetecho/janus-gateway#1701]
Hello,

I want to integrate this into my iOS and Android mobile application, So can you please guide me how I can get two APIs

1. Start streaming - It will return me my streaming URL
2. Stop streaming - it will stop my streaming and give me success message(Destroy URL),

Thank you in advance,

**Comment by lminiero** [comment]
As clearly explained in the guidelines, questions like this belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Besides, we have an extensive documentation you should read first. Closing.
