### ISSUE TITLE
Audio Bridge API synchronous request does not give an answer in onmessage()

### ISSUE THREAD

**Issue by mtltechtemp** [meetecho/janus-gateway#1702]
I'm trying to find out if a room exists by making this request:
```js
this.audiobridge.send({
  message: { request: "exists", room: 1234 }
});
```
In the console i have:
```
Synchronous transaction successful (janus.plugin.audiobridge)
```

No response in the `onmessage()`callback.
Have I missed something?

**Comment by lminiero** [comment]
Synchronous response don't go in `onmessage`, but in the `send` success callback. See the existing demos for examples. Closing.
