### ISSUE TITLE
Videoroom doesn't work reliably on chromebook

### ISSUE THREAD

**Issue by groupboard** [meetecho/janus-gateway#1705]
Using an Acer C720 chromebook with the latest updates:

- log into videoroom test page on chromebook
- on a Windows 10 PC, log into the videoroom test page using firefox

Both users see their own video, but the firefox PC user doesn't see the chromebook video.  Sometimes you need to reload the firefox page a few times to see it happen.

When using chrome it says "no remote video available", and then the video appears after about 10 seconds. Firefox just gives a white video window and never starts working.

It could be due to a buggy vp8 encoder on the chromebook, as it seems to work perfectly on our server when using h264.

**Comment by lminiero** [comment]
I'm afraid I never tested on a Chromebook, and don't have access to one... have you checked using the Admin API if media is flowing? You should check the chromebook publisher handle, and the firefox subscriber handle, to see if you can spot any anomaly. But if it works as expected with H.264, it might be indeed a problem it has with VP8 (have you tried VP9 as well?).

Do other demos using VP8 succeed? e.g., EchoTest, or VideoCall with Chromebook+Firefox?

**Comment by groupboard** [comment]
Some tests:

- videocall works fine.
- it works reliably on our server using vp8 or h264
- the demo on the meetecho.com server seems to work occasionally, and if it does work then reloading the page seems to cause it to fail
- about:webrtc shows that firefox is indeed receiving the video data, just not displaying it for some reason

Are you running the latest binary on your server? Ours is about a month or two old.

**Comment by lminiero** [comment]
> Are you running the latest binary on your server? Ours is about a month or two old.

We update it regularly, the last time a few hours ago.

**Comment by groupboard** [comment]
I'll try updating janus on our server whenever it's not in use.

**Comment by groupboard** [comment]
Server updated to latest code. Still working every time on our server, but mostly not working on the meetecho server. Although it does seem to work sometimes on the meetecho server...if I unpublish the feed from the chromebook and publish it again, it starts appearing on firefox. It also works from then on if the firefox user reloads.

I'll test later with the stock videoroom cfg file on our server to double check that isn't causing the issue.

**Comment by groupboard** [comment]
It still works perfectly on our server with the default videoroom cfg, but fails half the time on the meetecho server. I did notice that you're using http transport rather than websocket, so it takes a while for it to notice disconnects. That shouldn't have any effect on the video, so it might be unrelated. I don't have access to your admin page, so it's difficult for me to troubleshoot any more.

**Comment by lminiero** [comment]
We don't have TURN configured on those demos. If network is picky on your endpoints, that may be it.

**Comment by groupboard** [comment]
I did remove the TURN server and it still worked on our server. Also, that wouldn't explain why it works sometimes on meetecho.com. And when I check the webrtc stats it does seem to be connected ok.

**Comment by lminiero** [comment]
Is this still a problem? I'm not convinced it's an issue in Janus, but rather an issue on Chrome instead.

**Comment by groupboard** [comment]
I did some testing today, and it does seem to be working ok now.
