### ISSUE TITLE
Install Janus for Windown

### ISSUE THREAD

**Issue by zenlykoi** [meetecho/janus-gateway#1711]
How can i install lastest version janus in window? please help me!

**Comment by lminiero** [comment]
There's no version of Janus for Windows. The only way to install it there is using the WSL (Windows Subsystem for Linux), as explained in the README. Closing.

**Comment by stefanache** [comment]
Hi,
Janus can't be installed on/in Windows because it is only for Linux.
But need that need to have Windows 10 and can use on this Ubuntu 18.04 WSL:
https://www.arabicprogrammer.com/article/69642491441/
Bye
