### ISSUE TITLE
unified-plan publish more video stream 

### ISSUE THREAD

**Issue by jfdream** [meetecho/janus-gateway#1722]
The video picture is not clear when the multi-channel video stream is published

**Comment by lminiero** [comment]
Sorry but I have no idea what issue you think is there :slightly_smiling_face: 
You'll have to be clearer than that, and possibly provide steps to replicate the issue, if any.

**Comment by jfdream** [comment]
I use unified-plan branch, using the following code to create multiple video streams in the sdp. No matter which stream the receiver looks at, it is not clear.

https://gist.github.com/jfdream/48d04739a7e987de3fdbe583a24802ba

**Comment by lminiero** [comment]
That still says nothing about the issue. I see a 120p in your snippet, which very likely means it's you asking a tiny video. Closing.
