### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [meetecho/janus-gateway#1725]
I would like to point out that an identifier like “[`_JANUS_CORE_H`](https://github.com/meetecho/janus-gateway/blob/c6a1255ec5084afb8158cda972eeb09cec50372b/janus.h#L18 "Update candidate")” [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by lminiero** [comment]
Thanks for pointing that out. I'll keep note that this needs fixing when we get back from our vacation.
