### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by FrankMiller9000** [meetecho/janus-gateway#1726]
./janus: symbol lookup error: ./janus: undefined symbol: srtp_crypto_policy_set_aes_gcm_256_16_auth
ubuntu@ip-172-31-17-87:~/janus-gateway$ sudo janus ./janus --version

**Comment by lminiero** [comment]
I think you need a newer OpenSSL and/or libsrtp2. Closing as not a code issue.

**Comment by AndreyMiloserdov** [comment]
Updated everything, recompiled - same error (ubuntu 18.10)

**Comment by gabrieljbaker** [comment]
Hi @AndreyMiloserdov , did you ever find a resolution to this? I am running into the same issue.

**Comment by gabrieljbaker** [comment]
@lminiero Are you able to suggest anything else that might resolve this? Any help would be greatly appreciated.

**Comment by gabrieljbaker** [comment]
@HenkHull , also curious if you were able to resolve this!
