### ISSUE TITLE
Janus "Plugin Demo: Streaming" Opus/VP8 live stream is not working on Safari 12.1

### ISSUE THREAD

**Issue by ayafuji** [meetecho/janus-gateway#1736]
I've tried Plugin Demo: Streaming ( https://janus.conf.meetecho.com/streamingtest.html ) on Safari 12.1.2 (14607.3.9). 
It seems that safari version is enough to watch this. Because safari 12.1 support for VP8. 

``` 
Added support for H.264 simulcast and VP8 in WebRTC to improve support for multi-party video conferencing.
```
by  https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes

But when pushing "Watch or Listen" Button after selected Opus/VP8 live stream in pull down menu.
<img width="684" alt="スクリーンショット 2019-08-14 14 20 25" src="https://user-images.githubusercontent.com/6086940/62996344-5b28f880-be9f-11e9-85f3-15a002eff48c.png">

And waiting few seconds, it shows first frame. but stop completely.
<img width="686" alt="スクリーンショット 2019-08-14 14 20 39" src="https://user-images.githubusercontent.com/6086940/62996364-7562d680-be9f-11e9-950e-9c9fd15b9d7c.png">

Envrionment : 
Safari : 12.1.2 (14607.3.9)
mac OS : 10.14.6（18G84）

Also I've faced a same issue on iPhone safari. 

![IMG_8088](https://user-images.githubusercontent.com/6086940/62996677-76483800-bea0-11e9-8eac-fddad0b9abc9.PNG)

Stop Streaming at first frame on iPhone safari.
![IMG_8089](https://user-images.githubusercontent.com/6086940/62996688-7a745580-bea0-11e9-8a7c-5915c101160a.PNG)

and Safari version :
![IMG_8087](https://user-images.githubusercontent.com/6086940/62996710-8e1fbc00-bea0-11e9-9b56-634c28ac48ba.PNG)

Do I need other version of safari? or Should I install extra software to watch this?

**Comment by ayafuji** [comment]
This is for safari's specific security policy of between capture device and getting ice candidate according to https://webkit.org/blog/7763/a-closer-look-into-webrtc/.
If I want to get a accurate ice candidate from janus server, we have to take a capture device permission from each browser  (ios/macos) safari despite we actually dont use it.

proof mentioned above, I disable this security option using macos safari deveplopment mode. the streaming demo shows accurate frame. My next step is taking capture device permission during streaming demo sequence and code.

**Comment by lminiero** [comment]
Assuming it's a browser thing, then. Closing.

**Comment by djkoza** [comment]
Any updates of this? I have same problem with iOS devices. How to deal with that case?
Taking capture device permission is the right solution for streaming plugin on iOS device?
