### ISSUE TITLE
Could SIP plugin (Sofia) support codec configuration

### ISSUE THREAD

**Issue by chyxion** [meetecho/janus-gateway#1746]
It would be really useful for me to have the ability to set media codec priority.

For example: 
enable `PCMU/8000` only.
Or set codec order such as `PCMU/8000,PCMA/8000,G722/8000`

Thanks for your amazing project.

**Comment by lminiero** [comment]
I'll add the `enhancement` label to the issue, but to be honest it's very low priority for us. As such, no idea if/when it will be done. Pull requests always welcome of course!

**Comment by lminiero** [comment]
Besides, it's not really up to us: we only act as intermediaries between browser and SIP devices. The real negotiation happens between them.

**Comment by chyxion** [comment]
Thanks for your reply. 
I agree with your opinion, and I changed the SIP server's config. 
Thanks again.

**Comment by lminiero** [comment]
Closing as, after giving it some thought, we don't plan to add the feature. Good to know you fixed it on the SIP side!

**Comment by JuanJEA** [comment]
> It would be really useful for me to have the ability to set media codec priority.
> 
> For example:
> enable `PCMU/8000` only.
> Or set codec order such as `PCMU/8000,PCMA/8000,G722/8000`
> 
> Thanks for your amazing project.



> Thanks for your reply.
> I agree with your opinion, and I changed the SIP server's config.
> Thanks again.


Hi, can you give me an example of how you managed to prioritize a specific codec please. I have tried everything and I have not succeeded..

Thank you

**Comment by chyxion** [comment]
You may setup your SIP server's codec priorities

OR customize client's SDP on `sipcall.createAnswer/sipcall.createOffer`

```javascript
// sipcall.createAnswer
sipcall.createOffer({
    jsep: jsep,
    media: { audio: doAudio, video: doVideo },
    success: function(jsep) {
        // ...
    },
    error: function(error) {
        // ...
    },
    customizeSdp: function(jsep) {
        if (jsep && jsep.sdp) {
            const codecsKeep = []
            const removed = []
            jsep.sdp = jsep.sdp.split('\n')
                // remove codecs not in ['PCMA/8000', 'telephone-event/8000']
                .filter(row => {
                    // a=rtpmap:111 opus/48000/2
                    // a=rtpmap:9 G722/8000
                    const m = row.match(/^a=rtpmap:(\d+)\s(([\w-]+)(\/\d+)+)/)
                    if (m) {
                        // keep PCMA/8000 and telephone-event/8000
                        if (['pcma/8000', 'telephone-event/8000'].includes(m[2].toLowerCase())) {
                            codecsKeep.push(m[1])
                        } 
                        else {
                            removed.push(m[1])
                            return false
                        }
                    }
                    return true
                })
                // remove rtcp-fb, fmtp
                .filter(row => {
                    // a=rtcp-fb:111 transport-cc
                    // a=fmtp:111 minptime=10;useinbandfec=1
                    const m = row.match(/^a=(?:rtcp-fb|fmtp):(\d+)\s.+/)
                    if (m) {
                        if (removed.includes(m[1])) {
                            return false
                        }
                    }
                    return true
                })
                // update audio codecs
                .map(row => {
                    const m = row.match(/^(m=audio \d+ [A-Z/]+)(?: \d+)+/)
                    if (m) {
                        return m[1] + ' ' + codecsKeep.join(' ')
                    }
                    return row
                }).join('\n')
        }
  }
})
```

**Comment by lminiero** [comment]
Do these discussions on the group, NOT here.

**Comment by kinsleykajiva** [comment]
hi @chyxion , do you have the same implementation  in java ?
