### ISSUE TITLE
Janus incorrect use DNS SRV in SIP register process

### ISSUE THREAD

**Issue by lukaszw544** [meetecho/janus-gateway#1747]
Hello,
I use DNS SRV to provide HA, but in registration process to my Freeswitch Janus sometimes traying register to two hosts in one registration process.
And finaly I get error:
_Got a Janus API event to send (0x7f21740025a0)
  >> Pushing event: 0 (Success)
[101][nua_r_register]: 401 Unauthorized
        Digest:"sip.ge":101:1234
[101][nua_r_register]: 401 Unauthorized
        Digest:"sip.ge":101:1234
[101][nua_r_register]: 904 Operation has no matching challenge_

The register sequence look like:
ENPOINT ---> register ---> Freeswitch **(HOST A)**
ENPOINT <--- 401 unauthorized<--- Freeswitch **(HOST A)**
ENPOINT ---> register ---> Freeswitch **(HOST B)**
ENPOINT <--- 401 unauthorized<--- Freeswitch **(HOST B)**

The correct sequence should be (sometimes it happens):
ENPOINT ---> register ---> Freeswitch **(HOST A)**
ENPOINT <--- 401 unauthorized<--- Freeswitch **(HOST A)**
ENPOINT ---> register ---> Freeswitch **(HOST A)**
ENPOINT <--- 200 OK<--- Freeswitch **(HOST A)**

Janus version 0.6.1

**Comment by atoppi** [comment]
Janus does not directly handles the DNS queries when registering to the SIP server. That is delegated to the underlying sofia-sip stack.

**Comment by lminiero** [comment]
Yes, what Alessandro said. Besides, 0.6.1 is too old, and we don't investigate problems on older versions that may have been fixed already: please only open issues for master.

**Comment by lminiero** [comment]
@lukaszw544 do you have a .pcap dump of the problem happening? Just trying to understand if this may be related: https://sourceforge.net/p/sofia-sip/mailman/message/18563431/

**Comment by lminiero** [comment]
Closing for lack of feedback, and we can't investigate if you disappear. Feel free to reopen if you can provide the data we asked for.

**Comment by lukaszw544** [comment]
Hi, I'm sorry I haven't written for awhile.
I have .pcap dump, where I was tryaing register several times. 
The last test was correct.
Please look at this.
https://we.tl/t-Wl7cATtD69

**Comment by lminiero** [comment]
I think you're doing something wrong, as the REGISTER transaction couples have different call-ids. This looks like different REGISTER attempts with a wrong password, and so different attempts from you of sending a "register" command. I can see specifically:

1. a DNS request;
2. a first REGISTER that gets a 401;
3. another REGISTER in response to that 401, that either gets a new 401, or gets a 200.

Between 2. and 3. there's no additional DNS request, exactly as expected and as should happen. The new DNS request is only there any time you send a new SIP plugin "register" command, which makes sense, as it's a completely new transaction.

As such, I don't believe there's a bug, and that it's most likely something you're handling wrong in the client side.

**Comment by lukaszw544** [comment]
You see my registration operation many times, because I do trick in the client side.
When I get  from Janus errror: registration_failed (code=904) 'Operation has no matching challenge' 
I force re-registration. Between packages no.0 to no.8 you have wrong situation, the correct situation is between no.39 to no.46.
Log from my app:
[JanusWebphone] _onJanusMessage() al_webphone_JanusWebphone.js:682:21
[JanusWebphone]    msg.result = {"event":"registration_failed","code":904,"reason":"Operation has no matching challenge "} al_webphone_JanusWebphone.js:682:21
[JanusWebphone] Register failed, trying again! al_webphone_JanusWebphone.js:682:21
[JanusWebphone] register() al_webphone_JanusWebphone.js:682:21
Object { username: "sip:101@sip.ge:5060", display_name: "101", secret: "1234", proxy: "sip:sip.ge", sips: false, request: "register" }

Finally the operation was successful - sometimes in the first time, sometimes  in the tenth times.
I don't know why. The other desktop softphone don't have this problem - the registration process all the time is with Freeswitch (HOST A) or Freeswitch (HOST B) 👍 
ENPOINT ---> register ---> Freeswitch (HOST A)
ENPOINT <--- 401 unauthorized<--- Freeswitch (HOST A)
ENPOINT ---> register ---> Freeswitch (HOST A)
ENPOINT <--- 200 OK<--- Freeswitch (HOST A)

**Comment by lminiero** [comment]
The dump clearly shows that all iterations are of the type 1.2.3. I showed before: the first REGISTER and the first response to the 401 go to the same place, and both are preceded by a single SRV, so the second REGISTER cannot possibly go to a different server as you say. When the 2nd REGISTER fails (challenge failed), then you send a new "register" from the client, and so it's normal that a new SRV will take place: but again, you can clearly see from the .pcap how after each DNS resolve, there are 2 REGISTER messages, the first attempt, and the response to the challenge. As such, the SIP plugin is working as expected.

**Comment by lminiero** [comment]
Edit: ah no wait, looks like you're right: it's `192.168.1.124` and `192.168.1.123` in the first exchage... then I think it's a bug in Sofia SIP: the DNS response returns two addresses, and it's using one or the other, instead of sticking to one. The library has long been abandoned, so I'm not sure if it has been fixed: the Freeswitch team has kept working on it, so you may want to try and install their library version, to see if it's working as expected there instead.

**Comment by lukaszw544** [comment]
Great, we finally understood each other.
