### ISSUE TITLE
Echo test: remote stream never shows up

### ISSUE THREAD

**Issue by slavazhil** [meetecho/janus-gateway#1754]
Janus v0.7.3: https://pastebin.com/PP2qfgCD
Dockerfile: https://pastebin.com/qRm70RLK
Janus output: https://pastebin.com/EEGWRnWP
![Screen Shot 2019-08-30 at 8 19 11 AM](https://user-images.githubusercontent.com/29084963/64032972-5fd8e800-cb00-11e9-8abb-b024d377f414.png)

**Comment by lminiero** [comment]
As explained in the guidelines, question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Besides, we won't look at issues unless they also happen on master. Closing.

**Comment by slavazhil** [comment]
janus admin api: https://pastebin.com/Z4chdUsj
