### ISSUE TITLE
Configurable RTP port range may cause hanging when creating RTSP mountpoint via an API

### ISSUE THREAD

**Issue by remgodow** [meetecho/janus-gateway#1762]
Reproduction scenario:
1. Define rtp_port_range = "50000-50010" in janus.plugin.streaming.jcfg
2. Define 4 static rtsp streams in janus.plugin.streaming.jcfg
3. Run janus and create new rtsp mountpoint with an API, then destroy it with an API, **twice**
4. Try to create rtsp mountpoint with an API - call hangs

I was stepping through the code with the debugger and it seems that janus_streaming_create_fd() may loop infinitely because **if(!use_range && !quiet)** will never break.

**Comment by lminiero** [comment]
I'm not sure I get it. Even if that check doesn't break, it will go on in the while and this other check should cause it to break:

```
	if(use_range && rtp_port_wrap && rtp_port_next >= rtp_port_start) {
```

**Comment by remgodow** [comment]
Here is the definition:
```
janus_streaming_create_fd(int port, in_addr_t mcast, const janus_network_address *iface,
		const char *listenername, const char *medianame, const char *mountpointname, gboolean quiet)
```

And janus_streaming_allocate_port_pair() function calls it like this:

`janus_streaming_create_fd(rtp_port=50000, mcast, iface, media, media, name, TRUE);`

Where use_range is defined as:

`gboolean use_range = (port == 0) => use_range = (50000 == 0) => false`

therefore 

`if(use_range && rtp_port_wrap && rtp_port_next >= rtp_port_start) {`

will always be false because of use_range = FALSE, and 

`if(!use_range && !quiet)`

will always be false because of quiet=TRUE

**Comment by lminiero** [comment]
Makes sense, thanks for spotting this and providing a fix! I'll merge as soon as the CLA is signed.
