### ISSUE TITLE
[Question] Is it possible to improve video accuracy at server side?

### ISSUE THREAD

**Issue by monkey-b** [meetecho/janus-gateway#1764]
I am starting with the project, and it works well.
I have a server running and all demos work fine.

For what I do, i need sharp images in the feed. For my project, fluidity and lack of ghost images (residual) are more important than resolution.

So my question is : is it possible to improve that aspect on the server side or is it an issue on the player or recorder (browser) side?

Thank you and keep the good work.

**Comment by lminiero** [comment]
As clearly explained in the guidelines, questions like these belong to the [group](https://groups.google.com/forum/#!forum/discuss-webrtc): we only use Github for code related issues. Closing.
