### ISSUE TITLE
Error while using rabbitmq with SSL enabled

### ISSUE THREAD

**Issue by ramprakash110109** [meetecho/janus-gateway#1769]
Hi,

I tried to enable SSL in rabbitmq communication. But, the rabbitmq “In thread" gets closed frequently due to “AMQP_STATUS_SSL_ERROR” on amqp_simple_wait_frame_noblock method

The error code value is -512 and it’s corresponding error string value is “a SSL error occurred”.

I tried with various configurations like 1. Without client verification . 2. With many valid certificates , still the same error occurs.

For now,I have allowed the code flow to continue even if the error code is -512 with the check

```
int res = amqp_simple_wait_frame_noblock(rmq_client->rmq_conn, &frame, &timeout);
		if(res != AMQP_STATUS_OK) {
			/* No data */
			**if(res == AMQP_STATUS_TIMEOUT || res == -512)**
				continue;
			JANUS_LOG(LOG_VERB, "Error on amqp_simple_wait_frame_noblock: %d (%s)\n", res, amqp_error_string2(res));
			break;
		}
```

Do you have any idea regarding this issue? Can you plz suggest me on an workaround or some tips to solve this issue ?

Thanks

**Comment by lminiero** [comment]
@ramprakash110109 do you have any update on this? Is continuing the loop indeed the solution or did you experience issues in your tests?

**Comment by ramprakash110109** [comment]
I ran the server with this check for 5 days and i hadn't noticed any issues/crashes. Also, i checked for memory leaks with Address Sanitizer and it had none. 
Don't know at what frame it fails to decrypt and throws SSL error, but all my messages arrived safely at janus side. So yeah, it works but can't say for sure whether this is the solution
