### ISSUE TITLE
Failed to set remote offer sdp on Chrome

### ISSUE THREAD

**Issue by bhaskardabhi-oviyum** [meetecho/janus-gateway#1776]
Hi,

I am using Janus Gateway to stream my video from Gstreamer to Html. It works fine in case of Firefox but it fails on Chrome with the following error: 

`streamingtest.js:166 WebRTC error: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters.`

I tried to check if someone encountered the same issue but couldn't find any solution about how they resolved it.

I am using [demo js script](https://github.com/meetecho/janus-gateway/blob/master/html/streamingtest.js) for rendering video on the frontend. Following is my SDP:

```
v=0
o=- 1568628002096316 1 IN IP4 192.168.86.32
s=Mountpoint 1
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS janus
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 192.168.86.32
a=sendonly
a=mid:audio
a=rtcp-mux
a=ice-ufrag:4hn7
a=ice-pwd:Z3P8Mds5FjKaMDO0I7UJOl
a=ice-options:trickle
a=fingerprint:sha-256 _{fingerprint goes here}_
a=setup:actpass
a=rtpmap:111 opus/48000/2
a=msid:janus janusa0
a=ssrc:4050605038 cname:janus
a=ssrc:4050605038 msid:janus janusa0
a=ssrc:4050605038 mslabel:janus
a=ssrc:4050605038 label:janusa0
a=candidate:1 1 udp 2013266431 192.168.86.32 36232 typ host
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 192.168.86.32
a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:4hn7
a=ice-pwd:Z3P8Mds5FjKaMDO0I7UJOl
a=ice-options:trickle
a=fingerprint:sha-256 _{fingerprint goes here}_
a=setup:actpass
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=42e01f\;packetization-mode=1
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtcp-fb:96 goog-remb
a=msid:janus janusv0
a=ssrc:452239926 cname:janus
a=ssrc:452239926 msid:janus janusv0
a=ssrc:452239926 mslabel:janus
a=ssrc:452239926 label:janusv0
a=candidate:1 1 udp 2013266431 192.168.86.32 36232 typ host
a=end-of-candidates
```

Following the command which I use to start the GStreamer:

`v4l2src ! videoconvert ! videoscale ! videorate ! video/x-raw,width=640,height=480,framerate=15/1 ! videoconvert ! x264enc tune=zerolatency ! h264parse ! rtph264pay config-interval=1 pt=96 ! udpsink host=127.0.0.1 port=8080`

I am banging my head against the wall for the last 2 days but couldn't resolve the issue. Any help would be appreciated. I tried whatever was given in demo but it didn't help.

**Comment by lminiero** [comment]
`a=fmtp:96 profile-level-id=42e01f\;packetization-mode=1`

There's an extra semicolon that's not supposed to be there. Closing as not a code issue, please ask this kind of questions on the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
