### ISSUE TITLE
[Question] Adaptive Streaming

### ISSUE THREAD

**Issue by mneundorfer** [meetecho/janus-gateway#1792]
Being completely new to Janus, I am wondering if it can help me achieving automatic resolution / frame rate adaptation depending on the available bandwidth (like WebRTC when used between Chrome peers is providing) when *streaming data from a server to web clients*.

What I found so far:

* I can utilize the `streaming` plugin to fetch a RTSP stream and provide it to a web client which I already got working
* Janus does indeed provide [bandwidth management](http://webrtcbydralex.com/index.php/2018/03/14/extending-janus-webrtc-bandwidth-management/) - but not by default - and it is contained (only) in the VideoRoom plugin(?)

My question now is: What does the above describe bandwidth management do? Does it already include adaptation of input streams? Or can I get target bitrates from it, which then I need to feed into something like GStreamer? Or am I completely on the wrong track here?

Thanks in advance for any feedback!

**Comment by lminiero** [comment]
Please ask questions on the [group](https://groups.google.com/forum/#!forum/meetecho-janus), we only use Github for code/compilation issues and pull requests.

**Comment by mneundorfer** [comment]
Fair enough - I looked through the defined labels and saw the one that says `Question`, thats why I tried ;-)

**Comment by lminiero** [comment]
That's probably some predefined GitHub thing, I'll check if we can remove it if it's confusing. We have a template boilerplate that shows up when opening issues that should provide our guidelines on issues.

**Comment by mneundorfer** [comment]
Yes it does - and obviously I didn't read it careful enough. Sorry about that..!

**Comment by lminiero** [comment]
No worries!
