### ISSUE TITLE
why delay so much

### ISSUE THREAD

**Issue by yuanwangliu** [meetecho/janus-gateway#1794]
I am using janus on an cloud game project which need very real-time (less than 100ms latency)
your echo test example (which run on LAN host ) performed not good, it delayed more than 300ms, which human could feel obviously the delay 

when i use rtsp source and open the audio track, the delay is also so much, but when close the audio, only open the video, the delay is less (than 100ms), why ?

**Comment by lminiero** [comment]
As clearly explained in the guidelines you deleted to write this post, questions belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), not here. Closing.

**Comment by wangdemon** [comment]
> I am using janus on an cloud game project which need very real-time (less than 100ms latency) your echo test example (which run on LAN host ) performed not good, it delayed more than 300ms, which human could feel obviously the delay
> 
> when i use rtsp source and open the audio track, the delay is also so much, but when close the audio, only open the video, the delay is less (than 100ms), why ?


Have you solved the problem of delay？

**Comment by atoppi** [comment]
A question for the discourse group.
Anyway it's probably due to having audio and video within the same media stream (msid), with the former affected by delay and the decoder post poning the video track for lip syncing.
