### ISSUE TITLE
AudioBridge Kick Enhancement

### ISSUE THREAD

**Issue by klanjabrik** [meetecho/janus-gateway#1796]
Now, when a participant kicked, the kicked participant can rejoin the room. 

IMO, the kicked participant could join if only the "kick" status is removed. As long as the participant is in "kicked" list, the participant can not join the room. So i propose new request called `unkick`.

**Comment by lminiero** [comment]
That's what you use the ACL for. Kick only kicks a user, if you want to keep them out you need to use the ACL, or nothing prevents them to just use a different username and they'll get in. Closing.

**Comment by klanjabrik** [comment]
@lminiero What is ACL actually?
