### ISSUE TITLE
Operation not permitted on vpn network

### ISSUE THREAD

**Issue by MauricioNoguera** [meetecho/janus-gateway#1797]
Hello everybody,

Just trying to setup Janus to work with CISCO UCM sandbox. The sandbox uses a CiscoAnyConnect vpn client connection to reach the sip server 10.10.20.1. Once the vpn is established I can reach the sip server, however when I try to register a SIP phone, Janus is unable to send the register to this 10.10.20.1 server and returning with a "[nua_r_register]: 503 Service Unavailable" logged on the janus file log. Moreover, on the console displays and additional information such as

tport_vsend (0x7f9630099) : Operation not permitted (1) with (s=47 */10.10.20.1:5060)
nta: REGISTER (9908877): Operation not permitted (1) with */[10.10.20.1]:5060

This REGISTER packet never leaves the Janus box, I wonder if there is a network restriction.
I have pinged the sip server 10.10.20.1 from the janus box and responds, so I think I can discard network issues.

What could be happening? Is there a network restriction on using vpn connections? When the vpn is up a new network interface named "cscotun0".

Regards,
MN
Janus log: https://pastebin.com/MVqJm3Q2
Janus Console error display: https://drive.google.com/file/d/1-FAmJJcFYCYqozd8PWIp3JvO_q9f3R_o/view?usp=sharing

**Comment by lminiero** [comment]
Sounds like an interface error. At any rate, it would be an issue within Sofia SIP, not Janus, so not much we can do about it. Closing.

**Comment by lminiero** [comment]
Check the `janus.plugin.sip.jcfg` configuration file to see if you can force the SIP stack to bind to a specific network interface.
