### ISSUE TITLE
JANUS_VIDEO_CALL android plugin not getting remote stream

### ISSUE THREAD

**Issue by eric-orenge** [meetecho/janus-gateway#1798]
Help needed!! I have managed to successfully initiate connection (register, call, accept)  between the peers but cannot get the remote streams showing yet the local stream is showing. 

Here is the server log: https://pastebin.com/bcKENADW 

What can be the cause of this issue?

**Comment by lminiero** [comment]
As clearly explained in the guidelines, this is a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), not here. Closing.

**Comment by eric-orenge** [comment]
Posted it.  Can you please help me debug this?

https://groups.google.com/d/msgid/meetecho-janus/a0e62c9d-ff9e-4bcd-8203-3907a38a16d0%40googlegroups.com?utm_medium=email&utm_source=footer

Much appreciated
