### ISSUE TITLE
Couldn't load plugin 'libjanus_sipre.so': undefined symbol: uri_encode

### ISSUE THREAD

**Issue by essle** [meetecho/janus-gateway#1803]
An error occurs when starting Janus with a plugin sipre:
> [ERR] [janus.c:main:4584]       Couldn't load plugin 'libjanus_sipre.so': /usr/lib/janus/plugins/libjanus_sipre.so: undefined symbol: uri_encode

Configure:
> LIBRE_CFLAGS=-I/usr/include/re LIBRE_LIBS=-L/usr/lib ./configure --prefix=/usr --enable-plugin-sipre --enable-rest

**Comment by lminiero** [comment]
Likely you installed the library where Janus can't find it (e.g., /usr/lib instead of /isr/lib64). Closing as not a code issue.

**Comment by lminiero** [comment]
That said, please notice that the SIPre plugin is very outdated, and you should really use the Sofia version if you want to interact with SIP infrastructures.
