### ISSUE TITLE
Janus stuck and no further logs produced

### ISSUE THREAD

**Issue by digitalsamba** [meetecho/janus-gateway#1805]
Hi,

We have experienced that Janus got stuck and doesn't accept further incoming requests.
It was running for about 1 month and then suddenly stopped processing incoming requests.
​
Latest Janus log:
https://pastebin.com/kvqALAT7
​
Curl and Telnet output:
https://pastebin.com/FTckyV1P
​
Strace output:
https://pastebin.com/YFGYEbL7
​
From strace output it seems that it's constantly looping over `nanosleep`, but looking at janus.c - that seems to be the main waiting loop.
So probably there is a deadlock somewhere. Here is the GDB:
​
GDB threads info:
https://pastebin.com/XvAvJs77

GDB backtrace:
https://pastebin.com/4TBv5FMc
​
For now we've spun up another Janus and using it.
We've left stuck Janus running in case it is required for further debug and analysis.
​
The issue occurred on 0.7.1 Janus and libnice 0.1.15, but there is a chance it could be still present in master, that's why we are still reporting it.

Thank you in advance!

**Comment by lminiero** [comment]
If the Admin API is still running, you can enable the locking debug and try a new request: this might help understanding if it's one of our mutexes that's locked somewhere, and which one.

Apart from that, the gdb output is incomplete, as you're only showing one thread, the main one. You should run these additional commands on the running instance for more info:

```
ps -To pcpu=,tid=,comm= -p `pidof janus` | sort -nrk 1
```

and

```
gdb -p `pidof janus` --batch -ex "set pagination off" -ex "thread apply all bt full"
```

That said, 0.7.1 is 5 months old, and we changed A LOT in the meanwhile. As such, not sure I really want to debug something we likely fixed already...

**Comment by digitalsamba** [comment]
Output from ps -To pcpu=,tid=,comm= -p `pidof janus` | sort -nrk 1. From what we see, there are quite a lot MHD-connections listed:
https://pastebin.com/XzM2JkgF

Output from gdb -p `pidof janus` --batch -ex "set pagination off" -ex "thread apply all bt full".
https://pastebin.com/G0K73sYw

**Comment by atoppi** [comment]
Hi @digitalsamba,
many threads are missing from the last gdb dump. Are you sure you're capturing the entire output ?

**Comment by digitalsamba** [comment]
Unfortunately during the last gdb session Janus process exited, so we cannot have more logs.

**Comment by atoppi** [comment]
We'll wait for a complete dump then.

**Comment by lminiero** [comment]
> We'll wait for a complete dump then.

Possibly on master :slightly_smiling_face:

**Comment by atoppi** [comment]
@digitalsamba 
1) Limit the number of threads that MHD can create.
See `threads` parameter in `janus.transport.http.jcfg`, setting it i.e. to `8`.
You'll experience very likely the same issue, but with more compact dumps.
2) Are you directly using HTTPS on Janus? If so, please try switching to plain HTTP, terminating the HTTPS on a proxy.

**Comment by digitalsamba** [comment]
Thanks for the recommendations!
2. We already terminating TLS with nginx proxy, so we connect with HTTP to Janus.

**Comment by lminiero** [comment]
Another option is to also test the HTTP single thread branch, available here: #1173. The only reason it hasn't been merged yet is that it needs libmicrohttpd 0.9.59, and I'm not sure all popular repos ship it by default.

You can also try using a different transport, like websockets, which is more optimized than HTTP anyway (no long polling). In that case, make sure you use at least version 3.

**Comment by digitalsamba** [comment]
We found that this issue was related to external bots connecting and ultimately maxing out janus http threads on our server. 
We configured janus so that it can only talk to ngnix directly.
We tested on the latest stable version and have not seen a occurrence of this issue.

**Comment by lminiero** [comment]
Excellent, thanks for the update! Hopefully that won't be an issue anymore when we merge the single thread support for HTTP.
