### ISSUE TITLE
heap-buffer-overflow plugins/janus_sip.c:1288 janus_sip_sofia_logger

### ISSUE THREAD

**Issue by lcarneirofreitas** [meetecho/janus-gateway#1808]
Hi,

We have updated our janus-gateway version to the commit https://github.com/meetecho/janus-gateway/commit/154a2c1f1ba5e04ea710c653e8210fc30cb7eea6.

In this version janus has a memory error.

We, fortunately have the stack trace of the error below:

https://pastebin.com/A7PdtNEz

Thanks

**Comment by lminiero** [comment]
Unfortunately that trace says nothing about the cause of the issue, or even the issue itself for that matter.

**Comment by lcarneirofreitas** [comment]
Thank's Miniero

Really strange, we only have this error message in the janus logs.

We decreased the janus log level, and are watching the application behavior.

Att

**Comment by lminiero** [comment]
Notice that the `janus_sip_sofia_logger` function is not related to the Janus logs, but is actually used to intercept SIP messages and pass them to event handlers. Are event handlers enabled in your case?

**Comment by lminiero** [comment]
Apparently line 1288 in the commit you're using is a `janus_refcount_increase` call. This seems to suggest that the code is trying to increase the reference for a session that has already been freed, which shouldn't be happening. If you have a way to consistently replicate the issue, you may want to update to master, uncomment the `REFCOUNT_DEBUG` line in `refcount.h`, recompile Janus, and try again: when that crashes, please share the whole Janus log in a file somewhere: this way we can check if there's some path that can lead to a SIP session being freed ahead of time.

**Comment by lcarneirofreitas** [comment]
Hi Miniero, thank you so much for your help

We’ve started Janus with -e option and the sip module (janus.plugin.sip.jcfg) was running with the event handlers enabled, as default option.

We’ve removed the -e option and disabled the SIP events after your advise, we are monitoring the memory behaver and the number of live  sessions to get more details

If the Janus crash again i will let you know with all required logs

**Comment by lcarneirofreitas** [comment]
Hello Miniero

We are analyzing janus server after suggested changes, below are some prints of session behavior and memory.


![process-cpu-memory](https://user-images.githubusercontent.com/8731885/67101781-aa89ee80-f198-11e9-8969-a07b97bee4e0.png)

![janus-breakdown](https://user-images.githubusercontent.com/8731885/67101765-9fcf5980-f198-11e9-9947-f2da093733b2.png)

![janus-sessions](https://user-images.githubusercontent.com/8731885/67101791-ae1d7580-f198-11e9-8fec-d8130442eda3.png)

Note: The drops in memory consumption were caused because we restarted the service at night, at the moment we do not restart any more and the memory keeps rising.


We also collected some logs from this period.

https://gist.github.com/99b710e3e73d259ea8241c30dc371c08
https://gist.github.com/60dea714aa5b56f78fab2b4739be8772
https://gist.github.com/c08ac28d4c2091fbf55c597965e031fc
https://gist.github.com/00af5853e3f1590b3eda581d3a3113e2
https://gist.github.com/1cd28750472c64292f2023cbbae4de0f

We set up a new janus server with the uncommented REFCOUNT_DEBUG line in refcount.h, and are saving the log's for future analysis.



Thanks

**Comment by lminiero** [comment]
To be more precise: logs are useful, but _only_ when compiled with refcount debugging support, and _only_ after the summary is printed at the end since it tells us which references are still there (and the full log can help us figure out why). Without that, the only way we can detect memory leaks is with a libasan trace, which is again only printed when Janus exits cleanly: you'll need to compile Janus with libasan support for that.

As a side note, if you are using libasan, then the memory footprint in memory monitors will indeed look like it's always growing, even if it isn't. That's because libasan keeps track of all allocations, and so obviously uses memory for that. You can quickly check if that's the cause in your setup by compiling _without_ libasan support, and see if memory grows there too.

**Comment by MrVictorBro** [comment]
Hello lcarneirofreitas.
How did you get the Janus graph of the sessions?

**Comment by lcarneirofreitas** [comment]
Hello MrVictorBro

I use datadog to generate the graphs.
https://gist.github.com/lcarneirofreitas/32e9de32101819837ee76d80b6985b23

**Comment by lminiero** [comment]
@lcarneirofreitas any update on the info we asked? Thanks.

**Comment by lminiero** [comment]
Closing for lack of feedback. Feel free to reopen once you can confirm it's still happening and you can provide info to replicate, or the info we asked for a month ago.
