### ISSUE TITLE
Camera or microphone permission needed for non-publishers/viewers only since Chrome 77

### ISSUE THREAD

**Issue by ashimokawa** [meetecho/janus-gateway#1810]
I know this is probably not janus fault but it might lead to a lot of bug reports if not somehow addressed.

When trying streamingtest.html from the demos first, without having granted camera or mic access, it is impossible to open a stream. No error is thrown.

It seems to be a security concern that was adressed chrome 77. Without a site having mic/camera access it is also impossible to do some things like looking up the lokal IP address by abusung WebRTC for a js script running on the client. This might be connected.

**Comment by lminiero** [comment]
No, that's not needed. See mDNS discussions on the group. Closing.

**Comment by ashimokawa** [comment]
Yep, sorry for the noise. Using latest libnice fixes the issue, works now without accepting cam access on the clients.
Too bad most distributions including debian/unstable only have outdated libnice...

**Comment by lminiero** [comment]
> Too bad most distributions including debian/unstable only have outdated libnice...

Yep, that's why a few days ago I added a warning on the Janus log when libnice is older than 0.1.15, which should draw the attention more on those using it. I considered making it a requirement in the configure script, but that might have been overkill. Glad it's fixed now!
