### ISSUE TITLE
Timestamp issue

### ISSUE THREAD

**Issue by raghul528** [meetecho/janus-gateway#1811]
in rtp.c@janus_rtp_header_update function, before changing layer if Nack (retransmission of lost packets )packet timestame updated as context->v_last_ts it spoil the newly assigned timestamp so its better to save maximum value of  context->v_last_ts and handle based on maximum value of  context->v_last_ts, same issue for context->v_last_seq

**Comment by lminiero** [comment]
Not sure I understand the problem, or the proposed fix. If you're willing to work on a pull request with a patch, I'll be glad to review it.

**Comment by lminiero** [comment]
Closing.
