### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by GiaCatKhongVinh** [meetecho/janus-gateway#1812]
Hello, I'm getting an issue with the installation of Janus-gateway. Screenshot attached. It says the errors come from the newly added events/janus_wsevh.c.
![09-Oct-19 10-06-25 AM](https://user-images.githubusercontent.com/56330908/66448773-e0362580-ea7c-11e9-9414-ed82944257e2.png)
Please help to check. Thanks!

**Comment by GiaCatKhongVinh** [comment]
Sorry, I found out i used libwebsockets-dev 2.0.3-3build1.

**Comment by lminiero** [comment]
Mh it still means we should check the libwebsockets version, I wasn't aware that flag wasn't available on older versions. I'll add a check for that.

**Comment by lminiero** [comment]
Should be fixed in master, now: if libwebsockets is older than 2.4.0, we use `LWS_CALLBACK_CLOSED` instead of `LWS_CALLBACK_CLIENT_CLOSED`. Not sure if that's the only thing that could cause it to break, but this should be solved at least.

**Comment by tgabi333** [comment]
@GiaCatKhongVinh How did you get such an old libwebsocket? is it embedded into a certain linux distro?

**Comment by GiaCatKhongVinh** [comment]
@tgabi333: I'm using Ubuntu 18.04 distro and I had installed libwebsocket from the repo using command:
sudo apt-get install libwebsockets-dev

**Comment by tgabi333** [comment]
@lminiero from the changelog it seems to me that v3.0.0 LWS_CALLBACK_CLIENT_CLOSED was introduced in v3.0.0, but there is a 2.4.1 and 2.4.2 release which is broken now?

**Comment by lminiero** [comment]
I checked the version in the commit where this was added, and it said 2.4.0 there. I don't have those installed so I can't verify the check actually works myself.
