### ISSUE TITLE
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. Failed to parse audio codecs correctly.

### ISSUE THREAD

**Issue by essle** [meetecho/janus-gateway#1813]
Hello. 

**I'm using JavaScript code from demo 'SIP Gateway (Sofia)'**

After start of the call, i get an error:

> Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. Failed to parse audio codecs correctly.

SDP offer: https://pastebin.com/NKNf1Gbk
SDP answer: https://pastebin.com/5ksYhCi5

Janus configuration: https://ru-collector.ru/janus-admin/info
Janus conole log: https://pastebin.com/BPu9aCPd

**Comment by lminiero** [comment]
Apparently your SIP peer is not removing all attributes related to rejected payload types: one with 111 is still there in the answer. This is probably what confuses the browser. Closing as not a Janus issue.
