### ISSUE TITLE
Videoroom: Data channel not opening in Firefox 

### ISSUE THREAD

**Issue by picitujeromanov** [meetecho/janus-gateway#1819]
This one is tricky to reproduce. When you use videoroom plugin and try to publish own feed with media streams and data channels, sometimes data channel would not open. The only way I could go around this bug is to introduce unpublish -> publish retry logic until it eventually works

**Comment by lminiero** [comment]
What do you mean by "not open"? Failed negotiation? `ondataopen` not called? Not called for the publisher, or their subscribers?

**Comment by picitujeromanov** [comment]
onopen is not called for publisher

**Comment by lminiero** [comment]
Is this still an issue with master?

**Comment by lminiero** [comment]
Tried for a while but I can't replicate this, so I'll close. Feel free to re-open if it's still an issue in master and you can provide data to replicate the problem.
