### ISSUE TITLE
Modular recorder

### ISSUE THREAD

**Issue by euskadi31** [meetecho/janus-gateway#1822]
Hi @lminiero,

Do you think it's possible to modularized the recorder?

I would like to implement a hls recorder on the videoroom plugin.

I think it would be easier to make a recorder plugin rather than duplicate the code of the videoroom plugin.

Thanks you for your work !

**Comment by lminiero** [comment]
Not planning to do that for the time being sorry. You'll have to add this to the plugin itself if you need it, or more simply use RTP forwarders to delegate the HLS translation process to an external component.
