### ISSUE TITLE
Janus gateway cash problem

### ISSUE THREAD

**Issue by ubonass** [meetecho/janus-gateway#1826]
1.when the client connect the gateway (The client use the wifi network) and use video call
   or anthoer plungin for streaming
2.The client switch the nework model  to 4G 
3.The gatway will cash when the client switch the network mode

**Comment by lminiero** [comment]
We'll need much more than that to figure out what's wrong. Please provide a gdb stacktrace or preferably a libasan dump of the crash: https://janus.conf.meetecho.com/docs/debug

**Comment by lminiero** [comment]
Closing for lack of feedback. As soon as you can provide the info we asked, feel free to reopen.
