### ISSUE TITLE
I want to integrate janus gateway in my flutter application

### ISSUE THREAD

**Issue by maxbhoria** [meetecho/janus-gateway#1829]
I am creating video streaming in my flutter application. Please provide me some guidelines to implement in my flutter apk. If there is any sdk to integrate in flutter please provide me some reference for that.
Thank you

**Comment by lminiero** [comment]
As clearly explained in the guidelines you ignored and deleted, this is a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Closing.

**Comment by shivanshtalwar0** [comment]
I started working on a flutter plugin to integrate Janus and webrtc stack in flutter application you might wanna explore or help me in developing it further.
[flutter_janus_client](https://github.com/shivanshtalwar0/flutter_janus_client)
