### ISSUE TITLE
Audio and video are not synchronized after process with janus-pp-rec

### ISSUE THREAD

**Issue by mightZhong** [meetecho/janus-gateway#1834]
1. Use a janus ios app join a janus video room
2. Audio and video packets were be recorded.
3. Use janus-pp-rec to process the audio and video file
4. Check the duration of opus and webm file with ffprobe tool, it show the opus file duration is shorter than webm file

**Comment by alexamirante** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus). It's been discussed several times there.

**Comment by tarasian666** [comment]
Looks like issue still persist. 
Often audio is shorter, audio and video started at same time (relying on heders). Once audio was 17 minutes and video was 21 mins.
