### ISSUE TITLE
Heads up: Firefox and secure websockets over HTTP/2 don't work well

### ISSUE THREAD

**Issue by schoolcoder** [meetecho/janus-gateway#1837]
This is not a Janus bug - just a heads up if you are using Janus websockets with Firefox clients.

Firefox (version 65.0 or later) doesn't work well with secure websockets (wss) over HTTP/2. The websocket connection works for exactly 5 minutes, but then the browser forces the connection closed. Pings and/or keep-alives don't help. This affects any websocket server, including Janus. 

This applies if you are using libwebsockets and it was built with HTTP/2 support enabled. HTTP/2 was enabled by default starting with libwebsockets version 3.1.0.

There are two ways to work around the problem:

(1) Disable wss over HTTP/2 in Firefox.
OR
(2) Disable wss-over-HTTP/2 support in Janus by rebuilding libwebsockets. (See explanation below.)

For (1), open about:config in Firefox, and change the `network.http.spdy.websockets` preference to false.

For (2), rebuild libwebsockets with HTTP/2 support disabled. Add `-DLWS_WITH_HTTP2=0` to the libwebsockets cmake command, as shown here:

`cmake -DLWS_MAX_SMP=1 -DLWS_WITH_HTTP2=0 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..`

BTW: This is a Firefox-only issue. Chrome and Edge work fine with or without HTTP/2 support.

There's a new bug on this at Mozilla: 
[https://bugzilla.mozilla.org/show_bug.cgi?id=1590299](url)

**Comment by lminiero** [comment]
Thanks for the useful info. That said, we usually discourage enabling secure transports directly in Janus, and suggest putting a proxy like httpd or nginx to take care of that part instead (eg., https to the proxy, http to Janus). This means it should probably be easier to prevent this in a proxy configuration, rather than recompiling libeebsockets or tweaking the browser settings.

**Comment by tgabi333** [comment]
It seems that Firefox 72 fixes the problem, could you verify?

**Comment by lminiero** [comment]
Firefox stable is 74, so if Firefox 72 fixes it, I guess we can close this. Thanks for the feedback!

**Comment by tgabi333** [comment]
@lminiero could you please unpin this issue as well
