### ISSUE TITLE
getUserMeida Or getDisplayMedia Not Allowed in Electron

### ISSUE THREAD

**Issue by GuoSirius** [meetecho/janus-gateway#1845]
![image](https://user-images.githubusercontent.com/48358523/67833031-74485980-fb1e-11e9-9f19-24598cc39346.png)

如果是浏览器，则会弹出选择共享哪个屏幕 或者 窗口，对于 Electron 应用来说是没有弹出选择的，而且权限不允许。

建议可以在调用时传入参数，进行合并，或者提供一个钩子机制，可以重写这一部分。

**Comment by lminiero** [comment]
Please ask your question in English. That said, this is a question for our Google group, not a code issue, so I'm closing this.

**Comment by GuoSirius** [comment]
> Please ask your question in English. That said, this is a question for our Google group, not a code issue, so I'm closing this.

If it is a browser, it will pop up to select which screen or window to share. For Electron application, there is no pop up selection and permissions are not allowed.



It is suggested that you can pass in arguments at invocation time, merge, or provide a hook mechanism that you can override.
