### ISSUE TITLE
Media stream ID's should be unique

### ISSUE THREAD

**Issue by akilude** [meetecho/janus-gateway#1847]
Currently for the video room plugin at least, remote streams all have the same id "janus". Media Stream ID's are supposed to be unique https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/id

3rd party libraries like [iosrtc](https://github.com/cordova-rtc/cordova-plugin-iosrtc) rely on the media stream id to identify streams, since all remote streams have the same id, it causes bugs like [this](https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/432)

So is it possible to update janus to follow the [spec](https://www.w3.org/TR/mediacapture-streams/#attributes) and provide unique ids.

Thanks,
Akil

**Comment by lminiero** [comment]
Already fixed in #1459.

**Comment by akilude** [comment]
Thank you, i must have missed that. Closing.

**Comment by lminiero** [comment]
Notice it hasn't been merged yet, as it's a huge refactoring. It does include that change, though, at least IIRC.

**Comment by hohno-panopto** [comment]
@lminiero I am sorry for coming back to this old conversation. Am I correct that this issue will never be fixed on legacy branch (0.x) and the only solution is to migrate to multi-stream branch? I also have some 3rd party library that relies on MediaStream.id's uniqueness. #1459 was closed and I lost track of the discussion.
