### ISSUE TITLE
"Timeout expired for session" error... when reclaim_session_timeout flag is set

### ISSUE THREAD

**Issue by picitujeromanov** [meetecho/janus-gateway#1850]
We're experiencing random session timeouts when 'reclaim_session_timeout' is set (to 15) and joining video-room as data channel participant only, resulting in well .. kicking out the participant. It's not happening all the time but problem completely disappeared when we commented out reclaim_session_timeout

**Comment by lminiero** [comment]
`reclaim_session_timeout` is only involved *after* the regular API timeouts, or when a transport plugin tells us a transport is gone. As such, it's unlikely that enabling or disabling it can trigger random disconnections: it's much more likely that the cause is different. If you can replicate it, please share portions of the log (as gist/pastebin, not here inline) that show info for the affected session ID.

**Comment by picitujeromanov** [comment]
We'll be doing some testing sometime early next week. I'll get the logs and share them with you

**Comment by lminiero** [comment]
Any update on this? Thanks.

**Comment by schikin** [comment]
Hi everyone, is there actually a proper documentation on how the mentioned `reclaim_session_timeout` works?

We are using WebSockets to interface with Janus and from documentation it reads that WS connection drop should result in dropping the related sessions and this is what we are observing. In our deployment we have a number of Janus instances in one DC and a bunch of controlling services in cloud. There are obviously changing networking conditions between them so connections drop once in a while. It would be great if there was a way to reclaim the sessions upon WS reconnect.

It seems like `reclaim_session_timeout` is designed for that but what would be the API for this? What do I send upon WS reconnection? Just a keepalive?

**Comment by lminiero** [comment]
No documentation, sorry. Check #1199 which is where this was implemented. If you're using `janus.js`, `reconnect()` is the method to use (again, explained in the link above), otherwise check how it's used in the library or look for `"claim"` in `janus.c` for more info.

**Comment by lminiero** [comment]
Closing for lack of feedback. If this is still an issue and you can provide info to replicate the issue, feel free to reopen.
