### ISSUE TITLE
Cannot hangup a ringing call: [ERR] [plugins/janus_sip.c:janus_sip_handler:3225] Wrong state (not established? status=inviting)

### ISSUE THREAD

**Issue by LucasFrezarini** [meetecho/janus-gateway#1856]
Hey there,

I'm having some trouble with the hang up of calls that hasn't started yet. When the caller dial to some number but give up of the call while it's ringing, the call doesn't hangup properly and keeps ringing to the callee for a while (something close to 10 seconds). I'm sending a `hangup` request to Janus when the caller hangs up, as recommended in the sip plugin [documentation](https://janus.conf.meetecho.com/docs/sipsofia.html):

> hangup can be used to terminate the communication at any time, either to hangup (BYE) an ongoing call or to cancel/decline (CANCEL/BYE) a call that hasn't started yet.

However, checking the SIP traffic, I've found that when the caller hangs up a call while it's ringing, Janus isn't sending a CANCEL/BYE SIP request. Analyzing the logs of Janus, when the hangup request is sent by the caller on a call in the inviting state, the following error is logged:

```
[Mon Nov  4 16:02:36 2019] [ERR] [plugins/janus_sip.c:janus_sip_handler:3225] Wrong state (not established? status=inviting)
```

After finding this out, I dug up the [code](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c) related to the sip plugin to investigate what is causing this problem and to verify if I am doing something wrong, and I've found the `if clause` that is preventing the CANCEL request of being made (line 3744):

```C
// [...]
} else if(!strcasecmp(request_text, "hangup")) {
	/* Hangup an ongoing call */
	if(!janus_sip_call_is_established(session)) {
	JANUS_LOG(LOG_ERR, "Wrong state (not established? status=%s)\n", janus_sip_call_status_string(session->status));
	/* Ignore */
	janus_sip_message_free(msg);
	continue;
	//~ g_snprintf(error_cause, 512, "Wrong state (not in a call?)");
	//~ goto error;
}
// [...]
```

Just for testing, I've removed this `if clause` to check up if the hangup would work without this verification, and I've found that after this modification, when a hangup request is send to Janus by the caller on a ringing call, a SIP CANCEL request is send successfully and the call is terminated:

![cancelrequest](https://user-images.githubusercontent.com/16738007/68298670-af93dc80-0078-11ea-8c3f-bd5b5f78d49c.png)

Of course, I doubt that just removing the `if clause` should be the solution to the problem and may have some side effects, and that's why I don't opened a pull request. Maybe it should be valid to add a verification to allow inviting calls? or creating a specific flow to cancel a ringing/inviting call?

```C
// [...]
	/* Hangup an ongoing call */
	if(!janus_sip_call_is_established(session) && session->status != janus_sip_call_status_inviting) {
            // Log wrong state error...
        }
// [...]
```
```

**Comment by lminiero** [comment]
Good point, I guess this was lost when the `janus_sip_call_is_established()` method was introduced in a pull request to fix re-INVITE issues. I'll make the fix shortly.

**Comment by zaid-asif-brainx** [comment]
I am still facing this issue, have you updated the code?

**Comment by lminiero** [comment]
Yes, it's been there since 0.7.6

**Comment by zaid-asif-brainx** [comment]
Ahh okayy.. But i am still facing this issue, Any idea how to solve this.
i've checked my Asterisk logs and my janus client never sending the CANCEL/BYE event.
