### ISSUE TITLE
Timestamp reset not considered in janus_rtp_header_update

### ISSUE THREAD

**Issue by chadisid** [meetecho/janus-gateway#1860]
Timestamp reset is not considered while changing the rtp header timestamp to the janus timestamp. This can gives wrong timestamps.

context->a_last_ts = (timestamp-context->a_base_ts) + context->a_base_ts_prev;

**Comment by lminiero** [comment]
We don't need to consider them: math is on `uint23_t`, so if it goes beyond (as it will), it wraps. Unless you have a specific use case you can document, and have an example of it going wrong, we'll close this issue.

**Comment by lminiero** [comment]
Didn't see a response to my point above, so I'll close. Feel free to reopen if you believe there's something that needs to be addressed.
