### ISSUE TITLE
janus.plugin.sip  Disconnect minutes after successful login

### ISSUE THREAD

**Issue by yuexiajiayan** [meetecho/janus-gateway#1863]
I logged into my SIP account, but I couldn't call in in a few minutes

The official demo log always outputs login info, but I don't have a problem with the settings？

reg ok log:
The official demo log:
Long poll...
janus.js:754 Got a plugin event on session 6247297672678506
 ::: Got a message :::
siptest.js:151 {sip: "event", result: {…}}
result: {event: "registered", username: "100805", register_sent: true, master_id: 3653576600}sip: "event"__proto__: Object
siptest.js:191 Successfully registered as 100805!

my log:
Long poll...
janus.js:754 Got a plugin event on session 6247297672678506

have no event 。

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Closing.
