### ISSUE TITLE
Streaming H.264 to Chrome doesn't work

### ISSUE THREAD

**Issue by TheWizz** [meetecho/janus-gateway#1864]
I'm attempting to use the standard "streamingtest.html" example to play an H.264 video originating from a network camera. This works fine in Safari and Firefox, but does NOT work in Chrome (all on macOS). I've tried the current Chrome 78 as well as Chrome Canary 80. All steps up to when the video would appear work as usual. I select the stream on the dropdown and hit "Watch ot Listen". The stream seems to connect OK. No error messages in the browser's console, nor in the Janus end. Janus is built from source downloaded from gihub today (2019-11-12), and using the standard "streamingtest.html" to play. 

When I press "Watch ot Listen", the "Started" message appears shortly above the video box, and also the" kbits/sec" indicator, which fluctuates a bit up and down with the correct bitrate. I can see that the srcObject of the #remotevideo being set. However, the "active" state of this srcObject never becomes true on Chrome (which I see it does on Safari and Firefox).

Here's the relevant snippet from the janus.plugin.streaming.jcfg file:

```
rtsp-test: {
	type = "rtsp"
	id = 96
	description = "RTSP Test"
	audio = false
	video = true
	url = "rtsp://10.0.1.14/s2"
	#below setting of videofmtp required to play video on Safari
	videofmtp = "profile-level-id=42e01f;packetization-mode=1"
}
```

Any thoughts on where to look to figure out what's going on here? It's usually Chrome that works OK, and Safari giving us grief, but here it seems the other way around...

-JM

**Comment by lminiero** [comment]
Asked a thousand times on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) already where, as the guidelines clearly explain, this question belongs. Closing.
