### ISSUE TITLE
Textroom:SDP missing mandatory information

### ISSUE THREAD

**Issue by LeanAndon** [meetecho/janus-gateway#1868]
Anyone can help me , Thanks!

test url:   https://rtc.10019.cn
 after install janus, [video room] is ok; but [text room] is Nok. 
【textroom】 demo test result： 
################################
Creating new session: 8303722922868057; 0x7f1320001a90
Creating new handle in session 8303722922868057: 8870042465193886; 0x7f1320001a90 0x7f1320003e00
[8870042465193886] Creating ICE agent (ICE Full mode, controlling)
[WARN] [8870042465193886] Skipping disabled/unsupported media line...
[WARN] [8870042465193886] Skipping disabled/unsupported media line...
[ERR] [sdp.c:janus_sdp_process:351] [8870042465193886] SDP missing mandatory information
[ERR] [sdp.c:janus_sdp_process:352] [8870042465193886] 0x7f1344001450, 0x7f1344001250, (nil), (nil)
[ERR] [janus.c:janus_process_incoming_request:1285] Error processing SDP
Destroying session 8303722922868057; 0x7f1320001a90
Detaching handle from JANUS TextRoom plugin; 0x7f1320003e00 0x7f1320003f40 0x7f1320003e00 0x7f13200025d0
No WebRTC media anymore

janus 
###########################
Compiler:                  gcc
libsrtp version:           2.x
SSL/crypto library:        OpenSSL
DTLS set-timeout:          not available
Mutex implementation:      GMutex (native futex on Linux)
DataChannels support:      yes
Recordings post-processor: no
TURN REST API client:      yes
Doxygen documentation:     no
Transports:
    REST (HTTP/HTTPS):     no
    WebSockets:            yes
    RabbitMQ:              yes
    MQTT:                  no
    Unix Sockets:          yes
    Nanomsg:               yes
Plugins:
    Echo Test:             yes
    Streaming:             yes
    Video Call:            yes
    SIP Gateway (Sofia):   yes
    SIP Gateway (libre):   no
    NoSIP (RTP Bridge):    yes
    Audio Bridge:          yes
    Video Room:            yes
    Voice Mail:            yes
    Record&Play:           yes
    Text Room:             yes
    Lua Interpreter:       no
    Duktape Interpreter:   no
Event handlers:
    Sample event handler:  yes
    WebSocket ev. handler: yes
    RabbitMQ event handler:yes
    MQTT event handler:    no
    Nanomsg event handler: yes
JavaScript modules:        no

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by LeanAndon** [comment]
Thank you very much！ But  I can not find the answer . May you help me?

**Comment by lminiero** [comment]
You won't find it here. As very clearly explained in the guidelines, questions like this belong to the group, which is why I gave you a link to that.

**Comment by LeanAndon** [comment]
Thank you!  I search in https://groups.google.com/forum/#!forum/meetecho-janus 
with keywords like 'Textroom' ,'SDP'
May you please show me where the answer is? Thanks!

**Comment by LeanAndon** [comment]
I set up again as your guidline. It's ok. Thanks.
