### ISSUE TITLE
MQTT transport enhancement: properties of the status message

### ISSUE THREAD

**Issue by manifest** [meetecho/janus-gateway#1871]
We already have [a way](https://github.com/meetecho/janus-gateway/blob/master/conf/janus.transport.mqtt.jcfg.sample#L44) to specify a message body for the status message.

The proposal is to allow specifying message properties for the status message from within MQTT transport plugin configuration. By default, properties won't be set (the current behavior).

**Comment by lminiero** [comment]
If this is related to the pull request you opened, please link them explicitly.

**Comment by manifest** [comment]
There isn't any PR for this issue yet and it doesn't relate to [#1872](https://github.com/meetecho/janus-gateway/issues/1872). The proposal is to add a list of properties to the app's configuration that would be sent along with the payload of the status message.

That doesn't change anything in a sense of how Janus plugins work, but it will allow a bit more flexible integrations with other MQTT components. In our particular case, we have some required properties that need to be sent with any MQTT message.

**Comment by lminiero** [comment]
I assume that by "along with the payload" you mean as additional MQTT properties, and not embedded in the JSON of the message itself, correct?

If so, sounds good then! To be honest, though, we don't have plans to work on that, as we're hugely busy on other things and don't use MQTT much ourselves. In case a pull request is provided, happy to look at it :+1:

**Comment by manifest** [comment]
> I assume that by "along with the payload" you mean as additional MQTT properties, and not embedded in the JSON of the message itself, correct?

That's correct.

> In case a pull request is provided, happy to look at it.

We'll prepare a PR in the nearest future.

**Comment by lminiero** [comment]
Thanks for the clarification, looking forward to the enhancements!

**Comment by uwejan** [comment]
@manifest @lminiero  out of the scope of this issue, am trying to use mqtt transport. i notice all demos have not used mqtt. and all client libs do not use it. would shade some light on how client will work to be more specific, lets say how will client screenshare using mqtt transport?
Your input appreciated.

**Comment by manifest** [comment]
@uwejan This documentation covers [Transport API](https://janus.conf.meetecho.com/docs/rest.html) for all supported protocols including MQTT. You can also check our [plugin](https://github.com/netology-group/janus-conference) and [signaling server](https://github.com/netology-group/conference) out for more details.

**Comment by lminiero** [comment]
@manifest is this functionality still required? I'm wondering if the issue can be closed, or if you were indeed still planning to contribute this new feature. To my knowledge no one else seemed to be asking for it, so if it's not needed anymore I can close this.

**Comment by lminiero** [comment]
Closing as there doesn't seem to be interest in this feature anymore.
