### ISSUE TITLE
"quality" parameter in configuration options for AudioBridge. What does it mean?

### ISSUE THREAD

**Issue by ekorolev** [meetecho/janus-gateway#1876]
Hi!

I found the parameter "quality" in the documentation for the AudioBridge plugin.

```
{
        "request" : "configure",
        "muted" : <true|false, whether to unmute or mute>,
        "display" : "<new display name to have in the room>",
        "quality" : <0-10, Opus-related complexity to use, lower is higher quality; optional, default is 4>,
        "volume" : <percent value, <100 reduces volume, >100 increases volume; optional, default is 100 (no volume change)>,
        "record": <true|false, whether to record this user's contribution to a .mjr file (mixer not involved),
        "filename": "<basename of the file to record to, -audio.mjr will be added by the plugin>"
}
```

`<0-10, Opus-related complexity to use, lower is higher quality; optional, default is 4>`

What does it mean? Is it the sound that is mixed and sent to the client? Either is it the quality that is used to mix the first client's voice with voices from other participants?

I tried to change that parameter but I didn't notice any difference. Can anyone explain? Sorry, if there is the answer on the internet, I didn't found it.

**Comment by lminiero** [comment]
Questions belong to the group, not here. https://groups.google.com/forum/#!forum/meetecho-janus
