### ISSUE TITLE
a crash in janus_plugin_session_is_alive

### ISSUE THREAD

**Issue by mivuDing** [meetecho/janus-gateway#1879]
I use the latest version, and when doing automatically test, which would join and quit videoroom very quickly and massively(many peers), found a stumbled upon crash in janus_plugin_session_is_alive of "if(plugin_session == NULL || plugin_session < (janus_plugin_session *)0x1000 || g_atomic_int_get(&plugin_session->stopped))".
gdb1:
![企业微信截图_15749260551581](https://user-images.githubusercontent.com/50724784/69797269-5dbf1c00-120a-11ea-89c8-7483fc3f6dac.png)
gdb2:
![企业微信截图_15749313396963](https://user-images.githubusercontent.com/50724784/69797302-6adc0b00-120a-11ea-9f41-213e5c09dfc7.png)

**Comment by lminiero** [comment]
Nothing we can do with screenshots: https://janus.conf.meetecho.com/docs/debug
Besides, you're not telling us which Janus version this is: make sure you test with master, otherwise we won't look at it.

**Comment by lminiero** [comment]
@mivuDing any update on the debugging info we asked for?

**Comment by mivuDing** [comment]
> @mivuDing any update on the debugging info we asked for?
my code is not the latest master, and had do some modify. I am looking for the problem, if there are any useful information, I will ask for your help. tks.

**Comment by mivuDing** [comment]
I have found the reason, the problem only happened on my modify code, sorry for bother you.
