### ISSUE TITLE
Event handlers crashing on json_incref on init

### ISSUE THREAD

**Issue by mirkobrankovic** [meetecho/janus-gateway#1882]
Log from load:
https://pastebin.com/dmRyf30A
GDB report:
https://pastebin.com/wmZuxKLB
By which it looks like that it can't access memory where event/json object is:

> #0  0x00007f3f04b9be47 in json_incref (json=0x5987d3db0baaa) at /usr/include/jansson.h:100
> 100     if(json && json->refcount != (size_t)-1)
> (gdb) p * json
> Cannot access memory at address 0x5987d3db0baaa

**Comment by lminiero** [comment]
Fixed in eb87505b99fb3574c7837199a775ad82078195a5 :+1:

**Comment by mirkobrankovic** [comment]
hahaha so quick :D 
Great work :)
