### ISSUE TITLE
Memory leak when using videoroom and SIP plugins

### ISSUE THREAD

**Issue by thengoster** [meetecho/janus-gateway#1897]
We are using Janus v0.8.0 and libnice 0.1.16. We set up a videoroom plugin per videocall, where we have 1 publisher and 3 subscriber handles per person (total of 4 peer connections from each client). As each person joins the videocall, we connect one of the subscriber feeds to the new publisher. Once the person's subscriber handles are all filled up and a new person joins, we use the Janus switch functionality to move the oldest subscriber feed to the new publisher.

We also use a SIP plugin to connect audio with asterisk to mix the audio, which is a separate peer connection per person. 

We've noticed that the memory from Janus is growing substantially (several GB) over time when running load. We modified refcount.h to enable reference count debugging and noticed there is a memory leak in the SIP plugin. However, this is a very small amount of memory leak detected, 46kB leaked from SIP when Janus was using ~1GB overall. We verified after the load was stopped via the Janus Admin that there were no Janus handles remaining. 

Please address these SIP plugin leaks shown in the attached output below.
[SIP_Janus_leak.txt](https://github.com/meetecho/janus-gateway/files/3962661/SIP_Janus_leak.txt)

How do we investigate the remaining large portion of the memory leak?

We built Janus using these options:
CFLAGS="-fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-lasan"

...and then ran as:
ASAN_OPTIONS=detect_leaks=1 /usr/local/bin/janus

Once the load was stopped, we sent a CTRL-C to produce the LeakSanitizer output (attached file).

Thank you.

**Comment by lminiero** [comment]
A better way to detect leaks with libasan is launch with

    ASAN_OPTIONS=fast_unwind_on_malloc=0

**Comment by thengoster** [comment]
Our team ran Janus with `ASAN_OPTIONS=fast_unwind_on_malloc=0` as you suggested, but found no differences in leaks detected, unfortunately.

This time, we ran a simplified scenario of just one videocall of 16 users with no switching and saw that the memory usage from Janus was rising steadily. Janus memory usage for reference:

Beginning of call, all participants joined: 471568 KiB
~1 hour since beginning of call: 516684 KiB

Below is a link to the libasan output:
https://pastebin.com/bS1RAuNP

Again, the memory usage is not adding up and we are having a tough time figuring out where this discrepancy is coming from. 

We have the Janus log from that call to examine, so we will be parsing through that log to see if there are any missed decreases on a memory address. What else do you suggest we do to find this memory leak?

**Comment by lminiero** [comment]
When Janus is compiled with libasan, monitoring the memory makes no sense, since it will constantly grow: libasan keeps track of all memory allocations (for the exit summary) so the memory will grow as a consequence. It should only be used when you know there's a leak (because memory grows without libasan) and you want to know where it happens. It goes without saying that libasan shouldn't be used in production, if you plan to keep Janus running for long times, exactly because memory will keep on growing.

**Comment by thengoster** [comment]
Thanks for all of the help. It turns out that the memory leak that we were seeing prior to compiling Janus with libasan was using Janus v0.7.5. We never ran load on Janus v0.8.0 without libasan, so we assumed it was still the memory leak. Suffice to say, the leak we saw from v0.7.5 is gone after moving to v0.8.0.

However, there is still that small leak coming from objects utilizing libsofia from my previous pastebin link, could you take a look at that please? Thanks again.

**Comment by lminiero** [comment]
Fixed, in some recent change we ended up having two `su_home_init` instead of one (probably a result of code being moved around and not cleaned up).
