### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by GQAdonis** [meetecho/janus-gateway#190]
I am getting the following error compiling the Janus Gateway:

/root/janus-gateway/janus.c:4516: undefined reference to `libwebsock_bind_ssl'

Any ideas?

**Comment by saghul** [comment]
Looks like you're compiling with WebSocket support but you haven't installed libwebsock. If youy don't really need the WebSocket support you can disable it by passing --disable-websockets to ./configure.

**Comment by lminiero** [comment]
Closing as not an issue. Please refer to the meetecho-janus google group for this kind of questions.
