### ISSUE TITLE
Update janus.js for session destroy function onbeforeunload not working in browser's newest versions

### ISSUE THREAD

**Issue by DaGLiMiOuX** [meetecho/janus-gateway#1902]
Chrome has "disabled" sending Sync XHR requests to prevent end user staying too long in a page where has a sync request when leaving the page, which can impact in end user experience (in their opinion of course).

To prevent errors when calling the session destroy function on page unload, the function must be updated to use `sendBeacon()`, which is made for this kind of tasks. The function does an async call, but can be used on before unload event in almost any browser (except IE, as always...)

Here are the links related to this problem:

- Chrome feature removal: https://www.chromestatus.com/feature/4664843055398912
- MSDN: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon
- W3C: https://w3c.github.io/beacon/
- CanIUse: https://caniuse.com/#feat=beacon

**Comment by lminiero** [comment]
Thanks for the heads up! If you can work on a pull request that fixes the way we do it now, I'd be glad to have a look.

**Comment by DaGLiMiOuX** [comment]
> Thanks for the heads up! If you can work on a pull request that fixes the way we do it now, I'd be glad to have a look.

As soon as I get time in Christmas holidays, I will try to create a PR.

**Comment by oscarvadillog** [comment]
Thanks Diego, I'll let you know my feedback when you start with the PR.

**Comment by lminiero** [comment]
Please see the PR above and let me know if it fixes the issue.

**Comment by lminiero** [comment]
@DaGLiMiOuX @oscarvadillog any update? I'd like to merge ASAP, and will do that tomorrow unless you test and say it's breaking something for you.

**Comment by lminiero** [comment]
Merged.

**Comment by DaGLiMiOuX** [comment]
Sorry I'm a little busy at work right now, but I was looking at it on Friday and it seemed okay for me. I will give it a try ASAP.

Sorry for the late reply. I will keep you updated if something breaks after the update.

Thank you for your work.
