### ISSUE TITLE
vp9-svc video room connect with andorid phone problem

### ISSUE THREAD

**Issue by cihansimsir** [meetecho/janus-gateway#1909]

**Comment by cihansimsir** [comment]
Hi everyone,
I try to connect vp9-svc video room with my Android phone. I set up my flags but processing of my code is different than laptop. Buttons are not working true. I tried a lot of way to make it true but I couldnt. If anybody have any information, please share with me.
Thank  you!!

**Comment by cihansimsir** [comment]
Hi everyone,
I try to connect vp9-svc video room with my Android phone. I set up my flags but processing of my code is different than laptop. Buttons are not working true. I tried a lot of way to make it true but I couldnt. If anybody have any information, please share with me.
Thank  you!!

**Comment by JH1118Park** [comment]
hello. 
please try to use libvpx(vp9) sw codec.
