### ISSUE TITLE
Adding Timestamp to log

### ISSUE THREAD

**Issue by abieuzent** [meetecho/janus-gateway#191]
Add to actual console log a standard timestamps.

Thanks

**Comment by lminiero** [comment]
If we add this, it will be optional. I personally don't want my output to be clogged by a 30% additional overhead to have a timestamp for each line. We'll probably implement this only when we'll start working on logging to an external file, though. It's on our TODO list but I don't have a timeline.

**Comment by ploxiln** [comment]
I used to run almost all services with timestamps in log lines. But then I started using a log aggregation / management system which itself adds timestamps to log lines, so I adjusted most services to not put timestamps in log lines, to avoid it going in twice. I can understand the desire to have it either way.

**Comment by lminiero** [comment]
Added as an option, both command line and configuration file. Disabled by default.
