### ISSUE TITLE
vp9-svc video room connection with andorid phone problem

### ISSUE THREAD

**Issue by cihansimsir** [meetecho/janus-gateway#1910]
Hi everyone,
I try to connect vp9-svc video room with my Android phone. I set up my flags but processing of my code is different than laptop. Buttons are not working true. I tried a lot of way to make it true but I couldnt. If anybody have any information, please share with me.
Thank  you!!

**Comment by akilude** [comment]
Hi,

This seems like more of a question than something wrong with janus, please posts questions in the [google group](https://groups.google.com/forum/?pli=1#!forum/meetecho-janus) , if its a bug with janus, please provide more info than just saying it doesn't work.

**Comment by cihansimsir** [comment]
Actually It  is a question, I just try to learn anybody have same problem
with me, and try to learn how to fix this problem. I also posted in google
group but I couldn't see any answer.
Thanks for your Interests..

akilude <notifications@github.com>, 6 Oca 2020 Pzt, 10:40 tarihinde şunu
yazdı:

**Comment by cihansimsir** [comment]
my problem is that I try to connect vp9-svc video room and switch buttons
but my screen sizes are 3:4 so I couldnt switch buttons and I want learn
how to fix this problem.

Cihan Şimşir <cihansimsirrr@gmail.com>, 20 Oca 2020 Pzt, 10:14 tarihinde
şunu yazdı:
