### ISSUE TITLE
Possible memory leak in `html/janus.js`

### ISSUE THREAD

**Issue by vladexologija** [meetecho/janus-gateway#1914]
Hi there,

I think there is a possible memory leak in `html/janus.js`. There are listeners declared on lines
https://github.com/meetecho/janus-gateway/blob/11d78977f333bcadf3c34d27f1e30225f19befbf/html/janus.js#L66
https://github.com/meetecho/janus-gateway/blob/11d78977f333bcadf3c34d27f1e30225f19befbf/html/janus.js#L325
but I couldn't find `window.removeEventListener` in the `destroySession` method.

Thanks ahead 👍

**Comment by lminiero** [comment]
I thought they were removed automatically when the page is refreshed? They are not bound to the session (and so shouldn't be removed in `destroySession` in case), but to the `Janus.init`, which means they're only done once when the page is loaded.

**Comment by lminiero** [comment]
Closing.
