### ISSUE TITLE
Janus does not actively probe client state

### ISSUE THREAD

**Issue by helisong427** [meetecho/janus-gateway#1917]
Janus does not actively probe for the existence of clients, especially for the message queue transport layer (rabbitmq, etc.).For example, after a client sends a 'create' message, no messages (including keepalive messages) are sent, which allows janus to store a lot of useless session data

**Comment by RSATom** [comment]
Are you sure session not drop after timeout?
By default it's 60 seconds and configured here: https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L54

**Comment by lminiero** [comment]
Not sure what the question is about, but I hardly think it's a bug, so I'll close.
