### ISSUE TITLE
 undefined reference to `libwebsock_bind_ssl'

### ISSUE THREAD

**Issue by u11140** [meetecho/janus-gateway#192]
Hello guys,
                  I am installing demos of janus on localhost and followed the instructions from http://janus.conf.meetecho.com/docs/README.html  .
 First I have installed dependencies.  After that, I did 

 git clone https://github.com/meetecho/janus-gateway.git
 cd janus-gateway

Then used:	   sh autogen.sh
	                   ./configure --prefix=/opt/janus 
                            make 
When I entered "make" command on terminal, I got following error

janus-janus.o: In function `main':
/home/user/janus-gateway/janus.c:4516: undefined reference to `libwebsock_bind_ssl'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_verify@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_shutdown@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_verify_result@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `ERR_lib_error_string@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_write@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_set_fd@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_NAME_get_text_by_NID@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_connect@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_ctrl@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `BIO_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_library_init@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_accept@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `ERR_get_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `EVP_sha1@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_default_passwd_cb_userdata@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_use_certificate_file@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_ex_data@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_get_ext_count@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `BIO_new_socket@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `HMAC@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_pending@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_STORE_CTX_get_error_depth@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `ERR_func_error_string@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_get_subject_name@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_load_error_strings@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `TLSv1_client_method@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_check_private_key@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_load_client_CA_file@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `OBJ_obj2nid@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_ex_data_X509_STORE_CTX_idx@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_ex_new_index@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `OBJ_nid2sn@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_verify_cert_error_string@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_peer_certificate@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_new@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `sk_value@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_verify_depth@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_use_PrivateKey_file@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSLv23_method@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_EXTENSION_get_object@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_STORE_CTX_set_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_STORE_CTX_get_ex_data@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_cipher_list@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_current_cipher@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_STORE_CTX_get_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_get_issuer_name@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_free@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_default_passwd_cb@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `ERR_error_string_n@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `BIO_ctrl@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_new@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_get_ext@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `RAND_pseudo_bytes@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_shutdown@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_STORE_CTX_get_current_cert@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_set_bio@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `TLSv1_method@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_read@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509V3_EXT_get@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `RAND_load_file@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_load_verify_locations@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_session_id_context@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509_NAME_oneline@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `ERR_reason_error_string@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CIPHER_get_name@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_CTX_set_client_CA_list@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `SSL_set_ex_data@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `X509V3_EXT_d2i@OPENSSL_1.0.0'
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../lib/libsofia-sip-ua.so: undefined reference to `sk_num@OPENSSL_1.0.0'
collect2: error: ld returned 1 exit status
make[2]: *** [janus] Error 1
make[2]: Leaving directory `/home/user/janus-gateway'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/user/janus-gateway'
make: *** [all] Error 2

Can anyone please help me?

**Comment by lminiero** [comment]
libwebsock has been replaced by libwebsockets in the latest version of Janus, so this issue is deprecated. Please try the new version of Janus instead.

**Comment by u11140** [comment]
I am trying to get tar file from this
http://paydensutherland.com/libwebsock-1.0.4.tar.gz
but i am not able to find it . could you give me the url from where I can download it

**Comment by lminiero** [comment]
As I said, we don't use libwebsock anymore.
Get the latest version of Janus and refer to the updated README for installing.

**Comment by u11140** [comment]
I tried following command 
git clone git://git.libwebsockets.org/libwebsockets
And after some time I am gettig following error
Cloning into 'libwebsockets'...
fatal: unable to connect to git.libwebsockets.org:
git.libwebsockets.org[0: 114.36.230.130]: errno=Connection timed out

I tried 3-4 times but could not get it

**Comment by lminiero** [comment]
Works fine here. It may be some filters in your network that prevent you from reaching the address/port. Try visiting https://libwebsockets.org/ for more download alternatives.

**Comment by u11140** [comment]
Hi lminiero, I have downloaded libwebsockets from https://github.com/warmcat/libwebsockets
But still getting same error

**Comment by saghul** [comment]
@u11140 get the latest *Janus* code from the git repository.
