### ISSUE TITLE
streaming video freezes in chrome79 when video track "mute" then "unmute"

### ISSUE THREAD

**Issue by okunishinishi** [meetecho/janus-gateway#1920]
Video freezed in chrome79 when  "muted"  and "unmuted"  event fired sequentially

i don't think you should add/remove tracks on remote stream in browser.

https://github.com/meetecho/janus-gateway/blob/06e76a81b9e69ab8a5da378fa26af39f8a626d1e/html/janus.js#L1765

https://github.com/meetecho/janus-gateway/blob/06e76a81b9e69ab8a5da378fa26af39f8a626d1e/html/janus.js#L1773

**Comment by okunishinishi** [comment]
It occurs when streaming small size videos (eg. 100x100)

**Comment by lminiero** [comment]
> i don't think you should add/remove tracks on remote stream in browser.

We should, instead, it's the only way the browser/application can know when a stream is gone. If you get those frequent events, then it's the stream that is that way: for instance it happened to me sometimes with streams encoded by gstreamer 0.10, but not gstreamer 1.0, which means it's an issue with the stream itself. That said, you're free to ignore those events in your web application: while the demos enforce them, you don't have to.

Closing as not an issue.
