### ISSUE TITLE
npm install janus-gateway error

### ISSUE THREAD

**Issue by tonyload** [meetecho/janus-gateway#1921]
when i install janus-way by npm   it shows
Install fail! Error: [janus-gateway@git://github.com/meetecho/janus-gateway.git]Run "C:\WINDOWS\system32\cmd.exe /d /s /c git clone https://github.com/meetecho/janus-gateway.git D:\code\realprj\netconfer\node_modules\.tmp\a4a4d441-aa36-40f9-905c-e02eeec7cc5b" error, exit code 128

my  package.json file like this:
 "dependencies": {
    "axios": "^0.19.0",
    "babel-polyfill": "^6.26.0",
    "core-js": "^3.4.3",
    "element-ui": "^2.13.0",
    "exports-loader": "^0.7.0",
    "janus-gateway": "git://github.com/meetecho/janus-gateway.git",
    "vue": "^2.6.10",
    "vue-router": "^3.1.3",
    "vuex": "^3.1.2"
  },

how should i insatll janus-gateway  rightly ?

**Comment by RSATom** [comment]
For me it looks like you are trying to do something very strange. Don't think you can repo with C code in Node.js project.

**Comment by lminiero** [comment]
Closing.

**Comment by shamseerahammedm** [comment]
+1
