### ISSUE TITLE
Segmentation fault in audiobridbe plugin

### ISSUE THREAD

**Issue by chpl** [meetecho/janus-gateway#1923]
Janus built from v0.7.6 tag
dependencies: {
      "glib2": "2.50.3",
      "jansson": "2.9",
      "libnice": "0.1.16",
      "libsrtp": "libsrtp2 2.2.0",
      "crypto": "OpenSSL 1.1.0l  10 Sep 2019"
}

https://pastebin.com/wx9qvSQr

Happens when participant leave room before media is ready

**Comment by lminiero** [comment]
Please test master, I don't debug older versions.

**Comment by lminiero** [comment]
The commit above should fix it: there was a missing check on whether the participant's `room` was `NULL`, and it was dereferenced anyway, hence your crash.
