### ISSUE TITLE
Streaming for rtsp cannot work...

### ISSUE THREAD

**Issue by tms2003** [meetecho/janus-gateway#1924]
I just try streaming for rtsp.and my config janus.plugin.streaming.jcfg like this:

```
rtsp-test: {
	type = "rtsp"
        id = 99
        description = "RTSP Test"
        audio = false
        video = true
        url = "rtsp://127.0.0.1:8080/wwe.m4e"
        #rtsp_user = "username"
        #rtsp_pwd = "password"
}

```
the rtsp://127.0.0.1:8080/wwe.m4e generated by  live555,and play in vlc is ok. but I get this tip in web page:

`
WebRTC error... {"stack":"Error: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: Failed to set remote video description send parameters."}
`

why?

**Comment by lminiero** [comment]
Clearly a codec/profile issue, discussed plenty of times on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) (where questions like this belong). Closing.
