### ISSUE TITLE
Feature: add rtp payload type into rtp_forward response

### ISSUE THREAD

**Issue by euskadi31** [meetecho/janus-gateway#1926]
Hi,

Is it possible to add `video_pt` and `audio_pt` into `rtp_forward` response ?

It would be very useful to create an sdp file.

Thanks

**Comment by lminiero** [comment]
There's no need for that, you can specify the payload types to use yourself when invoking `rtp_forward`, and those will be used no matter what the publisher is actually using. Closing.

**Comment by euskadi31** [comment]
ok, thank you
