### ISSUE TITLE
Screen not working on the latest firefox version 72.0.2

### ISSUE THREAD

**Issue by arun3528** [meetecho/janus-gateway#1931]
Tried screen sharing on the latest firefox browser with the latest mac os cantalina .

**Comment by arun3528** [comment]
![Screen Shot 2020-01-28 at 5 24 56 PM](https://user-images.githubusercontent.com/3895486/73310912-362d0580-41f3-11ea-83cc-cef5c61d74cb.png)

**Comment by oscarvadillog** [comment]
Which version exactly of FF did you test?

**Comment by lminiero** [comment]
Works fine here (Firefox 72.0.2 on Linux), so it must be an issue with your Fedora instance on Mac OS. Closing.
