### ISSUE TITLE
Streaming plugin never sends 'started' event, maybe related to ice candidates

### ISSUE THREAD

**Issue by benolayinka** [meetecho/janus-gateway#1936]
Edit: I wrote this yesterday and I've fixed it now, but since I can't find any other github issues referencing it, I'm going to post the issue and let someone close it for reference:

I'm using the Janus.js API, and sometimes, after requesting a stream, I never receive the 'started' event, and I never get a stream. A single refresh almost always fixes it, and then I receive a 'started' event normally, and a stream.

I followed the instructions initially and compiled libnice 0.1.15, but still had trouble with ice candidates. What solved the issue for me, was downgrading to a version of libnice I found from this thread:
https://github.com/meetecho/janus-gateway/issues/788

That means
```
git clone https://github.com/libnice/libnice.git
cd libnice
git checkout dbaf8f5ccd76089e340883887c7e08e6c04de80a
./autogen.sh
./configure --prefix=/usr
make && sudo make install
```

**Comment by lminiero** [comment]
Clearly a connectivity issue and not a code one, so doesn't belong here. Closing.

**Comment by alexamirante** [comment]
Let me add, for the sake of people that may run into this thread in the future, that using a version of libnice that is older than 2.5 years is not recommended at all! Even the 0.1.15 release that you tried first is from ~1 year ago. We always suggest that people compile Janus against a recent version of libnice, master is recommended.
