### ISSUE TITLE
 undefined reference to `srtp_get_version_string' while running 'make' command

### ISSUE THREAD

**Issue by arunkrishna2992** [meetecho/janus-gateway#1939]
janus-janus.o: In function `janus_info':
/home/arun/Downloads/janus-gateway/janus.c:326: undefined reference to `srtp_get_version_string'
collect2: error: ld returned 1 exit status
Makefile:1778: recipe for target 'janus' failed
make[2]: *** [janus] Error 1
make[2]: Leaving directory '/home/arun/Downloads/janus-gateway'
Makefile:3065: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/arun/Downloads/janus-gateway'
Makefile:1377: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lminiero** [comment]
Discussed (and solved) several times already on the [group](https://groups.google.com/forum/#!forum/meetecho-janus). Closing.
