### ISSUE TITLE
Chrome 41 - Failed to parse SessionDescription (Record&Play plugin)

### ISSUE THREAD

**Issue by chest3x** [meetecho/janus-gateway#194]
For some time, recording (Record&Play plugin) using Chrome was working correctly, but now for a while (can't surely say how long, since I'm mostly using Firefox, but it was something about 2-3weeks ago) my videos are empty, because no data is flowing inside RTP. Today I discovered this problem in console, which I suspise might be the issue.

    WebRTC error: janus.js:1405 
    Failed to parse SessionDescription. s= Expect line: s=

I have seen the latest commit with SDP change for Chrome 43, but it does not help. 
I also tried the new, clean version of Janus (with none of my code) and the issue persists.
The problem is with Chrome 41. On Firefox everything works good.

Thank You.

**Comment by lminiero** [comment]
Very busy week -- I'll try to look into this ASAP.
You may want to also notify this issue on the meetecho-janus google group to check if anyone met the same issue and handled this.

**Comment by nowylie** [comment]
Are you able to supply a copy of the Session Description that causes this error?

After a quick browse of the record&play plugin my guess is that the recording name is a null string or similar, and that the template is outputting a line of `"s=\r\n"` (which is invalid).

**Comment by lminiero** [comment]
A null string would be rendered as ```(nil)```, I think. An empty string would cause the output you described instead, so if that's the bug I know what to fix. Waiting for the flawed SDP from @chest3x then.

**Comment by chest3x** [comment]
You are right, empty string causes this problem in Chrome. After filling the field, system works as expected.
Firefox, however, handles this good.

**Comment by nowylie** [comment]
This behavior in Firefox (while convenient) is technically invalid. One of the frustrations with using SDP for media descriptions is that it is quite verbose and has a lot of rules.

It might be helpful to default back to some safe values when invalid ones are passed to the SDP template.

**Comment by lminiero** [comment]
I'll fix the empty ```s=``` attribute in the plugin. I'll think about whether or not handling this in the core SDP builder as well.
