### ISSUE TITLE
to solve compiling error "diagnostic" in GCC 4.4.X and lower

### ISSUE THREAD

**Issue by chengmo03013106** [meetecho/janus-gateway#1942]
https://github.com/meetecho/janus-gateway/blob/5b0aa041cd2ef50bdba100f162acbc14d641067a/rtp.c#L66

I faced the error "#pragma GCC diagnostic not allowed inside functions" durning compiling.
to solve this I added #if defined(__GNUC__) && __GNUC__ >= 5 and #endif warpped the L66.

It worked fine on my case.

Hope helpful.

**Comment by lminiero** [comment]
gcc 4.x is very old, though...

Not sure why only adding the `#if/#endif` around line 66 fixes it for you, since just a couple of lines below there's another `#pragma` to restore the diagnostic. Shouldn't you add the same for line 68 as well?

**Comment by chengmo03013106** [comment]
> gcc 4.x is very old, though...
> 
> Not sure why only adding the `#if/#endif` around line 66 fixes it for you, since just a couple of lines below there's another `#pragma` to restore the diagnostic. Shouldn't you add the same for line 68 as well?

Yep, that's right. 
I did so in each "#paragma ... diagnostic" parts.
Two of them in rtp.c, Another two parts in utils.c, line 289 , 300

**Comment by lminiero** [comment]
Please provide a pull request which includes all the fixes you need, and we'll review it. We don't have access to such an old version of the compiler, and so wouldn't be able to verify our changes fix it.

**Comment by chengmo03013106** [comment]
> Please provide a pull request which includes all the fixes you need, and we'll review it. We don't have access to such an old version of the compiler, and so wouldn't be able to verify our changes fix it.

I am sorry that I can not sure the pull request because the codes were from my team. 
The only thing I am sure is jauns version "const char *janus_version_string = "0.6.0";" which located in version.c

It might not be necessary to be fixed for my old version compiler.

**Comment by lminiero** [comment]
Version 0.6.0 is very old. Considering this is related to a very old gcc version (which I guess isn't very common anymore), I'll close the issue: if you still feel it should be solved, please contribute a fix and we'll review.

**Comment by chengmo03013106** [comment]
> Version 0.6.0 is very old. Considering this is related to a very old gcc version (which I guess isn't very common anymore), I'll close the issue: if you still feel it should be solved, please contribute a fix and we'll review.

That's all right.
Thank you for all the things
