### ISSUE TITLE
Failed to set remote candidate in janus webrtc

### ISSUE THREAD

**Issue by sreelakshmitvvdn** [meetecho/janus-gateway#1948]
Creating new session: 1391956285474418; 0x7ff4ec004c00
Creating new handle in session 1391956285474418: 8396830102908858; 0x7ff4ec004c00 0x7ff4ec005210
Creating new session: 1145972219248356; 0x7ff4ec00b8c0
Creating new handle in session 1145972219248356: 470886556776584; 0x7ff4ec00b8c0 0x7ff4ec01e110
[470886556776584] Creating ICE agent (ICE Full mode, controlled)
[8396830102908858] Creating ICE agent (ICE Full mode, controlling)
[ERR] [ice.c:janus_ice_setup_remote_candidates:3180] [8396830102908858] Failed to set remote candidates :-( (added 1, expected 2)
[WARN] [8396830102908858]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [8396830102908858]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [8396830102908858]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [8396830102908858]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [470886556776584]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [470886556776584]     Missing valid SRTP session (packet arrived too early?), skipping...
[8396830102908858] The DTLS handshake has been completed
[janus.plugin.videocall-0x7ff4ec001e60] WebRTC media is now available
[WARN] [8396830102908858] Not video and not audio? dropping (SSRC 52736345)...
[WARN] [8396830102908858] Not video and not audio? dropping (SSRC 1623599927)...
[WARN] [8396830102908858] Not video and not audio? dropping (SSRC 273700490)...
[WARN] [8396830102908858] Not video and not audio? dropping (SSRC 3272164033)...
[WARN] [8396830102908858] Not video and not audio? dropping (SSRC 1393688609)...
[janus.plugin.videocall-0x7ff4ec001e60] No WebRTC media anymore
[8396830102908858] WebRTC resources freed; 0x7ff4ec005210 0x7ff4ec004c00
[janus.plugin.videocall-0x7ff4ec00b890] No WebRTC media anymore

Please suggest how to proceed

**Comment by lminiero** [comment]
Closing since you blatantly ignored the guidelines.

**Comment by sreelakshmitvvdn** [comment]
Creating new session: 7789516933537062; 0x7f4d04002a60
Creating new handle in session 7789516933537062: 4913543116657166; 0x7f4d04002a60 0x7f4d04002ff0
Creating new session: 3333120844467441; 0x7f4ce0001780
Creating new handle in session 3333120844467441: 1998185423860826; 0x7f4ce0001780 0x7f4d04006240
[WARN] [4913543116657166] No stream, queueing this trickle as it got here before the SDP...
[WARN] [4913543116657166] No stream, queueing this trickle as it got here before the SDP...
[WARN] [4913543116657166] No stream, queueing this trickle as it got here before the SDP...
[4913543116657166] Creating ICE agent (ICE Full mode, controlled)
[1998185423860826] Creating ICE agent (ICE Full mode, controlling)
**[ERR] [ice.c:janus_ice_setup_remote_candidates:3180] [1998185423860826] Failed to set remote candidates :-( (added 1, expected 2)**
[WARN] [1998185423860826]     Missing valid SRTP session (packet arrived too early?), skipping.


We have followed the guidelines in README  file and now while running the server , we are getting the above issue. Please help me out
