### ISSUE TITLE
Creating new session: 7789516933537062; 0x7f4d04002a60

### ISSUE THREAD

**Issue by sreelakshmitvvdn** [meetecho/janus-gateway#1949]
Creating new session: 7789516933537062; 0x7f4d04002a60
Creating new handle in session 7789516933537062: 4913543116657166; 0x7f4d04002a60 0x7f4d04002ff0
Creating new session: 3333120844467441; 0x7f4ce0001780
Creating new handle in session 3333120844467441: 1998185423860826; 0x7f4ce0001780 0x7f4d04006240
[WARN] [4913543116657166] No stream, queueing this trickle as it got here before the SDP...
[WARN] [4913543116657166] No stream, queueing this trickle as it got here before the SDP...
[WARN] [4913543116657166] No stream, queueing this trickle as it got here before the SDP...
[4913543116657166] Creating ICE agent (ICE Full mode, controlled)
[1998185423860826] Creating ICE agent (ICE Full mode, controlling)
**[ERR] [ice.c:janus_ice_setup_remote_candidates:3180] [1998185423860826] Failed to set remote candidates :-( (added 1, expected 2)**
[WARN] [1998185423860826]     Missing valid SRTP session (packet arrived too early?), skipping.

We have followed the guidelines in README  file and now while running the server , we are getting the above issue. Please help me out

_Originally posted by @sreelakshmitvvdn in https://github.com/meetecho/janus-gateway/issues/1948#issuecomment-587281131_

**Comment by lminiero** [comment]
Will you stop opening the same issue over and over? And again, you did NOT follow the guidelines, which is the text you removed to submit this very issue:

> If you want to open an issue, please make sure that:
>
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved in master;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available [here](http://janus.conf.meetecho.com/docs/debug.html)).
>
> If so, just remove this text and share your findings!

This clearly belongs to the group, where it has been discussed already other times. Besides, you're not even saying which version of Janus and libnice you're using. Closing.

**Comment by sreelakshmitvvdn** [comment]
Why u peoples are so rude.. We are trying to use janus and we got error. We
felt janus as good so we thought of implementing that.

When we are stuck in an error, and we are not getting how to proceed thats
why we thought of asking help.

If you peoples are closing issues without proper replying that's so bad
