### ISSUE TITLE
segmentation fault at start in janus_recordplay

### ISSUE THREAD

**Issue by ldenoue** [meetecho/janus-gateway#195]
I had used the record play plugin with media { audio: true, video: false} because I only wanted audio to be recorded.
But then when I restarted Janus, the function update_recording_list crashed because it doesn't find the video file on disk.
It's probably crashing around here:
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_recordplay.c#L1522

**Comment by lminiero** [comment]
Thanks, I'll look into this.
