### ISSUE TITLE
Failed to set remote candidates

### ISSUE THREAD

**Issue by shihabkaranchery** [meetecho/janus-gateway#1950]
i have configured the janus-gateway in azure. installed all dependency. when try to make video call sessions created but no video available logs are seems like

Creating new session: 7295874067549813; 0x7fec98004230
Creating new handle in session 7295874067549813: 2264190151434116; 0x7fec98004230 0x7fec98005430
Creating new session: 3622043621310499; 0x5557f104b700
Creating new handle in session 3622043621310499: 3486814800053046; 0x5557f104b700 0x7fec98008f60
[ERR] [transports/janus_http.c:janus_http_handler:1239] Invalid url /ws/v1/cluster/apps/new-application
[3486814800053046] Creating ICE agent (ICE Full mode, controlled)
[2264190151434116] Creating ICE agent (ICE Full mode, controlling)
**[ERR] [ice.c:janus_ice_setup_remote_candidates:3180] [2264190151434116] Failed to set remote candidates :-( (added 1, expected 2)**
**[WARN] [2264190151434116]     Missing valid SRTP session (packet arrived too early?), skipping...**
[WARN] [2264190151434116]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [2264190151434116]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3486814800053046]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [2264190151434116]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3486814800053046]     Missing valid SRTP session (packet arrived too early?), skipping...
**[2264190151434116] The DTLS handshake has been completed**
**[janus.plugin.videocall-0x7fec98004430] WebRTC media is now available**
**[WARN] [2264190151434116] Not video and not audio? dropping (SSRC 3036569962)...**
[WARN] [2264190151434116] Not video and not audio? dropping (SSRC 3126498254)...

any idea how to fix this..

**Comment by anteyk** [comment]
Hi @shihabkaranchery how did you fix this error
 `Failed to set remote candidates :-( (added 1, expected 2)`
?

**Comment by chnirt** [comment]
i have the same problem ? How to fix this error

**Comment by shihabkaranchery** [comment]
it was my STUN server issue. i have added Stun in HTTP and WebSocket configurations files and run the Janus sever li this `sudo janus --nat-1-1=<my_instance_ip>`
