### ISSUE TITLE
Question relating with the license of the new Plugin

### ISSUE THREAD

**Issue by lm123** [meetecho/janus-gateway#1951]
We plan to develop new plugin based on current VideoRoom to meet the requirement from our customer. Shall the new plugin follow with GPL v2 license as Janus itself, and open sourced to the community?

**Comment by lminiero** [comment]
If you modify the VideoRoom, then GPL v3 (not v2) applies, because that's how it's licensed. If you write a brand new plugin, you can keep it to yourself. Closing as not a code issue, and discussions like this belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
