### ISSUE TITLE
Add more specific type of event.

### ISSUE THREAD

**Issue by euskadi31** [meetecho/janus-gateway#1953]
Hi @lminiero, 

Do you think it's possible to add an `event_type` property in event (event handler)?

It is difficult to deserialize events in strongly typed languages (Go, Java, ...), because we cannot choose the right class according to the type.

Example:

Media video receiving:
```json
{
	"emitter": "janus",
	"type": 32,
	"timestamp": 1581607427442327,
	"session_id": 4285643828377147,
	"handle_id": 4246276132067595,
	"opaque_id": "aAClXnah1XDC",
	"event": {
		"media": "video",
		"receiving": true
	}
}
```

Media video slow link:

```json
{
	"emitter": "janus",
	"type": 32,
	"timestamp": 1581607429854220,
	"session_id": 4285643828377147,
	"handle_id": 4246276132067595,
	"opaque_id": "aAClXnah1XDC",
	"event": {
		"media": "video",
		"slow_link": "downlink",
		"lost_lastsec": 7
	}
}
```

What would be good is to have the event type as follow:

```json
{
	"emitter": "janus",
	"type": 32,
	"timestamp": 1581607429854220,
	"session_id": 4285643828377147,
	"handle_id": 4246276132067595,
	"opaque_id": "aAClXnah1XDC",
	"event_type": 14,
	"event": {
		"media": "video",
		"slow_link": "downlink",
		"lost_lastsec": 7
	}
}
```

The value `14` is a value in an enum / define for example.

What do you think ?

Thank You

**Comment by lminiero** [comment]
I'm not sure that would be a good idea. It would be a violation of the "envelope" (the header), which must be opaque to the content of the event, and in your suggestion would instead be a value specific to the `type` value. This kind of additional info _may_ be added to the `event` object, but that would up to the triggerer of the event.

**Comment by euskadi31** [comment]
Indeed, the type could be in the event, as it is already the case for plugin events:

```
{
	"emitter": "janus",
	"type": 64,
	"timestamp": 1581607427206600,
	"session_id": 4285643828377147,
	"handle_id": 4246276132067595,
	"opaque_id": "aAClXnah1XDC",
	"event": {
		"plugin": "janus.plugin.videoroom",
		"data": {
			"event": "published",
			"room": 509775970513,
			"id": 4943065796806907
		}
	}
}
```

**Comment by lminiero** [comment]
On the other hand, since we have a `type`, we could have a `subtype` that might be what you need. I'll think about how to best do this. I was also considering changing `type` to a string, since a number doesn't tell much without a legend that says what's what, but that would be a breaking change so that would only happen much later in case.

Marking this as "enhancement" so that we can keep track on this.

**Comment by euskadi31** [comment]
Great !

> I was also considering changing type to a string, since a number doesn't tell much without a legend that says what's what, but that would be a breaking change so that would only happen much later in case.

At first could you add that in the documentation?

**Comment by lminiero** [comment]
Please refer to the PR above (which adds some docs as well).
