### ISSUE TITLE
SIP plugin: how to receive INVITE

### ISSUE THREAD

**Issue by aborunski** [meetecho/janus-gateway#1954]
Hello,

I'm implementing softphone based on Sip.plugin (Sofia). Currently a can successfully make outgoing phone calls but also I want receive incoming calls. The question is: where TRUNK server should send INVITE event for incoming call? to Janus port (http 8088 or ws 8188) or directly to Sofia installed on system?

**Comment by lminiero** [comment]
Closing as, per the guidelines, this is clearly not a code issue, but a question that belongs to the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
