### ISSUE TITLE
Unified-plan: Deadlock during dynamic rtp mountpoint creation

### ISSUE THREAD

**Issue by k0ntre201** [meetecho/janus-gateway#1955]
Sending "Create" request to the streaming plugin causes a deadlock (there is no response for this an future requests).

I have found this caused by trying to get locked mutex (_mountpoints_mutex_ in _janus_streaming_create_rtp_source_ function).

**Comment by lminiero** [comment]
The #1459 branch is currently severly out of sync with master. I'm planning to work on a new pull request in the upcoming weeks, as too much has changed in master in the meanwhile, and so conflict resolution on the existing PR would be a nightmare.

**Comment by lminiero** [comment]
Closing (see #1956 for motivation).
