### ISSUE TITLE
Missing Call to g_atomic_int_get() in SIP Plugin

### ISSUE THREAD

**Issue by MichaelB76** [meetecho/janus-gateway#196]
Just a minor thing I noticed when looking at the SIP plugin. In janus_sip_sofia_callback(), case nua_r_shutdown: there is the following line:

if(status < 200 && stopping < 3)

The access to the stopping variable isn't wrapped with g_atomic_int_get() like the others so this isn't thread safe. Also, the check is for "stopping < 3" but searching through the file this is only ever set to 0 or 1. I guess the use of this variable was changed at some point but this was missed.

**Comment by lminiero** [comment]
Probably a leftover, I'll fix this in the next revision, thanks.
