### ISSUE TITLE
Often "No remote video available" with UV4L and Janus Room

### ISSUE THREAD

**Issue by sreibs** [meetecho/janus-gateway#1961]
Hi all,

I am publishing a video for Raspberry CM3+ to a janus video room which I am hosting on my own server. I am playing with the "video room" demo.

Regarding video from regular browser from laptop webcam, it is quite fine.

However, the video stream of my Raspeberry gets cut randomly by "No remote video available". It is random, but as an average, I would say every 20 seconds, for 1 second. Which is quite annoying.

On the Raspberry, I am using uv4l server, following http://www.linux-projects.org/uv4l/tutorials/janus-gateway/
The configuration is the one of the tuto.

My janus room is :
`        publishers = 3
        bitrate = 1000000
        fir_freq = 1
        #audiocodec = "opus"
        videocodec = "vp8"
        record = false
        #rec_dir = "/path/to/recordings-folder"
`

I played with bitrate, fir_freq video format on the Pi etc... but nothing seems to have an impact. 

Do you have any clue to improve this ?

Thank you very much

PS: Network is fine (optical fiber) and CPU is ok (<40% on the Pi, almost nothing on the server)

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), closing.
