### ISSUE TITLE
HTTP error not call error callback when attaching plugin

### ISSUE THREAD

**Issue by hxl-dy** [meetecho/janus-gateway#1967]
https://github.com/meetecho/janus-gateway/blob/5680b403223f7216789ea5149b0907ff2ba2726d/html/janus.js#L1264-L1266

janus.js:1265 Probably a network error, is the server down?: {message: "Probably a network error, is the server down?", error: TypeError: Failed to fetch}message: "Probably a network error, is the server down?"error: TypeError: Failed to fetch__proto__: Object
error @ janus.js:1265
(anonymous) @ janus.js:151
Promise.catch (async)
httpAPICall @ janus.js:149
createHandle @ janus.js:1183
Janus.attach @ janus.js:540

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
