### ISSUE TITLE
Record H264 Streaming from gstreamer

### ISSUE THREAD

**Issue by LeeHao** [meetecho/janus-gateway#197]
Hey guys,

I have successfully used janus to stream H264 source from gstreamer and display it in firefox.  When I try to record this stream, I found it can not be playback. Does Janus only support VP8 codec recording? Can I do H264 recording by modify some code and how can I do that? 

Thanks in advance for any help you can provide.

Regards, 
Hao

**Comment by lminiero** [comment]
The recorder doesn't care, our post processing tool does instead. It assumes Opus has been recorded for audio and VP8 for video, and so creates a WebM for the video recordings. If you want to modify something, you'll need to play with the processing stuff, not the core.

**Comment by ldenoue** [comment]
Lorenzo, are you aware of a sample plugin that would decode VP8 frames in order to e.g. modify the image and then send back the modified encoded image as VP8 again?
I've read about kurento and they had these kinds of "plugins".
(by the way I am based in Verona, Italy now)

**Comment by lminiero** [comment]
None of our plugins does. I know of users who have been writing their own plugins, and and some did transcoding. One of them did something very similar to what you're looking into, using OpenCV and the like. Not sure this is open source, though. You may want to ask on the meetecho-janus google group instead of here: we only use github for issues.

**Comment by LeeHao** [comment]
Thanks, Lorenzo! So the recoder only save the rtp packages in a .mjr file and when playback (with recordplay plugin), also assumes Opus and VP8, is that rignt?

**Comment by lminiero** [comment]
Exactly. We'll probably need to revisit this sometime in the future.

**Comment by lminiero** [comment]
Closing as not an issue.
