### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by enhany** [meetecho/janus-gateway#1970]
VideoRoom will segfault on line 6294 simetimes.
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L6294

When I create new subscriber with close_pc=false. After this, publisher leave the room. And I send 'configure' request for subscriber with update=true, then videoroom will segfailt.

**Comment by enhany** [comment]
Another situation:
create subscriber with close_pc:false, join the room,
then send 'leave' and 'configure'with update=true requests in a row.

coredump on the same line as above.

**Comment by lminiero** [comment]
Thanks, we'll have a look ASAP :+1:

**Comment by lminiero** [comment]
The commit above should fix it. Notice that when you have `close_pc: false`, the publisher leaves and then you ask for an `update`, the expected result is that nothing will happen: the PeerConnection will NOT be renegotiated.

**Comment by enhany** [comment]
@lminiero yes, it's ok, PeerConnection will not be renegotiated.
Expected result in this case - janus will not crash :)
