### ISSUE TITLE
libnice: bunch of errors, probably oom related

### ISSUE THREAD

**Issue by mp16** [meetecho/janus-gateway#1974]
I had this weird messages in the syslog:

```
Feb 27 17:53:43 janus[16089]: (process:16089): libnice-CRITICAL **: nice_agent_add_local_address: assertion 'NICE_IS_AGENT (agent)' failed
Feb 27 17:53:43 janus[16089]: (process:16089): libnice-CRITICAL **: nice_agent_add_local_address: assertion 'NICE_IS_AGENT (agent)' failed
Feb 27 17:53:43 janus[16089]: (process:16089): libnice-CRITICAL **: nice_agent_add_stream: assertion 'NICE_IS_AGENT (agent)' failed
Feb 27 17:53:43 janus[16089]: (process:16089): libnice-CRITICAL **: nice_agent_set_port_range: assertion 'NICE_IS_AGENT (agent)' failed
Feb 27 17:53:43 janus[16089]: (process:16089): libnice-CRITICAL **: nice_agent_gather_candidates: assertion 'NICE_IS_AGENT (agent)' failed
Feb 27 17:53:43 janus[16089]: (process:16089): libnice-CRITICAL **: nice_agent_attach_recv: assertion 'NICE_IS_AGENT (agent)' failed
```

It looks like `nice_agent_set_port_range` is only used only there:
https://github.com/meetecho/janus-gateway/blob/2d3c53e8a874c5717126af7319c19c64ae3854a0/ice.c#L3457

And all other functions listed in the log are called from there (`janus_ice_setup_local`), so, it looks like to be the good location.

My guess is `handle->agent` is null. Probably because of a temporary low memory situation.

I suggest to check the value of `handle->agent` once created by `g_object_new()` here https://github.com/meetecho/janus-gateway/blob/2d3c53e8a874c5717126af7319c19c64ae3854a0/ice.c#L3242

So, if the server start to run out of memory, it does not continue to run with invalid objects.

Note: some further investigation looks like the server was not in a case of out of memory. I am still investigating... but I think that checking the value of `handle->agent` can be good.

**Comment by lminiero** [comment]
That won't work, as all glib functions simply abort when they can't allocate something.

**Comment by atoppi** [comment]
Hi @mp16,
in order to obtain a core dump for the failed assertion and inspect the variables, run Janus under GDB with the GLIB debugging environment variables

```
G_DEBUG=fatal-criticals gdb ./janus
```

Don't forget to compile Janus with the proper debugging flags (`-ggdb3 -O1 -fno-omit-frame-pointer`).

**Comment by mp16** [comment]
Hello,

Ok I will try this, thanks for the help.

**Comment by lminiero** [comment]
@mp16 any update on this?

**Comment by mp16** [comment]
Not yet.

I have compiled janus with the master branch (commit 02399ce75c8b47a0bdc8b65359652b4f67a57f13). Janus has been started yesterday with gdb, ran all the night, but this morning it bugged but it's a different issue. Janus stopped to reply to any websocket request, it accepts connection, it accepts to receive data, but it no more reply. Since it was started with gdb, I am trying to see if I can find something useful, I will open a new issue if I found something.

So, about the current issue, I will run it again all the week-end in gdb and see monday if it has crashed.

**Comment by mp16** [comment]
Because of #1973 I did not have enough time friday to set up in production the latest version.

Now 9386afb8f812aa6864b82aea64a8fb1c7ccadcfa is in production and I will do some feedback in few days.

**Comment by lminiero** [comment]
Can this be considered fixed, now?

**Comment by mp16** [comment]
Since monday, no crash. But this one is a very rare bug that I had after months.

Since my solution to check `handle->agent` is not ok and since Janus is now running in a debug mode, I will open a new issue if I have more information.
