### ISSUE TITLE
Generate ECDSA Private Key (instead of RSA) in janus_dtls_generate_keys

### ISSUE THREAD

**Issue by Sean-Der** [meetecho/janus-gateway#1978]
I was testing some stuff against Janus with Pion and noticed the cert size differences when looking at DTLS handshakes (RSA being larger). Would you be interested in a PR that adds ECDSA generation? I put the pseudo code below, but will be a very tiny diff.  Would mean smaller DTLS handshakes and faster cert generation!

I am happy to put it behind a configuration option etc... however you prefer the change.

```
        if ((eccGroup = OBJ_txt2nid("prime256v1") == NID_undef) {
          // error
        }

        if ((eccKey = EC_KEY_new_by_curve_name(eccGroup)) == NULL) {
          // error
        }

        EC_KEY_set_asn1_flag(eccKey, OPENSSL_EC_NAMED_CURVE);

        if (EC_KEY_generate_key(eccKey) == 0) {
          // error
        }
        if (EVP_PKEY_assign_EC_KEY(*ppPkey, eccKey) == 0) {
          // error
        }
```

**Comment by lminiero** [comment]
@Sean-Der a PR would be great, thanks! About whether to make it configurable or not, I'm not sure: if this is known to work with all OpenSSL versions, I think we can just do it considering the benefits, even though having it configurable (default being true) would allow us to have a "safe" backup in case it turns out not to always work as expected.

**Comment by lminiero** [comment]
@Sean-Der would the above pseudo-code replace the whole content of `janus_dtls_generate_keys()`, or only some parts of it? If you let me know I can try and prepare a PR myself.

**Comment by Sean-Der** [comment]
Sorry for the delay! Been a crazy week (not like you though!)

I will open my PR in about 90 more mins.

**Comment by Sean-Der** [comment]
```
sean@SeanLaptop:~$ openssl x509 -in foo.crt -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2104109506 (0x7d6a29c2)
        Signature Algorithm: ecdsa-with-SHA1
        Issuer: O = Janus, CN = Janus
        Validity
            Not Before: Mar 14 20:43:49 2019 GMT
            Not After : Mar 13 20:43:49 2021 GMT
        Subject: O = Janus, CN = Janus
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:da:e4:6c:54:af:89:4e:e4:cd:85:8b:b3:d7:b4:
                    f5:8e:7b:fe:3a:a5:0c:e9:1f:ec:d7:30:d2:8b:29:
                    f2:f5:9a:53:bf:60:a6:e7:ce:cf:a8:e4:b9:d6:0d:
                    2e:45:07:a9:59:15:fb:f0:fe:f7:fb:96:b5:98:45:
                    46:1b:a8:67:75
                ASN1 OID: prime256v1
                NIST CURVE: P-256
    Signature Algorithm: ecdsa-with-SHA1
         30:45:02:20:7b:59:38:3b:cb:3b:45:5c:b5:cf:98:92:72:c0:
         74:bf:1b:46:9f:f2:ae:f8:35:c9:15:ed:a5:65:57:88:e1:5e:
         02:21:00:f7:fc:1f:4a:b2:db:41:5b:9f:9f:dc:b6:a8:88:b9:
         80:a3:2e:a8:10:cd:82:1c:e1:8e:ab:64:94:83:50:57:62
```
