### ISSUE TITLE
Building .deb files fails due to html/Makefile.am

### ISSUE THREAD

**Issue by FThrum** [meetecho/janus-gateway#1985]
I build .deb packages for janus with the checkinstall command, however there is one small issue which does not allow me to do this with the default code.
In  html/Makefile.am there is an
`rm $(DESTDIR)$(demodir)/Makefile*`

This is failing because if the Makefile are missing the packaging process fails because rm can not delete the files.
```
make[3]: Entering directory '/home/fabian.thrum/build/janus-gateway/html'
make[3]: Nothing to be done for 'install-exec-am'.
true
/bin/mkdir -p /usr/share/janus/demos
cp -r * /usr/share/janus/demos
rm /usr/share/janus/demos/Makefile*
rm: cannot remove '/usr/share/janus/demos/Makefile': No such file or directory
rm: cannot remove '/usr/share/janus/demos/Makefile.am': No such file or directory
rm: cannot remove '/usr/share/janus/demos/Makefile.in': No such file or directory
```

 Adding an -f  in html/Makefile.am fixes the issue:
`rm -f $(DESTDIR)$(demodir)/Makefile*`

**Comment by lminiero** [comment]
Thanks for the heads up, this should fix it then! :+1:

**Comment by lminiero** [comment]
Whoops, forgot to add a reference to you in the commit... I'll make sure credits are given in the changelog when we tag the next version.

**Comment by FThrum** [comment]
Who, thanks for the quick fix !
