### ISSUE TITLE
HOWTO / Feature Request: Dynamic Room Creation

### ISSUE THREAD

**Issue by DamonOehlman** [meetecho/janus-gateway#2]
I can see that for the plugins that have a concept of rooms that rooms are configured in relevant plugin configuration file, with the room id being identified in an INI file section.

Is there any plans to support dynamic room creation through the API.  Or alternatively something similar to the way nginx uses the `HUP` signal to trigger a reload of configuration files?

I'm fine with either way :)

**Comment by Ajmal1990** [comment]
Can I able to create a room with a specific name like "room 1" ? What is the latest  status of dynamic room creation and destroying? No mentions in the docs?

**Comment by cacheworks** [comment]
@Ajmal1990 
Yes you can, as described in this comment, just change the description;
https://github.com/meetecho/janus-gateway/issues/2#issuecomment-35289245

The videoroom plugin API requests are mentioned here; https://janus.conf.meetecho.com/docs/janus__videoroom_8c.html#sfuapi
