### ISSUE TITLE
Frequent HTTP transport hangs since PR #1173

### ISSUE THREAD

**Issue by agclark81** [meetecho/janus-gateway#2000]
We had just updated to the latest master on a production server and we immediately began seeing regular HTTP transport deadlocks where Janus stops responding to any HTTP request. These deadlocks occurred both with and without the fixes from #1984.

We hadn't seen this prior to PR #1173 that merged in the single-threaded HTTP transport. I've posted the backtrace of the threads from one of the occurrences with the fixes from #1984.

Backtrace: https://pastebin.com/prGXMwdr

Please let us know if there is more information that we can help to provide.

**Comment by lminiero** [comment]
Have you checked #1998 already?

**Comment by agclark81** [comment]
We're not seeing any references to getaddrinfo in the backtrace. Would #1998 be applicable then? The threads seem to be waiting on g_mutex_lock_slowpath from a few different starting points.

**Comment by lminiero** [comment]
Then you may want to run with lock debugging enabled and replicate the issue: that will tell you which mutex is held and where.

**Comment by lminiero** [comment]
As an update, it looks like an issue with "claim" on HTTP, and easy enough to replicate. I'll let you know when I come with a fix.

**Comment by lminiero** [comment]
That should do it. Please let me know if that's not the case.

**Comment by agclark81** [comment]
Many thanks, Lorenzo. I'll test and follow up with the logs with lock debugging enabled if we continue to see any further deadlocks.
