### ISSUE TITLE
setting media.keepVideo = false when adding/replacing audio in janus.js

### ISSUE THREAD

**Issue by joeyjarosz** [meetecho/janus-gateway#2002]
I haven't begun testing against this yet (will be able to in the next week or two), so I thought I'd bring it to your attention just in case it's a typo related to past/current issues that you can spot right away.

If it's an issue, I should be able to provide feedback due to the way streams/tracks are created and passed to janus on my end, otherwise feel free to close as I'm sure I'll quickly figure out why it's been like that for the past 2 years.

https://github.com/meetecho/janus-gateway/blob/5f75debf3a66d5d959de777114a587665a39f257/html/janus.js#L1947

**Comment by lminiero** [comment]
Looks like a typo, I'll fix it :+1:
