### ISSUE TITLE
Video Room - simulcast - Substreams s1, s2 not available when bandwidth unrestricted

### ISSUE THREAD

**Issue by akilude** [meetecho/janus-gateway#2003]
Hi,

**Steps to reproduce:**
1. Visit  https://janus.conf.meetecho.com/videoroomtest.html?simulcast=true in 2 different tabs/devices and join the room
2. Do not set any bandwidth limit on the publishers

**Observed Behaviour:**
Only substream S0 is available, we cannot switch to the other substreams resulting in bad quality even in good connections.

**Additional Info:**
On limiting the publishers bandwidth, the other substreams gradually become available (after a few seconds).

This works fine in the echotest plugin without limiting the bandwidth.

Tested on Chrome 80, Firefox 74.

Thanks.

**Comment by lminiero** [comment]
Works as expected here. The fact that you say:

> On limiting the publishers bandwidth, the other substreams gradually become available (after a few seconds).

suggests the VideoRoom is created with a bitrate limitation, which is used as the default when you choose "no limitation". When you change the limit per-user to a different value, then the advertised bandwidth increases, and higher substreams become available too.

Closing as not an issue.

**Comment by akilude** [comment]
Ah, i see that you have mentioned it in the demo details, should have paid more attention , sorry about that.
