### ISSUE TITLE
ERR: SNI: Unknown ServerName:

### ISSUE THREAD

**Issue by lortas** [meetecho/janus-gateway#2006]
I am using:
```
# LANG=C.UTF8 dpkg -l janus
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                               Version                Architecture           Description
+++-==================================-======================-======================-=========================================================================
ii  janus                              0.2.6-1build2          amd64                  general purpose WebRTC gateway
```
Disabled everything except wss. Start the service and it got up without errors.
But if my WebRTC-Client tries to connect, I get the following error:
```
ERR: SNI: Unknown ServerName: ###myFQDN###
```
`###myFQDN###` is set as `server_name` in `janus.cfg` and is also the `CN` of my certificate.

Regards

**Comment by lminiero** [comment]
Honestly, I have no idea what you're talking about: nothing of what you show there seems to belong to Janus, and for sure we won't support version 0.2.6 that is 3 years old, sorry.

Closing.

**Comment by lortas** [comment]
Yes, it is about Janus, but its okay not supporting 0.2.6 anymore.
Sorry, had no clue that the current Ubuntu Server LTS provides a Janus version that old.
