### ISSUE TITLE
Issue during installation (compiling) on Fedora 31

### ISSUE THREAD

**Issue by Supercounter** [meetecho/janus-gateway#2008]
Hey guys,

I'm using a fresh installation of Fedora 31 and i'm trying to install the Janus Gateway.

During the compiling fase, i'm running into the following issue : 

./configure --prefix=/opt/janus

------------------------------------------------------------------
configure: error: Package requirements (
                    glib-2.0 >= 2.34
					libconfig
                    nice
                    jansson >= 2.5
                    libssl >= 1.0.1
                    libcrypto
                    zlib
                  ) were not met:

Package 'nice', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JANUS_CFLAGS
and JANUS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
--------------------------------------------------------------------------

I checked and got the following versions installed :

-glib2-2.62.5-1.fc31.x86_64 
-libconfig-1.7.2-4.fc31.x86_64
-libnice-0.1.16-6.fc31.x86_64
-jansson-2.12-4.fc31.x86_64
-openssl-1:1.1.1d-2.fc31.x86_64
-zlib-1.2.11-19.fc31.x86_64

Any advice?

Kind Regards,

Supercounter

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by elhananjair** [comment]
@lminiero I think this thing is a bug or an issue, for example, the latest version of jansson is 2.13 as you might check it here (http://digip.org/jansson/releases/) but during the build of janus it complains like jansson >= 2.5 must be installed, which is way older version than jansson 2.13. 
As a result, it might be good I think if it could be possible to check this thing in the source of janus. 
Thank you.
