### ISSUE TITLE
Potential deadlock in janus_videoroom.c

### ISSUE THREAD

**Issue by agclark81** [meetecho/janus-gateway#2016]
We're observing some deadlocks that are occurring in janus_videoroom.c. In the following backtrace (truncated to the first 250 threads for brevity), https://pastebin.com/n4UrbeUX, we had accumulated 2150 running threads with 2099 stuck on plugins/janus_videoroom.c:3962 (" janus_mutex_lock(&rooms_mutex);"). The other threads with a lock included:

1 thread - plugins/janus_videoroom.c:5358 - janus_mutex_lock(&videoroom->mutex);
33 threads - plugins/janus_videoroom.c:2471 - janus_mutex_lock(&rooms_mutex);
3 threads - plugins/janus_videoroom.c:2482 - janus_mutex_lock(&room->mutex);

We haven't yet been able to locate the other thread that may be involved in this deadlock, but we would like to propose a change to https://github.com/meetecho/janus-gateway/blob/576afcd0da8ef7422b437b03d1343e852c273252/plugins/janus_videoroom.c#L5359

At line 5351, we lock &rooms_mutex and then we seek to lock &videoroom->mutex (5358) before subsequently unlocking &rooms_mutex (5359). We would propose unlocking the &rooms_mutex first to avoid the potential for a deadlock elsewhere where we might lock &rooms_mutex and then lock &videoroom->mutex in the reverse order. It would seem to be unnecessary to nest the locks in this particular case, but we'd love the collective opinion on this.

**Comment by lminiero** [comment]
If you can try this patch in your environment and verify it fixes the lock for you, we'll definitely welcome a PR! It may be part of the issue, as I think we have occurrences where we lock the room mutex first, and then we lock the global one (especially in the asynchronous message handling thread).

**Comment by lminiero** [comment]
As a side note, you may want to enable the lock debugging: it will make logs incredibly more verbose, but it will allow you to track where a lock gets stuck, and so possibly figure out why.

**Comment by agclark81** [comment]
We'll be contributing a PR shortly that includes these changes and a few other adjustments that we've made that are improving stability.

**Comment by lminiero** [comment]
Closing as I just merged your PR :+1:
