### ISSUE TITLE
Destroy videoroom automatically

### ISSUE THREAD

**Issue by mr-heng-ye** [meetecho/janus-gateway#2017]
I have a webapp that the user may terminate at any time, therefore I want to destroy the resources used by the VideoRoom when the creator has been disconnected.

**Comment by lminiero** [comment]
Not a code issue, so doesn't belong here.
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by mr-heng-ye** [comment]
I don't have a google account.

**Comment by alexamirante** [comment]
That sucks!

**Comment by wangfpp** [comment]
how auto destory videoroom
