### ISSUE TITLE
Typo in close WebSocket code on session timeout

### ISSUE THREAD

**Issue by ycherniavskyi** [meetecho/janus-gateway#2018]
Just notice strange close WebSocket code on session timeout - `3504`, for sure it intended to be `504`.

https://github.com/meetecho/janus-gateway/blob/5931445f9ced40d83e273afdaafafffa0b606e39/html/janus.js#L781

**Comment by lminiero** [comment]
Thanks, fixed :+1:

**Comment by lminiero** [comment]
Apparently `3504` was chosen by @nevcos in #1431: I changed it to `504`, now, but maybe he can share some more info on why he chose that other value instead.

**Comment by lionelnicolas** [comment]
@lminiero websocket close codes should be 4 digits.

See https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent .

**Comment by lminiero** [comment]
Aaah, thanks for the clarification, I'm a dummy! I'll revert the change then :+1:

**Comment by ycherniavskyi** [comment]
@lminiero ups, sorry for the hassle 😕.
@lionelnicolas thank you for clarification. I was one click away. I checked [`WebSocket.close([code[, reason]])`](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close), but didn't check permitted status codes.

**Comment by lminiero** [comment]
@ycherniavskyi no problem, thanks for checking and reporting what you thought was an issue! I learned something new anyway :)
