### ISSUE TITLE
Unable to use libsrtp installed with other prefix than /usr

### ISSUE THREAD

**Issue by mspanc** [meetecho/janus-gateway#2019]
I am trying to compile janus-gateway 0.9.1 against libsrtp 2.3.0 on ubuntu bionic.

If I pass other prefix than /usr while compiling libsrtp it fails

```
checking for srtp_init in -lsrtp2... no
checking for srtp_init in -lsrtp... no
configure: error: libsrtp and libsrtp2 not found. See README.md for installation instructions
```

e.g. I do 

```
./configure --prefix=/opt/app/libsrtp --enable-openssl
make shared_library
sudo make install
```

then I pass /opt/libsrtp/lib/pkgconfig  to the PKG_CONFIG_PATH environment variable while configuring janus-gateway.

pkg-config properly resolves the library

```
root@2c76424c6db8:/build/janus-gateway# PKG_CONFIG_PATH=/opt/app/libnice/lib/pkgconfig:/opt/app/libsrtp/lib/pkgconfig pkg-config --cflags libsrtp2
-I/opt/app/libsrtp/include
root@2c76424c6db8:/build/janus-gateway# PKG_CONFIG_PATH=/opt/app/libnice/lib/pkgconfig:/opt/app/libsrtp/lib/pkgconfig pkg-config --libs libsrtp2
-L/opt/app/libsrtp/lib -lsrtp2 -lcrypto -ldl -pthread
```

but janus-gateway's configure scripts seem to fail in such case.

**Comment by lminiero** [comment]
We manually add `-lsrtp` or `-lsrtp2` depending on which one we find, which we don't do via pkg-config. The `configure.ac` should probably updated to use pkg-config with separate variables just for libsrtp (so that they don't impact the other dependencies), but to be honest we're so busy these days that is pretty low on my priority list. Should you want to try and update the configure script and share a pull request, I'll be happy to review!

**Comment by lminiero** [comment]
See PR above.

**Comment by lminiero** [comment]
@mspanc @hangocanh2303 ping

**Comment by mspanc** [comment]
Hey, thank you, I'll test the fix this week.

**Comment by hangocanh2303** [comment]
I confirmed, it's working with centOS 7, thank you.

**Comment by lminiero** [comment]
@hangocanh2303 thanks for confirming. @mspanc any update?

**Comment by lminiero** [comment]
I'll take that as a yes.

**Comment by vjalternativ** [comment]
installed librtp-1.5 and libsrtp-2 by compile in centos 7 but still having the issue in centos 7 with prefix /usr
