### ISSUE TITLE
some versions of gengetopt fail with latest debug-timestamps option

### ISSUE THREAD

**Issue by ploxiln** [meetecho/janus-gateway#202]
I'm running a fully up-to-date ubuntu-14.04.2 with gengetopt-2.22.6-2 installed from the standard repo.

With the latest update to `janus.ggo`, gengetopt generates this in the middle of `cmdline.c`:

```c
static void
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@ar *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
```

If I edit `janus.ggo` and just delete the line `option "debug-timestamps" D ...`, then run gengetopt again, that part of the file looks like

```c
static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
```

So, really not your fault, but rather inconvenient...

**Comment by lminiero** [comment]
I guess I could get rid of the gengetopt dependency for users, and just commit the generated c code instead.

**Comment by ploxiln** [comment]
I agree, it might overall be worth it to commit cmdline.c + cmdline.h

But before that, I wonder if anyone else can confirm this with ubuntu-14.04? Is it something special about my environment?

**Comment by ploxiln** [comment]
it's probably not much help, but I figured out that `^@` is how vim displays null bytes, and confirmed with hexdump:

```
00003fc0  73 5f 69 6e 66 6f 29 3b  0a 7d 0a 0a 0a 73 74 61  |s_info);.}...sta|
00003fd0  74 69 63 20 76 6f 69 64  0a 00 00 00 00 00 00 00  |tic void........|
00003fe0  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00004000  61 72 20 2a 6f 70 74 2c  20 63 6f 6e 73 74 20 63  |ar *opt, const c|
00004010  68 61 72 20 2a 61 72 67  2c 20 63 6f 6e 73 74 20  |har *arg, const |
00004020  63 68 61 72 20 2a 76 61  6c 75 65 73 5b 5d 29 0a  |char *values[]).|
00004030  7b 0a 20 20 46 49 58 5f  55 4e 55 53 45 44 20 28  |{.  FIX_UNUSED (|
```

That's 39 null bytes that showed up in the middle.

**Comment by ploxiln** [comment]
If I build gengetopt from source, it works fine. So that's what I'll do.

I'm going to do a clean VM install of ubuntu to rule out corruption of libc or libgcc or something wacky, then I'll report it on launchpad (ubuntu's bug tracker).

**Comment by lminiero** [comment]
I use Fedora and it never happened to me, neither on the 18 I have on my laptop not on the 21 I have at home, so I'm afraid I can't help you there. On our servers we still use Ubuntu 12.04 and its fine there too.

**Comment by ploxiln** [comment]
It's not even a bug in this particular version; it's a bug in virtualbox shared folders. I've been building test versions of janus-gateway in a virtualbox shared folder so I can edit outside the virtual machine and compile/install inside...

**Comment by ploxiln** [comment]
(and it worked... except for the latest change to janus.ggo, and the packaged gnugetopt! tweak either and no apparent problem)
