### ISSUE TITLE
Moving to the future

### ISSUE THREAD

**Issue by ibc** [meetecho/janus-gateway#2021]
- Project "Settings": Rename repository name to **janus**.
- `s/janus-gateway/janus/g` everywhere.
- In local repo: `git remote set-url origin git@github.com:meetecho/janus.git`
- Tweet it.

**Comment by lminiero** [comment]
I'll think about it :stuck_out_tongue_winking_eye:

**Comment by ibc** [comment]
THANKS U HAVE NOW TIME TO THINK THINGS

**Comment by alexamirante** [comment]
OH MY I'd love that change but I guess it would break so many scripts, including mine of course...

**Comment by ibc** [comment]
Just apply `s/janus-gateway/janus/g` in all the world.

**Comment by ibc** [comment]
WHAT? WHY? TOO BUSY MAKING ROOM IDS ALPHANUMERIC GUYS?
