### ISSUE TITLE
RabbitMQ exchange type should be configurable

### ISSUE THREAD

**Issue by mspanc** [meetecho/janus-gateway#2023]
In 0.9.1 the RabbitMQ exchange type is not configurable and is set to `fanout`.

The initialization procedure seems to be the following:

1. Connect to the RabbitMQ
2. Establish the channel
3. Declare an exchange as `fanout`
4. Declare an incoming queue
5. Declare an outgoing queue

It raises the following problems:

1. Unless the channel is bound to the exchange, sending a message into it will not cause any routing - and here binding does not happen
2. If you bind these two channels to the same exchange but the exchange is set to fanout, a message sent to the exchange will be delivered to both queues. Effectively Janus will read its own messages. Moreover, that leads to an endless loop of errors, as if you create a session, and Janus will reply with `success` message it will be routed back to Janus and it will reply with `error` message (as `success` is not valid call),  which will be again routed back to Janus etc.
 
The proper default procedure should be the following:

1. Connect to the RabbitMQ
2. Establish the channel
3. Declare an exchange as `direct`
4. Declare an incoming queue
5. Declare an outgoing queue
6. Bind the incoming queue to the exchange and set routing_key to the incoming queue name
7. Bind the outgoing queue to the exchange and set routing_key to the outgoing queue name

But for more advanced setups it should be configurable (at least the exchange type).

**Comment by lminiero** [comment]
We're extremely busy and won't certainly have time to fix all this, as this is quite low priority for us. Should you be willing to provide a patch, we'll be glad to review a pull request.

**Comment by pitkonst** [comment]
We are using RabbitMQ transport as it is implemented, and do not encount porblems you described. Fanout exchange is used to deliver same result message to multiple servers.

**Comment by lminiero** [comment]
@mspanc @pitkonst there's a new PR implemented by @voicenter in #2104 that should provide support for that. It looks fine to me, so please test and in case it works for you too I'll merge.

**Comment by lminiero** [comment]
Closing as the PR has been merged.
