### ISSUE TITLE
Reinvites during SIP plugin recording

### ISSUE THREAD

**Issue by shrhoads** [meetecho/janus-gateway#2025]
I think I found a situation where SIP plugin recording fails, I'm using Janus version: 92 (0.9.2)
Janus commit: 5f75debf3a66d5d959de777114a587665a39f257
Compiled on:  Thu Mar 26 02:55:04 UTC 2020

When parsing a recorded file with janus-pp-rec, I noticed the SSRC changes if there are SIP reinvites and the audio seems to be missing on the peer recording (I assume because the SSRC changes at the reinvite?)

In my example there are 2 reinvites and the SSRC changes:

File is 292007 bytes
Pre-parsing file to generate ordered index...
This is an audio recording:
  -- Codec:   pcmu
  -- Created: 1585228667332565
  -- Written: 1585228667332773
SSRC detected: 940659567
[WARN] Dropping packet with unexpected SSRC: 3195203570 != 940659567
...
[WARN] Dropping packet with unexpected SSRC: 3195203570 != 940659567
[WARN] Dropping packet with unexpected SSRC: 1209571003 != 940659567
...
[WARN] Dropping packet with unexpected SSRC: 1209571003 != 940659567
Counted 1604 RTP packets
Counted 271 frame packets
Writing .wav file header
/opt/record/215563353-peer-audio.wav is 86764 bytes
Bye!

Also I think the recording logic misses recording the actual RTP packets from the peer after the reinvite as they are silence in the recording.

**Comment by shrhoads** [comment]
I worked around it by commenting out the filtering code (line 707ish in janus-pp-rec.c maybe that should just be a warning instead of hard filter?

**Comment by lminiero** [comment]
No, you can't just drop it: re-ordering will go in the drain, and the result will be a mess. The recorder should be fed a consistent stream, so what should be done I guess is ensure that media being saved by the SIP plugin always has the same SSRC, which means using `janus_rtp_header_update`. No idea when I'll be able to look into this, though, as we're swamped with work: as usual, pull requests welcome.

**Comment by lminiero** [comment]
I just checked and we're actually already fixing the RTP header in the SIP plugin:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L6092
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L6164

You may want to do a wireshark capture of a SIP call, and share them along the mjr recordings of the same call through Janus.

**Comment by lminiero** [comment]
@shrhoads any update on the captures? otherwise I'll just assume it's not an issue and close.

**Comment by lminiero** [comment]
Closing.
