### ISSUE TITLE
Changed janus.plugin.videoroom.jcfg room-1234 for 16 publishers BUT ...

### ISSUE THREAD

**Issue by brailateo** [meetecho/janus-gateway#2028]
When the 7'th participant tries to connect to video room test it fails.
The error is remoteFeed.rfindex is undefined
at onremotestream function, line
Janus.attachMediaStream($('#remotevideo'+remoteFeed.rfindex).get(0), stream);

I previously created the divs and the
<div class="panel-body relative" id="videoremote15" style="padding:0px;margin:0px;"></div>
up to 15

Is there any other place where it should be changed something in order to allow 16 publishers?
Thanks,
P.S. After testing Jitsi and OpenVidu (Kurento) , Janus seems to be the best solution, not processor and memory hungry with excellent bandwidth preserving options.

**Comment by lminiero** [comment]
The demo is hardcoded to 6 slots, you'll have to change that too. Closing as not an issue, discussions belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus) and not here.
