### ISSUE TITLE
Audio transmission stops with a beep/strange noise

### ISSUE THREAD

**Issue by mr-heng-ye** [meetecho/janus-gateway#2032]
I am using the videoroom plugin, with audio and video transmission. After a few minutes, the audio transmission stops, and the subscribers get a beep or a weird noise. On the publisher computer, the microphone icon disappears showing that the audio is no longer being used. The publisher computer is running Firefox Developer Edition. There are no error messages.

**Comment by lminiero** [comment]
As explained in the guidelines, usage issues belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), NOT here. Closing.
