### ISSUE TITLE
Complete installation guide with Apache/Nginx proxy with SSL

### ISSUE THREAD

**Issue by dnnbuddy** [meetecho/janus-gateway#2035]
We want a complete installation guide for Ubuntu or CentOS. It is difficult to find a complete working installation with Apache or Nginx proxy with SSL enabled. It always throws an error. (getUserMedia() null error). 

Please guide us by providing complete documentation for this requirement. We are planning to use your valuable product to communicate with patients remotely. Your help is highly appreciated.

**Comment by lminiero** [comment]
You WANT? The info in the README is more than enough.

**Comment by dnnbuddy** [comment]
> You WANT? The info in the README is more than enough.

We have installed it in the cloud. But we get a getusermedia() related javascript error. Can you help us rectify that?

**Comment by dnnbuddy** [comment]
We are trying to figure out the issue now. I am online at skype. thusithata is my id.

**Comment by dnnbuddy** [comment]
We have successfully installed it. We had several issues in the installation previously.

**Comment by abishekrsrikaanth** [comment]
@dnnbuddy would you happen to have the complete installation script that you used to set this up successfully? Would like to be able to run a script on fresh ubuntu installation will all pre-requisites and the gateway itself.

**Comment by errawn** [comment]
> You WANT? The info in the README is more than enough.

really? which part in the readme where i can find the nginx? i cant see it :)))

https://janus.conf.meetecho.com/docs/README.html
