### ISSUE TITLE
Videoroom: transport_wide_cc_ext=true seems to cause video issues in Chrome

### ISSUE THREAD

**Issue by schoolcoder** [meetecho/janus-gateway#2042]
In the videoroom plugin, setting transport_wide_cc_ext to true causes Chrome subscribers to lose a publisher's video stream (not audio) sporadically, causing the video to flash off for about a second and then come back on. This happens frequently--maybe once every 10 to 30 seconds.

It happens only when publisher is on Chrome (version 80); Firefox publisher works fine. Have not tested Safari. I see an increase in lost and nack-ed packets in Chrome while the video is out, so I'm sure it's being caused by less-than-ideal network conditions.

However, if I turn off transport_wide_cc_ext, the problem goes away. I am using the latest janus master.

**Comment by lminiero** [comment]
I don't think this is an issue: it works just fine here. Having `transport_wide_cc_ext` enabled is definitely better than having it disabled, especially in scenarios where the network isn't great. You can try experimenting with different (smaller?) `twcc_period` values in the config. Closing.

**Comment by schoolcoder** [comment]
On our server, transport_wide_cc_ext definitely causes problems with a Firefox publisher and Chrome subscriber. Changing the twcc_period (25, 50, 100, 200, 500, 1000) did not affect the video on/off problem, but disabling transport_wide_cc_ext most definitely does. 

We see the problem only with Firefox publisher and Chrome subscriber. Chrome/Chrome works fine; Firefox/Firefox works fine. Chrome publisher/Firefox subscriber also works fine.

We're intentionally testing in an environment with about 1-2% packet loss, so we expect some issues. However, the video on/off problem is far worse, making the video unusable. In this same environment (using same two machines for the publisher and subscriber, same Janus server), disabling transport_wide_cc_ext is the only way I've found to fix the problem.
