### ISSUE TITLE
Memory leak in streaming plugin

### ISSUE THREAD

**Issue by NikSmith** [meetecho/janus-gateway#2049]
Hi.
I have some memory leak problems in a streaming plugin.
When I use this plugin with the "videobufferkf" enabled, my memory usage increases.
After I turned it off and got the horizontal line of memory usage.

Janus version: 0.9.2
Streaming plugin version: 0.0.8

![image](https://user-images.githubusercontent.com/6698935/78391033-421bb600-75ee-11ea-9acf-06c1a0095507.png)

**Comment by lminiero** [comment]
Can't replicate this. Maybe an issue with the media source?

**Comment by NikSmith** [comment]
I use the following scheme:
Gstreamer (Server A) -> Videoroom (Server B) -> Streaming (Server C)

Gstreamer plays record via  webrtc.
And I get a memory leak on server C. Can you tell me what information can be useful for debugging?

**Comment by lminiero** [comment]
Build with libasan support on server C (https://janus.conf.meetecho.com/docs/debug), replicate the issue, stop the sessions cleanly on server C and then stop it: libasan will print the memory still allocated, if any, so if you see that info copy it into a gist/pastebin and provide it here.

**Comment by NikSmith** [comment]
Thank you. I'll try it later.

**Comment by lminiero** [comment]
Any update? Without that info, since we can't replicate, we'll just close.
