### ISSUE TITLE
When "switch" a subscribed publisher to another stream in videoroom sometimes got "No such room"

### ISSUE THREAD

**Issue by brailateo** [meetecho/janus-gateway#2050]
**Usage description:**

- videoroom with 6 publishers ADMIN, SPEAKER and A,B,C,D
- only ADMIN subscribed to view every other participant
- A,B,C,D are subscribing ONLY to ADMIN and SPEAKER publishers (with data channels)
- SPEAKER is subscribing only to ADMIN
- ADMIN hears and see all other 5 participants and acts as an old phone dispatcher operator
- A,B,C,D send "floor request" to ADMIN through messages on data channel
- ADMIN sends "swtichto" commands to everyone, A,B,C,D reacts
- A,B,C,D are issuing a "switch" request for SPEAKER subscription to SWITCH to the new designed speaker (let's say A) so B,C,D are watching now A
- the switch command contains the public rfid of the new stream

**BUG DISCOVERED:**
everything is working fine until someone let's say D (from A,B,C,D) is leaving room and entering again.
When switch command is coming to watch A in SPEAKER box, even B and C are receiving "No such room" event EVEN IF THE GLOBAL rfid stream id is right! (I've double checked).
The only chance to restore functioning is restart B and C clients and everything works again, though the rfid sended to "switchto" is the same

**In server log I got the error:**
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:6137] No such room

Teo

**Comment by lminiero** [comment]
> When switch command is coming to watch A in SPEAKER box, even B and C are receiving "No such room" event EVEN IF THE GLOBAL rfid stream id is right! (I've double checked).

rfid means nothing, it's a client view, not the server perspective. `No such room` there means the subscriber has been destroyed. You're probably not setting `close_pc` to `FALSE` when creating subscribers.

Closing as not an issue and belongs to the [group](https://groups.google.com/forum/#!forum/meetecho-janus).

**Comment by brailateo** [comment]
> rfid means nothing, it's a client view, not the server perspective. `No such room` there means the subscriber has been destroyed. You're probably not setting `close_pc` to `FALSE` when creating subscribers.
> 
> Closing as not an issue and belongs to the [group](https://groups.google.com/forum/#!forum/meetecho-janus).

**This issue is describing the same error!** I saw that you closed it too!
https://github.com/meetecho/janus-gateway/issues/1761

@jflasch proposed a patch there! 

Teo
