### ISSUE TITLE
Janus only sending audio sometimes

### ISSUE THREAD

**Issue by dnish** [meetecho/janus-gateway#2052]
Hey,
I'm having a strange issue with the Janus video plugin. Sometimes, Janus is only sending the audio stream. I've already checked the sessions in the admin interface, and I can see, that audio bytes are sent (in and out), but the video bytes are 0. This affects both clients. I've requested video and audio via getUserMedia() and can see the video as "local stream". I don't get any errors on the client side, just a black video screen for the remote stream. After reloading the page, it works again, but 3-4 reloads later, I'm having the issue again.

Sometimes there is also this scenario

Client 1:
<img width="665" alt="Bildschirmfoto 2020-04-06 um 16 20 28" src="https://user-images.githubusercontent.com/7636313/78568580-97400d80-7822-11ea-9aa9-5660d2cb473e.png">

Client 2:

<img width="487" alt="Bildschirmfoto 2020-04-06 um 16 19 04" src="https://user-images.githubusercontent.com/7636313/78568571-94ddb380-7822-11ea-8936-c2635147e9b2.png">

I also get 
```
Janus started receiving our audio
Janus started receiving our video
```
on both clients.

After a reload, it works again. In production I've noticed, that we have black screens on 4/10 users. After 1-2 reconnects to the same user, I get a video stream.

**Comment by lminiero** [comment]
The screenshots clearly show the browser not sending any video, so as a result we have nothing to relay. Closing as not an issue. As a side note, questions like this belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), not here.

**Comment by dnish** [comment]
@lminiero Yeah, but did you read the log it shows:

```
Janus started receiving our audio
Janus started receiving our video
```

This is what I get on both clients when it shows the state above. I'm using your video plugin example.

**Comment by dnish** [comment]
@lminiero Any chance to find out which server version you are using on your demos (https://janus.conf.meetecho.com/janus). Seems like an issue with our server, if I'm using yours, everything is working fine.

**Comment by liu-minjie** [comment]
> @lminiero Any chance to find out which server version you are using on your demos (https://janus.conf.meetecho.com/janus). Seems like an issue with our server, if I'm using yours, everything is working fine.
> 
> // Edit: For any others who have this issue: It seems that an older version of libnice caused this issue. Just upgraded to the latest one and everything is running fine now.

Do you know why this issue is related to libnice?  why After reloading the page, it works again.
