### ISSUE TITLE
Error code 465: Error processing SDP

### ISSUE THREAD

**Issue by amakovskyi** [meetecho/janus-gateway#2056]
Hello! I developing Android client app with Janus VideoRoom plugin and received this error. All request/responses are correct until I trying to publish offer. My request:

https://pastebin.com/nebghZQj

Response is:

`{"janus":"error","session_id":2960802420708581,"transaction":"aM5UWeXQyeKg","error":{"code":465,"reason":"Error processing SDP"}}`

I using latest Google WebRTC library:

`
    implementation 'org.webrtc:google-webrtc:1.0.30039'
`

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
