### ISSUE TITLE
video room plugin createOffer stream error

### ISSUE THREAD

**Issue by gushenjie** [meetecho/janus-gateway#2058]
Server version 0.9.2, I enter the meeting by default, use a custom mediastream for video transmission through createOffer stream, then I switch screen sharing, and then I want to continue to use the initial mediastream for transmission after the screen sharing, the server always returns to stop receiving video

code:

    [Removed because guidelines say not to paste huge bunches of text but you did it anyway]

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
