### ISSUE TITLE
PR #2044 breaks trickle candidate detection

### ISSUE THREAD

**Issue by agclark81** [meetecho/janus-gateway#2064]
The isTrickleEnabled(trickle) function as changed in PR #2044 is not functionally identical to the previous iteration. Specifically, we're seeing isTrickleEnabled being called where trickle=undefined.

Previously, when trickle=undefined, the following returns true.

```javascript
return (trickle === false) ? false : true;
```

Now, with this change, it returns false.

https://github.com/meetecho/janus-gateway/blob/933c094b36354516bfa82ff56aecc6a296d8250c/html/janus.js#L3463

**Comment by atoppi** [comment]
Basically the PR transforms a true-by-default in a false-by-default check.
I think the default should be true (being trickling a desirable feature in most cases).

**Comment by lminiero** [comment]
Feel free to propose fixes.
