### ISSUE TITLE
Janus crash: transports/janus_http.c:1824

### ISSUE THREAD

**Issue by taaltaal** [meetecho/janus-gateway#2066]
We had some crashes before, this time we compiled with libasan as suggested in the docs.

The output is here:
https://pastebin.com/j7ucdmyE

P.S. Running from master. I hope this information helps!

**Comment by lminiero** [comment]
Sounds like a similar issue as #2062. As I said there, enable refcount debugging by uncommenting the `#define REFCOUNT_DEBUG` line in refcount.h and recompile: if it crashes again, we'll need both the libasan info and the last part of the log to track what happened to the affected transport (long enough to track the reference that went to 0 from when it was started). Notice the log will be VERY verbose with refcount debugging enabled, so you may want to make sure you have enough room for that.

**Comment by bitfirenetworks** [comment]
@lminiero, if this is related to #2071 as you suspect, this may be of use in debugging. I captured it with the REFCOUNT_DEBUG enabled: https://pastebin.com/DvBknrpB

**Comment by lminiero** [comment]
@bitfirenetworks thanks, I'll have a look later today :+1:

**Comment by bitfirenetworks** [comment]
Here's the same log and asan output, but all the way back to the creation of the object, with all the noise removed: https://pastebin.com/YgL9nDDU

**Comment by lminiero** [comment]
Please don't trim the file. There's no guarantee that the lines you kept are related to the pointer that was affected: in your case, it dies on a `janus_transport_session` instance (pointer `0x60400087cd70`), but 1. there's no init anywhere (so no refcount initialization), and 2. none of the refcount references are anywhere near that pointer.

**Comment by bitfirenetworks** [comment]
Here is the un-pruned log as far back as I have it for that crash: https://pastebin.com/qX0ex9mL

**Comment by lminiero** [comment]
Thanks :+1:
This isn't master, though: please test with that, as for sure you're missing [one of the fixes](https://github.com/meetecho/janus-gateway/commit/1915f0fc07988fa70624d0a63b09ae6d7bc7510d) we had for requests being unreffed too soon (which could lead to transports being unreffed too soon as well). If it happens on master too, I'll have a look to see what else needs fixing.

**Comment by bitfirenetworks** [comment]
Crashes in this area were more frequent in 0.9.2, but it happens pretty reliably in master as well. I'm early in my own hunt still, but I'm looking into the janus_http_timeout function as a potential suspect.
Crash in master: https://pastebin.com/fKnRF098

**Comment by lminiero** [comment]
This is more helpful but still doesn't cover the affected reference from the start. It seems to crash on `0x6040001723b0`, but the first reference we see for that reference is a decrease, not the init:

```
[transports/transport.c:janus_transport_session_destroy:38:decrease] 0x6040001723b0 (1)
```

The weird part is that we see it going to `0`, and then another decrease after that, which shouldn't happen:

```
[transports/janus_http.c:janus_http_send_message:958:decrease] 0x6040001723b0 (0)
[..]
[transports/janus_http.c:janus_http_timeout:1999:decrease] 0x6040001723b0 (1)
```

If you have a more complete log of the same crash, I'll check what steps that reference goes through, to figure out why there are more decreases than increases.

**Comment by lminiero** [comment]
It may be a race condition when getting rid of the timeout: the timeout is still active, so we clear it and unref the related resources, but while we do it, the timeout fires, and so unrefs the same resources again. I'll check if this can be avoided somehow.

**Comment by lminiero** [comment]
@taaltaal @bitfirenetworks please see the PR above. Provide feedback there, NOT here.

**Comment by lminiero** [comment]
Merged the PR, so I'll close.
