### ISSUE TITLE
The connection is constantly being disconnected

### ISSUE THREAD

**Issue by alokazay** [meetecho/janus-gateway#2067]
![image](https://user-images.githubusercontent.com/2505029/79148000-80269000-7dcd-11ea-9803-adb796d57554.png)  
 
Why is this happening? Screenshot from pages https://janus.conf.meetecho.com/videoroomtest.html

_Originally posted by @alokazay in https://github.com/meetecho/janus-gateway/issues/2062#issuecomment-613028719_

**Comment by akilude** [comment]
Please see https://github.com/meetecho/janus-gateway/pull/1972

**Comment by alokazay** [comment]
Yesterday I had two test conversations of 40 minutes each.  every 5-15 minutes the video disappears.  can this be somehow fixed?

**Comment by alokazay** [comment]
thanks
