### ISSUE TITLE
wrongly warns at runtime about libnice being too old

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#2069]
Janus checks at _build_ time the version of libnice, and use that to warn at _runtime_ if the version is older than 0.1.15.

Libnice can be safely upgraded to newer versions without recompilation, however: Only when the ABI changes is it necessary to relink.

Makes sense to warn, and seems from comments that build time check was necessary. So I guess there is no other approach possible.

What I suggest is then to clarify in the runtime warning that it only knows about libnice version at buildtime - that helps conservative sysadmins (as opposed to devops minded people rebuilding everything always) to also consider that their system-shared libraries might have been upgraded.

Thanks for considering.

**Comment by lminiero** [comment]
We have to do it at build time because libnice doesn't provide any version definition in their headers we can use at runtime (which is what we do with other dependencies). As such, the only way we can do that is during the configure process. I'll think of a clearer message.

**Comment by lminiero** [comment]
This should be clearer now. I also changed the suggested version to be 0.1.16, because even 0.1.15 had issues that the more recent version fixed.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2020-04-15 10:56:40)
> This should be clearer now. I also changed the suggested version to be 0.1.16, because even 0.1.15 had issues that the more recent version fixed.

Thanks!

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
