### ISSUE TITLE
configure --disable-libcurl not sufficient to disable turn rest api

### ISSUE THREAD

**Issue by ploxiln** [meetecho/janus-gateway#207]
I'm not an autoconf expert, but I don't see a connection in configure.ac between disable_libcurl and enable_turn_rest_api.

If I have libcurl-dev installed, and run `./configure --disable-libcurl ...`, configure still prints

```
checking for LIBCURL... yes
...
TURN REST API client:      yes
```

**Comment by lminiero** [comment]
You're right, we're missing an AS_IF check when the library is found, which instead is there for the other similar checks. I'll fix that tomorrow.

**Comment by lminiero** [comment]
Modified ```--disable-libcurl``` to ```--disable-turn-rest-api```, as that's what it really means. Just tried and seems to be working for me. You need to do a make clean after disabling if you compiled with libcurl support, as otherwise the symbols are still there I guess.
