### ISSUE TITLE
"Allow" adding params to sendBeacon in janus.js for session destroy

### ISSUE THREAD

**Issue by DaGLiMiOuX** [meetecho/janus-gateway#2070]
After Chrome 80, a `sendBeacon` for session destroy on unload was the replacement for the XHR sync function #1902 .

I've found a problem with this function, because we require to add params in URL, like a token or whatever information we need. We've found that this is an issue, because we are not allowing accesing directly to janus server from client browser, instead requests are managed by our own app, then redirected to janus, acting as a proxy for janus requests.

Would be helpful to allow adding params for `sendBeacon` request. We have no problem with any other request, because we are using jQuery ajax to perform requests and we modify its default settings to add those params when janus.js methods are called to perform requests to the server.

I would like to hear from you about this or if you counted on it, so we can try to perform a PR into `janus.js`.

Br,
D.

**Comment by lminiero** [comment]
Why not set your own page-closed detector, and do the sendBeacon there? If you'd rather provide a PR, I'll be glad to review it (assuming it doesn't break backwards compatibility).

**Comment by DaGLiMiOuX** [comment]
> Why not set your own page-closed detector, and do the sendBeacon there? If you'd rather provide a PR, I'll be glad to review it (assuming it doesn't break backwards compatibility).

I have my own sendBeacon detector, but in case someone has a similar situation where a param must be set to handle requests, even if they have their own sendBeacon or not, I think that allowing some extra params in URL could be helpful.

Btw, I'm using the built-in closing session using sendBeacon to prevent modifying janus.js nor programming what is already done.

I'll try to post a simple but working PR this afternoon.

Br,
D.

**Comment by DaGLiMiOuX** [comment]
Refering again to my comment into PR: Any modification into this function, even just the URL, would be enough to create your own sendBeacon.
