### ISSUE TITLE
Issue in SRTP encryption

### ISSUE THREAD

**Issue by ramprakash110109** [meetecho/janus-gateway#2072]
I have 3 janus instances running in 3 different machines to test streaming functionality	

Sometimes, I get errors while encrypting packets during rtp_forward.
Eg., “Error encrypting audio packet for ….”

Similarly, I get errors during decrypt also.
Eg., “Audio SRTP unprotect error: …..”

i saw the source code in  janus_videoroom plugin and everything looks fine. Can you suggest me  the potential causes by which this can happen?

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
