### ISSUE TITLE
postprocessing coredump

### ISSUE THREAD

**Issue by enhany** [meetecho/janus-gateway#2073]
When input video file is corrupted (I don't know why), then janus-pp-rec crashes on this line:
https://github.com/meetecho/janus-gateway/blob/master/postprocessing/pp-webm.c#L635

output:
https://pastebin.com/FKvm1JiE

**Comment by atoppi** [comment]
Do you have a recording to share to reproduce the issue?

**Comment by lminiero** [comment]
Besides, the output as you shared is unfortunately useless. Please recompile with debugging support: https://janus.conf.meetecho.com/docs/debug

**Comment by lminiero** [comment]
I guess you're not really interested in us fixing this, or you would have deigned to respond in 5 days. Closing.
