### ISSUE TITLE
"NotReadableError": Could not start video source in Chrome - Linux/Mac

### ISSUE THREAD

**Issue by Jeevhi** [meetecho/janus-gateway#2078]
Getting "NotReadableError": Could not start video source" in Chrome. Works perfect in Firefox. 

- Tried different computers - both Linux and Mac with latest Chrome and issues remains the same. 
- The camera permission is granted. 
- other webrtc demos from https://webrtc.github.io/samples/ works perfect in Chrome so no hardware issues as such
- Tried both normal and incognito windows
- completely closed all the apps and kept only a single chrome window with single tab - issue still exists
- audio seems to be working

error logs here  https://pastebin.com/zhHkzTve

**Comment by MvEerd** [comment]
This question seems more appropriate for the meetecho-janus google group so let's continue there.
https://groups.google.com/forum/#!forum/meetecho-janus

The hosted demos and master still work fine on all my different machines with different Chrome versions so this seems to be an issue related to your setup.

Useful information to include in your post on the group / to check would be:
- Where are you hosting the videoroom demo?
  (WebRTC needs https or be on localhost for the gUM request to succeed)
- Is your default device set correctly in chrome://settings/content/camera ?
- Which version of Chrome are you using exactly?

If the problem persists you can use something like process explorer to find out if and which process is using your hardware device.

Happy to help debug further on the [Google group](https://groups.google.com/forum/#!forum/meetecho-janus
), so we can keep Github uncluttered for confirmed code issues

**Comment by lminiero** [comment]
Agreed, group matter.
