### ISSUE TITLE
setting UnifiedPlan in janus.js

### ISSUE THREAD

**Issue by Jeevhi** [meetecho/janus-gateway#2079]
Looks like  `Janus.unifiedPlan` will remain `false` in chrome the way it is checked.

https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L376

**Comment by lminiero** [comment]
No, it won't, it will get in here: https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L390
Closing as not an issue.

**Comment by Jeevhi** [comment]
and why would you like to do it that way when you know unifiedPlan is supported >= 72. You are unnecessarily create a RTPConenction

**Comment by lminiero** [comment]
Because 72 to 74 was buggy as hell, and that's how I wrote it at the time. Feel free to submit a pull request to optimize this.
