### ISSUE TITLE
websocket transport disconnected occasionally

### ISSUE THREAD

**Issue by tomnotcat** [meetecho/janus-gateway#2082]
I use videoroom plugin with websocket transport, most time janus works well, but occasionally websocket will disconnect, the janus log file output:
[libwebsockets][ERR] ****** 0x7fe6cc0026e0: Sending new 187 (<81>~), pending truncated ...
It's illegal to do an lws_write outside of
the writable callback: fix your code

Clarification: Don't misunderstand, "fix your code" is part of log，not my words.

**Comment by lminiero** [comment]
I reopened #2081 so we can close this.
