### ISSUE TITLE
SHA256 and more?

### ISSUE THREAD

**Issue by Neustradamus** [meetecho/janus-gateway#2085]
Can you add RFC support?
- RFC8489: Session Traversal Utilities for NAT (STUN): https://tools.ietf.org/html/rfc8489
- RFC8760: The Session Initiation Protocol (SIP) Digest Access Authentication Scheme: https://tools.ietf.org/html/rfc8760

SHA-256
SHA-512/256

**Comment by lminiero** [comment]
In case you haven't noticed (it's only written in capital letters in the text you removed to write yours) we use GitHub ONLY FOR ISSUES.

**Comment by Neustradamus** [comment]
@lminiero: Thanks for your comment.

For compatibility and security problems, no?
