### ISSUE TITLE
new possible feature for videoroom

### ISSUE THREAD

**Issue by Computician** [meetecho/janus-gateway#209]
I have written a new feature(that I am cleaning up but works for right now) that is a raw rtp listener for all the feeds in a given video room. 

It makes a request against a room, provides a host IP and a port base and then janus will start streaming the rtp streams to that host and over a range of ports that start at that port base. 

Is this something that we want in the code base or would be best to just keep this separate? I don't want to bother cleaning it up and stuff if there is no chance of merging the pull request. 

Request:
`{
   "janus":"message",
   "transaction":"8mefvq9ak7l6",
   "body": {
      "request":"anonymous_listen",
      "room":1234,
      "host":"192.168.0.17",
      "port":5000
   }
}`

response:
`{
   "janus": "success",
   "session_id": 12333,
   "sender": 11222,
   "transaction": <same as above>
   "plugindata": {
        "plugin": "janus.plugin.videoroom",
        "data": {
             "stream_number": 2,
             "room": 1234,
             "streams": [
                  {
                       "user_id": 12344565,
                       "audio_port": 5000,
                       "video_port": 5002
                  },
                  {
                       "user_id": 12333333,
                       "audio_port": 5004,
                       "video_port": 5006
                 }
            ]
       }
   }
}`

**Comment by lminiero** [comment]
This probaby depends on the use case. I guess in general it might be a useful feature, if not for monitoring to e.g. more or less easily forward a WebRTC stream to a component that translates it to RTMP, for instance. I'm not sure if this actually makes more sense as a separate plugin or not, although I guess the main purpose is to add a feature to an existing videoroom context which is reasonable.

That said, I understand your current API is temporary, but I'm not sure I'm comfortable with how it works. Where do all those other ports come from? What if you only want some users to be forwarded? IMHO it would be easier and more flexible to make this a per-publisher feature: that is, you can only request a specific publisher to be sent to some external component, which allows you to specify the exact address that needs to be reached; if more than one publisher or all of them need to be forwarded, iterate. I assume you're also thinking of ways to get rid of a forwarder, in case it's not needed any more for a publisher that keeps on publishing?

**Comment by Computician** [comment]
Right, it is in its infancy and not fully formed as of yet. This is the
reason for the question :). It very well could be a publisher specific
request.

I am trying to treat this kind of like recording and making it publisher
specific makes sense in that context.

**Comment by lminiero** [comment]
Closing as the feature has been submitted in #255
