### ISSUE TITLE
sofia-sip dead upstream (no code changes since 2011)

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#2092]
I am concerned that the SIP plugin links with sofia-SIP - a project which is dead upstream:
No code changes since 2011, and several forks carrying a range of patches for seemingly severe issues (see [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854846) and [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854845)).

Perhaps sensible to instead link with SIPre which is actively maintained?
I am unaware how involved or even sensible that is,
just notice that seemingly it was dropped because maintaining _two_ SIP plugins was unmaintainable
rather than because SIPre in particular was a bad choice.

**Comment by lminiero** [comment]
> Perhaps sensible to instead link with SIPre which is actively maintained?

Not going to happen, sorry. Tried it, and the learning curve was too high: I got to a point where it was mostly working, but was also very buggy (my fault, not the library's of course). I honestly have no intention of working on yet another SIP plugin (using whatever stack out there) or reviving that effort, especially since the one we have now is so full of features.

The library may be out of date, but it's used by projects like Freeswitch and dracthio as well, so it can't suck that much.

**Comment by jonassmedegaard** [comment]
Fair enough :-)

Perhaps it then makes sense to document which fork or "flavor" or Sofia-SIP you test against (if at all) - seems different patches are carried for both [FreeSwitch](https://github.com/signalwire/freeswitch/tree/master/libs/sofia-sip) and [drachtio](https://github.com/davehorton/sofia-sip) that you mentioned.

**Comment by lminiero** [comment]
I personally use the repo version from Fedora: not sure if that includes some of those patches or not. Anyone is free to install the flavour they want, though, we just link against what we find.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2020-04-21 12:17:13)
> I personally use the repo version from Fedora: not sure if that 
> includes some of those patches or not. Anyone is free to install the 
> flavour they want, though, we just link against what we find.

Thanks for those details.

I know each user is free to do whatever (no need to spell that out IMO), 
but I do think it would be helpful to mention e.g. in README.md the 
detail that you use the Sofia-SIP shipped with Fedora, because the lack 
of an active upstream for so long makes it particularly unclear which is 
known to work well.

(as Debian developer I will take a close look at the Fedora package to 
see if sensible to borrow patches from there)

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by alexamirante** [comment]
It's also worth saying that we've been using the ubuntu package in production for a long time. We usually don't do fancy stuff with SIP though, just place and receive calls.
