### ISSUE TITLE
Compile error against libnice

### ISSUE THREAD

**Issue by benwilber** [meetecho/janus-gateway#2095]
Compiling Janus at master (7bb3b867fc760ff2adabe8c396d589a21f3d1067) is producing an error:

```
janus-janus.o: In function `janus_info':
/tmp/janus-gateway-master/janus.c:329: undefined reference to `libnice_version_string'
janus-janus.o: In function `main':
/tmp/janus-gateway-master/janus.c:5184: undefined reference to `libnice_version_string'
```

Compiling Janus v0.9.2 (b6b32bb705f7769eadcc09a61b47bb397d76adca) does not produce this error.

I'm compiling with:

```
$ PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --prefix=/usr/local --enable-plugin-lua --enable-rest --enable-post-processing
```

OS: CentOS 7

libnice: [master](https://gitlab.freedesktop.org/libnice/libnice/-/commit/a9c2846a89c4e74efbd7ef59fcfe7ff05efb2c5e)
relevant log:

http://dpaste.com/3QNG8JR

This compiles against Janus v0.9.2, but not against master (7bb3b867fc760ff2adabe8c396d589a21f3d1067).

```
# whereis libnice
libnice: /usr/local/lib/libnice.so /usr/local/lib/libnice.la
```

**Comment by lminiero** [comment]
Probably caused by this: https://github.com/meetecho/janus-gateway/commit/b718a068cf6829a7d9be53098b2286714bef336d
This was a fix for gcc10, though, so we're not going to revert that. What compiler does CentOS have? My guess is that `version.c` has not been created yet when it gets to building `janus.c`, but it still shoudln't complain about undefined references until it goes to linking.

**Comment by benwilber** [comment]
Here's the GCC on CentOS 7

```
Last login: Wed Apr 22 20:26:01 on ttys002
bumblecopter3:~ benw$ cd Projects/trevelyan/
bumblecopter3:trevelyan benw$ vagrant ssh
Last login: Thu Apr 23 00:28:29 2020 from 10.0.2.2
[vagrant@localhost ~]$ ggc -v
-bash: ggc: command not found
[vagrant@localhost ~]$ gcc -V
gcc: error: unrecognized command line option ‘-V’
gcc: fatal error: no input files
compilation terminated.
[vagrant@localhost ~]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

I suspected that commit you linked was the likely culprit, but I wasn't able to determine exactly why that would cause the regression.  I'll be happy to provide more information to assist debugging if necessary.

**Comment by lminiero** [comment]
gcc 4.x is ancient.

**Comment by lminiero** [comment]
Try moving these two lines:

https://github.com/meetecho/janus-gateway/blob/master/Makefile.am#L132-L133

before the line with `janus.c` and recompile.

**Comment by lminiero** [comment]
As an alternative, put `version.c` before the two `cmdline` here:

https://github.com/meetecho/janus-gateway/blob/master/Makefile.am#L189

**Comment by lminiero** [comment]
In theory, both should ensure we try to build version.c first, and then janus.c

**Comment by benwilber** [comment]
Neither of those fixed it, but I did manage to find my problem.  I wasn't exporting the PKG_CONFIG_PATH when running `make`, only configure.  Peculiar that it still worked with v0.9.2 though.  Thanks for your help, I appreciate it.  This is excellent software.
