### ISSUE TITLE
heap-buffer-overflow in websockets transport write

### ISSUE THREAD

**Issue by agclark81** [meetecho/janus-gateway#2098]
We've observed a pattern of heap-buffer-overflow crashes when a large number of clients (1000+) use an already-attached videoroom session over websockets to join a room with ptype=subscriber for a specific feed where media has just started. This results in an unexpected crash of the service with "READ of size 4116 at 0x631002a1c7fd thread T13 (ws thread)". The size is consistent across crashes, but the memory offset varies.

The logs, with asan output, is here: https://pastebin.com/8LU9YREZ

The lws_write call is initiated by this:

https://github.com/meetecho/janus-gateway/blob/4fb459e5906177c4c7452ceb7ffd761286f54dba/transports/janus_websockets.c#L1191

It looks like we're getting a mutex lock on &ws_client->ts->mutex, but I'm not seeing anything else that might be manipulating the buffer outside of this lock, so I'm not sure what is going on.

Thanks!

**Comment by atoppi** [comment]
It is worth mentioning that you are running over HTTP/2:
```
#5 0x1499a2f29474 in lws_h2_frame_write (/lib64/libwebsockets.so.16+0x31474)
#6 0x1499a2f2e220 in rops_write_role_protocol_h2 (/lib64/libwebsockets.so.16+0x36220)
#7 0x1499a2f0a192 in lws_write (/lib64/libwebsockets.so.16+0x12192)
```

Test again with another protocol and/or latest libwebsockets (enabling debugging symbols).

**Comment by agclark81** [comment]
Good observation, Alessandro, We'll recompile with HTTP/2 disabled and enable debugging symbols and see if this reoccurs. It could just be some bugginess in the HTTP/2 implementation in lws.

**Comment by lminiero** [comment]
Did disabling HTTP2 in lws fix it? Can this be closed?

**Comment by agclark81** [comment]
Yes, I think we can safely close this issue for the time being. It has not re-occurred with HTTP/2 disabled, and we were unable to find an issue in the Janus code where the value of buffer could change, which suggests that the issue may be in lws. We'll submit something new if we re-encounter under these new conditions. Thanks!
