### ISSUE TITLE
Deadlock in janus_check_sessions

### ISSUE THREAD

**Issue by frk2** [meetecho/janus-gateway#210]
Hi,
I experienced a very predictable deadlock in janus_check_sessions: 337

The problem is quite obvious as this is a double lock on sessions_mutex. You end up with the following backtrace (and lock):
Thread 16 (Thread 0x7fc1c7fff700 (LWP 99981)):
#0  0x00007fc2118d3f2c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fc2118cf657 in _L_lock_909 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007fc2118cf480 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#3  0x000000000042a376 in janus_session_notify_event (session_id=3946447357, event=0x7fc1bc001b80) at janus.c:414
---Type <return> to continue, or q <return> to quit---
#4  0x0000000000429a87 in janus_check_sessions (user_data=0xaed1e0) at janus.c:337
#5  0x00007fc2133b9703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fc2133b8ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007fc2133b9048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007fc2133b930a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x0000000000429d39 in janus_sessions_watchdog (user_data=0xaed2d0) at janus.c:367
#10 0x00007fc2133ddf05 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fc2118cd182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007fc2115fa47d in clone () from /lib/x86_64-linux-gnu/libc.so.6

I believe the culprit is the following commit:
https://github.com/meetecho/janus-gateway/commit/8a7df51e0056f30dae1a4a99a7f3cbb79d08aeca

**Comment by lminiero** [comment]
Good catch, I'll fix it.
