### ISSUE TITLE
HMAC Auth

### ISSUE THREAD

**Issue by vhanadium** [meetecho/janus-gateway#2103]
Hi guys,

I just installed a Janus Gateway on a centOS linux and everything works fine except for the authentication.

The configuration of auth is:
#api_secret = "janusrocks"
token_auth = true
token_auth_secret = "kevin"

Then I generated this key with PHP:
1619283016,janus,janus.plugin.echotest:MmUzN2VlNTY5N2E1MGNkYWY5NjI3OGM4MDI4MmQ2Y2UwODliZDY0Yw==

I modified your echo test page to add the token on line 91 just after the comment about the token auth by adding this:
token: "1619283016,janus,janus.plugin.echotest:MmUzN2VlNTY5N2E1MGNkYWY5NjI3OGM4MDI4MmQ2Y2UwODliZDY0Yw==",

The server keep on refusing access with 403 error:
{janus: "error", transaction: "a8u52lIc1Jpy", error: {code: 403, reason: "Unauthorized request (wrong or missing secret/token)"}}

if anyone could provide some insight this is driving me mad.

TY, regards.

**Comment by lminiero** [comment]
HMAC is only available for the VideoRoom right now.

**Comment by vhanadium** [comment]
Ok so should we use anything else we need to use ADMIN/MONITOR token system then ?

**Comment by lminiero** [comment]
https://janus.conf.meetecho.com/docs/auth

**Comment by vhanadium** [comment]
I know I read the documentation before asking, is the "Stored token based authentication mechanism" works on everything or just the VideoRoom too plz ?

**Comment by vhanadium** [comment]
Well I tried in the VideoRoom test html file same configuration and I get the same message:

{janus: "error", transaction: "PQjfdYEGNGk1", error: {code: 403, reason: "Unauthorized request (wrong or missing secret/token)"}}

**Comment by lminiero** [comment]
Those work everywhere, signed tokens only on VideoRoom. I'll make that clearer in the docs.

**Comment by lminiero** [comment]
> Well I tried in the VideoRoom test html file same configuration and I get the same message:

You're doing something wrong: `janus.js` supports tokens natively. https://janus.conf.meetecho.com/docs/JS

That said, ask these questions on the [group](https://groups.google.com/forum/#!forum/meetecho-janus), not here. Github is only for code issues.
