### ISSUE TITLE
WebRTC error... "getUserMedia not available"

### ISSUE THREAD

**Issue by vamsiduranc** [meetecho/janus-gateway#2105]
Hello,

I have setup Janus-gateway in Azure cloud infrastructure and installation was successful. 

- I was able to start Janus server. 
- I was able to access Janus Demo Pages from Internet
- I have also configured firewall as shown in below screenshot.

![image](https://user-images.githubusercontent.com/32363189/80278967-1df85400-8718-11ea-899f-48bcc26317f7.png)

When I do a echo test i see ``` WebRTC error... "getUserMedia not available" ``` error message.

![image](https://user-images.githubusercontent.com/32363189/80278892-81ce4d00-8717-11ea-9528-f4258861c9b4.png)

I am new to this deployment, can you please help me in resolving the issue? Appreciate your help. Thank You!

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by neilyoung** [comment]
@vamsiduranc I think the reason might caused by this
https://www.fxsitecompat.dev/en-CA/docs/2019/getusermedia-can-no-longer-be-used-on-insecure-sites/
