### ISSUE TITLE
Timeout expired for session XXX and "Ending watchdog mainloop" never ends

### ISSUE THREAD

**Issue by ldenoue** [meetecho/janus-gateway#211]
After I get this timeout, I'm unable to stop Janus.
I get:
[WARN] [1751251754] Didn't receive audio for more than a second...
[WARN] [1751251754] Didn't receive video for more than a second...
Timeout expired for session 403831024...

^CStopping gateway, please wait...
Ending watchdog mainloop...

And it never stops.
Possible deadlock somewhere?

Laurent

**Comment by lminiero** [comment]
Most likely related to #210

**Comment by ldenoue** [comment]
indeed, it works now, grazie Lorenzo!
