### ISSUE TITLE
janus ignore candidate gived by api call

### ISSUE THREAD

**Issue by michelepra** [meetecho/janus-gateway#2111]
I'm using janus 0.6.3 with NoSIP plugin with good results.
I try to upgrade from 0.6.3 to 0.9.2 without change external code that control janus and from some test i find that recent version doesn't handle candidate as before.
Ice phase always fail, didn't receive remote candidate from janusevent, and in log i always see 
_Got a mid='audio' candidate (index 0) but we're bundling, ignoring..._
or
_Got a mid='video' candidate (index 1) but we're bundling, ignoring..._

After a while i find that there's a change in how janus manage candidate

https://github.com/meetecho/janus-gateway/blob/c3a338ac7b8206c3183d6e971ced621707de6df0/ice.c#L790

I try to restore this line as before `if(sdpMLineIndex > 0)` and this did the trick, janus start to work as expected, event is coming and ice phase never failed.

This change is bad for janus core or i find a bug inserted by this commit https://github.com/meetecho/janus-gateway/commit/dd31422278e0aa267d3156320778d69577607fbb??

**Comment by lminiero** [comment]
You're likely doing something wrong. Yes, we ignore all candidates with an mline index higher than 0, and that's done on purpose, since everything is bundled now. Closing, API question so belongs to the [group](https://groups.google.com/forum/#!forum/meetecho-janus).

**Comment by michelepra** [comment]
> You're likely doing something wrong. Yes, we ignore all candidates with an mline index higher than 0, and that's done on purpose, since everything is bundled now. 

From janus log i see that recent tag ignore all candidates, also with mline = 0

I think because `stream_mid ` exist. This element is construct by parsing sdp but as trickle ice wants i send candidate after sdp parsing end.

In particular with NoSIP plugin i do this step

1. Generate session
2. Generate handle of NoSIP plugin for this session
1. call "generate" to this handle with JSEP SDP 
2. after generate end call "trickle" for every candidate
3. when gathering complete call "trickle" with completed attribute

I think ther's nothing wrong in this procedure
