### ISSUE TITLE
Server crash using Videoroom plugin with status ABRT

### ISSUE THREAD

**Issue by DaGLiMiOuX** [meetecho/janus-gateway#2113]
I've found a server crash in Janus gateway server using Videoroom plugin after a function called `free()` reported `invalid size`.

I'll post a pastebin to let you track the error: [pastebin](https://pastebin.com/c9zCvy64)

I cannot find a way to reproduce it, but I'll do my best as this was a testing server and we were not doing these tests.

Br,
D.

Using tagged version 0.9.3

**Comment by atoppi** [comment]
It looks like we are already discussing this in #2097

**Comment by DaGLiMiOuX** [comment]
Thanks you for de information. I'll keep an eye on it as there is no much I can do with it or even create a PR. Not so familiar with C...

Br,
D.

**Comment by DaGLiMiOuX** [comment]
I did a test with multiple devices.

Is it possible that `free()` is being called when user closes its tab? The test we were doing is connecting into a room a Windows PC and an iOS 13 device (iPhone 11). Maybe is having some troubles with the session closing with `sendBeacon` function? I mean, if janus is receiving the request and when the `free()` function is being called, is there something related that is making it crash. I don't know what it does, but sounds like is trying to free the connection/session with the server or something like that and is causing the error.

I'm sorry that I cannot provide any further information. Btw, I will try with a more debugging level in janus instance and see if I can see something more useful.

Br,
D.

**Comment by lminiero** [comment]
https://janus.conf.meetecho.com/docs/debug

**Comment by DaGLiMiOuX** [comment]
Sorry for the late reply and not providing any debugging. We're so busy at this moment in our work... I've updated to 0.9.4 and seems fixed. Btw, I will take a closer look and reopen with dumps if required.

Thanks for your work.

Br,
D.
