### ISSUE TITLE
maybe suport nng as replacement for nanomsg

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#2117]
nanomsg has had no new release since October 2018, and no code changes at Github since July 2019. Their homepage prominently states this:
> This project has largely been superceded by the nng project.

[nng](https://github.com/nanomsg/nng) states this:
> This project offers both wire compatibility and API compatibility, so most nanomsg users can begin using NNG right away.
>
> Existing nanomsg and mangos applications can inter-operate with NNG applications automatically.

Seems relevant to explore support for nng in addition to (or replacement for) nanomsg.

**Comment by lminiero** [comment]
Not planning to do that, sorry. If anyone wants to take the challenge, we welcome pull requests.

**Comment by lminiero** [comment]
@jonassmedegaard FYI, I played a bit with this in the weekend. Unlike their claims, they changed quite a lot in NNG: the compatibility layer itself has many constraint, so isn't worth the trouble. As such, I decided to try updating the code to just use NNG itself, instead: it was not an easy task, and compiles correctly now, but still doesn't seem to work.

The main change is in their asynchronous management: they got rid of POSIX APIs, for a much more convoluted and obscure (to me) AIO mechanism. While they provide you with a way to get a "fake" descriptor associated to their sockets that you can use in a poll yourself (unlike the `nn_poll` they had previously), it doesn't seem to work, or at least not consistently. The "writable" part in particular seems broken. Refactoring the whole plugin to use their new AIO stuff seems way too much work for the trouble, especially considering I didn't find good documentation on how it's supposed to work.

More importantly, it doesn't look like there are many NNG bindings out there. I wanted to use a simple nodejs application for testing, and the only NNG binding available is an unofficial one that won't even compile on newer (>= 12) nodejs deployments. Not sure about bindings to other languages, but the lack of reliable nodejs bindings is kind of a big deal to me. I tried to write a barebone NNG application in C to talk to, but of course if I'm doing something wrong in the plugin code, I'm making the same mistakes there, so there's no way for me to know what I should fix or how.

As such, while I can share the effort I worked on so far as a (very) WIP, I don't think it would be merged anytime soon anyway.

**Comment by jonassmedegaard** [comment]
Oh my.  Sorry I lured you down that rabbit hole :-(

Thanks for sharing the efforts and criticism.

**Comment by lminiero** [comment]
Nothing to be sorry about! I wasn't aware of NNG, and we will indeed need to support it sooner or later, so thanks for the heads up on that. I'll open a PR with the current changes: maybe someone with better knowledge than me will be able to see what's wrong with it, so that we're ready when we do need to merge it.

**Comment by lminiero** [comment]
See PR above. Updating the label for this issue.

**Comment by lminiero** [comment]
Closing as we closed the PR as well.
