### ISSUE TITLE
Error gathering candidates...

### ISSUE THREAD

**Issue by wheresjames** [meetecho/janus-gateway#2119]
I'm getting the following error while using full-trickle + coturn.  Works with half-trickle.

> (process:64): libnice-CRITICAL **: 11:26:57.197: nice_agent_gather_candidates: assertion 'NICE_IS_AGENT (agent)' failed
> [ERR] [ice.c:janus_ice_outgoing_traffic_handle:3992] [2520865549608866] Error gathering candidates...

Fails: 0.9.3 and master
Works: <= 0.9.2
Other info: ubuntu:18.04, libnice:0.1.16|master, coturn:master

**Comment by lminiero** [comment]
What do you mean by coturn: are you configuring TURN in Janus? Unless you *really* need it, it's discouraged: https://janus.conf.meetecho.com/docs/FAQ#turn
If you say it works with older versions, try finding the commit that breaks it for you using `git bisect`.

**Comment by lminiero** [comment]
Added an additional check to avoid the error (which is harmless anyway): https://github.com/meetecho/janus-gateway/commit/8e56d7849afeb0236690cc1f4bd282e5ad6f526a

**Comment by wheresjames** [comment]
Thanks for the tip on git bisect.  First time I've used it.  
The error was introduced here https://github.com/meetecho/janus-gateway/commit/7aae63518efe96374a94306ed4d3bc00c2a45e4a
I'll try adding the check you posted and see what happens.

**Comment by wheresjames** [comment]
So the error didn't have anything to do with the issue I was having, tunnel vision on my part.  It seems things were just stalling after pushing the request  to start candidate gathering.  A call to g_main_context_wakeup() after fixed it for me.

I submitted a PR.
https://github.com/meetecho/janus-gateway/pull/2121/commits/98553756d557ca78f17f3d548b8c7a9548ef510f
