### ISSUE TITLE
Cannot build versions past 0.9.2 without libsrtp 2.3.0 but 2.3.0 causes SRTP error

### ISSUE THREAD

**Issue by austinmarkus** [meetecho/janus-gateway#2123]
Hi,

Thanks again for your amazing product. I've come across an issue building your latest versions. Code on or before 0.9.2 works fine. Build environment is Ubuntu 18.04 with these additional libs from source libwebsockets 3.2-stable, libmicrohttpd 0.9.62, libnice 0.1.16, and usrsctp master.

If I build 0.9.3 or master with libsrtp 2.2.0 I get the error:
CCLD     janus
janus-dtls.o: In function `janus_dtls_srtp_incoming_msg':
/home/xxxxxx/build/janus-gateway-0.9.3/dtls.c:861: undefined reference to `srtp_crypto_policy_set_aes_gcm_256_16_auth'

If I upgrade to libsrtp 2.3.0, Janus builds without issue however I get an SRTP error when I try to stream (tested on audioBridge and videoRoom plugins). Error:

[Wed Apr 29 20:41:40 2020] [ERR] [dtls.c:janus_dtls_srtp_incoming_msg:923] [7032191712486157] Oops, error creating inbound SRTP session for component 1 in stream 1??
[Wed Apr 29 20:41:40 2020] [ERR] [dtls.c:janus_dtls_srtp_incoming_msg:924] [7032191712486157]  -- 1 (srtp_err_status_fail)

Full log of error here: https://pastebin.com/V4dDJjh3

Let me know if you need any additional information or logs.

**Comment by lminiero** [comment]
https://janus.conf.meetecho.com/docs/FAQ.html#aesgcm
