### ISSUE TITLE
Janus HTTP transport locking issue

### ISSUE THREAD

**Issue by bolsote** [meetecho/janus-gateway#2128]
After rolling out a Janus version targeting 0.9.3 (plus a few additional commits from `master`) we realised some of our instances were freezing, requiring a full service restart.

Upon further investigation we found some interesting results. When comparing the stack traces of the threads associated with the HTTP transport in both a frozen instance and a working one we realised the former was stuck at a `g_mutex_lock` call:

```
#0  0x00007ffa611b64d9 in syscall () at /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffa62e5a2dc in g_mutex_lock_slowpath (mutex=0x7ffa24009d38) at /build/glib2.0-xkQkqE/glib2.0-2.48.2/./glib/gthread-posix.c:1312
#2  0x00007ffa53655ddc in  () at /usr/lib/x86_64-linux-gnu/janus/transports/libjanus_http.so
#3  0x00007ffa5343bb22 in MHD_connection_handle_idle (connection=connection@entry=0x7ffa240250e0) at connection.c:3640
#4  0x00007ffa5343cc98 in call_handlers (con=con@entry=0x7ffa240250e0, read_ready=<optimised out>, write_ready=<optimised out>, force_close=<optimised out>) at daemon.c:1163
#5  0x00007ffa534415c0 in MHD_epoll (daemon=daemon@entry=0x55ddff7fe800, may_block=may_block@entry=1) at daemon.c:4265
#6  0x00007ffa5344256a in MHD_polling_thread (cls=0x55ddff7fe800) at daemon.c:4427
#7  0x00007ffa614866ba in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007ffa611bc41d in clone () at /lib/x86_64-linux-gnu/libc.so.6
```

In this particular instance the debug symbols for Janus were not available. We were not able to reproduce the issue in an instance with them installed (only due to the difficulty of triggering it on demand).

From the `libmicrohttpd` section of the stack trace we can conclude the culprit is the callback triggered from here:

https://github.com/Karlson2k/libmicrohttpd/blob/v0.9.59/src/microhttpd/connection.c#L3640

A good candidate for this is `janus_http_request_completed`, which operates on two separate locks, `session->mutex` and `session->mutex`. At this point we have not been able to trigger this issue in an instance with enough visibility to further narrow down our diagnostic.

We did not suffer from this problem in older versions of Janus (0.8.x line), so we suspect this might have been introduced by this refactoring: https://github.com/meetecho/janus-gateway/pull/1173

If we manage to hit the problem in an instance with debug symbols we will post further information.

**Comment by alexamirante** [comment]
Already fixed in https://github.com/meetecho/janus-gateway/commit/436ccccabf100f9f454ccaf92afcf02bb7358aa0
