### ISSUE TITLE
Streaming plugin - renegotiation causing same session multiple times in mp->viewers 

### ISSUE THREAD

**Issue by TomFFF** [meetecho/janus-gateway#2129]
We see a lot of SRTP/SRTCP errors in our logs for some streaming handles.

We think it caused by a 'double watch' to the streaming plugin.

Version used : master branch commit 03e0f63c8037fc12ba54f3d43d976a7628a05b63

If you send a `watch` for a mountpoint that you are already viewing, the session will be added again in `mp->viewers` (and that's causing a lot `srtp_err_status_replay_fail` errors because we are trying to send each packet multiple times to the viewer)

There is already a check on `janus_streaming.c:4564` to see if it's a watch for the same mountpoint 
`if(session->mountpoint != mp) {`
but in   else `janus_streaming.c:4599` we go to done : 

```
janus_refcount_decrease(&mp->ref);
JANUS_LOG(LOG_VERB, "Request to update mountpoint/stream %s subscription (no restart)\n", id_value_str);
session->sdp_version++;	/* This needs to be increased when it changes */
goto done;
```

And in done `janus_streaming.c:4820` we add the session again in the viewers : 
`mp->viewers = g_list_append(mp->viewers, session);`

After this the session is 2 times in mp->viewers resulting in the SRTP/SRTCP errors

It's easy to reproduce by sending the  `watch` call 2 times.

**Comment by lminiero** [comment]
Thanks, I'll check and work on a fix in case.

**Comment by lminiero** [comment]
This commit should fix the issue, or at least it does for me. Please let me know if you can still replicate it somehow.

**Comment by TomFFF** [comment]
Thanks for again the quick fix !

I can't reproduce it anymore and didn't noticed the  `srtp_err_status_replay_fail` error with real clients since the fix.
