### ISSUE TITLE
Huge error log from ice.c

### ISSUE THREAD

**Issue by tomnotcat** [meetecho/janus-gateway#2132]
I update janus to v0.9.3, found janus output huge error log sometimes like below:
[ERR] [ice.c:janus_ice_outgoing_traffic_handle:4332] [5367713818582052] ... only sent -1 bytes? (was 292)

The log amount is very huge, about 1000+ per second, But just lasts about 5 seconds.

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
