### ISSUE TITLE
Cannot start secure websockets if boringssl is used

### ISSUE THREAD

**Issue by xadhoom** [meetecho/janus-gateway#2138]
With latest version janus-gateway 0.9.4 (not tried with previous ones) was trying out boringssl support (using latest chromium-stable branch of it), but cannot start secure websockets anymore, only standard ones.

We use also https transport, which works ok.

Compilation does not issue any warning and detects boringssl correctly. Disabling boringssl makes it work again.

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by lminiero** [comment]
As a side note, enabling secure WS in Janus itself is not recommended. We recommend using proxies like nginx/httpd for the purpose: https://janus.conf.meetecho.com/docs/deploy

**Comment by xadhoom** [comment]
Ok, will try to dig forum, but honestly did not find any reference between boringssl and secure websockets. Unless I must test with master :D

**Comment by lminiero** [comment]
Pointing to the forum as it's not a code issue, so doesn't belong here. My guess is that it's most likely a conflict between the ssl library Janus uses (BoringSSL in your case) and the one lws is linked to.
