### ISSUE TITLE
Long poll connection still open after destroy

### ISSUE THREAD

**Issue by TomFFF** [meetecho/janus-gateway#2139]
Version used : master commit 0f6849e8cb58194275cf3f21f3161b01f0432ed9

In the current version the long poll connection doesn't close when you destroy the related session. I did also a test with and old version of janus (v0.7.3) and in that version the poll connection also stops when you destroy the session

Test script : 
```
#!/bin/bash
date;
SESSION_ID=`curl --data '{ "janus": "create", "transaction": "tester.py"}' http://127.0.0.1:8088/janus 2>&1 | grep 'id' | sed 's/.*: //'`;
echo "Session created $SESSION_ID";
curl http://127.0.0.1:8088/janus/$SESSION_ID &
sleep 1;
DESTROY=`curl --data '{ "janus": "destroy","transaction":"test-destroy"}' http://127.0.0.1:8088/janus/$SESSION_ID  2>&1 | grep 'janus'`;
echo $DESTROY;
wait < <(jobs -p)
date;
echo "all finished"
```

Output on current master (so it takes 30seconds to finish): 

```
Tue May  5 13:23:57 CEST 2020
Session created 1199016583816231
"janus": "success",
{
   "janus": "keepalive"
}Tue May  5 13:24:27 CEST 2020
all finished
```

Output on v0.7.3

```
Tue May  5 13:20:07 CEST 2020
Session created 2130358450387072
"janus": "success",
{
   "janus": "keepalive"
}Tue May  5 13:20:08 CEST 2020
all finished
```

In the old code there  was a check to break the poll : 

https://github.com/meetecho/janus-gateway/blob/e0ad1ff9c23592c18aa662301c6d19f12a38b6da/transports/janus_http.c#L1817-L1819

Since the switch to the single threaded version this is part is changed ofcourse.

In the current version this code is triggered to cleanup the long poll queue, but maybe it can also try to close the active poll connection ?

https://github.com/meetecho/janus-gateway/blob/e95f8bc5e1226aff29d07e9a775499cbb1fc1816/transports/janus_http.c#L1079-L1087

**Comment by lminiero** [comment]
Probably a result of the fixes we made in #2075 to fix the crashes. To be honest, if it's not crashing now this is quite low priority for me, especially now that the HTTP code is much more stable. If you can come up with a fix, I'll gladly review a pull request.

**Comment by TomFFF** [comment]
Yes I understand that it's not a big issue, but we had some client code that was more or less depending on it. 

I fixed it for now by sending a fake keepalive in `janus_http_session_over` like this :

```
@@ -1081,6 +1081,11 @@ void janus_http_session_over(janus_transport_session *transport, guint64 session
                timeout ? "has timed out" : "is over",
                claimed ? "but has been claimed" : "and has not been claimed", session_id);
        /* Get rid of the session's queue of events */
+       json_t *root = json_object();
+       json_object_set_new(root, "janus", json_string("keepalive"));
+       json_object_set_new(root, "session_id", json_integer(session_id));
+       janus_http_send_message(transport,NULL, FALSE, root);
```
but I can imagine that you would like a better fix, but I don't have enough experience with c code to fix in a better way :-)

**Comment by lminiero** [comment]
Very likely fixed in https://github.com/meetecho/janus-gateway/commit/88df9449ac54f27afa29672cf092fac65a695c29
