### ISSUE TITLE
SIP Plugin, INVITE with SDP including SRTP audio option Fails

### ISSUE THREAD

**Issue by shrhoads** [meetecho/janus-gateway#214]
I was doing some testing with the SIP plugin, and a Polycom VVX 410, and in the configuration on the polycom SIP phone, if you include SRTP it confuses the Janus SIP plugin and calls from the SIP phone to WebRTC fail, but calls in the other direction are OK.  To fix this I disabled the Offer SRTP option in the SIP phone, but thought I would document it here in case it's an interop issue.  Here is the SDP in question:

```
[nua_i_invite]: 100 Trying
Someone is inviting us in a call:
v=0
o=- 1429995836 1429995836 IN IP4 192.168.3.9
s=Polycom IP Phone
c=IN IP4 192.168.3.4
t=0 0
a=sendrecv
m=audio 2252 RTP/SAVP 9 102 0 8 18 127
a=crypto:8 AES_CM_128_HMAC_SHA1_80 inline:dEqpO7RgmMamQxQ8S8WFAVE5FOaOEsexwRz74Ql5
a=rtpmap:9 G722/8000
a=rtpmap:102 G7221/16000
a=fmtp:102 bitrate=32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:127 telephone-event/8000
m=audio 2252 RTP/AVP 9 102 0 8 18 127
a=rtpmap:9 G722/8000
a=rtpmap:102 G7221/16000
a=fmtp:102 bitrate=32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:127 telephone-event/8000
  >> Media connection:
       192.168.3.4
  >> Media lines:
       Audio: 2252
       Media connections:
       Media RTP maps:
         [9] G722
         [102] G7221
         [0] PCMU
         [8] PCMA
         [18] G729
         [127] telephone-event
       Media attributes:
       Audio: 2252
       Media connections:
       Media RTP maps:
         [9] G722
         [102] G7221
         [0] PCMU
         [8] PCMA
         [18] G729
         [127] telephone-event
       Media attributes:
Pushing event to peer: {
   "sip": "event",
   "result": {
      "event": "incomingcall",
      "username": "5005"
   }
}
[1226159507] Audio has been negotiated
[ERR] [janus.c:janus_handle_sdp:3398:] [1226159507] More than one audio line? only going to negotiate one...
```

If it's out of scope for Janus feel free to close the issue :).  Thanks.

**Comment by lminiero** [comment]
The problem is not SRTP, but the multiple audio lines. The SIP plugin (as Janus at the moment) only supports one media line per type. I guess that disabling SRTP your phone simply removes the additional m-line for that and only keeps the unencrypted one.

**Comment by shrhoads** [comment]
Should the SRTP one work (I assume not)?  Should the janus audio choosing logic look for the unencrypted one and choose that one to process?

**Comment by lminiero** [comment]
No, the SIP plugin does not support SRTP, just plain RTP as of now. The plugin/core should reject the SRTP one (m=audio 0) and only handle the other one, but as we said we don't support multiple media lines of the same type (in this case audio).

**Comment by shrhoads** [comment]
Ok will close the issue, it's on the SIP agent's responsibility to just send one audio candidate.  Thanks.
