### ISSUE TITLE
SDP Parse Error No webrtc-datachannel token

### ISSUE THREAD

**Issue by dariogomez** [meetecho/janus-gateway#2140]
Hi everybody,

I'm using janus 0.9.5 on ubuntu 18.04 server with nginx proxy.

I've recieved this message error when I what to start the echo test or the video call example only on firefox.

> WebRTC error: DOMException: "SIPCC Failed to parse SDP: SDP Parse Error on line 54:  No webrtc-datachannel token in m= media line, parse failed.
" janus.js:3072:9
    webrtcError 

I'm using Firefox 75.0 (64-bit) on mac and Firefox 72.0.2 on ubuntu desktop.

Thanks in advance!

**Comment by lminiero** [comment]
Not a code issue, so doesn't belong here.
https://groups.google.com/forum/#!forum/meetecho-janus
