### ISSUE TITLE
Demos broken in Firefox behind NAT

### ISSUE THREAD

**Issue by arctica** [meetecho/janus-gateway#2148]
Hi, thanks for your great work on Janus. I appreciate the philosophy behind it.

That being said I'm having problems getting the demos, especially the Videoroom, to work in Firefox 76 under MacOS when behind NAT.

I opened two browsers: Safari and Firefox and joined the videoroom (on the official janus website) in both. In Safari I can see the local as well as the remote video. In Firefox however I can see only the local video and not the stream from Safari.

There could be two issues: Safari not being able to publish or Firefox not being able to receive. I believe it is the latter as the Safari console shows no errors but in Firefox there is a prominent error about ICE failing.

Full console log here: https://pastebin.com/raw/7jDJFkas

I've tried most of the others including streaming and textroom and they all failed in the same way. Interestingly the Echotest demo worked! I am not sure what makes this one special.

A friend tried with Firefox 76 on Ubuntu and it worked fine, he is not behind NAT though.

Please let me know what further information would be helpful to dig deeper into the issue.

Thanks.

**Comment by lminiero** [comment]
https://groups.google.com/forum/m/#!forum/meetecho-janus
