### ISSUE TITLE
Janus segfaults sometimes when destroying RTP mountpoint

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#215]
Steps to reproduce:

1. Start Janus
2. Create a streaming mount-point for an rtp (live) stream via API.
3. Destroy that mount-point via API.

Console output:
[546012789] There's a message for JANUS Streaming plugin
Handling message: {
   "request": "destroy",
   "id": 35253947,
   "secret": "*******"
}
Request to unmount mountpoint/stream 35253947
[35253947] Leaving streaming relay thread
Segmentation fault (core dumped)

**Comment by lminiero** [comment]
Yep, I guess we're not unhooking the viewers from the mountpoint correctly when this happens. I'll look into it, although I can't replicate it. Do you have a stacktrace to provide (via pastebin) of when it happens?

**Comment by arjenveenhuizen** [comment]
Sure, here you go: http://pastebin.com/bEPGb20i

Hope it helps!

**Comment by lminiero** [comment]
Let me know if this improves things: this patch removes all listeners before destroying the mountpoint, and also notifies each one of them of the stream being stopped.

**Comment by arjenveenhuizen** [comment]
Unfortunately, that did not help. The segfault seems to happen less frequent but it is definately still there. If it is of any help: just after destroying the mount points one after the other simultaneously (two in my cases), I disconnect the websocket connection from the client side.

**Comment by lminiero** [comment]
If what you want is to stop streaming, you can also use the "disable" request in the plugin, which will stop broadcasting that mountpoint. This way, in your application logic, you can have your users detach from the mountpoint and when almost everybody's gone, actually destroy the mountpoint. A bit hacky but it might help for the moment until this is fixed for good.

**Comment by arjenveenhuizen** [comment]
Yes, that could be a solution as well. 

What I actually would like to achieve is to:
0. Start Janus
1. Start my application
2. Create an rtp mount point.via API
3. Start serving an A/V stream on the UDP ports associated to that rtp mount point
4. Tear down the mount point, disconnecting any client and making sure that no one is using the UDP ports.
5. Restart at step 1 without stopping Janus

My work around consists of:
0. Start Janus,
1. Start my application
2. List all active mount points and check if my UDP ports are already associated to any of the mount points (I modified the "list" response of the plugin to include that data)
3a. If already available, communicate the already created mount point id to the clients
3b. If not available, create the mount point
3. Stop my application, but keep Janus running
4. Restart at step 1 while Janus can keep on running or can be shut down.

Anyway, hope it gets fixed permanently soon!

**Comment by lminiero** [comment]
Is it still happening with the latest Janus? If so, can you share an updated backtrace?

**Comment by arjenveenhuizen** [comment]
Just tested it and it looks like it no longer segfaults with GIT HEAD. I will keep an eye on it but for now feel free to close it.

**Comment by arjenveenhuizen** [comment]
Just tested it and it looks like it no longer segfaults with GIT HEAD. I will keep an eye on it but for now feel free to close it.

**Comment by lminiero** [comment]
Cool, thanks for the info! Feel free to reopen in case.
