### ISSUE TITLE
[question] play multicast RTP video stream on the web browser

### ISSUE THREAD

**Issue by webrtcccccc** [meetecho/janus-gateway#2153]
I have a RTP streaming question. A iot device is continued sending videos to the local network, it use protocol is RTP(Not SRTP), and the ip destination is 239.255.1.1(multicast), so every device in the local area network can receive these RTP video package. I have the video Session Description Protocol file, so i can play the video use ffmpeg on the computer successfully. Now i want to use the web browser to play the multicast RTP video stream in the local area network, is there a solution that can provide me with reference, thank you very much!

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
