### ISSUE TITLE
Segmentation fault after Firefox connection

### ISSUE THREAD

**Issue by maxboehm** [meetecho/janus-gateway#2154]
Janus crashes quite constantly (app. 80%) via Firefox by joining a textroom. I've built Janus today from master.

Janus-Log: https://pastebin.com/raw/ZL7KVMDg
GDB stacktrace: https://pastebin.com/raw/HTg7WPzA
Script for compiling Janus: https://pastebin.com/bApyNvP2

We think the following steps lead to this crash:
- Initialize the Janus library
- Attach to text room plugin
- Setup the DataChannel ({ "request": "setup" })
- createAnswer (only using datachannels)
- Send {"message": { "request": "ack" }, jsep: jsep}

Result: Often (app. 80%) causes Janus crashes when connecting with Firefox (Safari as well, Chrome not yet)

If you need more information, please let me now. 

Thank you,
Max

**Comment by maxboehm** [comment]
> 2650    netinet/sctputil.c: No such file or directory.
Uff..

**Comment by maxboehm** [comment]
I have added the libdir parameter. But Janus keeps crashing.

I have found another weird behaviour. Janus keeps crashing below log level 5. As soon as I am reconfiguring janus (via admin api) to log level 5, Janus stops crashing

**Comment by lminiero** [comment]
Please provide a libasan trace: https://janus.conf.meetecho.com/docs/debug

**Comment by maxboehm** [comment]
https://pastebin.com/raw/RmSiyrAv

Please note: usrsctp is now built from the current master

**Comment by atoppi** [comment]
Hi @maxboehm,
does the same happen with OpenSSL in place of BoringSSL ?

**Comment by lminiero** [comment]
Seems to be crashing deep within usrsctp: not sure there's anything we can do to help. TextRoom definitely works fine here with Firefox. Have you tried our online demos?

**Comment by atoppi** [comment]
According to libasan, something has been nulled and caused a SIGSEGV.
Inspect the core dump with gdb and try to understand which variable has been set to null.
Anyway, like @lminiero said, this looks like a crash in the library, not strictly related to Janus.

**Comment by maxboehm** [comment]
Hi @atoppi : I will check that.
Does it make sense to upload the dump? I have no experience in debugging C... 
@lminiero : I can't conclude fo rsure, that we are doing everyhing right on the frontend side. Nevertheless, I guess it should not lead to a crash. The online demos are working!

**Comment by atoppi** [comment]
No, we can not debug binary dumps coming from other machines.

**Comment by maxboehm** [comment]
Hm. I've just switched to OpenSSL, same behaviour: https://pastebin.com/raw/LzYVA4iD

Thank you so far!

I will try two things
1. Debug via gdb (By accident, you do not have a link to an appropriate beginner guide?)
2. Play with versions & checkout dates of janus as well as usrsctp. Hopefully I can determine the breaking change.

**Comment by maxboehm** [comment]
Obviously there was a bug in usrsctp between 2020-05-11 13:37 and 2020-05-16 13:37. Thanks to duplicating libs I managed it somehow to miss that.

Closing the issue... 

Have a nice weekend :-)
