### ISSUE TITLE
janus server  Arm processor

### ISSUE THREAD

**Issue by gushenjie** [meetecho/janus-gateway#2159]
Does the janus service support servers with arm processors, and does the system support unbuntu or centos

**Comment by RSATom** [comment]
https://snapcraft.io/janus-gateway
I've used it on Raspberry Pi...

**Comment by RSATom** [comment]
And I think questions like this better ask on https://groups.google.com/forum/m/#!forum/meetecho-janus

**Comment by lminiero** [comment]
@RSATom it's bold pretty much everywhere, and it's also in the template when you open a new issue... I'm afraid most people just don't read it :wink:
