### ISSUE TITLE
Not able to View H.264 Stream

### ISSUE THREAD

**Issue by munishmahajan** [meetecho/janus-gateway#2160]
Running gstreamer with following command - gst-launch-1.0 filesrc location=../recordings/20181025_170123.mp4 ! qtdemux  ! video/x-h264 ! h264parse !rtph264pay ! udpsink host=10.0.16.50 port=8004 sync=true
In Stream Test, it shows bytes receiving but does not play video. Using h264 parser at streaming side.
Am i using wrong muxer?

Thanx,
Munish

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
