### ISSUE TITLE
compiling issue ... have I forgotten something?

### ISSUE THREAD

**Issue by htc1977** [meetecho/janus-gateway#2162]
Hello,

I just downloaded and tried to build the latest Janus Gateway like it is mentioned in your README.
After cloning the git and executing autogen.sh and configure, I wanted to compile it via make, but I get this error message.

```
[...]
  CC       janus_cfgconv-version.o
  CCLD     janus-cfgconv
  CC       transports/libjanus_websockets_la-janus_websockets.lo
transports/janus_websockets.c: In function ‘janus_websockets_init’:
transports/janus_websockets.c:535:11: error: ‘struct lws_context_creation_info’ has no member named ‘ws_ping_pong_interval’
  535 |    wscinfo.ws_ping_pong_interval = pingpong_trigger;
      |           ^
make[2]: *** [Makefile:2276: transports/libjanus_websockets_la-janus_websockets.lo] Error 1
make[2]: Leaving directory '/opt/janus-gateway'
make[1]: *** [Makefile:3261: all-recursive] Error 1
make[1]: Leaving directory '/opt/janus-gateway'
make: *** [Makefile:1499: all] Error 2
```

Sorry in advanced, maybe I'm too dumb for this, but I really don't know how to debug and fix this.

Any help appreciated.

**Comment by mattcamp** [comment]
I also hit this when using the master branch of libwebsockets.

If you check out the v2.4-stable branch then janus compiles ok.

**Comment by htc1977** [comment]
thanks @mattcamp , that fixed my libwebsockets error, too.

**Comment by lminiero** [comment]
Apparently that property was removed in 4.x: https://github.com/warmcat/libwebsockets/commit/7f69714602c9339a9fa9302311a680fd084558b1
The new way to do that is specified here: https://github.com/warmcat/libwebsockets/blob/master/READMEs/README.lws_retry.md
For now, I should probably add a check for the version, and show a warning that the ping pong is unavailable if libwebsockets are too new: when I have some time I'll add support for the new mechanism too.

**Comment by lminiero** [comment]
@htc1977 @mattcamp any chance you guys can test if this last commit works as expected with libwebsockets 4? Not just whether it compiles, but also if it translates to the right ping/pong behaviour. I only have lws3 installed, here, and no time to test it myself. Thanks.

**Comment by atoppi** [comment]
I can confirm that ping-pong is correctly working with lws 4 now.
