### ISSUE TITLE
After 0.92, warning in streaming plugin: [WARN] libcurl not available, Streaming plugin will not have RTSP support

### ISSUE THREAD

**Issue by gjovanov** [meetecho/janus-gateway#2165]
Until today we were using Janus 0.92 tagged version, based on our Docker Image (Debian:buster-slim based):

https://github.com/gjovanov/docker/blob/master/janus-slim/Dockerfile

We tried to upgrade on Janus 0.95 (nothing else changed except (ARG JANUS_VERSION="v0.9.5" previously being ARG JANUS_VERSION="v0.9.2") and we started getting this warning:

`[WARN] libcurl not available, Streaming plugin will not have RTSP support`

It seems similar to #1858 .  With the difference on Debian Buster we a bit newer version of libcurl4:

```bash
dpkg -l  | grep libcurl
ii  libcurl4:amd64             7.64.0-4+deb10u1            amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
```

We are not sure if this really is an issue or a warning that can be ignored?

Thanks.

**Comment by lminiero** [comment]
You can ignore it if you don't need RTSP. If you do, check the configure results, if you're getting that message it means it couldn't find libcurl. Why that is I don't know, you'll have to check: works fine here. Closing as not a code issue, ask on the group instead.

**Comment by gjovanov** [comment]
Thanks for clarifying @lminiero !

Indeed it was an issue with not fining the correct `libcurl` package on Debian Buster, since we had installed `libcurl4-gnutls-dev` instead of `libcurl4-openssl-dev`

The warrning has disappeard after installing `libcurl4-openssl-dev`.
