### ISSUE TITLE
How can I make a static binary for janus-pp-rec?

### ISSUE THREAD

**Issue by softer** [meetecho/janus-gateway#2166]
Version used: [d41f265](https://github.com/meetecho/janus-gateway/commit/d41f265b1f5a82b1483fc7df3c7e5dd1f117b178)

I want to use janus-pp-rec in AWS Lambda. Can I make this binary static?
I tried this:
```
# ./configure --help | grep static
  --enable-static[=PKGS]  build static libraries [default=no]
# ./configure --prefix=/opt/janus --disable-all-plugins --disable-all-transports --disable-all-handlers --disable-all-loggers --enable-post-processing --enable-static
...
# make
# ldd janus-pp-rec  | wc -l
110
# make LDFLAGS="-all-static"
...
/usr/bin/ld: cannot find -lnice
collect2: error: ld returned 1 exit status
```

Libraries were installed as written in README

Thanks!

**Comment by lminiero** [comment]
We don't support building static executables, you'll have to mess with configure.ac and Makefile.am yourself I'm afraid. Closing, use the [group](https://groups.google.com/forum/#!forum/meetecho-janus) if you want to discuss this further with other users.
