### ISSUE TITLE
100% CPU infinite loop in libmicrohttpd

### ISSUE THREAD

**Issue by arctica** [meetecho/janus-gateway#2168]
Running Janus 0.9.5 via snap on Ubuntu I've noticed a Janus instance which should have been idle is using 100% of one cpu core.

The server should have been idle, it was a test server and noone was using it. In the admin page I see no handles as expected. The reason I logged into the server was that yesterday I noticed janus was using about 1-3% CPU while sitting idle after I did a bunch of videoroom plugin tests. That already seemed too high to me when it should be completely idle. Today then I noticed it has gone to 100%.

```
# ps -To pcpu,tid,comm -C janus | sort -r -k1
81.7   65076 MHD-single
%CPU     TID COMMAND
 0.3   65068 mp 2
 0.3   65061 mixer 1234
```

```
(gdb) bt
#0  0x00007f61812ebbb7 in epoll_wait () from target:/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f61513cf80a in ?? () from target:/snap/janus-gateway/565/usr/lib/x86_64-linux-gnu/libmicrohttpd.so.12
#2  0x00007f61513d095a in ?? () from target:/snap/janus-gateway/565/usr/lib/x86_64-linux-gnu/libmicrohttpd.so.12
```

strace shows it is in an infinite loop polling the sockets and trying to read something:

```
[pid 65076] epoll_wait(18, [], 128, 0)  = 0
[pid 65076] recvfrom(29, 0x7f6138069cfb, 1, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 65076] epoll_wait(18, [], 128, 0)  = 0
[pid 65076] recvfrom(29, 0x7f6138069cfb, 1, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
[pid 65076] epoll_wait(18, [], 128, 0)  = 0
[pid 65076] recvfrom(29, 0x7f6138069cfb, 1, 0, NULL, NULL) = -1 EAGAIN (Resource temporarily unavailable)
```
Using lsof to check what socket with fd 29 is:

```
janus   65023 root   29u     IPv6             313108      0t0    TCP static.140.45.12.49.clients.your-server.de:8089->trk-74.iguanatrack.com:56402 (ESTABLISHED)

janus   65023 root   29u     IPv6             313108      0t0    TCP 49.12.45.140:8089->209.141.58.74:56402 (ESTABLISHED)
```
I have no idea what this iguanatrack.com is, maybe a crawler of some sort. The following site seems to suggest that: https://www.abuseipdb.com/check/209.141.58.74

Port 8089 suggests this was a connection to the https transport and the backtrace pretty much confirms that.

I am leaving the server in this state so further debugging is possible as I have no idea how I would reproduce it unfortunately.

This might possibly a bug in libmicrohttpd or in janus' usage of it. Any suggestions how to proceed?

**Comment by lminiero** [comment]
Possibly related to this FAQ item:
https://janus.conf.meetecho.com/docs/FAQ#https

We don't recommend enabling HTTPS in Janus directly: better leave that up to a proxy like nginx, and only do plain HTTP/WS in Janus instead (that's what we do in production).

That said, I'm not going to dig into the libmicrohttpd internals, sorry. You may want to open an issue on their mailing list to see if they can find the cause.

**Comment by arctica** [comment]
Thank you for the reply and pointer to the FAQ entry. Somehow I didn't see that when I was doing searches and also looking at the google group. I totally understand why you suggest letting a proper webserver handle the HTTP in front of Janus. HTTP (and with SSL even more so) is a complex protocol, too complex for what is actually needed. Will go with the suggested nginx proxy in front for HTTPS and then plain HTTP between that and Janus. That will have additional side benefits anyways as it's a more flexible setup. Again, thanks!
