### ISSUE TITLE
call lws_service_cancel() can not work in janus_websocket_send_message()

### ISSUE THREAD

**Issue by chengmo03013106** [meetecho/janus-gateway#2177]
> If you want to open an issue, please make sure that:
>
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved in master;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available [here](http://janus.conf.meetecho.com/docs/debug.html)).
>
> If so, just remove this text and share your findings!

call lws_service_cancel() can not work in janus_websocket_send_message()

I was using janus v0.9.1 with libwebsocket v3.2.0, and I encountered that this which located in janus_websocket_send_message(). 
the code called lws_service_cancel() to try to active the poll of lws instead of call lws_callback_on_writable. The modifing of here was supposed that lws_service_cancel()'s consuming was cheaper than later one. It should run in the callback function janus_websockets_common_callback and went to the branch of switch case (LWS_CALLBACK_EVENT_WAIT_CANCELLED), and then, all writable clients would be called by lws_callback_on_writable.

But there was not worked as what I think, there was not janus_websockets_common_callback() after 
lws_service_cancel() called in janus_websocket_send_message(). 

The lws-team told me that lws_service_cancel() was supposed that active the poll of lws from other thread rather than self-thread, Is there some wrong with it ? 
Or it could be my mistakes in somehow ?

**Comment by lminiero** [comment]
#1638

**Comment by chengmo03013106** [comment]
> #1638

Excuse me, There were some mistakes of my expression.
I was using janus v.0.9.1 which were later than this merging.
What I encountered is : 
After calling lws_service_cancel() , there was nothing happen, the program would not run to janus_websockets_common_callback()
