### ISSUE TITLE
Packets RTP forwarded to Mountpoint are "Truplicated" in case of simulcast

### ISSUE THREAD

**Issue by trankkilou** [meetecho/janus-gateway#2179]
While doing Streaming mount point benchmark we notice a lot of error in janus log 👍 
[Wed May 27 14:58:34 2020] [ERR] [ice.c:janus_ice_outgoing_stats_handle:3981] [5178857833275260] Got 404 SRTP/SRTCP errors in the last few seconds (last error: srtp_err_status_replay_fail)

to reproduce 
1/ set simulcast2=true in publisher
2/ configure RTP forwarding in a videoroom with simulcast with 3 ports, for instance
video port -> 10000
video port2 -> 10001
video port3 -> 10002
(specify a ssrc for each or NOT -> change nothing)
3/ you can notice you have your 3 sub streams in each port
**but each outgoing stream has every packet 3 times**

captured packets between janus and mount point in cc
[full-sud.pcap.gz](https://github.com/meetecho/janus-gateway/files/4690052/full-sud.pcap.gz)
you can set filter to "udp.dstport eq 60118"
you will notice at once the issue
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/17863520/83045427-d716ba80-a045-11ea-8a6b-1c559ed5ba9b.png">

**Comment by atoppi** [comment]
@trankkilou IIUC that pcap contains the traffic between the Janus room and the Janus streaming mountpoint, right?

**Comment by trankkilou** [comment]
yep the videroom is one server and the mountpoint on another one.

**Comment by lminiero** [comment]
Works fine here. Are you sure you're not creating the same forwarder multiple times by mistake? Since the same socket is used for all forwarders belonging to the same publisher, you'll see the same source port too, which is why it "looks" like duplicates (because it is, if you're forwarding the same publisher to the same place more than once). You can double check that sending a "listforwarders" request for the publisher.

**Comment by atoppi** [comment]
I have tried your steps doing the following:
- join a room as a publisher with enabled simulcasting
- confirmed simulcast is active through webrtc internals and Janus admin
- started forwarding toward ports `6001`, `6002`, `6003`
- captured traffic on those ports

I don't see any triplicated packet, Janus is forwarding each packet once for each sc layer.

[sc_forwarding.pcapng.gz](https://github.com/meetecho/janus-gateway/files/4695045/sc_forwarding.pcapng.gz)

**Comment by trankkilou** [comment]
Hi Lorenzo,

Actually  , this is the first thing we check. 

We can double check with a « listforwarders », for sure.

J-

**Comment by trankkilou** [comment]
here the check, only one forwarder 👍 
the RTP forward request:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/17863520/83136704-37f6cf00-a0e8-11ea-8ab5-7fe57602c64c.png">

the list forwarders request
<img width="535" alt="image" src="https://user-images.githubusercontent.com/17863520/83136604-13025c00-a0e8-11ea-8673-7333d393aabe.png">

note: on server which has videoroom, lots of 
_[WARN] Incoming RTCP SR SSRC (2367286513) does not match the expected one (2549146262) video=1_
messages in log

**Comment by atoppi** [comment]
Please try to track (through debugging or logging) how many times Janus is making [this call](https://github.com/meetecho/janus-gateway/blob/f0d124471e876eae25f126cc4f772941f0814d8f/plugins/janus_videoroom.c#L4972) to be sure that the server is sending multiple copies of the same packet.

**Comment by trankkilou** [comment]
Hi Alessandro ,

We won’t reproduce anymore so I assume we should have made a mistake :)

Sorry for the disturbing, I guess you can close the case :)

J-
