### ISSUE TITLE
Couldn't found transports/.libs/libjanus_http.so.0.0.0 durning compiling

### ISSUE THREAD

**Issue by chengmo03013106** [meetecho/janus-gateway#2181]
Hi guys :

I encountered this problem:
After running `configure --disable-all-transports --enable-rest --enable-websocket --.......`
There were no error durning `make` and I got "Couldn't found transports/.libs/libjanus_http.so.0.0.0" when I ran `make install`. 
I had checked the transports/.libs/, there was no libjanus_http.so.0.0.0. 

In additional :
my libjanus_http.la file as follow could be helpful.

  1 # libjanus_http.la - a libtool library file
  2 # Generated by libtool (GNU libtool) 2.4.6
  3 #
  4 # Please DO NOT delete this file!
  5 # It is necessary for linking the library.
  6 
  7 # The name that we can dlopen(3).
  8 dlname='libjanus_http.so.0'
  9 
 10 # Names of this library.
 11 library_names='libjanus_http.so.0.0.0 libjanus_http.so.0 libjanus_http.so'
 12 
 13 # The name of the static archive.
 14 old_library=''
 15 
 16 # Linker flags that cannot go in dependency_libs.
 17 inherited_linker_flags=' -pthread'
 18 
 19 # Libraries that this one depends upon.
 20 dependency_libs=' -L/opt/webrtc/install/libmicrohttpd/lib /opt/webrtc/install/libmicrohttpd/lib/libmicrohttpd.la -L/opt/webrtc/install/jansson/lib -L/opt/webrtc/install/glib/lib /opt/webrtc/install/glib/lib/libglib-2.0.la -lpthre    ad -lrt /opt/webrtc/install/jansson/lib/libjansson.la'
 21 
 22 # Names of additional weak libraries provided by this library
 23 weak_library_names=''
 24 
 25 # Version information for libjanus_http.
 26 current=0
 27 age=0
 28 revision=0
 29 
 30 # Is this an already installed library?
 31 installed=no
 32 
 33 # Should we warn about portability when linking against -modules?
 34 shouldnotlink=no
 35 
 36 # Files to dlopen/dlpreopen
 37 dlopen=''
 38 dlpreopen=''
 39 
 40 # Directory that this library needs to be installed in:
 42 libdir='/home/chengmo/development/bee/janus_prefix/lib/janus/transports'

The 2nd question : 
I want to know how to generate xxx.la file, which steps of compiling could be work for it ?

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
