### ISSUE TITLE
Janus crash after textroom datachennel is open

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#2185]
Hi!

I use janus (pulled from master).
This crash cause by textroom plugin, when sending {"request":"ack"}

https://gist.github.com/izemize/912caccef69f4a750cd340e54907c568

**Comment by lminiero** [comment]
Works fine here, looks like an issue with your local installation of usrsctplib.

**Comment by izemize** [comment]
You suggest update usrsctplib because security issue. Chrome? I use from
github master. Which version is good Ford Janus?

Lorenzo Miniero <notifications@github.com> ezt írta (időpont: 2020. máj.
29., P 10:35):

**Comment by izemize** [comment]
Ok. So i re-install lib with make clean, and now it works.
