### ISSUE TITLE
janus_rtp_header_extension_parse_audio_level state problem

### ISSUE THREAD

**Issue by maxboehm** [meetecho/janus-gateway#2192]
As discussed in Pull Request #2172, we are currently trying to detect the audio level via janus.

After that pull request, we stumbled upon the next interesting behaviour. I invested quite some time, but have no final result.

So far:
**Case a)**
1. join (audio=false,video=false)
2. configure(audio=true)
-> desired behaviour

**Case b)**
1. join (audio=false,video=false)
2. configure(audio=false,video=true)
3. configure(audio=true,video=true)
-> It does not work any more, no audio level is found. This is happening in Chrome as well as in Firefox. Somehow, depending which of both I share first, the audio level recognition does not work anymore.

I digged into the function _janus_rtp_header_extension_parse_audio_level_.
- Case a): "id"=1
- Case b): "id" = -2, after changing that manually to 1, I get the desired results.

ID is determined by "stream->audiolevel_ext_id" in ice.c:2551. 

At this point, I dropped out. Any ideas?

Thank you!

**Comment by lminiero** [comment]
`stream->audiolevel_ext_id` is set in `janus.c`:
https://github.com/meetecho/janus-gateway/blob/master/janus.c#L1412
using `janus_rtp_header_extension_get_id` to find the extension ID in the new SDP. If you see `-2` it means the extension was not found in the SDP:
https://github.com/meetecho/janus-gateway/blob/master/rtp.c#L77
As such, you should check if the SDP still has the related extmap.

**Comment by maxboehm** [comment]
Thank you for the hints, will do that next week as I am on the road this week.

**Comment by maxboehm** [comment]
Got it.

If I enable the mic after the webcam, the method `janus_rtp_header_extension_get_id` **will not** be called. It is rather a conditional problem: I get the log "Negotiation update, checking what changed" after enabling the mic and found, that in this part of the [condition (janus.c:1426)]( https://github.com/meetecho/janus-gateway/blob/master/janus.c#L1426) the extension is not handled. 

I've modified [janus.c in my fork](https://github.com/maxboehm/janus-gateway/blob/master/janus.c#L1466) and the audio level recognition is working now. Just not sure about the consequences. What do you think?

**Comment by lminiero** [comment]
It depends on the changes. Have you checked if it works as expected in the new multistream branch instead? Renegotiations should work "better" there.

**Comment by maxboehm** [comment]
To be honest, I don't understand why it should behave differently in the multistream branch.

The condiition is the same: as soon, as it is a renegotiation, there won't be any extension handling at all.

I've just opened a PR: #2223. Happy to get feedback, though, my knowledge is limited in seeing any consequences. I merely replicated the behaviour of the previous condition...

**Comment by lminiero** [comment]
> To be honest, I don't understand why it should behave differently in the multistream branch.

Because the parsing has been changed considerably, and the core is now much more aware of different m-lines (which it maps to medium instances internally).

**Comment by maxboehm** [comment]
> Janus commit: [37e08f3ffa4e8b97c80fa2d0bfd20f6c51ce3c9c](https://github.com/meetecho/janus-gateway/commit/37e08f3ffa4e8b97c80fa2d0bfd20f6c51ce3c9c)
> Compiled on:  Fri 12 Jun 2020 01:06:52 PM CEST
> Starting Meetecho Janus (WebRTC Server) v0.10.1

Indeed, multistream works.

**Comment by maxboehm** [comment]
Are there any plans till when you will merge the multistream branch? Or is there a chance that you will merge my pr (#2223)? 

Thank you!

**Comment by lminiero** [comment]
Multistream branch needs some more testing before it is merged (hopefully we'll start getting feedback from people using it soon). I haven't looked at your PR yet, as I'm quite busy on other things. Not sure I'll be able to do that today, so it may only happen next week. Anyway, if it works I'll merge it in master, and then "ignore" it in the multistream branch (where it's not an issue) when I realign the two.

**Comment by maxboehm** [comment]
> Not sure I'll be able to do that today, so it may only happen next week.
No hurry, it's friday :) Also, if it can not be merged into current master I still can build it from my fork and go back later to your master if you have merged multistream.
