### ISSUE TITLE
do janus support ulpfec/red for video ?

### ISSUE THREAD

**Issue by openserli** [meetecho/janus-gateway#2193]
hi all,
does janus support video fec relate feature?  i see nack config, but not found fec  config,
fec is important when RTT is high for handle video packet loss.

**Comment by lminiero** [comment]
Not yet. Closing as not a code issue, questions belong to the group.
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by openserli** [comment]
but, video fec is very important for mobile video quality. i think we need add fec.

**Comment by lminiero** [comment]
Then do it. Looking forward to your pull request!
