### ISSUE TITLE
TURN REST API request does not supply username

### ISSUE THREAD

**Issue by joe-average-user** [meetecho/janus-gateway#2199]
The janus_turnrest_request function in turnrest.c does not send a username. Which means it does not work with the classical turnhttp-server. Is there a chance to supply it?

**Comment by lminiero** [comment]
You'll have to be more specific than that. Please share what it does, what it doesn't, and what it should do, and we'll look into it.

**Comment by joe-average-user** [comment]
Sorry for the inconvenience, I thought pointing to the function would explain the problem.
turnhttp-server, which is more or less the "standard implementation" of the rest api for coturn, does this (go code):

func (self *Service) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
        username := r.FormValue("username")
        if username == "" {
                http.Error(rw, "Must supply a username.", http.StatusBadRequest)
                return
        }

which means a tag "username=" is expected to be present. But the named function in janus does this:

janus_turnrest_response *janus_turnrest_request(void) {
        janus_mutex_lock(&api_mutex);
        if(api_server == NULL) {
                janus_mutex_unlock(&api_mutex);
                return NULL;
        }
        /* Prepare the request URI */
        char query_string[512];
        g_snprintf(query_string, 512, "service=turn");
        if(api_key != NULL) {
                /* Note: we've been using 'api' as a query string parameter for
                 * a while, but the expired draft this implementation follows
                 * suggested 'key' instead: as such, we send them both
                 * See https://github.com/meetecho/janus-gateway/issues/1416*/
                char buffer[256];
                g_snprintf(buffer, 256, "&api=%s", api_key);
                g_strlcat(query_string, buffer, 512);
                g_snprintf(buffer, 256, "&key=%s", api_key);
                g_strlcat(query_string, buffer, 512);
        }
        char request_uri[1024];
        g_snprintf(request_uri, 1024, "%s?%s", api_server, query_string);
        JANUS_LOG(LOG_VERB, "Sending request: %s\n", request_uri);
        janus_mutex_unlock(&api_mutex);
        /* Prepare the libcurl context */
        CURLcode res;
        CURL *curl = curl_easy_init();
        if(curl == NULL) {
                JANUS_LOG(LOG_ERR, "libcurl error\n");
                return NULL;
        }
        curl_easy_setopt(curl, CURLOPT_URL, request_uri);
        curl_easy_setopt(curl, api_http_get ? CURLOPT_HTTPGET : CURLOPT_POST, 1);
        if(!api_http_get) {
                /* FIXME Some servers don't like a POST with no data */
                curl_easy_setopt(curl, CURLOPT_POSTFIELDS, query_string);
        }
        curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10L);   /* FIXME Max 10 seconds */

which basically means there is no username/userid at all.
The corresponding ietf draft specifies:

2.1.  Request

   The request includes the following parameters, specified in the URL:

   o  service: specifies the desired service (turn)

   o  username: an optional user id to be associated with the
      credentials




Uberti                  Expires January 16, 2014                [Page 3]

 
Internet-Draft            TURN Server REST API                 July 2013


   o  key: if an API key is used for authentication, the API key

   Example:

   GET /?service=turn&username=mbzrxpgjys

Which means just about the only example in the draft contains a username.

During the talking of the several entities in the webrtc session the "userid" (or username in some places) is continously given, like (here as "nick" partly "X"ed):

Jun 04 12:38:13 host janus[126248]: [WSS-0x7fda78000b60] Got 2821 bytes:
Jun 04 12:38:13 host janus[126248]: [WSS-0x7fda78000b60] First fragment: 2821 bytes, 0 remaining
Jun 04 12:38:13 host janus[126248]: {"body":{"audio":true,"data":true,"request":"configure","video":true},"handle_id":672993126695639,"janus
":"message","jsep":{"nick":"XkXaX@XtXnXt.XXX","sdp":"v=0\r\no=mozilla...THIS_IS_SDPARTA-77.0 3860578920749964072 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 
0\r\na=fingerprint:sha-256 42:00:8D:38:19:D2:96:4C:3E:2A:F8:42:CA:0F:3F:44:99:9F:04:43:AF:10:C0:2A:C4:85:4B:29:57:3D:B6:8E\r\na=group:BUNDLE 0 1
 2\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=audio 9 UDP/TLS/RTP/SAVPF 109 9 0 8 101\r\nc=IN IP4 0.0.0.0\r\na=sendonly\r\na=extmap:
1 urn:ietf:params:rtp-hdrext:ssrc-audio-level\r\na=extmap:2/recvonly urn:ietf:params:rtp-hdrext:csrc-audio-level\r\na=extmap:3 urn:ietf:params:r
tp-hdrext:sdes:mid\r\na=fmtp:109 maxplaybackrate=48000;stereo=1;useinbandfec=1\r\na=fmtp:101 0-15\r\na=ice-pwd:d27c7ba828b1bd52f8ad1f78a24f97a7\
r\na=ice-ufrag:40721bd2\r\na=mid:0\r\na=msid:{37fe5fda-34d0-4600-8574-3c4902611cab} {2a16dfe7-0008-4670-92cc-2852fd25693e}\r\na=rtcp-mux\r\na=rt
pmap:109 opus/48000/2\r\na=rtpmap:9 G722/8000/1\r\na=rtpmap:0 PCMU/8000\r\na=rtpmap:8 PCMA/8000\r\na=rtpmap:101 telephone-event/8000/1\r\na=setu
p:actpass\r\na=ssrc:1496732474 cname:{b4f4536c-ae58-43b0-9544-480de73d3ad6}\r\nm=video 9 UDP/TLS/RTP/SAVPF 120 121 126 97\r\nc=IN IP4 0.0.0.0\r\
na=sendonly\r\na=extmap:3 urn:ietf:params:rtp-hdrext:sdes:mid\r\na=extmap:4 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time\r\na=extm
ap:5 urn:ietf:params:rtp-hdrext:toffset\r\na=extmap:6/recvonly http://www.webrtc.org/experiments/rtp-hdrext/playout-delay\r\na=fmtp:126 profile-
level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\na=fmtp:97 profile-level-id=42e01f;level-asymmetry-allowed=1\r\na=fmtp:120 max-
fs=12288;max-fr=60\r\na=fmtp:121 max-fs=12288;max-fr=60\r\na=ice-pwd:d27c7ba828b1bd52f8ad1f78a24f97a7\r\na=ice-ufrag:40721bd2\r\na=mid:1\r\na=ms
id:{37fe5fda-34d0-4600-8574-3c4902611cab} {055c0acf-19ea-4e57-8292-3daab90b6b51}\r\na=rtcp-fb:120 nack\r\na=rtcp-fb:120 nack pli\r\na=rtcp-fb:12
0 ccm fir\r\na=rtcp-fb:120 goog-remb\r\na=rtcp-fb:121 nack\r\na=rtcp-fb:121 nack pli\r\na=rtcp-fb:121 ccm fir\r\na=rtcp-fb:121 goog-remb\r\na=rt
cp-fb:126 nack\r\na=rtcp-fb:126 nack pli\r\na=rtcp-fb:126 ccm fir\r\na=rtcp-fb:126 goog-remb\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=
rtcp-fb:97 ccm fir\r\na=rtcp-fb:97 goog-remb\r\na=rtcp-mux\r\na=rtpmap:120 VP8/90000\r\na=rtpmap:121 VP9/90000\r\na=rtpmap:126 H264/90000\r\na=r
tpmap:97 H264/90000\r\na=setup:actpass\r\na=ssrc:3941817648 cname:{b4f4536c-ae58-43b0-9544-480de73d3ad6}\r\nm=application 9 UDP/DTLS/SCTP webrtc
-datachannel\r\nc=IN IP4 0.0.0.0\r\na=sendrecv\r\na=ice-pwd:d27c7ba828b1bd52f8ad1f78a24f97a7\r\na=ice-ufrag:40721bd2\r\na=mid:2\r\na=setup:actpa
ss\r\na=sctp-port:5000\r\na=max-message-size:1073741823\r\n","type":"offer"},"session_id":4460484082002102,"transaction":"8"}
Jun 04 12:38:13 host janus[126248]: [WSS-0x7fda78000b60] Done, parsing message: 2821 bytes

Could be that I am missing something, but I think the username (given in return in the JSON) should at least somehow reference presented nicks, userids, usernames or whatever it may be called.
Not?

**Comment by lminiero** [comment]
Please don't paste huge bunches of text inline. As clearly explained in the issue template guidelines, you should use pastebin or gist for that.

> I think the username (given in return in the JSON) should at least somehow reference presented nicks, userids, usernames or whatever it may be called.

In case we need to provide a username, it can't be anything plugin-specific, since this is done by the core which knows nothing of plugin concepts (e.g. what a VideoRoom publisher ID is). The best we can do is either use some existing info (e.g., opaque_id or session_id/handle_id), or simply send a random username every time. As an alternative we can also use the same username every time, but not sure if the service you mention will fail because the username exists, in that case.

If you can provide more details on what's expected and what's (not) accepted, we'll have a look.

**Comment by lminiero** [comment]
That said, the draft clearly says `username` is optional (which is probably why we didn't use it):
https://tools.ietf.org/html/draft-uberti-rtcweb-turn-rest-00#section-2.1

So you may also want to look into that implementation to see if you can have it skip the check.

**Comment by lminiero** [comment]
PS: is there a good reason you're trying to use TURN in Janus? Read this if you haven't already: https://janus.conf.meetecho.com/docs/FAQ#turn

**Comment by joe-average-user** [comment]
> PS: is there a good reason you're trying to use TURN in Janus? Read this if you haven't already: https://janus.conf.meetecho.com/docs/FAQ#turn

And exactly this is our intention:
"or if you simply want to limit the number of open ports and so force all media traffic to go through the TURN server port alone."

**Comment by joe-average-user** [comment]
> That said, the draft clearly says `username` is optional (which is probably why we didn't use it):
> https://tools.ietf.org/html/draft-uberti-rtcweb-turn-rest-00#section-2.1
> 
> So you may also want to look into that implementation to see if you can have it skip the check.

Well, janus expects a JSON returned with "username" and "password" in it. I hardly can think of any good reason why a daemon (turnhttp-server) that has really no knowledge of the true use of his return value should simply "invent" some new username for the caller ... ?

**Comment by joe-average-user** [comment]
> > I think the username (given in return in the JSON) should at least somehow reference presented nicks, userids, usernames or whatever it may be called.
> 
> In case we need to provide a username, it can't be anything plugin-specific, since this is done by the core which knows nothing of plugin concepts (e.g. what a VideoRoom publisher ID is). The best we can do is either use some existing info (e.g., opaque_id or session_id/handle_id), or simply send a random username every time. As an alternative we can also use the same username every time, but not sure if the service you mention will fail because the username exists, in that case.
> 
> If you can provide more details on what's expected and what's (not) accepted, we'll have a look.

In this case I'd probably take a session_id (meaning something that's really somehow related to other output in the logs regarding the current action)

**Comment by lminiero** [comment]
> "or if you simply want to limit the number of open ports and so force all media traffic to go through the TURN server port alone."

You don't need Janus to use TURN for that. Just force users to use TURN (there's a constraint for that) so that only relay candidates are used, and Janus will use those.

**Comment by lminiero** [comment]
> In this case I'd probably take a session_id

There will be several connections with the same session_id: what happens if you use the same username multiple times?

**Comment by alexamirante** [comment]
>And exactly this is our intention:
"or if you simply want to limit the number of open ports and so force all media traffic to go through the TURN server port alone."

I'm actually not convinced at all by this reason and we should probably change the answer to the FAQ. If you want to limit the number of *exposed* ports, which I guess is your goal, you must do that by configuring your NAT/Firewall accordingly. Even if you don't configure TURN for Janus and configure your firewall to block all incoming UDP traffic, you would still allow the outgoing traffic as it won't pose any security concern. As such, configuring TURN *for clients* is more than enough.

**Comment by joe-average-user** [comment]
Really, I am not convinced by your implementation of the REST API per se. What are you - at all - trying to achieve by asking for username/password/URIs without giving any hint about the current usage of those values to the turn rest api server? The security imposed by the api key alone really is minimal. 
And of course: since I do not know your janus implementation details my proposal of session_id as a username is founded on my (wrong?) thinking that a session is equal to a single connection. If it is not, then what identifies a connection in janus? Is there something like a connection id? Then simply use this as username. nevertheless I still do think that data presented by the janus-user (like the nick/userid/username from the videoroom) would be a lot more transparent. Your code core should have (or gain) access to such data by pointers in some data structures associated with the core. If the used plugin is no videoroom but something else there should be some way for the plugin to give such information to the core.

**Comment by lminiero** [comment]
I made a simple question (what happens when the username exists) and I still haven't heard any answer. When I know what happens (or is supposed to happen) in that case, I can come up with a potential solution. Until then, I'm pretty busy as it is to go hunting for answers myself on something we never use, sorry.

**Comment by joe-average-user** [comment]
The reason for my ignoring your question so far is that I do not understand what the question really is. A turn rest api gives you a new set of credentials for the presented username, as long as the acls allow for that - just as explained in the ietf draft. If janus gets a new credential or no answer depends on the admins idea of what to do. By any means the credentials are not the same, even if the requested username is the same. And that is as well documented in the draft, because

"To avoid the need for state passing between the web service and TURN
   server, the returned credentials consist of a TURN username that
   encodes all the necessary state (expiry time and application user
   id), and a TURN password that is a digest of this state, signed with
   the shared secret key."

Which means that you present the "user id", and the turn rest api gives you the TURN username back constructed like explained above.
So what is your question really?

**Comment by lminiero** [comment]
You seem to be confusing Janus for a traditional endpoint like a browser, which it isn't. That is exactly why I'm asking what this TURN REST API backend expects. 

Users may end up creating multiple PeerConnections at the same time, whether it's to the same plugin or different ones. This really doesn't matter to the Janus core, it's just multiple PeerConnections it's handling. Ideally, for the same user, you'd only need one set of TURN credentials for all those connections, and that's how a browser would behave I assume. That's why I was wondering what happens when you use the same username more than once: the way Janus works, the TURN REST API would be hit with the same username more than once.

Caching username and credendials is not an option. First of all, a "user" is an application concept, depends on plugins and the way the application talks to Janus; attempting to force such a concept to Janus (e.g., "all PeerConnections created with this session ID") could cause issues (server-side applications may be using a single session ID for all of their users, and the TURN server may have a limit of allocations you can do with the same credentials). Besides, we don't know how long those credentials will be valid, which means we might cache something for too long and use invalid details.

I assumed the `key` we're providing was exactly the "application user ID" you're referring to, so that's why I think we never added any username there. If we need to provide a username, and you can confirm that if we send multiple requests with the same username to the backend (for the reasons explained above) it won't reject them, then I can work on a fix.

**Comment by joe-average-user** [comment]
Thank you for your detailed answers. I can assure you that a "standard turn http rest api" would not reject the multiple requests on the same username only because they are _multiple_. Just about the only reason for a reject I can think of is user-interaction, meaning an admin that wants to deny this user for some reason.
But reading all your answers one very basic question arises on my side: what is this authentication via the rest api used for in janus - at all? At this point we are simply ignoring the error and cannot find a functional deficiency so far. Which means we either have not understood what function we are missing at this point, or all is functional and something could be "better" than it is now, if this authentication worked. Can you teach us what it is for in the janus code?
We thought it would allow a by-user authentication of creation of PeerConnections, but obviously it does not...? And this is the reason we would like to see a username presented that is in some externally reproducable way connected to the data presented by the browser client to janus.

**Comment by lminiero** [comment]
It's only there because at the time (several years ago) some people were not comfortable with needing to expose static credentials you could configure if you needed a TURN server to be used for Janus itself. In those cases, using the TURN REST API allows for a dynamic management of TURN credentials, new ones for each PeerConnection.

The user is never involved in the process: it's purely a server-side thing. In case you'd like to see some mapping between user-info and TURN usernames, we can use `opaque_id` for the purpose, which is what I suggested in my first response. The `opaque_id` is something you set when attaching handles, and so something you can provide to Janus as an application for tagging users: Janus doesn't care about them (that's why it's opaque), they're mostly meant to be used in event handlers for correlating events related to different Janus handles belonging to the same user on the server side, but I guess they can be used here as well. A simple patch to apply might be: if an `opaque_id` exists, use that as username, otherwise stringify the `session_id` and send that.

**Comment by joe-average-user** [comment]
Well, if you take a look at my second message there is a packet debug dump that contains lots of information from the client side presented for "installing" some peer connection, one of which is called "nick" which is in fact a username from the client browser app. If it added an opaque_id the extraction work for janus should be pretty much the same. Surely I'd take the id if it is the only choice I had, but for transparency the fields presented in several packets named "nick", "user_id","username" (all the same content AFAIK) would be a winner.
As far as I understood your explanation the rest api itself is more or less functionally xor api_key. Either the configured key is used as a authentication method, or usernames checked through the rest api. But the janus function itself is not touched, no matter what way.
This explains why we cannot find anything not working currently.
Thank you.

**Comment by lminiero** [comment]
Added the username in the PR above. I didn't test it as I'm busy on other things. If you can confirm it works, I'll merge.

**Comment by joe-average-user** [comment]
While we're at it, according to your knowledge is there a config possibility to reduce the number of used ports down to one i.e. 443/https containing all streams/peer connections (in video-room plugin)? Because a "standard setup" with turn server very often fails to work in company guest networks.

**Comment by gjovanov** [comment]
One way of achieving single PORT usage e.g. 433 for both Janus and Coturn,
if you have one server, but multiple IPs, then you can split with two
different NGINX instances:
1. NGINX1 listening on  IP1:80,   IP1:443/TCP and IP1:443/UDP filtering
HTTP traffic
2. NGINX2 listening on IP2:443/UDP filtering UDP traffic for Coturn

You can find an example of this in the docker-compose.yml

https://github.com/gjovanov/roomler/tree/master/.nginx

using:
/nginx.conf
/coturn/nginx.conf

This way NGINX1 and IP1 are used as a reverse-proxy for Janus as well your
APP and NGINX2 and IP2 is used as a reverse proxy for Coturn.

There are also attempts online, to resolve this without the need of two IPs
with either:
a) ALPN protocol filtering
b) SNI (server name indication) filtering

discussed here: https://community.jitsi.org/t/nginx-coturn-port-443/27820/7

But it seems that it's not so easy to do that as not all browsers are
sending ALPN or SNI and on top of that via Nginx it's hard to on UDP/TCP
level to decide whether you want to route your connection to Coturn or
HTTP/HTTPS.

So as a workaround is having 2 IPs either on the same machine or multiple
machines.

**Comment by lminiero** [comment]
I think you can do that with a single IP and a single nginx, if you reverse proxy the different paths. That said, this is out of scope here: please move this kind of discussions to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), I'd rather we keep Github only for code-specific issues.

**Comment by lminiero** [comment]
@joe-average-user can the PR be merged? Does it do what you needed?

**Comment by joe-average-user** [comment]
@lminiero Yes, I can approve that it does what it should do.
Thank you !

**Comment by lminiero** [comment]
Ack, merging then :+1:
