### ISSUE TITLE
Response to streaming plugin "list" command doesn't contain metadata 

### ISSUE THREAD

**Issue by willamowius** [meetecho/janus-gateway#2204]
The documentation says that the channel list of the streaming plugin returned by "list" contains the metadata.

Just tested against master, that it is not included.

Either the code or the documentation should be changed. I think changing the code would be better, because its handy to have the metadata right away.

**Comment by lminiero** [comment]
> I think changing the code would be better, because its handy to have the metadata right away.

I agree. Don't have time to do that now though, so if you can share a pull request I'll gladly review.

**Comment by willamowius** [comment]
I can do that.

I would propose to show the "enabled" field in the list, too.

**Comment by lminiero** [comment]
Closing as both matters were addressed.
