### ISSUE TITLE
Parameters missing in vp9svctest.js

### ISSUE THREAD

**Issue by marcdownie** [meetecho/janus-gateway#2207]
This line:
https://github.com/meetecho/janus-gateway/blob/a180329b3a1e39c110424ff6906c03a01a1cbf5a/html/vp9svctest.js#L439

should surely read:

`function newRemoteFeed(id, display, audio, video) {`

given, say:

https://github.com/meetecho/janus-gateway/blob/a180329b3a1e39c110424ff6906c03a01a1cbf5a/html/vp9svctest.js#L465

This is the difference between vp9svctest.js working and not working on our installation.

**Comment by lminiero** [comment]
Thanks, if you submit a PR, I'll review and in case merge.

**Comment by lminiero** [comment]
Closing as your PR was merged.
