### ISSUE TITLE
The streaming plugin "edit" command ignores the empty string as new metadata

### ISSUE THREAD

**Issue by willamowius** [meetecho/janus-gateway#2208]
When you use the "edit" command, the streaming plugin will silently ignore the empty string as new metadata and leave the old metadata in place, even so an empty string is valid metadata when set through the config file.

**Comment by lminiero** [comment]
That's because we have a `strlen(json_string_value(md)) > 0` check in place.

**Comment by willamowius** [comment]
I would consider that a bug. I started with metadada = "" in the config, used the "edit" command to set it to something and when I tried to "edit" it back to empty it was ignored and keep the first edit in place.

**Comment by lminiero** [comment]
I'd argue that the actual bug might be we're not ignoring the empty string from the configuration file in the first place :slightly_smiling_face:  But on the other end, there's no way to reset a metadata string (e.g., set it to NULL), so the ability to set it to an empty string would be helpful.
