### ISSUE TITLE
Videoroom: switch operation and simulcast (VP8)

### ISSUE THREAD

**Issue by mtbramo** [meetecho/janus-gateway#2219]
I'm using switch operation to change from one publisher to another (using same codec, only video VP8).
I was surprised that we doesn't have "substream" and "temporal" present in the list of paremeters for that request. I have also checked the code and doesn't see any operation to reinitialize janus_rtp_simulcast_context on that operation (seen reinit of VP9 parameters but no VP8).

After some test, I think that we should have trouble, doesn't return to initial request substream_target if we get "falling back" (janus_rtp_simulcasting_context_process_rtp) during initial feed relay, then perform a switch to new one.

Regards.

**Comment by lminiero** [comment]
It's likely we didn't update "switch" when simulcast support was added at the time, or SVC for that matter. No time to look into it right now, sorry. If you can prepare a pull request with a fix, I'll be glad to review.

**Comment by mtbramo** [comment]
Thanks, I'll try to find some time to prepare a fix.

**Comment by lminiero** [comment]
I ended up working on a patch myself, as it seemed easy enough to add. I didn't test it, so you may want to do that yourself.

**Comment by mtbramo** [comment]
I have done it too, so I could compare and check (I could only check VP8 with our platform).

Thanks.
