### ISSUE TITLE
Compilation error srtp on raspberry pi

### ISSUE THREAD

**Issue by XPModder** [meetecho/janus-gateway#2224]
I cannot compile janus-gateway on the raspberry pi zero w. I have followed the instructions exactly and I am trying to compile without websockets, data-channels, rabbitmq and docs. I installed all dependencies and running -/configure doesnt throw any errors, but when I run make, I always get multiple of the same error.
/home/pi/janus-gateway/dtls.c undefined reference to 'srtp_crypto_policy_set_aes_gcm_256_16_auth'

I get this error 8 times always with that file and lines between 860 and 902. 

I have both the latest version of libsrtp2-dev and libsrtp0-dev installed. (I cannot install libsrtp-dev, it will always choose libsrtp0-dev instead)

I used this command to install all the dependencies:
sudo apt-get install libmicrohttpd-dev libjansson-dev libnice-dev libssl-dev libsrtp-dev libsofia-sip-ua-dev libglib2.0-dev libopus-dev libogg-dev libini-config-dev libcollection-dev pkg-config gengetopt libtool automake dh-autoreconf

**Comment by alexamirante** [comment]
https://janus.conf.meetecho.com/docs/FAQ#aesgcm
