### ISSUE TITLE
Janus-Gateway-Js Documentation / Samples

### ISSUE THREAD

**Issue by Namec** [meetecho/janus-gateway#2226]
Dear All,

i recently get on meetecho Janus, and i think this was made for me :-)

being new to Javascripts, i am wondering if there is more detailed docs on how to use the Javascript API or any working samples with official library

by the way i am working on react.

may the force be with you all

**Comment by lminiero** [comment]
https://janus.conf.meetecho.com/docs/
For other questions, please use the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
