### ISSUE TITLE
instruction about installing libwebsockets for x86_64

### ISSUE THREAD

**Issue by jamken** [meetecho/janus-gateway#2227]
Hi, all
In the README.md of janus-gateway, it tell me these instruction to install libwebsockets, like 
```
git clone https://libwebsockets.org/repo/libwebsockets
cd libwebsockets
# If you want the stable version of libwebsockets, uncomment the next line
# git checkout v3.2-stable
mkdir build
cd build
# See https://github.com/meetecho/janus-gateway/issues/732 re: LWS_MAX_SMP
cmake -DLWS_MAX_SMP=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..
make && sudo make install
```

but as for x86_64 machine, these instrution would install libwebsockets.so into /usr/lib in case janus websocket transport cannot found this library. The correct install location for library on x86_64 is /usr/lib64. To install libwebsockets.so into /usr/lib64, the instruction should be (according to official document from lws): 
```
git clone https://libwebsockets.org/repo/libwebsockets
cd libwebsockets
# If you want the stable version of libwebsockets, uncomment the next line
# git checkout v3.2-stable
mkdir build
cd build
# See https://github.com/meetecho/janus-gateway/issues/732 re: LWS_MAX_SMP
cmake -DLWS_MAX_SMP=1 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DLIB_SUFFIX=64 -DCMAKE_C_FLAGS="-fpic" ..
make && sudo make install
```

maybe README.md should be updated? :)

**Comment by lminiero** [comment]
No, it shouldn't. It's written more than once as a note, for other libraries too, that the folder to install to may be different depending on architecture and distro. Closing.
