### ISSUE TITLE
Opening, then closing, then trying to open Websocket connect again causes error

### ISSUE THREAD

**Issue by Computician** [meetecho/janus-gateway#223]
For each request, a new session is created and plugin attached and then detached and destroyed after synchronously waiting for the request return value.

So, 

```
InitializeConnection() //get session
AttachPluginHandle()
MakeRequest() //this will create a video room
DetachPluginHandle
DestroySession() //

```

This is done with the websocket interface. Almost half of the time, a request is not processed correctly due to the error `[1430923487:3918] WARN: error on reading from skt` and then half of the time after that error, I get a libmicrohttpd crash(for some reason, the SKT failure sometimes makes the subsequent request a REST one which then causes the other issue I have open about libmicrohttpd crashes #212 ). 

I can reliably recreate this by making a session, request, destroy session.

**Comment by Computician** [comment]
Forget that last part, it is not Janus failing back on REST, it is my code that tries to make a REST request after the SKT error and then consequently kills the libmicrohttpd

**Comment by lminiero** [comment]
Not sure what the problem is: libmicrohttpd doesn't handle websockets, libwebsockets does.

**Comment by Computician** [comment]
this was on me and how I was handling connections

**Comment by lminiero** [comment]
Right, a timeout in Janus should result in the connection being closed on our end, which might explain why you were getting that.
