### ISSUE TITLE
Timeout expired for session

### ISSUE THREAD

**Issue by fidelhuang1** [meetecho/janus-gateway#2237]
I install janus, runing it, it work well, but  visit echotest click start, no work,  chek log

Janus commit: not-a-git-repo
Compiled on:  Thu Jun 18 23:30:54 CST 2020

Logger plugins folder: /opt/janus/lib/janus/loggers
[WARN] 	Couldn't access logger plugins folder...
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Server) v0.10.0
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Using 10.52.67.4 as local IP...
[WARN] Token based authentication disabled
Initializing recorder code
Using nat_1_1_mapping for public IP: 129.212.12.11
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
TURN server to use: webcall.xxxxx.com:3478 (udp)
TURN REST API backend: (disabled)
Crypto: OpenSSL pre-1.1.0
[WARN] The libsrtp installation does not support AES-GCM profiles
Fingerprint of our certificate: 1D:1B:51:32:B5:7E:03:00:42:19:35:AD:5B:0B:4E:C5:D2:CD:6E:5A:C5:1A:8A:95:5E:F5:C0:08:D0:49:1A:3C
Joining Janus requests handler thread
[WARN] Event handlers support disabled
Plugins folder: /opt/janus/lib/janus/plugins
Sessions watchdog started
Loading plugin 'libjanus_audiobridge.so'...
JANUS AudioBridge plugin initialized!
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_recordplay.so'...
JANUS Record&Play plugin initialized!
Loading plugin 'libjanus_sip.so'...
JANUS SIP plugin initialized!
Loading plugin 'libjanus_nosip.so'...
JANUS NoSIP plugin initialized!
Loading plugin 'libjanus_streaming.so'...
JANUS Streaming plugin initialized!
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
JANUS VideoRoom plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_textroom.so'...
JANUS TextRoom plugin initialized!
Transport plugins folder: /opt/janus/lib/janus/transports
Loading transport plugin 'libjanus_http.so'...
HTTP transport timer started
HTTP webserver started (port 8088, /janus path listener)...
HTTPS webserver started (port 8089, /janus path listener)...
[WARN] Admin/monitor HTTP webserver disabled
Admin/monitor HTTPS webserver started (port 7889, /admin path listener)...
JANUS REST (HTTP/HTTPS) transport plugin initialized!
Loading transport plugin 'libjanus_websockets.so'...
[WARN] libwebsockets has been built without IPv6 support, will bind to IPv4 only
libwebsockets logging: 0
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
[WARN] Admin WebSockets server disabled
[WARN] Secure Admin WebSockets server disabled
JANUS WebSockets transport plugin initialized!
Loading transport plugin 'libjanus_pfunix.so'...
[WARN] Unix Sockets server disabled (Janus API)
[WARN] Unix Sockets server disabled (Admin API)
[WARN] No Unix Sockets server started, giving up...
[WARN] The 'janus.transport.pfunix' plugin could not be initialized
WebSockets thread started
Creating new session: 20054955465164; 0x7faa100010c0
Timeout expired for session 20054955465164...
Destroying session 20054955465164; 0x7faa100010c0

Timeout expired for session

**Comment by lminiero** [comment]
http://groups.google.com/d/forum/meetecho-janus
