### ISSUE TITLE
get 403 when send keepalive with curl from android

### ISSUE THREAD

**Issue by jameszhong2008** [meetecho/janus-gateway#2243]
sent http requestto janus server from android with curl, when the auth token and apisecret is not enable, works great.
after turn on the auth_token and apisecret, it connect successful, but when I send keeplive package, the server return 403.
Can anybody help me out of there, any suggestion is appreciate.

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
