### ISSUE TITLE
How do i change room number in audio conference ?

### ISSUE THREAD

**Issue by espeniel76** [meetecho/janus-gateway#2244]
Hello.

I'm developing voice conference call messenger with janus gateway.
but, i have a problem.
the problem is can not create room.
it works at room number 1234, but other number is not work.
my source is it from janus demo page. that is reason?
Or should I use other code that works?
or, Should I purchase the full version?

thanks

**Comment by lminiero** [comment]
https://groups.google.com/forum/?oldui=1#!forum/meetecho-janus
