### ISSUE TITLE
Have problem with compilate

### ISSUE THREAD

**Issue by Zudva** [meetecho/janus-gateway#2248]
Hi!  Why im not can compilate? 

Where can I find the error log?

---CODE---

`which git` rev-parse HEAD | awk 'BEGIN {print "#include \"version.h\""} {print "const char *janus_build_git_sha = \"" $0"\";"} END {}' > version.c
echo "Wed Jun 24 15:33:58 MSK 2020" | awk 'BEGIN {} {print "const char *janus_build_git_time = \""$0"\";"} END {} ' >> version.c
echo "103" | awk 'BEGIN {} {print "int janus_version = "$0";"} END {} ' >> version.c
echo "0.10.3" | awk 'BEGIN {} {print "const char *janus_version_string = \""$0"\";"} END {} ' >> version.c
pkg-config --modversion nice | awk 'BEGIN {} {print "const char *libnice_version_string = \""$0"\";"} END {} ' >> version.c
make  all-recursive
make[1]: Entering directory '/home/user/janus-gateway'
Making all in html
make[2]: Entering directory '/home/user/janus-gateway/html'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/user/janus-gateway/html'
make[2]: Entering directory '/home/user/janus-gateway'
`which git` rev-parse HEAD | awk 'BEGIN {print "#include \"version.h\""} {print "const char *janus_build_git_sha = \"" $0"\";"} END {}' > version.c
echo "Wed Jun 24 15:33:58 MSK 2020" | awk 'BEGIN {} {print "const char *janus_build_git_time = \""$0"\";"} END {} ' >> version.c
echo "103" | awk 'BEGIN {} {print "int janus_version = "$0";"} END {} ' >> version.c
echo "0.10.3" | awk 'BEGIN {} {print "const char *janus_version_string = \""$0"\";"} END {} ' >> version.c
pkg-config --modversion nice | awk 'BEGIN {} {print "const char *libnice_version_string = \""$0"\";"} END {} ' >> version.c
  CC       janus-version.o
  CCLD     janus
janus-dtls.o: In function `janus_dtls_srtp_incoming_msg':
/home/user/janus-gateway/dtls.c:861: undefined reference to `srtp_crypto_policy_set_aes_gcm_256_16_auth'
/home/user/janus-gateway/dtls.c:862: undefined reference to `srtp_crypto_policy_set_aes_gcm_256_16_auth'
/home/user/janus-gateway/dtls.c:896: undefined reference to `srtp_crypto_policy_set_aes_gcm_256_16_auth'
/home/user/janus-gateway/dtls.c:897: undefined reference to `srtp_crypto_policy_set_aes_gcm_256_16_auth'
/home/user/janus-gateway/dtls.c:900: undefined reference to `srtp_crypto_policy_set_aes_gcm_128_16_auth'
/home/user/janus-gateway/dtls.c:901: undefined reference to `srtp_crypto_policy_set_aes_gcm_128_16_auth'
/home/user/janus-gateway/dtls.c:865: undefined reference to `srtp_crypto_policy_set_aes_gcm_128_16_auth'
/home/user/janus-gateway/dtls.c:866: undefined reference to `srtp_crypto_policy_set_aes_gcm_128_16_auth'
collect2: error: ld returned 1 exit status
Makefile:1870: recipe for target 'janus' failed
make[2]: *** [janus] Error 1
make[2]: Leaving directory '/home/user/janus-gateway'
Makefile:3271: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/janus-gateway'
Makefile:1464: recipe for target 'all' failed
make: *** [all] Error 2

---///CODE---

**Comment by avdance** [comment]
Did you install libsrtp ?

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/discuss-webrtc

**Comment by Zudva** [comment]
> https://groups.google.com/forum/#!forum/discuss-webrtc

Thank you!

**Comment by Zudva** [comment]
@avdance yes, i download and compiled it.

This problem with libsrtp, you think?
