### ISSUE TITLE
Video on localhost without any network interfaces

### ISSUE THREAD

**Issue by asmyasnikov** [meetecho/janus-gateway#2251]
Hi!
I'm have some issue with configure janus on host without any network interfaces (only localhost). STUN and TURN servers are unavailable. 
I need to show video from janus (for example grab v4l device to local browser and push to janus through ffmpeg) in local browser.
I have 2 network configurations: without any network interfaces and with hotplugged usb-ethernet controller. In last case video successfully show in local and remote browser. In first case video cannot showing in local browser. Both cases - intranet (STUN and TURN servers are unavailable).
I'm tryied to change many config variables in `janus.jcfg`: `ice_ignore_list`, `ice_enforce_list`, `full_trickle`, `ice_tcp`, `ice_lite` and other. Bad get fail for show video in local browser if nothing networks interfaces.
How to configure janus for local showing video without any network interfaces.
Janus version: 0.10.2 (I have such issue in 0.7.2 and 0.9.6)

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
