### ISSUE TITLE
ICE Failed

### ISSUE THREAD

**Issue by jeverd** [meetecho/janus-gateway#2254]
So running janus in docker on AWS EC2. Seems to be getting ICE failed error for some users, while others its fine. Added the nat_mapping, and specified STUN servers in `janus.jcfg`.   Don't really know whats going on, any ideas?

The specific error is `[WARN] [3574748659155302] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)`

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
