### ISSUE TITLE
server optimize video audio

### ISSUE THREAD

**Issue by gushenjie** [meetecho/janus-gateway#2255]
Hello, I tried to make audio and video calls in mainland China and Taiwan, and found that even if the video is at 640x480, 1 megabit rate, there will be packet loss in the video stream. Is there an optimized method? In the case of pure audio, the content may be lost intermittently. The server version I use is 0.9.5. Is the latest server version optimized for the above issues?

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
