### ISSUE TITLE
Frame Freezing issue janus

### ISSUE THREAD

**Issue by manumenon** [meetecho/janus-gateway#2259]
i am using Janus streaming plugin to stream my video feed into UI. From the backend side, i am using python and FFmpeg to process the incoming RTSP stream and publish it. i am adding my  FFmpeg pipeline here. From UI when i am playing it freezes. This is like a production issue for Us. I am new to the WEBrtc concept. Everything is in  same machine and i am using the private IP of the machine to communicate 

______________________________________________________
import cv2
import numpy as np
from datetime import datetime
import os
import subprocess as sp

font = cv2.FONT_HERSHEY_SIMPLEX
width1, height1 = 480, 270
command = [
    "ffmpeg",
    "-y",
    "-f",
    "rawvideo",
    "-vcodec",
    "rawvideo",
    "-pix_fmt",
    "bgr24",
    "-s",
    f"{width1}x{height1}",
    "-i",
    "-",
    "-c:v",
    "libvpx",
    '-pix_fmt', 'yuv420p',
    "-crf",
    "30",
    "-b:v",
    "800K",
    "-r",
    "16",
    "-f",
    "rtp", '{}'.format(os.environ.get("RPT_PORT","rtp://192.168.1.47:10027?pkt_size=1300"))
 
]

proc = sp.Popen(command, stdin=sp.PIPE, shell=False)

def create_blank(width, height):
    image = np.random.randint(255, size=(height, width, 3))  # np.zeros((height, width, 3), np.uint8)
    image = image.astype(np.uint8)
    t = datetime.now().ctime()
    return image

def put_tme(image):
    t = datetime.now().ctime()
    cv2.putText(image, '{}'.format(t), (int(width1 / 4.3), int(height1 / 2)), font, .6, (255, 255, 255), 2, cv2.LINE_AA)
    return image
image = create_blank(width1, height1)
while True:
    img=  put_tme(image.copy())
    proc.stdin.write(img.tostring())
    ret = cv2.waitKey(10)
    if ret == 27:
        break

cv2.destroyAllWindows()
________________________________________________
The above code is something i use to test. this is also breaking for me. pls help

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by manumenon** [comment]
> https://groups.google.com/forum/#!forum/meetecho-janus

sir  @lminiero . no one is replying to this group. I think the project is dead. Because this was a critical issue for me I lost my project

**Comment by lminiero** [comment]
The project is very much alive. If you expect people to jump to help you, you don't understand the concept of "community" much. We don't work for you, and neither to them.

**Comment by manumenon** [comment]
> The project is very much alive. If you expect people to jump to help you, you don't understand the concept of "community" much. We don't work for you, and neither to them.

i added a doubt like 4/5 week back. no one is here to reply. I do understand it's a community version and I am ready to help people.  what should I do.  i don't want people to jump. but at least point me in some direction so i could get it fixed.
