### ISSUE TITLE
DataChannell version 0.10.2 

### ISSUE THREAD

**Issue by gushenjie** [meetecho/janus-gateway#2262]
Hello, I updated the server version here.After the update, I found that the Android side sends a message to the Web side through the DataChannel.The Web side can receive the message, but the Web side sends the message to the Android side, and the Android side cannot receive the message. Can it be received by sending on the web, is this a bug after updating the server?

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus
