### ISSUE TITLE
Error while attempting to do video streaming on the demo website on iPad

### ISSUE THREAD

**Issue by amarantedaniel** [meetecho/janus-gateway#2263]
This is a live website issue, I've been trying to implement video streaming and using the demo code as an example but I believe there are issues on iOS

This is the error I got while trying to stream on iPad (same error happens on both chrome and safari browsers):

![IMG_0021](https://user-images.githubusercontent.com/7462237/86470128-2caf4880-bd11-11ea-91c1-dee05d49b5dc.PNG)

I can try to provide more info if you think this is a real issue

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by amarantedaniel** [comment]
Hi @lminiero this is not my code, it is an error on the live website, that's why I posted it as an issue. 

I will post in on the group then.

It would be helpful if you provide more info instead of just pasting the google group link. It's not very friendly to just post the link like that.

**Comment by lminiero** [comment]
> It would be helpful if you provide more info instead of just pasting the google group link. It's not very friendly to just post the link like that.

If I started providing more info for each issue opened by people that don't read the guidelines, I wouldn't have time to do anything else. It's what I've done for 6 years, now, and I'm getting tired of it. Questions belong to the group, not here: this is clearly not a code issue, as the template you deleted told you.

**Comment by amarantedaniel** [comment]
I didn't delete any templates. I went to https://janus.conf.meetecho.com/streamingtest.html and clicked the buttons.

But that's ok, I will post it on the group then, sorry about that.

**Comment by lminiero** [comment]
I'm talking about the issue template.

> If you want to open an issue, please make sure that:
>
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved in master;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available [here](http://janus.conf.meetecho.com/docs/debug.html)).
>
> If so, just remove this text and share your findings!

I'll have to make the text clearer, even though that probably wouldn't help, since I don't think anyone reads it anyway.
