### ISSUE TITLE
Passing additional parameters in creating audio room with websockets (js)

### ISSUE THREAD

**Issue by this-marwan** [meetecho/janus-gateway#2264]
Hello!
I'm currently trying to create an audio room using the Javascript API (using websockets) and would like to pass parameters concerning audio level events. I can successfully create an audio room (and join rooms) but I can't seem to add additional parameters besides the token and api secret. 

Not sure if I missed something, but a look at the source code seems to show that creating a session using websockets does not look for any additional parameters (besides token and api secret) to add to the request : https://github.com/meetecho/janus-gateway/blob/3dadb5c13b3a1f6d0c6374b4072fd1f20fbe798d/html/janus.js#L815-L838

I'm thinking my current workaround would be to create the audio room and then edit it (haven't tried it yet).

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/.github/ISSUE_TEMPLATE.md

> 1. We only use GitHub for code issues, NOT for connectivity/negotiation/WebRTC issues or questions: for those, use the meetecho-janus group instead.

http://groups.google.com/d/forum/meetecho-janus
