### ISSUE TITLE
android janus client

### ISSUE THREAD

**Issue by gushenjie** [meetecho/janus-gateway#2268]
Hello, is there a relatively new android native project combined with janus service? https: //github.com/benwtrent/janus-gateway-android This version has not been updated for 5 years. If so, can you update it?

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/.github/ISSUE_TEMPLATE.md

> 1. We only use GitHub for code issues, NOT for connectivity/negotiation/WebRTC issues or questions: for those, use the meetecho-janus group instead.

http://groups.google.com/d/forum/meetecho-janus
