### ISSUE TITLE
Streaming is not working on ipad safari

### ISSUE THREAD

**Issue by salimbasar** [meetecho/janus-gateway#2269]
When i test demos i see that streaming is not working on ipad safari. Other are working without any problem.

my ipad is 5th generation. 

> **IMPORTANT! READ OR WE WILL JUST CLOSE YOUR ISSUE!**
>
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.
> 2. If you think you really found a bug, make sure nobody reported it already (do a search first, and check open issues);
> 3. Make sure the issue wasn't already solved in master: we will ignore the issue otherwise.
> 4. Do **NOT** paste large amounts of text inline in the issue or comments: it makes the exchanges much harder to follow. If you need to provide logs or code snippets, either use a service like [pastebin](http://pastebin.com/) and [gist](https://gist.github.com/), or use the `details` and code block Markdown features to collapse them.
> 5. If you're encountering crashes, make sure you provide a useful trace of what happened: depending on the issue, we may need output from AddressSanitizer or GDB stacktraces (more details available [here](http://janus.conf.meetecho.com/docs/debug)).
>
> If you understood the guidelines, please do remove this text and share your findings. Notice that if you remove this text without reading the guidelines, or you just ignore them, we'll close the issue without further explanation.

**Comment by lminiero** [comment]
Maybe read the guidelines again?
