### ISSUE TITLE
Websocket accepted subprotocol

### ISSUE THREAD

**Issue by borist2** [meetecho/janus-gateway#2270]
Hi,

I was trying to implement application that communicates with Janus using websockets. I found out that if more than one subprotocol is specified in header Sec-WebSocket-Protocol, Janus will return all those subprotocols as accepted. I think this is not correct and instead it should return only single accepted subprotocol.
For example if I specify `Sec-WebSocket-Protocol: janus-protocol, test-janus-protocol`, Janus returns same header, instead of just `Sec-WebSocket-Protocol: janus-protocol`.

**Comment by lminiero** [comment]
That part is done by libwebsockets, so I'm not sure there's anything we can do ourselves to fix that. We already only "register" the subprotocols we'll deal with. You may want to open an issue on their github to see if it's indeed a problem there. Closing, feel free to reopen if it turns up we can fix it here too.
