### ISSUE TITLE
Screen Sharing in Video Room Integration

### ISSUE THREAD

**Issue by aakash141991** [meetecho/janus-gateway#2272]
Dear Team,

I have used the videoroomtest and integrated video conferencing successfully. But I want to integrate the screen sharing also in my video room. How can I start the screen sharing in the video room where users are connected.

videoroom plugin already attached for video conferencing
janus.attach(
		{
	         plugin: "janus.plugin.videoroom",

Screensharing also uses videoroom plugin. How to do this. Please help.

Any help will be appreciated. 

Regards,
Aakash

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/.github/ISSUE_TEMPLATE.md

> 1. We only use GitHub for code issues, NOT for connectivity/negotiation/WebRTC issues or questions: for those, use the meetecho-janus group instead.

http://groups.google.com/d/forum/meetecho-janus

**Comment by fanlion** [comment]
i have same problem, sharing screen and camera in same room and same time.
