### ISSUE TITLE
Invalid element (ptype) error when try to subscribe to a publisher

### ISSUE THREAD

**Issue by DilsMatchanov** [meetecho/janus-gateway#2282]
I use Janus videoroom plugin and try to subscribe to a publisher using this request:

```javascript
{
  janus: "message",
  transaction: "joinSubscriber",
  body: {
    request : "join",
    ptype : "subscriber",
    room: 420436192888300,
    feed: 4984714098599738
  },
  session_id: 8001049884565230,
  handle_id: 410813247328185
}
```

and after that I get this error:
```javascript
{
  janus: "event",
  session_id: 8001049884565230,
  sender: 410813247328185,
  transaction: "joinSubscriber",
  plugindata: {
    data: {
      error: "Invalid element (ptype)",
      error_code: 430,
      videoroom: "event",
    }
  }
}
```

I am almost sure that this is not a bug and I have missed something but I have spent a whole day trying to solve this. Hope you can help me.

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/.github/ISSUE_TEMPLATE.md

> 1. We only use GitHub for code issues, NOT for connectivity/negotiation/WebRTC issues or questions: for those, use the meetecho-janus group instead.

http://groups.google.com/d/forum/meetecho-janus
