### ISSUE TITLE
[ERR] [plugins/janus_videoroom.c:janus_videoroom_handler:6243] No such room [7446206134035959] Sending event to transport...

### ISSUE THREAD

**Issue by taojishou** [meetecho/janus-gateway#2283]
When we exit the videoroom and re-enter, it prompts questions like this.
we didn't close websocket，just send  {"request" : "leave"}.
Is it necessary to close websocket?

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/.github/ISSUE_TEMPLATE.md

> 1. We only use GitHub for code issues, NOT for connectivity/negotiation/WebRTC issues or questions: for those, use the meetecho-janus group instead.

http://groups.google.com/d/forum/meetecho-janus
