### ISSUE TITLE
error: libmicrohttpd not found

### ISSUE THREAD

**Issue by gcodedota** [meetecho/janus-gateway#2284]
Hi there,
I'm having issue upgrading to version ```0.10.3```. I used version ```0.9.0``` with flag ```--enable-rest``` on, and everything was working fine.
But during the upgrade, this issue ```configure: error: libmicrohttpd not found. See README.md for installation instructions or use --disable-rest ``` pop up.
Im pretty sure I already installed those packages
```
Step 32/41 : RUN dpkg -l | grep libmicrohttp
 ---> Running in 247ebb03ca4f
ii  libmicrohttpd-dev             0.9.44+dfsg-1ubuntu2                     amd64        library embedding HTTP server functionality (development)
ii  libmicrohttpd10               0.9.44+dfsg-1ubuntu2                     amd64        library embedding HTTP server functionality
```
can someone help me pls

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/.github/ISSUE_TEMPLATE.md

> 1. We only use GitHub for code issues, NOT for connectivity/negotiation/WebRTC issues or questions: for those, use the meetecho-janus group instead.

http://groups.google.com/d/forum/meetecho-janus
