### ISSUE TITLE
Janus Crashing with segmentation Fault

### ISSUE THREAD

**Issue by ajay-psd** [meetecho/janus-gateway#2287]
Hi,

I have build Janus latest master branch v0.10.4,  
I have used HTTP transport and implemented videoroom application.  Janus crashes with Segmentation Fault,  this happens always after any session destroyed event is triggered form client.

I am not sure if any wrong thing i have made. Please check and suggest.

Here is core-dump debug
https://gist.github.com/ajay-psd/4142f16c5e92cd95a93dad9ac1345361

here is built info for reference, one warning in compilation
https://gist.github.com/ajay-psd/f372b7d86a4eed72c0938611ae497fd0

**Comment by lminiero** [comment]
Try getting a libasan dump too: https://janus.conf.meetecho.com/docs/debug

**Comment by ajay-psd** [comment]
Hi Tried getting libasan dump using
CFLAGS="-O1 -g3 -ggdb3 -fno-omit-frame-pointer -fsanitize=address -fno-sanitize-recover=all -fsanitize-address-use-after-scope" LDFLAGS="-fsanitize=address" ./configure --prefix=/opt/janus

but not able to configure
[root@dev-webrtc janus-gateway]# vim config.log 

configure:3662: $? = 0
configure:3651: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)
configure:3662: $? = 0
configure:3651: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3662: $? = 4
configure:3651: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3662: $? = 4
configure:3682: checking whether the C compiler works
configure:3704: gcc -O1 -g3 -ggdb3 -fno-omit-frame-pointer -fsanitize=address -fno-sanitize-recover=all -fsanitize-address-use-after-scope  -fsanitize=address conftest.c  >&5
gcc: error: unrecognized command line option '-fno-sanitize-recover=all'
gcc: error: unrecognized command line option '-fsanitize-address-use-after-scope'
configure:3708: $? = 1
configure:3746: result: no
configure: failed program was:


Later I updated my gcc  4.8 to gcc 7 and have bulid again janus from scratch.
Now janus i not crashing. It looks working fine.  I will check and test more times and update here

Thanks!.

**Comment by atoppi** [comment]
There is a typo in
`fsanitize-address-use-after-scope`

**Comment by lminiero** [comment]
Sorry, but I don't have time to get into this. Plenty of tutorials around on how to get libasan running. When you have a dump to share (as a pastebin/gist link, NOT inline), please do.

**Comment by ajay-psd** [comment]
Thanks Lorenzo,
after updating to gcc7 and recompiling janus,  janus is not crashing now.  I will update libasan dump if any such case i encounter.
