### ISSUE TITLE
make error:postprocessing/pp-av1.c:98:40: error: ‘AV_CODEC_ID_AV1’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by yuexiajiayan** [meetecho/janus-gateway#2293]
libavutil      55. 34.101 / 55. 34.101
libavcodec     57. 64.101 / 57. 64.101
libavformat    57. 56.101 / 57. 56.101
libavdevice    57.  1.100 / 57.  1.100
libavfilter     6. 65.100 /  6. 65.100
libavresample   3.  1.  0 /  3.  1.  0
libswscale      4.  2.100 /  4.  2.100
libswresample   2.  3.100 /  2.  3.100
libpostproc    54.  1.100 / 54.  1.100

in avcodec.h have no AV_CODEC_ID_AV1?

**Comment by chadfurman** [comment]
Why did you close this issue?  I'm having the same problem

**Comment by chadfurman** [comment]
Ah, upgrade janus.  :+1:

**Comment by kmeyerhofer** [comment]
I'm having this same issue when trying to build janus on master.
@chadfurman Where is the fix when upgrading janus?

**Comment by chadfurman** [comment]
I literally pulled latest remote master into my local branch and it worked

**Comment by hiteshgarg14** [comment]
Hi, I am currently facing this issue. I tried installing multiple Janus releases using Docker. Is there any other dependency/package required to enable post-processing (like FFmpeg etc)?

**Comment by bskton** [comment]
Same problem with debian:stretch.
Have error `postprocessing/pp-av1.c:59:46: error: 'AV_CODEC_ID_AV1' undeclared (first use in this function)` while compiling janus 0.11.4.

**Comment by lminiero** [comment]
We only use `AV_CODEC_ID_AV1` if this check succeeds:

```
#if !LIBAVCODEC_VER_AT_LEAST(57, 25)
```

Not sure if the ffmpeg on Debian needs a higher version to have AV1 support.
