### ISSUE TITLE
Crash for unknown reasons

### ISSUE THREAD

**Issue by 648540858** [meetecho/janus-gateway#2300]
this is the log；
[https://gist.github.com/648540858/44135642522fe4fdb6f15865581c4c9a](https://gist.github.com/648540858/44135642522fe4fdb6f15865581c4c9a)

I added the field displayName. The modified file is in the log。I'm not sure that's what caused it。

**Comment by lminiero** [comment]
Clearly not master, as line numbers don't match. As clearly explained in the guidelines, you have to try master first, or we won't look at the issue.

**Comment by 648540858** [comment]
master
[https://gist.github.com/648540858/09962bf5974111c5f67c060ceba2d366](https://gist.github.com/648540858/09962bf5974111c5f67c060ceba2d366)

**Comment by lminiero** [comment]
Looks like a race condition where both sides are closed more or less at the same time: this commit https://github.com/meetecho/janus-gateway/commit/a6731baaf13b4b89268c5e47817598dc819972e9 should help address it. Closing for the time being, let us know if it's still not fixed.

**Comment by lminiero** [comment]
I wouldn't say "the problem remains", since it happens in a completely different place, which means the original issue has been solved. Busy now, I'll try to find time later or in the next few days.

**Comment by 648540858** [comment]
OK, I'm careless。

**Comment by lminiero** [comment]
Mh, looks like it's a similar issue: the peer is freed while we're using its structure. I guess we're missing sessions referencing each other when they're in a call to each other (or trying to establish a call), which might help prevent this. I'll try to work on a fix and let you know when there's a commit to try.

**Comment by lminiero** [comment]
Please check the above commit, to see if it fixes it for you.

**Comment by 648540858** [comment]
The crash took place further forward，The content is relatively small, I posted it directly
```
(gdb) bt
#0  0x00007ff05ffb33eb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ff05ff92899 in __GI_abort () at abort.c:79
#2  0x00007ff0607332fd in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ff0500f6c00 in janus_videocall_handler (data=<optimized out>) at plugins/janus_videocall.c:1285
#4  0x00007ff060711181 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ff060167669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#6  0x00007ff06008f2b3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by lminiero** [comment]
My fault, there was a copy/paste typo: https://github.com/meetecho/janus-gateway/commit/ef954f96c60b25f90935f107c6362d4a27ab3d47 should fix it.

**Comment by lminiero** [comment]
@648540858 any update? Can this be closed?

**Comment by 648540858** [comment]
I've been testing it for a day and it hasn't happened again. It's great
