### ISSUE TITLE
Build error on janus post-processor support

### ISSUE THREAD

**Issue by ajay-psd** [meetecho/janus-gateway#2303]
Hi All,

I have pulled latest master branch tried to build  janus/post-processor for recordings conversion.
But am unable to build janus with post-processor,  based on below error looks some bug in code.

can any suggest what need to be checked, 
I am not a C developer otherwise i would have try look for fix if in case any where in janus and give PR ; 

`  CC       postprocessing/janus_pp_rec-pp-h264.o `
`postprocessing/pp-h264.c: In function ‘janus_pp_h264_create`
`postprocessing/pp-h264.c:98:8: error: 'AVFormatContext {aka struct AVFormatContext}' has no member named video_codec; did you mean 'video_codec_id'?`
 ` fctx->video_codec = codec;`
   `     ^~~~~~~~~~~`
     `   video_codec_id`
make[2]: *** [postprocessing/janus_pp_rec-pp-h264.o] Error 1`

configure command
./configure  --prefix=/opt/janus30  --disable-all-transports --disable-all-handlers  --enable-post-processing --disable-all-plugins --enable-all-js-modules 

Here is full gits paste
https://gist.github.com/ajay-psd/dffc74b678f4b91bf26a76b13cd8dbea

building on/using AWS, centos7,  gcc7

**Comment by ajay-psd** [comment]
Here is full gits paste
https://gist.github.com/ajay-psd/dffc74b678f4b91bf26a76b13cd8dbea

i am using on building 
AWS,  centos7,  gcc7

**Comment by ajay-psd** [comment]
Hi  
This is fixed now. 
Looks like **libav** library was older/different version.

I have removed all libav*,  packages and reinstall libavcodec,libavformat,libavutil devel package, it got resolved.

Thanks

**Comment by lminiero** [comment]
Ack, closing then.
