### ISSUE TITLE
Janus Crashes on Start

### ISSUE THREAD

**Issue by PedroRTomas** [meetecho/janus-gateway#2305]
Hi, there
Following the instructions at https://janus.conf.meetecho.com/docs/debug
Here is the full output, including the AdressSanitizer info, that I've got when lunching Janus: https://paste.opensuse.org/20691090
If the problem is related to any of the warnings present, please let me know.

Note: I've followed the setup/configure options available at https://github.com/meetecho/janus-gateway/blob/master/README.md making a 'make configs' and lunching the server after it. (With no luck)

Any thoughts?
Thanks in advance!

**Comment by lminiero** [comment]
There are no lines, so it's impossible to say. The only info is that is seems to be crashing while initializing the WebSockets transport. Maybe you have a broken libwebsockets installation?

**Comment by PedroRTomas** [comment]
Is there any way to make lines appear? I've tried to install another version of libwebsockets, but the problem persists.
The problem seems to be related with a memory leak, no? The report says it is trying to read 'address 0x000000000000'

**Comment by lminiero** [comment]
Sorry, you'll have to figure out how to provide better dumps on your own. Closing as I believe this is an issue specific to your setup. Feel free to reopen if you can provide more detailed info on the error.
