### ISSUE TITLE
janus crash in videocall plugin

### ISSUE THREAD

**Issue by 648540858** [meetecho/janus-gateway#2306]
this is the log, 
[https://gist.github.com/648540858/d5b7360d612680bcc1c6d0ed1647bf8c](https://gist.github.com/648540858/d5b7360d612680bcc1c6d0ed1647bf8c)

**Comment by lminiero** [comment]
Not master.

**Comment by 648540858** [comment]
OK, I found a new submission and I'll try again with the new version。

**Comment by lminiero** [comment]
@648540858 closing as a month passed and we still didn't receive useful info, so I'll just assume it's fixed or you don't care anymore. Feel free to reopen if you can replicate with master.
