### ISSUE TITLE
Return is_private streams when valid admin_key is specified in request

### ISSUE THREAD

**Issue by makkarpov** [meetecho/janus-gateway#2308]
Currently there is no way to query private streams even for admin. If you lost ID of private stream, you can no longer interact with it, even delete.

So here is the feature request: check for `admin_key` in `list` request and when it is valid, return all streams regardless of their `is_private` flag.

**Comment by lminiero** [comment]
No time to work on that at the moment, sorry. We're about to go on vacation, so maybe at the end of the month. Pull requests welcome, of course.

**Comment by lminiero** [comment]
Just checked and it already works like this in all plugins with private resources. Closing.
