### ISSUE TITLE
Seg Fault while configuring

### ISSUE THREAD

**Issue by PedroRTomas** [meetecho/janus-gateway#2311]
Hi,
Is there a specific version of gcc that needs to be installed in order to run './configure' ?
Here are the 3 last lines before the seg fault occurred:
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... no
checking if gcc supports -c -o file.o... Segmentation fault

I've run this with valgrind and the report is available at: https://paste.opensuse.org/12965850
(Valgrind command use: sudo valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt ./configure --prefix=/opt/janus )

Besides gcc itself, is there any other package that can be responsible for this?

gcc version:
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

OS version:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Comment by atoppi** [comment]
It looks something is broken in your build chain, hence not something we could help with.
Should you not succeed with `gcc` for some reason, you might still try with `clang`.
