### ISSUE TITLE
No unique id for streaming plugin's onremotestream callback

### ISSUE THREAD

**Issue by skywalkershen** [meetecho/janus-gateway#2316]
The senario is there are multiple video containers on my web page, and each of them should pull a stream. Yet, after using {request: 'watch', id: xxx} in streaming plugin, streams returned in onremotestream callback all have identical id: 'janus'. There's no way I can tell what source the stream comes from, and which video container I should put the stream.

I do notice there is an issue 1459 mentioning that.

quoted: 

> As to the streamingtest.js demo, it has already been updated to the new janus.js callbacks. It still does NOT present those streams in a nice way, though: meaning that if you have, e.g., two video streams, you'll see both, but they won't have any label associated to that to have more context. I plan to update that later on.

I wonder whether there is any update about this, and whether you can give me some guide to fix this, like adding a source field in returned stream.

Thank you.

**Comment by lminiero** [comment]
Not an issue. All PeerConnections have the same format for strings, as that's core-specific, plugins have no say. You can very easily associate each stream to the correct handle already. Closing.

**Comment by AndyGura** [comment]
@lminiero Can you please leave a sample code or at least some details regarding this:

> You can very easily associate each stream to the correct handle already.

It is still not clear how to identify streams. Thank you!

**Comment by lminiero** [comment]
All the demos show how to do this.

**Comment by lamoboos223** [comment]
hi guys!

i had same issue like yours but i got it fixed now. so i added the [janus.js](https://github.com/lamoboos223/random/blob/main/janus.js) file where these is the method `onremotetrack` because the old `janus.js` has only `onremotestream` which return the first track of my multistream.

and this is the snippet on how to use it @AndyGura 


```js
 // Create session
    janus = new Janus(
        {
            server: server,
            success: function () {
                janus.attach({
                    plugin: "janus.plugin.streaming",
                    success: success,
                    onmessage: onmessage,
                    onremotetrack: onremotetrack,
                    error: function (error) {
                        console.error(error);
                    }
                });
            }
        });

function onremotetrack(track, mid, on, metadata) {
        stream = new MediaStream([track]);
        remoteTracks[mid] = stream;
        Janus.warn("Created remote video stream:", mid);
        if (mid == "v1") {
            Janus.attachMediaStream($('#video1').get(0), stream);
        }
        else if (mid == "v2") {
            Janus.attachMediaStream($('#video2').get(0), stream);
        }
        else if (mid == "v3") {
            Janus.attachMediaStream($('#video3').get(0), stream);
        }
    }

```
