### ISSUE TITLE
Error attaching plugin... Ooops: 460 No such plugin 'janus.plugin.textroom'

### ISSUE THREAD

**Issue by ansomkrd** [meetecho/janus-gateway#2317]
Good afternoon. Installed Janus in the end everything works except text chat. The configuration file is there, but for some reason it says that the plugin is not installed. I watched it in the regular demo. What could be the problem?

Can you also tell me which connection option is more stable?

Is there built-in noise reduction?

**Comment by groupboard** [comment]
If you check the output of "configure" you should see that the text room plugin isn't being compiled. Most likely it is because one of the required libraries is missing (probably usrsctp).

**Comment by atoppi** [comment]
> Can you also tell me which connection option is more stable?
Is there built-in noise reduction?

These are questions for the group.

As of the original issue, @groupboard is probably right, you're missing some dep for the textroom plugin.
Double check the output of the configure script.
