### ISSUE TITLE
libusrsctp not found. See README.md for installation instructions or use --disable-data-channels

### ISSUE THREAD

**Issue by neilyoung** [meetecho/janus-gateway#2320]
Hi,

I'm compiling Janus on a Raspberry PI 3B+, Buster Lite. Everything fine so far and the gateway works. Now I wanted to enable data channels. I ran `./configure` again with `--enable-data-channels` but got this error:

```
configure: error: libusrsctp not found. See README.md for installation instructions or use --disable-data-channels
```

AFAIK the only mentioning of libursctp in README is for the MacOS installation. I also cannot find how to install this dependency. 

Any pointer welcome

**Comment by neilyoung** [comment]
OK, found the answer here:

```
https://github.com/sctplab/usrsctp
```

(follow the [manual](https://github.com/sctplab/usrsctp/blob/master/Manual.md) link)

Maybe it is worth to add these instructions to the README.md for how to enable data channels. If you like, I can make this contribution (unless you have another idea):

```
# Install libursctp
git clone https://github.com/sctplab/usrsctp.git
cd usrsctp/
./bootstrap
./configure
make
sudo make install
```

**Comment by neilyoung** [comment]
Hmm. No. Maybe I did shoot too fast. The lib compiled, but can't be loaded at runtime

`./janus: error while loading shared libraries: libusrsctp.so.1: cannot open shared object file: No such file or directory
`

**Comment by neilyoung** [comment]
OK, solved by adding `/usr/local/lib` via `sudo nano /etc/ld.so.conf` and re-running `sudo ldconfig`

**Comment by atoppi** [comment]
Not sure which `README` did you read. We already have the instructions for compiling `usrsctp`:

> For what concerns usrsctp, which is needed for Data Channels support, it is usually not available in repositories, so if you're interested in them (support is optional) you'll have to install it manually. It is a pretty easy and standard process:
```git clone https://github.com/sctplab/usrsctp
cd usrsctp
./bootstrap
./configure --prefix=/usr && make && sudo make install
```
> Note: you may need to pass --libdir=/usr/lib64 to the configure script if you're installing on a x86_64 distribution.

Anyway closing the issue as this is not a code issue.
