### ISSUE TITLE
Two contact headers on registration using janus plugin sip

### ISSUE THREAD

**Issue by chris2016** [meetecho/janus-gateway#2321]
Hi,

we have a new instance of a Janus server and I think i found a bug regarding the SIP registration. Our Janus instance is on AWS. For STUN/TURN we use coturn. 

When I register a user Janus / SIP Plugin seems to handle the registration wrong.

When registering a phone I receive two registration attempts from the Janus Server. The firsty one contains one contact header with the local ip and the second register request contains the contact header twice with the local and public IP.

1. Register request

REGISTER sip:sipserver1.example.com:5061 SIP/2.0

Via: SIP/2.0/UDP 10.0.0.194:57945;rport;branch=z9hG4bKmtyB79gmFDK0Q
Max-Forwards: 70
From: <sip:70...@janus01.example.com:5060>;tag=mB1eQ4aU2HBrD
To: <sip:70...@janus01.example.com:5060>
Call-ID: d7e9186d-5858-1239-ec8e-0a0b996afee1
CSeq: 951586809 REGISTER
Contact: 7000 <sip:`7000`@**10.0.0.194:57945**>
Expires: 3600
User-Agent: WebRTC Gateway
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, UPDATE, REFER, MESSAGE, INFO, NOTIFY
Supported: replaces, path
Content-Length: 0

2. Register request contains two contact headers

REGISTER sip:sipserver1.example.com:5061 SIP/2.0
Via: SIP/2.0/UDP 10.0.0.194:58936;received=3.126.XX.XX;branch=z9hG4bK32B18HKe8a6rr;rport=58936
Max-Forwards: 70
From: <sip:70...@janus01.example.com:5060>;tag=28D1cN29c5ccc
To: <sip:70...@janus01.example.com:5060>
Call-ID: ac27054a-58df-1239-6ea4-0a0b996afee1
CSeq: 951601287 REGISTER
Contact: 7000 <sip:70...@3.126.XX.XX:58936;transport=udp>
Contact: 7000 <sip:70...@10.0.0.194:58936>;expires=0
Expires: 3600
User-Agent: WebRTC Gateway
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, UPDATE, REFER, MESSAGE, INFO, NOTIFY
Supported: replaces, path

That leads to a non reachable browser by the sip server because of the local IP.

Is that a bug or a misconfiguration? I posted that yesterday in the google group but further research today let me to the assumption that it is a bug so I posted it here

Cheers 
Chris

**Comment by chris2016** [comment]
I was doing more tests. When I remove behind_nat from the janus.plugin.sip.jcfg  
I only see one register attempt: 

Via: SIP/2.0/UDP 10.0.0.194:57945;rport;branch=z9hG4bKmtyB79gmFDK0Q
Max-Forwards: 70
From: sip:70...@janus01.example.com:5060;tag=mB1eQ4aU2HBrD
To: sip:70...@janus01.example.com:5060
Call-ID: d7e9186d-5858-1239-ec8e-0a0b996afee1
CSeq: 951586809 REGISTER
Contact: 7000 sip:`7000`@**10.0.0.194:57945**
Expires: 3600
User-Agent: WebRTC Gateway
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, UPDATE, REFER, MESSAGE, INFO, NOTIFY
Supported: replaces, path
Content-Length: 0

After enabling behind_nat I receive again two register requests and two contact headers. 

I treid your server without NAT and my SIP Server. If I exchange my gateway with your gateway hosted here https://janus.conf.meetecho.com/siptest.html it just works fine. So it is the registration process which is failing. Can you please advise what is wrong here? I am going to try to look through the code and find the issue but not sure If I am able to do so.

**Comment by lminiero** [comment]
If you're NATted, use `behind_nat` and then specify an `outbound_proxy` when registering. Closing as not an issue (it would be in the Sofia SIP library anyway, not our plugin), ask questions like this on the [group](http://groups.google.com/d/forum/meetecho-janus) instead.
