### ISSUE TITLE
janus server Distributed deployment

### ISSUE THREAD

**Issue by gushenjie** [meetecho/janus-gateway#2327]
Hello, how do you realize the distributed deployment of janus server and realize the media communication between different servers

**Comment by atoppi** [comment]
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.

Please ask questions like this on the group.
Not a code issue, closing.
