### ISSUE TITLE
iOS H264 issue in janus v0.10.5

### ISSUE THREAD

**Issue by kimilpyoung** [meetecho/janus-gateway#2330]
i used janus v0.10.5

transfer from iOS to janus video room with h264

All other devices(android, web) are visible in chromed 
but ios isn't

chrome sdp just 
"DOMException: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local answer sdp: Failed to set local video description recv parameters."

this doens't happen in version 0.9.0

When creating videoroom, h264_profile was also created with 42e01f but the error is same

**Comment by atoppi** [comment]
Does the same happen with Firefox or another ios device?
Would you mind sharing the SDP offer from Janus ?

**Comment by atoppi** [comment]
@kimilpyoung setting `h264_profile` will not force Janus SDP to contain that profile but it will just be the preferred profile in case multiple versions exist.
Can you share the SDP offer sent by the ios client ?

**Comment by tgabi333** [comment]
@kimilpyoung you would better to use vp8 in safari, from ios 13.5, the baseline profile (42e01f) - which is compatible with janus - had a very bad quality.

**Comment by kimilpyoung** [comment]
> That error (Failed to execute 'setLocalDescription' on 'RTCPeerConnection') will happen if you don't have the h264 profile set properly. How exactly are you creating the room?
> 
> You should definitely be seeing 42e01f in the fmtp line if the room is set correctly, so it looks like the room doesn't have the h264_profile set. Have you also set the "videocodec" parameter to "h264" for the room?

Yes, when I made a room, I set up codec h264 and h264_profile and sent it

**Comment by groupboard** [comment]
Can you post your code for creating the room (or room config file). And what are the exact steps to recreate? (Connect first on browser/ios version, then on ...?)

**Comment by kimilpyoung** [comment]
> @kimilpyoung 설정 `h264_profile`은 Janus SDP가 해당 프로필을 포함하도록 강제하지 않지만 여러 버전이있는 경우 선호하는 프로필입니다.
> iOS 클라이언트에서 보낸 SDP 제안을 공유 할 수 있습니까?

First, this is the create command sent when creating.
`var newRoom = {
                  "request": "create",
                  "room": channel,
                  "ptype": "publisher",
                  "display": ''+opaqueId,
                  "bitrate": bitrate,
                  "videoorient_ext": false,
                  "videocodec": "h264",
                  "h264_profile":"42e01f",
                  "publishers": 50
                };
`

And, This is an offer sdp sent from iOS to janus.

`v=0\r\no=- 1598312441093440 1 IN IP4 x.x.x.x
s=Mountpoint 1\r\nt=0 0\r\na=group:BUNDLE audio video
a=msid-semantic: WMS janus
m=audio 9 UDP\/TLS\/RTP\/SAVPF 111
c=IN IP4 x.x.x.x
a=sendonly
a=mid:audio
a=rtcp-mux
a=ice-ufrag:vCbP
a=ice-pwd:MCHrmuZHO8zHyXJVYdBm+P
a=ice-options:trickle\r\na=fingerprint:sha-256 C0:75:7B:E3:CC:FD:DA:27:45:55:A9:A4:1D:F2:86:94:37:B9:F5:4F:EF:AE:E2:09:59:7C:AD:03:F9:49:C2:FC
a=setup:actpass
a=rtpmap:111 opus 48000 2
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=msid:janus janusa0
a=ssrc:306353742 cname:janus
a=ssrc:306353742 msid:janus janusa0
a=ssrc:306353742 mslabel:janus
a=ssrc:306353742 label:janusa0
a=candidate:1 1 udp 2015363327 x.x.x.x 19074 typ host
a=end-of-candidates
m=video 9 UDP\/TLS\/RTP\/SAVPF 100 101
c=IN IP4 x.x.x.x
a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:vCbP
a=ice-pwd:MCHrmuZHO8zHyXJVYdBm+P
a=ice-options:trickle\r\na=fingerprint:sha-256 C0:75:7B:E3:CC:FD:DA:27:45:55:A9:A4:1D:F2:86:94:37:B9:F5:4F:EF:AE:E2:09:59:7C:AD:03:F9:49:C2:FC
a=setup:actpass
a=rtpmap:100 H264\/90000
a=fmtp:100 packetization-mode=1;
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtpmap:101 rtx\/90000
a=fmtp:101 apt=100
a=ssrc-group:FID 1122506908 1753778864
a=msid:janus janusv0
a=ssrc:1122506908 cname:janus
a=ssrc:1122506908 msid:janus janusv0
a=ssrc:1122506908 mslabel:janus
a=ssrc:1122506908 label:janusv0
a=ssrc:1753778864 cname:janus
a=ssrc:1753778864 msid:janus janusv0
a=ssrc:1753778864 mslabel:janus
a=ssrc:1753778864 label:janusv0
a=candidate:1 1 udp 2015363327 x.x.x.x 19074 typ host
a=end-of-candidates`

**Comment by kimilpyoung** [comment]
> @kimilpyoung 당신은 safari에서 vp8을 사용하는 것이 좋습니다 .iOS 13.5부터는 janus와 호환되는 기준 프로파일 (42e01f)의 품질이 매우 나쁩니다.

**Comment by kimilpyoung** [comment]
Sorry for the wrong click.

**Comment by groupboard** [comment]
Seems to work fine for me when I do that. What device are you running chrome on? Do you get a "success" reply to that message and then join the room? Also, just note that "ptype" is an invalid parameter for the "create" message. I'm not sure if it matters, but you could try removing that.

**Comment by kimilpyoung** [comment]
> 내가 할 때 잘 작동하는 것 같습니다. 어떤 기기에서 크롬을 실행하고 있습니까? 해당 메시지에 대한 "성공"응답을받은 다음 방에 참여합니까? 또한 "ptype"은 "create"메시지에 대해 잘못된 매개 변수입니다. 중요한지 잘 모르겠지만 제거해 볼 수 있습니다.
> 
> 또한 방이 이미있는 경우 "만들기"는 아무 작업도 수행하지 않으므로 janus를 중지하고 시작하여 오래된 방이 없는지 확인하십시오 (또는 서버를 다시 시작하지 않으려면 빈 방을 모두 삭제하십시오). ).

The device running chrome is mac (os X)
And  iOS is using native library(libjingle).

And, The server keeps restarting to recreate the videoroom.
I tried running it with chrome on window as well, but the issue is the same.

**Comment by atoppi** [comment]
@kimilpyoung 

> And, This is an offer sdp sent from iOS to janus.
```
v=0\r\no=- 1598312441093440 1 IN IP4 x.x.x.x
s=Mountpoint 1\r\nt=0 0\r\na=group:BUNDLE audio video
a=msid-semantic: WMS janus
m=audio 9 UDP/TLS/RTP/SAVPF 111
c=IN IP4 x.x.x.x
a=sendonly
a=mid:audio
a=rtcp-mux
a=ice-ufrag:vCbP
a=ice-pwd:MCHrmuZHO8zHyXJVYdBm+P
a=ice-options:trickle\r\na=fingerprint:sha-256 C0:75:7B:E3:CC:FD:DA:27:45:55:A9:A4:1D:F2:86:94:37:B9:F5:4F:EF:AE:E2:09:59:7C:AD:03:F9:49:C2:FC
a=setup:actpass
a=rtpmap:111 opus 48000 2
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=msid:janus janusa0
a=ssrc:306353742 cname:janus
a=ssrc:306353742 msid:janus janusa0
a=ssrc:306353742 mslabel:janus
a=ssrc:306353742 label:janusa0
a=candidate:1 1 udp 2015363327 x.x.x.x 19074 typ host
a=end-of-candidates
m=video 9 UDP/TLS/RTP/SAVPF 100 101
c=IN IP4 x.x.x.x
a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:vCbP
a=ice-pwd:MCHrmuZHO8zHyXJVYdBm+P
a=ice-options:trickle\r\na=fingerprint:sha-256 C0:75:7B:E3:CC:FD:DA:27:45:55:A9:A4:1D:F2:86:94:37:B9:F5:4F:EF:AE:E2:09:59:7C:AD:03:F9:49:C2:FC
a=setup:actpass
a=rtpmap:100 H264/90000
a=fmtp:100 packetization-mode=1;
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=ssrc-group:FID 1122506908 1753778864
a=msid:janus janusv0
a=ssrc:1122506908 cname:janus
a=ssrc:1122506908 msid:janus janusv0
a=ssrc:1122506908 mslabel:janus
a=ssrc:1122506908 label:janusv0
a=ssrc:1753778864 cname:janus
a=ssrc:1753778864 msid:janus janusv0
a=ssrc:1753778864 mslabel:janus
a=ssrc:1753778864 label:janusv0
a=candidate:1 1 udp 2015363327 x.x.x.x 19074 typ host
a=end-of-candidates
```

This does NOT look like an offer from your client. Are you sure ?

**Comment by kimilpyoung** [comment]
> 뿡 빵뀨
> 
> > 그리고 이것은 iOS에서 janus로 보낸 제안 sdp입니다.
> 
> ```
> v=0\r\no=- 1598312441093440 1 IN IP4 x.x.x.x
> s=Mountpoint 1\r\nt=0 0\r\na=group:BUNDLE audio video
> a=msid-semantic: WMS janus
> m=audio 9 UDP/TLS/RTP/SAVPF 111
> c=IN IP4 x.x.x.x
> a=sendonly
> a=mid:audio
> a=rtcp-mux
> a=ice-ufrag:vCbP
> a=ice-pwd:MCHrmuZHO8zHyXJVYdBm+P
> a=ice-options:trickle\r\na=fingerprint:sha-256 C0:75:7B:E3:CC:FD:DA:27:45:55:A9:A4:1D:F2:86:94:37:B9:F5:4F:EF:AE:E2:09:59:7C:AD:03:F9:49:C2:FC
> a=setup:actpass
> a=rtpmap:111 opus 48000 2
> a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
> a=msid:janus janusa0
> a=ssrc:306353742 cname:janus
> a=ssrc:306353742 msid:janus janusa0
> a=ssrc:306353742 mslabel:janus
> a=ssrc:306353742 label:janusa0
> a=candidate:1 1 udp 2015363327 x.x.x.x 19074 typ host
> a=end-of-candidates
> m=video 9 UDP/TLS/RTP/SAVPF 100 101
> c=IN IP4 x.x.x.x
> a=sendonly
> a=mid:video
> a=rtcp-mux
> a=ice-ufrag:vCbP
> a=ice-pwd:MCHrmuZHO8zHyXJVYdBm+P
> a=ice-options:trickle\r\na=fingerprint:sha-256 C0:75:7B:E3:CC:FD:DA:27:45:55:A9:A4:1D:F2:86:94:37:B9:F5:4F:EF:AE:E2:09:59:7C:AD:03:F9:49:C2:FC
> a=setup:actpass
> a=rtpmap:100 H264/90000
> a=fmtp:100 packetization-mode=1;
> a=rtcp-fb:100 nack
> a=rtcp-fb:100 nack pli
> a=rtcp-fb:100 goog-remb
> a=extmap:1 urn:ietf:params:rtp-hdrext:sdes:mid
> a=rtpmap:101 rtx/90000
> a=fmtp:101 apt=100
> a=ssrc-group:FID 1122506908 1753778864
> a=msid:janus janusv0
> a=ssrc:1122506908 cname:janus
> a=ssrc:1122506908 msid:janus janusv0
> a=ssrc:1122506908 mslabel:janus
> a=ssrc:1122506908 label:janusv0
> a=ssrc:1753778864 cname:janus
> a=ssrc:1753778864 msid:janus janusv0
> a=ssrc:1753778864 mslabel:janus
> a=ssrc:1753778864 label:janusv0
> a=candidate:1 1 udp 2015363327 x.x.x.x 19074 typ host
> a=end-of-candidates
> ```
> 
> 이것은 귀하의 고객의 제안처럼 보이지 않습니다. 확실합니까 ?

This Sdp is created by iOS.

**Comment by lminiero** [comment]
> This Sdp is created by iOS.

It clearly isn't, since it has `janus` all over. That's the SDP sent by Janus. As a side note, as explicitly written in the guidelines, please do NOT paste huge bunches of text (including SDPs) inline here, but use pastebin/gist or something else instead.

**Comment by kimilpyoung** [comment]
Sorry. Confused with another offer.
Real Offer sdp is this url : 
[](https://pastebin.pl/view/b4cac7a9)

42e01f profile doesn't seem to be suggested

**Comment by lminiero** [comment]
If the device doesn't offer that profile, how is Janus expected to set it in the answer?

**Comment by atoppi** [comment]
as a side note: while checking this issue [we have found out and fixed](https://github.com/meetecho/janus-gateway/commit/fc4a91f63ad0594c09ab13a12a9dcc1a6c8b2f33) a problem that caused Janus to reject the video m-line if a participant tries to publish himself for a second time using a h264 profile different from the one configured in the video room.

**Comment by kimilpyoung** [comment]
> If the device doesn't offer that profile, how is Janus expected to set it in the answer?

It was a question of whether there was any change in the way it was handled in the previous version.
Based on the suggested profile, janus will set up an answer.

**Comment by kimilpyoung** [comment]
> as a side note: while checking this issue [we have found out and fixed](https://github.com/meetecho/janus-gateway/commit/fc4a91f63ad0594c09ab13a12a9dcc1a6c8b2f33) a problem that caused Janus to reject the video m-line if a participant tries to publish himself for a second time using a h264 profile different from the one configured in the video room.

Thank you. We will try again with the latest version of the commit

**Comment by lminiero** [comment]
> It was a question of whether there was any change in the way it was handled in the previous version.
> Based on the suggested profile, janus will set up an answer.

The only change is that Janus now allows plugins to prefer a profile over another, which is what we try to do. If the profile isn't there, though (which is your case), we'll answer with the first profile we find (which is what we did before).

**Comment by amnonbb** [comment]
#2211
The same problem here for Safari and Firefox. In my case i use h264 codec. So i don't what happen with others (vp8, vp9)

**Comment by kimilpyoung** [comment]
But... It doesn't seem to be resolved yet.

Let’s try and find the cause

**Comment by atoppi** [comment]
As already mentioned, there is nothing wrong in Janus here.
Your iOS client seems to offer a h264 profile different from the common `42e01f`.

Try to use `42e034` in the room configuration as it is the only baseline profile offered by your client.
Hopefully Chrome and other non-iOS clients will support that.
If that's not the case, I'm afraid there is nothing much we can do.

**Comment by lminiero** [comment]
Closing as not an issue.

**Comment by ikallali** [comment]
+1
