### ISSUE TITLE
Data Channels support refuses to compile unless it's configured with BoringSSL

### ISSUE THREAD

**Issue by artogahr** [meetecho/janus-gateway#2331]
I've been trying to install janus on Fedora. I've fixed up all the dependencies as instructed in the README.md, and when I run ./configure with --enable-data-channels flag everything runs smoothly and in the end show "Yes" in front of data channels support. But when I go and start janus, in start logs it says data channels support is not compiled. I've tried lots of things, including reinstalls, but weirdly enough only thing that fixed it was configuring with BoringSSL instead of OpenSSL, [as mentioned here](https://groups.google.com/g/meetecho-janus/c/mx8d7uTQlJA/m/kS9wTXvdCwAJ)

Steps to reproduce:
> Download janus from github
> resolve all dependencies 
> ./configure --enable-data-channels
> Should show that data channels is enabled
> make && sudo make install
> start janus
> says data channels support is not compiled
> ./confgure with BoringSSL
> make && sudo make install
> start janus
> data channels work now

I couldn't find any note about data channels requiring BoringSSL, and fixing that took me quite a while, so I thought I'd create an issue.

**Comment by atoppi** [comment]
The message that says `Data Channels support not compiled` appears if the macro `HAVE_SCTP` has not been defined when configuring.
Try a clean install, check your `config.log` and search for the line `#define HAVE_SCTP 1`.

**Comment by artogahr** [comment]
How do you think enabling BoringSSL interferes with `HAVE_SCTP` flag? Because right after it working if I configure it without BoringSSL it goes back to saying `Data Channels support not compiled` again.

**Comment by atoppi** [comment]
If the configure output says "data channel enabled yes" then it does not make any sense to me.
Please try a clean install cloning again the repo in a new folder and check your `config.log` as suggested.

**Comment by lminiero** [comment]
Very likely a configuration issue, so clearly doesn't belong here, but on the [group](http://groups.google.com/d/forum/meetecho-janus). Closing.

**Comment by sistemasici** [comment]
This is a real isue. i cant compile with data channels.

**Comment by atoppi** [comment]
Our CI workflow compiles Janus with (and w/o if that is worth something) data channels after every commit and so far no issue has been found.

**Comment by sistemasici** [comment]
> Our CI workflow compiles Janus with (and w/o if that is worth something) data channels after every commit and so far no issue has been found.

my bad.. i fix it with apt-get install libusrsctp-dev libusrsctp-examples libusrsctp2
sorry.

**Comment by lumaqnhkaim** [comment]
> I've been trying to install janus on Fedora. I've fixed up all the dependencies as instructed in the README.md, and when I run ./configure with --enable-data-channels flag everything runs smoothly and in the end show "Yes" in front of data channels support. But when I go and start janus, in start logs it says data channels support is not compiled. I've tried lots of things, including reinstalls, but weirdly enough only thing that fixed it was configuring with BoringSSL instead of OpenSSL, [as mentioned here](https://groups.google.com/g/meetecho-janus/c/mx8d7uTQlJA/m/kS9wTXvdCwAJ)
> 
> Steps to reproduce:
> 
> > Download janus from github
> > resolve all dependencies
> > ./configure --enable-data-channels
> > Should show that data channels is enabled
> > make && sudo make install
> > start janus
> > says data channels support is not compiled
> > ./confgure with BoringSSL
> > make && sudo make install
> > start janus
> > data channels work now
> 
> I couldn't find any note about data channels requiring BoringSSL, and fixing that took me quite a while, so I thought I'd create an issue.

Possibly you need to specify `--libdir=/usr/lib64` (RHEL-based) or `--libdir=/usr/lib/x86_64-linux-gnu` (Debian-based) during `./configure` for x86_64 machine. Reference: https://github.com/meetecho/janus-gateway#:~:text=inet6%0Amake%20%26%26%20sudo%20make%20install-,Note%3A%20you%20may%20need%20to%20pass,-%2D%2Dlibdir%3D/usr/lib64%20to%20the

**Comment by dmitrydiavita** [comment]
Hi all, I had same problem with enabling data channels, and after trying all solutions , and before attempt to install BoringSSL, I figured out, that in instruction of BoringSSL installation in Janus docs, is recommended to run `make clean` before re-installing Janus. I run it, and re-build Janus, and data channels has been engined.
