### ISSUE TITLE
Streaming plugin switching not sending PLI properly

### ISSUE THREAD

**Issue by nerdbaggy** [meetecho/janus-gateway#2333]
Hello,
Using the streaming plugin PLI are not getting sent properly when a device calls the switch api command.

Server 2 - The server that the streaming clients are connecting to - https://gist.github.com/nerdbaggy/1ea8853fd5d8be76fee3a3fbe99e6d16
Server 1 - The server that is sending video streams from the videoroom plugin - https://gist.github.com/nerdbaggy/8b3156425f864eb4fda92db91d3f85af

Server 1 at 'Sat Aug 22 18:48:03 2020' we can see that the server is sending the proper PLI stuff
```
janus_1          | [Sat Aug 22 18:48:03 2020] RTCP from forwarder sending PLI to 120000014 (??)
```

Server 2 at 'Sat Aug 22 18:48:13' we can see the client switches streams. And the client video just stops and shows nothing
```
janus_1          | [Sat Aug 22 18:48:13 2020] Request to switch to mountpoint/stream 120000001 (old: 120000002)
```

Server 1 at 'Sat Aug 22 18:48:18 2020' 5 seconds after the switch command it gets 3 forwarder packets asking for PLI
```
janus_1          | [Sat Aug 22 18:48:18 2020] RTCP from forwarder sending PLI to 120000005 (??)
janus_1          | [Sat Aug 22 18:48:19 2020] RTCP from forwarder sending PLI to 120000005 (??)
janus_1          | [Sat Aug 22 18:48:20 2020] RTCP from forwarder sending PLI to 120000005 (??)
```

**Comment by lminiero** [comment]
Asked a ton of times on the [group](http://groups.google.com/d/forum/meetecho-janus) already, which is where questions like this belong. Read the docs on RTCP support in Streaming plugin and VideoRoom forwarders.

**Comment by lminiero** [comment]
Ah, you meant during a switch, not in general: makes sense then, I'll work on a fix shortly.
