### ISSUE TITLE
about screen share problem

### ISSUE THREAD

**Issue by lb240** [meetecho/janus-gateway#2336]
hi, We meet a problem about screen share, detail is:
    1、janus version is  0.10.5
    2、use videoroomtest demo, 3 man publishing, then use screensharetest demo,1 man share his screen.  If this is the case, then another man join this screen share room,  all other videoroom's man would be disconnected, no video.    why?
   
    by the way,  if videoroomtest's  room only 2 man  published, The rest is the same,   There will be no problem

**Comment by atoppi** [comment]
I have replicated your scenario and everything works as expected.
Closing as not a code issue, please refer to the group.
