### ISSUE TITLE
SRTCP unprotect error:  srtp_err_status_replay_fail 

### ISSUE THREAD

**Issue by lb240** [meetecho/janus-gateway#2339]
hi：
    when the videoroomtest demo started, there has been a mistake：
   [ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=70-->70)

   
**detail log is ：**

---------------------------------------------------
  Starting Meetecho Janus (WebRTC Server) v0.10.5
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Using ********* as local IP...
[WARN] Token based authentication disabled
Initializing recorder code
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
TURN REST API backend: (disabled)
[WARN] Janus is deployed on a private address (*******) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
Crypto: OpenSSL pre-1.1.0
[WARN] The libsrtp installation does not support AES-GCM profiles
Fingerprint of our certificate: E6:FF:52:95:67:95:94:8C:05:46:64:F6:96:50:65:A6:FD:8D:91:6B:84:BC:C5:72:BF:46:1F:BF:C8:B1:D3:35
[WARN] Event handlers support disabled
Plugins folder: /opt/janus/lib/janus/plugins
Loading plugin 'libjanus_audiobridge.so'...
JANUS AudioBridge plugin initialized!
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_recordplay.so'...
JANUS Record&Play plugin initialized!
Loading plugin 'libjanus_nosip.so'...
JANUS NoSIP plugin initialized!
Loading plugin 'libjanus_streaming.so'...
JANUS Streaming plugin initialized!
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
JANUS VideoRoom plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_textroom.so'...
JANUS TextRoom plugin initialized!
Transport plugins folder: /opt/janus/lib/janus/transports
Loading transport plugin 'libjanus_http.so'...
Sessions watchdog started
Joining Janus requests handler thread
HTTP webserver started (port 8088, /janus path listener)...
[FATAL] [transports/janus_http.c:janus_http_init:791] Couldn't start secure webserver on port 8089...
[WARN] Admin/monitor HTTP webserver disabled
[FATAL] [transports/janus_http.c:janus_http_init:849] Couldn't start secure admin/monitor webserver on port 7889...
JANUS REST (HTTP/HTTPS) transport plugin initialized!
Loading transport plugin 'libjanus_websockets.so'...
[WARN] libwebsockets has been built without IPv6 support, will bind to IPv4 only
libwebsockets logging: 0
WebSockets server started (port 8188)...
HTTP transport timer started
Secure WebSockets server started (port 8989)...
[WARN] Admin WebSockets server disabled
Secure Admin WebSockets server started (port 7989)...
JANUS WebSockets transport plugin initialized!
Loading transport plugin 'libjanus_rabbitmq.so'...
RabbitMQ SSL support disabled
[WARN] RabbitMQ support disabled (Janus API)
[WARN] RabbitMQ support disabled (Admin API)
[WARN] RabbitMQ support disabled for both Janus and Admin API, giving up
[WARN] The 'janus.transport.rabbitmq' plugin could not be initialized
Loading transport plugin 'libjanus_mqtt.so'...
MQTT SSL support disabled
[WARN] MQTT support disabled for both Janus and Admin API, giving up
JANUS MQTT transport plugin destroyed!
[WARN] The 'janus.transport.mqtt' plugin could not be initialized
Loading transport plugin 'libjanus_pfunix.so'...
[WARN] Unix Sockets server disabled (Janus API)
[WARN] Unix Sockets server disabled (Admin API)
[WARN] No Unix Sockets server started, giving up...
[WARN] The 'janus.transport.pfunix' plugin could not be initialized
WebSockets thread started
Creating new session: 5230264064127798; 0x7f14140010e0
Creating new handle in session 5230264064127798: 6962835114202500; 0x7f14140010e0 0x7f1414001850
[6962835114202500] Creating ICE agent (ICE Full mode, controlled)
[6962835114202500] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7f1414001360] WebRTC media is now available

[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=70-->70)
[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=22-->22)
[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=70-->70)
[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=22-->22)
[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=70-->70)
[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=22-->22)
[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=70-->70)
[ERR] [ice.c:janus_ice_cb_nice_recv:2795] [6962835114202500]     SRTCP unprotect error: srtp_err_status_replay_fail (len=22-->22)

**Comment by lminiero** [comment]
Please read the guidelines again before opening an issue.
