### ISSUE TITLE
Janus RPM for CentOS 7 & 8

### ISSUE THREAD

**Issue by daniel-lucio** [meetecho/janus-gateway#2344]
Not an Issue perse, but not another place to put it.

I have made available janus-gateway RPMs for CentOS 7 and 8, just install this repo https://okay.network/blog-news/rpm-repositories-for-centos-6-and-7.html and do a yum install janus-gateway. (Install EPEL repo first)

Enjoy

**Comment by lminiero** [comment]
@daniel-lucio thanks! What versions do you make available there? Tagged ones or master? We list repo resources here:
https://janus.conf.meetecho.com/docs/resources#repos

which is automatically generated from the `mainpage.dox` foxygen file:
https://github.com/meetecho/janus-gateway/blob/master/mainpage.dox

Not sure how we can advertise it there, or if you can do a PR to add it yourself. Anyway, the best place to make people aware of this is the [group](https://groups.google.com/forum/#!forum/meetecho-janus), as most people don't look at issues. Closing as we're now aware of this, thanks again!

**Comment by daniel-lucio** [comment]
Hi, for now only 0.10.4, I will do the next as soon as you release the tag. I will send a pull request soon and post it in the group. Thanks.
