### ISSUE TITLE
RTP input to VideoRoom plugin 

### ISSUE THREAD

**Issue by biostone** [meetecho/janus-gateway#2346]
Is it possible to add RTP input to VideoRoom plugin? If so, we could let one VideoRoom instance takes inputs from one or more VideoRoom's RTP forwarding, which would make a perfect scalability solution for the VideoRoom plugin.

**Comment by lminiero** [comment]
Not planned at the moment, maybe in the future for the multistrean branch but not sure if/when. You'll have to rely on the Streaming plugin until then.
