### ISSUE TITLE
Start returing transaction_id in sendMessage

### ISSUE THREAD

**Issue by zevarito** [meetecho/janus-gateway#2350]
Would make sense to return the `transaction` each time you call `sendMessage` ?
I see a benefit for this change as when you want to distinguish request/response cycle operations from events originated somewhere else. If it does, I would like to submit a PR.
Thanks Lorenzo for the project, really love the way you figured it out.

https://github.com/meetecho/janus-gateway/blob/1a825c485ec0dc212569b014a834634c1e977962/html/janus.js#L1357

**Comment by lminiero** [comment]
I don't think it would: the JS application never sees transactions at all, those are added by janus.js internally. Besides, requests/responses are easy to handle already, as responses are reported in the `success` callback of `sendMessage`, events somewhere else entirely. Closing.

**Comment by zevarito** [comment]
> the JS application never sees transactions at all, those are added by janus.js internally.

That is true for a JS application, but if you'd like to build a wrapper around Janus.js that other JS apps can use (which does make sense IMO), having access to that transaction id simplify lot of things about design. Anyway, thanks for looking at it.
