### ISSUE TITLE
Janus Crash

### ISSUE THREAD

**Issue by Vishal41** [meetecho/janus-gateway#2351]
Hi I'm encountering occasional crashes with janus. The GDB stacktrace is below:
https://pastebin.com/sSHksb2V
Do let me know if any additional information is needed.

**Comment by lminiero** [comment]
That's not master: line numbers don't match. We did a lot of fixes on HTTP already, so make sure it's still an issue on master as well or I'll close.

**Comment by Vishal41** [comment]
Ok thanks. I'll update to master and update here if I still get the issue in a few days.

**Comment by Vishal41** [comment]
Haven't encountered the crash for few days. Closing now. Thanks.
