### ISSUE TITLE
rtp_forward when using the h264 codec issue

### ISSUE THREAD

**Issue by danionescu2007** [meetecho/janus-gateway#2353]
Using the videoroom plugin I have set up publishing a video stream to a room and have chosen the H.264 codec when creating the room. I see in the SDP response that indeed H.264 is selected.
In the javascript application I initialise the rtp_forward with the following code:
`rtpmsg = { request: "rtp_forward", publisher_id: 99930178307150, room: 1234, "audio_port": 11008, "audiopt": 111, "video_port": 11010, "videopt": 96, "host": "danionescu.go.ro", "secret": "adminpwd" };`
`sfutest.send({"message": rtpmsg });`

I am receiving the audio in ffmpeg, but not the video. ffmpeg complains:
`Could not find codec parameters for stream 1 (Video: h264, none): unspecified size`

The same steps, but using the vp8 codec, works just fine.
I am using [this sdp](https://gist.github.com/danionescu2007/3de2c4c2e7ef9de4b3d6840c94aa98db)
Do you think there might be a problem on the janus side? Or maybe I am doing something wrong.
I would appreciate any suggestion as I am struggling for more than a week now trying to overcome this issue :) 

I am using the last github version of janus available as of last month when I built the docker image. I don't see any patches since then related to h264.

Thank you in advance.

**Comment by lminiero** [comment]
Closing as not a code issue (and I see you posted on the group already).
