### ISSUE TITLE
Video recorded is upside down

### ISSUE THREAD

**Issue by tomnotcat** [meetecho/janus-gateway#2370]
I use the videoroom plugin with record enabled,
When an iOS device lock in landscape mode, join the room, the video orientation has no problem.
But when I play the recorded video by janus, The video got upside down.
I don't know where cause the bug, Does webrtc has some 'orientation' property in video stream and janus not save the 'orientation' property in the recorded file?

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/?oldui=1#!forum/meetecho-janus). Closing.
