### ISSUE TITLE
[multistream] Crash dump

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#2373]
#2211

https://pastebin.pl/view/fce89123

**Comment by lminiero** [comment]
Please add some description of what's happening, and how. Besides, a libasan dump might help: not much we can do with a gdb trace alone.

**Comment by lminiero** [comment]
That said, I can't help if you're testing #2324, as it's not my PR and I haven't looked at it. I don't even know if it's aligned to the latest multistream branch.

**Comment by amnonbb** [comment]
Sorry, i fixed tag.
I meet it already. But when i add ice restart it's happen more often

**Comment by amnonbb** [comment]
I don't if it's a case. But when i look to that place:
https://github.com/meetecho/janus-gateway/blob/multistream/plugins/janus_videoroom.c#L8519
ps->svc

In IF before that we also for ps:

ps && ps->simulcast

**Comment by amnonbb** [comment]
i tried to reproduce it manually with libasan but without success.
For sure it happend when i added to clients ice restart. 
i'll try to reproduce it in production but on non important event. 
So it will take tame.

**Comment by amnonbb** [comment]
https://controlc.com/e6f8d2f1

**Comment by lminiero** [comment]
I just rebased the multistream branch, so please test against that one.

**Comment by lminiero** [comment]
Closing as I didn't receive additional info, so I guess the rebase fixed it.
