### ISSUE TITLE
Audiobridge RTP Forwarder Length Issue for PCMU/PCMA - Simple Fix

### ISSUE THREAD

**Issue by owl-debug** [meetecho/janus-gateway#2375]
When attempting to use the RTP forwarder feature of the audiobridge plugin (for PCMU data), I noted the data was not arriving correctly for my application.

Upon some further investigation, I noted the packets were rather small and it seemed, surely, there was an error somewhere in the Janus codebridge for the `plugins/janus_audiobridge.c` file.

Surely, I was able to track down what will likely be a rather obvious, but easy-to-overlook bug; as soon as you see it, you will know.

In `plugins/janus_audiobridge.c:L6648` (on master and the most current release), we have the following statement:

`int plen = (JANUS_AUDIOCODEC_OPUS ? (length+12) : 172);`

Notably, this ternary statement will always evaluate to true, causing `plen` to always equal `length + 12`; also, notably, for PCMU/PCMA data, `length == 0`; as such, the payload is necessarily sent with an always invalid size (12 instead of 172). In fact, none of the PCMU data actually arrives, only the rtph data.

I believe the aforementioned C statement should be corrected to be

`int plen = ((forwarder->codec == JANUS_AUDIOCODEC_OPUS) ? (length+12) : 172);`

**Comment by lminiero** [comment]
Good catch, thanks! I actually simplified that part, leaving always `length+172` and setting length to `160` for G711.
