### ISSUE TITLE
auto destory videoRoom

### ISSUE THREAD

**Issue by wangfpp** [meetecho/janus-gateway#2377]
### How auto destory videoRoom

i poweroff my pc but videoRoom exist

**Comment by lminiero** [comment]
> **IMPORTANT! READ OR WE WILL JUST CLOSE YOUR ISSUE!**
>
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.
