### ISSUE TITLE
videoroom dataChannel

### ISSUE THREAD

**Issue by wangfpp** [meetecho/janus-gateway#2378]
### how to use videoRoom DataChannel？

**Comment by lminiero** [comment]
> **IMPORTANT! READ OR WE WILL JUST CLOSE YOUR ISSUE!**
>
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.
