### ISSUE TITLE
Inconsistent use of mySdp in janus.js

### ISSUE THREAD

**Issue by maanas** [meetecho/janus-gateway#2379]
In these two locations

https://github.com/meetecho/janus-gateway/blob/4614b6b2b43031bcde457b9bd9b65e8a364d6f52/html/janus.js#L2775
https://github.com/meetecho/janus-gateway/blob/4614b6b2b43031bcde457b9bd9b65e8a364d6f52/html/janus.js#L3016

whereas in this location
https://github.com/meetecho/janus-gateway/blob/4614b6b2b43031bcde457b9bd9b65e8a364d6f52/html/janus.js#L3048-L3051

In the previous two use, mySdp is a string whereas in the latter location this is a dictionary. I am trying to port the janus.js in the flutter https://github.com/maanasnetwork/flutter_janus

https://developer.mozilla.org/en-US/docs/Web/API/RTCSessionDescription provides a class with sdp and type. The use of mySdp is appeared to be inconsistent. Please correct me if my understanding is not correct.

**Comment by lminiero** [comment]
There is indeed an inconsistency, but `mySdp` is not used for anything, if not as a check to ensure we do have a local SDP. The one we send is obtained via the PeerConnection object anyway (which then updates our object).

**Comment by lminiero** [comment]
This should now be fixed, as `mySdp` is always an object with `type` and `sdp`.
