### ISSUE TITLE
I  can't run streaming plugin properly with a waiting circle on the player

### ISSUE THREAD

**Issue by richard1219** [meetecho/janus-gateway#2389]
I  can't run streaming plugin properly, I alway got a waiting circle on the chrome player and it seem the play got data but no picture displayed, it show "Stream Started 1112kbps/sec" on the top of the player, pls give me a hand.

I run ffmpeg like this:
_/opt/soft/ffmpeg/bin/ffmpeg  -i rtmp://58.200.131.2:1935/livetv/hunantv -c:v libx264 -profile:v baseline -s 640x480  -an -preset ultrafast  -tune zerolatency -f rtp  rtp://172.17.0.2:8004_

and I get the folow ffmpeg output:
_SDP:
v=0
o=- 0 0 IN IP4 127.0.0.1
s=No Name
c=IN IP4 172.17.0.2
t=0 0
a=tool:libavformat 58.29.100
m=video 8004 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1

frame=13360 fps= 25 q=26.0 size=  130929kB time=00:08:54.36 bitrate=2007.2kbits/s speed=   1x_

I configure the streaming plugin like this:
_h264-sample: {
        type = "rtp"
        id = 10
        description = "H.264 live stream coming from gstreamer"
        audio = false
        video = true
        videoport = 8004
        videopt = 96
        videortpmap = "H264/90000"
        videofmtp = "packetization-mode=1" #"profile-level-id=42e01f;packetization-mode=1"
        secret = "adminpwd"
}_

I believe janus run properly because I get the following log:

_[Fri Oct  9 07:00:25 2020] [h264-sample] New video stream! (ssrc=1138302557, index 0)
...
[Fri Oct  9 07:00:32 2020] [147146790653064] The DTLS handshake has been completed
[Fri Oct  9 07:00:32 2020] [janus.plugin.streaming-0x7f1fb40012d0] WebRTC media is now available_

It can be my configuration issue, can anybody give me a hand? thanks.

**Comment by lminiero** [comment]
> **IMPORTANT! READ OR WE WILL JUST CLOSE YOUR ISSUE!**
>
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.

**Comment by wangfpp** [comment]
@richard1219  dou you resolve this problem?
