### ISSUE TITLE
listparticipants json payload truncated when more than 130 people in TextRoom

### ISSUE THREAD

**Issue by nustiueudinastea** [meetecho/janus-gateway#2397]
Hi folks, in our stress testing we found an issues with the textroom, when reaching or passing roughly 130 people in a room. When initially joining the room and there are already over 130 people joined, if performing a `listparticipants` operation, the call returns but the answer is truncated (invalid JSON). I attached the truncated JSON payload recovered from the Firefox console.

[textroom_payload.json.txt](https://github.com/meetecho/janus-gateway/files/5401605/textroom_payload.json.txt)

**Comment by lminiero** [comment]
What version of Janus is this? Make sure to test with master too, if this is older, as there may have been fixes on datachannels. Have you checked if the same happens when sending the `listparticipants` request via Janus API and/or Admin API as well? (you'll have to use `request: "listparticipants"` in that case).

**Comment by nustiueudinastea** [comment]
Hi @lminiero , this is on version v0.10.5. We're not using v0.10.6 yet because we noticed that it has slightly worse video quality than the previous version. 

We are using the websockets API to make these requests, but today I hope to be able test this via the http admin dashboard as well. Will post an update ASAP.

**Comment by lminiero** [comment]
Very likely the WS fragmentation issue we solved in 0.10.6
https://github.com/meetecho/janus-gateway/blob/master/CHANGELOG.md#v0106---2020-10-05

**Comment by nustiueudinastea** [comment]
Ok, I will be testing with master and 0.10.6 if required. I will close the issue if I can confirm this is fixed. Thanks!

**Comment by nustiueudinastea** [comment]
I confirm that this issue has been fixed on master. We don't get a truncated WS response anymore. It works via WS and via the HTTP API. Thanks!

**Comment by lminiero** [comment]
Cool, thanks for the confirmation!
