### ISSUE TITLE
libnice build time version check doesn't account for different PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by ssalenik** [meetecho/janus-gateway#2403]
This is a minor annoyance :)
This check here uses system's pkg-config:
https://github.com/meetecho/janus-gateway/blob/a64173f451140c5e2dd258595f935db07a263902/Makefile.am#L207-L211

If janus is configured with `PKG_CONFIG_PATH` which points to another pkgconfig location for libnice, then it could be compiled with a newer version, but this check will still result in a runtime warning about outdated libnice.

eg:
```
./configure PKG_CONFIG_PATH=/my/libnice/path/lib/pkgconfig
```

Not sure what the best approach here is.

**Comment by ssalenik** [comment]
I think actually passing in the user configured PKG_CONFIG_PATH here would be enough, eg:
```
PKG_CONFIG_PATH=THE_ONE_FROM_CONFIGURE pkg-config --modversion nice ...
```

**Comment by ssalenik** [comment]
OK, so I guess the simplest solution is just to run `make` and `make install` with the same `PKG_CONFIG_PATH` var and that fixes it... I dunno if its "kosher" in automake to have configure pass this as a var to Makefile.am. If not, then I guess just close this.

**Comment by atoppi** [comment]
Hi @ssalenik thanks for looking into this.
If you already have a proper fix, would you mind submitting a PR ? Also don't forget to sign the CLA if you didn't already!
