### ISSUE TITLE
SIP plugin: initiate outgoing calls with repetitive Call-IDs after janus restart

### ISSUE THREAD

**Issue by ycherniavskyi** [meetecho/janus-gateway#2404]
The issue was reported to me by billing support because they see that "Janus WebRTC Server SIP Plugin UA" repetitively sends SIP INVITEs with the same Call-IDs.
After some investigation, I found that `janus_sip_random_string(int, char*)` (and some other functions) use [`rand()`](https://linux.die.net/man/3/rand) which, when used without proper `srand()`, generate the same random sequence on each janus restart.

In [RFC 3261](https://tools.ietf.org/html/rfc3261#section-8.1.1.4) I found that it is recommended to use cryptographically random identifiers in the generation of Call-IDs.

So if the current implementation is not intentional, then maybe it is better to replace `rand()` with `janus_random_uint32()` (which internally use [`g_random_int()`](https://developer.gnome.org/glib/stable/glib-Random-Numbers.html#g-random-int) which also is not cryptographic but at last set different `seed` on jnaus restart).

**Comment by lminiero** [comment]
Thanks for the heads up, just done in the above commit. I noticed the same random string function was in the HTTP transport too, so I fixed it there as well.

**Comment by ycherniavskyi** [comment]
Wow, it was fast! 😳⚡️👍
