### ISSUE TITLE
SIP plugin: generate offer SDP which produce browsers WebRTC error

### ISSUE THREAD

**Issue by ycherniavskyi** [meetecho/janus-gateway#2413]
In the Chrome console I can see the next error (call completely failed):
```
WebRTC error: DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote offer sdp: The BUNDLE group contains MID='video' matching no m= section / janus.js:417
```
In the Firefox console I can see the next error (only audio stream initiated):
```
WebRTC error: DOMException: No transceiver for bundled mid video / janus.js:417:15
```

After some investigation, I suppose that the issue with the next line `m=video 0 RTP/AVP 120 121 126 97` in [incoming SIP call SDP](https://gist.github.com/ycherniavskyi/a4eca8c25c79e51da008b37ae71e83b3), which is lead to generating the next incorrect (from browsers point of view) line `a=mid:(null)` in [Janus offer SDP](https://gist.github.com/ycherniavskyi/f7a1a1e26742a82f6f0ae70c67279cb6).

**Comment by lminiero** [comment]
Pretty sure we fixed this already, recently. Make sure you're using master, if not already.

**Comment by ycherniavskyi** [comment]
Are you about #2390? Ok, I will try master and report.

**Comment by ycherniavskyi** [comment]
Just got the necessary logs, and can confirm that in v0.10.7 the issue is resolved - instead of `a=mid:(null)` now generated `a=mid:1`.
