### ISSUE TITLE
[janus-pp-rec] Huge opus files when received timestamp is 0 (see #2328)

### ISSUE THREAD

**Issue by atoppi** [meetecho/janus-gateway#2414]
Since #2328 contained a patch with a not acceptable solution, we are creating this issue to keep track of the post-processor problem described in the PR.
Please refer to #2328 for more context.

**Comment by atoppi** [comment]
fyi #2345 has been merged, so I I'll start working again on this.

**Comment by atoppi** [comment]
@ihusejnovic a PR has been published for this issue now.
Please test #2467 with your recordings and see if it fixes the huge files problem.

**Comment by ihusejnovic** [comment]
> @ihusejnovic a PR has been published for this issue now.
> Please test #2467 with your recordings and see if it fixes the huge files problem.

Hey @atoppi, it's working very well. All files with a problematic timestamp are successfully converted. I will use this branch in production from Monday and let you know if I notice any issues. Thank you!

**Comment by lminiero** [comment]
Thanks for the feedback @ihusejnovic, we'll merge then :+1: 
In case you spot issues in production, this can be fixed along the way.
