### ISSUE TITLE
[multristream] Unknown property 13 for preparing SDP answer

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#2415]
#2211 

Something happened with orientation ext in last rebase

**Comment by lminiero** [comment]
I'll have a look on Monday, thanks for reporting.

**Comment by lminiero** [comment]
It was not an issue of rebasing. A recent commit that had restored the ability to negotiate H.264 and VP9 profiles was adding passing them as arguments when generating audio m-lines too, and so they were unrecognized (13 is `JANUS_SDP_OA_H264_PROFILE`). It should be fixed now.

**Comment by amnonbb** [comment]
Fix solve problem with orientation ext: it's work now. But janus log still spammed with message:
 [WARN] Unknown property 13 for preparing SDP answer, ignoring...

**Comment by lminiero** [comment]
Fixed.
