### ISSUE TITLE
[multistream] Did not get audio onremotetrack callback

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#2418]
#2211 

The issue is on last rebase multistream.
I try it on my application and on mvideoroomtest demo (https://pastebin.pl/view/a85d6b2d) - the same result

Step to reproduce:
1 - feed1 and feed2 join room (no problem here)
2 - feed2 exit from room
3 - feed2 join same room
4 - feed1 - do net get audio onremotetrack callback

**Comment by amnonbb** [comment]
dbb9807 - fix problem.
Issue can be closed

**Comment by lminiero** [comment]
Ack, closing then.
