### ISSUE TITLE
full_trickle problems

### ISSUE THREAD

**Issue by PatrikTes** [meetecho/janus-gateway#2425]
Dear Janus team,

we are testing right now a web-conference with 13-14 publishers in one session.
Our janus configuration was made with the full_trickle (as it makes ICE negotiation faster)

... but....

we were not able to get more participants as 6 or 7 into the standard videoorom. Receiving error on the server: ICE failed.

after we setup full_trickle to false, everything works like a charm and we have had 13-14 participants in videoroom.

Has someone else the same problem? Or are we the only one?

Thank you very much!

**Comment by atoppi** [comment]
Just a clarification in case you missed this: enabling full trickling on Janus will just enable trickle sending for Janus candidates and it is not needed to have trickles incoming from browsers.

Please do the following:
1) capture the Admin API for failing peers and you'll have more insights on exchanged candidates and handshake status
2) search janus logs in verbose level (5) when the issue happens

**Comment by PatrikTes** [comment]
@atoppi Thank you! We will do so and I will inform you here about the results, maybe it helps also someone else.

**Comment by atoppi** [comment]
@PatrikTes any update on this ?

**Comment by PatrikTes** [comment]
Sorry :( still investigating. I will update you once we have some news

**Comment by lminiero** [comment]
If you still care about this issue, please share some more details: otherwise we'll have to assume this is not a problem anymore, and we'll just close this.

**Comment by lminiero** [comment]
Closing.
