### ISSUE TITLE
janus-gateway locking (no crash but not accepting new websocket connections)

### ISSUE THREAD

**Issue by jmordica** [meetecho/janus-gateway#2429]
We use janus-gateway 0.10.5 with websockets and SIP plugin enabled.

We've experienced the server/instance `locking` where it disconnects all of the websocket connections at once but doesn't crash and stops accepting new connections. There is no clear indicator of what is causing the frozen state (only a large amount of these types of messages: https://pastebin.com/EtWqMkW2). There are many more in the log but this should be enough for example purposes.

Has anyone experiencing this? I'm not sure what additional info to provide here but can provide more if needed.

**Comment by lminiero** [comment]
Unless you try with master first, we won't look at the dump, sorry.

**Comment by tmatth** [comment]
@jmordica which version of libwebsockets are you using? Also, are you building it with `-DLWS_MAX_SMP=1`?

**Comment by jmordica** [comment]
@tmatth Im using the Debian stretch libwebsockets-dev (2.0.3-2)

Here’s my janus-gateway docker build (which is pretty standard I believe)  https://pastebin.com/hsnmqaMv

Should I Build a custom (and later) version of libwebsockets and with that flag you mentioned?

**Comment by tmatth** [comment]
> @tmatth Im using the Debian stretch libwebsockets-dev (2.0.3-2)
> 
> Here’s my janus-gateway docker build (which is pretty standard I believe) https://pastebin.com/hsnmqaMv
> 
> Should I Build a custom (and later) version of libwebsockets and with that flag you mentioned?

Well like @lminiero I'd try Janus master first.

**Comment by jmordica** [comment]
This only happens when Janus has been running for a few weeks and have handled approx. 500-600 active sessions throughout the day. We don’t experience these types of crashes with low traffic so it’s hard to “test” if that makes sense. I may take a stab at using master, as building with newest libwebsockets from source.

**Comment by jmordica** [comment]
I have more info on this (although i'll need to be directed in how to obtain what you will need in order to troubleshoot further). 

So it seems that the longer a user stays connected to the SIP plugin, the more cpu that thread uses. I can `top -H -p <pid of janus>` and see that in the command column of `top` I see one of these per user connected: `sip myUserId`.

It seems like the ones consuming the most CPU are the ones connected for the longest time. Is there some type of cleanup that needs to happen via the SIP plugin to release the CPU over time? Using latest master btw.

**Comment by atoppi** [comment]
@jmordica not sure how this is relatable to the main issue (locked lws).
Anyway to have a detailed view of what a specific thread/process is doing, you may want to take a look at `perf`.

**sample janus and all forked threads for 10 secs**
```bash
perf record -F 200 -a --call-graph dwarf -p $(pidof janus) -- sleep 10
```

**sample a specific pid for 10 secs**
```bash
perf record -F 200 --call-graph dwarf -p $PID_TO_SAMPLE -- sleep 10
```
In both cases you'll get a `perf.data` output that must be analyzed (see Reporting section of [ref](http://www.brendangregg.com/perf.html#OneLiners)).

**Comment by jmordica** [comment]
I haven't had time to dig in and debug in greater detail. As a workaround, we've set a 12hr timeout on the client side to re-initialize the Janus handles to the SIP plugin which has resolved the crashing issue.

**Comment by lminiero** [comment]
Any update on this?

**Comment by lminiero** [comment]
We haven't receive a response in weeks, so I'll assume this is fixed. Closing.
