### ISSUE TITLE
chrome     Removing remote track  

### ISSUE THREAD

**Issue by TongBig** [meetecho/janus-gateway#2431]
As a subscriber,  can't see the video on Google browser  why?   other browser is ok

As a publisher  publish own stream is ok to see other personer video

**Comment by akilude** [comment]
Hi, 

a better place to ask these questions would be the [google group](http://groups.google.com/d/forum/meetecho-janus) instead.

**Comment by TongBig** [comment]
As a subscriber, can't see the video of publisher on Google browser why? other browser is ok
