### ISSUE TITLE
Janus getting crashed in audiobridge plugin

### ISSUE THREAD

**Issue by ramprakash110109** [meetecho/janus-gateway#2432]
Hi,

During high load in production, I am facing janus crash in past few days. The crash happens in 
“Line no. 6297 of janus_audiobridge.c of master branch“ I.e., g_snprintf(s_name, sizeof(s_name), "AudioBridge %s", participant->room->room_id_str);

GDB backtrace of the core dump file is present in https://pastebin.com/D05MWWT3

While in GDB, I printed the  value of participant->room and it is NULL.
Is there any check missing ?

**Comment by atoppi** [comment]
The source lines from gdb do not match the master revision.
Can you please provide a gdb trace from a recent version ?

**Comment by atoppi** [comment]
[This commit](https://github.com/meetecho/janus-gateway/commit/cd20d6c5807026965e7f0c845a1d72769d91f201) should avoid the crash in future, please test and report if it works.

**Comment by ramprakash110109** [comment]
Oops, I have added few comments for my reference in janus_audiobridge.c. That's why the line numbers are different in gdb stack trace. I am using master branch of janus v0.10.4.

Thanks for the commit @atoppi  😊 . I will try this commit and update you.

**Comment by lminiero** [comment]
@ramprakash110109 any update? Did you test Alessandro's commit? Does it fix the issue for you?

**Comment by ramprakash110109** [comment]
Yes @lminiero . That commit solved the issue.  Thanks for your support 😊

**Comment by lminiero** [comment]
Ack, thanks for the update! Closing the issue then.
