### ISSUE TITLE
Loading transport plugin 'libjanus_http.so'  error 

### ISSUE THREAD

**Issue by neekerss** [meetecho/janus-gateway#2435]
janus.log:
Loading transport plugin 'libjanus_http.so'...
[31m[ERR][0m [janus.c:main:5320] 	Couldn't load transport plugin 'libjanus_http.so': /usr/local/lib/libgnutls.so.30: symbol mpn_copyi, version HOGWEED_6 not defined in file libhogweed.so.6 with link time reference

How to compile libmicrohttpd that supports HTTPS? What version do you need? For example: libmicrohttpd, libgcrypt, libgnutls.

**Comment by atoppi** [comment]
Not a code issue, question for the group
https://groups.google.com/g/meetecho-janus
