### ISSUE TITLE
missing contact header in sip invite

### ISSUE THREAD

**Issue by charleslee1010** [meetecho/janus-gateway#2439]
We use janus-gateway master with websockets and SIP plugin enabled. 
We use share/janus/demos to test sip registeration and sip call.
After we disable sips and force using of udp by modifying siptest.js, sip registration succeeds.
But sip call fails with the following error:  Missing Contact Header

Has anyone experienced this? I'm not sure what additional info to provide here but can provide more if needed.

We use centos 7.4 and the sofia version:
sofia-sip.x86_64                            1.13.0-14.d10a3d268c     @freeswitch
sofia-sip-devel.x86_64                      1.13.0-14.d10a3d268c     @freeswitch

Here is console output:
nta.c:3305 agent_recv_response() nta: received 400 Missing Contact Header for INVITE (28286682)
nta.c:3372 agent_recv_response() nta: 400 Missing Contact Header is going to a transaction

Below is the sip invite message captured by freeswitch, the Contact header is NOT found. 

<details><summary>SDP</summary>

```
INVITE sip:1001@sbc03.onecall.vip:16385 SIP/2.0
Via: SIP/2.0/UDP 172.16.0.232:36673;rport;branch=z9hG4bKS79HeK1gt6mNr
Max-Forwards: 70
From: "1000" <sip:1000@121.196.44.143>;tag=jZ5Xt3y5cpUSc
To: <sip:1001@sbc03.onecall.vip:16385>
Call-ID: ILwMIAZNwDveNJ45aIWDRJH
CSeq: 28285324 INVITE
User-Agent: Cool WebRTC Gateway
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, UPDATE, REFER, MESSAGE, INFO, NOTIFY
Supported: replaces
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 958

v=0
o=- 3731379636021817265 2 IN IP4 1.1.1.1
s=-
t=0 0
m=audio 40676 RTP/AVP 111 103 104 9 0 8 106 105 13 110 112 113 126
a=rtpmap:104 ISAC/32000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=rtcp-fb:111 transport-cc
```
</details>

**Comment by lminiero** [comment]
As explained in the guidelines, please don't paste SDPs and larger text as it is inline. Either use pastebin/gist, or use the Github markdown features to use quotes and make them collapsible (I just updated your original text myself to do that).

That said, contact headers are set by Sofia, not us. Did you do a "register" before calling? If so, you can try setting `behind_nat = true` in the SIP plugin configuration to see if that helps.

**Comment by charleslee1010** [comment]
Thanks for updating.
I did do "register" before calling and behind_nat=true was set in the SIP plugin configuration.

**Comment by lminiero** [comment]
The Contact header is definitely there in all my requests (both REGISTER and INVITE), and this is using the unmodified demo. As such, I think we can ascribe it to the Sofia SIP version you have on CentOS. Closing as not an issue.

**Comment by cppdev-1** [comment]
**charleslee1010**, have you solved this issue?

**Comment by xadhoom** [comment]
I think that basically the sofia-sip in fedora is pretty outdated and now the real mantainers of sofia-sip (afaik officially endorsed) are the guys of the freeswitch team. So makes sense to make Janus work against a recent and maintained sofia-sip library.

We also have this problem which prevents using Janus and FS on the same box on CentOS. Right now we're trying to check where the incompatibility lies and maybe create a patch for Janus to handle both.

**Comment by flaviogrossi** [comment]
We seem to have tracked it down to be an issue with a change that only exists on that sofia repo (which, according to http://sofia-sip.sourceforge.net/index.html is now the main repo, so i think it is a priority to have it fixed).

I opened an issue here https://github.com/freeswitch/sofia-sip/issues/52 with the details if anyone wants to join the discussion or provide more details.

**Comment by cppdev-1** [comment]
@xadhoom @flaviogrossi @lminiero

The reason is that developers of libsofia have commented out the code that adds contact header to request. See nua_client_request_sendmsg in nua_client.c for more information.
In our case we use only guest SIP sessions. To solve the problem we generate contact header from SIPTAG and add it to SIP INVITE request.
 
PR - https://github.com/meetecho/janus-gateway/pull/2597

**Comment by lminiero** [comment]
Looking into this right now, as I'm trying to refactor @cppdev-1's PR to make it a bit less complex.
Since I have 1.12.11 installed and not 1.13.x, can you guys confirm it's only an issue for guest registrations, and not when you register normally? It's not clear looking at the referenced Freeswitch PRs, since I don't see answers from their team and I'm not familiar enough with the Sofia internals to understand the implications of the change that apparently broke it.
@charleslee1010 @xadhoom @flaviogrossi

**Comment by lminiero** [comment]
See the PR above for a possible fix. Feedback welcome: please notice that if I don't get any feedback, I'll just cancel the PR and close the issue again, as I'll assume there's no interest in this anymore.

**Comment by xadhoom** [comment]
I'll be glad to review if no one else does, but in a couple of weeks since
I'm not operational in these days.

Il mar 22 giu 2021, 12:11 Lorenzo Miniero ***@***.***> ha
scritto:

**Comment by lminiero** [comment]
Thanks!

**Comment by flaviogrossi** [comment]
> See the PR above for a possible fix. Feedback welcome

the first tests were successful, this seems to work fine. Added some details in the relevant PR if anyone wants to follow the discussion

**Comment by flaviogrossi** [comment]
There is still something not working when trying to setup tls with the new sofia though (if not using the `sips: false` parameter of course). In particular the `nua_create()` call fails, but that's a separate issue, will look into it later
