### ISSUE TITLE
FireFox SDP issue

### ISSUE THREAD

**Issue by catid** [meetecho/janus-gateway#2443]
Seeing this error from Janus C++ code when trying to view a video stream with FireFox.  Chrome browser works but FireFox does not.

[ERR] [sdp.c:janus_sdp_process:376] [6431443741637516] SDP missing mandatory information
[ERR] [sdp.c:janus_sdp_process:377] [6431443741637516] (nil), (nil), 0x7f0d4c005340, 0x7f0d4c005100
[ERR] [janus.c:janus_process_incoming_request:1417] Error processing SDP

Seems like the ruser=null is causing this problem?

**Comment by lminiero** [comment]
Missing `ruser` and `rpass` means the SDP we received contained no ICE candidates (`ice-ufrag` and `ice-pwd` attributes). Have you checked the SDP to see if that's the case?

**Comment by catid** [comment]
Will look into it thanks

**Comment by MrYoda** [comment]
No updates? I have the same issue on Firefox 83 (Ubuntu) with Janus streaming plugin. Textroom works well.
And janus streaming demo on official website works well, hmm.

**Comment by atoppi** [comment]
As Lorenzo said, check the SDP sent to Janus.

**Comment by MrYoda** [comment]
> As Lorenzo said, check the SDP sent to Janus.

Thanks! Checked, `ice-pwd` and `ice-ufrag` are missing.
Please do you know how could I add or unremove it from Firefox SDP? Can't find any strings with these params in any JS files.

**Comment by lminiero** [comment]
If those fields are missing, then Janus is doing its job. Closing.

**Comment by MrYoda** [comment]
In my case it was missing param `videofmtp = "profile-level-id=42e01f;packetization-mode=1"` for streaming mountpoint.
Let it help somebody in the future.

**Comment by CastroDF** [comment]
Same issue here, solved after adding the param that @MrYoda suggested. Chrome and Safari were working without problem,  but Firefox was failing. Thanks!
