### ISSUE TITLE
Videoroom segfault crash

### ISSUE THREAD

**Issue by karelbrascamp** [meetecho/janus-gateway#2449]
We use 0.10.7.

We were using 0.10.5 until a few weeks, and we experienced a similar crash. We updated to 0.10.7 to make sure we could report our bug here, and, well, maybe the issue would be fixed.

That said, I'm not really sure if it's an actual bug: we experience load spikes quite regularly, check this screenshot to see the pattern:
<img width="642" alt="Screenshot 2020-11-25 at 11 53 04" src="https://user-images.githubusercontent.com/296419/100218364-f323e780-2f14-11eb-9f4d-b34d1eebbf06.png">

When both crashes occured (using the 0.10.5 and 0.10.7), we experienced a load spike that was a lot higher than the spikes in the image, after which Janus shut down. Here's the stack trace of the last crash:

[https://pastebin.com/ZnQxgJB5](https://pastebin.com/ZnQxgJB5)

Are the load spikes normal behaviour for Janus? They can off course trigger a crash when they spiral out of control. 
We added another Janus server to our setup to scale the load. It (obviously) lowers the load, and the spikes are lower too. 

Kind regard, Karel

**Comment by lminiero** [comment]
0.10.7 is not the latest version. Please try master (which is 0.10.9 now).

**Comment by karelbrascamp** [comment]
Ah crap, there was a release we missed. Sorry, we'll update.

Regarding the load spikes, are they normal?

**Comment by atoppi** [comment]
1) Please give some more details about your usage (e.g. number of rooms, number of participants, kind of interactions etc.)
2) Not sure what the issue is about... is it a crash or a load spike?
3) Could you please clarify this statement?
> They can off course trigger a crash when they spiral out of control.
4) When testing with latest release, don't forget to enable libasan
5) As of the spikes, I have never noticed them before but being "quite regular" makes me think that it could be some kind of maintenance routine happening on the machine (just guessing).
6) As of the crash, it is very difficult to identify a cause from that specific trace. Crashing on a mutex could be explained by a container struct (in this case `room`) being freed and rewrote, and so `room->mutex` points to an invalid area where an unlock triggers a SIGSEGV. Anyway the trace is not complete and a libasan dump would be more helpful.

**Comment by karelbrascamp** [comment]
Thanks for your response.

1.  At peek hours, there are about 100 rooms. There's always at least one user occupying the room, transmitting video and audio. There can be 0 - 5 other users in the room watching the sender. Mostly though, there's just one, though often, there will be 0 viewers.
2. It's about the crash, but I thought maybe the spikes might be related since..
3. Spikes might trigger a crash if the spikes spike higher than the capacity of the server and the server won't recover in time, the load will peak too high. For example, in the screenshot I sent you the spikes yield a load somewhere between 10 and 15, but during the two crashes we encountered the load went up to 100 before the crash
4. We will
5. The machine is running just Janus.  Now that we added an extra server, we noticed way less extreme spikes
6. We'll add libasan

Thanks again

**Comment by atoppi** [comment]
Is it possible that you are deleting a room while publishing someone in it?

**Comment by karelbrascamp** [comment]
yes that would certainly be possible, but I would have to look closely to see if we don't kick the users first. I'll have to come back to that

**Comment by karelbrascamp** [comment]
There indeed are scenarios where we do not kick users before we close the room. Should we?

**Comment by lminiero** [comment]
Please provide the asan traces we asked for. No point in speculating on the causes until we see what's happening.

**Comment by karelbrascamp** [comment]
Allrighty, we'll test and deploy the latest version and get back when we have fresh crash data

**Comment by lminiero** [comment]
Any update on this?

**Comment by karelbrascamp** [comment]
We deployed the latest versions with asan traces on all servers, but no crashes since.
I'd say just close the issue, I'll open a new one when we do have crash data.

**Comment by lminiero** [comment]
Ack, thanks for the update, closing then.
