### ISSUE TITLE
websocket server periodically ignores messages

### ISSUE THREAD

**Issue by Computician** [meetecho/janus-gateway#245]
I have had a continual issue with the websocket server on Janus ignoring a message and never sending a response. 

This happens from time to time when using the javascript API wrapper with two local chrome browser clients connecting to a video room.

Most often the session creation message sent in the `onopen` callback handler is ignored but I have also had a plugin attach request ignored(again, just using the janus.js and the videomcu example code). 

I am not passing any special arguments to my janus server and am using the default config file provided in the project.

**Comment by Computician** [comment]
Also, I am not sending an abnormal amount of ice candidates. I am using trickling but I am only using one stun server(the one provided by default by janus as both of these peers on the same network).

**Comment by Computician** [comment]
This seems to only happen when the wss connection pointer is in the old_wss list.

**Comment by Computician** [comment]
Well, never mind on it only happening when it is in the old connection list...

**Comment by Computician** [comment]
I seem to have narrowed it down to when the old connection list reaches near 20+ connections.

**Comment by Computician** [comment]
Why is a Linked list being used if we have to check element existence so often? When I get the list to about 20+ members, the connection works fine if the ws_client entry is near the top, but if it is not in the list at all or towards the end, the communication between the client and the ws server seems spotty.

I am double checking my theory through some additional tests but, this seems logical to me

**Comment by Computician** [comment]
Well, the list is not the culprit as I switched it out with a hash_table and had the same issue.

**Comment by lminiero** [comment]
The old connection list is there to avoid replying on a WebSocket that has been marked as closed, since there were potential causes for damage otherwise. If your WebSocket is in that list, it means it was closed by one of the two parties, which might explain why those messages are ignored by the server.

**Comment by lminiero** [comment]
I'll also try and replicate the 20+ old connections next week.

**Comment by lminiero** [comment]
Sorry but I couldn't replicate it. I had an old_wss list of about 50 closed connections, and a janus.js library modified to shoot the same candidate about 30 times on each onicecandidate callback, and it worked as expected (I could see all the candidate replicas in admin, so they were handled). Do you have any sample application to reliably replicate the issue?

Have you also checked, via debug, whether the cause is the WebSocket code dropping the message or it being lost somewhere in plugins instead? Just to make sure the issue's there.

**Comment by Computician** [comment]
When two parties join a room at essentially the same time and just close the browser page instead of being redirected, this happens. The WebSocket connection `onopen` fires but the create request is ignored or the attach is. 

I am going to add some more logging to see if the messages are received by the endpoint and are not ignored. But since the `create` message is not even respected, that implies no plugin is involved.

**Comment by Computician** [comment]
Below it can be seen that one of the create requests is ignored. This request is coming from the janus.js wrapper on a windows machine. Consiquently, the rest of my javascript does not execute. This happens a fair amount. I have a some websocket clients connect, create a session, attach a plugin, join a video room, then close their connection and their browser. I wait for the websocket sessions to be closed due to time out, then try the same pattern again and inevitably messages are ignored, not by the plugin, but by the websocket handler. 


`[WSS-0x8fd3c00] Connection was in old list...
[WSS-0x8fd3c00]   -- Ready to be used!
[WSS-0x8fd3c00] Got 47 bytes:
{"janus":"create","transaction":"sTq1aq2NNbJh"}
[WSS-0x902e400]   -- Ready to be used!
[WSS-0x902e400] Got 47 bytes:
{"janus":"create","transaction":"7ADh1KNSZTYk"}
Creating new session: 3434620482
[WSS-0x902e400] Got 105 bytes:
{"janus":"attach","plugin":"janus.plugin.videoroom","transaction":"jGbo8XaXht0A","session_id":3434620482}
Creating new handle in session 3434620482: 367001755
[WSS-0x902e400] Got 170 bytes:
{"janus":"message","body":{"request":"join","room":449,"ptype":"publisher","display":"stream"},"transaction":"kf3zWlTmbG1G","session_id":3434620482,"handle_id":367001755}
[WSS-0x902e400] Got 74 bytes:
{"janus":"keepalive","session_id":3434620482,"transaction":"YWeoXnOrjpnF"}
[WSS-0x902e400] Got 74 bytes:
{"janus":"keepalive","session_id":3434620482,"transaction":"OSByaOU97yOQ"}
[WSS-0x902e400] Got 74 bytes:
{"janus":"keepalive","session_id":3434620482,"transaction":"b1c1QEwoxwYY"}
[WSS-0x902e400] Got 74 bytes:
{"janus":"keepalive","session_id":3434620482,"transaction":"SDGn0T2eSROC"}
`

**Comment by Computician** [comment]
I think I found a bug:

https://github.com/meetecho/janus-gateway/blob/master/janus.c#L3093

Shouldn't that cast the `user_data` parameter?

**Comment by lminiero** [comment]
Mh, not sure if we're doing it wrong, as we do the same for rabbitmq (but it may just be a silly copy/paste error). I'll check what a task is passed, as that's done automatically by the glib thread pool.

**Comment by lminiero** [comment]
Yep looks like you're right: in principle it works anyway, because we have a pointer to the client also in the ```janus_request_source``` instance, that is available as part of the ```request```. That said, the task uses the wrong pointer for the client, as that's actually the request, and this may lead to weird behaviour: in particular, if the wrong ```client``` pointer is the same as the one used for an old WebSocket client, it won't do the ```janus_process_incoming_request```, thus effectively dropping the request, which may be what you experienced.

Have you tried setting the client to ```user_data``` instead and see if that fixes it for you?

**Comment by Computician** [comment]
Well, the janus websocket client instance associated with the thread pool is most assuredly the `user_data` parameter. So, potentially, there is a pointer issue when checking against the `old_wss` sessions list as the wrong pointer is being checked for membership.

**Comment by lminiero** [comment]
Yep just wrote about that: it's not an issue if it goes on, instead, as we use a difference reference there.

**Comment by Computician** [comment]
I am going to test a little bit more. If it does not happen again, I am going to revert and add a printout to see if it is being treated as an old connection even though it is not due to the wrong pointer printout.

**Comment by lminiero** [comment]
I already pushed the fix as it was indeed a typo. Let me know if that was the only cause of the issue you experienced.

**Comment by Computician** [comment]
I have not been able to reproduce with the change. I will reopen the issue if it occurs again.

**Comment by lminiero** [comment]
Great, and thanks for spotting that typo! My old eyes are getting weary :-)
