### ISSUE TITLE
Video launch problem

### ISSUE THREAD

**Issue by yusufdamat** [meetecho/janus-gateway#2452]
Spinner runs on Apple devices Safari and Chrome browsers and the video stays on black screen.

I ran into this problem with the Recorder / Playout module. I did as much research as I could but couldn't solve the problem.

https://imgyukle.com/i/TUfE36

https://imgyukle.com/i/TUfogx

**Comment by lminiero** [comment]
As explained in the guidelines, connectivity issues belong to the [group](https://groups.google.com/g/meetecho-janus), not here. Closing.
