### ISSUE TITLE
Video stream return null

### ISSUE THREAD

**Issue by pzprovi** [meetecho/janus-gateway#2453]
Janus js plugin have function in sip plugin client for unmuteVideo()
The function work perfectly when start video call. If I start audio only call and try to switch into video call the function unmuteVideo() not work due to stream is null.

How to switch re invite audio to video call? I just want during audio only call to switch into video call.
Can you help me? Some js siptest or janus js code examples, etc...

```
if(video) {
// Mute/unmute video track
	if(!config.myStream.getVideoTracks() || config.myStream.getVideoTracks().length === 0) {
		Janus.warn("No video track");
		return false;
	}
```

**Comment by lminiero** [comment]
As explained in the guidelines, questions like this belong to the [group](https://groups.google.com/g/meetecho-janus). Please open a post there instead.
