### ISSUE TITLE
[Multistream]  Dynamic range  port allocation for ports2 & 3 in Simulcast Missing

### ISSUE THREAD

**Issue by rahmanash-dbz** [meetecho/janus-gateway#2456]
In Multistream branch, there is a check where port value (for ports2 and ports3) should be greater than 0 for creating file descriptor (which has dynamic range port allocation code). 

This check is not there in Master and it was working properly. Just wanted to check , whether this is the intended behaviour or because of multistream branch, lagging behind the master.

**Comment by lminiero** [comment]
We only changed this recently in master, to allow random ports being picked for simulcast too. I guess this hasn't been included in multistream when we aligned the code. I'll take note of the fact this will need to be addressed, but not sure when it will happen (very busy on other things).

**Comment by rahmanash-dbz** [comment]
Noted, I will change code in my local to continue testing things. Shall i close this issue or leave it as a reminder ?

**Comment by lminiero** [comment]
If you fixed it in your code already to match what we do in master, please consider submitting a pull request.

**Comment by rahmanash-dbz** [comment]
Closing the issue as it was fixed in  #2463
