### ISSUE TITLE
Error "undefined reference to `srtp_crypto_policy_set_aes_gcm_256_16_auth'" when starting Janus

### ISSUE THREAD

**Issue by FMPstudio** [meetecho/janus-gateway#2462]
Hey there,

i ran into a strange issue when starting janus gateway under Ubuntu 18.04 on an Azure Cloud Server. The installation process including all necessary dependencies. Also libsrtp-2.2.0 with

`./configure --prefix=/usr --enable-openssl`

janus has been configured to start as a service via root user and was working fine until yesterday. There i stopped the service, restarted janus and it crashed? with the following error:

`sudo ./janus`
`./janus: symbol lookup error: ./janus: undefined symbol: srtp_crypto_policy_set_aes_gcm_256_16_auth`

when i start janus from the commandline without the sudo command, it works as expected. 

When i compile libsrtp with the flag --disable-aes-gcm and reinstall janus, it works again by starting it via root user but then i experience problems with the videoroom plugin. 

Kind regards
René

**Comment by lminiero** [comment]
Please read the FAQ before opening issues.
https://janus.conf.meetecho.com/docs/FAQ#aesgcm

**Comment by FMPstudio** [comment]
I did. But this doesn't help me any further. I figured out, that i had gstreamer also running on that server. After uninstalling gstreamer, janus just started up as expected. So it seems that there is an issue with a shared library - in that case with libsrtp2.

**Comment by alexamirante** [comment]
Gstreamer installs libsrtp as a dependency, no matter if you already compiled it from sources. You should properly set your `LD_LIBRARY_PATH` when launching Janus to have them coexist in the same machine.
