### ISSUE TITLE
autogen.sh errors under Ubuntu 20.04

### ISSUE THREAD

**Issue by qjmiao** [meetecho/janus-gateway#2473]
$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
configure.ac:83: error: possibly undefined macro: AM_CONDITIONAL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:88: error: possibly undefined macro: AC_DEFINE
configure.ac:157: error: possibly undefined macro: AS_IF
configure.ac:363: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by atoppi** [comment]
Ubuntu 20.04 here, everything working as expected. Not a code issue, closing.

**Comment by lminiero** [comment]
Very likely you're just missing some base dependency like `autoconf` or `automake`.
