### ISSUE TITLE
Websocket Support

### ISSUE THREAD

**Issue by gtntdev** [meetecho/janus-gateway#2474]
Is there any plan that Websocket and Secure Websocket protocol ist supported in the future?

Best, Lukas

**Comment by lminiero** [comment]
Websockets are supported already.

**Comment by gtntdev** [comment]
> 
> 
> Websockets are supported already.

Sorry wrong project ... I meant to ask it in the webrtc Streamer project from [here](https://github.com/mpromonet/webrtc-streamer).
