### ISSUE TITLE
Couldn't load event handler plugin 'libjanus_wsevh.so'

### ISSUE THREAD

**Issue by atyachin** [meetecho/janus-gateway#2476]
After building libwebsocket according to readme, and then building Janus and enabling event handlers, I get the following error while Janus loads (Janus log):

```
Loading event handler plugin 'libjanus_wsevh.so'...
[ERR] [janus.c:main:5083]    Couldn't load event handler plugin 'libjanus_wsevh.so': /opt/janus/lib/janus/events/libjanus_wsevh.so: undefined symbol: lws_extension_callback_pm_deflate
```

Here's how to fix it (update Janus Readme):
Build libwebsocket with the following option:
`cmake -DLWS_MAX_SMP=1 -DLWS_WITHOUT_EXTENSIONS=0 -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..`

**Comment by atoppi** [comment]
thanks for spotting this @atyachin, do you want to submit a PR?

**Comment by lminiero** [comment]
Updated the README, thx :+1:
