### ISSUE TITLE
DTLS alert is sent out from Janus

### ISSUE THREAD

**Issue by lm123** [meetecho/janus-gateway#2477]
We sometimes received "DLTS alert" event from Janus, from Janus log, we found the below error messages:

^[[31m[ERR]^[[0m [dtls.c:janus_dtls_srtp_incoming_msg:717] [2039780301088796] Handshake error: error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01

In which condition, the above error is reported?

Before such error appeared, our Janus client can work with Janus normally.

**Comment by atoppi** [comment]
Looks like a DTLS handshake issue.
Which clients are you using to connect to Janus ?

**Comment by lm123** [comment]
The client is written by ourselves. Do you mean it is fault of client?

**Comment by lminiero** [comment]
This seems like an issue with the DTLS stack on the client side or how it's configured, yes, as we've never seen this error before.

**Comment by lm123** [comment]
Our client can work fine with Janus for several days, but from one moment, such error is reported by Janus. And this error will  be existed from then on. Can you give some clue on such strange behavior?

**Comment by lminiero** [comment]
No. As we said, it's very likely a client side issue. Check what ciphers you're exchanging and how for DTLS, our defaults are specified here, https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L171
Closing as not a Janus issue.
