### ISSUE TITLE
Missing tcptype info for the TCP candidate!

### ISSUE THREAD

**Issue by fbellet** [meetecho/janus-gateway#2480]
Hi!

I noticed this error in my janus log, caused by an overflow of the 100 chars buffer used in janus_ice_cb_new_remote_candidate() to store a candidate sdp line.

For example, this buffer is exactly 100 chars long, and doesn't allow to store the tcptype value, being the cause of the previous error:

"remote1 1 tcp 1837072639 xxx.xxx.xxx.xxx 50376 typ prflx raddr xxx.xxx.xxx.xxx rport 50376 tcptype "

**Comment by lminiero** [comment]
It might make sense to increase that buffer size: 100 may indeed be too conservative. I'll push a fix later, thanks for the heads up!

**Comment by lminiero** [comment]
This commit should fix it: I've changed it to `200`, which is what we used already in a few other places too for candidates.
