### ISSUE TITLE
Fix mqtt config file comments to reveal ssl support

### ISSUE THREAD

**Issue by cameronelliott** [meetecho/janus-gateway#2483]
The Mqtt config file implies that SSL is not supported,
and I had to dig through the issues to find out that doesn't seem true.
Issue #1048 and PR #1064 seem to indicate SSL/TLS is supported.

Is a small PR to fix the comments encouraged/allowed?

[Confusing comment in code](https://github.com/meetecho/janus-gateway/blob/971d26387ee22b0e9b01bb107a26ca5d0ba14a7b/conf/janus.eventhandler.mqttevh.jcfg.sample#L18)

**Comment by lminiero** [comment]
That PR added support for SSL/TLS to the MQTT transport plugin, where the related configuration file does have proper comments. The file you linked to is the MQTT event handler, which I don't think supports encryption at this point (but I may be wrong).

**Comment by cameronelliott** [comment]
You are correct, sorry for my mistake.
