### ISSUE TITLE
`make config` fails on Ubuntu 20 due to glib

### ISSUE THREAD

**Issue by SlimeQ** [meetecho/janus-gateway#2493]
on latest Ubuntu 20, I've worked through the entire build process and have installed just fine. The last step is `make config` but I get a ton of errors linking glib.

```
In file included from config.c:20:
config.h:14:10: fatal error: glib.h: No such file or directory
   14 | #include <glib.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [<builtin>: config] Error 1
```

After much googling I've determined that there's just an issue finding glib on Ubuntu for some reason because it gets installed into /usr/include/glib-2.0 instead of /usr/include as expected. This is a relatively easy fix through arguments:

```
make config CFLAGS="-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include"
```

This works much better, but now we get errors about the actual functions being found:

```
gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -lglib-2.0  -Wl,--export-dynamic  config.c   -o config
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
/usr/bin/ld: /tmp/ccfVBPKm.o: in function `janus_config_jfcg_parse':
config.c:(.text+0x201): undefined reference to `config_setting_get_int'
/usr/bin/ld: config.c:(.text+0x22f): undefined reference to `g_snprintf'
/usr/bin/ld: config.c:(.text+0x28c): undefined reference to `janus_log_level'
/usr/bin/ld: config.c:(.text+0x379): undefined reference to `janus_log_timestamps'
/usr/bin/ld: config.c:(.text+0x424): undefined reference to `janus_log_colors'
/usr/bin/ld: config.c:(.text+0x446): undefined reference to `janus_log_global_prefix'
/usr/bin/ld: config.c:(.text+0x452): undefined reference to `janus_log_global_prefix'
/usr/bin/ld: config.c:(.text+0x492): undefined reference to `janus_vprintf'
/usr/bin/ld: config.c:(.text+0x4c0): undefined reference to `config_setting_get_int64'
```

This list is much longer, it appears to be some glib functions as well as janus functions that depend on them.

This may technically be glib's fault (this issue appears to be common on Ubuntu) but in it's current state Janus cannot be compiled correctly under Ubuntu 20.

**Comment by lminiero** [comment]
We use Ubuntu 20 for all our production servers and it builds just fine. It's probably something broken in your setup.

**Comment by SlimeQ** [comment]
I made a typo.

```
make configs
```
not
```
make config
```
