### ISSUE TITLE
Janus drop receiver rtcp packet with video only streaming plugin.

### ISSUE THREAD

**Issue by jhcho-hanvision** [meetecho/janus-gateway#2496]
Hi!

I am testing with streaming plugin with video only.
Sometimes rtp packets are missed, but Janus drop receiver's rtcp packet with below message and no retransmissions.

Dropping RTCP packet with unknown SSRC (1)
Dropping RTCP packet with unknown SSRC (1)
...

It works well for audio and video rtp stream.
I checked janus source code and found that with audio & video case "janus_rtcp_get_receiver_ssrc(buf, buflen)" is used, but with video only case "janus_rtcp_get_sender_ssrc" is used to get ssrc. (recvonly video only stream)

Thank you for your support with Janus.

**Comment by lminiero** [comment]
Is this with master or a recently tagged version? If it's happening on master but not on 0.10.8, it may be a recently introduced change (I remember we slightly changed the RTCP code to address a couple of simulcast issues).

**Comment by atoppi** [comment]
This is a regression introduced after [ecba652](https://github.com/meetecho/janus-gateway/commit/ecba652c8c3f7470f416f81b71c24d746af492f1).
I'll come up with a fix asap.

**Comment by atoppi** [comment]
It should be fixed now, thanks for reporting @jhcho-hanvision
