### ISSUE TITLE
Videoroom segfault

### ISSUE THREAD

**Issue by karelbrascamp** [meetecho/janus-gateway#2497]
Allright, after closing the issue yesterday one of our servers crashed again. 
I'm afraid we couldn't find the crashlog this time.  I did however find the following snippet in the syslog:

https://pastebin.pl/view/304397ae

It has some added asan info, does it help?

Kind regards, Karel

**Comment by lminiero** [comment]
The link doesn't work.

**Comment by karelbrascamp** [comment]
Works fine for me?

**Comment by karelbrascamp** [comment]
Better like this?
https://gist.github.com/karelbrascamp/079225c4767fa4ae46b25cbb7a9c6a5c

**Comment by atoppi** [comment]
It crashed during a `kick` request submitted through the admin api.
Is that something that your application is doing?

**Comment by karelbrascamp** [comment]
Yes, we use the admin api to authenticate users.

**Comment by atoppi** [comment]
Hi,
could you test again [with this commit](https://github.com/meetecho/janus-gateway/commit/52bb0fcd88d32e66af88f0e2bedbc31a8389f4f2) ?

**Comment by karelbrascamp** [comment]
Great! we will test.

Do you maybe know something more about the context where the crash occurred? So we can try to recreate?

**Comment by atoppi** [comment]
> It crashed during a kick request submitted through the admin api.

This is the only thing I could understand from the trace.

**Comment by karelbrascamp** [comment]
Sure, but kicking per se does not crash our janus. We kick all the time. I though maybe you spotted a crash condition you now prevent from occurring. Like for example a user that left himself just before being kicked, a scenario like that. What does your fix prevent?

**Comment by atoppi** [comment]
It just holds a reference to the participant while the `kick` request is being handled, making sure the object is not free'd meanwhile.
This is already done in other places of the code, I've just applied the same pattern.

As of the scenario, it's impossible to get more data without a core dump and/or logs.

**Comment by atoppi** [comment]
If there is any race condition here, very likely it is something related to users going away while being kicked out.

**Comment by karelbrascamp** [comment]
Allright, thanks for the info, I think we can work with that

**Comment by karelbrascamp** [comment]
By the way, we experienced another crash. Not the exact same, it was a segfault caused by a write this time:

https://gist.github.com/karelbrascamp/a7ea6032b7c3e3763a3eae7e79015905

Would you consider this a new issue?

**Comment by lminiero** [comment]
Please let's not mix issues. Confirm the kick one is solved first, and only provide new reports if they include the fix Alessandro mentioned.

**Comment by karelbrascamp** [comment]
Sure thing.

**Comment by lminiero** [comment]
@karelbrascamp any news on the kick issue? Can this be closed?

**Comment by lminiero** [comment]
Closing.
