### ISSUE TITLE
Audio is faster than video streaming

### ISSUE THREAD

**Issue by djdjdjek** [meetecho/janus-gateway#2498]
Hi 

I use janus to broadcast a file (mp4) to website both audio( opus) and video(h264), and it works!

But the audio still fast almost 1 second than video. I am sure the mp4 file is fine.
Could somebody tell me how to solve that.  Thanks.

p.s. I think the video streaming delay, not audio faster.

**Comment by lminiero** [comment]
Please use the forum for questions: https://groups.google.com/g/meetecho-janus
