### ISSUE TITLE
WebRTC error: No capture device found on Chrome

### ISSUE THREAD

**Issue by UQuark0** [meetecho/janus-gateway#2500]
I've called create offer with such media object:
`
media: {
    audioSend: true,
    videoSend: true,
    audioRecv: false,
    videoRecv: false,
    video: "lowres",
},
`

If a webcam is absent the "WebRTC error: No capture device found" error appears. Note that `failIfNoVideo` is not set and defaults to false. The problem doesn't reproduce in Firefox.

**Comment by lminiero** [comment]
Question for the group, not related to Janus: https://groups.google.com/g/meetecho-janus
