### ISSUE TITLE
Support `wss` on websocket event handler plugin

### ISSUE THREAD

**Issue by baster20** [meetecho/janus-gateway#2501]
[https://github.com/meetecho/janus-gateway/blob/5ec8568709c483ae89b1aa77e127d14c3b59428c/events/janus_wsevh.c#L266](https://github.com/meetecho/janus-gateway/blob/5ec8568709c483ae89b1aa77e127d14c3b59428c/events/janus_wsevh.c#L266)

I have bad knowledge of C and I can be wrong, but on this row, function `strcasecmp`  return number biggest then 0 if use address like `wss://.....`. And after that we receive error who say that we need use `wss://`.

      if(strcasecmp(protocol, "ws") || !strlen(address)) {
		JANUS_LOG(LOG_FATAL, "Invalid address (only ws:// and wss:// addresses are supported)\n");
		JANUS_LOG(LOG_FATAL, "  -- Protocol: %s\n", protocol);
		JANUS_LOG(LOG_FATAL, "  -- Address:  %s\n", address);
		JANUS_LOG(LOG_FATAL, "  -- Path:     %s\n", path);
		goto error;
      }

**Comment by lminiero** [comment]
It's not just a matter of removing a check. You need to configure certificates and other stuff to act as a websocket client. We're not planning to extend the WS event handler to add wss support, so I'll close this. In case you manage to add support for it yourself, please consider submitting a pull request.

**Comment by lminiero** [comment]
That said, we should probably change the `strcasecmp(protocol, "ws")` to `strcasecmp(protocol, "ws:")`, otherwise `wss` would indeed pass that check while it shouldn't.

**Comment by lminiero** [comment]
The error message is misleading as well, as we don't really support `wss://` in the handler.

**Comment by lminiero** [comment]
Should be fixed in https://github.com/meetecho/janus-gateway/commit/ee99ce85251e4a47ee27b4358db6f8322f1db892
I really only had to fix the error message in the code, since the check was already correct. 

Incidentally, I also fixed a couple of issues I experienced in my setup, namely:

1. an undefined reference to `lws_extension_callback_pm_deflate`
2. a crash because we were not specifying a subprotocol in the `lws_protocols` object (I'll make the subprotocol configurable in an upcoming commit)

**Comment by baster20** [comment]
Thank you, for answer. 
I already setup all websocket stuff on Janus in `janus.transport.websockets` and on back server as a server for receiving. 
For first I want only use `wss` for security reason and I did not see anywhere that there is no support for `wss`. My bad.
But with use  `ws` now I receive 400 error (`lws_client_handshake: got bad HTTP response '400'`).
I use proxy by Nginx. 
Config:
        
      location /ws {
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_pass http://php:3666;
      }
From [http://www.websocket.org/echo.html](http://www.websocket.org/echo.html) connection is good. 
Can you get me advice , on what lib (janus, libwebsocket, ws server for receive) I need to look ? 

And in your fix [`ee99ce8`](https://github.com/meetecho/janus-gateway/commit/ee99ce85251e4a47ee27b4358db6f8322f1db892) maybe need remove `and` on `"Invalid address (only ws:// **and addresses** are supported)\n")`

**Comment by lminiero** [comment]
Please post questions on the [group](https://groups.google.com/g/meetecho-janus), not here.

**Comment by lminiero** [comment]
> And in your fix [`ee99ce8`](https://github.com/meetecho/janus-gateway/commit/ee99ce85251e4a47ee27b4358db6f8322f1db892) maybe need remove `and` on `"Invalid address (only ws:// **and addresses** are supported)\n")`

Thanks, fixed!

**Comment by baster20** [comment]
Ok, thanks :)
