### ISSUE TITLE
Janus.js errors IE11 (because of the use of "for...of")

### ISSUE THREAD

**Issue by StephaneG31** [meetecho/janus-gateway#2503]
We use Janus as a SIP gateway.
Since some changes it doesn't work anymore on IE11 as you can see below on the meetecho demo
![baQzVoTHJr](https://user-images.githubusercontent.com/4253015/102829617-cd8cdf80-43e7-11eb-9704-00e7942e4b3b.gif)

for...of seems not be supported by IE 11 https://stackoverflow.com/questions/39670401/javascript-for-of-fails-in-ie-11

Is it possible to use a more legacy for avoiding errors on IE 11 ?

As we bundle janus.js to some others library in our SPA, our SPA doesn't work anymore on IE11

**Comment by lminiero** [comment]
Well, since even Microsoft is abandoning IE11 (Teams doesn't support it anymore), I honestly don't know why we should bother :slightly_smiling_face:  So no, sorry, we're not going to do any work on getting it to work, especially considering I already know if we fix this, something else will pop up. If you want to support IE11 for your users, you'll have to make these tweaks to janus.js yourself.

**Comment by tmatth** [comment]
> We use Janus as a SIP gateway.
> Since some changes it doesn't work anymore on IE11 as you can see below on the meetecho demo
> ![baQzVoTHJr](https://user-images.githubusercontent.com/4253015/102829617-cd8cdf80-43e7-11eb-9704-00e7942e4b3b.gif)
> 
> for...of seems not be supported by IE 11 https://stackoverflow.com/questions/39670401/javascript-for-of-fails-in-ie-11
> 
> Is it possible to use a more legacy for avoiding errors on IE 11 ?
> 
> As we bundle janus.js to some others library in our SPA, our SPA doesn't work anymore on IE11

I imagine there's a polyfill for this kind of thing

**Comment by StephaneG31** [comment]
> > We use Janus as a SIP gateway.
> > Since some changes it doesn't work anymore on IE11 as you can see below on the meetecho demo
> > ![baQzVoTHJr](https://user-images.githubusercontent.com/4253015/102829617-cd8cdf80-43e7-11eb-9704-00e7942e4b3b.gif)
> > for...of seems not be supported by IE 11 https://stackoverflow.com/questions/39670401/javascript-for-of-fails-in-ie-11
> > Is it possible to use a more legacy for avoiding errors on IE 11 ?
> > As we bundle janus.js to some others library in our SPA, our SPA doesn't work anymore on IE11
> 
> I imagine there's a polyfill for this kind of thing

No because it's not a function is missing it's language semantic new operator (like a foreach).
So we fix that only in our Code. 
The fix consists only to change 6 lines by 12 lines.
In Software for Enterprise, we can see more than 25% of user traffic comes from IE. 
Even if we don't use Janus.js for IE, all modern javascript application framework bundles all is lib into one file.
So a big errors in one lib file, occurs an error for the bundle file and so crash our application.

So we will report each time this fix on Janus.js by our team.
