### ISSUE TITLE
SIP/TLS Handshake fails in Ubuntu 20.04

### ISSUE THREAD

**Issue by pckhib** [meetecho/janus-gateway#2511]
Ubuntu 20.04 has TLSv1.0 and TLSv1.1 disabled by default. (OpenSSL version 1.1.1).

If I try to initiate a registration with tls (sips), the handshake fails as the protocol version is not supported.
```tls_connect(0x7f243800f4a0): TLS setup failed (error:00000001:lib(0):func(0):reason(1))```

One fix is to reenable TLSv1.0 as described e.g. [here](https://stackoverflow.com/questions/62357205/openssl-cant-establish-ssl-connection-because-unsupported-protocol/62359497#62359497).

As it seems as Sofia-SIP supports TLSv1.2, it would be good to have an option in Janus to configure the protocol version which shall be used.

**Comment by lminiero** [comment]
Not sure what we're supposed to do, though? The link you shared looks like a system configuration, not something Janus related. If you have information on how to configure TLS support in Sofia SIP (so that we can maybe add a new configuration option for it), that would be helpful.

**Comment by pckhib** [comment]
It seems as it might be configurable with [nua_create](http://sofia-sip.sourceforge.net/refdocs/nua/nua_8h.html#a5143ffe880249d0570f428a20035641d):
`All tport tags are passed to tport. They are documented in <sofia-sip/tport_tag.h>`

[TPTAG_TLS_VERSION](http://sofia-sip.sourceforge.net/refdocs/tport/tport__tag_8h.html#aa0b6cea82e2ab72b6c87adc504626dec): Sets the TLS version (version 0 implies SSL2/SSL3).

https://github.com/meetecho/janus-gateway/blob/9ac3053182441f58cb91dfa381b288f2f1f9bfa0/plugins/janus_sip.c#L6597

**Comment by lminiero** [comment]
> [TPTAG_TLS_VERSION](http://sofia-sip.sourceforge.net/refdocs/tport/tport__tag_8h.html#aa0b6cea82e2ab72b6c87adc504626dec): Sets the TLS version (version 0 implies SSL2/SSL3).

Thanks for testing and for the tip! The documentation doesn't say what other values are supported, though: this makes it hard coming up with a configurable property, and I'm not sure whether always forcing `TPTAG_TLS_VERSION(0)` might have undesired consequences in some cases (e.g., for those using sips successfully right now).

**Comment by pckhib** [comment]
This might help:
https://github.com/freeswitch/sofia-sip/blob/f6f29b483e9c31ce8d3e87419ec3deea8679312d/libsofia-sip-ua/tport/sofia-sip/tport_tag.h#L195

```c
enum tport_tls_version {
  TPTLS_VERSION_SSLv2 = (1 << 0),
  TPTLS_VERSION_SSLv3 = (1 << 1),
  TPTLS_VERSION_TLSv1 = (1 << 2),
  TPTLS_VERSION_TLSv1_1 = (1 << 3),
  TPTLS_VERSION_TLSv1_2 = (1 << 4),
};
```

What I couldn't find yet is which value is being used by default.

**Comment by atoppi** [comment]
@pckhib that `enum` seems to be defined only in the freeswitch fork.

**Comment by atoppi** [comment]
`tport_tls.c`
```c
    const SSL_METHOD *meth;

    /* meth = SSLv3_method(); */
    /* meth = SSLv23_method(); */

    if (ti->version)
      meth = TLSv1_method();
    else
      meth = SSLv23_method();

    tls->ctx = SSL_CTX_new((SSL_METHOD*)meth);
```

`ti->version` is set by the tag `TPTAG_TLS_VERSION`.

So if `version` has a defined and not zero value `TLSv1.0` will be used.
Conversely `SSLv23_method` will be used. According to openssl that method has been deprecated but at least on my machine (Ubuntu 20.04) it is defined as:

`#define SSLv23_method           TLS_method`

where `TLS_METHOD` should be the  "_highest version mutually supported by the client and the server_".

**Comment by lminiero** [comment]
> I added the following line to the `nua_create` call and it works.
> 
> ```c
> TPTAG_TLS_VERSION(0),
> ```
> 
> The connection is done using the protocol version 3.3 which is TLSv1.2.

@pckhib I wanted to get back to this and try to add an option, but what I don't get is how you got a TLSv1.2 connection by passing `0` to `TPTAG_TLS_VERSION`, since looking at the code the default (0) is SSLv2.3 as pointed out by @atoppi: that was true in 1.12.11 (the snippet Alessandro copy) but is also [still true](https://github.com/freeswitch/sofia-sip/blob/master/libsofia-sip-ua/tport/tport_tls.c#L325) now in the latest version of the code. As such, I wanted to understand if that property does indeed change something or not. Not sure if you still care about this (a lot of time has passed), but in case some feedback might help, as I don't have a SIP/TLS setup for testing.

**Comment by lminiero** [comment]
Closing as it looks like there's no interest in this anymore.
