### ISSUE TITLE
Crash on v0.10.10 at the startup using libwebsockets 4.1 stable

### ISSUE THREAD

**Issue by antoniotuzzi** [meetecho/janus-gateway#2514]
I had a crash recompiling version ba0b83bbc93b070c3ff47a46eede4cb7d61c59d7 (10.10)
with libwebsockets 4.1 stable

the crash happens at the startup

attaching the log, with sanitizer symbols
[janus log crash with websocket 4.1.log](https://github.com/meetecho/janus-gateway/files/5807483/janus.log.crash.with.websocket.4.1.log)

**Comment by atoppi** [comment]
I do not have any issue with lws 4.1 and janus master.

- use the branch `origin/v4.1-stable` of lws
- clean build lws and janus
- since I know you are compiling on macos, set a specific install path through
```-DCMAKE_INSTALL_PREFIX:PATH=/usr -DLWS_INSTALL_LIB_DIR=lib -DLIB_SUFFIX=64```
this will install lws in `/usr/lib64`

**Comment by atoppi** [comment]
Closing since I think this is a problem with your local setup.
