### ISSUE TITLE
memory overflow g_source_unref error

### ISSUE THREAD

**Issue by andymcauley** [meetecho/janus-gateway#2516]
After several weeks of running on a busy site for several weeks  - regularly over 250 videoroom publishers, many of whom have multiple viewers streaming - the Janus service crashed at a busy time.
The service restarted OK within about 2.5 minutes.

I mentioned this to Alessandro and advised to post the issue here

We are running Janus v0.10.9 on Ubuntu 20.04 LTS over http (https is handled by AWS ELB).

---

There is nothing in the janus log  to indicate any error  (the janus log was at debug level 3 to minimise disk space usage) - just a gap of about 2.5 minutes before a restart message ...

```
 [Sun Jan 10 00:00:07 2021] [WARN] [7058671499411499]     Missing valid SRTP session (packet arrived too early?), skipping...
Logger plugins folder: /opt/janus/lib/janus/loggers
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Server) v0.10.9
---------------------------------------------------
Checking command line arguments...
Debug/log level is 3
 [Sun Jan 10 00:02:39 2021] [WARN] Token based authentication disabled
[Sun Jan 10 00:02:39 2021] [WARN] mDNS resolution disabled, .local candidates will be ignored
```

...However, in the syslogs we can see that janus threw an exception `g_source_unref: assertion 'source != NULL' failed` which seems seems to say the error was in libglib-2.0 

```
Jan 10 00:00:07 ip-172-31-11-21 janus[676]: g_source_unref: assertion 'source != NULL' failed
Jan 10 00:00:07 ip-172-31-11-21 kernel: [2370169.612392] show_signal_msg: 27 callbacks suppressed
Jan 10 00:00:07 ip-172-31-11-21 kernel: [2370169.612394] MHD-single[849]: segfault at 8 ip 00007fbba95094a5 sp 00007fbb47ffda80 error 4 in libglib-2.0.so.0.6400.3[7fbba94d7000+84000]
Jan 10 00:00:07 ip-172-31-11-21 kernel: [2370169.612409] Code: e9 18 01 00 00 0f 8c 8a 00 00 00 49 8b 44 24 08 48 85 c0 0f 84 dc 00 00 00 49 89 c4 49 8b 2c 24 44 3b 75 10 75 df 48 8b 43 58 <48> 8b 40 08 48 85 c0 0f 84 93 00 00 00 48 83 7d 00 00 74 27 48 8b 
```
(kern.log reiterates the error in syslog above)

/var/log/apport.log - says there was a memory overflow error

```
ERROR: apport (pid 3029251) Sun Jan 10 00:00:07 2021: called for pid 676, signal 11, core limit 18446744073709551615, dump mode 1
ERROR: apport (pid 3029251) Sun Jan 10 00:00:07 2021: ignoring implausibly big core limit, treating as unlimited
ERROR: apport (pid 3029251) Sun Jan 10 00:00:07 2021: executable: /opt/janus/bin/janus (command line "/opt/janus/bin/janus")
ERROR: apport (pid 3029251) Sun Jan 10 00:00:07 2021: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 3029251) Sun Jan 10 00:02:38 2021: core dump exceeded 19697 MiB, dropped from /var/crash/_opt_janus_bin_janus.0.crash to avoid memory overflow
ERROR: apport (pid 3029251) Sun Jan 10 00:02:38 2021: wrote report /var/crash/_opt_janus_bin_janus.0.crash
/var/crash/_opt_janus_bin_janus.0.crash 
```

I've added the relevant logs and the crash dump to a zip file at https://drive.google.com/file/d/1mhD3nR-aoDQcQ9Xgh5XJJTI4Rg0q-pQJ/view?usp=sharing

**Comment by atoppi** [comment]
I don't see any stack trace in the logs, it's impossibile to understand where the assertion failed.

**Comment by andymcauley** [comment]
@atoppi thanks for looking.  
i've had another look through the system generated logs and unfortunately, we don't have any fuller information - presumably this is because log level was on 3?

> I don't see any stack trace in the logs, it's impossibile to understand where the assertion failed.

**Comment by atoppi** [comment]
You could try compiling janus with libasan (but I'm not sure a call stack will be shown) or run janus inside `gdb` by issuing
```G_DEBUG=fatal_warnings gdb janus```

**Comment by tmatth** [comment]
Are you running with glib 2.64.3? See https://github.com/meetecho/janus-gateway/issues/2421

**Comment by andymcauley** [comment]
thanks Tristan, this does look like a similar issue to 2421, though we have only experienced it as a one off, rather than periodically under load  - we are running glib 2.64.2, so an upgrade to glib could be in order

> Are you running with glib 2.64.3? See #2421

**Comment by lminiero** [comment]
@andymcauley any update?

**Comment by andymcauley** [comment]
> @andymcauley any update?

@lminiero  - we haven't pursued updating the glib library as the error has only happened the once so far (rather than the regular error the referenced in #2421)  and our service is in use 24/7. If the error happens again, or when we are ready to schedule and update to version of Janus, we will make sure glib is upadted to 2.64.3 or higher

**Comment by lminiero** [comment]
Ack, I'll close the issue then. Feel free to comment here again in case it happens again with an updated glib too.
