### ISSUE TITLE
Janus Delay Video Stream  

### ISSUE THREAD

**Issue by feelpatel** [meetecho/janus-gateway#2523]
Hi,
When I publish video streaming from RPI not getting instantly in the browser.  
I getting an instant stream but it does not display instantly in the video tag.
After some seconds it's displayed.
```
 onremotestream: function(stream) {		
    Janus.attachMediaStream($('#local-viewer_demo-signaling_channel').get(0), stream);
    var video = $('#local-viewer_demo-signaling_channel').get(0);
   video.play();
},
 ```
when I'm debugging I found code didn't receive the below object instantly, when the below object received the video streaming display on the video tag.
```
codecId	RTCCodec_video_Inbound_107
[codec]	H264 (107, level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f)
framesPerSecond	6
qpSum	5369
[qpSum/framesDecoded]	46.2
frameWidth	1920
frameHeight	1080
estimatedPlayoutTimestamp	3.82014e+12
```
Thanks in advance!

@lminiero

**Comment by lminiero** [comment]
Please don't mention me on new issues/PRs: I already get a notification on new ones.
Closing as not an issue, but a question for the [group](https://groups.google.com/g/meetecho-janus) instead (where it has been asked many times already).

**Comment by feelpatel** [comment]
![video_loss](https://user-images.githubusercontent.com/68987312/105481803-8edf9300-5ccd-11eb-9797-47f8b94dfdba.png)
In Javascript Front Side, I didn't receive this object instantly so it's my Javascript Client-side Issue Or Janus Server Side.
If It's a Client-side issue then What I will Change on My Code?
