### ISSUE TITLE
Binding to a specific IP for websocket is not working

### ISSUE THREAD

**Issue by Symbiatch** [meetecho/janus-gateway#2530]
I'm trying to set the websocket transport to a specific IP, not to all. This works for HTTP transport just fine, but for websocket it results in no port bindings at all. No matter what IP I put to ws_ip it doesn't work. Neither does ws_interface.

From code I see it tries to find an interface to the IP and then bind to that. Seems due to how libwebsockets needs it. Without any ws_ip/ws_interface setting it binds to :::8188, with any ip/interface it doesn't bind at all. Logs still claim it successfully started the server in port 8188.

Debian testing, Linux 5.10, libwebsockets16 4.0.20, tried both on hardware and in a Docker container with the same results.

> Loading transport plugin 'libjanus_websockets.so'...
JANUS WebSockets transport plugin created!
Configuration file: /etc/janus/janus.transport.websockets.jcfg
[janus.transport.websockets.jcfg]
    general: {
        json: indented
        ws: true
        ws_port: 8188
        ws_ip: 10.0.1.1
        wss: false
    }
    admin: {
        admin_ws: true
        admin_ws_port: 7188
        admin_ws_ip: 10.0.1.1
        admin_wss: false
    }
    cors: {
    }
    certificates: {
        cert_pem: /etc/ssl/certs/ssl-cert-snakeoil.pem
        cert_key: /etc/ssl/private/ssl-cert-snakeoil.key
    }
libwebsockets logging: 0
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
Admin WebSockets server started (port 7188)...
[WARN] Secure Admin WebSockets server disabled
JANUS WebSockets transport plugin initialized!
        Version: 1 (0.0.1)
           [janus.transport.websockets] JANUS WebSockets transport plugin
           This transport plugin adds WebSockets support to the Janus API via libwebsockets.
           Plugin API version: 8
           Janus API: enabled
           Admin API: enabled

strace results:

> bind(19, {sa_family=AF_INET6, sin6_port=htons(7188), sin6_flowinfo=htonl(0), inet_pton(AF_INET6, "::ffff:10.0.1.1", &sin6_addr), sin6_scope_id=0}, 28) = -1 EINVAL (Invalid argument)

So for some reason it's trying to bind and it just doesn't work. HTTP binds properly to IPv4 address and that works.

> bind(21, {sa_family=AF_INET, sin_port=htons(8088), sin_addr=inet_addr("10.0.1.1")}, 16) = 0

This happens with both ws_ip and ws_interface, they both use the IPv6 address for binding and ws_interface finds the correct IP, but it just won't work.

**Comment by Symbiatch** [comment]
It actually might be the problem that it only binds to IPv6. I cannot connect to localhost:8188 with IPv4 at all even with default configuration, only to :::8188 with IPv6. Maybe that's why it won't allow binding to an IPv4 address either since it wants to only work with IPv6

**Comment by lminiero** [comment]
I think internally libwebsockets uses an IPv6 socket to bind both IPv4 and IPv6, so it's normal you see that in strace: it doesn't mean it's only doing IPv6. In the plugin we just pass whatever you configure to the `iface` property of the `lws_context_creation_info` object, as that's supposed to be enough. I won't be able to test myself until tomorrow. In the meanwhile, you may want to also ask on their issues page.

**Comment by Symbiatch** [comment]
That's the strange thing, usually it binds to both IPv6 and IPv4 but for some reason it won't accept any connections with IPv4 at all, it directly drops them. I'll post on their issues also if I can manage to make it as relevant as possible for them.

At least Janus should realize that the bind did not work instead of saying WS was started here:

> [libwebsockets][DEBUG] lws_interface_to_sa: uplevelling ipv4 bind to ipv6
[libwebsockets][ERR] ERROR on binding fd 16 to port 8188 (-1 22)
[libwebsockets][INFO] _lws_vhost_init_server: lws_socket_bind says -1
[libwebsockets][DEBUG] deferred iface: adding vh default
[libwebsockets][ERR] VH default: iface eth1:0 port 8188 DOESN'T EXIST
WebSockets server started (port 8188)...

**Comment by lminiero** [comment]
> At least Janus should realize that the bind did not work instead of saying WS was started here:

And how exactly are we supposed to do that if the method succeeds?

**Comment by Symbiatch** [comment]
> 
> 
> > At least Janus should realize that the bind did not work instead of saying WS was started here:
> 
> And how exactly are we supposed to do that if the method succeeds?

I assume you could add `LWS_SERVER_OPTION_FAIL_UPON_UNABLE_TO_BIND` to tell the library to return NULL when binding fails?

**Comment by lminiero** [comment]
Thanks for the tip! I'll have to check if this is only available starting from some lws versions, but I'll make some tests and add that tomorrow.

**Comment by Symbiatch** [comment]
> 
> 
> Thanks for the tip! I'll have to check if this is only available starting from some lws versions, but I'll make some tests and add that tomorrow.

I created a PR but didn't check if it's from a specific version, I could do that too and amend it.

Also if I give `LWS_SERVER_OPTION_DISABLE_IPV6` to libwebsockets I can bind to IPv4 correctly and everything works. So I'm not sure what should exactly be done to make it work correctly for IPv6 and IPv4. I'll check a bit more.

**Comment by lminiero** [comment]
Can this be closed too?

**Comment by Symbiatch** [comment]
> Can this be closed too?

This one is still open. It would either require setting an option to disable IPv6 for the library or figuring out otherwise why it doesn't work. I haven't heard anything yet from libwebsockets so not sure how to go forward on it. 

Checking settings IP address for : would work for adding the IPv6 disable flag or not, but if I want to bind by interface then it wouldn't work, so I don't have a good idea how to handle it for all cases and I assume it's not desirable to just add a flag for "I want IPv4" since it should just work.

**Comment by atoppi** [comment]
FWIW I was not able to replicate the issue.
I've compiled lws two times, with `-DLWS_IPV6=ON` and `-DLWS_IPV6=OFF` (default).
In both cases I was able to bind the ws server through `ws_ip = 127.0.0.1` and to correctly setup a connection from my Chrome browser.

`-DLWS_IPV6=ON`

```
netstat -nlp | grep 8188
tcp6       0      0 127.0.0.1:8188          :::*                    LISTEN      27154/janus

netstat -nat | grep 8188
tcp        0      0 127.0.0.1:36774         127.0.0.1:8188          ESTABLISHED

```

`-DLWS_IPV6=OFF` (default)
```
 netstat -nlp | grep 8188
tcp        0      0 127.0.0.1:8188          0.0.0.0:*               LISTEN      30669/janus

netstat -nat | grep 8188   
tcp        0      0 127.0.0.1:38580         127.0.0.1:8188          ESTABLISHED

```

**Comment by atoppi** [comment]
forgot to mention I'm using lws v4.1 (from `v4.1-stable` branch)

**Comment by Symbiatch** [comment]
Seems others have also had the same issue with lws and it might be related to kernel version or something. I can run on Linux Subsystem for Windows some lws code just fine binding to interfaces, but the exact same code on my Debian server (kernel 5.10 AMD64) exhibits this issue. Also on lws issue a user mentioned they had this exact thing happen after OS upgrade and had to do the exact same fix (adding disable IPv6) to mitigate it. Also the server has IPv6 whereas my laptop doesn't, so that can also affect things.

There's some incompatibility thing in the library, but to determine what and why is a bit more difficult.

In any case this isn't directly a Janus problem so not sure if this issue should be open here or not. Of course it could be fixed with an additional check/option, but if it could be handled somehow in lws that would be the best way. I'll keep digging a bit to figure out why this is. I can of course patch Janus myself with IPv6 disabling if others don't have the issue.

**Comment by lminiero** [comment]
Ack, we'll close then, since neither Alessandro nor me seem to be able to replicate, and it does indeed sound like a lws thing. In case you discover anything more, please do feel free to use this issue to let us know.

**Comment by goekce** [comment]
Archlinux here. I have `libwebsockets` 4.2.1 and get similar error:
```
Loading transport plugin 'libjanus_websockets.so'...
libwebsockets logging: 3
[libwebsockets][ERR] ERROR on binding fd 13 to port 8188 (-1 97)
[libwebsockets][ERR] VH default: iface lo port 8188 DOESN'T EXIST
[libwebsockets][ERR] init server failed
[FATAL] [transports/janus_websockets.c:janus_websockets_init:679] Error creating vhost for WebSockets server...
[WARN] No WebSockets server started, giving up...
[WARN] The 'janus.transport.websockets' plugin could not be initialized
```
