### ISSUE TITLE
Videoroom: ICE restarts as a subscriber

### ISSUE THREAD

**Issue by remvst** [meetecho/janus-gateway#2537]
Hey there,

I'm currently building an application using the videoroom plugin and was looking into ICE restarts. So far I think I got them to work for the publishing side, however I find the subscriber side a bit confusing when reading the docs.

> Notice that the same exact steps we just went through (`watch` request, followed by JSEP offer by the plugin, followed by start request with JSEP answer by the viewer) is what you also use when renegotiations are needed, e.g., for the purpose of ICE restarts.

There is no mention of that `watch` request in the docs (and I get an error if I fire one), so I assumed it was a `join` request instead.

So I tried to send the following message:

```js
{
  janus: 'message',
  body: {
    request: 'join',
    ptype: 'subscriber',
    room: 2329283243204937,
    feed: 1611781504646,
    audio: true,
    video: true,
    data: true
  },
  transaction: 'TODO0.08565046641877228',
  apisecret: 'janussecret'
}
```

which gives me an `ack` back:

```js
{
  janus: 'ack',
  session_id: 6065274145616990,
  transaction: 'TODO0.08565046641877228'
}
```

and later on an error event (and also an error in Janus' logs):

```js
{
  janus: 'event',
  session_id: 6065274145616990,
  transaction: 'TODO0.08565046641877228',
  sender: 4863436952761774,
  plugindata: {
    plugin: 'janus.plugin.videoroom',
    data: {
      videoroom: 'event',
      error_code: 425,
      error: 'Already in as a subscriber on this handle'
    }
  }
}
```

This seems fair but still prevents me from getting a new offer from Janus. Is there another (maybe undocumented) request that needs to be fired in order to perform ICE restarts for subscribers?

**Comment by tmatth** [comment]
There is an issue in the documentation here, as you point out `watch` is not a valid videoroom request. I believe the sequence you want is:
- `join` as subscriber
- `configure` with `restart:true`
- this responds with `configured` + the JSEP you need to process and send an answer for with a `start` request to complete the sequence

Hopefully someone more confident with the semantics here can submit a documentation fix PR :)

**Comment by remvst** [comment]
> There is an issue in the documentation here, as you point out `watch` is not a valid videoroom request. I believe the sequence you want is:
> 
>     * ~`join` as subscriber~ you've already joined, so this step isn't needed
> 
>     * `configure` with `restart:true`
> 
>     * this responds with `configured` + the JSEP you need to process and send an answer for with a `start` request to complete the sequence

Thank you for the quick reply, will try that and report back ;)

**Comment by remvst** [comment]
Can confirm I received a new offer with this solution (don't forget `restart` field in the `configure` request).

So I think there are two issues in the docs:
- the `watch` request part should be replaced with a `configure` request
- the `restart` field should be mentioned in the `configure` docs

I'd submit a PR but I'm also not super confident about the exact semantics (and also wouldn't want to take credit from you actually coming up with the solution)

**Comment by lminiero** [comment]
That's a copy/paste type, since `watch` is a Streaming plugin request, and that's indeed how you restart subscriptions there (you do a watch+start again). Tristan is right, you use `configure` with a `restart:true` in the VideoRoom to ask the plugin to send a new offer that originates an ICE restart. I'll update the docs.
