### ISSUE TITLE
videoroom: SDP PT parsing issue if codec profile is set

### ISSUE THREAD

**Issue by tmatth** [meetecho/janus-gateway#2544]
### Summary
For videoroom publishers that explicitly set the codec profile, it seems that the wrong payload type is being retrieved (specifically the pt number after the one we want, or -1) from the offer SDP. For chrome 88, I hadn't noticed the issue since given the adjacent lines:
```
"a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\n"
"a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f\r\n"
```
returning 108 masked the bug (since the profile-level-id matched, even though it has an unsupported packetization-mode that should be excluding it).

However in chrome 90, it's effectively returning -1 and rejecting video:
```
[Tue Feb  2 17:12:54 2021] [WARN] Couldn't find codec we needed (h264) in the offer, rejecting video
```
presumably due to the addition of AV1 (payload type 35).

The line here is suspect since from the logs it seems to be logging that it has the next payload type already, e.g.
```
H.264 profile 42e01f found --> 35
```
where 35 is the payload type for AV1 (new to chrome 90).

https://github.com/meetecho/janus-gateway/blob/213b6c7c63a2fca5450d3dd7672a9472e8235ed1/sdp-utils.c#L731
--
### Reproducer
This should be illustrated by the reproducer here:
https://github.com/meetecho/janus-gateway/pull/2543

which, given some real SDPs (after they've been preprocessed by janus to remove RTX et al) fail at extracting the correct payload types:

```
$ ./sdp-testcase
# expecting 125, 108 is the next line and should be disqualified since it has packetization-mode=0
H.264 profile 42e01f found --> 108
[WARN] Got pt 108 for h264 42e01f

H.264 profile 42e01f found --> 35
[WARN] Got pt -1 for h264 42e01f

VP9 profile 0 found --> 108
[WARN] Got pt -1 for vp9 0

VP9 profile 0 found --> 35
[WARN] Got pt -1 for vp9 0

VP9 profile 2 found --> 108
[WARN] Got pt -1 for vp9 2

VP9 profile 2 found --> 35
[WARN] Got pt -1 for vp9 2
```

Hopefully I'm not missing something obvious and the reproducer makes the problem clear.

### Versions affected
master 213b6c7c63a2fca5450d3dd7672a9472e8235ed1

**Comment by lminiero** [comment]
Thanks for spotting this, I'll look into this later today :+1:
