### ISSUE TITLE
incorrect SDP answer in the video room

### ISSUE THREAD

**Issue by B-R-Bender** [meetecho/janus-gateway#2547]
Hello guys!

I, recently, was looking for a way to set the audio bitrate in the videoroom higher (by default, it was about 32kbps). The way this could be achieved is to mungle local SDP before creating an offer to tweak audio fmtp line. For instance from this:
`a=fmtp:111 minptime=10;useinbandfec=1\r\n`
to this:
`a=fmtp:111 minptime=10;useinbandfec=1;cbr=1;stereo=1;maxaveragebitrate=160000\r\n`
So I've tried to `createOffer.customizeSdp` callback and surprisely it has no effect. So I found this #1430. And it seems to be that when we receiving an answer from janus along with remote description it has no fmtp line for an audio source at all. Hence I've experienced no changes on audio quality (monitoring over webrtc-internals).
But, if I've mungled answers SDP with this dirty hack:
`jsep.sdp = jsep.sdp.replace("a=rtpmap:111 opus/48000/2\r\n", "a=rtpmap:111 opus/48000/2\r\na=fmtp:111 minptime=10;useinbandfec=1;cbr=1;stereo=1;maxaveragebitrate=160000\r\n");` I've got the expected behaviour.

So from my perspective it's an issue. And it could be fixed in a 2 different ways:

1. make janus to send correct answer with requested _Optional parameters_ as listed in 6.1 of [RFC7587](https://tools.ietf.org/html/rfc7587)
2. provide a way to customize answers SDP just like `createOffer` does

second option is what I've done to my code, so I've ended up with this [gist](https://gist.github.com/B-R-Bender/8e71e8f9b72584e53748f607199814ad)

I can do a PR if it's ok, so please give some feedback on this.
And thank you for all your time.

**Comment by lminiero** [comment]
`customizeSdp` is available both for createOffer and createAnswer. We use it in the Streaming demo already:

https://github.com/meetecho/janus-gateway/blob/master/html/streamingtest.js#L161

**Comment by B-R-Bender** [comment]
I'm talking not about `createAnswer` but `handleRemoteJsep` instead which is `prepareWebrtcPeer` which is actually is `RTCPeerConnection.setRemoteDescription()`

**Comment by lminiero** [comment]
Then yes, a PR would be welcome: as long as you use `customizeSdp` for consistency, and not the weird function name I see in your gist :slightly_smiling_face:

**Comment by B-R-Bender** [comment]
I'm using such kind of naming to self describe methods as something dangerous and better not to touch right away in the method signature. But from the consistency perspective sure I will use `customizeSdp`. Give me a couple minutes I'll prepare a PR.

**Comment by B-R-Bender** [comment]
@lminiero you can check out the PR
and thank you for a quick response!
