### ISSUE TITLE
meson_options.txt:1:0: ERROR: Unknown type feature

### ISSUE THREAD

**Issue by NirAbel** [meetecho/janus-gateway#2551]
hello,
I'm trying to install the project and it's failed with this error:

The Meson build system
Version: 0.45.1
Source dir: /home/nir/Documents/libnice
Build dir: /home/nir/Documents/libnice/build
Build type: native build

meson_options.txt:1:0: ERROR: Unknown type feature.

A full log can be found at /home/nir/Documents/libnice/build/meson-logs/meson-log.txt

**Comment by lminiero** [comment]
libnice related question, so doesn't belong here. Closing.

**Comment by jcormier** [comment]
FYI, meson version for ubuntu 18.04 is too old.  Install with pip instead.
```
sudo apt install ninja-build
sudo -H pip3 install meson
```
