### ISSUE TITLE
SIP is still registered after send {request: 'unregister'} message

### ISSUE THREAD

**Issue by GX-CHEN** [meetecho/janus-gateway#2552]
In client-side JavaScript, when using the following code to unregister from SIP  (based on this comment to send unregister request: https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L155), I notice that the SIP is connected & registered, seems the `unregister` didn't succeed.

```
        const unregister = {
          request: 'unregister'
        };
        sipcall.send({ message: unregister });
```
Not sure if it's a bug from the Janus side, or maybe my usage wan't correct.
I didn't see the example of `unregister` in https://github.com/meetecho/janus-gateway/blob/master/html/siptest.js, so can I request to have the correct usage of unregister from SIP (from client-side JS)?

**Comment by lminiero** [comment]
If you mean the demo, it's not meant to change when you send "unregister". If from a SIP perspective the unregister did its job, then the plugin is working as expected.

**Comment by GX-CHEN** [comment]
> If you mean the demo, it's not meant to change when you send "unregister". If from a SIP perspective the unregister did its job, then the plugin is working as expected.

Sorry for the confusion with my wording in issue description.

1. Please ignore the `demo` part in my description
2. The issue I want to report is simply that: **sending "unregister" doesn't work**, because after sending`{  request: 'unregister' };` message, the SIP server is still regiestered

**Comment by lminiero** [comment]
Have you checked the SIP traffic? I believe an unregister is basically a REGISTER with an expire set to `0`, so you can check if we're indeed doing that.

**Comment by GX-CHEN** [comment]
> Have you checked the SIP traffic? I believe an unregister is basically a REGISTER with an expire set to `0`, so you can check if we're indeed doing that.

My team-member helped to verified that after sending `{ request: 'unregister' }`, there is no action for set expire as `0`.

However based on your comment, I think I found the root cause: the request_text should be `unsubscribe` (https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L3201) instead of `unregister` mentioned in the comment here https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L155

So turns out to be a quite small thing, I think either update the comment, or update the request_text value will reduce confusions. 

Thanks for the help!

**Comment by lminiero** [comment]
You're looking at the wrong part of the code: `unsubscribe` is used to cancel a previous SUBSCRIBE, _not_ a REGISTER. This is where the `unregister` is handler:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L3088

which does call `nua_unregister`. Make sure you're not receiving errors back when calling it.

**Comment by lminiero** [comment]
Just tried myself and sending

    sipcall.send({message: {request: "unregister"}});

I do see the REGISTER with `Expires: 0` message being sent. As such, this feels like an issue on your side.

**Comment by GX-CHEN** [comment]
> Just tried myself and sending
> 
> ```
> sipcall.send({message: {request: "unregister"}});
> ```
> 
> I do see the REGISTER with `Expires: 0` message being sent. As such, this feels like an issue on your side.

Got it, thanks for help looking into it! So it's probaly an issue on my side. I'll close the issue.
