### ISSUE TITLE
./configure requires npm

### ISSUE THREAD

**Issue by AntoninRousset** [meetecho/janus-gateway#2555]
Following the compilation procedure of the README, it seems the configure phase fails if `npm` is not installed:
```sh
config.status: error: in `/tmp/janus-gateway':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
```
Quick fix: install `npm`

**Comment by lminiero** [comment]
No, configure doesn't depend on npm. Closing as not an issue.

**Comment by AntoninRousset** [comment]
Okay, any idea why this errors pops out?
I am working in a docker so it is pretty easy for me to tell you that janus won't configure without npm installed...

**Comment by lminiero** [comment]
Configure scripts depend on stuff like `autoconf` and `automake`, and have been around for much longer than `npm` has. It's much more likely that when you install `npm` you end up installing the dependency the configure script requires too. I don't know what's missing in your setup as I don't know it, but we use Docker a lot and we most certainly don't install `npm` when we install Janus there. Please continue the discussion on the [group](https://groups.google.com/g/meetecho-janus) if still an issue, as we only use Github for bugs.
