### ISSUE TITLE
Use of strerror(errno) pattern in Janus

### ISSUE THREAD

**Issue by tmatth** [meetecho/janus-gateway#2561]
Currently (as of commit 4f8943adf7c3292a1a4aaa08fd022c1308b9357d) there are 140 invocations of `strerror(errno)`.

The problem is that since `strerror` uses a static buffer, this idiom isn't safe to use in a multithreaded process like Janus. The alternatives are:
- `char *strerror_r(int errnum, char *buf, size_t buflen);` <- caller passes  a buffer and its size, this is guaranteed to be thread-safe
- using the `%m` format string, e.g.
    `JANUS_LOG(LOG_ERR, "Error in sendto... %d (%s)\n", errno, strerror(errno));`
   becomes
   `JANUS_LOG(LOG_ERR, "Error in sendto... %d (%m)\n", errno);` (note the `%m` format string doesn't take an argument).
   
 I'd be happy to submit a PR but this is a lot of churn so I wanted to get feedback first.

**Comment by lminiero** [comment]
That's a fair rationale. What does the `%m` format do? It looks like the easiest way to address this, without the need for additional bufferrs.

**Comment by tmatth** [comment]
> That's a fair rationale. What does the `%m` format do? It looks like the easiest way to address this, without the need for additional bufferrs.

In glibc, it's basically equivalent to using `strerror_r` internally apparently.

**Comment by lminiero** [comment]
Looks like it's GNU specific, though, so may not be portable. Maybe we do need to use `strerror_r`? Which would be a PITA.

**Comment by tmatth** [comment]
> Looks like it's GNU specific, though, so may not be portable. Maybe we do need to use `strerror_r`? Which would be a PITA.

FYI:
```
   Feature Test Macro Requirements for glibc (see feature_test_macros(7)):

       strerror_r():
           The XSI-compliant version is provided if:
           (_POSIX_C_SOURCE >= 200112L) && !  _GNU_SOURCE
           Otherwise, the GNU-specific version is provided.
```

that said I'm not aware of any compilers supported by Janus that don't support this feature (BTW do you maintain a list of supported compilers, aside from CI?)

**Comment by lminiero** [comment]
We only test with `gcc` and `clang`. No idea if WSL and MacOS support `%m` though.

**Comment by tmatth** [comment]
> We only test with `gcc` and `clang`. No idea if WSL and MacOS support `%m` though.

I think MacOS supports `strerror_r` but not `%m` :-1:
