### ISSUE TITLE
Disabling VideoRoom publisher recording in 'configure' request doesn't work

### ISSUE THREAD

**Issue by biodranik** [meetecho/janus-gateway#2564]
A room in VideoRoom plugin is created without a `secret` and with `record: true` (`lock_record: true/false` doesn't change anything).
A publisher joins the room like in your VideoRoom JS demo, and then sends a `configure` request with `record: false`. Supposedly, this publisher's video, audio, and data should not be recorded after that. But it's not the case: the recordings are still saved on the Janus server.

P.S. `enable_recording` request with `record: false` works fine

**Comment by lminiero** [comment]
Are you using master? This reminds me of #2550 which we fixed already.

**Comment by lminiero** [comment]
Just tested and it works as expected. Closing.

**Comment by biodranik** [comment]
@lminiero Yes, I am using the master branch and reproduced it again on the current master. The bug reproduces, if the recording is disabled in the `configure` request inside `createOffer` reply, like in your videoroom demo (in `publishOwnFeed()`).

It works in a separate `configure` request with `record: false` at any later time (but empty 8-byte .mjr files are still created in this case).
