### ISSUE TITLE
multistream: segfault when sending videocodec in joinandconfigure 

### ISSUE THREAD

**Issue by daviderenger** [meetecho/janus-gateway#2568]
Just tried out the new fixes merged to multistream-branch. And when sending 'videocodec' in the joinandconfigure message to videoroom, no matter what it is, valid codec or not, Janus crashes. This is the last logs:

```
Will remove payload type 124 (124 rtx/90000)
Will remove payload type 125 (125 rtx/90000)
Will remove payload type 127 (127 rtx/90000)
Will remove payload type 98 (98 rtx/90000)
 -------------------------------------------
  >> Anonymized
 -------------------------------------------
[1]    7375 segmentation fault (core dumped)  /opt/janus/bin/janus -F /usr/local/etc/janus
```

Tested with both Chrome and Firefox, same result.

**Comment by lminiero** [comment]
Yes, I'm working on this right now, as I also noticed that we lost the ability as a publisher to specify which codec to force in general (only the codecs configured when creating the room are used). I should hopefully have a fix for both later today.

**Comment by lminiero** [comment]
PS: for future issues, please provide [meaningful traces](https://janus.conf.meetecho.com/docs/debug). The snippet you shared provides no info at all that could help identify issues by just looking at them.

**Comment by daviderenger** [comment]
Ok thanks, yeah sorry for that I will post more detailed information next time!

**Comment by lminiero** [comment]
Should be fixed in https://github.com/meetecho/janus-gateway/pull/2211/commits/f2be6df1613a35f2bf0b74158dcb2c1f32b36873
