### ISSUE TITLE
janus videoroom doesn't dispay the stream forward by the aiortc when i run janus example code in aiortc

### ISSUE THREAD

**Issue by zhiweny1122** [meetecho/janus-gateway#2571]
janus videoroom doesn't dispay the stream forward by the aiortc when i run janus example code in aiortc .
I can the videos when I use chrome ,but i can't see the video from aiortc client .
Is this a bug ? the aiortc log seems ok, but thers is no video in janus default room 1234
my command is as folllow：
python janus.py http://www.streamocean.com:8088/janus --play-with a.mp4

the Janus log is like this and these is no display video.

ARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...

**Comment by zhiweny1122** [comment]
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [3782647910941351]     Missing valid SRTP session (packet arrived too early?), skipping...
[ERR] [dtls.c:janus_dtls_retry:1118] [3782647910941351] DTLS taking too much time for component 1 in stream 1...
[janus.plugin.videoroom-0x7f8c4c002450] No WebRTC media anymore; 0x7f8c4c008800 0x7f8c4c001860
[3782647910941351] WebRTC resources freed; 0x7f8c4c008800 0x7f8c1c0022a0

**Comment by lminiero** [comment]
You may want to ask the aiortc developers. The only thing I see in this log is that DTLS didn't complete, so the WebRTC is not up as far as Janus is concerned.

**Comment by zhiweny1122** [comment]
sure , I will ask aiortc side at the same time .

**Comment by atoppi** [comment]
I have tested the aiortc echotest sample we distribute in `test` folder and everything seems to work as expected.
```
atoppi@atoppi:~/src/janus-gateway/test$ ./test_aiortc.sh 
Starting Janus binary from /home/atoppi/src/janus-gateway ...
Waiting for some seconds before launching the test ...
Launching test /home/atoppi/src/janus-gateway/test/echo.py ...
INFO:echo:Creating session
INFO:echo:WebSocket connected
INFO:echo:Session created
INFO:echo:Attaching handle
INFO:echo:Sending keepalive
INFO:echo:Handle attached
INFO:echo:DataChannel (JanusDataChannel) created
INFO:echo:Keepalive OK
INFO:echo:Sending message to the plugin
INFO:echo:Janus Event --> event
INFO:echo:Track audio received
INFO:echo:Track video received
INFO:echo:Running for a while...
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 57245) -> ('192.168.1.170', 40393)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.170', 37301) -> ('192.168.1.170', 40393)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('172.17.0.1', 44492) -> ('192.168.1.170', 40393)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 57245) -> ('192.168.1.169', 49855)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 57245) -> ('192.168.1.170', 40393)) State.WAITING -> State.IN_PROGRESS
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 57245) -> ('192.168.1.170', 40393)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.170', 37301) -> ('192.168.1.170', 40393)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('172.17.0.1', 44492) -> ('192.168.1.170', 40393)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 57245) -> ('192.168.1.169', 49855)) State.WAITING -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.170', 37301) -> ('192.168.1.169', 49855)) State.FROZEN -> State.FAILED
INFO:ice:Connection(0) Check CandidatePair(('172.17.0.1', 44492) -> ('192.168.1.169', 49855)) State.FROZEN -> State.FAILED
INFO:ice:Connection(0) ICE completed
INFO:echo:Janus Event --> webrtcup
INFO:echo:Janus Event --> media
INFO:echo:DataChannel (JanusDataChannel) open
INFO:echo:DataChannel (JanusDataChannel) sending: echo-ping
INFO:echo:DataChannel (JanusDataChannel) received: Janus EchoTest here! You wrote: echo-ping
INFO:echo:Janus Event --> media
INFO:echo:Ending the test now
INFO:echo:Test Passed
INFO:echo:DataChannel (JanusDataChannel) closed
INFO:echo:Janus Event --> event
INFO:echo:Destroying session
INFO:echo:Janus Event --> hangup
INFO:echo:Session destroyed
INFO:echo:Closing WebSocket
INFO:echo:Connection closed
TEST SUCCEEDED
```

**Comment by tmatth** [comment]
On Wed, Mar 3, 2021 at 3:55 AM Mike <notifications@github.com> wrote:
>
> janus videoroom doesn't dispay the stream forward by the aiortc when i run janus example code in aiortc .
> I can the videos when I use chrome ,but i can't see the video from aiortc client .
> Is this a bug ? the aiortc log seems ok, but thers is no video in janus default room 1234
> my command is as folllow：
> python janus.py http://www.streamocean.com:8088/janus --play-with a.mp4

You might want to try with a vp8 file, something (videoroom or aiortc
more likely) may be defaulting to vp8.

**Comment by tmatth** [comment]
On Wed, Mar 3, 2021 at 8:50 AM Tristan Matthews <tmatth@videolan.org> wrote:
>
> On Wed, Mar 3, 2021 at 3:55 AM Mike <notifications@github.com> wrote:
> >
> > janus videoroom doesn't dispay the stream forward by the aiortc when i run janus example code in aiortc .
> > I can the videos when I use chrome ,but i can't see the video from aiortc client .
> > Is this a bug ? the aiortc log seems ok, but thers is no video in janus default room 1234
> > my command is as folllow：
> > python janus.py http://www.streamocean.com:8088/janus --play-with a.mp4
>
> You might want to try with a vp8 file, something (videoroom or aiortc
> more likely) may be defaulting to vp8.

Also it will help rule out profile-level-id mismatch or some other
h.264 specific thing.

**Comment by zhiweny1122** [comment]
My aiortc client works well with your public janus server and my command is as follow
 python janus.py https://janus.conf.meetecho.com/janus --play-from 190309153658147087.mp4 --record-to aa.ts.
Howerver the aiortc client can record the video from chrome ,but it does't display the video from aiortc.
I didn't know why the dtls handshake not compled in Janus side. 
BTW : 
It is very helpful if you tell how to set the janus codec to h264 in server side .
Thanks.

**Comment by lminiero** [comment]
Closing as not an issue. Please use the group for further help.
