### ISSUE TITLE
multistream: Janus crashed when a participant join a videoroom

### ISSUE THREAD

**Issue by vuta1927** [meetecho/janus-gateway#2572]
Recently our janus server sometime had been crashed when an user try join videoroom. This is trace from core dump file when janus crash: https://pastebin.com/v8bgcpmb

Looked at your codes janus_videoroom.c, I think you guys are missing check null condition in line 8825 for 'ps' variable.

**Comment by lminiero** [comment]
There's no line 8825 in the multistream VideoRoom. Please try the latest changes, not older commits.

**Comment by vuta1927** [comment]
Strangely, I can find this line in janus_videoroom.c in mutilstream branch, it has been commited 8 days ago. https://github.com/meetecho/janus-gateway/blob/f2be6df1613a35f2bf0b74158dcb2c1f32b36873/plugins/janus_videoroom.c#L8825

**Comment by lminiero** [comment]
My bad... I was looking at the master version :man_facepalming: 
You're right, we probably need that additional check over there, I'll add it shortly.
