### ISSUE TITLE
Document "timeout" and "detached" REST-like API messages

### ISSUE THREAD

**Issue by strohel** [meetecho/janus-gateway#2576]
When using Janus (with videoroom plugin), we encounter these messages in addition to documented ones:
```json
{
    "janus": "timeout",
    ...
}
```
```json
{
    "janus": "detached",
    ...
}
```
I have not found them documented on https://janus.conf.meetecho.com/docs/rest.html or https://janus.conf.meetecho.com/docs/videoroom.html

I was able to guess some of their semantics from the code - i.e. `"timeout"` seems to imply that the session has been destroyed completely. But it would be nice to document them explicitly (unless that's already done somewhere where I haven't found it).

CC @application-developer-DA @jxs.

**Comment by RSATom** [comment]
To keep session alive you have to send `keepalive` message periodically.

**Comment by lminiero** [comment]
Fixed.

**Comment by strohel** [comment]
Thanks a bunch, @lminiero! @application-developer-DA, @jxs check the commit, contains some good extra info.
