### ISSUE TITLE
Video room crash

### ISSUE THREAD

**Issue by enhany** [meetecho/janus-gateway#2578]
I run janus for long time, today I got crash in master branch.

unfortunately I can't repeat it, because it was in one of server in production.
stack:
https://pastebin.com/raw/dtm67g1d

`
(gdb) f 1
  0x00007f4e7401891f in janus_videoroom_setup_media (handle=<optimized out>) at plugins/janus_videoroom.c:5078
5078                                    janus_mutex_unlock(&participant->room->mutex);

(gdb) p participant
$1 = (janus_videoroom_publisher *) 0x7f4e249cf030

(gdb) p participant->room
$2 = (janus_videoroom *) 0x0
` 

What can I do more to find the reason?

**Comment by lminiero** [comment]
Good chances are we fixed this already, as I think we already addressed race conditions like this recently. You may want to try with master, since you mentioned running Janus for a long time (so may be an older version). Should it happen again, libasan dumps are preferrable, as they tell us where/why a resource was destroyed when used again: https://janus.conf.meetecho.com/docs/debug

**Comment by enhany** [comment]
@lminiero 

It's last master. This is one of servers where I run latest master:
`-rwxr-xr-x 1 root root 3089136 Mar  8 22:53 /usr/local/janus/bin/janus`
as you can see - compiled 8 of March.

This is my first crash of Janus for long long time - this is why I doubt it will be again (and I hope it will not).

**Comment by atoppi** [comment]
> What can I do more to find the reason?

reproduce with libasan

**Comment by enhany** [comment]
> reproduce with libasan

I already recompile it with libasan. waiting...

**Comment by atoppi** [comment]
We got another report of the very same issue, so marking this as bug.
@enhany would you please enable verbose logging (5) and locking_debug (check admin page) before trying to reproduce ?

**Comment by aliceinspase** [comment]
> @lminiero 
> 
> 
> 
> It's last master. This is one of servers where I run latest master:
> 
> `-rwxr-xr-x 1 root root 3089136 Mar  8 22:53 /usr/local/janus/bin/janus`
> 
> as you can see - compiled 8 of March.
> 
> 
> 
> This is my first crash of Janus for long long time - this is why I doubt it will be again (and I hope it will not).

**Comment by lminiero** [comment]
@enhany can you try with the latest master? We added a fix for another issue, that we suspect may actually be at the root of what you were experiencing, since it was in the notify-participants code: https://github.com/meetecho/janus-gateway/commit/01529b6faa395ebeeb106928db30c7138c5225eb

**Comment by enhany** [comment]
@lminiero 
I will install latest master today night.

**Comment by lminiero** [comment]
Any update? Or can this be closed?

**Comment by enhany** [comment]
still nothing... may be this bug has been fixed in meanwhile.
