### ISSUE TITLE
Janus VideoRoom Api join

### ISSUE THREAD

**Issue by ajayjohnwick** [meetecho/janus-gateway#2583]
"request"   : "join",
"ptype"     : "publisher",
 "room"      :  room_id,
 "id"        : str(_id),
  I run this code and  I get this message as output
{'janus': 'ack', 'session_id': 3268536221895769, 'transaction': 'KYe8NemGrm'}
I didn't get {"janus":"success"}
Can you please explain why

**Comment by lminiero** [comment]
Question for the group, and all explained in the documentation anyway.
