### ISSUE TITLE
Asterisk Registration Works but Can Not Call

### ISSUE THREAD

**Issue by r00tk1ll** [meetecho/janus-gateway#259]
I tested the Janus Gateway on your demo site and using the SIP Gateway Demo I can successfully register to my Asterisk PBX and call SIP Peers.

But when I installed the Janus Gateway on my CentOS 7 server I  can register to my Asterisk PBX but I can not call any SIP Peers.

So Since it works on your demo page I'm assuming I may have some settings wrong on the Janus Gateway. 

In the console logs it shows:
Notifying application...
siptest.js:132  ::: Got a message :::
siptest.js:133 {"sip":"event","result":{"event":"calling"}}
siptest.js:161 Waiting for the peer to answer...

At this point it just sits there and times out (408)

Could you please give me a starting point on how to troubleshoot this?

Thanks

**Comment by saghul** [comment]
Does your Asterisk server get any SIP traffic from Janus?

**Comment by r00tk1ll** [comment]
Yes I see sip traffic via sip debug the Invite and Sip Read Packets, Im not noticing any errors accept in the log file I see:

chan_sip.c: Skipping packet - Bad request protocol about 6 times

This is an Amazon Server thats behind NAT and the firewall is off.

Any help would be appreciated

**Comment by saghul** [comment]
> chan_sip.c: Skipping packet - Bad request protocol about 6 times

That's your problem right there. Asterisk is not liking the SIP traffic it has received. Which is weird, because what Janus sends it's pretty standard. Can you paste such a packet?

**Comment by lminiero** [comment]
Yep, as Saul said it's probably an issue with your setup. If you can paste the SIP messaging (in something like pastebin and not in plain text here, please) that could help.

**Comment by r00tk1ll** [comment]
Here is the relevant asterisk debug output and the asterisk sip debug output in paste bin: 

http://pastebin.com/TcvdP0kp

Thanks for helping guys!

**Comment by saghul** [comment]
The SIP traffic looks all weird, like packet fragmentation perhaps. Can you capture it with ngrep?

~~~~
ngrep -d any -W byline -t port 5060
~~~~

**Comment by r00tk1ll** [comment]
Heres the output for that command:
http://pastebin.com/X9b4JFhw

So logically, since the official Janus demo page works perfectly with my asterisk server, the problem must be on our janus servers end, right?

Is the demo page on a server that is not behind NAT? Could you possibly share the settings from the janus.cfg file on the demo server?

Thanks

**Comment by lminiero** [comment]
The cfg is the vanilla one, basically: the server is not NATted.

**Comment by saghul** [comment]
The ngrepped traffic you pasted shows incomplete SIP packets. I have no
idea how that could happen, they are not that big! Perhaps try to use SIP
over TCP.

**Comment by r00tk1ll** [comment]
Could this just be a NAT issue? I'd hate to troubleshoot all of this because of a router lol 

Is there anyway to test if Sofia sip is working properly? I can successfully run the echo test plugin in this current setup without any problems

**Comment by lminiero** [comment]
Over UDP you'd never get incomplete packets: packets that are larger than the MTU would simply be dropped, no fragmentation there. Do you have any tcpdump/Wireshark capture available?

**Comment by r00tk1ll** [comment]
Wireshark on the client, janus server, or asterisk server?

**Comment by saghul** [comment]
You can log what Sofia send by exporting this variuable before running Janus:

~~~~
export TPORT_LOG=9
~~~~

**Comment by r00tk1ll** [comment]
Ok I ran that command then janus, where are the sofia logs saved to? Also, Im running the janus html files on a separate server than the janus gateway, this shouldn't matter should it?

**Comment by saghul** [comment]
> Ok I ran that command then janus, where are the sofia logs saved to?

They are just printed to stdout.

> Also, Im running the janus html files on a separate server than the janus gateway, this shouldn't matter should it?

That shouldn't matter.

**Comment by r00tk1ll** [comment]
Ok here is the output of the janus gateway with TPORT_LOG=9, let me know if something stands out:

http://pastebin.com/rFbuL820

Thanks Again!

**Comment by r00tk1ll** [comment]
Is there a way I can ask about this in the janus gateway google group? It wont let me post there...

Thanks

**Comment by lminiero** [comment]
You need to subscribe to the group to post.

**Comment by lminiero** [comment]
There's no SIP dump in that log... besides, debug 7 is unneeded here, it just adds a lot of noise.

Anyway, from the previous log you sent I see a via line followed by an SDP followed by the SIP request/headers. If that's what actually going on the wire (a wireshark/tcpdump would clarify that) then that's the cause: it's not valid SIP.

**Comment by r00tk1ll** [comment]
Thanks lminiero, so what do you recommend I do to troubleshoot this?

**Comment by lminiero** [comment]
A wireshark/tcpdump capture on either side of the SIP communication (ideally on Janus) could help. Of course just add a filter for SIP traffic, other traffic would not be relevant.

**Comment by lminiero** [comment]
Any update? without a dump there's nothing we can do.

**Comment by lminiero** [comment]
Closing for lack of feedback and because a few things changed in the SIP code in the meanwhile. If you can still replicate it with the latest version, feel free to reopen.
