### ISSUE TITLE
Trivial: Websocket event handler janus is not properly handling the path part in the backend parameter

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2603]
Humbled over a trivial bug (weekend exercise ;)) where janus seems not to properly handle the url path parameter in the janus.eventhandler.wsevh.jcfg

Path was configured like this:
backend = "ws://10.20.3.220:3000/janus/ws"

But the request is missing the first slash and therefore not properly routed through a straight forward node-express-router implementation.

**GET janus/ws HTTP/1.1**
Pragma: no-cache
Cache-Control: no-cache
Host: 10.20.3.220
Origin: http://10.20.3.220
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Key: xvZWqCblY08tyMEfCV2Orw==
Sec-WebSocket-Protocol: janus-event-handlers
Sec-WebSocket-Version: 13

HTTP/1.1 400 Bad Request
Connection: close

I could only solve it with a double slash
backend = "ws://10.20.3.220:3000//janus/ws"

**Comment by tmatth** [comment]
@JanFellner sounds like this issue?
https://github.com/warmcat/libwebsockets/commit/d2c140c8edb057e6e539b4b4a3f4581f1f0050ee

**Comment by lminiero** [comment]
@tmatth thanks for the pointer, so this means we'll have to fix the URI parsing in our code, correct?

**Comment by lminiero** [comment]
Should be fixed now.

**Comment by JanFellner** [comment]
Will check thanks... :)

**Comment by JanFellner** [comment]
Works as expected. Thanks.
