### ISSUE TITLE
missing export in janus.js and janus.nojquery.js files

### ISSUE THREAD

**Issue by Qvatra** [meetecho/janus-gateway#2605]
Hello,
I was trying to import janus-gateway client-side by doing the following:
`const { Janus } = require('janus-gateway/html/janus.nojquery.js');`

the problem is that Janus object is not beeing exported so nothing is get binded and I cant access
`Janus.init` function in my context.

wouldnt it be better to export `Janus` object in both `janus.js` and `janus.nojquery.js` files by adding:
`exports.Janus = Janus;` ?

**Comment by lminiero** [comment]
Not sure what version you're trying, but we haven't had a `janus.nojquery.js` in the repo in years.

**Comment by Qvatra** [comment]
@lminiero hi, thanks for reply!

By running ```npm i janus-gateway@latest``` this is what installed:
"janus-gateway": "^0.2.3",
that package has both ```janus.js``` and ```janus.nojquery.js``` in ```node_modules/janus-gateway/html``` folder

**Comment by lminiero** [comment]
That's not our package and not something we maintain, and `0.2.3` is incredibly old. Closing as not an issue.

**Comment by lminiero** [comment]
I think the `npm` folder in tis repo is what you're looking for, for up-to-date stuff.

**Comment by Qvatra** [comment]
@lminiero, ok thank you.
doest is mean that the intended way of having janus.js in my project is copy pasting that file?

**Comment by lminiero** [comment]
Not familiar with that code, please check the docs: https://janus.conf.meetecho.com/docs/js-modules
