### ISSUE TITLE
Janus Dtls handshake send big packet than mtu size on ubuntu1804

### ISSUE THREAD

**Issue by zhiweny1122** [meetecho/janus-gateway#2608]
It looks like janus sever send a big packet than the mtu size during the Dtls handshake when it connect to aiortc client.
I use wireshark to capture the packet during the dtls handshake process.
Is it a bug of Janus because i set the mtu size to 1200 in janus jcfg file ?
I attached the wireshark picture.
![20210330114446](https://user-images.githubusercontent.com/26403439/112942197-57281800-9162-11eb-9951-899bbff59745.jpg)

**Comment by lminiero** [comment]
Seems to be working as expected here. Maybe the OpenSSL/LibreSSL/BoringSSL version you're using?

**Comment by zhiweny1122** [comment]
my openssl is 1.1.1

**Comment by zhiweny1122** [comment]
your public janus site send the certificate fragment and reassembled ? 
Can you tell me to set this ?
![good20210331135345](https://user-images.githubusercontent.com/26403439/113097576-b69d2b00-9229-11eb-95aa-65fb74385537.jpg)

**Comment by lminiero** [comment]
Please stop posting photos, they're useless and don't help.
Are you passing your own certificate? Does this happen when you let Janus autogenerate certificates too?

**Comment by zhiweny1122** [comment]
This issue is resloved when i update the certificate to janus signed.
It is a bug of janus.

**Comment by lminiero** [comment]
A colleague just made me notice that your picture shows the TLS traffic (TCP), *NOT* DTLS. As such, closing as there's no issue at all.
