### ISSUE TITLE
Missing simulcast statistics in eventhandler connection for firefox

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2610]
Hi,

i started using the websocket event handler to get to know about statistics of the different PCs.
While implementing this i am removing code from the admin API i used to poll for these statistics.
I now humble over something i did not notice before but also looks like an issue in the admin api or at least a different behaviour.

I create a peerConnection from FireFox to the videoroom (using unified-plan / transceiver).
I add audio and video (including simulcast). Everything is working fine.

Using the admin api i can now poll for the stats and i receive statisics about the different simulcast layers **BUT** the **rtcp_stats** **video-sim1**, **video-sim2** structs are missing. I did not really care about those so far as i was only interested in the traffic on the simulcast layers which are located in the **in_stats**. If i remove the video stream and add it again the missing structs are in the admin result data.

The interesting thing is that the websocket implementation does not offer me (likely due to the missing rtcp_stats elements) any information about simulcast at all. I do only see the video-sim1, video-sim2 events if i remove/add the stream.

I pasted the admin poll blob on pastebin:
https://pastebin.com/TB9x5Xv9 - initial admin poll payload after adding the video for the 1.st time
https://pastebin.com/2rE2zVBQ - admin poll payload after removing and adding the video for the 2.nd time

On chrome everything is working straight forward. Did not check safari so far (would do tomorrow)

Jan

**Comment by JanFellner** [comment]
Hi Lorenzo,

i am using the way you propose it in your samples (chrome uses munging, firefox uses the api) but i already had using the sample in mind. Will recheck and post here.

Jan

**Comment by lminiero** [comment]
No need, I just made an EchoTest from Chrome with `simulcast2=true` and could replicate. I have a guess on what may be the cause, so I'll let you know if I have a fix.

**Comment by JanFellner** [comment]
Looks good, just checked out master working as expected.
