### ISSUE TITLE
Stutter in video - Question.

### ISSUE THREAD

**Issue by TheSashmo** [meetecho/janus-gateway#2612]
Hey everyone, I'm creating a ticker here, because I have tried everything possible, at least to my abilities.

I've been dabbling with Janus and webrtc for a while now and have come up with some great little solutions, but I have encountered a problem with playing video. Now, the issue isn't noticeable much when there is a lot of motion on the screen. For example a music video playing, you can barely notice, or a talking head, you don't see any issue at all. But if you look at this video clip and the camera panning up and down, you can see a constant stutter in the video. There is a jump in the video at the top of the panning, thats just the end of the recording sample that I was using to feed my transcoder for the solution. 

The point is to focus on the jutter in the video.

I've tried many different encodes of the live video and I just can eliminate it. When I check the webrtc internals, I can see that the FPS is not constant at 60, or at 30 at the rate that I encoded it at. I'm using gstreamer to feed the stream, and I am using janus as the webrtc server to handle the rest.

I am working towards an ultra low latency video player solution and I have it. It works real good. I can do two way webcam to webcam chats, but the presentation of my external source is just not consistently smooth.

Things that I have tried:

B-frames on or off
intra-refresh on or off
profile levels
presetshigh bitrate, low bitrate
MTU settings
Queues in gstreamer pipeline

Anyways thanks in advance. I would consider paying for some consultation to close this up for me, or better yet, offer up a part time or full time job as part of our team to develop cool things like this.

This is on a LOCAL network. There is no network losses and its all on the same machine!

Here is a link to the video so that you can see what I have: https://www.dropbox.com/s/36i6qvx1fv8uvr8/Screen%20Recording%202021-03-17%20at%206.44.15.mov?dl=0

**Comment by lminiero** [comment]
You're not saying much to help identify the issue. What's the resolution? What's the bitrate? The encoding pipeline in gstreamer? Are you ensuring packets are small enough? etc.  That said, this question probably belongs to the [group](https://groups.google.com/g/meetecho-janus), as it's a user issue and likely not a bug.

**Comment by lminiero** [comment]
Closing for lack of feedback.
