### ISSUE TITLE
error creating inbound SRTP session for component 1 in stream 1

### ISSUE THREAD

**Issue by karan10kk** [meetecho/janus-gateway#2614]
[WARN] [2497217044689508]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [7438770168762002]     Missing valid SRTP session (packet arrived too early?), skipping...
[WARN] [7438770168762002]     Missing valid SRTP session (packet arrived too early?), skipping...
**[ERR]** [dtls.c:janus_dtls_srtp_incoming_msg:923] [2497217044689508] **Oops, error creating inbound SRTP session for component 1 in stream 1??**
**[ERR]** [dtls.c:janus_dtls_srtp_incoming_msg:924] [2497217044689508]  -- 1 (srtp_err_status_fail)

does anyone have any solution for it..??

**Comment by lminiero** [comment]
As explained in the guidelines, questions like this belong to the [group](https://groups.google.com/g/meetecho-janus). Closing.
