### ISSUE TITLE
Websocket event handler delivers media events (type:32, subtype:1) multiple times

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2615]
Using the videoroom sample with simulcast i receive the video receiving event three times but i would expect it to be delivered only once.

here filtered for the relevant events:
`{
  emitter: 'janus.estos.de',
  type: 16,
  subtype: 6,
  timestamp: 1617265195421999,
  session_id: 8445497250597053,
  handle_id: 2417694560024348,
  opaque_id: 'videoroomtest-tlYgvHcj3tfS',
  event: { connection: 'webrtcup' }
}`
`{
  emitter: 'janus.estos.de',
  type: 32,
  subtype: 1,
  timestamp: 1617265195434044,
  session_id: 8445497250597053,
  handle_id: 2417694560024348,
  opaque_id: 'videoroomtest-tlYgvHcj3tfS',
  event: { media: 'audio', receiving: true }
}`
`{
  emitter: 'janus.estos.de',
  type: 32,
  subtype: 1,
  timestamp: 1617265195465856,
  session_id: 8445497250597053,
  handle_id: 2417694560024348,
  opaque_id: 'videoroomtest-tlYgvHcj3tfS',
  event: { media: 'video', receiving: true }
}`
`{
  emitter: 'janus.estos.de',
  type: 32,
  subtype: 1,
  timestamp: 1617265195512588,
  session_id: 8445497250597053,
  handle_id: 2417694560024348,
  opaque_id: 'videoroomtest-tlYgvHcj3tfS',
  event: { media: 'video', receiving: true }
}`
`{
  emitter: 'janus.estos.de',
  type: 32,
  subtype: 1,
  timestamp: 1617265195512602,
  session_id: 8445497250597053,
  handle_id: 2417694560024348,
  opaque_id: 'videoroomtest-tlYgvHcj3tfS',
  event: { media: 'video', receiving: true }
}`

Furthermore i have difficulties in handling the separated statistic events cause i cannot tell when i have received all the events for the videoroom plugin handle. Could be:
* audio
* video
* audio&video 
* audio&video&video-sim1&video-sim2
* video&video-sim1&video-sim2

But while receiving the events there is no way for the receiver to distinguish which events i will receive and or when i did receive all the events for a plugin handle. (pulling the admin api i get all data at once so i know the scenerie)

Best from my point of view would be a flag in the event handler configuration to provide the statistics plugin handle related summarized and not each media and layer one by one.

What i currently do is that i store the events i received as bit mask and if i receive an event i already received i know that i have them all. But that delays the first events and the second comes right after the first. If media is removed it again occurs cause i need one iteration to adopt to the new events.

I really don´t know how to properly use it the way it´s currently implemented :)

**Comment by lminiero** [comment]
"Video receiving true" events are three because you're using simulcast, which uses three separate video streams, so it's expected. I agree that it's missing an indication about the substream they refer to, though, so that needs to be fixed. Not sure why you mention the VideoRoom, though: stats have nothing to do with plugins, and are the same no matter which you use.

> But while receiving the events there is no way for the receiver to distinguish which events i will receive and or when i did receive all the events for a plugin handle. (pulling the admin api i get all data at once so i know the scenerie)

That's the main point of event handlers: pushing info when it's availlable. If you need a snapshot with multiple info, just use the Admin API.

> Best from my point of view would be a flag in the event handler configuration to provide the statistics plugin handle related summarized and not each media and layer one by one.

We're not going to change the way events are pushed via event handlers, sorry: definitely not before multistream is merged.

**Comment by JanFellner** [comment]
> "Video receiving true" events are three because you're using simulcast, which uses three separate video streams, so it's expected
I would understand this if i would receive the same events when i disable simulcast layers on the client side but there are no such events then (neither if i remove a layer nor if i re add it - getStreamEncodings -> active:false ->setStreamEncodings). But actually they are only dispatched initially but not while things are changing...

>That's the main point of event handlers: pushing info when it's availlable. If you need a snapshot with multiple info, just use the >Admin API.
If i just want statistic data the admin api adds a huge bunch of other data. I call janus every second for every subscription and every publishing. I just want to remove the not needed stuff and therefore i use the eventhandler api. 15 person in one videoroom -> 211 requests a second, every ~5msec a request that adds so much payload i don´t need, also puts load on janus cause i don´t know how efficient that admin data is fetchable inside janus...

>We're not going to change the way events are pushed via event handlers, sorry: definitely not before multistream is merged.
Just wanted to mention it. No need to change any plan. Multistreaming would be a big step forward also concerning bwe on the client side... Definetly interested in it :)

I just think the way it´s currently implemented makes it hard to use it for such a purpose. (As i also found some other bugs i suspect that not that many are currently using the eventhandler api)

**Comment by lminiero** [comment]
I've added the missing substream to the `receiving` events, when simulcast is used. I verified this works with the EchoTest, and that even when I stop layers via `setParameters()` on the transceiver sender and then resume them later on, I get the `receiving:false` and then `receiving:true` I expect.

**Comment by lminiero** [comment]
Mentioning @mirkobrankovic as I think he mentioned this lack of support for simulcast events being an issue in the past.
