### ISSUE TITLE
Multistream: unsubscribing using publisher mid is not working with string_ids set

### ISSUE THREAD

**Issue by isnumanagic** [meetecho/janus-gateway#2617]
Hi,
On `multistream` branch, sending `unsubscribe` request with `feed` + `mid` fields when using `string_ids` does not seem to be working. After digging through the code, it seems that case is only covered when `string_ids` is set to false, even though that should not be a problem. Here is the problematic conditional: https://github.com/meetecho/janus-gateway/blob/50c5600d458d56eb2ecd6e77f83349451db63ad7/plugins/janus_videoroom.c#L8609

**Comment by isnumanagic** [comment]
`feed_id` is only set when `string_ids` is set to false, as seen here: https://github.com/meetecho/janus-gateway/blob/50c5600d458d56eb2ecd6e77f83349451db63ad7/plugins/janus_videoroom.c#L8592

**Comment by lminiero** [comment]
Good catch, it's very likely that this is one of the leftovers when we merged the support for string identifiers from master. I'll have a look and fix it.

**Comment by lminiero** [comment]
The above commit should fix it: I found a few other parts where it needed the fix too.
