### ISSUE TITLE
current gentoo port fails

### ISSUE THREAD

**Issue by tunerooster** [meetecho/janus-gateway#2618]
Does anyone know who maintains the gentoo ebuild for this package?  It fails to compile because of a known issue with janus-websockets.c and 
libwebsockets.  It appears that the problem has been fixed in the current source code, but the gentoo janus-gateway-0.4.5.ebuild (from the ikelos layman overlay) is using old code.

It would be useful to have a janus-gateway-9999.ebuild version of the ebuild which pulls from github, but an update to the current stable release would be fine as well.

I have not been able to get this package to compile on gentoo and hope someone can help!

Thanks!

**Comment by lminiero** [comment]
I don't know but it's not us. You may want to ask on the [group](https://groups.google.com/g/meetecho-janus) instead.
