### ISSUE TITLE
eventfd descriptors accumulating

### ISSUE THREAD

**Issue by NotherGithubAccount** [meetecho/janus-gateway#2619]
We're using a relatively simple Duktape plugin derived from the echo demo for the video side of a chat, the chat itself is managed by a separate websocket server.

Over time, file descriptors for "-> anon_inode:[eventfd]" accumulate, until pushEvent() calls start failing with "Error spawning pushevent thread (at line 642)". I assume that's when some sort of limit for these descriptors is reached.

Janus is version 0.10.8. (Still observing 0.10.10, but I couldn't find any changes related to such behavior.)
libnice 0.1.18
Duktape: 2.6.0
libwebsocket 4.1.4
libsrtp 2.3.0

Admittedly, it seems unlikely that this is a general bug nobody else noticed, but I'm not sure what one could do wrong in a Duktape plugin that would cause this. We are cleaning up streams and sessions, and the increase does not correlate with the number of connections or streams, it's much slower. It's also leaking memory, far more than we use within the plugin, suggesting that it's more than just the FD not getting closed properly.

Any help debugging this would be much appreciated.

**Comment by cppdev-1** [comment]
This case seems akin to https://github.com/meetecho/janus-gateway/issues/2522 .

**Comment by NotherGithubAccount** [comment]
Thanks for the reference. Not sure what to make of #2522. The op says it was a problem with the open file limit, yet apparently measured 256k open files. I don't think it's the same issue.

Under normal operations after a restart, we use about 200-300 file descriptors. We ran into Debian's 1024 limit after a couple of days, so we changed that to 100k. I don't remember what the exact error message was back then, but it did point to an open file limit. Now we're seeing problems at around 4k FDs with that different error. I'm guessing we're running into another limit, but that's just a symptom.

**Comment by cppdev-1** [comment]
@NotherGithubAccount I've meant that there is a descriptor leak.

**Comment by lminiero** [comment]
Whether the cause is the same or not, you should provide the same information we asked there. Nothing we can do otherwise.

**Comment by NotherGithubAccount** [comment]
@cppdev-1 Yes, but unless I'm misinterpreting that issue, the problem was a false method of measuring open files and the limit not being set correctly for that use case, not a real leak.

I see the increase of eventfd references in /proc/$PID/fd.

**Comment by NotherGithubAccount** [comment]
@lminiero Unfortunately that setup is already in production. I'll try to get an strace during a quiet time. Though it's a very gradual increase, it likely won't be enough to test with a handful of connections.

**Comment by atoppi** [comment]
@NotherGithubAccount have you montored the number of threads spawned by Janus ?

>the increase does not correlate with the number of connections or streams
maybe something related to event handlers or transports used ?

**Comment by NotherGithubAccount** [comment]
@atoppi I hadn't thought of that, no. Since I recently restarted the server and don't have a reference point, I can't yet say if threads increase with eventfd handles. It should become obvious in a few days.

We're not using any event handlers. The sample handlers were compiled, but aren't enabled in the config, log says "Event handlers support disabled" on startup. The only transport is wss, number of sockets reported by netstat look normal.

**Comment by atoppi** [comment]
@NotherGithubAccount any update about this issue ? Have you managed to get a `strace` capture for eventfds?

**Comment by NotherGithubAccount** [comment]
Sorry, no, pesky day job getting in the way. ;-)

Though I can say that number of threads reflects usage and do not increase with event FDs.

**Comment by lminiero** [comment]
Closing for lack of feedback, so I assume it's not a problem anymore. Feel free to reopen if you think it's still an issue and you can provide more details.
