### ISSUE TITLE
Add Authorization header to each request to server

### ISSUE THREAD

**Issue by st-vinguyen** [meetecho/janus-gateway#2621]
Hi,
I'm now using `janus-gateway` on the client-side.
I want to create a proxy as a middleware that will handle the business logic before forwarding the request to Janus server.
Anyone, please let me know if there is any way to attach my access token (through Authorization header) to each request.
Thanks

**Comment by lminiero** [comment]
Please ask questions on the [group](https://groups.google.com/g/meetecho-janus). Closing as not a code issue.

**Comment by st-vinguyen** [comment]
@lminiero 
I already have the solution to deal with it. Thanks for your reply.
