### ISSUE TITLE
Several mutex locks not initialized in Janus streaming plugin (janus_streaming.c) when using pthread mutexes

### ISSUE THREAD

**Issue by dbrichards** [meetecho/janus-gateway#2622]
Hi.

In the file **janus_streaming.c**, I believe the global mutex "**mountpoints_mutex**" and the "**mutex**" in the **janus_streaming_mountpoint** typedef (when dynamically allocated) are not initialized. This is only a problem if pthread mutexes are used (**USE_PTHREAD_MUTEX** is defined).  If Glib mutex locks are used (the janus default), the problem is masked because Glib uses zero as its initialization value.

**Comment by dbrichards** [comment]
CORRECTION... I apologize!  After further review, I believe the only uninitialized mutex is "**mountpoints_mutex**". Thanks.

**Comment by lminiero** [comment]
Thanks, fixed :+1:

**Comment by dbrichards** [comment]
Thanks!
