### ISSUE TITLE
Enabling websocket event handler but disabling websockets leads to broken wsevh

### ISSUE THREAD

**Issue by ssalenik** [meetecho/janus-gateway#2628]
This is pretty minor, but if you configure with `--disable-websockets` transport but with `--enable-websockets-event-handler` the libjanus_wsevh lib doesn't get linked to libwebsockets, I think because the `WS_MANUAL_LIBS="-lwebsockets"` only gets sets when `--enable-websocekts`:

https://github.com/meetecho/janus-gateway/blob/b40d98a9f20c7fb4b71a090cfc7f54fa20eac0fc/configure.ac#L567-L591

Not sure if the preferred solution would be to set `-lwebsockets` on  `--enable-websockets-event-handler` as well, or to not allow the event handler without the transport? But I don't think the transport is needed if we just want the event handler, right?

**Comment by lminiero** [comment]
That's a good catch, thanks. I'm wondering if we have the same issue with other protocols libraries that have both a transport plugin and an event handler.

**Comment by lminiero** [comment]
Looks like WS was the only one affected, so I added the missing line you spotted. Thanks for the heads up!
