### ISSUE TITLE
Janus crashes when sending multiple successive "attach" messages over websocket

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#263]
Using git HEAD, we get a hard crash when sending multiple "attach" message one after another on the same websocket connection. Perhaps it is ICE related. Debug logging always ends here:

Log dump 1: http://pastebin.com/WznDawN7

And another log dump: http://pastebin.com/4QHMt4PG

[Update: moved logs to pastebin]

**Comment by lminiero** [comment]
Please don't paste huge lines of text in the comments, as explained in CONTRIBUTING.md... use services like gist or pastebin.

Multiple attach create different handles, and different handles have different ICE contexts, so I don't think it's ICE related. Please provide a gdb stacktrace, logging alone doesn't provide enough info.

**Comment by lminiero** [comment]
Any news on this? I can't replicate it: I'm able to send tons of "attach" requests in a row over the same WebSocket connection and they all work. Closing as apparently not an issue, feel free to reopen if you can provide more details to replicate the problem.
