### ISSUE TITLE
How to diable B frame when I use chrome to connect janus 

### ISSUE THREAD

**Issue by zhiweny1122** [meetecho/janus-gateway#2632]
Hi Janus:
I set the codec = h264 and h264_profile = "42e01f" in janus jcfg.
I use the chrome and a usb logitech camera  to visit the janus server , and the video display well.
when I use the aiortc to pull the stream upload by chrome, I found the h264 stream have B frames.
Is there a way to avoid the B frame in Janus ?
"

**Comment by lminiero** [comment]
Questions for the group or discuss-webrtc, not here. Closing.
