### ISSUE TITLE
The Janus SIP Plugin not parsing custom headers in REGISTER 200 OK.

### ISSUE THREAD

**Issue by dbrichards** [meetecho/janus-gateway#2636]
The Janus SIP Plugin does not parse custom headers in the REGISTER 200 OK message. I have specified the custom (non-standard) headers that should be read on incoming SIP events using the "incoming_header_prefixes" field in the register request.  It appears the code does this for many other message types, but not for the REGISTER 200 OK. 

I'm not sure if this is by design or not. Would it be possible get this capability for the REGISTER 200 OK? Thanks!

**Comment by lminiero** [comment]
It looks like `janus_sip_get_incoming_headers` is used in case a register fails, but not when it succeeds. Probably an oversight in the original PR. I'll add it shortly.

**Comment by dbrichards** [comment]
Thanks!
