### ISSUE TITLE
Frame marking RTP header extension cannot be parsed

### ISSUE THREAD

**Issue by cppdev-1** [meetecho/janus-gateway#2638]
A value is assigned to `participant->framemarking_ext_id`
```
if(msg_simulcast && (participant->vcodec == JANUS_VIDEOCODEC_VP8 ||
							participant->vcodec == JANUS_VIDEOCODEC_H264)) {
						JANUS_LOG(LOG_VERB, "Publisher is going to do simulcasting\n");
						janus_rtp_simulcasting_prepare(msg_simulcast,
							&participant->rid_extmap_id,
							&participant->framemarking_ext_id,
							participant->ssrc, participant->rid);
					} else {		
```
However, a value of `context->framemarking_ext_id` is used.
```
gboolean janus_rtp_simulcasting_context_process_rtp(janus_rtp_simulcasting_context *context,
		char *buf, int len, uint32_t *ssrcs, char **rids,
		janus_videocodec vcodec, janus_rtp_switching_context *sc) {
...		
		if(janus_rtp_header_extension_parse_framemarking(buf, len,
				context->framemarking_ext_id, JANUS_VIDEOCODEC_H264, &tid) == 0) {
...		
}
```
The value of `participant->framemarking_ext_id` is never assigned to `context->framemarking_ext_id` so that `janus_rtp_header_extension_parse_framemarking` cannot parse frame marking extension.

**Comment by lminiero** [comment]
The frame marking extension is deprecated and going to be removed from all browsers (who don't use it either anymore, to my knowledge). As such, we're going to remove it from Janus as well, so I wouldn't worry about whether it's set or not.

**Comment by cppdev-1** [comment]
@lminiero Does that mean temporal layers in H.264 are deprecated? Is frame marking rtp extension not used in H.264 temporal layers anymore? What is the replacement?

**Comment by lminiero** [comment]
Yes, to my knowledge it's not used anymore, so there's no way to use temporal layers in H.264 simulcast at the moment. The future replacement is being discussed in AVTCORE, but will probably be the generic extension they're working on for AV1 as well.

**Comment by cppdev-1** [comment]
@lminiero Thank you! I think this issue can be closed.

**Comment by lminiero** [comment]
No need to close, we can keep it open until I merge #2640, which is the PR to remove framemarking. This way people encountering the same problem will know what to refer to.

**Comment by Romk-a** [comment]
@lminiero Could you tell me please how to adjust the temporal layer parameter in h264 (simulcast) if we don't use framemarking?

**Comment by lminiero** [comment]
> @lminiero Could you tell me please how to adjust the temporal layer parameter in h264 (simulcast) if we don't use framemarking?

You don't, it will just be substreams. Temporal layers are not strictly speaking part of simulcast anyway, since they're SVC stuff.
