### ISSUE TITLE
clearInterval in videoroomtest.js not working because bitrateTimer has different ID

### ISSUE THREAD

**Issue by azimot** [meetecho/janus-gateway#2642]
Janus Ver : 0.11.1
Plugin : videoroom
Issue : in videoroomtest with just 2 publisher/subscriber, one of them refreshed their page then issue occurred  

setInterval function always returns an ID to use it for clear in future but if you check by a simple log print, this part of code running by 4 !!

In line of 635 : 

```
    bitrateTimer[remoteFeed.rfindex] = setInterval(function () {
        // Display updated bitrate, if supported
        var bitrate = remoteFeed.getBitrate();
    $('#curbitrate' + remoteFeed.rfindex).text(bitrate);
    // Check if the resolution changed too
    var width = $("#remotevideo" + remoteFeed.rfindex).get(0).videoWidth;
    var height = $("#remotevideo" + remoteFeed.rfindex).get(0).videoHeight;
    if (width > 0 && height > 0)
        $('#curres' + remoteFeed.rfindex).removeClass('hide').text(width + 'x' + height).show();
}, 1000);
```

That means we have 4 setInterval function that wants to update bitrate and video dimensions but last one ID kept in  bitrateTimer variable and when publisher feed has destroyed, oncleanup event in newRemoteFeed function called, and by using 
`clearInterval(bitrateTimer[remoteFeed.rfindex]);`
Just one of four interval function will be clear because we had more interval IDs three of them are lost and then not cleared.

How do I to resolve that : 
I used clearInterval(bitrateTimer[remoteFeed.rfindex]); before assigning any value to bitrateTimer[remoteFeed.rfindex] (line : 635) if have anyone so will be cleared, but this is not technical, in fact that part of code must be called by one because one new feed we got for one new publisher/subscriber .

**Comment by lminiero** [comment]
Yes, it's normal you see the log being printed more than once: the subscriber code is invoked for each subscription you create, and you will often even multiple subscription instances. The setInterval ID is owned by the `remoteFeed` instance, which will be different for each instance, and will each work on a different UI element typically.

Unless you can explain better what issue you think is happening, I'll have to close this as a non-issue.

**Comment by azimot** [comment]
Yes you are right, I checked it again with more accuracy and see this is not a problem.

Sorry for opening new Issue.
I close it as it was not an Issue
