### ISSUE TITLE
centos7.9 compile janus-gateway, error: ice.c:2131:2: error: implicit declaration of function ‘nice_address_ip_version’ [-Werror=implicit-function-declaration

### ISSUE THREAD

**Issue by chris-shenzhen-china** [meetecho/janus-gateway#2643]
compile error info: 

ice.c: In function ‘janus_ice_cb_new_local_candidate’:
ice.c:2131:2: error: implicit declaration of function ‘nice_address_ip_version’ [-Werror=implicit-function-declaration]
  gboolean ipv6 = (nice_address_ip_version(&candidate->addr) == 6);

---pls help, how can i fix it?

**Comment by lminiero** [comment]
You need to update libnice.

**Comment by chris-shenzhen-china** [comment]
updated libnice, done, thanks anyway.
