### ISSUE TITLE
multistream/videoroom: data_mindex not set to the correct value

### ISSUE THREAD

**Issue by mgarabedian** [meetecho/janus-gateway#2647]
While attempting a videoroom recording ( multistream branch ), I came across a bug on the data mjr recording.  Data was being saved in the audio mjr file, instead of the data mjr file (which was blank).

Digging in further, it appears participant->data_mindex is never updated in the plugin. I was able to solve this issue with the following code:

in janus_videroom.c

```
/* Add the stream to the list, if it's new */
if(new_ps) {
  participant->streams = g_list_append(participant->streams, ps);
  //FIX
  if(ps->type == JANUS_VIDEOROOM_MEDIA_DATA){
	  participant->data_mindex = ps->mindex;
  }
  //END FIX
  g_hash_table_insert(participant->streams_byid, GINT_TO_POINTER(ps->mindex), ps);
  g_hash_table_insert(participant->streams_bymid, g_strdup(ps->mid), ps);
}
```

**Comment by lminiero** [comment]
Good catch! Looking at the code, I suspect this wasn't just preventing data recording, but data channel braodcasting to other subscribers as well, especially in cases where data subscribers and audio subscribers didn't match. I'll fix this as suggested :+1:

**Comment by mgarabedian** [comment]
Great, thanks. It looks like the code should also be added to janus_videoroom_multistream.c

**Comment by lminiero** [comment]
There's no such thing: there's just a single VideoRoom plugin.

**Comment by mgarabedian** [comment]
Apologies. That was something I was trying on my end. Thanks.
