### ISSUE TITLE
Simulcast only response to High and Low Profile (Chrome)

### ISSUE THREAD

**Issue by itamayo** [meetecho/janus-gateway#2650]
Hi there !

I have been doing simulcast tests with a 640x480 camera. And well in the echoTest test of your page as in local, it only lets me change the substream H and L. I wonder if it is some bug, or has its logic. I am using chrome v89 (GNU / Linux). As far I understand it should be using M substream for 320x240 (downScale:2). Close the issue if it isn't relevant, thanks !

**Comment by lminiero** [comment]
Questions belong to the group, closing.
