### ISSUE TITLE
executing make issue

### ISSUE THREAD

**Issue by SkazochnikZlodey** [meetecho/janus-gateway#2654]
$sh autogen.sh
$./configure --prefix=/opt/janus
$ make
`which git` rev-parse HEAD | awk 'BEGIN {print "#include \"version.h\""} {print "const char *janus_build_git_sha = \"" $0"\";"} END {}' > version.c
echo "Tue May  4 09:13:03 UTC 2021" | awk 'BEGIN {} {print "const char *janus_build_git_time = \""$0"\";"} END {} ' >> version.c
echo "113" | awk 'BEGIN {} {print "int janus_version = "$0";"} END {} ' >> version.c
echo "0.11.3" | awk 'BEGIN {} {print "const char *janus_version_string = \""$0"\";"} END {} ' >> version.c
PKG_CONFIG_PATH="" pkg-config --modversion nice | awk 'BEGIN {} {print "const char *libnice_version_string = \""$0"\";"} END {} ' >> version.c
make  all-recursive
make[1]: Entering directory '/home/testingvladimir_izmalkov/janus-install/janus-gateway'
Making all in html
make[2]: Entering directory '/home/testingvladimir_izmalkov/janus-install/janus-gateway/html'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/testingvladimir_izmalkov/janus-install/janus-gateway/html'
make[2]: Entering directory '/home/testingvladimir_izmalkov/janus-install/janus-gateway'
  CC       transports/transports_libjanus_websockets_la-janus_websockets.lo
transports/janus_websockets.c: In function ‘janus_websockets_c$ommon_callback’:
transports/janus_websockets.c:1457:37: warning: variable ‘methods’ set but not used [-Wunused-but-set-variable]
     char origin[256], headers[256], methods[256];
                                     ^~~~~~~
transports/janus_websockets.c:1626:17: error: implicit declaration of function ‘lws_write_ws_flags’; did you mean ‘BN_with_flags’? [-Werror=implicit-function-declaration]
     int flags = lws_write_ws_flags(LWS_WRITE_TEXT, ws_client->bufoffset == LWS_PRE, ws_client->bufpending <= (size_t)amount);
                 ^~~~~~~~~~~~~~~~~~
                 BN_with_flags
transports/janus_websockets.c:1626:17: warning: nested extern declaration of ‘lws_write_ws_flags’ [-Wnested-externs]
cc1: some warnings being treated as errors
Makefile:2266: recipe for target 'transports/transports_libjanus_websockets_la-janus_websockets.lo' failed
make[2]: *** [transports/transports_libjanus_websockets_la-janus_websockets.lo] Error 1
make[2]: Leaving directory '/home/testingvladimir_izmalkov/janus-install/janus-gateway'
Makefile:3293: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/testingvladimir_izmalkov/janus-install/janus-gateway'
Makefile:1468: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lminiero** [comment]
Sounds like you need a more recent libwebsockets.

**Comment by SkazochnikZlodey** [comment]
with v4.2-stable
Updated 5 days ago by millikk
20
17
make is passed.
Thanks for help

**Comment by wann2** [comment]
with v4.2-stable
Updated 5 days ago by millikk
20
17
make is passed.

Is the upper the solution?
Could you please explain in detail to understand?
