### ISSUE TITLE
Multistream: Unable to enable more than 4 video codecs in a room

### ISSUE THREAD

**Issue by isnumanagic** [meetecho/janus-gateway#2657]
Trying to enable support for all 5 codecs (i.e. `videocodec = vp8,vp9,h264,h265,av1`) throws error `Unsupported video codec 'h265,av1'`. This is because string split has max tokens set to 4 (not 6):
https://github.com/meetecho/janus-gateway/blob/b9d01265cc726ec298b3513d3dca01283d98421f/plugins/janus_videoroom.c#L3161

**Comment by lminiero** [comment]
That's not specific to multistream: the same is in master as well, and probably for audio codecs too rather than video only, in both cases a leftover from when I extended the support. I'm not at the office today, I'll address this tomorrow.
