### ISSUE TITLE
Output opus (optionally) in mka

### ISSUE THREAD

**Issue by lu-zero** [meetecho/janus-gateway#2658]
Since the preprocessor is already muxing to webm would be fairly simple to support this format as well.

If you are ok with adding this feature, I can send a patch myself to implement it.

**Comment by lminiero** [comment]
Do you mean the postprocessor? Sure, please submit the patch as a pull request and we'll have a look, thanks!

**Comment by lminiero** [comment]
As a side note, the Opus output currently uses libogg directly, and not ffmpeg, so the changes may not be trivial; the webm output is only there for VP8 and VP9.
