### ISSUE TITLE
failed to build v0.11.2 with mqtt

### ISSUE THREAD

**Issue by sassyn** [meetecho/janus-gateway#2666]
Hi,

I'm using Ubuntu 20.04. 
I have build paho.mqtt.c tag version v1.3.2, version v1.3.6 and also the latest, but when building janus I'm getting the error:

transports/janus_mqtt.c: In function ‘janus_mqtt_client_disconnect’:
transports/janus_mqtt.c:1335:3: error: implicit declaration of function ‘janus_condition_wait_until’; did you mean ‘janus_condition_wait’? [-Werror=implicit-function-declaration]
 1335 |   janus_condition_wait_until(&ctx->disconnect.cond, &ctx->disconnect.mutex, deadline);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |   janus_condition_wait

Janus version is v0.11.2.

Any Idea?

Thanks

**Comment by lminiero** [comment]
Looks like we have different definitions for that macro when we use Glib mutexes (default) and when we use pthread (what you're doing apparently). In the latter the macro is indeed incorrectly defined as ` janus_condition_wait`, I'll fix this.

**Comment by lminiero** [comment]
Edit: to be more precise, `janus_condition_wait` is actually fine, as it's there in both cases: it's `janus_condition_wait_until` that's missing in the pthread case. I'll have to check if it's because it's missing entirely in the pthread API, which would be an issue.

**Comment by lminiero** [comment]
Should be fixed now, even though I haven't tested (I always use Glib implementation in my testbed).

**Comment by sassyn** [comment]
seems to be working!

Thank you
