### ISSUE TITLE
Janus do not respects SDP m=video line priority

### ISSUE THREAD

**Issue by B-R-Bender** [meetecho/janus-gateway#2669]
Hello!
I'm encountered an issue with m=video line processing on the server side.

I'm mangling local SDP to change video codec priority with respect to user preferences.
To do so I'm reordering media tokens in m=video line so preferred codec will appear at the start.

For instance:
before mangling
`m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123`
after
`m=video 9 UDP/TLS/RTP/SAVPF 108 109 125 107 96 97 98 99 100 101 102 121 127 120 35 36 124 119 123`

This way I'm expecting janus to create answer with 
`m=video 9 UDP/TLS/RTP/SAVPF 108 109`
but instead I see this was negotiated
`m=video 9 UDP/TLS/RTP/SAVPF 102 121`

I suppose it worth to mention that I'm trying to prioritize not the codec itself but the specific `profile-level-id`
for the `h264` to be used for the negotiation.
Also I know there is a corresponding option in `janus.plugin.videoroom.jcfg` but it's not allows me to prioritize those levels dynamically and it has an issue also - if SDP mangling is done on the client side (for the bitrate controls as an example) janus wipes it while creating an answer.

Could you, guys, have a look please.
Thank you in advance.

**Comment by lminiero** [comment]
We don't have great support for profiles in VideoRoom. I don't remember what the core SDP utils do when you don't specify a profile in the room, but when we do it must be an exact match: we don't have priorities for profiles.

**Comment by lminiero** [comment]
Pretty sure that for profiles (fmtp) we're reading the order of the fmtp lines, _NOT_ the order of payload types in the m-line itself. This means that you need to munge those too, not just the m=video line.

**Comment by lminiero** [comment]
@B-R-Bender have you tried what I wrote above?

**Comment by lminiero** [comment]
Closing.

**Comment by B-R-Bender** [comment]
Thank you Lorenzo.
I'm sorry for a late response, I'll give it a try and will share my findings.

**Comment by B-R-Bender** [comment]
Yes, It worked for me.
I've reordered fmtp lines and it works, thank you!
