### ISSUE TITLE
Maybe this statement is redudant

### ISSUE THREAD

**Issue by lhphong09t2** [meetecho/janus-gateway#2670]
In audiobridge example javascript file - janus-gateway/html/audiobridgetest.js
Line 144
if(!webrtcUp) {													
   webrtcUp = true;

I am confused that whether this statement redudant or not? because you didn't to videoroom example
If this isn't an issue, just skip it. Thanks

**Comment by lminiero** [comment]
It's not redundant. It's to ensure we only do that once, since it defaults to `false`, and is set to `false` when we hangup too. Closing.
