### ISSUE TITLE
postprocessing

### ISSUE THREAD

**Issue by homevk15** [meetecho/janus-gateway#2678]
Error occured during installation in Ubuntu 16 xenial
postprocessing/pp-g722.c:213:3: error: implicit declaration of function ‘av_packet_free’ [-Werror=implicit-function-declaration]
   av_packet_free(&avpacket);

**Comment by lminiero** [comment]
Is this the only warning you see? `av_packet_free` is used in other processors as well, not just G722. Is it just the "implicit declaration" warning, or is there some error after that?

**Comment by homevk15** [comment]
It's an error after a compilation using 'make'.
I chose your older version v0.11.1 (April 6,2021) and it was compiled and it works OK

**Comment by homevk15** [comment]
sorry Lorenzo, I lost terminal where I couldn't compile 'Janus'. There were many warnings about packets needed for postprocessing.

**Comment by lminiero** [comment]
Then please try again and share the whole output in a pastebin or gist link. It compiles just fine here.

**Comment by atoppi** [comment]
@homevk15 are you issuing `make clean` before trying to compile? The recent merging of #2665 has changed the way pp-rec imports libav dependencies.

**Comment by lminiero** [comment]
Any update? Otherwise I'll just close, since it works fine here.
