### ISSUE TITLE
[sip] Response code when declining a call

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#268]
(I thought I'd open an issue before making a patch this time around)

Currently, when declining a call, the response code used is 603, which is unfortunate, because all other devices configured with the same account will stop ringing.

@lminiero how about getting an extra parameter with the decline command specifying the code? In its absence 486 would be used, since it better communicates the reason for declining the call.

**Comment by saghul** [comment]
(Once agreed I volunteer to write the patch)

**Comment by lminiero** [comment]
I agree that a parameter for explicitly requiring a 603 is better, since in general we have to assume that the SIP client is unaware of other devices configured for the same account and should behave accordingly.

**Comment by saghul** [comment]
Fixed in #270
