### ISSUE TITLE
Unable to launch Janus URLs in browser after deployment

### ISSUE THREAD

**Issue by subashsds** [meetecho/janus-gateway#2681]
Dear Team,

We are setting up Janus in our Ubuntu server. We have followed the steps given in the following URL: (https://janus.conf.meetecho.com/docs/README.html).
All the dependencies/plugins has been installed without any error and we have started the janus servises successfully. PFB the status of the janus service.

root@*****:/home/ubuntu# ps -ef | grep janus
root      136749       1  0 May31 ?        00:11:52 /opt/janus/bin/janus -d 5 -6
root      146578  146570  0 12:20 pts/0    00:00:00 grep --color=auto janus

We are able to access the URL (http:/localhost:8088/janus/info) in Ubuntu server using curl command. The same URL is accessible in browser as well (http://<<ubuntu server IP>>:8088/janus/info)

But other URLs (mentioned below) are nate accessible either using curl command in server or browser.
http:/localhost:8088/janus/index.html
http:/localhost:8088/janus/videocalltest.html

Can you advice if we are missing any steps or any additional configuration should be done to enable it.

**Comment by lminiero** [comment]
Explained in the docs: https://janus-legacy.conf.meetecho.com/docs/deploy
