### ISSUE TITLE
sip demo error

### ISSUE THREAD

**Issue by Zzij** [meetecho/janus-gateway#2683]
hi
  i installed janus following README.md. when i used sip-test demo, something wrong with me. i searched anywhere, but i could not solve the problem.
which sofia-sip version should i choose？
any advice could you give?
hope for your reply.

janus： latest master code
linux：centos 7.5
sofia-sip：1.13.3
browser：Chrome Version 89.0.4389.82

![image](https://user-images.githubusercontent.com/35696626/120762456-db26c380-c548-11eb-8f3d-b385312d6809.png)
![image](https://user-images.githubusercontent.com/35696626/120762546-f2fe4780-c548-11eb-98f8-3d434985e953.png)

error log

Registering as a guest
Guest will have username 1001
Joining sofia loop thread (1001)...
Setting up sofia stack (sip:1001@192.168.137.128)
[ERR] [plugins/janus_sip.c:janus_sip_handler:3035] Two seconds passed and still no NUA, problems with the thread?

**Comment by lminiero** [comment]
Sounds like issues installing Sofia SIP on CentOS properly, which has been discussed several times in the past already. Please search on old issues or old threads on the forum for details. Not a Janus issue anyway.

**Comment by mayfender** [comment]
I found this problem can you tell me how to solved it.

**Comment by Zzij** [comment]
use version 1.12.11

**Comment by lminiero** [comment]
FYI, I think I found the main cause of this issue with versions of Sofia SIP higher than 1.12. It looks like the NUA creation would fail when both SIP and SIPS were bound to: considering we bound to SIPS as well by default, this caused the failure, so the commit above disables that, and only enables it when asked for via API. This will very likely cause issues with SIPS when Sofia >= 1.13, for those that need SIPS, but we can look into that at a later stage.
