### ISSUE TITLE
Remote Video not loading/Streaming

### ISSUE THREAD

**Issue by subashsds** [meetecho/janus-gateway#2686]
Dear Team,

We have installed Janus and webserver. We are able to access the page successfully from browser. But we are facing issue in testing the demo video call.

When i access the URL "https://<<myserver>>:8443/janusUi/html/videocalltest.html"

The attached page loads and I can see my video publishing. But remote vide is not streaming/loading. PFA the screenshot
 
Kindly help to resolve this issue

Thanks
Subash
![videoerror](https://user-images.githubusercontent.com/26743470/120858266-2d470380-c5a0-11eb-9bd7-bf815e1a9842.png)

**Comment by vvviphosl** [comment]
"https://<>:8443/janusUi/html/videocalltest.html"

**Comment by subashsds** [comment]
Hi Team, the above update doesn’t give any resolution. Can you suggest what action should be taken or if anything is missing from our end? Request you to please send some proper reference which we can refer to resolve this

**Comment by lminiero** [comment]
As per the guidelines, question belongs to the group, not here.
