### ISSUE TITLE
Toggle webcam in videoroom plugin

### ISSUE THREAD

**Issue by vovaminof** [meetecho/janus-gateway#269]
Hello, I have a question, I am using videoroom plugin to create virtual room for video conference. I want to have an ability to turn on/off webcam stream, is it possible? What kind of request should I send to accomplish it?

Thanks in advance!

**Comment by saghul** [comment]
You are probably better off using the mailing list: https://groups.google.com/forum/#!forum/meetecho-janus for questions.

**Comment by vovaminof** [comment]
Thanks
