### ISSUE TITLE
Videoroom event : Error 429

### ISSUE THREAD

**Issue by narayanan-ka** [meetecho/janus-gateway#2710]
Hello 

Im testing the videoroom multistream but getting the following error message in the console 

Error code: 429,
Error: Missing mandatory element (secret)

What do I need to add/modify and where ?

**Comment by lminiero** [comment]
Don't use our demo server, install your own.

**Comment by narayanan-ka** [comment]
Hello. We have installed janus on our server already.

**Comment by lminiero** [comment]
Then as explained in the guidelines, please ask questions on the [group](https://groups.google.com/g/meetecho-janus), not here.

**Comment by narayanan-ka** [comment]
I have already.

https://groups.google.com/g/meetecho-janus/c/Zk2xYtDjSRk/m/JRbRdOcUAAAJ


Kindly assist us.
