### ISSUE TITLE
transports/janus_websockets.c:1626:17: error: implicit declaration of function ‘lws_write_ws_flags’

### ISSUE THREAD

**Issue by wann2** [meetecho/janus-gateway#2711]
![image](https://user-images.githubusercontent.com/8732515/123236807-1436d000-d518-11eb-932c-3d63a56f2760.png)

When I execute "make", the below error always happens.

<img width="1202" alt="스크린샷 2021-06-24 오후 6 13 39" src="https://user-images.githubusercontent.com/8732515/123237034-45af9b80-d518-11eb-8fb8-ec39084a41c4.png">

**Comment by lminiero** [comment]
See #2654.

**Comment by wann2** [comment]
I read #2654, but I do not understand how he could resolve it.
Hard to understand.

The below is that I installed libwebsockets.

![image](https://user-images.githubusercontent.com/8732515/123243050-9bd30d80-d51d-11eb-90ce-e3633c4374cf.png)
