### ISSUE TITLE
transports/janus_websockets.c:1626:17: error: implicit declaration of function ‘lws_write_ws_flags’

### ISSUE THREAD

**Issue by wann2** [meetecho/janus-gateway#2712]
![image](https://user-images.githubusercontent.com/8732515/123236807-1436d000-d518-11eb-932c-3d63a56f2760.png)

When I execute "make", the below error always happens.

<img width="1202" alt="스크린샷 2021-06-24 오후 6 13 39" src="https://user-images.githubusercontent.com/8732515/123237034-45af9b80-d518-11eb-8fb8-ec39084a41c4.png">

I read #2654 that lminiero  commented, but I do not understand how he could resolve it.
Hard to understand. Could you explain in details to understand and solve it?

The below is that I installed libwebsockets.

![image](https://user-images.githubusercontent.com/8732515/123244269-b5c12000-d51e-11eb-9ade-757cf25c33c9.png)

**Comment by lminiero** [comment]
Please **STOP** opening issues for the same thing over and over! I already pointed you to the solution. If you open another issue I'll have to ban you from the repo.

**Comment by wann2** [comment]
Sorry, but I do not understand what you pointed the solution and the issued I did marked "closed", I would appreciate if you could explain to me what is wrong.

**Comment by lminiero** [comment]
You're using an old release of lws, and you need a recent one.

**Comment by wann2** [comment]
Now I can see what is the problem. Thanks a lot and sorry for the issue i wrote. I met Janus today for the first time. I has been trying to implement it for my company.
Thanks lminiero

**Comment by jabesq** [comment]
@wann2 How did you fix your issue because i'm facing the same with janus 0.11.3 and libwebsocket (branch master)

**Comment by jainishslk** [comment]
@wann2 I also facing the same problem. how did you fix issue?
