### ISSUE TITLE
Cross-compilation fails on Debian because `pkg-build` is used directly to to create `libnice_version_string`

### ISSUE THREAD

**Issue by igo95862** [meetecho/janus-gateway#2713]
This is the line in `Makefile.am`:

https://github.com/meetecho/janus-gateway/blob/23535f02ac15d8b5bf6b4a7dfb51c7cadc4bad07/Makefile.am#L211

Not sure why but at least on Debian the `PKG_CONFIG_PATH` is not set however it provides wrappers like `aarch64-linux-gnu-pkg-config` setup which are set by `PKG_CONFIG` variable.

I think changing that line to use `"$(PKG_CONFIG)"` fixes the issue. I tested ARM64 cross-compile on Debian and AMD64 on Arch Linux and it seems to work.

**Comment by lminiero** [comment]
PKG_CONFIG doesn't seem to be defined anywhere on my Fedora, so I'm not sure the fix would work.

**Comment by lminiero** [comment]
Scratch that, I wasn't considering these env variables may only make sense within the context of configure/make. Just tried putting what you suggested and it seems to do the trick.

**Comment by igo95862** [comment]
> Scratch that, I wasn't considering these env variables may only make sense within the context of configure/make. Just tried putting what you suggested and it seems to do the trick.

Good to hear. I was just about to pull Fedora docker image to test.
