### ISSUE TITLE
maybe replace libwebsocket with wslay

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#2716]
I've noticed [some](https://www.eclipse.org/lists/mosquitto-dev/msg02468.html) [projects](https://godotengine.org/article/websocket-updates-udp-multicast) switching from libwebsocket to Wslay - mentioning here in case that might be relevant here as well.

**Comment by lminiero** [comment]
Thanks for the heads-up, but I don't see any reason why we should switch ourselves, considering the WS transport works as expected, and it would take a lot of time to look into these alternatives and refactor the existing code.
