### ISSUE TITLE
Videoroom :Black remote video display when i stream mp4 or any video file

### ISSUE THREAD

**Issue by thecodewarlock19** [meetecho/janus-gateway#2717]
I get a black remote video display when i stream mp4 or any video file the following is my code.
   But this same code works (remote video works) when i stream live from device camera. thanks in advance

`Janus.debug("Created remote video stream:", stream);` =>
 Created remote video stream: MediaStream {id: "5a3d8f2d-4ca3-4deb-85a3-ee3fb0a4c7df", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}

`  self.publishOwnFeed=function(useAudio=true) {
	   
	  // var myVideo = document.getElementById('myVideo');
	   var playbackElement = document.getElementById("myVideo");
	   
		playbackElement.onplay = function() {
			
		var myvideo = $('#myVideo').get(0);
		  // Set the source of one <video> element to be a stream from another.
		  var stream = myvideo.captureStream();
		  
		  //rightVideo.srcObject = stream;
		  
		// Publish our stream
		self.sfutest.createOffer(
			{
				// Add data:true here if you want to publish datachannels as well
				media: {
					replaceVideo: true,
					replaceAudio: true
				},
				stream: stream,
				// Publishers are sendonly
				// If you want to test simulcasting (Chrome and Firefox only), then
				// pass a ?simulcast=true when opening this demo page: it will turn
				// the following 'simulcast' property to pass to janus.js to true
				simulcast: self.doSimulcast,
				simulcast2: self.doSimulcast2,
				success: function(jsep) {
					Janus.debug("Got publisher SDP!", jsep);
					var publish = { request: "configure", audio: useAudio, video: true };
					// You can force a specific codec to use when publishing by using the
					// audiocodec and videocodec properties, for instance:
					// 		publish["audiocodec"] = "opus"
					// to force Opus as the audio codec to use, or:
					// 		publish["videocodec"] = "vp9"
					// to force VP9 as the videocodec to use. In both case, though, forcing
					// a codec will only work if: (1) the codec is actually in the SDP (and
					// so the browser supports it), and (2) the codec is in the list of
					// allowed codecs in a room. With respect to the point (2) above,
					// refer to the text in janus.plugin.videoroom.jcfg for more details.
					// We allow people to specify a codec via query string, for demo purposes
					if(self.acodec)
						publish["audiocodec"] = self.acodec;
					if(self.vcodec)
						publish["videocodec"] = self.vcodec;
					self.sfutest.send({ message: publish, jsep: jsep });
				},
				error: function(error) {
					Janus.error("WebRTC error:", error);
					if(useAudio) {
						 self.publishOwnFeed(false);
					} else {
						 self.publishOwnFeed(true);
					}
				}
			});
		};
	  
	}`

    `onremotetrack: function(track, mid, on) {
    Janus.debug("Remote track (mid=" + mid + ") " + (on ? "added" : "removed") + ":", track);
    if(!on) {
	    // Track removed, get rid of the stream and the rendering
	    var stream = self.remoteTracks[mid];
	    if(stream) {
		    try {
			    var tracks = stream.getTracks();
			    for(var i in tracks) {
				    var mst = tracks[i];
				    if(mst){
					    mst.stop();
				    }
			    }
		    } catch(e) {}
	    }
	    if(track.kind === "video") {
		    self.remoteVideos--;
	    }
	    delete self.remoteTracks[mid];
	    return;
    }
    // If we're here, a new track was added
    if(track.kind === "audio") {
	    
	    // New audio track: create a stream out of it, and use a hidden <audio> element
	    stream = new MediaStream();
	    stream.addTrack(track.clone());
	    self.remoteTracks[mid] = stream;
	    Janus.log("Created remote audio stream:", stream);
	    
	    $('#remote_video_').append('<audio class="hidden" id="peervideo' + mid + '" autoplay playsinline/>');
	    Janus.attachMediaStream($('#peervideo' + mid).get(0), stream);		
	    Janus.attachMediaStream($('#remote_video' ).get(0), stream);							
	    $('#peervideo' + mid).get(0).volume = 1;
    
	    
    } else {
	    
	    // New video track: create a stream out of it
	    self.remoteVideos++;
	    stream = new MediaStream();
	    stream.addTrack(track.clone());
	    self.remoteTracks[mid] = stream;
	    Janus.debug("Created remote video stream:", stream);
	    Janus.attachMediaStream($('#remote_video' ).get(0), stream);
	    //document.querySelector("#remote_video").srcObject =stream;						
    }
    },`

**Comment by thecodewarlock19** [comment]
But this same code works (remote video works) when i stream live from from device camera

**Comment by akilude** [comment]
Hi,

Best place to ask questions is the [group](https://groups.google.com/g/meetecho-janus/)

**Comment by lminiero** [comment]
Yes, belongs to the group.
