### ISSUE TITLE
On Safari use multistream mode, the player not working after other user re-enter room

### ISSUE THREAD

**Issue by yutin1987** [meetecho/janus-gateway#2718]
Will use same MediaStreamTrack (same mind) when it has new track of user, after old user leaving / unsubscribe, but that track has been "ended".

On Chrome and Firefox is working, so this issue only on Safari.

How to get status?
```
janus.attach({
  onremotetrack(track, mid, on) {
    console.log(track.readyState);  // "live" or "ended"
  },
});
```
On audio player html tag (reassign new player):
```
  audioEl.current.addEventListener('playing', playingHandler); // if it is working will get this status
  audioEl.current.addEventListener('loadstart', loadstartHandler); // new user will keeping this status
 ```

**Comment by lminiero** [comment]
Please don't post screenshots, they're useless to identify issues. Make sure you test our default demo and provide info on that, as we don't debug third-party clients.

**Comment by yutin1987** [comment]
On this demo can repeated issues

https://janus.conf.meetecho.com/mvideoroomtest.html

On audio got `readyState=ended`, when other user rejoining
![截圖 2021-06-29 下午5 23 23](https://user-images.githubusercontent.com/2505934/123772843-c1399000-d8fe-11eb-8270-5808d502584a.png)

On video always `readyState=live`, when other user rejoining
![截圖 2021-06-29 下午5 12 53](https://user-images.githubusercontent.com/2505934/123771007-4c198b00-d8fd-11eb-84d9-8f3627da943c.png)

On chrome is working.
![截圖 2021-06-29 下午5 21 02](https://user-images.githubusercontent.com/2505934/123772973-dc0c0480-d8fe-11eb-992b-c94af99842b5.png)

**Comment by fippo** [comment]
sounds like https://bugs.chromium.org/p/chromium/issues/detail?id=1187576 which was fixed in Chrome but might not yet be in Safari.

**Comment by lminiero** [comment]
I guess this is not a Janus issue, then. Closing.
