### ISSUE TITLE
Multistream results in a blank screen

### ISSUE THREAD

**Issue by narayanan-ka** [meetecho/janus-gateway#2720]
My friend and myself are working on a streaming app. He posted on the groups. Got no response yet. Any help will be appreciated. 

"I am using flutter and flutter-janus-client to create a multistreaming service, or so I think.

What I want to do is broadcast the contents of a video room with, say 2 publishers, to others. For this I am first creating a videoroom, then create an rtp-forward, finally create a streaming mountpoint. Here is the code for rtp-forwarding and multi streaming mountpoint:

RTP-Forward:

var rtp = {
   "request": "rtp_forward",
   "room": 5555, //room_id,
   "publisher_id": publisherId,
   "host": "127.0.0.1",
   "host_family": "ipv4",
   "streams": [
      {
         "port": vp,
         "pt": 100,
       },
       {
         "port": ap,
         "pt": 111,
       }
   ],
};

Multistreaming:

var mountpoint = {
   "request" : "create",
    "type" : "rtp",
   "id" : 10,
   "name" : "my multistream",
   "description" : "test multistream",
   "is_private" : false,
   "audio" : true,
   "video" : true,
   "permanent" : false,
   "videoport": vp,
   "audioport": ap,
   "videopt": 100,
   "audiopt": 111,
   "videortpmap": "VP8/90000",
   "audiortpmap": "opus/48000/2",
   "media": [
      {
         "type" : "audio",
         "mid" : "a",
         "label" : "Audio stream",
         "port" : 5106,
         "pt" : 111,
         "rtpmap" : "opus/48000/2",
      },
       {
         "type" : "video",
         "mid" : "v1",
         "label" : "Video stream #1 a",
         "port" : 1106,
         "pt" : 100,
         "rtpmap" : "VP8/90000",
       },
       {
         "type" : "video",
         "mid" : "v2",
         "label" : "Video stream #2 b",
         "port" : 1108,
         "pt" : 100,
         "rtpmap" : "VP8/90000",
       },
   ],
};

I know I am doing something wrong  here due to my poor understanding of janus and webrtc, probably the ports are wrong as well. Can someone please help me with this ? Thanks in advance"

**Comment by lminiero** [comment]
Not receiving answers on the group doesn't entitle you to just open issues here. Someone will answer when there will be time to give an answer. Closing.
