### ISSUE TITLE
Janus ICE handle possible leak

### ISSUE THREAD

**Issue by groupboard** [meetecho/janus-gateway#2731]
To recreate:

- start janus with -d 7
- add -dREFCOUNT_DEBUG=1 to CFLAGS
- open videoroom test page with a few users
- reload web page a few times for each user
- press ctrl+c

You'll see a message saying a number of reference counters are still allocated. The more you reload the page for the users, the more refs are active at the end. They seem to be allocated from janus_ice_handle_attach_plugin at this line:

`janus_plugin_session *session_handle = g_malloc(sizeof(janus_plugin_session));
`

but are not deallocated anywhere (I think they should be deallocated in janus_ice_plugin_session_free, but not sure).

**Comment by groupboard** [comment]
[janus_debug.txt](https://github.com/meetecho/janus-gateway/files/6795761/janus_debug.txt)

Here is an example debug log. I've just removed ip addresses, and added a little bit more debug info to print the handle refs to make it easier to track them.

**Comment by groupboard** [comment]
Oh, and I should add that I tested with libasan and nothing was mentioned regarding leaks. I think it's not technically a leak (in terms of how libasan defines a leak) because the memory is still referenced from somewhere in janus even though the refcount is 0.

**Comment by lminiero** [comment]
IMO that's normal, and there's no leak to worry about. Refreshing a page means a session needs to timeout before it's cleaned: you're probably issuing the CTRL+C before that, and so the still-to-timeout-sessions are leaked. You can see an explaination of why and why it's nor an issue [here](https://github.com/meetecho/janus-gateway/issues/2624#issuecomment-819522489).

**Comment by groupboard** [comment]
Yes, you're right. During earlier testing I did notice a 5 second delay between closing the browser and seeing the debug message saying the resources were freed. But I think I forgot to wait during this particular test. I tried it again now and there are no resources still allocated when I wait 10 seconds before pressing ctrl+c. Closing.
