### ISSUE TITLE
error: implicit declaration of function lws_write_ws_flags

### ISSUE THREAD

**Issue by tranngocphat0901** [meetecho/janus-gateway#2739]
Hi guys,

I have install janus server on Ubuntu 18.04 but I have a problem. Please help me fix it.

/some text ommit/
make  all-recursive
make[1]: Entering directory '/root/janus-gateway'
Making all in html
make[2]: Entering directory '/root/janus-gateway/html'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/janus-gateway/html'
make[2]: Entering directory '/root/janus-gateway'
  CC       transports/transports_libjanus_websockets_la-janus_websockets.lo
transports/janus_websockets.c: In function ‘janus_websockets_common_callback’:
transports/janus_websockets.c:1460:37: warning: variable ‘methods’ set but not used [-Wunused-but-set-variable]
     char origin[256], headers[256], methods[256];
                                     ^~~~~~~
transports/janus_websockets.c:1629:17: error: implicit declaration of function ‘lws_write_ws_flags’; did you mean ‘BN_with_flags’? [-Werror=implicit-function-declaration]
     int flags = lws_write_ws_flags(LWS_WRITE_TEXT, ws_client->bufoffset == LWS_PRE, ws_client->bufpending <= (size_t)amount);
                 ^~~~~~~~~~~~~~~~~~
                 BN_with_flags
transports/janus_websockets.c:1629:17: warning: nested extern declaration of ‘lws_write_ws_flags’ [-Wnested-externs]
cc1: some warnings being treated as errors
Makefile:2274: recipe for target 'transports/transports_libjanus_websockets_la-janus_websockets.lo' failed
make[2]: *** [transports/transports_libjanus_websockets_la-janus_websockets.lo] Error 1
make[2]: Leaving directory '/root/janus-gateway'
Makefile:3315: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/janus-gateway'
Makefile:1472: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lminiero** [comment]
Update libwebsockets.

**Comment by tranngocphat0901** [comment]
> Update libwebsockets.

Hi @lminiero, Let me try.

**Comment by tmatth** [comment]
Note that Janus' CI is using v4.1-stable, so if in doubt you can be sure that that version works:
https://github.com/meetecho/janus-gateway/blob/9a76ed29aebe5da21b8ffdeb4b1b2d442c2f232b/.github/workflows/janus-ci.yml#L123
