### ISSUE TITLE
videoroom plugin playing remote stream on windows not work

### ISSUE THREAD

**Issue by dewebdes** [meetecho/janus-gateway#2748]
hi meetecho
before anything, tanx for ur perfect solution, its grate :)
videoroom plugin work fine in all mobile browsers
but the issue is for all windows browsers
in windows, localstream is fine and it send the stream perfectly and mobile clients get the remotestream perfect
and it get the  others remote streams with ok peer connection
**BUT Can Not Display Them**
_remotevideo.srcObject.getTracks()[0/1].muted==true_
just dark blank screen was seen...

I got ur **last git** today and build,make,install it again, and remove old opt and demo files and replace them by new ones...
but the **issue not fixed**

Also, screensharingtest have same issue:
the stream from windows play fine in mobile but not playing in another system windows. just dark blank screen was seen.

I was tested these with different ISP s from multi countries with different windows and mobile versions, and it can not be the NAT or ISP bug or related to Android/ISO/Windows/Browser versions.

I will be glad if you can fix this in your videoroom plugin and update videoroomtest and screensharingtest samples and I will pause my start-up until hear something from you.

Be Successful, I am prodding to your team 👍

**Comment by lminiero** [comment]
Questions and usage problems belong to the [group](https://groups.google.com/g/meetecho-janus), not here.

**Comment by dewebdes** [comment]
By the way
I write this bug on google group:
https://groups.google.com/g/meetecho-janus/c/LsZExza20Uc

you answered questions that writes after this conversation, BUT not answered to this yet on google...
and my issue on github not a question about usage, this is a bug report.
I am thinking that ur manner is political and i understand it.

**Comment by lminiero** [comment]
I do not answer ALL questions on the group. It's a community, so a place where all users are supposed to help each other, not the "Lorenzo fixes everything" group. I answer what I want, as a best effort, and in my spare time. No idea what you mean by "political", but if it's meant as an insult, you're definitely not increasing the chances I'll ever answer that post you opened.

**Comment by dewebdes** [comment]
But all question about blank screen have no answer
u just answer fast to very simple questions like "https not set" or ...
the main question is multiteam for windows
and i think u have the solution
but keep it for ur customers and who contact u for order a webrtc applications
and i understand this
but u understand that people like me take a lot of time to work on ur engine and advertise for it
and this is not fair at final

**Comment by lminiero** [comment]
I'm not staying here to be insulted: I've devoted my professional like to open source. If I wanted to make easy money, I'd turn Janus into a proprietary tool that ungrateful freeloaders like you can't use anymore. Now get lost: I'm officially on vacation, so get back in a month or ask somebody else for help.

**Comment by alexamirante** [comment]
I shut down this thread as I don't like the attitude and where it's going. Hope this behavior is not seen as "too political"...
