### ISSUE TITLE
Getting error: Missing mandatory element (feed)

### ISSUE THREAD

**Issue by kumail-raza** [meetecho/janus-gateway#2750]
https://janus.conf.meetecho.com/mvideoroomtest.js:662
```
 // We wait for the plugin to send us an offer
var subscribe = {
	request: "join",
	room: myroom,
	ptype: "subscriber",
	streams: subscription,
	private_id: mypvtid
};
remoteFeed.send({ message: subscribe });
```

Receiving error onmessage (callback) line #685;

**Missing mandatory element (feed)**

Any clue why I am getting this error when I am testing the same JS file with our janus server? Is there any configuration that need to be made on server side?

Further I am not getting **streams** on joining or any user subscribe. Message get received but in response object streams are not available.

**Comment by groupboard** [comment]
Are you using the multistream branch on your server?

**Comment by atoppi** [comment]
Clearly a client/server mismatch.
You are using the `multistream` client and the `master` server and that is not supported since the client is referring to an API not present in the `master` version.
