### ISSUE TITLE
Feature request: ring tone

### ISSUE THREAD

**Issue by fabioganga** [meetecho/janus-gateway#2752]
Hi,
Thanks for such a great tool!
Please, can you add a ring tone in future releases?
If I am registered and waiting for a call but on another browser tab I don't realise when someone is calling me.
Thanks, and keep up the great job!

**Comment by lminiero** [comment]
We're not planning to add it to the demos, but this is something you can actually implement yourself quite trivially, using the events the plugin already sends you: makes for a good homework for sure :slightly_smiling_face:
