### ISSUE TITLE
Unsubscribe from publisher's datachannel disables all subscribed data channels, can't resubscribe

### ISSUE THREAD

**Issue by kaqq** [meetecho/janus-gateway#2755]
**Working scenario:**
1. Subscribe to a single publisher's video and data channels.
2. Unsubscribe from data channel by sending: 
` "body": {
    "streams": [
      {
        "feed": 8532500667596649,
        "mid": "1"
      }
    ],
    "request": "unsubscribe"`
  3. we are not receiving data channel messages
  4. subscribe to data channel again.
  5. data channel messages start flowing.
  
**Not working scenario:**
1.subscribe to many publisher's video and data channels.
2. Unsubscribe from one of subscribed publishers by sending: 
` "body": {
    "streams": [
      {
        "feed": 8532500667596649,
        "mid": "1"
      }
    ],
    "request": "unsubscribe"`
result:
  3. We are not receiving any data channel messages from any publisher. 
  4. subscribe to data channel again not working, messages are not flowing. 
 expected:
   3. We are not receiving data channel messages from this publisher, however, the rest of them are working
   4. subscribe to data channel again enables messages from this publisher. 
   
   tested on latest multistream: f9762155d09a82a484132a869828f087153f014f
   Worth mentioning that after triggering any SDP change for the subscriber (even unsubscribe from video) datachannel is fixed.

**Comment by atoppi** [comment]
I can reproduce the issue.
Janus log
```
[Wed Aug 25 12:35:32 2021] Removing subscriber streams
[Wed Aug 25 12:35:32 2021] No unsubscription done, skipping renegotiation
```
Then the subscriber can not receive any message from any publisher.

**Comment by atoppi** [comment]
@kaqq try commenting this line and building janus again
https://github.com/meetecho/janus-gateway/blob/0d0aacd6a57f3ce06384091561ba29bb507991b6/plugins/janus_videoroom.c#L2846

It seems to solve the issue for me.
Please also make sure that everything else works as expected.

**Comment by lminiero** [comment]
Yes, that line definitely needs to be removed: it's already in the code that handles the removal of the streams in the following lines, when a subscription becomes completely empty, which is the only place where it should be. In fact, `ready` is set back to `1` if subsequent renegotiations add media again.

I'll have to check if the `ready=1` thing is done when re-subscribing to datachannels as well, though, as IIRC it currently checks the media direction, which doesn't change for datachannels.
