### ISSUE TITLE
error on installation of janus-gateway [multistream] branch

### ISSUE THREAD

**Issue by kumail-raza** [meetecho/janus-gateway#2759]
On running the *make* command

![image](https://user-images.githubusercontent.com/2698458/130137409-3a52fcf9-0625-471d-ab01-1fdbba8763dc.png)

For installation step: 
I was referring to https://ourcodeworld.com/articles/read/1197/how-to-install-janus-gateway-in-ubuntu-server-18-04

OS: Ubuntu 18.04

**Comment by atoppi** [comment]
Why reading other guides when we have all the installation steps wonderfully detailed in the official README ?
Anyway, as already answered a ton of times, you need to update libwebsockets.

**Comment by kumail-raza** [comment]
there are multiple issues while using the steps in README. I must say you should guys provide a Dockerfile or official image.

**Comment by alexamirante** [comment]
If you think there are issues with the steps listed in the README, then fix them and submit a Pull Request. That's how OSS is supposed to work.
