### ISSUE TITLE
janus-pp-rec video conversion failed reason:  free(): invalid next size (fast)

### ISSUE THREAD

**Issue by harshald28** [meetecho/janus-gateway#2762]
In some .mjr  conversions we are getting "free(): invalid next size (fast)" issue. Due to policy, I can't share the actual .mjr file here but ideally, we found such types of mjr's getting created when the user is on the bad network and the size of recording is very small. 

[Full stack trace from AddressSanitizer](https://pastebin.com/LF1E2Sw6)

I have tried on 0.10.7 as well but found the same issue. Also, can this be handle with help of any additional parameters from janus-pp-rec while converting the file?

**Comment by atoppi** [comment]
we can't do much without a sample to reproduce the issue

**Comment by lminiero** [comment]
I suspect the recording contains something other than VP8, as this line is suspicious:

```
  -- 2x2 (fps [6390,31230] ~ 14)
```

A `2x2` resolution makes no sense. @harshald28 as Alessandro said there's nothing we can do without a file to replicate the issue.

**Comment by lminiero** [comment]
Closing for lack of feedback.
