### ISSUE TITLE
SIP Attended transfer is broken in v0.11.4

### ISSUE THREAD

**Issue by pawnnail** [meetecho/janus-gateway#2766]
It's an odd one, due to a pragma added after "if" statement at line 4159 in commit b826883, probably best to fix by moving the pragma to just above the if statement:
````
#pragma GCC diagnostic ignored "-Winline"
			if(refer_to == NULL)
				refer_to = sip_refer_to_format(session->stack->s_home, "<%s>", uri_text);
#pragma GCC diagnostic warning "-Winline"
````

**Comment by lminiero** [comment]
Thanks for spotting this! Even though I don't understand why it should fail: the precondition is not excluding code depending on some check, it's just programmatically disabling useless warnings when compiling. Have you verified that moving the pragma one line up it fixes transfers for you?

**Comment by lminiero** [comment]
Made the commit anyway since it was cleaner, so if that was the issue it should be fixed now :+1:

**Comment by pawnnail** [comment]
Have verified indeed. Moving pragma or adding curly braces block fixes the problem without doubt. Without the fix the refer-to header is missing part "?replaces=...".
