### ISSUE TITLE
Subscriber-side configure request for videoroom plugin

### ISSUE THREAD

**Issue by ancorgs** [meetecho/janus-gateway#277]
As discussed in [1], it would be useful to implement a request type that the subscribers can use to modify the audio/video/data flags (similar to the "configure" request that works for publishers). 

[1] https://groups.google.com/forum/#!topic/meetecho-janus/X252X996Pvw

**Comment by lminiero** [comment]
This should do it, let me know if that's not the case.

**Comment by lminiero** [comment]
@ancorgs any update? Can we close this?

**Comment by ancorgs** [comment]
Sorry for not being very responsive, I have been traveling.

But yes, we already have a prototype of jangouts making use of it and it works as expected. Nice job!

In general, the stability of the whole thing seems to be worse now, but that's a different matter not related to this issue (I'll do some extra checks and report back the findings).
