### ISSUE TITLE
Questions about janus Internals

### ISSUE THREAD

**Issue by ClosetMonkey** [meetecho/janus-gateway#2771]
Hi, I've been studying up on Janus and I have a few questions. First, how many janus processes typically run on a single machine? When a new endpoint is made are they all handled in the main thread, do new endpoints spawn a new thread per endpoint, or a new process? Are all connections into a single endpoint handled in the same thread, or does janus spawn a new thread per connection? 

Also, this doc https://yorc.readthedocs.io/en/master/cli.html describes janus as having an interactive command line interface. Is this true?

Thanks

**Comment by lminiero** [comment]
Please ask questions on the [group](https://groups.google.com/g/meetecho-janus), not here. As explained in the guidelines, we only use github for issues.
