### ISSUE TITLE
Janus.js meet data channel error

### ISSUE THREAD

**Issue by m01i0ng** [meetecho/janus-gateway#2779]
Hi:

When I run `echotest` demo, I meet `data channel` error, and text input is disabled

![image](https://user-images.githubusercontent.com/19723234/135014283-e43a324f-3bf5-4662-b320-798b5663d24c.png)
![image](https://user-images.githubusercontent.com/19723234/135014339-d66a92e1-a123-482e-8868-b1369e52e4ac.png)

**Comment by vinhsang7410** [comment]
i also have same your issues, have you fix it ?
