### ISSUE TITLE
an update message does not clear the cache of .mjr files that where deleted

### ISSUE THREAD

**Issue by wilbertmatthew** [meetecho/janus-gateway#278]
I issued an update message to the gateway, but the .mkj files that where deleted still show is the record list when a list message is sent. The update message return is a success, and the gateway shows that it processed the update request for the correct directory where the files where stored as shown in the gateway log snippet.

Handling message: {
   "request": "update"
}
Updating recordings list in .janus

After which the files are not removed from the cache

**Comment by lminiero** [comment]
This will require some more careful management than just removing old recordings that are not listed anymore. In fact, some users may be watching that specific recording, and simply getting rid of it because the .nfo file is gone could lea to serious issues. I guess the safest approach is to close the viewers' PeerConnections when they're watching a recording that an update removed from the list, but this will take a while as I have to study the best way to do that.

**Comment by wilbertmatthew** [comment]
ok thanks

**Comment by lminiero** [comment]
This commit should fix that. If any viewer is watching a removed recording, they're "kicked" and the playout is stopped. The only potential side effect is that now, if a recording already existed, it's not loaded again: this means that if, for instance, you edited an existing .nfo file to change the path to the .mjr files to use, this change will not be reflected. To effectively update an existing recording, you need to first remove it and then add it again.

Let me know if that works as expected.

**Comment by lminiero** [comment]
@wilbertmatthew any news?

**Comment by wilbertmatthew** [comment]
Lorenzo,

I used the latest recordplay demo (in the latest version of the gateway). I
ran into these problems:

1. Checked that no recordings where in the recording directory nor found by
the app.
[image: Inline image 1]

1. Created a recording, see listed in the recording list and played it.
[image: Inline image 1]

2. Created a second recording and saw recording 1 and 2 listed in the
recording list.

[image: Inline image 2]

3. I then played recording 2 and saw it play. However after it played it
was removed from the recording list. Console log
shows:
 Got a list of available recordings:
recordplaytest.js:330 Array[2]
recordplaytest.js:332   >> [1745156316] test1 (2015-07-24 06:35:46)
recordplaytest.js:332   >> [0]  ()

[image: Inline image 3]

4. I stopped the server and re ran the app and two recordings where
retrieved and displayed in the recording list.
Got a list of available recordings:
recordplaytest.js:330 [Object, Object]
recordplaytest.js:332   >> [1307382144] test2 (2015-07-24 06:37:47)
recordplaytest.js:332   >> [1745156316] test1 (2015-07-24 06:35:46)

5. I repeated the test playing recording 2 and the same thing happened. I
see it played

[image: Inline image 5]
 but what ever recording is played is removed from the record play list and
if you try and play it again the server crashes with a core dump.

[image: Inline image 4]

6. I check that the two test files are still in the recording directory and
they are.
[image: Inline image 1]

I ran the same test a number of times and can confirm that the problem is,
when a recording is played files are removed from the cache. I am assuming
this as they are not removed from the recording directory.

wilbert jackson

**Comment by lminiero** [comment]
Can't see any image, but I can see your problem, it's an issue in the code. I'll fix it right away, should be easy enough.

**Comment by lminiero** [comment]
Can you check again with the updated code?

**Comment by wilbertmatthew** [comment]
I tested the new fix and it has fixed the problem. But when I delete an .nfo and its .mjr files the deleted file is still shown in the recording list. If stop and start the server the recording list no longer shows the deleted file.

**Comment by lminiero** [comment]
Mh that's weird, it should be working as expected now. Unfortunately I have no time to look into this now. If the update message is still not doing its job, please leave the issue open and I'll look into it when I get back from the conference.

**Comment by wilbertmatthew** [comment]
The Update message does work to remove a delete file from the recording list. Log snippet shows the transaction.

Request for the list of recordings
Got a HTTP POST request on /janus/1978233880/2308953172...
[2308953172] There's a message for JANUS Record&Play plugin
Handling message: {
   "request": "update"
}
Updating recordings list in .janus
Importing recording '1745156316.nfo'...
Skipping recording with ID 1745156316, it's already in the list...
Recording 1307382144 is not available anymore, removing...
Recording 1307382144 still has viewers, delaying its destruction until later

thanks much

wilbert jackson
