### ISSUE TITLE
Deadlock in VideoRoom plugin on malformed "joinandconfigure" request

### ISSUE THREAD

**Issue by shripchenko** [meetecho/janus-gateway#2780]
Hi everyone.
In d7c9ef09da1a7ebca7c5a5bbb46ee3e6e1e42aa1 commit few blocks of code was added to `janus_videoroom.c`
`if(audiocodec && json_string_value(json_object_get(msg->jsep, "sdp")) != NULL) {
......
}`
... for `audiocodec` and videocodec` (please see the commit for exact diff).

In `goto error` subsection of this code you only `janus_refcount_decrease(&publisher->ref);`, while in fact there should be additional
`
janus_mutex_unlock(&publisher->room->mutex);
janus_refcount_decrease(&publisher->room->ref);
`

This provoke deadlock in VideoRoom plugin in such error conditions.

The same apply to `if(videocodec ...` section few lines below.

**Comment by atoppi** [comment]
Thanks @shripchenko, it should be fixed now.
