### ISSUE TITLE
Janus suddenly decides to shut down and SEGFAULTs

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#279]
Situation: Janus running one videoroom with two clients connected, and serving three RTP mount-points to a web client simultaneously. 

Out of the blue, Janus decided to shutdown (as far as I understand from this log): http://pastebin.com/WdPDq6Fp
Luckily, I was able to grab a core dump
gbd bt: http://pastebin.com/FRNYuCW3
gdb bt full: http://pastebin.com/eVLXZLDT

Besides this, I am clueless as to what exactly happened.

Ps. running on a8a3c33f350429e2f2ff1473cc9ff9b2d41dd9dc

**Comment by lminiero** [comment]
Is it still an issue with the latest Janus and/or the modular transports branch?

**Comment by lminiero** [comment]
Closing for lack of feedback. If it's still an issue, please refer to [this page](https://janus.conf.meetecho.com/docs/debug) for info on how to enable Address Sanitizer for additional debugging information.

**Comment by arjenveenhuizen** [comment]
We didn't run into this issue recently but haven't been stressing Janus that much lately. Will keep an eye out for this bug but we can leave it closed for now.

**Comment by lminiero** [comment]
Thanks, keep us posted!
