### ISSUE TITLE
Empty (broken?) candidate in janus SDP anwer on publisher joining

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2791]
I am back again working on https://github.com/meetecho/janus-gateway/pull/2769 and merged the latest master into my feature branch.

I now notice that my publishing chrome browser has issues handling the SDP answer from janus as it contains an empty 😲 candidate. I never saw that and it looks pretty much like a bug to me. (I cannot tell if that is now master merge related, the dependencies have not been touched...)

Here just a snap of the candidates. The last one in video is always (reproducible) empty.

...
a=candidate:21 1 tcp 1010830335 fd10::d2d:4b3c:2118:ed68 21399 typ host tcptype passive
a=candidate:22 1 udp 2015366399 fd10::c501:a7c6:cbdf:c8d3 27558 typ host
⁉ a=candidate:23

Full offer answer is here:
https://pastebin.com/tKvkHuDH

Any hint how to nail that down?

Jan

**Comment by Machosh** [comment]
Hello. Are those two PRs solve Problem???

In my case, failed to setRemoteDescription to 24~25th peer.

And the SDP’s size was ALWAYS 17.5KB.

I tried to 

Changing define JANUS_BUFSIZE’s value to double

Or

Setting MAX_JANUS_BUFSIZE(just copy JanFellner’s sdp-util.c)

But the SDP’s size was AlWAYS 17.5KB, so failed to setRemoteDescription at the 24~25th peer




working Peer in SDP
```
a=candidate:1 1 udp 2015363327 3.36.141.20 28743 typ host

a=end-of-candidates

m=video 9 UDP/TLS/RTP/SAVPF 96

c=IN IP4 3.36.141.20

a=sendonly

a=mid:23

a=rtcp-mux

a=ice-ufrag:QP0s

a=ice-pwd:T1zo5tY/Nx133UDUM5r8Ol

a=ice-options:trickle

a=setup:actpass

a=rtpmap:96 VP8/90000

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=rtcp-fb:96 goog-remb

a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=extmap:13 urn:3gpp:video-orientation

a=ssrc-group:FID 569723175 2138576610

a=msid:janus janus23

a=ssrc:569723175 cname:janus

a=ssrc:2138576610 cname:janus

```



error occured Peer in SDP

```

a=candidate:1 1 udp 2015363327 3.36.141.20 28743 typ host

a=end-of-candidates

m=video 9 UDP/TLS/RTP/SAVPF 96

c=IN IP4 3.36.141.20

a=sendonly

a=mid:24

a=rtcp-mux

a=ice-ufrag:QP0s

a=ice-pwd:T1zo5tY/Nx133UDUM5r8Ol

a=ice-options:trickle

a=setup:actpass

a=rtpmap:96 VP8/90000

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=rtcp-fb:96 goog-remb

a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=extmap:13 urn:3gpp:video-orientation

a=ssrc-group:FID 4038323982 2046724361

a=msid:janus janus24

a=ssrc:4038323982 cname:janus"

```

**Comment by Machosh** [comment]
Hello. Are those two PRs solve Problem???
In my case, failed to setRemoteDescription to 24~25th peer.
And the SDP’s size was ALWAYS 17.5KB.
I tried to

Changing define JANUS_BUFSIZE’s value to 65536
Or
Changing my sdp-util.c to [](https://github.com/meetecho/janus-gateway/pull/2793)

But the SDP’s size was AlWAYS 17.5KB, so failed to setRemoteDescription at the 24~25th peer

working Peer in SDP

```
a=candidate:1 1 udp 2015363327 3.36.141.20 28743 typ host

a=end-of-candidates

m=video 9 UDP/TLS/RTP/SAVPF 96

c=IN IP4 3.36.141.20

a=sendonly

a=mid:23

a=rtcp-mux

a=ice-ufrag:QP0s

a=ice-pwd:T1zo5tY/Nx133UDUM5r8Ol

a=ice-options:trickle

a=setup:actpass

a=rtpmap:96 VP8/90000

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=rtcp-fb:96 goog-remb

a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=extmap:13 urn:3gpp:video-orientation

a=ssrc-group:FID 569723175 2138576610

a=msid:janus janus23

a=ssrc:569723175 cname:janus

a=ssrc:2138576610 cname:janus
```

error occured Peer in SDP

```
a=candidate:1 1 udp 2015363327 3.36.141.20 28743 typ host

a=end-of-candidates

m=video 9 UDP/TLS/RTP/SAVPF 96

c=IN IP4 3.36.141.20

a=sendonly

a=mid:24

a=rtcp-mux

a=ice-ufrag:QP0s

a=ice-pwd:T1zo5tY/Nx133UDUM5r8Ol

a=ice-options:trickle

a=setup:actpass

a=rtpmap:96 VP8/90000

a=rtcp-fb:96 ccm fir

a=rtcp-fb:96 nack

a=rtcp-fb:96 nack pli

a=rtcp-fb:96 goog-remb

a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01

a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid

a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay

a=extmap:13 urn:3gpp:video-orientation

a=ssrc-group:FID 4038323982 2046724361

a=msid:janus janus24

a=ssrc:4038323982 cname:janus
```

**Comment by lminiero** [comment]
@Machosh are you talking about multistream? This is issue was on master, which cannot have 25 m-lines in an SDP. The multistream branch should already have code that automatically grows the SDP as needed.

**Comment by Machosh** [comment]
@lminiero  Yes. Definitely in Multistream.

`This is issue was on master, which cannot have 25 m-lines in an SDP`
 -> was this changed applied from the first version of multistream??
 -> if not, Can you tell me which PR changed this??

It will be the simplest way to update to a new version,
but I have some custom changed sources, so I want to change only the exact point.
