### ISSUE TITLE
I can not get keyframe from streaming 

### ISSUE THREAD

**Issue by StephenChio** [meetecho/janus-gateway#2794]
hello
when I use streaming plugin to receive the rtp data from videoRoom by rtp_forward
I can hear the audio at the first time, but some time I can not see the video(black screen), after a few sec，the video come out.
I create a rtp stream to receive data，set videobufferkf=true.
webRTC log：
> W/video_receive_stream2.cc: (line 745): No decodable frame in 200 ms, requesting keyframe.

thinks

**Comment by lminiero** [comment]
As explained in the documentation, you need to configure RTCP too for keyframes. Closing as out of scope here, please use the group for questions like this.

**Comment by StephenChio** [comment]
Thank you, Your answer is very helpful to me. I apologized for asking question on Issues. I will use the group for questions.
