### ISSUE TITLE
Loss "janus_videoroom_publisher_dereference_nodebug" before return 

### ISSUE THREAD

**Issue by WangLCG** [meetecho/janus-gateway#2795]
https://github.com/meetecho/janus-gateway/blob/943558d761130c35a19cdc3c3a890418f13aa3b8/plugins/janus_videoroom.c#L5472
https://github.com/meetecho/janus-gateway/blob/943558d761130c35a19cdc3c3a890418f13aa3b8/plugins/janus_videoroom.c#L5522

**Comment by lminiero** [comment]
Thanks, fixed!
