### ISSUE TITLE
[Multistream] [Video Room] Can not hear others on Safari

### ISSUE THREAD

**Issue by st-vinguyen** [meetecho/janus-gateway#2796]
**Step to reproduce**

1. Join a video room on chrome (User 1)
2. Join the same room on Safari (User 2) -> can hear User 1
3. User 1 unpublish and then publish again.
4. User 2 can not hear from User 1 anymore.

Do you have any idea to deal with this issue?

**Comment by lminiero** [comment]
As explained in the guidelines, please ask questions on the [group](https://groups.google.com/g/meetecho-janus).
