### ISSUE TITLE
Unable to join a room using janus-proxy 

### ISSUE THREAD

**Issue by muthuaravind** [meetecho/janus-gateway#2799]
{"videoroom":"event","error_code":430,"error":"Invalid element type (id should be a string)","traceback":["  File \"\/usr\/local\/lib\/python3.6\/dist-packages\/januscloud\/proxy\/plugin\/videoroom.py\", line 2391, in _handle_async_message\n    new_publisher.connect_backend(backend_server)\n","  File \"\/usr\/local\/lib\/python3.6\/dist-packages\/januscloud\/proxy\/plugin\/videoroom.py\", line 786, in connect_backend\n    _send_backend_message(backend_handle, body)\n","  File \"\/usr\/local\/lib\/python3.6\/dist-packages\/januscloud\/proxy\/plugin\/videoroom.py\", line 279, in _send_backend_message\n    data.get('error_code', JANUS_VIDEOROOM_ERROR_UNKNOWN_ERROR))\n"]}  on session 852580733184344

**Comment by lminiero** [comment]
SOunds like you're incorrectly using the API. Please refer to the documentation, and ask questions on the [group](https://groups.google.com/g/meetecho-janus).
