### ISSUE TITLE
Native examples and native apps

### ISSUE THREAD

**Issue by buihuythangqn** [meetecho/janus-gateway#280]
Can you give some examples for writing native apps using Janus. I can't see any of them when building Janus. Just some header files and I don't know how to use them. For example, how can I write 2 programs run on 2 computers and connect them together using Janus? Thanks.

**Comment by lminiero** [comment]
Please ask this on the group, the gihtub issues are only for problems with Janus.
https://groups.google.com/forum/?fromgroups=#!forum/meetecho-janus
