### ISSUE TITLE
Multistream branch, not close local stream after destroy janus

### ISSUE THREAD

**Issue by dewebdes** [meetecho/janus-gateway#2800]
https://github.com/meetecho/janus-gateway/blob/multistream/html/mvideoroomtest.html
The problem is for above link
After "Stop" button click and janus destroy **but** the local stream is still remain alive and webcam is in use by program
I try many many ways to stop the local track streams, like:

var vidTrack = myPluginHandle.webrtcStuff.myStream.getVideoTracks();
vidTrack.forEach(track => track.enabled = false);
vidTrack.forEach(track => track.stop());

But cant fix the problem, I used the multistream version because its ok in all devices but master version have some issue in windows ...

In the online demo: https://janus.conf.meetecho.com/mvideoroomtest.html
After stop, the page was reload and in this way its ok and webcam be disconnected
but I dont want to reload the page after stop streaming

**Comment by lminiero** [comment]
Please ask questions on the [group](https://groups.google.com/g/meetecho-janus), not here.

**Comment by dewebdes** [comment]
https://groups.google.com/g/meetecho-janus/c/K1cHhKIO_6w

**Comment by dewebdes** [comment]
I was post it on google group
But I dont understand the difference about BUGs and Questions
Sometime we dont know how to use the source, then this is the question
But, sometimes a clear bug is exist in your original online demo, then this can not be a question and this must be a bug or issue.
For example, my posted issue like this https://github.com/meetecho/janus-gateway/issues/2801 but you answered this link and for my same issue u tell that this is not issue and is a question?!!
in another hand, the reported issue form me, was not my issue, this is still exist in your live demo.

by the way, I love janus even u dont answer me like before happened, be successful with golden days....

**Comment by dewebdes** [comment]
It can be fixed with IFrames without reload the page:

<iframe allow="camera *;microphone *" id="etc" src="multistreamvideoroom.htm" style="position: fixed; top: 0px; left: -0px; z-index: 20000; display: none; width: 100%; height: 100%;"></iframe>

but this is dirty solution, I mean I can fixing the issue for my project as fast in this way but It's a pity for such a good engine (janus)
