### ISSUE TITLE
Signed token authentication doesn't work well on join to the room.

### ISSUE THREAD

**Issue by timsolov** [meetecho/janus-gateway#2810]
The issue is present on the latest master branch.

Cases with `token_auth = true` and `token_auth_secret = "janus871625371523"` in janus.cfg.

Scenario
1) Generate two tokens for all requests and for specail videoroom plugin:
    a) `1637606957,janus,janus.plugin.videoroom:/rWSlAurLtqWhVgRQ/x/UEO+IzI=`
    b) `1637606957,janus.plugin.videoroom,room=3edb0cdd-7173-481d-82f0-5eb31937d20f:XZQHOyCKF02PA48PIeUftAZjwC0=`
2) Connect to Websocket and use (a) token - all is fine. (without token we receive not authorized - all good).
3) Join the room `3edb0cdd-7173-481d-82f0-5eb31937d20f`:
3.1) **Actual behavior**: Try to join the room `3edb0cdd-7173-481d-82f0-5eb31937d20f` without token - we enter the room. Also with token (b) we will enter the room.
3.2) **Expected behavior**: Try to join the room `3edb0cdd-7173-481d-82f0-5eb31937d20f` without token - not authorized error. With token (b) - enter the room.

There are an issues in `plugins/janus_videoroom.c` (janus_videoroom_access_room function) and in `auth.c` (janus_auth_check_signature_contains function).

I can fix the bug.

**Comment by lminiero** [comment]
Unfortunately, it looks like this fix breaks regular tokens in the VideoRoom (ACL). I'll have to see how this can be addressed. If I can't find any way to address this properly, I'll have to revert this patch, as ACL are what most users use in production today.
