### ISSUE TITLE
Janus :: Streaming Plugin :: RTSP stream not working

### ISSUE THREAD

**Issue by Nigam-Patel-Main** [meetecho/janus-gateway#2811]
We use Janus for streaming  one IP Camera but we got the error :

**[1] Reconnected to the RTSP server, streaming again
[WARN] [1] 5s passed with no media, trying to reconnect the RTSP stream**

- **The camera RTSP URL working Perfact in VLC Player**.
- We use libcurl version **7.58.0**
-  We use below request to create mountpoint in Janus streaming plugin 
    var body = {
          "request": "create",
          "type": "rtsp",
          "id": [id],
          "description": "IP Camera",
          "video": true,
          "audio": true,
          "url": [rtsp url without credentials],
          "rtsp_user": [username],
          "rtsp_pwd": [password],
          "videortpmap": "H264/90000",
          "videofmtp": "profile-level-id=42e01f;packetization-mode=1"
        };
Error Stack Trace Mention In This Link: [pastebin Janus Streaming Log](https://pastebin.com/GP9C3VRr)

**If you required RTSP URL then just inform I provide in private mail.**

**Comment by RSATom** [comment]
Janus doesn't support [RTSP Interleaved mode](https://en.wikipedia.org/wiki/Real_Time_Streaming_Protocol#Embedded_(Interleaved)_Binary_Data)

**Comment by Nigam-Patel-Main** [comment]
@RSATom Thank for response
But What is the solution for that ? Where I need to change ?

**Comment by RSATom** [comment]
If your ip cam is behind router - you will have to add port forwarding for UDP ports

**Comment by Nigam-Patel-Main** [comment]
@RSATom  This RTSP URL working perfect in VLC Player. If the problem of routing than may not work in VLC Player.

**Comment by RSATom** [comment]
VLC tries UDP first, if it can't receive anything within 5 seconds (if I remember correctly) it switches to interleaved mode.

**Comment by RSATom** [comment]
If you will provide me username/pass for your rtsp, I could confirm it...

**Comment by Nigam-Patel-Main** [comment]
Can you provide your email ?

**Comment by RSATom** [comment]
it's pubic in my profile

**Comment by RSATom** [comment]
BTW, I bet @lminiero will close this issue soon, since it's more suitable for https://groups.google.com/g/meetecho-janus ...

**Comment by Nigam-Patel-Main** [comment]
I sent an email please check. 
Okay I am Generate This Issue In This Group and close this issue.

**Comment by lminiero** [comment]
> BTW, I bet @lminiero will close this issue soon, since it's more suitable for https://groups.google.com/g/meetecho-janus ...

You read my mind, as it was exactly what I was going to do now that I arrived at the office :smile:

**Comment by Nigam-Patel-Main** [comment]
😅

**Comment by lminiero** [comment]
@Nigam-Patel-Main we're not going to add interleaved mode to the plugin any time soon, so no point in opening the issue on the group eitherI think. As @RSATom said you should configure the UDP port mapping in that case.

**Comment by Nigam-Patel-Main** [comment]
@lminiero Sir 
what should be the solution I am stuck in this

**Comment by RSATom** [comment]
@Nigam-Patel-Main I would not recommend you asking it here... @lminiero can stop answering at all if you will proceed to do it...
