### ISSUE TITLE
Conduction webrtc connection over video room

### ISSUE THREAD

**Issue by RaniRaven** [meetecho/janus-gateway#2819]
We have a code connecting and doing all the facilitation of using video room with publisher and subscriber.
All the calls to Janus-Gateway are returning with o.k. including the "start" of the streaming by calling start versus the room.
The start returns with o.k., but the Janus server itself displays multiple errors, as in the attached png file.
I've looked into some of the ideas about it, and I cannot understand the issues there.
Everything is o.k. communication wise, and the Janus-Gateway is running inside docker desktop (windows) on my computer, so no issues of NAT and other networking.
There is some issue with the ICE protocol, starting only when the video started, although all the checks were completed successfully when both "sides" of the video room were added as publisher and subscriber corrspondly.
![janus-error](https://user-images.githubusercontent.com/13769039/143555227-5c80e9b5-981f-4744-8543-72324d5f26ae.png)

**Comment by lminiero** [comment]
Exchanging messages with Janus doesn't guarantee a PeerConnection will succeed: so the oks are normal, but you're getting an ICE failure, which comes from the actual attempt to establish a communication. As such, there's no issue in Janus, so please post this question on the [group](https://groups.google.com/g/meetecho-janus) instead, where problems of this nature should be discussed.
