### ISSUE TITLE
Documentation for admin/monitor api, and for handling the janus.jcfg file

### ISSUE THREAD

**Issue by RaniRaven** [meetecho/janus-gateway#2820]
After passing on all the documentation in the site, it seems like some explanations are missing.
How to edit the janus.jcfg file ? What do all the properties mean ? Can all the settings be done there through the admin-api, or are there things that require actual editing of this file ?
Does janus-gateway process holds a file-watcher versus this file to change it dynamically upon editing, or a restart is needed there ?Is there any link where I can find detailed information with samples for using the admin-api and changing the .jcfg file ?
Moreover, for the admin-api, what is the port upon which it is listening ?

Regards,
Rani

**Comment by lminiero** [comment]
You need to edit janus.jcfg manually, and no, not all settings can be tweaked via Admin API, only those listed in the documentation. Editing them there, though, is temporary, not permanent: the config file is never modified by Janus, which only reads it at startup.

> Moreover, for the admin-api, what is the port upon which it is listening ?

You my want to learn more about the modular transports in Janus, and the related config files.
