### ISSUE TITLE
Cannot create socket for audio ... 978 (Address family not supported by protocol)

### ISSUE THREAD

**Issue by RaniRaven** [meetecho/janus-gateway#2821]
Hi all,

Attached is the issue we get when trying to start janus-gateway on linux docker.
We cannot figure out how to solve this issue, we belive it has something to do with the ipv6 support maybe, or something in the way the docker framework (local) on linux is handling the networking.
This is  as the same image is running o.k. on Window's docker desktop

Would appreciate your advice about this.
![janus-protocol-issue](https://user-images.githubusercontent.com/13769039/143556650-3f31943c-eb63-42f5-9a37-4e286d41f72f.png)
.

**Comment by lminiero** [comment]
Possibly related to #2508, as in BSD for instance you can't use an IPv6 socket to listen for both IPv4 and IPv6, which is what we do by default. Maybe your Linux configuration currently forbids it too. If so, just force ipv4 when creating the mountpoint (check the config file and documentation of the Streaming plugin for details).

**Comment by RaniRaven** [comment]
I've tried any offered configuration, nothing works. Janus-Gateway refuses to run for some reason when setting anything to IPv4 only, like changing the address to "0.0.0.0", or anything else. No matter what I do I cannot overcome the issue above. Could not find any relevant documentation on that issue.
Where is the explanation of how to overcome this issue is explained ? Cannot run janus-gateway in any constellation on Ubuntu's docker.

**Comment by lminiero** [comment]
This is the point where we decide what kind of socket to create:
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L5459

Try specifying an interface too, or a specific local IPv4. You may want to add some debug lines to print what the value of the `family` variable is when a socket is created.
