### ISSUE TITLE
Gathering candidates Error

### ISSUE THREAD

**Issue by lm123** [meetecho/janus-gateway#2834]
Janus v0.10.10, we meet the following two errors:

1. 
[ice.c:janus_ice_setup_local:3692] [7261210517768617] Error gathering candidates...
[janus.c:janus_process_incoming_request:1442] Error setting ICE locally
[janus.c:janus_process_incoming_request:1699] [7261210517768617] Received a trickle, but still cleaning a previous session

2.
(process:31882): GLib-ERROR **: Creating pipes for GWakeup: Too many open files

Such problems are solved in the latest version?

**Comment by lminiero** [comment]
https://janus-legacy.conf.meetecho.com/docs/FAQ.html#ulimit
