### ISSUE TITLE
Chrome 96: Plan B SDP semantics is no longer supported

### ISSUE THREAD

**Issue by Garik-** [meetecho/janus-gateway#2839]
Hi,
I'm experiencing problems with some installation of chrome 96.
The error is : "DOMException: Failed to construct 'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe compatibility issues on modern browsers and is no longer supported. See https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time."
Seems that Chrome has dropped the support of plan-b sdp semantic.

**Comment by lminiero** [comment]
We don't set plan-b semantics anywhere in janus.js, except for Chrome <=72: https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L1821

**Comment by Garik-** [comment]
This is my mistake. I used the ipad emulation mode for debugging with user-agent substitution :(

**Comment by lminiero** [comment]
Ack, closing then.
