### ISSUE TITLE
Janus crashes with latest release

### ISSUE THREAD

**Issue by dnish** [meetecho/janus-gateway#2840]
Hey,
since the last updates, Janus crashes every 10 minutes on our main server (Ubuntu 20.04).

Version: 0.11.7 and Master

Error: 
```Dec 20 20:10:36 ns541136 kernel: [983376.078081] hloop 475389242[5625]: segfault at f8 ip 00005619fda729e8 sp 00007f0d5f6f5750 error 4 in janus[5619fda24000+b8000]```.

We are using the video call plugin (not the video room plugin).

**Comment by lminiero** [comment]
That's not enough information to debug. Please check the debugging instructions in the docs to collect something we can look at.

**Comment by dnish** [comment]
Yeah, we are having a .crash file in ```/var/crash/_opt_janus_bin_janus.0.crash```. But when using <code>gdb /opt/janus/bin/janus /var/crash/_opt_janus_bin_janus.0.crash</code> I get the following error:


> Reading symbols from /opt/janus/bin/janus...done.
> "/var/crash/_opt_janus_bin_janus.0.crash" is not a core dump: File format not recognized

**Comment by direritcom** [comment]
Hello, have you found a solution to the problem?
We have exactly the same situation on Ubuntu 20.04.
We can't fix the error so far to make a dump.

> Hey, since the last updates, Janus crashes every 10 minutes on our main server (Ubuntu 20.04).
> 
> Version: 0.11.7 and Master
> 
> Error: `Dec 20 20:10:36 ns541136 kernel: [983376.078081] hloop 475389242[5625]: segfault at f8 ip 00005619fda729e8 sp 00007f0d5f6f5750 error 4 in janus[5619fda24000+b8000]`.
> 
> We are using the video call plugin (not the video room plugin).

**Comment by lminiero** [comment]
There's literally _nothing_ we can do until you share a meaningful dump as I've said my previous message.

**Comment by dnish** [comment]
Hey,#
nope, I'm still waiting for an answer from @lminiero how I can read the crash file.

**Comment by lminiero** [comment]
I have no idea how you can open that dump: I don't know your system. Please do some more research on your own.

**Comment by dnish** [comment]
> I have no idea how you can open that dump: I don't know your system. Please do some more research on your own.

Well, it is written in the issue (Ubuntu 20.04). I've already searched for the gdb error and didn't find anything that fixed the issue.

**Comment by direritcom** [comment]
Didn't you have this problem in this version?

> Meanwhile you can revert back to 0.11.6.

**Comment by dnish** [comment]
> Didn't you have this problem in this version?
> 
> > Meanwhile you can revert back to 0.11.6.

Nope, there it doesn't happen. We've already reverted our production server back to 0.11.6. Only thing we have there is that Janus crashes silently every 4-5 days without any logs (checked syslog and janus.log). When this happens, users can still connect to the server, but the server stops connecting people. So when people calling other people, nothing happens, but Janus still accepts connection. But this issue exists since a few versions and was already mentioned in another topic.

**Comment by direritcom** [comment]
> > Didn't you have this problem in this version?
> > > Meanwhile you can revert back to 0.11.6.
> 
> Nope, there it doesn't happen. We've already reverted our production server back to 0.11.6. Only thing we have there is that Janus crashes silently every 4-5 days. When this happens, users can still connect to the server, but the server stops connecting people. So when people calling other people, nothing happens, but Janus still accepts new connections. But this issue exists since a few versions and was already mentioned in another topic. There I already got the same problem that I couldn't read the crash file.
> 
> Maybe you can try to read your crash file. If you are on Ubuntu too, you will find it in /var/crash.

We also have a crash on version 0.11.6 every day at the same time. Tomorrow we will try to catch the log.

Dec 23 12:23:32 admin kernel: [116911.677961] hloop 180146043 [133309]: segfault at f8 ip 00005633900dcde0 sp 00007f0d1e7bb760 error 4 in janus [56339009c000 + 86000]

**Comment by direritcom** [comment]
> > Didn't you have this problem in this version?
> > > Meanwhile you can revert back to 0.11.6.
> 
> Nope, there it doesn't happen. We've already reverted our production server back to 0.11.6. Only thing we have there is that Janus crashes silently every 4-5 days. When this happens, users can still connect to the server, but the server stops connecting people. So when people calling other people, nothing happens, but Janus still accepts new connections. But this issue exists since a few versions and was already mentioned in another topic. There I already got the same problem that I couldn't read the crash file.
> 
> Maybe you can try to read your crash file. If you are on Ubuntu too, you will find it in /var/crash.

We tracked the error

janus_ice_outgoing_traffic_handle (handle=0x7fffec06db80, pkt=0x55555560bc80 <janus_ice_media_stopped>) at ice.c:4350
4350                    if(!component->in_stats.audio.notified_lastsec && component->in_stats.audio.bytes && !stream->audio_send) {

**Comment by dnish** [comment]
> > Maybe you can try to read your crash file. If you are on Ubuntu too, you will find it in /var/crash.
> 
> We tracked the error, libnice master.
> 
> janus_ice_outgoing_traffic_handle (handle=0x7fffec06db80, pkt=0x55555560bc80 <janus_ice_media_stopped>) at ice.c:4350 4350 if(!component->in_stats.audio.notified_lastsec && component->in_stats.audio.bytes && !stream->audio_send) {

Perfect, yeah we got the same with libnice and segfault.

**Comment by direritcom** [comment]
> > > Может быть, вы можете попробовать прочитать свой файл сбоя. Если вы тоже используете Ubuntu, вы найдете его в / var / crash.
> > 
> > 
> > Мы отследили ошибку, мастер libnice.
> > janus_ice_outgoing_traffic_handle (handle = 0x7fffec06db80, pkt = 0x55555560bc80 <janus_ice_media_stopped>) на ice.c: 4350 4350 if (! component-> in_stats.audio.notified_lastsec && component-> in_stats_audio.-tream)
> 
> Отлично, да, у нас такая же ошибка (segfault libnice).

We've made an edit, hopefully this will solve the problem.

static gboolean janus_ice_outgoing_traffic_handle(janus_ice_handle *handle, janus_ice_queued_packet *pkt) {
  janus_session *session = (janus_session *)handle->session;
  janus_ice_stream *stream = handle->stream;
  janus_ice_component *component = stream ? stream->component : NULL;
  if(pkt == &janus_ice_start_gathering) {
    /* Start gathering candidates */
    if(handle->agent == NULL) {
      JANUS_LOG(LOG_WARN, "[%"SCNu64"] No ICE agent, not going to gather candidates...\n", handle->handle_id);
    } else if(!nice_agent_gather_candidates(handle->agent, handle->stream_id)) {
      JANUS_LOG(LOG_ERR, "[%"SCNu64"] Error gathering candidates...\n", handle->handle_id);
      janus_ice_webrtc_hangup(handle, "ICE gathering error");
    }
    return G_SOURCE_CONTINUE;
  } else if(pkt == &janus_ice_add_candidates) {
    /* There are remote candidates pending, add them now */
    GSList *candidates = NULL;
    NiceCandidate *c = NULL;
    while((c = g_async_queue_try_pop(handle->queued_candidates)) != NULL) {
      JANUS_LOG(LOG_VERB, "[%"SCNu64"] Processing candidate %p\n", handle->handle_id, c);
      candidates = g_slist_append(candidates, c);
    }
    guint count = g_slist_length(candidates);
    if(stream != NULL && component != NULL && count > 0) {
      int added = nice_agent_set_remote_candidates(handle->agent, stream->stream_id, component->component_id, candidates);
      if(added < 0 || (guint)added != count) {
        JANUS_LOG(LOG_WARN, "[%"SCNu64"] Failed to add some remote candidates (added %u, expected %u)\n",
          handle->handle_id, added, count);
      } else {
        JANUS_LOG(LOG_VERB, "[%"SCNu64"] %d remote %s added\n", handle->handle_id,
          count, (count > 1 ? "candidates" : "candidate"));
      }
    }
    g_slist_free(candidates);
    return G_SOURCE_CONTINUE;
  } else if(pkt == &janus_ice_dtls_handshake) {
    if(!janus_is_webrtc_encryption_enabled()) {
      JANUS_LOG(LOG_WARN, "[%"SCNu64"] WebRTC encryption disabled, skipping DTLS handshake\n", handle->handle_id);
      janus_ice_dtls_handshake_done(handle, component);
      return G_SOURCE_CONTINUE;
    } else if(!component) {
      JANUS_LOG(LOG_WARN, "[%"SCNu64"] ICE component not initialized, aborting DTLS handshake\n", handle->handle_id);
      return G_SOURCE_CONTINUE;
    }
    /* Start the DTLS handshake */
    janus_dtls_srtp_handshake(component->dtls);
    /* Create retransmission timer */
    component->dtlsrt_source = g_timeout_source_new(50);
    g_source_set_callback(component->dtlsrt_source, janus_dtls_retry, component->dtls, NULL);
    guint id = g_source_attach(component->dtlsrt_source, handle->mainctx);
    JANUS_LOG(LOG_VERB, "[%"SCNu64"] Creating retransmission timer with ID %u\n", handle->handle_id, id);
    return G_SOURCE_CONTINUE;
  } else if(pkt == &janus_ice_media_stopped) {
    if (component == NULL)
      JANUS_LOG(LOG_ERR, "[%"SCNu64"] Component is null, media stopped\n", handle->handle_id);
    if (stream == NULL)
      JANUS_LOG(LOG_ERR, "[%"SCNu64"] Stream is null, media stopped\n", handle->handle_id);
    if (component != NULL && stream != NULL) {
      /* Either audio or video has been disabled on the way in, so use the callback to notify the peer */
      if(!component->in_stats.audio.notified_lastsec && component->in_stats.audio.bytes && !stream->audio_send) {
        /* Audio won't be received for a while, notify */
        component->in_stats.audio.notified_lastsec = TRUE;
        janus_ice_notify_media(handle, FALSE, 0, FALSE);
      }
      int vindex=0;
      for(vindex=0; vindex<3; vindex++) {
        if(!component->in_stats.video[vindex].notified_lastsec && component->in_stats.video[vindex].bytes && !stream->video_recv) {
          /* Video won't be received for a while, notify */
          component->in_stats.video[vindex].notified_lastsec = TRUE;
          janus_ice_notify_media(handle, TRUE, vindex, FALSE);
        }
      }
      return G_SOURCE_CONTINUE;
    }
    else return G_SOURCE_CONTINUE;

**Comment by lminiero** [comment]
Please don't put huge chunks of code inline: it's written explicitly in the guidelines. I edited the comment for you to make it a collapsed section instead. That said, your patch is not helpful, as you don't say what you changed and why.

> We tracked the error, libnice master.
> 
> ```janus_ice_outgoing_traffic_handle (handle=0x7fffec06db80, pkt=0x55555560bc80 <janus_ice_media_stopped>) at ice.c:4350 4350 if(!component->in_stats.audio.notified_lastsec && component->in_stats.audio.bytes && !stream->audio_send) {```

What is the cause? component and/or stream being `NULL`? Something else? If you managed to track it down to that, more info would be helpful to work on a fix.

**Comment by lminiero** [comment]
In the meanwhile, I've added NULL checks to both in the `janus_ice_media_stopped` management. If it still crashes for you in the same point, please let us know and we'll reopen the issue.

**Comment by dnish** [comment]
> In the meanwhile, I've added NULL checks to both in the `janus_ice_media_stopped` management. If it still crashes for you in the same point, please let us know and we'll reopen the issue.

Hey @lminiero,
it's still happening here - on every version after 11.6. I've also updated libnice and libsrtp2 to their latest versions. The server crashes after a few minutes:

```
Jan 31 17:13:03 ns541136 kernel: [ 2223.985770] hloop 700484825[25487]: segfault at f8 ip 0000558a5a1f59e8 sp 00007f6009eda750 error 4 in janus[558a5a1a7000+b8000]
Jan 31 17:13:08 ns541136 systemd[1]: janus.service: Main process exited, code=killed, status=11/SEGV
```

The only thing that works is reverting back to version 11.6.  If you still need another dump, I can revert back to the latest version when we have a lower load on our servers.

**Comment by lminiero** [comment]
That dump provides no information. Please provide a libasan trace.

**Comment by dnish** [comment]
@lminiero I've reconfigured Janus, hope this one helps:

https://pastebin.com/Qz732QB9

**Comment by dnish** [comment]
Hey @tmatth,
thank you very much. I've rebuilt Janus, the error disappears, but we get a new one:

https://pastebin.com/NMbpKEj7

**Comment by tmatth** [comment]
> Hey @tmatth, thank you very much. I've rebuilt Janus, the error disappears, but we get a new one:
> 
> https://pastebin.com/NMbpKEj7

If I'm reading this correctly, it seems like `janus_ice_webrtc_free` is being called at the same time as `janus_ice_relay_rtp`, such that:
This check:
https://github.com/meetecho/janus-gateway/blob/a832c5d34d90f6cc63e8450433c9cd2ec920c870/ice.c#L4934
is insufficient by the time this line is executed:
https://github.com/meetecho/janus-gateway/blob/a832c5d34d90f6cc63e8450433c9cd2ec920c870/ice.c#L4936
as this has happened in between:
https://github.com/meetecho/janus-gateway/blob/a832c5d34d90f6cc63e8450433c9cd2ec920c870/ice.c#L1595
