### ISSUE TITLE
av1 codec sdp syntax change some case

### ISSUE THREAD

**Issue by ilpyoung** [meetecho/janus-gateway#2844]
> **IMPORTANT! READ OR WE WILL JUST CLOSE YOUR ISSUE!**
>
> 1. We only use GitHub for code issues, **NOT** for connectivity/negotiation/WebRTC issues or questions: for those, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead.
> 2. If you think you really found a bug, make sure nobody reported it already (do a search first, and check open issues);
> 3. Make sure the issue wasn't already solved in master: we will ignore the issue otherwise.
> 4. Do **NOT** paste large amounts of text inline in the issue or comments: it makes the exchanges much harder to follow. If you need to provide logs or code snippets, either use a service like [pastebin](http://pastebin.com/) and [gist](https://gist.github.com/), or use the `details` and code block Markdown features to collapse them.
> 5. If you're encountering crashes, make sure you provide a useful trace of what happened: depending on the issue, we may need output from AddressSanitizer or GDB stacktraces (more details available [here](http://janus.conf.meetecho.com/docs/debug)).
>
> If you understood the guidelines, please do remove this text and share your findings. Notice that if you remove this text without reading the guidelines, or you just ignore them, we'll close the issue without further explanation.

Hi 

I am trying to use AV1 on m98
AV1 codec of sdp was marked as AV1X.
However, there are cases where it comes in as AV1 depending on the PC.
It might be a change in libwebrtc m98

![스크린샷 2021-12-29 오전 11 26 24](https://user-images.githubusercontent.com/85208281/147621565-283b3310-434b-4d1b-a1fc-5f8d453e80e0.png)

So janus shows Unsupported codec 'none' and fails to negotiate video

When I change AV1X in sdputils file and utils to AV1, the codec is recognized normally.
Looks like it needs a fix

It may be a problem depending on the version of libwebrtc
It seems that it needs to be modified so that both AV1 and AV1X work.

**Comment by fippo** [comment]
libwebrtc changed this in M96 as noted [in this PSA](https://groups.google.com/g/discuss-webrtc/c/ACmDgZEAooc/m/dCDBbZF9BwAJ)

**Comment by lminiero** [comment]
Yeah I read the PSA but forgot to act on it. Supporting both sounds like a pain, so not sure I'll do that. I'll likely end up sticking to the new version, but I'll only decide when I go back to the office after my vacation.
