### ISSUE TITLE
listforwarders request generates a "Failed to stringify message" error

### ISSUE THREAD

**Issue by amoizard** [meetecho/janus-gateway#2846]
Hi,

Janus version: "multistream branch" (commit 237282e)

short: "listforwarders" generate a "Failed to stringify message" error in the logs

To reproduce:
1/ I use HTTP API
2/ I create a room
3/ I wait for a publisher to come
4/ I send "rtp_forward" (success reported and forward working)
5/ I send a "listforwarders".

This last request generate

>      [ERR] [transports/janus_http.c:janus_http_send_message:1107] Failed to stringify message...

And no HTTP answer is returned by janus.

When "rtp_forward" is not configured yet, the "listforwarders" correctly reports an empty list:

```
"plugindata":{
  "plugin":"janus.plugin.videoroom",
  "data":{
   "videoroom":"forwarders",
   "room":"room1",
   "publishers":[
     {"publisher_id":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","display":"yyyyyyyyyyyyyyyyyyyyyyyyyy"}
   ]
  }
}
```

The issue looks related to janus_videoroom_rtp_forwarder_summary method. When line 6154 below is commented, the json is returned (without required information)

```
// LINE 6154 //json_object_set_new(pl, "forwarders", flist);
```

I have not been able to locate the issue more precisely.

**Comment by lminiero** [comment]
If commenting out that line fixes it, then it means something is broken in how the `flist` object itself is created, so you can try commenting other parts of the code instead, that is those that actually add stuff to that object . I don't have time right now to test, but I'll try to do that in the next few days.

**Comment by amoizard** [comment]
Thanks for answering.

I already tried to modify only "janus_videoroom_rtp_forwarder_summary" method to minimize the object returned.
I have added "return json;" after line 2634 

```
json_object_set_new(json, "stream_id", json_integer(f->stream_id));
//ADDED
return json;
//ADDED
```

But the error was still the same!
I probably missed something obvious...

**Comment by lminiero** [comment]
The above commit fixes it for me.

**Comment by amoizard** [comment]
Thanks a lot! I confirmed it also worked for me.
