### ISSUE TITLE
Janus occasionally segfaults when using websocket & rest API

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#285]
While stress-testing Janus (GIT HEAD), we notice that Janus occasionally segfaults (always during session setup/ICE negotiation) when using the websocket and/or rest API.
I was able to grab a stack trace, see: http://pastebin.com/wNgKqpkD
stdout: http://pastebin.com/BdKmEYkF

It looks to me that this has to do with libwebsockets. At the moment of the crash, a client was in the process of connecting to Janus via the REST API while there were already a couple of clients connected via the websocket API.

Any idea? For now we are moving away from using the websocket API because it appears to be the source of quite some issues.

**Comment by lminiero** [comment]
I never encountered any such crash, and we use WebSockets intensively in many projects. What version of Janus is this? at the line 5052 the backtrace mentions there's nothing harmful:
https://github.com/meetecho/janus-gateway/blob/master/janus.c#L5052

That said, please try this version instead:
https://github.com/meetecho/janus-gateway/pull/281

It's the one we'll use in the short future as a basis for all transports, including WebSockets.

**Comment by arjenveenhuizen** [comment]
Ah, I did not see #281 yet. Very interesting. Thx for the heads up. 

Because of some minor adjustments in our own janus.c, the file lines do not match with git head anymore.
In our version, line 5052 is equivalent to https://github.com/meetecho/janus-gateway/blob/master/janus.c#L5097

**Comment by lminiero** [comment]
Might be an issue in libwebsockets, reinstall it to be sure.

**Comment by arjenveenhuizen** [comment]
We are already using git head of libwebsockets. (without any modifications;))

**Comment by lminiero** [comment]
Yep, I mean recompile/reinstall, in case it's an issue with the library you have (as I said it gives us no issue).

**Comment by arjenveenhuizen** [comment]
Ah, well, that is exactly what I did a couple of days ago actually (a fresh git clone of janus + libnice + libwebsockets).

**Comment by arjenveenhuizen** [comment]
FYI, we started with a clean slate and switched to the modular-transports branch two days ago. Things are looking stable now for both the Websocket and REST API.

**Comment by lminiero** [comment]
Let us know if the modular-transports branch gives you any issue, on the related PR page. We update it regularly, also merging with master when any change there happens, so you should check often if we fixed anything.
