### ISSUE TITLE
implicit declaration of function ‘nice_address_ip_version’ 

### ISSUE THREAD

**Issue by achao1104** [meetecho/janus-gateway#2850]
Hello,

When I executed 'make' for Janus, it reports the following error:

ice.c: In function ‘janus_ice_cb_new_local_candidate’:
ice.c:2195:2: error: implicit declaration of function ‘nice_address_ip_version’ [-Werror=implicit-function-declaration]
  gboolean ipv6 = (nice_address_ip_version(&candidate->addr) == 6);
  ^

**Comment by ylighgh** [comment]
hi,Did you solve this problem?

**Comment by clarkhillm** [comment]
you need an updated libnice ...
