### ISSUE TITLE
sctp_sendv error after datachannel client disconnects

### ISSUE THREAD

**Issue by le-chat** [meetecho/janus-gateway#2854]
Sometimes logs from Janus are polluted by messages like
```[ERR] [sctp.c:janus_sctp_send_text_or_binary:818] [8531979795481126] sctp_sendv error (2)```
They seem to happen after some datachannel client disconnects. For example, if I open in browser a page, which connects to video and data channel and successfully receives both video and data messages, and later close browser (last time I've checked with `kilall ...`, but just closing window seems to work too), 5 minutes later I begin to see a lot of logs with `sctp_sendv error`.

If I correctly understand https://github.com/meetecho/janus-gateway/blob/23b7c212cc89c8bb95fd67113acae9a86c65dc25/sctp.c#L818, errno 2 (No such file or directory) means that sctp->sock is invalid and will never become valid. Does not it make sense to close data channel in this case?

If yes, how can I achieve this, is it appropriate to call janus_sctp_association_destroy here?

I've updated Janus to recent master (23b7c21) and confirmed this is still an issue.

There exists issue #1007 with sctp_sendv error, but I believe the reason here is different.

**Comment by le-chat** [comment]
I've tested with 99d198c, but for now getting only ```[WARN] [6161759772422067] Couldn't send all pending messages, queueing new message``` (previously I've seen sometimes this, sometimes `sctp_sendv error` in such situation). If I capture `sctp_sendv error` with more detailed log, I'll write.

In any case, setting session_timeout to nonzero seems to fix problem. We will deploy fresh Janus with `session_timeout = 60` and see results this and next week.

Thank you for your help.

**Comment by lminiero** [comment]
> In any case, setting session_timeout to nonzero seems to fix problem. We will deploy fresh Janus with `session_timeout = 60` and see results this and next week.

Yeah, a `session_timeout` of `0` only makes sense if you have your own way of detecting when users leave without notifying the API, meaning you'd then remove the sessions yourself.

**Comment by lminiero** [comment]
@le-chat any update on your tests? Or can this be closed?

**Comment by le-chat** [comment]
I haven't seen `sctp_sendv error` anymore. I think, yes, this may be closed. Thank you again.
