### ISSUE TITLE
IMPORTANT: Multistream merge date, and 0.x branch

### ISSUE THREAD

**Issue by lminiero** [meetecho/janus-gateway#2855]
Hi all,

as you probably know, we've been working on the [multistream](https://github.com/meetecho/janus-gateway/pull/2211) branch for quite a long time and in a couple of different iterations. We now have an official date for when that branch will be merged in master, which is **February 11th 2022**, that incidentally also is the 8th birthday of Janus :hand_over_mouth: 

Of course, we know that many people use the current version of Janus in production today, and we're not planning to abandon that code, quite the opposite. In fact, while the multistream branch will become the `1.0` version of Janus, the existing `0.x` code will live on in the following branch instead:

https://github.com/meetecho/janus-gateway/tree/0.x

As such, if you don't want to upgrade to the new version of Janus yet, you can get your code from that branch instead, and nothing should change for you. The branch is already active, and acting as a lazy mirror of the current master, so if you want to be sure you're not caught unprepared by the change we'll make in February and are currently pulling your changes directly from the `master` branch, you can change your scripts to pull the `0.x` branch instead and all should be fine. If you usually use releases instead, then all should be ok, as the plan is to still occasionally push releases for the `0.x` branch well.

That said, while we do indeed want to keep the `0.x` branch updated, especially when we become aware of bugs or security issues to fix, please notice that we'll start focusing much more on the new version as soon as it is merged, especially to start working on enhancements we've kept on hold so far, and we'll likely greatly limit the addition of new features to the old version instead. As such, while the current version of Janus will indeed be kept alive for quite some time, you'll definitely want to have a look at the new version as well to plan an upgrade sooner or later, especially if you'll want to take advantage of new features.

I guess that three weeks are enough of a heads up to prepare for the change (whether you plan to keep the old version of switch to the new one), but in case you have feedback to share or suggestions to make on how to keep this as painless as possible for everyone, please let us know.

**Comment by spscream** [comment]
Hi, 

Can you please publish 0.x releases documentation somewhere? 
Now on https://janus.conf.meetecho.com/ docs are published only for multistream branch.

**Comment by lminiero** [comment]
That's what https://janus-legacy.conf.meetecho.com is for :slightly_smiling_face: 
It's been available for quite some time already: https://groups.google.com/g/meetecho-janus/c/AqZ6ENFXH44/m/PA7BV69UEAAJ

**Comment by spscream** [comment]
> That's what https://janus-legacy.conf.meetecho.com is for 🙂 It's been available for quite some time already: https://groups.google.com/g/meetecho-janus/c/AqZ6ENFXH44/m/PA7BV69UEAAJ

Thx, TIL :)

**Comment by lminiero** [comment]
As a side note, the main website also has a link to the 0.x docs and demos in the top bar.

**Comment by lminiero** [comment]
> As a side note, the main website also has a link to the 0.x docs and demos in the top bar.

Argh, correcting myself, looks like that link is wrong and still points to `janus` and not `janus-legacy`! I'll have to fix that...

**Comment by lminiero** [comment]
> > As a side note, the main website also has a link to the 0.x docs and demos in the top bar.
> 
> Argh, correcting myself, looks like that link is wrong and still points to `janus` and not `janus-legacy`! I'll have to fix that...

Fixed in https://github.com/meetecho/janus-gateway/pull/2211/commits/b12228f1d36608684ca60d2fdc7512083e54be8d

**Comment by lminiero** [comment]
As you may have noticed, we have merged the multistream branch and, as promised, the 0.x branch is live as well. For some more info, you cah check this blog post I wrote: https://www.meetecho.com/blog/multistream/

**Comment by Charles92011** [comment]
Did you release the multistream branch on docker hub?

**Comment by elhananjair** [comment]
@lminiero, please I couldn't find a way to build janus on Fedora, I was trying to use docker for that but all are outdated only implementing janus 0.x.

**Comment by lminiero** [comment]
I use fedora ever day and it compiles just fine for me. Please ask questions like this on the meetecho-janus group, not here.

**Comment by Charles92011** [comment]
> @lminiero, please I couldn't find a way to build janus on Fedora, I was trying to use docker for that but all are outdated only implementing janus 0.x.

I forked the canyan docker instance and updated the Janus version to 1.x:
https://github.com/Charles92011/janus-gateway-docker

Repost your question in the google group and I'll reply with the docker compose file
https://groups.google.com/g/meetecho-janus

**Comment by lminiero** [comment]
I tinnk we can close this now: the difference between `0.x` and `1.x` should be known to most, and it's highlighted in the README and demos website.
