### ISSUE TITLE
Get viewers by participants in video-room api janus

### ISSUE THREAD

**Issue by rprata** [meetecho/janus-gateway#2856]
In [Janus video room api](https://janus.conf.meetecho.com/docs/videoroom), is is possible `listParticipants`. So, each participant has this fields:

```
        "participants" : [              // Array of participant objects
                {       // Participant #1
                        "id" : <unique numeric ID of the participant>,
                        "display" : "<display name of the participant, if any; optional>",
                        "publisher" : "<true|false, whether user is an active publisher in the room>",
                        "talking" : <true|false, whether user is talking or not (only if audio levels are used)>
                },
...
```

Is it possible add a field with number of `subscribers` and information about these subscribers:  [`viewers`], `num_viewers`? It will help us to get more information about participant in api.

**Comment by lminiero** [comment]
I guess it could be done, since IIRC we do return that information when using the Admin API to query a publisher.

**Comment by lminiero** [comment]
Note that I'm _only_ talking about the number of viewers, _not_ info on the individual viewers here. If you want that information, you should rely on other approaches like event handlers instead.

**Comment by rprata** [comment]
Ok. However if `number of viewers` was returned by this API could be easier to handle stream life cycle. However, I tried to use event handlers to get this information, but I couldn't not. Please, could me send a tutorial or docs about this approache?
