### ISSUE TITLE
Help me please - Failed to start JANUS Server

### ISSUE THREAD

**Issue by chegmarco1989** [meetecho/janus-gateway#2859]
**Hello.

I am facing a serious problem when I try to start the Janus Server on my dedicated Ubuntu Server on which I myself have successfully installed Janus following of course the [this Tutorial](https://facsiaginsa.com/janus/install-janus-webrtc-server-on-ubuntu), through the command `service janus start` and `service janus status`, I get the following errors:**

> root@host:~# service janus status
> ● janus.service - Janus WebRTC Server
>      Loaded: loaded (/etc/systemd/system/janus.service; disabled; vendor preset: enabled)
>      Active: failed (Result: exit-code) since Sat 2022-01-22 02:05:20 UTC; 22min ago
>     Process: 64436 ExecStart=/usr/bin/sudo /opt/janus/bin/janus (code=exited, status=1/FAILURE)
>    Main PID: 64436 (code=exited, status=1/FAILURE)
> 
> Jan 22 02:05:20 host.worklx.com systemd[1]: Started Janus WebRTC Server.
> Jan 22 02:05:20 host.worklx.com sudo[64436]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/janus/bin>
> Jan 22 02:05:20 host.worklx.com sudo[64436]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jan 22 02:05:20 host.worklx.com sudo[64453]: Janus commit: 71d9373116d1ef0547487de8afed3caa78c45407
> Jan 22 02:05:20 host.worklx.com sudo[64453]: Compiled on:  Wed Jan 19 09:19:28 UTC 2022
> Jan 22 02:05:20 host.worklx.com sudo[64453]: Error opening log file /var/log/janus/janus.log: No such file or di>
> Jan 22 02:05:20 host.worklx.com sudo[64436]: pam_unix(sudo:session): session closed for user root
> Jan 22 02:05:20 host.worklx.com systemd[1]: janus.service: Main process exited, code=exited, status=1/FAILURE
> Jan 22 02:05:20 host.worklx.com systemd[1]: janus.service: Failed with result 'exit-code'.
> lines 1-15/15 (END) 

**Indeed, when, I do: `journalctl -u janus` to check for Logs errors, I get the following return:**

> -- Logs begin at Wed 2022-01-19 08:31:57 UTC, end at Sat 2022-01-22 02:12:56 UTC. --
> Jan 19 09:21:47 host.worklx.com systemd[1]: Started Janus WebRTC Server.
> Jan 19 09:21:47 host.worklx.com sudo[116514]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/janus/bi>
> Jan 19 09:21:47 host.worklx.com sudo[116514]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Janus commit: 71d9373116d1ef0547487de8afed3caa78c45407
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Compiled on:  Wed Jan 19 09:19:28 UTC 2022
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Logger plugins folder: /opt/janus/lib/janus/loggers
> Jan 19 09:21:47 host.worklx.com sudo[116515]: [WARN]         Couldn't access logger plugins folder...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: ---------------------------------------------------
> Jan 19 09:21:47 host.worklx.com sudo[116515]:   Starting Meetecho Janus (WebRTC Server) v0.11.7
> Jan 19 09:21:47 host.worklx.com sudo[116515]: ---------------------------------------------------
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Checking command line arguments...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Debug/log level is 4
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Debug/log timestamps are disabled
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Debug/log colors are enabled
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Adding 'vmnet' to the ICE ignore list...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Using 159.65.90.131 as local IP...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Token based authentication disabled
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Initializing recorder code
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, ha>
> Jan 19 09:21:47 host.worklx.com sudo[116515]: TURN REST API backend: (disabled)
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Crypto: OpenSSL >= 1.1.0
> Jan 19 09:21:47 host.worklx.com sudo[116515]: No cert/key specified, autogenerating some...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Fingerprint of our certificate: 79:29:59:CD:75:22:F8:4B:47:69:50:D>
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Event handlers support disabled
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Plugins folder: /opt/janus/lib/janus/plugins
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Sessions watchdog started
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_audiobridge.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS AudioBridge plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_videocall.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS VideoCall plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_videoroom.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS VideoRoom plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_echotest.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS EchoTest plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_recordplay.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS Record&Play plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_streaming.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Joining Janus requests handler thread
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS Streaming plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_nosip.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS NoSIP plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_voicemail.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS VoiceMail plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_textroom.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS TextRoom plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading plugin 'libjanus_sip.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS SIP plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Transport plugins folder: /opt/janus/lib/janus/transports
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading transport plugin 'libjanus_http.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: HTTP webserver started (port 8088, /janus path listener)...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS REST (HTTP/HTTPS) transport plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading transport plugin 'libjanus_websockets.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: [WARN] libwebsockets has been built without IPv6 support, will bin>
> Jan 19 09:21:47 host.worklx.com sudo[116515]: libwebsockets logging: 0
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Websockets server started (port 8188)...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: JANUS WebSockets transport plugin initialized!
> Jan 19 09:21:47 host.worklx.com sudo[116515]: Loading transport plugin 'libjanus_pfunix.so'...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: [WARN] No Unix Sockets server started, giving up...
> Jan 19 09:21:47 host.worklx.com sudo[116515]: [WARN] The 'janus.transport.pfunix' plugin could not be initialized
> Jan 19 09:21:47 host.worklx.com sudo[116515]: WebSockets thread started
> Jan 19 09:21:47 host.worklx.com sudo[116515]: HTTP transport timer started
> Jan 19 12:31:00 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 13:01:45 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 13:02:24 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 13:02:36 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 13:02:48 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 13:02:49 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 13:02:51 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 14:32:15 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 14:36:56 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 16:11:08 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 16:50:26 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 16:56:40 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 18:31:23 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 19:27:16 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 20:11:25 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 20:38:56 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 23:23:10 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 19 23:42:58 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 01:06:05 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 02:47:17 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 02:58:02 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 03:06:17 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 04:54:35 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 05:04:01 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 05:57:09 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 07:42:10 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 08:20:16 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 09:47:46 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 09:48:08 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 09:48:08 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 09:48:08 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 09:48:09 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 09:48:12 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 10:55:01 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 11:23:52 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 12:54:17 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 14:23:14 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 17:19:49 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 17:19:49 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 17:19:50 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 17:19:50 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 17:26:49 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 19:22:53 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 19:24:28 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 19:40:19 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 22:50:56 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 22:50:57 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 20 23:16:22 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 01:15:32 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 02:09:33 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 03:36:52 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 03:46:06 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 04:32:34 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 04:39:05 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 06:13:44 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 08:24:26 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 09:01:16 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 09:13:22 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 10:25:55 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 10:33:16 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 11:49:46 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 12:00:07 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 13:46:07 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 16:08:04 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 17:35:53 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 18:58:37 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 18:58:38 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 19:40:32 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 20:12:42 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 20:16:48 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 21:04:42 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 21:04:52 host.worklx.com sudo[116515]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid ur>
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Stopping server, please wait...
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Ending sessions timeout watchdog...
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Sessions watchdog stopped
> Jan 21 22:29:14 host.worklx.com sudo[116515]: In a hurry? I'm trying to free resources cleanly, here!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Closing transport plugins:
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Stopping webserver(s)...
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS REST (HTTP/HTTPS) transport plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: WebSockets thread ended
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS WebSockets transport plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Ending requests thread...
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Leaving Janus requests handler thread
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Destroying sessions...
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Freeing crypto resources...
> Jan 21 22:29:14 host.worklx.com sudo[116515]: De-initializing SCTP...
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Closing plugins:
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS AudioBridge plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS Record&Play plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS VideoRoom plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS TextRoom plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS VoiceMail plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS NoSIP plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS VideoCall plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS SIP plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS EchoTest plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: JANUS Streaming plugin destroyed!
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Closing event handlers:
> Jan 21 22:29:14 host.worklx.com sudo[116515]: Bye!
> Jan 21 22:29:13 host.worklx.com systemd[1]: Stopping Janus WebRTC Server...
> Jan 21 22:29:14 host.worklx.com systemd[1]: janus.service: Succeeded.
> Jan 21 22:29:14 host.worklx.com systemd[1]: Stopped Janus WebRTC Server.
> -- Reboot --
> Jan 22 02:03:50 host.worklx.com systemd[1]: Started Janus WebRTC Server.
> Jan 22 02:03:50 host.worklx.com sudo[62980]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/janus/bin>
> Jan 22 02:03:50 host.worklx.com sudo[62980]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jan 22 02:03:50 host.worklx.com sudo[62997]: Janus commit: 71d9373116d1ef0547487de8afed3caa78c45407
> Jan 22 02:03:50 host.worklx.com sudo[62997]: Compiled on:  Wed Jan 19 09:19:28 UTC 2022
> Jan 22 02:03:50 host.worklx.com sudo[62997]: Error opening log file /var/log/janus/janus.log: No such file or di>
> Jan 22 02:03:50 host.worklx.com sudo[62980]: pam_unix(sudo:session): session closed for user root
> Jan 22 02:03:50 host.worklx.com systemd[1]: janus.service: Main process exited, code=exited, status=1/FAILURE
> Jan 22 02:03:50 host.worklx.com systemd[1]: janus.service: Failed with result 'exit-code'.
> Jan 22 02:03:56 host.worklx.com systemd[1]: Started Janus WebRTC Server.
> Jan 22 02:03:56 host.worklx.com sudo[63010]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/janus/bin>
> Jan 22 02:03:56 host.worklx.com sudo[63010]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jan 22 02:03:56 host.worklx.com sudo[63024]: Janus commit: 71d9373116d1ef0547487de8afed3caa78c45407
> Jan 22 02:03:56 host.worklx.com sudo[63024]: Compiled on:  Wed Jan 19 09:19:28 UTC 2022
> Jan 22 02:03:56 host.worklx.com sudo[63024]: Error opening log file /var/log/janus/janus.log: No such file or di>
> Jan 22 02:03:56 host.worklx.com sudo[63010]: pam_unix(sudo:session): session closed for user root
> Jan 22 02:03:56 host.worklx.com systemd[1]: janus.service: Main process exited, code=exited, status=1/FAILURE
> Jan 22 02:03:56 host.worklx.com systemd[1]: janus.service: Failed with result 'exit-code'.
> Jan 22 02:05:20 host.worklx.com systemd[1]: Started Janus WebRTC Server.
> Jan 22 02:05:20 host.worklx.com sudo[64436]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/opt/janus/bin>
> Jan 22 02:05:20 host.worklx.com sudo[64436]: pam_unix(sudo:session): session opened for user root by (uid=0)
> Jan 22 02:05:20 host.worklx.com sudo[64453]: Janus commit: 71d9373116d1ef0547487de8afed3caa78c45407
> Jan 22 02:05:20 host.worklx.com sudo[64453]: Compiled on:  Wed Jan 19 09:19:28 UTC 2022
> Jan 22 02:05:20 host.worklx.com sudo[64453]: Error opening log file /var/log/janus/janus.log: No such file or di>
> Jan 22 02:05:20 host.worklx.com sudo[64436]: pam_unix(sudo:session): session closed for user root
> Jan 22 02:05:20 host.worklx.com systemd[1]: janus.service: Main process exited, code=exited, status=1/FAILURE
> Jan 22 02:05:20 host.worklx.com systemd[1]: janus.service: Failed with result 'exit-code'.
> lines 156-192/192 (END)

**I really need your help please.**

**Comment by lminiero** [comment]
Please refer to the [group](https://groups.google.com/g/meetecho-janus) for questions like this, as explained in the guidelines we only use GitHub for tracking bugs in Janus.
