### ISSUE TITLE
[0.x] default_bitrate documented as having default=auto but that is not an integer

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#2863]
At #2802 configuration option default_bitrate is introduced, but it seems the documentation is off at some places:

E.g. this was added to <conf/janus.plugin.audiobridge.jcfg.sample>:
```
# default_bitrate = default bitrate in bps to use for the all participants (default=auto, libopus decides; automatically used for forwarders too)
```

But this was added to <conf/janus.plugin.audiobridge.jcfg.sample>
```
{"default_bitrate", JSON_INTEGER, JANUS_JSON_PARAM_POSITIVE},
```

Seems to me the documented default should be changed to `0`.

**Comment by lminiero** [comment]
Good point, thanks for spotting this! I'll fix this right way :+1:
