### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by getarun** [meetecho/janus-gateway#2866]
Hello everyone,

thank you for developing janus - it has been fun to work with it.
Some time ago, I deployed a janus instance at version 11.4 (pulled from master - commit dca2068beb8df3aaed64cb6f91ffce6078d75f61). It works fine, but now I am eager to update the version to the 11.7 tag (11.7 - commit 99d198cdadc6e9586a953367d376fcd7c52e67d2). This did not work (chooseDefaultDependencies not a function), so I decided to deploy a 11.4 again, but this time as tagged release (11.4 - commit 4f8cc1624955488640107537be037f9ba7112c14). Now I get the same same error as with the updated version. Because I did not change the interacting code that imports janus.es.js & the janus instance answers on its admin interface, I suspect an module installation issue.

Question: Are modules only valid for a certain commit or are they valid for a version range? Since I found (and tried) two JS modules
- /home/username/janus-gateway/npm/bundles/janus.es.js
- /opt/janus/share/janus/javascript/janus.es.js
I wonder which one I should use.

I installed janus on a "bare metal" droplet (Ubuntu 20.04). Would you suggest trying a installation via package manager? If I choose to go this way - where do I find matching modules to use in code?

Have a nice day :)

**Comment by getarun** [comment]
Installation sumup:
```
sudo apt  install libmicrohttpd-dev libjansson-dev \
        libssl-dev libsrtp2-dev libsofia-sip-ua-dev libglib2.0-dev \
        libopus-dev libogg-dev libcurl4-openssl-dev liblua5.3-dev \
        libconfig-dev pkg-config gengetopt libtool automake
```
#enable websocket support
```
apt install libwebsockets-dev
```
#compile libnice yourself, distro version may cause issues
```
sudo apt install meson python3 ninja-build
git clone https://gitlab.freedesktop.org/libnice/libnice
cd libnice
meson --prefix=/usr build && ninja -C build && sudo ninja -C build install
```
Finally install janus from source (without optional stuff)
```
apt install make
git clone https://github.com/meetecho/janus-gateway.git
cd janus-gateway
sh autogen.sh
export PKG_CONFIG_PATH="/usr/lib64/pkgconfig"
./configure --prefix=/opt/janus --enable-all-js-modules 

make
make install
```

**Comment by RSATom** [comment]
1. This sort question is for group: https://groups.google.com/g/meetecho-janus
2. You can just use https://snapcraft.io/janus-gateway

**Comment by getarun** [comment]
:) Thank for for the replay. I, will try and repost if needed.

**Comment by RSATom** [comment]
I would recommend you close this issue or Lorenzo will be angry :)

**Comment by getarun** [comment]
Better start the day with good mood :)

**Comment by lminiero** [comment]
> I would recommend you close this issue or Lorenzo will be angry :)

Is that how people are thinking of me now? :stuck_out_tongue_closed_eyes: 
That said, yes, question so it belongs to the group, but that said I don't know why/how you opened an issue without using our new templates?

**Comment by RSATom** [comment]
> Is that how people are thinking of me now? :stuck_out_tongue_closed_eyes:

I'm afraid yes 😉 I'm even fear answer you... :rofl:

**Comment by deanelwood** [comment]
It’s why I keep quiet in the corner and never reply :p

**Comment by lminiero** [comment]
I've made some changes to the issues template page, hopefully this will reduce the confusion in the future.
