### ISSUE TITLE
[master] fatal error: 'stun/usages/bind.h' file not found

### ISSUE THREAD

**Issue by albirrkarim** [meetecho/janus-gateway#2870]
First i dont know the version of janus i use. i just download it this day. im sorry im very new in web rtc

My device:
Macbook air M1
Mac OS 12.1

After install all dependency with brew based on [this](https://anilwadghule.com/2019/10/04/how-to-install-janus-webrtc-server-on-macos/) 

im runing `./configure --prefix=/opt/janus` and it work, after that i run `make` and got this error.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/29292018/152312790-b5ead222-ba55-4a8e-8ce4-869ad6c81616.png">

`which git` rev-parse HEAD | awk 'BEGIN {print "#include \"version.h\""} {print "const char *janus_build_git_sha = \"" $0"\";"} END {}' > version.c
echo "Thu Feb  3 16:02:37 WIB 2022" | awk 'BEGIN {} {print "const char *janus_build_git_time = \""$0"\";"} END {} ' >> version.c
echo "118" | awk 'BEGIN {} {print "int janus_version = "$0";"} END {} ' >> version.c
echo "0.11.8" | awk 'BEGIN {} {print "const char *janus_version_string = \""$0"\";"} END {} ' >> version.c
PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig" "/opt/homebrew/bin/pkg-config" --modversion nice | awk 'BEGIN {} {print "const char *libnice_version_string = \""$0"\";"} END {} ' >> version.c
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in html
make[2]: Nothing to be done for `all'.
  CC       janus-ice.o
warning: unknown warning option '-Wunsafe-loop-optimizations' [-Wunknown-warning-option]
warning: unknown warning option '-Wunused-but-set-variable'; did you mean '-Wunused-const-variable'? [-Wunknown-warning-option]
ice.c:24:10: fatal error: 'stun/usages/bind.h' file not found
#include <stun/usages/bind.h>
         ^~~~~~~~~~~~~~~~~~~~
2 warnings and 1 error generated.
make[2]: *** [janus-ice.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by lminiero** [comment]
Compilation problem, not a code issue, so this belongs to the [group](https://groups.google.com/g/meetecho-janus). Closing.
PS: next time, if you use one of the templates, don't change the title of the prefix. You chose multistream, and then said master, which led to broken labels.
