### ISSUE TITLE
[0.x] Different port in Contact header/VIA when using TLS

### ISSUE THREAD

**Issue by tijmenNL** [meetecho/janus-gateway#2871]
**What version of Janus is this happening on?**
0.11.7

**Was this working before?**
No on 0.11.6 it does the same

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
During the testing of #2868 I noticed incoming calls stop after 30s. This only happens when you use TLS as transport to the SIP proxy (`proxy: sips:IP:PORT`).

The call is stopped because a missing ACK on the 200OK. This happens because the contact header contains a different port then the VIA header in the initial REGISTER:

```
REGISTER sips:81.23.228.129:5061 SIP/2.0
Via: SIP/2.0/TLS 85.17.186.26:37027;branch=z9hG4bK4HcHBKtX6eeUe
...
Contact: <sip:tijmen@85.17.186.26:32947;transport=tcp>
```
Also when not using force_tcp:
```
REGISTER sips:81.23.228.129:5061 SIP/2.0
Via: SIP/2.0/TLS 85.17.186.26:37549;branch=z9hG4bKZNFyrDQeQte7c
...
Contact: <sip:tijmen@85.17.186.26:45283;transport=udp>
```
In case of just TCP:
```
REGISTER sip:85.17.186.23;transport=tcp SIP/2.0
Via: SIP/2.0/TCP 85.17.186.26:47482;branch=z9hG4bKy1B5Sj23gSyrj
...
Contact: <sip:tijmen@85.17.186.26:47482>
```

**Comment by tijmenNL** [comment]
To give a bit more info, it may not be a problem that the headers are different. 

But in case of an ACK the request URI is used for the last hop to route the packet (proxy->UA). The request URI  is the contact from the register request. 

This fails, since I think the contact port is wrong and nobody is listening there. At least I get send timeout on the proxy and I see nothing arriving on Sofia.

**Comment by lminiero** [comment]
My guess is that since you're using a proxy, all dialogs are supposed to be sent/received over that connection? Not sure what the impact of `NUTAG_REGISTRAR` is in Sofia.

The contact header reminds me of #2439, which again was only an issue for newer versions of Sofia, and causing the contact header not to be added at all, which is why we created a workaround in #2708. You may want to try and force the workaround to trigger in your case as well, just to check if manually overriding the contact header helps.

If not, this may be a weird way Sofia handles this scenario internally, and I can't help there. Pulling a recent version of Sofia may be worth trying, just to check if the FreeSWITCH developers addressed this problem.

**Comment by tijmenNL** [comment]
I checked it some more and if you send the register over TLS to the sip proxy, the contact really needs to have transport=tls and the _actual_ port Sofia is listening. It makes no sense to send your register over TLS and then also listen on UDP, or TCP for incoming connections.

Also we use a public IP in the sip plugin. Where//why it goes wrong here is the following:
- The INVITE reaches sofia OK over TLS which was used to register
- Sofia replies 200OK with the contact:port with or without transport=tcp
- The ACK is send by the proxy over TLS to the port in the contact. The transport is not considered. Since the contact on the 200OK has a public IP it is not fixed/rewritten by the proxy with the actual IP:PORT from where it is received. So the consequence is that the packet is being sent using TLS to a TCP port where Sofia is listening. And this does not work.

So to solve this I can either add a work around in the proxy to fix the contact, or see if we can make Sofia use a contact header with the right port and transport=tls if either the proxy or outbound proxy uses TLS.

**Comment by lminiero** [comment]
Or maybe `outbound_proxy` should be used instead of `outbound`? That way the same connection for the original register is definitely always used, IIRC.

**Comment by tijmenNL** [comment]
I tried that and it does not change a thing. The contact still contains a different port than the TLS connection:
```
tport_listen(0x7f81100067d0): listening at udp/85.17.186.26:34701/sip
tport_listen(0x7f8110006d10): listening at tcp/85.17.186.26:34701/sip
tport_listen(0x7f8110007570): listening at tls/85.17.186.26:46865/sips
...
nta: agent_init_via: SIP/2.0/udp 85.17.186.26:34701 (sip)
nta: agent_init_via: SIP/2.0/tcp 85.17.186.26:34701 (sip)
nta: agent_init_via: SIP/2.0/tls 85.17.186.26:46865 (sips)
...
REGISTER sip:sip2sip.info SIP/2.0
Via: SIP/2.0/TLS 85.17.186.26:46865;branch=z9hG4bK4B3B1vt8yDFNp
...
Contact: <sip:tijmen@85.17.186.26:34701>
```
So I will check if can come up with a patch to fix it

**Comment by Si-Richards** [comment]
> I checked it some more and if you send the register over TLS to the sip proxy, the contact really needs to have transport=tls and the _actual_ port Sofia is listening on for TLS. It makes no sense to send your register over TLS and then also listen on UDP, or TCP for incoming connections.
> 
> Also we use a public IP in the sip plugin. Where//why it goes wrong here is the following:
> 
> * The INVITE reaches sofia OK over TLS which was used to register
> * Sofia replies 200OK with the contact:port with or without transport=tcp
> * The ACK is send by the proxy over TLS to the port in the contact. The transport is not considered. Since the contact on the 200OK has a public IP it is not fixed/rewritten by the proxy with the actual IP:PORT from where it is received. So the consequence is that the packet is being sent using TLS to a TCP port where Sofia is listening. And this does not work.
> 
> So to solve this I can either add a work around in the proxy to fix the contact, or see if we can make Sofia use a contact header with the right port and transport=tls if either the proxy or outbound proxy uses TLS.

Can you share exactly your TLS workaround ?

**Comment by tijmenNL** [comment]
I haven't had time yet  to do more extensive testing and/or adding a fix our proxies.  We don't actually use TLS now, only TCP.

I can't tell you a workaround, since it depends on which proxy server software you are using.

**Comment by lminiero** [comment]
Is this still a problem that should be fixed in Janus, or something the Sofia library is doing wrong? Not sure what the outcome of the discussion was. I feel like it's the latter?

**Comment by lminiero** [comment]
Thanks for the feedback, I'll wait for more info in the future then!
