### ISSUE TITLE
[0.x] Detected memory leak

### ISSUE THREAD

**Issue by dnish** [meetecho/janus-gateway#2876]
**What version of Janus is this happening on?**
Current GIT master

**Have you tested a more recent version of Janus too?**
No, only older

**Was this working before?**
The error didn't occur on the fixes before

**Is there a gdb or libasan trace of the issue?**
https://pastebin.com/q5ZF0Q3C

Hey,
I've installed the latest master of Janus. Seems that the other errors got fixed, now I get a memory leak warning / crash (see Pastebin link above).

**Comment by lminiero** [comment]
Looks like you pressed CTRL+C more than once to speed up closing Janus, so you didn't give it time to clear resources. As such, I don't think those can be considered leaks. If you feel there's a leak instead, then enable refcount debugging by uncommenting the `REFCOUNT_DEBUG` define in `refcount.h`, recompile, and clean Janus _cleanly_: make sure all sessions are closed, and then only hit CTRL+C once, and wait for Janus to quit, which will print a refcount summary at the end.

**Comment by lminiero** [comment]
@dnish any update?

**Comment by lminiero** [comment]
Closing.

**Comment by dnish** [comment]
@lminiero Yeah this could be the issue, I'll test it again when we upgrade again to the latest commit.
