### ISSUE TITLE
[1.x] Simulcast inactive layer (~ syntax) is not being recognized by Janus and ~ is not returned in the answer

### ISSUE THREAD

**Issue by digitalsamba** [meetecho/janus-gateway#2879]
Simulcast supports sending inactive layer through addTransceiver method. 
```
[
    { rid: 'h', active: false, maxBitrate: bitrates.high },
    ....................
]
```

This is translated to the tilde syntax (~) in the SDP: **a=simulcast:send ~h;m;l**
Currently Janus SDP answer is: **a=simulcast:recv h;m;l**, which unfortunately reenables the simulcast layer.

Expected behaviour of the answer should be: **a=simulcast:recv ~h;m;l**

Currently the workaround is to hack the SDP answer locally in the browser to add the ~ sign.
Other hack is to call **.active = false** on the layer again after the answer.

The tilde (~) syntax is explained in https://datatracker.ietf.org/doc/html/rfc8853

**Comment by lminiero** [comment]
Looks like the SDP parser in Janus filters the tilde out automatically: even when `~h` is in the offer, `h` is what we parse and return. Which is fine on one end (we do want that to be the rid name we're aware of), but it's weird as I would have assumed Janus would have incorrectly thought `~h` was the name. I'll have a look at the code to see why that is, and then think of a way to keep the state of substreams as offered.

**Comment by lminiero** [comment]
Checked the code, and when we receive the simulcast/rid info via SDP:

	a=rid:h send
	a=rid:m send
	a=rid:l send
	a=simulcast:send ~h;m;l

we only parse the `rid` attributes, and ignore the `simulcast` one. This explains why the rid names we're aware of are correct (no tilde there). We'll have to parse the `simulcast` attribute too to be aware of which substream is disabled.

**Comment by lminiero** [comment]
Please test the PR above: it seems to be working as expected for me.

**Comment by digitalsamba** [comment]
@lminiero  - Just tested it, seems to work fine :) We removed the manual replace hack.

**Comment by lminiero** [comment]
Ack, thanks! I'll merge then, and backport to `0.x` as well.
