### ISSUE TITLE
can rtp_forwarder launch a program?

### ISSUE THREAD

**Issue by paleozogt** [meetecho/janus-gateway#288]
The new ```rtp_forwarder``` feature by @Computician  in #255 is pretty darn useful, but it could be more useful.

It reminds me of the [exec_push](https://github.com/arut/nginx-rtmp-module/wiki/Directives#exec_push) feature of [nginx-rtmp-module](https://github.com/arut/nginx-rtmp-module).  Whenever a recording starts, it launches a program you specify, which can do whatever it wants with the stream (transcoding, etc).

**Comment by lminiero** [comment]
See #153, nice idea but not planned for now.
