### ISSUE TITLE
[1.x] Compilation on openSUSE 15.3 fails: `transports/transports_libjanus_websockets_la-janus_websockets.lo`

### ISSUE THREAD

**Issue by tacerus** [meetecho/janus-gateway#2884]
**What version of Janus is this happening on?**
```
const char *janus_build_git_sha = "4792a7391508855c8af4183a9c264e0a6a887bbb";
const char *janus_build_git_time = "Mon 14 Feb 2022 01:45:05 PM CET";
int janus_version = 1000;
const char *janus_version_string = "1.0.0";
const char *libnice_version_string = "0.1.14";
```

**Have you tested a more recent version of Janus too?**
Latest Git master, there is nothing newer.

**Was this working before?**
No, compilation with 0.x failed as well, albeit with a different error. Assuming it makes more sense to track the 1.x one.

**Is there a gdb or libasan trace of the issue?**
n/a

**Additional context**
Hi,
thanks for the nice software!

I am trying to compile it on openSUSE 15.3 but encounter some compiler warnings which cause the process to error out:

Build environment:
Make: GNU Make 4.2.1
GCC: gcc version 7.5.0
Target: x86_64-suse-linux

Configure command line:
`./configure --prefix=/usr/local --enable-plugin-lua --enable-plugin-duktape --enable-post-processing`

Make snippet:
```
transports/janus_websockets.c: In function ‘janus_websockets_common_callback’:
transports/janus_websockets.c:1243:37: warning: variable ‘methods’ set but not used [-Wunused-but-set-variable]
     char origin[256], headers[256], methods[256];
                                     ^~~~~~~
transports/janus_websockets.c:1412:17: error: implicit declaration of function ‘lws_write_ws_flags’; did you mean ‘BN_with_flags’? [-Werror=implicit-function-declaration]
     int flags = lws_write_ws_flags(LWS_WRITE_TEXT, ws_client->bufoffset == LWS_PRE, ws_client->bufpending <= (size_t)amount);
                 ^~~~~~~~~~~~~~~~~~
                 BN_with_flags
transports/janus_websockets.c:1412:17: warning: nested extern declaration of ‘lws_write_ws_flags’ [-Wnested-externs]
  CCLD     transports/libjanus_nanomsg.la
cc1: some warnings being treated as errors
make[2]: *** [Makefile:2284: transports/transports_libjanus_websockets_la-janus_websockets.lo] Error 1
```

The non-truncated configure and make outputs may be found here:
https://hugz.io/tdadsd/configure.txt
https://hugz.io/hf6sn/make.txt

Additionally, the generated Makefile might be of relevance:
https://hugz.io/yy2tx6/Makefile.txt

The build finishes if `-Werror=implicit-function-declaration` is removed from the Makefile's `CFLAGS`:

```
...
transports/janus_websockets.c: In function ‘janus_websockets_common_callback’:                                                           
transports/janus_websockets.c:1243:37: warning: variable ‘methods’ set but not used [-Wunused-but-set-variable]                          
     char origin[256], headers[256], methods[256];                                                                                       
                                     ^~~~~~~                                                                                             
transports/janus_websockets.c:1412:17: warning: implicit declaration of function ‘lws_write_ws_flags’; did you mean ‘BN_with_flags’? [-Wi
mplicit-function-declaration]                                                                                                            
     int flags = lws_write_ws_flags(LWS_WRITE_TEXT, ws_client->bufoffset == LWS_PRE, ws_client->bufpending <= (size_t)amount);           
                 ^~~~~~~~~~~~~~~~~~                                                                                                      
                 BN_with_flags                                                                                                           
transports/janus_websockets.c:1412:17: warning: nested extern declaration of ‘lws_write_ws_flags’ [-Wnested-externs]                     
  CCLD     transports/libjanus_websockets.la                                                                                             
make[2]: Leaving directory '/home/georg/janus-gateway'                                                                                   
make[1]: Leaving directory '/home/georg/janus-gateway' 

$ janus --version
Janus commit: 4792a7391508855c8af4183a9c264e0a6a887bbb
Compiled on:  Mon 14 Feb 2022 02:01:49 PM CET

janus 1.0.0
```

Happy to provide more details if needed.

**Comment by atoppi** [comment]
sounds like https://github.com/meetecho/janus-gateway/issues/2654

**Comment by tacerus** [comment]
Thank you very much! I missed that one upon searching through the issues.

Removing the packaged libwebsockets 2.4.0 and compiling/installing libwebsockets v4.3-stable solves this issue.

**Comment by tacerus** [comment]
Or so I thought, starting `janus` results in:

`Couldn't load transport plugin 'libjanus_websockets.so': libwebsockets.so.19: cannot open shared object file: No such file or directory`

GIven that it detected it during `configure` (I re-run it after replacing the installed `libwebsockets`), should it not detect it just as well during runtime?

```
$ locate libwebsockets.so
...
/usr/local/lib/libwebsockets.so
/usr/local/lib/libwebsockets.so.19
```

**Comment by lminiero** [comment]
Configure and runtime are different beasts. If your system is not configured to look for libraries in /usr/local/lib, either preload the library or update LD_LIBRARY_PATH.

**Comment by tacerus** [comment]
Thank you very much - I forgot to run `ldconfig` - my bad!
