### ISSUE TITLE
Janus 100% CPU load when compiled against libnice GIT HEAD and using streaming plugin

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#289]
See also this thread: https://groups.google.com/forum/#!topic/meetecho-janus/3bmcHYJL_WU
The problem is definitely ICE related (and not directly related to the fact that we are using the streaming plugin), see this HTOP screenshot: http://imgur.com/Yh3WX4A

Problem is solved when using libnice-dev package from the standard (ubuntu 14.04 x64) repository and recompiling janus (we are using GIT HEAD, modular-transports branch).

**Comment by ploxiln** [comment]
probably related to #154

**Comment by lminiero** [comment]
I agree with @ploxiln, closing as a duplicate.

**Comment by kolmanv** [comment]
@arjenveenhuizen 
Sorry for unrelated question, but how can I compile Janus (or what should I do) in order to see the different threads as you showed in HTOP screenshot?

**Comment by ploxiln** [comment]
That's an htop option. Press F2 to enter setup, go down to "Display options", go right and toggle "Hide userland threads" off and "Display threads in a different color" on. You may also want to turn Tree view on with F5.

Looks like this only works on linux, and not in the ported old version of htop for OS X available from homebrew.

**Comment by kolmanv** [comment]
Awesome, works, thanks Pierce this is very helpfull!
