### ISSUE TITLE
[1.x] Janus does not relay FIR requests

### ISSUE THREAD

**Issue by gdesmott** [meetecho/janus-gateway#2891]
I have one (GStreamer) app sending video to another through Janus. The sender is dropping 10% of its packets to simulate a poor network connectivity. The receiver is configured to request keyframe when required.
When needed the receiver is sending FIR requests to Janus but those requests do not seem to be relayed by Janus in the sender stream.

This should work or am I missing something here?

**What version of Janus is this happening on?**
`master`

**Comment by lminiero** [comment]
You're not saying which plugin this is.

**Comment by gdesmott** [comment]
Right sorry. This is with the videoroom plugin.

**Comment by lminiero** [comment]
If the VideoRoom received a PLI or FIR from a subscriber, a PLI (never a FIR) is sent to the publisher.

**Comment by gdesmott** [comment]
I observed PLI sent from Janus indeed. So FIR from subscriber are converted to PLI?
What's the rationale for not sending the FIR instead?

**Comment by lminiero** [comment]
Browsers don't use FIR.

**Comment by gdesmott** [comment]
That makes sense, thanks. Closing this as I received those PLI so it seems things are working as intended.
