### ISSUE TITLE
[1.x] Warnings when receiving SR on RTX stream

### ISSUE THREAD

**Issue by gdesmott** [meetecho/janus-gateway#2892]
When doing RTX, GStreamer is sending SR to both streams, the original and RTX one, as [stated in the spec](https://datatracker.ietf.org/doc/html/rfc4588#section-6.1). But by doing so it raises such warnings in Janus:

`[WARN] Incoming RTCP SR SSRC (2890932452) does not match the expected one (2698731040) video=1`

Looking at my gst logs I found that `2890932452` is the RTX stream while `2698731040` is the original one:

```
rtpsource rtpsource.c:1556:rtp_source_get_new_sr: no clock-rate, getting for pt 97 and SSRC 2890932452
rtpbin gstrtpbin.c:988:get_pt_map: caching pt 97 as application/x-rtp, media=(string)video, payload=(int)97, clock-rate=(int)90000, encoding-name=(string)RTX, apt=(string)96
```

```
rtpsource rtpsource.c:1556:rtp_source_get_new_sr: no clock-rate, getting for pt 96 and SSRC 2698731040
rtpbin gstrtpbin.c:988:get_pt_map: caching pt 96 as application/x-rtp, media=(string)video, payload=(int)96, clock-rate=(int)90000, encoding-name=(string)H264, packetization-mode=(string)1, sprop-parameter-sets=(string)"Z0LAH9kAUAW7AWoCAgKAAAADAIAAAB5HjBkk\,aMuMsg\=\=", profile=(string)constrained-baseline, rtcp-fb-ccm-fir=(boolean)true, rtcp-fb-nack=(boolean)true, rtcp-fb-nack-pli=(boolean)true, rtcp-fb-goog-remb=(boolean)true, rtcp-fb-transport-cc=(boolean)true
```

Shouldn't Janus handle those SR, or at the very least silently ignore them instead of raising such warnings?

**What version of Janus is this happening on?**
`master`

**Comment by lminiero** [comment]
> Shouldn't Janus handle those SR, or at the very least silently ignore them instead of raising such warnings?

Yes, silently ignoring them would be good. We'll fix this later.

**Comment by gdesmott** [comment]
The phrasing "does not match the expected one" can still make users think that sender is sending something wrong to the server. Wouldn't be best to remove this log all together if the SR is from the RTX stream?

**Comment by lminiero** [comment]
That's harder to enforce since the "expected" RTCP may be the local or remote one, depending on the context. As it currently is, that's already always the case nevertheless: we have a lookup to find the right medium stream when we get a packet, that uses the SSRC as a key, so if it's an SSRC we don't know the RTCP is never processed. As such, the unknown SSRC is always the RTX one anyway. Making it VERB means you'll never see it in the logs unless you're using Janus with higher verbosity for debugging.
