### ISSUE TITLE
Wrong return value in janus_mutex_trylock for PTHREAD implementation

### ISSUE THREAD

**Issue by BogdanovKirill** [meetecho/janus-gateway#2894]
Bug: contract of **janus_mutex_trylock** depends on compilation settings (pthread enabled/disabled)

https://github.com/meetecho/janus-gateway/blob/eae294707f8b7d7f013862ae98f0d69f85eaf60c/src/mutex.h#L37

Ассording to manual for **pthread_mutex_trylock** :
"If successful, the pthread_mutex_lock() and pthread_mutex_unlock() functions shall return zero; otherwise, an error number shall be returned to indicate the error."

It means that you should logically invert result value:
` ret = !pthread_mutex_trylock(a);`

Also you could compare with GLIB implementation:
https://github.com/meetecho/janus-gateway/blob/eae294707f8b7d7f013862ae98f0d69f85eaf60c/src/mutex.h#L87

Ассording to manual for **g_mutex_trylock** :
Tries to lock mutex. If mutex is already locked by another thread, it immediately returns FALSE. Otherwise it locks mutex and returns TRUE.

**Comment by lminiero** [comment]
Good catch. It looks like we currently only use it once, in the Streaming plugin, where we assume the Glib logic you pasted is the correct one. As such, yes, as you suggest we should invert the pthread definition. I'll do that shortly.

**Comment by BogdanovKirill** [comment]
@lminiero 
It seems that your fix is not enough. Check here:
https://github.com/meetecho/janus-gateway/blob/eae294707f8b7d7f013862ae98f0d69f85eaf60c/src/mutex.h#L39
