### ISSUE TITLE
[1.x] Protection fault 

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#2896]
**What version of Janus is this happening on?**
Latest git ("commit-hash": "e7fec8294704b5f034dd03546b85bb201724d496")

**Was this working before?**
It's actually was worked but yesterday it's happend like boom, every 10-15 minutes crash on every server. I did change on client, but nothing that touch to streaming plugin

**Is there a gdb or libasan trace of the issue?**
https://pastebin.com/AFyNUyHy

**Comment by atoppi** [comment]
hi @amnonbb it seems glib is reporting a failed assertion, not clear which one since the symbols for glib are not enabled.
Is there something on the janus log about the assertion?
How your client is interacting with the streaming plugin? Any chance of "risky" concurrent tasks (like i.e. mountpoint destruction while in use)?

**Comment by atoppi** [comment]
My guess is that the `session->streams_byid` hashtable is being un-reffed and freed by another thread through `janus_streaming_hangup_media_internal`.

You're probably using and old version of glib that [includes an assertion ](https://github.com/GNOME/glib/blob/2.46.2/glib/ghash.c#L373)when looking up nodes, hence the **SIGABRT**.

Very likely this is the same problem of #2882

**Comment by amnonbb** [comment]
Thanks for fast feedback.
Mountpoints does not change, but possible that someone try to get something from died sessions

**Comment by amnonbb** [comment]
> You're probably using and old version of glib that [includes an assertion ]

We use latest CentOS (Rocky) that, as known, not include latest version libs.
What glib version does not include includes an assertion?

**Comment by atoppi** [comment]
glib (or its version) is not to blame here, the assertion (or whatever equivalent action in recent versions) is just making the program abort for "safety" reason because the hashtable memory in that point is not valid anymore.
We need to investigate the issue and let you know if further data is needed.

**Comment by atoppi** [comment]
@amnonbb can you please check the janus logs?
> Is there something on the janus log about the assertion?

**Comment by amnonbb** [comment]
In log nothing about, but systemd journal got some info:
https://pastebin.com/vCF39u9m

**Comment by atoppi** [comment]
yep I can spot both

```GLib:ERROR:ghash.c:378:g_hash_table_lookup_node: assertion failed: (hash_table->ref_count > 0)```

and

```
g_hash_table_lookup: assertion 'hash_table != NULL' failed
```

this seems to confirm my previous guess and also that #2882 refers to the same issue.

**Comment by lminiero** [comment]
@amnonbb please see if the PR above helps.

**Comment by amnonbb** [comment]
@lminiero It's did not.
I made libasan trace:
https://pastebin.com/xaS5SsWG
Maybe it tell something more about

**Comment by lminiero** [comment]
That's a different crash in a different place. I'll have a look.

**Comment by amnonbb** [comment]
I think i got problem cause from client side. Looks like i'm free iceRestart function that did problem in past. In some condition client may enter to uncontrollable loop of ice failed <-> iceRestart.

**Comment by lminiero** [comment]
Please let us know if that fixes it on your side, but we'll still need to figure out why that should cause a crash. My guess is that, if you're correct, that loop somehow causes at least one of our reference counts to decrease when it shouldn't, thus causing an early destruction when a resource is still used. In that case, we'd need a Janus log of a crash with refcount debugging enabled, or with a client code snippet that can consistently replicate the problem.

**Comment by amnonbb** [comment]
I'll try to manually reproduce client bug

**Comment by amnonbb** [comment]
As i supposed, that was a problem. Today was 0 crash. I tried manually reproduce client bug but without success yet...

**Comment by amnonbb** [comment]
I'm still can't reproduce bug manually.
But 2 days ago in our public janus stream server i got crash every 10-20 minutes. I'm compile janus with refcount debug but forgot to increase default coredump size 🤦
So for now got only very long [janus.log](https://str1.kab.sh/janus.log)

**Comment by atoppi** [comment]
@amnonbb I can see Janus being restarted many times, but there is no clue about what caused the stop.

**Comment by amnonbb** [comment]
It's start when our clients from Russia got problem. In Janus.log it's look spaming of ICE Failed errors. So it's somehow connected

**Comment by lminiero** [comment]
Downloading the log now. For next time, please tar/zip it before uploading large files, as text can be greatly compressed.

**Comment by lminiero** [comment]
I can't see any problem in the logs either: unortunately the libasan traces are missing in between restarts, so we have no way to check what caused the crash, and don't have info on which references we should track back to the source.

**Comment by lminiero** [comment]
As a side note, I merged the PR above which was originally conceived as a potential fix to your problem, as there was indeed a race condition there that it fixes. While it didn't prevent other crashes for you, it definitely fixed _that_ crash, since the further report you shared showed a crash in another place.

**Comment by amnonbb** [comment]
I stated latest Janus with libasan and refcount debug today. Hope we can get more info.

**Comment by amnonbb** [comment]
https://pastebin.com/tWy09CsX

**Comment by atoppi** [comment]
The last segfault is unrelated to the context of this issue.
Also it is happening in the MQTT library. I'd suggest trying with the latest tagged version of paho.

If the same crash is still occurring, please open another issue.

**Comment by amnonbb** [comment]
Ok i'll try. And this issue can be closed i suppose, because second bug i can't reproduce manually. I did many tries.

**Comment by atoppi** [comment]
Thanks @amnonbb , we'll closing this now, please re-open should the crash occur again.
