### ISSUE TITLE
[0.11.8] ICE connection error after update android chrome to 98.0

### ISSUE THREAD

**Issue by les7171** [meetecho/janus-gateway#2905]
After upgrading Chrome to version 98 (android), there was a problem connecting as a subscriber. At the same time, the flow to janus-gateway goes and holds, i.e. ICE works out correctly and the connection goes. Standard settings. Chromium based browsers v 97 and older works correctly

**Comment by lminiero** [comment]
Please discuss runtime problems with ICE on the [group](https://groups.google.com/g/meetecho-janus), not here.
