### ISSUE TITLE
[0.x] Chrome no media from B side

### ISSUE THREAD

**Issue by shutandrii** [meetecho/janus-gateway#2907]
**What version of Janus is this happening on?**
0.11.7

**Have you tested a more recent version of Janus too?**
No. We're using some customization regarding receiving numbers from the URI SIP string.

**Was this working before?**
Its working on Firefox browser any latest version.

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
We've faced issues while receiving media on Chrome browsers (beta, and stable Chrome/98.0.4758.102).

The issue is we don't receive any media from B side while making a call, while we can receive it with the same settings on the firefox browser. While B side can hear A side but otherwise. Both sides can hear each other only at the Firefox browser (tested with 97.0.1).

On the browser side, there are no errors while making this call.

From both browsers, we are testing WS and WSS (with valid CA cert) and it keeps to be the same for both cases.

**Comment by lminiero** [comment]
There is no such version 0.11.17, I assume you meant 0.11.7? That said, we cannot debug a version of Janus that has been modified, sorry. If you can share details on an unmodified version of Janus that presents errors, we're happy to take a look.

**Comment by shutandrii** [comment]
I will test on non-modified now.

**Comment by shutandrii** [comment]
I have tested it on Chrome with https://janus.conf.meetecho.com/siptest.html using our VOIP SIP server it is working fine, what can be an issue for the web client in this case?

**Comment by direritcom** [comment]
Hello, we have the same problem, but https://janus.conf.meetecho.com/videoroomtest.html still does not work with incoming streams from mobile devices.

**Comment by shutandrii** [comment]
> We have same problem chrome v98.0.4758.102 windows and edge. Safari and firefox works. Chrome on MAC works. janus 0.11.2
> 
> Same happens on janus videoconferrence test room at https://janus.conf.meetecho.com/videoroomtest.html. Incoming audio and video streams do not start/
> 
> But we have several users that still can connect. Additional info: it happens only if a user is behind nat and requires ice negotiation. Connection stops right after the negotiation ends. No packets recieved from janus in chrome://webrtc-internals.

Agree with the information regarding stats, it seems to fail to negotiate and WRTC stats are empty. But Firefox working just great using the same configuration.

**Comment by ikoiot** [comment]
Tried with different stun servers. No changes

**Comment by shutandrii** [comment]
> Tried with different stun servers. No changes

Yes, also changing STUN/ICE/TURN is not making any sense.

**Comment by atoppi** [comment]
For what is worth, just tested  https://janus.conf.meetecho.com/videoroomtest.html with both Chrome 98 and 100 on Linux and everything works as expected.

**Comment by shutandrii** [comment]
At the moment when I'm trying to make a call - I'm getting this error on chrome,

{
    "code": 490,
    "reason": "Error setting ICE locally"
}

Can't get any dumps since any media has been passed... If you need the same info from Firefox (dump of working call) let me know.

**Comment by lminiero** [comment]
You need to share the Janus log around where that error is returned, as it will tell us where it happened.

**Comment by shutandrii** [comment]
> You need to share the Janus log around where that error is returned, as it will tell us where it happened.

4355042277067369] The DTLS handshake has been completed

[janus.plugin.sip-0x7fb218002b00] WebRTC media is now available

[janus.plugin.sip-0x7fb218002b00] No WebRTC media anymore

[4355042277067369] WebRTC resources freed; 0x7fb228002c50 0x7fb2280024b0

[ERR] [plugins/janus_sip.c:janus_sip_handler:4465] Wrong state (not established/inviting? status=idle)

Detaching handle from JANUS SIP plugin; 0x7fb228002c50 0x7fb218002b00 0x7fb228002c50 0x7fb228003e30

[4355042277067369] Handle and related resources freed; 0x7fb228002c50 0x7fb2280024b0

Destroying session 644412929457251; 0x7fb2280024b0

**Comment by lminiero** [comment]
That's not the log line where the "Error setting ICE locally" error is generated. This says the SIP plugin received possibly an answer but there was no ongoing call, meaning something else closed the connection before the answer was received.

**Comment by shutandrii** [comment]
But this is all I have regarding the call I have provided and have ICE error on Chrome. Just this.

**Comment by shutandrii** [comment]
I just made a Chrome test with Meetecho Janus (WebRTC Server) v0.11.7

This is what I get on ringing

`
[WARN] [984497186517899] Agent already exists?
[ERR] [janus.c:janus_process_incoming_request:1471] Error setting ICE locally
uri after conversion: sip:7510535797843447@ocas.me
[984497186517899] The DTLS handshake has been completed
[janus.plugin.sip-0x7f071c00c050] WebRTC media is now available
`


And this is what I get when I hang up the call

`[ERR] [plugins/janus_sip.c:janus_sip_handler:4465] Wrong state (not established/inviting? status=idle)
[janus.plugin.sip-0x7f071c00c050] No WebRTC media anymore
[984497186517899] WebRTC resources freed; 0x7f072400cb50 0x7f0724029780
`

**Comment by lminiero** [comment]
The `Agent already exists?` line confirms to me this is a client side management problem, to me. You're probably not hanging up previous PeerConnections, and as a result you get those errors. Closing.
