### ISSUE TITLE
Semi accurate documentation

### ISSUE THREAD

**Issue by yan-foto** [meetecho/janus-gateway#291]
As I was trying to find out the reason for [this sentence](https://github.com/meetecho/janus-gateway/blob/master/mainpage.dox#L1585):

> As you probably know, you cannot open WebRTC-powered web applications by just opening the application HTML files from file system, as it won't work. This means that to test and use Janus you'll need to host your applications on a webserver.

I found out that (at least for streaming example) the aforementioned is valid only for UAs that doesn't implement [srcObj](http://www.w3.org/TR/2013/WD-mediacapture-streams-20130903/#widl-HTMLMediaElement-srcObject) property of [HTMLMediaElement](https://developer.mozilla.org/en/docs/Web/API/HTMLMediaElement) (i.e. `<video>`). Such UAs [use](http://www.w3.org/TR/2013/WD-mediacapture-streams-20130903/#direct-assignment-to-media-elements) `createObjectURL` to create a blob URL and then assign it to `<video>`. 

In case of Chrome (tested with version `43.0.2357.134 (64-bit)`) `srcObj` is not implemented and since workers [are not allowed to run locally](http://www.html5rocks.com/en/tutorials/workers/basics/#toc-security) (i.e. `file://` scheme) the documentation is valid but in case of Firefox (tested with version `39.0`) I was able to stream webcam video locally without delivering my `streamingtest.html` through a webserver (see [`adapter.js`](https://github.com/webrtc/adapter/blob/master/adapter.js#L175)).

**Comment by lminiero** [comment]
Fair point, but since is an easy error most users make, and many use Chrome, we thought that advising on the best practice to test this was best. I'll check if and how I can revisit the docs to clarify your point when I get back home from the conference.

**Comment by yan-foto** [comment]
Thank you for your quick replies :top: ! I was just at the verge of pulling my hair out because I wasn't sure how webRTC is implemented exactly. I'd say a oneliner would help people like me to get some orientation.

**Comment by lminiero** [comment]
This should be clearer, thanks for the feedback.
