### ISSUE TITLE
[1.x] Latest chrome. Demos at https://janus.conf.meetecho.com/ not working. 

### ISSUE THREAD

**Issue by ikoiot** [meetecho/janus-gateway#2911]
Tested on your site from different places.
latest 98.0.4758.102 chrome macos and windows fail
Edge fails
safari and firefox works

Symptoms: 
Echo test works.
Videoroom can't recieve any stream. But output stream works.

Same happens with webrtc and in google meetings and our server.
Different providers and places - same

If you need logs i'm ready to help.

**Comment by lminiero** [comment]
If it doesn't work in Google Meet either, I highly doubt it's a problem in Janus, and more likely a problem on your side (NAT/firewall?). We just tested that version of Chrome on Windows and it works fine here, in fact. As such, you may want to open a bug on the Chrome/WebRTC bug tracker, not here. Closing.
