### ISSUE TITLE
make 

### ISSUE THREAD

**Issue by MesharSuliman** [meetecho/janus-gateway#2913]
janus-gateway % make
make: *** No targets specified and no makefile found.  Stop.

**Comment by lminiero** [comment]
Read the instructions.

**Comment by MesharSuliman** [comment]
First of all, you can use `brew` to install most of the dependencies:

	brew install jansson libnice openssl srtp libusrsctp libmicrohttpd \
		libwebsockets cmake rabbitmq-c sofia-sip opus libogg curl glib \
		libconfig pkg-config autoconf automake libtool

then ?
