### ISSUE TITLE
[0.makex]

### ISSUE THREAD

**Issue by MesharSuliman** [meetecho/janus-gateway#2914]
1/Mac m1 
2/Ubuntu
bbitmq-c/build/janus-gateway$ make
**make: *** No targets specified and no makefile found.  Stop.**
m@m:~/libnice/libsrtp-2.2.0/boringssl/usrsctp/libwebsockets/build/paho.mqtt.c/rabbitmq-c/build/janus-gateway$ 
@make

**Comment by lminiero** [comment]
It's all explained in the readme. If you can't follow that, ask ok the group, not here.
