### ISSUE TITLE
Simulcast layer availability is not properly signalled when disabling layers

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2919]
**What version of Janus is this happening on?**
f62c80f (02.March.2022)

**Have you tested a more recent version of Janus too?**
i saw this working in the legacy version

**Additional context**
I have a publisher that is doing simulcast through sdp mundging (chrome) or the api way (firefox).
As layer get active in the two browsers i get the appropriate signals from janus

{
  "janus": "media",
  "mid": "1",
  "receiving": true,
  "sender": 4273062757902817,
  "session_id": 7923158100977834,
  "substream": 0,
  "type": "video"
}
{
  "janus": "media",
  "mid": "1",
  "receiving": true,
  "sender": 4273062757902817,
  "session_id": 7923158100977834,
  "substream": 2,
  "type": "video"
}
{
  "janus": "media",
  "mid": "1",
  "receiving": true,
  "sender": 4273062757902817,
  "session_id": 7923158100977834,
  "substream": 1,
  "type": "video"
}

If i now disable the highest (h) or then following the middle layers (m) on the client side by changing the encoding in the sender parameters (active = false), i would expect to get a notification from janus. *however* i only get the notification if i disable the lowest (l) layer and then i get the notifications for the three layers i already disable way before.

{
  "janus": "media",
  "mid": "1",
  "receiving": false,
  "sender": 4273062757902817,
  "session_id": 7923158100977834,
  "substream": 0,
  "type": "video"
}
{
  "janus": "media",
  "mid": "1",
  "receiving": false,
  "sender": 4273062757902817,
  "session_id": 7923158100977834,
  "substream": 2,
  "type": "video"
}
{
  "janus": "media",
  "mid": "1",
  "receiving": false,
  "sender": 4273062757902817,
  "session_id": 7923158100977834,
  "substream": 1,
  "type": "video"
}

**Comment by lminiero** [comment]
I can replicate the issue. I'll have a look in the next few days.

**Comment by JanFellner** [comment]
✔ checked with #48c90574 looks good .)
