### ISSUE TITLE
Missing notification when switching to temporal layer 2

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2921]
**What version of Janus is this happening on?**
#48c90574

**Have you tested a more recent version of Janus too?**
No, just one newer tag that has no effect on the problematic behaviour

**Was this working before?**
In non multistreaming i saw the missing event

**Additional context**
Using simulcast with different browsers all working fine. Implemented switching between the different layers on the multistreaming branch. When switching the substream layers i get the positive acknowledgement by janus and shortly later the event that the layer was switched. I also get that when switching the temporal layers but i am missing the notification when switching to temporal 2.

Example flow for switching to temporal layer 1
{
  "body": {
    "fallback": 250000,
    "mid": "1",
    "request": "configure",
    "temporal": 1
  },
  "handle_id": 5124837308033646,
  "janus": "message",
  "session_id": 6064461777641284,
  "transaction": "S_message_340"
}
{
  "janus": "ack",
  "session_id": 6064461777641284,
  "transaction": "S_message_340"
}
{
  "janus": "event",
  "plugindata": {
    "data": {
      "configured": "ok",
      "room": "R_94ed71b2bec640f48ae4945452277e78",
      "videoroom": "event"
    },
    "plugin": "janus.plugin.videoroom"
  },
  "sender": 5124837308033646,
  "session_id": 6064461777641284,
  "transaction": "S_message_340"
}
{
  "_": "2022-03-14T14:20:02.373Z - ws - in",
  "janus": "event",
  "plugindata": {
    "data": {
      "mid": "1",
      "room": "R_94ed71b2bec640f48ae4945452277e78",
      "temporal": 1,
      "videoroom": "event"
    },
    "plugin": "janus.plugin.videoroom"
  },
  "sender": 5124837308033646,
  "session_id": 6064461777641284
}

⚠ For temporal layer 2 the message flow is the same, just the event that announces the switch to temporal 2 is missing.

The source browser is delivering 30fps, i just checked that.

**Comment by lminiero** [comment]
To my knowledge, browsers now only send two temporal layers (0,1), so button 2 is useless as there will never be a temporal layer 2.

**Comment by JanFellner** [comment]
But even if i do a firefox to firefox session janus is not sending me the temporal 2 notification...

So if it is now supported on a per browser basis i would expect the notification or if it is not supported i would expect the documentation to align to it. The behavior currently is somehow strange in between.
From the doc its supported, chrome is not supporting it, but janus allows me to send 2 but is not properly acting to it.

Am i blind?

**Comment by lminiero** [comment]
> Am i blind?

Maybe you are: I just wrote "IIRC, at least for a while, Chrome stopped sending 3 temporal layers, but some others (e.g., Firefox) still did". That's a decision we made months ago, when that was the case, and then we never changed the behaviour since then. Is it clear now? Or do I need to make a drawing?
