### ISSUE TITLE
[0.x][1.x] Streaming plugin example not showing video in incognito mode in combination with NordVPN(and possibly other VPNs)

### ISSUE THREAD

**Issue by davidengelmaier** [meetecho/janus-gateway#2925]
**What version of Janus is this happening on?**
Happening with the official video demo on the site https://janus.conf.meetecho.com/streamingtest.html

**Have you tested a more recent version of Janus too?**
Happens with all versions

**Was this working before?**
No

**Additional context**
The problem is the in the combination with VPN, namely the NordVPN and most strongly the incognito mode.
Steps to reproduce:
1. start the NordVPN 
2. open an incognito mode window in Chrome(also reproduced in Safari and Firefox) with https://janus.conf.meetecho.com/streamingtest.html
3. start the demo and choose the Multistream test
4. you will hear the audio, but not see the video(50%+ packets are lost, although i have managed to get rid of that problem in my setup i can still not see the video)

This can actually be fixed by requesting the navigator.mediaDevices.getUserMedia({audio: true, video: true}); and allowing the mic & camera before the playback, but obviously that is not a solution :(

Interestingly enough https://janus.conf.meetecho.com/recordplaytest.html plays without issues even in sessions with playback only without requesting permissions for the camera and microphone

**Comment by atoppi** [comment]
Is it working without VPN?
When using a VPN the available MTU gets usually smaller. Audio packets are small, so that seems to confirm my guess.
If that's the case, nothing we can fix in Janus. AFAIR we do not enforce any MTU when relaying.

**Comment by lminiero** [comment]
We never enforce an MTU, since we cannot. That would mean buffering RTP packets, depacketizing and repacketizing them to get a smaller MTU, which is never going to happen. Since you're using the Streaming plugin and the source of media is external, you need to enforce a smaller MTU there, not in Janus (which is maybe not happening in the script we use on the demo website, not sute).

**Comment by lminiero** [comment]
That may have something to do with [RFC 8828](https://www.rfc-editor.org/rfc/rfc8828.html), section 5.2 specifically.

**Comment by fippo** [comment]
check what candidates you get on https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ without and with getUserMedia (note that the permission is persisted in chrome). That should show what Lorenzo says -- without GUM you only get the default route which will be the VPN

**Comment by lminiero** [comment]
Not an issue, so I'll close this.

**Comment by davidengelmaier** [comment]
> Not an issue, so I'll close this.

yes, and thank you very much again for the help!
