### ISSUE TITLE
Janus sending statistics for unsubscribed tracks

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2926]
**What version of Janus is this happening on?**
#c684d43

**Have you tested a more recent version of Janus too?**
nope

**Was this working before?**
did not see this in the non multistreaming branch

**Additional context**
We are using the websocket event handler to get statistics pushed from janus.

Using the videoroom i have two publishers and one subscriber.
This subscriber is subscribed to media from both publishers. (audio&video mid 0-3 in the subscription plugin handle)
I unsubscribe from one of the publishers.

For the subscription plugin handle i would now expect to get statistics pushed for the resulting mids after the unsubscribe.
However i get statistics for all mids that were in the subscription before.

**Comment by lminiero** [comment]
The Janus core has no clue about what a subscription is: that's a plugin (VideoRoom) thing.
If a track exists, whether it's active or not, we push stats for it. This is intended.

**Comment by JanFellner** [comment]
Shouldn´t the two tracks be gone if i unsubscribe it using the janus video room api?

**Comment by lminiero** [comment]
That's not how SDP works, the m-lines remain there. In the Janus core, 1 mline = 1 medium instance, which is what we call a track.

**Comment by JanFellner** [comment]
sorry, just checked the sdp, k, still there inactive... -> cloooosing :)

**Comment by lminiero** [comment]
I love when we can close issues so quickly! :smile:

**Comment by JanFellner** [comment]
We can continue to discuss that one on the next janus con with a beer if you want to 😁

**Comment by lminiero** [comment]
Hopefully we'll be able to do one again soon!
