### ISSUE TITLE
Gateway seems to generate corrupt SIP INVITE

### ISSUE THREAD

**Issue by jamesabravo** [meetecho/janus-gateway#293]
I've built janus v0.0.9-179-g47319ca and have been testing it on a 64-bit VM using CentOS7.

Using the 'SIP Gateway' demo, I can see the UDP SIP REGISTER & OPTIONS being sent fine from the janus gateway but the INVITE always seems to be corrupt in that the SDP seems to be within the SIP headers and the content length is 0 ???

I've upload pcap [here](http://s000.tinyupload.com/?file_id=03971865924916259359)

Below is a INVITE sent from janus when testing with chrome...

```
Via: SIP/2.0/UDP 10.70.6.68:53124;rport;branch=z9hG4bKD3gjaagQ0H03g
v=0
o=- 2549325653888730941 8150854048624674660 IN IP4 10.70.6.68
s=-
t=0 0
m=audio 58062 RTP/AVP 111 103 104 9 0 8 106 105 13 126
c=IN IP4 10.70.6.68
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
Max-Forwards: 70
From: <sip:12001@10.70.6.68>;tag=ct5S6FQHFFg9H
To: <sip:12002@10.70.6.68>
Call-ID: 11745fd9-acca-1233-a8a3-0800271ca635
CSeq: 78542924 INVITE
Contact: <sip:12001@10.70.6.68:53124>
User-Agent: Janus WebRTC Gateway SIP Plugin 0.0.5
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 0
```
...and below is a INVITE sent from janus when testing with firefox...
```
Via: SIP/2.0/UDP 10.70.6.68:39083;rport;branch=z9hG4bKv6US994XteXgS
v=0
o=Mozilla-SIPUA-34.0 5706753775682860511 4478113185364573227 IN IP4 10.70.6.68
s=SIP Call
t=0 0
m=audio 51138 RTP/AVP 109 9 0 8 101
c=IN IP4 10.70.6.68
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=ptime:20
Max-Forwards: 70
From: <sip:12001@10.70.6.68>;tag=U463Z31S6m52e
To: <sip:12002@10.70.6.68>
Call-ID: 972e0e11-acce-1233-15a0-0800271ca635
CSeq: 78543895 INVITE
Contact: <sip:12001@10.70.6.68:39083>
User-Agent: Janus WebRTC Gateway SIP Plugin 0.0.5
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 0
```

**Comment by lminiero** [comment]
Possibly related to #259 where I saw a similar log. It's most likely an issue with your setup, or with the Sofia SIP version, as it seems to be working fine for pretty much everyone else (me included). Definitely not an issue with Janus as we delegate all SIP management to Sofia SIP itself.

Not sure what version of Sofia SIP CentOS 7 ships.

**Comment by jamesabravo** [comment]
Ok, thanks. I'll dig a bit deeper

**Comment by lminiero** [comment]
Any update on this?

**Comment by jamesabravo** [comment]
Sorry, didn't have time to debug. Ended up using webrtc2sip.

**Comment by lminiero** [comment]
FYI, that turned out to be a problem in compiling Sofia SIP with gcc >= 4.8, there are patches that fix this behaviour: https://code.google.com/p/unimrcp/issues/detail?id=169
