### ISSUE TITLE
If there are more than 16 participants (all publishers) in a room, the server will go down.

### ISSUE THREAD

**Issue by pitchsolution** [meetecho/janus-gateway#2934]
**What version of Janus is this happening on?**
V1.0.1

**Have you tested a more recent version of Janus too?**
Yes

Hi.
I want to ask a question

I am using version 1.0.1, meetingroom plugin
If there are more than 16 participants (all publishers) in a room, the server will go down.

What can I do to increase the maximum number of participants in a room and have a smooth meeting.

thanks.

**Comment by atoppi** [comment]
What do you mean by "the server will go down" ?
Is it crashing? Do you have a call stack / asan dump to show ?

**Comment by pitchsolution** [comment]
Yes it crashing

Below is the log


(janus:2786395): GLib-ERROR **: 16:57:21.156: Creating pipes for GWakeup: Too many open files

Trace/breakpoint trap (core dumped)

-- all log
[WARN] [1534396635776259] Unknown SSRC, dropping packet (SSRC 3041780643)...
[WARN] [1534396635776259] Unknown SSRC, dropping packet (SSRC 3041780643)...
[WARN] [4213910813357106] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
Creating new handle in session 4495486973980185: 8351019844777463; 0x7ff618021a40 0x7ff62818ed90
Creating new handle in session 3325709356272450: 3902772168860150; 0x7ff61801a110 0x7ff628199830
Creating new handle in session 7916305662203558: 8566727524489616; 0x7ff618060ca0 0x7ff628148000
Creating new handle in session 6247657038058925: 2989539724636252; 0x7ff6180264d0 0x7ff628148200
Creating new handle in session 7025617911314808: 3843132732730024; 0x7ff6180359d0 0x7ff628160c30
Creating new handle in session 5859887291440133: 352355216765824; 0x7ff61801fd60 0x7ff628189310
Creating new handle in session 4859432117760641: 2912160449372179; 0x7ff628004940 0x7ff62818a760
Creating new handle in session 7933824138818114: 5757279621610281; 0x7ff61813e520 0x7ff62819b9a0
[8566727524489616] Creating ICE agent (ICE Full mode, controlling)
Creating new handle in session 5989594184284326: 1750308041640544; 0x7ff618008840 0x7ff628188f30
Creating new handle in session 5139869424960801: 3927463541402093; 0x7ff628024070 0x7ff62818d1f0
[3902772168860150] Creating ICE agent (ICE Full mode, controlling)
[8351019844777463] Creating ICE agent (ICE Full mode, controlling)
[WARN] [8566727524489616] Failed to add some remote candidates (added 1, expected 2)
[352355216765824] Creating ICE agent (ICE Full mode, controlling)
[WARN] [3902772168860150] Failed to add some remote candidates (added 0, expected 1)
[WARN] [8351019844777463] Failed to add some remote candidates (added 0, expected 1)
[3902772168860150] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff61813ba00] WebRTC media is now available
[janus.plugin.videoroom-0x7ff61813ba00] Data channel available
[2989539724636252] Creating ICE agent (ICE Full mode, controlling)
[8566727524489616] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff6281845a0] WebRTC media is now available
[janus.plugin.videoroom-0x7ff6281845a0] Data channel available
[8351019844777463] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff618101b50] WebRTC media is now available
[janus.plugin.videoroom-0x7ff6180c6970] Data channel available
[3843132732730024] Creating ICE agent (ICE Full mode, controlling)
[janus.plugin.videoroom-0x7ff618101b50] Data channel available
[WARN] [4213910813357106] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[WARN] [2989539724636252] Failed to add some remote candidates (added 0, expected 1)
[1750308041640544] Creating ICE agent (ICE Full mode, controlling)
[WARN] [352355216765824] Failed to add some remote candidates (added 1, expected 2)
[WARN] [3843132732730024] Failed to add some remote candidates (added 0, expected 1)
[5757279621610281] Creating ICE agent (ICE Full mode, controlling)
[2989539724636252] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff62809e8f0] WebRTC media is now available
[janus.plugin.videoroom-0x7ff62809e8f0] Data channel available
[352355216765824] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff628153b60] WebRTC media is now available
[janus.plugin.videoroom-0x7ff628153b60] Data channel available
[2912160449372179] Creating ICE agent (ICE Full mode, controlling)
[3843132732730024] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff628173580] WebRTC media is now available
[WARN] [1750308041640544] Failed to add some remote candidates (added 2, expected 3)
[janus.plugin.videoroom-0x7ff628173580] Data channel available
[3927463541402093] Creating ICE agent (ICE Full mode, controlling)
[WARN] [5757279621610281] Failed to add some remote candidates (added 0, expected 1)
[1750308041640544] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff628102cd0] WebRTC media is now available
[4213910813357106] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff61809e040] WebRTC media is now available
[janus.plugin.videoroom-0x7ff628102cd0] Data channel available
[WARN] [4213910813357106] Unknown SSRC, dropping packet (SSRC 473123807)...
[janus.plugin.videoroom-0x7ff61809e040] Data channel available
[WARN] [4213910813357106] Unknown SSRC, dropping packet (SSRC 792988979)...
[WARN] [4213910813357106] Unknown SSRC, dropping packet (SSRC 792988979)...
[5757279621610281] The DTLS handshake has been completed
[janus.plugin.videoroom-0x7ff62815dc00] WebRTC media is now available
[WARN] [4213910813357106] Unknown SSRC, dropping packet (SSRC 792988979)...
Creating new handle in session 7916305662203558: 1115439794970775; 0x7ff618060ca0 0x7ff62815b4a0
Creating new handle in session 3325709356272450: 982761389222134; 0x7ff61801a110 0x7ff6281983c0
Creating new handle in session 7933824138818114: 3748440068576480; 0x7ff61813e520 0x7ff62819d280
Creating new handle in session 5859887291440133: 1624760757720942; 0x7ff61801fd60 0x7ff62819da70
[janus.plugin.videoroom-0x7ff62815dc00] Data channel available
Creating new handle in session 6247657038058925: 3659830499771995; 0x7ff6180264d0 0x7ff62819e4e0
Creating new handle in session 3327753008275145: 6318731650395784; 0x7ff6280523a0 0x7ff62819eaf0
Creating new handle in session 5139869424960801: 3769250328900691; 0x7ff628024070 0x7ff62819f0b0
Creating new handle in session 4495486973980185: 6130842904272977; 0x7ff618021a40 0x7ff62819f8b0
[WARN] [2912160449372179] Failed to add some remote candidates (added 1, expected 2)
Creating new handle in session 7025617911314808: 197354886722705; 0x7ff6180359d0 0x7ff6281a0110

(janus:2786395): GLib-ERROR **: 16:57:21.156: Creating pipes for GWakeup: Too many open files

Trace/breakpoint trap (core dumped)
[root@dev bin]#

**Comment by atoppi** [comment]
Already discussed many times.
Increase the open files limit in the OS.

**Comment by lminiero** [comment]
> (janus:2786395): GLib-ERROR **: 16:57:21.156: Creating pipes for GWakeup: Too many open files

Yes, as @atoppi said this is well explained in the FAQ too: https://janus.conf.meetecho.com/docs/FAQ.html#ulimit

**Comment by pitchsolution** [comment]
Thank you so much!
