### ISSUE TITLE
[1.x] Streaming not working on Chrome 100.0.4896.60

### ISSUE THREAD

**Issue by vkresch** [meetecho/janus-gateway#2937]
Not sure if this is the right place to post my problem. Please let me know where I should post then. 

I am using Chrome version 100.0.4896.60 and I am trying to test if streaming works on my browser. But as it seems it does not:
![janus_bug](https://user-images.githubusercontent.com/14346967/161337900-a625fc52-88d9-4340-9155-c0e99d557967.gif)

How should I resolve this issue? Any help/guide/hint is appreciated. What do I need to install? In Firefox 98.0.2 everything works fine for me. Thanks in advance.

**Comment by lminiero** [comment]
Looks like an autoplay issue, maybe some stricter constraint in newer versions of Chrome. As such, not a problem in Janus itself.

**Comment by atoppi** [comment]
it's working as expected here on both Chrome 100 (beta) and 101 (dev)

**Comment by lminiero** [comment]
Works fine on Chrome/Linux 102 too. I'll close this issue, then.

**Comment by vkresch** [comment]
Thanks for the feedback. Any tips on how I should debug the issue on my browser? I tried it again with vanilla Chrome without any blocking extension/plugins (like adblocker) and I still have this issue ...

**Comment by atoppi** [comment]
Which OS are you running ?
