### ISSUE TITLE
Janus provides an sdp offer with unsubscribing the last streams right befor hanging up

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2938]
**What version of Janus is this happening on?**
#930b056

**Have you tested a more recent version of Janus too?**
there is none

**Was this working before?**
don´t think so

**Additional context**
In the videoroom i have:
- a subscription peerConnection and on this peerConnection i do unsubscribe the last tracks.
- with the videoroom updated event i get an sdp offer (only inactive tracks).
At that point i am sending the offer to the client as i did not yet inspect the sdp.
The client creates an answer and starts to handshake the peerConnection.
This times out as....

milliseconds later janus drops the connection with a DTLS alert.

Expectation: If there is nothing in the peerConnection left over to handshake janus should not provide an sdp.

<details>
<summary>Snippet</summary>

```
{
  "_": "2022-04-07T14:31:22.762Z - ws - out",
  "apisecret": "janus_4$estos",
  "body": {
    "request": "unsubscribe",
    "streams": [
      {
        "feed": "9f95df8c-f382-4b7c-9334-e7d648e98f20",
        "mid": "0"
      },
      {
        "feed": "9f95df8c-f382-4b7c-9334-e7d648e98f20",
        "mid": "1"
      }
    ]
  },
  "handle_id": 224380829192392,
  "janus": "message",
  "opaque_id": "P_f820de4ed55f4252aa30fd0d057ba599|Jan",
  "session_id": 2079457008173267,
  "transaction": "S_message_20"
}

{
  "_": "2022-04-07T14:31:22.772Z - ws - in",
  "janus": "event",
  "jsep": {
    "sdp": "...",
    "type": "offer"
  },
  "plugindata": {
    "data": {
      "room": "R_4b26d460aa0c4ab79b6f97204ce5e0ae",
      "streams": [
        {
          "active": false,
          "mid": "0",
          "mindex": 0,
          "ready": false,
          "send": true,
          "type": "audio"
        },
        {
          "active": false,
          "mid": "1",
          "mindex": 1,
          "ready": false,
          "send": true,
          "type": "video"
        }
      ],
      "videoroom": "updated"
    },
    "plugin": "janus.plugin.videoroom"
  },
  "sender": 224380829192392,
  "session_id": 2079457008173267,
  "transaction": "S_message_20"
}
{
  "_": "2022-04-07T14:31:22.795Z - ws - in",
  "janus": "hangup",
  "reason": "DTLS alert",
  "sender": 224380829192392,
  "session_id": 2079457008173267
}
```

**Comment by lminiero** [comment]
A collection of inactive m-lines is a valid SDP, why shouldn't we provide an offer?

**Comment by lminiero** [comment]
No, Janus won't drop the session. It works as expected in the `mvideoroom.html` demo for instance: if you have people in, and then everybody leaves, the subscription remains active and works. Are you sure you aren't closing tracks yourself? If you do that on the first track (the one media is bundled in) that's what may be closing the PeerConnection.

**Comment by JanFellner** [comment]
I do it like in Monkey Island: You win i loose :)

**Comment by lminiero** [comment]
:see_no_evil:
