### ISSUE TITLE
[modular-transports] Enabling WebRTC admin WS interface renders normal WS interface unresponsive

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#294]
If we enable the Websocket Admin interface in conf/janus.transport.websockets.cfg (setting admin_ws = yes), the normal WS interface on port 8188 appears to be reachable but no response is received when sending a message (e.g. create_session).

When disabled (admin_ws = no), things work as they are supposed to work. 

Config file: http://pastebin.com/qAJrK1ry

**Comment by lminiero** [comment]
Seems to be working fine here:

```
// Create Janus API client
ws = new WebSocket("ws://localhost:8188", "janus-protocol");
ws.onmessage = function(msg) { console.log(msg); };
ws.onopen = function() { console.log("Janus API Connected") };
// Create Admin API client
aws = new WebSocket("ws://localhost:7188", "janus-admin-protocol");
aws.onmessage = function(msg) { console.log(msg); };
aws.onopen = function() { console.log("Connected") };
[..]
// Send Janus API request
ws.send(JSON.stringify({janus:"create", transaction: "123"}));
[..]
// Send Admin API request
aws.send(JSON.stringify({janus:"list_sessions", secret: "janusoverlord", transaction: "123"}));
```

Typing these commands in the JavaScript console gives me the expected result: both servers are running and handling the respective requests accordingly.

I wonder if in your setup the admin service is never returning for some reason. You may want to add some JANUS_LOG lines before each one of the service handlers here just to make sure they're all being called on a regular basis:

https://github.com/meetecho/janus-gateway/blob/modular-transports/transports/janus_websockets.c#L605

Anyway, as suggested by Pierce, I'll move each WebSockets service to a different thread in one of the next commits, so if that's the case it should fix it.

**Comment by lminiero** [comment]
Closing as apparently not an issue. Feel free to reopen if you can provide more details on how to replicate this.

**Comment by arjenveenhuizen** [comment]
Hey, just tested it again and I cannot reproduce this error using the current GIT HEAD of the modular-transports branch. Fixed!
