### ISSUE TITLE
Possible bug in oncleanup near line 861

### ISSUE THREAD

**Issue by henrylaxen** [meetecho/janus-gateway#2942]
**What version of Janus is this happening on?**
anus version: 1001 (1.0.1)
Janus commit: 930b0564bf85f85faa3c0ad976b005c8fb15e8f6
Compiled on:  Fri Apr  8 04:30:10 AM PDT 2022

**Have you tested a more recent version of Janus too?**
I got this from git yesterday.

**Was this working before?**
I doubt it.

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**

Dear Lorenzo,

I think I noticed a bug in your mvideoroomtest.js code:
in your oncleanup: code you have:
`    $('#remotevideo'+i).remove();`
but all of your remotevideo ids are defined with:
`    $('#remotevideo' + slot + '-' + mid)`

and thus the cleanup code cannot match an existing dom id.
I hope this is helpful.

Best wishes,
Henry Laxen

**Comment by lminiero** [comment]
Yes, there's indeed a problem there, but that's the `oncleanup` for the handle of all subscriptions, so when that fires all videos should disappear anyway. I'll probably have to add a custom class to all subscription elements, so that we can just do a remove on that.

**Comment by lminiero** [comment]
I made a simpler fix, that is using this instead:

    $('#videoremote'+i).empty();

as all the things we were removing were appended to those divs anyway, e.g.:

    <div class="panel-body relative" id="videoremote5"></div>
