### ISSUE TITLE
SlowLink message by Janus with wrong value

### ISSUE THREAD

**Issue by RaniRaven** [meetecho/janus-gateway#2943]
**What version of Janus is this happening on?**
V0.10.7

Janus send slowlink notification (through websocket is the case I checked) with wrong values.
This is what i got :
{
"janus": "slowlink",
"session_id": 5490732879329616,
"sender": 1589708216572705,
"media": "video",
"uplink": false,
"lost": 4294911420
}

There seem to be an overflow problem here, as this amount of packets was never passed anywhere.

In order to reconstruct -
I ran test with 25 rooms, with one publisher and one subscriber application for each room.
The application sends a video stream with 2.5 Mbit/sec bitrate to each room.
From 10 rooms, locally I start seeing those slowLink notifications.
In 25 (sometimes less) I start seeing those messages with indication on huge numbers (impossible !!) of packets loss.

I can send you my application which creates this, but I guess your JAttack application can imitate the same.

**Comment by lminiero** [comment]
0.10.7 is almost 2 years old. Please try again with the latest `0.x` branch.

**Comment by RaniRaven** [comment]
I just reproduced the same issue on Janus  v1.0.1, with that same big number.
It happens when you run enough rooms in the instance (or docker), about 30 rooms with videos will cause this problem with high probability.

**Comment by atoppi** [comment]
hi @RaniRaven 
could you please apply the following patch to latest `master` and report the output ?

```diff
diff --git a/src/ice.c b/src/ice.c
index 15747b39..e7e32655 100644
--- a/src/ice.c
+++ b/src/ice.c
@@ -1885,6 +1885,9 @@ janus_slow_link_update(janus_ice_peerconnection_medium *medium, janus_ice_handle
        gboolean video = (medium->type == JANUS_MEDIA_VIDEO);
        guint sl_lost_last_count = uplink ? medium->in_stats.sl_lost_count : medium->out_stats.sl_lost_count;
        guint sl_lost_recently = (lost >= sl_lost_last_count) ? (lost - sl_lost_last_count) : 0;
+       if (sl_lost_recently > 100) {
+               JANUS_LOG(LOG_WARN, "[%"SCNu64"] DEBUG-SLOWLINK uplink=%d lost=%u sl_lost_last_count=%u\n", handle->handle_id, uplink, lost, sl_lost_last_count);
+       }
        if(slowlink_threshold > 0 && sl_lost_recently >= slowlink_threshold) {
                /* Tell the plugin */
                janus_plugin *plugin = (janus_plugin *)handle->app;
```

It should print in a Warning message useful debug data for loss reports >100.

**Comment by lminiero** [comment]
@RaniRaven any update on the patch above?

**Comment by lminiero** [comment]
I guess it's not an issue anymore, closing.
