### ISSUE TITLE
Retrieve successful registration reason/phrase in SIP Plugin

### ISSUE THREAD

**Issue by ycherniavskyi** [meetecho/janus-gateway#2944]
Some SIP provided which we operate with on fault registration return next header `SIP/2.0 200 Authorization failure Via: SIP/2.0/UDP`, so as you can see `status == 200` but `phrase == Authorization failure`. I am not sure about the reason for such behaviour, but we can't change it anyway.

Is it possible to extend `registered` message with `reason` parameter with the analogy to `registration_failed` message?

It could be optional:
```diff
diff --git a/src/plugins/janus_sip.c b/src/plugins/janus_sip.c
index e74ae65d..2046e245 100644
--- a/src/plugins/janus_sip.c
+++ b/src/plugins/janus_sip.c
@@ -5961,6 +5961,9 @@ void janus_sip_sofia_callback(nua_event_t event, int status, char const *phrase,
                                json_object_set_new(reg, "sip", json_string("event"));
                                json_t *reging = json_object();
                                json_object_set_new(reging, "event", json_string(event_name));
+                               if(phrase && !strcmp(phrase, "OK")) {
+                                       json_object_set_new(reging, "reason", json_string(phrase));
+                               }
                                json_object_set_new(reging, "username", json_string(session->account.username));
                                if(event == nua_r_register) {
                                        json_object_set_new(reging, "register_sent", json_true());
```
or persistant:
```diff
diff --git a/src/plugins/janus_sip.c b/src/plugins/janus_sip.c
index e74ae65d..ad00824a 100644
--- a/src/plugins/janus_sip.c
+++ b/src/plugins/janus_sip.c
@@ -5961,6 +5961,7 @@ void janus_sip_sofia_callback(nua_event_t event, int status, char const *phrase,
                                json_object_set_new(reg, "sip", json_string("event"));
                                json_t *reging = json_object();
                                json_object_set_new(reging, "event", json_string(event_name));
+                               json_object_set_new(result, "reason", json_string(phrase ? phrase : ""));
                                json_object_set_new(reging, "username", json_string(session->account.username));
                                if(event == nua_r_register) {
                                        json_object_set_new(reging, "register_sent", json_true());
```

The main idea is to get the actual `phrase` of successful registration, so it will be possible to process it in some custom way.

**Comment by lminiero** [comment]
That sounds like something that should be fixed on the provider side, not Janus. I'm not ok with checking if the text is different from "OK" as it might be for legitimate reasons. If the provider refuses to do the right thing, I'm afraid you'll have to apply this patch on your Janus instances manually, because IMO it would be a hack to do that in the main codebase.

**Comment by ycherniavskyi** [comment]
I also don't like the variant with checking for "OK" string to be honed.
But maybe we could stop on the variant with adding `code` and `reason`, by analogy to `subscribe_succeeded`, `subscribe_failed`, and `registration_failed` messages? It will not break anything but extend the processing possibility in such wired cases. (And yes, `code` value will be redundant because it always will have the same value, but the general message structure will be more consistent.)

And actually here is the answer from the provider:
> The 200 Authorization failure response is intended to reduce the percentage of brute force attacks. The user receives 200 code explaining the failed authorization attempt, however, this fools some automated systems.

🤷🏻‍♂️

**Comment by lminiero** [comment]
> he 200 Authorization failure response is intended to reduce the percentage of brute force attacks. The user receives 200 code explaining the failed authorization attempt, however, this fools some automated systems.

This sounds like a weak excuse to me, as this hack would break a lot of phones as well that just as Janus would expect a 4xx.

Sorry, but I'm not going to handle this in our code: this sounds like something you may want to fix through a proxy like Kamailio or OpenSIPS, where you can rewrite traffic so that the correct error code is restored instead.

**Comment by ycherniavskyi** [comment]
I understand your point. Thank you for the clarification and suggestion about using a proxy (I will investigate in this direction).
