### ISSUE TITLE
[1.x] RTSP stream from Camera hanging in browser

### ISSUE THREAD

**Issue by jp-bennett** [meetecho/janus-gateway#2946]
We have yet another Camera brand that supports h.264 streams that isn't working with Janus. The viewer can be inspected at https://demo.zoneminder.com/index.php?view=watch&mid=2

The Janus log from a Chrome attempt at viewing: https://pastebin.com/DzYjaZ9L

**Comment by lminiero** [comment]
Maybe the `profile-level-id=42A01E` is the problem? I do see the browser answering with a success, but with a `profile-level-id=42001e` in the SDP. Have you checked the stats in the browser (e.g., `chrome://webrtc-internals`) to see if data is being received, but not decoded?

**Comment by lminiero** [comment]
![Screenshot_2022-04-13_12-58-17](https://user-images.githubusercontent.com/3684796/163166164-87c9c533-a260-4a02-b565-dc8c6bb20c9a.png)

I opened the demo page you linked, and I see data coming in, which is not decoded. As such, this sounds like a codec issue, not a problem in Janus (that won't transcode but just relay). Overriding the profile _may_ help (setting `videofmtp` when you create the mountpoint), but with H.264 you never know: it may be the video the camera is sending is indeed something the WebRTC H.264 decoder in browsers can't digest.

**Comment by connortechnology** [comment]
This camera is a Dlink DCS-942L so is a very early h264 supporting camera.   There are no profile settings for it unfortunately so it is very likely that it is not good h264 for webrtc.

**Comment by lminiero** [comment]
By overriding the profile I meant in the SDP Janus sends to the browser, which is something you can do by passing a `videofmtp` property when creating the mountpoint: this was, independently of what the camera offers, the Streaming plugin will put what you added there. A static example can be found [here](https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.streaming.jcfg.sample.in#L252).

**Comment by jp-bennett** [comment]
Even setting the profile statically doesn't get video playing. I think codec issues is correct. It's odd, because the browser will play the video in a <video> container, once it's recorded.

**Comment by lminiero** [comment]
The H.264 decoder used for WebRTC in browsers is not the same H.264 decoder used for container-based streams.

**Comment by jp-bennett** [comment]
It would be nice if there was a way to catch this and throw an error/notify the user. Other than that, I think we can close this bug as can't fix.

**Comment by lminiero** [comment]
Unfortunately there's no way to catch it programmatically, as the decoder works internally in the browser, so all you see is the effect (no video). I guess one thing you could try to do is poll the stats via the `getStats()` API in the browser, as there should be stat values that tell you how many bytes were received, and how many frames decoded: if you have bytes but no frames, then something's wrong trying to decode the media.

**Comment by lminiero** [comment]
I guess we can close this, thanks for the feedback!
