### ISSUE TITLE
[1.x] Getting "a=inactive" from "janus.plugin.audiobridge"

### ISSUE THREAD

**Issue by mail2mhossain** [meetecho/janus-gateway#2947]
The way I am working

Step 01. Creating Session
Step 02. Attching "janus.plugin.audiobridge"
Step 03. Sending Join message
Step 04: In Joined event, 
	A. Creating PeerConnection
	B. Initializing Audio Capture Device
	C. Sending configure Message with sdp

Step 05: Receiving "ok" message with sdp where I found "a=inactive"

Question: why getting "a=inactive"

Step 06: Setting Remote Description

**Comment by lminiero** [comment]
What's the SDP you're sending? You'll only get an inactive if inactive is what you're sending yourself, or possibly if no codecs are supported (but I may be wrong here).

**Comment by mail2mhossain** [comment]
Offer SDP:

v=0
o=- 30274 0 IN IP4 127.0.0.1
s=sipsorcery
t=0 0
a=group:BUNDLE 1
m=audio 9 UDP/TLS/RTP/SAVP 0 8 9 101
c=IN IP4 0.0.0.0
a=ice-ufrag:FEHB
a=ice-pwd:YBLZAWCIMDRQRLXCRDWGBKLG
a=fingerprint:sha-256 22:78:92:0A:38:07:1B:30:44:56:B0:15:DC:6E:98:6C:BF:78:12:F8:BB:F8:C1:54:02:85:90:EC:F5:4E:67:DE
a=setup:actpass
a=candidate:2117 1 udp 659136 192.168.31.194 56049 typ host generation 0
a=ice-options:ice2,trickle
a=mid:1
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:9 G722/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=rtcp-mux
a=rtcp:9 IN IP4 0.0.0.0
a=end-of-candidates
a=sendrecv
a=ssrc:610095144 cname:31fd5894-2ac6-4481-bea2-5538cc1b8e52

Based on above offer sdp, janus returns following answer sdp:

v=0
o=- 1649948920166307 1 IN IP4 54.163.154.72
s=AudioBridge 9900
t=0 0
a=group:BUNDLE
a=ice-options:trickle
a=fingerprint:sha-256 09:E0:26:0C:FA:0D:EA:DA:70:39:97:39:60:E1:CD:68:27:9E:48:13:78:09:34:47:76:93:09:2F:B5:45:4A:26
a=msid-semantic: WMS janus
m=audio 0 UDP/TLS/RTP/SAVP 0
c=IN IP4 54.163.154.72
a=inactive
a=mid:1

**Comment by lminiero** [comment]
> You'll only get an inactive if inactive is what you're sending yourself, or possibly if no codecs are supported (but I may be wrong here).

Exactly what happened. Your offer only has G.711 and G.722, not Opus, which the AudioBridge requires by default. If you want to use G.711, you'll need to pass a `codec: "pcmu"` or `codec: "pcma"` to your `join` request.

Closing as this is behaving as expected.
