### ISSUE TITLE
[1.x]textroom plugin: Invalid element type (room should be a positive integer)

### ISSUE THREAD

**Issue by FJEagle** [meetecho/janus-gateway#2948]
Previously, it was working when we used the roomId like "TeanA1234", but it breaks in v1.0.
Is there a good reason to restrict roomId numeric instead of string? Thanks

**What version of Janus is this happening on?**
v1.0, 71c5c070a0d32e415533833ee561df2d5cbfac2e

**Have you tested a more recent version of Janus too?**
v1.0 tag, is the pretty recent version.

**Was this working before?**
Previously, it was working in the janus of verison 0.11.8 when we used the roomId like "TeanA1234".

**Additional context**
error log:
Textroom plugin: got message from DataChannel: {
       "textroom": "error",
       "error_code": 414,
       "error": "Invalid element type (room should be a positive integer)",
       "transaction": "564842969377"
    }

**Comment by lminiero** [comment]
Identifiers are numeric by default, you need to set `string_ids` to `true` to use strings:
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.textroom.jcfg.sample#L20
