### ISSUE TITLE
[0.x] Memory not free after session timeout

### ISSUE THREAD

**Issue by rchoffar** [meetecho/janus-gateway#2957]
**What version of Janus is this happening on?**
0.12

**Was this working before?**
I don't know

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
Hello, i am using janus with video room plugin, i was investing about memory limit being reached
My janus is runing in a kubernete pod so i was able to inspect the memory usage

<img width="331" alt="Capture d’écran 2022-04-26 à 14 54 31" src="https://user-images.githubusercontent.com/20708864/165320026-50d8e999-0f3a-4427-ac18-5a99818b5d22.png">

In the above image i joined the demo room ( provided in the html folder `videoroomtest.html`) with 4 tabs

Then i closed all 4 tab and as you can see, the memory usage didnt go back to normal ( 28MB at start, 37 at highest, 32 when all sessions destroyed ).
I tried to remove all logs but nothing change.
I also tried to close the 1234 room but nothing change too.

Am i missing something or is there anything i cant do ? My pod i crashing after running 2 weeks because of the limit

Thanks in advance

**Comment by lminiero** [comment]
> My pod i crashing after running 2 weeks because of the limit

Do you get an out of memory error? My guess is the crash is somewhere else, as we regularly check for memory leaks, and I'm not aware of any. If you think there's leaks, uncomment [this line](https://github.com/meetecho/janus-gateway/blob/master/src/refcount.h#L63) and possibly compile with libasan support, anche check what appears when you close Janus cleanly after closing all active sessions. If there's leaks that should tell you where.

**Comment by rchoffar** [comment]
No i am not having out of memory error, the pod is getting removed because of the limit being reached ( my probleme is more about memory keep getting up sessions after sessions ).
I will try to close janus after closing sessions.
But why i need to close janus to free all memory ? In hypothesis detroying all sessions should go back to initial memory usage no ?

**Comment by lminiero** [comment]
Any update?

**Comment by lminiero** [comment]
Closing.
