### ISSUE TITLE
Cant create a new room in the videroom demo [1.x]

### ISSUE THREAD

**Issue by Jay031** [meetecho/janus-gateway#2959]
**What version of Janus is this happening on?**
1.x

**Additional context**
Before I'm going to use Janus fully on my project, I would like to know if the server is able to enable rooms to be created easily.
When I use the 'create' request for a room against the demo version it gives no error, but when I try to join the room it says:

room 4343 (the one this demo uses as a test room) does not exist... Do you have an updated janus.plugin.videoroom.jcfg configuration file?

Does this mean I always have to write the new room to a new file and restart Janus?
Because I would like the server to just pick up requests for new rooms if I allow it. Or is it just a limitation of the demo?

Thanks in advance!

**Comment by liujianlou** [comment]
请仔细查看   https://janus.conf.meetecho.com/docs/videoroom.html

**Comment by lminiero** [comment]
Rooms can be created dynamically, we do it all the time. Please refer to the documentation (link in previous response) to see what to expect from a successful room create. Also notice that by default rooms are not persistent, meaning that if you restart Janus, rooms you created before won't be there anymore: again, the docs will tell you how to persist them instead.

Closing as not a code issue, please ask questions on the [group](https://groups.google.com/g/discuss-webrtc) if you still have doubts.
