### ISSUE TITLE
[1.x]When a person has multiple cameras and subscribes remotely, it is impossible to tell which one is.

### ISSUE THREAD

**Issue by liujianlou** [meetecho/janus-gateway#2961]
First of all, thanks to janus team. I am new to janus. I have a small problem at present: when someone has multiple cameras, creating multiple streams, remote track can't tell which camera it is. What I want to express is, according to the label of the camera, it plays to different divs. Is there any plan to add a tag when creating cameras? Remote track can distinguish according to this tag.
Thank you, I look forward to your reply.

**Comment by lminiero** [comment]
Any time you subscribe or update a subscription, the "updated" event contains a list of streams, who they come from, and the related `mid` in the PeerConnection. Use the `mid` from the `MediaStreamTrack` in the browser to know which stream it refers to. It's what we do in the demo as well. You can find more info in the documentation.

Closing as not a code issue, please ask further questions on the [group](https://groups.google.com/g/discuss-webrtc) instead.
