### ISSUE TITLE
FireFox shortly shows old video when unsubscribing and resubscribing to a different party (same mid)

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2970]
**What version of Janus is this happening on?**
8f048f8 (21.04.2022)

**Have you tested a more recent version of Janus too?**
No, did not see any changes related to the issue in the change log

**Was this working before?**
Don´t think so :)

I have a subscriber and then after another two publisher in the videoroom (in firefox)

1.)
The first publisher joines that room and publishes audio video.
The subscriber subscribes to his media.
The subscribing peerConnection is settled (offer answer ...), media is transported.
The publisher leaves the room.
The subscribing peerConnection is renegotiated "empty" (both tracks a=inactive)

2.)
A different publisher joines the room and publishes different audio video tracks into the room.
The subscriber subscribes to his media. (The subscription happens on the same mids as before)
On the client side i now see for about 1 second the old video of the 1.party (having left the room) then the new video of the 2. party (having joined the room)

This does not happen in chrome, i did not test any other chromium based browser.

In the beginning you could say this is a FireFox issue but then the thing about the track ids @fippo once mentioned came to my mind.
https://github.com/meetecho/janus-gateway/issues/2918#issuecomment-1064112024

The browser thinks, hey that track was there before. Let´s reuse it as it has the same stream and track id.

The only solution i currently see is delaying the displaying of a subscription on the firfox side if it is reusing an existing mid but thats kind of super ugly :\

Comments and hints welcome.

**Comment by lminiero** [comment]
We're not going to change the way we advertise streams/tracks in the SDP in the short term, as that's going to take a considerable refactoring, which would likely require some sort of cooperation between core and plugins: in fact, the core has no idea what each track is or what it's related to, that's something that only makes sense to plugins (e.g., audio n.3 and video n.5 coming from the same participant "Bob"). As such, for the time being I think whatever workaround you can come up with on the client side is probably the way to go.

I'll mark this as "enhancement" but to be honest I'm not sure when I'll start addressing it.

**Comment by JanFellner** [comment]
Thanks for the update.

I don´t know if plugin and core need to know the content of each track. I would have thought that using the feedID in combination with the publisher mid as string "feedID_mid" used for the track id in the sdp should be sufficient to have a unique identification for the client that it is a different track.

That would be an easy test if that solves the issue for firefox or not.

Or are plugin and core relying on the janus0-n names in the sdp against each other?

**Comment by JanFellner** [comment]
I want a callback - to ask the plugin about the wanted trackid...  😎
💣💥💢

**Comment by JanFellner** [comment]
Short update from my side.

I munged the SDP and added a dynamic id for the stream and track
a=msid:guid guid_mid

does not solve the issue -> firefox still plays the old track for about a second

Will try a different approach...

**Comment by lminiero** [comment]
We've added msid support in #2998. You can try testing that to see if that helps.

**Comment by JanFellner** [comment]
Just saw the update from your side.
I already played around with faking msid ids into the janus offer with sdp munging. The effect was the same.
We are now solving it by knowing if a mid is reused and we show the video delayed. It´s ugly and not working 100% but i see this as an issue of firefox and some internal caching

**Comment by lminiero** [comment]
Then I'll close, as I don't think there's anything else we can do about this.

**Comment by fippo** [comment]
well, one could page @jan-ivar and ask for help

**Comment by JanFellner** [comment]
⛑🆘 calling dr. @jan-ivar
