### ISSUE TITLE
[1.x] missing SIP-Contact-header on SUBSCRIBE-messages

### ISSUE THREAD

**Issue by doerner** [meetecho/janus-gateway#2973]
**What version of Janus is this happening on?**
Janus 1.0.1-r0 on alpinelinux

**Have you tested a more recent version of Janus too?**
no

**Was this working before?**
no

**Is there a gdb or libasan trace of the issue?**
no

**Additional context**
SIP-SUBSCRUBE messages (using the sip-plugin) do not contain the mandatory Contact-header.

**Comment by lminiero** [comment]
Sounds like something that should be fixed in Sofia SIP, if needed, not Janus, as we don't control the SIP logic. Please try a more recent version of Sofia SIP, if you have 1.2.11 installed, and reconfigure/recompile Janus.

**Comment by lminiero** [comment]
@doerner did you have a chance to try a more recent version of Sofia SIP as suggested?

**Comment by doerner** [comment]
The alpine Linux distribution uses by standard a more recent Sofia SIP package (1.13.7). This is as far as I know the current version.

**Comment by lminiero** [comment]
Then I'm afraid there's nothing we can do about that. Setting the Contact header is up to the stack when you use NUA.

**Comment by lminiero** [comment]
This should now be fixed, closing.
