### ISSUE TITLE
[0.x] Streaming Plugin: No RTCP Receiver Report / Error in sendto

### ISSUE THREAD

**Issue by sjkummer** [meetecho/janus-gateway#2975]
**What version of Janus is this happening on?**
v0.11.2

**Have you tested a more recent version of Janus too?**
no

**Was this working before?**
Not as I know

**Is there a gdb or libasan trace of the issue?**
no

**Additional context**

When using the streaming plugin, I do not see an RTCP receiver report from Janus to the RTP source.

Instead, the following error is logged:
```
[ERR] [plugins/janus_streaming.c:janus_streaming_rtcp_remb_send:1556] Error in sendto... 22 (Invalid argument)
```

Modes: `rtp` and `rtsp` 
OS: macOS and Ubuntu

`videortcpport` is set

RTP address is `::1` (loopback)

**Comment by sjkummer** [comment]
Same behavior on master:
```
[ERR] [plugins/janus_streaming.c:janus_streaming_rtcp_pli_send:1772] Error in sendto... 22 (Invalid argument)
```

**Comment by lminiero** [comment]
That's not how the RTCP support in the Streaming plugin works. The Streaming plugin will never send Receiver Reports. Besides, the port you specify is the port the plugin binds to, but it will be inactive until someone latches on to it: this means that the Streaming plugin must first receive a packet on that RTCP port, and only then it figures out who it should send RTCP ports to. The only packets that are relayed, though, are PLI and REMB, as we only use this feature for remotely asking for a keyframe (e.g., in conjunction with VideoRoom RTP forwarders, who perform the latching I mentioned above).

Closing as not an issue.

**Comment by sjkummer** [comment]
Thanks for the clarification regarding Receiver Reports.

I was able to fix the failed REMB and PLI packets: It's an IPv6 problem with the `addrlen` parameter of `sendto()`.

Can be fixed as follows:

```
	/* Prepare the recipient */
	struct sockaddr_in remote4 = { 0 };
	struct sockaddr_in6 remote6 = { 0 };
	socklen_t addrlen = stream->rtcp_addr.ss_family == AF_INET ? sizeof(remote4) : sizeof(remote6);
	/* Send the packet */
	int sent = 0;
	if((sent = sendto(stream->rtcp_fd, rtcp_buf, rtcp_len, 0,
			(struct sockaddr *)&stream->rtcp_addr, addrlen)) < 0) {
		JANUS_LOG(LOG_ERR, "Error in sendto... %d (%s)\n", errno, g_strerror(errno));
	} else {
		JANUS_LOG(LOG_HUGE, "Sent %d/%d bytes\n", sent, rtcp_len);
	}
```

I can create  PR later.

**Comment by lminiero** [comment]
> I was able to fix the failed REMB and PLI packets: It's an IPv6 problem with the `addrlen` parameter of `sendto()`.

Ah thanks, that has probably gone unnoticed for a while now! I suspect there are other parts of the code where we may have a similar issue, so I'll check if that's the case and fix those too.
