### ISSUE TITLE
[1.x] Use canvas in the janus.plugin.videoroom

### ISSUE THREAD

**Issue by liujianlou** [meetecho/janus-gateway#2979]
First of all, thanks to the janus team. I have been using janus for a while, and I currently see adding canvas to videos. The plugin in the example is' janus.plugin.echotest'. When I put it in the' janus.plugin.videoroom' plugin and published it, the createOffer specified stream as canvasStream, I can't get the picture when I subscribe remotely. Is this my usage problem or is it not supported in the' janus.plugin.videoroom' plugin? Looking forward to your reply

**Comment by lminiero** [comment]
Canvas is orthogonal to the plugin used, since it's still video as far as Janus is concerned. Not a code issue, so please ask these questions on the group: https://groups.google.com/g/meetecho-janus
