### ISSUE TITLE
Janus occasionally segfaults on disconnect (videoroom)

### ISSUE THREAD

**Issue by Eltiech** [meetecho/janus-gateway#298]
Compiled libwebsocket  and Janus(r641.85a1a99) just an hour or two ago. libsrtp is 1.5.2.

Running janus on my server with secure websockets, and debugging at level 6.

On my home machine I:

1) Open the vanilla(other than switching to secure websockets) videomcutest page with chrome with one webcam, and hit start, etc

2) Using another tab, or an entirely different browser(with a different webcam), on the same machine, I connect to the same page, do the same thing.

3) At this point both seem to be functioning normally, and sharing with eachother, and visible on a 3rd client if I want.

4) Wait a bit, hit stop, or close the tab on second browser, wait a minute or so.

Sometime it crashes then, other times it does not, and I have to reopen the tab, reshare, close, wait a bit again, but eventually it does crash.

Initially I was going to say in firefox, but then as I was typing and trying to replecate it a few more times, I was able to get it to crash with both connections via chrome. 

I've also been able to cause similar crashes while connected with firefox on my phone, sometimes even without closing(spotty cell connection maybe?)

Logs + traces(at end):

http://pastebin.com/EN9Ef8QH

http://pastebin.com/evFG3b7m

http://pastebin.com/b59g9q7h

**Comment by arjenveenhuizen** [comment]
We suffer from the same problem (same checkout, same dependencies versions, but we use non-secure websockets instead). At our side it is very hard to reproduce the problem (unfortunately I do not have any stack traces right now). I hope this is indeed the same problem and that it gets solved!

**Comment by lminiero** [comment]
It might be some hard to spot memory corruption issue that is occurring in your setup. This is definitely not happening to us, and we use Janus quite extensively, so your instructions are hard to replicate.

One way to investigate deeper might be to make use of AddressSanitizer, which helps detecting memory errors. Compared to valgrind, it has the advantage of being much faster (according to the specs, it should only slow down Janus by 2x, while Valgrind makes it sluggish as hell), but it requires you to recompile the project with their library as a dependency.

To give it a try, you need to have at least gcc 4.8 and install libasan if available in your repos. Once done that, reconfigure this way (of course change the configure options the way you chose them)

    CFLAGS="-fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-lasan" ./configure --prefix=/home/lminiero/janus-test/

then do a make clean and a new make + make install. Check with an ```ldd janus``` that libasan is part of the dependencies. If it is, just run Janus as usual and try to replicate the issue: AddressSanitizer should provide you with more detailed info on what went wrong.

That said, please use the latest version of Janus, if you're not already doing so. I have no intention of digging specific revisions to check what was wrong weeks ago .

**Comment by Eltiech** [comment]
Thank you, I'll certainly try that. Also, as I said, I was running a version I cloned and compiled just last night.

**Comment by lminiero** [comment]
> Thank you, I'll certainly try that. Also, as I said, I was running a version I cloned and compiled just last night.

Sorry, missed that part :wink: 
Ok, keep us posted.

**Comment by lminiero** [comment]
Updated the AddressSanitizer sample command line with an extra flag (```-g3```) as it should help get you line numbers in the error log.

**Comment by lminiero** [comment]
Please try again with this latest commit, and check the discussion in #297 on the motivations. If this fixes it for you too I'll close the issue.

**Comment by willbarrett** [comment]
We're loading it up on our staging environment right now. We'll let you know what we find out!

**Comment by Eltiech** [comment]
Seems fixed on my end! Used it with some friends for a few hours Saturday night, no crashes.

**Comment by Eltiech** [comment]
Also thanks for the info on AddressSanitizer. I'll look into using that for any future issues/reports.
