### ISSUE TITLE
[0.x] candidate gathering timeout

### ISSUE THREAD

**Issue by cfbraun** [meetecho/janus-gateway#2982]
**What version of Janus is this happening on?**
Version 0.12.2 8e450a097f5f0c7e9c034e954fbc709797521f1c

**Have you tested a more recent version of Janus too?**
No, as the relevant code is unmodified

**Was this working before?**
No

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
I am using Janus with the videoroom plugin on a server with multiple LAN interfaces. Interface eno2.30 has static IP on the Internet, Interface eno2.21 has private IP 172.21.0.1. Users are connecting either over the Internet or over local LAN. For local LAN to work I need to allow ICE on eno2.21. For external users behind some kinds of firewall, I need to use TURN on eno2.30. When I enable TURN, Janus (i.e. libnice) tries to find TURN candidates for both interfaces. As the TURN server can not respond to a private IP, libnice takes a long time before sending candidate-gathering-done. During this time Janus reports 'No candidates not gathered yet for stream??', even though some candidates have already been found and finally times out.

When replacing the test '!stream->cdone' with '!janus_full_trickle_enabled && !stream->cdone', ICE works fine with the above setup when enabling full_trickle.

**Comment by lminiero** [comment]
> When I enable TURN

Why are you enabling TURN on Janus? 99% of the times it's not needed:
https://janus.conf.meetecho.com/docs/FAQ.html#turn

**Comment by cfbraun** [comment]
Why we enabled TURN:

This was something we noticed while debugging some connectivity problems. A specific client (using Chrome 76 on Windows) is able to connect to the echotest plugin on our server, but when subscribing to a video room the client does not receive video. When connecting to the echotest plugin, Chrome would include relay candidates, but when answering the offer from the video room subscription (which did not include any relay candidates), Chrome would not trickle any relay candidates. When we enabled TURN for Janus, the subscription would include (trickled) relay candidates and Chrome would add them to it's candidate pairs. In the end this did not fix the problem (and we still don't understand it), but during this test we noticed the long delay.

> If you don't want Janus to block on candidates, enable full trickle instead

That is exactly what we did. Without enabling full trickle, Janus will output warnings pointing to that. With full trickle enabled these warnings were gone, but still Janus reported 'No candidates not gathered yet for stream??' until the TURN connection for 172.21.0.1 finally times out. That is what motivated the change we did. Janus actually does trickle the candidates, but waits in janus_ice_outgoing_traffic_handle until ICE has completed.

**Comment by lminiero** [comment]
> A specific client (using Chrome 76 on Windows) is able to connect to the echotest plugin on our server, but when subscribing to a video room the client does not receive video

As explained in the FAQ, this means the _client_ needs to configure TURN, not Janus. TURN for Janus itself is useless most of the times, and harmful in others (like yours).

**Comment by cfbraun** [comment]
Sorry if I was unclear. We DO configure TURN in the client, but without configuring TURN in Janus the browser does not trickle any relay candidates back to Janus (for the subscription). As mentioned above enabling TURN in Janus did make the browser use relay candidates, but this did not solve the initial problem. Thank you for your time!

**Comment by lminiero** [comment]
> without configuring TURN in Janus the browser does not trickle any relay candidates back to Janus (for the subscription)

This sounds like a client configuration problem, or a browser issue: a peer enabling TURN is never dependant on the other peer enabling TURN as well. The two TURN sessions would be completely independent of each other. I'd check if something is wrong in how the subscription PeerConnection is created, e.g., looking at the webrtc-internals there; you can also try setting a `iceTransportPolicy: 'relay` option to force TURN to see if it actually does. That said, please refer to the forum for info on this.
