### ISSUE TITLE
build instructions for nextcloud

### ISSUE THREAD

**Issue by hboetes** [meetecho/janus-gateway#2985]
Hi there,

thanks for the excellent instructions for building janus. Here's what I ran into whilst following them.

- The https://libwebsockets.org/ certificate had expired, so I could had to use the github mirror.
- The ./configure instructions show no option for changing the etc/ dir.
- You might want to add `User=janus` to the systemd config, and some instructions to set up a user for the janus account.
- This also forced me to copy the snakeoil cert elsewhere, somewhere where user janus could read. 
- I `chmod -R o-rwx /usr/local/etc/janus` and `chgrp -R janus /usr/local/etc/janus`
- Do you happen to know the specific requirements for building janus to get working support for nextcloud talk?
- I've added websockets and usrsctp and left out all other optional dependencies. It seems to work with nextcloud.

**Comment by lminiero** [comment]
Are you sure you opened the issue on the right repo? I suspect this was meant for the nextcloud project (which is not owned not mantained by us).

**Comment by hboetes** [comment]
yes

**Comment by lminiero** [comment]
Then I believe this is out of scope here. Please use the [group](https://groups.google.com/g/meetecho-janus) for discussing deployment related considerations.

**Comment by hboetes** [comment]
Personally I treat constructive feedback differently.
