### ISSUE TITLE
ICE connectivity issue while streaming from remote machine to Janus Gw installed in EC2 instnace

### ISSUE THREAD

**Issue by altanai** [meetecho/janus-gateway#299]
Hello Janus Team , Janus Gateway is one of the really kool things I have seen recently. Kudos for that  . Its very neat in streaming  from my local webcam using gstreamer to  local Janus gateway and I am able to see the webrtc stream on firefix . 
However as i try to install the janus gateway on AWS ec2 instance ( ubuntu ) and try to stream using my remote machine's webcam I have ICE connectivity issues. I tried to resolve them by adding my xirsys TURN credentials inside janus.js ,however even that didnt help the issue . 
Could you please direct so that I am successfully able to stream from remote webcam to janus gateway on EC2 instance .

**Comment by lminiero** [comment]
Please post on the meetecho-janus google group for questions like this:
https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md
