### ISSUE TITLE
[1.x] Adding new stream to existing connection

### ISSUE THREAD

**Issue by vlad-grigoryan** [meetecho/janus-gateway#2996]
**What version of Janus is this happening on?**
v1.0.2

**Have you tested a more recent version of Janus too?**
Yes, the latest one

I have created the Session with `janus.plugin.videoroom`
`janus = new Janus(
   {
      server: server,
      success: function() {
         // Attach to video room test plugin
         janus.attach(
            {
               plugin: "janus.plugin.videoroom",
               success: function(pluginHandle) {
                  // Create new Peer Connection
                  this.videoroomPlugin = pluginHandle;
                  ...

                   // send join request
                  var register = {
                     request: "join",
                     room: myroom,
                     ptype: "publisher",
                     display: username
                  };
                  plugin.send({ message: register });
                  `
   After this I have a successful Per connection    with 2 publishers
   In time call I am trying to make a second request: "join", to add a screen share stream to an existing connection , using the same plugin instance which used before for creating connection  
   `         var register = {
            request: "join",
            room: room,
            ptype: "publisher",
            display: screen + name
         };
         plugin.send({ message: register });
         `
 but I get an error  "Already in as a publisher on this handle". 
 is there any way to add new stream or track to an existing connection, without calling recreating new peer connection,(calling jauns.attach)

**Comment by lminiero** [comment]
That's not how you add another stream: "join" must be made only once. Please use the [group](https://groups.google.com/g/meetecho-janus) for usability or API questions, we only use github to track bugs.
