### ISSUE TITLE
Videoroom Subscription delivers 1Mbit/s data after firefox unpublishes a video track replacesTrack(null)

### ISSUE THREAD

**Issue by JanFellner** [meetecho/janus-gateway#2999]
In the multistreaming videoroom i have one publisher and one subscriber.
The publisher provides audio and video to the subscriber that is properly showing the video.

As soon as i unpublish the videoTrack through replaceTrack(null) (no sdp exchange on the publisher or subscriber side) the bitrate shortly drops but then instantly rises again to 1mbit.

This only happens if the publisher is using firefox, if the publisher is using chrome the birate drops to 0.
It does not depend on the subscribers browser (chrome and firefox look the same here)

It´s not the publisher that is creating the media, it looks like janus somehow does it (however...)

Bitrate on the publisher side after unpublishing the video track (goes down)
![grafik](https://user-images.githubusercontent.com/53753460/172878067-f7675ae8-8f1d-474c-8e7d-8c84e4408142.png)

Bitrate on the subscriber side. You can see the ramp up from simulcast and then the short drop on unpublishing.
![grafik](https://user-images.githubusercontent.com/53753460/172878393-1df12471-437e-40d6-9cda-b465d4426e9f.png)

Any idea how i can diagnose this issue a bit deeper?

Just build the bleeding edge janus to be sure it´s not already fixed (e5b25bb72ac50718afd8da56739e751b5c4a9a86) was the same with the version i used before (8f048f8002092b8fb55e48cd22e3776c155c58de)

Firefox is the current release version (101.0)

**Comment by lminiero** [comment]
I don't think there's anything to fix in Janus, especially if Chrome doesn't do it. The only thing Janus does is providing TWCC and optionally REMB feedback, but it's the browser that decides how much to send.

**Comment by JanFellner** [comment]
*HOW* ugly, the stats of the browser say, hey i am not longer sending media.
The extern tool shows, this shitty browser still sends media... Asking @fippo if he has an idea on that topic as muting using replaceTrack(null) is kind of the common way to my understanding and i am wondering that this happens in ff... (Continuing to investiage it...)

**Comment by JanFellner** [comment]
Closing it for now as not a janus issue (i would have actually wondered anyway where the bitrate should have come from...)

**Comment by fippo** [comment]
grab a unencrypted pcap and look what gets sent

**Comment by JanFellner** [comment]
No time to dig into it from the firefox side as no matter which issue none of them was adresse or likely won´t get addressed.

Solved it the same way as i currently disable certain simulcast layers where firefox is not supporting the active flag.
set encoder parameters maxbitrate=1, scaleResolutionDownBy=2000

Check this 
https://bugzilla.mozilla.org/show_bug.cgi?id=1676855 (also open since 2 years...)
