### ISSUE TITLE
Janus-Gateway WebRTC Resolution

### ISSUE THREAD

**Issue by BenJaziaSadok** [meetecho/janus-gateway#300]
I installed Janus-WebRTC gateway on ubuntu server and started created a multiuser chat and broadcast. When is run this example Janus echotest example In my own server i always getting a bad resolution 640x480 whatever my uploading bandwidth. I tried to change default values on janus.js but without results.

Another info that may help. When i run janus and run the echotest exemple i get this warning

    [WARN] Getting a lot of NACKs (slow uplink) for video, forcing a lower REMB: 65536

Are there a way to handle this to allow the best resolution?

**Comment by lminiero** [comment]
First of all, don't change default values in janus.js: there are flags to ask for higher resolution,

http://janus.conf.meetecho.com/docs/JS.html (look for createOffer)

that said, lot of NACKs mean heavy packet loss. Browsers adapt the resolution according to the available bandwidth, so if it's not enough they'll reduce the resolution accordingly: there's nothing you can do to prevent that.

**Comment by lminiero** [comment]
PS: not a question for the github issues. Please continue this conversation on the meetecho-janus google group instead: https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md
