### ISSUE TITLE
RTSP Not working on latest version

### ISSUE THREAD

**Issue by meduar** [meetecho/janus-gateway#3001]
I am using the JANUS latest version.

I am trying to set up an RTSP it doesn't work it shows a loop of errors that don't stop(I have to kill the JANUS process), I tried different things different configs, and the RTSP feed has been tested it is visible with VLC.

My configurations are:
*****janus.jcfg***
media: {
	ipv6 = false
}
*****janus.transport.http.jcfg***
general: {
	http = true
	port = 8088
	interface = "wlan0"
	ip = "0.0.0.0"
}
********janus.plugin.streaming.jcfg*********
rtsp-test: {
	type = "rtsp"
	id = 99
	description = "RTSP Test"
	audio = false
	video = true
        videoiface="wlan0" # I have tried with and without and something like this         videoiface="0.0.0.0"
	url = "rtsp://0.0.0.0:8554/unicast" # I have tried 127.0.0.1, ip: 192.168.1.104	
}
************************************************************************************************************
I modified the line of code where the error is shown for something like this: 
file: janus_streaming.c line: 6575
JANUS_LOG(LOG_ERR, "[%s] Cannot create socket for %s... %d (%s) gigo: %d - %d - %d \n", mountpointname, medianame, errno, g_strerror(errno), family, SOCK_DGRAM, IPPROTO_UDP);

Variables that I am printing additionally:
**family:0
SOCK_DGRAM:1
IPPROTO_UDP:17**

************************************************************************************************************
Error messages:
v=0
o=- 1655037437581138 1 IN IP4 192.168.1.104
s=LIVE555 Streaming Media v2020.05.15
i=LIVE555 Streaming Media v2020.05.15
t=0 0
a=tool:LIVE555 Streaming Media v2020.05.15
a=type:broadcast
a=control:*
a=range:npt=0-
a=x-qt-text-nam:LIVE555 Streaming Media v2020.05.15
a=x-qt-text-inf:LIVE555 Streaming Media v2020.05.15
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:168
a=rtpmap:96 H264/90000
a=fmtp:96 profile-level-id=4d401f;sprop-parameter-sets=Z01AH52oFAFuhAAAAwAEAAADAMoQ,aO48gA==
a=x-dimensions:1280,720
a=control:track1
m=audio 0 RTP/AVP 14
c=IN IP4 0.0.0.0
b=AS:168
a=fmtp:14
a=control:track2
**[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6575] [rtsp-test] Cannot create socket for video... 124 (Address family not supported by protocol) gigo: 0 - 1 - 17
[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6575] [rtsp-test] Cannot create socket for video... 124 (Address family not supported by protocol) gigo: 0 - 1 - 17**
....
************************************************************************************************************
Any Idea what could it be? please help, I have already tried for days it doesn't work.

**Comment by meduar** [comment]
The system I am using is LINUX

There is an issue in the code in the line 6572
fd = socket(family == AF_INET ? AF_INET : AF_INET6, SOCK_DGRAM, IPPROTO_UDP);

the variable family at this point is 0, by default is 0, and is never going to be 4

family == AF_INET ? AF_INET : AF_INET6
so always is going to be set to 6, IPV4 is never going to work

I fixed the code now it is setting the variable family to 2
.............................................................. after fixing this line I am getting ************
[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6572] Horse: 10[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6582] [rtsp-test] setsockopt on socket failed for video... 99 (Protocol not available)
[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6572] Horse: 10[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:6582] [rtsp-test] setsockopt on socket failed for video... 99 (Protocol not available)
* Found bundle for host: 0x6a3118 [serially]
* Re-using existing connection #0 with host 0.0.0.0
* Connected to 0.0.0.0 (127.0.0.1) port 8554 (#0)
> SETUP rtsp://[127.0.0.1:8554/unicast/track1](http://127.0.0.1:8554/unicast/track1) RTSP/1.0
.............................................................. after fixing this line I am getting ************

Reconnected to the RTSP server, streaming again

Anyway even after fixing it, it still doesn't work properly

**Comment by lminiero** [comment]
The code is correct: we default to IPv6 sockets by default, because binding to IPv6 implicitly binds to IPv4 as well. If you want to force IPv4, you should specify an interface for both audio and video when creating the RTSP mountpoint:

https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.streaming.jcfg.sample.in#L28
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.streaming.jcfg.sample.in#L36

The links above are the documentation for creating mountpoints in configuration files, but the syntax is the same when using the API. If you specify a valid interface or its IPv4 address, that one will be passed, and family will be different than 0.

**Comment by lminiero** [comment]
0.0.0.0 won't work, you'll need an existing IP address. Anyway, I see you wrote on the group as well, where this belongs, since it looks like a configuration issue and not a problem in the code, so this can be discussed there.
