### ISSUE TITLE
mutliple stun servers

### ISSUE THREAD

**Issue by dennisTGC** [meetecho/janus-gateway#3006]
Hi I'm a bit concerned about janus exiting when a stun server is not reachable. I know it's been discussed in issue #987, but is there a way to setup multiple stun servers? I couldn't find any documentation on it. We rely on stun.nextcloud.com, but I would like to setup another source as stun.nextcloud.com was down this weekend. 

Also, is setting a stun server still required when using the parameter `nat_1_1_mapping`?

**Comment by lminiero** [comment]
You can tell Janus not to exit when the STUN server isn't reachable:
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.jcfg.sample.in#L387-L395

On multiple STUN servers, you can only set 1 in libnice.

**Comment by dennisTGC** [comment]
Most excellent.. I've been reading so much, I seem to have missed that. Sorry for taking your time and great effort!
