### ISSUE TITLE
[1.x] Docker image TLS data not flushed through correctly until timeout

### ISSUE THREAD

**Issue by NickHoath** [meetecho/janus-gateway#3017]
**What version of Janus is this happening on?**
Janus version: 1004 (1.0.4)
Janus commit: d884b2a9d978e18514bf2fbaddc19cc3e1cc03a9
Compiled on:  Mon Jul  4 04:06:49 UTC 2022
Docker: FROM canyan/janus-gateway:master

Janus commit: 04229be3eeceb28dbc57a70a57928aab223895a5
Compiled on:  Mon Nov  2 16:22:05 UTC 2020

janus 0.10.7
Docker: FROM canyan/janus-gateway:latest

**Have you tested a more recent version of Janus too?**
Tested with 0.1.17 same issue
Tested with 1.0.4 same issue

**Was this working before?**
Don't know

**Additional context**
This might be down to the docker image...

Here's a curl to the HTTPS port:
curl -k --request POST   --url https://servername:8089/janus   --header 'Content-Type: application/json'   --data '{"janus":"create","transaction":"JNM3mw7r0zwa","apisecret":"janusrocks"}'
{
   "janus": "success",
   "transaction": "JNM3mw7r0zwa",
   "data": {
      "id": 1417347273745026
   }
curl: (18) transfer closed with outstanding read data remaining
}

Here's a curl to the HTTP port:
curl -k --request POST   --url http://valerion.co.uk:8088/janus   --header 'Content-Type: application/json'   --data '{"janus":"create","transaction":"JNM3mw7r0zwc","apisecret":"janusrocks"}'
{
   "janus": "success",
   "transaction": "JNM3mw7r0zwc",
   "data": {
      "id": 6550631623996452
   }
}

Same issue seen from web client, as well has in house code.

**Comment by NickHoath** [comment]
NB: Will try some of the other docker containers.

**Comment by lminiero** [comment]
We don't provide any Docker image in this repo, so I think this is out of scope here. If you can replicate the problem in a normal installation of Janus, please feel free to reopen.
