### ISSUE TITLE
Ice Restart Fails After Hangup for Subscriber in Videoroom[1.x]

### ISSUE THREAD

**Issue by rahmanash-dbz** [meetecho/janus-gateway#3021]
When a peerconnection Hangup , let's say after DTLS Timeout , and when trying ice restart to this handle, it is not giving an offer as expected. It's because of setting subscriber->answered as 0 in hangup_media_internal (Line 7629). And, when trying ice restart, since 0 denotes waiting for  an offer, it is not proceeding (line 9975) and hence ice restart never happens 

Is it the intended behaviour and have to create a new plugin for proceeding further ? or is it a bug ? Please shed some light on this
Thanks

**Comment by lminiero** [comment]
If a PeerConnection was hang up, you can't restart it. You can only recover from an ICE failed state, not from a DTLS alert.
