### ISSUE TITLE
Issue with live stream on connection switch (WiFi -> 4G)

### ISSUE THREAD

**Issue by romenov** [meetecho/janus-gateway#3029]
When the stream is playing and the connection switches between WiFi and mobile data, the stream stops and won't start again (not even when switching back to WiFi).

This can be reproduced on the Plugin Demo: Streaming with the Opus/VP8 livestream (currently on ios 15.5 but have observerd it on older versions)

**Comment by lminiero** [comment]
ICE restarts are up to the application. Please ask further guidance on the group, not here, since there's no bug to fix.
