### ISSUE TITLE
Combine two livestreams

### ISSUE THREAD

**Issue by mjnk9xw** [meetecho/janus-gateway#3030]
how can i combine 2 live streams with video stream 1 on the left, video stream 2 on the right and 1 audio stream output to a new live stream. thanks

**Comment by lminiero** [comment]
If you're talking about videomixing, no plugin supports that in Janus. You'll have to forward the media somewhere else for the job. That said, this is out of scope here, so please ask on the [group](https://groups.google.com/g/meetecho-janus) instead.
