### ISSUE TITLE
[1.0.4] Janus VideoRoom bitrate crash (segfault)

### ISSUE THREAD

**Issue by kuba-pb** [meetecho/janus-gateway#3033]
**What version of Janus is this happening on?**
https://github.com/meetecho/janus-gateway/tree/v1.0.4
```
"name": "Janus WebRTC Server",
"version": 1004,
"version_string": "1.0.4",

 "dependencies": {
    "glib2": "2.66.8",
    "jansson": "2.13.1",
    "libnice": "0.1.19",
    "libsrtp": "libsrtp2 2.4.2",
    "libcurl": "7.74.0",
    "crypto": "OpenSSL 1.1.1n  15 Mar 2022"
  },
  
"janus.plugin.videoroom": {
      "name": "JANUS VideoRoom plugin",
      "author": "Meetecho s.r.l.",
      "description": "This is a plugin implementing a videoconferencing SFU (Selective Forwarding Unit) for Janus, that is an audio/video router.",
      "version_string": "0.0.9",
      "version": 9
    },
```

**Was this working before?**
It does not crash on version `0.11.6`

**Is there a gdb or libasan trace of the issue?**
https://gist.github.com/kuba-pb/881d66c2c6ce74477bf58ae0cef01e42

**Additional context**
On setting video bitrate: 256000 by the web client, the janus server crash (segfault).
Link to ASan trace: https://gist.github.com/kuba-pb/881d66c2c6ce74477bf58ae0cef01e42

**Comment by atoppi** [comment]
Unable to repro on `1.0.4` and `master`, tested with 4 participants (videoroom and multistrem videoroom test pages).
@kuba-pb are you able to reproduce the issue?

**Comment by kuba-pb** [comment]
Yep, we've already crashed janus server 3 times.

**Comment by atoppi** [comment]
Level 5 is a good start for troubleshooting.
Please enable log timestamps in janus.jcfg.

Could you have missed some important details about the scenario? e.g.:
- how many participants ?
- how many media published per participant ?

Try to provide some more details about your application and the interaction with janus.

**Comment by lminiero** [comment]
@kuba-pb any update? Otherwise, since we can't replicate, we'll just close the issue.

**Comment by kuba-pb** [comment]
@lminiero - I'll try to get some _step_by_step_ scenario from frontend (where js client is used), otherwise I can modify http plugin and dump http requests  and also tcp dump (if it can be helpful).

**Comment by kuba-pb** [comment]
@lminiero - I got some extra info from frontend team.
 
Client sends request asking for a bitrate:
```
plugin.send({ message: { request: 'configure', bitrate: 512000 } })
```
from plugin which does not publish/transfer any video (only subscribe to video room plugin).

In previous version (before 1.X), Janus just ignored this kind of requests. In the current one we get a segmentation fault.

**Comment by lminiero** [comment]
Just tried sending that request on an audio-only handle in the VideoRoom and it works just fine. I also tried unpublishing, so that the handle is only used to receive presence information (no PeerConnection) and it didn't crash either.

**Comment by lminiero** [comment]
> Link to ASan trace: https://gist.github.com/kuba-pb/881d66c2c6ce74477bf58ae0cef01e42

Mh looking at the asan trace you shared a few weeks ago, it may be a missing NULL check on `handle->pc` in `janus_ice_relay_rtcp`, which we do have in `janus_ice_relay_rtp` and `janus_ice_relay_data`. I'll push a fix that you can try.

**Comment by lminiero** [comment]
@kuba-pb can you pull the latest master to see if the commit above fixes the problem for you?

**Comment by kuba-pb** [comment]
Btw. are you planning to release a new version (1.0.5 or 1.1.0) with this fix?

**Comment by lminiero** [comment]
@tjaniczek a scenario could still help, especially if this fix is just making it harder to happen! I'll close the issue in the meanwhile, but if you can provide a way to replicate the problem with 1.0.4 that would be appreciated.

@kuba-pb we did a release before the summer break and only did a few commits since, we'll wait for more substantial changes before tagging a new version.
