### ISSUE TITLE
[1.x] The RTSP stream cannot authorizing.

### ISSUE THREAD

**Issue by cjy123cjy** [meetecho/janus-gateway#3038]
**What version of Janus is this happening on?**
1.0.4

**Have you tested a more recent version of Janus too?**
Yes, 1.0.0

**The background**
I am working on a hikvision IP camera, and here is my configurations:
```
rtsp-test: {
     type = "rtsp"
     id = 99
     description = "RTSP Test"
     audio = false
     video = true
     url = "rtsp://172.22.0.14:554/Streaming/Channels/101"
     rtsp_user = "${user}"
     rtsp_pwd = "${pwd}"
     secret = "adminpwd"
     rtsp_reconnect_delay = 5
     rtsp_session_timeout = 0
     rtsp_timeout = 10
     rtsp_conn_timeout = 5
 }
```

**My issue**
The RTSP stream works well at VLC and another open-source projects. But I got the following error at janus:
```
Loading plugin 'libjanus_streaming.so'...
[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:7249] Couldn't get DESCRIBE code: 401
[ERR] [plugins/janus_streaming.c:janus_streaming_init:2603] Error creating 'rtsp' mountpoint 'rtsp-test'...
JANUS Streaming plugin initialized!
```

I searched in the repo and found this issue: [Unable to authenticate RTSP stream](https://github.com/meetecho/janus-gateway/issues/839). However, it did not quite conclude the reason. Could you give me some ideas? Thanks a lot!

**Comment by atoppi** [comment]
First of all, try to use a recent libcurl.
Then, as Lorenzo mentioned in #839
> we're bound to what libcurl provides in terms of RTSP authentication, which is probably not much

Probably there is some kind of (unsupported) challenge going on in the authentication process.
You could also observe a wireshark dump for both working / not working setups, maybe you could spot the reason of the failure.

**Comment by lminiero** [comment]
> First of all, try to use a recent libcurl

Actually, this is one of the few instances where upgrading may not be recommended. RTSP authentication has been broken in curl for a long time, but there were workarounds that could get it to still work until version 7.78.0. Versions older than that will nor do proper RTSP authentication, so if a recent version of libcurl is installed, downgrading should get RTSP auth to work again.

**Comment by cjy123cjy** [comment]
Got you. Now my curl version is 7.68.0, then I'm going to downgrade it to a appropriate version. However, its version should not lower than 7.45.0 right? 
You can close the issue first and I'll reply if the issue is fixed. Thanks for your help again!

**Comment by lminiero** [comment]
7.68 should be fine as it's older than 7.79 (which is the one that definitely broke auth for me).

**Comment by Tyler-2** [comment]
I'm told that 7.87 fixes this. But I've never had Janus working soooo...

**Comment by connortechnology** [comment]
7.87 in ubuntu lunar appears to still not work.

**Comment by AleXoundOS** [comment]
Combination of janus-gateway with curl 7.74 does work with RTSP authorization.

**Comment by baudneo** [comment]
Latest master branch of curl fixes the RTSP auth issue.

**Comment by sanjayb157** [comment]
[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:8411] Couldn't get DESCRIBE code: 401

curl -V
curl 7.74.0-DEV (x86_64-pc-linux-gnu) libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.18

./bin/janus -V
Janus version: 1400 (1.4.0)
Janus commit: d0f6bdd46a7f4c3557942ab4450be918d8d62531

Pls guide

**Comment by sanjayb157** [comment]
done with  curl -V curl 7.74.0 and 

url = "rtsp://admin:sili476@192.168.1.121:554/stream1"
#rtsp_user = "admin"
#rtsp_pwd = "sili476"
