### ISSUE TITLE
Add ability to disable logging colors

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#304]
When running Janus as a service (though systemd, PR coming!) the generated log lines contain the ANSI escape codes, resulting in output like this:

~~~~
Aug 10 12:06:46 node03 janus[20544]: HTTP webserver started (port 8088, /janus path listener)...
Aug 10 12:06:46 node03 janus[20544]: #033[33m[WARN]#033[0m HTTPS webserver disabled
Aug 10 12:06:46 node03 janus[20544]: WebSockets server started (port 8188)...
Aug 10 12:06:46 node03 janus[20544]: #033[33m[WARN]#033[0m Secure WebSockets server disabled
Aug 10 12:06:46 node03 janus[20544]: #033[33m[WARN]#033[0m RabbitMQ support not compiled
Aug 10 12:06:46 node03 janus[20544]: #033[33m[WARN]#033[0m Admin/monitor HTTP webserver disabled
Aug 10 12:06:46 node03 janus[20544]: #033[33m[WARN]#033[0m Admin/monitor HTTPS webserver disabled
~~~~

It would be nice if a command like switch (--disable-colors perhaps) woud disable this behavior. Thanks!

**Comment by lminiero** [comment]
Makes sense, I'll work on this when I get back to work on Monday.

**Comment by lminiero** [comment]
This commit should do it: it's either ```debug_colors=no``` in the config file, or a ```-o``` on the command line. Let me know if that's not working as expected for you!
