### ISSUE TITLE
[1.x] janus-pp-rec on av1 record

### ISSUE THREAD

**Issue by DomrachevIvan** [meetecho/janus-gateway#3040]
**What version of Janus is this happening on?**
janus-1.0.4

**Have you tested a more recent version of Janus too?**
same results on last master commit 4346c1ad387fa0a710a45d978ee980d83a756caa

**Was this working before?**
i do not know

**Additional context**
created room with:
"videocodec":"av1",
"record":true,
"rec_dir"...
started translation. got video-1.mjr file.
and if i try to do

> $ janus-pp-rec video-1.mjr video-1.mkv
> Janus version: 1004 (1.0.4)
> Janus commit: not-a-git-repo
> Compiled on:  Wed Aug 24 11:03:15 MSK 2022
> 
> Logging level: 4
> 
> Source file: videoroom-1234-user-2476588066334211-1661328032023786-video-1.mjr
> Target file: videoroom-1234-user-2476588066334211-1661328032023786-video-1.mkv
> 
> File is 1167817 bytes
> Pre-parsing file to generate ordered index...
> Video orientation extension ID: 13
> This is a video recording:
>   -- Codec:   av1
>   -- Created: 1661328032023790
>   -- Written: 1661328032677489
> SSRC detected: 2071001781
> Counted 1369 RTP packets
> Counted 1369 frame packets
>   -- Detected new resolution: 320x240 (seq=1)
> [   0.000s] Video rotation: 0 degrees
>   -- Detected new resolution: 480x360 (seq=123)
>   -- Detected new resolution: 640x480 (seq=191)
>   -- 640x480 (fps [2790,9090] ~ 32)
> First keyframe: 0
> ESC[31m[ERR]ESC[0m [postprocessing/pp-av1.c:janus_pp_av1_process:503] Error writing video frame to file... (error -1094995529)
> ESC[31m[ERR]ESC[0m [postprocessing/pp-av1.c:janus_pp_av1_process:503] Error writing video frame to file... (error -1094995529)
> ESC[31m[ERR]ESC[0m [postprocessing/pp-av1.c:janus_pp_av1_process:503] Error writing video frame to file... (error -1094995529)
> ESC[31m[ERR]ESC[0m [postprocessing/pp-av1.c:janus_pp_av1_process:503] Error writing video frame to file... (error -1094995529)
> ...
> 

last line repeated many times and result .mkv file is 631 bytes length (as i see its only header).

**Comment by lminiero** [comment]
Looking around `1094995529` seems to be an "Invalid data" error (I'll have to add calls to `av_err2str` to make error reporting clearer). That said, I just tested it myself with an AV1 MJR and it works fine. If you can share the MJR file, that might help.

**Comment by lminiero** [comment]
The commit in https://github.com/meetecho/janus-gateway/commit/b0b8ffcb5aad4f816dcc73ae68cc57e75e6feccb should add some more precise info when getting errors like those, can you try with that one?

**Comment by DomrachevIvan** [comment]
```
$ janus-pp-rec videoroom-1234-user-8053437905630854-1661845842027758-video-1.mjr videoroom-1234-user-8053437905630854-1661845842027758-video-1.mkv
Janus version: 1100 (1.1.0)
Janus commit: not-a-git-repo
Compiled on:  Tue Aug 30 10:42:26 MSK 2022

Logging level: 4

Source file: videoroom-1234-user-8053437905630854-1661845842027758-video-1.mjr
Target file: videoroom-1234-user-8053437905630854-1661845842027758-video-1.mkv

File is 407289 bytes
Pre-parsing file to generate ordered index...
Video orientation extension ID: 13
This is a video recording:
  -- Codec:   av1
  -- Created: 1661845842027766
  -- Written: 1661845843542068
SSRC detected: 934225452
Counted 377 RTP packets
Counted 377 frame packets
  -- Detected new resolution: 320x240 (seq=1)
[   0.000s] Video rotation: 0 degrees
  -- Detected new resolution: 480x360 (seq=360)
  -- 480x360 (fps [6390,7380] ~ 14)
First keyframe: 0
[ERR] [postprocessing/pp-av1.c:janus_pp_av1_process:504] Error writing video frame to file... (error -1094995529, Invalid data found when processing input)
[ERR] [postprocessing/pp-av1.c:janus_pp_av1_process:504] Error writing video frame to file... (error -1094995529, Invalid data found when processing input)
[ERR] [postprocessing/pp-av1.c:janus_pp_av1_process:504] Error writing video frame to file... (error -1094995529, Invalid data found when processing input)

```
[videoroom-1234-user-8053437905630854-1661845842027758-video-1.mjr.zip](https://github.com/meetecho/janus-gateway/files/9450885/videoroom-1234-user-8053437905630854-1661845842027758-video-1.mjr.zip)

**Comment by lminiero** [comment]
Looks like the problem is postprocessing to .mkv: I first postprocessed to .mp4 without errors, trying to do the same with .mkv fails. Probably writing AV1 is not properly supported in MKV files, so I'll just disable the functionality.

**Comment by DomrachevIvan** [comment]
mp4 is fine. such a simple solution, but I didn't guess. thank you!
