### ISSUE TITLE
[1.x] CURLOPT_ERRORBUFFER not being used in libcurl requests

### ISSUE THREAD

**Issue by jp-bennett** [meetecho/janus-gateway#3043]
CURLOPT_ERRORBUFFER isn't being allocated or set, so when CURL errors happen, we miss out on some possible further information. This could be added to both 1.x and 0.x. See https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html or more info.

For context, we're getting 
`[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:5324] Couldn't send DESCRIBE request: Unsupported protocol`
when trying to connect to a camera, and have yet to figure out the root cause. The error buffer might have a bit more info.

**Comment by atoppi** [comment]
According to curl docs
```
Consider CURLOPT_VERBOSE and CURLOPT_DEBUGFUNCTION to better debug and trace why errors happen.
```
We [already set CURLOPT_VERBOSE](https://github.com/meetecho/janus-gateway/blob/c319024609509c74a7c3df1b9849533aaa9b3955/src/plugins/janus_streaming.c#L7438) if janus log level is more verbose than INFO (e.g. >= 5).

Have you tried setting janus log level to 5 ?

**Comment by jp-bennett** [comment]
> Have you tried setting janus log level to 5 ?

It was set to 7, and still didn't get a verbose error message. But if CURLOPT_ERRORBUFFER isn't set, CURL isn't going to send a detailed message. curl_easy_strerror() just returns a static string associated with the CURL errornum.
See: https://curl.se/libcurl/c/curl_easy_strerror.html

**Comment by lminiero** [comment]
I guess that it does need to be allocated, since if we just use a static buffer that would fail since we use the same curl instance from multiple functions. I'll see if this can be added easily to the RTSP struct stuff.

**Comment by atoppi** [comment]
@jp-bennett 
> It was set to 7, and still didn't get a verbose error message.

By default libcurl [will send ](https://curl.se/libcurl/c/CURLOPT_VERBOSE.html)the verbose information to `stderr`.
Were you reading that output too?

**Comment by lminiero** [comment]
@jp-bennett can you check the PR above?

**Comment by jp-bennett** [comment]
> @jp-bennett can you check the PR above?

Looks good. I'll try to give it a test run later today, too.

**Comment by lminiero** [comment]
@jp-bennett any update?

**Comment by jp-bennett** [comment]
@lminiero Looks like it does give some extra information. Did some brief testing, and seems to work. Looks good!

**Comment by lminiero** [comment]
Thanks! I'll merge then.
