### ISSUE TITLE
Audiobridge leave event not broadcasting to the room participants

### ISSUE THREAD

**Issue by igorMIA** [meetecho/janus-gateway#3050]
**What version of Janus is this happening on?**
v0.11.8  Janus commit: 21a5fc91d2c508481b9173e474a8688d615fd580

**Have you tested a more recent version of Janus too?**
Nope

**Was this working before?**
Nope

**Is there a gdb or libasan trace of the issue?**
Nope

**Additional context**
When using `AudioBridge` plugin(im using one WS connection for all users in a room) with a room that has 2 joined users, when a user sends leaving, according to the [doc](https://janus-legacy.conf.meetecho.com/docs/audiobridge.html) i should receive 1 event for who leaves and 1 for whom stays in a room `All the participants will receive an event notification with the ID of the participant who just left`. But im receiving only one event for who leaves.

I misunderstand something or else? Thanks!

**Comment by atoppi** [comment]
https://github.com/meetecho/janus-gateway/blob/0.x/plugins/janus_audiobridge.c#L7333

Any other participant should receive a message like this
```
"audiobrige": "event",
"room": THE_ROOM_ID,
"leaving": THE_PARTICIPANT_ID
```

whereas the leaving participant should receive
```
"audiobrige": "left",
"room": THE_ROOM_ID,
"id": THE_PARTICIPANT_ID
```

**Comment by igorMIA** [comment]
I see now.
That receives leaving user:

`{'janus': 'event', 'session_id': 6164516361380486, 'transaction': 'e7a01172-0a36-450d-bb7c-51eb30013046', 'sender': 47215404790115, 'plugindata': {'plugin': 'janus.plugin.audiobridge', 'data': {'audiobridge': 'left', 'room': 2, 'id': 1}}}`

Those other ones:

`{'janus': 'event', 'session_id': 2407871138680013, 'sender': 289527480273898, 'plugindata': {'plugin': 'janus.plugin.audiobridge', 'data': {'audiobridge': 'event', 'room': 2, 'leaving': 1}}}`

`{'janus': 'event', 'session_id': 2857233047145284, 'sender': 1032066145458512, 'plugindata': {'plugin': 'janus.plugin.audiobridge', 'data': {'audiobridge': 'event', 'room': 2, 'leaving': 1}}}`

Make sense! Thanks!
May i suggest editing the doc for this part, to make it more specific, or it's not a big deal?

**Comment by atoppi** [comment]
> May i suggest editing the doc for this part, to make it more specific

Thanks for the suggestion, the doc has been updated.
