### ISSUE TITLE
[1.x] Demos fail (possibly due to no IPv6?)

### ISSUE THREAD

**Issue by iam-TJ** [meetecho/janus-gateway#3052]
The bug report template doesn't lend itself to this report so going free-form!

First time encountering Janus and thinking it could be useful I tried the demos, specifically:

https://janus.conf.meetecho.com/streamingtest.html

But none produced any media.

This is on Debian 11 Buster amd64 with Firefox 104.0.1, and then testing again with a clean install of Chromium v105.0.5195.52, all on kernel v5.19.6.

I opened up the Dev tools on Firefox and discovered the following clues which make me suspect this is due to lack of IPv6 support for the the demo server.

```
ICE state changed to failed streamingtest.js:70:16
WebRTC: ICE failed, add a TURN server and see about:webrtc for more details
```

I operate IPv6-only networks but with a DNS64/NAT64 gateway. My suspicion is that the demo is expecting IPv4 connectivity and is not binding to IPv6 sockets or has no `AAAA` DNS records? This seems to be confirmed since my local DNS resolver shows one of my NAT64 addresses is mapped for an `AAAA` lookup of `janus.conf.meetecho.com` :

```
$ resolvectl query janus.conf.meetecho.com
janus.conf.meetecho.com: 217.61.26.66          -- link: PUBLIC
                         2a01:7e00:e001:ee64::d93d:1a42 -- link: PUBLIC
                         (venus.conf.meetecho.com)
```

**Comment by lminiero** [comment]
venus.conf.meetecho.com is the web server hosting the demos, not the server hosting Janus. Janus is hosted on a different server (fronted by venus for signalling, so it looks like it's still venus) and that server does indeed not have IPv6. Janus does support IPv6 if the server does, though. Closing as not an issue.
