### ISSUE TITLE
[1.x]

### ISSUE THREAD

**Issue by techwipes** [meetecho/janus-gateway#3053]
**What version of Janus is this happening on?**
v 1.0.4

**Have you tested a more recent version of Janus too?**
Yes v 1.0.3

**Was this working before?**
Yes, I had no problem before 2nd of September

**Additional context**
Hello Janus team!
I had some problem with compiling Janus during building docker image. Was using my docker file about 2 last years without any problem. And since last Friday (2 September 2022) I got a lot of logs with errors. Some of them related with open ssl 3.0, I am using Ubuntu 22.04 for my image.

![image](https://user-images.githubusercontent.com/60771543/188429932-938d1d10-8b24-4197-b603-c7f61af47fe9.png)

I have rolled back for openssl 1.1.1, but it didn`t helps me, got the same error.

With best regards!

**Comment by atoppi** [comment]
already fixed in https://github.com/meetecho/janus-gateway/commit/48549ab4b1c8492b01c5edad6689d738a9c63a7b
