### ISSUE TITLE
[1.x] audiobridge: possible race condition on room mute/unmute

### ISSUE THREAD

**Issue by RSATom** [meetecho/janus-gateway#3065]
**What version of Janus is this happening on?**
master

**Have you tested a more recent version of Janus too?**
I didn't test, but looked to sources, and believe issue was added by https://github.com/meetecho/janus-gateway/commit/e2a76ed66e71347478d29e8e2b0b790339563137

**Was this working before?**
I believe yes, before https://github.com/meetecho/janus-gateway/commit/e2a76ed66e71347478d29e8e2b0b790339563137

**Is there a gdb or libasan trace of the issue?**
No. I didn't get any crash/issue myself, I just was looking in sources and found it.

**Additional context**
I'm still not sure 100% I didn't miss something, but I think I found possible race condition in `audiobridge` plugin.
The problem is here: https://github.com/meetecho/janus-gateway/blob/38f8b707da3b2bc63c46ecf9d09589aea4fd658e/src/plugins/janus_audiobridge.c#L4167

and here: https://github.com/meetecho/janus-gateway/blob/38f8b707da3b2bc63c46ecf9d09589aea4fd658e/src/plugins/janus_audiobridge.c#L6857

at the first place it has `audiobridge->mutex` locked, but it has no any lock at the second place (it locks `audiobridge->mutex` later, to send notification to room's participants). So I believe it can lead to race condition if admin will try mute/unmute user at the same time as user. 

Can you please confirm I didn't miss something?

**Comment by lminiero** [comment]
I'll have a look and get back to you, thanks for spotting this!

**Comment by RSATom** [comment]
FYI I've prepared [patch](https://github.com/RSATom/janus-gateway/commit/dbb9604478f15f4e14b9304d2214f061a37c803d) but didn't test it well yet...

**Comment by lminiero** [comment]
From a quick glance it looks ok. I had a look at the code yesterday, but first wanted to understand if there could be problems mixing the audiobridge mutex with the participant's qmutex: it shouldn't be the case, but I wanted to double check. I had to work on something different yesterday, though, so I didn't finish checking.

Please let me know how your patch tests, and if you notice any problem or regression! In case it looks like it's working ok, feel free to submit it as a PR and we'll merge.

**Comment by RSATom** [comment]
There is no any rush, so take your time. And I'll create PR after some testing :+1:

**Comment by lminiero** [comment]
@RSATom did you submit a PR with your patch eventually? I lost track of things :smile:

**Comment by RSATom** [comment]
@lminiero unfortunately no :disappointed: I had to fork audiobridge plugin to make it more suitable for my needs and just can't test  patch well. So I think this issue has no meaning for me anymore.

**Comment by lminiero** [comment]
Ack, I'll close then. We can worry about it if it becomes an issue in the futurre. Thanks!
