### ISSUE TITLE
[1.x] Videoroom deadlock after legacy "switch" request

### ISSUE THREAD

**Issue by guapman** [meetecho/janus-gateway#3066]
**What version of Janus is this happening on?**
1.1.0-11, 07e546430e35ab5341695bbe493e24c26510a6b3

**Have you tested a more recent version of Janus too?**
Yes, 1.0.4

**Additional context**
After "switch" request videoroom plugin stuck as mutex unlock is missed in the legacy switch handler code.
Patch: https://gist.github.com/guapman/fbf407280a49fde7049d4ac5aae91cf5

**Comment by lminiero** [comment]
Good catch, thanks for spotting this! I'll push the fix shortly.
