### ISSUE TITLE
[1.x] Crash when freeing medium msid

### ISSUE THREAD

**Issue by formater** [meetecho/janus-gateway#3081]
**What version of Janus is this happening on?**
Janus version: 1100 (1.1.0)

**Have you tested a more recent version of Janus too?**
No, because I can't reproduce the crash

gdb backtrace available here:
https://gist.githubusercontent.com/formater/8424e2e88e398cd90120dcf86c48abb4/raw/680ea9eb7db7a37257471bfd410a679f4b627edf/gistfile1.txt

**Comment by lminiero** [comment]
We'll need many more details than "it crashed". What were you trying to do? What's the scenario? Which plugins? Any useful information? Thanks.

**Comment by formater** [comment]
Sorry. The only compiled plugin is the sip plugin. The janus gateway is used as webrtc sip gateway. 
I don't know what happened during the crash, because that server is in production, multiple people use the service.

It was up an running for months, and this is the first time seg fault happened. Will try to update to latest version, and wait a few more months to see if the issue still exists or not :)

**Comment by lminiero** [comment]
> The check for `medium != NULL` is missing in the involved block, I guess we need to address that.

Good catch, I'll add it.
