### ISSUE TITLE
g_thread_pool_set_max_idle_time

### ISSUE THREAD

**Issue by wan721** [meetecho/janus-gateway#3084]
https://github.com/meetecho/janus-gateway/blob/cffad3c54eb046ddc457e145ff899d4866d08b6b/src/janus.c#L5352

If we're not using AddressSanitizer, should we comment out this line or set it to a smaller value (in my system the default is 15 seconds).

**Comment by atoppi** [comment]
@wan721 did you encounter any issue due to that timeout setting being too high?
I can see _potential_ problems with bursts of requests in a short time and unlimited pool size, is that your case?

> I don't think we have a way to detect AddressSanitizer at compile time

fwiw asan can be detected through macros on both `gcc` and `clang`

- **gcc** ([ref](https://gcc.gnu.org/onlinedocs/gcc-5.5.0/cpp/Common-Predefined-Macros.html))
```c
#ifdef __SANITIZE_ADDRESS__
// code that builds only under AddressSanitizer
#endif
```

- **clang** ([ref](https://clang.llvm.org/docs/AddressSanitizer.html#conditional-compilation-with-has-feature-address-sanitizer))
```c
#if defined(__has_feature)
#  if __has_feature(address_sanitizer)
// code that builds only under AddressSanitizer
#  endif
#endif
```

**Comment by wan721** [comment]
Thank you @atoppi. We're encountering an issue when trying to attach a plugin because thread resources are unavailable
```
[ice.c:janus_ice_handle_attach_plugin:1430] [2085675373781348] Got error 0 (Error creating thread: Resource temporarily unavailable) trying to launch the handle thread...
Detaching handle from JANUS VideoRoom plugin; 0x7f7068d1a880 0x7fa65efa4f80 0x7f7068d1a880 0x7f7068d1a9d0
[janus.c:janus_process_incoming_request:1221] Couldn't attach to plugin 'janus.plugin.videoroom', error '-1'
```
So, we're looking for ways to reclaim idle threads back to the system as fast as possible.

**Comment by wan721** [comment]
> @wan721 did you encounter any issue due to that timeout setting being too high? I can see _potential_ problems with bursts of requests in a short time and unlimited pool size, is that your case?
> 
> > I don't think we have a way to detect AddressSanitizer at compile time
> 
> fwiw asan can be detected through macros on both `gcc` and `clang`
> 
> * **gcc** ([ref](https://gcc.gnu.org/onlinedocs/gcc-5.5.0/cpp/Common-Predefined-Macros.html))
> 
> ```c
> #ifdef __SANITIZE_ADDRESS__
> // code that builds only under AddressSanitizer
> #endif
> ```
> 
> * **clang** ([ref](https://clang.llvm.org/docs/AddressSanitizer.html#conditional-compilation-with-has-feature-address-sanitizer))
> 
> ```c
> #if defined(__has_feature)
> #  if __has_feature(address_sanitizer)
> // code that builds only under AddressSanitizer
> #  endif
> #endif
> ```

Thanks for the suggestion! We will try that code.

**Comment by lminiero** [comment]
I got a mail about a post I don't see listed here, which mentioned an `Error creating thread: Resource temporarily unavailable` as one of the causes to revise this. Make sure you're setting `ulimit` accordingly: https://janus.conf.meetecho.com/docs/FAQ.html#ulimit
