### ISSUE TITLE
[1.x][audiobridge] possible race condition (but I'm not sure)

### ISSUE THREAD

**Issue by RSATom** [meetecho/janus-gateway#3090]
I have a feeling race condition is possible here:

https://github.com/meetecho/janus-gateway/blob/3c9d6ed2aeee38c682509ab3279016b8576833aa/src/plugins/janus_audiobridge.c#L6006-L6007

I mean Isn't room reset should go after mutex lock?

**Comment by lminiero** [comment]
I don't think so, since that's a participant property, not a room one.

**Comment by RSATom** [comment]
yes, but in other parts of plugin there are places where this property changing only with `audiobridge->mutex` locked...

**Comment by lminiero** [comment]
Moved the NULL assignment to after we get the mutex. Closing :+1:
