### ISSUE TITLE
variable name

### ISSUE THREAD

**Issue by wan721** [meetecho/janus-gateway#3091]
https://github.com/meetecho/janus-gateway/blob/cc67cd9ac25eac46bd314548199dd8ea231e4ebe/src/plugins/janus_videoroom.c#L6812

Just wondering if the variable "room_prev_recording_active" should really be named "room_new_recording_active"? Since it's being assigned the "record" value from the request (through variable "recording_active"?

Thank you.

**Comment by lminiero** [comment]
Good catch: it was probably a copy/paste misshap from our use of a `prev_recording_active` variable in the loop (which is named correctly in that case though). I'll fix the typo.
