### ISSUE TITLE
[1.1.0]  Janus sip plugin recorded peer video is black, because of unimplemented keyframe request

### ISSUE THREAD

**Issue by tvildo** [meetecho/janus-gateway#3092]
**What version of Janus is this happening on?**
1.1.0

**Have you tested a more recent version of Janus too?**
Yes, Master

**Was this working before?**
No

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
I see that in the source code of sip plugin, when recording is enabled, we don't request PLI. So when I try to play, recorded video is black.   Blame: [See source code here](https://github.com/meetecho/janus-gateway/blob/5d55eeb2e17c99a258e8448b815b179729524ddf/src/plugins/janus_sip.c#L4556)

I just want to ask if there is an easy way to get peer session reference and send PLI as we do it [here](https://github.com/meetecho/janus-gateway/blob/5d55eeb2e17c99a258e8448b815b179729524ddf/src/plugins/janus_sip.c#L4623):

**Comment by tvildo** [comment]
I think it will be great to add optional parameter in "start recording" request and based on that we can decide to send PLI or not. I can implement that, but It is just not clear to me how can I get peer session reference at that point in recording request handler in sip plugin.

**Comment by lminiero** [comment]
As I said, there's no peer session reference, as the peer is a SIP user, who may or may not be a browser user. The RTCP packet must be manually crafted and manually sent on the related socket.

**Comment by lminiero** [comment]
@tvildo please test the PR above.

**Comment by tvildo** [comment]
Thank you @lminiero for quick fix. 
In my case I found another problem between Janus <--> Asterisk and solved it and created [pull request](https://github.com/meetecho/janus-gateway/pull/3094) with description what and why I did

**Comment by lminiero** [comment]
Closing the issue then, as your PR aims to address a different requirement.

**Comment by michelepra** [comment]
can also be done in [nosip plugin](https://github.com/meetecho/janus-gateway/blob/1c5f60bf61f434fb0287efd2a0699c9fa281b4ac/src/plugins/janus_nosip.c#L1651)?
