### ISSUE TITLE
[1.1.0] How to access my device with janus-gateway?

### ISSUE THREAD

**Issue by Psychesnet** [meetecho/janus-gateway#3095]
**What version of Janus is this happening on?**
janus-gateway-1.1.0

**Have you tested a more recent version of Janus too?**
No, because this is not a bug, it is a question.

**Was this working before?**
Yes, I think this should work at all version.

**Is there a gdb or libasan trace of the issue?**
No.

**Additional context**
Hi @lminiero ,

I'm a developer at camera embedded system. We are going to intergrate janus-gateway into our device.
Janus-gateway works well at LAN network. I can use streamingtest.html to watch rtsp stream from camera.
We go to next step. We setup stun server with google stun and we can see device connect successfully with stun server from log.
```
STUN server to use: stun.l.google.com:19302
  >> 108.177.125.127:19302 (IPv4)
Testing STUN server: message is of 20 bytes
  >> Sent 20 bytes, waiting for reply...
  >> Got 32 bytes...
  >> XOR-MAPPED-ADDRESS: 0
  >> Our public address is 125.229.20.93
```

Good, my question is How to access my device with janus demos web from my PC?
Should I setup a stun server at my PC? 
I think I need to change the source code of janus.js, but how?

If you have any suggestion, please give me some help. Thanks. Have a good day.

**Comment by lminiero** [comment]
As explained in the guidelines, please use the [group](https://groups.google.com/g/meetecho-janus) for questions. We only use github for code issues.
