### ISSUE TITLE
[1.x] janus_rtcp_parse_lost_info() is not implemented

### ISSUE THREAD

**Issue by mdevaev** [meetecho/janus-gateway#3099]
This is actual for both 0.x and 1.x branches. I found `janus_rtcp_parse_lost_info() and I wanted to use it in my plugin, but it turned out that there is no implementation of this function in `rtcp.c`. It is necessary to either add an implementation of this, or remove it.

**Comment by lminiero** [comment]
It looks like that function was removed in 9332c248f200bfc9c67fb4d683b50eb451f03cfc, as it had been integrated in the more generic parsers in previous changes and fixes. I'll get rid of the signature, thanks for spotting this!

**Comment by mdevaev** [comment]
:ok_hand:
