### ISSUE TITLE
Client part available on npm

### ISSUE THREAD

**Issue by MathRobin** [meetecho/janus-gateway#310]
Hi !

Thanks a lot for your great work !

Is it possible to add janus js client on npm ?

**Comment by lminiero** [comment]
No such thing, sorry. The closest thing to a ready-to-use Janus client stack on node is this project, but I'm not sure how up-to-date it is: https://github.com/rtc-io/rtc-janus
Anyway, once you grasp how the Janus API works, it shouldn't be too hard to implement one yourself:
http://janus.conf.meetecho.com/docs/rest.html

PS: please only use GitHub for issues, for questions like this it's best to rely on the meetecho-janus google group, where other users may have solved this already.

**Comment by aisch** [comment]
@MathRobin not sure if this helps but we wrote this to make interfacing w/ custom plugins a little nicer: https://github.com/mayfieldrobotics/janus-js.

@lminiero if interested we also wrote python bindings [here](https://github.com/mayfieldrobotics/janus-py) and used it to talk to janus from a [ros](http://www.ros.org/) env.

**Comment by lminiero** [comment]
@aisch amazing efforts, I didn't know about those! I'm planning to make a list of all resurces like this in the near future, to provide a list of useful tools for interested users, so I'll make sure to list yours too.
