### ISSUE TITLE
Notify subscriber condition checking

### ISSUE THREAD

**Issue by wan721** [meetecho/janus-gateway#3100]
https://github.com/meetecho/janus-gateway/blob/ef984223dd0cfbaa07445c18748f506899678305/src/plugins/janus_videoroom.c#L8935

Hi, I'm just curious. In the second condition-checking, "or there's no room(anymore)"
shouldn't it be
room != NULL && g_atomic_int_get(&room->destroyed))

(no ! before g_atomic_int_get) ?

**Comment by lminiero** [comment]
This should actually probably be

    room == NULL || g_atomic_int_get(&room->destroyed))

since also a `NULL` room property in the subscriber means the subscriber instance is not in the room anymore. I'll have another look later and commit a fix in case. Thanks for spotting this!

**Comment by wan721** [comment]
I think
room == NULL || g_atomic_int_get(&room->destroyed))
makes sense.
Thank you Lorenzo.

**Comment by lminiero** [comment]
Apologies for the delay, I was abroad for a conference last week. I just pushed the fix.

**Comment by wan721** [comment]
> Apologies for the delay, I was abroad for a conference last week. I just pushed the fix.

Apologies for my delay as well. I almost forgot all about it as well.
