### ISSUE TITLE
[1.1]

### ISSUE THREAD

**Issue by AugustoZanoni** [meetecho/janus-gateway#3102]
version: 1101

I'm trying to add a new track to the videoroom plugin using

```
{
        tracks: [{ type: 'screen', add: true, capture: true }],
        success: function(jsep) {
            echotest.send({ message: { video: true }, jsep: jsep })
        }
        error: function(error) {
            bootbox.alert('WebRTC error... ' + error.message);
        }
   }
```

The negotiation come back with the jsep and it seems to work fine, but I don't get the log ' Janus started receiving ' and it doesn't work

I'm using the sample code from mvideoroomtest.js and using console to emit the offer, also, using wss://janus.conf.meetecho.com/ws

**Comment by AugustoZanoni** [comment]
To test just paste this code to console after join the room

```
sfutest.createOffer(
    {
        tracks: [{ type: 'video', add: true, capture: true }],
        success: function(jsep) {
            sfutest.send({ message: { video: true }, jsep: jsep })
        },
        error: function(error) {
            console.log(error)
        }
    }
)
```

**Comment by lminiero** [comment]
`{ video: true }` is not a valid message for the VideoRoom plugin, which will reject it. As a result, the plugin will never generate an SDP answer to your offer.

**Comment by AugustoZanoni** [comment]
> `{ video: true }` is not a valid message for the VideoRoom plugin, which will reject it. As a result, the plugin will never generate an SDP answer to your offer.

That's how is described on the docs (https://janus.conf.meetecho.com/docs/JS.html).

How should I add a new video track ?

**Comment by lminiero** [comment]
That's an example using the EchoTest plugin. The message you send to a plugin must obviously comply with what the plugin expects: since you're using the VideoRoom, you must use the VideoRoom API.

**Comment by AugustoZanoni** [comment]
Thanks. It was missing the "request" attribute. 

```
{ request: "configure", video: true }
```
