### ISSUE TITLE
[1.x] HTML audio element added twice in streaming plugin demo

### ISSUE THREAD

**Issue by fammler** [meetecho/janus-gateway#3109]
I think there is a minor issue in the streaming plugin demo. When running the single RTP source stream (config _rtp-sample: { ... }_ , OPUS/VP8) of the streaming plugin demo, the HTML audio element is rendered twice. 

In streamingtest.js, the function callback "onremotetrack" is called twice per track, once with value "**muted: true**" and once with "**muted: false**" (see attached part of browser logs). 

For each call, an `<audio ...> `element is added I think. 

**What version of Janus is this happening on?**
Janus version: 1101 (1.1.1)

**Have you tested a more recent version of Janus too?**
I pulled the most recent version. 

**Was this working before?**
not sure. 

**Is there a gdb or libasan trace of the issue?**
<details>
  <summary>Part of browser logs: unmuting tracks</summary>
  
streamingtest.js:156 Remote track (mid=a) added: MediaStreamTrack {kind: 'audio', id: 'janusa', label: 'janusa', enabled: true, **muted: true**, …}

streamingtest.js:156 Remote track (mid=v) added: MediaStreamTrack {kind: 'video', id: 'janusv', label: 'janusv', enabled: true, **muted: true**, …}

streamingtest.js:156 Remote track (mid=a) added: MediaStreamTrack {kind: 'audio', id: 'janusa', label: 'janusa', enabled: true, **muted: false**, …}

streamingtest.js:156 Remote track (mid=v) added: MediaStreamTrack {kind: 'video', id: 'janusv', label: 'janusv', enabled: true, **muted: false**, …}
</details>

**Additional context**
--

**Comment by lminiero** [comment]
Mh looks like you're right, and it happens with the video element too. Apparently both the redundant audio and video elements aren't really used, since they're hidden and unhooked, but they shouldn't exist in the first place. I checked the VideoRoom demo to see if it's something we're doing wrong in general, but it doesn't happen there, so it may indeed be something specific to the Streaming demo. I'll have a look to see what's going on.

**Comment by lminiero** [comment]
Just noticed that due to a typo my commit didn't automatically tag this issue: FYI, 6ecabec0db63ad21c6f47c39a0cfa04b367a2357 should fix the problem, thanks for spotting it!
