### ISSUE TITLE
[1.x] admin.html not working

### ISSUE THREAD

**Issue by gdesmott** [meetecho/janus-gateway#3115]
So the admin API is working on my server:

```console
$ curl --location --request POST http://78.46.109.86:7088/admin/ --data-raw '{
    "janus":"list_sessions",
    "transaction":"random_alphanumeric_string",
    "admin_secret":"janusoverlord"
}'
{
   "janus": "success",
   "transaction": "random_alphanumeric_string",
   "sessions": []
```

But trying to use https://janus.conf.meetecho.com/admin.html with it is not working.
I get this error:

> Couldn't contact the backend: is Janus down, or is the Admin/Monitor interface disabled?

Is there something wrong with this page?

**Comment by lminiero** [comment]
The Admin API is obviously disabled on the official demos, since we don't want to allow people to snoop on who else is using the demos.

**Comment by gdesmott** [comment]
Ah ok, I assumed this tool was meant to be used directly.

How can I get my server to serve `admin.html` itself then? Didn't find any doc about that.

**Comment by lminiero** [comment]
It's in the same folder as the other demos, so exactly as you usually serve them:
https://janus.conf.meetecho.com/docs/deploy

**Comment by gdesmott** [comment]
Great, thanks a lot!
