### ISSUE TITLE
[0.x] janus-gateway(v0.2.3) not working in react native with polyfill's 

### ISSUE THREAD

**Issue by prashantkhatal** [meetecho/janus-gateway#3117]
**What version of Janus is this happening on?**
v0.2.3 janus-gateway (using npm i janus-gateway) as client

**Have you tested a more recent version of Janus too?**
no other stable versions

**Was this working before?**
not sure

**Is there a gdb or libasan trace of the issue?**
I am using it in react native.
In **janus.nojquery.js**, token is not encoded resulting to 400 while long pulling. Also unable to use it as module(ie. no default exported Janus from it). video room plugin is not working.

**Additional context**
Using following as polyfill
```

window.RTCPeerConnection = RTCPeerConnection;
window.RTCRtpSender = RTCRtpSender;
window.MediaStreamTrack = MediaStreamTrack;
window.MediaStream = MediaStream;
window.RTCSessionDescription = RTCSessionDescription;
window.addEventListener = () => {};
window.adapter = adapter;

navigator.mediaDevices = mediaDevices;
navigator.getUserMedia = () => {};
```

**Comment by lminiero** [comment]
I'm sorry but 0.2.3 is five years old, so we won't consider this issue. Please use a recent version of the library instead.

**Comment by prashantkhatal** [comment]
> I'm sorry but 0.2.3 is five years old, so we won't consider this issue. Please use a recent version of the library instead.

can you please point which version? 
Whenever i use **npm i janus-gateway** it installs 0.2.3.

Thanks
