### ISSUE TITLE
[1.x] Unable get latest version of janus-gateway using npm 

### ISSUE THREAD

**Issue by prashantkhatal** [meetecho/janus-gateway#3118]
Unable to get latest version using **npm i janus-gateway**
It sticks to 0.2.3 version while installing using npm which is 5 yrs old.

Use commands
```
npm i janus-gateway
```

Please help with the commands to install latest janus-gateway using npm.

Thanks.

**Comment by lminiero** [comment]
I just told you in another issue that we don't provide that library via npm... Either download janus.js from the html folder here, or use the info in the documentation I linked to get the latest version as a module.
