### ISSUE TITLE
[0.x] Two Janus requests in one websocket message results in 'Missing mandatory element (transaction)'

### ISSUE THREAD

**Issue by jwittner** [meetecho/janus-gateway#3120]
**What version of Janus is this happening on?**
0.11.2

**Have you tested a more recent version of Janus too?**
No, though I've inspected the code and, if I'm correct in my current assessment, the issue will happen in 'master' as well.

**Was this working before?**
I'm not sure, but I suspect not.

**Is there a gdb or libasan trace of the issue?**
Unfortunatley not gdb or libasan. I can share wireshark logs though if useful.

**Additional context**
We were seeing this error in the title from Janus intermittently. Digging into wireshark logs I see this occurs when Janus would be processing a single websocket message with two janus request message objects in it.

Looking at [janus_websockets.c](https://github.com/meetecho/janus-gateway/blob/f5208073e702606ab338a31fa3dfbf38651d8e6c/src/transports/janus_websockets.c#L1314) it doesn't look like we support this properly with the current handling of `json_loads`. 

Following this code through to [janus.c](https://github.com/meetecho/janus-gateway/blob/f5208073e702606ab338a31fa3dfbf38651d8e6c/src/janus.c#L1044) it looks like nothing detects the failure to parse from `json_loads` until we check for the required request parameters and find that the object doesn't have a 'transaction' element (in fact its a null object, or so I believe).

I have work in progress (just getting setup to test now) to correctly handle multiple json objects in one websocket message, and to detect and report any json parsing errors directly. Since I haven't validated this through tests, I haven't made that PR but am happy to do so with current state if it helps the discussion.

**Comment by lminiero** [comment]
@jwittner please see the PR above. I tested this briefly and it seems to be returning the right error when replicating the scenario you described.

**Comment by jwittner** [comment]
Ok, pushed up a draft PR (working with a teammate today to test locally, but any help is much appreciated if you want to take what I have the rest of the way. Otherwise once I've tested I can publish the PR.

**Comment by jwittner** [comment]
I published my PR after testing to good effect today. Review much appreciated.
