### ISSUE TITLE
[1.x] AV Sync Issue in Janus on iOS devices

### ISSUE THREAD

**Issue by ansh1101** [meetecho/janus-gateway#3129]
**What version of Janus is this happening on?**
version 1.1.0

**Have you tested a more recent version of Janus too?**
Yes i have tested this on many versions older and newer but still facing this issue in every version

**Was this working before?**
i dont have any clue on this , but since v0.10.7 it is not working

**Is there a gdb or libasan trace of the issue?**
IWe have been facing this issue since last 7 months and i have raised this many times but i havent got any resolution on this ticket, and we are getting many escallations from clients regarding please try to fix this issue.
[https://drive.google.com/drive/folders/1BvhlquN_W0EwL6d0w1q05Mf7vs1lDyhX](https://drive.google.com/drive/folders/1BvhlquN_W0EwL6d0w1q05Mf7vs1lDyhX)
Attaching this sample recording which has sync issue and not being fixed by restamp option

i am trying to fix this with restamping options but it doesn't look like it does justice to all of the affected recordings,

**Comment by lminiero** [comment]
As @atoppi already told you on the group, restamping won't work if the problem is in the video. Please stop spamming the same issue over and over everywhere.

**Comment by atoppi** [comment]
Assuming the mjr from the link
```
videoroom-23c0a891-7c53-4bf1-83c9-974375aee93d-user-f7bba8a4-697d-44f8-9f1a-352d158009aa-1670928416740885-video.mjr
```
then converting to pcap with `mjr2pcap` and analyzing the RTP, I have obtained the following table based on the video keyframes:

<!DOCTYPE html>

<html>

<body>


real time (secs) | RTP TS | RTP time | delta (secs)
-- | -- | -- | --
0 | 0 | 0.00 | 0.00
0.21 | 6664 | 0.07 | -0.14
1.1 | 60394 | 0.67 | -0.43
2.44 | 210874 | 2.34 | -0.10
5.28 | 462874 | 5.14 | -0.14
5.83 | 507424 | 5.64 | -0.19
46.1 | 4061870 | 45.13 | -0.97
46.25 | 4074217 | 45.27 | -0.98
47.1 | 4146127 | 46.07 | -1.03
147.05 | 13143877 | 146.04 | -1.01
155.04 | 13866223 | 154.07 | -0.97
157.26 | 14065713 | 156.29 | -0.97
160.43 | 14296552 | 158.85 | -1.58
162.52 | 14485901 | 160.95 | -1.57


</body>

</html>

_real time_ is the absolute relative time of reception as recorded by janus.
_RTP time_ is the relative time as calculated from RTP timestamp (e.g. RTP ts / 90000).
The delta  column is the difference (_RTP time_ - _real time_).

At ~46 seconds of video, there is a huge spike in video latency (about 1 sec).
So the RTP source (device app) is lagging and the video is being delayed.

Side Note: the keyframe interval in this video stream is not regular and probably demanded by a remote PLI.

**Comment by AnshIDfy** [comment]
what do you mean by **client**
front end app? or device

**Comment by ansh1101** [comment]
what do you mean by **client**
front end app? or device
it can't be Front End app as media data is transfer over socket to Media server so how that can be fixed at source level. Our product is browser based not a native mobile app.
Please guide me

**Comment by AnshIDfy** [comment]
Any updates here??

**Comment by ansh1101** [comment]
any updates on this

**Comment by atoppi** [comment]
Which device, os version and browser are you using?
Try with another browser to see what happens.

Of course you can not change the browser code.
As far as I know, overall on mobile devices you get a better experience with native apps since browsers tend to have a lot of power management policies and conservative scheduling.

Like we already said, restamping is not available for the video at the moment.

**Comment by AnshIDfy** [comment]
moslty iOS devices, irrespective of browsers

**Comment by ansh1101** [comment]
This is happening majorly for iOS devices, irrespective of browser we use.

**Comment by tmatth** [comment]
> Can you explain a little more what do you mean by adding dummy AudioContext to the page. And how you implemented it

https://stackoverflow.com/questions/9811429/html5-audio-tag-on-safari-has-a-delay/54119854#54119854

**Comment by tmatth** [comment]
> Isn't this a fix for local playback delays? The problem here is their client is often drifting and generating incorrect timestamps that don't take into account the actual capture time. What's broken in fact are recordings, in their case.

@lminiero oh I missed that this is recording-specific.

**Comment by ansh1101** [comment]
@atoppi  what's your POV on this

**Comment by atoppi** [comment]
The fix that @tmatth suggested is just for local (browser) playback delay, it does not change how packets are sent to the server
