### ISSUE TITLE
Janux 1.x commit  d505788 fails to build on Fedora Rawhide

### ISSUE THREAD

**Issue by bkmgit** [meetecho/janus-gateway#3131]
**What version of Janus is this happening on?**
Commit  d505788
and release 1.0.4
**Have you tested a more recent version of Janus too?**
This is current development head

**Was this working before?**
Was working with other compilers

**Is there a gdb or libasan trace of the issue?**
Not applicable.

**Additional context**
With Gcc 12.2.1 20221121 get
In file included from /usr/include/curl/curl.h:3195,
                 from turnrest.c:21:
turnrest.c: In function ‘janus_turnrest_request’:
turnrest.c:168:9: error: void value not ignored as it ought to be
  168 |         curl_easy_setopt(curl, api_http_get ? CURLOPT_HTTPGET : CURLOPT_POST, 1);
      |         ^

Checking version of curl gives
$ curl --version
curl 7.87.0 (aarch64-redhat-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.5 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 libpsl/0.21.1 (+libidn2/2.3.3) libssh/0.10.4/openssl/zlib nghttp2/1.51.0
Release-Date: 2022-12-21
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets

**Comment by jonassmedegaard** [comment]
Same failure now occurs on Debian unstable as well, as reported here: https://bugs.debian.org/1027656

**Comment by lminiero** [comment]
Closing. thanks for the fix!
