### ISSUE TITLE
[1.x] Record&Play plugin  open recording data-channel error

### ISSUE THREAD

**Issue by JavanFeng** [meetecho/janus-gateway#3134]
**What version of Janus is this happening on?**
v1.1.1，acutally,I changed some else branch, it still has problem

**Is there a gdb or libasan trace of the issue?**
when I using the Record&Play plugin to record data-channel, the problem happened;but ti is right when recording only audio and vedio。 

**Additional context1**
i just use the exsample under the dir (demos). and just add {type: 'data'} to the offer request:
![image](https://user-images.githubusercontent.com/31945784/209932495-8ff17ae8-1301-4a37-9501-acf4655a8a57.png)

**then the err happened:** 
[ERR] [sdp-utils.c:janus_sdp_parse:667] Invalid m= line (no payload types/formats): m=application 0 UDP/DTLS/SCTP
[ERR] [sdp.c:janus_sdp_preparse:42]   Error parsing SDP? Invalid m= line (no payload types/formats): m=application 0 UDP/DTLS/SCTP
[ERR] [janus.c:janus_plugin_handle_sdp:3689] [26778865119573] Couldn't parse SDP... Invalid m= line (no payload types/formats): m=application 0 UDP/DTLS/SCTP
[ERR] [janus.c:janus_plugin_push_event:3607] [26778865119573] Cannot push event (JSON error: problem with the SDP)
[WARN] [26778865119573] Error resolving mDNS address (68933263-a828-4316-b22b-10421b773315.local): Error resolving “68933263-a828-4316-b22b-10421b773315.local”: Name or service not known
[WARN] [26778865119573] ICE failed for component 1 in stream 1, but let's give it some time... (trickle received, answer received, alert not set)
[ERR] [ice.c:janus_ice_check_failed:1998] [26778865119573] ICE failed for component 1 in stream 1...
[janus.plugin.recordplay-0x7f2c28001bd0] No WebRTC media anymore
File is 8 bytes: rec-7320023697688874-data.mjr
Closed data recording rec-7320023697688874-data.mjr

meanwhile  all saced recording files just have content : MJR00002   （string）

**Additional context1**
and then I  tested: just send createOffer Request , the log in server console under here:
![image](https://user-images.githubusercontent.com/31945784/209933323-02a0be44-f69b-4dc2-8f96-d0abedb9987e.png)

and at client,I got the log : Creating answer (iceDone=false)。and the ondataopen method  never invoked

I am newer about janus,so I am not sure it is a issueor i has the wrong code?
so what i shoud do?

**Comment by lminiero** [comment]
Did you compile Janus with datachannels support?

**Comment by lminiero** [comment]
Nevermind that, I managed to replicate the problem. The Record&Play plugin doesn't support datachannels, and so was rejecting them silently: this caused a broken SDP to be generated, as the format in the m-line was absent, while it should be there. The commit above fixed it for me. Notice that this fixes the error, but data will still be rejected by the Record&Play plugin.

**Comment by JavanFeng** [comment]
I see. and now it can work well although not recording data. but it still generals the file xx-data.mjr. it is not a problem, cause the plugin doesn't  support datachannel, I will not use it to recorder data. 

before,I thount it will worked well like videoroom pligin's recording(support datachannel), although the document says it can‘t (the comment on the code means it can record data?）。

thanks anyway : )
