### ISSUE TITLE
[1.x]

### ISSUE THREAD

**Issue by CraigRSheppard** [meetecho/janus-gateway#3151]
**What version of Janus is this happening on?**
Put the version and the commit identifier (available in `version.c` or from an `info` request) here
> Janus version: 1101 (1.1.1)

**Have you tested a more recent version of Janus too?**
Yes/no. If yes, which one. If not, why.
> Have not tried version 1.1.2 yet.

**Was this working before?**
If you have information on a version/commit where the issue wasn't there (e.g., the result of a `git bisect`), please provide it here.
> In the process of testing for a new WebRTC network, first time testing with this version. Have been using the legacy version for a while.

**Is there a gdb or libasan trace of the issue?**
If you have a trace related to the issue (e.g., after a segfault), provide it as a gist/pastebin/other link here, or as a [collapsible section](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). Do **NOT** paste logs inline. For more information on the kind of traces we may find useful, please refer to the [documentation](https://janus.conf.meetecho.com/docs/debug).

**Additional context**

** Janus version: 1101 (1.1.1)
Janus commit: 0a6bd68926dae0a115e05c9e0ceddd428938396a
Compiled on:  Sun Dec 11 04:35:38 UTC 2022 **

The signaling server was unable to connect to the websocket for Janus and seeing in the Janus log the error "Rejecting incoming HTTP request on WebSockets endpoint".

Running the snap version of Janus-Gateway, doing some load testing with 4 senders and 8 receivers. Issue has only happened once so far. Has been solid for the last 14 hours.

Please advise if more information is needed.

Thanks,
Craig

**Comment by lminiero** [comment]
> The signaling server was unable to connect to the websocket for Janus and seeing in the Janus log the error "Rejecting incoming HTTP request on WebSockets endpoint".

Looks like you were trying to use regular HTTP signalling (Janus "REST" API) with the WebSockets backend, since that message only appears in the `LWS_CALLBACK_HTTP` fallback. Closing.
