### ISSUE TITLE
VideoRoom(Multi-Stream) Remote audio track mute/unmute event is not getting

### ISSUE THREAD

**Issue by Nigam-Patel-Main** [meetecho/janus-gateway#3163]
Janus Version 1.1.3

Have you tested a more recent version of Janus too?
Yes, 1.1.3 is the latest version

Was this working before:
No

Problem 1: **When we mute/unmute the audio from the publisher then the event is not received at the receiver side(remote).** 
Problem 2: **The talking event is also not triggering even if I configure the "audio_level_event" at the room.**

`toggleAudio() {
    let subscribe = {
      request: "configure",
      streams: [
        {
          mid: this.feed.audioStream.mid,
          send: !this.feed.audioStream.isRunning
        }
      ]
    };
    this.feed.pluginHandle.send({ message: subscribe });
    if (this.feed.audioStream.isRunning) {
      this.feed.pluginHandle.muteAudio()
    } else {
      this.feed.pluginHandle.unmuteAudio()
    }
    this.feed.audioStream.isRunning = !this.feed.audioStream.isRunning
  }`

`room-1234: {
        description = "Demo Room"
        secret = "adminpwd"
        publishers = 20
        bitrate = 512000
        fir_freq = 10
        #audiocodec = "opus"
        #videocodec = "vp8"
        record = true,
        audiolevel_ext = true,
        audiolevel_event = true,
        audio_active_packets = 100,
        audio_level_average = 25
        rec_dir = "/opt/janus/share/recording/123"
}
`

Video Attached Below Please Refer to this:

https://user-images.githubusercontent.com/32161774/218053082-37bcf1ba-64ab-4f53-87da-c49c0cb7d0a6.mp4

@lminiero Please help me out with this...

**Comment by Nigam-Patel-Main** [comment]
@lminiero Please give me the solution.

Or if I missing adding some detail then let me know.

I need to go live with the Janus media server

**Comment by lminiero** [comment]
Please ask questions on our Google group, not here. We only use github for issues.
