### ISSUE TITLE
The community group is now on Discourse (meetecho-janus will be archived)

### ISSUE THREAD

**Issue by lminiero** [meetecho/janus-gateway#3177]
Hi all,

the [meetecho-janus](https://groups.google.com/g/meetecho-janus) Google Group has served us well in this ~10 years, but it has started to become more and more unusable, unfortunately, especially to us who have to use it everyday. In the past couple of days, for instance, I have been completely unable to post any new topic for some unknown reason, and I know I wasn't the only one. As such, we decided to move to Discourse instead, which will give us a more modern and flexible discussion place, where we could for instance create different categories which was never possible here:

https://janus.discourse.group/

Please open new discussions there, as we'll slowly faze the old group out, and will eventually archive it. Unfortunately there was no way to migrate existing discussions there, but old posts will still remain accessible there for historic purposes.

Thanks,
Lorenzo

**Comment by oej** [comment]
Is there a way to get postings in Discourse over email? So I don't have to check in there to see if there's any new items? Push instead of pull :-)

**Comment by lminiero** [comment]
I talked about this with Joshua Colp yesterday on Mastodon and he said

> I know you can set up your account like a mailing list, and also reply via email like a mailing list. Starting threads I do not know.
> Ooh - it can be done!

so my guess is that it should indeed possible. Not sure if this is something I have to enable somewhere in the Discourse settings, or if it's something as a registered user you can configure in your own preferences. If you find something please do share!

**Comment by lminiero** [comment]
@oej I asked Joshua some more info and he provided some [here](https://fosstodon.org/@jcolp@mstdn.ca/109983103267902335), so it does look like something you should be able to configure in your own preferences. If you also want to be able to open new topics from mail, that's something I'll have to look into the admin settings.

**Comment by oej** [comment]
I can live with logging in to open new topics, that's a push anyway. I'll look into the pull mechanisms.

**Comment by oej** [comment]
I have played with some settings - will report back if it works.

**Comment by Chay009** [comment]
Hello i am interested in this repo i want to work more with integrations to webapps so that we can expand our service please if some one can spare some time i need your help i want to integrate werbtc -janus-rtmp
