### ISSUE TITLE
can we update janus server urls on the fly without breaking the peer connection ? [0.x]

### ISSUE THREAD

**Issue by svikas641** [meetecho/janus-gateway#3182]
I am currently using janus version 0.11.4 . I want to update the ws urls on the fly but not able to do it without breaking the peer connection. 
If this is already available in docs, please send me the link or something.

**Comment by lminiero** [comment]
No, updating Janus requires a restart of the server.

**Comment by svikas641** [comment]
![image](https://user-images.githubusercontent.com/16942496/225564024-83b8200a-854b-4cc2-8188-ee434ff65403.png)
Can you please, provide more context on this, also i am talking about this particular array.

**Comment by svikas641** [comment]
i want to update this array and add new element and delete present 2 elements.

**Comment by lminiero** [comment]
That's `janus.js`, not Janus. If you update that list, in theory nothing back should happen, since the current session has a variable with a copy of the server currently in use.
