### ISSUE TITLE
[1.x] Fifth publisher can't publish stream

### ISSUE THREAD

**Issue by nikohpng** [meetecho/janus-gateway#3183]
## Description
I use chrome to join room by videoroom(multistream).

I can't publish stream when i was fifth publisher

## Enviroment
+ [x] centos7
+ [x] janus1.1.3

## Error log
![0900289fd20233b013f536f31ef7343](https://user-images.githubusercontent.com/27041231/225861768-94a0a10a-7f88-474c-a1a8-375fcd790dcd.png)

**Comment by lminiero** [comment]
That's an error on `nice_agent_gather_candidates`, which means an issue gathering candidates. Maybe you configured a very narrow port range in `janus.jcfg` and all of them have been exhausted by the PeerConnections you created in the meanwhile. At any rate, not an issue in Janus.
