### ISSUE TITLE
[1.x]maybe janus_videoroom_subscriber_stream_free bug

### ISSUE THREAD

**Issue by openspring** [meetecho/janus-gateway#3190]
**What version of Janus is this happening on?**
version 1.1.3

**Additional context**
janus_videoroom.c

When the following test conditions are added to the  janus_videoroom_subscriber_stream_free func
JANUS_LOG(LOG_VERB, "videoroom janus_videoroom_subscriber_stream_free\n");
When someone exits, you will not see the stream deleted

The possible cause of the problem is in the janus_videoroom_subscriber_stream_add function

janus_refcount_increase(&stream->ref);	/* This is for the mid-indexed hashtable */   in this line

When subcriber is deleted, the stream->ref is not deleted

**Comment by atoppi** [comment]
I'm unable to reproduce on master (tested both videoroom and multistream videoroom demos).

**Comment by openspring** [comment]
This error is caused by my changes, this is a misunderstanding
