### ISSUE TITLE
[1.x] Inconsistent socket address type usage

### ISSUE THREAD

**Issue by ycherniavskyi** [meetecho/janus-gateway#3193]
It was introduced with 3da3ffa - `sockaddr_in6` was not replaced with `sockaddr_storage` for [`video_rtp_address` and `video_rtcp_address` variables](https://github.com/meetecho/janus-gateway/blob/6ee092af300241c9c552bef6107b51e2d377a2a4/src/plugins/janus_sip.c#LL6713C2-L6713C2).

**Comment by atoppi** [comment]
Thanks for reporting @ycherniavskyi!
