### ISSUE TITLE
[1.x] icestate is very often disconnected

### ISSUE THREAD

**Issue by avinashsureka** [meetecho/janus-gateway#3195]
I use janus.plugin.videoroom based on mvideoroomtest demo code.
I use janus module with webpack by https://janus.conf.meetecho.com/docs/js-modules.html.
-package.json
{
  "dependencies": {
    "janus-gateway": "git://github.com/meetecho/janus-gateway.git"
  }
}
So i truse janus version is recent.
iceserver is used as google stun server by setting nothing value.
Janus server is installed on digital ocean Ubuntu 20.04 droplet by following manual.
All are working.
I can see others' video+audio stream and others can see mine too.
But streaming is VERY OFTEN not connected.
on Console, "ICE state changed to disconnected" by icestate callback,
Sometimes it works well.
Is this iceserver problem?
I tried to use my stun server by installing coturn.
But same. Sometimes works and sometimes icestate is disconnected.
Can anyone help me?
Best Regards.

**Comment by atoppi** [comment]
Since you deployed Janus in the cloud, probably an issue with reachable network ports (check rtp port range and open them accordingly on the instance configuration).

I'am afraid questions like these belong[ to the group](https://janus.discourse.group/), so please use that if you need more help.

**Comment by avinashsureka** [comment]
@atoppi Thank you for your reply.
I opened ports correctly.
So sometimes streaming works well. but sometimes it doesn't work by disconnecting ice state.
