### ISSUE TITLE
[1.x] any reason for switch to not have substream param?

### ISSUE THREAD

**Issue by brave44** [meetecho/janus-gateway#3196]
In videoroom plugin, switch command doesn't have substream param, as subscribe or configure command have (https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_videoroom.c#L9428). Simulcast just resets on switching (https://github.com/meetecho/janus-gateway/blob/master/src/plugins/janus_videoroom.c#L11237 
).

It forces us to do configure to needed substream every time we doing switch, not ideal, especially if room have many streams.

Is it some specific reason to such implementation is switch, or it's just not implemented? Can we do PR with this logic?

**Comment by lminiero** [comment]
No specific reason: I think we recently fixed the simulcast configuration in multistream VideoRoom, and probably just forgot to do the same for switch too. A pull request would indeed be welcome: please notice I'll be abroad in vacation the whole week, so I may be very slow to review until I'm back.

**Comment by lminiero** [comment]
Merged.
