### ISSUE TITLE
cannot ./install

### ISSUE THREAD

**Issue by frogeraie** [meetecho/janus-gateway#320]
I followed the steps described in " http://the.randomengineer.com/2014/05/21/lightweight-live-video-in-a-webpage-with-gstreamer-and-webrtc/".
After having cloned janus from github I get an error message when I enter " ./install.sh":
bash: ./install.sh: No such file or directory
and indeed I cannot find any file of this name.
Did I clone the wrong repository? Something missing? Is Janus for 32-bit system only?

**Comment by lminiero** [comment]
Please follow the instructions this project homepage. That blog post is more than a year old.
