### ISSUE TITLE
[1.x] Janus process killed after 15 participants, seems hloop problems

### ISSUE THREAD

**Issue by azimot** [meetecho/janus-gateway#3200]
OS: ubuntu 20.04 update
cpu : 10 cores Xeon(R) CPU E7-4850 v4 @ 2.10GHz
ram : 16GB

Janus version : 1.1.1
libnice version : 0.1.17
libsrtp version : 2.2.0
usrsctp version : 0.9.5.0
libwebsockets version : 4.3.2
used transport : websocket 
 
plugins: {
        disable = "libjanus_voicemail.so,libjanus_recordplay.so,libjanus_echotest.so,libjanus_nosip.so,libjanus_streaming.so,libjanus_videocall.so,libjanus_textroom.so"
}

transports: {
        disable = "libjanus_rabbitmq.so,libjanus_pfunix.so"
}

I'm using Videoroom plugin with 1 publisher and 15 subscribers
all things was fine while I had just 15 subscribers. after 16th joined Janus crashed and killed by OS
I just check processes and there are many hloop processes! more than 325 threads

logs and crash report are exist :

[top with apport](https://gist.githubusercontent.com/azimot/b9d206ab4f484cdb2e2d16e0226aecab/raw/f1f27dc5cfdb7e80299dc304b2b639833d29ea77/gistfile1.txt)
 
if you see, there are more that 320 threads on hloop before apport process eaten CPU 
at first I think apport was buggy and this is why linux killed low priority processes additionally Janus too
so I disable apport and then run a test again 

[process log without apport process](https://gist.githubusercontent.com/azimot/c09be5ac3e49cf7e2116f758546c4469/raw/9bef01dff400effa4e7f9af4592d25691d8abfbd/gistfile1.txt)

I checked thread limitation on linux but it's OK and enough

[_opt_janus_bin_janus.0.crash](https://gist.githubusercontent.com/azimot/4027d713fab2631ba0cf8d7ef6dc6915/raw/56151bd604eecbab9ad296c92baa291199d2f3af/gistfile1.txt)

Is hloop related to libnice ? must be used newer libnice version ?

As I see there is no zombie. in normal usage, linux killed Janus process , any idea to resolve that or similar experiences ?

**Comment by lminiero** [comment]
Make also sure you didn't forget to increase the ulimit:
https://janus.conf.meetecho.com/docs/FAQ.html#ulimit

**Comment by atoppi** [comment]
I was assuming you are using the VideoRoom in multistream mode, if that is not the case (e.g. you are using Janus 1.x with 0.x syntax), then that number of `hloop` threads might not be significant, since in a VR with 16 participants you might end up having up to 16^2 = 256 active handles and `hloop` threads.
In that case, as Lorenzo mentioned, you are probably hitting a kernel limit.

**Comment by azimot** [comment]
@atoppi @lminiero exactly Lorenzo, that's reason is related to ulimit !!

my way that solved problem :
`ulimit -a` show us almost all user limits defined by default in Linux
`cat /proc/$(pidof janus)/limits` show us limits of Janus to use

temporary increase limits to see problem is solved :
`ulimit -n 60000`
`ulimit -Hn 600000`
`ulimit -Sn 60000`
Note : `ulimit -n` is not enough `ulimit -Sn` and `ulimit -Hn` are two switches that we must be used and I assumed if we want to have set them permanently please edit `limits.conf` file :
`nano /etc/security/limits.conf`

`#ulimit -Hn 1048576`
`root    hard    nofile  1048576`
`#ulimit -Sn 60000`
`root    soft    nofile  60000`

`root` is user that Janus running by. in most tutorials used * (star) to get all users but this is not working !! must be use exact user we want to set new configs.

after any reboot we cant to see `cat /proc/$(pidof janus)/limits` is correct 

Lorenzo is not this problem popular ? 15-16 participants is regular usage by VideoRoom plugin and these configs are empty in main Janus installation tutorial in website and [README.md](https://github.com/meetecho/janus-gateway/blob/master/README.md) too

problem solved but I'm pretty confused ! 
that problem is solved by `ulimit -Sn` but it's related to open files limit (disk I/O (read/write)) but hence I know about Janus architecture while we don't record streams on disk we should be not have huge open files . 

why that happened ?!? 
and why Janus (without stream recording) needs to have more open files ??!


Thank You

**Comment by atoppi** [comment]
In Unix/Linux OS file descriptors are used for any kind of I/O resource:
- files
- pipes
- eventfds
- network sockets
- etc...

If you need more details about the fds in use by Janus, check the [lsof](https://man7.org/linux/man-pages/man8/lsof.8.html) command.

Closing the issue now.
