### ISSUE TITLE
FFmpeg-WHIP: Initially, the latency was about 150ms, but it later increased to approximately 480ms

### ISSUE THREAD

**Issue by winlinvip** [meetecho/janus-gateway#3222]
**What version of Janus is this happening on?**
0.10.10. The bug is present in version 0.10.10, but it may also exist in other versions, including the latest one.

**Have you tested a more recent version of Janus too?**
No. Since we haven't tested it with the latest version, it doesn't appear to be related to the version.

**Was this working before?**
No.

**Is there a gdb or libasan trace of the issue?**
No.

**Additional context**
We are currently exploring ways to [enable ffmpeg to support WHIP](https://github.com/ossrs/ffmpeg-webrtc/pull/1#usage-ffmpeg-janus). We conducted tests using Janus and the results were positive, with very low subsecond latency.

At first, the latency was around 150ms, but it later rose to approximately 480ms, as depicted in the images below.

<img width="480" alt="image" src="https://github.com/meetecho/janus-gateway/assets/2777660/975a7850-caaf-4fea-ae51-13adde163921">

<img width="480" alt="image" src="https://github.com/meetecho/janus-gateway/assets/2777660/934be77d-556b-4e4b-85fb-56dcf22131b7">

As we do not possess extensive knowledge of Janus, we are unable to debug the code ourselves. Therefore, we would greatly appreciate your assistance in identifying potential solutions to address this issue.

**Replay steps**

We have provided a [step-by-step reproduction](https://github.com/ossrs/ffmpeg-webrtc/pull/1#usage-ffmpeg-janus) of this issue, which should allow you to reliably reproduce it. This issue is not occurring randomly.

**Comment by lminiero** [comment]
An increased deòay suggests that something may be wrong with respect to the RTCP exchange. How advanced is RTCP support in your WHIP integration?

**Comment by atoppi** [comment]
v0.10.10 is from two years ago, please try to experiment with a recent Janus version or you might encounter other issues that could have already been solved!

My advice for debugging the issue is to do a pcap through the admin API of both pub and sub legs, then study the RTP timestamps and check the origin of the skew.

**Comment by lminiero** [comment]
> v0.10.10 is from two years ago, please try to experiment with a recent Janus version or you might encounter other issues that could have already been solved!

I hadn't noticed the test was made against v0.10.10... then obviously yes, test the latest 0.x or master.

**Comment by lminiero** [comment]
That said, I don't see this delay with master. I've tried capturing the screen, using a stopwatch page demo, and the delay seemed constantly around 100/120ms to me (I've kept it open for some time).

![Screenshot_2023-05-18_17-27-04](https://github.com/meetecho/janus-gateway/assets/3684796/ac5fedc8-55e1-4a42-a12e-ae05e301a9da)

**Comment by winlinvip** [comment]
Understood, thank you. I will verify the most recent version.

**Comment by winlinvip** [comment]
I tested the version 1.1.4, still the same ,the latency is about 520ms

```
  Starting Meetecho Janus (WebRTC Server) v1.1.4
```

![image](https://github.com/meetecho/janus-gateway/assets/2777660/20d8f475-43f1-4068-a468-5866963a6f20)

You can reproduce the issue by following https://github.com/ossrs/ffmpeg-webrtc/pull/1#usage-ffmpeg-janus

**Comment by lminiero** [comment]
I already saw the instructions: how do you think I tested it the last time? :wink: 
As I already said, I don't get those delays. Sounds like an issue in your Janus setup maybe?

**Comment by winlinvip** [comment]
I got it. 👍  If you're unable to reproduce this issue, it's possible that the problem is specific to my environment. In that case, we can close this issue, and it's unlikely that others will encounter the same problem. 

Thank you for your attention. 😄
