### ISSUE TITLE
Add an event firehose to the admin/monitoring API

### ISSUE THREAD

**Issue by ndarilek** [meetecho/janus-gateway#323]
I would like to globally monitor all events associated with all sessions/handles from a single place, regardless of whether I myself have created them.

The use case is a microservice/component that tracks call state. While the authentication system is great and a useful first step, it still may be possible for users to create calls manually which they are not permitted to make. I would like to terminate these immediately when they are detected. I would also like to track call duration so I can bill users for time communicating with assistants, compensate assistants for same, and ensure that no one exceeds monthly call quotas.

A web socket interface from the admin API would be great for this. It could probably act the same as the traditional web socket API, except it would send all messages rather than just ones for sessions created by the connection. It'd be great if the same session could allow interacting with sessions in a limited way, but not strictly required. Maybe even just the ability to destroy sessions/handles would be useful, while leaving other functionality to the more traditional API.

Thanks.

**Comment by lminiero** [comment]
The admin API is already available over websockets in the modular-transports branch, which I encourage you to start testing as we'll make the switch soon.

While it may be interesting to add events to the admin API, we'll most definitely not duplicate functionality. So if you want to remove sessions and the like, you'd have to use the regular Janus API for that in conjuction with whatever info you get from the events.

**Comment by lminiero** [comment]
Implemented as part of a different API in #536.
