### ISSUE TITLE
[1.x] SIP plugin: typo in json transfer parameters validation structure

### ISSUE THREAD

**Issue by ycherniavskyi** [meetecho/janus-gateway#3235]
I'm fairly confident that `replace` should be used instead of `call_id`.

https://github.com/meetecho/janus-gateway/blob/125e0241bf87d6a5d7743b6dbc3db522840ffeb7/src/plugins/janus_sip.c#L818

**Comment by lminiero** [comment]
Good catch! I'll fix this right away :+1:

**Comment by lminiero** [comment]
Fixed in both `master` and `0.x`.
