### ISSUE TITLE
[1.x] Multiple calls when switching networks

### ISSUE THREAD

**Issue by RafaelFantinel** [meetecho/janus-gateway#3237]
Hello,

I face the following problem:
Multiple calls when switching networks.
I have an incoming call in progress, I make a second call to that same number, when switching internet during the calling process a second call is received to that number

**Comment by lminiero** [comment]
I'm sorry but I have no idea what problem you're talking about, or why you reopened this. If you're interested in our help, you'll need to be much more detailed than this, starting from which plugins are in use.
