### ISSUE TITLE
[1.x] Support for batched configure requests in Streaming Plugin

### ISSUE THREAD

**Issue by petarminchev** [meetecho/janus-gateway#3238]
We are very happy with the batch configure request in VideoRoom plugin - https://github.com/meetecho/janus-gateway/pull/2986.
For scaling purposes we rtp_forward to the Streaming Plugin. It would make our lives a lot easier if Streaming plugin supported batched configure requests. It is especially useful during paging - instead of sending dozens of requests to Janus, we will send only one configure request - which streams to be send: true/false. Also by looking at the VideoRoom pull request, it doesn't seem like a huge effort.
Could you consider adding batched configure requests to Streaming Plugin? We think it is a very valuable feature.

Thank you in advance!

**Comment by lminiero** [comment]
Well that patch wasn't small, and the Streaming plugin works a bit differently from the VideoRoom -- I wouldn't call it a "small effort" :stuck_out_tongue: 
I can add it to the todo list but not sure when I'll have time to do that. I'd obviously be happy to review a pull request that implements this feature too.

**Comment by lminiero** [comment]
Thanks! I'll try to do it later today.
