### ISSUE TITLE
[1.x]  twcc restore value in Status Vector Chunk

### ISSUE THREAD

**Issue by praveen-kd-23** [meetecho/janus-gateway#3253]
**What version of Janus is this happening on?**
Version 1.1.4

**Have you tested a more recent version of Janus too?**
Yes , Version 1.1.4

**Was this working before?**
No

**Additional context**
  While building a transport-cc Feedback packet , 
  
  status , max_status , all_same values were restored at Status Vector Chunk (T=1 , S=1) , but the same values not Restored at else case (T=1 , S=0). This will result in wrong feedback report .
  
  If case where Restore Values handled
  https://github.com/meetecho/janus-gateway/blob/bd6e1fe34fb2ee23555ab7651d06d595b6ea1d8e/src/rtcp.c#L1762
  
  else case where Restore Values not handled
  https://github.com/meetecho/janus-gateway/blob/bd6e1fe34fb2ee23555ab7651d06d595b6ea1d8e/src/rtcp.c#L1779
  
  
  Isn't the Restore values code block , common for both(S = 0 & S = 1) the Status Vector Chunk Cases .

**Comment by lminiero** [comment]
The whole team is on vacation, we'll have a look when we're back in a few weeks.

**Comment by praveen-kd-23** [comment]
Hi @atoppi  , 
    
    If you look at the code block above the mentioned one , it process only 7 packets , If the Queue contains 11 packets , T=1 S=1 branch will process only 7 packets from the queue , and the values need to be restored for the remaining 4 values in the queue .
    
    Similarly , for T=1 S=0  branch , It process only 14 elements , If there were more elements to present ( say queue contains 17 elements ) , values need to be restored for the remaining 3 values .

**Comment by atoppi** [comment]
@praveen-kd-23 I have seen your reply in an email but the message is missing here, did you delete it?

**Comment by praveen-kd-23** [comment]
I'm sorry to report that I have misreported the issue , As you mentioned there will not be a case where queue will have some packets after processing .

**Comment by atoppi** [comment]
reminder for me and @lminiero : the twcc report generation code needs a bit of refactoring :-P

**Comment by atoppi** [comment]
I'm reopening this since I've checked that the "reset for loop" is being called when adding losses to the link.

**Comment by atoppi** [comment]
After a bunch of tests with loss, delay and jitter, I concluded that the "reset for loop" could happen only when generating a 2-bits symbols, when e.g. getting a sequence like this:
```
(notreceived) (size=1)
(notreceived) (size=2)
(notreceived) (size=3)
(smalldelta) (size=4)
(smalldelta) (size=5)
(notreceived) (size=6)
(smalldelta) (size=7)
(largeornegativedelta) (size=8)
2-bits 7 symbols generated, (remaining=1)
```
Until the 7th symbol, the algorithm is trying to compose a 1-bit 14 symbols chunk but suddenly a large or negative delta comes in, so a 2-bits chunk must be generated, with the 8th status being still in the buffer.
