### ISSUE TITLE
[0.x] Not receiving screen media stream

### ISSUE THREAD

**Issue by NicolasDionB** [meetecho/janus-gateway#3261]
**What version of Janus is this happening on?**
0.13.3

**Have you tested a more recent version of Janus too?**
No, it's the production environnement.

**Was this working before?**
Yes it was working in 0.11.6 before our last update to 0.13.3 about 2 months ago.

**Additional context**
It used to work fine but now, sometimes, when we connect in a room with a screen sharing stream active (getDisplayMedia), and generally with a few other camera/microphone streams as well, we don't receive stream data at first. It seems that later on, if the person sharing the screen makes a big change, like change the displayed slide for instance, we may then receive the image. It's as if the client was waiting for a keyframe of some sort.

I don't have much more information for now on this as I wasn't able to reproduce the problem yet but we have multiple reports of this. Note that we do not use the _VideoRoom_ plugin for this but a custom plugin we made.

As something changed in the recent updates that could explain such a behavior?

I will post any updates I have on this but I wanted to open the issue in case someone could provide some insights on the problem.

**Comment by lminiero** [comment]
Closing.
