### ISSUE TITLE
[1.x]

### ISSUE THREAD

**Issue by necati1054** [meetecho/janus-gateway#3262]
**What version of Janus is this happening on?**
v0.7.3

**Have you tested a more recent version of Janus too?**
v0.7.3

**Was this working before?**
no

**Is there a gdb or libasan trace of the issue?**
https://pastebin.pl/view/0a585896
https://cdn.discordapp.com/attachments/1138848547748466698/1143138144162697236/image.png
https://cdn.discordapp.com/attachments/1138848547748466698/1143138266682499072/image.png
https://cdn.discordapp.com/attachments/1138848547748466698/1143138401663582268/image.png

**Additional context**

**Comment by RSATom** [comment]
You have to try the latest Janus version. v0.7.3 is too old.

**Comment by necati1054** [comment]
We had downloaded and directly installed from GitHub before. Can you provide the GitHub link for the new version? Let's do a fresh installation.

**Comment by RSATom** [comment]
I don't remember if Meetecho ever provided binaries. But you can try https://snapcraft.io/janus-gateway

**Comment by atoppi** [comment]
We have never published a binary release.

We recommend to follow the instructions written in the README and build from sources on this official repo.

Closing now, in case you still experience crashes with a fresh version feel free to reopen.

**Comment by atoppi** [comment]
For support and consultancy requests please send an email to info@meetecho.com or compile the contact form at www.meetecho.com
