### ISSUE TITLE
[0.x] Jnaus memory allocating in ice.c

### ISSUE THREAD

**Issue by vzhmachenko** [meetecho/janus-gateway#3268]
I updated my janus to v0.13.4. And as system's got pretty high load level there is some growing in memory usage until it is ends. But we can omit this problem for the present time. I've got Segmentation Fault one time and it seems there is some problem in ice.c file.
I see that you admit that there can be problem in g_thread_try_new, because I see the error checking. So maybe there is some reason to check 'loop'-variable in g_malloc0-allocating? Actually, I can see that it is not the only one example where you allocate memory and you suppose that there isn't any error occurred. Can you explain why you are going by this way?
Thankyou.

**Comment by lminiero** [comment]
> I've got Segmentation Fault one time

We'll need a stack trace of some sort, if you want us to check what's wrong.
janus.conf.meetecho.com/docs/debug

**Comment by vzhmachenko** [comment]
> We'll need a stack trace of some sort, if you want us to check what's wrong. janus.conf.meetecho.com/docs/debug

I've read the info you had given and there is an asked information: https://gist.github.com/vzhmachenko/a7532508904e0723f05f8521c1d92062
Please, correct me if I'm mistaken

**Comment by lminiero** [comment]
Unfortunately we can't use this stack as there's no symbols and no info on what happened or where.

**Comment by vzhmachenko** [comment]
It is pity. You can close it.

**Comment by vzhmachenko** [comment]
I've managed to get this: https://gist.github.com/vzhmachenko/a6d3402d3b2b725f3454c15149b16755
Please, look at this.

**Comment by lminiero** [comment]
> I've managed to get this: https://gist.github.com/vzhmachenko/a6d3402d3b2b725f3454c15149b16755

Still nothing helpful, I'm afraid, since it doesn't address line numbers. Please try the latest version of the `0.x` branch, as it looks like you're using some precompiled version of 0.13.4.

**Comment by lminiero** [comment]
@vzhmachenko have you tried the latest `0.x` as suggested?

**Comment by lminiero** [comment]
Ack, closing then.
