### ISSUE TITLE
missing publisher dereference when there is no buffer

### ISSUE THREAD

**Issue by wan721** [meetecho/janus-gateway#3269]
https://github.com/meetecho/janus-gateway/blob/2db954b8fac28858f10ce5b7ac46f569bd64f58a/src/plugins/janus_videoroom.c#L8206

Hi,
Are we missing a `janus_videoroom_publisher_dereference_nodebug(participant);` when there is no buffer?
Thanks

**Comment by lminiero** [comment]
I guess that was indeed an oversight, thanks for spotting it!
