### ISSUE TITLE
[1.x] Replace lua-ansicolors by lua-term

### ISSUE THREAD

**Issue by bkmgit** [meetecho/janus-gateway#3272]
**What version of Janus is this happening on?**
Latest development version

**Have you tested a more recent version of Janus too?**
This is on the most recent version

**Was this working before?**
This is a weak dependency package change

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
See https://github.com/hoelzro/ansicolors

**Comment by lminiero** [comment]
PR merged.
