### ISSUE TITLE
[1.x] Stream fails to load on Linux machine (tested on firefox, chromium and chrome)

### ISSUE THREAD

**Issue by fbrandle** [meetecho/janus-gateway#3285]
**What version of Janus is this happening on?**
commit ae23fb0f47ca3207cdd74b78d54212c08a402171 "[Use lua term (](https://github.com/meetecho/janus-gateway/commit/ae23fb0f47ca3207cdd74b78d54212c08a402171)https://github.com/meetecho/janus-gateway/pull/3273[)](https://github.com/meetecho/janus-gateway/commit/ae23fb0f47ca3207cdd74b78d54212c08a402171)"

**Have you tested a more recent version of Janus too?**

N/A, as it is the latest commit (except the log)

**Was this working before?**
unknown

**Is there a gdb or libasan trace of the issue?**
If you have a trace related to the issue (e.g., after a segfault), provide it as a gist/pastebin/other link here, or as a [collapsible section](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). Do **NOT** paste logs inline. For more information on the kind of traces we may find useful, please refer to the [documentation](https://janus.conf.meetecho.com/docs/debug).

https://pastebin.com/5himsC83

**Additional context**

Hello, we are currently evaluating janus to stream a video from some of our cameras to a users browser. During this we noticed, that on linux the stream is not working at all (the track instantly ends). On MacOS we were able to get it running in chrome, but not on safari. Sadly I was not yet able to investigate the MacOS issue, but I guess it is related to the linux one. Is this error something related to janus, or is it in the RTP transport? I am using the streaming example adapted to our current janus instance (URL is snipped in the chrome log and replaced with JANUS_SERVER_URL. The cameras are transmitting in h264 which seems to work. I hope you are able to help me with this issue! While I am not that knowledgable (yet), I think the line 122 "[266804:14:1027/105516.897914:INFO:media_session.cc(2851)] Video m= section 'v' being rejected in answer." seems to be especially interesting?

**Comment by lminiero** [comment]
Please ask questions on failed WebRTC streams on the [group](https://janus.discourse.group/). Per our guidelines, we only use github to track code issues, which this isn't (connectivity/codec problem).
