### ISSUE TITLE
[1.x] Stuttering video streams

### ISSUE THREAD

**Issue by pkb36** [meetecho/janus-gateway#3289]
hello.

I am testing Janus on the Nvidia Jetson Module.

I am testing on Jetpack OS 4.6 and upgraded to Jetpack OS 5.1.2 this time, and there was no problem with streaming on 4.6, but after upgrading to 5.1.2, when I look at the log of Janus, the video streaming is interrupted for a while after outputting the following message 100% after #2 NACK -- RTPFB (205) occurs.
[ice.c:janus_ice_cb_nice_recv:3150] [8229993576585489] >> 22358
[8229993576585489] >> >> Can't retransmit packet 22358, we don't have it...
Is there any solution for this cause?
What steps can we take?

Translated with www.DeepL.com/Translator (free version)

**Comment by lminiero** [comment]
I'm not familiar with Jetpack, but at this point I'd say it's an issue with that, rather than Janus. Please refer to the [group](https://janus.discourse.group/) for questions like this.
