### ISSUE TITLE
[1.2.1] janus.plugin.audiobridge not found

### ISSUE THREAD

**Issue by muramidaza** [meetecho/janus-gateway#3306]
I installed Janus-GateWay.

apt-get -y update && \
    aptitude install -y libmicrohttpd-dev libjansson-dev \
    libssl-dev libsofia-sip-ua-dev libglib2.0-dev \
	libopus-dev libogg-dev libcurl4-openssl-dev liblua5.3-dev \
	libconfig-dev pkg-config libtool automake doxygen graphviz \
    libusrsctp-dev \
    libavutil-dev libavcodec-dev libavformat-dev

wget https://github.com/cisco/libsrtp/archive/v2.2.0.tar.gz &&\
    tar xfv v2.2.0.tar.gz &&\
    cd libsrtp-2.2.0 &&\
    ./configure --prefix=/usr --enable-openssl &&\
    make shared_library && make install

    git clone https://gitlab.freedesktop.org/libnice/libnice &&\
    cd libnice &&\
    meson --prefix=/usr build && ninja -C build && ninja -C build install

git clone https://github.com/meetecho/janus-gateway.git &&\
    cd janus-gateway &&\
    sh autogen.sh && \
    	./configure --prefix=/usr/local --enable-docs --enable-post-processing && \
    	make && \
    	make install && \
    	make configs

Everything works except janus.plugin.audiobridge

**Comment by muramidaza** [comment]
The video room is working. Text chat works. But if I send a request for an audio room

**Comment by RSATom** [comment]
Audiobridge now has new dependency - libspeexdsp

So you should install libspeexdsp-dev too. Unfortunately it's not documented yet.

**Comment by muramidaza** [comment]
"/usr/local/lib/janus/plugins" no file. Have files: libjanus_echotest.la        libjanus_nosip.la        libjanus_recordplay.la        libjanus_sip.la        libjanus_streaming.la        libjanus_textroom.la        libjanus_videocall.la        libjanus_videoroom.la
libjanus_echotest.so        libjanus_nosip.so        libjanus_recordplay.so        libjanus_sip.so        libjanus_streaming.so        libjanus_textroom.so        libjanus_videocall.so        libjanus_videoroom.so
libjanus_echotest.so.2      libjanus_nosip.so.2      libjanus_recordplay.so.2      libjanus_sip.so.2      libjanus_streaming.so.2      libjanus_textroom.so.2      libjanus_videocall.so.2      libjanus_videoroom.so.2
libjanus_echotest.so.2.0.1  libjanus_nosip.so.2.0.1  libjanus_recordplay.so.2.0.1  libjanus_sip.so.2.0.1  libjanus_streaming.so.2.0.1  libjanus_textroom.so.2.0.1  libjanus_videocall.so.2.0.1  libjanus_videoroom.so.2.0.1

**Comment by RSATom** [comment]
Related announcement is here: https://janus.discourse.group/t/new-jitter-buffer-in-the-audiobridge-important/208

**Comment by muramidaza** [comment]
Thank you, after adding libspeexdsp-dev the audio room started working
