### ISSUE TITLE
[1.x] [plugin] [streaming] can we support more videos in one mountpoints

### ISSUE THREAD

**Issue by zyliu1985** [meetecho/janus-gateway#3309]
In multistream, we can support at most 3  video frame streams. Can we support more than 3?  Thank you .

videoport2 = second local port for receiving video frames (only for rtp, and simulcasting)
videoport3 = third local port for receiving video frames (only for rtp, and simulcasting)

such as:
videoport4 = third local port for receiving video frames (only for rtp, and simulcasting)
videoport5 = third local port for receiving video frames (only for rtp, and simulcasting)
or 
videoports = 0,1,2,3,4,5,6

**Comment by lminiero** [comment]
videoport2/3 have nothing to do with additional videos: they're for simulcast support. Multiple videos are already supported, as shown in the demos. Closing as not an issue.
