### ISSUE TITLE
Incorrect check for private IP range

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#331]
~~~~
Sep 18 10:15:59 node03 janus[31983]: [WARN] Janus is deployed on a private address (81.23.228.146) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
~~~~

By looking at the code, local_ip is checked as is, whcih I don't think it's correct, those macros seem to expect host order longs. Also those macros only work with IPv4 netmasks, AFAIS.

I tried to fix this [here](https://github.com/saghul/janus-gateway/tree/fix-local-ip-check) but kung-fu seems to be weak today, as it doesn't seem to work.

**Comment by lminiero** [comment]
Good point, I came to the knowledge of those macros when looking through the pull request for the multicast support in the streaming plugin:

https://github.com/meetecho/janus-gateway/pull/266/files#diff-b6451ee93281bd18cf90a556862c894eR2294

which does indeed use the long address and not the IP, my fault... looking at the code there the address should be in host order, maybe that's what is missing in your fix?

**Comment by lminiero** [comment]
Sorry, I should really double check before writing: the ```ntohl``` is there already!

**Comment by lminiero** [comment]
Played with those macros a bit and I still can't make much sense of them. I eventually prepared a very dumb check on the string itself using RFC1918 ranges and it seems to work consistently:

```
#include <stdio.h>
#include <stdlib.h>

#include <arpa/inet.h>

int main(int argc, char *argv[]) {
	if(argc < 2) {
		printf("Usage: %s ip\n", argv[0]);
		exit(1);
	}
	const char *local_ip = argv[1];
	printf("Checking %s...\n", local_ip);
	struct sockaddr_in addr;
	if(inet_pton(AF_INET, local_ip, &addr) > 0) {
		unsigned short int ip[4];
		sscanf(local_ip, "%hu.%hu.%hu.%hu", &ip[0], &ip[1], &ip[2], &ip[3]);
		if(ip[0] == 10) {
			printf("   -- Private address (class A)\n");
		} else if(ip[0] == 172 && (ip[1] >= 16 && ip[1] <= 31)) {
			printf("   -- Private address (class B)\n");
		} else if(ip[0] == 192 && ip[1] == 168) {
			printf("   -- Private address (class C)\n");
		} else {
			printf("   -- Public address\n");
		}
	}
	exit(0);
}
```

Probably not the prettiest code, but it does its job.

**Comment by saghul** [comment]
Heh, good one, thanks!
