### ISSUE TITLE
[1.x] NACK and REMB with SIP plugin audio

### ISSUE THREAD

**Issue by Mahmo0odsalah** [meetecho/janus-gateway#3310]
**What version of Janus is this happening on?**
1.1.1

**Have you tested a more recent version of Janus too?**
No, I checked the changes and there doesn't seem to be anything related to this behavior.

**Was this working before?**
No

**Is there a gdb or libasan trace of the issue?**
No
**Additional context**
I have been using Janus as a WebRTC server with the SIP plugin. My setup is pretty simple, the client (a web browser) establishes a WebRTC session with Janus which in turn establishes a SIP session with my SIP server. It’s Audio only. I was checking the SDP and nackCount and realized there’s no nack negotiation or actual NACK packets initiated from Janus. How do I configure Janus to both negotiate and use NACK.

I tried customizing the SDP on the client side to insert NACK negotiation rtcp-fb lines for every audio codec negotiated, but nothing changed. Janus just relays the SIP ANSWER received from the SIP server which of course doesn’t contain any NACK related stuff and it nevers requests any retransmissions.

**Comment by lminiero** [comment]
You've already mentioned this on the [group](https://janus.discourse.group/t/nack-and-remb-with-sip-plugin/724). Browsers don't negotiate NACK support for audio, but even if they did, Janus would terminate and handle it at the WebRTC level, and not forward NACK requests on the SIP side. REMB should already be relayed instead. Closing as not a code issue: discussion can continue on the group, if needed.

**Comment by Mahmo0odsalah** [comment]
@lminiero Thank you, I have some follow-ups. I hope you don't mind me mentioning you on the group
