### ISSUE TITLE
[1.x] Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.

### ISSUE THREAD

**Issue by kboek** [meetecho/janus-gateway#3320]
**What version of Janus is this happening on?**
1.2.2

**Have you tested a more recent version of Janus too?**
No, this is the most recent from the master branch

**Was this working before?**
Unsure

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
When creating an offer with RTCPeerConnection.createOffer(), the m=video comes first (at mid:0), but in the answer, the m=audio is first. This causes the error on the client side; as the order and media identifiers must match in SDP offer and answer. And therewith causes incompatibility with server-independent players, e.g. https://webrtc.player.eyevinn.technology/?type=whep

[answer.txt](https://github.com/meetecho/janus-gateway/files/13894105/answer.txt)
[offer.txt](https://github.com/meetecho/janus-gateway/files/13894106/offer.txt)

**Comment by lminiero** [comment]
You're using the plugins wrong. You're sending a recvonly offer to the VideoRoom (I guess for a subscriber?), that the VideoRoom will ignore, since the VideoRoom plugin always offers for subscribers. If you want to use Janus for WHEP, you need to use the Streaming plugin.
https://www.meetecho.com/blog/whep-qui/

**Comment by kboek** [comment]
Thank you for your response and blog article. So to connect WHIP to WHEP, do I need to create a mountpoint in the Streaming plugin that points to the stream in the Videoroom? And what would be the JSON for the "create" API call to the Streaming plugin?

**Comment by lminiero** [comment]
Please refer to the Streaming plugin documentation for that.
