### ISSUE TITLE
Toggle between rear and front camera in Javascript API[1.x]

### ISSUE THREAD

**Issue by Adrien300101** [meetecho/janus-gateway#3324]
Hi, 
Ihave been uing janus videoroom plugin and the Javascript API to built a video conferencing web app mainly meant for smartphones. I was wondering how to change between rear a d front camera for phones in the Javascript API. Is there a function to handle this or I need to create one on my own?

**Comment by lminiero** [comment]
Please use the [group](https://janus.discourse.group/) for "how to" questions. We only use github or code issues.
