### ISSUE TITLE
Add unauthenticated no-payload ping endpoint for health checks

### ISSUE THREAD

**Issue by husam212** [meetecho/janus-gateway#3336]
The current admin `ping` request is unauthenticated, but it requires a JSON payload, it's not possible to add a payload to health checks in most web servers (for example Caddy and Nginx) and DNS services (for example Route53 and Cloudflare). This makes it hard to implement auto-failover using reverse proxy or DNS service, it would be useful to have a dedicated URI `/ping` for health checks that doesn't require a payload.

**Comment by lminiero** [comment]
That's a good suggestion, thanks! I'll see if that can be added to the HTTP transport.

**Comment by lminiero** [comment]
Implemented in the commit above for both Janus and Admin APIs.

**Comment by husam212** [comment]
Thanks! That was quick.
