### ISSUE TITLE
[1.x] rtp_port_range not being respected

### ISSUE THREAD

**Issue by colinturner99** [meetecho/janus-gateway#3352]
**What version of Janus is this happening on?**
Janus version: 1203 (1.2.3) Janus commit: cb6e49138f0ddc1456f29bab4fed7d9851e1e00c

**Have you tested a more recent version of Janus too?**
Yes

**Was this working before?**
Yes in older version we had deployed 

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
When opening a RTP stream the port is random outside of the range in Janus.jcfg,

Janus.jcg 
media: {
        #ipv6 = true
        #ipv6_linklocal = true
        #min_nack_queue = 500
        rtp_port_range = "20000-30000"
        #dtls_mtu = 1200
        #no_media_timer = 1
        #slowlink_threshold = 4
        #twcc_period = 100
        #dtls_timeout = 500
}

Janus Startup Log

> Logger plugins folder: /lib/janus/loggers
> [WARN]  Couldn't access logger plugins folder...
> ---------------------------------------------------
>   Starting Meetecho Janus (WebRTC Server) v1.2.3
> ---------------------------------------------------
> 
> Checking command line arguments...
> Debug/log level is 4
> Debug/log timestamps are disabled
> Debug/log colors are enabled
> Adding 'vmnet' to the ICE ignore list...
> Using x.x.x.x as local IP...
> Token based authentication disabled
> Initializing recorder code
> RTP port range: 20000 -- 30000
> Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, full-trickle, IPv6 support disabled)
> ICE port range: 20000-30000
> STUN server to use: stun.l.google.com:19302
>   >> 74.125.250.129:19302 (IPv4)
> Testing STUN server: message is of 20 bytes
>   >> Our public address is x.x.x.x (Removed)
> TURN REST API backend: (disabled)
> Crypto: OpenSSL >= 1.1.0
> No cert/key specified, autogenerating some...
> Fingerprint of our certificate: 6C:C5:DA:E8:1B:C3:F1:EF:0C:65:7D:B1:EA:A6:A0:C7:AF:F9:34:11:41:18:77:21:75:2C:D3:F9:C0:F4:F9:85
> [WARN] Data Channels support not compiled
> Event handlers support disabled
> Plugins folder: /lib/janus/plugins

**Comment by atoppi** [comment]
tried with latest master, can not reproduce

**Comment by lminiero** [comment]
> When opening a RTP stream

I guess this depends on what you mean by "opening an RTP stream"? As Alessandro pointed out, this definitely works as expected on the WebRTC side (which is where that option applies).
