### ISSUE TITLE
[1.x] Crash / segfault on 1.2.2 

### ISSUE THREAD

**Issue by tespio** [meetecho/janus-gateway#3354]
**What version of Janus is this happening on?**
Janus version: 1202 (1.2.2) Janus commit: #3346 

**Have you tested a more recent version of Janus too?**
No. Since March 22 when i've compiled this commit with libasan it just crashed today.

**Was this working before?**
Well, intermittently, mostly yes, but since we started using 1.2.1 had several segfaults  (as reported [HERE](https://janus.discourse.group/t/strange-segfaults-on-1-2-1/948) on March 22)

**Is there a gdb or libasan trace of the issue?**
https://gist.github.com/tespio/1ffdc026c90bc2337b84492b656cf626

**Additional context**
It seems like I have more or less the same asan dump like the one mentioned on discourse [HERE](https://janus.discourse.group/t/videoroom-crash-on-janus-v1-2-1/867/9?u=tespio)

**Comment by atoppi** [comment]
@tespio @RSATom please test #3355

**Comment by tespio** [comment]
I've recompiled with the #3355 but it may take a while until I can come back with some observations, if any. (hopefully if it doesn't crash anymore so there won't be any observation to be made :) )

**Comment by tespio** [comment]
Okay, here we go again @atoppi. It took a while but it crashed again.

https://gist.github.com/tespio/4ac1473acb77cc7a0c8cda3ed9834a5d

**Comment by atoppi** [comment]
@tespio this one looks different. A `destroy` room request has freed a room that was being accessed while handling a RTP packet of one of the participants.
Please open a new issue.

If the previous crash is not happening anymore we'll close this one and merge the proposed patch.

**Comment by tespio** [comment]
> @tespio this one looks different. A `destroy` room request has freed a room that was being accessed while handling a RTP packet of one of the participants. Please open a new issue.
> 
> If the previous crash is not happening anymore we'll close this one and merge the proposed patch.

Okay @atoppi. I will open a new issue with the same gist. Thank you.
