### ISSUE TITLE
[1.x] Crash / segfault on 1.2.3 

### ISSUE THREAD

**Issue by tespio** [meetecho/janus-gateway#3360]
**What version of Janus is this happening on?**
Janus version: 1203 (1.2.3) Janus commit: #3355 

**Have you tested a more recent version of Janus too?**
No, after the previous issue we had and the fix we applied we ran it to see if it's stable.

**Was this working before?**
Since recompiling with the proposed patch following the issue #3354, it just crashed again with the out put in the gist below.

**Is there a gdb or libasan trace of the issue?**
https://gist.github.com/tespio/4ac1473acb77cc7a0c8cda3ed9834a5d

**Additional context**
(https://github.com/meetecho/janus-gateway/issues/3354#issuecomment-2074432879)

**Comment by lminiero** [comment]
Please test the PR linked above.

**Comment by tespio** [comment]
> Please test the PR linked above.

I have recompiled with the PR you linked and i'll be monitoring. Still compiled with libasan just in case. Will follow-up if the case. Thank you @lminiero !!!!

**Comment by lminiero** [comment]
@tespio any update?

**Comment by tombolk** [comment]
We have 3 Janus servers also running commit 263f1b0ac1d1a4c12c4fa18d675a85234a005118 but we are still experiencing segfaults. Is there a way we can provide more information about the segfault crashes to pinpoint the problem?

**Comment by atoppi** [comment]
@tombolk yes, share your gdb/asan dump here if you think it might be related, otherwise just open a new issue with a description of the use case and the call stacks from crash dump.

**Comment by tespio** [comment]
> @tespio any update?

Sorry for delay @lminiero , I have been on a business trip and away from computer. So far no, I didn't get any other segfault. At least on the servers running https://github.com/meetecho/janus-gateway/commit/263f1b0ac1d1a4c12c4fa18d675a85234a005118 !
So for now I have no updates.

**Comment by lminiero** [comment]
Ack, we'll merge then :+1:

**Comment by jessedewild** [comment]
@lminiero We are still having this issue when running the PR above.

**Comment by tespio** [comment]
> @lminiero We are still having this issue when running the PR above.

But is it the same issue @jessedewild  ? Do you have janus compiled with libasan and have the same dump like i had? Maybe it's something different?!

**Comment by jessedewild** [comment]
We now have compiled the Janus servers with libasan, and we are waiting for a 'segfault' crash to occur again! @tespio @lminiero
