### ISSUE TITLE
[1.x] inconsistency happen when more than 6 users join at same time 

### ISSUE THREAD

**Issue by venkateshcontus** [meetecho/janus-gateway#3362]
**What version of Janus is this happening on?**
[1.2.3](https://github.com/meetecho/janus-gateway/commit/77f2cb86466ba29199fd5fdef08bbd5a453f2bc1)

**Have you tested a more recent version of Janus too?**
Yes.

**Was this working before?**
No

**Is there a gdb or libasan trace of the issue?**
   Join more than 6 users **at same time** you feel the inconsistency. 

**Additional context**
 All the users does not get the all members streams. users get partial members stream. Joining time also increasing based on the members count. last users took 10 to 20 sec to join the room.

**Comment by lminiero** [comment]
You're clearly trying to open all those sessions in the same browser, so not an issue, as explained in [this comment](https://janus.discourse.group/t/problem-viewing-existing-stream-on-multiple-clients-sessions/987/2)

**Comment by venkateshcontus** [comment]
Hi,

     We are not trying in the same browser. I have a team with 10 members  tried in web and mobile app. In our application we have schedule meeting feature to create meeting link and share it to my members.
