### ISSUE TITLE
[1.x]inconsistency happen when more than 6 users join at same time with different browsers (web and mobile)

### ISSUE THREAD

**Issue by venkateshcontus** [meetecho/janus-gateway#3363]
What version of Janus is this happening on?
[1.2.3](https://github.com/meetecho/janus-gateway/commit/77f2cb86466ba29199fd5fdef08bbd5a453f2bc1)

Have you tested a more recent version of Janus too?
Yes.

Was this working before?
No

Is there a gdb or libasan trace of the issue?
Join more than 6 users at same time you feel the inconsistency.We are not trying in the same browser. I have a team with 10 members  tried in web and mobile app. In our application we have schedule meeting feature to create meeting link and share it to my members and join at same time.

Additional context
All the users does not get the all members streams. users get partial members stream. Joining time also increasing based on the members count. last users took 10 to 20 sec to join the room.

**Could you share the best configuration with 8 members.**

**Comment by atoppi** [comment]
> All the users does not get the all members streams. users get partial members stream.

Share a janus message/events log for a client with this issue. I suspect this is something related to client code.

> Joining time also increasing based on the members count. last users took 10 to 20 sec to join the room

10 users joining at the same time is a quite common scenario. I never experienced a 20 secs waiting, again this smells like issue with the application code.

> Could you share the best configuration with 8 members.

No idea what is the question.

**Comment by lminiero** [comment]
@venkateshcontus any update on what Alessandro asked?

**Comment by venkateshcontus** [comment]
Hi,

     Please wait will share the logs

**Comment by venkateshcontus** [comment]
Hi,

This is the Janus server configuration we are using, with this configuration while joining 8 members in a room we are facing the issue mentioned earlier.

cpu cores       : 1
vCPU : 2
Memory : 6GB
Download: 1020.72 Mbit/s
Upload: 1004.01 Mbit/s
Ping : 64 bytes from [8.8.8.8](http://8.8.8.8/): icmp_seq=1 ttl=60 time=11.4 ms
Ping : 64 bytes from [1.1.1.1](http://1.1.1.1/): icmp_seq=3 ttl=60 time=1.34 ms

https://mf-janus-test.mirrorfly.com/?room=1 - more than 6 members join the same room with their own system we got the latency.

**Comment by lminiero** [comment]
This is not the information Alessandro asked for. Please share the message flow for a client with issues.

**Comment by atoppi** [comment]
On top of that, even mimicking the layout,  that web app is not the one we have on our demos.

**Comment by venkateshcontus** [comment]
Hi,

     Yes, we changed the limit size from 6 to 10 from your default demo page. Please find the event log in one of the client.It took almost 1.5 mins to render all the 9 users video.
[websocket_messages.json](https://github.com/meetecho/janus-gateway/files/15432021/websocket_messages.json)

**Comment by lminiero** [comment]
@venkateshcontus any update on this? If not, we'll just close the issue as there isn't any, from our perspective.

**Comment by venkateshcontus** [comment]
@lminiero Thanks for your support. After enabling full_trickle = true janus.jcfg it works as expected. All the 8 to 10 members are joined quickly. Please close this ticket.
