### ISSUE TITLE
[1.x] Commandline option "--version" no longer exists

### ISSUE THREAD

**Issue by fancycode** [meetecho/janus-gateway#3383]
**What version of Janus is this happening on?**
```
Janus version: 1203 (1.2.3)
Janus commit: bc044995a94c623b747bb35ecb9f059190903803
```

**Have you tested a more recent version of Janus too?**
no

**Was this working before?**
This is working with the 0.x branch.

**Additional context**
Looks like this got removed by the migration away from gengetopt which added a handler for `--version` automatically.

We used this on our build systems as a simple check to see if all dependencies are available, so it would be great if this could be re-added. I'll check if I find some time the next days to prepare a PR myself.

**Comment by lminiero** [comment]
> Looks like this got removed by the migration away from gengetopt

Yeah, this is very likely: in `1.x` we create the options programmatically with GLib (GoptionEntry), which does generate a helper automatically (`-h`) but it doesn't indeed expose a version too as we did before. This should be added to `options.c`/`.h`. I'm out of office the next few days but I'll look into it when I'm back.
