### ISSUE TITLE
[1.x] why is it recommended to use libnice v0.1.18? libnice 0.1.19 exists a number of bug fixes

### ISSUE THREAD

**Issue by alexber220** [meetecho/janus-gateway#3385]
**What version of Janus is this happening on?**
Janus version: 1203 (1.2.3)
Janus commit: bc044995a94c623b747bb35ecb9f059190903803

**Have you tested a more recent version of Janus too?**
no

**Additional context**
can i use libnice 0.1.22?

**Comment by lminiero** [comment]
Please start discussions or ask questions on our [https://janus.discourse.group/](Discourse), not here. We only use github for code issues.
