### ISSUE TITLE
[1.x] How to set the sip server address for pure WebRTC<->SIP Gateway

### ISSUE THREAD

**Issue by flantel** [meetecho/janus-gateway#3393]
Hi,

I have a Kamailio proxy, and want all WebRTC to be forwared to that proxy (not web UI, just WebRTC protocol to SIP) 

I can't find where to set this.

Thanks

**Comment by lminiero** [comment]
Please post questions on the [group](https://janus.discourse.group/), we only use github for code issues and pull requests.
