### ISSUE TITLE
[0.x] Linking errors due to C++ dependency in recent versions of BoringSSL

### ISSUE THREAD

**Issue by uxmaster** [meetecho/janus-gateway#3395]
**What version of Janus is this happening on?**
0.14.3 (commit 2b2aa11)

**Have you tested a more recent version of Janus too?**
This is the latest 0.x version

**Was this working before?**
It was working with the previous chromium-stable BoringSSL commit 1b7fdbd9101dedc3e0aa3fcf4ff74eacddb34ecc.

**Is there a gdb or libasan trace of the issue?**
N/A

**Additional context**
With recent versions of BoringSSL (https://boringssl.googlesource.com/boringssl/+log/refs/heads/chromium-stable), Janus build fails with linker errors pointing to undefined symbols from C++ standard library.

It is probably due to https://boringssl-review.googlesource.com/c/boringssl/+/66288

**Comment by lminiero** [comment]
Good catch: I already fixed this in a local setup (where I was experimenting with BoringSSL for a different reason) but forgot to push the fix upstream. I'll do that shortly.
