### ISSUE TITLE
1.2.2  --enable-post-processing

### ISSUE THREAD

**Issue by qet119** [meetecho/janus-gateway#3397]
./configure --prefix=/opt/janus --enable-post-processing --enable-libsrtp2 --enable-json-logger -disable-aes-gcm

When compiling version 1.2.2 --enable-json-logger, the following problem occurs

postprocessing/pp-av1.c: In function 'janus_pp_av1_close':
postprocessing/pp-av1.c:531:14: error: 'AVFormatContext {aka struct AVFormatContext}' has no member named 'url'
g_free(fctx->url);
^~
postprocessing/pp-av1.c:532:7: error: 'AVFormatContext {aka struct AVFormatContext}' has no member named 'url'
fctx->url = NULL;
^~
Makefile:2651: recipe for target 'postprocessing/janus_pp_rec-pp-av1.o' failed
make[2]: *** [postprocessing/janus_pp_rec-pp-av1.o] Error 1
make[2]: Leaving directory '/opt/janus-gateway-1.2.2/src'
Makefile:1386: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/opt/janus-gateway-1.2.2/src'
Makefile:566: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

This issue has been confirmed to not exist in versions 1.2.0 and 1.2.1

**Have you tested a more recent version of Janus too?**
YES

**Comment by atoppi** [comment]
You're probably linking against an old version of ffmpeg.

**Comment by computersalat** [comment]
Then why is there no check for a minimum version ? What is the minimum version needed ?
``` 
[   50s] checking for
[   50s]                            glib-2.0 >= 2.34
[   50s]                            jansson >= 2.5
[   50s]                            libssl >= 1.0.1
[   50s]                            libcrypto
[   50s]                            libavutil
[   50s]                            libavcodec
[   50s]                            libavformat
[   50s]                            ogg
[   50s]                            zlib
[   50s]                          ... yes
```

running into exact same problem:
```
[   79s] postprocessing/pp-av1.c: In function 'janus_pp_av1_close':
[   79s] postprocessing/pp-av1.c:531:14: error: 'AVFormatContext {aka struct AVFormatContext}' has no member named 'url'
[   79s]    g_free(fctx->url);
[   79s]               ^~
[   79s] postprocessing/pp-av1.c:532:7: error: 'AVFormatContext {aka struct AVFormatContext}' has no member named 'url'
[   79s]    fctx->url = NULL;
[   79s]        ^~
```

Looks like libavformat57 is too old ?

**Comment by atoppi** [comment]
It was added in https://github.com/FFmpeg/FFmpeg/commit/ea3672b7d67c432724bdbc8de0221f869b6a04c6 (January 2018), with ffmpeg v4.
Libavformat57 is for ffmpeg 3.x, so yes, it's quite old and does not include that field.
