### ISSUE TITLE
[1.1.3] After enabling Janus Full Trickle, ICE Connected state was never successful for some users.

### ISSUE THREAD

**Issue by vishercontus** [meetecho/janus-gateway#3399]
**What version of Janus is this happening on?**
1.1.3

**Have you tested a more recent version of Janus too?**
No

**Was this working before?**
Never Tried before.

We have enabled Full Trickle in Janus  server  as we noticed delay in joining the call. After enabling  we have added the below code in iOS & Android . 

//  peerConnection.add(RTCIceCandidate(sdp: candidate, sdpMLineIndex: sdpMLineIndex, sdpMid: sdpMid)) 
// candidate,sdpMLineIndex,sdpMid => Received from Janus.

When joining with multiple users (4 users) in a call at the same time ICE Connected state was never triggered  randomly for at least one of the user in the call.  Ice connection was never successful for that User., but the candidates are received  from the server. This is happening in 3 out of 10 calls. Issue was not observed when users are joining one by one with minimal delay.

**Comment by lminiero** [comment]
If Janus is sending the candidates, it looks like a client side issue: maybe you're not passing candidates to the PeerConnection object correctly. Also make sure you inspect the Janus Admin API, to see what the ICE status is for the affected handles. That said, this is not a code issue but a usage one, so it's out of scope here: please refer to the [group](https://janus.discourse.group/).
