### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 

### ISSUE THREAD

**Issue by adi-BW** [meetecho/janus-gateway#3405]
**What version of Janus is this happening on?**
I have taken the latest pull of the janus code.

**Additional context**
I am trying to connect to janus media server.
I have deployed my client code behind nginx and deployed my janus server on another cloud server.
so whenever I try to make connection to the janus using videoroom plugin I got this error.
**net::ERR_INCOMPLETE_CHUNKED_ENCODING 200**
surprisigly sometime connection made successfully but sometime giving error.
I have checked my janus logs and they are giving this error.
**[ERR] [transports/janus_http.c:janus_http_send_message:1097] Invalid HTTP connection...**

can you please help why this is happening.
![browser_trace](https://github.com/meetecho/janus-gateway/assets/139936563/24d9f277-5b7c-47b9-a06f-e70178e1380f)
![Capture](https://github.com/meetecho/janus-gateway/assets/139936563/9a0e4cdf-5b12-415c-b925-cf4acd532d30)

**Comment by lminiero** [comment]
Please ask questions like this on the [group](https://janus.discourse.group/), not here, since this looks like a configuration problem and not a code issue (we only use github for the latter).

**Comment by adi-BW** [comment]
this is not a configuration problem.
the same configurations works well with previous versions of Janus.
I think there is some problem with the code.

**Comment by radojko** [comment]
I had the same issue with current master version but had no issue with 1.2.3.
Problem solved with older master version then current with: 
git checkout ea2799743d49938077c8267d85af1cf79777d3c5

**Comment by radojko** [comment]
I had the same issue with current master version but had no issue with 1.2.3.
Problem solved with older master version then current with: 
git checkout ea2799743d49938077c8267d85af1cf79777d3c5

**Comment by atoppi** [comment]
Then bisect Janus and provide the commit.

**Comment by lminiero** [comment]
We found the cause of the issue: it was an unintended consequence of c161ca023fe9be31016407172f52145cddc6f94b, where we normalized the value of `janus_get_monotonic_time()`. I'm about to push a fix for that.
