### ISSUE TITLE
Required Nginx/Apache Server configuration

### ISSUE THREAD

**Issue by venkateshcontus** [meetecho/janus-gateway#3413]
What version of Janus is this happening on?
[1.2.3](https://github.com/meetecho/janus-gateway/commit/77f2cb86466ba29199fd5fdef08bbd5a453f2bc1)

Have you tested a more recent version of Janus too?
Yes.

Was this working before?
-

What are the basic configurations need to update based on the call usage in the nginx/apace server.

**Comment by lminiero** [comment]
Please ask questions on the [group](https://janus.discourse.group/), not here. We only use Github for code issues.
