### ISSUE TITLE
[1.x]Does the video room plugin support data channels?

### ISSUE THREAD

**Issue by AnasIncense** [meetecho/janus-gateway#3417]
**What version of Janus is this happening on?**
Put the version and the commit identifier (available in `version.c` or from an `info` request) here
v1.2.2
**Have you tested a more recent version of Janus too?**
Yes/no. If yes, which one. If not, why.
no
**Was this working before?**
If you have information on a version/commit where the issue wasn't there (e.g., the result of a `git bisect`), please provide it here.

**Is there a gdb or libasan trace of the issue?**
If you have a trace related to the issue (e.g., after a segfault), provide it as a gist/pastebin/other link here, or as a [collapsible section](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). Do **NOT** paste logs inline. For more information on the kind of traces we may find useful, please refer to the [documentation](https://janus.conf.meetecho.com/docs/debug).

**Additional context**
The audio and video transmission is perfect in the video room, and I want to use the data channel to transfer files while transmitting audio and video. Found that the sdp forwarded by Janus contains information about "m=application". But the data channel was not successfully established, so does Janus not support data channels in the video room plugin?

**Comment by atoppi** [comment]
Yes it does.

**Comment by AnasIncense** [comment]
Thank you.😊
