### ISSUE TITLE
[0.x] Rtsp mountpoint not created

### ISSUE THREAD

**Issue by c-dshah** [meetecho/janus-gateway#3425]
Facing an error for creating RTSP mountpoint in janus:

Adding Streaming mountpoint 'Rtsp-NVR-Stream'
Audio NOT enabled, Video enabled
Starting streaming relay thread
DESCRIBE answer:RTSP/1.0 200 OK
CSeq: 1
Content-Base: rtsp://rtsp:rtsp@173.15.173.249:5540/b5779bbb8f40b3432d9907ea7bd30e0ae9a47c231cf030eb485fb0b4bf6ff4e9/
Content-Length: 250
Content-Type: application/sdp
Server: gortsplib

v=0
o=- 0 0 IN IP4 127.0.0.1
s=Stream
c=IN IP4 0.0.0.0
t=0 0
m=video 0 RTP/AVP 96
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; sprop-parameter-sets=Z01AFouVAUB7QgAAK/IAAr8hCA==,aP44gA==; profile-level-id=4D4016
a=control:trackID=0

[Rtsp-NVR-Stream] Found sprop-parameter-sets: Z01AFouVAUB7QgAAK/IAAr8hCA==,aP44gA==
^[[31m[ERR]^[[0m [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:8274] Couldn't SETUP, got error code: 461
^[[31m[ERR]^[[0m [plugins/janus_streaming.c:janus_streaming_init:2791] Error creating 'rtsp' mountpoint 'Rtsp-NVR-Stream'...

**Comment by atoppi** [comment]
The rtsp endpoint (gortsplib) is answering with error 461 (Unsupported Transport) to the SETUP request.

**Comment by lminiero** [comment]
Already discussed o the group, closing.
