### ISSUE TITLE
[1.x] Janus docker container restarts

### ISSUE THREAD

**Issue by Denis155** [meetecho/janus-gateway#3429]
**What version of Janus is this happening on?**
Janus version: 1300 (1.3.0)

**Have you tested a more recent version of Janus too?**
No, we are using the latest version

**Additional context**
Hello
I have a problem. Docker container with Janus sometimes restarts. I can't find the reason for this. Are there any errors in the log file that can cause the restart?
[janus.log](https://github.com/user-attachments/files/17037525/janus.log)
The restart usually occurs during periods of most intensive use of the video room plugin.
Last restart time [Mon Sep 16 12:27:02 2024]

**Comment by atoppi** [comment]
`v1.3.0` is (still) not provided by us.
Closing since we can not help with problems affecting unofficial releases.

**Comment by atoppi** [comment]
Sorry for the misunderstanding, I did not recall that v1.3.0 is the next planned release.

**Comment by atoppi** [comment]
Well actually there is a very large number of errors in the log file, but nothing seems to directly relate to a crash or similar.

You could try running the server with sanitizers in order to check if some fatal condition is being encountered during the execution.

**Comment by Denis155** [comment]
I'll try, thanks.
