### ISSUE TITLE
[1.x] update videocall plugin docs to remove/replace apprtc link

### ISSUE THREAD

**Issue by sandeshkhadka** [meetecho/janus-gateway#3431]
**What version of Janus is this happening on?**
1.3.0

**Have you tested a more recent version of Janus too?**
Yes

**Was this working before?**
Yes

**Is there a gdb or libasan trace of the issue?**
N/A
(https://janus.conf.meetecho.com/docs/debug).

**Additional context**
I was reading the janus docs and found the apprtc link mentioned in the videocall plugin (https://apprtc.appspot.com) returns 404 error. After visiting apprtc's github I got to know it has been shutdown.  It might be good to update the docs to either replace the link with apprtc's github repo(https://github.com/webrtc/apprtc) or simply remove the link. 
I can raise a PR if you wish

**Comment by lminiero** [comment]
Thanks for the heads up! No need for a PR, I'll fix it myself.
