### ISSUE TITLE
[1.x] videoroom janus turnserver

### ISSUE THREAD

**Issue by gushenjie** [meetecho/janus-gateway#3432]
I have a problem now. The janus service is deployed on a public network server, and turnserver is deployed on another server. I filled in the address information of turnserver in the js client, and found that the video screen cannot be transmitted through videoroomtest.html. I used https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ to test that turnserver can make a hole successfully. If the two services are deployed on the same server, there will be no problem.

**Comment by lminiero** [comment]
Please ask questions like this on the [group](https://janus.discourse.group/), we only use Github for code issues.
