### ISSUE TITLE
[1.x] Error in log file

### ISSUE THREAD

**Issue by Denis155** [meetecho/janus-gateway#3433]
**What version of Janus is this happening on?**
Janus version: 1300 (1.3.0)

**Have you tested a more recent version of Janus too?**
No, we are using the latest version

**Additional context**
Hello
I see a lot of similar errors in the Janus log file:
[[31 m[ERROR]^[[0 m [ice.c:janus_ice_outgoing_traffic_handle:4896] [6410793062591149] ... has only -1 byte been sent? (it was 1037) instead of -1 byte? (it was 71)

What does this really mean?
And could this trigger a restart of Janus?

**Comment by atoppi** [comment]
It means Janus is trying to send packets to a not reachable (anymore) endpoint because e.g. the other side switched ICE pair or some other network issue occurred.

> And could this trigger a restart of Janus?
I don't think so but maybe a prolonged status might trigger undefined side-effects.

**Comment by Denis155** [comment]
Okay, thank you
