### ISSUE TITLE
[1.x]  how to config  video room  cascading  in two host?

### ISSUE THREAD

**Issue by zzxap** [meetecho/janus-gateway#3434]
**What version of Janus is this happening on?**
1.2.4

**Have you tested a more recent version of Janus too?**
Yes

**Was this working before?**
no

**Is there a gdb or libasan trace of the issue?**
no

**Additional context**
I had run janus success in a single host. but i want to run it in two host like janusA janusB

I  had read https://www.meetecho.com/blog/sfu-cascading/ 
            and https://github.com/meetecho/janus-gateway/pull/3014
but i dont konw how to config it in *.jcfg file  .how to  config  two janusServer  in  the  .jcfg file? 
 janusA  how to  know  janusB  exists?

and how to post a request?  is there a demo about 
how to 
request: "add_remote_publisher",  
 request: "publish_remotely",

janusA  how to  know  janusB  exists? when add_remote_publisher

need  to  set two host public ip in nat_1_1_mapping of janus.jcfg?

**Comment by atoppi** [comment]
You can't do that through manual configuration of jcfg files.
You need to use the plugin APIs.

Orchestration must be performed by a separate piece of software, like an application server.

**Comment by zzxap** [comment]
> You can't do that through manual configuration of jcfg files. You need to use the plugin APIs.
> 
> Orchestration must be performed by a separate piece of software, like an application server.



> You can't do that through manual configuration of jcfg files. You need to use the plugin APIs.
> 
> Orchestration must be performed by a separate piece of software, like an application server.
to the video room api hard to understand how 
{
	request: "publish_remotely",
	room: 1234,
	publisher_id: 98765432,
	secret: "adminpwd",
	remote_id: "test",
	host: "<IP of target>",
	port: 10000,
	rtcp_port: 10001
}     
the host is janusA or janusB's IP? 
how they know each other?

**Comment by atoppi** [comment]
Please use https://janus.discourse.group/ for questions unrelated to code issues.

**Comment by zzxap** [comment]
https://janus.conf.meetecho.com/docs/videoroom   
the video room api not say how to use request: "publish_remotely",
