### ISSUE TITLE
[1.x]janus_audiobridge_participant’ has no member named ‘annc

### ISSUE THREAD

**Issue by zzxap** [meetecho/janus-gateway#3436]
when buile jauns 

plugins/janus_audiobridge.c: In function ‘janus_audiobridge_process_synchronous_request’:
plugins/janus_audiobridge.c:5550:73: error: ‘janus_audiobridge_participant’ has no member named ‘annc’
 5550 |                         json_object_set_new(pl, "file_id", json_string(p->annc->id));
      |                                                                         ^~
plugins/janus_audiobridge.c:5551:29: error: ‘janus_audiobridge_participant’ has no member named ‘annc’
 5551 |                         if(p->annc->filename)
      |                             ^~
plugins/janus_audiobridge.c:5552:82: error: ‘janus_audiobridge_participant’ has no member named ‘annc’
 5552 |                                 json_object_set_new(pl, "filename", json_string(p->annc->filename));
      |                                                                                  ^~
plugins/janus_audiobridge.c:5553:61: error: ‘janus_audiobridge_participant’ has no member named ‘annc’
 5553 |                         json_object_set_new(pl, "playing", p->annc->started ? json_true() : json_false());
      |                                                             ^~
plugins/janus_audiobridge.c:5554:58: error: ‘janus_audiobridge_participant’ has no member named ‘annc’
 5554 |                         json_object_set_new(pl, "loop", p->annc->loop ? json_true() : json_false());
      |                                                          ^~
At top level:
plugins/janus_audiobridge.c:1421:36: warning: ‘checkstop_file_parameters’ defined but not used [-Wunused-variable]
 1421 | static struct janus_json_parameter checkstop_file_parameters[] = {
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
plugins/janus_audiobridge.c:1415:36: warning: ‘play_file_parameters’ defined but not used [-Wunused-variable]
 1415 | static struct janus_json_parameter play_file_parameters[] = {

**Comment by tmatth** [comment]
Seems like the build is broken if libogg isn't present, should be fixed in #3438.
