### ISSUE TITLE
[1.x][FATAL] [janus.c:main:5906] No Janus API transport is available... enable at least one and restart Janus

### ISSUE THREAD

**Issue by zzxap** [meetecho/janus-gateway#3437]
after build 
and run
 /opt/janus/bin/janus -F /opt/janus/etc/janus
it show
 [FATAL] [janus.c:main:5906] No Janus API transport is available... enable at least one and restart Janus

how to fix this? 1.2.4

**Comment by tmatth** [comment]
You need to build and enable at least one of the Janus transport APIs (http, nanomsg, pfunix, rabbitmq and/or websockets). For getting started, http is probably the simplest (requires libmicrohttpd). See: https://janus.conf.meetecho.com/docs/rest.html

**Comment by zzxap** [comment]
./configure --prefix=/opt/janus 
make
make install
make configs

is build like this will enable websockets and http?

**Comment by zzxap** [comment]
after build  not janus.transport.http.jcfg  in /opt/janus/etc/janus
I put a janus.transport.http.jcfg  in /opt/janus/etc/janus
set https = true  and set certificates:
 run 
/opt/janus/bin/janus -F /opt/janus/etc/janus

https service  is not  up

lsof -i:8089  show nothing

**Comment by zzxap** [comment]
no log HTTP webserver started (port 8088, /janus path listener)...
https server not start  
http not contain in build 

./configure --prefix=/opt/janus
make
make install
make configs

**Comment by lminiero** [comment]
As Tristan said, you didn't compile any transport plugin. The `configure` script tries to find dependencies, if one isn't found the related plugin isn't built. Very likely you don't have the dev versions of MHD or libwebsockets. Check the outptut of the configure at the end, it will tell you what it will build.

Closing as not a code issue.
