### ISSUE TITLE
[1.x] Stability issues

### ISSUE THREAD

**Issue by Niks950** [meetecho/janus-gateway#3439]
**What version of Janus is this happening on?**
1.2.4
 commit-hash: 4f8f00ff5d3e0bcea715bb007328ded712f4e447

**Have you tested a more recent version of Janus too?**
Yes. 1.3.0

**Additional context**
Hello
I have several problems using the VideoRoom plugin.
1. Audio or video from the participants is interrupted and freezes.
2. Docker container with Janus restarts when a large number of participants connect to the video room
Problems occur if there are a large number of participants in the room, more than 100.

How can I determine the cause of these problems?

**Comment by lminiero** [comment]
The VideoRoom is not meant to handle that many users, at least not out of the box. The helper threads functionality in #3067 should help, but that also depends on what you mean by 100 participants, and how they're handled (multistream vs separate connections): if they're all active, you're creating a huge mesh that will basically kill participants with the bandwidth.

**Comment by Niks950** [comment]
Yes, I use multistream. In my scenario, there are about 100 people in the video room, but audio and video streams are broadcast only from 2-3 people, the rest of the participants are listeners, these participants often have the problem that they do not see or hear video or audio from those 2-3 people. Reconnecting to the video room often solves the problem.

**Comment by lminiero** [comment]
Then see what I said about helper threads, that are disabled by default.

**Comment by Niks950** [comment]
Thank you! Can you give a recommendation on setting the number of helper threads in my case, please? When about 100 participants join the room at about the same time.

**Comment by lminiero** [comment]
I don't have any recommendation. It's up to you to experiment. If you check the [group](https://janus.discourse.group/), there were some discussions on how to use helper threads for the Streaming plugin, and it's not that different in the VideoRoom (even though the approach is different). Start with 1, check the results, then try more. You definitely don't want a 100.
