### ISSUE TITLE
[1.x] no unpublished event for remote publishers on remove_remote_publisher

### ISSUE THREAD

**Issue by spscream** [meetecho/janus-gateway#3442]
**What version of Janus is this happening on?**
master

**Have you tested a more recent version of Janus too?**
tested on master

**Was this working before?**
I don't tested on earlier versions

**Is there a gdb or libasan trace of the issue?**
no

**Additional context**
When we call remove_remote_publisher only leaving event is generated, publishers don't get unpublished event

**Comment by lminiero** [comment]
> publishers don't get unpublished event

Did you mean "other participants" when saying "publishers"?

I don't think that's an issue: `leaving` kinda "includes" `unpublished`, and so receiving that should act as a trigger for the latter too. Usually `unpublished` only makes sense if you close your publisher PeerConnection but stay in the room, which is not what `remove_remote_publisher` does (the related publisher instance is removed entirely).

**Comment by spscream** [comment]
So why regular publishers appear different than remote and doesn't work the same? Documentation says nothing about it.

documentation about publishers `unpublished` event says what:
```
Notice that the same event will also be sent whenever the publisher feed disappears for reasons other than an explicit unpublish , e.g., because the handle was closed or the user lost their connection. Besides, notice that you can publish and unpublish multiple times within the context of the same publisher handle.
```

I explain why this is important for our case and :
we don't have direct connection of our clients to janus, janus sessions are created by our backend and we produce our own events (vr_published/vr_unpublished) to clients based on published/unpublished events from janus. We don't react to leaving events from janus now because we were relied on documentation about `unpublished` event.

If regular publisher dissapears by reasons other than an explicit unpublish, our clients got vr_unpublished event anyway, but in case of the remote publisher dissapearing they don't receive anything now.

We can add vr_unpublished event to our client based on leaving event, but we will have double vr_unpublished event for our clients, since we still have handle of unpublished event

So to fix our case we can:
- add handling of leaving event and send new `vr_leaving` event(which will not be backward compatibly with current clients versions)
- distinguish remote publisher and local publisher in state of our app to react differently, which leads to some overhead in state and logic

**Comment by lminiero** [comment]
> * add handling of leaving event and send new `vr_leaving` event(which will not be backward compatibly with current clients versions)

You could send `vr_unpublished` when you get the `leaving` event too. I don't see the need for a new event.
