### ISSUE TITLE
[1.x] Segmentation Fault on janus_recordplay_playout_thread

### ISSUE THREAD

**Issue by Loki899899** [meetecho/janus-gateway#3445]
**What version of Janus is this happening on?**
"version": 1104,
 "version_string": "1.1.4",
 "commit-hash": "cce3f2399830a1f62116af9eb08821ae63bda0f0",

**Have you tested a more recent version of Janus too?**
No, currently I'm not able to(won't be for a while), I'll update results accordingly once I test the latest version.

**Was this working before?**
First time encountering this. Earlier version didn't seem to have this problem

**Is there a gdb or libasan trace of the issue?**
Please find the GDB trace [here](https://pastebin.com/TjLwqcUp).

**Additional context**
System: CentOS Stream release 8
Please let me know if any other details are needed.

**Comment by lminiero** [comment]
1.1.4 is a year and a old half: I most definitely recommend upgrading. That said, your gdb trace doesn't seem to provide ny useful info, as the line it points to can't possibly crash (it's a simply math on number variables). The only recent fix we made to Record&Play that could cause a crash is https://github.com/meetecho/janus-gateway/commit/bad60d7032026af453a98ed7aba7fbc083385ea2 so when you upgrade you should be able to confirm whether that was the actual cause of yours too. Before submitting new reports, please considering building with libasan support which will give better info on the causes of a crash.

**Comment by Loki899899** [comment]
I'll definitely be upgrading
Sorry the trace wasn't helpful (math, I thought the same, I did try to check the values the ts_diff seemed null and the line above it seemed to have no value for video->prev I thought that could be something), not good at C.
Also while building next time I'll surely try to do it with libasan

**Comment by lminiero** [comment]
@Loki899899 any update on this?

**Comment by Loki899899** [comment]
Updated to the latest version and it seems everything is working fine, haven't encountered this again, guess I'll close it.
Thank you for your time.
