### ISSUE TITLE
[1.x]no events receive when open events=true

### ISSUE THREAD

**Issue by zzxap** [meetecho/janus-gateway#3448]
janus.eventhandler.gelfevh.jcfg.
janus.transport.http.jcfg
janus.transport.websockets.jcfg

set
enabled = true	

backend = "www.xxsssa.com"

on backend net.Listen("tcp", ""+":"+port)

when invoke   http create room and join room .no event com to the backen.

**Comment by lminiero** [comment]
Please ask questions like this on the [group](https://janus.discourse.group/).
