### ISSUE TITLE
[1.x]is it possible set any room's secret?

### ISSUE THREAD

**Issue by zzxap** [meetecho/janus-gateway#3450]
any i can find any create question button in the janus.discourse.group.how to use janus.discourse.group?
room-*: {
	description = "Demo Room"
	# is_private = true
	secret = "adminpwd"
	# pin = "roompwd"
	# history = 10
	post = "https://www.fastchatchat.com:8072/receiveMessage"
}

is it possible set any room's secret?

**Comment by lminiero** [comment]
You need to sign up to make questions on the group.
