### ISSUE TITLE
[1.x] Streaming plugin can leak RTP port

### ISSUE THREAD

**Issue by woutd** [meetecho/janus-gateway#3464]
**What version of Janus is this happening on?**
1.2.4

**Have you tested a more recent version of Janus too?**
No

**Was this working before?**
Probably not

**Is there a gdb or libasan trace of the issue?**
No

**Additional context**
When the first media port for a create request is free but the second port is in use Janus returns an error and does not create the streaming mountpoint. But it keeps listening on the first port. It is now unable to free this port.

To reproduce:

Create first mountpoint and listen to 24210 and 24211:
```
{'janus': 'message', 'body': {'request': 'create', 'type': 'rtp', 'id': '12345', 'is_private': True, 'media': [{'mid': 'video', 'type': 'video', 'iface': '127.0.0.1', 'port': 24210, 'pt': 96, 'codec': 'h264', 'fmtp': 'profile-level-id=42e01f;packetization-mode=1'}, {'mid': 'audio', 'type': 'audio', 'iface': '127.0.0.1', 'port': 24211, 'pt': 111, 'codec': 'opus'}], 'secret': 'XXX', 'pin': 'foobar', 'permanent': True, 'admin_key': 'YYY'}, 'transaction': 'foobar'}
```

Janus returns:
```
{'janus': 'success', 'session_id': 8590268524389867, 'transaction': 'foobar', 'sender': 3926924562162867, 'plugindata': {'plugin': 'janus.plugin.streaming', 'data': {'streaming': 'created', 'created': 'mp-12345', 'permanent': True, 'stream': {'id': '12345', 'type': 'live', 'description': 'mp-12345', 'is_private': True, 'host': '127.0.0.1', 'ports': [{'type': 'video', 'mid': 'video', 'port': 24210}, {'type': 'audio', 'mid': 'audio', 'port': 24211}]}}}}
```

Janus is listening to 24210 and 24211:
```
udp        0      0 127.0.0.1:24210        0.0.0.0:*                           3541152/janus       
udp        0      0 127.0.0.1:24211        0.0.0.0:*                           3541152/janus 
```

Try to create second mountpoint to listen on 24212 and 24210:
```
{'janus': 'message', 'body': {'request': 'create', 'type': 'rtp', 'id': '12346', 'is_private': True, 'media': [{'mid': 'video', 'type': 'video', 'iface': '127.0.0.1', 'port': 24212, 'pt': 96, 'codec': 'h264', 'fmtp': 'profile-level-id=42e01f;packetization-mode=1'}, {'mid': 'audio', 'type': 'audio', 'iface': '127.0.0.1', 'port': 24210, 'pt': 111, 'codec': 'opus'}], 'secret': 'XXX', 'pin': 'foobar', 'permanent': True, 'admin_key': 'YYY'}, 'transaction': 'foobar'}
```

Janus returns error because 24210 is in use and does not create the mountpoint:
```
{'janus': 'success', 'session_id': 6373290042750009, 'transaction': 'foobar', 'sender': 7906082748689840, 'plugindata': {'plugin': 'janus.plugin.streaming', 'data': {'streaming': 'event', 'error_code': 456, 'error': "Can't add 'rtp' stream, error creating data source stream"}}}
```

But is still listening on 24212:
```
udp        0      0 127.0.0.1:24210        0.0.0.0:*                           3541152/janus       
udp        0      0 127.0.0.1:24211        0.0.0.0:*                           3541152/janus 
udp        0      0 127.0.0.1:24212        0.0.0.0:*                           3541152/janus       
```

This only happens if the first port is free but the second is not.

**Comment by atoppi** [comment]
please test #3465

**Comment by woutd** [comment]
I can confirm #3465 fixes the above issue.

**Comment by lminiero** [comment]
@woutd thanks for the feedback! We'll add some more cleanup in a few other places where I can see a potential leak happening, and then we'll merge.

**Comment by woutd** [comment]
Alright, thanks @lminiero and @atoppi!

**Comment by lminiero** [comment]
@woutd I just pushed some more cleanups, especially on startup. Could you let me know if it still works as expected for you?

**Comment by woutd** [comment]
@lminiero I tested with the additional commit, it is still working as excepted.

**Comment by lminiero** [comment]
Excellent, thanks! I'll do a few more tests myself and then I'll merge, then.

**Comment by lminiero** [comment]
Closing since we merged the PR.
