### ISSUE TITLE
[1.x] Error gathering candidates...

### ISSUE THREAD

**Issue by mrhb6006** [meetecho/janus-gateway#3477]
I developed a software using Janus
In this software, a sound room is provided to users by using the audio bridge plugin

Sometimes when the number of members in the room increases (for example, 500 people including listeners and 2 speakers)
The membership in the room encounters an error and the following error is seen in the logs

[ERR] [ice.c:janus_ice_setup_local:3811] [3931553910270455] Error gathering candidates...
[ERR] [janus.c:janus_process_incoming_request:1542] Error setting ICE locally

And after a long time it will be fixed by itself (janus)

But sometimes rooms with 10000 members are formed without problems and without interruption, and the above error occurs only sometimes.

The stun server settings are completely correct
The server resources are quite sufficient (250 GB RAM and 80 CPU cores).

![ScreenShot_2024-11-09_08-12-05](https://github.com/user-attachments/assets/e46dde2d-b625-4154-b9bd-d54e94a96b78)

**Comment by lminiero** [comment]
That means you exhausted the range of ports you configured (probably too small for the number of concurrent PeerConnections). Not an issue, so please refer to the [group](https://janus.discourse.group/) for questions like this.
