### ISSUE TITLE
[1.x] "Missing mandatory element (feed)"

### ISSUE THREAD

**Issue by Moyout** [meetecho/janus-gateway#3489]
**What version of Janus is this happening on?**
Put the version and the commit identifier (available in `version.c` or from an `info` request) here

**Have you tested a more recent version of Janus too?**
Yes/no. If yes, which one. If not, why.

**Was this working before?**
If you have information on a version/commit where the issue wasn't there (e.g., the result of a `git bisect`), please provide it here.

**Is there a gdb or libasan trace of the issue?**
If you have a trace related to the issue (e.g., after a segfault), provide it as a gist/pastebin/other link here, or as a [collapsible section](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). Do **NOT** paste logs inline. For more information on the kind of traces we may find useful, please refer to the [documentation](https://janus.conf.meetecho.com/docs/debug).

**Additional context**

version : v1.3.1
When I use 'janus':' join ', I provide room, seedId, and handleId, but the returned data says' feed' is missing, and I don't know where this field was obtained from.
What is' feed '？
I couldn't find the keyword 'feed' during the process of 'create' ->'attach' ->join down room ->'publish'. What exactly does this mean? “session_id”？ “sender”？ Your document is poorly written and difficult to understand.
Does anyone know?

**Comment by lminiero** [comment]
Please ask questions ike this on the [group](https://janus.discourse.group/), and refer to the [documentation](https://janus.conf.meetecho.com/docs/videoroom) for the proper way to use the APIs.
