### ISSUE TITLE
[1.x] About janus.js websocket pattern send keepalive message

### ISSUE THREAD

**Issue by DividingLine** [meetecho/janus-gateway#3490]
Hello, esteemed Creator! Regarding the use of the 'janus.plugin.sip' plugin in janus.js, when the browser's memory allocation is insufficient or the browser is running in the background, the current page may freeze, causing the keepalive messages to gradually slow down and eventually stop sending. However, the SIP status remains registered.

I would like to ask if it is appropriate to use document.addEventListener('visibilitychange') to monitor visibility changes and proactively send a keepalive message, or if you have any better solutions.

**Comment by DividingLine** [comment]
<img width="1465" alt="WechatIMG386" src="https://github.com/user-attachments/assets/9367cf57-2441-4145-b339-898e6ff15908" />
In this way

**Comment by DividingLine** [comment]
I found the issue: it's because I have two media servers. Media server A notifies me of an incoming call, but when I call "answer," the request is sent to media server B. I don't know why the receiving and sending media servers are different. I'm using WebSocket, and it should only connect to one media server, right? This is really troubling me. Could you please share any ideas or suggestions to help me with this?

**Comment by lminiero** [comment]
Please discuss this on our [group](https://janus.discourse.group/), as this doesn't sound like a code issue (which is the only thing we use github for).
