### ISSUE TITLE
[1.x] Discarding too old outgoing packet

### ISSUE THREAD

**Issue by stone-tong** [meetecho/janus-gateway#3496]
Dear developer,

Recently encounter the issues, "Discarding too old outgoing packet", the following is the core version library I using:

Janus gateway version: 1.1.1
libnice version: 0.1.21

The stream's resolution is 4K@60fps AVC, and the maxium bitrate is 160Mbps.

Can you give me some directions for this issues?
Thanks.

**Comment by stone-tong** [comment]
> That means the server is struggling to keep up with the pace of the inbound packets. Tune event_loops in janus.jcfg and monitor hardware resources usage. Closing since this is not a code issue and should be discussed on the group.
Thanks  for your reply :-)
![image](https://github.com/user-attachments/assets/a0453b05-6e93-4b22-941a-18e41ae54284)
you meant this operation in janus.jcfg?

**Comment by atoppi** [comment]
Yes.

**Comment by stone-tong** [comment]
Another questions,

Why the hloop thread has heavy load on CPU, how to tune this?
![image](https://github.com/user-attachments/assets/f34fb7ce-2895-4b70-916a-0ed20404bd57)
Thanks.
