### ISSUE TITLE
SIP plugin: support of separate auth username?

### ISSUE THREAD

**Issue by tuijldert** [meetecho/janus-gateway#352]
I noticed that `janus_sip.c` uses the "username" for both sip identity as well as authorization username.

I'd like to be able to supply a separate name for that.

Is there already a pull request for that?

If not, can we agree on a `json` interface definition for it?

Thanks in advance,
Tom.

**Comment by lminiero** [comment]
There's no such thing as of yet. We'll look how hard it is to do this with the Sofia stack. If you happen to work on that in the meanwhile and prepare a PR that would be more than welcome, of course!

**Comment by tuijldert** [comment]
Should be no problem for the stack as it is the plugin that feeds it with a username on authentication (which can differ from the account name).
What needs to be done is to extend `janus_sip_account` with a `authusername` field (or whatever) and fill it with a -new to be defined- json field (`authuser`?).

When that field is not present in the register request, the authentication just reverts to sip username.

I can have a stab at a PR, just 1 more question: what exactly is the definition of the `identity` and `username` fields of `janus_sip_account` ?

**Comment by lminiero** [comment]
This is where we send the REGISTER:
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1180

```session->account.username``` is the username part of the SIP URI, ```username_text``` the whole SIP URI. I guess it will be a matter of figuring out which Sofia SIP tag needs to be added to (or modified in, if already there) ```nua_register``` to do what you're looking for.

**Comment by tuijldert** [comment]
Nope.
It'll be in the 401 response handling of the register (sofia_callback, `case: nua_r_register`) where the `account.username` is used that needs to use an `account.authuser` for the subsequent `nua_authenticate()` call.

I'll make a PR, so you can review it.
