### ISSUE TITLE
Audioconf, mute individual people.

### ISSUE THREAD

**Issue by mattvv** [meetecho/janus-gateway#355]
Hey guys, More of a conceptual question here.
I've been using audio conference and since the buffer was put in it's been working fabulously.
One thing i'm wondering is if I can mute certain people to others. For example.

Room has 3 users. ABC.
User A wants to mute User B but only to him.
User C should still be able to hear users A and B, but User A should only hear User C.

Is there anything in place for this at the moment - is this something that is possible to be implemented or is the stream mixed together on the server side for all users!

Thanks,

Matt

**Comment by lminiero** [comment]
@mattvv sorry for the late response, missed this issue apparently...

You cannot make selective muting in the audiobridge plugin, as the mix that is prepared is what everybody gets: the only thing the plugin does for each user is removing their own contribution (as of course that needs to be excluded from the mix). To do something like you suggest (coaching scenario?) I think you'd have to either rely on a couple of rooms for the purpose (attaching A, B and C to both but in different ways, that is in a way that implements what you need) or use the videoroom plugin instead for audio only purposes (e.g., something like [this](https://tools.ietf.org/html/rfc7058#section-6.3.3)).

**Comment by mattvv** [comment]
Thank you for the very detailed reply @lminiero . The videoroom plugin looks like it has the grunt for this. Although this is not on my pipeline for just now, great to know the approach needed.
Thank you
