### ISSUE TITLE
rec_dir being ignored in configure message

### ISSUE THREAD

**Issue by MagicIndustries** [meetecho/janus-gateway#357]
I'm using the videoroom plugin and trying to send the following command:

var configure = { 'request': 'configure', 'room': _config.room, 'record': true, rec_dir: '/usr/local/share/janus/recordings' };
_data.videoRoomPluginHandle.send({'message': configure});

The command goes through and janus does record, but it ignores the directory when passed and just dumps the files out in whatever directory janus was started from.

No special configuration, tried it on several machines with the same result.

**Comment by lminiero** [comment]
Are you passing a filename when configuring a publisher? If so, that currently takes precedence over the ```rec_dir```, meaning that if you pass a filename that's handled as a path, and as such is used for the recording accordingly. The ```rec_dir``` only kicks in when you don't pass any name and let the plugin pick one for you.

I guess this may be a bit confusing, and that we should probably revisit that.

**Comment by lminiero** [comment]
This commit should fix that, feel free to reopen if that's not the case.

**Comment by MagicIndustries** [comment]
Lovely, thanks for that. I figured out that the create did it so I switched to setting it there.




Toby Tremayne

Founder & Chief Troublemaker
MAGIC INDUSTRIES

INSPIRE ~ DISRUPT ~ ENABLE

Mobile:       0416048090
Email:         toby@magicindustries.net
Web: http://www.magicindustries.net
LinkedIn: http://au.linkedin.com/in/tobytremayne
Skype:        lyricist1
Twitter:       @magicindustries

"Nihil Verum, Omnia Licita"

**Comment by lminiero** [comment]
Ah, I actually thought you already were talking about a ```create``` rec_dir being ignored when doing a ```configure```: ```configure``` has no such thing as a ```rec_dir```, you can only provide a filename there.

**Comment by MagicIndustries** [comment]
I think I was trying it from something I saw in the forums. Never mind, all working now!


Toby Tremayne

Founder & Chief Troublemaker
MAGIC INDUSTRIES

INSPIRE ~ DISRUPT ~ ENABLE

Mobile:       0416048090
Email:         toby@magicindustries.net
Web: http://www.magicindustries.net
LinkedIn: http://au.linkedin.com/in/tobytremayne
Skype:        lyricist1
Twitter:       @magicindustries

"Nihil Verum, Omnia Licita"
