### ISSUE TITLE
Segmentation fault with more of 3 clients

### ISSUE THREAD

**Issue by jelitox** [meetecho/janus-gateway#358]
i follow the instructions to install janus and everything was fine but, when i start to connect in demo clients an devices, the server crash with a Segmentation fault error. i check every dependency that is in the readme of the repo. 

here is the gdb and bt log.. 
http://pastebin.com/cC0Cnbqa

**Comment by lminiero** [comment]
What distro is this on? That sounds like an issue in your setup, e.g., something loke [this](https://access.redhat.com/solutions/435733): definitely not an issue in Janus itself.

**Comment by jelitox** [comment]
ok, i'm using debian jessie, i will look the setup, the link require a subscription

**Comment by lminiero** [comment]
The link was just a google search to indicate other people had similar issues. It surely has nothing to do with Janus, as it seems a problem with named pthreads as used by libmicrohttpd.

**Comment by jelitox** [comment]
i'm testing on another scenario to see what is really affecting

**Comment by lminiero** [comment]
Any update on this?

**Comment by lminiero** [comment]
Closing for lack of feedback and because we can't reproduce it, feel free to repoen when there's more info.
