### ISSUE TITLE
libnice warning/error when using --force-rtcp-mux

### ISSUE THREAD

**Issue by ploxiln** [meetecho/janus-gateway#370]
I see the following error once for each webrtc connection, when using --force-rtcp-mux

```
(process:1): libnice-WARNING **: Could not find component 2 in stream 1
[ERR] [janus.c:janus_process_incoming_request:1532] [2337688670] Error forcing dummy candidate on RTCP component of stream 1
```

The webrtc connections still generally work. I just thought it was an interesting warning which I suspect #362 caused.

**Comment by lminiero** [comment]
Yes, you're probably right, thanks for noticing this: I forgot to add that check, I'll fix this shortly.

**Comment by lminiero** [comment]
That should do it, let me know if that's not the case.
