### ISSUE TITLE
the ability to put a call on hold or mute

### ISSUE THREAD

**Issue by bhakimi** [meetecho/janus-gateway#374]
currently i dont see a way to place the call on hold or mute using the web sip test page, maybe its missing or not implemented yet. sorry if this is the wrong place to submit this. please let me know where i should submit future requests if this is the wrong place to do so

**Comment by lminiero** [comment]
Github is for issues, not for questions: the meetecho-janus Google group is the place to go.

That said, on-hold is not  supported yet. You can achieve muting by muting the local MediaStream in Javascript.

**Comment by bhakimi** [comment]
sorry about that, will submit a ticket in the group.
