### ISSUE TITLE
How to create connection when Janus server behind NAT 

### ISSUE THREAD

**Issue by talbenbasat** [meetecho/janus-gateway#376]
Hi,

I have a Janus server located behind a NAT in my pc.
I trying to access the Janus server through a web client outside of my private LAN, unsuccessfully.

I don't wish to port forward the Janus server port, and I was trying to use the public ice servers.

This is my configuration for the Janus web client API.
```

janus = new Janus(
        {
            server: <my public ip>:8088/janus,
            iceServers : [{url:'stun:stun.voip.eutelia.it'}],
            success: function() {
                console.log('success');
            },
            error: function(error) {
                console.log(error);
            },
            destroyed: function() {
              console.log('destroyed');
            }
        }
```

And my configuration for the janus server is
```
[nat]
stun_server = stun.voip.eutelia.it
stun_port = 3478
nice_debug = true
```

by looking at the code it doesn't look like the ice servers configuration kicks in,
and the web client tries to access my public ip.

can you please help me out

**Comment by saghul** [comment]
That's not what ICE is used for. It's used for the establishment of media sessions.

If you want to access the Janus API from behind NAT you need to forward a port, there is no way around that, I'm afraid.

**Comment by lminiero** [comment]
That's right, for all static signalling stuff (web server, websocket server, etc.) port forwarding is required. Media negotiation can rely on STUN/TURN instead.

Closing as not an issue, please refer to the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) Google group instead for questions like this, as explained in [CONTRIBUTING.md](https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md).

**Comment by talbenbasat** [comment]
OK
Thanks
