### ISSUE TITLE
Floating Point Exception when Stopping Janus

### ISSUE THREAD

**Issue by MichaelB76** [meetecho/janus-gateway#378]
Hi, I've had several occurrences of a crash on g_hash_table_lokkup() called from janus_session_notify_event(0 in janus.c. So far this has only happened when stopping Janus but I don't know whether it could occur at other times. Here's a paste of the core dump:

http://pastebin.com/CSGhrXzW

**Comment by lminiero** [comment]
That might be a race condition due to the fact that, when shutting Janus down, the sessions hashtable is in the process of being destroyed. That said, there probably is something that still allows ```janus_session_notify_event``` to kick in even when the session has stopped normally, as I did notice a few leaks there (an event sent on a dead session that would not be freed). I'll investigate this more when I have some time.

**Comment by MichaelB76** [comment]
Thanks. I'm getting this quite regularly now, since we merged in the latest code a few weeks ago, so it's possible a recent change is causing this, although with timing issues you can never be sure.

**Comment by lminiero** [comment]
@MichaelB76 can you check if this last commit fixes it? It adds a more conservative check on sessions before notifying events, and may help with what you were experiencing: for one, I don't seem to be getting those ```janus_session_notify_event``` related leaks in my logs anymore, so unnotified events should be removed correctly here.

**Comment by MichaelB76** [comment]
@lminiero - OK thanks, I'm busy with other things at the moment but should be able to test this next week.

**Comment by MichaelB76** [comment]
Tested this again today with the latest Janus code and I got the crash again on shutdown after a few attempts.

**Comment by lminiero** [comment]
I guess that's happening if you shutdown while there are still users on the platform, right? Anyway, I'm working on a completely new approach to memory management based on reference counters, which will eventually land in #403. It will take some time, though, as it's quite a heavy refactoring.

**Comment by MichaelB76** [comment]
Yes, I had a couple clients connected at the time. However, I think I've seen it without clients connected as well, although the watchdog might not have cleaned them up yet.

I agree that some form of reference counting is a better approach in the long run, I've seen the discussion on the outstanding pull request. Good luck with the refactor, sounds like a tricky one.

**Comment by lminiero** [comment]
Closing as a lot has changed since this issue was last discussed. Feel free to reopen if still an issue.
