### ISSUE TITLE
Janus Terminates with SIGTRAP When Connecting Multiple Clients

### ISSUE THREAD

**Issue by MichaelB76** [meetecho/janus-gateway#379]
Bit of a strange one this, we've had Janus crash with a SIGTRAP (trace/breakpoint trap) when connecting multiple clients at the same time. Here's a paste of the core dump:

http://pastebin.com/7cEyJfqx

...and here's the relevant section of the logfile:

http://pastebin.com/TSpWZY81

Something to note is that there are a large number of error messages like this:

[Mon Nov  9 15:29:31 2015] [31m[ERR][0m [../plugins/sb_softclient.c:sb_softclient_allocate_local_ports:Bind failed for audio RTCP (port 13337), trying a different one...

Until finally we get this error from GLIB:

(process:1807): GLib-ERROR **: Creating pipes for GWakeup: Too many open files

It sounds like Janus may be stuck in a loop leaking file descriptors. The experimental plugin we are using is very heavily based on the sip plugin, I'm pretty confident the session initiation code hasn't been touched.

Any help would be appreciated, please let me know if there is any other info you'd like. So far we've only seen this problem once but we'll be performing similar tests. We're also trying to stress test Janus, so far we've had 35 clients connected and the cpu and memory usage are running at a few percent on our server.

**Comment by lminiero** [comment]
That's a well known issue, described in our FAQs online. Check point 20:
https://janus.conf.meetecho.com/docs/FAQ.html
Nevermind it referring to the VideoRoom plugin, it's actually the same thing (it's just easier for the issue to happen when using VideoRoom due to the way it handles subscriptions).

**Comment by lminiero** [comment]
When I mention issue, I don't mean issue in Janus, of course: it's a known problem that can happen with a known solution. It's OS related, not Janus related.

**Comment by MichaelB76** [comment]
Thanks, will give that a try. If this limit is increased would you expect Janus to bind to the RTCP port eventually then? I was surprised at the number of errors.

**Comment by simongymer-speakerbus** [comment]
It could handle the error situation of being unable to open another "file" properly though so that it doesn't crash?

I'm wondering if we keep hitting this issue because the handles are not being cleaned up properly on disconnect as it would explain a few things? Sorry I've not looked at the disconnection code to know how the handles are cleaned up.

**Comment by lminiero** [comment]
Limits have to be increased, there's no other workaround.

**Comment by MichaelB76** [comment]
@Iminiero - Just a heads up, from our testing there appears to be a handle leak in Janus. 12 new handles are allocated when a client connects but only 10 are released when it disconnects. We'll investigate some more to eliminate our plugin as a cause and see if we can pin it down.

We will have to increase ulimit as the default of 1024 is inadequate for the number of clients we want to connect, so that's useful thanks.

**Comment by artmatsak** [comment]
@lminiero We're running into the same issue with the "GLib-ERROR **: Creating pipes for GWakeup: Too many open files" crash. Here are our limits:

```
$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1908
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1908
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Could the 65536 limit for open files still be not enough?

**Comment by atoppi** [comment]
If 65536 is not enough, very likely there's a leak somewhere.
Investigate the nature of open files with tools like `lsof` and check for the Janus running threads too with `pstree`.

**Comment by artmatsak** [comment]
Thank you. Here is a sample of the `lsof` output for the Janus process:

```
janus   26840 guser  612u  0000                0,9        0      5576 anon_inode
janus   26840 guser  613u  0000                0,9        0      5576 anon_inode
janus   26840 guser  614u  0000                0,9        0      5576 anon_inode
janus   26840 guser  615u  IPv4          144027491      0t0       UDP sfu06.XXX:39198 
janus   26840 guser  616u  IPv4          144027492      0t0       UDP sfu06.XXX:57889 
janus   26840 guser  633u  0000                0,9        0      5576 anon_inode
janus   26840 guser  645u  0000                0,9        0      5576 anon_inode
janus   26840 guser  646u  0000                0,9        0      5576 anon_inode
janus   26840 guser  647u  IPv4          143987352      0t0       UDP sfu06.XXX:42289 
janus   26840 guser  648u  IPv4          143987353      0t0       UDP sfu06.XXX:40078 
janus   26840 guser  649u  0000                0,9        0      5576 anon_inode
janus   26840 guser  650u  0000                0,9        0      5576 anon_inode
janus   26840 guser  651u  IPv4          143987354      0t0       UDP sfu06.XXX:58946
```

And here is the `pstree` output:

```
$ pstree 26840
janus-+-{echotest handle}
      |-{echotest watchd}
      |-{handles watchdo}
      |-{http watchdog}
      |-{iceloop 1383343}
      |-{iceloop 1435968}
      |-{iceloop 1490751}
      |-{iceloop 1578756}
      |-{iceloop 1759189}
      |-{iceloop 1925253}
      |-{iceloop 2055785}
      |-{iceloop 2094578}
      |-{iceloop 2516901}
      |-{iceloop 2555632}
      |-{iceloop 2718806}
      |-{iceloop 2722125}
      |-{iceloop 2916436}
      |-{iceloop 2983231}
      |-{iceloop 3172994}
      |-{iceloop 3319006}
      |-{iceloop 3928873}
      |-{iceloop 4236443}
      |-{iceloop 4286691}
      |-{iceloop 4353903}
      |-{iceloop 4494090}
      |-{iceloop 4551372}
      |-{iceloop 4678432}
      |-{iceloop 4947540}
      |-{iceloop 5117808}
      |-{iceloop 5268122}
      |-{iceloop 5270806}
      |-{iceloop 5347146}
      |-{iceloop 5580348}
      |-{iceloop 6053922}
      |-{iceloop 6320602}
      |-{iceloop 6402486}
      |-{iceloop 6445689}
      |-{iceloop 6566627}
      |-{iceloop 6933792}
      |-{iceloop 6959712}
      |-{iceloop 7026024}
      |-{iceloop 7031038}
      |-{iceloop 7041272}
      |-{iceloop 7206010}
      |-{iceloop 7398968}
      |-{iceloop 7491448}
      |-{iceloop 7553873}
      |-{iceloop 7555982}
      |-{iceloop 7667381}
      |-{iceloop 7681624}
      |-{iceloop 7722558}
      |-{iceloop 7759172}
      |-{iceloop 7785223}
      |-{iceloop 7835652}
      |-{iceloop 7926051}
      |-{iceloop 7993191}
      |-{iceloop 8310541}
      |-{iceloop 8380286}
      |-{iceloop 8519407}
      |-{iceloop 8556084}
      |-{iceloop 8647857}
      |-{iceloop 8784338}
      |-{iceloop 8879255}
      |-{iceloop 8948431}
      |-{icesend 1435968}
      |-{icesend 1925253}
      |-{icesend 2516901}
      |-{icesend 2722125}
      |-{icesend 2916436}
      |-{icesend 2983231}
      |-{icesend 4286691}
      |-{icesend 5270806}
      |-{icesend 7031038}
      |-{icesend 7206010}
      |-{icesend 7398968}
      |-{icesend 7491448}
      |-{icesend 7553873}
      |-{icesend 7555982}
      |-{icesend 7667381}
      |-{icesend 7785223}
      |-{icesend 8556084}
      |-{libmicrohttpd}
      |-{log}
      |-{mp 1}
      |-{mp 2}
      |-{pool}
      |-{recordplay hand}
      |-{recordplay watc}
      |-{sessions watchd}
      |-{streaming handl}
      |-{streaming watch}
      |-{textroom handle}
      |-{textroom watchd}
      |-{videocall handl}
      |-{videocall watch}
      |-{videoroom handl}
      |-{videoroom watch}
      `-{ws thread}
```

**Comment by artmatsak** [comment]
OK, so it looks like `iceloop` is to blame. `26840` is Janus's PID:

```
guser@sfu06:~$ lsof | grep 26840 | wc -l
18786
guser@sfu06:~$ lsof | grep iceloop | wc -l
13044
```

Here's a sample of `lsof | grep iceloop`: https://pastebin.com/AJBjnBpM. Any ideas please?

**Comment by atoppi** [comment]
Makes sense. The `iceloop` is dispatching the glib events by using system pipes.
A stale `iceloop` means that a peer connection has not been correctly closed.

**Comment by artmatsak** [comment]
Thank you. Is this something we should fix in our own code then? What should we pay attention to?

**Comment by lminiero** [comment]
Make sure you're using master, as it may be something we fixed long ago. If still an issue, please open a new one: this one has been closed for a while already, and I'd rather not mix stuff here.

**Comment by artmatsak** [comment]
All right, will do, thanks.
