### ISSUE TITLE
Janus uses hardcoded path for plugins config instead of one from the main config file

### ISSUE THREAD

**Issue by mspanc** [meetecho/janus-gateway#385]
I've found out that in janus 0.0.9 (compiled with --prefix=/usr) janus always tries to read plugin config from /usr/etc/janus/*.cfg instead of directory set in the main config file.

**Comment by lminiero** [comment]
By default, the Makefile instructs janus.c on which folder the configuration files have been installed in according to prefix and other options:
https://github.com/meetecho/janus-gateway/blob/master/Makefile.am#L116
https://github.com/meetecho/janus-gateway/blob/master/janus.c#L2980
You can probably change /usr/etc/janus/ to something like /etc/janus/ passing the proper directive to configure. You can also change this dynamically through the command line:

    -F, --configs-folder=path     Configuration files folder (default=./conf)

That said, the plugins_folder you see in janus.cfg is where the shared objects are installed, not the configuration files. Configuration files, whether from the core or plugins/transports, are all in the same place by default. If you're writing your own plugin, you can decide to read that from somewhere else, or even to use something different from INI files entirely (e.g., XML or JSON files): the fact the stock plugins read files named after their namespace from the default folder is just a convention.

**Comment by mspanc** [comment]
Ah ok, I hadn't figured out that there're separate directives for plugin configs and main config.
