### ISSUE TITLE
GLib-GObject-CRITICAL **: g_object_new_valist: object class 'NiceAgent' has no property named 'ice-udp'

### ISSUE THREAD

**Issue by LetsVape** [meetecho/janus-gateway#398]
I see the following Critical error/warning pop up in my log, it doesn't seem to affect the server's stability though

(process:14060): GLib-GObject-CRITICAL **: g_object_new_valist: object class 'NiceAgent' has no property named 'ice-udp'

Would that be because my libnice is at 0.1.4-1 at the moment?
(I just used aptitude as I didn't see a  version mentioned)
Do the changes in this commit [44a0816](https://github.com/meetecho/janus-gateway/commit/44a081696f1ca34cd7eefe81f8aa9d032ff2bbf8) require the changes in libnice 0.1.8
http://upstream.rosalinux.ru/changelogs/libnice/0.1.8/changelog.html?

Just wanted to make you aware and raise this, I will try updating libnice, I just don't want to reboot the process yet to keep this OpenSSL uptime test going! :+1: 

Thanks!

**Comment by lminiero** [comment]
Good catch: this patch fixed the broken behaviour for libnice versions that do support ICE-TCP, which didn't affect older versions. I'll put the new GObject attributes within a define.

**Comment by lminiero** [comment]
Should be fixed in https://github.com/meetecho/janus-gateway/commit/de24ab3da0d65b8a3f297a19df0ba35dd4a17668 let me know if that's not the case.

**Comment by LetsVape** [comment]
Thanks for the quick response and fix as usual!
I'll try to test this asap on the dev server when I get home later

**Comment by lminiero** [comment]
Ok, closing in the meanwhile, feel free to reopen if it's still an issue.

**Comment by uasan** [comment]
The error appears

`(janus:17881): GLib-GObject-CRITICAL **: 16:18:07.166: g_object_new_is_valid_property: object class 'NiceAgent' has no property named 'consent-freshness'`

Janus v1.2.1
libnice 0.1.19
