### ISSUE TITLE
chrome deprecated functions

### ISSUE THREAD

**Issue by bhakimi** [meetecho/janus-gateway#401]
'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.
janus.js?v=f88bf27:1881 Stopping local stream tracks

https://groups.google.com/forum/#!topic/doubango/AItIvbSzc3Q
Chrome is going to deprecate three mediastream APIs in it next update in November.

There are three MediaStream deprecations in Chrome 45:

MediaStream.ended
MediaStream.label
MediaStream.stop()
In parallel are two additions:

MediaStream.active
MediaStreamTrack.stop()
Source : https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en

**Comment by lminiero** [comment]
Fixed many weeks ago: https://github.com/meetecho/janus-gateway/commit/389082b3a2380e5be8f51c6792f8eb84a8390a19#diff-151c1165a0606ba9f4d6e10c44f2b3e1

**Comment by lminiero** [comment]
Don't worry if you still see the warning, it's because we first try the old style stop in a try catch, and then the new one. We need both as we have to support older browsers.

**Comment by bhakimi** [comment]
I'm going crazy because I'm using the latest Janus.js file and chrome gave me that error

**Comment by lminiero** [comment]
See response above: it's normal if you still see it, as we do the old-style stop anyway, since pre-november browsers will expect it. It's in a try-catch so it won't break anything.

**Comment by lminiero** [comment]
Besides, it's a warning, not an error.

**Comment by bhakimi** [comment]
ahh thx =)

On Wed, Dec 2, 2015 at 2:36 PM, Lorenzo Miniero <notifications@github.com>
wrote:

> Besides, it's a warning, not an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meetecho/janus-gateway/issues/401#issuecomment-161455892>
> .
>

-- 


20950 Warner Center Lane, Building A | Woodland Hills | California | 91367
Phone: 888-456-5454 | *Fax:* 888-401-7809 
*Web:* www.safesoftsolutions.com
