### ISSUE TITLE
PID file includes mess when debug_level = 7 

### ISSUE THREAD

**Issue by idubinets** [meetecho/janus-gateway#406]
Hi guys,

we tried pid file feature today and when debug_level = 7, janus writes some debug traces to it. something like this:

    3911
    (process:3911): libnice-DEBUG: Agent 0x7fbb60009c10 : allocating stream id 1 (0x7fbb6000da70)
    (process:3911): libnice-DEBUG: Agent 0x7fbb60009c10: added relay server [64.71.3.142]:3478 of type 0
    (process:3911): libnice-DEBUG: Agent 0x7fbb60009c10 : In ICE-FULL mode, starting candidate gathering.
    (process:3911): libnice-DEBUG: Agent 0x7fbb60009c10 : libnice compiled without UPnP support
    (process:3911): libnice-DEBUG: Agent 0x7fbb60009c10: Trying to create host candidate on port 0
    (process:3911): libnice-DEBUG: Agent 0x7fbb60009c10: Could not set IPV6 socket ToS
    (process:3911): libnice-DEBUG: Agent 0x7fbb60009c10 : Adding new srv-rflx candidate discovery 0x7fbbb68e2010

Can you please fix that?

**Comment by lminiero** [comment]
As in, Janus is writing debug traces to the PID file?

**Comment by saghul** [comment]
can you try https://github.com/meetecho/janus-gateway/pull/407 ? libnice is probably just printing to stdout, but since we used to close those file descriptors, fd 1 is asigned to the pid file. The PR reopens stdin/out/err to /dev/null, in order to preserve those fds.

**Comment by lminiero** [comment]
Could not replicate it in any of the following scenarios:

1. debug 7 and PID fle specified (```janus -d 7 -p /tmp/janus.pid```);
2. debug 7, PID fle specified and log file (```janus -d 7 -p /tmp/janus.pid -L /tmp/janus.log```);
3. debug 7, PID fle specified, log file and no console output (```janus -d 7 -p /tmp/janus.pid -L /tmp/janus.log -N```).

All worked as expected. I thought that maybe the "no stdout" was causing that (maybe stdout/stderr redirection was to blame and it conflicted with the file descriptor used by the PID file) but it doesn't look like it.

**Comment by lminiero** [comment]
Check https://github.com/meetecho/janus-gateway/commit/365b8c95171537d656138fe21462e3af33d05e5a instead, it includes the fix @saghul made in #407.

**Comment by idubinets** [comment]
Hi guys,

sorry for delay. just verified. issue is fixed

Thanks!
