### ISSUE TITLE
File Descriptors Leaked in SIP Plugin

### ISSUE THREAD

**Issue by MichaelB76** [meetecho/janus-gateway#409]
Something I've noticed is that the count of file descriptors used by Janus climbs over time. Using lsof shows that two consecutive udp ports are leaked every time a SIP client disconnects. Checking with Wireshark I can see these are the RTP and RTCP ports used to receive audio from the SIP client. Eventually Janus runs out of file descriptors and crashes.

I have a fix for this that seems to work OK, I've simply added the following to janus_sip_relay_thread() after the loop exits but before the thread is stopped:

if (session->media.audio_rtp_fd) {
	close(session->media.audio_rtp_fd);
	session->media.audio_rtp_fd = 0;
}
if (session->media.audio_rtcp_fd) {
	close(session->media.audio_rtcp_fd);
	session->media.audio_rtcp_fd = 0;
}
if (session->media.video_rtp_fd) {
	close(session->media.video_rtp_fd);
	session->media.video_rtp_fd = 0;
}
if (session->media.video_rtcp_fd) {
	close(session->media.video_rtcp_fd);
	session->media.video_rtcp_fd = 0;
}

(The video stream appears to have the same problem so up to 4 FDs could be leaked per client.)

However, I'm not sure if this is the best place to clean this up or whether there are any thread safety issues I've missed. I notice sb_softclient_incoming_rtp() also uses these file descriptors and I'm not sure if this can be called after the SIP relay thread exits its loop, so a review of the fix would be appreciated.

I don't think the other plugins are affected by this.

**Comment by lminiero** [comment]
Are you sure you're using the latest version? I think we fixed this a couple of weeks ago.

**Comment by MichaelB76** [comment]
You're right thanks, I'd missed that.
