### ISSUE TITLE
run configure failed

### ISSUE THREAD

**Issue by langhuihui** [meetecho/janus-gateway#410]
checking for JANUS... configure: error: Package requirements (
                    glib-2.0 >= glib_version
                    nice
                    jansson
                    libssl >= ssl_version
                    libcrypto
                    sofia-sip-ua
                  ) were not met:

Requested 'glib-2.0 >= glib_version' but version of GLib is 2.47.3
Requested 'libssl >= ssl_version' but version of OpenSSL is 1.0.1e

-----------------------
I found 

glib_version=2.32
ssl_version=1.0.1

in the configure file

**Comment by lminiero** [comment]
Do you have the development versions of those libraries installed? Just the runtime won't help.

**Comment by langhuihui** [comment]
Name        : openssl-devel
Arch        : x86_64
Version     : 1.0.1e
Release     : 42.el6
Size        : 2.2 M
Repo        : installed
From repo   : base

-----------
I Compiled Glib from the source code.

**Comment by lminiero** [comment]
.el6? If this is CentOS, that's known to give issues with Janus, especially 6.5.

**Comment by langhuihui** [comment]
But why configure is not passed

**Comment by langhuihui** [comment]
is this code glib-2.0 >= glib_version missing '$'?
maybe the right code like this
 glib-2.0 >= $glib_version

**Comment by saghul** [comment]
Can you pastebin your configure.log?

**Comment by lminiero** [comment]
configure scripts are not created manually, they're created by the autogen script.
Try launching autogen.sh again. Also check what's the result of ```pkg-config --libs --cflags glib-2.0``` as pkg-config is used to find glib.

**Comment by langhuihui** [comment]
[config.txt](https://github.com/meetecho/janus-gateway/files/55115/config.txt)

**Comment by lminiero** [comment]
Please use pastebin.com or gist.github.com instead

**Comment by langhuihui** [comment]
`pkg-config --libs --cflags glib-2.0
-I/usr/local/include/glib-2.0 -I/usr/local/lib/glib-2.0/include  -L/usr/local/lib -lglib-2.0`

I make install the Glib to /usr/local
I set PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

**Comment by ploxiln** [comment]
The key part seems to be:
```
configure:12423: checking for pkg-config
configure:12441: found /usr/bin/pkg-config
configure:12453: result: /usr/bin/pkg-config
configure:12478: checking pkg-config is at least version 0.9.0
configure:12481: result: yes
configure:12492: checking for JANUS
configure:12506: $PKG_CONFIG --exists --print-errors "
                    glib-2.0 >= glib_version
                    nice
                    jansson
                    libssl >= ssl_version
                    libcrypto
                    sofia-sip-ua
                  "
Requested 'glib-2.0 >= glib_version' but version of GLib is 2.47.3
Requested 'libssl >= ssl_version' but version of OpenSSL is 1.0.1e
```

Maybe that version of pkg-config does not support that --exists syntax with some comparisons exactly? I might try running that manually, without the version comparisons, and see if the problem is that pkg-config is not finding the libs at all, or failing the version comparisons.

Just by the way, glib2 2.47.x is *unstable*, the latest *stable* release is 2.46.x (even minor releases are stable, odd minor releases are unstable development versions preparing for the next stable release)

**Comment by langhuihui** [comment]
Name        : pkgconfig
Arch        : x86_64
Epoch       : 1
Version     : 0.23
Release     : 9.1.el6
Size        : 137 k
Repo        : installed
From repo   : anaconda-CentOS-201311272149.x86_64
Summary     : A tool for determining compilation options
URL         : http://pkgconfig.freedesktop.org
License     : GPLv2+

**Comment by ploxiln** [comment]
looking closer at the configure script - the glib_version and ssl_version variables don't end up substituted correctly, it's probably a bug in configure.ac that was hidden because the version of pkg-config on fedora/debian/ubuntu consider the literal strings "glib_version" and "ssl_version" to precede the version numbers

**Comment by langhuihui** [comment]
`glib-2.0 >= $glib_version` works

**Comment by langhuihui** [comment]
checking for libwebsocket_get_internal_extensions in -lwebsockets_shared... no
checking for libwebsocket_get_internal_extensions in -lwebsockets... no
configure: error: libwebsockets not found. See README.md for installation instructions or use --disable-websockets

------

In fact I has make install libwebsockets successfully

**Comment by langhuihui** [comment]
I found 

configure:13711: checking for libwebsocket_get_internal_extensions in -lwebsockets_shared
configure:13746: gcc -o conftest -g -O2   conftest.c -lwebsockets_shared   >&5
/usr/bin/ld: cannot find -lwebsockets_shared
collect2: ld returned 1 exit status

in config log.

**Comment by ploxiln** [comment]
This is something different.

libwebsockets has a pkgconfig file, but it's not used by janus' configure script. For the janus configure script test to find it, if you installed libwebsockets to `/usr/local`, you need to add these arguments to `./configure`:
```
LDFLAGS="-L/usr/local/lib -Wl,-rpath=/usr/local/lib" CFLAGS="-I/usr/local/include"`
```

**Comment by langhuihui** [comment]
I installed libwebsockets to /usr
` ./configure --prefix /opt/janus LDFLAGS="-L/usr/lib -Wl,-rpath=/usr/lib" CFLAGS="-I/usr/include"`

---
It still not works
There are `libwebsockets.a` `libwebsockets.so` `libwebsockets.so.6` in /usr/lib

**Comment by ploxiln** [comment]
hmm yeah the LDFLAGS etc aren't helpful if the libs really are in the default locations, nvm about that.

So, uh, I also don't have `libwebsockets_shared` either, I just have `libwebsockets` (.so...). It looks like the configure script is trying to detect which of `-lwebsockets` and `-lwebsockets_shared` has `libwebsocket_get_internal_extensions` and on your system it's not working, maybe due to a difference in autoconf or something like that.

So, `cannot find -lwebsockets_shared` is OK, `checking for libwebsocket_get_internal_extensions in -lwebsockets_shared... no` is OK, but the one without `_shared` should be found. Is that also in the config.log?

**Comment by langhuihui** [comment]
I updated the config.log.
https://gist.github.com/langhuihui/cf1fc9857d183659b18c

**Comment by arjenveenhuizen** [comment]
I happen to face the exact same issue on ubuntu 14.04 x64 using git master and compiling libwesockets from source per the instructions.

**Comment by ploxiln** [comment]
```
configure:13791: checking for libwebsocket_get_internal_extensions in -lwebsockets
configure:13826: gcc -o conftest -I/usr/include  -L/usr/lib -Wl,-rpath=/usr/lib conftest.c -lwebsockets   >&5
/tmp/cc0OGkEG.o: In function `main':
conftest.c:(.text+0xa): undefined reference to `libwebsocket_get_internal_extensions'
collect2: ld returned 1 exit status
```

This config.log says that it found -lwebsockets but it didn't have the function it was checking for. It must not have found the correct libwebsockets.so

btw I build libwebsockets like this, note the origin and the options:

```
PREFIX=/usr/local
SU_CMD=sudo
LIBWEBSOCKETS_REV="1.5-chrome47-firefox41"
LIBWEBSOCKETS_TARBALL="libwebsockets-${LIBWEBSOCKETS_REV}.tar.gz"
wget --no-verbose \
    http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/snapshot/${LIBWEBSOCKETS_TARBALL}
tar -xf $LIBWEBSOCKETS_TARBALL
cd libwebsockets-$LIBWEBSOCKETS_REV
cmake -DCMAKE_INSTALL_PREFIX:PATH=$PREFIX -DLWS_WITHOUT_TESTAPPS:BOOL=ON
make
$SU_CMD make install
```

**Comment by arjenveenhuizen** [comment]
@ploxiln: your installation script works and allows janus to find libwebsocket and build just fine.

**Comment by langhuihui** [comment]
as arjenveenhuizen's said

**Comment by arjenveenhuizen** [comment]
Perhaps it would be a good idea to update the janus README.md to reflect ploxiln's install script?

**Comment by lminiero** [comment]
Not sure what you're asking me to add. We look for ```libwebsocket_get_internal_extensions``` in configure.ac when looking for libwebsockets for a reason, as it must be recent enough. How to find the library itself may depend on where it has been installed. The additional LDFLAGS and CFLAGS specified by @ploxiln can help if configure fails by itself.

**Comment by arjenveenhuizen** [comment]
What I mean is that when I compile libwebsockets using the instructions provided in the README, I experience the problem as reported in this topic. When I compile libwebsocket using ploxiln's script, it works. If multiple people experience the same problem, and the alternative script does not have any drawbacks, why not update the instructions in the readme?

**Comment by lminiero** [comment]
The only difference I see (apart from the usage of a specific revision) is that the ```-DCMAKE_C_FLAGS="-fpic"``` part is missing, which other people (me included) needed instead for pretty much the same reason. Have you tried building libwebsockets using the README instructions without that part to see if that works?

**Comment by ploxiln** [comment]
I wouldn't say that the current instructions in the README are wrong, it's not clear why they didn't work for some people ... it's just the usual issues of putting together a complex software stack on different linux distros and configurations, and not fully understanding all the build systems. (That's OK, they're rather complicated.)

Anyway, I'll post a link to an updated version of a more comprehensive build script I have to the google group, in a few hours, to make it easier to find.

**Comment by ploxiln** [comment]
Actually, @lminiero it looks like the latest master branch of libwebsockets has an api change, see http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/tree/changelog - my build instructions use v1.5-chrome47-firefox41 which is before the api change. So these failures make sense.

It may be enough to add the cmake option `-DLWS_WITH_OLD_API_WRAPPERS=1` to get the compatible api from the master branch version.

**Comment by lminiero** [comment]
Thanks for the heads up, I was not aware of this. I'll add the cmake option to the README.

**Comment by langhuihui** [comment]
make error
In file included from janus.h:33,
                 from dtls.c:15:

typedef‘janus_ice_trickle’ 

define twice

**Comment by ploxiln** [comment]
that sort of thing is different and deserves its own issue, and a bit more info on what configure and build options were used

**Comment by tvildo** [comment]
Fix for me in Centos 7 was :
1) compile and install libnice
2) export PKG_CONFIG_PATH=/usr/lib/pkgconfig
