### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by langhuihui** [meetecho/janus-gateway#414]
In file included from janus.h:33,
                 from dtls.c:15:
ice.h:413: 错误：typedef‘janus_ice_trickle’重定义
ice.h:152: 附注：‘janus_ice_trickle’的上一个声明在此
In file included from dtls.c:15:
janus.h:111: 错误：typedef‘janus_request’重定义
janus.h:42: 附注：‘janus_request’的上一个声明在此

---
config.log
[https://gist.github.com/langhuihui/cf1fc9857d183659b18c]

---
chinese words mean there are some redefine errors

**Comment by ploxiln** [comment]
It seems your unusual configuration has uncovered another bug which newer build tools don't seem to complain about. I opened a pull request with a potential fix.
