### ISSUE TITLE
[Videoroom] "SyntaxError: JSON.parse: expected ',' or '}' after property value in object" in FF

### ISSUE THREAD

**Issue by idubinets** [meetecho/janus-gateway#416]
Hi guys,

I continue playing with Janus and now I am testing video room. Today I faced issue which should be fixed for sure.

I noticed that firefox browser can't parse messages which come from janus. Especially big messages with SDP inside.

I added some log traces to the janus_websockets.c. This is result:
https://gist.github.com/idubinets/a666e02c1ca95825d3ff

notice: 
Sent 4796/4798 bytes

two bytes were not sent!

Thanks,
Ivan

**Comment by idubinets** [comment]
you use formatting for json messages what is not necessary I think. this is not human readable info, so you can significantly reduce size of the messages if you will turn it off.

of course this is not fix of the problem, I am not familiar with websockets library you used and don't know how *write* method works :-(

**Comment by lminiero** [comment]
Sorry, saw this last week when I couldn't reply and then forgot to answer... I'll check what's wrong, although it's really weird that you're geting so large messages, even when an SDP is involved. What's causing these sizes?

**Comment by idubinets** [comment]
I think it is normal behavior for ice protocol.
I am physically located in Ukraine, but our servers are in USA, so there are a lot of candidates to establish peer 2 peer connection. I normally have 25-30 ice candidates!

**Comment by lminiero** [comment]
But with trickle you shouldn't need all those candidates at all. Clients would trickle their candidates (so lighter SDP originated by browsers) while Janus won't trickle but will have very few candidates (only host and maybe srflx, if STUN is needed).

**Comment by idubinets** [comment]
I used default configuration for testing. what I changed is added turn config.

Anyway, you need improve websockets module, because in future somebody else can send big message and this will cause same problem.

libwebsockets documentation is horrible. but it sounds like you just need additional sending buffer for each connected client. so you will copy message to this buffer and then send it while one will not be completely transmitted. Then go to the another message and so on. I don't see in libwebsockets docs how to explain websockets library when we are stopped sending current message, so one will finalize current websockets frame correctly. maybe there is some flags...

**Comment by lminiero** [comment]
> Anyway, you need improve websockets module, because in future somebody else can send big message and this will cause same problem.

Yep, I agree, I'm just surprised by the increasing sizes due to candidates as Janus should only have a few of them on its side. Why did you add TURN to Janus by the way? If Janus is publicly reachable you don't need that: you'll probably only want to configure TURN on the JavaScript side for users.

I'll have a look at what's causing the messages being cut in libwesockets, and if there's any way to prevent that (although IIRC I think we already did that when handling the "writable" part).

**Comment by idubinets** [comment]
if we potentially will use janus in future, we will not be able to open wide range of ports required for p2p connection establishment. We can use only 80 and 443. same way, users potentially will have symmetrical nat,so turn is required.

Turn server should be configured for both sides, otherwise connection will not work. especially if secured access configured for turn. I am wrong?

**Comment by lminiero** [comment]
You only need TURN on the side that is limited. If the user is limited, but the server is not, you only need to configure TURN for the client in JavaScript, not the server. As far as the server is concerned, a TURN user is just a udp user as the TURN server does the relaying on the user's behalf.

You only need to configure TURN for Janus If you're planning on putting it on a server that has the same connectivity limitations (which doesn't make much sense though and is very inefficient).

**Comment by lminiero** [comment]
Let me know if the pull request above fixes it for you, and if it doesn't introduce any other regression in your usage of the platform.

**Comment by idubinets** [comment]
I added some comments to it

**Comment by idubinets** [comment]
about turn, you just discovered something new for me, I will read rfc.

I was thinking that both sides should know turn parameters. I will read RFC once again

**Comment by idubinets** [comment]
I verified, your patch works as need

can you please merge one to the master?
