### ISSUE TITLE
which browser can supply the H.264? 

### ISSUE THREAD

**Issue by father2002** [meetecho/janus-gateway#423]
Hi everybody here,
  Now I use the janus-gateway test H.264.  I get the stream from our ip camara, and send rtp to janus port, this step has succeed. But now I find, with firefox 43, the newest version can't play the stream.
How to configure the firefox ? my os is windows x64.

**Comment by saghul** [comment]
This is not a Janus question.

You can enable H264 in about:config, search for "h264".

**Comment by lminiero** [comment]
Not a Janus question and not an issue either. Please refer to the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) group instead.
