### ISSUE TITLE
HTTPS is very slow.

### ISSUE THREAD

**Issue by externuz** [meetecho/janus-gateway#428]
When we changed the protocol from HTTP to HTTPS Janus became very slow. HTTP protocol had no such problems.

**Comment by lminiero** [comment]
Maybe some certificate issue that is causing the handshake to take a long time. Anyway, using HTTPS directly in Janus is not recommended. as libmicrohttpd has some issues on some distros where it causes 100% cpu usage when HTTPS is involved. It's better to stick to HTTP, and put a frontend (apache httpd, lighttpdo or ngingx) as a proxy to handle HTTPS on its behalf. You can find some examples [here](https://janus.conf.meetecho.com/docs/deploy).
