### ISSUE TITLE
Compile janus-pp-rec.c

### ISSUE THREAD

**Issue by externuz** [meetecho/janus-gateway#431]
There is no information, about how to compile this utility - janus-pp-rec.c, only how to use it.
When I try to compile it manually by 
```
gcc -o janus-pp-rec janus-pp-rec.c `pkg-config --cflags --libs gtk+-2.0`
``` 
there is many problems in log:
/tmp/ccDC1G3j.o: In function `main':
janus-pp-rec.c:(.text+0x42): undefined reference to `janus_log_init'
janus-pp-rec.c:(.text+0x168): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x262): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x34f): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x4a8): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x5e4): undefined reference to `janus_vprintf'
/tmp/ccDC1G3j.o:janus-pp-rec.c:(.text+0x720): more undefined references to `janus_vprintf' follow
/tmp/ccDC1G3j.o: In function `main':
janus-pp-rec.c:(.text+0x1133): undefined reference to `json_loads'
janus-pp-rec.c:(.text+0x126e): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x134e): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x136c): undefined reference to `json_object_get'
janus-pp-rec.c:(.text+0x1479): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x1492): undefined reference to `json_string_value'
janus-pp-rec.c:(.text+0x15cb): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x15e9): undefined reference to `json_object_get'
janus-pp-rec.c:(.text+0x16f6): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x170f): undefined reference to `json_string_value'
janus-pp-rec.c:(.text+0x1826): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x1940): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x195e): undefined reference to `json_object_get'
janus-pp-rec.c:(.text+0x1a6b): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x1a84): undefined reference to `json_integer_value'
janus-pp-rec.c:(.text+0x1a9f): undefined reference to `json_object_get'
janus-pp-rec.c:(.text+0x1bac): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x1bc5): undefined reference to `json_integer_value'
janus-pp-rec.c:(.text+0x1cc1): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x1dab): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x1e95): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x1f7f): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x2098): undefined reference to `janus_vprintf'
/tmp/ccDC1G3j.o:janus-pp-rec.c:(.text+0x2243): more undefined references to `janus_vprintf' follow
/tmp/ccDC1G3j.o: In function `main':
janus-pp-rec.c:(.text+0x33bc): undefined reference to `janus_pp_opus_create'
janus-pp-rec.c:(.text+0x34d3): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x34f6): undefined reference to `janus_pp_webm_preprocess'
janus-pp-rec.c:(.text+0x360d): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x3623): undefined reference to `janus_pp_webm_create'
janus-pp-rec.c:(.text+0x373a): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x3785): undefined reference to `janus_pp_opus_process'
janus-pp-rec.c:(.text+0x389c): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x38bf): undefined reference to `janus_pp_webm_process'
janus-pp-rec.c:(.text+0x39d6): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x39e1): undefined reference to `janus_pp_webm_close'
janus-pp-rec.c:(.text+0x39e8): undefined reference to `janus_pp_opus_close'
janus-pp-rec.c:(.text+0x3b04): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x3c42): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x3d76): undefined reference to `janus_vprintf'
janus-pp-rec.c:(.text+0x3d7b): undefined reference to `janus_log_destroy'
collect2: error: ld returned 1 exit status

**Comment by lminiero** [comment]
No need for this, just pass --enable-postprocessing to configure. Do a
./configure --help for the exact syntax.
Il 25/dic/2015 12:26, "Vladislav Kolesnikov" <notifications@github.com> ha
scritto:

**Comment by externuz** [comment]
No. It does not works on my Debian 7. By the way, on ubuntu 15.10 janus-pp-rec was installed automatically without any problems.

There is configure log:

webmaster@janus:/opt/janus-gateway$ sudo ./configure --prefix=/opt/janus --disable-websockets --disable-data-channels --disable-rabbitmq --disable-docs --enable-postprocessing
configure: WARNING: unrecognized options: --enable-postprocessing
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking dependency style of gcc... (cached) gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for JANUS... yes
checking for nice_agent_set_port_range in -lnice... yes
checking for nice_address_equal_no_port in -lnice... no
configure: libnice version does not support TCP candidates
checking for dlopen in -ldl... yes
checking for srtp_init in -lsrtp... yes
checking for usrsctp_finish in -lusrsctp... no
checking for LIBCURL... no
configure: libcurl not found. The TURN REST API client will not be built.
checking for doxygen... no
checking for dot... no
checking for gengetopt... yes
checking for TRANSPORTS... yes
checking for MHD... yes
checking for libwebsocket_get_internal_extensions in -lwebsockets_shared... no
checking for libwebsocket_get_internal_extensions in -lwebsockets... no
checking for amqp_error_string2 in -lrabbitmq... no
checking for PLUGINS... yes
checking for OPUS... yes
checking for OGG... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating html/Makefile
config.status: creating docs/Makefile
config.status: executing depfiles commands
config.status: executing libtool commands
configure: WARNING: unrecognized options: --enable-postprocessing

DataChannels support:      no
BoringSSL (no OpenSSL):    no
Recordings post-processor: no
TURN REST API client:      no
Doxygen documentation:     no
Transports:
    REST (HTTP/HTTPS):     yes
    WebSockets:            no
    RabbitMQ:              no
Plugins:
    Echo Test:             yes
    Streaming:             yes
    Video Call:            yes
    SIP Gateway:           yes
    Audio Bridge:          yes
    Video Room:            yes
    Voice Mail:            yes
    Record&Play:           yes

If this configuration is ok for you, do a 'make' to start building Janus. A 'make install' will install Janus and its plugins to the specified prefix. Finally, a 'make configs' will install some sample configuration files too (something you'll only want to do the first time, though).

**Comment by externuz** [comment]
configure: WARNING: unrecognized options: --enable-postprocessing

**Comment by lminiero** [comment]
Please do not paste huge chunks of text in the comments, as stated repeatedly over both Google group and contributions guidelines. There are services like pastebin or gist for the purpose.

Besides, since I was way from my pc, I said:

> Do a
> ./configure --help for the exact syntax.

which gives

    --enable-post-processing
                          Enable building post-processing utility

**Comment by lminiero** [comment]
Closing as not an issue.
