### ISSUE TITLE
why webserver disabled

### ISSUE THREAD

**Issue by majorye** [meetecho/janus-gateway#433]
![image](https://cloud.githubusercontent.com/assets/36510/12071083/71c7330a-b0d3-11e5-9052-31850be0b657.png)

![image](https://cloud.githubusercontent.com/assets/36510/12071079/405f7f70-b0d3-11e5-9a5a-d7b5deb49268.png)

**Comment by lminiero** [comment]
Github is for issues, not questions. Please use the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) for those.
