### ISSUE TITLE
why libwebsockets not found

### ISSUE THREAD

**Issue by majorye** [meetecho/janus-gateway#434]
follow the [janus-gatway](https://github.com/meetecho/janus-gateway) readme,  when excute 

```
./configure --prefix=/opt/janus
```

see libwebsockets not found like below screenshot:
![image](https://cloud.githubusercontent.com/assets/36510/12071096/65632c1c-b0d4-11e5-9012-f91c4e5fbc71.png)

OS: Ubuntu 15.10  same as #14

**Comment by lminiero** [comment]
Github is for issues, not questions. Please use the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) for those.
