### ISSUE TITLE
Outgoing rabbitmq queue's name is overwritten/wiped

### ISSUE THREAD

**Issue by Eltiech** [meetecho/janus-gateway#435]
I have the transport config at its defaults(other than it being enabled). However, no matter what I set it to, janus seems to be sending outgoing messages to a queue with all the characters in its name nulled out.

Here's the output of rabbitmq's firehose tracer, viewed via [this python script](https://gist.github.com/khomenko/2562165)

    [x] 'publish.':u'spitfire@spitfire':[u'to-janus']:'{"janus":"create","transaction":"xasu9jgdxrxgk3xr"}'
    [x] 'deliver.to-janus':u'spitfire@spitfire':[u'to-janus']:'{"janus":"create","transaction":"xasu9jgdxrxgk3xr"}'
    [x] 'publish.':u'spitfire@spitfire':[u'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']:'{\n   "janus": "success",\n   "transaction": "xasu9jgdxrxgk3xr",\n   "data": {\n      "id": 4271151692\n   }\n}'
    [x] 'publish.':u'spitfire@spitfire':[u'to-janus']:'{"janus":"create","transaction":"ngoxvqs8fuk57b9"}'
    [x] 'deliver.to-janus':u'spitfire@spitfire':[u'to-janus']:'{"janus":"create","transaction":"ngoxvqs8fuk57b9"}'
    [x] 'publish.':u'spitfire@spitfire':[u'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00']:'{\n   "janus": "success",\n   "transaction": "ngoxvqs8fuk57b9",\n   "data": {\n      "id": 4118201706\n   }\n}'

And here's the janus debug output

    Loading transport plugin 'libjanus_rabbitmq.so'...
    JANUS RabbitMQ transport plugin created!
    Configuration file: /etc/janus/janus.transport.rabbitmq.cfg
    [janus.transport.rabbitmq.cfg]
        [general]
            enable: yes
            host: localhost
            to_janus: to-janus
            from_janus: from-janus
        [admin]
    RabbitMQ support for Janus API enabled, localhost:5672 (to-janus/from-janus)
    [WARN] RabbitMQ support disabled (Admin API)
    Creating RabbitMQ socket...
    Connecting to RabbitMQ server...
    Logging in...
    Joining EchoTest handler thread
    EchoTest watchdog started
    Joining VideoRoom handler thread
    VideoRoom watchdog started
    Opening channel...
    Declaring incoming queue... (to-janus)
    Declaring outgoing queue... (from-janus)
    Setup of RabbitMQ integration completed
    JANUS RabbitMQ transport plugin initialized!
            Version: 1 (0.0.1)
            [janus.transport.rabbitmq] JANUS RabbitMQ transport plugin
            This transport plugin adds RabbitMQ support to the Janus API via rabbitmq-c.
            Plugin API version: 5
            Janus API: enabled
            Admin API: disabled
    [WARN] Transport plugin 'libjanus_http.so' has been disabled, skipping...
    [WARN] Transport plugin 'libjanus_websockets.so' has been disabled, skipping...
    Sessions watchdog started
    Joining RabbitMQ out thread
    Joining RabbitMQ in thread
    Frame type 1, channel 1
    Method AMQP_BASIC_DELIVER_METHOD
    Delivery #1, to-janus
    -- This is a Janus API request
    Frame type 2, channel 1
    Frame type 3, channel 1
    Got 51/51 bytes from the Janus API queue (51)
    {"janus":"create","transaction":"fzxeex4ug0la0pb9"}
    Got a Janus API request from janus.transport.rabbitmq (0x23128c0)
    Transport task pool, serving request
    Creating new session: 488741953
    Sending Janus API response to janus.transport.rabbitmq (0x23128c0)
    Sending Janus API event via RabbitMQ
    Sending Janus API message to RabbitMQ (104 bytes)...
    {
    "janus": "success",
    "transaction": "fzxeex4ug0la0pb9",
    "data": {
        "id": 488741953
    }
    }
    Timeout expired for session 488741953...
    Sending Janus API event via RabbitMQ
    Sending Janus API message to RabbitMQ (53 bytes)...
    {
    "janus": "timeout",
    "session_id": 488741953
    }
    [janus.c:janus_cleanup_session:286] Cleaning up session 488741953...
    Destroying session 488741953

I'm on the latest version of janus and librabbitmq-c. Let me know if there's anything else needed to troubleshoot this.

**Comment by lminiero** [comment]
You're right, apparently the cause is this commit here: https://github.com/meetecho/janus-gateway/commit/98abb11d38a0c0f3c4908a65963f6263c62f3695#diff-487e4ae0bbc4d56a42faf9fecab1073c where we basically tried to fix some leaks. I guess that when we do a ```amqp_cstring_bytes``` to declare queues, the bytes are not copied but the original strings are actually still used: since we free them, they point to garbage and messages are sent on non-existing queues.

I'll fix this shortly and let you know when it's working again.

**Comment by lminiero** [comment]
This fixes it for me, let us know if it's still broken for you.

**Comment by Eltiech** [comment]
Yep, looks great. Thanks man.
