### ISSUE TITLE
libwebsocket

### ISSUE THREAD

**Issue by interfaith** [meetecho/janus-gateway#436]
the new api will not compile,

**Comment by ploxiln** [comment]
Can you please include what commands you ran to build/install libwebsockets and build janus, and what the configure or make error message was.

(If you include a long log of the compile, please put it in a pastebin/gist and only include the link in the issue comment)

**Comment by interfaith** [comment]
git clone git://git.libwebsockets.org/libwebsockets
cd libwebsockets
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..
make && sudo make install

then configure for janus gives

checking for TRANSPORTS... yes
checking for MHD... yes
checking for libwebsocket_get_internal_extensions in -lwebsockets_shared... no
checking for libwebsocket_get_internal_extensions in -lwebsockets... no
configure: error: libwebsockets not found. See README.md for installation instructions or use --disable-websocket

**Comment by ploxiln** [comment]
If you carefully examine the janus README.md, there's a new argument to cmake for libwebsockets: `-DLWS_WITH_OLD_API_WRAPPERS=1`

**Comment by ploxiln** [comment]
huh that might not work anymore let me check

**Comment by ploxiln** [comment]
yup, removed in https://github.com/warmcat/libwebsockets/commit/11c05bfa09a0d4a71588a6eb8d03aba5e1c48e59

simplest thing to do is checkout tag `v1.5-chrome47-firefox41` of libwebsockets and use that (doesn't require the new cmake define or anything)

**Comment by interfaith** [comment]
one comment from libwebsocket
The name of libwebsocket_get_internal_extensions has been changed to lws_get_internal_extensions in the latest master branch. So janus would have to be changed to use the new updated API.

So you should checkout the latest libwebsockets release instead, that has the old API and build that instead.

**Comment by interfaith** [comment]
download this ? 
http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/tag/?h=v1.5-chrome47-firefox41

**Comment by ploxiln** [comment]
yup, downloading and using that tarball should work; another option is to add the command `git checkout v1.5-chrome47-firefox41` to the existing commands in the README, just before `cmake ...`

**Comment by lminiero** [comment]
Ah, so they've removed the compatibility layer? Why add it in the first place to then just get rid of it almost immediately? I'll update the README tomorrow to refer to the tagged version.

**Comment by lminiero** [comment]
Updated in https://github.com/meetecho/janus-gateway/commit/c77dcef1566fb340eeea4e0ec4bed83c3a689515

**Comment by ivanovaleksey** [comment]
Hello guys, what is the right way to install `libwebsockets` today?

Initially I was installing it via package manager, i.e. `apt-get install libwebsockets-dev`.
It seemed to install version _1.7.1_ (though I am not sure here).
But I was receiving an error 
> configure: error: libwebsockets not found. See README.md for installation instructions or use --disable-websocket

Then I found this issue. I tried to install it from source like it said in Janus README
```
git clone git://git.libwebsockets.org/libwebsockets
cd libwebsockets
# it said that I could also checkout to v1.5-chrome47-firefox41 tag
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..
make && make install
```
and then I reconfigure Janus with `--enable-websockets`. It succeed.

Why does it fail with package version?
And should I checkout to v1.5-chrome47-firefox41? It seems to be a very old version (last commit on Oct 28, 2015).

Thanks.

**Comment by lminiero** [comment]
The README is outdated, I think you need at least 2.x as we use the library
vhost stuff now.

L.

Il 10 nov 2017 11:34 PM, "Aleksey Ivanov" <notifications@github.com> ha
scritto:

**Comment by ivanovaleksey** [comment]
Thank you @lminiero, on master branch I seem to install _2.4.0_.
