### ISSUE TITLE
Reload Configuration File

### ISSUE THREAD

**Issue by rodrhern** [meetecho/janus-gateway#437]
It is possible to reload the `janus.plugin.streaming.cfg` configuration file in order to create more streaming endpoints without interrupting the already axisting ones???

Best Regards

**Comment by lminiero** [comment]
You can use the API to create and destroy mountpoints, also permanently.

**Comment by frankville** [comment]
Hi, I'm also interested on the posibility of reload streaming.cfg to add/remove streams without needing to restart the entire janus. Is it possible with an api call?

**Comment by lminiero** [comment]
You can add/remove streams via API already, and choose whether to make mountpoints permanent and save them to cfg. As such, I don't really see a need for a reload request.

**Comment by frankville** [comment]
Oh, I couldn't find any docs or examples about that. Where can I read about how to  create/remove streams and save them to cfg? I've read in the admin/monitoring section but didn't found anything.

**Comment by frankville** [comment]
ok, I'll post a thread there. thanks!
