### ISSUE TITLE
Video and Audio device changing (videoroom)

### ISSUE THREAD

**Issue by leonuh** [meetecho/janus-gateway#439]
Hi there,

I am planning to develop a feature to change the video / audio device (stream) in the videoroom. Do you have any opinion / suggestion / concern?

The basic idea:
- getting the sources through getSources
- extends createOffer with a "forced" parameter - to recreate the offer with the new devices
so prepareWebrtc function would be extended with something like:
```
if(callbacks.forced && config.sdpSent) {
    config.sdpSent = false;
    config.pc = null;
    pluginHandle.send({
        message: { request: 'detachstream' },
        success: function() {
            callbacks.forced = false;
            prepareWebrtc(handleId, callbacks);
        }
    });
    return;
}
```
The "detachstream" would prepare the feed to reattach the new stream (i tried it out and it works - but maybe other things are necessary)
```
 if(participant->sdp) g_free(participant->sdp);
 participant->sdp = NULL;
 participant->audio_active = FALSE;
 participant->video_active = FALSE;
```
- createOffer media's audio / video param would be extended to accept objects(constraint) like:
```
{
    optional: [{
        sourceId: audioDeviceId
    }]
}
```

**Comment by lminiero** [comment]
I don't think this needs any change in the videoroom plugin: as far as the plugin is concerned, you're negotiating a media channel, and it really doesn't care if the video is camera1, camera2 or a screen share. When you want to change the source of the media, there's no need for a detachstream request: you just unpublish, and then publish again, this time with a different source for the media.

Any improvement on the way sources are detected and used on the JavaScript side is more than welcome instead!

**Comment by lminiero** [comment]
I think we can close this?
