### ISSUE TITLE
Videoroom recordings (timestamp) issue

### ISSUE THREAD

**Issue by externuz** [meetecho/janus-gateway#440]
I have a big problem with the time in recordings files name. The problem is that I collect the full record in a room with the help of ffmpeg, based on these timestamps (in filename), but they are at odds with reality for 2-3 seconds. Is it possible to somehow get a more accurate start time?

**Comment by lminiero** [comment]
When post processing video recordings, the tool prints out the time the recording was created and when the first keyframe was received. You can use those pieces of information to figure out the gap, as the resulting video file will miss anything prior to the keyframe, and so with that info you can align it to audio or other recordings. You can also just pass ```--header``` to only have the tool print out that the first info (creation time) without converting the recording (again), but you'll have to process the recording to get the keyframe time instead.

Closing as we added those to solve exactly that problem, and it works for us.

**Comment by lminiero** [comment]
To continue this discussion, please use the meetecho-janus group instead.

**Comment by externuz** [comment]
That's what I do. The problem is that three of files - the two have a real time, and in one - offset by about 3 seconds from the actual time. Actually it started in the 1453036010000 and in the file name - 1453036013000. This is verified by experiment

**Comment by lminiero** [comment]
I'm not talking about created/written times, there's an additional piece of info for when the first keyframe appeared: https://github.com/meetecho/janus-gateway/blob/master/postprocessing/pp-webm.c#L315
You'll need to play with whatever tool you're using to then make use of that info to enforce the belated appearance of the affected medium.

**Comment by externuz** [comment]
Where can I extract that info? Don't understand. janus-pp-rec does not log this info to console

**Comment by lminiero** [comment]
Open the link I posted: there's a print of something like "First keyframe". If it's not printing anything for you you're either using a too old version of the processor, or the video recording has no keyframe at all (unlikely).

**Comment by externuz** [comment]
[WARN] New .mjr header format
This is an audio recording:
  -- Codec:   opus
  -- Created: 1453370850569703
  -- Written: 1453370851548238
Counted 1268 RTP packets
Counted 1268 frame packets
Writing .opus file header
gena.opus is 101284 bytes
Bye!

-- Writen:    <------ this?

**Comment by lminiero** [comment]
Nope... as I already said some mails ago, "You can also just pass --header to only have the tool print out that the first info (creation time) without converting the recording (again), _but you'll have to process the recording to get the keyframe time instead_." Just convert as usual.

**Comment by externuz** [comment]
I understood. Many thanks!!!
