### ISSUE TITLE
No such feed

### ISSUE THREAD

**Issue by externuz** [meetecho/janus-gateway#445]
I have a problem with feeds. 
When new feed has been published, cb function execute:
```
Translation.prototype.publish = function(cb) {
  var self = this;
  self.handle.createOffer({
    media: {
      audioRecv: false,
      videoRecv: false,
      audioSend: true,
      videoSend: true
    },
    success: function(jsep) {
      self.handle.send({
        'message': {
          'request': 'configure',
          'audio': true,
          'video': true
        },
        'jsep': jsep
      });
      cb({});
      // check if janus has this stream
    },
    error : function(err) {
      cb({ err : err });
    }
  });
};
```

this callback function tell other users to connect videoroom as listener and show stream on their screens. But sometimes, feed does not exists in Janus, and i have error in Janus log (No such feed xxxxxxxx);

Where can I do my callback, to be sure feed is exist in Janus? Or how can I know in my js, that feed is exist?

**Comment by lminiero** [comment]
When your new publisher gets a "published" event (or something like this, check the demo to be sure) then the publisher feed is available for subscribers. Closing as not an issue, please continue this discussion on the meetecho-janus Google group for more help and feedback (our github issues is for real problems only).
