### ISSUE TITLE
segfault in janus_sip.c:1924

### ISSUE THREAD

**Issue by cwerner-bfs** [meetecho/janus-gateway#447]
Hi guys,

When hanging up SIP calls we are seeing segfaults from time to time in janus_sip.c (line 1924). We are using the code from the currect master branch.

```
root@janus:~/janus/janus-gateway# gdb /opt/janus/bin/janus /core
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
[...]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/opt/janus/bin/janus'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  janus_sip_sofia_callback (event=nua_r_shutdown, status=200, phrase=0x7ff190002370 "Shutdown successful", nua=0x7ff1900bb900, magic=0x7ff1900be8e0, nh=0x0, hmagic=0x0, sip=0x0, tags=0x7ff190002360)
    at plugins/janus_sip.c:1924
1924                            su_root_break(ssip->s_root);
(gdb) print ssip
$1 = (ssip_t *) 0x0
```

Looks like ssip points to 0x0, but I cannot find the reason for that.

It happens here roughly once in a series of 100 hangup events. It might be, that in these rare cases the SIP session has died for some other resons short before hanging up (but I cannot say for sure). 

Any ideas?

Best regards

Christian

**Comment by lminiero** [comment]
I thought we checked for the validity of ```ssip``` at the beginning of ```janus_sip_sofia_callback```, but we apparently aren't... I guess you're right in thinking the SIP session has died before for some reason, but you should check the logs to see if that's the case. Anyway, I'll add some checks for ```ssip``` before it is used in that or other event handlers in the callback.

**Comment by lminiero** [comment]
Let me know if this fixes it for you.

**Comment by cwerner-bfs** [comment]
Yes, no more segfaults. :)

Thanks a lot!
