### ISSUE TITLE
Missing var statement in Janus.js causes handles not to be destroyed in some cases.

### ISSUE THREAD

**Issue by MagicIndustries** [meetecho/janus-gateway#448]
I've found while using the video room plugin, when I refresh my client there are some console errors when it tries to disconnect. It appears these errors are preventing the proper destruction of handles, and were causing my sessions to hang around and get mixed up.

The errors are caused by missing var statements in three for loops, I'm thinking maybe I'm seeing them because I'm concatenating the janus code into other code that has use strict enabled.

Will organise a pull request

**Comment by lminiero** [comment]
Thanks for the feedback, keep us posted!

**Comment by MagicIndustries** [comment]
All done. Let me know if you need anything more for it

**Comment by lminiero** [comment]
Works for me :wink:
