### ISSUE TITLE
Missing the authorization header in SIP message

### ISSUE THREAD

**Issue by hoangtuansu** [meetecho/janus-gateway#450]
Hello,

When I test the gateway with OpenCoreIMS, it fails at REGISTER step to P-CSCF because of the missing of authorization field in SIP message. I tried to add some codes in janus_sip.c (just for the sake of getting through REGISTER step) as following but it still not work. 
`...
_static char *authorization_h;_

...

gpointer janus_sip_sofia_thread(gpointer user_data) {

...

_authorization_h = g_strdup("Digest USERNAME=\"alice@open-ims.test\", REALM=\"open-ims.test\", NONCE=\"\", RESPONSE=\"\", URI=\"sip:open-ims.test\"");_

session->stack->s_nua = nua_create(session->stack->s_root,
                                janus_sip_sofia_callback,
                                session,
                                SIPTAG_ALLOW_STR("INVITE, ACK, BYE, CANCEL, OPTIONS"),
                                NUTAG_M_USERNAME(session->account.username),
                                NUTAG_URL(sip_url),
                                _SIPTAG_AUTHORIZATION_STR(authorization_h),_
                                TAG_IF(session->account.sips, NUTAG_SIPS_URL(sips_url)),
                                SIPTAG_USER_AGENT_STR(user_agent),
                                NUTAG_KEEPALIVE(keepalive_interval * 1000),     /* Sofia expects it in milliseconds */
                                NUTAG_OUTBOUND(outbound_options),
                                SIPTAG_SUPPORTED(NULL),
                                TAG_NULL());
...

`
I don't know if this is an issue of gateway or I should check further with sofia-sip (and rebuild the sofia lib ). So please correct me if I'm wrong.

Regards,

**Comment by lminiero** [comment]
There shouldn't be any need to mess with the code, the authorization stuff is handled automatically by the plugin. If you need a different authorization username than the SIP username to register, check the "authuser" option.

That said, it's normal for the first REGISTER message to fail, as the server will reply with a 401 and the stack will provide the authorization string in a new REGISTER that follows.

**Comment by hoangtuansu** [comment]
Hi,

The IMS system always requires the Authorization header in every REGISTER message (you can check the message flow [here](https://www.eventhelix.com/ims/registration/ims_registration.pdf). In the first message, its values may be empty in some fields (e.g. NONCE, RESPONSE) but it must exists, otherwise the P-CSCF will notify the missing of Authorization header, as following (from OpenIMSCore system):

> > ERR:P-CSCF:cscf_get_authorization: Message does not contain Authorization
> > header.
> >  2(18811) INF:P-CSCF:P_add_integrity_protected: No authorization header found.

I see that this is webrtc2sip, not webrtc2ims which SIP is extended. But IMHO, adding this stuff makes it possible to interwork with both IMS system and SIP-legacy one.

**Comment by lminiero** [comment]
If so, I think you have to add the header when creating the REGISTER, not when creating the stack in general. that is around here: https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_sip.c#L1232

**Comment by hoangtuansu** [comment]
Hi Iminiero,

After adding some stuffs as following, it solved problem.

> authorization_h = g_strdup("Digest USERNAME=\"alice@open-ims.test\", REALM=\"open-ims.test\", NONCE=\"\", RESPONSE=\"\", URI=\"open-ims.test\"");
> nua_register(session->stack->s_nh_r,
>                      NUTAG_M_USERNAME(session->account.username),
>                      SIPTAG_FROM_STR(username_text),
>                      SIPTAG_AUTHORIZATION_STR(authorization_h),
>                      SIPTAG_TO_STR(username_text),
>                      SIPTAG_EXPIRES_STR(ttl_text),
>                      NUTAG_PROXY(proxy_text),
>                     TAG_END());

But it's still not working since the "authuser" value should be "alice@open-ims.test" instead of only "alice". To successfully register, I modified at client side by adding additional "authuser" to REGISTER message  in siptest.js, as following:

> var register = {
> 		"request" : "register",
> 		"username" : username
> 	};
> 	var sip_user = username.substring(4, username.indexOf('@'));    /* skip sip: */
> 	var sip_domain = username.substring(username.indexOf('@')+1);
> 	**register["authuser"] = sip_user+'@'+sip_domain;**
> 	
> 	if(selectedApproach === "secret") {
> 		// Use the plain secret
> 		register["secret"] = password;
> 	} else if(selectedApproach === "ha1secret") {
> 		register["ha1_secret"] = md5(sip_user+':'+sip_domain+':'+password);
> 	}

I'm unable to install an legacy-SIP server to test if it works. I think this change should be made at gateway side instead.

**Comment by lminiero** [comment]
The Digest usually works on the username. If the whole URI is the username in your context, then yes, you should use authuser for that, as otherwise we just strip the username part from the provided SIP URI and use that.

I'll make some tests to make sure your proposed fix (authorization header right away) doesn't break anything in other contexts.

**Comment by lminiero** [comment]
Please test this PR and let me know if that works for you.
