### ISSUE TITLE
How to republish?

### ISSUE THREAD

**Issue by mbellezi** [meetecho/janus-gateway#454]
I'm having this scenario:
1) One subscribe and publish a stream
2) The ICE fails at the client (suppose wrong or offline stun server) for this publishing
3) One needs to publish again, so one unpublish the stream and publish again after 2 seconds (as recommended)
4) One still gets 'Can\'t publish, already published'

Do I need to unsubscribe, subscribe again and then publish again? What is the better solution in this case (ICE failed).

Thx

**Comment by lminiero** [comment]
Duplicated of #452.
