### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by externuz** [meetecho/janus-gateway#457]
Janus stopping after about 20 mins from start. In console: Segmentation fault (core dumped)

**Comment by lminiero** [comment]
You need to be much more detailed than this...
https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md

**Comment by externuz** [comment]
Last messages from console: http://pastebin.com/vNGMn9Uq
Debug level is 7

**Comment by externuz** [comment]
That's interesting. After about 15 min working in `top`:

http://imgur.com/gJ6i5ni

**Comment by externuz** [comment]
With debug level 7 and debug nice:

http://pastebin.com/wYx4qpFS

**Comment by externuz** [comment]
Use only TURN, not STUN. Server stopped with 530% CPU. Here is a log:
http://pastebin.com/eWwCKPUH

**Comment by externuz** [comment]
Problem has been solved by disabling TURN

**Comment by lminiero** [comment]
Did you have TURN enabled in the Janus configuration file? As the FAQ says that should not be needed: you most typically only need it on the client side (JavaScript), that is for end users. Nevertheless, it shouldn't result in the CPU usage you see. Anwyay, closing the issue for now, feel free to reopen in case it happens again.

**Comment by mwager** [comment]
Sending a "join" request with Firefox 47.0.1 from a windows VM (NAT) to the server on the host gives me sometimes:

```
2016-07-19T08:34:45.263356710Z  [1453172324522112] Creating ICE agent (ICE Full mode, controlled)
2016-07-19T08:34:45.727358765Z  Segmentation fault (core dumped)
```

We need to restart the gateway then.

**Comment by lminiero** [comment]
Saying it crashes without providing details doesn't help. We need a backtrace of the error.

**Comment by lminiero** [comment]
Besides, why commenting on a long-closed issue? If you believe you found a new problem, please open a new issue, paying attention to the [guidelines](https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md).
