### ISSUE TITLE
janus_streaming.c poll revents not all handled

### ISSUE THREAD

**Issue by marchaase** [meetecho/janus-gateway#459]
I'm getting a tight loop in a streaming thread causing high CPU.  I have a webcam on a laptop streaming video to the janus server, but I occasionally close the lid and let it go to suspend and unsuspend it starts the stream up again.  Not sure if that has anything to do with this, but I have had the high cpu usage when the stream was active as well. 

In htop I am able to identify the process with a name of one of my video streams.  When I strace the process it's tight looping on a poll call.
`poll([{fd=0, events=0}, {fd=8, events=POLLIN}], 2, 1000) = 1 ([{fd=0, revents=POLLERR|POLLHUP}])`

It's coming back with a POLLERR and POLLHUP response in revents.

Looking at the source in janus_streaming.c it seems there is a file descriptor for the audio and video streams that look at the responses to the poll @ https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L3421 and https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L3469.  But they only handle the POLLIN event.

I have not had much time to dig through the source code, but it looks like this condition isn't handled and causes the process to spin on the poll event.  It looks like the POLLHUP means the other side hung up, but I'm not sure if that is the case as I've seen this occur while the stream was active.

In any case it looks like there is a hole here where only POLLIN revents are handled.

**Comment by lminiero** [comment]
I don't see how POLLHUP can be set since it's a UDP socket and so there's no connection to be closed in the first place. It sounds more like it's the local listening socket that "breaks down" for some reason. When I get back to the office on Monday I'll give this a look.

**Comment by marchaase** [comment]
I agree it doesn't make sense for a POLLHUP to occur on a UDP socket.  But maybe it's because the POLLERR as well?  If there was an error on the socket then maybe the POLLHUP indicates that the socket is closed or has an error?  I don't think it's a connection per say breaking down, but maybe the socket itself?  Though I can't imagine how or why that could occur.

I searched the source here on github for other poll calls and the only other call I see is in janus_sip.c which I'm not using.

The error isn't occurring right now and I'm not sure what/when causes the issue to appear, but if I see it I'll try to gather more information on it.  I'll be running with debug level 7 to see if I can see anything in the logs.  And I can try to attach to the process with gdb to see if I can get some information that way, but I don't have the source compiled in debug so I'm not sure if I'm competent enough to see what's going on there.

**Comment by lminiero** [comment]
I'll add a check for POLLERR and POLLHUP in the code to print an error in the logs when that happens. I guess this will also have to result in the viewers be notified about the mountpoint becoming unavailable, and the mountpoint itself to be disabled (rather than destroyed).

**Comment by lminiero** [comment]
Can you let me know if this helps? https://github.com/meetecho/janus-gateway/pull/460
Especially if you manage to find a way to easily replicate the issue.

**Comment by marchaase** [comment]
I havn't figured out a way to replicate the issue.  It did happen again yesterday.  I just updated to the pull request branch streaming-pollerr and recompiled and re-installed.

I'll see if I see the new LOG_ERR message when/if I see some stream issues.

I think the errno might be wrong as well - as the poll didn't return -1.  It looks like on the man page for poll it only sets errno for the -1 return.  Would a recvmsg be appropriate here?  Though I'm not sure what kind of data could be obtained through that call.

I'm not sure if just setting the mountpoint->enabled to false is going to solve the problem.  From the looks of it I think the while loop will still spin on the poll as it will just continue to push out POLLERR|POLLHUP revents.  It looks like the same might happen on the -1 return getting caught in the earlier if statement after the poll.

I guess it'd be pretty hard to get an error on a udp socket might be part of the reasons these branches never get hit.

I'll keep an eye out for more information, and I still have not been able to find a way to easily replicate the issue.  I'm on an overloaded openVZ VPS and I have a hunch it might be due to the struggle for resources, but I still would think the kernel would just drop data before having a socket error for udp.

**Comment by lminiero** [comment]
Setting the mountpoint->enabled to false is not going to solve the problem, but since we're breaking the loop when an error happens we're preventing other users to subscribe to a mountpoint that can't be used anymore. The only way to recover would be to recreate the file descriptor somehow, which if we did may or may not succeed, and may lead to a different kind of loop (especially if it's a matter or resources exhaustion).

The pull request tries to at least detect when the problem happens: we can then try to figure out later what the best approach to handle it should be.

**Comment by lminiero** [comment]
I merged the PR, so now you can just try with master. Closing this issue as the main problem (poll events not being handled) should be fixed, feel free to repoen if that's not the case. Should you want to suggest particular actions when this happens in the streaming plugin (for which we currently disable the mountpoint and tell all viewers the show is over), please open a new issue.
