### ISSUE TITLE
libmicrohttpd required even with --disable-rest

### ISSUE THREAD

**Issue by andreasg123** [meetecho/janus-gateway#461]
../configure --disable-rest
checking for MHD... no
configure: error: libmicrohttpd not found. See README.md for installation instructions or use --disable-rest

There is no test for enable_rest in configure.ac before checking for libmicrohttpd:

PKG_CHECK_MODULES([MHD],
                  [libmicrohttpd],
                  [],
                  [
                    AC_MSG_ERROR([libmicrohttpd not found. See README.md for installation instructions or use --disable-rest])
                  ])

When removing libmicrohttpd after configure, make still runs without problems.

**Comment by lminiero** [comment]
You're right, I'll fix the check, thanks for noticing.

**Comment by lminiero** [comment]
This fixes it for me, feel free to reopen if that's not the case.
