### ISSUE TITLE
Configuration files are required

### ISSUE THREAD

**Issue by andreasg123** [meetecho/janus-gateway#462]
I followed README.md that states: "In the absence of a configuration file, the only mandatory options to
specify in the command line are the ones related to the DTLS certificate."

However, configuration files for the HTTP and Websockets transports are required because otherwise the plugins do nothing:

bin/janus -d 9 -c foo.crt -k foo.key
JANUS REST (HTTP/HTTPS) transport plugin created!
Configuration file: /data/janus/etc/janus/janus.transport.http.cfg
[ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.transport.http.cfg'... error 2 (No such file or directory)
[FATAL] [transports/janus_http.c:janus_http_init:637] No HTTP/HTTPS server started, giving up...
Loading transport plugin 'libjanus_websockets.so'...
JANUS WebSockets transport plugin created!
Configuration file: /data/janus/etc/janus/janus.transport.websockets.cfg
[ERR] [config.c:janus_config_parse:91]   -- Error reading configuration file 'janus.transport.websockets.cfg'... error 2 (No such file or directory)
[FATAL] [transports/janus_websockets.c:janus_websockets_init:480] No WebSockets server started, giving up...
[FATAL] [janus.c:main:3670] No Janus API transport is available... enable at least one and restart Janus

For HTTP, an empty configuration file doesn't work either because no webserver is enabled by default:
[janus.transport.http.cfg]
[WARN] HTTP webserver disabled
[WARN] HTTPS webserver disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled

The following seems to be the minimally acceptable file:

[general]
http = yes

It would be nice if the transport plugins had defaults.  Otherwise, changing README.md to indicate required configuration files would make this less confusing.

**Comment by lminiero** [comment]
You're right, thatks for spotting this, the documentation is indeed a bit outdated here. I'll think about whether we should have defaults for the configuration files, or instead mandate the configuration files to be available and so update the docs accordingly. I'm personally more inclined towards the latter, especially considering there may be third party plugins and transport modules we don't have control on.

**Comment by saghul** [comment]
I'm a huge fan of zero-configuration. Ideally it Just Works (TM) out of the box, with zero work on the user side, this really increases their satisfaction.

**Comment by lminiero** [comment]
Fair point, some plugins will still require a configuration to be meaningful, though: for instance, the streaming plugin needs mountpoints to be explicitly provided, otherwise it can't "invent" them. I'll try to come with some reasonable defaults where they're missing.

**Comment by saghul** [comment]
Sure, not everything can work, that's fine. The bottom line is IMHO to give the most amount of functionality with the least amount of configuration.

**Comment by lminiero** [comment]
Thinking about it, we have a "just works" thing: it's called "make configs" right after you install, that installs some default configuration files for you. I think I'll stress that point out in the docs, rather than concocting some default values that may be harmful rather than helpful: e.g., if you don't specify an HTTP webserver but do specify an HTTPS one, are you implicitly enabling the HTTP webserver as well (as the default may be true) or telling the module to only do HTTPS? I'd much rather have the configuration files draw the behaviour, and have default configuration files for people who don't want to worry (which is also me, as I usually change only a tiny part of them, if any).

**Comment by lminiero** [comment]
This change to the README should hopefully make this all clearer: https://github.com/meetecho/janus-gateway/commit/4756ae279eed4ebdbd8172b9c4a25f9e8bbfd2c4
