### ISSUE TITLE
Janus crash

### ISSUE THREAD

**Issue by epasqualotto** [meetecho/janus-gateway#473]
We are testing some interoperability between the SIP plugin and Cisco CallManager.
The call is working (audio only) from SIPdemo to Cisco CallManager but if I call from a phone connected to PBX I got:

[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32711)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32712)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32713)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32714)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32715)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32716)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32717)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32718)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32719)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32720)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32721)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32722)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32723)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32724)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32725)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32726)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32727)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32728)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32729)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32730)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32731)...
[ERR] [ice.c:janus_ice_send_thread:3123] [494981431] ... SRTP protect error... err_status_replay_old (len=104-->104, ts=1515344976, seq=32732)...
No WebRTC media anymore
[ERR] [plugins/janus_sip.c:janus_sip_handler:1451] Wrong state (not in a call? status=idle)
[494981431] WebRTC resources freed

**Comment by lminiero** [comment]
Is the problem a crash/segfault, or audio not working?

What is happening when you get the phone call from the PBX froom a signaling and media perspective? Are you re-using an existing PeerConnection and/or still active SIP call? The errors you pasted are from a replay detected by SRTP, meaning the plugin tried to send a timestamp/sequence number combo that was already sent in the recent past (which means that's what the SIP endpoint is sending).

**Comment by epasqualotto** [comment]
Maybe the error isn't linked to the crash. I've reproduce the call with debug=7 and Janus doesn't log any lines.

This is the complete SIP trace: http://box.backloop.biz/index.php/s/GnVoA2QDRs2FXZs

**Comment by lminiero** [comment]
Sorry, won't have time to look into this until next week. Make sure you're
using the latest master as we fixed a couple of serious issues in the SIP
plugin lately.
Il 24/feb/2016 18:03, "epasqualotto" <notifications@github.com> ha scritto:

**Comment by lminiero** [comment]
Is this still an issue with an up-to-date Janus?

**Comment by shrhoads** [comment]
I can report that our crashes using SIP plugin seemed to have stopped.  I'll report if they come back.

**Comment by lminiero** [comment]
Ok, thanks, closing this issue then. Feel free to reopen in case.
