### ISSUE TITLE
Janus on Centos 7

### ISSUE THREAD

**Issue by oej** [meetecho/janus-gateway#475]
Not a bug, but for documentation. Successfully compiled the base Janus on Centos 7. These packages was helpful:
```
yum -y install epel-release
yum -y install jansson jansson-devel libnice libnice-devel openssl-devel  \
libsrtp libsrtp-devel libmicrohttpd-devel libmicrohttpd cmake opus \
opus-devel libogg libogg-devel glib2 glib2-devel pkgconfig autoconf automake wget gengetopt \
libogg libogg-devel libtool doxygen curl libcurl-devel graphviz
```

**Comment by lminiero** [comment]
You mean epel-release? I'll add this to the README when I'm back, thanks!
Il 26/feb/2016 20:06, "Olle E. Johansson" <notifications@github.com> ha
scritto:

**Comment by lminiero** [comment]
This commit adds a note on ```epel-release``` to the README which should make it clearer.
