### ISSUE TITLE
Cannot start http transport unless running as root

### ISSUE THREAD

**Issue by richp10** [meetecho/janus-gateway#480]
I have janus working perfectly when running as root - but want to run with few priv's.  Janus seems unable to bind to port 80 when not running as root. 

This works great..
```
export LD_LIBRARY_PATH=/usr/lib64 
/bin/janus --configs-folder=/home/janus/conf
```

But the following does not: 

Create a dedicate user to run janus

```
/usr/sbin/groupadd janus
/usr/sbin/useradd janus -g janus
/usr/sbin/usermod -s /bin/bash -d /home/janus janus
```

Run as this user...

```
su -c "export LD_LIBRARY_PATH=/usr/lib64 ;/bin/janus --configs-folder=/home/janus/conf" -s /bin/bash janus

```

The websockets transport loads, but not http or http admin..

```
Loading transport plugin 'libjanus_http.so'...
[FATAL] [transports/janus_http.c:janus_http_init:400] Couldn't start webserver on port 80...
[WARN] HTTPS webserver disabled
[FATAL] [transports/janus_http.c:janus_http_init:545] Couldn't start admin/monitor webserver on port 81...
```

Any thoughts?

**Comment by njam** [comment]
Usually non-root users cannot bind ports below 1024 on Linux.

**Comment by lminiero** [comment]
Exactly, @njam beat me to it :+1: 
Closing as not an issue.
