### ISSUE TITLE
Missing .nfo files

### ISSUE THREAD

**Issue by MagicIndustries** [meetecho/janus-gateway#483]
No matter how I setup the recording, I can't seem to get any .nfo files. I'm using the videoroom plugin, and the audio and video recordings are created in the appropriate directory, but there are no .nfo files.

Is there a setting somewhere to turn these files on or off? I need them as they're the only real way to know if a recording is finished by looking at the files.

**Comment by Globik** [comment]
And cmdline.c with cmdline.h are missing in this janus repository!!! But why? Why they are hidden in the .gitignore file??

**Comment by saghul** [comment]
@Globik those files are generated as part of compilation, they are not missing.

**Comment by lminiero** [comment]
@MagicIndustries the .nfo files are only generated by the Record&Play plugin: they're not a standard for our recordings, just a simple way to index them in that plugin. The VideoRoom recording only saves the .mjr files. Closing as not an issue.

**Comment by Globik** [comment]
Ah, I see. On msys2 runned autogen.sh script and configurating with compiling shown those cmdline's stuff, merci.
