### ISSUE TITLE
Exception on getUserMedia if video only but no camera

### ISSUE THREAD

**Issue by hoene** [meetecho/janus-gateway#489]
If you are calling getUserMedia with no audio but video, but the video camera is not installed,
then you get an exception.

However, you should get an error message 'No capture device found'

The bug is in janus.js round line 1455.

The line "if(!audioExist && !videoExist) {"
should be changed to 
if(!(audioExist && isAudioSendEnabled(media)) && !(videoExist && videoSupport)) {

Thanks

**Comment by lminiero** [comment]
Thanks for reporting this, we'll check if we can replicate this and if the fix you suggested works fine in other scenarios as well.

**Comment by lminiero** [comment]
@hoene we had to do a different check than the one you proposed, to account for when a device is available but not requested, and when one isn't but is actually needed. The new commit should address all the possible scenarios, and only fail when all the requested capture devices are not available.

**Comment by lminiero** [comment]
This additional commit fixes some edge cases where a double negative could actually be interpreted as a positive. This should fix the issue you reported, so I'll close the issue. Feel free to reopen in case you believe it's still not working as expected.

Thanks!
