### ISSUE TITLE
Unknown message media in janus.js

### ISSUE THREAD

**Issue by choene** [meetecho/janus-gateway#491]
Janus.js does not handle the "media" message so far.

However, this would be useful if e.g., the screensharing is switched off.

In order to support this feature, a pluginHandle call back would be useful.

For example, an modification of janus.js around line 370 can be made:

			}
		} else {
			var callback = pluginHandle.onmessage;
			if(callback !== null && callback !== undefined) {
				Janus.debug("Notifying application...");
				// Send to callback specified when attaching plugin handle
				callback(data, jsep);
			} else {
				Janus.warn("Unknown message '" + json["janus"] + "'");
			}
		}
	}
	
	// Private helper to send keep-alive messages on WebSockets
	function keepAlive() {

**Comment by lminiero** [comment]
We've been thinking about something like this, and yep, the idea is to add a handle callback a bit like ```consentDialog```, that is a ```media(on)``` that you can implement to be notified about when media starts and stops flowing. We'll probably add something like this in the near future.

**Comment by lminiero** [comment]
Implemented in https://github.com/meetecho/janus-gateway/commit/26f2fe26b1842da110441db9a946168c48862b84
