### ISSUE TITLE
Unable to start HTTPS Server

### ISSUE THREAD

**Issue by bharti795** [meetecho/janus-gateway#493]
changed the following 

https = yes			        ; Whether to enable HTTPS (default=no)
secure_port = 8889			; Web server HTTPS port, if enabled

Error is - 
[FATAL] [transports/janus_http.c:janus_http_init:488] Couldn't start secure webserver on port 8889...

Do I need to change something somewhere also ?

**Comment by lminiero** [comment]
Probably a configuration error. Closing as not an issue. Please use our meetecho-janus Google group for questions that pertain configuration and deployments.
