### ISSUE TITLE
Configuring keepalives

### ISSUE THREAD

**Issue by stormbkk87** [meetecho/janus-gateway#495]
Using RabbitMQ interface to Janus (SIP plugin) via Node server. Keepalives from the Node client (iOS 9) app work fine when application is in foreground. 

When the iOS app goes into the background, the client can't send keepalives every 50 seconds anymore. The minimum allowed keepalive is every 10 minutes to save battery life (Apple documentation). Is it possible to configure the Janus keepalive timeout? Or tell Janus to trust the Node server and keepalive all sessions until destroyed?

cheers

**Comment by lminiero** [comment]
It's not configurable via signalling, you'll have to configure the value in janus.c
Closing as not an issue, please ask questions of this sort on the [Google Group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
