### ISSUE TITLE
Add timestamp to all log entries

### ISSUE THREAD

**Issue by njam** [meetecho/janus-gateway#498]
Currently some messages in janus' log are not prefixed with a timestamp. To parse entries automatically it would be nice if all lines would have one.
wdyt?

cc @kris-lab

```
Bye!
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Gateway) v0.1.0
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are enabled
Debug/log colors are disabled
[Fri Apr  8 09:30:32 2016] Using 10.0.2.15 as local IP...
[Fri Apr  8 09:30:32 2016] [WARN] Token based authentication disabled
[Fri Apr  8 09:30:32 2016] RTP port range: 10010 -- 14999
```

**Comment by saghul** [comment]
If you run Janus using something like systemd it will do it automatically.
IMHO it belongs there.

**Comment by lminiero** [comment]
But he has a point that, since we have the feature in our own logging systems, it does seem a bit inconsistent. The problem here is that the configuration is only parsed after some more important things  happen, so I'll have to check if and how I can move things around a bit.

**Comment by njam** [comment]
I see your point about systemd/journald! Feel free to close this, it's not very important.

**Comment by lminiero** [comment]
Ack, I'll keep that in mind anyway for future commits.
