### ISSUE TITLE
Failed to set remote answer sdp: Offer and answer descriptions m-lines are not matching.

### ISSUE THREAD

**Issue by joshdickson40** [meetecho/janus-gateway#501]
I'm having some trouble getting data channel support working. I do see that it is installed and running correctly on the gateway / server side.

When testing the gateway using the audio bridge plugin and adding "data: true" to the media object sent in the createOffer() function as suggested, we get "Failed to set remote answer sep: Offer and answer descriptions m-lines are not matching."

The only [other case](https://groups.google.com/forum/#!topic/discuss-webrtc/Zl_dSnUT0go) I can find with that coming up is from Lorenzo from a few years ago, but I'm afraid I don't understand what he said the solution was.

Has anyone else run into this? Would love to know how to fix. Thanks!!!

**Comment by saghul** [comment]
A trace showing both the offer and answer would definitely help pinpoint the problem.

**Comment by joshdickson40** [comment]
Does [this](http://pastebin.com/WrikAuuT) webrtc-internals dump help? Will happily get a different log if that is not what you're talking about.

**Comment by lminiero** [comment]
The AudioRoom plugin does not handle data channels. It always only negotiates audio, and rejects video if it finds it in the offer. I guess it's not rejecting the data channel m-line as well, which results in a different number of m-lines in the answer and the failure you experience. I'll fix that in upcoming commits.

**Comment by joshdickson40** [comment]
Aha, that would certainly do it. Apologies, I should have realized from the documentation.

Is there an alternative strategy I should be using via an additional plugin that could achieve this use case? Or am I better off using something like a dedicated socket connection to achieve this.

**Comment by joshdickson40** [comment]
Ah, I see why I was confused. The audio room does not implement data channel but the video room does. 

Could I utilize the video room and disable the video stream?

**Comment by lminiero** [comment]
Yes, in the VideoRoom plugin you can negotiate what you want, even a datachannel only room if you'd like. The problem is in the AudioRoom plugin that doesn't always match the m-lines you offer as it doesn't take into account data channels.

**Comment by lminiero** [comment]
This should fix it: feel free to reopen if that's not the case.

**Comment by joshdickson40** [comment]
Wonderful. Thank you very much gentlemen.
