### ISSUE TITLE
Occasional segfault, possibly related to libnice?

### ISSUE THREAD

**Issue by arjenveenhuizen** [meetecho/janus-gateway#503]
On our production unit (CentOS 6.7 with ubuntu 14.04 docker container running janus git master) we run into a floating point segmentation fault ("13 Floating point exception(core dumped) ./janus -C conf/janus.cfg --configs-folder=`pwd`/conf") for the past couple of months. Unfortunately, it is impossible to reproduce and it happens only from time to time (sometimes after 5 minutes with a couple of connection, sometimes after 20 hours after hundreds of connections).

It seems to be related to libnice as far as I can make up from the stack trace but I am not an expert at interpreting gdb output.
[gdb bt](http://pastebin.com/9xuZyu1p)
[gdb bt full](http://pastebin.com/fs98ffhn)

I think https://github.com/etcimon/libasync/issues/7 seems to cover a similar problem (but in a completely different problem).

**Comment by arjenveenhuizen** [comment]
As I come to think of it, it does look a lot like #154  
We are using libnice-dev (1.0.4) right now.

**Comment by lminiero** [comment]
Sorry for the late reply, I was abroad. #154 should have been addressed in newer libnice versions, actually, IIRC. Did switching to a newer/older version help?

**Comment by arjenveenhuizen** [comment]
Yes, we switched to 1.13 and from that point onward we didn't notice any crashes anymore. Also, the spinning problem mentioned in #154 appears to be solved. I guess this issue can be closed but I think it is a good idea to update the install instruction to build the latest libnice from source as well.

**Comment by lminiero** [comment]
Closing this issue then.
