### ISSUE TITLE
Pressure testing data wanted

### ISSUE THREAD

**Issue by zycbobby** [meetecho/janus-gateway#505]
We are considering to introduce janus-gateway + audiobridge plugin to be used in production environment. 

I have tried some demo, open up serveral clients to join the same audio room, and I found the cpu usage of janus increasing sharply since more and more clients are joined.

I have checked some previous issues about CPU cost(especially the one about libnice), but I dont think that is a problem for me.

I wondered someone have the pressure testing report or recommended configuration for production use of janus?

**Comment by lminiero** [comment]
Please post requests like this on our meetecho-janus Google group, github is for issues only.
