### ISSUE TITLE
ice state issue

### ISSUE THREAD

**Issue by chienfuchen32** [meetecho/janus-gateway#508]
Hi, there!
I'm currently building a raspberry pi with a public website.
(idea from:http://www.rs-online.com/designspark/electronics/eng/blog/building-a-raspberry-pi-2-webrtc-camera?/designspark/electronics/blog/building-a-raspberry-pi-2-webrtc-camera=)
raspberry pi is behide NAT, website client is the same.
this work on LAN envioment, but now I could't find any connection to Janus connection...
I've tried stun(stun.l.google.com) and turn server(numb.viagenie.ca) both are added by Janus.cfg and streamtest.js, still no luck... It seems like there's no connection.
any suggestion? thanks!

about:webrtc in firefox shows:
ICE Stats
Local Candidate	Remote Candidate	ICE State	Priority	Nominated	Selected
192.168.52.1:64409/udp(host)	192.168.1.109:33584/udp(host)	failed	8646913483524145000		
192.168.85.1:64410/udp(host)	192.168.1.109:33584/udp(host)	failed	8646913483524014000		
10.100.82.52:64408/udp(host)	192.168.1.109:33584/udp(host)	failed	8646913483523883000		
192.168.52.1:64409/udp(host)	raspberry pi ip:33584/udp(serverreflexive)	failed	7205760503253959000		
192.168.85.1:64410/udp(host)	raspberry pi ip:33584/udp(serverreflexive)	failed	7205760503253828000		
10.100.82.52:64408/udp(host)	raspberry pi ip:33584/udp(serverreflexive)	failed	7205760503253697000		
client ip:36061/udp(serverreflexive)					
SDP
Local SDP

v=0

o=mozilla...THIS_IS_SDPARTA-43.0.1 4689911986851822618 0 IN IP4 0.0.0.0

s=-

t=0 0

a=sendrecv

a=fingerprint:sha-256 32:FD:8F:55:FE:C7:2F:98:EB:51:83:5C:53:A0:F8:D1:2E:47:B7:DA:B0:25:25:20:2D:82:DD:B5:BF:FB:9C:D3

a=group:BUNDLE video

a=ice-options:trickle

a=msid-semantic:WMS *

m=video 36061 RTP/SAVPF 96

c=IN IP4 client ip

a=candidate:0 1 UDP 2122121471 10.100.82.52 64408 typ host

a=candidate:4 1 UDP 2122252543 192.168.52.1 64409 typ host

a=candidate:8 1 UDP 2122187007 192.168.85.1 64410 typ host

a=candidate:1 1 UDP 1685921791 client ip 36061 typ srflx raddr 10.100.82.52 rport 64408

a=recvonly

a=end-of-candidates

a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1

a=ice-pwd:4d3cb8544f452e644f78542fa60c15ed

a=ice-ufrag:d5efe41a

a=mid:video

a=rtcp-fb:96 nack

a=rtcp-mux

a=rtpmap:96 H264/90000

a=setup:active

a=ssrc:1922265686 cname:{4ee4529b-624b-491d-a303-65cb8e95062e}

Remote SDP

v=0

o=- 1461739370852472 1461739370852472 IN IP4 raspberry pi ip

s=-

t=0 0

a=sendrecv

a=group:BUNDLE video

a=msid-semantic:WMS janus

m=video 1 RTP/SAVPF 96

c=IN IP4 raspberry pi ip

a=candidate:1 1 udp 2013266431 192.168.1.109 33584 typ host

a=candidate:2 1 udp 1677721855 raspberry pi ip 33584 typ srflx raddr 192.168.1.109 rport 33584

a=candidate:1 2 udp 2013266430 192.168.1.109 43683 typ host

a=candidate:2 2 udp 1677721854 raspberry pi ip 43683 typ srflx raddr 192.168.1.109 rport 43683

a=sendonly

a=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38

a=fmtp:96 profile-level-id=42e028;level-asymmetry-allowed=0;packetization-mode=1

a=ice-options:trickle

a=ice-pwd:ZQVcyExHP3Uaz+ahRbqR5Y

a=ice-ufrag:JyaQ

a=mid:video

a=rtcp-fb:96 nack

a=rtcp-mux

a=rtpmap:96 H264/90000

a=setup:actpass

a=ssrc:3566222015 cname:janusvideo

a=ssrc:3566222015 msid:janus janusv0

a=ssrc:3566222015 mslabel:janus

a=ssrc:3566222015 label:janusv0

RTP Stats
inbound_rtp_video_0

admin.html shows:
{
    "session_id": 3725251364,
    "session_last_activity": 28030835569,
    "session_transport": "janus.transport.http",
    "handle_id": 2529322762,
    "created": 27969219641,
    "send_thread_created": 0,
    "current_time": 28048640599,
    "plugin": "janus.plugin.streaming",
    "plugin_specific": {
        "state": "watching",
        "mountpoint_id": 1,
        "mountpoint_name": "gst-rpwc",
        "destroyed": 0
    },
    "flags": {
        "got-offer": 1,
        "got-answer": 1,
        "processing-offer": 0,
        "starting": 1,
        "ready": 0,
        "stopped": 0,
        "alert": 0,
        "bundle": 1,
        "rtcp-mux": 1,
        "trickle": 1,
        "all-trickles": 1,
        "trickle-synced": 0,
        "data-channels": 0,
        "has-audio": 0,
        "has-video": 1,
        "plan-b": 0,
        "cleaning": 0
    },
    "agent-created": 27969313789,
    "ice-mode": "full",
    "ice-role": "controlling",
    "sdps": {
        "profile": "RTP/SAVPF",
        "local": "v=0\r\no=- 1461741145906532 1461741145906532 IN IP4 raspberry pi ip\r\ns=Streaming Test\r\nt=0 0\r\na=group:BUNDLE video\r\na=msid-semantic: WMS janus\r\nm=video 1 RTP/SAVPF 96\r\nc=IN IP4 raspberry pi ip\r\na=mid:video\r\na=sendonly\r\na=rtcp-mux\r\na=ice-ufrag:MVVL\r\na=ice-pwd:AH1PvZw88QqJObTEYadokh\r\na=ice-options:trickle\r\na=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38\r\na=setup:actpass\r\na=connection:new\r\na=rtpmap:96 H264/90000\r\na=fmtp:96 profile-level-id=42e028;packetization-mode=1\r\na=rtcp-fb:96 nack\r\na=rtcp-fb:96 goog-remb\r\na=ssrc:1466294377 cname:janusvideo\r\na=ssrc:1466294377 msid:janus janusv0\r\na=ssrc:1466294377 mslabel:janus\r\na=ssrc:1466294377 label:janusv0\r\na=candidate:1 1 udp 2013266431 192.168.1.109 53445 typ host\r\na=candidate:2 1 udp 1677721855 raspberry pi ip 53445 typ srflx raddr 192.168.1.109 rport 53445\r\na=candidate:1 2 udp 2013266430 192.168.1.109 53226 typ host\r\na=candidate:2 2 udp 1677721854 raspberry pi ip 53226 typ srflx raddr 192.168.1.109 rport 53226\r\n",
        "remote": "v=0\r\no=mozilla...THIS_IS_SDPARTA-43.0.1 6437285156945315013 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=fingerprint:sha-256 CC:29:2E:4E:0D:57:FB:1D:19:2F:D6:54:2A:43:2A:BF:13:ED:E2:AC:5B:10:49:87:14:DA:CB:48:60:AB:73:C3\r\na=group:BUNDLE video\r\na=ice-options:trickle\r\na=msid-semantic:WMS *\r\nm=video 9 RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=recvonly\r\na=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1\r\na=ice-pwd:469ac2b10737194c146803fa0f7d8bda\r\na=ice-ufrag:831ae9bf\r\na=mid:video\r\na=rtcp-fb:96 nack\r\na=rtcp-mux\r\na=rtpmap:96 H264/90000\r\na=setup:active\r\na=ssrc:1481871470 cname:{6a2268f7-2c7e-4e8b-8a29-286b6674e089}\r\n"
    },
    "streams": [
        {
            "id": 1,
            "ready": -1,
            "disabled": "false",
            "ssrc": {
                "video": 1466294377,
                "video-peer": 1481871470
            },
            "components": [
                {
                    "id": 1,
                    "state": "failed",
                    "local-candidates": [
                        "1 1 udp 2013266431 192.168.1.109 53445 typ host\r\n",
                        "2 1 udp 1677721855 raspberry pi ip 53445 typ srflx raddr 192.168.1.109 rport 53445\r\n"
                    ],
                    "remote-candidates": [
                        "0 1 UDP 2122121471 10.100.82.52 62686 typ host",
                        "4 1 UDP 2122252543 192.168.52.1 62687 typ host",
                        "8 1 UDP 2122187007 192.168.85.1 62688 typ host",
                        "1 1 UDP 1685921791 client ip 1814 typ srflx raddr 10.100.82.52 rport 62686"
                    ],
                    "dtls": {},
                    "in_stats": {},
                    "out_stats": {}
                }
            ]
        }
    ]
}

**Comment by lminiero** [comment]
Please DON'T paste huge bunches of text in the message: as explained in CONTRIBUTING.md, use services like pastebin or gist for the purpose. Besides, this belongs to the meetecho-janus group (where I see you've already posted), github is only for issues, so closing here.
