### ISSUE TITLE
handle.getBitrate() (from janus.attach success callback) always returns "0 kbits/sec"

### ISSUE THREAD

**Issue by leonklingele** [meetecho/janus-gateway#512]
You get a `handle` passed as a parameter to the janus.attach success callback.
`handle.getBitrate()` / `handle.webrtcStuff.bitrate.value` always returns "0 kbits/sec".

`handle.webrtcStuff.bitrate` yields:
```
Object {
  bsbefore: null,
  bsnow: null,
  timer: 35,
  tsbefore: null,
  tsnow: null,
  value: "0 kbits/sec"
}
```
Tested in latest Chrome, Chromium and Firefox.

**Comment by lminiero** [comment]
Last time I checked it was definitely working for me, I'l have to try again. Anyway, it also depends on what handle you're calling it on. On a sendonly PeerConnection, for instance, it would indeed always return 0, as there would be no incoming data.

**Comment by lminiero** [comment]
PS: getBitrate() will of course only do something _after_ you negotiated a PeerConnection: creating a handle is not enough.

**Comment by lminiero** [comment]
Just tested with Chrome 51, Firefox 46 and Firefox 49 and it works as expected, so closing as apparently not an issue. Feel free to reopen if you can provide more data to replicate the problem.
