### ISSUE TITLE
Error when share screen with Firefox

### ISSUE THREAD

**Issue by magarcia** [meetecho/janus-gateway#513]
When I use `janus.plugin.videoroom` with janus.js to share screen with Firefox, I receive an error:
```javascript
MediaStreamError {
  name: "NotFoundError",
  message: "The object can not be found here.",
  constraint: "",
  stack: ""
}
```

After some investigation I found that my Firefox (45.0.1) don't support `mediaSource: 'window'`. When I execute `navigator.mediaDevices.getUserMedia({video: {mediaSource: 'window'}})` I get the same error, but `navigator.mediaDevices.getUserMedia({video: {mediaSource: 'screen'}})` works perfectly.

I have no idea where the error comes from. My current setup is:
- **OS**: Arch Linux
- **Browser**: Firefox 45.0.1
- **Window Manager**: bspwm (Tiling Window Manager) _<- I suspect this is the cause_

Wherever the error comes, janus.js should be able to deal with this error, trying share `screen` when share `window` fails.

**Comment by lminiero** [comment]
Fixed in #518, thanks for bringing the issue up!
