### ISSUE TITLE
cant create a room with a specific id

### ISSUE THREAD

**Issue by awsmsrc** [meetecho/janus-gateway#52]
or dont know how

**Comment by akbarattar3** [comment]
I am not able to create the room using random integer.
This is my request :
{"janus":"create","message":{"request":"create","room":12345678,"is_private":false},"transaction":"R6reH33TsA1k"}
Response is :
onMessage{
       "janus": "success",
       "transaction": "R6reH33TsA1k",
       "data": {
          "id": 7336440816591461
       }
    }
But the video room is not created throwing following error when try to join on that room id
onMessage{
       "janus": "event",
       "session_id": 657810914978082,
       "transaction": "CdkYL0z38gsw",
       "sender": 2082074529278489,
       "plugindata": {
          "plugin": "janus.plugin.videoroom",
          "data": {
             "videoroom": "event",
             "error_code": 426,
             "error": "No such room (12345678)"
          }
       }
    }

**Comment by shehinfn** [comment]
why i am not 

> I am not able to create the room using random integer.
> This is my request :
> {"janus":"create","message":{"request":"create","room":12345678,"is_private":false},"transaction":"R6reH33TsA1k"}
> Response is :
> onMessage{
> "janus": "success",
> "transaction": "R6reH33TsA1k",
> "data": {
> "id": 7336440816591461
> }
> }
> But the video room is not created throwing following error when try to join on that room id
> onMessage{
> "janus": "event",
> "session_id": 657810914978082,
> "transaction": "CdkYL0z38gsw",
> "sender": 2082074529278489,
> "plugindata": {
> "plugin": "janus.plugin.videoroom",
> "data": {
> "videoroom": "event",
> "error_code": 426,
> "error": "No such room (12345678)"
> }
> }
> }

getting same error

**Comment by tostra** [comment]
If I do not reset the WS (`Janus.sessions[s].destroy({unload: true, notifyDestroyed: false});`) the "join"(code below) will not work the next time (rooms exist but can't join, says "No such room"), Probably need to reset something or it is a Janus bug, why do I need to reset the web-socket every time I want to join a room: 
```

 var create = {
			request: "create",
			room: myroom,
			ptype: "publisher",
			publishers: pub,
			pin: xxx
		};

		sfutest.send({ message: create, success: function(result) {
					var register = {
			request: "join",
			room: myroom,
			ptype: "publisher",
			pin: xxx		};
				sfutest.send({ message: register });

	} });`
