### ISSUE TITLE
h264 with AAC

### ISSUE THREAD

**Issue by jalowin** [meetecho/janus-gateway#520]
Hi everybody:
I am trying encode from ffmpeg to janus, with only video my ffmpeg is ok but if I encode video and audio not play

This is my config

[h264-sample]
type = rtp
id = 1
description = H.264 live stream coming from gstreamer
audio = yes
video = yes
videoport = 5008
videopt = 126
videortpmap = H264/90000
videofmtp = profile-level-id=42e01f\;packetization-mode=1
videobufferkf = no
audioport = 5010
audiopt = 97
audiortpmap = MPEG4-GENERIC/48000/2
audiofmtp = profile-level-id=1;mode=AAC-hbr

And this is my command line for ffmpeg

ffmpeg -re -i video.mp4 -f rtp -fflags nobuffer -g 1 -c:v nvenc_h264 -s 640x360 -aspect 16:9 -pix_fmt yuv420p -preset llhp -b:v 600k -maxrate 600k -minrate 600k -delay 0 -movflags faststart -fflags nobuffer -an udp://127.0.0.1:5008 -f rtp -vn -flags +global_header -c:a libfdk_aac -profile:a aac_he -eld_sbr 1 -ar 48000 -ab 64k -ac 2 udp://127.0.0.1:5010

Wich are the config for aac codec in janus?

Thanks for all

Best regards

**Comment by lminiero** [comment]
Please post on the meetecho-janus group and close this, github is only for
issues. That said, I don't think WebRTC browsers support aac, so you
probably can't do that anyway.
Il 12/mag/2016 11:20, "jalowin" <notifications@github.com> ha scritto:
