### ISSUE TITLE
config Janus run on https / chrome 

### ISSUE THREAD

**Issue by nhtdata** [meetecho/janus-gateway#527]
Dear Admin / Leader 
need support config DEMO Janus run on https and chrome
WebRTC error... {"name":"PermissionDeniedError","message":"Only secure origins are allowed (see: https://goo.gl/Y0ZkNV)."}

HTTP webserver started (port 8088, /janus path listener)...
HTTPS webserver started (port 8889, /janus path listener)...

**Comment by lminiero** [comment]
Please use the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) group for questions like this, github is only for code issues. The error you got means you tried to do WebRTC on an HTTP (not HTTPS) web page. HTTP is only allowed for localhost.
