### ISSUE TITLE
How does media transport to client side when NAT hole punching failed

### ISSUE THREAD

**Issue by idreamerhx** [meetecho/janus-gateway#529]
Hi, thanks for your great project first.  I setup janus in my raspberry pi 2 at home. The network at home is Symmetric NAT. I use vpn between the PI and a public vps server (which has a public ip). I have tried my own turnserver and several public stun/turn servers. The signaling between webpage and janus server is ok, but media data can not transport.

I see firefox about:webrtc  all candidates ip:port failed.
The question is how should I do to make media data transport by a relay server?

btw, I tried linphone, it's media relayed by linphone's server.
If I setup vpn connection to make PI and web client in a local net, the p2p (which use a local ip) is ok.

thanks^^

**Comment by lminiero** [comment]
Please post this on our [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) group, github is only for code issues.
