### ISSUE TITLE
Formalized Freeswitch plugin

### ISSUE THREAD

**Issue by astro44** [meetecho/janus-gateway#537]
I noticed that there would be some dev work in adding some high level API's customized for plugins.... any chance **Freeswitch** will be added to the mix? Some best practices would be useful also....  We're starting to look further into Janus and we're heavily vested in Freeswitch/Kamailio(as SBC), so anything would make it even easier for us to adopt Janus.

**Comment by lminiero** [comment]
Please ask this question on our [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) group, as we only use github for issues.
