### ISSUE TITLE
Click to call 

### ISSUE THREAD

**Issue by Cristianoiai** [meetecho/janus-gateway#539]
It is possible to connect a SIP User to url using Janus, or prefixing the SIP settings so that the User click on start and then call, called a fixed number?

START>>>>>CALL>>>>>called a fixed number

**Comment by saghul** [comment]
Yes, of course. But you'll have to write that code yourself. GitHub is for issues, for other questions please use the mailing list.

**Comment by lminiero** [comment]
Closing!
