### ISSUE TITLE
json_pack would make JSON object creation more compact and readable

### ISSUE THREAD

**Issue by andreasg123** [meetecho/janus-gateway#540]
[json_pack](http://jansson.readthedocs.io/en/2.5/apiref.html#json_pack) offers compact object creation.  Before:

```
json_t *event = json_object();
json_object_set_new(event, "videoroom", json_string("event"));
json_object_set_new(event, "room", json_integer(participant->room->room_id));
json_object_set_new(event, "leaving", json_integer(participant->user_id));
```

After:

```
json_t *event = json_pack("{sssisi}, "videoroom", "event", "room", participant->room->room_id, "leaving", participant->user_id);
```

It would be nice if JSON object creation could use `json_pack` where appropriate.

**Comment by lminiero** [comment]
That may be just me, but I actually find it less readable! :stuck_out_tongue_winking_eye: 
Anyway, I didn't know about it and it looks like a cool feature we can have a look at for the future, assuming it doesn't break backwards compatibility for those with too old Jansson library versions.

**Comment by saghul** [comment]
For that little JSON object maybe, try the ones with an SDP inside!

It is, however a good idea to use this in production, to make the packets smaller. Maybe a compile time switch?

**Comment by lminiero** [comment]
Actually I don't think this makes the packets any smaller, right? AFAIU, it's just a different, more compact way of filling a json_t object. If size is an issue, you can make packets smaller by removing the `JSON_INDENT(3)` we have when getting a string out of that.

**Comment by saghul** [comment]
Well, spaces and newlines do count! Not a big issue though.

**Comment by lminiero** [comment]
It's a good idea, though. I might add a new configuration setting (e.g., prettyjson or something like that) that defines the number to have in `JSON_INDENT` (0 disables it), and/or involves `JSON_COMPACT` to push it even further.

**Comment by saghul** [comment]
👍

**Comment by andreasg123** [comment]
Yes, I like the idea of having a configuration setting to remove indentation.  Otherwise, I would be in favor of just removing the indentation because one can always look at the parsed JSON in the browser debugger.

Regarding the readability of `json_pack`, one can still define the object in multiple lines:

	json_t *event = json_pack("{sssisi},
		"videoroom", "event",
		"room", participant->room->room_id,
		"leaving", participant->user_id);

`json_pack` was added in [version 2.0](https://jansson.readthedocs.io/en/2.0/changes.html).

**Comment by lminiero** [comment]
Yep, I've been playing with this a bit (for a new PR I'll post I think tomorrow that should optimize core-to-plugin interaction), and it's quite cool. I think that's where I'll address the indentation part as well, as the only place where we'll have JSON stringification will be transport plugins.

**Comment by saghul** [comment]
Sweet, it was added so long ago even us using Debian stable can use it :-)

**Comment by ploxiln** [comment]
fwiw, I add a couple of minor patches to janus before I use it, and one of them removes the JSON_INDENT everywhere

**Comment by lminiero** [comment]
As anticipated, I created a PR on the effort I was mentioning yesterday. The "whether to indent or do compact" JSON stuff is not there yet, but will eventually be added to each of the transport: plugins: you'll be able to specify, for each transport, whether you want pretty JSON or a compact representation, as they'll be the only ones to actually serialize JSON data for use in the Janus and Admin API.

**Comment by lminiero** [comment]
Closing as we're already doing this in a few parts of the code, and the "compact" stuff has been integrated in the transport modules since then.
