### ISSUE TITLE
RTSP libcurl support

### ISSUE THREAD

**Issue by dirkdesmet** [meetecho/janus-gateway#541]
I'm trying to use a RTSP stream with Janus, but when starting the webRTC gateway I see this error:
`[ERR] [plugins/janus_streaming.c:janus_streaming_init:768] Can't add 'rtsp' stream 'camera', libcurl support not compiled...
`

How do I compile Janus with libcurl support?

**Comment by lminiero** [comment]
Install the libcurl development libraries, reconfigure Janus and make clean + make install again. Closing as not an issue: please use the group for questions like this, github is only for problems with the code.
