### ISSUE TITLE
Only works with active internet connection, even if devices are in the same local network

### ISSUE THREAD

**Issue by seirotis** [meetecho/janus-gateway#542]
Hi,

I've set up Janus in a VM (Vagrant with Virtualbox).
The example plugins (e.g. audiobridge) work fine from one browser tab to another on my laptop if the device is connected to Wi-Fi / the Internet.

However as soon as I disconnect the laptop from Wi-Fi, I'm no longer able to hear myself speaking.
I guess this is because the traffic is going through the Internet and does not remain in my local network.

As I'm really new into WebRTC: How can this debugged? Is it even supposed to work within the same network?
From what I understand, the Peer Connection should be established from my laptop to the local IP.

**Comment by ploxiln** [comment]
If you look at the browser's webrtc debug page, you may find that it connected to a port on your wifi adapter's public ip address, which is being used for NAT to provide internet access to the VM. When that ip address is lost, it stops working.

(Does your host machine have a virtual network device that connects directly to a virtual network device in the VM, or does the VM just have NAT through the virtualbox application on the host?)

**Comment by seirotis** [comment]
Yup, both browser tabs are P2P-connecting to my Internet router's public IP.
The VM uses NAT through the VB app.

My router's IP: 123.123.123.123
My laptop's IP: 192.168.1.10
The VM's IP: 10.0.2.15

Why does the Peer Connection from laptop to VM not go directly from 192.168.1.10 <-- to --> 10.0.2.15?
Isn't that what ICE is supposed to do?

**Comment by ploxiln** [comment]
10.0.2.15 is only visible inside the VM, the browser on the host has no route to that ip address. You could add another virtual adapter that does directly connect the host and vm (with a virtual adapter on the host side as well). In vagrant this is called a "private_network". Alternatively, you could use bridging instead of NAT to connect the vm to the network, so the vm gets a 192.168.1.X ip address just like your host does.

**Comment by seirotis** [comment]
I'm so sorry for any inconvenience.
Thank you for the quick VB / Vagrant tutorial. That solved the problem :-)
