### ISSUE TITLE
Janus crash after 'update' in recordplay

### ISSUE THREAD

**Issue by kalta** [meetecho/janus-gateway#551]
Hi,

After a successful create and attach to "janus.plugin.recordplay", if a 'update' request is sent, Janus crashes. Tested with last version from git and happens (to me at least) every time.

The relevant log is [here](http://pastebin.com/FuHERJdD).

Thank you!

**Comment by lminiero** [comment]
Please don't post huge bunches of text. As explained in the guidelines, use services like pastebin o gist for the purpose. That said, we also need a stacktrace.

**Comment by kalta** [comment]
I'm sorry, I really thought it was not so big. My fault.

I'll try to get the stacktrace. Janus runs inside a docker container and it is destroyed as soon as it crashes... Do you know where the stack trace should be generated, so that I can map that directory outside of docker?

**Comment by lminiero** [comment]
Sorry for this awfully late reply, my github notifications are not working correctly for some reason... core dumps are usually handled according to the OS core pattern, you should check what your `/proc/sys/kernel/core_pattern` contains.

**Comment by lminiero** [comment]
Any update?

**Comment by kalta** [comment]
I didn't have time to test it... I'll try to do it this week.
Thanks.

**Comment by kalta** [comment]
I'm sorry, I finally could get back to this and find the way to get the coredump.

To recap, if I copy file 1234.nfo to 4321.nfo (and change the name inside also) Janus core dumps while sending and 'update' request for "janus.plugin.recordplay".

[Here](http://pastebin.com/4QNd4rcS) is the core dump.
Thanks.

**Comment by lminiero** [comment]
That crash line ends [nowhere relevant](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_recordplay.c#L1575) on master. Please try again on an updated version of Janus.

**Comment by kalta** [comment]
OK, this [stacktrace](http://pastebin.com/1X1tBqCt) is from today's master (f88b08a).

**Comment by lminiero** [comment]
Works fine here, I can't replicate this. You may want to either launch Janus via valgrind and retry, or compile with libasan support (https://janus.conf.meetecho.com/docs/debug) to see if either spot a memory corruption issue happening in your case.

**Comment by lminiero** [comment]
Any news with valgrind or libasan on an updated Janus?

**Comment by lminiero** [comment]
Closing as we can't replicate. Feel free to reopen if you can provide more details.
