### ISSUE TITLE
Add package.json / NPM Package

### ISSUE THREAD

**Issue by medialwerk** [meetecho/janus-gateway#552]
Hello,
we want to use the janus-gateway js lib with webpack and npm. Is it possible to add a package.json and (optional) publish it to npm?

Thanks! :-)

**Comment by lminiero** [comment]
We have no plans to do that in the near future. Have you checked this other project instead? https://github.com/ndarilek/node-janus

**Comment by medialwerk** [comment]
Thanks for your fast answer. It seems that this project is a node adapter to the webrtc gateway. We only need the js library for the browser. Within your repository there is already a bower.json. But not every build system uses bower. We use the npm package manager also for the client and webpack gets the js files for our client side bundle. I could fork your repository and add a package.json, so we can install it with npm and get the janus.js with webpack out of the node_modules folder. But at first i wanted to ask if you want to add this to your repo.

**Comment by medialwerk** [comment]
I also can make a pull request with the package.json, if you want it within your lib.

**Comment by lminiero** [comment]
This is one of the reasons why I didn't even want the bower file in the first place... so many frameworks and everybody uses a different one! :smile:

The bower file you see was not made by us, it was a contribution made by an user. I'm not even sure it's still up-do-date, as I never used the thing.

If all that is needed is a lightweight packake.json file, a PR would be welcome! Unless it means mantaining it somehow? What could trigger such a change?

**Comment by medialwerk** [comment]
Yes i really can unserstand that, and if your team has to take care of these "files" in the future... I think its very lightweight and it only points to the janus.js file. So only if the path to the client-side lib changes, the path has to be adapted. I wouldn't publish it on npm, only add that file. With the package.json it's possible then to install the janus.js with npm if you use the official github url and for example the release tag.

**Comment by lminiero** [comment]
Makes sense, and thanks for the clarification! If you could prepare that file and issue a PR for that I'll definitely add it to the repo.

Thanks!

**Comment by saghul** [comment]
> Thanks for your fast answer. It seems that this project is a node adapter to the webrtc gateway. We only need the js library for the browser.

The library works with browserify AFAIS.

**Comment by medialwerk** [comment]
Ah okay, but as i know with browserify you also have the library installed with npm, and this is not possible without a package.json. There are libraries which enable that you can require bower modules also with webpack and browserify. But i do not see the need of bower, if browserify and webpack can handle npm modules directly. (The funny thing is, that bower has to be installed with npm)

**Comment by medialwerk** [comment]
I have made a pull request with a package.json: https://github.com/meetecho/janus-gateway/pull/553

**Comment by saghul** [comment]
I meant that node-janus works with browserify. So you can use that one directly in your app.

**Comment by njam** [comment]
fyi we're working on a JS client that should work in Node.js and the browser.
Still work in progress!
https://github.com/cargomedia/janus-gateway-js

cc @vogdb @tomaszdurka

**Comment by saghul** [comment]
@njam fantastic! Thanks for sharing!

**Comment by medialwerk** [comment]
> I meant that node-janus works with browserify. So you can use that one directly in your app.

Ah ok thanks, then it would work with webpack too i guess. I didn't know that this is a janus webrtc client. The question I ask myself is if there is the need for many js clients (for node or not node). I would prefer one js client library which is not dependent on node or on a browser. Like the one from @njam. It would be nice to have a "official" client side module in the future. Thanks!

**Comment by lminiero** [comment]
@njam really interesting effort, thanks for sharing! Let me know if you want me to add this to the [resources](https://janus.conf.meetecho.com/docs/resources) docs page, and if you have other stuff you'd like to see there as well (I think there only are janus-gateway-rtpbroadcast and janus-gateway-ruby now).

**Comment by lminiero** [comment]
Closing as the PR was merged.
