### ISSUE TITLE
Example for ffmpeg publishing VP8

### ISSUE THREAD

**Issue by alexcroox** [meetecho/janus-gateway#554]
I'm aiming for VP8 video streaming since H.264 support hasn't dropped in Chrome yet.

My config is

```
[gst-rpwc]
type = rtp
id = 1
description = Test Stream
audio = no
video = yes
videoport = 8004
videopt = 96
videortpmap = VP8/90000
videofmtp = profile-level-id=42e028\;packetization-mode=1
```

I'm testing initially on OSX with the built in webcam. This is the pipeline 

`ffmpeg -f qtkit -video_device_index 0 -i "" -video_size 640x480 -f mpeg1video -b:v 800k -r 30`

I'm just not sure how to pipe that to my Janus Gateway server! Do I _have_ to use gstreamer?

Edit: I tried `ffmpeg -f qtkit -video_device_index 0 -i "" -video_size 640x480 -f mpeg1video -b:v 800k -r 30 http://x.x.x.x:8004` but I got connection refused.

**Comment by lminiero** [comment]
Please post questions like this on our meetecho-janus group. Github is only for code issues.

**Comment by alexcroox** [comment]
Apologies, moved to [stackoverflow](http://stackoverflow.com/questions/37590331/ffmpeg-publishing-vp8-to-janus-gateway)

**Comment by lminiero** [comment]
I actually meant our [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) Google group...

**Comment by alexcroox** [comment]
Ah my membership was approved, I'd applied to a Google Group in the past and it took over a week to be able to post which is why I opted for SO in the mean time. Sorry about that...
