### ISSUE TITLE
Audiobridge plugin: What causes the big delay / lag / latency?

### ISSUE THREAD

**Issue by seirotis** [meetecho/janus-gateway#555]
Hi,

I've tested the audiobridge and echo plugin both on the janus website and in a local installation on my PC.
There is a noticeable delay when using the audiobridge plugin, even if I connect from one browser tab to another on the same machine.
What is causing this delay and how to reduce it?

The echo plugin has no noticeable delay.

I've tested some other peer-to-peer WebRTC solutions from one browser tab to another, and I didn't notice any delays there. :/

**Comment by lminiero** [comment]
Sorry, I completely missed this issue for some reason... some inherent delay is to be taken into account, when using the AudioBridge, as it does not simply relay stuff around, and is definitely not peer-to-peer. As explained in the docs, it is an audio mixer, and so for each participant it decodes data, adds it to an internal mixer, and then returns a full mix including the other participants. Some buffering is also involved to try and make sure audio is reasonably good even in case of jitter.

That said, it really depends on what you mean by "noticeable".

**Comment by lminiero** [comment]
Any update?

**Comment by joshdickson40** [comment]
This can probably be closed as any minor lag is normal given what the plugin does (i.e. not p2p).

**Comment by lminiero** [comment]
Closing then, in case of more details this can be reopened.
