### ISSUE TITLE
No tag for v0.1.1

### ISSUE THREAD

**Issue by maxhawkins** [meetecho/janus-gateway#556]
Could you add a git tag for the v0.1.1 commit? I'd like to point to that version in one of my build scripts that uses the new record API.

**Comment by lminiero** [comment]
We don't tag versions until they're completed, or otherwise people might think it's definitive while it's not. The v0.1.1 is the version we're currently contributing to. When a 0.1.2 or 0.2.0 comes out we'll tag v.0.1.1.

If you want to refer to a specific revision, just use the commit hash.
