### ISSUE TITLE
segfault in janus_plugin_push_event

### ISSUE THREAD

**Issue by maxhawkins** [meetecho/janus-gateway#557]
I get this segfault when I repeatedly create and destroy sessions attached to my plugin, which is based on janus_videocall. It crashes consistently after about ten times connecting and disconnecting.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000044af2b in janus_flags_is_set (flags=flags@entry=0xe98, flag=flag@entry=8) at utils.c:92
92  utils.c: No such file or directory.
[Current thread is 1 (Thread 0x7fc3bb7fe700 (LWP 20))]
(gdb) bt
#0  0x000000000044af2b in janus_flags_is_set (flags=flags@entry=0xe98, flag=flag@entry=8) at utils.c:92
#1  0x000000000043dbec in janus_plugin_push_event (plugin_session=0x7fc3ac02c260, plugin=0x7fc3c21072e0 <janus_myplugin_plugin>, transaction=0x0, 
    message=0x7fc3ac0324e0 "{\n   \"myplugin\": \"event\",\n   \"result\": {\n      \"event\": \"hangup\",\n      \"call_id\": \"448b2d45-4594-492f-be07-044790ad4b55\",\n      \"reason\": \"Remote hangup\"\n   }\n}", sdp_type=0x0, sdp=0x0) at janus.c:2501
#2  0x00007fc3c1f013f5 in janus_myplugin_hangup_media (handle=0x7fc3ac05c810) at libjanus_myplugin.c:508
```

The equivalent line to libjanus_myplugin.c:508 in janus_videocall is this one, where the leaving user is notifying its peer of its departure:
https://github.com/meetecho/janus-gateway/blob/f9bc3076d19542533598049c37d71479192d1dfb/plugins/janus_videocall.c#L1247

The segfault occurs because `peer->handle->gateway_handle` refers to memory which has already been freed.

The revision I'm using is f9bc3076d19542533598049c37d71479192d1dfb. Let me know if you need any more information!

**Comment by lminiero** [comment]
Try compiling with libasan support, as explained [here](https://janus.conf.meetecho.com/docs/debug), which should help spot heap memory errors and thing like that.

**Comment by lminiero** [comment]
Any update?

**Comment by maxhawkins** [comment]
Sorry, I got pulled off onto another project. I'll run with asan and get back to you in a few weeks.

**Comment by lminiero** [comment]
Too much has changed in the code since last summer for this to be relevant now. Closing for now, feel free to reopen if still an issue.
