### ISSUE TITLE
Support strings as room_id at the janus audiobridge plugin

### ISSUE THREAD

**Issue by medialwerk** [meetecho/janus-gateway#559]
Hello,
we finally integrated the janus webrtc gateway in our project, thanks again for your support. But we have a tricky issue with our room_ids, because we want to map a uuid to a janus room_id. Our first approach was to convert the uuids (hex) to an int, but this results in a very long int with a bigger range as a guint64 type supports (the datatype for the room_id variable). Normally uuids are stored as a string. With the guint64 datatype its not possible for us to create unique rooms if we don't want to implement a more complicated mapping service. Is it possible to add string support for the room id?

**Comment by lminiero** [comment]
That's not planned, sorry. The easiest way to do that is to use an out of band mechanism to associate your string IDs to Janus room IDs instead.

**Comment by kalta** [comment]
Hi.
We had a similar problem. Our solution has been to use a hash function that generates an integer over the UUID (in our case, erlang:phash2), and store the UUID as room's name.
