### ISSUE TITLE
HTTP transport: ACL does not work, if no interface/IP specified 

### ISSUE THREAD

**Issue by uxmaster** [meetecho/janus-gateway#564]
If no interface/IP is specified for binding, IP address (https://github.com/meetecho/janus-gateway/blob/master/transports/janus_http.c#L977) is always 0.0.0.0, which renders ACL unusable.
I have checked it with libmicrohttpd 0.9.33 (Ubuntu 14.04.4) and 0.9.50 (the newest).

This regression is caused by https://github.com/meetecho/janus-gateway/commit/55280d5221ce46b49abcc3aba6cfcec9a85644e0, when I backed it out, everything returned to normal.

**Comment by lminiero** [comment]
I don't see why `MHD_USE_DUAL_STACK` should pollute the client address (because ACL is for the address of the client, not the server's). Maybe a bug in the library?

**Comment by lminiero** [comment]
Found out the cause of the issue: when you pass `MHD_USE_DUAL_STACK`, the addresses that are passed to that method are always IPv6, no matter the source. Since our callback assumes it's a `sockaddr_in`, the resolution of the address gives `0.0.0.0`. I'll try and fix the check there.
