### ISSUE TITLE
HTTP transport: 'MHD_create_response_from_data' is deprecated

### ISSUE THREAD

**Issue by uxmaster** [meetecho/janus-gateway#565]
I get the following warning, when building with libmicrohttpd 0.9.50:

    transports/janus_http.c: In function 'janus_http_handler':
    transports/janus_http.c:1050:3: warning: 'MHD_create_response_from_data' is deprecated (declared at /opt/janus/include/microhttpd.h:2068) [-Wdeprecated-declarations]
    response = MHD_create_response_from_data(0, NULL, MHD_NO, MHD_NO);

**Comment by lminiero** [comment]
Does it still work, though? Or is this causing undefined references and/or broken HTTP support?

**Comment by lminiero** [comment]
Found out about `MHD_create_response_from_buffer`, which also has modes like `MHD_RESPMEM_MUST_FREE` to automatically free the buffers when done (something we currently do on our own). Not sure if it's available on older versions of the library, though, and if I'll have to add yet another layer of old API vs. new API as we already do for libwebsockets...

**Comment by lminiero** [comment]
Looks like it has been around long enough (since 0.9.5), so I'll just replace the method.
