### ISSUE TITLE
Streaming plugin. 'filename' param for 'create' action.

### ISSUE THREAD

**Issue by vogdb** [meetecho/janus-gateway#566]
Hi! According to plugin's docs https://janus.conf.meetecho.com/docs/janus__streaming_8c.html#details the parameter for the local file of 'create' is called `filename` but according to the sources it's called `file` https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L1268. When I tried to test `filename`, it silently killed the janus process. `file` worked fine.

**Comment by lminiero** [comment]
By "silently killed" you mean Janus crashed? That should'nt happen. We'll fix the docs, thanks for spottinh this.

**Comment by vogdb** [comment]
> By "silently killed" you mean Janus crashed?

yes!

**Comment by lminiero** [comment]
Thanks, I'll look into it.

As a side note, we don't have any API info in the Streaming docs. The `filename` you see there is for the configuration file, and it's indeed called `filename` there, so it's not wrong. I'll change the name of the attribute in the API to match that of the configuration, so from the next commit it will be `filename` and not `file` there as well.

**Comment by lminiero** [comment]
Fixed in https://github.com/meetecho/janus-gateway/commit/bee1cb3495c8cbc8af49c3c20206760ad1247753
