### ISSUE TITLE
Problem with TURN server

### ISSUE THREAD

**Issue by gergelyhegykozi** [meetecho/janus-gateway#57]
Hi developers!

I have started to test Janus and I came across some problems.

1.: Chrome: I added STUN and TURN servers to iceServers. Sometimes it works sometimes not. If I test just the TURN or just the STUN server then it has no problem.
2.: Firefox: Somehow it can't handle TURN server even if I set stun server before ( so if I set TURN server then Firefox will be ruined )

I use simple http protocol.

All what I noticed in log:

```
[ERR] [ice.c:janus_ice_cb_nice_recv:632:] [4142278257]     Missing valid SRTP session, skipping...
[4142278257] The DTLS handshake has been completed
WebRTC media is now available
[ERR] [ice.c:janus_ice_cb_nice_recv:632:] [1863047056]     Missing valid SRTP session, skipping...
[1373465566] There's a message for JANUS VideoRoom plugin
[1373465566] Done! Sending connectivity checks...
[ERR] [ice.c:janus_ice_relay_rtcp:1259:] [1863047056]     video stream (#1) component has no valid SRTP session (yet?)
No more remote candidates for handle 1373465566!
[ERR] [ice.c:janus_ice_cb_nice_recv:604:] Still waiting for the DTLS stack for component 1 in stream 2...
[ERR] [ice.c:janus_ice_cb_nice_recv:632:] [1373465566]     Missing valid SRTP session, skipping...
[1373465566] The DTLS handshake has been completed
WebRTC media is now available
[ERR] [ice.c:janus_ice_cb_nice_recv:604:] Still waiting for the DTLS stack for component 1 in stream 2...
[ERR] [ice.c:janus_ice_cb_nice_recv:637:] [1373465566]     SRTP unprotect error: err_status_auth_fail (len=32-->32)
[ERR] [ice.c:janus_ice_cb_nice_recv:632:] [1373465566]     Missing valid SRTP session, skipping...
[1863047056] The DTLS handshake has been completed
WebRTC media is now available
[ERR] [ice.c:janus_ice_relay_rtp:1202:] [1373465566]     video stream component has no valid SRTP session (yet?)
[ERR] [ice.c:janus_ice_cb_nice_recv:637:] [1863047056]     SRTP unprotect error: err_status_replay_fail (len=1007-->1007)
[ERR] [ice.c:janus_ice_cb_nice_recv:637:] [1863047056]     SRTP unprotect error: err_status_replay_fail (len=1006-->1006)
```

What should I check or change?

Thank you in advance!
Gergely

**Comment by mejiamariano** [comment]
Hi! @lminiero , we're still experiencing this kind of issue of @leonuh with our prototype of videoroom plugin. We think that we need to verify whether our handshake to TURN servers are good and realistic to  upload / download stream. 

I hope you had a great idea on this part.

**Comment by lminiero** [comment]
You should look into the admin API, especially the affected handles. There's a quick tutorial [here](www.meetecho.com/blog/understanding-the-janus-admin-api/) on where to look and what to look for.

**Comment by mejiamariano** [comment]
@lminiero, what is the case if no in/out stats but the state was connected? I found in your tutorial that if the peerConnection was broken there's no in/out stats. While on the said article it tells to be "disconnected".

**Comment by lminiero** [comment]
The tutorial explains that the cause can be either ICE failing (not your case apparently) or DTLS failing. If the dtls section of the admin API info is empty or reports an error, then the DTLS handshake was either not started, not completed or simply failed.

**Comment by smendez-hi** [comment]
@lminiero About this: "then the DTLS handshake was either not started, not completed or simply failed". I'm having this problem and i don't know what to do next. State is ready, i have local and remote candidates with both public and private addresses, but `dtls`, `in_stats` and `out_stats` are empty. What should i try?
