### ISSUE TITLE
RFC 4235 support in sip plugin for BLF notifications

### ISSUE THREAD

**Issue by krull** [meetecho/janus-gateway#572]
Hello!

Outstanding work on janus! We're creating our first webRTC app with janus as our backend!

We were wondering if there are plans for RFC 4235 support in the future so that Call Info and BLF notifications are available on the client-side endpoints. You see our Javascript cannot see anything being sent through janus regarding this feature even though we have facilitated the feature on the JS side.

Thanks!

**Comment by lminiero** [comment]
No plan, sorry. But PR are always welcome :wink: 
In the future we may work on a plugin that keeps SIP on the JavaScript side (so no SIP within Janus itself), but no idea on when we'll work on this.

**Comment by krull** [comment]
Hi. Thanks for the reply, @lminiero 

Since janus sip plugin is open, we can effectively implement RFC support. We'll see what we can do here and issue a pull requests once done. Thanks again.

**Comment by Si-Richards** [comment]
> Hi. Thanks for the reply, @lminiero
> 
> Since janus sip plugin is open, we can effectively implement RFC support. We'll see what we can do here and issue a pull requests once done. Thanks again.

Was this ever implemented ?

**Comment by lminiero** [comment]
No, but if this works using subscribe/notify, we did implement a generic mechanism for that.
