### ISSUE TITLE
crash when connection stoping.

### ISSUE THREAD

**Issue by ericoyf** [meetecho/janus-gateway#576]
console log:
[root@bogon ~]# /opt/janus/bin/janus 
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Gateway) v0.1.1
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Using 192.168.19.143 as local IP...
[WARN] Token based authentication disabled
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, IPv6 support disabled)
[WARN] Janus is deployed on a private address (192.168.19.143) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
BUNDLE is NOT going to be forced
rtcp-mux is NOT going to be forced
ICE handles watchdog started
Fingerprint of our certificate: D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38
Plugins folder: /opt/janus/lib/janus/plugins
Loading plugin 'libjanus_streaming.so'...
JANUS Streaming plugin initialized!
Loading plugin 'libjanus_audiobridge.so'...
JANUS AudioBridge plugin initialized!
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
JANUS VideoRoom plugin initialized!
Streaming watchdog started
AudioBridge watchdog started
EchoTest watchdog started
VideoRoom watchdog started
Loading plugin 'libjanus_recordplay.so'...
JANUS Record&Play plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_sip.so'...
JANUS SIP plugin initialized!
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin initialized!
Transport plugins folder: /opt/janus/lib/janus/transports
Loading transport plugin 'libjanus_http.so'...
Record&Play watchdog started
VoiceMail watchdog started
SIP watchdog started
VideoCall watchdog started
HTTP webserver started (port 8088, /janus path listener)...
[WARN] HTTPS webserver disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
JANUS REST (HTTP/HTTPS) transport plugin initialized!
Loading transport plugin 'libjanus_pfunix.so'...
Configuring SOCK_SEQPACKET Unix Sockets server (Janus API)
[WARN] Unix Sockets server disabled (Admin API)
JANUS Unix Sockets transport plugin initialized!
Loading transport plugin 'libjanus_rabbitmq.so'...
HTTP/Janus sessions watchdog started
Unix Sockets thread started
[WARN] RabbitMQ support disabled (Janus API)
[WARN] RabbitMQ support disabled (Admin API)
[WARN] RabbitMQ support disabled for both Janus and Admin API, giving up
Loading transport plugin 'libjanus_websockets.so'...
libwebsockets >= 1.6 available, using new API
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
[WARN] Admin WebSockets server disabled
[WARN] Secure Admin WebSockets server disabled
JANUS WebSockets transport plugin initialized!
Sessions watchdog started
WebSocket (Janus API) thread started
Creating new session: 2071290063
Creating new handle in session 2071290063: 1477765196
[1477765196] Creating ICE agent (ICE Full mode, controlled)

(process:19478): GLib-GObject-WARNING **: g_object_new_valist: object class `NiceAgent' has no property named `reliable'
[1477765196] The DTLS handshake has been completed
WebRTC media is now available
No WebRTC media anymore
Detaching handle from JANUS EchoTest plugin
GLib (gthread-posix.c): Unexpected error from C library during 'pthread_mutex_lock': Invalid argument.  Aborting.

**Comment by ericoyf** [comment]
when i test, i open demo in browser and click button 'start'. After 5 seconds, click button 'stop', server will crash. thanks!

**Comment by lminiero** [comment]
Apparently you forgot to read the [guidelines](https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md) for opening new issues...

Anyway, you probably have a too old version of libnice installed.

**Comment by ericoyf** [comment]
i have installed libnice 0.1.4, and it's okay. thanks.
