### ISSUE TITLE
Video is a green rectangle (H.264), iOS, Ionic 2

### ISSUE THREAD

**Issue by bushev** [meetecho/janus-gateway#579]
I'm trying to get work Ionic 2 application on iOS. Stream comes from Raspberry pi (gStreamer + Janus WebRTC gateway)

Application is a streaming application with the following logic:

1. Create connection to RPi using Janus WebRTC gateway
2. Obtain stream and create video tag with src: `URL.createObjectURL(stream)`

I'm getting WebRTC support by the following plugin: https://github.com/eface2face/cordova-plugin-iosrtc

Streaming **works great** in FireFox browser by `ionic serve --platform=ios` command.

Streaming is **NOT works** inside iOS emulator and on a real device. I just got a green rectangle instead of stream, like on the picture above:

![7935075e-4d25-11e6-88ac-88124d9d2881](https://cloud.githubusercontent.com/assets/7535766/16933348/46ac6b76-4d55-11e6-8e6f-9ee89326db88.jpeg)

gStreamer command:

`raspivid --verbose --nopreview --width 640 --height 480 --framerate 15 --bitrate 1000000 --profile main --timeout 0 -o - |  gst-launch-1.0 -v fdsrc ! h264parse ! rtph264pay config-interval=1 pt=96 ! udpsink host=127.0.0.1 port=8004`

Janus config:

    [gst-rpwc]
    type = rtp
    id = 1
    description = RPWC H264 test streaming
    audio = no
    video = yes
    videoport = 8004
    videopt = 96
    videortpmap = H264/90000
    videofmtp = profile-level-id=4D401F\;packetization-mode=1

I have googled a similar problem (http://stackoverflow.com/questions/21120717/h-264-video-wont-play-on-ios). 

They say iOS safari support Main profile with AVC level 3.1. I'm tried this proposal but it doesn't help me too..

I'm also tried the following "pairs" (profile-level-id + profile) without success:

    "42e028 + baseline"  
    "640028 + hight"

No any errors in console. Traffic for the app is also OK (~100kbps). But I see green square instead of image..

**Comment by lminiero** [comment]
Not a bug, since other endpoints play the stream fine, so doesn't belong here. Please post on [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) instead.

**Comment by sezerkorkmaz** [comment]
any news?

**Comment by krishnaclouds** [comment]
Really any update on this?
