### ISSUE TITLE
Sofia error with SDP includes a data channel

### ISSUE THREAD

**Issue by kalta** [meetecho/janus-gateway#581]
Hello,

in the sip plugin, if the incoming webrtc request includes not only audio and video but also an m=application line, sofia fails with [this error](http://pastebin.com/wB5wND2W).

It is not very important, once you know the reason because Janus is hanging the call...

**Comment by saghul** [comment]
The SIP plugin does not support media types other than audio and video, I'm afraid.

**Comment by lminiero** [comment]
It looks like a failure in Sofia SIP, though, rather than the SIP plugin, which shouldn't happen... converting the plugin to use the new SDP approach in #578 might solve this.

**Comment by lminiero** [comment]
This commit adds a check: if datachannels are in the offer, it's rejected right away. This should solve the cryptic error you were getting before.
