### ISSUE TITLE
dtls alert error

### ISSUE THREAD

**Issue by mtdxc** [meetecho/janus-gateway#582]
I have test latest janus(f88b08a4d) with chrome 52, in this release h264 is useable, but I found a problem when publisher my video. 
in the chrome I found this error
janus:"hangup" reason:"DTLS alert" sender:5294568410369083 session_id:2483373267456921

and this is log in the janus server 
[ERR] [dtls.c:janus_dtls_srtp_incoming_msg:562] [5294568410369083] Handshake error: error:14102410:SSL routines:DTLS1_READ_BYTES:sslv3 alert handshake failure
[5294568410369083] WebRTC resources freed

it sounds like this is the reason(chrome 52's changelog)
ECDSA-based Certificate Generation
The Elliptic Curve Digital Signature Algorithm (ECDSA) is now used as default for generating RTCCertificates. For more details, head over to the Web Fundamentals article.

any help abount this?

**Comment by lminiero** [comment]
https://groups.google.com/forum/#!topic/meetecho-janus/1-u2rQM5dUo
