### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by mwager** [meetecho/janus-gateway#583]
Janus randomly crashes when sending a "join" request or while reloading the page (which means
Creating new session...)

(maybe related #457)

Logs: http://pastebin.com/uZvN6wqp
GDB trace: http://pastebin.com/UByGWvNE

The coredump was created at 8:39
root@0662acddb1e4:~/janus-gateway# ll /opt/janus/bin/core
-rw------- 1 root root 494546944 Jul 21 08:39 /opt/janus/bin/core

-> relates to: 2016-07-21T08:39:56.366303408Z  Segmentation fault (core dumped)

**Comment by lminiero** [comment]
Looks like the handle pointer over which the event was pushed was invalid for some reason. If you can replicate this easily, try compiling Janus with libasan support, as that may give more info on memory corruptions and things of that sort: https://janus.conf.meetecho.com/docs/debug

You may also want to try with the #403 branch to see if things improve, as we use reference counters there which make it much less likely to get into problems like this. The more people play with it and can provide feedback, the sooner we can merge it.

**Comment by mwager** [comment]
We tried the refcount branch with no success. We still vet lots of seg faults. Now I recompiled locally with libasan support, but no additional output on a crash. Am I doing something wrong? Where should the output be?

### Re-compile steps:
root@66fdb1a5fb1b:~/janus-gateway# CFLAGS="-fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-lasan" ./configure --prefix=/opt/janus --disable-rabbitmq
root@66fdb1a5fb1b:~/janus-gateway# make clean
root@66fdb1a5fb1b:~/janus-gateway# make
root@66fdb1a5fb1b:~/janus-gateway# make install


### Seems to work:
root@66fdb1a5fb1b:~/janus-gateway# ldd janus | grep asan
  libasan.so.0 => /usr/lib/x86_64-linux-gnu/libasan.so.0 (0x00007f6b205ee000)

root@66fdb1a5fb1b:/# ldd /opt/janus/bin/janus | grep asan
	libasan.so.0 => /usr/lib/x86_64-linux-gnu/libasan.so.0 (0x00007fefd26f8000)

Then I followed the logs again and triggered the crash like explained earlier in this issue:

http://pastebin.com/32yPzVD6

But there are no additional logs.

**Comment by lminiero** [comment]
Sorry, not an expert on AddressSanitizer and so I don't know what can cause it not to print out a dump of what broke things.

**Comment by ploxiln** [comment]
`LDFLAGS` needs to also have `-fsanitize=address`, it does more than just link libasan

If you set `ASAN_OPTIONS=help=1` in the environment for the augmented binary, it should give you a list of supported ASAN_OPTIONS. if you get nothing, you didn't manage to build with address sanitizer yet :)

**Comment by ploxiln** [comment]
fwiw I was not successful on ubuntu-14.04 last I tried to use address sanitizer for something else, but was successful with newer distros.

valgrind slows down the application considerably, but it's an easier to apply option, and if you do get lots of crashes it shouldn't be hard to get a few under valgrind reasonably quick.

**Comment by mwager** [comment]
@ploxiln thx, I now tried:


    CFLAGS="-fsanitize=address -fno-omit-frame-pointer" LDFLAGS="-lasan -fsanitize=address" ./configure --prefix=/opt/janus --disable-rabbitmq


So this time I did get output from sanitizer:

http://pastebin.com/NH503Whz



### OS info:

root@6afe56f35d68:~/janus-gateway# cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"
NAME="Ubuntu"
VERSION="14.04.4 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.4 LTS"
VERSION_ID="14.04"

**Comment by IvRRimum** [comment]
Any update about this?

**Comment by lminiero** [comment]
A lot has changed in the code in the meanwhile, is this still an issue?

**Comment by medialwerk** [comment]
We (mwager and i) had frozen the voip development until now because we were not able to release it within a reasonable period of time. These days I started my development with version v0.2.2 and the issue has not occured until now, so i think we can close this issue :-).

**Comment by lminiero** [comment]
Thanks for the update! Closing then.
