### ISSUE TITLE
error when exiting session

### ISSUE THREAD

**Issue by rlsharp** [meetecho/janus-gateway#590]
Recreate:
1. using chrome goto https://janus.conf.meetecho.com/
2. select echotest from dropdown (others have same problem but this is easiest to show)
3. hit start to start the demo
4. bring up javascript console (cntrl-shift-j)
5. select "Preserve log" so error message does not disappear
6. Go to any other website except back arrow (i.e. google.com)
7. In the log you will see an error message
I have looked in janus.c and jquerry which is called but not experienced enough with jquerry or ajax to determine the cause. Only problem from this (other then error message) is it seems (sometimes) for videocall the name used for registration is not cleaned up right away and can not be reused for a minute.

**Comment by lminiero** [comment]
Most likely not errors at all, but messages sent to a handle that has been destroyed in the meanwhile because the page is being closed (and we destroy the session in unbeforeunload). Closing the issue then, feel free to reopen if you can provide more info pointing to an actual issue.

**Comment by rlsharp** [comment]
The actual issue is the error messages. It is like the car's check engine
light - best not to ignore. :)
