### ISSUE TITLE
All seems to be okay except no stream display.

### ISSUE THREAD

**Issue by wyounglee** [meetecho/janus-gateway#599]
It seems to be okay, but there is no stream display on Chrome. 
Loading icon is shown forever. Is there any check point?

I'm using RTSP configuration and RTSP is from live555.
[rtsp-test]
type = rtsp
id = 99
description = RTSP Test
audio = no
video = yes
url=rtsp://admin:admin@192.168.0.13:554/Video-1

................................
HTTP/Janus sessions watchdog started
WebSocket (Janus API) thread started
[rtsp-test] New video stream! (ssrc=149098743)
Creating new session: 2425905053669295
Creating new handle in session 2425905053669295: 7406724725032148
[7406724725032148] Creating ICE agent (ICE Full mode, controlling)
[WARN] [7406724725032148] Still waiting for the DTLS stack for component 1 in stream 1...
[7406724725032148] The DTLS handshake has been completed
WebRTC media is now available

**Comment by lminiero** [comment]
Not a code issue, so doesn't belong here, as explained in [here](https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md). Write on [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
