### ISSUE TITLE
Gateway not working behind nat

### ISSUE THREAD

**Issue by warrenjmcdonald** [meetecho/janus-gateway#6]
If the gateway is behind NAT the STUN setting does not seem to be working as all of the returned SDP has the inside address of the server, not the outside of the NAT.

I have tried several know good STUN servers. I also ran tcpdump on the server and there were no requests out to the STUN server to get addresses. 

See SDP from Gateway below

v=0
o=- 5052254696594837720 3 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS janus
a=fingerprint:sha-256 C5:5F:DA:7D:84:47:B1:BF:6B:55:16:62:48:31:3E:D3:F1:7B:25:89:92:4A:4B:4D:4D:D9:D5:AF:EA:D8:15:44
m=audio 52898 RTP/SAVPF 111 103 104 0 8 106 105 13 126
c=IN IP4 10.0.0.204
a=sendrecv
a=rtcp:52291 IN IP4 10.0.0.204
a=ice-ufrag:gZ20
a=ice-pwd:Wka5ZcTc5hRM9eTNOw9CwD
a=setup:active
a=connection:new
a=mid:audio
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:12345 cname:janusaudio
a=ssrc:12345 msid:janus janusa0
a=ssrc:12345 mslabel:janus
a=ssrc:12345 label:janusa0
a=candidate:1 1 udp 2013266431 10.0.0.204 52898 typ host
a=candidate:1 2 udp 2013266430 10.0.0.204 52291 typ host
m=video 41486 RTP/SAVPF 100 116 117
c=IN IP4 10.0.0.204
a=sendrecv
a=rtcp:36645 IN IP4 10.0.0.204
a=ice-ufrag:Ys3N
a=ice-pwd:7G1PRxOrMBsghcvCi5A0t0
a=setup:active
a=connection:new
a=mid:video
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=ssrc:54321 cname:janusvideo
a=ssrc:54321 msid:janus janusv0
a=ssrc:54321 mslabel:janus
a=ssrc:54321 label:janusv0
a=candidate:2 1 udp 2013266431 10.0.0.204 41486 typ host
a=candidate:2 2 udp 2013266430 10.0.0.204 36645 typ host

**Comment by shrdlu68** [comment]
I am facing this issue with current master.
Behind NAT, Janus registers with the internal IP address rather than the external one.
This happens despite using a stun server `-S` or specifying the external address `-1`.

**Comment by lminiero** [comment]
@shrdlu68 please don't hijack old and closed issues, especially those from ages ago.
