### ISSUE TITLE
VideoRoom plugin error from rpi UV4L

### ISSUE THREAD

**Issue by cylwin** [meetecho/janus-gateway#600]
I need to stream from the RPI Camera to a Janus room with webrtc. I installed UV4L on my PI, and try the demo with the gateway url https://janus.conf.meetecho.com : it's work.

I installed janus-gateway on a server (demos here : https://janus.kizbat.com) And the gateway url is : janus.kizbat.com:8089

"Janus video room" work very well with browsers (chrome from my computer), 
but when I try to connect with uv4L on the pi I get this error on the janus log :

```
[3157879423705975] Creating ICE agent (ICE Full mode, controlled)
[WARN] [3157879423705975] Skipping disabled/unsupported media line...
[ERR] [ice.c:janus_ice_cb_component_state_changed:1473][3157879423705975] ICE failed for component 1 in stream 1...
No WebRTC media anymore
Detaching handle from JANUS VideoRoom plugin
No WebRTC media anymore
Cleaning up handle 3157879423705975...
```

I tried to setup a STUN/TURN server, but I get the same error.

Do you have an idea ?

**Comment by lminiero** [comment]
Not a code issue, closing. Please post on the meetecho-janus google group for questions like these.

**Comment by whb883** [comment]
@cylwin I have the same problem. Has the problem been solved?
