### ISSUE TITLE
Consider a slight name adjustment

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#604]
Hi there,

(This is 101% my personal opinion, so feel free to consider or discard it as such)

From [this article]() published today:

> Janus is… somewhat tougher to explain.
> 
> Their website states that it is a “general purpose WebRTC Gateway”. So in my mind it will mostly fit into the role of a WebRTC-SIP gateway.
> 
> That said, I’ve seen more than a single vendor using it in totally other ways – anything from an SFU to an IOT gateway.
> 
> I need to see more evidence of use cases where production services end up using it for multiparty as opposed to a gateway component to suggest it as a solid alternative.

I guess is that when you folks named it a "gateway" you were thinking about an "enabler" or "facilitator".  In the context of WebRTC, however, a gateway typically means the conversion to another protocol / standard / what have you.

My (humble) suggestion is that you consider adjusting that wording so people don't make the same mistake Tsahi made.  Janus is more than a gateway, is a WebRTC toolkit, a WebRTC (application) server, a WebRTC Swiss army knife, <- insert your own ->.

Not sure how invested you folks are in the full name, just thought I'd throw in my 2 cents :-)

**Comment by lminiero** [comment]
That's a good point, as we actually got this confused thoughts about the name from several folks... I'm personally not committed, so a change could definitely be taken into account!

**Comment by lminiero** [comment]
Calling for [suggestions](https://groups.google.com/forum/#!topic/meetecho-janus/r3f0_81mNR8)... :smile:

**Comment by lminiero** [comment]
Closing as we have it as a pinned discussion on the group.
