### ISSUE TITLE
Enhancement Request:  Add SIP leg to Audio Room (mixed) Plugin

### ISSUE THREAD

**Issue by shrhoads** [meetecho/janus-gateway#605]
It would be hugely useful to be able to combine the SIP plugin and the Audio Room Plugin.  I know it wouldn't be a core WebRTC feature, but it would allow someone who doesn't have a browser to join an audio conference.

**Comment by saghul** [comment]
I've been thinking about this recently too. Lorenzo, I think this could be achieved by chaining the SIP and Audio/Video Room plugins with our "Boring SDP" plugin.

**Comment by lminiero** [comment]
Many asked about this, but it's not something we plan to work on as part of our own activities on the existing plugins, as this feature can be quite easily achieved by leveraging an external SIP-based conference bridge (e.g., on Asterisk or Freeswitch). This is how we do it ourselves in our conferencing products, for instance: SIP users can join directly the SIP bridge, WebRTC users can do that via the SIP plugin in Janus. Turning Janus into a SIP server/bridge scares me and seems unneeded.

**Comment by shrhoads** [comment]
Freeswitch and Asterisk are great (and other commercial solutions like Aspect Prophecy) but in the case where would only be the increasingly more rare SIP leg in a mostly WebRTC world it add a lot of complexity, but I understand wanting to keep janus pure.  Thanks for listening.

**Comment by lminiero** [comment]
Even the rare SIP leg support means implementing a complete SIP server functionality. This means having to worry about the tons of different things that can happen or be needed in that space, potential transcoding required, etc. Scary :smile:

**Comment by deanelwood** [comment]
We have the same view and have been thinking about creating a mod_janus for FreeSWITCH (so a FreeSWITCH module that acts as a Janus/WebRTC client) as an alternate approach. This would abstract Janus from having to worry about SIP.

This might be a workable solution, and perhaps in a more appropriate place. For it to work inside the existing videoroom plug-in though you’d have to mix audio streams.

**Comment by lminiero** [comment]
Wouldn't you have to mix video streams too, though? Otherwise you'd need a separate SIP session for each publisher you want to subscribe to (until we implement Unified Plan to have all videos within the same PeerConnection).

**Comment by deanelwood** [comment]
No, we were thinking that we wouldn’t mix video streams, just audio. Audio would be mixed at Janus, not FreeSWITCH.

Browser clients would connect in the usual way, with an audio and a video stream. Janus videoroom plugin would relay (no mix) video streams to other users, and MIX audio streams, relaying a single mixed audio stream.

A SIP user would connect to FreeSWITCH, mod_janus would b2bua that to Janus and the SIP users upstream audio (transcoded to OPUS by FreeSWITCH if required) would be mixed by Janus along with browser users. Downstream audio from the mixed videoroom plugin would go back to FreeSWITCH for each SIP user. So the SIP user just “joins” the Janus mixed audio stream.

There are of course lots of ways to approach this (as you know, and I have read several of your thoughts on this :) ). You could also have FreeSWITCH just do all the audio and mixing for you, but I had some concerns around lip-sync and some benefits lost from having Janus at the heart of the architecture.

Awesome project btw Lorenzo. Reminds me of the FreeSWITCH early days. I haven’t written code in *years* but Janus got me started again and I’ve been playing around with a few modules.

**Comment by lminiero** [comment]
Thanks for the kind words! And for sharing these interesting ideas. Anyway, I guess that some lip-sync is always lost whenever one of the media is relayed and the other mixed, no matter where mixing happens.

**Comment by deanelwood** [comment]
>>Anyway, I guess that some lip-sync is always lost whenever one of the media is relayed and the other mixed, no matter where mixing happens.<<

That’s true, but my thinking was that if both video and audio are in the same place it’s easier to manage (maybe?).

Anyway, I think the fact that you don’t want to add SIP to Janus is one of the reasons I like Janus - it’s simple and pure in approach. Like you I think there are better ways to approach SIP/legacy interop problems.

**Comment by Jase3000** [comment]
In respect to SIP/legacy interop what would be, then, the best approach to add a SIP user to a video room - even if it is just added as a audio only participant?
Could the sip plugin be leveraged?
Or if not, is there anything out there that could do this?
I'm asking as a janus/webrtc newbie...
Thanks

**Comment by lminiero** [comment]
@Jase3000 this is more of a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), feel free to open a conversation there.

**Comment by uxmaster** [comment]
Concerning the lip-sync, it is sufficient to ensure video goes first and audio can be delayed up to 125 ms for no one will notice the misalignment, see https://www.youtube.com/watch?v=K4vyRvMASPU
