### ISSUE TITLE
core dump when test TextRoom

### ISSUE THREAD

**Issue by liyongming1982** [meetecho/janus-gateway#607]
1.  ubuntu 14.04 is ok , but 16.04 is fail

2. running  log :  
[1901706820832651]     Written 61 bytes on the read BIO...
[1901706820832651] Stream reset event: flags = 1, [1901706820832651] DTLS alert triggered on stream 1 (component 1), closing...
[1901706820832651] Telling the plugin about it (JANUS TextRoom plugin)
No WebRTC media anymore
Segmentation fault (core dumped)

3.  gdb ./janus core output:
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./janus -d 7'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f367864d960 in _xend ()
    at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:33
33	../sysdeps/unix/sysv/linux/x86/elision-unlock.c: No such file or directory.
[Current thread is 1 (Thread 0x7f362ffff700 (LWP 7847))]

**Comment by lminiero** [comment]
That's not enough information. We need a gdb or libasan stacktrace (in a pastebin/gist link, not pasted here).

**Comment by liyongming1982** [comment]
thank you so much for reponse , and the core file is too large about 320M when uncompress
[core.zip](https://github.com/meetecho/janus-gateway/files/461331/core.zip)

[janus.zip](https://github.com/meetecho/janus-gateway/files/461318/janus.zip)

**Comment by lminiero** [comment]
I didn't mean the whole coredump, just the stacktrace... `gdb bt`

**Comment by liyongming1982** [comment]
sorry for mistake , now update : 
[bt.txt](https://github.com/meetecho/janus-gateway/files/461373/bt.txt)

**Comment by lminiero** [comment]
At line 1354 I see a `g_list_length` call, and nothing that seems to refer to threads as the backtrace suggests. Are you using the latest master? If not, please update and do a `bt full`.

**Comment by liyongming1982** [comment]
cpu : Intel® Core™ i7-6700K CPU @ 4.00GHz × 8  , and ubuntu 16.04 , so i think it is about hardware problem

**Comment by liyongming1982** [comment]
so i  built glibc with --enable-lock-elision=no from source code , and only reinstall the libpthread-2.23.so and  reboot system , then no dump again , please close this issue .
At last , thank you for you support !

**Comment by lminiero** [comment]
Good to know you sorted this out, thanks for the update!
