### ISSUE TITLE
'/svn/trunk/KERN/usrsctp' path not found

### ISSUE THREAD

**Issue by akilude** [meetecho/janus-gateway#608]
Hi,

I am trying to install the gateway on a Digital Ocean box running Ubuntu 14.04, I'm stuck trying to fetch  usrsctp from svn.

The command i use is:    `svn co http://sctp-refimpl.googlecode.com/svn/trunk/KERN/usrsctp usrsctp`
Its returns the following error 

> svn: E160013: Unable to connect to a repository at URL 'http://sctp-refimpl.googlecode.com/svn/trunk/KERN/usrsctp'
> svn: E160013: '/svn/trunk/KERN/usrsctp' path not found

Thanks,
Akil.

**Comment by ploxiln** [comment]
looks like that moved to https://github.com/sctplab/sctp-refimpl/tree/master/KERN/usrsctp

But probably a better place to get it is https://github.com/sctplab/usrsctp

steps will have to change to use git, of course

**Comment by lminiero** [comment]
If the path changed, I'll have to update the README, thanks for the heads up.

**Comment by akilude** [comment]
Hi @lminiero , I built the latest version from master but i referred installation instructions from an older source [here](https://groups.google.com/forum/#!topic/meetecho-janus/RYP4FBaeUi0).

Sorry, My bad :(
