### ISSUE TITLE
Demo Video Call not working

### ISSUE THREAD

**Issue by smyrgeorge** [meetecho/janus-gateway#610]
Hello,

I just tried a video call and i'm getting the following errors:

`janus.js:1960 WebRTC error: DOMException: Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER`

`adapter.js:367 Uncaught (in promise) DOMException: Failed to set remote offer sdp: Called in wrong state: STATE_SENTOFFER`

any help would be appreciated.

**Comment by lminiero** [comment]
Does this happen on our demo page too? Which browsers?

**Comment by smyrgeorge** [comment]
This happens on your demo page and also on a local setup. We tested `Chrome 53.0.2785.101 (64-bit)` and `Firefox 48.0 (64-bit)`. I think `adapter.js` is the problem. Perhaps need to update to a recent version.

**Comment by MarcMacia** [comment]
I have the same issue both in your demo page and a local setup, only for the Video Call demo. I tested in Chrome `53.0.2785.101 (64-bit)` and `Firefox 48.0 (64-bit)` in Ubuntu 16.04 and Chrome `51.0.2704.106 m (64-bit)` and `Firefox 47.0.1 (64-bit)` in Windows 10.

The Firefox console doesn't display an error from adapter.js like in Chrome:
```
DOMException [InvalidStateError: "Cannot set remote offer in state have-local-offer"
code: 11
nsresult: 0x8053000b]
```

In my local setup I'm using a recent version of Janus, a commit of last week.

**Comment by lminiero** [comment]
Thanks for the feedback, I'll check later.

**Comment by lminiero** [comment]
Fixed in https://github.com/meetecho/janus-gateway/commit/bcd6fab7c9215ae81d237d6caabe7148731be7d8
