### ISSUE TITLE
Firefox 48 - VideoCall doesn't work properly

### ISSUE THREAD

**Issue by MarcMacia** [meetecho/janus-gateway#616]
I have noticed that the videocall demo doesn't work ok with `Firefox 48`, I checked it with `Firefox 47` and works well there (No problems with `Chrome`).

That is the situation:

1. Register 3 users (a, b, c)
2. 'a' calls 'b' and they establish the videocall successfully
3. 'a' or 'b' does hangup.
4. After this neither 'a' nor 'b' aren't able to establish the videocall with 'c' or with themselves again.

I've tested this in your demo page and in a local setup. I've gotten the following (I don't know if it will be useful): 
When 'a' retries connect with 'b':
```
[WARN] Ignoring negotiation update, we don't support them yet...
```
When a or b try to connect with 'c':
```
[WARN] Ignoring negotiation update, we don't support them yet...
[ERR] [ice.c:janus_ice_send_thread:3484] ... SRTP protect error... err_status_replay_old 
... x100
```

**Comment by lminiero** [comment]
Looks like Firefox is not sending a DTLS alert when the PeerConnection is closed, and so Janus is never notified about the fact the WebRTC PeerConnection is now down. As a result, when you try to negotiate a new session, as far as Janus is concerned there is one up already, and it thinks you're trying to update it.

I'll have to check if this is a bug in Firefox, and if they fixed it in the meanwhile.

**Comment by MarcMacia** [comment]
Thanks for the reply, I tested in `Firefox 49` with the Beta Channel and it didn't work either.

**Comment by lminiero** [comment]
Yeah, I know, Nightly does it too. I've asked on the `mozilla.dev.media` about this. To go around this, I guess I'll have to make sure it's the plugin that forces the PeerConnection to cloose too, rather than wait for an alert that may never come.

**Comment by MarcMacia** [comment]
I understand, thank you. This will be the best solution because seems that they decided stop to send that alert for some reason.

**Comment by lminiero** [comment]
FYI: https://bugzilla.mozilla.org/show_bug.cgi?id=1303867

**Comment by lminiero** [comment]
In the meanwhile, I committed a change that has the VideoCall plugin also ask the core to close the PeerConnection on both ends, when a `hangup` is received. Seems to be working as expected for me on Firefox 48, and I could make several calls after the first one.

Closing the issue, feel free to reopen if still happening.

**Comment by sergey-safonov** [comment]
Looks like the same issue with echotest plugin in Firefox 50. 

I'am trying to createOffer with different audio/video devices after hangup, but can't.

Janus daemon log:

```WebRTC media is now available
[WSS-0x7f80a0003940] Destroying WebSocket client
[WARN] [3003913645961125] Didn't receive audio for more than a second...
[WARN] [3003913645961125] Didn't receive video for more than a second...
[WARN] [3003913645961125] Ignoring negotiation update, we don't support them yet...
[WARN] [3003913645961125] Not video and not audio? dropping (SSRC 3562780176)...```
