### ISSUE TITLE
Multiple streaming plugin entities with different multicast groups can't share the same port

### ISSUE THREAD

**Issue by mvollrath** [meetecho/janus-gateway#617]
I'm testing this streaming plugin configuration:

```
[gstreamer]
type = rtp
id = 1
description = Stream from gstreamer
audio = no
video = yes
videomcast = 224.42.42.1
videoport = 6000
videopt = 96
videortpmap = VP8/90000

[gstreamer2]
type = rtp
id = 2
description = Stream from gstreamer
audio = no
video = yes
videomcast = 224.42.42.2
videoport = 6000
videopt = 96
videortpmap = VP8/90000
```

This is potentially a legal configuration, but I get this output:

```
Loading plugin 'libjanus_streaming.so'...
[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:2305] [gstreamer] Video listener IP_ADD_MEMBERSHIP ok
[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:2305] [gstreamer2] Video listener IP_ADD_MEMBERSHIP ok
[ERR] [plugins/janus_streaming.c:janus_streaming_create_fd:2313] [gstreamer2] Bind failed for video (port 6000)...
[ERR] [plugins/janus_streaming.c:janus_streaming_create_rtp_source:2446] Can't bind to port 6000 for video...
[ERR] [plugins/janus_streaming.c:janus_streaming_init:644] Error creating 'rtp' stream 'gstreamer2'...
JANUS Streaming plugin initialized!
```

This can be allowed, by setting `SO_REUSEPORT` on the socket if a multicast group is specified.

The following *abbreviated* logic in `janus_streaming_create_fd` will allow different multicast groups to share the same port:

```
if(port > 0) {
  if(IN_MULTICAST(ntohl(mcast))) {
    int reuse = 1;
    if (setsockopt(fd, SOL_SOCKET, SO_REUSEPORT, &reuse, sizeof(reuse)) == -1) {
      JANUS_LOG(LOG_ERR, "[%s] %s listener setsockopt SO_REUSEPORT failed\n", mountpointname, listenername);
      close(fd);
      return -1;
    }
    // This is needed to filter out unicast on the specified port.
    address.sin_addr.s_addr = mcast;
  }
}
```

Needing to set `s_addr` to `mcast` is sort of a separate bug, when you bind to `INADDR_ANY` unicast datagrams will be received on what was intended to be a multicast binding.

I tested this and it works, but I'm not planning to use it because Docker is not particularly multicast-friendly.  I found that out after I started writing this issue, so instead of ditching it, I'm leaving it here for posterity.

**Comment by lminiero** [comment]
Yep, different mountpoints need to use different ports, whether it's multicast (even on a different group) or not. Even with the change you made, though, I'm not sure this would not work in practice, as the two different multicast mountpoints would use different threads to handle incoming packets, and so would likely steal each other's data. You'd need a single receiver that handles the group demultiplexing for you. Unless this demultiplexing is already handled at lower levels and no conflicts arise, I'm not a great expert on multicast itself.

That said, thanks for sharing these details! I'll think about whether to make it explicit that you need to use different ports, or incorporate your fix itself.

**Comment by mvollrath** [comment]
As long as you bind a specific address (the group IP) and set `SO_REUSEPORT`, the kernel guides datagrams with gusto.

**Comment by lminiero** [comment]
Got it, thanks. I'll work on integrating your suggested fix in the code.

**Comment by lminiero** [comment]
Added your code to the mountpoint setup, thanks!
