### ISSUE TITLE
Too many packets in queue

### ISSUE THREAD

**Issue by amnonbb** [meetecho/janus-gateway#626]
Thanks for implementing RTP forward future in Audiobridge plugin!
It's do very simple life in my live translation project.
Today i tried it with ~ 20 connection
And igot log spaming with:

[WARN] Too many packets in queue (13 > 12), removing older ones

it's part of debug level 5
http://pastebin.com/5WXc557q

For 1 hours Janus take 5Gb Memory

**Comment by lminiero** [comment]
I guess a `LOG_WARN` is too verbose for that, or at least we shouldn't print that for all messages but only, let's say, every few seconds. I'll see if how we can make that less harmful.

**Comment by lminiero** [comment]
This commit (and the one after that which fixed a couple of typos) should make the notification much less verbose/spammy. It remains a `LOG_WARN` output, but it only appears every 5 seconds or so for a specific participant. It may still be a bit verbose with many people in the room, but in no way as verbose to result in a 5GB log file.

Closing, let me know if that works for you, if not feel free to reopen.
