### ISSUE TITLE
Audio Bridge Plugin: join as a "listen only" participant not working? (FireFox)

### ISSUE THREAD

**Issue by BellesoftConsulting** [meetecho/janus-gateway#629]
If you join the AudioRoom in Firefox  and don't allow Mic access or if you join the audio room in recv only mode, the WebRTC handshake does not appear to work.

You can easily replicate the issue with the audiobridge plugin demo by changing  the stock audiobridgetest.js  (line 134) from media: {video: false}  to media: { video: false, audioSend: false, audioRecv: true } 

Chrome seems to work fine. 

What I do to replicate is flip audioSend  to true, save the JS file, connect as a publisher, then flip it to audioSend to false, save, then load the page on FF.

**Comment by lminiero** [comment]
Yep, managed to replicate it and just fixed it. Apparently the cause was the fact we were replying with `a=sendrecv` (which means "I'll send and receive") in response to the `a=recvonly` ("I'll only receive") the browser sent, instead of using a `a=sendonly` as we should. This commit fixes that.

**Comment by BellesoftConsulting** [comment]
wow, fastest bugfix in history!
Will test now

**Comment by lminiero** [comment]
I don't know why this wasn't resulting in an exception in JavaScript, though: I would have expected an error when doing the `setRemoteDescription`, but I couldn't find it.

**Comment by BellesoftConsulting** [comment]
I am afraid it worked the first time, but now it seems to be doing the same thing :(

**Comment by lminiero** [comment]
Seems to be working fine here, with both Firefox 48 and 51 (Nightly). I guess your problem is now caused by something else, looking at the Admin API info may provide more details.
