### ISSUE TITLE
h264 not playable

### ISSUE THREAD

**Issue by superdump** [meetecho/janus-gateway#630]
Using the videoroom plugin I have set up publishing a video stream to a room and have chosen the H.264 codec when creating the room. I see in the SDP signalling that indeed H.264 is selected.

I post-process the `.mjr` file with `janus-pp-rec` to a `.mp4` file but the resulting file is not playable in VLC, GStreamer, Quicktime, etc. Does this currently work for anyone else or is this a bug?

**Comment by lminiero** [comment]
Yeah, just verified that's indeed the case with both Chrome and Firefox. It definitely did work before and we changed almost nothing in the code, there, so something changed in the way the browsers are encoding stuff that breaks our processing.

I just tried recording to a `.mjr` an H.264 RTP stream Gstreamer sends to the Streaming plugin, and the processing works fine there. Looking at the parsing debug, it looks that, while Gstreamer sends NALs 7 (SPS) and 8 (PPS), Chrome and Firefox don't. Those are the NALs we parse to evaluate the resolution of the stream, and in fact for the `.mjr` files captured from browsers our code fails to see what the resolution to write in the `.mp4` container is. Anyway, the default when it's not found is 640x480, which is the resolution I'm using for those streams, so it's not just a matter of parsing the right resolution. At the same time, I tried RTP-forwarding an H.264 publisher to a gstreamer pipeline that decodes the stream and displays it, and it works fine there, so there may be something that we're missing in our depacketization code.

Considering that our processor does nothing else than depacketizing and writing to file (no decoding/transcoding), I really have no idea on what we should fix: the code we use seems correct. Unfortunately I'm no H.264 or FFmpeg expert, so if somebody can help figuring out what's wrong that would be cool.

**Comment by lminiero** [comment]
Wait, progress! Just found out, digging more in some dumps, that the SPS and PPS actually **are** sent, but as part of aggregated packets (STAP-A). Working on parsing those now...

**Comment by superdump** [comment]
I was just going to start looking into it myself. Great progress! 😄  Thanks for looking into it so quickly.

**Comment by lminiero** [comment]
Ok, this patch fixes it for me for all the attempts you made. Feel free to re-open if it's not working for you for some reason.

**Comment by superdump** [comment]
That works, thanks! The file plays fine in VLC. Not in QuickTime Player on macOS Sierra but that's another topic. 😄
