### ISSUE TITLE
Audio description wrong

### ISSUE THREAD

**Issue by revmischa** [meetecho/janus-gateway#632]
I'm trying to add audio to a RTP source and getting the error:
"WebRTC error: OperationError: Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote audio description send parameters"

My config looks like:
```
[mishrtp]
type = rtp
description = Cash money G unit
audio = yes
video = yes
videoport = 4009
videortpmap = h264/90000
videopt = 100
audioport = 4008
audiopt = 100
audiortpmap = ac3/48000/6
```

What am I doing wrong? Is there some documentation I should be looking at for valid values and such?

**Comment by alexamirante** [comment]
There are a couple of mistakes:

1. You're trying to negotiate AC-3 audio, which not supported by the browser;

2. You're using the same payload type `100` for both audio and video, so even if you fix the codec issue you'd get garbled audio and broken video.

Closing as not an issue, please refer to the [discussion forum](https://groups.google.com/d/forum/meetecho-janus) for this kind of questions.
