### ISSUE TITLE
VP9 video and audio out of sync (videoroom recording)

### ISSUE THREAD

**Issue by xenyou** [meetecho/janus-gateway#633]
steps to reproduce

## 1. edit janus.plugin.videoroom.cfg

```
[1234]
description = Demo Room
secret = adminpwd
publishers = 6
bitrate = 128000
fir_freq = 10
;audiocodec = opus
videocodec = vp9
record = true
rec_dir = /tmp/janus-videoroom
```

## 3. postprocess mjr files

```
janus-pp-rec xxxx-video.mjr xxxx.webm
janus-pp-rec xxxx-audio.mjr xxxx.opus
ffmpeg -i xxxx.webm -i xxxx.opus -c:a copy -c:v copy out.webm
```

## 4. play the out.webm

It started fine but after a certain period of time, video and audio got unsynchronized.
I tested this with commit f56482305635889bd232d1dcce4603e608da428d.

**Comment by xenyou** [comment]
Browser is Chrome 53.

**Comment by xenyou** [comment]
Recording VP8 also cause the same issue.
And I remember commit 48967c3e69d5cbbdeff6e3f96d3640bc0129ae10 did not cause this problem.

**Comment by lminiero** [comment]
@xenyou we're definitely not experiencing issues with VP8 recordings (never played much with VP9), so it might be unrelated. Besides, recording does nothing more than dumping incoming RTP frames in a structured way to file, and post-processing reorders them and extracts the payload to save it to a media container. It may be  problem with the source, something you can verify trying to do the same with different captures from different machines/devices.

Can you share some sample files, and/or go forward through revisions (maybe starting from the one you say works, to be sure) to find which commit apparently broke it for you?

**Comment by xenyou** [comment]
@lminiero 

Thanks for explaining it.
I'll investigate it.

**Comment by xenyou** [comment]
It seems that Chrome 53 is the cause.

Actually I'm using electron.
After I downgraded it to an old version (based on Chrome 50), It fixed!!

I'll close it.

**Comment by lminiero** [comment]
Thanks for the update! That's weird though... I'm on Chrome 54 myself and I don't recall having these issues. Unless it's only happening when used in Electron? Do you have some indicators on when this desync starts happening (after how much time), so that I can try and replicate it in case? Any info on plugin you're using and bitrate you're forcing?
