### ISSUE TITLE
Is the gateway down? (connected=false) in janus.js line 711

### ISSUE THREAD

**Issue by karth295** [meetecho/janus-gateway#641]
I'm using Janus: fa78e35d444342f970dbc7b1e4a59aaec9bc7ce9 and both clients are separate windows of Chrome 53.0.2785.116 m on Windows.

I see this error when I have two clients connect to the videoroom plugin using the janus.js API. The symptom is that both of their video streams seem to arbitrary be blank for several seconds at a time, and then come back. The server logs are here: http://pastebin.com/VEN8kPuS, but I'm not sure whether that indicates an issue.

I don't see this issue when the clients connect with the provided videoroomtest.html, so clearly I'm using the API wrong. Either way, this error message is confusing because the gateway is not actually down.

**Comment by lminiero** [comment]
Maybe a connectivity issue between clients and server? That would explain the black video as well, since I do see several "Didn't receive audio|video for more than a second" lines in your log.

**Comment by amnonbb** [comment]
I got the same problem.
It's started when i updated janus form 0.1.2 to 0.2.0

grepped log:
http://pastebin.com/D9skEg1F

**Comment by lminiero** [comment]
`Didn't receive video for more than a second` is not something that can be caused by an update, it means the server is not receiving those video packets.

**Comment by karth295** [comment]
I'll close this issue for now because I don't have evidence that it's a Janus bug. I'll run the gateway on my local machine, and post whether I have the same problem.
