### ISSUE TITLE
Janus streaming + videocall Hybrid?

### ISSUE THREAD

**Issue by IvRRimum** [meetecho/janus-gateway#646]
Hello,

Is it possible right now( using videoroom plugin and streaming plugin ), to create a video room in witch, for example, 5 people talk( using video/audio ) and rest connect to just view them talk?

2 types to connect to a video room.
1) As a broadcaster(the guy that shows his video/audio)
2) Viewer, the guys who watches, but doesn't send anything back.

Thanks!

**Comment by IvRRimum** [comment]
Viewer count is unlimited( 10000000 viewers should be possible ).

**Comment by lminiero** [comment]
Closing as not a code issue. Please use the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) group for questions like this.

**Comment by IvRRimum** [comment]
Okey, sorry, will ask there!
