### ISSUE TITLE
Exposing session-related data from plugin to the external world through transport

### ISSUE THREAD

**Issue by manifest** [meetecho/janus-gateway#649]
It **would be nice** to implement some kind of resource discovery for plugins. In other words:
- plugins own some resources (for instance, we could say that resources of videoroom plugin are media streams)
- information about their availability could be exposed to the external world through transport (MQTT has Last Will and Testament (LWT) feature for this purpose)

We could have used `session_created` transport's callback, but there is a **problem**, we couldn't provide any additional information within it (like description of resource) as for now.

> 	The Last Will and Testament (LWT) feature is used in MQTT to notify other clients about an ungracefully disconnected client. Each client can specify its last will message (a normal MQTT message with topic, retained flag, QoS and payload) when connecting to a broker. The broker will store the message until it detects that the client has disconnected ungracefully. If the client disconnect abruptly, the broker sends the message to all subscribed clients on the topic, which was specified in the last will message. The stored LWT message will be discarded if a client disconnects gracefully. LWT helps to implement strategies when the connection of a client drops or at least to inform other clients about the offline status.
http://www.hivemq.com/blog/mqtt-essentials-part-9-last-will-and-testament

From the MQTT transport's point of view, it could work (in general) this way:
- transport specifies its last will message on connect: '{"active": false}'
- plugin "janus.plugin.videoroom" started, it says to the transport about it,  the transport publishes retain message to LWT: '{"active": false, "janus.plugin.videoroom": []}
- stream 1 arrived, "janus.plugin.videoroom" plugin says to the transport about the new resource, the transport publishes retained message to LWT: '{"active": false, "janus.plugin.videoroom": [{"id": 1, "type": "stream"}]}'
- one more stream is arrived, retained message is equal to: '{"active": false, "janus.plugin.videoroom": [{"id": 1, "type": "stream"}, {"id": 2, "type": "stream"}]}' now
- stream 1 left, retained message is equal to: '{"active": false, "janus.plugin.videoroom": [{"id": 2, "type": "stream"}]}' now
- if "janus.plugin.videoroom" gone, the transport will send retained message to LWT topic: '{"active": true}' 
- if the transport fails, broker will send retained message to LWT topic: '{"active": false}'

**Question**. Is there any way to publish a message to the different topic (in case of MQTT it would be LWT topic instead of topic associated with Janus API)? Or any way to solve the issue described above?

**Comment by lminiero** [comment]
Not sure what you're asking, actually. Do you mean something like the mechanism we're implementing in #536? If not, can you clarify?

**Comment by manifest** [comment]
@lminiero thanks for pointing me out. Event handler plugins look like a good solution for the issue.
