### ISSUE TITLE
Janus doesn't see stream if the stream started before it

### ISSUE THREAD

**Issue by lukasz-zaroda** [meetecho/janus-gateway#650]
I have a following problem. If I will start stream before Janus, and then will start Janus - it doesn't see the stream. I have to restart the stream for it to be visible. My configuration is:

[gst-rpwc]
type = rtp
id = 1
description = Camera #1
audio = no
video = yes
videoport = 8004
videopt = 96
videortpmap = H264/90000
videofmtp = profile-level-id=42e028\;packetization-mode=1

Is there anything that can be done about it?

**Comment by lminiero** [comment]
Closing as not a code issue. Please ask questions like these on the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) Google group.
