### ISSUE TITLE
ICE error when connecting with Edge

### ISSUE THREAD

**Issue by kooler** [meetecho/janus-gateway#651]
Looks like there is an issue when connecting with Edge (checked version 14.14393).

All demos (including EchoTest) fail with "ICE failed" error. Tested on local Janus server as well as on janus.conf.meetecho.com.

@lminiero:
> That's a known issue, that we've tried to address as part of the changes made here as well:
https://github.com/meetecho/janus-gateway/pull/619

Let's try to figure out what causes it.

**Comment by kooler** [comment]
Here's output from Edge console when trying to connect to EchoTest on janus.conf.meetecho.com: http://pastebin.com/0bVW5tc9

**Comment by lminiero** [comment]
Have you checked the Admin API for that handle? Just to check if the remote candidates from the browser do reach Janus. I remember we also checked that on #619 and IIRC the candidates list was empty or missing `srflx` candidates, which is one of the things that ay lead to a failure.

**Comment by kooler** [comment]
I did previous tests on janus.conf.meetecho.com, so I believe I can't check Admin API there. But here're logs from local Janus server:
- Edge console: http://pastebin.com/7qq0b6F5
- Handle from Admin API: http://pastebin.com/r5Gu0cZR
- Janus log (with log level 5): http://pastebin.com/9kDkMCh1

**Comment by lminiero** [comment]
Seems to be consistent with what was tested in the PR. In your case it's probably failing because of this:

        "local-candidates": [
          "1 1 udp 2013266431 172.17.0.2 10154 typ host\r\n",
          "2 1 udp 1677722111 145.131.195.140 60159 typ srflx raddr 172.17.0.2 rport 10154\r\n",
          "3 1 udp 167772671 178.62.245.74 53075 typ relay raddr 172.17.0.2 rport 10154\r\n"
        ],
        "remote-candidates": [
          "1 1 UDP 2130706431 192.168.1.136 28498 typ host"
        ],

Edge is not sending srflx candidates, but only host ones. For some reason it's ignoring the STUN server. Not sure why that is, as the adapter.js code should make sure it's used automatically if set. Have you checked if configuring a different STUN server, or adding a TURN server to echotest.js, gets you more candidates there?

**Comment by lminiero** [comment]
Anyway, even without srflx candidates, it "should" work by using prflx candidates. Can it be there's a firewall that's preventing STUN packets to get through, whether it's to reach a STUN server or do a connectivity check?

**Comment by kooler** [comment]
Indeed there was an issue with format of iceServers. After it was fixed more remote candidates appeared but ICE still fails (with the same error message).
Here's new handle: http://pastebin.com/dp9fhgz5

**Comment by lminiero** [comment]
What was the invalid format? Something we need to fix in janus.js?

But does it work with other browsers in your setup? It looks like you're doing everything on the same machine (same public IP obtained via STUN), but the local IPs have different masks (192.x vs 172.x), which seems to suggest this would never work. Is Janus on a Docker machine?

**Comment by kooler** [comment]
I provided list of Stun/Turn servers to janus.js with "url" (instead of "urls") property.

Janus is indeed running inside Docker and all other browsers (checked Chrome and FF) work fine with that setup. Only Edge causes ICE issues.

**Comment by lminiero** [comment]
Got it, tnx for the clarification. At this point, it's a matter of figuring out why the checks fail. It may be either because one of the two can't reach the other, or because something in the communication fails (e.g., STUN authentication errors?)

One way to check that is enabling the libnice debugging in Janus, which shows everything that happens STUN-wise in a session. This should allow us to check whether or not the STUN packets Edge sends do get to Janus or not. Another check that can be done is sniffing traffic (e.g., via Wireshark) to see if STUN packets are exchanged at all between the two, and if any of them hit a wall for some reason.

I'm thinking now that there might be another possible cause. Janus sends all its candidates within the SDP itself, and does not trickle them as browser do. May it be that the adapter.js shim is not processing those inline SDP candidates and passing them to the stack as it should, and as such Edge is never made aware of any Janus candidate at all? I'll check this tomorrow morning.

Thanks for helping me  tackle this issue!

**Comment by lminiero** [comment]
I think I know what's happening: Edge is indeed not applying the remote candidates from Janus, but not because it's not parsing them (it is), it simply is not setting them as it believes there are still candidates missing as there's no `a=end-of-candidates` in the m-line. Unfortunately I'm not sure whether we can just add the `a=end-of-candidates` to all m-lines in Janus, as this might cause trouble with some stacks (not sure how Chrome, Firefox, or mobile stacks would react to that).

A quick way to see if that's the case is the following. Edit the `adapter.js` file at this line:
https://github.com/meetecho/janus-gateway/blob/master/html/adapter.js#L1614
and set `isComplete=true;` before the definition of `cands`. This way we'll trick the Edge shim into thinking the attribute was there, which should lead the candidates to be parsed and used.

Can you let me know if that works?

**Comment by cacheworks** [comment]
👍 When isComplete is set to true ICE no longer fails

Unfortunately DTLS then fails though,
Here is the gateway output;
https://gist.github.com/cacheworks/da16818898f25f3dd3bca52bd1d4bd0f

the Edge console output;
https://gist.github.com/cacheworks/1494765055a4018bae1983ff8fab46a8

and the handle info after DTLS failed;
https://gist.github.com/cacheworks/2a0a7da4e7c21edff1a676e8f3db0b19

**Comment by lminiero** [comment]
ICE is still connecting, from Janus' point of view:

    [5591231992284183] Component state changed for component 1 in stream 1: 2 (connecting)
    [5591231992284183] Discovered new remote candidate for component 1 in stream 1: type=prflx

It never gets to connected/completed, so DTLS never starts. I don't think ICE is getting to those states in Edge either as there seems to be no indication about that in the JS logs, so the error they report may be misleading. Do you know if Edge has something libe about:webrtc or the chrome://webrtc-internals to see the current state of a PeerConnection?

At this point, a capture via wireshark/tcpdump may indeed be needed to see why ICE doesn't seem to complete.

**Comment by lminiero** [comment]
Any update on the capture? I tried installing one of the VirtualBox Edge images on my Fedora, but apparently no soundcard is ever detected in the guest no matter what, which makes testing impossible.

**Comment by kooler** [comment]
Not yet, but I'll do some wiresharking tomorrow morning.

**Comment by lminiero** [comment]
Just managed to make some tests with one of my colleagues that had access to a Windows 10 machine.  Long story short, we did get something working there, but we'll need some adjustments to the code.

1. The ICE part (the isComplete hack) is only part of the job, and seems to only work consistently when offering and not always when answering (e.g., streaming plugin).
2. In the EchoTest, Edge does not advertize BUNDLE in the offer, but Janus answers with a BUNDLE instead, which it shouldn't; as a result, Edge does ICE with the first component, which in fact works in the Admin API, but ignores the second component, which fails; as a result, for Janus the session is incomplete and broken, and so is in Edge. I managed to get this working by not having Janus add the BUNDLE line if BUNDLE is not supported, and this way the EchoTest worked (both audio and video). That said, I need to fix this as well, because it also results in Janus not advertizing BUNDLE when offering, which it needs to do.

I'll try to work on these fixes tomorrow and keep you posted.

**Comment by lminiero** [comment]
Ok, thanks to the help of @atoppi I found a working environment and just pushed the changes.

This fixes a bug in Janus where we were overwriting the remote fingerprint/ICE credentials when bundling, which resulted in Janus using the wrong info when trying to do connectivity checks with Edge. Besides, JavaScript fixes include enabling BUNDLE support in Edge programmatically, and adding an `end-of-candidates` attribute at the end of the remote SDP before setting the remote description for Edge only.

Beware that the version of Edge that we tried still only supported `X-H264UC` for video, and so video is always automatically disabled by `janus.js` when Edge is used, as Chrome and Firefox would barf on it. As such, demos like Streaming involving video and VideoRoom will most likely not work. EchoTest, audio-only Streaming and AudioBridge worked fine instead. If you disable the force-video-off in `janus.js` (https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L2142) you'll be able to at least test video in the EchoTest too, which seemed pretty chunky anyway. If your version of Edge supports other video codecs too (e.g., VP8 or standard H.264) try disabling that check and let us know if the rest works too.

Closing as this fixes it for us. Feel free to reopen if that's not the case and you can provide more feedback.

**Comment by lminiero** [comment]
PS: if you set `videortpmap = X-H264UC/90000` in a Streaming mountpoint, Edge accepts it, but a regular H.264 gstreamer pipeline doesn't result in any video being displayed in Edge, which makes me think a plain H.264 stream is not really compliant with this custom profile Microsoft uses. Just food for thought in case you want to play with gstreamer/ffmpeg pipelines to get a working Streaming video mountpoint in Edge :wink:

**Comment by lminiero** [comment]
PPS: apparently Edge supports plain H264 if you enable a [hidden flag](https://blogs.windows.com/msedgedev/2016/05/27/previewing-h-264avc-for-ortc/#gWCtbAROjD4emrwf.97) in `about:flags`! Just tried both an H.264 Streaming plugin mountpoint and an H.264 Videoroom and they worked great :+1: (assuming you remove the no-video constraint in `janus.js` I mentioned, of course).

**Comment by fippo** [comment]
The latest insider build has standard H264 unflagged. H264UC has SVC streams

**Comment by lminiero** [comment]
> The latest insider build has standard H264 unflagged. H264UC has SVC streams

Thanks for the info, I didn't know about that! The version my colleague tried is the stable one I guess.

**Comment by kooler** [comment]
Thanks for information Lorenzo and for a great work!

**Comment by kooler** [comment]
Still have problem with connecting to AudioBridge demo from Edge. ICE doesn't fail anymore, but looks like now DTLS doesn't come through.

Janus throws to log few hundreds of messages like this:
```
[3317922357052408] >> >> Read 243 bytes from the write_BIO...
[3317922357052408] >> >> ... and sent 243 of those bytes on the socket
[3317922357052408] DTLSv1_get_timeout: 3899
[3317922357052408] DTLSv1_get_timeout: 3799
[3317922357052408] DTLSv1_get_timeout: 3698
...
```
and after few seconds Edge reports that "DTLS handshake failed".

Works fine from Firefox on the same machine (so shouldn't be network related).

**Comment by lminiero** [comment]
Always worked fine here so can't replicate. Try inspecting with wireshark/tcpdump to see if you spot anything weird in the DTLS handshake.

**Comment by kooler** [comment]
Ok, will check it.

**Comment by macdonaldj** [comment]
hate to revive an old thread, but i am having similar issues with edge browser. the streaming demo works on meetecho demo site, but on my local server, i get the ICE failed error message. When i switched to ice-lite, the console would show an invalid state error. Everything works great on other browsers. The test is using the a-law source file from repo. Any help would appreciated

Janus log: http://pastebin.com/RjNfQ4wi
Edge  console log: http://pastebin.com/3u3EJn09

**Comment by macdonaldj** [comment]
the audio  issue as fixed once some udp ports were opened.  no onto getting a dummy video gstream working (using the streaming gstream plugin to only send audio and not video)

**Comment by RobertLowe** [comment]
Reviving this again, sorry all.

> Is Janus on a Docker machine?

@lminiero you nailed it.

Everything was fine in chrome, broken in firefox. I moved the janus service outside the docker container to the host where all ports are exposed. 

Inside Docker Firefox generated this:

    SDP
    Local SDP
    v=0
    o=mozilla...THIS_IS_SDPARTA-58.0.2 5930554725350164466 0 IN IP4 0.0.0.0
    s=-
    t=0 0
    a=sendrecv
    a=fingerprint:sha-256 F2:81:BC:D6:B9:A5:AF:83:20:A2:13:2C:7A:68:69:04:38:C6:82:F7:B0:E1:06:55:20:C1:C0:70:41:71:7D:8F
    a=group:BUNDLE audio video
    a=ice-options:trickle
    a=msid-semantic:WMS *
    m=audio 57538 UDP/TLS/RTP/SAVPF 111
    c=IN IP4 64.137.149.59
    a=candidate:0 1 UDP 2122252543 10.88.111.5 57538 typ host
    a=candidate:2 1 TCP 2105524479 10.88.111.5 9 typ host tcptype active
    a=candidate:1 1 UDP 1686052863 64.137.149.59 57538 typ srflx raddr 10.88.111.5 rport 57538
    a=recvonly
    a=end-of-candidates
    a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
    a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1
    a=ice-pwd:656c1ea6ef47aef53d47d3bba65c932e
    a=ice-ufrag:09618fef
    a=mid:audio
    a=rtcp-mux
    a=rtpmap:111 opus/48000/2
    a=setup:active
    a=ssrc:1716977557 cname:{3bfd82b0-0cce-d148-b2fc-e2c5c9ef6c4e}
    m=video 57538 UDP/TLS/RTP/SAVPF 96
    c=IN IP4 64.137.149.59
    a=recvonly
    a=fmtp:96 max-fs=12288;max-fr=60
    a=ice-pwd:656c1ea6ef47aef53d47d3bba65c932e
    a=ice-ufrag:09618fef
    a=mid:video
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 goog-remb
    a=rtcp-mux
    a=rtpmap:96 VP8/90000
    a=setup:active
    a=ssrc:1493414341 cname:{3bfd82b0-0cce-d148-b2fc-e2c5c9ef6c4e}
    Remote SDP
    v=0
    o=- 1518126625544380 1 IN IP4 54.221.201.171
    s=-
    t=0 0
    a=sendrecv
    a=group:BUNDLE audio video
    a=msid-semantic:WMS janus
    m=audio 9 UDP/TLS/RTP/SAVPF 111
    c=IN IP4 54.221.201.171
    a=candidate:1 1 udp 2013266431 54.221.201.171 56985 typ host
    a=candidate:2 1 udp 1677722111 54.221.201.171 56985 typ srflx raddr 172.17.0.2 rport 56985
    a=candidate:3 1 udp 167772671 0.0.0.0 49154 typ relay raddr 172.17.0.2 rport 56985
    a=sendonly
    a=end-of-candidates
    a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
    a=fingerprint:sha-256 A9:15:BF:01:A7:D4:C9:95:9C:B4:7D:D4:93:EE:39:84:EB:80:ED:BB:FB:80:5B:E1:B8:1B:73:48:62:4A:47:A0
    a=ice-options:trickle
    a=ice-pwd:f+HWC7yEOO3q5x7fFsOoTD
    a=ice-ufrag:vhBP
    a=mid:audio
    a=rtcp-mux
    a=rtpmap:111 opus/48000/2
    a=setup:actpass
    a=ssrc:362142371 cname:janusaudio
    a=ssrc:362142371 msid:janus janusa0
    a=ssrc:362142371 mslabel:janus
    a=ssrc:362142371 label:janusa0
    m=video 9 UDP/TLS/RTP/SAVPF 96
    c=IN IP4 54.221.201.171
    a=candidate:1 1 udp 2013266431 54.221.201.171 56985 typ host
    a=candidate:2 1 udp 1677722111 54.221.201.171 56985 typ srflx raddr 172.17.0.2 rport 56985
    a=candidate:3 1 udp 167772671 0.0.0.0 49154 typ relay raddr 172.17.0.2 rport 56985
    a=sendonly
    a=end-of-candidates
    a=fingerprint:sha-256 A9:15:BF:01:A7:D4:C9:95:9C:B4:7D:D4:93:EE:39:84:EB:80:ED:BB:FB:80:5B:E1:B8:1B:73:48:62:4A:47:A0
    a=ice-options:trickle
    a=ice-pwd:f+HWC7yEOO3q5x7fFsOoTD
    a=ice-ufrag:vhBP
    a=mid:video
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtcp-fb:96 goog-remb
    a=rtcp-mux
    a=rtpmap:96 VP8/90000
    a=setup:actpass
    a=ssrc:3864012077 cname:janusvideo
    a=ssrc:3864012077 msid:janus janusv0
    a=ssrc:3864012077 mslabel:janus
    a=ssrc:3864012077 label:janusv0
    RTP Stats
    inbound_rtp_audio_0
    Local: 16:50:58 GMT-0500 (EST) inbound-rtp SSRC: 0
    inbound_rtp_video_1
    Local: 16:50:58 GMT-0500 (EST) inbound-rtp SSRC: 3864012077

After moving Janus to the host things we're happy:

    SDP
    Local SDP
    v=0
    o=mozilla...THIS_IS_SDPARTA-58.0.2 5930554725350164466 0 IN IP4 0.0.0.0
    s=-
    t=0 0
    a=sendrecv
    a=fingerprint:sha-256 F2:81:BC:D6:B9:A5:AF:83:20:A2:13:2C:7A:68:69:04:38:C6:82:F7:B0:E1:06:55:20:C1:C0:70:41:71:7D:8F
    a=group:BUNDLE audio video
    a=ice-options:trickle
    a=msid-semantic:WMS *
    m=audio 57538 UDP/TLS/RTP/SAVPF 111
    c=IN IP4 64.137.149.59
    a=candidate:0 1 UDP 2122252543 10.88.111.5 57538 typ host
    a=candidate:2 1 TCP 2105524479 10.88.111.5 9 typ host tcptype active
    a=candidate:1 1 UDP 1686052863 64.137.149.59 57538 typ srflx raddr 10.88.111.5 rport 57538
    a=recvonly
    a=end-of-candidates
    a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
    a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1
    a=ice-pwd:656c1ea6ef47aef53d47d3bba65c932e
    a=ice-ufrag:09618fef
    a=mid:audio
    a=rtcp-mux
    a=rtpmap:111 opus/48000/2
    a=setup:active
    a=ssrc:1716977557 cname:{3bfd82b0-0cce-d148-b2fc-e2c5c9ef6c4e}
    m=video 57538 UDP/TLS/RTP/SAVPF 96
    c=IN IP4 64.137.149.59
    a=recvonly
    a=fmtp:96 max-fs=12288;max-fr=60
    a=ice-pwd:656c1ea6ef47aef53d47d3bba65c932e
    a=ice-ufrag:09618fef
    a=mid:video
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 goog-remb
    a=rtcp-mux
    a=rtpmap:96 VP8/90000
    a=setup:active
    a=ssrc:1493414341 cname:{3bfd82b0-0cce-d148-b2fc-e2c5c9ef6c4e}
    Remote SDP
    v=0
    o=- 1518126625544380 1 IN IP4 54.221.201.171
    s=-
    t=0 0
    a=sendrecv
    a=group:BUNDLE audio video
    a=msid-semantic:WMS janus
    m=audio 9 UDP/TLS/RTP/SAVPF 111
    c=IN IP4 54.221.201.171
    a=candidate:1 1 udp 2013266431 54.221.201.171 56985 typ host
    a=candidate:2 1 udp 1677722111 54.221.201.171 56985 typ srflx raddr 172.17.0.2 rport 56985
    a=candidate:3 1 udp 167772671 0.0.0.0 49154 typ relay raddr 172.17.0.2 rport 56985
    a=sendonly
    a=end-of-candidates
    a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
    a=fingerprint:sha-256 A9:15:BF:01:A7:D4:C9:95:9C:B4:7D:D4:93:EE:39:84:EB:80:ED:BB:FB:80:5B:E1:B8:1B:73:48:62:4A:47:A0
    a=ice-options:trickle
    a=ice-pwd:f+HWC7yEOO3q5x7fFsOoTD
    a=ice-ufrag:vhBP
    a=mid:audio
    a=rtcp-mux
    a=rtpmap:111 opus/48000/2
    a=setup:actpass
    a=ssrc:362142371 cname:janusaudio
    a=ssrc:362142371 msid:janus janusa0
    a=ssrc:362142371 mslabel:janus
    a=ssrc:362142371 label:janusa0
    m=video 9 UDP/TLS/RTP/SAVPF 96
    c=IN IP4 54.221.201.171
    a=candidate:1 1 udp 2013266431 54.221.201.171 56985 typ host
    a=candidate:2 1 udp 1677722111 54.221.201.171 56985 typ srflx raddr 172.17.0.2 rport 56985
    a=candidate:3 1 udp 167772671 0.0.0.0 49154 typ relay raddr 172.17.0.2 rport 56985
    a=sendonly
    a=end-of-candidates
    a=fingerprint:sha-256 A9:15:BF:01:A7:D4:C9:95:9C:B4:7D:D4:93:EE:39:84:EB:80:ED:BB:FB:80:5B:E1:B8:1B:73:48:62:4A:47:A0
    a=ice-options:trickle
    a=ice-pwd:f+HWC7yEOO3q5x7fFsOoTD
    a=ice-ufrag:vhBP
    a=mid:video
    a=rtcp-fb:96 ccm fir
    a=rtcp-fb:96 nack
    a=rtcp-fb:96 nack pli
    a=rtcp-fb:96 goog-remb
    a=rtcp-mux
    a=rtpmap:96 VP8/90000
    a=setup:actpass
    a=ssrc:3864012077 cname:janusvideo
    a=ssrc:3864012077 msid:janus janusv0
    a=ssrc:3864012077 mslabel:janus
    a=ssrc:3864012077 label:janusv0
    RTP Stats
    inbound_rtp_audio_0
    Local: 16:50:58 GMT-0500 (EST) inbound-rtp SSRC: 0
    inbound_rtp_video_1
    Local: 16:50:58 GMT-0500 (EST) inbound-rtp SSRC: 3864012077



--- 


All that said, are there specific port ranges Janus will use, does it have control there? Thanks. 😄
