### ISSUE TITLE
Javascript API license.

### ISSUE THREAD

**Issue by Place1** [meetecho/janus-gateway#654]
Hey! I've been exploring janus for a few days now. It's really impressive. I was just wondering the license for the Javascript API. The specific file i'm wondering about is `html/janus.nojquery.js` but this applies for many other files in the project. The file has an MIT license in the header but the `COPYING` notice says GPL v3.

So what's up? Are people able to use the JS api under MIT or GPL?

**Comment by lminiero** [comment]
The project is GPLv3 but janus.js and janus.nojquery.js are MIT, that's why we explicitly added the different license at the head of those two files only.

**Comment by Place1** [comment]
Thanks for the quick answer. I Appreciate it. I haven't encountered this before 👍
