### ISSUE TITLE
Janus running on AWS inside docker, FF fails to broadcast but video is received

### ISSUE THREAD

**Issue by Grif-fin** [meetecho/janus-gateway#656]
Running Janus on AWS-EC2 inside a container (run with --nat-1-1=<server_public_ip>). The docker image is running inside a container with --net=host which should use the same network stack as the EC2. There are no restrictions on opening ports on EC2 and the range for UPD ports opening on Janus is 20000-40000.

This is issue is intermediate so it does sometimes work on FF (49.0). Connection to Janus is via SSL.

Janus logs when issue is reproduced:

Creating new handle in session 6461880164274591: 8157076978061162
[8157076978061162] Creating ICE agent (ICE Full mode, controlled)
Creating new handle in session 6461880164274591: 4640674006796049
[4640674006796049] Creating ICE agent (ICE Full mode, controlled)
Creating new handle in session 6461880164274591: 8796390997304774
[8796390997304774] Creating ICE agent (ICE Full mode, controlling)
[WARN] [8796390997304774] Still waiting for the DTLS stack for component 1 in stream 1...
[8796390997304774] The DTLS handshake has been completed
WebRTC media is now available
[WARN] [4640674006796049]     video stream (#1) component has no valid SRTP session (yet?)

Janus logs when FF works OK:

[2673420269801946] The DTLS handshake has been completed
WebRTC media is now available
Detaching handle from JANUS Throwdown plugin
No WebRTC media anymore
Detaching handle from JANUS Throwdown plugin
No WebRTC media anymore
Detaching handle from JANUS Throwdown plugin
No WebRTC media anymore
Cleaning up handle 4147228782345230...
[4147228782345230] WebRTC resources freed
[4147228782345230] Handle and related resources freed
Cleaning up handle 6124919781714137...
[6124919781714137] WebRTC resources freed
[6124919781714137] Handle and related resources freed
Cleaning up handle 2673420269801946...
[2673420269801946] WebRTC resources freed
[2673420269801946] Handle and related resources freed
Creating new session: 6461880164274591

We are actively building on this so any logs or tries needed please let us know.

**Comment by lminiero** [comment]
Please post questions like these on our [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) group, we only use github for code issues. That said, you probably need to configure a STUN server for Janus as well when using it on AWS. You'll find similar questions (and their answers) on the group I mentioned.

**Comment by Grif-fin** [comment]
Configuring STUN server in janus.cfg solved the problem, thanks.

**Comment by zhangalex** [comment]
@Grif-fin Can you share what you changed in janus.cfg?
