### ISSUE TITLE
"ICE Failed" hangup notifications indistinguishable

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#657]
On poor connections, sometimes the ICE Candidate trickle completes without error, a local stream is present, we get a publisher sdp, and we publish successfully -- yet we still get "hangup" notification w/ the message "ICE Failed" -- the actual hangup message isn't being sent to the onCleanup event handler, and so the interfacing code has no way to know that it should retry the connection.

**Comment by lminiero** [comment]
Are you receiving a `webrtcup` event before that

**Comment by lminiero** [comment]
Sorry, hit the wrong button by mistake... are you receiving a `webrtcup` event before that? If not, then you did not publish successfully. A `webrtcup` event is the only way you're sure Janus did complete the PeerConnection setup on its end as well.

**Comment by chadfurman** [comment]
I'll have to get back to you on this.  There isn't a "webrtcup" callback event in janus.js either, either.  Nor is there any console log indicating this event has fired.  The Janus server does log "The DTLS handshake has been completed" but due to the scaling infrastructure I've setup, getting at the old Janus server log is currently difficult (this will be improved eventually)

This is also a non-consistent event, so reproducing it on-demand for the purpose of this conversation is not possible.  However, I am actively working on creating a "reconnect" routine to handle this scenario and will add more information as it becomes available. 

Callbacks specific to failed / successful ICE would be very helpful.  And thank you for letting me know to look for "webrtcup" messages

**Comment by lminiero** [comment]
The `hangup` event already includes details on why a setup failed (e.g., ICE failure) but you're right, the JavaScript library isn't providing enough context or information on that to the application. We'll have to think on the best way to do that. Anyway, you can get info on whether or not Janus believes things are ok with the PR or not in the `webrtcState` callback, look here for an example,

https://github.com/meetecho/janus-gateway/blob/master/html/echotest.js#L148

which incidentally is triggered by either `webrtcup` or `hangup`:

https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L405
https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L419

**Comment by chadfurman** [comment]
Thanks for that!  I saw webrtcState but didn't think to look for a callback!

**Comment by lminiero** [comment]
Does that fix your issue, meaning we can close it, or not? Or was there something we needed to change?

**Comment by chadfurman** [comment]
With some wrapper logic to know what is being attempted, and using webrtcup to determine if it succeeded or not, I believe I am in a good spot.  Thank you.  

While that doesn't necessarily communicate what error happened, it's good enough for my needs :)

**Comment by lminiero** [comment]
Ah ok, re-reading the thread it seems we're not passing the cause of the hangup in the callbacks, only an up/down kind of info. I'll add that in one of the next commits, e.g., as an additional optional param to `webrtcState`.

**Comment by izemize** [comment]
I work with Ice Failed issue 4-5 hours before found the problem in my case. Ice Failed triggers by commented lines in this js code.

```javascript
onmessage: function(msg, jsep){
                    var event = msg["videoroom"];

                    if (event !== undefined && event !== null) {
                        if (event === "joined") {
                            myid = msg["id"];
                            private_id = msg["private_id"];

                        }else if(event === "destroyed")
                        {


                        }else if(event === "event")
                        {
                            /*if (msg['kicked'] === student_feed) {
                                $('#rvideo').addClass('hidden');
                                bootbox.alert('A felhasználóval a kapcsolat megszakadt, mert azt a szerver szándékosan megszakította.');
                                return;
                            }*/

                            if(msg["publishers"] !== undefined && msg["publishers"] !== null) {
                                var list = msg["publishers"];
                                for (var f in list) {
                                    var id = list[f]["id"];
                                    var display = list[f]["display"];
                                    Janus.debug("  >> [" + id + "] " + display);
                                    newRemoteFeed(id, display);
                                }
                            }else if(msg["leaving"] !== undefined && msg["leaving"] !== null)
                            {
                                var leaving = msg["leaving"];
                            }else if(msg["unpublished"] !== undefined && msg["unpublished"] !== null)
                            {
                                var unpublished = msg["unpublished"];
                            }else if(msg["error"] !== undefined && msg["error"] !== null)
                            {
                                if(msg['error_code'] === 426) {
                                    bootbox.alert('Nincs nyitva a szoba!');
                                }
                            }
                        }
                    }
```

Chrome console: janus.js:412 Failed to parse response body: [object Object]
Janus debug:

```javascript
[...]
[WARN] [6572460555970539] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[ERR] [ice.c:janus_ice_check_failed:1552] [6572460555970539] ICE failed for component 1 in stream 1...
```

It's not funny. :dancing_men:

**Comment by izemize** [comment]
Hi. I'm back. I get this error again after modify javascript. Conclusion:  shandle.handleRemoteJsep({jsep: jsep}); not called.
