### ISSUE TITLE
Feat Req:  Admin API query to get plugin status information  (ex: details on videoroom plugin rooms)

### ISSUE THREAD

**Issue by shrhoads** [meetecho/janus-gateway#659]
Unless I'm mistaken, the janus.plugin.videoroom.cfg file is the only way to provision video rooms.  Right now you can find out which video rooms are in use by doing a query for sessions, then handles for that session then details on each of those handles, but that would be potentially a lot of queries.

Would like to do an admin query to get the list of configured rooms then another query to get the ones that are currently in use.  The first is optional, a query that returns an array of the room numbers in use would be fine.

Thanks again for Janus

**Comment by lminiero** [comment]
You can get the same info creating a handle towards the VideoRoom plugin and do a "list" request.

**Comment by lminiero** [comment]
Anyway, I agree some more generic plugin-related info should be available in the Admin API info. That said, it can't possibly be what you ask. Rooms are a concept specific to the VideoRoom plugin, and the core knows nothing about them, so the Admin API can't expose methods to query generic stuff that varies from plugin to plugin. The best we can do, I guess, is envisaging a different query you can make via Admin API (e.g., "plugin_info" or something like that) which, addressed to a specific plugin, has the plugin return a bunch of internals it feels like sharing.

**Comment by lminiero** [comment]
As a further alternative, make sure you check the Event Handlers PR #536 as that would allow you to be notified about everything that happens in core and plugins, including rooms. As such, you'd be able to keep state in that yourself.

**Comment by shrhoads** [comment]
Right the use case I'm working on is load balancing/managing resources, so an Admin API is preferred.  I think a "plugin-status" query would be great and it can just return it's JSON of whatever the plugin perfers.

**Comment by shrhoads** [comment]
One concern with keeping it myself (which I can currently do) is if bad things happen (tm) there is no convergence back to reality, a status query would help with that.

**Comment by lminiero** [comment]
Ack, will keep this in mind for future versions. Not sure when I'll be able to work on this as next week I'll be abroad for a conference though.

**Comment by shrhoads** [comment]
No worries, thanks for your efforts!

**Comment by deanelwood** [comment]
ADDED: Just noticed that Lorenzo already replied, but sending this off to the thread anyway in case it’s of use to anyone else reading….


You can provision/delete rooms also via the API.

Via the same API you can retrieve a list of rooms, which will contain for each room the number of participants. That should be enough for you to determine whether or not they’re in use, if you assume zero participants is probably not in use.

I use this for some simple check_mk scripts for monitoring (gives me a nice histogram of total conferences over time and numbers of participants) - snippet of code example for the API call in PHP, but should be simple to convert to anything, below:-

// WARNING : I don’t really code anymore, I’m playing with Janus in my spare time for fun/self-education. Treat any code/concepts from me as probably highly dangerous and not fit for production purpose...

/*
	Used by check_mk scripts. Returns an Array of Janus rooms with data on each.
*/
function listJanusRooms() {

	// Set up a transaction with the API
	$uuid = getUUID();
	$transaction = '{ "transaction" : "'.$uuid.'", "janus" : "create", "plugin":"janus.plugin.videoroom" }';
	$janusArray = postToJanus($transaction, "");

	if ($janusArray === false) return false;

	// Tell Janus we want to talk to the videoroom plugin
	$path = $janusArray['data']['id'];
	$uuid = getUUID();
	$transaction = '{"janus":"attach","plugin":"janus.plugin.videoroom","transaction”:”$uuid"}';
	$janusArray = postToJanus($transaction, $path);

	if ($janusArray === false) return false;

	$pluginId = $janusArray['data']['id’];
	$uuid = getUUID();

	// Fire in the request for the room list
	$transaction = '{"janus" : "message", "body": {"request" : "list", "plugin":"janus.plugin.videoroom"}, "transaction": “$uuid"}';
	$janusArray = postToJanus($transaction, $path."/".$pluginId);

	if ($janusArray === false) {
		return false;
	}

	return $janusArray;

}

I’m testing a similar technique to remove “old” rooms - I added a timestamp property to the room structure which I stamp with a time_t when the last user leaves. Rooms that are returned by this API call that have zero users and last user left > x minutes ago I delete. This means rooms are not prematurely deleted, eg, when users refresh - which is a common thing I'm seeing if something goes wrong (all users refresh at the same time or reboot browser etc).

Here’s an example of how I use the Janus API to create a room:-

/*
	Create a Janus room and return the ID
*/
function createJanusRoom($uuid, $threadId, $pin) {
	$room = false;
	$uuid = getUUID();

	$transaction = '{ "transaction" : "'.$uuid.'", "janus" : "create", "plugin":"janus.plugin.videoroom", "description" : "'.$uuid.'" }';
	$janusArray = postToJanus($transaction, "", $threadId);

	if ($janusArray === false) return false;

	$uuid = getUUID();
	$path = $janusArray['data']['id'];
	$transaction = '{"janus":"attach","plugin":"janus.plugin.videoroom","transaction”:”$uuid"}';
	$janusArray = postToJanus($transaction, $path, $threadId);

	if ($janusArray === false) return false;

	$uuid = getUUID();
	$pluginId = $janusArray['data']['id'];
	$transaction = '{"janus" : "message", "body": {"request" : "create", "plugin":"janus.plugin.videoroom", "description" : "'.$uuid.'","bitrate" : _TARGET_BITRATE, "publishers" : _MAX_PUBLISHERS, "record" : false }, "transaction": “$uuid"}';
	$janusArray = postToJanus($transaction, $path."/".$pluginId, $threadId);

	if ($janusArray === false) {
		return false;
	}

	$room = $janusArray['plugindata']['data']['room'];

	return $room;
}


Dean

**Comment by lminiero** [comment]
Yep, that's what I meant by list. In case the server code allows for it (I guess that's not the case for PHP), you can create the session and attach the handle just once, and re-use it for recurrent "list" requests, rather than recreating them all over again.

**Comment by deanelwood** [comment]
Thanks Lorenzo.

>>(I guess that's not the case for PHP)<<

No, more likely just poor coding/design from me - I put a warning in there for that reason (it’s been a while!).

Thanks,

D

**Comment by shrhoads** [comment]
If that's the preferred method I will go down that path.

**Comment by lminiero** [comment]
Keeping a session alive though means sending keepalives on a regular basis, which means having a server side component that lingers in the background. I'm not an expert on PHP but IIRC it's only reactive, that is it only kicks in when somebody makes a request, doesn't it?

**Comment by lminiero** [comment]
> If that's the preferred method I will go down that path.

Right now it's the ONLY way (if you exclude the PR we haven't merged yet). The Admin API addition will provide an alternative later on.

**Comment by shrhoads** [comment]
I did implement the session API call to get a list of rooms/etc.  I think that function probably should be admin api only.  An anonymous session API should probably only see items about it's own session for security reasons.

**Comment by lminiero** [comment]
That's what the `private` property and the `secret` are for in rooms and things like that.

**Comment by shrhoads** [comment]
Going to close this, I worked around it using a user session as you suggested.

**Comment by lminiero** [comment]
It is still on my TODO list though :wink: 
I was planning to add it to the Event Handlers branch, as that's a breaking enough change (meaning plugins would still need to adapt a bit to fit) that we can enrich with a feature like this. I'll notify here if and when that happens.
