### ISSUE TITLE
dtls cannot initiate srtp

### ISSUE THREAD

**Issue by lilong-epfl** [meetecho/janus-gateway#660]
Hi,
when I try to run Janus gateway, I got the following fatal: 
`[FATAL] [dtls.c:janus_dtls_srtp_init:231] Ops, error setting up libsrtp?`

which cause call hangup or  DTLSv1_get_timeout. 

Any idea about this?
Thanks

**Comment by cacheworks** [comment]
Which version of libsrtp are you using?
If you're not using 1.5 try installing that manually as described in the [README.md](https://github.com/meetecho/janus-gateway/blob/master/README.md)

**Comment by lminiero** [comment]
Are you using an old version of Janus? line 231 of dtls.c points to a comment
https://github.com/meetecho/janus-gateway/blob/master/dtls.c#L231

**Comment by lilong-epfl** [comment]
I tried openssl with version 1.0.1e, 1.0.1f, 1.0.2j. I also changed the libsrtp with version 1.5.4 and 1.5.0. But nothing works.

**Comment by lilong-epfl** [comment]
I am using Janus 0.1.0

**Comment by lilong-epfl** [comment]
I am using Buildroot, Janus 0.1.0 is the only one integrated into Buildroot. If I change the config file to higher version. I always got Segment fault.

**Comment by lminiero** [comment]
Sorry but we can't provide support for something so old. Try installing a more recent version and in case it still happens feel free to re-open this issue. That said, if it it fails on `srtp_init()` it's probably an issue with libsrtp itself, rather than Janus.

**Comment by lilong-epfl** [comment]
Hi, this problem is solved by update libnice to 0.1.10. The reason is that libnice symbol clash with openSSL. 
Both libraries define the function **RAND_bytes()**. For some reason, openSSL tries to call the function defined in libnice instead use it's own definition. If this happen, it also cause the famous **DTLSv1_get_timeout** problem. Starting from 0.1.10, libnice rename this function to **nice_RAND_bytes()** to avoid this issue. 
related link: [https://lists.freedesktop.org/archives/nice/2014-October/000976.html](url)
[https://lists.freedesktop.org/archives/gstreamer-commits/2015-January/084746.html](url)

**Comment by lminiero** [comment]
Aaaah cool, I didn't know about that, thanks for the heads up!

**Comment by lilong-epfl** [comment]
I don't know why my related links don't work here, but you can copy it to the browser. May be someone can help edit it.
