### ISSUE TITLE
Feature request: audiobridge mute other users/modify their volume

### ISSUE THREAD

**Issue by Place1** [meetecho/janus-gateway#668]
Hey I don't know the protocol around here but I think it'd be a great feature for the Audiobridge plugin to support users muting other users and users changing the volume of other users.

This would allow you to make a loud person quiet or mute someone you don't want to hear during a voice call.

**Comment by lminiero** [comment]
This would mean introducing the concept of some sort of "superuser" in the plugin, somebody who's authorized to do things the others don't. The AudioBridge plugin doesn't have anything like that right now, and I'm not sure we'll add that as you just pick a username, there's no authentication involved. I guess this might be considered as one of the other admin-related requests we have, though, e.g., "create" and "destroy", which do require you to pass the room's secret which only the creator of the room knows.

In the meanwhile, though, you can already achieve muting another user if you wrap the Janus API in an application server of yours. This way, you have control over the messaging of all the handles, and so muting X means using X's handle to send a mute request.

As to the volume, we don't have a knob for that yet. I guess this is something we can add to the TODO list, e.g., as a new parameter for a "configure" request as "muted" already is.

**Comment by Place1** [comment]
I think I may have miscommunicated the idea behind the 'users muting other users' was more to implement features like 'ignore'.

For example, the audiobridge currently creates the mixed stream for you without adding your own audio (so you don't get a loop back); perhaps we could support adding other users to your 'ignore list' so you can stop their audio being added to the mix so you don't need to hear them. In this case, everyone else will still here the person because they aren't muted but you personally won't hear them because you flagged them to be ignored for your own mix coming from the bridge.

The use cases for this range from being able to ignore abusive people to just wanting to not hear someone who may have left their mic open while being away from the computer.

I imagine there'd be new API endpoints added to support 'ADD' and 'REMOVE' of users from your ignore list.

Sorry if I didn't describe it well!

My idea for the volume feature is similar, you want to be able to adjust the volume of a specific person in your mix coming from the audio bridge. Perhaps someone wants to make 'person A' louder but someone else wants to make 'person A' quieter.

**Comment by lminiero** [comment]
That's not going to be easy, unfortunately, as we don't really do a per-person mix. We mix everyone together, and then for each user we just remove their own contribution, which is an optimized way of mixing. Preparing a truly per-person mix, up to individual volumes for specific users that are different depending on who listens, would mean making different sums for each user, and thus increase the CPU consumption exponentially, so it's not a road we're willing to take for this plugin. The volume thing is interesting, and we'll probably add that, but it will be global as it this for all other aspects, as in "person X will have a 50% volume in the mix for everybody".

Of course you're still free to extend the plugin yourself if you're interested in a much more drill-down feature.

**Comment by Place1** [comment]
Hmm, I sort of understand. I'll admit i've only recently picked up Janus so i'm very naive.
Looking through the implementation of the plugin I can see this is where the users contribution is removed.
(line 3064 to 3078)
```
/* Send proper packet to each participant (remove own contribution) */
...
if(p->active && !p->muted && !p->prebuffering && p->inbuf) {
				GList *first = g_list_first(p->inbuf);
				pkt = (janus_audiobridge_rtp_relay_packet *)(first ? first->data : NULL);
				p->inbuf = g_list_delete_link(p->inbuf, first);
			}
			janus_mutex_unlock(&p->qmutex);
			curBuffer = (opus_int16 *)(pkt ? pkt->data : NULL);
			for(i=0; i<samples; i++)
				sumBuffer[i] = buffer[i] - (curBuffer ? (curBuffer[i]) : 0);
```

If I wanted to implement at least ignoring specific users would I just need to remove the data from the specific user in a similar fashion? Perhaps every participant has a list of 'ignored users' and in this part of the code it's used to remove their contribution as well as your own?

I understand if this is something that won't be added to the AudioBridge plugin but it might be something I can still try and do.

**Comment by lminiero** [comment]
Just implemented a simple setting that allows you to modify your own volume in a room, as a percent value. Default is 100 meaning no manipulation done.
