### ISSUE TITLE
Feature request: disable dtls srtp

### ISSUE THREAD

**Issue by mtdxc** [meetecho/janus-gateway#669]
this is not a bug but require a enhance function.
I found janus will take lots of cpu if we have 15+ user online in the same videoroom.
It may be the srtp reason, webrtc require peerconnection to create with dtls srtp enable by default, This require janus to do srtp_unprotect and srtp_protect for  every packet, It may takes much cpu.
and then I found webrtc can turn off srtp by this(in natvie api) 
struct RTCConfiguration {
    rtc::Optional<bool> enable_dtls_srtp;
} 
but when I try to set this flag to true, I found it can't work with janus.
[10-25 07:49:21] 1694 [WARN] [1218233152971671] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[10-25 07:49:21] 1694 [WARN] [1218233152971671] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)

can we take this function  work, I think it will make janus to support much users.

**Comment by mtdxc** [comment]
and I have do some research with sdp:
`**< line is disable dtls srtp and > line is the srtp enable....** `
< m=audio 9 RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 126
> m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 102 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:nqpH
a=ice-pwd:XbwA8z1g7ES741sd/UPcWZHu
> a=fingerprint:sha-256 7B:5D:40:A8:3A:4B:1C:03:35:2B:03:5F:0E:75:A4:B8:1D:0A:2B:97:9C:E0:DE:C8:3D:5A:10:9F:8C:FC:07:CF
> a=setup:actpass
< a=crypto:1 AES_CM_128_HMAC_SHA1_80 inline:z+H+gU1BrhFjebuWMdn2amur/6YY4tlt4+RGi2y6

**Comment by lminiero** [comment]
DTLS is mandatory in WebRTC.

**Comment by notedit** [comment]
@mtdxc   you can disable dtls  yourself  

i have noticed that

**Comment by lminiero** [comment]
I think you're very much confused on what you think that flag does... Disabling DTLS does NOT disable SRTP, it simply falls back to SDES-SRTP (which is only supported in Chrome, and is something the standard says explicitly NOT to do).

**Comment by mtdxc** [comment]
yes you are right. I am confuse: disable the flgs  can't not disable srtp...
but with srtp the performace with janus is not very well. 
even janus has much bandwidth， any other idea?

**Comment by notedit** [comment]
@mtdxc   i am researching this,  any progress have you made?

**Comment by notedit** [comment]
i have seen a  disable_encryption  option in webrtc's native code.

https://groups.google.com/forum/#!topic/discuss-webrtc/VgYC3kz4EsI

**Comment by lminiero** [comment]
Janus only does encryption. If you need a server with no encryption you'll need to use another one.

**Comment by notedit** [comment]
@lminiero  what i want to make sure is that if  we can disable srtp,  if so  we can reduce lots of cups use on server side.

i will digg much.

**Comment by mtdxc** [comment]
sorry it don't digger in it...

At 2016-11-05 22:40:11, "notedit" <notifications@github.com> wrote:


@mtdxc i am researching this, any progress have you made?

**Comment by macdonaldj** [comment]
@lminiero  What kind of encryption is used? Mainly the UDP traffic that is coming from a stream
