### ISSUE TITLE
No way to disable "keepalive" console logging without disabling all server responses

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#676]
In janus.js we log "got even on session" which is _great_ and I want to keep all events logged from the session.  Except keepalive events.  I don't care about the bajillion million keepalive packets.  But I can't stop logging keepalive packets without disabling all debugging logs.  

I'm filtering them out in my front-end logging library (that publishes to my server so I can review things if something goes south for my users).  But really, having a "verbose verbose" setting with less-useful debugging messages like that would be great.

**Comment by lminiero** [comment]
What line in the code are we referring to? Messages can be logged either in the core or (transport) plugins.

**Comment by chadfurman** [comment]
4th and 5th line of handleEvent()  in Janus.js

**Comment by lminiero** [comment]
Ah you meant in JavaScript: I thought you were talking of the server-side logs.

It's already a `Janus.debug`. I guess a new logging binding (e.g., `vdebug`) used in very verbose situations (which ones?) that still uses `console.debug` could do the trick. Quite busy right now so not sure when I'll be able to look into that. PR always welcome though :smiley:

**Comment by chadfurman** [comment]
I'm filtering out candidate sent, sending trickle candidate, trickle received, and keepalive right now. Reduced my logs by over 50%.

I'll look into making a PR

**Comment by lminiero** [comment]
Done in https://github.com/meetecho/janus-gateway/commit/ae58a81f6ecf71e6aad769ed0704b9a86b7bf483

**Comment by chadfurman** [comment]
very nice, thank you
