### ISSUE TITLE
ringback tone

### ISSUE THREAD

**Issue by lilong-epfl** [meetecho/janus-gateway#677]
Hi, 
I am trying to play with the sip gateway plugin. I notice that when I make a phone from the browser to a SIP phone, the browser is silence before the RTP flow starts. Is that possible to generate the ringback tone in the browser side?

Best,
Long

**Comment by lminiero** [comment]
The ringing tone is something you do yourself, looking at the signalling. Play a file when you get the ringing event from the plugin, and stop it when the call has been accepted/denied.

Closing as not an issue, questions like these belong to the [group](https://groups.google.com/forum/#!forum/meetecho-janus)
