### ISSUE TITLE
"slowlink" from ice.c unrecognized by janus.js

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#681]
https://github.com/meetecho/janus-gateway/blob/master/ice.c#L1385

This produces an event called "slowlink", but in fact it has `"janus": "slowlink"` and `janus.js` does not handle `json["janus"] == 'slowlink'` 

https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L357

What happens is that the message is not recognized, so the "onmesasge" handler is never called.

**Comment by lminiero** [comment]
`onmessage` is not supposed to be triggered for `slowlink`, just plugin messages. This needs a new callback that we currently don't have there.

**Comment by chadfurman** [comment]
@lminiero rather than make a new ticket, I wanted to comment on this also and make sure it was a bug first:

Here we state that a publisher with a slow uplink is weird because they don't receive anything:
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2121

Is that saying that the uplink from the gateway to the client is slow?  When the client receives an "uplink" slowlink, it feels like it should be the gateway telling the client that their uplink is slow -- which makes sense for a publisher?

**Comment by lminiero** [comment]
Not a bug, it's from Janus' perspective.

**Comment by chadfurman** [comment]
Thanks!

**Comment by lminiero** [comment]
slowlink handler added in https://github.com/meetecho/janus-gateway/commit/ae58a81f6ecf71e6aad769ed0704b9a86b7bf483
