### ISSUE TITLE
VideoRoom plugin: room persistence 

### ISSUE THREAD

**Issue by soulfly** [meetecho/janus-gateway#682]
As I understand all rooms in VideoRoom plugin are stored in RAM and will be destroyed after server reboot
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L1140

Is there any way to make them persistent?

**Comment by oscarvady** [comment]
You can create the videorooms via configuration file
(janus.plugin.videoroom.cfg).

If you want to create these room dynamically via JavaScript, you have the
property "permanent" to get it.

2016-11-16 11:36 GMT+01:00 Igor Khomenko <notifications@github.com>:

**Comment by soulfly** [comment]
Yes, I need to create rooms via API

that's interesting, 
but I do not see any info about 'permanent' property here https://janus.conf.meetecho.com/docs/janus__videoroom_8c.html

**Comment by soulfly** [comment]
also, nothing is listed here in config example
https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.videoroom.cfg.sample

**Comment by oscarvady** [comment]
When you send the "create" request via API, you can set the property
"permanent" to true.

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L1270

IMPORTANT: Please, dont't use Github Issue for that questions. You should
use Mailing List...

2016-11-16 12:30 GMT+01:00 Igor Khomenko <notifications@github.com>:

**Comment by soulfly** [comment]
Thanks.
Would be great to have it in documentation as well
