### ISSUE TITLE
Plugin Demo: Video Room - Stuck on "Publishing..."

### ISSUE THREAD

**Issue by noamtcohen** [meetecho/janus-gateway#684]
I've deployed Janus to EC2 after getting "Ice Failed" I've added an elastic IP and change the config with 1-1 nat.
Now the video room doesn't hung up but it gets stuck with a gray overlay over the video saying "publishing..."
All UDP & TCP ports are open in the security group.

**Comment by lminiero** [comment]
Not a question for here as not a code issue. Please discuss on [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
