### ISSUE TITLE
ICE fails for screen share but same ICE works for video/audio

### ISSUE THREAD

**Issue by amangupta26** [meetecho/janus-gateway#685]
I have been using videoroom plugin for publishing/subscribing video+audio. Lately, I have started using screenshare feature. But when I start the screen share session, the local stream for screen share is received and after some seconds, an error is thrown by janus as 
`[ERR] [ice.c:janus_ice_cb_component_state_changed:1473] [3194612646613880] ICE failed for component 1 in stream 1...`

which means the ICE has failed and that can be observed in admin logs also 
[logs]( https://gist.github.com/amangupta26/fa7bdc32428305573388a0c128fffa63)

Why is ICE passing for video/audio but fails for screen share specifically.

**Comment by lminiero** [comment]
Your dumps don't help understanding what's wrong, as you used two different browsers. Since they're different implementations, it's not clear what the real cause is.

**Comment by amangupta26** [comment]
Can you suggest me what type of logs I should look into, that will be helpful to debug this issue?

**Comment by amangupta26** [comment]
Anyone else facing the same problem. I have tried many other options like using --nat-1-1 <public_ip>, but always ends up in following error:

`[Mon Nov 28 05:19:51 2016] [1867419177154968] Creating ICE agent (ICE Full mode, controlled)
[Mon Nov 28 05:20:01 2016] [ERR] [ice.c:janus_ice_cb_component_state_changed:1473] [1867419177154968] ICE failed for component 1 in stream 1...`

**Comment by lminiero** [comment]
Very likely you have network constraints that prevent a successful establishment of connectivity. If not a firewall, maybe a symmetric NAT. See if adding a TURN server on the client side helps. Besides, make sure Janus is on an open-enough server.

**Comment by amangupta26** [comment]
Yes, I am using Xirsys to get both STUN and TURN servers. Everything works perfectly when I am not screensharing i.e. using video/audio. The problem happens only if I am using Screensharing.

**Comment by lminiero** [comment]
Screensharing has nothing to do with this. It's a video as any other.
