### ISSUE TITLE
./configure shouldn't halt on non-critical missing dependencies

### ISSUE THREAD

**Issue by saghul** [meetecho/janus-gateway#689]
Hey,

I just updated Janus and now that the MQTT support was merged ./configure complains that I don't have the necessary dependencies and suggests that I run it with --disable-mqtt. Can't it figure it out on its own and just disable it?

**Comment by lminiero** [comment]
I guess that's fair, and that probably also applies to some other features we provide (e.g., rabbitmq). Anyway, I'm not that much of an expert of autoconf/automake to understand how to differentiate a "figure out by yourself if it's there" and an "I explicitly added --enable-mqtt and it's not there" scenario. In the first case, it should use it if available, and ignore it if it isnt, while in the second it should break with an error.

I'll give this a look and see if I can come up with something.

**Comment by lminiero** [comment]
The above commit should fix that. I tried to make most of the checks "smarter", in the sense that they're all "maybes" that can become a "yes" if the librariy is found. If you explicitly enabled a flag (e.g., --enable-mqtt) and the library is not found, then the configure fails as it should.

Let me know if that doesn't work as expected or if it breaks anything for you.

**Comment by saghul** [comment]
Sorry I missed the notification.  Just tested this and it works like a charm!  Your autoconf kungfu is strong. 👍
