### ISSUE TITLE
missing dependency (libcurl)

### ISSUE THREAD

**Issue by fbertone** [meetecho/janus-gateway#691]
Hi,
the streaming plugin (at least the **RTSP** one, I didn't check the others) 
requires libcurl to work, but in the documentation is not listed in the dependencies.

I think it's also worth mentioning that some distros (e.g. ubuntu) ship libcur under various "flavour" names packages (libcurl4-openssl-dev, libcurl4-nss-dev).

Another thing to note is that RTSP digest authentication requires a version of libcurl >= 7.45.0 to work and older distros (e.g. Ubuntu 14.04) only supply older versions of libcurl that are not compatible with digest authentication.

However, I should open a separate ticket for digest authentication because the way streaming plugin itself should implement authentication in a different way.

Anyways, apparently RTSP implementation in libcurl is quite poor, if possible I would suggest to switch to another library (live555?)

**Comment by lminiero** [comment]
You're right, it's not listed in the [deps](https://janus.conf.meetecho.com/docs/DEPS.html) documentation either. We only use it for RTSP support in the Streaming plugin and for the optional TURN REST API support.

As to live555, I'd rather not add yet another library to the bunch, and besides I'm not at all familiar with it (but PRs are always welcome :wink: ). libcurl seems easy enough to use and satisfactory for most use cases. Besides, your suggestions on improvements in other issues should help fix what's broken now.

**Comment by lminiero** [comment]
Added to the docs, we'll address your other points in the other issues, closing this one.

**Comment by sontt2379** [comment]
hi fbertone

Do you know how to upgrade libcurl to 7.45.0 at least?
I'm using Raspberry 3 with libcurl version 7.38.0. It seam the lastest version for Debian (ref: https://curl.haxx.se/download.html)

Thanks

**Comment by fbertone** [comment]
Note that you need 7.45 only if you have to support digest authentication, otherwise 7.38 should be fine.
I updated from ubuntu 14.04 to 16.04 but if you want to stick with your OS I think you should download the sources and compile them by yourself.

**Comment by sontt2379** [comment]
hi fbertone

- I'm going to use libcurl 7.45 for support digest authentication.
- I tried to build curl 7.50.2 follow https://gist.github.com/fideloper/f72997d2e2c9fbe66459 but my libcurl still not change like this:

"curl 7.50.2 (armv7l-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3"

Any suggestions, Thanks

**Comment by fbertone** [comment]
I guess you have to explicitly set the version to use, but you should refer either to Debian or libcurl documentation (but I think it's a standard linux procedure)
