### ISSUE TITLE
RTSP authentication

### ISSUE THREAD

**Issue by fbertone** [meetecho/janus-gateway#692]
Hi,
So, as I was saying in #691, a small change should be done in streaming plugin in order to support digest authentication.
Now the rtsp URL is passed as-is to curl, if we have a camera which uses basic authentication we can simply put username and password in the form rtsp://username:password@uri and it works just fine.
However I had a hard time trying to use a camera that only support digest authentication.
It turns out that you have to properly configure libcurl in order to use this kind of authentication.
In particular, you have to set [CURLOPT_USERNAME](https://curl.haxx.se/libcurl/c/CURLOPT_USERNAME.html) and [CURLOPT_PASSWORD](https://curl.haxx.se/libcurl/c/CURLOPT_PASSWORD.html) with the correct values and not just leave them in the url. In addition should also set the types of authentications to use, with the parameter [CURLOPT_HTTPAUTH](https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html).

For example I tried to hardcode my data in [janus_streaming.c around line 2752](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L2752) like this

        curl_easy_setopt(curl, CURLOPT_HTTPAUTH, CURLAUTH_DIGEST);
        curl_easy_setopt(curl, CURLOPT_USERNAME, "<username>");
        curl_easy_setopt(curl, CURLOPT_PASSWORD, "<password>");

Obviously a clean solution should take the values from the url and set them properly or even add username and password parameters in the plugin configuration file.

Note: CURLOPT_HTTPAUTH is a bitmask so don't use just CURLAUTH_DIGEST as I did, I think it could be safely set to CURLAUTH_ANY

**Comment by fbertone** [comment]
Oww, just remembered that I was forgetting an important piece of the story!

The code I posted does solve the very first step of the authentication (to get the SDP if I remember correctly) but just with it I still couldn't stream.

I guess that authentication data should be somehow re-sent with every subsequent command, but at the time I just didn't look further into the problem because I took another direction.

That's why this didn't end up in a PR.

**Comment by lminiero** [comment]
Thanks for the feedback. Yes, adding credentials to the configuration of the mountpoint (whether it's static or dynamic) sounds like a good idea. I also think using `CURLAUTH_ANY` is better as it leaves the decision to a preliminary negotiation between client and server (1*RTT more to setup the channel but it's an una-tantum step so not really a problem). No idea on the subsequent command thing, I'd expect the library to handle this by itself if you reuse the same context.

**Comment by fbertone** [comment]
Yeah I would also expect the library to automatically handle the session. I didn't test it extensively though. When I have the time I will check back and try to give you a complete feedback.

**Comment by fbertone** [comment]
Well I was wrong in my second comment, just tested again and the authentication seems to actually work without further modifications.
Let me know if you are planning to integrate the patch by yourselves or you prefer a PR (but I don't have a "clean" patch at the moment).

**Comment by lminiero** [comment]
Looks easy enough to do by myself, but it might not happen right away (tons of things to do).

**Comment by lminiero** [comment]
Implemented but not tested. Let me know if that works for you and if so please close the issue.

**Comment by fbertone** [comment]
Tested with both basic and digest authentication and works fine.
Good job! :)
