### ISSUE TITLE
RTSP plugin stops streaming after a few seconds

### ISSUE THREAD

**Issue by fbertone** [meetecho/janus-gateway#693]
Hi again,
I'm having a problem with the streaming plugin (RTSP) but I can't understand what is causing it.
Essentially the plugin streams correctly for a few seconds then it "dies" (the image in the browser freeze). It is a server-side problem because even if I reload the page in the browser it will never stream again until I stop the janus gateway and start again. I even tried setting a debug level of 6 (7 it's too much) but I can't find a clue.

Some context:
I'm using live555 media proxy to forward the rtsp stream  from the cam to the server.

CAM -> live555 proxy -> Janus gateway -> browser.

I tried other configurations to understand the problem:
CAM -> Janus gateway -> browser: works just fine
CAM -> live555 proxy -> VLC: works just fine

so it's obviously a problem between the live555 proxy and the janus gateway.

Then I tried to analyze the packets flows with tcpdump.
Apparently the live555 proxy is always sending new packets to the janus gateway, but after a certain amount of time the janus gateway stops forwarding them to the browser.

My idea it that the streaming plugin is not handling properly some message but for now it's just a feeling.
Any suggestion on what should I try to debug the problem?

**Comment by lminiero** [comment]
Check the [admin API](http://www.meetecho.com/blog/understanding-the-janus-admin-api/) to see if video bytes are sent after the freeze or not. You may also want to check via chrome://webrtc-internals (Chrome) or about:webrtc (Firefox), or simly via tcpdump/wireshark to see if the browser is getting data or not. The problem might be in the video bitstream and not Janus itself. Browsers don't support all H.264 profiles as regular RTSP clients typically do.

**Comment by fbertone** [comment]
Hi, thanks for the reply, I'll check the admin API.
However I've already taken the tcpdump path and it seems that is the gateway that stops sending data to the client (browser). 

I'm sure it' not a codec problem because for the first tenths of seconds it works nicely, and if I bypass the live555 proxy (linking directly the gateway to the cam) I have no problems at all.

**Comment by lminiero** [comment]
If it works bypassing a proxy, then it's more likely to be an issue with the proxy, isn't it?

**Comment by lminiero** [comment]
That said, if the Streaming plugin receives data, it definitely forwards it, there's no selective decision in it. My guess is that the proxy stops sending media for some reason (possibly because of some messaging it expects that fails to happen).

**Comment by fbertone** [comment]
I think it is an issue between the proxy and janus (on the janus side) because:
1) cam -> proxy -> vlc streams forever
2) to make things work again I have to restart janus (server side, if I just reload the web page nothing happens). Seems like the plugin hangs or something.
3) from a quick dump **it seems** that the proxy keeps sending UDP packets to janus, but janus suddenly stops forwarding them to the browser. Maybe I'm misinterpreting the dump but I don't think so.

However, it IS possible that the proxy stops sending media, in fact I blindly patched the proxy to try to avoid it closing the session. Maybe I still see packets flowing because of that patch but the session was closed at a higher level (yeah, quite a lot of code hacking going on, but I really can't finde WHERE relies the problem). I will revert the proxy patch to keep things clean.

But still, points 1 and 2 let mi think it's a communication problem between the proxy and janus.

Next week I will make more tests and try to compare the janus dump with a vlc dump to see if some messaging is missing or what.
Sometimes, *around* the time that the freeze happened, in the logs  I saw something like "we have a message to serve: {janus: keepalive}" (can't remember the exact spelling) but I don't know if it's related to the problem and I can't tell if it's a message referring to [proxy -> janus] side or [janus -> browser] side.

**Comment by fbertone** [comment]
OK, comparing janus and vlc dumps I think I found what causes the issue.

When the client (janus or vlc) send a **SETUP** command to initialize the stream, the proxy responds
with a **REPLY** that have a field "Session: <SID>;**timeout=65**"

When I use janus, exactly 65 seconds after the **PLAY** the proxy **PAUSE**s the stream.

With the VLC session I can see a generally richer RTSP/RTCP messaging, but what seems to be periodically sent every 65 seconds from VLC to the proxy is a "GET_PARAMETER rtsp://<URL>" request.

I don't know if it's a standard behavior or it's some customization but I'm pretty sure that's the answer.

**Comment by lminiero** [comment]
Yeah that's probably an application-level keepalive, just to be sure the client is still there. Anyway, as I thought Janus isn't sending anything to the client as at a certain point it's not receiving anything anymore itself.

**Comment by fbertone** [comment]
You surely were right.

According to [RFC 2326](https://tools.ietf.org/html/rfc2326#page-37)

> GET_PARAMETER with no entity body may be used to test client or server liveness ("ping")

[libcurl](https://curl.haxx.se/libcurl/c/CURLOPT_RTSP_REQUEST.html) says that

> Applications wishing to send a heartbeat message (e.g. in the presence of a server-specified timeout) should send use an empty GET_PARAMETER request. 

Seems that libcurl doesn't have the option to automatically handle the keep-alive messages but must be implemented by the application. I was looking for some reference code but couldn't find any at the moment.

I guess this would require a bit more time to implement?
As a quick fix for my problem I will try to disable the timeout altogether on the proxy.

**Comment by lminiero** [comment]
Yep, it should probably integrated in the poll thread to regularly send the keep-alive no later than the negotiated timeout.

**Comment by lminiero** [comment]
Do you have any quick examples on how to set up an RTSP stream and proxy via live555 to replicate and test this? Without that I won't be able to look into how to implement the GET_PARAMETER part, as I wouldn't be able to test anything.

**Comment by fbertone** [comment]
**To build and run the proxy:**

wget http://www.live555.com/liveMedia/public/live555-latest.tar.gz
tar xzf live555-latest.tar.gz
cd live
./genMakefiles linux-64bit
make
./proxyServer/live555ProxyServer -p 8554 [ -u {user} {password} ] rtsp://{origin_rtsp_stream_url} 

You should get the proxed stream at **rtsp://{ip}:8554/proxyStream**
I'm setting the port to 8554 just to not run it as root/sudo
I don't know a public rtsp stream to share at the moment but I can search something or I can try to replicate it otherwise (maybe with live555 Media Server itself?)

Let me know if that's acceptable for you and/or if you need more info.

**Comment by lminiero** [comment]
Implemented in https://github.com/meetecho/janus-gateway/commit/e66c93602733bc3c0e6fa1c144bcf0ae8a5f8959
Seems to work for me so closing. Feel free to reopen if this isn't the case.

**Comment by baudneo** [comment]
Sorry to resurrect a 6 year old issue but I have a question about how this works.

Here is an example SETUP answer from the camera that keeps getting 401 unauthorized every 95 seconds (90 sec timeout + 5 second Janus timeout)

```
 [janus-ZM] [Sun Jan  8 00:00:20 2023] SETUP answer:RTSP/1.0 200 OK
 CSeq: 3
 Date: Sun Jan  8 00:00:19 2023 GMT
 Transport: RTP/AVP;unicast;client_port=16960-16961;server_port=32956-32957
 Session: 3c63232c
```

Am I understanding correctly that the camera is not setting timeout=90; in the session header answer, therefore janus can not calculate when to automatically send a keep alive OPTIONS request? 

`rtsp_session_timeout` seems to be set to 0 be default, meaning no keep alive OPTIONS requests will be sent if a `;timeout=xx` is not set in Session header answer?

```
rtsp_session_timeout = by default the streaming plugin will check the RTSP connection with an OPTIONS query,
        the value of the timeout comes from the RTSP session initializer and by default
        this session timeout is the half of this value In some cases this value can be too high (for example more than one minute)
        because of the media server. In that case this plugin will calculate the timeout with this
        formula: timeout = min(session_timeout, rtsp_session_timeout / 2). (default=0s)
```

Just looking for guidance, thanks.
