### ISSUE TITLE
Second SIP call to SIP Plugin Dangling DTLS Thread/SDP Error

### ISSUE THREAD

**Issue by shrhoads** [meetecho/janus-gateway#696]
To reproduce:

Open two Chrome tabs at:  https://janus.conf.meetecho.com/siptest.html
Use:  
sip:v18.icoa.com  sip:6010@v18.icoa.com 6010 6010   as login #1 
sip:v18.icoa.com  sip:6011@v18.icoa.com 6011 6011   as login #2 

Dial dial 6011 from login #1, works normally
Second call fails with:  DOMException: Failed to set local answer sdp: Failed to push down transport description: Offerer must use actpass value for setup attribute.  (This appears in the #2 console)

The sdp offer has setup:passive instead of setup:actpass

In my logs it looks like there is some state that is not being cleaned up after Janus sip hangup.  The logs are filled with 

[WARN] [6791368214857040] Still waiting for the DTLS stack for component 1 in stream 1...

even though the hangup has been sent to the sip plugin.

**Comment by lminiero** [comment]
Check the Admin API after the hangup and before trying again, to see if the WebRTC stuff is already there, and most importantly if the call was ever established. If it is, something was not cleaned up. Consider that you have to wait about a second before a retry after a hangup, as that's how long the "garbage collector" we have for the WebRTC stuff typically takes to kick in. Trying on the reference counters PR should avoid that limitation.

**Comment by shrhoads** [comment]
I wait a long time usually between calls.  Should the webrtc resources be freed?  I'm not destroying the sip plugin or the session.  Since the sip registration is ongoing between calls, I'm just calling once, doing hangup on both sides then calling again.  I think there is some call state in the sip plugin that isn't reset between calls, but I don't know the code well enough to say for certain.  I think this used to work.

**Comment by lminiero** [comment]
The WebRTC stuff is not handled by the SIP plugin, but by the core. If anything's stuck in this case, it's likely there. To make sure stuff is cleared, also close the PeerConnection in your page, this will trigger a DTLS alert and as a result clean the WebRTC stuff in the core no matter the signalling.

**Comment by shrhoads** [comment]
Ok, I will close this for now and reopen when I get more info.
