### ISSUE TITLE
Memory keeps increasing until the gateway crashes

### ISSUE THREAD

**Issue by cacheworks** [meetecho/janus-gateway#700]
Opening this to not clutter the event-handler pull request as this is happening to me on the main branch as well as described here;
https://github.com/meetecho/janus-gateway/pull/403#issuecomment-260121014
and here;
https://github.com/meetecho/janus-gateway/pull/403#issuecomment-257595550

Memory logs show the following 
![image](https://cloud.githubusercontent.com/assets/13921000/20924853/d3388a58-bbb3-11e6-9d8f-0e77fb233f13.png)

I found some time to block all incoming connections to the gateway as you suggested and shut it down to see if LeakSanitizer showed some useful output. I don't think there's a lot of leaking going on here judging by the bytes but maybe this tells you something useful?

https://gist.github.com/cacheworks/71d58944b27b158149cc9b923bf236ce

I'm running the gateway on Ubuntu 16.04 with Libnice 0.1.13-ubuntu2 if that's useful to know at all. I unfortunately don't (yet) have another production server to offload the traffic to right now to test.

Any suggestions on different versions of libraries to try, or more tips on how to get to the bottom of this leak would be appreciated

Thanks for your time!

**Comment by lminiero** [comment]
One thing that I noticed is that if you compile with AddressSanitizer support, the memory will indeed look like it's constantly growing and never going away. I found about this when doing stress tests that exhibited this behaviour. Anyway, as soon as I compiled _without_ libasan the memory would not grow at all, not even when stress testing with my Jattack tool, and I could see it shrink back when users were going away. My guess is that libasan keeps in memory all info on all allocations, as it needs to keep track of them all to find out about leaks, which explains the memory growth in that case.

Is the memory growing for you even without AddressSanitizer instead?

**Comment by cacheworks** [comment]
It may indeed have been a while since I tried to compile without libasan support as I wanted to catch a crash that seemed to happen after longer uptme
I'll make sure to run it without address sanitizer support this week and see how memory usage behaves then!

Thank you for your insights on stresstesting!
Jattack seems useful to stress test different server configurations, are you planning on sharing the tool later or are you just using it for your own benchmarking?

**Comment by lminiero** [comment]
We don't plan to release it as open source for the near future, sorry.

Anyway, we'll also pay attention to the memory for future tests. We haven't done a lot of stress tests for plain conferencing (many to many), but mostly for one to many scenarios (streaming and videoroom) as from a PeerConnection perspective the concept is the same. Maybe testing the same scenario you're trying to evaluate might show something more.

**Comment by cacheworks** [comment]
![image](https://cloud.githubusercontent.com/assets/13921000/20933730/3dcfd9c8-bbd9-11e6-9d83-9cf36bc4ee77.png)


It seems like the difference shows instantly, the line is just flat now. Seems like I was too obsessed trying to get libasan / leaksanitizer output to try running it without for longer! I hope we can do without or replicate if a new crash pops up
I can't find any other cases of this happening (though finding posts about Libasan causing a memory leak seems difficult due to the keywords)

Could it be that AddressSanitizer gets confused by the way handles are allocated and there's an incompatiblity to use Libasan effectively with Janus? 

It seems like Valgrind would slow it down too much to use it for prolonged periods. I'm open to any suggestions to get more debug info out of this, I'll keep you posted on the stability of this, and will try the refcount branch without Libasan again later

**Comment by lminiero** [comment]
Not sure I understand your latest post. Do you mean that the leak is still occurring even without libasan, and that it's immediately apparent somehow? I'm really dumb when it comes to diagrams like the one you posted (more of a coder kind of guy I'm afraid) so any clarification might help :smile:

**Comment by cacheworks** [comment]
No worries, might've been phrased a bit oddly.

it seems like there is no longer an issue with the memory increasing when running without libasan, if you look at the graph below every instance of the memory climbing up quickly is the gateway crashing or restarting, the last little (nearly)  flat (green and blue) area is the memory usage since we stopped using AddressSanitizer completely 👍 

That raises the question though, is AddressSanitizer causing a memory leak, or is some of the code and memory allocation incompatible with how AddressSanitizer keeps track of that?

I cannot find any posts about AddressSanitizer only being able to run for a few days or causing a leak and it seems like this would prevent us from debugging crashes with libasan that happen after longer periods (so I hope gdb will be enough then) 

![image](https://cloud.githubusercontent.com/assets/13921000/20965025/4f66c7be-bc74-11e6-9d1a-9198f1eddd36.png)

**Comment by lminiero** [comment]
I don't think libasan is leaking: simply it keeps track of EVERYTHING that is allocated since when you start the application, and this results in its internal structures to grow up as time passes. It does this so that when you close the application it can check if any of the allocations that were ever done are still there, and thus report a leak. My guess is that it does NOT get rid of structures related to allocations that were properly deallocated because it also tells you whenever you're using a pointer that was freed before, telling you exactly where that happened in the code: as such, it needs to have a complete history of what happened to every pointer we handled. But again, this is all just my guess of how this works internally, I'm not really an expert of that.

If you recall, we noticed something similar with threads when working on the reference counters branch: https://github.com/meetecho/janus-gateway/pull/403#issuecomment-253330636
With that error you got we found out libasan was also keeping track of ALL threads that were ever spawned by the application, so it makes sense the same is happening for memory allocations too.

**Comment by cacheworks** [comment]
When I hit the limit of the number of threads in AddressSanitizer I was at least able to get output of that and find something saying there actually is a limit there though.

I've been searching around and am unable to find many other posts else talking about the memory constantly increasing with Libasan, I'd expect more mention of memory use if it's normal to use 6 times as much memory
The only post I found that seems relevant is this; https://gcc.gnu.org/ml/gcc-help/2014-04/msg00046.html

Which turned out to be a piece of code that was handled in an inefficient way by AddressSanitizer.
That makes me wonder if any of the memory allocation or freeing done in Janus is causing an unusually large memory usage
It's probably not possible to tell easily with the number of things going on in Janus, was just wondering, maybe I'm missing some obvious documentation or flags here.

We'll see how it runs for now, and see how to debug new issues when they arise, I see Leaksanitizer could be usedon its own without much overhead too, that might come in useful if it happens after long periods

Thanks for bouncing some thoughts back and forth here 👍
