### ISSUE TITLE
--disable-unix-sockets does not disable Unix Sockets

### ISSUE THREAD

**Issue by uxmaster** [meetecho/janus-gateway#701]
After issuing `.\configure --disable-unix-sockets` I still see `Unix Sockets:          yes` in the output.

**Comment by lminiero** [comment]
Probably caused by this commit, https://github.com/meetecho/janus-gateway/commit/8ae5908ef551898dd07c08952ce5729a91b20ea0
I'll check how easy this is to fix.

**Comment by lminiero** [comment]
This commit fixes it for me.
