### ISSUE TITLE
Deprecation Warning on calling detach method on a plugin handle

### ISSUE THREAD

**Issue by amangupta26** [meetecho/janus-gateway#704]
Browser logging following deprecation warning on calling detach method

`janus.nojquery.js:171 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.`

**Comment by amangupta26** [comment]
Does hangup method also tears down the plugin or just unpublish the streams?

**Comment by lminiero** [comment]
Discussed here with a proposed fix, they never got back to me:
https://groups.google.com/forum/#!searchin/meetecho-janus/async%7Csort:date/meetecho-janus/ciuhm-lEoqM/iiIGudLEBwAJ

Let me know if that works for you and I'll merge.

**Comment by amangupta26** [comment]
Yup that worked. I have done something like this though, instead of hardcoding async as `true`

Added an additional parameter to the detach method, which keeps it `undefined` unless explicitly passed
`detach : function(callbacks, async) { destroyHandle(handleId, callbacks, async); }`

Client side code:
`pluginHandle.detach({}, true);`

**Comment by lminiero** [comment]
No need to add an async parameter: `callbacks` is conceived to be an object, which means you can specify properties there as well (as we do when you create a Janus object, for instance). For the time being I'll just add my fix, later on I'll think about adding the parameter you suggested.

**Comment by lminiero** [comment]
Just modified the way `detach` and `destroy` work, by adding a new `asyncRequest` property to what you can pass when you invoke them: this should implement the same behaviour you added with your own patch. The default behaviour is to use an asynchronous request: `onbeforeunload` asks for a synchronous request instead.

Tested briefly and seems to be working for me, let me know if there's something broken.
