### ISSUE TITLE
Janus JS library still works if there is no camera, but user set it as required

### ISSUE THREAD

**Issue by soulfly** [meetecho/janus-gateway#705]
I propose to replace this

`if(!haveAudioDevice && !haveVideoDevice) `

to that

`if((audioSend && !haveAudioDevice) || (videoSend && !haveVideoDevice))`

here https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L1631

in this case, a user will be receiving an error if there is no camera.

**Comment by lminiero** [comment]
Some may like this, some may not, as not failing provides a fallback when something's not available. Anyway, I agree being strict would be better, and it should be the application's responsibility to handle that. On the other hand, we could make that a property, e.g., something like `failIfUnavailable:true|false` that you can use to decide whether to fail if you asked for the webcam and it's not there or not. I'll add this to the TODO list.

**Comment by lminiero** [comment]
Just implemented as two new properties you can set in the `media` object (`failIfNoAudio`/`failIfNoVideo`, both default to false to keep the behaviour as how it was so far) and they seem to work fine in the brief testing I just made. Let me know if that's not the case.

**Comment by soulfly** [comment]
that's great, thanks Lorenzo, going to give it a try
