### ISSUE TITLE
Where are mjr files are stored?

### ISSUE THREAD

**Issue by anildigital** [meetecho/janus-gateway#708]
Hi, 

I am running Janus locally. I ran recordplaytest, but could not find where the video files are stored?

**Comment by anildigital** [comment]
Found, it's in config file for the plugin 

```/usr/local/janus/etc/janus/janus.plugin.recordplay.cfg```

**Comment by oscarvady** [comment]
Anil, that's not an issue. Please, use the mailing list for these
questions. Thanks

2016-12-14 5:13 GMT+01:00 Anil Wadghule <notifications@github.com>:
