### ISSUE TITLE
Janus.js slowLink Call Throws Uncaught TypeError

### ISSUE THREAD

**Issue by joshdickson40** [meetecho/janus-gateway#710]
Seeing `Uncaught TypeError: pluginHandle.slowLink is not a function` pop up in my error console as I try to check some other things out this morning.

It appears that this issue was introduced with my last update to janus.js and adapter.js where `pluginHandle.slowLink(json["uplink"], json["nacks"]);` was added within the `else if(json["janus"] === "slowlink")` check, and that is the offending line. I am still on a custom version based on the final version of the events PR, so it looks like this must have been added to mainline some time before that. Looking at the current janus.js it doesn't look like it has been fixed in a way that would make my code out of date.

**Comment by lminiero** [comment]
You're right, we should have something that checks whether or not the callback exists. The same thing may occur for `mediaState` and a few others, I guess, so we'll have to fix this.

**Comment by joshdickson40** [comment]
I was trying to figure out where the callback was coming from quickly but I didn't have a solid handle on it. My testing is in the latest version of Chrome 55.

**Comment by lminiero** [comment]
It's supposed to be a callback the application sets when creating the handle, e.g., as here:
https://github.com/meetecho/janus-gateway/blob/master/html/echotest.js#L152

Anyway, it's not mandatory, so we have to check if it was set before invoking it. I'll fix this later today.

**Comment by joshdickson40** [comment]
Got it. Missed that. Is there any action to take? Obviously for that example we can print the issue, but are we supposed to do something about it?

**Comment by lminiero** [comment]
No, I'll just push a fix to janus.js: working on that now.

**Comment by lminiero** [comment]
Done, let me know if that fixes it for you, and if so please close this.

**Comment by joshdickson40** [comment]
Okay great, will do. Thank you!

On Fri, Dec 16, 2016 at 10:06 Lorenzo Miniero

<
mailto:Lorenzo Miniero <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Done, let me know if that fixes it for you, and if so please close this.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/meetecho/janus-gateway/issues/710#issuecomment-267613612
, or

**Comment by joshdickson40** [comment]
This looks to be all set, closing.
