### ISSUE TITLE
Does Janus support SRTP to WebRTC transmuxing?

### ISSUE THREAD

**Issue by khatribharat** [meetecho/janus-gateway#711]
I have an H.264 video encoder that's capable of pushing SRTP. I want a video workflow where the SRTP from the encoder is transmuxed to WebRTC for web browsers. I've already tried transmuxing RTP to WebRTC with Janus and it works. Just wanted to know if the secure profile of RTP (SRTP) could be transmuxed to WebRTC or not.

**Comment by lminiero** [comment]
Closing as not an issue. As explained in the guidelines, questions like this have to be made on the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) Google group.
