### ISSUE TITLE
openssl and GPL-3 license incompatibility 

### ISSUE THREAD

**Issue by linuxmaniac** [meetecho/janus-gateway#713]
The GPL (including version 3) is incompatible with some terms of the OpenSSL license, and therefore it is illegal to (re-)distribute janus binaries.

Please consider adding a license exception (or exemption) to explicitly allow linking to OpenSSL as described at https://www.gnu.org/licenses/gpl-faq.en.html#GPLIncompatibleLibs

```
Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or combining it with openssl (or a modified
 version of that library), containing parts covered by the terms of OpenSSL License, the licensors of this
 Program grant you additional permission to convey the resulting work. Corresponding Source for a 
non-source form of such a combination shall include the source code for the parts of openssl used as 
well as that of the covered work.
```

**Comment by lminiero** [comment]
@linuxmaniac thanks for the heads up, I was not aware of this!

So you mean copying the text you suggested after [this lines here](https://github.com/meetecho/janus-gateway/blob/master/COPYING#L405) should fix it?

**Comment by linuxmaniac** [comment]
Yes, I think so.

**Comment by lminiero** [comment]
Just did that, thanks again for reporting the issue!

**Comment by pombredanne** [comment]
@lminiero there is a remaining problem though, you have modified the GPL text in https://github.com/meetecho/janus-gateway/commit/ff4288624944aa985cfe005b38034b82fbe11008
 Your exception should be added after the text or in a separate file because as stated in https://github.com/meetecho/janus-gateway/blob/bfb1560c7b21ff5505c010285d5b1c91fd871e29/COPYING#L5

>  Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

**Comment by lminiero** [comment]
Thanks for the heads up! What do you mean by "after the text" though?

**Comment by pombredanne** [comment]
This would mean to move the exception text from https://github.com/meetecho/janus-gateway/commit/ff4288624944aa985cfe005b38034b82fbe11008#diff-7116ef0705885343c9e1b2171a06be0eR407 to https://github.com/meetecho/janus-gateway/commit/ff4288624944aa985cfe005b38034b82fbe11008#diff-7116ef0705885343c9e1b2171a06be0eR414 either at the end of the COPYING file e.g. here https://github.com/meetecho/janus-gateway/blob/master/COPYING#L682 and with a clear separation or in a separate file.

**Comment by lminiero** [comment]
Should be fixed in the above commit.
