### ISSUE TITLE
Gstreamer app

### ISSUE THREAD

**Issue by kfirbene** [meetecho/janus-gateway#717]
Hi,

I am new to Janus and need assistance.
I have a c++ graphical app on windows that has Gstreamer implemented in it and I switch the pipeline from an xml file.
I installed the compiled for windows version of Janus and I am able to run the demos from my IDE(phpstrom).
I want to stream the video to Janus and write a client side HTML that gets the video.
I could not find anywhere how to stream to Janus and where to set the client url for getting the video on the client side.
Can anyone assist?

Thanks.

**Comment by lminiero** [comment]
Question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus), we use Github only for issues.

**Comment by kfirbene** [comment]
thanks.
