### ISSUE TITLE
Janus crash - : Assertion `value' failed. Jansson

### ISSUE THREAD

**Issue by IvRRimum** [meetecho/janus-gateway#718]
```
janus: dump.c:342: do_dump: Assertion `value' failed.
Aborted (core dumped)
```

Happens whenever i try to leave a room( inconsistently tho ).

Any ideas? Someone had the same thing?

**Comment by lminiero** [comment]
We don't have any dump.c file in our project, so no idea where that comes from. You'll probably have to use gdb to check what's wrong: https://janus.conf.meetecho.com/docs/debug

**Comment by IvRRimum** [comment]
I think it is from jansson. Jansson has that file.

**Comment by lminiero** [comment]
Have you checked with gdb to see if a backtrace can explain what leads to that crash over there?

**Comment by IvRRimum** [comment]
What is gdb? Some debug log?

**Comment by IvRRimum** [comment]
P.S i merged latest changes into the project. Still experience crashes. Maybe its setup related?

**Comment by lminiero** [comment]
https://janus.conf.meetecho.com/docs/debug

**Comment by IvRRimum** [comment]
I hired a guy to do the job. So far looks like jansson was the problem. After removing the old jansson and installing libjansson-dev_2.9-1_amd64.deb and libjansson4_2.9-1_amd64.deb i dont see any crashes. Will continue to test and report here.

**Comment by lminiero** [comment]
Thanks, looking forward to that!

**Comment by IvRRimum** [comment]
Confirmed that jansson was the problem. We ran server for 2 days and tryed to crash it multiple times, by spamming stuff. We got as mutch as 25 people in one room. No crashes.

**Comment by lminiero** [comment]
Cool! I guess we can close this issue then.
