### ISSUE TITLE
When the plugin: textroom signaling field error, the client prompt string display incomplete

### ISSUE THREAD

**Issue by woo-fight** [meetecho/janus-gateway#720]
Char * error_cause = g_malloc0 (512);  in line 1413 of textroom.c,
char * can not be used because sizeof (error_cause) is used in JANUS_VALIDATE_JSON_OBJECT.
Once an error is detected this causes the returned string to be truncated.

**Comment by lminiero** [comment]
You're right, that should be `char error_cause[512];`, fixing that.
