### ISSUE TITLE
provide manpage for janus

### ISSUE THREAD

**Issue by linuxmaniac** [meetecho/janus-gateway#723]
Please provide a good old manpage for janus executable

**Comment by lminiero** [comment]
Will work on that after the holidays :wink:

**Comment by lminiero** [comment]
Just implemented as a PR in #726, can you check it's in line with what you'd expect out of a manpage? It's my first attempt to write one ever, so there may very well be something wrong or missing.

**Comment by linuxmaniac** [comment]
Fixed by  8485d09
