### ISSUE TITLE
No Video Shown on Streaming Demo with RTSP link.

### ISSUE THREAD

**Issue by barisvelioglu** [meetecho/janus-gateway#725]
Hi,

I added the code below to janus.plugin.streaming.cfg. No error on janus terminal occured.

```
[rtsp-test]
type = rtsp
id = 99
description = RTSP Test
audio = no
video = yes
url=rtsp://mpv.cdn3.bigCDN.com:554/bigCDN/definst/mp4:bigbuckbunnyiphone_400.mp4
```

I started to stream and it did without any error but nothing shown the screen. Just loading gif. I check the rtsp link with vlc player and its working.

![image](https://cloud.githubusercontent.com/assets/1805891/21581257/d25fcf54-d032-11e6-9ae2-a02748f6b199.png)

**Comment by lminiero** [comment]
Not a code issue so doesn't belong here. Ask on the [group](https://groups.google.com/forum/#!forum/meetecho-janus)
