### ISSUE TITLE
Couldn't access event handler plugins folder...

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#728]
Hi

Missing events_folder from janus.cfg example file.

[source](https://github.com/meetecho/janus-gateway/blob/6a998158ab0137ef2faa5bb377902bedf0f7e089/janus.c#L3676)

**Comment by lminiero** [comment]
Right, we're missing the placeholder: it still points to the default folder anyway, so there's no harm in it not being there. I'll add it after [this line](https://github.com/meetecho/janus-gateway/blob/master/conf/janus.cfg.sample.in#L9) when I get back to the office.
