### ISSUE TITLE
To fix JS documentation: getBitrate() works well for Firefox

### ISSUE THREAD

**Issue by soulfly** [meetecho/janus-gateway#730]
https://janus.conf.meetecho.com/docs/JS.html

there is a sentence: 

> getBitrate(): gets a verbose description of the currently received stream bitrate (only available on Chrome, for now);

but it works well on Firefox

**Comment by lminiero** [comment]
Yeah, that line is outdated and dates back to when we wouldn't do a getStats from Firefox. Will update.
