### ISSUE TITLE
Uncaught TypeError: r.slowLink is not a function

### ISSUE THREAD

**Issue by jasonblais** [meetecho/janus-gateway#733]
**Background**

Mattermost uses this Janus server as a WebRTC gateway for a preview feature of audio and video calls. We're using the official janus javascript library to create the sessions and establishing the webrtc connection between the peers, with limited changes.

Things have been working fine until updating to the latest Janus server earlier this week. Since then, we've received continuous `Uncaught TypeError: r.slowLink is not a function` JavaScript errors during a call.

Would you have any hints why these errors might be occurring, and how to fix them?

PS: There are also some issues with audio and video, but we're investigating whether those issues are on our end. Also began after the latest server update.

**Comment by lminiero** [comment]
Is your janus.js up to date? This was addressed and fixed in #710

**Comment by jasonblais** [comment]
We used version 0.21, your latest release. Are you planning to do a new release soon, or should we use your `master` branch instead?

**Comment by lminiero** [comment]
Using the latest janus.js should be enough, no need to update to master the rest of the code.

**Comment by jasonblais** [comment]
Okay, we'll try that. Thanks @lminiero!

**Comment by lminiero** [comment]
Closing since, as discussed, it should have been fixed for some time already. Feel free to reopen if that's not the case.

**Comment by jasonblais** [comment]
Sorry @lminiero, forgot to come back --> the issue is indeed fixed, thank you!

**Comment by karthik-aiyer-fujixerox** [comment]
@lminiero you mentioned we need to get the "latest" janus.js. 

Correct me  if I'm wrong, isn't the janus.js in 0.2.1 the latest? I see you have answered this same question earlier but i don't fine the "slowLink" callback handled in the 0.2.1 tag. It seems to be present in master, but then the master code for janus.js is not adding adapter.js atall and hence all the references of "adapter" object are failing!

**Comment by lminiero** [comment]
No, by latest I always mean master.

**Comment by lminiero** [comment]
The adapter is now imported in the html file.
