### ISSUE TITLE
ICE only works when fastly answered 

### ISSUE THREAD

**Issue by jlmari** [meetecho/janus-gateway#738]
Hi, the problem is that ICE connection only works if answered before 15s to allow permissions with the parameter trickle:true. I commented the issue https://github.com/meetecho/janus-gateway/issues/286, but I thought that it should be needed to open a new issue to this since I was capable to also reproduce the error in the Janus Demo Site

To reproduce the error on the VideoCall demo:
- Both caller and responder open the URL https://janus.conf.meetecho.com/videocalltest.html, start and write the nicknames
- Caller: Call using the nick of the responder and take the time you want to allow permissions
- Responder: Wait until more than 15 seconds and allow permissions

The call with "start" but anyone of them could see each other (br = 0kbps)

However, if the responder takes less than 15 seconds it will work correctly. 
Also, the problem is solved creating offer with trickle:false

**Comment by lminiero** [comment]
Looks like a browser-related issue, as trickle:false in janus.js simply instructs the browser to put all the candidates in the SDP instead of trickling them as they become available. Nothing changes in Janus itself, I believe. Have you checked the browser internals (webrtc-internals or about:webrtc) to see if they say something about the ICE state changes?

**Comment by jlmari** [comment]
Hello @lminiero , thanks for the qu
![caller](https://cloud.githubusercontent.com/assets/23699748/21803747/c66c9998-d72b-11e6-885d-227bc1b92384.png)
![responder](https://cloud.githubusercontent.com/assets/23699748/21803748/c66d3290-d72b-11e6-876b-16bca7af40ff.png)

ick answer. About the browsers, I can tell you the versions I have checked:
- Chrome: 55.0.2883.87
- Firefox 50.1.0
In both the error sames to be the same.

I also checked the browser internals on Chrome and I couldn't see anything strange, but I will attach the screenshots since I am not an expert on this field and maybe you or others are able to notice something unusual.

**Comment by lminiero** [comment]
Sorry for this late answer, looks like I missed this message. Have you tried if pure P2P calls answered more than 15 seconds later exhibit the same behaviour?

**Comment by jlmari** [comment]
Hello again @lminiero . Yes, I tried it and it seems that the pure P2P calls using WebRTC do not have this problem.

**Comment by lminiero** [comment]
I'll try to replicate this myself in the next few days to see if I spot anything weird.

**Comment by jlmari** [comment]
OK, I will continue watching for more relevant details. If you have troubles replicating the error, you can tell me and I will help as much as I can.

**Comment by lminiero** [comment]
It looks like the cause are missing remote candidates for the caller (the one that ends up waiting for more than 15s for an answer). Not sure why that's happening, but that would explain why when using trickle:false it works: in fact, in that case the offer would contain the candidates and so ICE would start. Here, instead, trickling never seems to occur, or maybe it does but Janus discards the packets. As a result, Janus is unaware of remote candidates, and so for the caller ICE is never started (ICE disconnected in the Admin API).

I'll try and see why that's happening in the next few days.

**Comment by lminiero** [comment]
Darn, I should really remember my own code... :wink: 
https://github.com/meetecho/janus-gateway/blob/master/janus.c#L1225
https://github.com/meetecho/janus-gateway/blob/master/janus.c#L2888
We really do discard candidates 15 seconds too "old"... not exactly sure why we did that, but I think it was to avoid situations where trickle candidates from a previous session and not properly removed would be mixed with legitimate candidates for a new PeerConnection. As such, I guess we should just increase that time check, rather than removing entirely. Maybe make that 45/60 seconds?

Anyway, can you try replacing that `15` with, let's say, `150`, and let me know if that fixes it for you?

**Comment by jlmari** [comment]
Great @lminiero , you just hit the nail on the head. I changed both 15s values to 150s and it seems that now the connection is working even if the caller waits more than the 15s. 

Yes, it seems that maybe increasing the time check would be a solution for that and maybe searching for a new complementing criteria to destroy the trickle candidate more accurately. Right now, I can only suggest something like when a session with a trickle candidate starts, destroy the others? but it is not a 100% solution for this question. Surely you can find a better one than me!

Thanks for the answer and the great work done with Janus, it really is very impressive :)

**Comment by lminiero** [comment]
> Right now, I can only suggest something like when a session with a trickle candidate starts, destroy the others?

That already should be happening, so I'm trying to remember the exact reason for that timer. I can't find any additional info in my notes. For the time being, I'll _fix_ this by changing 15 to 45. As soon as I have some more time to debug, I'll also try and remove that check entirely to evaluate the implications.
