### ISSUE TITLE
audiobridge with videocall plugin does not work

### ISSUE THREAD

**Issue by doonfrs** [meetecho/janus-gateway#743]
Hi;
Thank you for great gateway, this saved my project.

I am working on voice room chat, it works great, but now I have to enable video chat one-way as guest ask the other guest for camera, the second party will approve.

it works also, except when I load videocall plugin, audiobridge stop sending voice.
what do you suggest ?

**Comment by alexamirante** [comment]
We use GitHub for code issues only. Please ask this kind of questions on the [meetecho-janus](https://groups.google.com/forum/m/#!forum/meetecho-janus) forum.
