### ISSUE TITLE
audiobridge plugin, control from server

### ISSUE THREAD

**Issue by doonfrs** [meetecho/janus-gateway#744]
Hi;
Is it possible to grant the mic for only one guest in the room, and control it via server.
I implemented the solution from client side, but it is not secure as room guests may play with the console to enable the stream.

Thank you!

**Comment by alexamirante** [comment]
We use GitHub for code issues only. Please ask this kind of questions on the [meetecho-janus](https://groups.google.com/forum/m/#!forum/meetecho-janus) forum.
