### ISSUE TITLE
Rtsp with Gstreamer

### ISSUE THREAD

**Issue by mustafayuce33** [meetecho/janus-gateway#747]
Hello, 

First sorry for my bad english. We are trying to sink rtsp stream to janus-gateway. We are now successfully direct rtsp to janus by gstreamer. When we try to see stream on janus web interface it is saying that  "Stream Started" but nothing seems on screen. When we look at janus console logs it is capturing some of the packages successfully but for some packages it is giving error like this ;

gst-gstream] New video stream! (ssrc=19685404)
[ERR] [ice.c:janus_ice_send_thread:3586] [6611692869529667] ... SRTP protect error... srtp_err_status_bad_param (len=11-->11, ts=1989000, seq=442)...

Bye the way we are starting stream with gstream with the following command;

gst-launch-1.0 rtspsrc location=rtsp://192.168.1.235:554/h264_stream ! rtph264depay  ! h264parse ! udpsink host=127.0.0.1 port=9999

And also we have the following config;

[gst-gstream]
type = rtp
id = 5
description = Gstream
video = yes
videoport = 9999
videopt = 96
videortpmap = H264/90000
videofmtp = profile-level-id=42e028\;packetization-mode=1

What might be the reason of this situation ?

**Comment by lminiero** [comment]
We use GitHub for code issues only. Please ask this kind of questions on the [meetecho-janus](https://groups.google.com/forum/#!forum/meetecho-janus) forum.
