### ISSUE TITLE
Crash on disabled event backend using video call

### ISSUE THREAD

**Issue by mirkobrankovic** [meetecho/janus-gateway#749]
As title exaplins how to reproduce.
I didn't had issues with videoroom plugin
gdb trace
https://gist.github.com/mirkobrankovic/46a56117b9b81c9b21b33bf7bd35b96d

**Comment by lminiero** [comment]
@mirkobrankovic any update on the gdb info I asked about on the gist?

**Comment by lminiero** [comment]
Nevermind that, I managed to replicate the issue and fix a couple of typos that caused the crash. Feel free to reopen if it's still happening to you!

**Comment by mirkobrankovic** [comment]
oh sorry i wasnt notified for some reason for these messages :(
