### ISSUE TITLE
random_uint IDs allow collisions in video room

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#755]
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2882

the audio/video ssrcs as well as the new publisher->pvt_id could possibly collide with other publishers.  Not sure if this matters?

**Comment by lminiero** [comment]
SSRCs are overwritten by the core. Apart from that, they're per room values, and with a 32-bit (SSRC) and 64-bit (private ID) space it's hard for them to collide.

**Comment by chadfurman** [comment]
Hard, but not impossible.  In other places, you check to see if they collide, and simply re-roll when it happens.

**Comment by lminiero** [comment]
That would also force us to have an additional map for private IDs though. I'll add this to the TODO list.
