### ISSUE TITLE
No check after malloc in videoroom plugin

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#756]
https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L2982

If there's a memory error, this will segfault

**Comment by lminiero** [comment]
I had this discussion with a user on this some time ago. I had checks on the return value from allocations all over the place, and he suggested most were unneeded, as if it really returns NULL it's an out of memory error, which means the application will crash anyway. As such, in some new code I didn't add any controls over that. Do you believe we should have those checks instead?

**Comment by chadfurman** [comment]
I was taught by my professor that if you don't check the return value of malloc, the world will end.

If you _always_ check the return value of malloc, the program... might not... crash.  It just will stop behaving as expected....

**Comment by lminiero** [comment]
That's what I knew too and what I argued, but his argumentations convinced me. Searching around it looks like it's still an active discussion among other developers as well, e.g., those mentioning overcommits and stuff like that as a rationale behind the fact you may not need to check those values at all.

Anyway, I guess I agree checks probably don't harm, so I'll slowly add them back in when I have some time to check the whole code (help on that is appreciated of course!). Besides, I'll have to make sure the if(not) contents are coherent in branches like the reference counter: if there we need an unref, for instance, that in master isn't there, and it just merges cleanly, I'll also have to look into all the changes there.

**Comment by lminiero** [comment]
In order to avoid problems like those, I'll only restore those checks in the reference counters branch, and leave master as it is. This way, when reference counters are merged eventually, we'll have that sorted out too.

**Comment by chadfurman** [comment]
That makes sense. I just merged in reference counters to our codebase this week. Still trying to make heads or tails of it. Looks like I need to rethink how I destroy all my data structures. I did get the conflicts resolved. Regardless, this would be a Google groups discussion separate from this ticket haha

**Comment by lminiero** [comment]
> Still trying to make heads or tails of it. Looks like I need to rethink how I destroy all my data structures.

Yeah, it is indeed a big change in how memory is managed, which is one of the reasons it's taking a while before this is merged. I want to be sure we're not introducing leaks, rather than solving them, and making sure we ref/unref properly in all cases. For this testing from multiple parts can indeed help, so thanks for giving it a try.

That said, I added the `g_malloc0` checks. I'll probably have to do the same for stuff like `g_strdup()` and `json_object()`, among others, but I'll do that some other time.

**Comment by uxmaster** [comment]
Checking `g_malloc` return value against `NULL` is useless, unless you want to check if you are trying to allocate 0 bytes, since this is the only case when the function returns `NULL`.
Vide the source code: https://sourcecodebrowser.com/glib2.0/2.27.4/gmem_8c.html#a7a4d0e5bfab2055a3795572583482982

More bibliography:
http://stackoverflow.com/a/4042742
https://bugs.launchpad.net/eljardin/+bug/503086

**Comment by lminiero** [comment]
Meaning I did all that for nothing? :wink: 
Thanks for the pointer: what is returned then when it gets to `g_error ("%s: failed to allocate %"G_GSIZE_FORMAT" bytes", G_STRLOC, n_bytes);`?

**Comment by lminiero** [comment]
Ok, in the second link I read:

    Use g_try_malloc() and g_try_malloc0() instead, which will return NULL if memory
    allocation fails, and will not abort the execution of the program.

as apparently `g_malloc0` simply calls `g_error` and triggers a `SIGABRT` when no memory is available. So maybe we should simply change all `g_malloc0` to `g_try_malloc0` to match it to our checks and try to do things a bit more cleanly?

**Comment by lminiero** [comment]
That may not be worth the trouble, as there's no `g_try_strdup` version of `g_strdup`, which probably calls `g_malloc` internally... http://stackoverflow.com/a/7419274

**Comment by uxmaster** [comment]
Yes, `g_strdup` uses `g_malloc`. I cannot think of other way than to abort at memory allocation errors.

**Comment by lminiero** [comment]
Closing as there's no immediate plan to change the way we do allocations, although I'll keep it in mind.
