### ISSUE TITLE
Janus has only host type ICE address in SDP offer?

### ISSUE THREAD

**Issue by gzhang0723** [meetecho/janus-gateway#761]
From my understand, Janus only has host type ICE address in SDP offer. Is that true or I am missing something? If there is a public IP and Janus is not behind the NAT, it will work. However, what if the Janus is on the embedded device and behind NAT, it will not always work. 

Thanks,

**Comment by lminiero** [comment]
If Janus is behind a NAT, that's what [these settings](https://github.com/meetecho/janus-gateway/blob/master/conf/janus.cfg.sample.in#L79) are for.

Closing as not a code issue.

**Comment by gzhang0723** [comment]
Thank you so much Lorenzo. 

The issue initially showed as " ICE Failed in component 1 stream 1" . After changing the cfg file, there are more ice candidates for janus.  

However, if I want to add multiple stuns, will that be possible? What will be syntax for that? Also do you think multiple stuns in different geographic location will do any good? For example, will it possible to increase the number of the ICE candidates and thus provide a link that is more close to the user? 

Thanks,

**Comment by lminiero** [comment]
That's somethng you configure on the user's side, not Janus'... in janus.cfg you only configure the server Janus itself will use.
