### ISSUE TITLE
Performance is really slow

### ISSUE THREAD

**Issue by gzhang0723** [meetecho/janus-gateway#762]
With raw connection (gstreamer to gstreamer at two different pc), the results are pretty smooth with bitrate like 2000000 with VGA resolution. But if I use Janus, the picture is almost static. Where can I start to debug this? Nload results shows that there are about 2M bw from Janus out. That should not be too bad. Is it possible that package drop or maybe the browser does not decode it well?

**Comment by gzhang0723** [comment]
my setup is like this 
On capture device: gstreamer -> janus - > inter_comm app (an app to connect janus with the signal server) 
On cloud, there is signal server
On PC, the broweser get the Janus video. And currently it is really slow. 

What kind of log or thing that is needed to start on debug on it? I am guessing maybe on the broswer side there are packet loss or decoder is not efficient. Maybe it is a sw decoder because the gstreamer encoder is not compatible with it?

**Comment by lminiero** [comment]
Again, not a code issue: please use the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for questions like these.
