### ISSUE TITLE
Segfault when joining videoroom in refcount branch

### ISSUE THREAD

**Issue by cacheworks** [meetecho/janus-gateway#763]
Hello,

I was doing some testing and updated the refcount branch to 230660d2fbfd0834759783a534352e329a96a65e and got the following segfault when joining videoroom;
https://gist.github.com/cacheworks/2981f94b448c648c9a239701da8ee05e

Looking at the issue that prompted the commit it might still be a work in progress, just making sure you're aware. I wasn't able to spot the issue there yet.

I confirmed f86200fcca3f329b7f6061059508ed08778bc4e7 does not have this issue so am using that for now

Thanks!

**Comment by lminiero** [comment]
Sorry for this late comment, I've been abroad for an event. I'll look into this tomorrow.

**Comment by lminiero** [comment]
Could replicate the issue, introduced after a recent merge from another PR, and should have been fixed in this commit here: https://github.com/meetecho/janus-gateway/pull/403/commits/e139673ec11bacdf4400987d93a50f42e90d0884
Can you confirm it works for you as well now?

**Comment by cacheworks** [comment]
That indeed fixes this crash, thanks a lot for taking the time to have a look at this :+1:
