### ISSUE TITLE
refcount increase without a corresponding decrease (maybe?)

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#764]
Admittedly, I'm still wrapping my mind around the refcount stuff.  That said, here is where I see the increase:

https://github.com/meetecho/janus-gateway/blob/refcount/plugins/janus_videoroom.c#L2780

I don't see a `janus_refcount_decrease()` or a `g_clear_pointer()` for the &videoroom object here.  Maybe the refcount should be decreased at the end of the queue loop?  Or somewhere else?  I don't really know.

I do know that I have 10 references to my videoroom when everyone leaves the room -- this is _likely_ my fault, but I'm also suspicious of the aforementioned line.

Thank you for your time and all of your hard work!

**Comment by chadfurman** [comment]
Follow-up: adding a janus_refcount_decrease(&videoroom->ref) just above line 3094 here:

https://github.com/meetecho/janus-gateway/blob/refcount/plugins/janus_videoroom.c#L3094

and just above line 3103 here:
https://github.com/meetecho/janus-gateway/blob/refcount/plugins/janus_videoroom.c#L3103

causes a segfault when you leave the room and come back (but it does adjust the videoroom reference to 0)

**Comment by chadfurman** [comment]
Closing this.  I'm not sure how, but the refcount is hitting 0 even with this "increase" in place.  Not sure where it's being decreased, but it is...

**Comment by lminiero** [comment]
Hope this has all been addressed in the response on the PR itself.

**Comment by chadfurman** [comment]
Yes, I think so... :)
