### ISSUE TITLE
textroom plugin 'list' command doesn't seem to work

### ISSUE THREAD

**Issue by thehunmonkgroup** [meetecho/janus-gateway#766]
I'm able to successfully execute 'list' commands to the videoroom and audiobridge plugin, however using the same code with the textroom plugin fails.

Here's the output when I execute list on a videoroom plugin handle:

```
debug: Executing Janus videoroom plugin command with message: {"request":"list"}
Sending message to plugin (handle=312643734989790):
{ janus: 'message',
body: { request: 'list' },
transaction: 'cuUwzTs1E2DR' }
Got a success on session 1169148762667865
{ janus: 'success',
session_id: 1169148762667865,
sender: 312643734989790,
transaction: 'cuUwzTs1E2DR',
plugindata:
{ plugin: 'janus.plugin.videoroom',
data: { videoroom: 'success', list: [Object] } } }
Message sent!
{ janus: 'success',
session_id: 1169148762667865,
sender: 312643734989790,
transaction: 'cuUwzTs1E2DR',
plugindata:
{ plugin: 'janus.plugin.videoroom',
data: { videoroom: 'success', list: [Object] } } }
Synchronous transaction successful (janus.plugin.videoroom)
{ videoroom: 'success',
list:
[ { room: 1234,
description: 'Demo Room',
max_publishers: 6,
bitrate: 128000,
fir_freq: 10,
audiocodec: 'opus',
videocodec: 'vp8',
record: false,
num_participants: 0 } ] }
RETURN DATA
{ videoroom: 'success',
list:
[ { room: 1234,
description: 'Demo Room',
max_publishers: 6,
bitrate: 128000,
fir_freq: 10,
audiocodec: 'opus',
videocodec: 'vp8',
record: false,
num_participants: 0 } ] }
```

And then running the same list command on a textroom plugin handle:

```
debug: Executing Janus textroom plugin command with message: {"request":"list"}
Sending message to plugin (handle=759819753124802):
{ janus: 'message',
body: { request: 'list' },
transaction: '6p1uVgMZAz14' }
Got an ack on session 4303262646572199
{ janus: 'ack',
session_id: 4303262646572199,
hint: 'I\'m taking my time!',
transaction: '6p1uVgMZAz14' }
Message sent!
{ janus: 'ack',
session_id: 4303262646572199,
hint: 'I\'m taking my time!',
transaction: '6p1uVgMZAz14' }
RETURN DATA
undefined
```

I'm running v0.2.1 but a quick ```git diff v0.2.1..master plugins/janus_textroom.c``` doesn't show any changes to the list case of the handler, so I think this is a bug?

**Comment by thehunmonkgroup** [comment]
Well, I seem to have figured this out. From the textroom doc:
```
The only message that is sent to the plugin through the Janus API is a "setup" message, by which the user initializes the PeerConnection itself. Apart from that, all other messages are exchanged directly via Data Channels.
```
Which I guess means that you can't communicate directly with the handler to do things like create, delete, and list text rooms. This is a real bummer, because it makes creating them programmatically from the server side much harder.

Are there any plans to integrate CRUD operations directly into the textroom plugin like they are with the videoroom and audiobridge plugins?

**Comment by lminiero** [comment]
That's a good point. I guess at least `create`, `destroy` and `list` could be added to the handle communication itself. I'll add this to the TODO list.

**Comment by thehunmonkgroup** [comment]
I'd also suggest you add ```exists``` -- it's an easy one and useful to prevent duplicate create/destroy errors!

**Comment by lminiero** [comment]
Already done that, I'm about to publish a PR in the next few minutes.

**Comment by lminiero** [comment]
Done, please test and let me know if that works as expected.

**Comment by lminiero** [comment]
Closing as addressed in the PR.
