### ISSUE TITLE
[renamed] Configurable media timeouts

### ISSUE THREAD

**Issue by bhakimi** [meetecho/janus-gateway#771]
we could use this feature also, any chance this can be added to the project?

https://groups.google.com/forum/#!msg/meetecho-janus/U47gFCFreqw/t0PtQjgpBAAJ

**Comment by lminiero** [comment]
Closing as we only use Github for issues. Please keep discussions like this on the group.

**Comment by lminiero** [comment]
Thinking about it, it makes sense to have an issue here as a reminder, as that might be a useful feature. Could you rename the issue to something that refers to its purpose, e.g., "Configurable media timeouts"?

**Comment by lminiero** [comment]
Done, please test and let us know if it works as expected.

**Comment by bhakimi** [comment]
will test out in a few days, thank you for the prompt response

**Comment by bhakimi** [comment]
just to be clear, i can set this in janus.cfg right?

**Comment by lminiero** [comment]
Yeah https://github.com/meetecho/janus-gateway/pull/773/files#diff-92061b7f60d74c096d2180c059d27a15R66

**Comment by lminiero** [comment]
Closing as addressed in #773 which we merged.
