### ISSUE TITLE
please include source for code not authored here

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#778]
Hi,

Some code is included from external projects, but has been included here in a non-source form.

A simple example is html/jquery.min.js which has been "minified": It is technically possible but not easy to edit that code.

Another less obvious example is html/js/bootstrap.js which is not minified but still concatenated together, which is not the format upstream uses for development: It is easy to edit that code, but such changes are not easy to pass upstream.

Some distributors - Debian in particular - insist on redistributing as "source" only code which the authors consider _their_ source.

Please - if not for easing development without fragmentation, then for ease of redistribution - include _upstream_ source for all included code not authored here.

**Comment by lminiero** [comment]
Thanks for the feedback.

The web demos are there only for ease of playing with the server: the "actual" Janus is the C core and its plugins, nothing else. That's why the JS files are the way they are: the first time I worked on some demos, I used the libraries I already had available at the time in some test setups and was more familiar with (bootstrap and jquery, mostly, as I'm a lazy JS developer!) and they stayed pretty much the time since. I can't remember where I got most of them from, but I think jquery.min.js came from their site (from some time ago, obviously), while bootstrap.js is the version shipped, I believe, with the [template](https://bootswatch.com/cerulean/) I used (not sure if they did something different with the sources).

Not exactly sure on what I should do to fix this: does upstream in this context mean updating, e.g., jquery in this repo everytime it's updated itself? I personally don't have the energy nor the time to follow up on everything we use in the demos (which don't need anything but the basic stuff anyway). Or did you mean something different?

PRs to fix the current state would be very welcome of course.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2017-02-13 14:33:09)
> Thanks for the feedback.
> 
> The web demos are there only for ease of playing with the server: the 
> "actual" Janus is the C core and its plugins, nothing else.

Understood.  And those demos are highly appreciated!


> That's why the JS files are the way they are: the first time I worked 
> on some demos, I used the libraries I already had available at the 
> time in some test setups and was more familiar with (bootstrap and 
> jquery, mostly, as I'm a lazy JS developer!) and they stayed pretty 
> much the time since. I can't remember where I got most of them from, 
> but I think jquery.min.js came from their site (from some time ago, 
> obviously), while bootstrap.js is the version shipped, I believe, with 
> the [template](https://bootswatch.com/cerulean/) I used (not sure if 
> they did something different with the sources).

Perfectly understandable.  

The issue raised here is not that your web development style is "wrong". 
I appreciate your being sloppy with web development: I take that as 
indication you spend more of your precious time on the C code! ;-)

The issue is that when you _include_ code you did not author yourself, 
then that code comes with licensing terms and (arguably) other concerns 
not in your control.


> Not exactly sure on what I should do to fix this: does upstream in 
> this context mean updating, e.g., jquery in this repo everytime it's 
> updated itself? I personally don't have the energy nor the time to 
> follow up on everything we use in the demos (which don't need anything 
> but the basic stuff anyway). Or did you mean something different?

The issue here is not the quality of your demos: They are valuable even 
if non-working!  The issue is your inclusion of some code in a form only 
adequate for consumption but not really Free (as in speech).

Simplest¹ is to only include code authored as part of this project - 
only reference other code.

You can "reference at build time": Include a shell script to download 
the files needed from external projects.

Or you can "reference at runtime": Link to external stylesheets, fonts 
and javascript from online hosting services like https://cdnjs.com/ .

you can do both: For each ressource first link to local file(s) and 
immediately below that to online resource.

These are the files I have identified as being arguably problematic:

 html/fonts/*
 html/js/*
 html/adapter.js
 html/jquery.min.js


> PRs to fix the current state would be very welcome of course.

I prefer to not get too entangled in Github, but if I cannot persuade 
you (or others reading this) to do it then I'll reconsider...


 - Jonas

¹ No, the _very_ simplest is obviously to just ignore this issue :-P

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by lminiero** [comment]
Thanks for the clarifications, they're quite helpful!

> Or you can "reference at runtime": Link to external stylesheets, fonts
> and javascript from online hosting services like https://cdnjs.com/ .

I guess this is the easiest way forward, I'll work on a PR that does that as soon as I have some time.

**Comment by jonassmedegaard** [comment]
there's also html/jquery.blockUI.js - not an issue for Debian specifically (because the code is in the form upstream treats as source) but still external, and available online: https://cdnjs.com/libraries/jquery.blockUI

**Comment by jonassmedegaard** [comment]
uhm, and as a sidenote: I do not consider everything html/* as only "demos": html/janus.js and html/janus.nojquery.js is nice reusable code IMO!

**Comment by jonassmedegaard** [comment]
I realize I contradicted myself: If I really want you to keep attention to the C code, I should make you that PR.

I will try do that now...!

**Comment by lminiero** [comment]
Yep, that's right, and the different licensing we mention is actually referring to those two libraries and the demos themselves. But as you pointed out, having js files from third parties could make it appear the same licensing applies to them as well which isn't the case.

I'm taking note of what I'll have to reference externally. I don't expect problems with anything except adapter.js, which we did modify in some parts for better Edge interoperability, and which is not safe to simply take in its more recent form. I'll see what can be done with that.

**Comment by lminiero** [comment]
> I will try do that now...!

No problem, it shouldn't take much and I'm taking some notes already. Hopefully I'll have something ready by today: I'd only ask you to give a look at the PR once it's ready to be sure it's fine.

**Comment by jonassmedegaard** [comment]
ohh - you hacked adapter.js? I didn't think of that possibility - thanks for mentioning!

**Comment by jonassmedegaard** [comment]
ok, good.  I'd be happy to test!

**Comment by jonassmedegaard** [comment]
not sure, but your tweaks to adapter.js might be addressed in newer releases of that project (and if not you'd better pass such tweaks upstream instead)

**Comment by lminiero** [comment]
With a dynamic environment as WebRTC, where features appear and go away overnight, that's a bad idea. I'll have to think of something else.

**Comment by jonassmedegaard** [comment]
sorry, I lost you: What do you find a bad idea? To use a CDN? To pass bugfixes to adapter.js upstream?

**Comment by lminiero** [comment]
It's not bugfixes, but tiny changes needed to better interact with Janus from Edge, that don't always merge well with other usages in other contexts. Using the latest adapter.js here would not work as there are often slight changes in the API that break web apps. Can't recall what we did exactly, I'd have to check back in the logs to be sure.

**Comment by jonassmedegaard** [comment]
When adapter.js is a fork, then please do include it: Its "source according to upstream" is then its current form, because _you_ are its new upstream maintainer of this fork.

I have opened a separate issue about clarifying adapter.js not being a simple code copy like other files included with those demos.

**Comment by lminiero** [comment]
Please test #780, I won't merge until I'm sure no demo or documentation file is broken.

**Comment by jonassmedegaard** [comment]
looks good to me.

What I tested was interactively browsing through all pages, checking in Firefox debug for broken links or failing javascript code.

I did not test all functionality - because my server setup do not match the demo references - but assume that to not be affected by your changes here.

One minor detail I spotted: html/docs/index.html references css/demo.css which is broken - it should instead reference ../css/demo.css

**Comment by lminiero** [comment]
> One minor detail I spotted: html/docs/index.html references css/demo.css which is broken - it should instead reference ../css/demo.css

Tnx, fixed :+1: 

> I did not test all functionality - because my server setup do not match the demo references - but assume that to not be affected by your changes here.

I'll have to make a test of all demos then... will do that when I have some time.

**Comment by jonassmedegaard** [comment]
html/docs/index.html link to demo.css is correct now, but two other links are broken: to navbar.html and footer.html (sorry I missed those earlier).

**Comment by lminiero** [comment]
Externalized adapter.js too. I don't have time to check if this breaks things in any of the demos with some browsers, as I'm at the airport. Please test.

**Comment by lminiero** [comment]
Merged #780, closing.
