### ISSUE TITLE
please document need(s) for a forked adapter.js

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#779]
at https://github.com/meetecho/janus-gateway/issues/778#issuecomment-279432313 was mentioned that the adapter.js included with demos is a deliberate fork - but only mention of why that is needed I could find was the vaguely commented commit a5a82b9 .

Please document more prominently that using the included adapter.js may be beneficial over (newer, further developed) https://github.com/webrtc/adapter - and what benefits that would be.

**Comment by lminiero** [comment]
Merged #780, closing.
