### ISSUE TITLE
please include license header for html/adapter.js

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#781]
The file html/license.js contain the following:

>  Use of this source code is governed by a BSD-style license
>  that can be found in the LICENSE file in the root of the source
>  tree.

It seems the file was derived from the BSD-3 licensed https://github.com/webrtc/adapter project and that this project violates 2 of the 3 clauses of said license.

I guess you copied the file release/adapter.js from that project, which has its copyright and licensing header stripped - but beware that while they can do whatever (they own the copyright) any redistributor (including this project) *must* include the information - either in a separate file (e.g. LICENSE.md) or by re-adding the header.

I guess the best approach - to avoid confusion with the licensing of _this_ project - is to re-add the header.

**Comment by lminiero** [comment]
I didn't remove anything -- I guess you're right in saying I took the release version. I'll find the part of the header I should add and update #780

**Comment by jonassmedegaard** [comment]
Sorry, I didn't mean to imply that you removed the copyright and licensing header.

For the record, what I meant by "re-add the header" was undo what (most likely) _upstream_ removed.
