### ISSUE TITLE
Lost video on low bandwidth

### ISSUE THREAD

**Issue by sfreundlich** [meetecho/janus-gateway#783]
I installed janus-gateway on ubuntu server, and started to play with the videoroom client.
I changed the bitrate to 700-800kbps in order to get higher video quality, but when I have low bandwidth (e.g. bad wifi), I lost the video from that specific client (the bitrate label decreases to zero) and the server sends event to that client which says: "Janus stopped receiving our video".
I also tested it in an environment in which I control the bandwidth and when I go below 0.5Mbps, that specific user stop sending it's video, and also I can see in the webrtc-internals 500 PLIs sent.

When I go to 1.5Mb bitrate, the threshold is like 1Mbps bandwidth, and the video is not coming back after bandwidth rise to normal.

Does it suppose to happen with high bitrate and low bandwidth? Any suggestions what could be the source for this behavior?

**Comment by lminiero** [comment]
Please discuss this on the [group](https://groups.google.com/forum/#!forum/meetecho-janus), we only use Github for code issues and pull requests.
