### ISSUE TITLE
Reduce spurious "This handle is not attached to this session" messages from janus.js

### ISSUE THREAD

**Issue by thehunmonkgroup** [meetecho/janus-gateway#791]
"This handle is not attached to this session" shows up in the browser console as a warning, but it seems like often it's just the result of the client receiving an event after a handle has been properly closed.

Perhaps janus.js should reduce these console messages from console.warn to console.log where appropriate?

**Comment by lminiero** [comment]
Please provide info on the lines where this happens, to see which events cause this.

**Comment by thehunmonkgroup** [comment]
links to line numbers in janus.nojquery.js, and the event they are related to:

 - https://github.com/meetecho/janus-gateway/blob/master/html/janus.nojquery.js#L463 -- webrtcup
 - https://github.com/meetecho/janus-gateway/blob/master/html/janus.nojquery.js#L479 -- hangup
 - https://github.com/meetecho/janus-gateway/blob/master/html/janus.nojquery.js#L511 -- media
 - https://github.com/meetecho/janus-gateway/blob/master/html/janus.nojquery.js#L526 -- slowLink
 - https://github.com/meetecho/janus-gateway/blob/master/html/janus.nojquery.js#L561 -- generic 'event'

IMO all of these can be reduced in severity, with the possible exception of the generic events, which may need to be examined for the sub-event to see.

**Comment by lminiero** [comment]
Agreed, I'll fix them shortly.
