### ISSUE TITLE
Janus Screensharing MaxFramerate of 3?

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#800]
https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L1590

Why so low?  I think this should be 60.  There should also be a minimum frame-rate in here as well.  Ideally, this is configurable.

**Comment by lminiero** [comment]
I don't even know if that works or is processed, actually. AFAIK Chrome only does 5fps for screensharing, at least from what I heard in a presentation by Google at a recent event: https://docs.google.com/presentation/d/1x3zuhRy5Js1BEtDsksBw9Eh2FUyiKSDlzxi32DaI7jc/edit#slide=id.g1ca94fbb59_0_157

Closing as not a code issue: please discuss things like this on the group instead.

**Comment by chadfurman** [comment]
Chrome supports upto 60 FPS in Windows according to Alexandre Gouaillard.  I maintain this is a code issue because this option is not configurable.

**Comment by lminiero** [comment]
Got it, reopening then: PRs welcome too :smile:

**Comment by chadfurman** [comment]
Understood.  Trying to get a working demo for my client.  I'll have to understand better how the other options are making it in -- probably will add it as an option to the createOffer media config object.

**Comment by lminiero** [comment]
> probably will add it as an option to the createOffer media config object.

Yep, makes sense. Not sure if this should be a screensharing specific property (e.g., a maxFrameRate that only applies to screensharing, and so needs related semantics) or not, although I don't believe there's a consistent way of forcing the framerate for regular video captures on both Chrome and Firefox. As a side note, does the frame rate thing work on Firefox too?

**Comment by chadfurman** [comment]
Not sure about Firefox.  I have some demo code (not sure if I can share, contractually) that was provided as part of a work-order where it is implied that Firefox is supported.  The actual demo code has no browser detection.  My assumption would be yes, Firefox supports the same semantics.  

```
      constraints.video.mandatory.minFrameRate = framerate
      constraints.video.mandatory.maxFrameRate = framerate
```

**Comment by chadfurman** [comment]
https://github.com/meetecho/janus-gateway/pull/802  might be good.  Needs testing.  Just tossed it together quick.

**Comment by lminiero** [comment]
Tnx!
