### ISSUE TITLE
"Screensharing doesn't work with Audio"

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#801]
I've been working with Alexandre Gouaillard from the WebRTC working group, and he assures me that in newer versions of Google Chrome, screensharing streams do support audio alongside the video.  

Here in the screensharingtest demo, it's disabled all of the time:  https://github.com/meetecho/janus-gateway/blob/master/html/screensharingtest.js#L164

I believe that the demo should have this option set to "true" and then the audio stream will come from the system rather than a microphone input.  This audio stream is not available via getUserMedia -- I'm not 100% clear on how it actually works.

I'm still in the process of testing it, but from a demo that I was shown by Dr. Alex, there was audio in his screenshare and he said it was all part of the same stream.

**Comment by lminiero** [comment]
It's disabled because at the time the whole getUSerMedia/getScreenMedia part would fail otherwise. If there's a way to allow newer versions to work and not have others fail, I'm happy to integrate.

**Comment by chadfurman** [comment]
Ah alright.  I wonder if leaving the "audio" property out of the constraints entirely in the case of screensharing would do the trick...

**Comment by lminiero** [comment]
But that could end up capturing the system audio when you don't want to, which is dangerous. I guess at this point the easiest way is to honor the audio request, that is, if the user enabled audio in the media object, then try capturing audio as well, and leave it up to the application to disable audio when capturing screen/desktop, in case it's known to fail. That would add more burden on the application, though.

**Comment by chadfurman** [comment]
In this case, it's just the screensharingtest demo.  Unless janus.js has audio disabled for all screensharing (which I didn't notice that it did?), setting `audio: true` in the media object would be fine.  Before this gets a PR, though, we should identify the exact version of chrome that this was enabled in, and then add a version check in the demo test plugin.

**Comment by lminiero** [comment]
> Before this gets a PR, though, we should identify the exact version of chrome that this was enabled in, and then add a version check in the demo test plugin.

That's what I mean should probably happen in janus[.nojquery].js, though... we can probably just turn audio to false and throw a warning on the JavaScript console for older browsers, so that application developers can handle that too, if they want (e.g., display something to the user).

**Comment by chadfurman** [comment]
Oh, yup that makes sense.

**Comment by lminiero** [comment]
Closing as we do have a way to add audio now, thanks to the PR we recently merged. There still is the matter of getting system audio instead of mic audio, but that can be handled separately.
