### ISSUE TITLE
SRTP protect error and crash

### ISSUE THREAD

**Issue by glibersat** [meetecho/janus-gateway#805]
Hi,

I'm using the master branch of janus and have been using a few other older versions since a few months and I keep getting this printed on the console when clients are connected (websocket) using the streaming plugin:

[ERR] [ice.c:janus_ice_send_thread:3611] [3002700491704136] ... SRTP protect error... srtp_err_status_replay_fail (len=172-->172, ts=64426080, seq=3148)...

Then, about every 7 minutes, janus will crash. I don't know if that's related or not. We have ~20 users at the same time and a raspberrypi streaming Opus using gstreamer.

Any idea first, on how to suppress these errors and then, how to trace the cause of crash?

Thank you,

Guillaume

**Comment by lminiero** [comment]
`srtp_err_status_replay_fail` means you're sending the same packet more than once. Make sure you're not feeding the Streaming mountpoint with the same packet twice (e.g., two identical sources sending to the same port). As to the crash, you'll need to do some [debugging](https://janus.conf.meetecho.com/docs/debug) or there's nothing we can do to help.

**Comment by lminiero** [comment]
Any update?

**Comment by glibersat** [comment]
Yes!
We had two clients connecting from the same host every time, which, I guess, were responsible of these STRP errors. Now that we fixed that, the server seems stable.
I also upgraded to libstrp 2.0.

Even if it is fixed now, I'm a bit concerned that the clients can have such an impact on the stability of the server. Do you think there could be a leak somewhere in the websocket handling or in the debug console printing routines?

Cheers

**Comment by lminiero** [comment]
That's not what I meant. I didn't mean users on the WebRTC side, but whatever you're using to feed data to the Streaming mountpoint (gstreamer/ffmpeg/vlc/others). If they're feeding the same exact data (up to the RTP headers) to the same mountpoint twice, the same RTP packet will be encrypted twice, and the second one will trigger that error. That doesn't affect stability, it's an error message and the packet is discarded, but it is a nuance.

If you're feeding a mountpoint from a VideoRoom publisher with RTP forwarding, make sure you're not RTP-forwarding the same publisher to the same mountpoint twice at the same time, as the same issue would arise (same packet being handled more than once).

**Comment by lminiero** [comment]
Closing as apparently the issue got solved.
