### ISSUE TITLE
Warning "onaddstream is deprecated! Use peerConnection.ontrack instead." in janus.js

### ISSUE THREAD

**Issue by karth295** [meetecho/janus-gateway#806]
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onaddstream

OS: Fedora
Browser: Firefox 51
janus-gateway: beb0b807aea52d30d697b48708db1ac391785666 (but glancing at source code, issue probably still exists at head)

**Comment by lminiero** [comment]
Yeah we'll have to change that sooner or later.

**Comment by lminiero** [comment]
Can you check if #942 works for you? It implements ontrack, and I'd like to merge ASAP.

**Comment by lminiero** [comment]
Closing as we merged that PR.
