### ISSUE TITLE
preprocessing manpage not installed

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#813]
manpage postprocessing/janus-pp-rec.1 does not get installed when passing --enable-post-processing to configure.

**Comment by lminiero** [comment]
It is for me (Fedora 25) and we have the proper Makefile code to do that:
https://github.com/meetecho/janus-gateway/blob/master/Makefile.am#L364

**Comment by lminiero** [comment]
Are you sure the post processor is being installed for you? You can check that in the summary at the end of the configure.

**Comment by jonassmedegaard** [comment]
hm, indeed it works.  Sorry for the noise!

**Comment by lminiero** [comment]
No problem, thanks for checking these things!
