### ISSUE TITLE
source includes copyright-protected but unlicensed image

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#815]
The image html/up_arrow.png has an embedded color calibration profile which is "(c) 1998 Hewlett-Packard Company" without license.

Please strip the ICC profile from that image - using e.g. pngcrush.

**Comment by lminiero** [comment]
How can I check if I succeeded?

**Comment by jonassmedegaard** [comment]
apt install libimage-exiftool-perl
exiftool up_arrow.png

**Comment by jonassmedegaard** [comment]
...or a more generic install: cpanm Image::ExifTool

**Comment by lminiero** [comment]
:+1:

**Comment by jonassmedegaard** [comment]
thanks!

Is it much work to issue a release? This tiny issue was the last detail needed for me to be able to release a Debian package _without_ resorting to repackaging source.

**Comment by lminiero** [comment]
We issued a release just a few days ago. The way we handle that is to wait for when we're about to merge major changes before releasing a new one.

**Comment by jonassmedegaard** [comment]
fair enough  - I will fork the source for the initial Debian packaging release slightly, then.
