### ISSUE TITLE
implicit declaration in ice.c

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#818]
Debian autobuilders revealed a compiler warning about implicit declaration in ice.c:

<https://qa.debian.org/bls/packages/j/janus.html>

Side-note: Now that Janus is officially in Debian, you can monitor (and even subscribe to notices from) the health of Janus packaging for Debian at <https://tracker.debian.org/pkg/janus>.  It is purely optional: It is Debian's responsibility, not yours, how Janus fares with Debian.

**Comment by jonassmedegaard** [comment]
Sorry - here is the actual compiler warning, from one of above referenced buildlogs:

gcc -DPACKAGE_NAME=\"Janus\ Gateway\" -DPACKAGE_TARNAME=\"janus-gateway\" -DPACKAGE_VERSION=\"0.2.2\" -DPACKAGE_STRING=\"Janus\ Gateway\ 0.2.2\" -DPACKAGE_BUGREPORT=\"https://github.com/meetecho/janus-gateway\" -DPACKAGE_URL=\"https://janus.conf.meetecho.com\" -DPACKAGE=\"janus-gateway\" -DVERSION=\"0.2.2\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -D__EXTENSIONS__=1 -D_ALL_SOURCE=1 -D_GNU_SOURCE=1 -D_POSIX_PTHREAD_SEMANTICS=1 -D_TANDEM_SOURCE=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PORTRANGE=1 -DHAVE_LIBNICE_TCP=1 -DHAVE_SRTP_2=1 -DHAVE_LIBCURL=1 -DHAVE_SAMPLEEVH=1 -DHAVE_WEBSOCKETS=1 -DHAVE_LIBWEBSOCKETS_NEWAPI=1 -DHAVE_RABBITMQ=1 -DHAVE_PFUNIX=1 -I.   -Wdate-time -D_FORTIFY_SOURCE=2 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations -Wunused -fstrict-aliasing -Wextra -Wformat=2 -Winit-self -Winline -Wpacked -Wpointer-arith -Wmissing-format-attribute -Wmissing-noreturn -Wnested-externs -Wstrict-prototypes -Wunsafe-loop-optimizations -Wwrite-strings -Wno-missing-field-initializers -Wno-unused-parameter -Wcast-align -Wformat-nonliteral -Wformat-security -Wswitch-default -Wmissing-include-dirs -Wno-aggregate-return -Wunused-but-set-variable -Warray-bounds -Wold-style-definition -Wsign-compare -Wlarger-than=65537 -Wno-undef -Wno-redundant-decls -Wno-override-init -fstack-protector-all -g -ggdb -fPIC -rdynamic -pthread -pthread -I/usr/include/nice -I/usr/include/gupnp-igd-1.0 -I/usr/include/gupnp-1.0 -I/usr/include/gssdp-1.0 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DPLUGINDIR=\"/usr/lib/x86_64-linux-gnu/janus/plugins\" -DTRANSPORTDIR=\"/usr/lib/x86_64-linux-gnu/janus/transports\" -DEVENTDIR=\"/usr/lib/x86_64-linux-gnu/janus/events\" -DCONFDIR=\"/etc/janus\"   -g -O2 -fdebug-prefix-map=/«BUILDDIR»/janus-0.2.2+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -c -o janus-ice.o `test -f 'ice.c' || echo './'`ice.c
ice.c: In function 'janus_ice_send_thread':
ice.c:3264:5: warning: implicit declaration of function 'gettimeofday' [-Wimplicit-function-declaration]
     gettimeofday(&tv, NULL);
     ^~~~~~~~~~~~
ice.c:3264:5: warning: nested extern declaration of 'gettimeofday' [-Wnested-externs]

**Comment by lminiero** [comment]
Please don't paste huge bunches of text inline, use services like gist/pastebin when you need to.

That said, looking around it seems we just need a `#include <sys/time.h>` in `ice.c`. Not sure why it's not giving the warning on my Fedora 25.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2017-03-17 11:21:28)
> Please don't paste huge bunches of text inline, use services like 
> gist/pastebin when you need to.

What amount do you consider proper limit for inlining?

In this case the alternative would not be a pastebin but *nothing* - 
because it was simply a quote from the logfiles already online and 
referenced in the initial message ;-)


> That said, looking around it seems we just need a `#include 
> <sys/time.h>` in `ice.c`.

Ah, that sounds simple :-)


> Not sure why it's not giving the warning on my Fedora 25.

Possibly the explanation for differences in warnings is the compiler 
options passed by default to the build: In Debian we do not simply use 
the build options from your project but override some parts.


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by lminiero** [comment]
> What amount do you consider proper limit for inlining?

Anything that makes a message too big :smile:  I realize I may look picky, but since I have to go through all these messages over and over, huge pages make this all unreadable for me. External references are easier for me to process.

> In this case the alternative would not be a pastebin but *nothing* -
> because it was simply a quote from the logfiles already online and
> referenced in the initial message ;-)

I agree, your original reference was enough already.

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2017-03-17 11:36:11)
> > What amount do you consider proper limit for inlining?
> 
> Anything that makes a message too big :smile: I realize I may look 
> picky, but since I have to go through all these messages over and 
> over, huge pages make this all unreadable for me. External references 
> are easier for me to process.

Not too picky at all: I understand and want to respect your request.

Pretty damned difficult to interpret your definition of "too big" from 
staring at a smiley...

Five lines? Two lines?


 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by lminiero** [comment]
I guess everything that fills my browser window, so anything more than 25-30 lines? Boy, I *do* sound crazy! :slightly_smiling_face:

**Comment by jonassmedegaard** [comment]
Quoting Lorenzo Miniero (2017-03-17 13:19:18)
> I guess everything that fills my browser window, so anything more than 25-30 lines? Boy, I *do* sound crazy! :slightly_smiling_face: 

On the contrary: Makes sense that your measure of judgement is 
"screenfulls".  I recognixe the annoyance from irc where measure of 
judgement is single lines due to console UIs being common there.

FYI my measure of judgement here was email, since that is the tool I 
most commonly use for responding to issues at github (and at Debian 
where the bugtracker is modelled around mail rather than web).

Thanks for your elaboration!

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
