### ISSUE TITLE
unix sockets created are not removed again

### ISSUE THREAD

**Issue by jonassmedegaard** [meetecho/janus-gateway#819]
The unix sockets created at startup when pfunix transport is enabled, are left behind when daemon is stopped again.

Seems sensible to me that the daemon cleans up after itself.  Or alternatively that it does not create either - leaving both creation and cleanup of sockets to wrapper scripts (systemd, initV etc.).

**Comment by lminiero** [comment]
We're probably missing an `unlink` at the plugin destroy, will add it.
