### ISSUE TITLE
Error connecting to MQTT when username/password enabled

### ISSUE THREAD

**Issue by stormbkk87** [meetecho/janus-gateway#820]
Connecting using the MQTT transport works fine with default settings. However, when enabling passwords on MQTT and setting the username/password in mqtt janus config file, gives the following error.

    [ERR] [transports/janus_mqtt.c:janus_mqtt_client_connect_failure:495] MQTT client has been failed connecting to the broker, return code: 5. Reconnecting...

Tested username/password with third party client app MQTT.fx.

**Comment by lminiero** [comment]
Noticed you contributed #821 for this.

**Comment by lminiero** [comment]
Fixed by your PR, closing.
