### ISSUE TITLE
Streaming doesn't work on Firefox

### ISSUE THREAD

**Issue by stsdc** [meetecho/janus-gateway#822]
Running gstreamer:
`gst-launch-1.0 rpicamsrc ! h264parse ! rtph264pay config-interval=1 pt=126 ! udpsink host=127.0.0.1 port=8004`

Configuration file:
`[h264-sample]`
`type = rtp`
`id = 10`
`description = H.264 live stream coming from gstreamer`
`audio = no`
`video = yes`
`videoport = 8004`
`videopt = 126`
`videortpmap = H264/90000`
`videofmtp = profile-level-id=42e01f\;packetization-mode=1`

It works flawlessly on Chrome, but on every Firefox version (stable, Developer edition, mobile) I see spinner and that's all.
Janus:
`Creating new session: 7379639816440558`
`Creating new handle in session 7379639816440558: 424274647953534`
`[424274647953534] Creating ICE agent (ICE Full mode, controlling)`
`[424274647953534] The DTLS handshake has been completed`
`WebRTC media is now available`

Maybe there is specific gstreamer pipeline and Janus configuration that works with Firefox?

**Comment by lminiero** [comment]
Closing as not a code issue, question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus).

**Comment by stsdc** [comment]
Just found an error that doesn't happen in Chrome: 
` TypeError: window.navigator.match is not a function[Learn More] janus.js:146:61`

**Comment by lminiero** [comment]
Fixed two days ago: https://github.com/meetecho/janus-gateway/commit/a83f3cddb7a4629807a8ec8935ac7f21e09a84d3

**Comment by stsdc** [comment]
Sorry for bothering. Have a nice day.
