### ISSUE TITLE
Error Start Janus (transports/janus_pfunix.c:janus_pfunix_init:284)

### ISSUE THREAD

**Issue by SalvatoreAD** [meetecho/janus-gateway#824]
Hi, I have this error on start. Can you help me?
> 
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Gateway) v0.2.3
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Using 10.194.10.6 as local IP...
[WARN] Token based authentication disabled
Initializing recorder code
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, IPv6 support disabled)
ICE handles watchdog started
TURN REST API backend: (disabled)
[WARN] Janus is deployed on a private address (10.194.10.6) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
BUNDLE is NOT going to be forced
rtcp-mux is NOT going to be forced
Crypto: OpenSSL pre-1.1.0
Fingerprint of our certificate: D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38
Event handler plugins folder: /opt/janus/lib/janus/events
[WARN] Event handlers support disabled
Plugins folder: /opt/janus/lib/janus/plugins
Loading plugin 'libjanus_streaming.so'...
Sessions watchdog started
Streaming watchdog started
JANUS Streaming plugin initialized!
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_recordplay.so'...
EchoTest watchdog started
JANUS Record&Play plugin initialized!
Loading plugin 'libjanus_sip.so'...
Record&Play watchdog started
JANUS SIP plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
SIP watchdog started
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
VoiceMail watchdog started
JANUS VideoRoom plugin initialized!
Loading plugin 'libjanus_audiobridge.so'...
VideoRoom watchdog started
JANUS AudioBridge plugin initialized!
Loading plugin 'libjanus_videocall.so'...
AudioBridge watchdog started
JANUS VideoCall plugin initialized!
Loading plugin 'libjanus_textroom.so'...
VideoCall watchdog started
JANUS TextRoom plugin initialized!
TextRoom watchdog started
Transport plugins folder: /opt/janus/lib/janus/transports
Loading transport plugin 'libjanus_websockets.so'...
libwebsockets >= 1.6 available, using new API
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
[WARN] Admin WebSockets server disabled
[WARN] Secure Admin WebSockets server disabled
JANUS WebSockets transport plugin initialized!
Loading transport plugin 'libjanus_http.so'...
WebSocket (Janus API) thread started
HTTP webserver started (port 8088, /janus path listener)...
[WARN] HTTPS webserver disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
JANUS REST (HTTP/HTTPS) transport plugin initialized!
Loading transport plugin 'libjanus_pfunix.so'...
HTTP/Janus sessions watchdog started
[WARN] Unix Sockets server disabled (Janus API)
[WARN] Unix Sockets server disabled (Admin API)
[FATAL] [transports/janus_pfunix.c:janus_pfunix_init:284] No Unix Sockets server started, giving up...
[WARN] The 'janus.transport.pfunix' plugin could not be initialized

**Comment by lminiero** [comment]
Please read the [contributing guidelines](https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md) before opening issues. Closing as not a code issue, this is a question for the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
