### ISSUE TITLE
Feat Req: 'pin requirement' field support for each room in the room list response object

### ISSUE THREAD

**Issue by code-master5** [meetecho/janus-gateway#826]
Currently the the info for each room in the room list response object has these fields: 
```
        {
            "audiocodec": "opus",
            "bitrate": 0,
            "description": "my room",
            "fir_freq": 0,
            "max_publishers": 5,
            "num_participants": 0,
            "record": false,
            "room": 2146946532127888,
            "videocodec": "vp8"
         }
```
There is no way to check whether a room requires pin or not. It would be better if there would be some way to check for pin requirement before trying to access a room. Thanks.

**Comment by lminiero** [comment]
So you mean, only specify if it's PIN-protected, and not provide the PIN itself, right? I'll add this to the TODO list.

**Comment by code-master5** [comment]
@lminiero Yes, exactly. Thanks for this.

**Comment by lminiero** [comment]
Done, let me know if this works as expected for you.

**Comment by code-master5** [comment]
@lminiero Superb! It works exactly as I expected. Thank you very much. You saved us a lot of overhead.
