### ISSUE TITLE
ICE failed, see about:webrtc for more details

### ISSUE THREAD

**Issue by gatecrasher777** [meetecho/janus-gateway#83]
I get this browser response quite a lot (videoroom plugin), especially in Firefox. Sometimes it will take 2 or 3 or more attempts before it works. I've built the re-attempts (ie re-attaching to the plugin after cleanup) into my own app, but when it happens it might take many seconds to connect the stream and achieve happiness. This can happen on both local and remote streams. I'm still unsure why it is happening. Is it normal? Could it be due to packet loss or latency?  Analyzing the Janus logs tends to show a failure in one of the stream components. It then issues a hangup event. Any idea what could be happening here, how i might analyze this more deeply, and how it could be avoided?

**Comment by yan-foto** [comment]
I read the whole thread and I was wondering if my current situation also applies:

I use GStreamer to create a multicast stream, configure janus streaming plugin and start the gateway. Everything works fine in Chrome but not in Firefox. From the JS console output I can see that both follow the same procedure **but** Firefox throws the infamous `ICE Failed` error **before** the first trickle candidate is sent. Another error in Firefox is `RTCIceServer.url is deprecated! Use urls instead.`, which I'm not sure if its relevant or not.

*Note:* I have also had successful sessions in Firefox :confused:

**Comment by lminiero** [comment]
There's probably an exception somewhere in the Firefox console. Make sure the audio/video properties are correctly set in the mountpoint configuration: e.g., if video has a 9000 sampling rate instead of 90000, Chrome will digest it and Firefox won't.

**Comment by yan-foto** [comment]
That did the trick. Sorry for posting irrelevant bugs. :bow:

**Comment by geniant** [comment]
I got this bug in a special condition.
In our school network, torrents are blocked. I can not download any thing using BitTorrent.
but when connecting from ADSL or 3G etc... I don't get this problem.

**Comment by lminiero** [comment]
That's a different issue: your school network is probably filtering traffic, including RTP and STUN. You probably just need to setup/use a TURN server and configure it on the clients.

**Comment by Byakuran** [comment]
I`m sorry,my english is so terrible.I encountered the same problem.
can you tell me how to solve this problem or why did it happend?
