### ISSUE TITLE
Can join pin protected textroom, without pin

### ISSUE THREAD

**Issue by izemize** [meetecho/janus-gateway#830]
Hi

I can join pin protected textroom, without sending pin in join request.

```js
textroom.send({
        message:{'request':'create','room':room,'pin':hash,'pin_required':true},
        success:function(result)
        {
            return joinToTextRoom(result['room']);
        },
        error: function(videoroom, error_code, error)
        {
            Janus.debug('ERROR: '+error_code);
        }
    });
```

Sending string on data channel: {"textroom":"join","transaction":"5KEMrskceZNK","room":1,"username":"5rik5bUmHPLK","display":"Gábor I"}
janus.js:1306 Received message on data channel: {
   "textroom": "join",
   "room": 1,
   "username": "5rik5bUmHPLK",
   "display": "Gábor I"
}
janus.js:1306 Received message on data channel: {
   "textroom": "success",
   "participants": [],
   "transaction": "5KEMrskceZNK"
}

It's a security bug?

**Comment by lminiero** [comment]
First of all, there's no such thing as `pin_required` in `create` requests: it's only available as a read-only property in `list`. Providing a PIN is enough to make the room PIN-protected.

That said, yep, it looks like we're not validating the PIN on joins. I'll add this to the list of things to fix.
