### ISSUE TITLE
 h.264 stream is a green rectangle with iphone app, but work fine with notebook firefox web browser 

### ISSUE THREAD

**Issue by frankhanche** [meetecho/janus-gateway#831]
all,

No any errors in console. But Screen is green  with Iphone app.(like attach)

Really wonder what happened here, Thanks a lot.

**Stream comes from Raspberry pi (gStreamer + Janus WebRTC gateway)**
  gst-launch-1.0 --gst-debug=3 \
   v4l2src ! \
   video/x-raw,width=1280,height=720,framerate=5/1 ! clockoverlay ! \
   omxh264enc ! video/x-h264,profile=high !  h264parse ! queue ! \
   rtph264pay config-interval=1 pt=96 ! udpsink host=127.0.0.1 port=8004

**janus.plugin.streaming.cfg**
[h264-sample]
type = rtp
id = 1
description = H.264 live stream coming from gstreamer
audio = yes
video = yes
audioport =8002
audiopt = 111
audiortpmap = opus/48000/2
videoport = 8004
videopt = 96
videortpmap = H264/90000

**[janus log]**

**[Fri Mar 24 11:14:34 2017]   >> Merged (1799 bytes)**
**//-----------send to server--------------------------------**
[Fri Mar 24 11:14:34 2017] v=0^M
o=- 1490321674541115 1490321674541115 IN IP4 221.186.137.140^M
s=Streaming Test^M
t=0 0^M
a=group:BUNDLE audio video^M
a=msid-semantic: WMS janus^M
m=audio 9 RTP/SAVPF 111^M
c=IN IP4 221.186.137.140^M
a=sendonly^M
a=mid:audio^M
a=rtcp-mux^M
a=ice-ufrag:3Xt8^M
a=ice-pwd:1Zq+AjEvKEwgjnSwjr691H^M
a=ice-options:trickle^M
a=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38^M
a=setup:actpass^M
a=rtpmap:111 opus/48000/2^M
a=ssrc:295236073 cname:janusaudio^M
a=ssrc:295236073 msid:janus janusa0^M
a=ssrc:295236073 mslabel:janus^M
a=ssrc:295236073 label:janusa0^M
a=candidate:1 1 udp 2013266431 192.168.1.245 36389 typ host^M
a=candidate:3 1 udp 1677721855 221.186.137.140 61865 typ srflx raddr 192.168.1.245 rport 36389^M
a=candidate:1 2 udp 2013266430 192.168.1.245 40006 typ host^M
a=candidate:3 2 udp 1677721854 221.186.137.140 61725 typ srflx raddr 192.168.1.245 rport 40006^M
m=video 9 RTP/SAVPF 96^M
c=IN IP4 221.186.137.140^M
a=sendonly^M
a=mid:video^M
a=rtcp-mux^M
a=ice-ufrag:30k4^M
a=ice-pwd:1NkE7wyc0TYAmUsQYbypoj^M
a=ice-options:trickle^M
a=fingerprint:sha-256 D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38^M
a=setup:actpass^M
a=rtpmap:96 H264/90000^M
a=fmtp:96 profile-level-id=42e01f;packetization-mode=1^M
a=rtcp-fb:96 nack^M
a=rtcp-fb:96 goog-remb^M
a=ssrc:1440631439 cname:janusvideo^M
a=ssrc:1440631439 msid:janus janusv0^M
a=ssrc:1440631439 mslabel:janus^M
a=ssrc:1440631439 label:janusv0^M
a=candidate:2 1 udp 2013266431 192.168.1.245 39490 typ host^M
a=candidate:4 1 udp 1677721855 221.186.137.140 62417 typ srflx raddr 192.168.1.245 rport 39490^M
a=candidate:2 2 udp 2013266430 192.168.1.245 54757 typ host^M
a=candidate:4 2 udp 1677721854 221.186.137.140 63174 typ srflx raddr 192.168.1.245 rport 54757^M

**[Fri Mar 24 11:14:35 2017] [3058142516319755] Remote SDP:**
**//-----------from iphone app--------------------------------**
v=0^M
o=- 604450907565103306 2 IN IP4 127.0.0.1^M
s=-^M
t=0 0^M
a=group:BUNDLE audio video^M
a=msid-semantic: WMS^M
m=audio 9 RTP/SAVPF 111^M
c=IN IP4 0.0.0.0^M
a=rtcp:9 IN IP4 0.0.0.0^M
a=ice-ufrag:3aVp0N4OiFbNSQDh^M
a=ice-pwd:1oUnlemzs4Cy2P5L7OJrObaKk^M
a=fingerprint:sha-256 BA:EC:DC:91:4D:38:49:77:EB:67:67:41:37:D6:A6:BB:6C:BD:CA:33:42:69:6C:AD:CA:D3:FC:7E:9C:59:EB:18^M
a=setup:active^M
a=mid:audio^M
a=recvonly^M
a=rtcp-mux^M
a=rtpmap:111 opus/48000/2^M
a=fmtp:111 minptime=10;useinbandfec=1^M
m=video 9 RTP/SAVPF 96^M
c=IN IP4 0.0.0.0^M
a=rtcp:9 IN IP4 0.0.0.0^M
a=ice-ufrag:3aVp0N4OiFbNSQDh^M
a=ice-pwd:1oUnlems4Cy2P5L7OJrObaKk^M
a=fingerprint:sha-256 BA:EC:DC:91:4D:38:49:77:EB:67:67:41:37:D6:A6:BB:6C:BD:CA:33:42:69:6C:AD:CA:D3:FC:7E:9C:59:EB:18^M
a=setup:active^M
a=mid:video^M
a=recvonly^M
a=rtcp-mux^M
a=rtpmap:96 H264/90000^M
a=rtcp-fb:96 nack^M
a=rtcp-fb:96 goog-remb^M
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f^M

**[Thu Mar 23 10:05:02 2017] [2189146449040867] Remote SDP:**
**//-----------from notebook web browser--------------------------------**
v=0^M
o=mozilla...THIS_IS_SDPARTA-52.0 7545251431244529141 0 IN IP4 0.0.0.0^M
s=-^M
t=0 0^M
a=fingerprint:sha-256 65:12:68:F8:8D:F0:4E:14:A6:5A:A9:5E:57:4E:19:32:A3:8F:D6:19:73:EF:FA:C7:30:DE:54:6D:39:CD:70:0F^M
a=group:BUNDLE audio video^M
a=ice-options:trickle^M
a=msid-semantic:WMS *^M
m=audio 9 RTP/SAVPF 111^M
c=IN IP4 0.0.0.0^M
a=recvonly^M
a=fmtp:111 maxplaybackrate=48000;stereo=1;useinbandfec=1^M
a=ice-pwd:7b5ed160b64a92f887097526ce128858^M
a=ice-ufrag:12fr40c5^M
a=mid:audio^M
a=rtcp-mux^M
a=rtpmap:111 opus/48000/2^M
a=setup:active^M
a=ssrc:3608907773 cname:{5ba017dc-26ac-45ff-b381-ec6c9691a897}^M
m=video 9 RTP/SAVPF 96^M
c=IN IP4 0.0.0.0^M
a=recvonly^M
a=fmtp:96 profile-level-id=42e01f;level-asymmetry-allowed=1;packetization-mode=1^M
a=ice-pwd:7b5ed160b64a92f887097526ce128858^M
a=ice-ufrag:12fr40c5^M
a=mid:video^M
a=rtcp-fb:96 nack^M
a=rtcp-fb:96 goog-remb^M
a=rtcp-mux^M
a=rtpmap:96 H264/90000^M
a=setup:active^M
a=ssrc:3782857988 cname:{5ba017dc-26ac-45ff-b381-ec6c9691a897}^M

//BS
frank

**Comment by lminiero** [comment]
1. As explained in the guidelines, NO huge bunches of text inline please. gist/pastebin when it's needed.
2. Closing as not a code issue. Please refer to the [group](https://groups.google.com/forum/#!forum/meetecho-janus)
