### ISSUE TITLE
RTSP streaming stops after a few seconds (no RTCP)

### ISSUE THREAD

**Issue by fbertone** [meetecho/janus-gateway#832]
Hi,
I'm trying to re-stream with janus the output of an NVR.
The session janus-nvr is started correctly and the timeout is set to 60 seconds, however the session is closed by the nvr after a few seconds (about 10).
The problem seems to be that the nvr wants to communicate via **RTCP** but janus does not.
So, during the SETUP phase, janus reports 2 client ports (one for RTP and one for RTCP I suppose), but thet it does not listen on the second port.
Here's the SETUP message:
* janus -> nvr
```
SETUP rtsp://192.168.1.103/cam/realmonitor?channel=1&subtype=0/trackID=0 RTSP/1.0
CSeq: 3
Transport: RTP/AVP;unicast;client_port=45795-45796
Authorization: Basic YWRtaW46YWRtaW4=
```

* nvr -> janus
```
RTSP/1.0 200 OK
Server: Rtsp Server/2.0
CSeq: 3
Session: 13801393866;timeout=60
Transport: RTP/AVP;unicast;client_port=45795-45796;server_port=20000-20001;ssrc=66A362C2
x-dynamic-rate: 1
```
After 5 seconds the nvr sends an RTCP **Sender Report** message to port 45796 but the response is an ICMP **Destination port unreachable**

In VLC the SETUP is analogous but after 2 seconds (then every 5 seconds) VLC sends an RTCP **Receiver Report** message, after 5 seconds (then every 5 seconds) the NVR sends a **Sender Report** message.

I can share dumps if needed.

Thanks,
Fabrizio

**Comment by lminiero** [comment]
Sorry for the late response, I'm abroad for a conference and I'm not checking this page daily.

We currently don't do any RTCP in the plugin, and I don't think we'll implement a full RTCP stack in the plugin either just for RTSP. If you can identify the minimum behaviour that will get it working (e.g., if simply listening on the port and send a message once does the job) then we can try to do that. Of course, PRs are welcome to address this in a broader sense.

**Comment by fbertone** [comment]
Ok, thanks for the response.
IMO there's no need to implement a full RTCP stack, just send a message once in a while (but I don't know RTCP).
I'll try to do some testing and let you know or PR if I achieve something.

Have a nice conference!
F

**Comment by fbertone** [comment]
Hi there,
so apparently, for my specific case, opening the RTCP port seems to be enough to keep the connection alive, however I don't know if that's a universal solution or not. RTSP seems to be not so much standardized.
Should I PR the code to open the port?

**Comment by lminiero** [comment]
That would help, thanks! If it turns out not to be enough we at least have a socket ready to be used for the purpose.

**Comment by fbertone** [comment]
I'm also working on periodically sending the Receiver Report messages but I want to be sure to understand well how to forge the packets (libcurl apparently does not support RTCP natively).
