### ISSUE TITLE
Janus generates invalid RTCP packets with padding bit

### ISSUE THREAD

**Issue by koltru** [meetecho/janus-gateway#833]
in several places of the code where "rtcpbuf" is defined it is not initialised, for example
```
char rtcpbuf[srlen+sdeslen];
rtcp_sr *sr = (rtcp_sr *)&rtcpbuf;
sr->header.version = 2;
sr->header.type = RTCP_SR;
sr->header.rc = 0;
sr->header.length = htons((srlen/4)-1);
```

Since padding bit is not explicitly set it can be any.
It is better to initialise rtcpbuf with
`memset(rtcpbuf, 0, srlen+sdeslen);`
or with 
`char rtcpbuf[srlen+sdeslen] = {0}`
or set padding bit explicitly
`sr->header.padding = 0`
In the last case uninitialised rtcpbuf can still hide something.

**Comment by lminiero** [comment]
Good catch, thanks for spotting this. I think I fixed this already in a few cases but there definitely are others (like the ones you spotted) where we're not doing it. I'll take care of this when I get back, as I'll be busy all week at the IETF. PRs also welcome of course!

**Comment by lminiero** [comment]
Found a few minutes to fix this. It was only an issue in `ice.c`, as in all the helper methods (e.g., `janus_rtcp_pli`) we were doing that already. As such, I removed the extra `memset` we had in a few plugins when they called these helper methods.

**Comment by koltru** [comment]
Thanx, must be ok. I did test only my local fixes that looks similar. Tomorrow will test with your commit.

**Comment by koltru** [comment]
Tested. OK.

**Comment by lminiero** [comment]
Tnx!

**Comment by pps83rbx** [comment]
Not sure if that's related, but when running a voice call with webrtc/janus I get these logs quite often:

> (common_header.cc:43): Invalid RTCP header: Version must be 2 but was 0
