### ISSUE TITLE
Screenshare Plugin Problem:

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#835]
https://developer.chrome.com/extensions/desktopCapture

Note that callback has a second parameter, "options"

I had to unpack the screenshare plugin and modify it locally. 

Putting this ticket in the Janus repo because I can't find a repo for https://chrome.google.com/webstore/detail/janus-webrtc-screensharin/hapfgfdkleiggjjpfpenajgdnfckjpaj

**Comment by lminiero** [comment]
Ack, if you let us know what should be changed and where I'll update the extension. Will this be an optional feature though? Just to understand if this means the messaging to the extension will need to change too.

**Comment by chadfurman** [comment]
Despite the docs posted, I'm getting "undefined" for my `options` param

```
/* In background.js*/
// ... 
            var pending = chrome.desktopCapture.chooseDesktopMedia(message.options || ['screen', 'window'], channel.sender.tab, function (streamid, options) {
// note th ecallback has both "streamid" param and "options" param
```

So add the `options` param to the callback, like above, then attach it to the message before you `channel.postMessage()`

**Comment by mirkobrankovic** [comment]
@chadfurman , but what is the actual problem?

**Comment by lminiero** [comment]
Just a ping, as I fail to remember what options could be useful for. Is it just a context object, something like an opaque property you set when contacting the plugin, and the plugin gives back? If so, is there really a need for it?

**Comment by chadfurman** [comment]
* NOTE: even after adding in this parameter, I wasn't able to get the expected values back *

idea here being, from the chrome developer docs link (https://developer.chrome.com/extensions/desktopCapture) :

```
integer chrome.desktopCapture.chooseDesktopMedia(array of DesktopCaptureSourceType sources, tabs.Tab targetTab, function callback)
```

note `function callback`, which has the following argument structure:

`function(string streamId, object options) {...};`

and note that `options` is an object:
```
object	options	
Contains properties that describe the stream.
```

And one of those options is the following boolean

```
boolean	canRequestAudioTrack	
True if "audio" is included in parameter sources, and the end user does not uncheck the "Share audio" checkbox. Otherwise false, and in this case, one should not ask for audio stream through getUserMedia call.
```

**Comment by chadfurman** [comment]
janus.js has changed dramatically since this ticket was opened.  Perhaps we want to close it now?

**Comment by lminiero** [comment]
Ack, unless you plan to rebase feel free to close.

**Comment by chadfurman** [comment]
Closing, as this never really worked right for me anyway.
