### ISSUE TITLE
Unable to authenticate RTSP stream

### ISSUE THREAD

**Issue by clody69** [meetecho/janus-gateway#839]
I'm trying to use the BASIC Auth for a RTSP stream but I can't make it working.

The URL has this format: 
```
rtsp://<usr>:<pwd>@<address>:8101/defaultSecondary
```
Using VLC it works fine. I've tried to force BASIC or DIGEST auth in the code but it just doesn't connect. Any idea what could be ?

Some logs below:
```
*   Trying 79.23.205.231...
* Connected to eggzero.ddns.net (79.23.205.231) port 8101 (#0)
> DESCRIBE rtsp://eggzero.ddns.net:8101/defaultSecondary RTSP/1.0
CSeq: 1
Accept: application/sdp
If-Modified-Since: Thu, 01 Jan 1970 00:00:00 GMT

< RTSP/1.0 401 Unauthorized
< WWW-Authenticate: Digest realm="101509150167", nonce="jCj5z4Nw9RsphXnfN9sy4w3qSs2SVqpqJR8w1Udb038200", charset=utf-8, qop="auth"
< CSeq: 1
< Content-Length: 0
< Date: Sat, 01 Apr 2017 13:33:53 GMT
<
* Connection #0 to host eggzero.ddns.net left intact
* Issue another request to this URL: 'rtsp://eggzero.ddns.net:8101/defaultSecondary'
* Found bundle for host eggzero.ddns.net: 0x1f56310
* Re-using existing connection! (#0) with host eggzero.ddns.net
* Connected to eggzero.ddns.net (79.23.205.231) port 8101 (#0)
> DESCRIBE rtsp://eggzero.ddns.net:8101/defaultSecondary RTSP/1.0
CSeq: 2
Accept: application/sdp
If-Modified-Since: Thu, 01 Jan 1970 00:00:00 GMT

< RTSP/1.0 401 Unauthorized
* Authentication problem. Ignoring this.
< WWW-Authenticate: Digest realm="101509150167", nonce="ewokC8f3Ky5DztMeae6SHf3hGekk39Gi0dqa6Mdb038200", charset=utf-8, qop="auth"
< CSeq: 2
< Content-Length: 0
< Date: Sat, 01 Apr 2017 13:33:53 GMT
<
* Connection #0 to host eggzero.ddns.net left intact
[ERR] [plugins/janus_streaming.c:janus_streaming_create_rtsp_source:3218] Couldn't get DESCRIBE code: 401
[ERR] [plugins/janus_streaming.c:janus_streaming_init:1011] Error creating 'rtsp' stream 'rtsp-test'...

```

**Comment by lminiero** [comment]
Make sure your libcurl is >= 7.45.0, as RTSP authentication is not supported otherwise.

**Comment by clody69** [comment]
Yes, I'm using the correct curl version

**Comment by fbertone** [comment]
Hi, did you set user and password as parameters in the cfg instead of putting them in the url?

**Comment by clody69** [comment]
yes, I've tried various combinations

**Comment by 9a4gl** [comment]
Same problem here

**Comment by lminiero** [comment]
I don't have any authenticated RTSP server to test against, so not sure what's wrong. Anyway, we're bound to what libcurl provides in terms of RTSP authentication, which is probably not much. You may want to check if there are RTSP proxies that can help with that, e.g., if `live555ProxyServer` can take care of the authentication part and only expose a plain RTSP server you can then subscribe to (just thinking out loud here).

**Comment by lminiero** [comment]
Closing as there's nothing we can do to fix this. Any authentication scheme more complex than the one libcurl supports for RTSP will need support from external proxies.

**Comment by lminiero** [comment]
Just FYI, I just saw the same problem with a Foscam camera I was playing with. Apparently, regular clients (e.g., VLC) get a 401 as well, but then manage to get through. My guess is that there's some sort of challenge taking place, that either we or curl are not taking care of. Proxying with live555, e.g.:

    live555ProxyServer rtsp://user:pwd@192.168.1.121:88/videoSub

fixes it for me, as it's live555 that takes care of the authentication, and exposes a plain RTSP stream I can subscribe to. That said, I'll try and see if there's anything we can change in the code to fix this in the plugin as well (adding to TODO list with low priority).

**Comment by fbertone** [comment]
Do you have any traffic / requests dump to share?

**Comment by lminiero** [comment]
Not yet, I'll capture the RTSP exchange for sessions that work (e.g., via mplayer) and see how they differ from the exchange the Streaming plugin does instead. If it turns out to be challenge-based, we might check if there's anything we can do to fix it.

**Comment by lminiero** [comment]
Scratch that, authentication works just fine with my Foscam camera even without the proxy... like a newbie, I had a typo in the configuration file! :blush:

**Comment by jeremyarr** [comment]
FYI, getting the exact same issue with a DAHUA camera. Passing username and p/w in url works in VLC but get a 401 error when using Janus.

[my-rtsp-test]
type = rtsp
id = 999
description = myrtsp test
audio = no
video = yes
url = rtsp://admin:pwd@10.0.0.xx:554/cam/realmonitor?channel=1&subtype=1

Janus Error:
[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:3540] Couldn't get DESCRIBE code: 401

**Comment by lminiero** [comment]
Insert the credentials in the cfg using the related properties, not in the
rtsp url.

Il 30 ott 2017 12:51 AM, "Jeremy arr" <notifications@github.com> ha scritto:
