### ISSUE TITLE
DTLSv1_get_timeout: 956

### ISSUE THREAD

**Issue by kangshaojun** [meetecho/janus-gateway#842]
hi lminiero
my janus-gateway server trace a log:  DTLSv1_get_timeout: 956
some time one cant not  see another one  video , why?  thank you

**Comment by lminiero** [comment]
That's a verbose indication of how much time until the next DTLS timeout fires and we'll need to send a retransmission. Closing as not a bug.

**Comment by kangshaojun** [comment]
Thank you for your answer , but the dtls dont't handsnack complete
it's  retry  again by again

**Comment by lminiero** [comment]
Then you have to check the Admin API to see why. Questions for the group, we only use github for code issues.

**Comment by kangshaojun** [comment]
ok..  thank you  very much
