### ISSUE TITLE
janus RTSP H264 does not get sps/pps from DESCRIBE by parsing sprop-parameter-sets

### ISSUE THREAD

**Issue by saket424** [meetecho/janus-gateway#849]
Some RTSP cameras like Axis include the SPS/PPS info out of band in the RTSP DESCRIBE message and not ever repeated in any key frame. Can someone add RTSP support to parse the sprop-parameter-sets for H264 streams if they exist in the SDP ?

There is a publicly accessible axis camera @ rtsp://217.17.220.110/axis-media/media.amp

Sending request: DESCRIBE rtsp://217.17.220.110/axis-media/media.amp RTSP/1.0
CSeq: 2
User-Agent: LIVE555 Streaming Media v2016.02.09
Accept: application/sdp

Received 592 new bytes of response data.
Received a complete DESCRIBE response:
RTSP/1.0 200 OK
CSeq: 2
Content-Type: application/sdp
Content-Base: rtsp://217.17.220.110/axis-media/media.amp/
Date: Thu, 06 Apr 2017 22:30:55 GMT
Content-Length: 416

v=0
o=- 1491517855921810 1491517855921810 IN IP4 217.17.220.110
s=Media Presentation
e=NONE
b=AS:50000
t=0 0
a=control:*
a=range:npt=0.000000-
m=video 0 RTP/AVP 96
c=IN IP4 0.0.0.0
b=AS:50000
a=framerate:30.0
a=transform:-1,0,0;0,-1,0;0,0,1
a=control:trackID=1
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1; profile-level-id=420029; sprop-parameter-sets=Z0IAKeKQCgDLYC3AQEBpB4kRUA==,aM48gA==

**Comment by lminiero** [comment]
For RTSP, the Streaming plugin gets the whole SDP sent by the RTSP server and passes it to the browser, by adding WebRTC stuff to it. As such, the browser should already be getting the `sprop-parameter-sets` parameter if it's sent by the camera.

**Comment by saket424** [comment]
I attached the sdp in my original post. Janus fails to render this axis camera feed at rtsp://217.17.220.110/axis-media/media.amp . This feed works fine using vlc or https://github.com/mpromonet/webrtc-streamer (he has a herokuapp live demo where you can see the URL in action)


Any ideas on why Janus fails to render this axis-camera rtsp stream?

**Comment by lminiero** [comment]
I don't see the SDP Janus sends to the browser. Please provide that as well, as I can't do any testing myself right now. That should tell us what the browser is getting and if the parameter is missing for some reason.

**Comment by saket424** [comment]
SDP from Janus to the browser is attached below (obtained from setRemoteDecscription of chrome://webrtc-internals). sprop-parameter-sets parameter seems missing

type: offer, sdp: v=0
o=- 1491561334222489 1491561334222489 IN IP4 50.40.63.55
s=Streaming Test
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS janus
m=video 9 RTP/SAVPF 96
c=IN IP4 50.40.63.55
a=sendonly
a=mid:video
a=rtcp-mux
a=ice-ufrag:hwLa
a=ice-pwd:KTSaIEmUtZE1nBEXAFAw2b
a=ice-options:trickle
a=fingerprint:sha-256 7E:F6:B8:00:56:CB:64:7B:AA:68:38:EF:77:96:B5:7F:87:1E:7D:4F:6C:30:CA:0F:FD:A2:54:ED:F6:39:21:D4
a=setup:actpass
a=rtpmap:96 H264/90000
a=fmtp:96 packetization-mode=1;
a=rtcp-fb:96 nack
a=rtcp-fb:96 goog-remb
a=ssrc:3286696923 cname:janusvideo
a=ssrc:3286696923 msid:janus janusv0
a=ssrc:3286696923 mslabel:janus
a=ssrc:3286696923 label:janusv0
a=candidate:1 1 udp 2013266431 50.40.63.55 45899 typ host
a=candidate:1 2 udp 2013266430 50.40.63.55 40901 typ host


setLocalDescription from Browser in response is 
type: answer, sdp: v=0
o=- 103618907420407030 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE video
a=msid-semantic: WMS
m=video 9 RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:RB+f
a=ice-pwd:s+Uz3MnVk43lp17svcAlO7zl
a=fingerprint:sha-256 12:2E:BC:50:EA:9F:6A:6D:07:81:AE:2B:E0:F1:8D:CA:28:E2:71:7B:40:F6:ED:47:19:4F:65:E8:84:2C:A3:EC
a=setup:active
a=mid:video
a=recvonly
a=rtcp-mux
a=rtpmap:96 H264/90000
a=rtcp-fb:96 nack
a=rtcp-fb:96 goog-remb
a=fmtp:96 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f

Janus streaming demo page just spins spins with no media being rendered. I appreciate the support and engagement to get to the bottom of this issue.

**Comment by lminiero** [comment]
Please provide such dumps as gist/pastebin instead of pasting inline.

The parameter is indeed missing in the WebRTC SDP. Just did a quick check on the code again and I'm very likely mistaken when I say that for RTSP we just forward the SDP to the browser, as we generate one for every `watch` request no matter the source. I'll check the RTSP code later and see if there's a quick fix for this.

**Comment by lminiero** [comment]
Ok, I think I see the issue now... The camera is sending the `fmtp` attribute like this:

    a=fmtp:96 packetization-mode=1; profile-level-id=420029; sprop-parameter-sets=Z0IAKeKQCgDLYC3AQEBpB4kRUA==,aM48gA==

Since the plugin [parses the attribute](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L3154) like this:

    sscanf(f, "a=fmtp:%*d %2047s", fmtp);

it stops at the first whitespace, which means after `packetization-mode=1;`, and in fact in the WebRTC SDP that's all we see:

    a=fmtp:96 packetization-mode=1;

I guess we'll have to fix the way we parse that attribute to make it include the other parameters that may be present too.

**Comment by lminiero** [comment]
Can you try modifying the line in here:

https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_streaming.c#L3154

to this:

    sscanf(f, "a=fmtp:%*d %[^\r\n]s", fmtp);

do a new `make install` and let me know if it fixes it for you?

**Comment by saket424** [comment]
Good catch! Sure will do the validation and let you know shortly

**Comment by lminiero** [comment]
Actually I think that won't work, so no need to try... reading about the `%[^` thing, this does not stop at those termination characters, but just skips them, which is not what we want (you'll end up with a fmtp that contains the whole SDP, more or less). I'll have to work on some code to first take just the fmtp line, and only then apply that sscanf property. I'll let you know when I have a PR ready that does that, so that you can test it.

**Comment by saket424** [comment]
Actually I did already try and it does have the effect of the fmtp line of not being truncated and instead complete

a=fmtp:96 packetization-mode=1; profile-level-id=420029; sprop-parameter-sets=Z0IAKeKQCgDLYC3AQEBpB4kRUA==,aM48gA==

But ... , Now chrome(Version 57.0.2987.133 (Linux 64-bit)) bombs with that setRemoteDescription SDP
Not sure exactly whether it is unhappy with the profile level or the sprop-parameter-sets or both

**Comment by saket424** [comment]
I can confirm the chrome setRemoteDescription ERROR was due to profile-level-id=420029 and not sprop-parameter-sets=Z0IAKeKQCgDLYC3AQEBpB4kRUA==,aM48gA==

Still unable to render the remote axis-camera video... I thought we were close after your catch... I would appreciate if you(or others) can try rtsp://217.17.220.110/axis-media/media.amp and share your insights

**Comment by lminiero** [comment]
If the parameters go through with that change, and the browser still doesn't render the media, there isn't anything else we can do I'm afraid. If it's codec related (which I suspect) we don't transcode so it's the camera that needs to generate something the browser can digest.

**Comment by saket424** [comment]
I suggest you close this issue after implementing the sscanf fix which seems to work fine. Thanks

**Comment by saket424** [comment]
I switched rtsp sources to rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov and this has a more chrome-friendly fmtp packetization-mode=1;profile-level-id=42C01E;sprop-parameter-sets=Z0LAHtkDxWhAAAADAEAAAAwDxYuS,aMuMsg==

Still nothing is rendered in the janus streaming plugin. Packets are arriving from janus to the browser but none are being rendered. What could I be missing? I do have a recent libcurl > 7.45

ii  libcurl3:amd64                                7.47.0-1ubuntu2.2                             amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64                         7.47.0-1ubuntu2.2                             amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4-openssl-dev:amd64                    7.47.0-1ubuntu2.2                             amd64        development files and documentation for libcurl (OpenSSL flavour)

**Comment by lminiero** [comment]
Again, if packets get to the browsers and nothing is rendered, then it's likely a codec issue (explained above) and nothing we can do about it. Closing as not a Janus issue (will add the fix on Monday as I want to be 100% sure it doesn't misbehave).

**Comment by lminiero** [comment]
I thnk the fix works for you because the `a=fmtp` line is the last one. If it were somewhere in between, the issue I mentioned would occur, which means I cannot simply change the sscanf, I'll also have to split the line first.

**Comment by lminiero** [comment]
... although I just tested it with a sample string where fmtp is in between and it still works? Maybe the documentation for the negated scanset is just confusing and it's fine... I'll push the commit like that and we'll see if this will cause any trouble.

**Comment by lminiero** [comment]
Done in https://github.com/meetecho/janus-gateway/commit/c1537a6cc384252f3b412cc59dd715f827d471c4
