### ISSUE TITLE
Non-opus encoding for Janus?

### ISSUE THREAD

**Issue by czarina** [meetecho/janus-gateway#853]
Hi,

I see that Janus takes Opus encoded audio, but does it support, say, mp3?

I ask because I'm streaming from my Pi Zero with gstreamer, and Opus encoding takes the Pi's entire CPU and drops tons of audio packets, whereas Lame MP3 encoding, for some reason, uses <5% CPU. I'm encoding using gstreamer, and simply going from  `..lamemp3enc ! rtpmpapay..` to `..opusenc ! rtpopuspay ..` shoots my CPU usage from 5% to 100%.

**Comment by lminiero** [comment]
It's not a matter of whether Janus supports mp3, but if browsers do, and mp3 is not supported as a codec for WebRTC. The only standard alternative to Opus in WebRTC is G.711, which is very lightweight, but the quality would be quite bad. You may check if there are parameters that allow you to reduce the load Opus encoding adds (e.g., complexity). Closing as not an issue, please refer to the meetecho-janus group for further discussion.
