### ISSUE TITLE
videoroom stuck from webrtc m56

### ISSUE THREAD

**Issue by notedit** [meetecho/janus-gateway#857]
i have test multi webrtc version,   from native to web.

**Comment by lminiero** [comment]
You'll have to be way more precise than that, if you want us to help... I don't even understand what the issue is.

**Comment by notedit** [comment]
sorry.    

i just update to M57 webrtc,  when i connect to janus with videoroom, i can  receive the remote stream and the bandwidth  gains,  it means the peerconnection is up.  audio works fine,  but video will stuck  a few seconds again and again.
