### ISSUE TITLE
Cross Compile Error 

### ISSUE THREAD

**Issue by lancevalour** [meetecho/janus-gateway#858]
Great project, I tested on Ubuntu and it works fine. 

I am trying to compile the project on Linux ARMv7L and see error when trying to configure:

```commandline
./configure --host --prefix=/opt/janus
```

Error Message is below:

[Error Message](https://gist.github.com/lancevalour/2383458c33f9c63dad9e873bf79957c0)

Any suggestions on the error or cross compilation on other linux distributions?

Thanks,
Yicheng

**Comment by lminiero** [comment]
Shouldn't you set `--host` to something? Not an expert on cross compilation, so not sure. Anyway, closing as not a code issue: please discuss on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) where somebody may have already solved this.
