### ISSUE TITLE
Timeout/event for for remote hanged streams?

### ISSUE THREAD

**Issue by anildigital** [meetecho/janus-gateway#862]
Hi,

While testing WebRTC I notice, in Janus videoroom, I am connected and I can see remote publishers.

Now I change WiFi or connect to VPN and then I refresh videoroom (of if another publisher does that)

What I see is that the old streams are still there, showing nothing. So WebRTC is receiving remote streams from Janus for dead WebRTC sessions?

Is there any event that Janus is supposed to send, upon which I can remove that remote publisher stream from browser using a local JS document element remove call?

Am I missing anything?

Please see how my VideoRoom looks when someone changes WiFi or joins VPN.

<img width="907" alt="hanged_streams" src="https://cloud.githubusercontent.com/assets/266/25003752/939fa406-206e-11e7-88aa-c98e21afdbb1.png">

**Comment by lminiero** [comment]
Closing as you already opened more than one discussion on this on the group.
