### ISSUE TITLE
HTTP server won't start

### ISSUE THREAD

**Issue by raqua** [meetecho/janus-gateway#863]
Hi, 

I have installed janus and can not seem to start it, using basically default configs. I am on Arch Linux on Raspberry Pi 3 and I can't tell, whether there is issue with my system or I have found some strange bug, because googling did not really found anyone else having this problem. 
Logs:

Starting Meetecho Janus (WebRTC Gateway) v0.2.2

Checking command line arguments...
[janus.cfg]
    [general]
        configs_folder: /etc/janus
        plugins_folder: /usr/lib/janus/plugins
        transports_folder: /usr/lib/janus/transports
        events_folder: /usr/lib/janus/events
        debug_level: 7
        admin_secret: janusoverlord
    [certificates]
        cert_pem: /usr/share/janus/certs/mycert.pem
        cert_key: /usr/share/janus/certs/mycert.key
    [media]
    [nat]
        nice_debug: false
        ice_ignore_list: vmnet
    [plugins]
    [transports]
    [events]
Debug/log level is 7
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Selecting local IP address...
Autodetecting local IP...
Using 10.75.69.123 as local IP...
[WARN] Token based authentication disabled
Initializing recorder code
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, IPv6 support disabled)
ICE handles watchdog started
TURN REST API backend: (disabled)
[WARN] Janus is deployed on a private address (10.75.69.123) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
BUNDLE is NOT going to be forced
rtcp-mux is NOT going to be forced
  -- RTCP component blackhole socket bound to port 48595
Using certificates:
	/usr/share/janus/certs/mycert.pem
	/usr/share/janus/certs/mycert.key
Crypto: OpenSSL pre-1.1.0
Fingerprint of our certificate: 52:48:8E:26:5B:95:FD:56:76:78:6E:A7:41:B3:E9:89:DB:F2:87:2D:E4:4B:73:2E:A3:37:5D:9C:E3:BF:8A:B1
Event handler plugins folder: /usr/lib/janus/events
Sessions watchdog started
[WARN] Event handlers support disabled
Joining Events handler thread
Leaving EchoTest handler thread
Plugins folder: /usr/lib/janus/plugins
Loading plugin 'libjanus_streaming.so'...
JANUS Streaming plugin created!
Configuration file: /etc/janus/janus.plugin.streaming.cfg
[janus.plugin.streaming.cfg]
    [general]
    [raspicam]
        type: rtp
        id: 10
        description: H.264 live stream coming from gstreamer
        audio: no
        video: yes
        videoport: 8004
        videopt: 126
        videortpmap: H264/90000
        videofmtp: profile-level-id=42e01f;packetization-mode=1
Adding stream 'raspicam'
Audio NOT enabled, Video enabled, Data NOT enabled
Audio NOT enabled, Video enabled, Data NOT enabled
Starting streaming relay thread
  ::: [10][raspicam] H.264 live stream coming from gstreamer (live, RTP source, public, pin: no pin)
JANUS Streaming plugin initialized!
Joining Streaming handler thread
	Version: 7 (0.0.7)
Streaming watchdog started
	   [janus.plugin.streaming] JANUS Streaming plugin
	   This is a streaming plugin for Janus, allowing WebRTC peers to watch/listen to pre-recorded files or media generated by gstreamer.
	   Plugin API version: 8
Loading plugin 'libjanus_textroom.so'...
JANUS TextRoom plugin created!
Configuration file: /etc/janus/janus.plugin.textroom.cfg
[janus.plugin.textroom.cfg]
    [general]
        json: indented
    [1234]
        description: Demo Room
        secret: adminpwd
Adding text room '1234'
Created textroom: 1234 (Demo Room, public, secret: adminpwd, pin: no pin)
  ::: [1234][Demo Room]
Joining TextRoom handler thread
TextRoom watchdog started
JANUS TextRoom plugin initialized!
	Version: 2 (0.0.2)
	   [janus.plugin.textroom] JANUS TextRoom plugin
	   This is a plugin implementing a text-only room for Janus, using DataChannels.
	   Plugin API version: 8
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin created!
Configuration file: /etc/janus/janus.plugin.echotest.cfg
[janus.plugin.echotest.cfg]
    [general]
Joining EchoTest handler thread
JANUS EchoTest plugin initialized!
	Version: 6 (0.0.6)
	   [janus.plugin.echotest] JANUS EchoTest plugin
EchoTest watchdog started
	   This is a trivial EchoTest plugin for Janus, just used to showcase the plugin interface.
	   Plugin API version: 8
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin created!
Configuration file: /etc/janus/janus.plugin.videocall.cfg
[janus.plugin.videocall.cfg]
    [general]
Joining VideoCall handler thread
JANUS VideoCall plugin initialized!
	Version: 5 (0.0.5)
	   [janus.plugin.videocall] JANUS VideoCall plugin
	   This is a simple video call plugin for Janus, allowing two WebRTC peers to call each other through the gateway.
	   Plugin API version: 8
Loading plugin 'libjanus_recordplay.so'...
VideoCall watchdog started
JANUS Record&Play plugin created!
Configuration file: /etc/janus/janus.plugin.recordplay.cfg
[janus.plugin.recordplay.cfg]
    [general]
        path: /usr/share/janus/recordings
Updating recordings list in /usr/share/janus/recordings
Importing recording '1234.nfo'...
JANUS Record&Play plugin initialized!
Joining Record&Play handler thread
	Version: 3 (0.0.3)
	   [janus.plugin.recordplay] JANUS Record&Play plugin
	   This is a trivial Record&Play plugin for Janus, to record WebRTC sessions and replay them.
	   Plugin API version: 8
Record&Play watchdog started
Loading plugin 'libjanus_sip.so'...
JANUS SIP plugin created!
Configuration file: /etc/janus/janus.plugin.sip.cfg
[janus.plugin.sip.cfg]
    [general]
        keepalive_interval: 120
        behind_nat: no
        register_ttl: 3600
Autodetecting local IP...
Local IP set to 10.75.69.123
SIP keep-alive interval set to 120 seconds
SIP registration TTL set to 3600 seconds
SIP User-Agent set to Janus WebRTC Gateway SIP Plugin 0.0.6
JANUS SIP plugin initialized!
SIP watchdog started
Joining SIP handler thread
	Version: 6 (0.0.6)
	   [janus.plugin.sip] JANUS SIP plugin
	   This is a simple SIP plugin for Janus, allowing WebRTC peers to register at a SIP server and call SIP user agents through the gateway.
	   Plugin API version: 8
Loading plugin 'libjanus_voicemail.so'...
JANUS VoiceMail plugin created!
Configuration file: /etc/janus/janus.plugin.voicemail.cfg
[janus.plugin.voicemail.cfg]
    [general]
        path: /tmp/voicemail/
        base: /voicemail/
        events: yes
Recordings path: /tmp/voicemail/
Recordings base: /voicemail/
JANUS VoiceMail plugin initialized!
	Version: 6 (0.0.6)
	   [janus.plugin.voicemail] JANUS VoiceMail plugin
	   This is a plugin implementing a very simple VoiceMail service for Janus, recording Opus streams.
	   Plugin API version: 8
Loading plugin 'libjanus_videoroom.so'...
VoiceMail watchdog started
Joining VoiceMail handler thread
JANUS VideoRoom plugin created!
Configuration file: /etc/janus/janus.plugin.videoroom.cfg
[janus.plugin.videoroom.cfg]
    [general]
    [1234]
        description: Demo Room
        secret: adminpwd
        publishers: 6
        bitrate: 128000
        fir_freq: 10
        record: false
Adding video room '1234'
Created videoroom: 1234 (Demo Room, public, opus/vp8 codecs, secret: adminpwd, pin: no pin)
  ::: [1234][Demo Room] 128000, max 6 publishers, FIR frequency of 10 seconds, opus audio codec, vp8 video codec
JANUS VideoRoom plugin initialized!
	Version: 8 (0.0.8)
	   [janus.plugin.videoroom] JANUS VideoRoom plugin
VideoRoom watchdog started
Joining VideoRoom handler thread
	   This is a plugin implementing a videoconferencing SFU (Selective Forwarding Unit) for Janus, that is an audio/video router.
	   Plugin API version: 8
Loading plugin 'libjanus_audiobridge.so'...
JANUS AudioBridge plugin created!
Configuration file: /etc/janus/janus.plugin.audiobridge.cfg
[janus.plugin.audiobridge.cfg]
    [general]
    [1234]
        description: Demo Room
        secret: adminpwd
        sampling_rate: 16000
        record: false
Adding audio room '1234'
Sampling rate for mixing: 16000
Created audiobridge: 1234 (Demo Room, public, secret: adminpwd, pin: no pin)
Audio bridge thread starting...
Thread is for mixing room 1234 (Demo Room) at rate 16000...
  ::: [1234][Demo Room] 16000 (will NOT be recorded)
JANUS AudioBridge plugin initialized!
Joining AudioBridge handler thread
	Version: 10 (0.0.10)
	   [janus.plugin.audiobridge] JANUS AudioBridge plugin
	   This is a plugin implementing an audio conference bridge for Janus, mixing Opus streams.
	   Plugin API version: 8
Transport plugins folder: /usr/lib/janus/transports
AudioBridge watchdog started
Loading transport plugin 'libjanus_rabbitmq.so'...
JANUS RabbitMQ transport plugin created!
Configuration file: /etc/janus/janus.transport.rabbitmq.cfg
[janus.transport.rabbitmq.cfg]
    [general]
        enable: no
        json: indented
        host: localhost
        to_janus: to-janus
        from_janus: from-janus
    [admin]
[WARN] RabbitMQ support disabled (Janus API)
[WARN] RabbitMQ support disabled (Admin API)
[WARN] RabbitMQ support disabled for both Janus and Admin API, giving up
[WARN] The 'janus.transport.rabbitmq' plugin could not be initialized
Loading transport plugin 'libjanus_pfunix.so'...
JANUS Unix Sockets transport plugin created!
Configuration file: /etc/janus/janus.transport.pfunix.cfg
[janus.transport.pfunix.cfg]
    [general]
        enabled: yes
        json: indented
        path: /tmp/ux-janusapi
    [admin]
        admin_enabled: no
        admin_path: /tmp/ux-janusadmin
Configuring SOCK_SEQPACKET Unix Sockets server (Janus API)
Binding Unix Socket /tmp/ux-janusapi... (Janus API)
Listening on Unix Socket /tmp/ux-janusapi...
[WARN] Unix Sockets server disabled (Admin API)
JANUS Unix Sockets transport plugin initialized!
Unix Sockets thread started
	Version: 1 (0.0.1)
	   [janus.transport.pfunix] JANUS Unix Sockets transport plugin
	   This transport plugin adds Unix Sockets support to the Janus API.
	   Plugin API version: 6
	   Janus API: enabled
	   Admin API: disabled
Loading transport plugin 'libjanus_mqtt.so'...
JANUS MQTT transport plugin created!
Configuration file: /etc/janus/janus.transport.mqtt.cfg
[janus.transport.mqtt.cfg]
    [general]
        enable: no
        json: indented
        url: tcp://localhost:1883
        subscribe_topic: to-janus
        publish_topic: from-janus
    [admin]
        subscribe_topic: to-janus-admin
        publish_topic: from-janus-admin
[WARN] MQTT support disabled for both Janus and Admin API, giving up
JANUS MQTT transport plugin destroyed!
[WARN] The 'janus.transport.mqtt' plugin could not be initialized
Loading transport plugin 'libjanus_http.so'...
JANUS REST (HTTP/HTTPS) transport plugin created!
Configuration file: /etc/janus/janus.transport.http.cfg
[janus.transport.http.cfg]
    [general]
        json: indented
        base_path: /janus
        threads: unlimited
        http: yes
        port: 8088
        https: no
    [admin]
        admin_base_path: /admin
        admin_threads: unlimited
        admin_http: no
        admin_port: 7088
        admin_https: no
    [certificates]
        cert_pem: /usr/share/janus/certs/mycert.pem
        cert_key: /usr/share/janus/certs/mycert.key
Using a thread per connection for the Janus API HTTP webserver
Binding to all interfaces for the Janus API HTTP webserver
[FATAL] [transports/janus_http.c:janus_http_init:689] Couldn't start webserver on port 8088...
Using certificates:
	/usr/share/janus/certs/mycert.pem
	/usr/share/janus/certs/mycert.key
[WARN] HTTPS webserver disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
[FATAL] [transports/janus_http.c:janus_http_init:805] No HTTP/HTTPS server started, giving up...
[WARN] The 'janus.transport.http' plugin could not be initialized
Loading transport plugin 'libjanus_websockets.so'...
JANUS WebSockets transport plugin created!
libwebsockets >= 1.6 available, using new API
Configuration file: /etc/janus/janus.transport.websockets.cfg
[janus.transport.websockets.cfg]
    [general]
        json: indented
        ws: yes
        ws_port: 8188
        wss: no
    [admin]
        admin_ws: no
        admin_ws_port: 7188
        admin_wss: no
    [certificates]
        cert_pem: /usr/share/janus/certs/mycert.pem
        cert_key: /usr/share/janus/certs/mycert.key
libwebsockets logging: 0
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
[WARN] Admin WebSockets server disabled
[WARN] Secure Admin WebSockets server disabled
WebSocket (Janus API) thread started
JANUS WebSockets transport plugin initialized!
	Version: 1 (0.0.1)
	   [janus.transport.websockets] JANUS WebSockets transport plugin
	   This transport plugin adds WebSockets support to the Janus API via libwebsockets.
	   Plugin API version: 6
	   Janus API: enabled
	   Admin API: disabled
[WSS-0x63f7591c] 27 (LWS_CALLBACK_PROTOCOL_INIT)

Thanks.

**Comment by alexamirante** [comment]
Please read the [guidelines](https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md) before opening issues.

Closing as this belongs to the [meetecho-janus](https://groups.google.com/d/forum/meetecho-janus) forum. **Don't** paste logs in-line there, but use services like gist or pastebin.

**Comment by khinthuzaraung** [comment]
[ERR] [janus.c:main:4064]       Couldn't load plugin 'libjanus_sip.so': libsofia-sip-ua.so.0: cannot open shared object file: No such file or directory

I got this error how can I do?
