### ISSUE TITLE
WebSocket transport causes crash upon opening secure connection

### ISSUE THREAD

**Issue by grimlock-** [meetecho/janus-gateway#868]
This happens with my own certs as well as those currently in the repository. I thought this was a problem with how I built libwebsockets, but the lws test server was able to accept encrypted connections, so that doesn't appear to be the problem.
I don't have any plugins enabled, this is just while trying to interact with the gateway using the following javascript:
`ws_connection = new WebSocket("wss://192.168.43.4:8989", 'janus-protocol');`

OS, package versions, etc.:
```
OS: Ubuntu 14.04 LTS
Architecture: x86_64
OpenSSL version: 1.0.1f (distro package)
libsrtp version: 2.0 (manual build)
libwebsockets version: 2.2.0 (manual build)
```

janus.cfg
https://pastebin.com/G9CRXxHe

janus.transport.websockets.cfg
https://pastebin.com/sh04mXEr

These are the commands I used to build libwebsockets
```
git clone https://github.com/warmcat/libwebsockets.git
cd libwebsockets
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..
make
make install
```

and these are the ones for libsrtp
```
wget https://github.com/cisco/libsrtp/archive/v2.0.0.tar.gz
tar xfv v2.0.0.tar.gz
cd libsrtp-2.0.0
./configure --prefix=/usr --enable-openssl
make shared_library && sudo make install
```

Here's a backtrace after the crash
https://pastebin.com/47AYBmn3

If there's any more info you need just let me know.

**Comment by grimlock-** [comment]
oh yeah, here's the output from janus itself. I also just noticed the ws_logging proptery for the config file. I set the log level to 1023 for this output
https://pastebin.com/a6p1RTdW

**Comment by lminiero** [comment]
Sorry for this late reply, apparently I missed the notification on this issue.

I can't seem to be able to replicate this, it works just fine for me. Looking at the Janus log you mentioned, I see that you try to force a specific IP to bind to, but that apparently it fails (and not only for WebSockets):

```
[WARN] No interface associated with 192.168.43.4? Falling back to no interface...
```

anyway, then that's the address you try to connect to:

```
ws_connection = new WebSocket("wss://192.168.43.4:8989", 'janus-protocol');
```

Are you sure it's not just simply the wrong address/interface? From what I can see in the autodetect part of the log, the address seems to be different for the machine:

```
Selecting local IP address...
  -- Will try to use 192.168.43.4
[WARN] Error setting local IP address to 192.168.43.4, falling back to detecting IP address...
Using 192.168.43.187 as local IP...
```

**Comment by grimlock-** [comment]
Yes I'm connecting to the right address. I'm just getting the logs a little mixed up between my physical testing server and the VM I set up to debug this issue which I realize is rather confusing, sorry. The *.43.4 address is the IP for my physical server, but the log in my second post comes from the VM which was using the physical server's config file, but since the VM wasn't using NAT it was getting it's IP from my router which assigned it a different IP than *.43.4

If you're able to start up a VM with a fresh installation of Ubuntu, I have the steps for replicating the crash

1) Install Ubuntu 14.04.05 LTS (Server install image, not Desktop image)
URL: http://releases.ubuntu.com/14.04/
2) For the option asking about updates, set it to install security updates automatically
3) For the step asking what configurations to start with (i.e. LAMP server, OpenSSH server, Postgres server, etc.) check the OpenSSH option
4) Run this script as root: https://pastebin.com/2sfzB2kk
5) Replace the default "janus.cfg" and "janus.transport.websockets.cfg" files (found in /usr/local/etc/janus) with the files from my first post
6) Start janus as root
7) Open a WebSocket connection using the javascript from my first post (after changing the IP address to the VM's IP)

I'm not sure this makes a difference, but I'm running the javascript code from firefox via the F12 dev tools as opposed to loading a webpage.

**Comment by lminiero** [comment]
Still unable to replicate, so may be an issue with your libwebsockets installation. As a fix for this, try using a proxy to handle the secure part (e.g., nginx), and only use the plain websockets support in Janus itself. That's what we do in our own deployments for HTTP too.
