### ISSUE TITLE
Need a way to set "output" in demo

### ISSUE THREAD

**Issue by chadfurman** [meetecho/janus-gateway#869]
Unless my local copy is outdated, the device selection demo needs to include audio output device selection also.  It's different than input selection, as it's not a media constraint but a sink attached to each video element.

Edit: Just putting this here until I get around to making a PR for it.

**Comment by lminiero** [comment]
The device selection demo was never meant to list output devices, only input ones. Anyway, looks it wouldn't be [that hard](https://developers.google.com/web/updates/2015/10/media-devices), as we select them already (`enumerateDevices` returns them all) and we're currently filtering them out when we check `device.kind`. I'll have a look tomorrow (National holiday in Italy today).

**Comment by mirkobrankovic** [comment]
Exactly, then just pass the deviceid of that kind to selecting list and selected id to the constraints

**Comment by chadfurman** [comment]
Sink Id doesn't go in constraints though does it? Has to be attached to the
video elements?

**Comment by mirkobrankovic** [comment]
Sink Id?
Basicly enumerateDevice will return the device types/kind and ids, so if you want to take any of the specific device source it is simple as passing that same id to constranit deviceid attribute.

**Comment by lminiero** [comment]
Sink id does not go in the constraints, it's a property you set on the video element (at least that's what the example says). As such, I don't really believe it belongs to janus.js, but to the application level (in this case, the device test demo alone).

**Comment by lminiero** [comment]
Mh, looks like it's only available on Chrome 49...
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId
Is it really worth the trouble of adding something to the demo only a few people will be able to use?

**Comment by chadfurman** [comment]
Chrome 56+ has over 35% marketshare.  That's potentially almost a billion people.

Also, this is a feature in Google Hangouts.  And if you can pick your input, why not also the audio output?

**Comment by lminiero** [comment]
Yeah, but I mean, there's not much point in adding a feature to the demo if it won't work in Firefox. Besides, Google Hangouts is a very bad example to make: talk about a browser-specific application, where standards don't apply :wink: 

Anyway, I'll try to come up with a way to add the feature in a way that won't make Firefox users feel they're 2nd class citizens.

**Comment by lminiero** [comment]
Please check the PR and let me know.

**Comment by lminiero** [comment]
Any feedback on the PR? If it works, I'd like to merge soon.
