### ISSUE TITLE
You can break the rooms SDP if you pass Invalid room name(AKA desc).

### ISSUE THREAD

**Issue by IvRRimum** [meetecho/janus-gateway#874]
Okey, i figured this out.

When you create a room with a name: " " - Space character, without the quotes.
And then enter the room, the SDP answer becomes invalid.

The reason behind is pretty simple, the SDP answer includes current rooms name, heres the example with room name(dasdasadsdsa):
<img width="538" alt="screen shot 2017-04-27 at 21 56 42" src="https://cloud.githubusercontent.com/assets/5957079/25498708/be6d42aa-2b91-11e7-887a-7b601e4e3315.png">

However, if we set room name as( ): We get SDP error:
<img width="922" alt="screen shot 2017-04-27 at 21 59 11" src="https://cloud.githubusercontent.com/assets/5957079/25498737/d4c6bf40-2b91-11e7-92d2-3f933c4caf5e.png">

I think these kinds of validations would be better to do in janus side.

Thanks!

**Comment by IvRRimum** [comment]
@lminiero Should i make PR?

**Comment by lminiero** [comment]
Good catch: we should probably only use the numeric ID in the session name (e.g., `s=audioroom 1234\r\n`), or even something that's the same for all rooms (e.g., `s=AudioBridge room\r\n`). I think we're doing something similar in other plugins, so we'd better fix that there as well.

**Comment by lminiero** [comment]
> @lminiero Should i make PR?

No need, I'll make the changes myself, since as I said it's going to be needed in other plugins as well.

**Comment by lminiero** [comment]
This should fix it :+1:
