### ISSUE TITLE
Videoroom plugin bitrate settings appear to have no effect

### ISSUE THREAD

**Issue by gatecrasher777** [meetecho/janus-gateway#88]
Unlike in echo test (per demo site) where changes in bitrate setting has an immediate and noticeable effect on video quality, setting the bitrate in the videoroom (on own server) has no noticeable effect. 

This was also mentioned here:  https://groups.google.com/forum/#!topic/meetecho-janus/2q-JDnESph0

**Comment by BenJaziaSadok** [comment]
@gatecrasher777 sorry for replying on an old post, any details on how you solved that
