### ISSUE TITLE
Error - ICE failed for component 1 in stream 1...

### ISSUE THREAD

**Issue by mistermadness87** [meetecho/janus-gateway#881]
Hello, sometimes I recieve such message in Janus log
`[31m[ERR][0m [ice.c:janus_ice_cb_component_state_changed:1554] [2997678691141538] ICE failed for component 1 in stream 1...`
When it happening I recieve 200 to BYE message just when I pick up the phone. 
Usually in log I see
`[33m[WARN][0m [718193224858111] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)`
In that case everything work perfect. 
I'm using self signed default cert.
My OS DEBIAN 8.0.
This happening once on about 30 incoming calls
Thank you.

**Comment by lminiero** [comment]
The "still waiting" means that, while ICE failed for now, there may be other candidates arriving later that wuld work. A normal ICE failure means ICE failed definitely, and so you should check Admin API or Event Handlers to see why. Closing as not a code issue, please refer to the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
