### ISSUE TITLE
Bug: incorrect variable being checked for ending '/'

### ISSUE THREAD

**Issue by cbiggin** [meetecho/janus-gateway#882]
File: transports/janus_http.c

Line 624 is:
			if(strlen(admin_ws_path) > 1 && ws_path[strlen(admin_ws_path)-1] == '/') {

Should be:
			if(strlen(admin_ws_path) > 1 && admin_ws_path[strlen(admin_ws_path)-1] == '/') {

**Comment by lminiero** [comment]
Good catch, thanks! I'll fix right away.
