### ISSUE TITLE
sip plugin causes core dump for guest login if no username is provided

### ISSUE THREAD

**Issue by derrell** [meetecho/janus-gateway#885]
The sip example in the html directory states that one should be able to register as a guest, without a username. It prevents the user from actually doing so, however, which covers up a core dump in the sip plugin. Registering with:
```json
{
  message :
  {
    request  : "register",
    type     : "guest"
  }
}
```
causes the sip plugin to dump core because near line 1547, `g_strdup(username_text)` is attempting to copy NULL. The most simple fix is, near line 1508, to assign `username_text` to be the generated `user_id` value, as shown at the bottom of the following snippet:

```js
if(guest) {
	/* Not needed, we can stop here: just pick a random username if it wasn't provided and say we're registered */
	if(!username)
		g_snprintf(user_id, 255, "janus-sip-%"SCNu32"", janus_random_uint32());
	JANUS_LOG(LOG_INFO, "Guest will have username %s\n", user_id);
	send_register = FALSE;
        if (!username_text) {
                username_text = user_id; /* Ensure username_text has a value to assign identity, below */
        }
```

This fixes the core dump, but is not really a complete fix. The automatically generated id will now be used in the From: header of the INVITE, but is not a properly formed sip URI, so some (many?) servers refuse to accept that INVITE message. I propose changing the automatically-generated username to be a properly formed sip URI, so the above g_snprintf should become something like:

```js
g_snprintf(user_id, 255, "sip:janus-sip-%"SCNu32"@example.com", janus_random_uint32());
```

Derrell

**Comment by lminiero** [comment]
Excellent find, thanks for spotting this! I'm currently traveling, so I'll
apply a fix as soon as I can.

Il 10 mag 2017 3:45 PM, "Derrell Lipman" <notifications@github.com> ha
scritto:

**Comment by lminiero** [comment]
I think that, rather than "crafting" a SIP uri ourselves, we can simply force the username to be provided even for the guest case. I'll try to work on a quick patch now, although not sure I'll be able to push it right away (at the airport right now).

**Comment by lminiero** [comment]
Done, please let me know if that's still an issue.
