### ISSUE TITLE
Bind failed for audio RTP (port xxxx), trying a different one

### ISSUE THREAD

**Issue by bizzr3** [meetecho/janus-gateway#889]
getting this after a while 60 active calls. 

i have some issues on client side related to losing their ip conflict, is it related to that issue or is something else ? 

No WebRTC media anymore
Detaching handle from JANUS SIP plugin
No WebRTC media anymore
[6576351470770542] WebRTC resources freed
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_handler:2084] Wrong state (not in a call? status=idle)
[33m[WARN][0m [4312722926528899]     audio stream component has no valid SRTP session (yet?)
[4312722926528899] The DTLS handshake has been completed
WebRTC media is now available
[33m[WARN][0m [7653541488725361] ICE failed for component 1 in stream 1, but we're still waiting for some info so we don't care... (trickle pending, answer received, alert not set)
[33m[WARN][0m [7653541488725361]     audio stream component has no valid SRTP session (yet?)
[7653541488725361] The DTLS handshake has been completed
WebRTC media is now available
[WSS-0x7f30240385d0] Destroying WebSocket client
Cleaning up handle 1601203724883993...
[1601203724883993] WebRTC resources freed
[1601203724883993] Handle and related resources freed
[2226843489676772] Creating ICE agent (ICE Full mode, controlled)
Detaching handle from JANUS SIP plugin
No WebRTC media anymore
Cleaning up handle 2944180279234701...
[2944180279234701] WebRTC resources freed
[2944180279234701] Handle and related resources freed
Creating new session: 3336417245469715
Creating new handle in session 3336417245469715: 6129087013599935
Creating new session: 8399143698621823
[1548986369899428] Creating ICE agent (ICE Full mode, controlled)
Creating new handle in session 8399143698621823: 521088008330056
[6129087013599935] Creating ICE agent (ICE Full mode, controlled)
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 11942), trying a different one...
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 18014), trying a different one...
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 21704), trying a different one...
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 43986), trying a different one...
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 40304), trying a different one...
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 55304), trying a different one...
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 53924), trying a different one...
[31m[ERR][0m [plugins/janus_sip.c:janus_sip_allocate_local_ports:3133] Bind failed for audio RTP (port 38460), trying a different one...
.
.
.
.
.

and then crashed

**Comment by lminiero** [comment]
Closing as you blatantly ignored the guidelines. Please read them again before opening a new issue.
