### ISSUE TITLE
Videoroom playback freezes (frames dropping)

### ISSUE THREAD

**Issue by gatecrasher777** [meetecho/janus-gateway#89]
From https://groups.google.com/forum/#!topic/meetecho-janus/cZWQ0nsdM0k

These are samples using two different ISPs, showing the vast difference between frames received and frames decoded in Chrome. I think it is this difference that is causing the video freezes.  There doesn't seem to be any issues with audio.  Echo test does much better than the videoroom plugin with a fairly close resemblance between the two graphs in Chrome. Although on Firefox, the echo test performs poorly.

![janus_fr](https://cloud.githubusercontent.com/assets/8722680/5038167/79fa5c7e-6b96-11e4-9a48-39be9ec49fde.jpg)
![janus_fr2](https://cloud.githubusercontent.com/assets/8722680/5038173/825852c2-6b96-11e4-89a7-1d57412b08eb.jpg)

**Comment by heisGarvit** [comment]
Video Playback is still freezing in `Chrome Version 80.0.3987.163 (Official Build) (64-bit)`  however I installed firefox on same machine & it didn't lag `Firefox 75.0 (64-Bit)` so message to future visitors before messing with server do **switch browsers**!!
