### ISSUE TITLE
Undefined symbol error on Janus start

### ISSUE THREAD

**Issue by thelasthope4U** [meetecho/janus-gateway#891]
Attempting to build and run Janus branch sendthread-fix.
DId a make clean;
Updated local repository;
changed to sendthread-fix branch;
Compiled and installed.

On startup the following error was reported.
    Plugins folder: /opt/janus/lib/janus/plugins
    Loading plugin 'libjanus_sip.so'...
    janus: symbol lookup error: /opt/janus/lib/janus/plugins/libjanus_sip.so: undefined symbol: 
    janus_network_detect_local_ip_as_string

repeated with master branch and same error occured.  Verified that source code is correct and undefined symbol is present.

**Comment by lminiero** [comment]
What OS and gcc version? Dependencies?

**Comment by thelasthope4U** [comment]
Ubuntu 16.04.1 LTS
gcc version 5.4.0
dont know of any dependencies, not sure what you mean in this regard.

**Comment by lminiero** [comment]
> dont know of any dependencies, not sure what you mean in this regard

Yeah, sorry, I was confusing your problem with another issue... I shouldn't reply in the morning! :smile:

**Comment by joshdickson40** [comment]
You mentioned that you did a libsrtp update, could you try installing on a clean build of Ubuntu from a semi-recent kernel?

My Janus install for 16.04 looks like:

```
# install dependencies
sudo apt-get install -y libmicrohttpd-dev libcurl4-openssl-dev libjansson-dev libnice-dev libssl-dev libsofia-sip-ua-dev libglib2.0-dev libopus-dev libogg-dev pkg-config gengetopt libtool automake

# install updated version of libsrtp
wget https://github.com/cisco/libsrtp/archive/v2.0.0.tar.gz
tar xfv v2.0.0.tar.gz
cd libsrtp-2.0.0
./configure --prefix=/usr --enable-openssl
make shared_library && sudo make install
cd ~

# install urssctp for data channel support
git clone https://github.com/sctplab/usrsctp
cd usrsctp
./bootstrap
./configure --prefix=/usr && make && sudo make install
cd ~

# build janus
git clone https://github.com/meetecho/janus-gateway.git
cd janus-gateway
sh autogen.sh
./configure --prefix=/opt/janus --disable-websockets --disable-rabbitmq --disable-mqtt --disable-plugin-recordplay --disable-plugin-sip
make
sudo make install

# make sample docs
sudo make configs

# edit configs to your liking

```


If you want to start Janus on server boot:

```
# move systemd config into position
sudo mv ~/janus.service /etc/systemd/system/janus.service

# endble janus.service
sudo systemctl enable janus
```

**Comment by thelasthope4U** [comment]
Okay, I will give it a try tonight.  I noticed that you disable plugin-sip.  I don't use sip so I can do that.  
Will follow up later

**Comment by joshdickson40** [comment]
That's just as an example, it should work either way, though it's not a bad idea to disable everything you don't use. 

On Thu, May 18, 2017 at 18:29 thelasthope4U

<
mailto:thelasthope4U <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Okay, I will give it a try tonight. I noticed that you disable plugin-sip. I don't use sip so I can do that.

Will follow up later

—

You are receiving this because you commented.

Reply to this email directly,
https://github.com/meetecho/janus-gateway/issues/891#issuecomment-302559257
, or

**Comment by thelasthope4U** [comment]
Okay, success achieved, thanks much.
I installed new ubuntu 16.4, intalled janus and all works.    Would like to eventually know what happened on previous installation.  I would expect we will eventually have to update a production janus in the field someday so it is going to be important to learn what caused the previous issue.

Don't know for sure if this is a problem with the repository that I pulled or if it was the server.

@lminiero should this issue be closed?  I have been working in virtual machines so I have the one that would not start if additional troubleshooting is desired.

Thanks again everyone for the help

**Comment by joshdickson40** [comment]
You can close as this is definitely an issue with the dependencies and not Janus itself. In the future it's a good idea to build from a clean OS image if you need to upgrade the manually installed dependencies.

**Comment by lminiero** [comment]
@thelasthope4U when you say "all worls", is it when you disable the SIP plugin? If so, it only works because you simply disabled the compilation of the SIP plugin, which is the one that fails to load for you due to that undefined symbol... so in case the problem would still be there. @joshdickson40 do you get the same problem when enabling the SIP plugin itself? AFAIK it works for us on Ubuntu 16.04.

**Comment by alexamirante** [comment]
I just compiled Janus in a fresh Ubuntu 16.04.1 (kernel 4.2.0-34), with the SIP plugin enabled, and it runs fine.
It's within a docker container, but it should make no difference.

**Comment by thelasthope4U** [comment]
to follow up on @alexamirante, I did a few more tests.  Going back to the original installation that manifested the problem here.  I noticed that I was using libsrtp 1.5.4 and josh's instructions installed 2.0 so I uninstalled 1.5.4 and installed 2.0 libsrtp.  compiled again with same error.  I also compiled with --disable-plugin-sip and the problem still persisted.  I don't know if I should have expected it to go away when disable sip plugin is specified.  If so then we are on the wrong path.

Anyway, leaving this behind I returned to the new unbuntu install, did a make clean of janus, and rebuilt without --disable-plugin-sip (I always confirm output of configure to see that plugin is on or off) and janus did start okay and was operational.

I am willing to continue testing if you feel it will help solve the problem.  I am not an expert in linux so I am limited in some of this but very willing to do any tests.  For now I may be the only user to have this issue.

**Comment by lminiero** [comment]
> I also compiled with --disable-plugin-sip and the problem still persisted

Have you removed the shared object from the previous installation?

**Comment by thelasthope4U** [comment]
Not sure how to do that,  which object are you refering too?  
 I did completey remove the /opt/janus/ directory during one of the tests, if it is not there and is part of the build environment then I would expect clean to do that.

are you referring to the libsrtp component?  it is compiled as a shared library.

I was wondering why it was trying to do anything with sip if it was off.  

thanks for being patient with me, I have limited experience with linux so I am still getting to know my way around

**Comment by lminiero** [comment]
Is this still an issue with master?

**Comment by thelasthope4U** [comment]
At this time, no.  I was unable to resolve in place, so I created a new
install of OS and repeated build process.  It did work on the new install.
I did save the old OS install (virtual machine)  if you would like me to
look at anything additional.

If there are no other reports of issue, I would suggest closing.

Thanks for checking,

Thomas
On Jun 30, 2017 7:15 AM, "Lorenzo Miniero" <notifications@github.com> wrote:

Is this still an issue with master?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/meetecho/janus-gateway/issues/891#issuecomment-312241684>,
or mute the thread

**Comment by lminiero** [comment]
Thx for the update, closing then!

**Comment by PedroRTomas** [comment]
Hi, today I'm facing a similar error:
/opt/janus/bin/janus: symbol lookup error: /opt/janus/bin/janus: undefined symbol: srtp_crypto_policy_set_aes_gcm_128_16_auth

I'm running "Ubuntu Subsystem for Windows", Ubuntu 18.04.4 LTS

I've followed the instructions availables at: https://ourcodeworld.com/articles/read/1197/how-to-install-janus-gateway-in-ubuntu-server-18-04
And also installed other programs needed for compilation of some packages such as: meosn, ninja, ... (Don't think these are the problem)

Any thoughts?
Thanks in advance!
