### ISSUE TITLE
Mac OS Install Instructions Broken (libnice)

### ISSUE THREAD

**Issue by joshdickson40** [meetecho/janus-gateway#897]
Homebrew recently (last month) removed support for installing formulae via the boneyard (see https://github.com/Homebrew/homebrew-boneyard/pull/314).

This was required in order to install libnice on OS X.

I haven't been able to get libnice to build without error from source and instructions I've found so far are quite out of date. Maybe someone else has an answer here so we can submit a PR to get this remedied.

**Comment by lminiero** [comment]
Any solution for this? I never owned a Mac and never will, so no idea on how to fix the instructions myself.

**Comment by RouquinBlanc** [comment]
Hi guys,

Sorry for the late reply. Here is how I compile on my mac:
```
git clone https://github.com/warmcat/libwebsockets
cd libwebsockets
mkdir build
cd build
PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig cmake ..
make
```
My openssl was installed with brew.

**Comment by soulfly** [comment]
In my case  (macOS High Sierra) I was needed the following things to do:

1. brew install ffmpeg
2. brew install libogg
3. Add **PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig** when do **./configure**

**Comment by lminiero** [comment]
Closing as this should have been fixed in a recent commit.
