### ISSUE TITLE
Bitrate in REMB is not realtime in video room plugin

### ISSUE THREAD

**Issue by ridgeback1982** [meetecho/janus-gateway#899]
According to the mechanism of remote peer's REMB, it should be calculated in realtime, not a static value. But here in "janus_videoroom.c" the bitrate in REMB is always the same as the initial value. 
    Beyond that, for better work of REMB, there should be a overuse detector as in the WebRTC source code. But it is absent.

**Comment by lminiero** [comment]
We don't do bandwidth estimation. We only use REMB as a way to cap the bitrate to what the application wants: see how the VideoRoom uses it, for instance, in a way that can be done dynamically, so leaving a more reactive approach to the application itself. Closing as not an issue.

**Comment by ridgeback1982** [comment]
I don't agree with that, you cannot depend on the application's reaction with REMB. REMB indicates what the remote side think the uplink network looks like, that is the protocol of how to use REMB. If the REMB is always the same as set, the sender will think his uplink network bandwidth is always good. In a word, REMB make sense when the remote side can calc and set its value.

**Comment by lminiero** [comment]
Whether you agree with that or not, that's the way the system was built, and it works for us...

As I've said, REMB is not always the same in Janus. Or actually, it is if you just leave that as it is: you can change the value you send back via dynamic requests in most plugins, e.g., in the VideoRoom. Using feedback you get from Janus (e.g., slowlink events) you can react by changing that value (e.g., reducing it if you notice losses on a publisher) or doing other things (switching, dropping streams, etc.). That allows you to control the behaviour of REMB programmatically.

**Comment by ridgeback1982** [comment]
I have talked with my friends who is working on WebRTC+Janus like I do. I see that, there is demand on the server side to do bandwidth estimation. I know it is not easy to migrate the related code from WebRTC to Janus.

**Comment by lminiero** [comment]
Unfortunately we have other priorities and we don't plan on working on bandwidth estimation anytime soon. But of course pull requests are always welcome!
