### ISSUE TITLE
ICE Failed

### ISSUE THREAD

**Issue by shamil614** [meetecho/janus-gateway#90]
I'm having some problems with the echo test.  The server is deployed to a public IP on DigitalOcean, and the ssl cert is installed and configured.  Yesterday at work all seemed to work fine but after I got home either I changed a config or there's a networking situation that I don't understand.  The local video renders but the remote video fails.  

Here's what Janus logs:

```
Creating new session: 1423452863
Creating new handle in session 1423452863: 418682067
[418682067] There's a message for JANUS EchoTest plugin
[418682067] There's a message for JANUS EchoTest plugin
[418682067] Creating ICE agent (controlled mode)
[418682067] ICE send thread started...
[418682067] Done! Ready to setup remote candidates and send connectivity checks...
ICE started and trickling, sending connectivity checks for candidates retrieved so far...
[WARN] [418682067]    Unsupported transport tcp!
No more remote candidates for handle 418682067!
[ERR] [ice.c:janus_ice_cb_component_state_changed:634:] ICE failed for handle 418682067...
No WebRTC media anymore
[418682067] ICE send thread leaving...
```

Below are some screenshots
![screen shot 2014-11-14 at 6 33 02 am](https://cloud.githubusercontent.com/assets/729514/5045824/689ff27c-6bc8-11e4-9c25-bea61e09fa78.png)
![screen shot 2014-11-14 at 6 33 10 am](https://cloud.githubusercontent.com/assets/729514/5045825/68a2c114-6bc8-11e4-9e0c-3ef4653efb46.png)
![screen shot 2014-11-14 at 6 33 37 am](https://cloud.githubusercontent.com/assets/729514/5045826/68af1b30-6bc8-11e4-945e-455702e1894b.png)

**Comment by CaptainMcCrank** [comment]
What was the solution here?

I ran into this over the weekend and I absolutely could not resolve it.  I tried setting STUN & ICE Servers, but consistently ran into ICE Failed messages.

**Comment by nswarnkar** [comment]
looks, solution is never found for it on this forum. We are facing the exact problem but with alpine docker.
With ubuntu docker, we have no such issues. If any of need it, I will provide dockerfile and dependent stuff.

We are doing it on AWS, so ensure aws firewall rules are fine.

Above issue, has nothing to do with firewall, instead looks like either some build environment issue or something else.

**Comment by dejanp777** [comment]
Hello nswarnkar, 
Please provide dockerfile and dependent stuff for me too.
Thanks!

**Comment by nswarnkar** [comment]
Hi,
I made it available at :

https://github.com/nswarnkar/janus_docker

Hope you find no issues :)

**Comment by thirupathireddy999** [comment]
Hi Team I am Thiru
please  let me know what is the reason it failed , where we can fix this one .


Dec 07 07:00:27 ip-172-31-18-114 sudo[55457]: [WSS-0x7f377c0097a0] Destroying WebSocket client
Dec 07 07:00:27 ip-172-31-18-114 sudo[55457]: Destroying session 2903022895602233; 0x7f3788006880
Dec 07 07:00:27 ip-172-31-18-114 sudo[55457]: Detaching handle from JANUS VideoRoom plugin; 0x7f3788006950 0x7f3788007f90 0x7f3788006950 0x7f3788006>
Dec 07 07:00:27 ip-172-31-18-114 sudo[55457]: [8692756865077481] Handle and related resources freed; 0x7f3788006950 0x7f3788006880
Dec 07 07:05:42 ip-172-31-18-114 sudo[55457]: [WSS-0x7f377c00ae90] Destroying WebSocket client
Dec 07 07:05:42 ip-172-31-18-114 sudo[55457]: Destroying session 1907904165100295; 0x7f3788006ac0
Dec 07 07:05:42 ip-172-31-18-114 sudo[55457]: Detaching handle from JANUS VideoRoom plugin; 0x7f37880022d0 0x7f37880068e0 0x7f37880022d0 0x7f3788003>
Dec 07 07:05:42 ip-172-31-18-114 sudo[55457]: [janus.plugin.videoroom-0x7f37880068e0] No WebRTC media anymore; 0x7f37880022d0 0x7f37880034a0
Dec 07 07:05:42 ip-172-31-18-114 sudo[55457]: [65804917152261] Handle and related resources freed; 0x7f37880022d0 0x7f3788006ac0
Dec 07 07:26:09 ip-172-31-18-114 sudo[55457]: [ERR] [transports/janus_http.c:janus_http_handler:1436] Invalid url /ws/v1/cluster/apps/new-application
