### ISSUE TITLE
Bit rate Codec

### ISSUE THREAD

**Issue by clandolfa** [meetecho/janus-gateway#902]
Hi everybody,
we are trying to configure the rtp codec between the user and janus gateway , but we are not able to have the expected results.

We try to setup PCMA/PCMU, but the rate between the user and gateway is 192 Kbit/s. The rate we expect is around 80/90 Kbit/s.
We try to change the janus.plugin.streaming.cfg

[gstreamer-sample]
type = rtp
id = 1
description = Opus/VP8 live stream coming from gstreamer
audio = yes
video = yes
audioport = 5002
audiopt = 111
;audiortpmap = opus/48000/2
audiortpmap = pcmu/8000/1
videoport = 5004
videopt = 100
videortpmap = VP8/90000
secret = adminpwd

we set up a new value for audiortpmap using pcmu/8000/1, but it doesn't change anything.

Can you help us to understand which is the wrong settings?

**Comment by lminiero** [comment]
Closing as not a code issue. As explained on the guidelines, please ask questions like these on the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
