### ISSUE TITLE
Multiple TURN servers - the first one is always chosen.

### ISSUE THREAD

**Issue by petergerten** [meetecho/janus-gateway#909]
I have configured multiple TURN servers that correctly show up in the SDP as relay candidates but it seems that always the first (working) one in the list is chosen. I assumed ICE would give me the "best" one - based on ping-time or similar? Am I mistaken here or is something going wrong?

**Comment by petergerten** [comment]
After reviewing https://tools.ietf.org/html/rfc5245#section-4.1.2 it seems that this is actually not required. I wonder how people deal with multiple TURN servers to keep latency down in a global deployment.

**Comment by lminiero** [comment]
Closing as not a code issue, which is what we use GitHub for. Please refer to the group for questions like these, especially considering they refer to the client side (that's where you configure TURN servers).
