### ISSUE TITLE
Could it be possible to have another bower package for only janus.js ?

### ISSUE THREAD

**Issue by ArfyFR** [meetecho/janus-gateway#914]
In order to not download ALL sources ... for web clients' code using only janus.js

**Comment by lminiero** [comment]
The bower file was contributed, and we're not experts on that. If you can provide an updated version in a PR we'll definitely consider integrating that!

**Comment by ArfyFR** [comment]
Hmm, I am also "just" a bower user... I'll try to have a look, but not this week.

**Comment by lminiero** [comment]
Did #917 made the change you needed?

**Comment by ArfyFR** [comment]
Hi, not yet, for the moment it stays at version 0.2.2
```
bower janus-gateway#*           cached https://github.com/meetecho/janus-gateway.git#0.2.2
bower janus-gateway#*         validate 0.2.2 against https://github.com/meetecho/janus-gateway.git#*
...
bower janus-gateway#*                                      install janus-gateway#0.2.2
```
I'll retry later as your commit is only 2 hours old

**Comment by lminiero** [comment]
You're not using the latest version, then. That PR definitely sets the version to 0.2.3, https://github.com/meetecho/janus-gateway/pull/917/files
If it's trying to get a tagged version it will fail, though, as there's no 0.2.3 tag yet (0.2.3 is master).

**Comment by ArfyFR** [comment]
Perhaps missing the tag because in my bowser.json I have
    "janus-gateway" : "latest"
and it still is looking for the 0.2.2

**Comment by lminiero** [comment]
https://github.com/meetecho/janus-gateway/blob/master/bower.json

**Comment by lminiero** [comment]
Yeah, if it looks for the tag instead of getting master when the tag doesn't exist that's what may be happening. Never used bower so can't help, sorry, maybe @ancorgs (who contributed the fix) might know more.

**Comment by ancorgs** [comment]
We point directly to the janus repo, like this. https://github.com/jangouts/jangouts/blob/master/bower.json#L15 In that way we are always in full control of the exact revision we get.

I don't think my recent change will improve the situation. It only uses janus.js in the "final mix", but it still tries to download a lot of extra stuff during `bower install`, I would say.

Looks like nobody is expert in Bower here. :wink:

**Comment by lminiero** [comment]
Tagged 0.2.3 recently, which should make it less problematic. Closing as not planned.
