### ISSUE TITLE
[Jessie] Package Libsrtp installed but not found at ./configure

### ISSUE THREAD

**Issue by Sorikairo** [meetecho/janus-gateway#916]
I installed the latest Libsrtp0-dev package, which is the only package available for Libsrtp on Jessie official repositories.
However, when executing the ./configure command, I got this

```
checking for srtp_init in -lsrtp2... no
checking for srtp_init in -lsrtp... yes
checking srtp/srtp.h usability... yes
checking srtp/srtp.h presence... yes
checking for srtp/srtp.h... yes
checking for SRTP15X... no
configure: error: Package requirements (
                                                                 libsrtp >= 1.5.0
                                                               ) were not met:

No package 'libsrtp' found
```

**Comment by lminiero** [comment]
Very likely it's libsrtp 1.4.5 which we don't use, as it's known to give issues. Use a more recent version, installing it manually if the repo doens't provide it.
