### ISSUE TITLE
Double video inside SDP сauses 486 BUSY

### ISSUE THREAD

**Issue by netaskd** [meetecho/janus-gateway#921]
Hello,
I use janus as webrtc-sip gateway with sylk-webrtc. 
I've issue with double video inside SDP. Janus detect it, said that it will be ignored (line 152 from log), but anyway sent 486 BUSY.
Log from janus backend on https://pastebin.com/CKqmjK3U
in chrome console on sylkserver js client I see error:
```
blinkrtc:App Transition from /ready to /call +96ms
sylkrtc:Call Error setting remote description: DOMException: Failed to parse SessionDescription.  Failed to AddTransportInfo with content name: video +416ms
sylkrtc:Call Terminating call +10ms
```
Janus 0.2.3, commit: 627db8e60621db79e2740c4fb9470b4272095943

**Comment by lminiero** [comment]
We don't support multiple streams of the same kind yet.

**Comment by lminiero** [comment]
PS: you're getting the error back because of the `media=application` line, I think, although I thought we fixed that.

**Comment by lminiero** [comment]
Nope, that's not the cause, looks like you're declining yourself?

`{"body": {"code": 486, "request": "decline"}, "janus": "message", "transaction": "a420293adaa842be832aadb7661308b0", "handle_id": 2570745749746199, "apisecret": "0745f2f74f34451c89343afcdcae5809", "session_id": 6316618051453735}`
