### ISSUE TITLE
There is echo when we do audio conference 

### ISSUE THREAD

**Issue by varunrevcord** [meetecho/janus-gateway#922]
Hi ,

When we install the Janus server and we do join the audio conference room then there is rebound of sound what we say from the headphone mic to the headphone speaker. 

Steps to reproduce:
1) User ABC Join a audio conference room and the other user XYZ joins the audio conference room.
2) User XYZ mutes his MIC and make his speaker volumes zero.
3) Now what user ABC speaks into the MIC it comes back to him to speakers.
4) We are using the web to join the audio conference and I think webrtc echo cancellation is not wroking.

Thanks 
Varun

**Comment by lminiero** [comment]
Not a code issue, so please use the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for questions like this.
