### ISSUE TITLE
Avoid requesting  IPv6  from libhttpd when not needed. 

### ISSUE THREAD

**Issue by sdrsdr** [meetecho/janus-gateway#923]
In janus_http.c  at the moment there are code paths that call MHD_start_daemon with MHD_USE_DUAL_STACK option that  mandates  MHD_USE_IPv6 but if the system is not ipv6 capable the http transport fails to create any sockets and gets disabled.  However there are code paths that select MHD_USE_IPv6 based on ipv6 variable that seems quite sane. Can we please extend this to all calls to MHD_start_daemon? Is it OK for me to create a pull request on this?

**Comment by lminiero** [comment]
`MHD_USE_IPv6` does IPv6 only, so is not a good option in general. Where you see it used, is in code paths where the user requested binding to a specific interface or IP address, and so in that case if either is IPv6 only then it makes sense to use it.

On a more general note, we should only do `MHD_USE_DUAL_STACK` if IPv6 was enabled when Janus was started (via command line or config). I don't think we're passing that info to transports, though (the setting is more oriented to IPv6 support for ICE), or if we do expose that info via API. In case, that's what a change or PR should address.

**Comment by sdrsdr** [comment]
I my  microhttpd.h I have `MHD_USE_DUAL_STACK = MHD_USE_IPv6 | 2048,` and having MHD_USE_IPv6 in flags causes libmicrohttpd to try to create socket of family AF_INET6 and this fails on my non ipv6 enabled system. Using this simple check I'm able to start janus with example configurations  on both ipv6 and  non ipv6 enabled machines.
