### ISSUE TITLE
JavaScript API realys on polyfill for Janus.isWebrtcSupported  (and this is not mentioned)

### ISSUE THREAD

**Issue by sdrsdr** [meetecho/janus-gateway#926]
`navigator.getUserMedia` is  depricated and removed in recent Firefox. I think it did not make it to Firefox at all except as moz prefixed experimental feature that is also to be removed. Anyway according to https://developer.mozilla.org/en/docs/Web/API/Navigator/getUserMedia the newer code should use `navigator.mediaDevices` and so the proper `Janus.isWebrtcSupported` should be 
```
Janus.isWebrtcSupported = function() {
	return window.RTCPeerConnection !== undefined && window.RTCPeerConnection !== null &&
		((navigator.getUserMedia !== undefined && navigator.getUserMedia !== null) 
                || (typeof navigator.mediaDevices==='object'));
};

**Comment by lminiero** [comment]
We make use of `webrtc-adapter.js`, so as long as it's defined there, it should work for us.

**Comment by sdrsdr** [comment]
Uh .. I guess you should mention it somewhere? The code as a hole is struggling with this deprecation on some places so I thought  the polyfill is not needed per se

**Comment by lminiero** [comment]
It's been like that for three years :wink: 
Up to a couple months ago, we even loaded the adapter programmatically in janus.js itself, something we changed when we externalized all dependencies (so now it's the web page responsibility to make sure the adapter is there).

**Comment by sdrsdr** [comment]
No problem with that but can we mention all the dependencies at https://janus.conf.meetecho.com/docs/JS.html  :) All I can see is an optional dep on jquery .. and that did not work well ..

**Comment by lminiero** [comment]
Ack, we'll make it more explicit. The optional dependency on jquery means you can use janus.nojquery.js.

**Comment by lminiero** [comment]
Made more explicit in the docs: https://janus.conf.meetecho.com/docs/JS
