### ISSUE TITLE
Help Janus Https

### ISSUE THREAD

**Issue by jersonjunior** [meetecho/janus-gateway#931]
I'm trying to set up janus days with https but with no success. Any help is welcome, follow below my settings:

**janus.transport.http.conf**

[general]
json = indented                       
                                                       
base_path = /janus                      
threads = unlimited                     
http = yes                                      
port = 8088                                   
interface = eth0                       
;ip = 192.168.0.1                      
https = yes                                    
secure_port = 8089                      
secure_interface = eth0 
;secure_ip = 192.168.0.1        
;acl = 127.,192.168.0.

**Apache:**

<VirtualHost *:443>
;       ProxyPreserveHost On
        ServerName volts.eng.br
        ServerAlias www.volts.eng.br
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html/mydsomain.com.br/public_html
        ErrorLog /var/www/html/mydsomain.com.br/logs/error.log
        CustomLog /var/www/html/mydsomain.com.br/logs/access.log combined
        SSLEngine on
        SSLVerifyClient none
        SSLCertificateFile /etc/apache2/ssl/certificate.crt
        SSLCertificateKeyFile /etc/apache2/ssl/private.key
;        ProxyRequests Off
;        ProxyVia Off
;        ProxyPass /janus  http://127.0.0.1:8088/janus retry=0
;        ProxyPassReverse /janus  http://127.0.0.1:8088/janus
</VirtualHost>

**Browser error:**

error: Is the gateway down?

**Browser Console:**

Initializing library
janus.js:211 Library initialized: true
janus.js:238 Using REST API to contact Janus: https://www.volts.eng.br:8089/janus
jquery.min.js:4 OPTIONS https://www.volts.eng.br:8089/janus net::ERR_INSECURE_RESPONSE
send @ jquery.min.js:4
ajax @ jquery.min.js:4
createSession @ janus.js:594
Janus @ janus.js:278
(anonymous) @ siptest.js:80
dispatch @ jquery.min.js:3
i @ jquery.min.js:3
janus.js:618 error: 
error @ janus.js:618
o @ jquery.min.js:2
fireWith @ jquery.min.js:2
w @ jquery.min.js:4
d @ jquery.min.js:4
siptest.js:401 error: Is the gateway down?

**Comment by lminiero** [comment]
1. not a code issue, so please post on the group;
2. please DON'T paste all this stuff inline, use gist/pastebin (as explained in the guidelines).
