### ISSUE TITLE
Janus https

### ISSUE THREAD

**Issue by jersonjunior** [meetecho/janus-gateway#932]
I'm trying to set up janus days with https but with no success. Any help is welcome, follow below my settings:

https://pastebin.com/W49yKD6d

**Comment by lminiero** [comment]
Have you read only point 2? :stuck_out_tongue_winking_eye: 
Not a code issue --> https://groups.google.com/forum/#!forum/meetecho-janus

**Comment by jersonjunior** [comment]
Ok!
