### ISSUE TITLE
Please add a list of possible web frontends to your documentation

### ISSUE THREAD

**Issue by josch** [meetecho/janus-gateway#941]
Users of janus will at some point want to go beyond the provided demos.

It would be great if janus documentation would carry a list with such projects for new users of janus.

After some search I found https://github.com/jangouts/jangouts but I bet there are others out there - they are just hard to find.

**Comment by lminiero** [comment]
We already have something like this here: https://janus.conf.meetecho.com/docs/resources
Apart from this, I often share a non-exhaustive list of projects using Janus in my slides: https://www.slideshare.net/LorenzoMiniero

Not sure we need more. Closing as not an issue, please discuss on the group instead.

**Comment by josch** [comment]
I find no other frontends like jangouts provides one in the "resources" list. Am I missing something?

Which slides do you recommend me I read?

**Comment by lminiero** [comment]
The more generic ones, I guess, as a couple focus on more specific scenarios (IETF or SIP).

Not sure you'll find many custom frontends to Janus, though. Most of what you'll find are wrappers, or hooks to control Janus from different languages and frameworks. Stuff like web frontends are very much specific to the application. Again, please refer to the Google group for questions like this, if any user knows something that's where they'll chime in.
