### ISSUE TITLE
SIP Gateway - audio port number is zero

### ISSUE THREAD

**Issue by edantie** [meetecho/janus-gateway#946]
I'm trying the demo - SIP gateway

Everything look working well, but after registering correctly to an asterisk server, then a call is done to the new registered extension.

When answering the call (audio only), the SIP response is missing the port of the rtp audio in SDP.

<--- SIP read from UDP:172.16.67.219:60360 --->
SIP/2.0 200 OK
Via: SIP/2.0/UDP 172.16.0.5:5060;branch=z9hG4bK0ed3b1e5
From: <sip:200@172.16.0.5>;tag=as193f3c1c
To: <sip:edantie@172.16.67.219:60360>;tag=HUXr93jy2yZBK
Call-ID: 7801705a21f02feb47ac40112ba1939d@172.16.0.5:5060
CSeq: 102 INVITE
Contact: Eric <sip:edantie@172.16.67.219:60360>
User-Agent: Janus WebRTC Gateway SIP Plugin 0.0.6
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, UPDATE, MESSAGE, INFO
Content-Type: application/sdp
Content-Disposition: session
Content-Length: 167

v=0
o=mozilla...THIS_IS_SDPARTA-55.0 8250385083505305020 6783358317153188258 IN IP4 172.16.67.219
s=-
c=IN IP4 172.16.67.219
t=0 0
m=audio 0 UDP/TLS/RTP/SAVP 19
<------------->
--- (12 headers 6 lines) ---
[Jul  6 07:18:14] WARNING[12245][C-0000005a]: chan_sip.c:10025 process_sdp: Ignoring audio media offer because port number is zero
[Jul  6 07:18:14] WARNING[12245][C-0000005a]: chan_sip.c:10455 process_sdp: Failing due to no acceptable offer found

janus log at https://pastebin.com/LkExGQu0

**Comment by lminiero** [comment]
The log you posted shows a successful call.

As to the inline dump, that apparently is the port Firefox gave Janus, not a port set to 0 Janus set, which Janus simply receives (`Ignoring audio media offer because port number is zero`). You should check why Firefox is rejecting the media.

Closing as not a Janus issue.
