### ISSUE TITLE
libnice-socket:ERROR:udp-bsd.c:294:socket_send_messages: assertion failed: (sock->priv != NULL)

### ISSUE THREAD

**Issue by jackmjones25** [meetecho/janus-gateway#947]
Twice a day, my janus gw crashes.

On the janus.log I get this:
**
libnice-socket:ERROR:udp-bsd.c:294:socket_send_messages: assertion failed: (sock->priv != NULL)

BT:
https://pastebin.com/rHn2zDd6

fedora 25 server
libnice-0.1.13-7.fc25.x86_64
Using as webrtc-to-sip

**Comment by lminiero** [comment]
I have the same exact setup for my development environment and I never got that crash... Looks like a libnice issue, though, as it's doing a `sock->is_reliable` on a NULL `sock` variable (`0x00). Have you written the client part yourself, or is it basically a clone of the siptest demo page?

**Comment by jackmjones25** [comment]
It's based on the demo page of a few months ago... Should I take a look and rebuild it now?

about the server: What linux distro / libnice version do you recommend? Is there any ifnull/debug print I could try on the server regarding this?

**Comment by lminiero** [comment]
Updating the demo codebase might help, and so would using an up-to-date Janus as well of course.

As to the distro/libnice, your combo should be fine, as it's what I use for development daily on my laptop. Anyway, I think all our production servers are on Unbuntu and use libnice 0.1.13, and most companies I know use something similar. You may want to ask this question on the Google Group to have a feeling of what people use for their own needs.

**Comment by jackmjones25** [comment]
Thanks, mate. My janus gw is almost up-to-date (few weeks ago), but the client might have some differences (probably regarding the early media part - well done, btw!).

So, I'm updating everything today (client/server) to see if it stops. I'll let you know.

Forgot to tell you, the crash happens on peak times (as most crashes are).

**Comment by lminiero** [comment]
How many concurrent calls are peak time, in your case? Did you notice any CPU or mem spikes?

**Comment by jackmjones25** [comment]
No spikes on cpu/memory. Cpu usage on peak reaches 25% on this server (new relic metric) - it's not a big machine. 30~40 concurrent calls, and something like ~150 users.

**Comment by jackmjones25** [comment]
Seems it doesn't happen anymore.
What I did:
- updated server
- updated client
- split the load between 2 servers

**Comment by lminiero** [comment]
Thanks for the update!
