### ISSUE TITLE
Attachmediastream bug on smartphones

### ISSUE THREAD

**Issue by DaGLiMiOuX** [meetecho/janus-gateway#948]
I've recently found a bug on Janus.js and corrected it, but would be nice to append it to prevent overwritting it on the future.

**Case**
I'm working with a full width and full height video tag which has a videoroom remote stream attached to it. Also, for the other publishers, there are little windows with a small video tag and its corresponding remote stream attached to each one. Those windows are able to be clicked and if you do that, its corresponding stream is attached to the main/full width full height video tag.

The problem happens when working in a smartphone. You are able to change the `srcObject` in desktop and the main video tag stream changes, but for some reason it doesn't work at all in smartphones. The `srcObject` is changed, but video tag is stopped and does not play.

**Solution**
After searching a while to find the cause, I've found that if I hide and show the main video tag, the tag is refreshed and the stream is playing again, then I noticed that tag must be refreshed.

Changing these 2 functions:

```
Janus.attachMediaStream = function(element, stream) {
    if(adapter.browserDetails.browser === 'chrome') {
        var chromever = adapter.browserDetails.version;
        if(chromever >= 43) {
            element.srcObject = stream;
        } else if(typeof element.src !== 'undefined') {
            element.src = URL.createObjectURL(stream);
        } else {
            Janus.error("Error attaching stream to element");
        }
    } else {
        element.srcObject = stream;
    }
};
Janus.reattachMediaStream = function(to, from) {
    if(adapter.browserDetails.browser === 'chrome') {
        var chromever = adapter.browserDetails.version;
        if(chromever >= 43) {
            to.srcObject = from.srcObject;
        } else if(typeof to.src !== 'undefined') {
            to.src = from.src;
        } else {
            Janus.error("Error reattaching stream to element");
        }
    } else {
        to.srcObject = from.srcObject;
    }
};
```
With this 2 functions:

```
Janus.attachMediaStream = function(element, stream) {
    element.stop();
    if(adapter.browserDetails.browser === 'chrome') {
        var chromever = adapter.browserDetails.version;
        if(chromever >= 43) {
            element.srcObject = stream;
        } else if(typeof element.src !== 'undefined') {
            element.src = URL.createObjectURL(stream);
        } else {
            Janus.error("Error attaching stream to element");
        }
    } else {
        element.srcObject = stream;
    }
    element.load();
    element.play();
};
Janus.reattachMediaStream = function(to, from) {
    to.stop();
    if(adapter.browserDetails.browser === 'chrome') {
        var chromever = adapter.browserDetails.version;
        if(chromever >= 43) {
            to.srcObject = from.srcObject;
        } else if(typeof to.src !== 'undefined') {
            to.src = from.src;
        } else {
            Janus.error("Error reattaching stream to element");
        }
    } else {
        to.srcObject = from.srcObject;
    }
    to.load();
    to.play();
};
```
Makes it possible to change the stream src, refresh the video tag in smartphones and keep playing the stream.

Hope this helps and you can add it soon in a newer version.

Best regards,
Diego.

**Comment by lminiero** [comment]
Those are just helper functions, which we only left there as a convenience, since they're part of the rendering process which isn't really a `janus.js` responsibility, but something that should be part of the application. I'm a bit hesitant to add that, as I don't know what impact it might have on browsers for which it works just fine now (not only in terms of whether it works, but also if stopping/loading/playing introduces rendering delays, for instance). If you can figure out ways to match the devices for which this fixes it for you, we might make those new operation conditional on that.

**Comment by lminiero** [comment]
Considering your fix only adds a `stop` before the methods implementation, and a `load+play` at the end, this is something you can add in the application itself:

```
element.stop();
Janus.attachMediaStream(...);
element.load();
element.play();
```

with no need to modify the library itself. Closing: we can reopen in case we get more feedback on this being indeed a widespread problem (which doesn't seem to be the case).
