### ISSUE TITLE
Patch: Add libressl support

### ISSUE THREAD

**Issue by aduskett** [meetecho/janus-gateway#952]
Hello;

First off, thank you for creating and maintaining such a wonderful project! It really has been a life saver.
Second: I recently migrated from OpenSSL to LibreSSL, which is a fork of OpenSSL and API compatible with the OpenSSL 1.0.x.

As such, Janus works with it just fine, but it needs a small patch because LibreSSL's version number returns 2.x (current version is 2.5.5 as of two days ago.)

I made a patch for Janus as it sits right now.  Hopefully, you can add this into mainline.

Thanks!
Adam
[fix-compiling-against-libressl.txt](https://github.com/meetecho/janus-gateway/files/1148173/fix-compiling-against-libressl.txt)

**Comment by lminiero** [comment]
Hi Adam, thanks for the heads up. Can you prepare a pull request for this patch? I'm currently in Prague for IETF, and I won't have much time to work on any code myself until I get back. Thanks!

**Comment by aduskett** [comment]
Sure, can! I am surprised at how fast you got back to me!

Another thought before I do a pull request:

I noticed that you have an output during config for BoringSSL as well.  Would you want an output for libressl?

**Comment by lminiero** [comment]
We have an explicit indicator in configure for BoringSSL because you have to tell explicitly if you want to use it, via `--enable-boringssl`, as we expect it to be installed in `/opt/boringssl` and need to know that's what we'll need to look for. If there's an easy way in `configure.ac` to detect whether the OpenSSL we detected is actually LibreSSL, then that would indeed be helpful to print too in the end summary.

**Comment by lminiero** [comment]
Otherwise, even just printing it out in `janus_dtls_srtp_init` (where we have a similar distinction) would help.

**Comment by lminiero** [comment]
Just added the `configure.ac` check I mentioned in #954 and pushed the commit: https://github.com/meetecho/janus-gateway/commit/19de78a6b6bad220b79802db31e5b9a22e4f4b30
@aduskett can you confirm the check works for your LibreSSL usage of Janus? When doing a configure it should give you something like this in the end summary:

```SSL/crypto library:        LibreSSL
DTLS set-timeout:          not available
```
