### ISSUE TITLE
le

### ISSUE THREAD

**Issue by tylerjbrooks** [meetecho/janus-gateway#956]
> If you want to open an issue, please make sure that:
> 
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available[here](http://janus.conf.meetecho.com/docs/debug.html)).
> 
> If so, just remove this text and share your findings!

**Comment by lminiero** [comment]
Closing as I guess this was a mistake (I still see the placeholder text).
