### ISSUE TITLE
Issue on outbound sip call

### ISSUE THREAD

**Issue by mobilipia** [meetecho/janus-gateway#96]
Firstly this is a very great project. It beats all the other webrtc sip product with simplicity and functionality. Its simple enough to get the work done properly without additional overhead.
This seems to always happen anytime i try to make an outbound call. Inbound calls are fine and work great. I am using this on ubuntu 14.04. I tried to build for both 32 and 64 bit and the problem persists. Below is the log:

/opt/janus/bin/janus --config=/opt/janus/etc/janus/janus.cfg
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Gateway) v0.0.6
---------------------------------------------------

Reading configuration from /opt/janus/etc/janus/janus.cfg
Checking command line arguments...
Debug/log level is 4
Adding 'vmnet' to the ICE ignore list...
Using myipaddress as local IP...
Initializing ICE stuff (IPv6 candidates disabled)
Fingerprint of our certificate: C5:5F:DA:7D:84:47:B1:BF:6B:55:16:62:48:31:3E:D3:F1:7B:25:89:92:4A:4B:4D:4D:D9:D5:AF:EA:D8:15:44
Plugins folder: /usr/lib64/janus/plugins
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin initialized!
Loading plugin 'libjanus_audiobridge.so'...
JANUS AudioBridge plugin initialized!
Loading plugin 'libjanus_sip.so'...
JANUS SIP plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_streaming.so'...
VideoCall watchdog started
Echotest watchdog started
AudioBridge watchdog started
SIP watchdog started
VoiceMail watchdog started
JANUS Streaming plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
JANUS VideoRoom plugin initialized!
Loading plugin 'libjanus_recordplay.so'...
JANUS Record&Play plugin initialized!
HTTP webserver started (port 8088, /janus path listener)...
Streaming watchdog started
VideoRoom watchdog started
Record&Play watchdog started
[WARN] HTTPS webserver disabled
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
[WARN] RammitMQ support disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
Sessions watchdog started
Creating new session: 3759052905
Creating new handle in session 3759052905: 1358004202
[1358004202] There's a message for JANUS SIP plugin
outbound(0x7f9020002940): FAILED to validate <sip:/opt/janus/bin/janus --config=/opt/janus/etc/janus/janus.cfg
---------------------------------------------------
  Starting Meetecho Janus (WebRTC Gateway) v0.0.6
---------------------------------------------------

Reading configuration from /opt/janus/etc/janus/janus.cfg
Checking command line arguments...
Debug/log level is 4
Adding 'vmnet' to the ICE ignore list...
Using myipaddress as local IP...
Initializing ICE stuff (IPv6 candidates disabled)
Fingerprint of our certificate: C5:5F:DA:7D:84:47:B1:BF:6B:55:16:62:48:31:3E:D3:F1:7B:25:89:92:4A:4B:4D:4D:D9:D5:AF:EA:D8:15:44
Plugins folder: /usr/lib64/janus/plugins
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin initialized!
Loading plugin 'libjanus_audiobridge.so'...
JANUS AudioBridge plugin initialized!
Loading plugin 'libjanus_sip.so'...
JANUS SIP plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_streaming.so'...
VideoCall watchdog started
Echotest watchdog started
AudioBridge watchdog started
SIP watchdog started
VoiceMail watchdog started
JANUS Streaming plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
JANUS VideoRoom plugin initialized!
Loading plugin 'libjanus_recordplay.so'...
JANUS Record&Play plugin initialized!
HTTP webserver started (port 8088, /janus path listener)...
Streaming watchdog started
VideoRoom watchdog started
Record&Play watchdog started
[WARN] HTTPS webserver disabled
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
[WARN] RammitMQ support disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
Sessions watchdog started
Creating new session: 3759052905
Creating new handle in session 3759052905: 1358004202
[1358004202] There's a message for JANUS SIP plugin
outbound(0x7f9020002940): FAILED to validate <sip:mysipaddress@myipaddress:43522;transport=udp>
outbound(0x7f9020002940): FAILED with 405 Use  sipproxyaddress
[1358004202] There's a message for JANUS SIP plugin
[1358004202] Creating ICE agent (controlled mode)
[1358004202] ICE send thread started...
[1358004202] WebRTC resources freed
No WebRTC media anymore

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed
Segmentation fault (core dumped)
;transport=udp>
outbound(0x7f9020002940): FAILED with 405 Use sipproxyaddress
[1358004202] There's a message for JANUS SIP plugin
[1358004202] Creating ICE agent (controlled mode)
[1358004202] ICE send thread started...
[1358004202] WebRTC resources freed
No WebRTC media anymore

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed

(process:11778): GLib-CRITICAL **: g_async_queue_try_pop: assertion 'queue' failed
Segmentation fault (core dumped)

**Comment by lminiero** [comment]
Closing for lack of feedback, as it may have been an issue fixed by #122
