### ISSUE TITLE
Segmentation fault (master)

### ISSUE THREAD

**Issue by tgabi333** [meetecho/janus-gateway#963]
Hi'

I've just compiled the master and found a segmentation fault, when try to reload the page (disconnect and connect again)

Interesting part of janus log: https://pastebin.com/M4k7gEtv

GDB stacktrace: https://pastebin.com/qNX6vMW6

**Comment by tgabi333** [comment]
seems working with tagged release v0.2.4

**Comment by lminiero** [comment]
My guess is that the reload triggers the session timeout, which is not getting rid of handles (we moved that part), hence your issue. Let me see if I can come up with a fix.

**Comment by lminiero** [comment]
Let me know if this fixes it for you, and in case please close.

**Comment by tgabi333** [comment]
Thank @lminiero , it worked, we tested with a tons of reloading, only once i got this:

```
[Wed Aug  2 13:29:34 2017] Detaching handle from JANUS VideoRoom plugin
[Wed Aug  2 13:29:34 2017] No WebRTC media anymore
[Wed Aug  2 13:29:34 2017] [ERR] [janus.c:janus_plugin_handle_sdp:2858] [6161757516454272] Error gathering candidates!
[Wed Aug  2 13:29:34 2017] [ERR] [janus.c:janus_plugin_push_event:2729] [6161757516454272] Cannot push event (handle not available anymore or negotiation stopped)
```

**Comment by lminiero** [comment]
That's a good sign, it means something was trying to push an event on a handle that was removed in the meanwhile, something that wouldn't have worked anyway. Closing then.
