### ISSUE TITLE
frequent server crash

### ISSUE THREAD

**Issue by jackmjones25** [meetecho/janus-gateway#965]
At least once a day. Usually on peak times.

built from master ~20 days ago
client based on the example, same date.
using as webrtc2sip
server fedora 24

gbd / bt full: 

https://pastebin.com/DK1dJwTW

**Comment by bizzr3** [comment]
i had the same issues, and did not have time to fix it. but a quick solution i applied on production is running multiple instances of janus, with same config but different port. 
ps. you don't need most of plugins, so i have around 150 instances with only sip plugin, and it works perfectly.
will wait for updates.

**Comment by lminiero** [comment]
Make sure you're at least on commit https://github.com/meetecho/janus-gateway/commit/aa880c14750722b1640e7c739b33c7dce078e297#diff-e26c229e0800bdaf6e4e995fba5d3c4d as I did remember making a fix on some some crashes. Even better, try master and let me know if you're still getting the same crashes: as you can guess, I'd rather not investigate again issues that I may have already solved.

**Comment by lminiero** [comment]
Any update? Have you checked master as I suggested?

**Comment by lminiero** [comment]
Closing as I believe it was likely fixed with the commit I mentioned (and I'm not getting other feedback from you). If still an issue, please open a new one with updated details.
