### ISSUE TITLE
How to play recorded-video on web

### ISSUE THREAD

**Issue by anhlt309** [meetecho/janus-gateway#966]
I have a nginx-rtmp server for streaming local video files and I can view on my android by app supports rtmp protocol. Now, I want to view those video files on web (by chrome or firefox...), so I found janus-webrtc-gateway. I had configured nginx.conf as you recommend, but I dont how to select and view those video file on web. Please help me, thank you.

**Comment by lminiero** [comment]
Closing as not an issue. Please refer to the [group](https://groups.google.com/forum/#!forum/meetecho-janus) for questions like this.
