### ISSUE TITLE
janus crash janus_session_notify_event (session=0x7f6804003170, event=0x7f6800001fd0) at janus.c:527

### ISSUE THREAD

**Issue by jackmjones25** [meetecho/janus-gateway#970]
Not sure if it's the same, so  I'm openning a new thread.

The server just crashes (now it's a few times a day).

https://pastebin.com/F2KW0mMD

**Comment by MichaelB76** [comment]
I'm also getting a few intermittent crashes recently which may be related. The first is also something to do with SIP handling:

[https://pastebin.com/QTZS3xp7](https://pastebin.com/iCKq6xv7)

And a couple in janus_http.c.

[https://pastebin.com/QTZS3xp7](https://pastebin.com/QTZS3xp7)

I'm wondering if memory corruption is a possible cause. I'm running Valgrind at the moment but haven't found anything yet.

**Comment by MichaelB76** [comment]
Using Helgrind, found a possible race condition in janus_http.c, which could be related to the second crash in my last update:

[https://pastebin.com/qFPwzn0X](https://pastebin.com/qFPwzn0X)

 This is with v0.2.4 of Janus, so the line numbers should be correct.

==49833== Possible data race during write of size 8 at 0x5AC9368 by thread #1531
==49833== Locks held: 1, at address 0x5AC9308
==49833==    at 0xF1A0D5C: janus_http_send_message (janus_http.c:1022)

...

==49833== This conflicts with a previous read of size 8 by thread #1533
==49833== Locks held: none
==49833==    at 0xF1A5188: janus_http_handler (janus_http.c:1461)

**Comment by lminiero** [comment]
Are you using this commit, or an older one? https://github.com/meetecho/janus-gateway/commit/aa880c14750722b1640e7c739b33c7dce078e297
I remember fixing a session timeout crash before leaving that looked dangerously similar to this one.

**Comment by MichaelB76** [comment]
@Iminiero - Hope you had a good holiday. I saw that commit but when I looked at the linked issue (#963) the first comment said it was not a problem with v0.2.4. Can you confirm this please? If it's a risk in the released version I can give it a try.

I'm also not sure at this point whether the two seg faults I posted above are related to each other or the @jackmjones25 problem, I may need to log them as separate issues.

**Comment by lminiero** [comment]
Still waiting to understand if you guys tried master.

**Comment by MichaelB76** [comment]
Hi, I haven't tried master yet, but as I said above I'm not clear if #963 is a problem with the v0.2.4 code I'm running. @tgabi333's comment says it isn't.

I ran Janus v0.2.4 under Address Sanitizer over the weekend with some automated dialling, but it didn't fall over. I'm not sure of the best way to proceed at this stage, I may go back to running it under a debugger after adding some additional logging/diagnostic code.

**Comment by lminiero** [comment]
I recently (both before and after the summer break) made a few fixes related to the way sessions/handles are removed and cleaned. Whether these issues were lingering in 0.2.4 or introduced as part of following changes I really don't know, sorry.

**Comment by MichaelB76** [comment]
Ok thanks. Sounds like updating to the latest code is the best way forward, I'll try and get this sorted out.

**Comment by lminiero** [comment]
Closing this issue as from the title (and the line 527 in particular) that's definitely an issue we fixed. If it's still crashing for you on master, please open a new issue with updated details.
