### ISSUE TITLE
RTSP stream - configure rtpmap and fmtp for client SDP

### ISSUE THREAD

**Issue by uasan** [meetecho/janus-gateway#972]
Hello.

Many IP cameras, send incorrect (for browsers) `a=fmtp:` params, but RTP stream valid for browsers, if replace `a=fmtp:` value to correct value from config file **plugin.streaming.cfg**.

Example, SDP from IP cameras
```
a=fmtp:96 packetization-mode=1;profile-level-id=4D001E;sprop-parameter-sets=Z00AHpWoKA9puAgICBAA,aO48gAA=
```

This  SDP invalid for browsers (Chrome 60 - setRemoteDescriptionOnFailure)
```
Failed to set remote offer sdp: Session error code: 
ERROR_CONTENT. Session error description: Failed to set remote video description send parameters.
```
If replace `a=fmtp:` value to correct value from config file **plugin.streaming.cfg**
```
[RTSP]
type = rtsp
videofmtp = profile-level-id=42E01F\;packetization-mode=1
```
This fix for browsers (Chrome 60 - play video).

Quote from the discussion Chrome

> Chrome only supports Constrained Baseline Profile right now. We are working on adding support for more profiles, like (unconstrained) Baseline Profile, Main Profile, High Profile, etc. We didn't look at the SDP previously and accepted any profile, and that might work depending on what H264 decoder you end up with (SW or one of the HW decoders). Since we now look at the profile-level-id, we reject anything else than Constrained Baseline Profile. We are working on adding support for more profiles, but we need to properly enumerate the capabilities of the H264 decoder before accepting other profiles. You can work around the new profile enforcement in Chrome by setting profile-level-id to 42E01F if you want to get the old behavior back, but it's undefined behavior and we can't guarantee it will work.

https://groups.google.com/d/msg/discuss-webrtc/EKLBlSaiYdU/JJhZ1mKtDwAJ

Thanks.

**Comment by lminiero** [comment]
So do you mean we should allow, via configuration, to override the audio or video fmtp, if specified, Instead of using what the camera sends? And to use the original SDP otherwise? Or is this override already working as expected? Not sure if you provided a configuration fix, or if you were highlighting an issue in the code. If it's the former, please post your fix to the [group](https://groups.google.com/forum/#!forum/meetecho-janus), as that's where most of the Janus users hang out.

**Comment by uasan** [comment]
> So do you mean we should allow, via configuration, to override the audio or video fmtp, if specified, Instead of using what the camera sends? And to use the original SDP otherwise? Or is this override already working as expected?

Yes.

**Comment by lminiero** [comment]
Yes to what? It's three separate questions :smile:

**Comment by uasan** [comment]
Sorry :)

Fix:
> override the audio or video fmtp, if specified, Instead of using what the camera sends? And to use the original SDP otherwise

**Comment by uasan** [comment]
Now we are replacing in client:

```JS sdp.replace(/profile-level-id=[^;]+/, 'profile-level-id=42e01f'/*42e01f*/); ```

**Comment by lminiero** [comment]
Adding to the TODO list :+1:

**Comment by lminiero** [comment]
Just implemented and seems to be working for me. Please let me know if that's not the case.

**Comment by uasan** [comment]
Compile error, master branch

Fedora: 26
GCC: 7

```
plugins/janus_streaming.c:3763:63: error: expected statement before ‘)’ token
make[2]: *** [Makefile:1470: plugins/plugins_libjanus_streaming_la-janus_streaming.lo] Error 1
make[2]: Leaving directory '/opt/janus-gateway'
make[1]: *** [Makefile:2201: all-recursive] Error 1
make[1]: Leaving directory '/opt/janus-gateway'
make: *** [Makefile:1029: all] Error 2

```

**Comment by lminiero** [comment]
Whoops, that was a copy/paste error, fixing that :+1:

**Comment by uasan** [comment]
Yes, `videofmtp` is correct replaced, thanks!

**Comment by jeremyarr** [comment]
Thanks @uasan and @lminiero for identifying the issue and sorting it out. Confirmed as working for Dahua ip cameras in latest versions of Firefox and Chrome.
Perhaps would be good to mention this "gotcha" in the streaming sample config file.

**Comment by lminiero** [comment]
Like we do [here](https://github.com/meetecho/janus-gateway/blob/master/conf/janus.plugin.streaming.cfg.sample.in#L49)? :wink:

**Comment by jeremyarr** [comment]
😃
