### ISSUE TITLE
Using Janus with Python Flask

### ISSUE THREAD

**Issue by CreaRo** [meetecho/janus-gateway#974]
I have a camera that streams UDP packets (RTP-UDP) to my Flask webapp. Flask then converts this into an RTSP link that can be viewed over VLC/any RTSP player. I would now like to view the same feed on a web browser.

I am completely lost as to how I would use Janus on my Flask app. I've gone through the streaming Nodejs example (but barely understand what's happening) -- what would the steps for live streaming on a Flask app be?

**Comment by lminiero** [comment]
Closing as not an issue. Please post questions like this on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
