### ISSUE TITLE
Is this 'medium' variable a remainder of previously inlined sdp parsing? can it be removed?

### ISSUE THREAD

**Issue by okayawright** [meetecho/janus-gateway#976]
https://github.com/meetecho/janus-gateway/blob/90fa6b67385657a9ea6135fe178d9d44a0434846/html/janus.nojquery.js#L2110

**Comment by lminiero** [comment]
That's probably a leftover from the old way of parsing stats. I'll check as soon as I get back to the code in a f ew days (just going through the mail for now).
