### ISSUE TITLE
SIP gateway can't start.

### ISSUE THREAD

**Issue by khinthuzaraung** [meetecho/janus-gateway#977]
[root@ip-172-31-21-31 ~]# /opt/janus/bin/janus
Janus commit: 90fa6b67385657a9ea6135fe178d9d44a0434846
Compiled on:  Thu Aug 17 08:07:01 UTC 2017

---------------------------------------------------
  Starting Meetecho Janus (WebRTC Gateway) v0.2.5
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Using 172.31.21.31 as local IP...
[WARN] Token based authentication disabled
Initializing recorder code
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, IPv6 support disabled)
TURN REST API backend: (disabled)
[WARN] Janus is deployed on a private address (172.31.21.31) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...
BUNDLE is NOT going to be forced
rtcp-mux is NOT going to be forced
Crypto: OpenSSL pre-1.1.0
Fingerprint of our certificate: D2:B9:31:8F:DF:24:D8:0E:ED:D2:EF:25:9E:AF:6F:B8:34:AE:53:9C:E6:F3:8F:F2:64:15:FA:E8:7F:53:2D:38
Event handler plugins folder: /opt/janus/lib/janus/events
[WARN] Event handlers support disabled
Plugins folder: /opt/janus/lib/janus/plugins
Loading plugin 'libjanus_textroom.so'...
JANUS TextRoom plugin initialized!
Loading plugin 'libjanus_recordplay.so'...
JANUS Record&Play plugin initialized!
Loading plugin 'libjanus_streaming.so'...
JANUS Streaming plugin initialized!
Loading plugin 'libjanus_videocall.so'...
JANUS VideoCall plugin initialized!
Loading plugin 'libjanus_echotest.so'...
JANUS EchoTest plugin initialized!
Loading plugin 'libjanus_videoroom.so'...
JANUS VideoRoom plugin initialized!
Loading plugin 'libjanus_voicemail.so'...
JANUS VoiceMail plugin initialized!
Loading plugin 'libjanus_audiobridge.so'...
JANUS AudioBridge plugin initialized!
Transport plugins folder: /opt/janus/lib/janus/transports
Loading transport plugin 'libjanus_http.so'...
HTTP webserver started (port 8088, /janus path listener)...
[WARN] HTTPS webserver disabled
[WARN] Admin/monitor HTTP webserver disabled
[WARN] Admin/monitor HTTPS webserver disabled
JANUS REST (HTTP/HTTPS) transport plugin initialized!
Loading transport plugin 'libjanus_mqtt.so'...
[WARN] MQTT support disabled for both Janus and Admin API, giving up
JANUS MQTT transport plugin destroyed!
[WARN] The 'janus.transport.mqtt' plugin could not be initialized
Loading transport plugin 'libjanus_websockets.so'...
libwebsockets >= 1.6 available, using new API
WebSockets server started (port 8188)...
[WARN] Secure WebSockets server disabled
[WARN] Admin WebSockets server disabled
[WARN] Secure Admin WebSockets server disabled
JANUS WebSockets transport plugin initialized!
Loading transport plugin 'libjanus_pfunix.so'...
[WARN] Unix Sockets server disabled (Janus API)
[WARN] Unix Sockets server disabled (Admin API)
[WARN] No Unix Sockets server started, giving up...
[WARN] The 'janus.transport.pfunix' plugin could not be initialized
ICE handles watchdog started
Sessions watchdog started
TextRoom watchdog started
WebSocket (Janus API) thread started
VoiceMail watchdog started
EchoTest watchdog started
Streaming watchdog started
Record&Play watchdog started
VideoCall watchdog started
VideoRoom watchdog started
AudioBridge watchdog started
HTTP/Janus sessions watchdog started

installed it on centos 7 but can't start SIP gateway.

**Comment by MichaelB76** [comment]
Looking at the output above, it doesn't seem to be starting the SIP plugin. Have you checked the faq and config files?

**Comment by lminiero** [comment]
@khinthuzaraung as explained in the guidelines, please _DON'T_ post huge bunches of text (e.g., logs) in your messages: if you need to, use a service like gist or pastebin for the purpose. Apart from that, not a code issue, so closing: please ask questions like this on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
