### ISSUE TITLE
Attended and blind transfers

### ISSUE THREAD

**Issue by iclems** [meetecho/janus-gateway#978]
Add support for attended and blind transfers. This is a requirement to build a web softphone.

**Comment by bhakimi** [comment]
yea would love to have this too!!!

**Comment by iclems** [comment]
I tried to be reasonable in my request :-) I suspect the SIP library used behind the scenes does support this. From what I've read, conferencing / merging would be more complicated if you consider that you already need to instantiate different plugins to make simultaneous calls.

**Comment by bhakimi** [comment]
what you requested can be done by passing the right sip info from JS =) its a reinvite i believe

**Comment by bizzr3** [comment]
currently i have a full setup with all features including transfer. 
5000 calls per day. 

for transfer i used AMI and node js.

**Comment by bhakimi** [comment]
Would you mind sharing your code ?

**Comment by bizzr3** [comment]
@bhakimi sure give me some times, i will find a free time and i will make a repo for that.

**Comment by bhakimi** [comment]
Thank you very much !!!

**Comment by iclems** [comment]
Examples as to how to best manage simultaneous calls and call merge would be amazing. I'm working on this separately.

**Comment by lminiero** [comment]
> Add support for attended and blind transfers

You forgot to say "please"... :wink:

**Comment by iclems** [comment]
Oh pretty please! Sorry for the short issue created on the go. I've been working with Janus for the past week and it's really an impressive project. I'm loving it. Until now, I've mostly been using the HTTP transport combined with the SIP plugin.

**Comment by lminiero** [comment]
No worries, I was just kidding :slightly_smiling_face: 
To be fair, I'm not familiar with the feature you guys are asking for. If you can elaborate, that might help. Of course, it the same can be done via some tweaks on the SIP server as @bizzr3 suggested, even better...

**Comment by andresico** [comment]
In Asterisk you can do attended and blind transfers using its built-in features. So you can do transfers sending DTMF sequences with the SIP plugin.

**Comment by fiveways** [comment]
does the sipre plugin support attended and blind transfers ?

**Comment by lminiero** [comment]
No.

Il 01 ott 2017 11:36 PM, "fiveways" <notifications@github.com> ha scritto:

**Comment by ibc** [comment]
Hi guys, instead of requesting the SIP leg of Janus to be a full featured SIP endpoint (with blind/attended transfer), just consider it a "dumb SIP trunk". All the cool SIP features should be placed in an intermediary proxy or PBX.

**Comment by lminiero** [comment]
Feature implemented here: #1815 

I hope I'll get more feedback than the (non-existing) one I got for multiple calls.
Thanks

**Comment by iclems** [comment]
Sounds great. Hope I can give it a try soon. Don't have a good setup right now as it's been a while I haven't used the default SIP.

**Comment by lminiero** [comment]
Any feedback?

**Comment by jmordica** [comment]
This seems to be working fine for me. Using Kamailio as SBC ---> Asterisk.

**Comment by lminiero** [comment]
> This seems to be working fine for me. Using Kamailio as SBC ---> Asterisk.

Excellent, thanks for confirming!

Just merged in master.
