### ISSUE TITLE
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..

### ISSUE THREAD

**Issue by santoshbapu** [meetecho/janus-gateway#980]
> If you want to open an issue, please make sure that:
> 
> 1. you actually found a bug: for generic questions, use the [meetecho-janus](http://groups.google.com/d/forum/meetecho-janus) group instead;
> 2. nobody opened the same bug already (do a search);
> 3. the issue wasn't already solved;
> 4. you don't paste a huge amount of text in the issue or comments: use a service like [pastebin](http://pastebin.com/) or similar;
> 5. you provide a GDB stacktrace if Janus crashed on you, and/or output from AddressSanitizer or Valgrind (more details available[here](http://janus.conf.meetecho.com/docs/debug.html)).
> 
> If so, just remove this text and share your findings!

**Comment by santoshbapu** [comment]
git clone git://git.libwebsockets.org/libwebsockets
	cd libwebsockets
	# If you want the stable version of libwebsockets, uncomment the next line
	# git checkout v1.5-chrome47-firefox41
	mkdir build
	cd build
	cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..
	make && sudo make install

* *Note:* if libwebsockets.org is unreachable for any reason, replace
the first line with this:

	git clone https://github.com/warmcat/libwebsockets.git

after cd build    
        when wi am trying to run       
                    cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_C_FLAGS="-fpic" ..


  it display this....

CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/usr/local/share/cmake-3.2

But i install the cmake alreay 
  so what should i do ..

**Comment by lminiero** [comment]
Closing as not an issue. Please ask questions like this on the [group](https://groups.google.com/forum/#!forum/meetecho-janus).
