### ISSUE TITLE
Simultaneous SIP calls

### ISSUE THREAD

**Issue by iclems** [meetecho/janus-gateway#981]
I've been investigating managing simultaneous SIP calls. It seems reasonable to attach another SIP plugin as soon as you're on an active call to be able to receive incoming call requests separately during the current call. But it could actually be interesting to have an option for Janus SIP to not decline incoming calls if there's an active call but rather notify of "incoming call" to give us the opportunity to attach another plugin when this happens and not preventively in advance.

**Comment by iclems** [comment]
Indeed that would need to be tested. I believed that's how CallKit works on iOS for instance: receive a notification, re-register and get a RE INVITE

**Comment by andresico** [comment]
The way a solved the simultaneous SIP calls issue is by registering a new handler whenever I do or receive a new call. This way, you have always an available and registered handler for new incoming and outgoing calls. Busy handlers can be detached once the call is finished, but that forces you to create a new handler and register it, because detaching a handler unregisters the SIP peer. It would be great if we could detach a handler without unregistering the SIP peer.

**Comment by shrhoads** [comment]
Right you just start a new instance of janus with a new server side session.

**Comment by jmordica** [comment]
Is there a way to initiate the new instance without registering again?

Using this: https://github.com/meetecho/janus-gateway/issues/274

**Comment by lminiero** [comment]
Hi all, it took a while but we finally started working on this. Please read the PR above to learn how to use it, test and provide feedback. The sooner I know it works, the sooner I can merge.

**Comment by lminiero** [comment]
@iclems @andresico @shrhoads @jmordica have you all given up on Janus, or you just don't care about the feature anymore? :innocent:

**Comment by jmordica** [comment]
Sorry for the late response here. I had to use frafos but now that this feature exists I’d like to try it and hopefully swap back over to Janus.

**Comment by lminiero** [comment]
Cool! Looking forward to your feedback, if you'll start playing with this. There's some more updates coming to the SIP plugin as well, that I hope to be able to publish soon.

**Comment by jmordica** [comment]
This may not be the best place to ask this but what other sip updates are you planning?

**Comment by lminiero** [comment]
SIP transfer support, mostly.

**Comment by lminiero** [comment]
Plus some other things I'll discuss at JanusCon next week.

**Comment by jmordica** [comment]
Sweet! That will be awesome to have instead of having to use the PBX/Asterisk to handle it.

Thanks!

**Comment by lminiero** [comment]
I haven't received any feedback these past few weeks on the feature. Unless someone stops me with a good reason why not, I'll merge on Monday.

**Comment by jmordica** [comment]
This tested fine for me. Did this PR not get merged yet?

**Comment by lminiero** [comment]
Not merged yet as nobody gave me feedback.

**Comment by lminiero** [comment]
Just merged in 0.7.6.
