### ISSUE TITLE
Higher googRTT values between 0.2.2 and 0.2.3

### ISSUE THREAD

**Issue by whitemonkey** [meetecho/janus-gateway#982]
Upgrading to version 0.2.5 from 0.2.1 we noticed that googRTT times became noticeably higher. We tested other versions and found the change happened between 0.2.2 and 0.2.3. Using 0.2.2 our RTT times were pretty consistent at about 4ms; switching to 0.2.3 brings the times up considerably, with a lot more spikes.

![rtt0 2 3 2](https://user-images.githubusercontent.com/332325/29644292-dab75398-8829-11e7-973d-cbeb2b47da45.PNG)
![rttok](https://user-images.githubusercontent.com/332325/29644290-dab544e0-8829-11e7-86ca-b1154d15f605.PNG)

**Comment by lminiero** [comment]
Possibly some RTCP related thing, but not sure what. If you can narrow down the exact commit that breaks your googRTT evaluation it might help.

**Comment by whitemonkey** [comment]
git bisect shows that this is the commit: edbdcdd84e72007d4610d6584df50d60ace27072

this change fixes it:
```% git diff
diff --git a/rtcp.c b/rtcp.c
index 5dd445a..07bf939 100644
--- a/rtcp.c
+++ b/rtcp.c
@@ -541,7 +541,7 @@ int janus_rtcp_report_block(rtcp_context *ctx, report_block *rb) {
        rb->flcnpl = htonl(lost | fraction);
        if(ctx->lsr > 0) {
                rb->lsr = htonl(ctx->lsr);
-               rb->delay = htonl(((now - ctx->lsr_ts) / 1000000) << 16);
+               rb->delay = htonl(((now - ctx->lsr_ts) << 16) / 1000000);
        } else {
                rb->lsr = 0;
                rb->delay = 0;```

**Comment by lminiero** [comment]
Thanks for spotting that!

Mh, can't remember exactly the rationale behind that change, but I think it was because this seemed to be more accurate when computing the delay value, which may or may not have been indeed true. I'll have to make some tests printing both values, to see if one of the two is more "raw" than the other for some reason.

**Comment by lminiero** [comment]
PS: have you checked if the higher googRTT is indeed closer to the reality of the RTT?

**Comment by furqanrydhan** [comment]
The old value seems to be significantly closer to the real value. The new
value seems to be about 10-12x. We went from a 20-30 rtt to  300-400. The
ping from our location to our server is 12ms roughly

**Comment by lminiero** [comment]
Ack, will merge the change then, thanks for the feedback!
