### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by the-information-guy** [meetecho/janus-gateway#990]
Hey, 

Just wanted to try installing Janus on Ubuntu 16.04 following the README but I got stuck with this error when running `make`

I have tried using libsrtp 1.6.0 and 2.1.0 but still not working (I don't even know if that has something to do with it).

```
`which git` rev-parse HEAD | awk 'BEGIN {print "#include \"version.h\""} {print "const char *janus_build_git_sha = \"" $0"\";"} END {}' > version.c
echo dimanche 3 septembre 2017, 23:13:36 (UTC+0200) | awk 'BEGIN {} {print "const char *janus_build_git_time = \""$0"\";"} END {} ' >> version.c
/bin/sh: -c: line 0: syntax error at or near symbol « ( »
/bin/sh: -c: line 0: `echo dimanche 3 septembre 2017, 23:13:36 (UTC+0200) | awk 'BEGIN {} {print "const char *janus_build_git_time = \""$0"\";"} END {} ' >> version.c'
Makefile:2684 : the recipe for the target « version.c » failed
make: *** [version.c] Error 1
```
If someone's got a fix :)

Thanks

**Comment by lminiero** [comment]
Try changing this line

https://github.com/meetecho/janus-gateway/blob/master/Makefile.am#L174

by adding quotes, so

OLD: echo $(build_date) | ...
NEW: echo "$(build_date)" | ...

If it works, I'll update the file on the repo too.

**Comment by the-information-guy** [comment]
Yep, it's working :+1: 

Thanks for the quick fix

**Comment by lminiero** [comment]
Thanks for confirming it works, added the fix to the repo as well.
