### ISSUE TITLE
OSX websockets response statu code 101

### ISSUE THREAD

**Issue by bigboyaaa** [meetecho/janus-gateway#997]
I build latest code on OSX,websocket not response data.

**Comment by lminiero** [comment]
You'll have to describe your issue much better than that, if you want us to help...

**Comment by bigboyaaa** [comment]
@miniero  Thank you for your reply.
I just test videoroomtest.html.I have update server  with ws:127.0.0.1:8188,
when send {"janus":"create","transaction":"r1J9Wvr3Lsxt"} 
response:
 HTTP/1.1 101 Switching Protocols
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Accept: kYiEqtY1WsnTLFA2hwiN5kOiPW8=
Sec-WebSocket-Protocol: janus-protocol

**Comment by laurensramandt** [comment]
@bigboyaaa this seems like a default websocket handshake, viewed from the HTTP level
You may want to have a look at the Websocket specification, the [wiki article:](https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake), or [instructions about inspecting the Websocket frames](https://kaazing.com/inspecting-websocket-traffic-with-chrome-developer-tools/).

**Comment by lminiero** [comment]
Closing as not an issue. Please move the discussion on the [group](https://groups.google.com/forum/#!forum/meetecho-janus) instead.
